### ISSUE TITLE
Sort By : Viewers 

### ISSUE THREAD

**Issue by FunWithMyHole** [night/BetterTTV#1001]
In default twitch there is a sort by option one of these is sort by viewers but then you get stream win 100+ viewers maybe id be nice to sort for lowest view count that be nice :D

**Comment by night** [comment]
The best you can get is random sort on Twitch's directory. This specific request would require us to hook into Twitch's site in ways which are destructive if they ever change their code for the directory. We have strict limitations on the changes we make to Twitch to reduce potential for breakage, so this feature is not possible.
