### ISSUE TITLE
[Feature Request] "Emote Preview"

### ISSUE THREAD

**Issue by donadkins** [night/BetterTTV#1003]
Sort of like how image preview works, but displays a scaled up image of an emote when hovering over an emote.
I watch on really high res and emotes can be hard to see sometimes.

Note, FFZ has this option, but BTTV breaks it.

![emote preview](https://cloud.githubusercontent.com/assets/4638704/13556083/478790a4-e39f-11e5-9bd3-2bb9eebcd617.PNG)

**Comment by night** [comment]
There's not much of a point to re-displaying the emote when it's already displayed in chat. The point of larger images is for High DPI, not "previewing." If you're having trouble seeing emotes or reading text than you're probably straining your eyes and should zoom in the page.
