### ISSUE TITLE
Uptime and Latency Shown Below Player

### ISSUE THREAD

**Issue by ToxiClay** [night/BetterTTV#1014]
For migrants from FFZ (FFZ recently decided to stop working for me, so I switched to BTTV), would it be possible to add stream uptime and stream latency as an option below the player?

**Comment by night** [comment]
There is simply not enough space below the player to add more data, sorry. We try to reduce clutter, not add to it like our "competitor" does. You can type "/uptime" in chat to see the stream's uptime on an as-needed basis.
