### ISSUE TITLE
Chat colors

### ISSUE THREAD

**Issue by xDuskWolf** [night/BetterTTV#1017]
Chat colors seem to be defaulted to a very limited amount of colors when compared to normal twitch so people with custom colors using turbo do not show the custom color, only one of the default colors from twitch.

**Comment by EhsanKia** [comment]
Custom colors work fine, but they are limited to a subset of visible colors. This is on purpose and is a feature to avoid having people with unreadable names, such as black on black.

If you are *actually* limited to the 8 or so default Twitch colors, then that's a bug. Post screenshots with examples and actual color values.

**Comment by xDuskWolf** [comment]
That's unfortunate. I am unable to see the actual twitch color that I have due to this, and if it wasn't for all the custom emotes, I would uninstall the add-on.

**Comment by night** [comment]
Unfortunately actual colors tend to be hard to see on dark mode. We automatically calculate a lighter or darker color depending on the theme you use. There are still infinite colors that can be created, we only lighten or darken the shade.
