### ISSUE TITLE
Enable links to open in a new window

### ISSUE THREAD

**Issue by samkatakouzinosracing** [night/BetterTTV#1021]
May you add an option titled "Enable links to open in a new window"? 
I see this as possible to have links in Twitch stream panels to open in a separate window instead of replacing the Twitch page in the current window.

**Comment by cletusc** [comment]
Rather than doing this, it is probably easier to just middle-click the link? I rarely if ever left-click a link and instead middle-click links which has the same effect and works on all sites, not just Twitch.

**Comment by samkatakouzinosracing** [comment]
Nice to see this implemented, thank you.
