### ISSUE TITLE
Tab Completion Tooltip 

### ISSUE THREAD

**Issue by neldridge** [night/betterttv#1022]
I enabled Tab Completion Tooltip.

I type in a message, arrow back to the beginning, type an emote and press tab-- it shows the tooltip but won't let me update the new emote.

Recreate with:
stuff pogchamp<tab>

arrow to before stuff, type "pogchamp <tab>", tooltip will popup and it will not update the newest pogchamp.

I'm not the greatest at explaining, I can provide a video if necessary.

**Comment by voloshink** [comment]
Basically this is because the tab completion operates on the last word in the input. Maybe we could change it to be based on your cursor location.

**Comment by neldridge** [comment]
Ahh ok, I thought you could tab complete from anywhere before, guess I never noticed LUL . Cursor location seems better though.

**Comment by night** [comment]
Due to interface restrictions last word is the only way we can mutate the input, making this request infeasible.
