### ISSUE TITLE
Slow mode 'Chat in *sek'

### ISSUE THREAD

**Issue by PaulCraftDE** [night/BetterTTV#1026]
Hello,

If the slow mode is enabled the 'Chat' button changed to 'Chat in *sek'. So if I sub the streamer the slow mode is disabled. But the 'Chat in *sek' isn't change to the normal 'Chat' button. pls fix

**Comment by night** [comment]
The button is merely our best guess at when you can chat. It doesn't restrict you from chatting, it just *suggests* the time before trying to send again. BetterTTV has no idea if subscribers are immune to slow mode, only Twitch knows. It's a feature that's different for each channel.
