### ISSUE TITLE
Recommended For You

### ISSUE THREAD

**Issue by gaiakai** [night/BetterTTV#1029]
Please add a feature to turn off the shitty "Recommended For You" that twitch thinks is a good idea. http://prntscr.com/ahn0z1

**Comment by night** [comment]
I don't see this on my "All Games" page, so I can't fix it. Twitch may be trialing this, so you may want to email them your complaint instead.

**Comment by zoum26** [comment]
Why are you closing? I have the same problem. Please fix.

**Comment by vendethiel** [comment]
read @night 's message.
