### ISSUE TITLE
Feature Suggestion: Blacklist name autofill for @tagging

### ISSUE THREAD

**Issue by MasonTallis** [night/BetterTTV#1033]
People like to make names that are similar to streamer's name. It makes whispering a bit less easy. Can we specifically blacklist some names from showing up in @tag autofilling?

**Comment by night** [comment]
That's not very practical, unfortunately. If you ignore someone, however, they shouldn't show up in your chat or be in your tab completion list. You may need to refresh the page after ignoring them though.
