### ISSUE TITLE
Some special characters produces incorrect Hyperlink

### ISSUE THREAD

**Issue by Leumash** [night/BetterTTV#1037]
When pasting the link:
https://en.wikipedia.org/wiki/Matching_(graph_theory)

in twitch chat with BetterTTV installed, a hyper link is created for
https://en.wikipedia.org/wiki/Matching

while ignoring the _(graph_theory).

Tested on both Firefox and Chrome, same issue exists. The same link posted without BetterTTV produces the correct hyperlink.

I can't remember which link (or set of special characters) but other links are also incorrectly generated.

**Comment by night** [comment]
fixed by aca4ef323cd3f4e86ef0c26cc15b97e1d8c822fb
