### ISSUE TITLE
Anon mode until you type/Anon except for Whitelisted channels

### ISSUE THREAD

**Issue by Shilag** [night/BetterTTV#1038]
This would be a nice feature. I like the idea of anon mode because when you browse for new channels and one of them instantly goes "HI X WELCOME TO THE CHANNEL" it makes me uncomfortable, like I can't just instantly leave again.

However, I still want to chat in most channels I follow. So it would be nice to be anonymous until the first time you type in a channel, then you stay logged into the chat until you leave.

Alternatively, which in my opinion would be even better, is to have a Chat whitelist. Where you can set yourself to be anonymous and invisible for all channels you go to, but if you whitelist a channel you'll always be logged in and able to chat as usual for any channels you want.

**Comment by EhsanKia** [comment]
One neat solution I can think of is having chat commands for temporarily changing Anon Mode.

/anonoff
/anonon (this one sounds a bit silly)

These are **temporary** though. If you have Anon Mode setting turned on and use /anonoff in chat, it shouldn't change the setting, just connect to chat. So next time you refresh, you're again in Anon Mode.

**Comment by night** [comment]
There are already commands for toggling anon mode. You can use '/join' and '/part' in the chat box to toggle anon mode quickly and temporarily. When you refresh a page, the setting doesn't stick.

**Comment by Shilag** [comment]
But that wasn't what I was suggesting. I was suggesting an automatic whitelist that would handle that on a channel to channel basis that the user can specify. Personally, I think that would be a useful feature.
