### ISSUE TITLE
Broken Chat Image Preview

### ISSUE THREAD

**Issue by voltaek** [night/BetterTTV#1040]
I am only seeing the translucent tooltip, but the image never loads because its requests are receiving 400 error responses. I've looked through other issues on here (including closed ones), the NightDev forums, and Google'd around but I can't seem to find anyone else talking about this particular issue.

The URL tooltips which show up in the same translucent tooltips work just fine for me. In fact, that is the first request that happens when I hover over an image link, and it gets a 200 response (sent to `https://api.betterttv.net/2/link_resolver/<URL-encoded image URL here>`).

However, then there are immediately 3 additional requests - which are identical to one another - sent to `https://api.betterttv.net/2/image_embed/<URL-encoded image URL here>`. Almost every time both the first and second of these three new requests will stall / get cancelled, and never receive a response. The third will receive a 400 status code and 'Bad Request' response, and every so often the first one will as well, instead of it stalling out.

This occurs regardless of the image link being SSL or not, the image format doesnt matter, I've disabled every other Chrome extension I have, tried it in Incognito, tried it with caching enabled and disabled in dev tools, reinstalled BTTV, cleared cache and cookies, restarted (because Windows), etc. and I can't seem to get it to work or behave any differently. I know that at one point in the past it used to work, but now it never does.

If I had to take a stab I'm guessing there shouldn't be three requests firing at once, and maybe it's being seen as malicious or a DDoS and the remote server is just blocking the requests.

If you need anymore info I'd be happy to provide it.

**Comment by voltaek** [comment]
In addition to the above, I tried all the advice on [this page](https://community.nightdev.com/t/betterttv-debugging/3685) that I hadn't already:

- I checked the CDN test link, and it loaded up fine.
- I disabled Windows Firewall and Windows Defender (I don't run any dedicated AV/Firewall anymore) and still got the save 400 errors.

**Comment by night** [comment]
Sorry for the late reply. Can you share one of the links that are failing? Do you run any extensions that hide your browser referrer?

**Comment by voltaek** [comment]
I'm not running any extensions that do that that I'm aware of, and the problem still occurs with all extensions besides BTTV disabled.

Any image link I've tried from multiple sites, both SSL and not, fail. For example, here are two Imgur links: [SSL](https://api.betterttv.net/2/image_embed/https%3A%2F%2Fi.imgur.com%2FmFbO2OL.jpg) and [not](https://api.betterttv.net/2/image_embed/http%3A%2F%2Fi.imgur.com%2FmFbO2OL.jpg).

Trying to load those URLs in a separate browser tab gives me the same error, as does trying them from my phone, both on WiFi and over the cellular connection.

**Comment by voltaek** [comment]
Here is a [dump of the headers](http://pastebin.com/a7zkgCQy) from a request that is getting the 400 error (minus cookie hashes).

**Comment by night** [comment]
From the list of headers, your client is not sending a referrer header. We block requests not being referred from Twitch (to prevent people from abusing our API on other sites). Check that you are not running an extension that blocks those.

**Comment by voltaek** [comment]
Well I'm not sure why the last headers didn't list it, but when I checked just now I have `referer: https://www.twitch.tv/voltaek` under **Request Headers** and it's still failing the same way. I do notice that the `link_resolver` request that fires right before the image_embed one additionally has `origin: https://www.twitch.tv` listed, so maybe that is what is missing?

**Comment by voltaek** [comment]
@night 

http://pastebin.com/kXvRxhPk

I've put together all the header request info as well as the JS call stack traces that fire the requests to help get to the bottom of this. Included is a comparison between the succeeding `link resolver` request headers and its JS stack trace and the same for the three failing `image embed` requests.

Am I correct in assuming that there should not be three different requests always firing for `image embed`s? I think it's interesting that the three calls stacks for the same image request are all different as well.

**Comment by night** [comment]
this is fixed and pushed live
