### ISSUE TITLE
emotes

### ISSUE THREAD

**Issue by cjlewis090991** [night/BetterTTV#1046]
emotes are not showing up

**Comment by night** [comment]
What emotes? They appear to be working fine here. Try clearing your cookies/cache if you're still having issues.

**Comment by cjlewis090991** [comment]
all emotes arent showing.  i cleared cookies/cache

**Comment by night** [comment]
If your problem is that Twitch emotes are not showing up (not ours), then it's because their website is currently pretty much dying due to their CDN being overloaded from MLG. That's still not an issue with BetterTTV. Reach out to them for support then.
