### ISSUE TITLE
Showing emoticon source on hovering disappear quickly

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1049]
While hovering over an emoticon in the chat to see it source, you must hold the mouse still, or the information window will disappear, even on the smallest movement, even if the mouse is still over the emoticon. In the normal chat the title just moves along the mouse until you moving the mouse away from the emoticon, and it your case it's gone even while still hovering over the emoticon. Can you please fix this?

**Comment by voloshink** [comment]
I'm not sure what you mean, it works fine for me:

https://gyazo.com/7c65412af3f511ed9bb41346df8c2359

Which browser are you using?

**Comment by NBruderman** [comment]
Sorry for not commenting, the issue was caused by my browser. Not your fault in any way!
