### ISSUE TITLE
change chat highlighting color

### ISSUE THREAD

**Issue by Umbozz** [night/BetterTTV#1050]
a more subtle highlight color would work just fine, the red can make text hard to read sometimes and it stands out a bit too much (which is the point, but it is a but hard on the eyes, imo).
a quick search brought up that you had this request submitted before (#984, maybe more), but closed it due to a lack of popularity. i wish to express my support for this idea.

**Comment by ConditionOfMan** [comment]
I support this request. A customizable highlight color would be ideal.

**Comment by night** [comment]
duplicate of #237
