### ISSUE TITLE
Twitch Chat Reply - Some emotes do not work

### ISSUE THREAD

**Issue by Jonty800** [night/BetterTTV#1054]
Some BetterTTV emotes in the new Chat Reply BetterTTV implementation do not work. It looks like most are unexpectedly not parsed.

See the image below. FeelsGoodMan is a real emote and loads only twice in this chunk of chat messages. You can reproduce this on any channel during a past broadcast, and its more noticeable during chat spam.

![image](https://cloud.githubusercontent.com/assets/1188837/14211578/bf27c93a-f826-11e5-8bc6-7055148eb00b.png)

**Comment by night** [comment]
already fixed by 6771b89bcac5c2744ca083626b6459314ef4d236
