### ISSUE TITLE
dont pause

### ISSUE THREAD

**Issue by THE-KEKE** [night/BetterTTV#1055]
pls make it possible that if i click an emote form - or go to another channel the one im watching does not get paused 
tia

**Comment by night** [comment]
This is not a BetterTTV issue, sorry. Complain to Twitch instead.

**Comment by THE-KEKE** [comment]
i know it isnt, thats why i asked if it could be a BetterTTV option as so many others

**Comment by night** [comment]
We have very little control over the video player, including its autopausing. Twitch has much of its functionality walled off anonymous functions.

**Comment by THE-KEKE** [comment]
ah ok, thanks anyways
