### ISSUE TITLE
Can't Connect with Twitch

### ISSUE THREAD

**Issue by ZooksterGaming** [night/BetterTTV#1056]
Whenever I click "Connect Twitch" it looks as if it only refreshes the page, taking me back to the exact same page as before. Still with the "Connect Twitch" button available.
I tired Connecting from twitch and from bttv.

**Comment by night** [comment]
We already tweeted about Twitch having issues. Check it out at https://twitter.com/BetterTTV/status/716203465576419328

**Comment by ZooksterGaming** [comment]
Thanks for the quick reply. I wasnt even considering checking Twitter or FB.
