### ISSUE TITLE
hide whisper icon in theater mode

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#1057]
It can be annoying, especially if you minimize the chat (at least hide it if there are no new messages and/or show it only when the video is hovered):
![untitled](https://cloud.githubusercontent.com/assets/11561641/14228214/3cf55d26-f90f-11e5-907d-e125984d3b54.jpg)

**Comment by night** [comment]
You can now enable "Hide Conversations When Inactive" in BetterTTV settings.
