### ISSUE TITLE
Remove Posts Feed

### ISSUE THREAD

**Issue by Kliks** [night/BetterTTV#1058]
Dear whomever it may concern,
Please consider adding the option to disable posts from the about section below the video player.

Thank you,
A BetterTTV User

**Comment by BradyThe** [comment]
+1 It also would be nice to add an option to hide the Post feed if unused ("Nothing is here yet.").

**Comment by night** [comment]
twitch is getting rid of the feed soon: https://help.twitch.tv/customer/portal/articles/2936769-removing-channel-feed-and-pulse
