### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MADWurstDE** [night/BetterTTV#1061]
Sorry for my bad english, iam from germany.
An Option to write automaticly in your own colour like it does with the "/me (text)" command.
Greetings from Germany:)
![twitch](https://cloud.githubusercontent.com/assets/18282578/14277028/983561cc-fb21-11e5-948f-3a179946c047.PNG)

**Comment by night** [comment]
It is not possible to send a different color, sorry. The Twitch chat server only supports the same color as your name.
