### ISSUE TITLE
Pleb mode

### ISSUE THREAD

**Issue by ChunkyDizzyfoot** [night/BetterTTV#1066]
A chat mode tab for plebs (invisible to subs). Used when chat is in sub mode.

**Comment by ChunkyDizzyfoot** [comment]
Also, if possible it this does make it in. Block wall text, and ASCII art.

**Comment by ConditionOfMan** [comment]
I don't believe your first request is doable. If my understanding is correct, pleb messages get rejected by the IRC server before they ever get to your client or mine. Night would have to implement their own IRC system to be able to pull it off and then only [people who are using BTTV]  [who are in a channel that is in Sub-only mode] [who are not subs to the channel] and have the ["pleb chat" enabled] would be able to converse. Probably not worth even looking into.

**Comment by night** [comment]
Not possible.
