### ISSUE TITLE
Follow Notification requireInteraction

### ISSUE THREAD

**Issue by wakkabakkamakka** [night/BetterTTV#1069]
The follow alert for a followed channel that has gone live disappears after a few seconds. If you were afk in that moment and you come back you might miss that the channel has gone live. (or if you were in a persistent fullscreen mode of any other program)

It is possible (at least in google chrome) to make a user interaction necessary for a notification to disappear.
(see here: https://developers.google.com/web/updates/2015/10/notification-requireInteraction?hl=en2)
Please integrate that feature either fix or as an option that would be awesome.

This would be a huge improvement to the follow alert in my opinion because it would make absolutely sure that you never miss a channel going live (which as of right now happens all the time at least to me, because the notification disappears way too fast making the current follow notification almost useless imho).

Thank you very much.

**Comment by night** [comment]
no longer applicable
