### ISSUE TITLE
Can We Get This BTTV Emote?

### ISSUE THREAD

**Issue by Muwai** [night/BetterTTV#1071]
Basically it's the ??? meme guy.
![23d25e1b6f771b0533745cfcc1ba5009](https://cloud.githubusercontent.com/assets/18372454/14407471/43753758-ff0d-11e5-95be-c91532b736c1.png)

↓ I've turned the face into a 28x28 resolution with Photoshop ↓

![untitled-2](https://cloud.githubusercontent.com/assets/18372454/14407468/30463420-ff0d-11e5-866b-941584d4ddb3.png)

Not really sure what it would be called, perhaps "???Face".

Thanks,
Billy.

**Comment by night** [comment]
This is already an emote. Share it in your channel at  https://manage.betterttv.net/emotes/55cbeb8f8b9c49ef325bf738
