### ISSUE TITLE
Emote menu

### ISSUE THREAD

**Issue by Lwessel812** [night/BetterTTV#1078]
Add more slots for the favorite emotes slot (I can't seem to have more than about 5) Also when you click on an emote don't close the emote menu. Thanks.

**Comment by voloshink** [comment]
if you are referring to shared emote slots, that can be expanded via the bttv pro subscription. If you mean personal emote slots, there are currently no plans to expand them. You can prevent the emote menu from closing by using the pin button in the bottom right corner of the menu.

**Comment by cletusc** [comment]
He is referring to the emote menu favorites section. I have an issue created already but it will be quite a while before I have any real time to even work on the menu aside from emergency hotfixes. See cletusc/Userscript--Twitch-Chat-Emotes/issues/69 for more info.

**Comment by voloshink** [comment]
Alright, thanks.
