### ISSUE TITLE
Request: Option to exclude certain characters from chat

### ISSUE THREAD

**Issue by Jonty800** [night/BetterTTV#1080]
I notice in Chrome, whenever chat is spamming certain characters, my Chrome tab will either lag or freeze completely. I feel like a solution is to avoid rendering these certain characters, such as:

░▐█▌▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒████▌ ░░█▒▄▀▀▀▀▀▄▒▒▄▀▀▀▀▀▄▒▐███▌ ░░░▐░░░▄▄░░▌▐░░░▄▄░░▌▐███▌ ░▄▀▌░░░▀▀░░▌▐░░░▀▀░░▌▒▀▒█▌ ░▌▒▀▄░░░░▄▀▒▒▀▄░░░▄▀▒▒▄▀▒▌

**Comment by night** [comment]
You are able to blacklist characters in the chat settings
