### ISSUE TITLE
Links and "Ctrl + f" -like features 

### ISSUE THREAD

**Issue by 1231236969420** [night/BetterTTV#1082]
I know nothing about programming or whatever it is you do. I just have some ideas that might be some cool additional features that i think could maybe make a super program a little better. 

One idea is an addition to the "pin" feature that is already in BetterTTV. The idea is that links too gets pined in some way. Only one of the same link so that it doesn't take up too much space. The chat usually only spams 1-3 links at one time, so it might work somehow, i don't know.

Another idea is to have a list of words and/or sentences that would get highlighted in the chat when someone typed it. That way i could highlight when someone spams a specific sentence but i could also keep track if someone talks about a friend i know on twitch.

I think both ideas are pretty good and would be used a lot. But then again i dont know anything about programming and what kind of restrictions there are. I love the program i just thought of these ideas and wanted to let you know. 

Sincerely Mathias.

**Comment by 1231236969420** [comment]
I realize i might have posted this in the wrong tap... how do i even move it?

**Comment by night** [comment]
> One idea is an addition to the "pin" feature that is already in BetterTTV. The idea is that links too gets pined in some way. Only one of the same link so that it doesn't take up too much space. The chat usually only spams 1-3 links at one time, so it might work somehow, i don't know.

If you'd like links to also be highlighted (and therefore pinned), you can add "https:" and "http:" to your highlights list in the chat settings. This should cause most links to be highlighted.
 
> Another idea is to have a list of words and/or sentences that would get highlighted in the chat when someone typed it.

You can set highlighted users, words, and phrases in the chat settings already.
