### ISSUE TITLE
Mark on already watched VODs

### ISSUE THREAD

**Issue by HKS218** [night/BetterTTV#1083]
Hi, i don't know if it's possible but a mark or anything on already watched VODS would be very helpful
There so many VOD on twitch and keep track on all of them with chrome or firefox history is a real pain.
I noticed the "Think something is missing here? Send in a feature request!" on bottom of BTTV so here i come ^^
BTW thx for this amazing addition, i cant imagine anymore twitch without BTTV.

**Comment by HKS218** [comment]
Hi, did you add a mini purple timeline on vod thumbnail ?
It's amazing but i only get it on 1 of my 4 twitch account, how can i enable it on my main account? plz
![2016-05-11_234026](https://cloud.githubusercontent.com/assets/18583595/15197819/d3da0f10-17d3-11e6-96a5-0305c0a10527.jpg)
Thanks again, it's even better than expected

**Comment by night** [comment]
Twitch does this natively. Closing.

**Comment by EhsanKia** [comment]
They are probably A/B testing or slowly rolling out the update. You'll have to wait to get it on all your accounts.
