### ISSUE TITLE
New emoticon

### ISSUE THREAD

**Issue by Trikster101** [night/BetterTTV#1084]
Hello, i love the BTTV extension and I've always wondered why there isn't a a xD or XD emoticon, theres :D ;) :) D:, you get the point but there isn't one for xD/XD so why not create one, but make it like the :) emoticon (the monkey face).
 
Thanks for reading :D

**Comment by night** [comment]
We do not take emote requests, sorry. You can upload and share emotes at https://manage.betterttv.net
