### ISSUE TITLE
Embedded Strawpoll Broken

### ISSUE THREAD

**Issue by Aaron128l** [night/BetterTTV#1085]
Clicking "New poll available! Vote now!" on the linking of a Strawpoll will skip the voting page embed entirely and will just output the "Thanks" text as if you voted.

**Comment by night** [comment]
Curse said they are aware and are working to fix the issue.

**Comment by night** [comment]
Debating if we should just remove this feature.. Curse clearly doesn't care about StrawPoll anymore.. They just want the ad revenue

**Comment by pahakalle** [comment]
now they allow https on embeds and don't load any http content

**Comment by Ninja101** [comment]
This seems fixed on their part. Looking at the https embed page, there are no insecure resources. Issue now is that BetterTTV is still trying to load the insecure page into the browser.

**Comment by night** [comment]
BetterTTV's implementation has and is fine. Please refer to the source: https://github.com/night/BetterTTV/blob/aca4ef323cd3f4e86ef0c26cc15b97e1d8c822fb/src/templates/embedded-poll.jade
