### ISSUE TITLE
Ignore users on tabbing for emotes

### ISSUE THREAD

**Issue by lukderp** [night/BetterTTV#1086]
I want to spam more efficiently with TAB, but writing gachi-TAB- results in a user with gachiGASM12345, while I want gachiGASM.
maybe make the emote the first thing that pops up instead of the last ?

**Comment by night** [comment]
No, just no.

**Comment by lukderp** [comment]
cant it just be an option to prioritize emotes instead of nicknames? I can understand that you don't like spammy chats, but some people enjoy it...
