### ISSUE TITLE
Remove background from certain non-transparent emotes

### ISSUE THREAD

**Issue by matt3541** [night/BetterTTV#1087]
Some twitch emotes have white backgrounds instead of transparent which makes them look weird for users with dark mode

Example:
![ss 2016-04-24 at 06 21 43](https://cloud.githubusercontent.com/assets/11934593/14771769/6af95d1c-0a49-11e6-9460-d545e8ef6ffd.jpg)

**Comment by EhsanKia** [comment]
Fixed by #1198
