### ISSUE TITLE
ASCII Emoji Menu

### ISSUE THREAD

**Issue by 8BitPie** [night/BetterTTV#1089]
Nightdev hello, I would really like you to add a menu for ASCII emojis like Lenny ( ͡° ͜ʖ ͡°), seriously (ಠ_ಠ), party ┏(-_-)┛┗(-_- )┓┗(-_-)┛┏(-_-)┓, and more...
It would really help me and would be awesome.
Thanks.

**Comment by night** [comment]
We do not like to encourage spam more than it's already used on Twitch, sorry.
