### ISSUE TITLE
Adding chat options also on replay

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1100]
Recently, as you know, Twitch added chat replay to the broadcast. However, in this mod, there is no settings button, so you can't reach the options during the chat replay. For me, the main issue is that you cannot adjust the chat history size during replay. Sometimes it's really needed (at least for me), and if you could add this feature, I'll be really happy :) Nevertheless, this mod is amazing.

**Comment by night** [comment]
There's not really such a thing as chat history size when using chat replay. To go back in history futher, simply rewind the video. To go forward, fast forward the video.
