### ISSUE TITLE
Titles doesn't change color in dark mode

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1101]
Some titles are not changing the color while replacing to dark mode, thus become invisible. Screenshots added.
![chatdark](https://cloud.githubusercontent.com/assets/6445601/14935812/b7c322e8-0ee7-11e6-91bc-9fa3259db391.png)
![chatwhite](https://cloud.githubusercontent.com/assets/6445601/14935813/b7c3da58-0ee7-11e6-970d-f3fc8a67aa55.png)

**Comment by night** [comment]
fixed by dbe3ca2205b1cd0c85c2ca4e8e3ebb9d8603d691
