### ISSUE TITLE
Stream Title Fix

### ISSUE THREAD

**Issue by GKid94** [night/BetterTTV#1102]
Remove the white bar when you move your mouse over the stream title its really annoying.
[https://qmh0la-dm2305.files.1drv.com/y3phfPAXWCeCi6BgsbmlZDG49USBOPxn3L7BsAkwL1k2dp4qXZYlfChHAI-J6nQuE5pEs1d2zKLFoCud3kJLTK4XL3Ne48yqXFSVtmQDaTyrBfkkrxIrevTHtvuSXmCt8VH5_wmebAQQ8R05D1AcH3KFg/2016-05-01%20%284%29.png?psid=1](url)

**Comment by night** [comment]
This is already fixed but is not yet pushed out to public. It will be when it's ready.
