### ISSUE TITLE
Feature Request: Hide the "Conversations list" button

### ISSUE THREAD

**Issue by ashizen** [night/BetterTTV#1105]
My second monitor is a flatscreen TV and has a wonky resolution. The result is a gigantic Conversations List button that takes a considerable portion of the video feed, and I don't know how to get rid of it!
If there was an option in the BTTV settings to hide it, I would be ballin.

Thanks!

**Comment by night** [comment]
We have a setting called "Disable Whispers" already which hides this button.

**Comment by ashizen** [comment]
Oh, I hadn't restarted my twitch after I enabled it, so I assumed the function did something else. It works now.
