### ISSUE TITLE
Creative theming on dark mode

### ISSUE THREAD

**Issue by night** [night/BetterTTV#1107]
![image](https://cloud.githubusercontent.com/assets/2942184/15003443/ef38f9ac-1179-11e6-9cdc-2aabe6a85e12.png)

https://www.twitch.tv/directory/game/Creative/cooking

**Comment by teak** [comment]
fixed https://github.com/night/BetterTTV/commit/5009641d7c72b1e6bb9b7c6c0fb0457879ada70f
