### ISSUE TITLE
Emote Menu no longer working

### ISSUE THREAD

**Issue by Jacky1356400** [night/BetterTTV#1108]
The Emote Menu button is not showing up even though the option is enabled. Tried refresh and reinstall and that does nothing.
![bttv_bug](https://cloud.githubusercontent.com/assets/11830494/15006280/93342c84-1201-11e6-94dd-1f31485637e8.png)

**Comment by night** [comment]
This is now resolved.

https://twitter.com/BetterTTV/status/727750054560321538
