### ISSUE TITLE
Video Preview Isn't Working

### ISSUE THREAD

**Issue by GKid94** [night/BetterTTV#1116]
When i put my mouse over the stream picture it opens a preview window but the preview isn't starting, fix that :(
![2016-05-06 2](https://cloud.githubusercontent.com/assets/18757054/15062800/2d1193ee-1344-11e6-84a3-e34041f49a48.png)

**Comment by night** [comment]
We can't fix this, as it's a Twitch issue with playing HTML5 video over SSL.

**Comment by GKid94** [comment]
Damn, well that sucks :(

**Comment by EhsanKia** [comment]
Should we remove/disable this feature until it can be fixed? Is there anyone who is still on non-SSL Twitch and can use this at all?
