### ISSUE TITLE
Slow mode and Timeout countdown broken after twitch update

### ISSUE THREAD

**Issue by Slikrick** [night/BetterTTV#1121]
No longer shows the amount of time until you can next talk due to the button id changing.

Tested with timeouts using an alt account
![selection_005](https://cloud.githubusercontent.com/assets/7969393/15087387/5786359a-13b6-11e6-8926-64e8e5482194.png)

**Comment by gandalf3** [comment]
This appears to be broken again (7.2.2).

There's a more unique-looking data attribute now which might be useful for selecting with something like this:

    .tw-button[data-test-selector='chat-send-button']
