### ISSUE TITLE
possible new feature?

### ISSUE THREAD

**Issue by Angel753146** [night/BetterTTV#1122]
Hello, 
I am Angel753146 on here as well as on Twitch.  As an optional suggestion, can you make the Highlighted keywords make a sound on the computer (or whatever you're watching Twitch on) when they pop up?  This would be mainly for the people who watch while doing housework or homework.  After all, if you're lurking in a channel and concentrating on something else, you don't always notice the red highlights until after they've moved off-screen.  

Thank you for taking the time to read my suggestion.

Angel753146

**Comment by night** [comment]
There is already a feature for that. Enable the "Play Sound on Highlight/Whisper" setting in the BetterTTV Settings within the Twitch chat settings.
