### ISSUE TITLE
Personal Emotes NOT Working

### ISSUE THREAD

**Issue by Mogabie** [night/BetterTTV#1125]
My personal emotes (Mj420 mogaREKT mogaBEER and Mnoob) are not showing in other channels. I know these channel users have BetterTTV installed cause we use some of the same emotes and theirs are showing but mine arent

**Comment by voloshink** [comment]
Agreed

**Comment by night** [comment]
I cannot reproduce any issues. Do other users' Pro emotes work? If not, it sounds like you're unable to connect to our websocket server which is in charge of handling personal emotes. Additionally, since this isn't a bug you should reach out to our support instead: https://nightdev.com/contact
