### ISSUE TITLE
Annotation On Deleted Messages

### ISSUE THREAD

**Issue by xnamkcor** [night/BetterTTV#1128]
Can you add a setting to show some sort of highlighting or text annotation to recovered deleted comments to let the use know that what he is reading was deleted?

**Comment by night** [comment]
You can actually click on deleted messages to show the original message already.

**Comment by xnamkcor** [comment]
When in my request did I ask to see "the original message"? And at what point did I ask to have to click the message? Shall I click every single message to make sure they weren't deleted?

**Comment by night** [comment]
I'm not sure I understand the request then. Deleted messages are already marked a different shade of grey if you have "Show Deleted Messages" turned on.. If you click to show deleted messages, then you already know it's deleted.

**Comment by xnamkcor** [comment]
Can you add an option to change the shade? I can't see it. I have the option set that automatically undeletes it.
