### ISSUE TITLE
Twitch emote menu sometimes breaks chat history

### ISSUE THREAD

**Issue by voloshink** [night/BetterTTV#1131]
Making this so i don't forget.

Pasting in emotes using the twitch emote menu prevents the messages from getting added to chat history(sometimes at least)

**Comment by cletusc** [comment]
If it's any help, I am setting the text here: https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/blob/75b1d7d986226f75c151e5216537baac3a1c58f0/src/modules/ui.js#L620

**Comment by voloshink** [comment]
can't seem to reproduce anymore so i assume it probably got fixed or was just twitch weirdness
