### ISSUE TITLE
Feature Request: Chat Delay/Refresh

### ISSUE THREAD

**Issue by NS-Koyuki** [night/BetterTTV#1132]
Sometimes, on really big streams, or on those with poor moderation, or both, the chat moves so fast, it is physically painful on the eyes, hard to see anything said or that you needed to hear, and is probably an extreme epilepsy hazard considering how many chromatic or animated emotes people spam en masse and their name colors (even though the latter does have colorblind mode).

Solution: Make an option to turn on a chat delay feature that sets new messages to only display either A) after a set time/volume or B) at set intervals; and if B, an option to set the intervals longer or shorter a bit (i.e. every 3 to 15 seconds).

I was on Nightblue3's stream a while ago and I'm still rubbing my eyes from the visual vomit called a chat. Please add this before Twitch puts someone in a hospital. @_@"

**Comment by voloshink** [comment]
Delaying messages would quickly make them clog up, we would have to drop a certain percentage of messages. If we try to keep them in your browsers storage, it will probably kill the browser in a few minutes  .The spam in bigger chats is generally not worth reading anyway. I suggest turning on the local sub mode that betterttv has, that way you will only see messages from subs and mods, which should make the chat experience less terrible in bigger channels.
