### ISSUE TITLE
Feature request for BTTV - Locally pause chat

### ISSUE THREAD

**Issue by SilverNightwing** [night/BetterTTV#1133]
I find it very hard to click names in more active chats, as they always seem to avoid my cursor, or move just before I click. Having the ability to locally pause the chat would remove this issue completely, and these days the "Pause" key beside the scroll lock key on a keyboard goes largely unused. If possible I'd appreciate being able to press that key whenever I need to freeze the chat for myself (as opposed to for the entire channel) and resume when I press it again

**Comment by voloshink** [comment]
You can scroll up to stop the chat from moving

**Comment by SilverNightwing** [comment]
While this is true I find that feature to be rather finicky, especially in active chats, I'll fight the scroll of the chat while trying to scroll up, and have to try a few times before the pause takes effect. This is why I asked for a feature that pauses at the press of a key
