### ISSUE TITLE
Marking Streams

### ISSUE THREAD

**Issue by tyonic16** [night/BetterTTV#1143]
A large majority of twitch users follow 200+ channels which makes it hard to sort through our live channels, especially when I frequent a stream that averages very little concurrent viewers causing the larger channels I follow to cover them up. It'd really be a great feature to favorite a stream or two so that streams on the favorite list show up above the other streams on the followed tab.

**Comment by night** [comment]
The real solution to your problem is allowing users to sort by viewer count, which is something Twitch doesn't support. Until they do it isn't practical for us to store a favorites list since your following list is meant to be your favorites list.
