### ISSUE TITLE
Hiding recommended friends

### ISSUE THREAD

**Issue by Entrexx** [night/BetterTTV#1147]
I saw there is an option to hide the friends sidebar. I do like the friends feature.
The only thing that is really annoying in my opinion is the "recommended friends" sidebar.

Would be a nice feature to hide recommended friends but still see your friends list.

**Comment by skapytek** [comment]
Would appreciat ethis feature

**Comment by SaiyanOfDarkness** [comment]
This is even more important now.. because as soon as you type in chat with someone else you get recommended friend requests from anyone else in that chat that types .. "You're active in the same channels"

**Comment by night** [comment]
this was added
