### ISSUE TITLE
BTTV Feature request

### ISSUE THREAD

**Issue by badjokr** [night/BetterTTV#1153]
Since the notification shows when the guys go live, I'd also love to see if the guys on my "Twitch Friends" are live as well. 
What i mean is shown in the images linked. 
I'll be using my friend "RussianPaladin" as an example for this demonstration. 
http://imgur.com/a/FkjvW
Maybe have that small square to the right of the name be purple with a breathing effect to it like the "Live Now" box on the profile.
I've made this into a userstyle to see if it worked on my own with this CSS for the square:
```
@-webkit-keyframes custom-pulse140516 {
        0%   { background:#965DFF;}
        50%  { background:#8A6AC3;}
        100% { background:#965DFF;}
}
@-moz-keyframes custom-pulse140516 {
        0%   { background:#965DFF;}
        50%  { background:#8A6AC3;}
        100% { background:#965DFF;}
}
@-ms-keyframes custom-pulse140516 {
        0%   { background:#965DFF;}
        50%  { background:#8A6AC3;}
        100% { background:#965DFF;}
}
.js-username-hover>.ember-view>.presence--live{
     -webkit-animation: custom-pulse140516 1s infinite;
     -moz-animation:    custom-pulse140516 1s infinite;
     -ms-animation:     custom-pulse140516 1s infinite;
}
```
https://userstyles.org/styles/127871/twitch-friends-live-test
You need to add the css selector on the small square manually to try this out.
Thank you for reading trough my request. :)

**Comment by night** [comment]
Twitch may be adding this stuff soon (friends list is beta), so it may not be worth the effort.
