### ISSUE TITLE
Warn Users if Message being Composed Violates Nightbot Spam Filter for Current Channel

### ISSUE THREAD

**Issue by Codonbyte** [night/BetterTTV#1154]
The title speaks for itself. If the user is in a channel that uses Nightbot and the message the user is composing violates one of Nightbot's spam filters for the channel, display some sort of visual warning to the user _before_ they send the message. For example, have the "Chat" button turn red if the current message will trigger one of nightbot's spam filters, or better yet, have an icon showing Nightbot carrying a stop-sign or something appear, preferably animated to grab the users attention. 

I just checked out what all of Nightbot's spam filters are, and I doubt it would be too expensive to check for all of them in real-time as the user is typing their message. 

This feature would also be a huge selling point for Nightbot compared to other bots. Most broadcasters would much rather have users be warned about the rules ahead of time, rather than having them get purged or timed out after breaking them. This feature would definitely make twitch a **better** place overall.

**Comment by Codonbyte** [comment]
Here are some images I whipped up that could potentially be used as warning icons. 
They use only royalty-free clip-art from www.clipartbest.com so you shouldn't have any legal problems.
![nightbot on stop sign](https://cloud.githubusercontent.com/assets/11092687/15266572/c777f408-1977-11e6-937b-62e18a1df97d.png)

![nightbot holding stop sign](https://cloud.githubusercontent.com/assets/11092687/15266585/3bb9d340-1978-11e6-9abf-8dcea66efd63.png)


Here's the link to the royalty-free image I used so you know it won't get you sued: http://www.clipartbest.com/clipart-McLGXgKki

The top one will probably look better when scaled down to icon size, but the bottom one looks kind of cute in my opinion. If it was animated so it was waving the sign it would be better at grabbing the user's attention. 
Another thing you could do is change the icon so ithat Nightbot is giving the user a thumbs-up when their message is okay. That might make users hate Nightbot slightly less. 

Feel free to use those. No strings attached. Wouldn't mind a mention in the credits if you do use them, but honestly not a huge deal to me.

**Comment by night** [comment]
This is not a good idea since it teaches people around spam filters, sorry.

**Comment by Codonbyte** [comment]
Um what? So you think users should NOT be informed about the rules of the channel they are in? If users start "skirting around" spam filters too much, then the broadcaster can easily tighten the filter. If the filter is set to block 6 emotes and users keep posting 5 emotes and that's seen as too much, then the filter can easily be tightened to 5, or 4, or however many is deemed tolerable. 

Furthermore, it's not giving the user any information that's not trivial to obtain anyway. I can figure out what level a channel's spam filters are set to by trial and error fairly quickly; if a broadcaster doesn't want a user to spam emotes, and a user decides to type a message with a lot of emotes, they're GOING to find out about the spam filter sooner or later. Clearly it's better if they find out about it sooner.

**Comment by night** [comment]
The only people who are concerned about being timed out by a bot are the people intentionally breaking rules. If you aren't doing anything spammy then you have nothing to ever worry about.

**Comment by Codonbyte** [comment]
Um no, most users who get timed out by nightbot (or any bot) aren't trying to break any rules. I don't know where you get the idea that they are. 

Especially when nightbot's default settings consider 3 emoticons to be spam. Really? Have you never celebrated a streamer you watch gaining a new subscriber? 3 emoticons just doesn't cut it for such an occasion, my friend.

**Comment by voloshink** [comment]
are you +1ing your own comments?

**Comment by Codonbyte** [comment]
Yes. Is that against the rules?

**Comment by voloshink** [comment]
Against the rules? no. it just kinda defeats the purpose.

**Comment by Codonbyte** [comment]
Fair enough. I'll remove them, then. Not trying to be unproductive here. Just a little shocked that this idea wasn't shot down for a technical reason. Like, I expected that if it was closed it would be for some programming reason, like "it would require merging the code-bases for nightbot and betterttv which would cause the two separate products to become entagled", or "it would require too many queries for our servers to handle".

**Comment by Codonbyte** [comment]
I'm starting to get the impression that @night doesn't actually read people's responses at all. 

> The only people who are concerned about being timed out by a bot are the people intentionally breaking rules. If you aren't doing anything spammy then you have nothing to ever worry about.

How, exactly, do you know the intention of _every_ user who's ever been temp-banned by nightbot? Obviously you don't. You have nothing to back this statement up. Furthermore, it failed to address any of the points in my post, which leads me to think you didn't even read it. 

I'd be interested to know why you think nightbot spam filters are a big secret. They're really simple. They aren't complicated RegEX designed to catch tricky spam-bots. Any user who's been in a channel with nightbot for awhile will know what the settings are at. I really don't see why it would be harmful for a user to find out that information sooner, rather than later.
