### ISSUE TITLE
Whisper from Mod Cards

### ISSUE THREAD

**Issue by night** [night/BetterTTV#1160]
One feature that would be nice is if you would have a whisper option when you click a username in chat and not only in the viewer list.

**Comment by EhsanKia** [comment]
Yeah, it's something Twitch added to their modcards but since we built our own modcards, we don't have it.

I could add a button, just need to figure out what icon to use for it. The "ignore" icon is kinda what I wanted to use http://i.imgur.com/zkgc0DH.png

**Comment by night** [comment]
Added in 9876dfa83a1eb53fc47029060f8486db9e4807f4
