### ISSUE TITLE
Notify when a certain keyword is said in chat

### ISSUE THREAD

**Issue by BananaJoystick** [night/BetterTTV#1174]
My twitch username is DaluxMusic, but most people just call me Dalux in chat, and it's rather silly when the chat is flowing and I don't get notified and end up ignoring the message. Just a little cool thing. Get like a notification as if they would of said my entire username.

Cheers!

**Comment by voloshink** [comment]
How is this different from the current keyword highlight feature?

**Comment by EhsanKia** [comment]
Just to be clear, click the gear under chat, select "highlight keywords" and enter a list of space separated words. In your case, just enter "dalux".
