### ISSUE TITLE
Host Button Missing even when enabled

### ISSUE THREAD

**Issue by funkyrowanpixie** [night/BetterTTV#1175]
The Host button when enabled does not show on the player

I even checked deleting the cookies and re enabling it and it still wont appear

![bttv proof 1](https://cloud.githubusercontent.com/assets/5890200/15325192/852d238a-1c41-11e6-9edc-80f0e0805344.png)

![bttv proof 2](https://cloud.githubusercontent.com/assets/5890200/15325284/d824a162-1c41-11e6-9c61-c1418551802c.png)

proof of problem is above

**Comment by voloshink** [comment]
Fixed in 24f37711409e4caa65892d7d705f33839e067df4
