### ISSUE TITLE
Unlimited Two-Way Auto-Translations for a Price

### ISSUE THREAD

**Issue by Codonbyte** [night/BetterTTV#1177]
I like watching Minecraft streams. Unfortunately, most of the technical vanilla streams are in German, which I can't speak. 

If BetterTTV had an option to auto-translate all incoming and outgoing messages to languages of my choice, I'd be more than willing to pay for the translation fee, plus a reasonable processing fee to you guys. 

I'm thinking it could be a monthly subscription similar to channel subs, except that the amount you pay depends on how much text you translated. Purchasing this subscription would give you the option to activate "auto-translate mode". The user would be able to set both their outgoing language, and their incoming language, and all outgoing and incoming messages would be translated accordingly. 

One of the things I love about twitch is the fact that it allows me to chat with people from all over the world. Meeting people from other cultures has broadened my horizons, given me new perspectives, and even made me rethink some of my positions. 

This feature would take this a step further: smashing language barriers, and bringing the entire world even closer together. This would indisputably make twitch a **better** place.

**Comment by night** [comment]
Unfortunately it's much too expensive to offer autotranslation, sorry. At a cost of $10 per million characters and given the speed of typical Twitch chats, it would be a costly feature for us to add and we probably could not offer it at a cheap enough price to interest most users.
