### ISSUE TITLE
It would be awesome if you brought back Blackout Chat (Chroma Key)

### ISSUE THREAD

**Issue by Jdudegaming** [night/BetterTTV#1178]
It would be awesome if you brought back Blackout Chat (Chroma Key), at first I used it to chroma key my chat, but I kept using because it was so much easier to read. I understand if you want to keep this removed. Keep up the awesome job with the plugin, don't know how I'd use Twitch without it :)

**Comment by night** [comment]
We removed it because it was hardly used and was a maintenance annoyance. Migrate to KapChat instead: https://nightdev.com/kapchat
