### ISSUE TITLE
EMOTE MENU for bttv not working on Vivaldi Web browser

### ISSUE THREAD

**Issue by KhalaiAvenger** [night/BetterTTV#1179]
The emote menu for Vivaldi Web Browser is not showing. 

![capture](https://cloud.githubusercontent.com/assets/19418048/15341401/0e66e124-1c54-11e6-955a-f8ebee307cc1.PNG)

This is what it's like with Vivaldi.

Here's what bttv is like for Chrome where the emote menu actually shows.
![capture for chrome](https://cloud.githubusercontent.com/assets/19418048/15341443/4ff9564e-1c54-11e6-91c6-be93687fd0cc.PNG)

**Comment by cletusc** [comment]
Tracking this at cletusc/Userscript--Twitch-Chat-Emotes/issues/90 for my reference. Once I close that issue, I'll update with a comment here.

**Comment by cletusc** [comment]
This works just fine for me. Please make sure you have the `Emote Menu` option turned on.

![Option panel, "Emote Menu" setting turned on](http://i.imgur.com/rVJzm6M.png)

**Comment by KhalaiAvenger** [comment]
OH SHOOT! I forgot that it wasn't turned on by default.
