### ISSUE TITLE
Commands to Add /blacklist and /highlight Tokens

### ISSUE THREAD

**Issue by Codonbyte** [night/BetterTTV#1180]
Sometimes I encounter a user that I would really rather not communicate with. However I sometimes log channels I'm in so I won't /ignore them, because then the log would be incomplete. I therefore use BetterTTV's blacklist feature to block users. At the moment, adding a user to my blacklist requires opening up a dialog that causes the stream to freeze sometimes. 

I would like to be able to simply type /blacklist (big_jerk) and never see messages from big_jerk ever again. Also the same for /highlight. 

If you added this feature, to make it fully useful you'd also want to fix auto-complete so it can auto-complete a username even if it there is a round-bracket immediately before it, otherwise the leading ( would prevent auto-complete from filling in "big_jerk" for me. 

Another option would be to add a separate /blacklistuser command that takes a single token and automatically wraps it in quotes before sticking it on the end of the blacklist keywords (same for highlight). 

Adding this feature would also allow you to implement working **[Channel-Specific Keywords](https://github.com/night/BetterTTV/issues/68)** without the headache of designing a GUI for it. 

I mostly focused on /blacklisting (users), but I'd get plenty of mileage out of /blacklisting simple phrases as well; I really don't need to see one more twitch-chat discussion about Donald Trump.

**Comment by night** [comment]
We do not have any interest in extending the functionality of blacklists and highlights into chat at this time, sorry. We will eventually modify blacklists and highlights into a unified UI offering more customizability and features, but there's not currently an ETA for that happening. There are some larger base issues that need to be addressed before we can tackle this one.
