### ISSUE TITLE
[Bug] Channel Emote list not updating on channel leave

### ISSUE THREAD

**Issue by BradyThe** [night/BetterTTV#1189]
As shown in the attached screenshot below the Channel Emote list is not updating when switching channels within the same tab, for example through Following/Games/Channels, or switching to a hosted channel.
![firefox_2016-05-19_22-17-22](https://cloud.githubusercontent.com/assets/8181555/15408749/11a73b94-1e12-11e6-8953-9396752a7b75.png)

Green = Channel 1
Yellow = Channel 2
Red = Channel 3

**Comment by night** [comment]
The emotes are getting removed properly from our array, so it's another emote menu bug. cc @cletusc

**Comment by cletusc** [comment]
> another emote menu bug

:ok_hand: 

Confirmed, filed as cletusc/Userscript--Twitch-Chat-Emotes/issues/92

**Comment by night** [comment]
@cletusc any updates?

**Comment by cletusc** [comment]
Fixed in [latest version](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/releases), ready for your testing.
