### ISSUE TITLE
invisible chat

### ISSUE THREAD

**Issue by zethic** [night/BetterTTV#1193]
Hey idk what I did but my chat now wont show any text when bttv is on but works fine when it is off, i think it may have something to do with accidently blacklisting but I really have no clue.
![screenshot_2](https://cloud.githubusercontent.com/assets/19495908/15438482/67c4df12-1e9a-11e6-9aaf-703b90bc5666.png)
here is an example of empty chat, for some reason i can see one message with no text

**Comment by night** [comment]
I cannot reproduce this. Try clearing your cookies (from the beginning of time). That resets your BetterTTV settings, which should fix any issues with them.

**Comment by zethic** [comment]
I tried that and it didn't change anything, it turns out my adblock extension was causing this I'm not sure why cause I've had ad block and used bttv fine for a long while.

**Comment by zethic** [comment]
I switched my ad blocker from from adblock to adblock plus and it works fine now
