### ISSUE TITLE
Blacklist filters

### ISSUE THREAD

**Issue by skapytek** [night/BetterTTV#1195]
Hi,
i rly like the "blacklist" feature but what i dont like is the look and the handling.
I have a big amount of words, letters and other things in the blacklist and its getting rly uncomfortable when its getting bigger.

My suggestion is to rework the blacklist to give it a look like excel.
So we can put a word/sentence/letter,... in one row
For example in the first row i put: cyka
In the next row i put: {csgocircle.com} 
and so on

Another way would be to add support of filter lists like adblock pro have it.
So we can add a list that that includes cyrillic letters, another one includes twitch emotes, and so on.
Lists could be hosted on github, websites, or local on the pc where the user could update itself.

Best regards

**Comment by night** [comment]
Making a better UI for highlights and the blacklist is planned.

**Comment by skapytek** [comment]
Thanks for the info
