### ISSUE TITLE
Please add comma removal upon a mention

### ISSUE THREAD

**Issue by jameslee534** [night/BetterTTV#1201]
When typing a message to another user in a streamer's chat, BTTV automatically places a comma after "@username" in the beginning of a message. I honestly don't like this because I would like to use the @username without having to go out of my way to delete the comma that it automatically places. Please add an option to remove this feature! Thank you.

**Comment by voloshink** [comment]
We prefer to enforce proper grammar

**Comment by ketzusaka** [comment]
This is actually incredibly annoying and an option would be really great.
