### ISSUE TITLE
BTTV Not working 

### ISSUE THREAD

**Issue by WeeD02** [night/BetterTTV#1210]
I followed each part of the "Debugging BetterTTV" topic so I'm here for the JavaScript part:

`Uncaught ReferenceError: WeakMap is not defined betterttv.js?0.8070968426764011:107`

**Comment by night** [comment]
What OS (and version) are you using, and what browser (and version) are you using?

**Comment by WeeD02** [comment]
Windows 7 ; Google Chrome 31.0.1650.59 m

**Comment by EhsanKia** [comment]
Your chrome is really out of date. Chrome is up to version 50 already. Yours is over 2 years old. Do you have automatic updates specifically turned off? This bug aside, there are major security risks with using such an outdated browser. You really should update to the latest version of chrome.

**Comment by night** [comment]
Upgrading Chrome should fix the error.
