### ISSUE TITLE
twitch feature 

### ISSUE THREAD

**Issue by NeoEchogg** [night/BetterTTV#1212]
the clips feature does not work for me for partnered streamer or non partnered i tried twitch staff no help is there a fix for it thanks 

                                                               -NeoEcho.gg

**Comment by voloshink** [comment]
Is this an issue related to betterttv?

**Comment by NeoEchogg** [comment]
i dont know

**Comment by voloshink** [comment]
Well disable betterttv and see if it works

**Comment by NeoEchogg** [comment]
nope does not work 
 thanks though anymore suggestions

**Comment by voloshink** [comment]
well if it doesn't work without betterttv, then it's not a betterttv issue

**Comment by NeoEchogg** [comment]
i asked twitch staff but did not understand "my twitch feature clips wont work for me on partnered or nonpartnered streams"

**Comment by voloshink** [comment]
we are not twitch support

**Comment by NeoEchogg** [comment]
thanks for the help Kappa
