### ISSUE TITLE
BTTV Feature Request

### ISSUE THREAD

**Issue by firedog2k9** [night/BetterTTV#1217]
along with the darken Theme for ttv, it would be cool to darken chat as well when not in theater mode.

**Comment by firedog2k9** [comment]
maybe this is a bug? im getting white chat text on a white chat background with the normal dark theme on.

**Comment by EhsanKia** [comment]
Can you post screenshot of what you see?
Also, what browser and what operating system are you using.

**Comment by firedog2k9** [comment]
chrome, windows 7, the problem resolved itself after a computer restart. looked like it was a first run issue. thanks for the response.
