### ISSUE TITLE
Search BetterTTV settings

### ISSUE THREAD

**Issue by sguergachi** [night/BetterTTV#1219]
The settings list grows, and that's awesome. But at some point I think it would be great if we could search for a setting we are looking for instead of reading each one at a time.

**Comment by EhsanKia** [comment]
There's a new settings menu in the works. This is definitely a feature I'd love to see in it. Something similar to how RES on reddit works.

**Comment by DennisMellegaard** [comment]
I've noticed the the branch new-settings hasn't had any commits since  Mar 15. Do you mind if i give it a go. Thinking i will follow up on the react code that is there and continue to build upon that.

Just want to make sure that the new settings page idea isn't dropped or canceled.

**Comment by AlcaDesign** [comment]
Mock up using [Fuse](http://fusejs.io): http://codepen.io/Alca/pen/aJOzQM

**Comment by night** [comment]
we added this a while ago
