### ISSUE TITLE
Twitch chat in theater mode is not black

### ISSUE THREAD

**Issue by tbodt** [night/BetterTTV#1220]
In theater mode, it looks like this:

<img width="343" alt="screen shot 2016-05-31 at 1 25 06 pm" src="https://cloud.githubusercontent.com/assets/5678977/15689307/36562854-2733-11e6-813d-7d1ce3ac3480.png">

**Comment by EhsanKia** [comment]
Seems like #1218 broke this.

**Comment by tbodt** [comment]
Seems likely.

**Comment by night** [comment]
Fixed by #1224
