### ISSUE TITLE
2 Bugs found

### ISSUE THREAD

**Issue by deivedux** [night/BetterTTV#1223]
I have noticed some bugs:
1. Sometimes when I want to watch a stream replay or a highlight it doesn't always show up the player, but sounds from video are still being played.
2. When the stream ends, it shows the stream replay above the stream, but if the stream starts again it doesn't hide itself until I refresh the whole page. It's annoying when the streamer restarts his stream and makes his viewers to constantly refresh their pages.

**Comment by EhsanKia** [comment]
Both of those sound like Twitch issues, and unrelated to BTTV. Have you tried to see if either of those happens without BTTV enabled?

**Comment by night** [comment]
Both are Twitch bugs, indeed.
