### ISSUE TITLE
Bug in theatre-mode?

### ISSUE THREAD

**Issue by antyone** [night/BetterTTV#1225]
Can't seem for the life of me figure out how to fix this bug. Whenever I switch on the theatre mode, the chat area won't go dark, the font color changes but that's about it, it's frustrating. 

I tried clearing cache, removing the extension and installing it again, nothing seem to help.

Here's a link to the screen in case you are wondering what I mean:
http://imgur.com/IzZW6lu

**Comment by EhsanKia** [comment]
This is indeed. It has already been reported in #1220 and there's a fix for it coming very soon in #1224

**Comment by antyone** [comment]
Is there a quick-fix I could implement myself or do we have to wait? And how long?

Thanks.

**Comment by EhsanKia** [comment]
This only happens if you're in light mode, so for now, try turning on dark mode.
So just leave theater mode, click the cog under chat, check "Dark Mode", then re-enter theater mode.

The fix should come later today, hopefully in the next hour or so.

**Comment by antyone** [comment]
Yea I know about the dark theme but I absolutely hate how everything just looks the same everywhere.

Well thanks, I'll live until then :+1:

**Comment by antyone** [comment]
I just checked and its fixed in live channels, but the problem still persists in videos of previous broadcasts.

Edit/ ok this is weird, I was watching previous broadcast and everything was fine, until the chat just changed and brought up the white background once again, now this vod is broken for me but other previous broadcasts seem to be ok. Could there still be something triggering the change and bugging the chat?

**Comment by night** [comment]
If it's just an issue with VoDs, then open a new issue and we'll add it to the bug queue.
