### ISSUE TITLE
New Idea for Channel Mods

### ISSUE THREAD

**Issue by Mizvis** [night/BetterTTV#1226]
so i just had this thought. cant promise its never been suggested before but regardless. what if you give channel mods the ability to have a blacklisted set of any string of characters that we can specifically control. for example someone is spamming a specific set of characters that is a banned word in a given channel. but they have found a way to evade it. simply replacing an "I" with a "1". we ban them. they come back under another name. it happens in a very large channel that i mod on maybe a weekly basis. my current solution is to open mirc under my own twitch name that i am a mod of, and set up another key word for that channel for the bot to take care of. what would be better is to have a system in bttv where i can simply and easily copy said banned word, paste it into a box in bttv, and selecting a checkbox of what to do when said banned word(s) show up in chat. choose from a list ranging from purge, to perma ban, to custom timeout. no need for me to open and log into mirc, wait for it to load into the channel, rewrite some bot code to help me mod the channel. essentially turning bttv into a custom channel bot under your own account. most of the work is already in bttv. we have blacklisted custom words and we have really really simply ways for timing people out on a very small scale. but when you have 5000 people spamming "legion beta key" to the point where you can no longer have a immersive chat experience and the actually streamer is getting upset because mods cant keep up... i think being able to control what we do with said blacklisted keywords for the channel would be an excellent addition to the list of settings bttv has to offer. I hope this is kinda a new idea that wouldnt be to hard to implement. id love to know if this is something that can be achieved at a later date :)

**Comment by night** [comment]
That is a job for channel moderation bots with a blacklist feature, not for BetterTTV, sorry.
