### ISSUE TITLE
BetterTTV Channel's

### ISSUE THREAD

**Issue by Mr-Kino** [night/BetterTTV#1228]
So I've noticed that some channels are supporters of BTTV and the ICONS, but there is no way to know which ones are without asking the stream. Some streamers are far to busy to respond or don't get the message due to fast rolling chats. My suggestion is make a UI change so it displays if the channel supports emotes and other BTTV changes.

**Comment by night** [comment]
To get a list of a channel's BetterTTV emotes, enable the Emote Menu in the BetterTTV settings.
