### ISSUE TITLE
/horde /alliance emotes

### ISSUE THREAD

**Issue by Dominikpx** [night/BetterTTV#1229]
Since you cant see the horde/alliance emotes with bttv on, can you guys fix it or make it an option?

**Comment by EhsanKia** [comment]
A fix is coming soon. We just found out about it at the same time as anyone else and are working to add support for it. Cheers.

**Comment by joshuaferrara** [comment]
@EhsanKia Just saw this issue after making PR #1230 

You guys might have a better solution, though.

**Comment by Dominikpx** [comment]
Working now, nice
