### ISSUE TITLE
Feature request:  Chat filter

### ISSUE THREAD

**Issue by targaryen** [night/BetterTTV#1235]
It'd be cool if we could define words or phrases which would trigger the 'Hide Spam Messages' plugin to hide the message.

For example, if I define `horde` then I will no longer see chat messages that contain text like 'FOR THE HORDE!!!'.

**Comment by EhsanKia** [comment]
You can use the blacklist feature for this (click the gear under chat, select blacklist, enter horde). The spam message is specifically for detecting bots and people spamming across twitch.
