### ISSUE TITLE
Feature Request: # of users in chat (next to Viewer #)

### ISSUE THREAD

**Issue by TimeBomb** [night/BetterTTV#1236]
Would be quite nice to know the exact number of users in chat, placed next to the current viewers number. Would be a really interesting metric to see next to the normal viewer count - help differentiate between logged in vs logged out viewers, and potentially help identify some cases of view bots.

**Comment by EhsanKia** [comment]
While there is currently not live updating value anywhere, you can actually get this metric by typing /chatters in the chat window to get an up to date number of chatters. Same thing with /viewers and /followers. Hope that helps!

**Comment by TimeBomb** [comment]
Ah that's really cool, didn't know BetterTTV had those commands. Cheers @EhsanKia.
