### ISSUE TITLE
"Show Deleted Messages" font color not grey anymore.

### ISSUE THREAD

**Issue by Mitsuma** [night/BetterTTV#1238]
Not exactly sure when it happened but when you timeout/ban a user and you had the option "Show Deleted Messages" on the text was grey.

Now it stays the same color as the regular chat color which makes it very hard to distinguish.
![Example](http://i.imgur.com/1ySRu33.png)

I only have BTTV installed, no other plugin that could interfere. Reinstalling/re-enabling the extension didn't help. Clearing caches also did not help. Version 6.8R53 in Chrome 51.0.2704.79.

**Comment by night** [comment]
Fixed by 0db9fb108cfca92236a5acba1e5614dc15ae9164
