### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by Phaeye** [night/BetterTTV#1244]
As is when you enter a search on twitch(only on the website, mobile apps don't do this) only the top 3 search results are shown, which is quite annoying. Not sure if you could address this at all but just an idea. :)

**Comment by EhsanKia** [comment]
It looks like the way it currently works is that it shows:
- the top 3 users
- the top 3 live channels
- the top 3 vods
- 7 more vods
- 7 more live channels
- 7 more users

It's a very strange order but yeah, if you keep scrolling, and hitting next page, you do get more than 3 results? Might be cleaner if we reformatted this into 3 different columns though.

**Comment by Phaeye** [comment]
Oh yeah youre right. That is so unintuitive and weird...
Not really a big deal considering you can navigate it but that organization is rather unattractive

**Comment by night** [comment]
Twitch just improved their search.
