### ISSUE TITLE
Hide Clip feature

### ISSUE THREAD

**Issue by omd-mvp** [night/BetterTTV#1245]
I don't know if that would be even possible, but that clip feature + its accompanying pop-up annoys me, since I'm never gonna use it anyway.

**Comment by night** [comment]
I have no idea what you're referring to. If you mean the one-time popup Twitch gives to introduce you to them, then I don't see why we'd need to hide that since it happens once.

**Comment by omd-mvp** [comment]
Well, I get it on every stream, so that's why I mentioned it...

**Comment by EhsanKia** [comment]
Sounds like a bug with Twitch. Once you dismiss it, you should never see it again. Make sure you have cookies enabled in your browser.

**Comment by Mi-Turner** [comment]
Hello! I don't recall me sending a message regarding this?
