### ISSUE TITLE
Templates for ban reasons

### ISSUE THREAD

**Issue by chdxD1** [night/betterttv#1246]
Twitch lately introduced a new parameter to bans and timouts which is a reason. (See here: https://twitter.com/Twitch/status/739210308472823808)

It would be nice to have a list of reason templates to specify a reason much quicker and also via the GUI of BetterTTV.

**Comment by Reecon** [comment]
Wanted to suggest something like this. I think it would be useful to include the last message the banned user sent as the ban reason.
