### ISSUE TITLE
BTTV seem to break FrankerFaceZ emotes

### ISSUE THREAD

**Issue by Immortalizd** [night/BetterTTV#1247]
So, I just went on twitch and tested my FFZ emotes, and for some reason they were broken (as well as the site looking a bit funky). I enabled and disabled both BTTV and FFZ to check what was causing it, and it seems like BTTV is the sinner.

**Comment by night** [comment]
BetterTTV is functioning normally. Historically it's been FrankerFaceZ job to integrate with BetterTTV. If there's an incompatibility I'd suggest reaching out to them.

**Comment by Immortalizd** [comment]
Ok, thanks :+1:
