### ISSUE TITLE
It's hard to make the switch!

### ISSUE THREAD

**Issue by Cthreezzzy** [night/BetterTTV#1249]
I am having trouble getting use to BTTV because the chat is much more zoomed and wide, I don't know if there is already an option for this, I have looked but Idk if I missed it...  Anyways is there a way to make the chat like Normal Twitch? (The original font, and size of text)

Thank you

**Comment by night** [comment]
Not at this time, sorry. We make the font size a bit larger to be more comfortable to read (and lessen eye strain caused by Twitch's default size). We do not, however, modify the font.
