### ISSUE TITLE
Request for BTTV

### ISSUE THREAD

**Issue by NooneLikesDan** [night/BetterTTV#1252]
Just wondering if you could add an option that allows all standard and BTTV to be used without them being case specific. For example: Kappa could still activate as kappa. I know it might sound a little tedious, but tab completion doesn't always work as intended for me so I just prefer to type emotes out and if they could be non case sensitive it would be much easier. Thanks.

**Comment by night** [comment]
Emotes are case sensitive because many are simple words that you wouldn't be able to use if they weren't.
