### ISSUE TITLE
Double-click to Theater Mode?

### ISSUE THREAD

**Issue by awatson87** [night/BetterTTV#1253]
Huge fan of Better TTV, awesome work.

Curious as to whether or not it's feasible to have a "double-click to Theater mode" option - I rarely ever use full screen at work and thought it would be a huge convenience for when I need to access the site.  Not a heartbreaker if it couldn't be, but I know I wouldn't be the only person who'd appreciate it.

**Comment by night** [comment]
You can use automatic theater mode, but we're not willing to add a double-click function for theater mode as it seems superfluous when you could just click on theater mode.

**Comment by EhsanKia** [comment]
There's also already a hotkey. You can press alt+T to go in theater mode.
