### ISSUE TITLE
Chatter count in viewer list

### ISSUE THREAD

**Issue by pahakalle** [night/BetterTTV#1254]
Could you add a chatter counter to the new better viewer list.
It would be nice to see how many are chatting in a channel 
and when a channel is hosting another channel you cant see the viewer count.

**Comment by EhsanKia** [comment]
Might consider adding this to the Better Viewer List, but in the mean time, you can time /chatters, /viewers and /followers in chat to get an up to date count for those.

**Comment by pahakalle** [comment]
OK thanks 😄
