### ISSUE TITLE
Only some settings working

### ISSUE THREAD

**Issue by fishythefish** [night/BetterTTV#1260]
Last night, BetterTTV was working just fine. Today, only some of the settings seem to be taking effect. For instance, the dark theme is applied and I can toggle button colors between blue and purple, but streams don't go into theater mode automatically, BTTV emotes don't display, and emote autocomplete doesn't work.

I've cleared my cache and cookies, deleted the extension and reinstalled, and backed up and restored my settings.

**Comment by fishythefish** [comment]
Theater mode consistently fails to work, but emotes are inconsistent. After toggling all settings off, I reloaded the page and then reimported my settings. BTTV emotes and emote autocompletion started working. After refreshing the page, they stopped working again.
Attempting this "fix" again did nothing after this point.

**Comment by night** [comment]
There's a bunch of broken stuff due to Twitch changes. We're looking into it...
