### ISSUE TITLE
Better TTV Refusing to Load After Exhausting All Options

### ISSUE THREAD

**Issue by minerman5777** [night/BetterTTV#1261]
Hi, I encounter an issue with Better TTV seemingly out of the blue with various settings still remaining in effect on the Twitch Page but I can't access the settings and the GIF Emotes are unavailable. 

I've tried everything suggested by a mate in the chat room of the streamer we were watching.
Chrome Version: 51.0.2704.84 m
OS: Windows 10
I have full access to Twitch and it's features, and the https://cdn.betterttv.net/betterttv.js page loads fine
Relevant or no, 12 lines from Chrome's console from the very top will be enclosed in a text file
[Chrome Log.txt](https://github.com/night/BetterTTV/files/308495/Chrome.Log.txt)

Hope I can reach a solution.
Cheers.

**Comment by night** [comment]
Nothing in your logs point to an error with our extension. Follow debugging instructions at https://community.nightdev.com/t/betterttv-debugging/3685
