### ISSUE TITLE
"Send" button still Purple on Blue mode

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1264]
The button in the whisper section, after you go into a personal chat
![bug2](https://cloud.githubusercontent.com/assets/6445601/15963728/dcdbde3a-2f1c-11e6-8049-2e5b02b21e53.png)

**Comment by NBruderman** [comment]
If you want, I found quite a few "Purplish" stuff on Blue mode. Do you want me to report all of them differently, or on one issue?

**Comment by night** [comment]
all in one..
