### ISSUE TITLE
Timer on the messaging

### ISSUE THREAD

**Issue by ZeZerT** [night/BetterTTV#1265]
Hello,

This little bug I saw while spamming shit on the channel eulcs1 : The message "You are banned from talking in eulcs1 for 287 more seconds." makes the timer go for 1 second instead of the 287 it should be. 

I guess that's because you search for the first number in the string. Maybe taking the last, or the one between "for" and "more" would solve that. 

By the way, thank you for your addon.

**Comment by night** [comment]
Good catch: https://github.com/night/BetterTTV/blob/3f34341b1dcd6797662079848dd6cf504739066f/src/js/features/channel-state.js#L138

**Comment by NBruderman** [comment]
I'll tell you more, the timer does appear (Ban timer), but only after you send another message. Then the timer works fine.
