### ISSUE TITLE
Option to use up and down arrow keys within whispers

### ISSUE THREAD

**Issue by Jackalope-Gaming** [night/BetterTTV#1266]
Would it be possible to add an option so that we can use the up and down arrow keys to navigate inside a whisper instead of having those keys either change to a previous whisper or not do anything at all?

**Comment by night** [comment]
No, that's not possible, sorry. Twitch binds those in Ember, and it's shielded from what we can easily access. We would need to do excessive work to get this to work, and it's not worth the time.
