### ISSUE TITLE
Feature suggestion: Limit message characters 

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1282]
Idea that I just thought of: Like the option to limit the chat history, can you add a feature that hides every message above X characters (Chosen by the user). It can be really useful when there is a spam in the chat, and all those spams are longer that 100 characters (for example). Instead of waiting for action by the mods (which mostly not that helpful), the user just can set a limit to the length of the message he sees, and block the spam in that way.

**Comment by night** [comment]
We are not interested in getting into chat filtering, sorry. It tends to use more resources on clients, many of whom do not have adequate resources for filtering. Bots should be used by channels to restrict chat to rules.
