### ISSUE TITLE
Cursor returns to chat

### ISSUE THREAD

**Issue by Erumya** [night/BetterTTV#1284]
While watching a stream I like to leave my cursor on the stream such that I can utilize the space bar and page up/ page down hotkeys to control the video. However, BetterTTV always returns you to the chat box any time you alt+tab, go to a new tab, open start menu or anything else that makes it no longer your top window.
I'd like to keep the extension for the extended emote library but not having automatic access to my hotkeys harms my viewing experience.
Thank you for taking the time to read my ticket.
Any help or solutions would be greatly appreciated.

**Comment by night** [comment]
fixed by 67cdc995c7964301d5b8c22632d57727bedbb6fe

**Comment by Erumya** [comment]
Thank you very much.
