### ISSUE TITLE
Both buttons do the same

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1286]
While viewing a Whisper window you have both "minimize" and "maximize" buttons appearing at all times, and doing exactly the same action, either when the window minimized or shown. If I'm not wrong, only one of them should be appearing in a given time, depends on the action it does, either minimize when shown, or show when minimized.
![untitled](https://cloud.githubusercontent.com/assets/6445601/16180584/fbf9b23e-3691-11e6-9cd2-60eefcb314d4.png)

**Comment by EhsanKia** [comment]
Indeed, only one should be showing up. I can't seem to replicate the issue myself. Do you have any specific way of replicating this? Does it happen for all your whispers? Do you have any other extensions such as FFZ installed?

**Comment by NBruderman** [comment]
Hmmm... I just confirmed its happening also on my laptop... It happens to me all the time, I can replicate this on any given time. I don't have another extension that has any relations to Twitch, besides (maybe) adblock. It happens in every conversation to me. I can tell you I have dark mode and blue buttons on etc, but it keeps happening even after using the stock settings.

**Comment by NBruderman** [comment]
Closed by accident XD

**Comment by NBruderman** [comment]
Seems to be fine now... Don't know what happened. Anyway, closed for now.
