### ISSUE TITLE
Something I'd like to see added due to recent changes on twitch

### ISSUE THREAD

**Issue by dws6969** [night/BetterTTV#1300]
Is there a way to hide the suggested VODS when you open the "following" tab? I find them useless and would prefer to see either hosts or my followed games listed below the live feeds. I personally hate VODS, that's what youtube is for... I come to twitch to watch live feeds. XD Just thought I'd put it out there. Thanks either way. I love BTTV!!

**Comment by night** [comment]
Enable "Default to Live Channels" in the BetterTTV settings..
