### ISSUE TITLE
BTTV hides language filter on Dota 2 live channels page

### ISSUE THREAD

**Issue by Cyborgmatt** [night/BetterTTV#1301]
The Dota 2 live channels page now has a language filter on it however BTTV doesn't support this/hides it.
![chrome_2016-06-22_15-55-22](https://cloud.githubusercontent.com/assets/3114217/16271429/ed5f5934-3891-11e6-8ab9-bd9e1a2b3faf.png)

**Comment by EhsanKia** [comment]
I see it just fine, exactly as shown in the screenshot, with BTTV installed.
Do you have any other extensions installed?
