### ISSUE TITLE
BTTV not working?

### ISSUE THREAD

**Issue by pyramidheadddd** [night/BetterTTV#1304]
Hi I have had BTTV installed for a couple months now and today it just randomly stopped working? My browser says it's enabled and the settings page is still on my Twitch account but none of the features are working. I tried uninstalling and reinstalling it and still nothing. Anybody else having a similar issue?

**Comment by EhsanKia** [comment]
Yes, there is currently an issue with the API, it should be fixed shortly!

**Comment by dakillerclown87** [comment]
same issue here.

**Comment by dakillerclown87** [comment]
@EhsanKia yeah I made a topic about this lol didnt see this one.

**Comment by dakillerclown87** [comment]
@EhsanKia also some people are able to see them and some people can't. maybe it's within a browser? I'm using google chrome.

**Comment by EhsanKia** [comment]
If you already had the page open, you will see them, if you refresh, it won't be able to fetch the list of emotes.

**Comment by dakillerclown87** [comment]
@EhsanKia yeah I left a channel and joined another and it stopped working. maybe that's why. thanks for the info again.

**Comment by pyramidheadddd** [comment]
I hope it gets fixed soon! But it's not just an issue of not being able to see  bttv emotes, all my other BTTV features aren't working

**Comment by EhsanKia** [comment]
Should be back up, sorry for the inconvenience.

**Comment by EhsanKia** [comment]
@pyramidheadddd it shouldn't affect other BTTV features, that sounds like a different issue.

**Comment by pyramidheadddd** [comment]
All my features weren't working but thats been resolved! All good now :D Thanks!
