### ISSUE TITLE
BTTV stopped working for me

### ISSUE THREAD

**Issue by dakillerclown87** [night/BetterTTV#1305]
they won't show up for me anymore, every other emote shows up, and the personal emotes show up but all the other bttv emotes won't. I'm using google chrome and latest version, also  I cleared my cache and cookies still nothing, heres a gif. https://gyazo.com/329c323da392886280664d320c88fa5f
and another https://gyazo.com/3f419c4d9eb102d84372984b8b70c855

**Comment by EhsanKia** [comment]
Yes, there is currently an issue with the API, it should be fixed shortly!

**Comment by dakillerclown87** [comment]
@EhsanKia thanks for the update man.
