### ISSUE TITLE
The ability to delete single messages in chat.

### ISSUE THREAD

**Issue by KiwiJackal** [night/BetterTTV#1307]
The ability to delete single messages in twitch chat, like you can do in the chat replay from previous streams. Sometimes someone who has been behaved for an hour or so says something rude, I want to be able to just delete that one message instead of timing them out and deleting all their messages.

**Comment by EhsanKia** [comment]
That's not possible given given Twitch's chat commands. All you have access to is timing out someone. Deleting lines from recorded chat is an entirely different system which does not apply to chat.

**Comment by KiwiJackal** [comment]
Dam, ok thanks anyway.
