### ISSUE TITLE
Disable "Based on your viewing history"

### ISSUE THREAD

**Issue by GerardvanDijk** [night/BetterTTV#1311]
Recently, Twitch added a list of suggestions for past broadcast videos to the 'Following' tab, right under the channels you follow. Personally, I think it is completely useless and it bothers me a lot, and I am pretty sure I am not the only one. My suggestion is a disable button to hide this content.
I hope you will be able to implement this!

Kind regards, Gerard

**Comment by night** [comment]
Use the "Default to Live Channels" option already in the settings...

**Comment by MrFine1** [comment]
"Use the "Default to Live Channels" option already in the settings..."

But then the Live Games section isn't displayed at all. I want both my followed channels and the live games section to be visible without scrolling down.
