### ISSUE TITLE
BTTV Multi streams

### ISSUE THREAD

**Issue by AverageJedi** [night/BetterTTV#1316]
I think it would be cool to have a BTTV multistream feature. If 2 or more people I wanna watch are playing the same game, there should be a way to add them to one screen? I guess is the best way to describe it. There is my regurgitated idea I hope it makes sense.

**Comment by NBruderman** [comment]
http://multitwitch.tv/
No need to thank me

**Comment by AverageJedi** [comment]
**Facepalms indefinitely** had no idea, oops

**Comment by NBruderman** [comment]
Glad I could help :)
