### ISSUE TITLE
Unrecognized command: /t when timing out

### ISSUE THREAD

**Issue by notabot33** [night/BetterTTV#1317]
I am getting the message "Unrecognized command: /t" when timing out people with long lengths. 

`/t user 1000000`
`user has been timed out for 1000000 seconds.`
`Unrecognized command: /t`

The timeout does get applied.

![cbqkz8k](https://cloud.githubusercontent.com/assets/20174691/16396958/6894b876-3cb9-11e6-8b86-a332b45b67bf.png)

The error does not always occur.

**Comment by EhsanKia** [comment]
Just to clarify, this only happens when sending the message by clicking the send button with your mouse. Will fix in next patch.
