### ISSUE TITLE
New cheer icon in chat text area is black in Dark mode

### ISSUE THREAD

**Issue by jrbury** [night/BetterTTV#1318]
This is what the new cheer/bits icon looks like now with Dark mode

![image](https://cloud.githubusercontent.com/assets/7307833/16396770/632e4ecc-3c8e-11e6-82b7-c4494b4adffb.png)

This is what it looks like using the same values as the emoticon icon

![image](https://cloud.githubusercontent.com/assets/7307833/16396927/40faae80-3c8f-11e6-85dc-b2198fec7fd7.png)

normal: 888 
hover: 777

Let me know if this is acceptable and I'll put in a PR.

**Comment by EhsanKia** [comment]
We are currently working on fully supporting the new Cheers feature. This will be fixed as part of it.

**Comment by jrbury** [comment]
Gotcha, thanks!
