### ISSUE TITLE
Chat badge toggles

### ISSUE THREAD

**Issue by Celean** [night/BetterTTV#1323]
With the new "bits" feature adding Yet Another Chat Badge, some people now just about require a full line of chat just to show their badges and username. As such, it would be awesome if BTTV could add toggles to hide some of these.

Personally I would like the option to hide Turbo, Cheer and "Promo" Badges (like the recent Horde/Alliance one), while still showing Admin/Staff/GMod/Moderator/Subscriber, but as people may want to pick and choose, this could potentially be a toggle for every type of Paid/Promo badge.

**Comment by NBruderman** [comment]
You actually got a point. However, it's not easy to decide which badges can be toggled off and which not. The whole Horde/Alliance thing is gone right now. The Cheer thing seems to stay for now. The question here is what is the limit?

**Comment by Celean** [comment]
Well, you could make an argument for all types of badges, but I'm not sure a lot of people would want to not know who staff and moderators are, it's mostly to counter the "badge creep" with all the different badges you just pay money for. Seeing as the promo badges come and go, and I guess you'd rather not clutter the settings with ten different toggles for chat badges, having something like three toggles (say, Subscriber, Turbo and Cheer) could be a reasonable compromise.

**Comment by EhsanKia** [comment]
While your overall suggestion is good, it doesn't quite apply here because as far as I know, cheer badges replace turbo badge for now.

**Comment by night** [comment]
You can also disable bits badges by hiding bits in the BetterTTV settings. We might address this if more badges get added. For now, it's not an issue.
