### ISSUE TITLE
Re-subs doesn't show.

### ISSUE THREAD

**Issue by MattiSony** [night/BetterTTV#1324]
Doesn't look like re-subs are showing in chat. No one with BTTV could see the sub.

The raw output of the resub:

```@badges=subscriber/1,turbo/1;color=#FF0000;display-name=Max1mus219;emotes=;login=max1mus219;mod=0;msg-id=resub;msg-param-months=19;room-id=56625428;subscriber=1;system-msg=Max1mus219\ssubscribed\sfor\s19\smonths\sin\sa\srow!;turbo=1;user-id=61042270;user-type= :tmi.twitch.tv USERNOTICE #silentsentry```

**Comment by night** [comment]
yew broke it @EhsanKia

**Comment by EhsanKia** [comment]
I just tested it, it works fine on my end
![](http://i.imgur.com/N7RHg85.png)

Can you confirm you have no other extensions such as FFZ installed?

**Comment by night** [comment]
yesterday I had a resub that didn't show in chat.. so it's definitely a bug

**Comment by night** [comment]
it might show for others and not you?

**Comment by EhsanKia** [comment]
I'll test it further.

**Comment by MattiSony** [comment]
I do not have any other extensions that messes with the chat, multiple people have said it doesn't work with BTTV enabled.

**Comment by Decicus** [comment]
I noticed this earlier, and from what I noticed, resub messages with no message specified from the user didn't show up. If a message was specified, it showed up.

**Comment by EhsanKia** [comment]
Thanks for the heads up, should have a fix soon.
