### ISSUE TITLE
Chat button is broken

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1326]
Its now black (not purple/blue) and doesn't display the timer again
![untitled](https://cloud.githubusercontent.com/assets/6445601/16433752/7a1e8fdc-3d94-11e6-8a61-9a6bfe06020c.png)

**Comment by AlcaDesign** [comment]
Line 6 of [src/js/features/channel-state.js](https://github.com/night/BetterTTV/blob/74d152cbf1306e9d3e8c4fa8de27b7a334249381/src/js/features/channel-state.js#L6)
```javascript
var chatButton = '.chat-interface .chat-buttons-container .button.primary.float-right';
```

Currently, the button is 
```HTML
<button class="button float-right qa-chat-buttons__submit js-chat-buttons__submit" ...>...
```
so need to remove `primary` and probably add `js-chat-buttons__submit` and/or `qa-chat-buttons__submit`.

**Comment by EhsanKia** [comment]
They keep changing the CSS on that thing every week... ugh.

**Comment by teak** [comment]
Was this fixed? I fixed the original black button issue in https://github.com/night/BetterTTV/pull/1329/commits/1b7b291b711f2c6aea654486d954ee70a5eac875

**Comment by EhsanKia** [comment]
You fixed the css, but channel state showing slow mode time is still broke

**Comment by teak** [comment]
Should be in a different issue :P

**Comment by EhsanKia** [comment]
Or maybe you can fix this too OMGScoots the solution is right there you just need to commit it.

**Comment by teak** [comment]
I could commit it. But testing is a different matter. Im far to lazy for that OpieOP

**Comment by EhsanKia** [comment]
Testing? What's that LUL

**Comment by night** [comment]
should reference that button with `:last-child` instead of its classes then...
