### ISSUE TITLE
LUL emote not working after bits update

### ISSUE THREAD

**Issue by Zatlon** [night/BetterTTV#1328]
After the last twitch update, I cant see the LUL emote or FeelsBadMan, I tried reinstalling the BTTV still not working.. Check the attachment for a screenshot
![22](https://cloud.githubusercontent.com/assets/20197048/16437487/b7bac816-3da7-11e6-89bf-89b2a786a8b9.png)

EDIT: it also seems when I hover over an emote it doesnt show it name.

**Comment by EhsanKia** [comment]
It seems like none of the BTTV emotes where working there. It could've been a short server outage, can you confirm it's still happening?
