### ISSUE TITLE
Can't /join a channel when roaming around in Anon mode.

### ISSUE THREAD

**Issue by Echoskope** [night/BetterTTV#1346]
Enable Anon Chat mode via the BTTV settings menu, then type /join in chat and get this:

`10:30 BetterTTV: [Anon Chat] Logging you back into chat..`

But when you try to actually chat normally it comes back with this:

`You can't send messages when Anon Chat is enabled. You can disable Anon Chat in the BetterTTV settings.`

**Comment by night** [comment]
It's intentionally done like this. `/join` and `/part` are temporary, while the setting in the options is permanent.
