### ISSUE TITLE
Clips aren't embedded in chat like they are in vanilla twitch

### ISSUE THREAD

**Issue by Slikrick** [night/BetterTTV#1349]
How it looks in vanilla twitch light mode:

![vanilla](https://cloud.githubusercontent.com/assets/7969393/16582165/2f4e9646-427b-11e6-8395-3cd7f740e286.png)

How it currently looks in BetterTTV light mode:

![clip2](https://cloud.githubusercontent.com/assets/7969393/16582196/6a1aea18-427b-11e6-8cf7-384f158fe1f2.png)

I think it should be embedded by default like it does in twitch, but with an option to show up as a normal message like it does currently. Since it is very much out there, compared to the rest of the chat messages.

**Comment by EhsanKia** [comment]
I tried implementing this. My Ember hackfu isn't strong enough to figure out how to use their components to build the HTML for me, and I'm not gonna record the embed code myself so.

**Comment by teak** [comment]
The entire feature is just a regex and some HTML. Or is there more to it that I'm missing?

**Comment by EhsanKia** [comment]
It fetches metadata from some clips API too

**Comment by night** [comment]
I do not want this feature. Chat is spammy enough already.

**Comment by sooqua** [comment]
I want this, pls fix.

**Comment by night** [comment]
Swap to the beta, it exists on it already.
