### ISSUE TITLE
Suggestion for Show Deleted Messages

### ISSUE THREAD

**Issue by Whippity** [night/BetterTTV#135]
For this option, maybe add in the opportunity to unshow the message once the deleted message is shown. Like, right now, when the deleted message is shown, it just stays there. I believe that allowing the option to unshow it after showing the message would be beneficial.

**Comment by night** [comment]
I'm not sure I get the reason you'd want to unshow it after viewing it. The point of hiding the message in the first place is just to prevent people from potentially harmful messages, but if you choose to see the message you already know what to expect.
