### ISSUE TITLE
Why does my Bettertv won’t load my twitch streams? 

### ISSUE THREAD

**Issue by clarclar12** [night/BetterTTV#1352]
twitch name: ClarClar12

Whenever I remove BetterTTV as my chrome extension the twitch stream loads but when I put it, it just loads endlessly. It doesn't work only in my pc. It works fine on my laptop. I tried flushing my dns, used ccleaner, uninstall/install browser, no anti-virus, disabled other extentions and changing into the default chrome ip nothing works. Any more suggestions I should do? It's really weird that this happened.

Here's what's happening on the developer tools of chrome when I tried to load twitch stream with betterttv
https://gyazo.com/4f69f39ca7142104a108f130d43cfc18 <-- image link

tried the tracer route
Tracing route to cdn.betterttv.net [104.25.176.35]
over a maximum of 30 hops:

  1     2 ms     2 ms     2 ms  192.168.1.1
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6     *        *        *     Request timed out.
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9   187 ms   207 ms   188 ms  104.25.176.35

Trace complete.

this was the result.

**Comment by EhsanKia** [comment]
The console errors are not related to BTTV (are there any more you missed?)

The traceroute seems problematic, you're never even getting out of your own router.

Does this load for you? https://cdn.betterttv.net/betterttv.js

**Comment by clarclar12** [comment]
any idea what client that blocks this? I have tried everything and yes I can load the link. yeah my isp provider sucks so there's no point in relying in trace route :( 

I've tried the guide in the 2nd link. settings are same.

**Comment by EhsanKia** [comment]
This is network debugging. You say it works on other devices, are those devices also on the same network? If so, then router and above is fine, the device itself is the problem. Could be firewall settings or some antivirus?

**Comment by clarclar12** [comment]
my only firewall here is the windows itself. I have not installed any anti virus since it's a newly installed OS (like 2-3 months old?) I don't rely on anti-virus much coz it blocks  a lot of stuff

**Comment by clarclar12** [comment]
yes it works on my laptop with bttrttv
