### ISSUE TITLE
Toggle Viewer Count

### ISSUE THREAD

**Issue by BubiBalboa** [night/BetterTTV#1353]
Hello! 
I would like to request a feature. 

Please make a toggle to turn off the viewer count under the video and in theater mode.

Seeing a channel that I like having very little viewers makes me kinda sad and not enjoy the content as much. I already blocked the viewer count under the video with ublock but it seems there is a new feature that shows the viewer count in theater mode when the mouse is in the video window.
I think it would also be welcomed by streamers themselves to remove some pressure.

Thank you for your consideration.

**Comment by night** [comment]
You can have uBlock set to block that too if you must, but I don't think it's a major issue that warrants adding yet another setting.
