### ISSUE TITLE
Stream window size lags behind when resizing - Any fix?

### ISSUE THREAD

**Issue by Ree1981** [night/BetterTTV#1354]
Basically title. When you resize the browser window, or go from fullscreen to not fullscreen, the stream window lags behind in resizing itself in a way that's pretty buggy and annoying. This doesn't happen with BTTV turned off. Using the latest Firefox, 43.0.3.

Any fixes for this?

**Comment by night** [comment]
This is because we have to wait on Twitch's resizer to finish before executing our own. Otherwise they fight or mis-calculate measurements.

**Comment by Ree1981** [comment]
What's the purpose of your resizer?

**Comment by night** [comment]
> What's the purpose of your resizer?

Our resizer allows you to resize chat to make it larger. To resize chat, drag the left side of it.


> Can't we implement a disable option?

It is not possible to toggle every feature, sorry. It's not feasible for any software to make toggle for every feature since then there'd be thousands of options.
