### ISSUE TITLE
auto-html5 streams

### ISSUE THREAD

**Issue by bgaimur** [night/BetterTTV#1355]
Please add a feature to enable auto-html5 streaming for twitch. You do this by adding "?html5" to the end of the stream page's url. 

Example: 

https://www.twitch.tv/gamesdonequick 

becomes

https://www.twitch.tv/gamesdonequick?html5

papa bless

**Comment by EhsanKia** [comment]
That doesn't work. Clicking on that link still gives you a Flash player.

AFAIK that only works on popout player:
http://player.twitch.tv/?channel=gamesdonequick&html5
But not on the site.

**Comment by night** [comment]
Twitch is already working on html5. Let them work on it....
