### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by XtrLoLz** [night/BetterTTV#1356]
Hi, I have seen that some channels have an exclamation command that shows you the date when you followed. I though it would be awesome if it was implemented in BTTV. This is already in the twitch API but It's annoying to check so I wanted to suggest a /followed command which shows the date as shown in this link for example.

https://api.twitch.tv/kraken/users/xtrlolz/follows/channels/summit1g 

"created_at":"2015-04-02T19:13:49+00:00

Thank you.

**Comment by EhsanKia** [comment]
Added, should be available soon.
