### ISSUE TITLE
Channel badges

### ISSUE THREAD

**Issue by waytoomuchfun** [night/BetterTTV#1362]
Hello Everyone:

    Hope all is well.

    Not seeing the individual channel badges while using BetterTTV.  See the MOD badges OK.

    Thanks for the much better Twitch experience by having the browser BetterTTV add-on enabled on both Chrome and FireFox.

     Great days wished to all.

             Bye for this one,

                                                Way

**Comment by EhsanKia** [comment]
Can you give specific channel where you're experiencing this issue, as well as screenshots with and without bttv?

**Comment by waytoomuchfun** [comment]
Hello Eshan:
    Gamer is: Pandagirl91
     Hope this helps.
     Bye again for now,
                                W.

		_____________________________

**Comment by EhsanKia** [comment]
What badge are you missing? That channel does not have a subscriber button, so she does not have any badges.

**Comment by waytoomuchfun** [comment]
Thanks Ehsan:
     Panda is using a third party subscriber service...  Appears there is no channel badge icon available, (as / like you wrote).  Maybe one day there will be a change to this no icon deal.. (Probably up to Twitch, like usual)... :-)
       Thanks again for your time, helpful information and very quick replies, much appreciated.
        Best rest of the day to you! 

        Till another time, thanks one more time,
                                Jim. 


		_____________________________
