### ISSUE TITLE
Scrollback chat amount does not apply to chat replay

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1364]
The "Set Scrollback chat amount" is really useful to decrease lag in my place, but for some reason, the amount I've set on a live chat, which works perfectly, does not work on chat replay, which causes my frame drops. Can you fix it to work on both cases (Live and replay chat)?

**Comment by night** [comment]
closing this since it cannot be fixed without modifying Twitch's logic, which we won't do.
