### ISSUE TITLE
Emote menu causes massive lag when you have lots of subs.

### ISSUE THREAD

**Issue by tecnobrat** [night/BetterTTV#1367]
When I load ANY stream the emote menu causes massive lag.

It also causes the same lag when you enable the emote menu.

You can see a video with complete details here: https://www.youtube.com/watch?v=AvgQ5KdujN0

**Comment by EhsanKia** [comment]
@cletusc needs to take a look at this, as the emote menu is maintained by him.
https://github.com/cletusc/Userscript--Twitch-Chat-Emotes

**Comment by tecnobrat** [comment]
I opened an issue on that repo with https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/issues/93
