### ISSUE TITLE
Support for emoji images (like Twitter, etc.)

### ISSUE THREAD

**Issue by LepkoQQ** [night/BetterTTV#1368]
I made a little script that uses [twitter/twemoji](https://github.com/twitter/twemoji) to replace unicode emoji characters in chat with images.
There are also other emoji sets like [Ranks/emojione](https://github.com/Ranks/emojione) (both are available via CDN)

![screenshot 2016-07-12 01 58 25](https://cloud.githubusercontent.com/assets/2662937/16750742/43ee9692-47d4-11e6-9e51-622f2490d2ed.png)

I think this could be a feature that would be useful in bttv and I wanted to gauge interest before writing a pull request.

Cheers :)

**Comment by night** [comment]
I have considered adding emoji myself, but we're open to pull requests if you'd like to contribute one :)
