### ISSUE TITLE
Allow us to view blacklisted words

### ISSUE THREAD

**Issue by UnfulfilledDesires** [night/BetterTTV#1369]
Give us the ability to view blacklisted words for specific channels.

**Comment by EhsanKia** [comment]
As far as I know Twitch doesn't have any way of accessing those.
They are set by the channel owner, and the "censoring" happens
on Twitch backend, so the user never knows what's blacklisted until
they actually try writing that word.

It's probably a good thing too, some streamers blacklist their personal
information preemptively, and being able to see their blacklist could be very bad.
