### ISSUE TITLE
[Feature Request] Expand Game Following

### ISSUE THREAD

**Issue by DennisMellegaard** [night/BetterTTV#1373]
Following a game on Twitch isn't really that feature rich and even lackluster in some regards. This feature seems to be there to find new streamers to follow. But now it just acts like a bookmark. As of now, in your following directory, it only displays the name, cover art and number of viewers. 

What would be great is to show a list of the top 3 streams with information like title, tags(if creative) and number of viewers. Probably best to do this on hover, so we don't do multiple requests on page load.

![image](https://cloud.githubusercontent.com/assets/6856243/16880050/a89abb7a-4ab3-11e6-820e-84a7612359d0.png)

**Comment by night** [comment]
I don't personally think this is a more usable approach to followed games, and to be quite honest, the followed games feature was a flop for Twitch and I'm surprised they haven't removed it (they deprioritized it in the directory in all places it used to exist prominently).
