### ISSUE TITLE
Remove all pinned highlights with one click/button

### ISSUE THREAD

**Issue by mihedas** [night/BetterTTV#1379]
Hello,
sometimes when removing pinned highlights I accidentally ban/timeout a user because the X is right above the mod buttons. Also it would be more convenient to remove 10 highlights with just one click.
Also the X could be on the right side to solve the first mentioned problem.

Thanks

**Comment by night** [comment]
Enable "Timeout Pinned Highlights" in the BetterTTV settings as an alternative.

**Comment by EhsanKia** [comment]
I do agree that a "Remove all" seems more sensible that one by one. I don't see a case where you'd want to dismiss a single one and leave the rest? Maybe.
