### ISSUE TITLE
Badge System.

### ISSUE THREAD

**Issue by Effectstudios** [night/BetterTTV#1380]
I find that a lot of people use custom bots or something like the RevloBot "bot" badge just hasn't been implemented yet. I think having a client side feature where you could right click on the profile in chat and set to "bot". I know it would be nice for me.

**Comment by EhsanKia** [comment]
Channels can set 1-2 accounts as "bot" already.
Simply tell the channel owner to go here:
https://manage.betterttv.net/channel

Doesn't really make sense to have every single user manually set a bot badge.
