### ISSUE TITLE
Request for a new feature

### ISSUE THREAD

**Issue by Vampichu** [night/BetterTTV#1381]
Hi, first of all I wanted to tell you, you are doing a great job with BTTV. I really really love it and it makes everything a lot easier and cooler to look at. 
You just added those emojis in Twitch chats and I understand, that a lot of people will love these but for me it doesn't belong there and makes chat conversations a little bit exhausting. I wouldnt request to remove them, but it would be nice if users had the possibility to decide on their own which Emotes they want to be seen and which not. 
Yeah, maybe thats a little bit too special for an request here. I would totaly understand if it wouldnt come up. I just wanted to put the idea here because I know a lot of people who see this in a simliar way. Hope I could make up my point in a good way, my english isn't that good.
But you make a good job with BetterTwitchTV anyway. Greetings, Vampichu

**Comment by EhsanKia** [comment]
That is indeed a bit too much for a setting. We try to keep a good balance between customizability and ease of use, and features like this very quickly start bugging down the extension. By themselves, these features may seem harmless, but if we were to add every single one of these small requests, the extension would very quickly become a huge mess.

Sorry, and thank you for the feedback!
