### ISSUE TITLE
Whisper Desktop Notification

### ISSUE THREAD

**Issue by leannleann** [night/BetterTTV#1382]
I know there's an option to have a sound play when you get a whisper, but what about a desktop notification? Something like what you get when someone mentions you in chat, with a preview of the message.

**Comment by night** [comment]
If you enable Desktop Notifications in the settings you get them for whispers already..

**Comment by leannleann** [comment]
Oh. Well then it must be a bug, because I've had them enabled this whole time and never got any for whispers. I only seem to get them for when channels are live or when I'm mentioned in chat.

**Comment by EhsanKia** [comment]
It is indeed a bug, it only works for chat whispers.
