### ISSUE TITLE
Hosted channels using wrong channel name

### ISSUE THREAD

**Issue by archer77** [night/BetterTTV#1383]
Viewing a hosted channel after viewing a different hosted channel, causes the previously viewed channel's "view info" button show, instead of the correct one.
I attached an image below. I previously viewed richard_hammer then I viewed Iamspoon's hosted channel.
I don't know if this is just a twitch bug or if this is even replicable. 
![image](https://cloud.githubusercontent.com/assets/3753546/16937440/c00276e6-4d23-11e6-9ace-db0dde07e982.png)

**Comment by EhsanKia** [comment]
I can't replicate it, and it also looks like it's a Twitch bug as we don't touch that stuff in BTTV.

**Comment by night** [comment]
Definitely would be a Twitch bug..
