### ISSUE TITLE
Allow new "BTTV Emoji" feature to be turned off

### ISSUE THREAD

**Issue by ChaosCom** [night/BetterTTV#1384]
As the title says, allow turning off this non-sensical feature. Not only is it highly questionable as to why BTTV users would unanimously prefer an image like 
![](https://twemoji.maxcdn.com/2/72x72/2122.png) 
over a simple ™ 

but the feature itself is _obviously untested_, given how a _dark colored_ ![](https://twemoji.maxcdn.com/2/72x72/2122.png) image replacement on a "Dark Mode" background looks.

**Comment by night** [comment]
What's really non-sensical is why you thought making a rude post on here would be beneficial in resolving a bug.
