### ISSUE TITLE
Some messages with blacklisted emoji won't appear at all.

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#1385]
![](https://i.gyazo.com/d6a63f751d4e06f5118d8a4bbe9ddb49.png)

This particular emoji example is "🖕" (U+1F595) known as ["reversed hand with middle finger extended"](https://codepoints.net/U+1F595) and is in the [emoji blacklist.](https://github.com/night/BetterTTV/blob/fafc487194ac609cdab6c7380f9678217fc1146c/src/js/helpers/emoji-blacklist.json#L39) If the message comprises solely of this emoji, the message is just dropped and anyone with BTTV just won't see this message. (Like a broadcaster, moderator, etc.)

Another example:

![](https://i.gyazo.com/49dfde972d096b2fd97b2dad8e6f3987.png)
 1. All of the emoji in the blacklist with spaces in between
 1. All of the emoji but the index with the keycap asterisk with spaces in between
 1. All of the emoji but the index with the keycap asterisk without spaces in between

**Comment by AlcaDesign** [comment]
Also blacklisted single letters prevent flag emojis like "🇺🇸" (regional indicator symbol letters)

**Comment by NBruderman** [comment]
For the single letter ban, it cannot be lifted due Twitch emote policy (No single letter emotes). unless there is a workaround possibility for that, the flags will stay out :/ However, I cannot answer about the possibilites of it happening, that's @night and @EhsanKia field.

**Comment by AlcaDesign** [comment]
It must at least allow showing the native emoji character instead of nothing at all. It's not an image, it's a symbol. If Twitch wants to filter the emoji symbol itself, then it should but it isn't.

**Comment by EhsanKia** [comment]
Hmm yeah i don't think filtering native emoji's isn't really our job? Maybe we should just ignore those instead of hiding them?

**Comment by night** [comment]
It was a quick fix due to the spam. Anyone is welcome to contribute a pull request improving filtering.
