### ISSUE TITLE
[Feature Request] Pause Chat on Hover

### ISSUE THREAD

**Issue by WatsonB36** [night/BetterTTV#1391]
Being able to stop chat from scrolling while hovering over it would be nice for moderation, especially in fast moving channels.

**Comment by Aaron128l** [comment]
You can already scroll up to pause chat.

**Comment by WatsonB36** [comment]
When chat is moving fast and you scroll up it just jumps back down to the bottom. Making it even harder to find that message you were looking for.

**Comment by night** [comment]
If you need better moderation, right click on names instead to quickly timeout with precision.
