### ISSUE TITLE
Moderation buttons in front of name option?

### ISSUE THREAD

**Issue by StefanJanssen95** [night/BetterTTV#1394]
Its a long list of options but Ive checked it four times now, if its missing Im sorry.

This plugin adds the ban and timeout buttons in front of the users name. I know myself well enough that I will accidentally ban or timeout people. An option to remove these buttons would be great.

**Comment by teak** [comment]
This is not added by BTTV. Those buttons are a Twitch feature. You can toggle them off in the Twitch chat settings. (The cog button under chat.)
