### ISSUE TITLE
Highlight keywords cannot be imported/exported

### ISSUE THREAD

**Issue by matt3541** [night/BetterTTV#1395]
Exporting the settings to a file works fine but the "bttv_nicknames.backup" file is blank and doesn't work properly

**Comment by voloshink** [comment]
What do you mean by doesn't work properly, do you have any nicknames set?

**Comment by matt3541** [comment]
I have multiple nicknames set and exporting them just produces a file that contains "{}" with no parameters

**Comment by voloshink** [comment]
And are the highlight keywords exporting fine?

**Comment by matt3541** [comment]
I'm sorry I don't think I completely understand. In the chat settings when I click "set highlight keywords" is that the same thing as nicknames? if not how do I edit nicknames? I usually set several variations of my username in the "highlight keywords" so that I see them when people type them, and I assumed exporting "nicknames" in the settings menu would be those keywords.

**Comment by voloshink** [comment]
highlights are highlights and nicknames are nicknames. Highlights are exported with the rest of the settings, you can set nicknames by clicking on a person in chat and clicking the pencil next to their name in the modcard

**Comment by matt3541** [comment]
Ah, thank you for the clarification. Well, in any case, my highlight keywords do *not* appear to import with the rest of my settings, so that still seems to be an issue.

**Comment by night** [comment]
can you post your settings backup file contents to https://gist.github.com and link it here
