### ISSUE TITLE
Auto-Pause Broadcast | Compact Twitch View - BetterTTV Suggestions

### ISSUE THREAD

**Issue by travisnightwizard101** [night/BetterTTV#1400]
(Introduction)
Hello, I am Travis_Night___Wizard101 from Twitch, and I am new to GitHub.
I was hoping to give some Feature Requests for BetterTTV.
[ If this post is against any rules for this GitHub; I would like to know. ]

Name | Description | Examples
-------|--------------|-----------
Auto-Pause Broadcast | Upon joining a user's channel, that channel's broadcast will automatically be paused. | None
Compact Twitch View | Hides all videos, images, and makes large text smaller; however, advertising videos or images will only be shrunk. | Ex: broadcast previews, followed channels' icons, and other images/videos.

**Comment by night** [comment]
Please make two separate issues, one for each feature request. An introduction is not necessary. Just state what the feature description is, why it would be useful, and why you think people would use it.

Cheers
