### ISSUE TITLE
Emote menu overhaul

### ISSUE THREAD

**Issue by zdrijne** [night/BetterTTV#1403]
2 things: 

-Right now there are two emote menus: http://i.imgur.com/ot546lV.png. Please leave just one. I think the menu added by betterttv (square button with smiley face) is better integrated, so I say just leave that one. Although sub emotes from twitches emote menu are nice. Maybe a shrinkable sub emotes tab could be added to compensate. 

**JK apparently the second part was already implemented.** 
_-Give an ability to hide emotes from emote menu. There's ALOT of crap emotes that nobody ever uses and all they do is clutter up the emote menu. I'd happily hide the ones I don't like and only see them when someone (brave) dares to post them in chat._

**Comment by cletusc** [comment]
1. First one is up to BetterTTV to decide on.
2. The second one (hiding emotes) is already possible. Click the cog/settings on the emote menu, then hide away!

**Comment by zdrijne** [comment]
> First one is up to BetterTTV to decide on.

Well ofcourse, I'm gest making a suggestion. 

> The second one (hiding emotes) is already possible. Click the cog/settings on the emote menu, then hide away!

Thanks for telling. Hopefully these are also registring in settings backup file.

**Comment by night** [comment]
We dont want to remove the old one because some people still use it, sorry.
