### ISSUE TITLE
grinning monkey

### ISSUE THREAD

**Issue by fadster** [night/BetterTTV#1404]
Some of the monkey emotes are missing. For example, :D should bring up the grinning monkey, but instead it shows a silly yellow face. Would it be possible to get the full set of monkeys as we had them on JTV?

**Comment by night** [comment]
We have the full set of monkey emotes, but override that particular emote. This matches the emotes set from BetterJTV years ago. It's non-toggleable, sorry.

**Comment by fadster** [comment]
So you don't really have the full set of monkey emotes. Personal preferences aside, if one opts to switch from the standard Twitch emotes to the monkey emotes, one expects to switch to the full set. If you won't provide an option, how about including it with a different trigger so both would be available. Perhaps :-D could display the grinning monkey. It is, after all, one of the cutest monkey emotes. For the small amount of work this represents, I'm sure you'd make a significant number of people very happy.

**Comment by fadster** [comment]
How about keeping this open as a request for enhancement?

**Comment by fadster** [comment]
How does one go about requesting additional custom emotes? Should I just fork my own branch? To be honest, I don't understand why you wouldn't want to have the full set of monkey emotes. I'm suggesting the grinning monkey as an addition, not a replacement for the current grinning emote.

**Comment by fadster** [comment]
How does one go about requesting additional custom emotes? Should I just fork my own branch? To be honest, I don't understand why you wouldn't want to have the full set of monkey emotes. After all, this is precisely what the label and description of the relevant setting claim to do:

JTV Monkey Emotes  —  BetterTTV replaces the robot emoticons with the old JTV monkey faces

That yellow emote is not a JTV monkey face! I'm suggesting an additional trigger for the monkey, not a replacement. Surely this isn't an unreasonable request.
