### ISSUE TITLE
Twitch info panels not adjusting to width - side panel

### ISSUE THREAD

**Issue by FutureNipples** [night/BetterTTV#1405]
When expanding the side panel on a Twitch user's page, the info panels do not properly adjust to the width of the inner page.

Testing this issue with BTTV disabled fixes the problem.

Google Chrome
Version 51.0.2704.103 m
Windows 10

![fmg info panels](https://cloud.githubusercontent.com/assets/8377122/17188425/3cbc657a-53fa-11e6-8af6-4444d5641cb4.PNG)
![fmg info panels expanded](https://cloud.githubusercontent.com/assets/8377122/17188428/3ed60744-53fa-11e6-98a1-254c702abe54.PNG)

**Comment by night** [comment]
Cannot reproduce.
