### ISSUE TITLE
Stream window disappears occasionally - Have to reload several times

### ISSUE THREAD

**Issue by Ree1981** [night/BetterTTV#1408]
Fairly often when I click open a stream the window will just be gone. I can hear sound, and occasionally the window appears for a fraction of a second, but I have to reload the window to get it to appear. 3-4 times just now.

Windows 7, Firefox 43.0.3.

**Comment by night** [comment]
This is an issue only on Firefox. You can use Chrome in the meantime.

**Comment by night** [comment]
This should be fixed now.
