### ISSUE TITLE
Filter Unicode Spam

### ISSUE THREAD

**Issue by MaPePeR** [night/betterttv#141]
Hide or decrease the font size of messages, that contain a lot of non-letter characters, which are used to create ascii "arts" in the chat.

**Comment by Naththo** [comment]
It should be easy enough to figure out if a message contains ASCII. But would we want it to ignore the message if it contains ASCII art or if is **only** ASCII.

**Comment by MaPePeR** [comment]
Maybe a configurable threshold would be the best option. If there is more than x % non readable characters: remove the message.

**Comment by Naththo** [comment]
How about we just have it so if more than half the message contains ASCII, ignore it?

I can work on this if @night is cool with this.

**Comment by vendethiel** [comment]
I think we already talked about this, and agreed that we didn't need unicode crap in general. so I think @night will be cool with this

**Comment by Naththo** [comment]
My first PR here. So I'm all up for criticism. @night

**Comment by metarmask** [comment]
If #267 was implemented one could do `/[^a-z]{9,}/i`
Wouldn't work if there were any a-z letters in the middle though.
