### ISSUE TITLE
Force HTML5?

### ISSUE THREAD

**Issue by chronaden** [night/BetterTTV#1415]
Now that Twitch has rolled out their HTML5 player this week, which is awesome. But the player will still default to Flash when available. I need to run flash in my browser, but don't want the player to use flash. I've tried blocking flash content for the Twitch site in Chrome, but it still want's to use flash when it's installed even when blocked. 
Would it be possible to have BetterTTV to _FORCE_ HTML5 instead of Flash even with flash installed?

**Comment by night** [comment]
There's already a beta toggle in the video player settings.
