### ISSUE TITLE
Super Mario Maker Level Submission falsely marked as spam

### ISSUE THREAD

**Issue by DerZerfetzer** [night/BetterTTV#1416]
If you post a lot of levels in twitch chats to submit them through the level submission bot, you become marked as spam and all your messages become marked as spam on all of twitch.

The Messages usually look like this:
!add 841A-0000-0279-B728
!submit E87D-0000-0276-7A7E
!smm B8DD-0000-0278-6897

I think it is 0-9 and A-F only and always of the form XXXX-XXXX-XXXX-XXXX

This is to interact with http://smmtool.net/ and https://warp.world/ level submission bots, which are basically in every super mario maker stream!

This only applies to super mario maker streams of course ;)
Maybe you could add this as exception to the spam detection!

**Comment by DerZerfetzer** [comment]
This is to interact with http://smmtool.net/ and https://warp.world/ level submission bots, which are basically in every super mario maker stream!

**Comment by night** [comment]
It sounds like you massively request the same level across multiple streams, which will get you flagged. Don't do that.
