### ISSUE TITLE
Callout Names on Twitch "@<name>" Using Arrow keys

### ISSUE THREAD

**Issue by BlackBirdet** [night/BetterTTV#1417]
Dear BetterTTV,

I very much like your chrome extension but there is one simple thing i would like to have embedded.

When i call a name on Twitch using "@<name>" a list of names pops up, i usually use the arrow keys up and down to choose the name i want. but with BTTV that feature is missing and instead uses the /linehistory command. I would like to use the arrow keys to scroll or go through the names in that list instead of having the arrow keys for linehistory, even though i tried turning the linehistory off but nothing has changed. I even checked the BTTV settings, chat settings, and searched through google if the option was available but no luck. :)

I hope my request was clear and not vague.
Thank you for your time. :)

BlackBird

**Comment by voloshink** [comment]
You should be able to use tab and shift+tab to cycle through the names

**Comment by BlackBirdet** [comment]
Thank you very much for your help :)
I still prefer the arrow keys though. but i guess i'll have to get used to the tab and shift+tab to cycle.

Thank you very much.

**Comment by voloshink** [comment]
Tab is generally what is used for the functionality, hence why it's usually referred to as "tab complete".
