### ISSUE TITLE
"Swag Tag"

### ISSUE THREAD

**Issue by MaxZamoraJ** [night/BetterTTV#142]
I'd like you too add a feature to remove the "BTTV swag tag" from people who have it. It's annoying and it hides their usernames, and makes them highlighted in chat which is not what I want.

**Comment by teak** [comment]
BTTV Swag Tags are grandfathered. We will not be adding features or changing them in any way.

**Comment by MaxZamoraJ** [comment]
What does it mean that they are grandfathered?

**Comment by night** [comment]
http://en.wikipedia.org/wiki/Grandfather_clause

**Comment by MaxZamoraJ** [comment]
Is there a way that I can edit the code myself to hide it? Or should I just do some CSS tweaking?

**Comment by vendethiel** [comment]
sure, it's in the code, you can remove them.

**Comment by MaxZamoraJ** [comment]
Ok thanks for your assistance vendethiel
