### ISSUE TITLE
Option to remove posts below channels

### ISSUE THREAD

**Issue by Slikrick** [night/BetterTTV#1422]
Posts take up quite a bit of space for being a feature not a lot of people enjoy and often times push the other info part of the channel page out and taking up a lot of [useless space](http://i.imgur.com/TorRhHR.png).

I think it looks good when you are able to [toggle between them](http://i.imgur.com/IrY51KD.png) which is shown below the stream, posts or info. This only happens when there isn't much room on the page, however.

a toggleable "hide posts" switch below the stream similar to what broadcasters see on their own page may be nice instead of cluttering the settings menu. 

![](http://i.imgur.com/WzzFOK4.png)

**Comment by EhsanKia** [comment]
Is this different from #1058?

**Comment by EhsanKia** [comment]
Looked a bit into ember code, doesn't seem very doable.

**Comment by Slikrick** [comment]
Yea, pretty much the same just with more ideas/info. Didn't notice the previous.
