### ISSUE TITLE
BUG REPORT UNUSABLE IF NOT FIXED

### ISSUE THREAD

**Issue by sleightology** [night/BetterTTV#1424]
if someone @'s me / mentions me in there message in chat it wont even show up in my chat at all and i dont know what to do i have redownloaded BTTV about 7 times changed all the settings and nothing works please fix i cant use BTTV till its fixed

**Comment by Slikrick** [comment]
click the cogwheel. Check the "Set Blacklist Keywords" box and make sure your name is not in there.

**Comment by sleightology** [comment]
how do i see which words i have blacklisted

**Comment by sleightology** [comment]
THANK YOU
