### ISSUE TITLE
Unable to blacklist certain new emotes

### ISSUE THREAD

**Issue by PandaShaft** [night/BetterTTV#1425]
I am currently unable to blacklist the phrases :joy:  :ok_hand:  :100: and probably a few others similar to these but I haven't checked. Please let me be able to blacklist them, the children of twitch bother me which is why I use this feature on twitch haha

**Comment by night** [comment]
They are emoji characters, so you have to blacklist the character itself, not the text-code-representation (like `:ok_hand:`)
