### ISSUE TITLE
Can't use up/down arrows to change selection of @user from drop down

### ISSUE THREAD

**Issue by MJLaukala** [night/BetterTTV#1427]

**Comment by night** [comment]
up and down are reserved for other keybinds. try tab and shift-tab.

**Comment by MJLaukala** [comment]
I realize that but the key binds they are used for is illogical and promotes spam. Further more, if the text is more than a single line, I can no longer use the up and down arrow to navigate my cursor. For the most part BetterTTV is great but these particular key binds being used breaks some pretty fundamental functionality.
