### ISSUE TITLE
Unable to Blacklist Numbers

### ISSUE THREAD

**Issue by Glodwran468** [night/BetterTTV#1429]
I've noticed that any word/name with a number in it is treated as if the numbers were not there in the blacklist feature. Also, just a straight number will be completely ignored. It'd be great if this functionality could be fixed.

**Comment by night** [comment]
Can you provide reproduction steps?

**Comment by Glodwran468** [comment]
For instance: If I were to type Kappa123 into the blacklist, it still shows any time someone types Kappa123, but does not show regular Kappa anymore. Or if I were to just type 123, it still shows any messages with 123 in them.

**Comment by night** [comment]
I cannot reproduce the issue, so your reproduction steps do not work.
