### ISSUE TITLE
Embedded Polling broken

### ISSUE THREAD

**Issue by Skydragonsz** [night/BetterTTV#1433]
When a http://www.strawpoll.me/ link is posted in chat, the popup appears but it doesn't allow to vote. I just says "Thanks"!

**Comment by EhsanKia** [comment]
Curse own strawpoll.me and they've "broken" the embedding on sites months ago. We've tried reaching them and they claimed they'd fix it "soon" but it's been months and still nothing. If I had to guess, they wanted to push their new Curse client which has embedded polling, but that's just a guess.

Unfortunately there's nothing we can do about it.

Also https://github.com/night/BetterTTV/issues/1085
