### ISSUE TITLE
twitch emotes not showing in rechat

### ISSUE THREAD

**Issue by src7G** [night/BetterTTV#1434]
BTTV emotes showing in chat replay (VODS) twitch emotes not(live stream working only vod chat doesnt).
See pic: http://imgur.com/a/hYjLW

Hover the twitch emotes point e.g. to https://static-cdn.jtvnw.net/emoticons/v1/null/1.0

**Comment by voloshink** [comment]
can't reproduce the bug, but i do see some errors on the page, will look into it once im home

**Comment by voloshink** [comment]
should be fixed now
