### ISSUE TITLE
Need BetterTTV for Microsoft Edge

### ISSUE THREAD

**Issue by YuriBoiko** [night/BetterTTV#1435]
We really need BetterTTV for Microsoft Edge. It is very simple to convert the already available extension for Chrome for Microsoft Edge. It took me 5 minutes with this converter: [https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb](https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb). Please convert and upload it to store.

**Comment by night** [comment]
We are still waiting on Microsoft's conversion tool to be released. It was released and then pulled.

**Comment by deathkneel** [comment]
The tool is released now. Please upload BTTV to the windows store.

**Comment by Nostro01** [comment]
According to this [FAQ](https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/), you have to submit a request to MS at the moment, if you want it listed in the store.

> For the Windows 10 Anniversary Update, we are intentionally starting with a small set of extensions. The list of extensions is locked - you can see the list [at our extensions page here](https://developer.microsoft.com/en-us/microsoft-edge/extensions/). We want to be mindful about what extensions are available on the platform and watch for telemetry and feedback and make sure the reliability, performance and functionality of the browser isn’t impacted by these new features. Extension developers can submit a request to [https://aka.ms/extension-request](https://aka.ms/extension-request) to be considered for a future update.

**Comment by jack775544** [comment]
Just to bring this topic up again, the edge conversion tool is out now, I put the Chrome extension through it on my machine and needed only a one line change to get it working (add an author to the manifest file). This was with no rigorous testing however but the functionality seemed to be fine from my quick inspection.

Any chance of having this issue looked at again?

**Comment by night** [comment]
https://github.com/night/BetterTTV/issues/1435#issuecomment-247057487 is relevant still

**Comment by superusercode** [comment]
@night Have you submitted a request?

**Comment by night** [comment]
Visit https://www.microsoft.com/en-us/store/p/betterttv/9nblggh51tbk to install BetterTTV for Edge.
