### ISSUE TITLE
Twitch Rules Embed being cleared by BTTV

### ISSUE THREAD

**Issue by desertpogona** [night/BetterTTV#1441]
Hello BTTV Devs! I am a moderator for a very large Twitch Channel, and our channel has recently been allowed to utilize a new feature for Twitch that displays an embed in the chat, which asks for the user to agree to a rules prompt before using the chatroom. 

From how I understand things, BTTV prevents this prompt from happening, and clears the rules embed from ever being shown. We would really appreciate it if there was a way this not to be removed, because it helps keep our twitch community guidelines understood and enforced.  

If you have any questions on what community this is for so that you may test it, please contact me privately. Thank you.

**Comment by RHudson94** [comment]
Yep, I have this issue as well.

**Comment by voloshink** [comment]
Link the channel so we can look at it

**Comment by desertpogona** [comment]
@voloshink 
The community is for www.twitch.tv/vinesauce
The prompt that is supposed to be displayed is in the screenshot below.
http://prntscr.com/c3qvm6

**Comment by wallrik** [comment]
This works for me with BTTV unless it's already fixed?
But it needs looking at for the dark theme. [[1]](https://cloud.githubusercontent.com/assets/10890923/17649663/ceb68f02-623a-11e6-8a16-d9cee4b68942.jpg)

**Comment by EhsanKia** [comment]
When I checked a few days ago it was embedded in chat, and it still seems to be for me. Also, I only get it when I'm not logged in. As soon as I log in I cannot get it to appear no matter what. Tried in 4 different browsers.

**Comment by night** [comment]
Twitch is experimenting with rules. We will add support for it when/if it is released or we are provided with information on it.
