### ISSUE TITLE
Can't see normal Twitch emotes in chat replay

### ISSUE THREAD

**Issue by Tharnite** [night/BetterTTV#1442]
Whenever someone uses a normal emote in chat replay it shows up as text with a missing icon. When I remove the BetterTTV extention it goes back to normal.

**Comment by NBruderman** [comment]
I cannot reproduce the bug... It works completly normal, both on live stream and VOD... Maybe it's a problem with your browser? Have you tried to delete cookies and data?

**Comment by Tharnite** [comment]
thank you it works now
