### ISSUE TITLE
Can't see BTTV emotes anymore 

### ISSUE THREAD

**Issue by kite260** [night/BetterTTV#1447]
My BTTV Emotes are on I see the face in under the chat box and a friend shares here emotes with me but I no longer see the BTTV emotes tab in the emote box. Its shows Global but then goes right to the people I'm subbed to. In the file you can see my BetterTTV emotes are on but its not showing. But I can say that if I type it in chat it will pop up but my problem is I can't know or remember all the emotes.
![bttvemotes](https://cloud.githubusercontent.com/assets/21012033/17644911/6ed3d6bc-6163-11e6-814d-f8d8b278397d.png)

**Comment by night** [comment]
I cannot reproduce this issue. If you're still having issues, please reply with reproduction steps so we can reproduce the problem.

**Comment by kite260** [comment]
Thank you I fixed it buy editing my chrome script.
