### ISSUE TITLE
[enhancement] Allow resizing chat narrower than normal

### ISSUE THREAD

**Issue by bootmii** [night/BetterTTV#1449]
In theater mode, the video is letterboxed. This is because 320 pixels for chat is a lot of space. FFZ allows the user to resize the chat in a settings window down to 250 pixels, and this would have worked great if there weren't glaring incompatibilities like no way to access BTTV settings when used with FFZ or that width setting itself being incompatible with BTTV.

**Comment by michalpawl** [comment]
I too would like to be able to narrow the chat some more. Earlier I used Stylish to do that but BTTV overrides it.

**Comment by night** [comment]
The chat does not look good when less than Twitch's default, so we are not interested in supporting that, sorry.
