### ISSUE TITLE
Something isn't right 

### ISSUE THREAD

**Issue by ExtremeMortal** [night/BetterTTV#1451]
The join discord isn't working for me. It just shows blank

**Comment by notdom** [comment]
1. You do realize this repo is for BetterTTV and not Discord issues...? (Unless there is some feature that integrates BTTV/Discord that I haven't seen. If so, ignore my ignorance.)

2. Even in the event that you were to receive Discord support here, you didn't supply much info to be able to pinpoint the problem and therefore, not much can be done to solve the problem.

**Comment by voloshink** [comment]
Discord and BetterTTV do have an integration, but I agree on not giving us much information to reproduce the bug.

**Comment by night** [comment]
It works fine here.
