### ISSUE TITLE
Font changing

### ISSUE THREAD

**Issue by FuzeDzn** [night/BetterTTV#1455]
Originally my font on twitch was Helvetica. It was unclear if this was enforced by BTTV or default by twitch. However recently the default font has switched to Helvetica Neue which, as anyone who knows the Helvetica family will agree with. It doesn't look as nice and is a much smaller font to read overall.

Is this change in font being caused by BTTV, Twitch or something else? If its something else, could BTTV have a font selection so I can enforce Helvetica.

Helvetica Neue:
![neue](https://cloud.githubusercontent.com/assets/17186983/17713924/4f324caa-63f5-11e6-8a41-be2408eaeec3.png)
Helvetica:
![helevtica](https://cloud.githubusercontent.com/assets/17186983/17713925/5253195a-63f5-11e6-9e81-4493d148f3ef.png)

**Comment by Stoupedog** [comment]
The default font set by Twitch currently is Helvetica Neue followed by Helvetica if Neue isn't available. 

You could change this using an existing extension such as [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) for Chrome to apply custom css to the page and setting the body font to Helvetica. ([step-by-step](http://i.imgur.com/818MQwi.gifv))
<br><br>
> could BTTV have a font selection so I can enforce Helvetica.

See #57

**Comment by FuzeDzn** [comment]
Ahhh that makes sense now... I installed Neue whilst trying out new fonts for my twitch bot programme and I guess I didn't associate the installation of neue with the change on twitch.

Thanks for that css too though, I'll have to try that.
