### ISSUE TITLE
Directory Preview

### ISSUE THREAD

**Issue by Baaliefiy** [night/BetterTTV#1456]
I noticed that the directory preview had started working again, but I'm getting an issue that when Flash Player is enabled then it won't work but if I disable Flash Player it then it does.

Adobe Flash Player Version
Version: 22.0.0.209
Shockwave Flash 22.0 r0

**Comment by EhsanKia** [comment]
It's not possible to use Directory Preview with Flash unfortunately. There used to be a way to force HTML5 for the preview way back, but that method was disabled a few months back, basically killing the feature. We still kept it (although should've hidden the setting), knowing Twitch would eventually bring back HTML5 player, and now that it's back, it works again. But yes, there is no way around this, we just have to wait until Flash is fully replaced.
