### ISSUE TITLE
bttv emote button

### ISSUE THREAD

**Issue by drunktotems** [night/BetterTTV#1461]
The BTTV emote button wont show for me. I've tried reinstalling BTTV, refreshing the page countless times, reinstalling chrome, tried using different twitch accounts nothings worked. I have the BTTV emote on and BTTV gifs on but it still wont show

**Comment by cletusc** [comment]
Is the "Emote Menu" option on?

**Comment by drunktotems** [comment]
Thank you for telling me I'm retarded :)
