### ISSUE TITLE
Show Emoticon on Tab Autocomplete

### ISSUE THREAD

**Issue by ksthiele** [night/betterttv#1463]
It would be nice if there was a preview of an emoticon when autocomplete an emoticon with tab.

like typing "KAp" -> Tab -> Kappa       (kappa-emoticon)

**Comment by AlcaDesign** [comment]
Here's a mock-up:
![22px](https://cloud.githubusercontent.com/assets/7132646/18222373/73624c1a-715b-11e6-9be1-4b75cbca5293.png)

Without adjusting the height of the lines, the images had to scale down and it seems a little squished. The lines are 24px and the images are 22px to have at least some padding.

The emotes at different sizes without changing the height of the container:

| Pixels | Image |
| ----- | ------ |
| 24 | ![image](https://cloud.githubusercontent.com/assets/7132646/18222532/eaab1df2-715f-11e6-88fe-d7375d552b2a.png) |
| 22 | ![22px](https://cloud.githubusercontent.com/assets/7132646/18222373/73624c1a-715b-11e6-9be1-4b75cbca5293.png) |
| 20 | ![20px](https://cloud.githubusercontent.com/assets/7132646/18222468/fdae4b9c-715d-11e6-8eb4-53e212fcfe38.png) |
| 18 | ![18px](https://cloud.githubusercontent.com/assets/7132646/18222494/81310bc6-715e-11e6-9d7f-00e9c6899bc2.png) |
| 16 | ![16px](https://cloud.githubusercontent.com/assets/7132646/18222523/9e21ed58-715f-11e6-8b73-92cc13e46736.png) |
| 14 | ![14px](https://cloud.githubusercontent.com/assets/7132646/18222558/88d11a4a-7160-11e6-8bb8-da18bdf52d33.png) |

**Comment by night** [comment]
We take pull requests :)

**Comment by ksthiele** [comment]
Maybe this opportunity could be taken and render the emoticon when it's entered in the text field

**Comment by ksthiele** [comment]
Ok, I thought a little bit more about it, can you also show the badges of users? like mods, subscribers, staff, global moderators, admins and streamer etc?

**Comment by night** [comment]
We added this in a recent update!
