### ISSUE TITLE
Idea for a neat feature

### ISSUE THREAD

**Issue by Nessmy** [night/BetterTTV#1465]
It would be great to have a feature that automatically redirect twitch.tv to https://www.twitch.tv/directory/following/live. So when you enter twitch.tv in your browser, you are automatically redirected to your following page. No one watches the default twitch.tv page anyways. 

It is also annoying to always have to click "following" in the default twitch.tv homepage.

**Comment by cletusc** [comment]
Is bookmarking the following or live page not possible? I use the bookmark often enough that even typing "twitch.tv" my browser automatically suggests the following page.

**Comment by night** [comment]
Use a bookmark in your browser.
