### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by RelicOrigins** [night/BetterTTV#1468]
I'm not sure if anyone suggested this but I really enjoy the translate feature as it allows me to interact with streamers/ Chat from other languages,  but dislike I have to wait 5 minutes  to translate each message is there anyway you can allow unlimited translations. 

I'm interested to see what the community has to offer on this idea as well so I look forward to hearing everyone's feedback. :)

Take Care and Great Plugin 

Relic

**Comment by voloshink** [comment]
The limit is there because these translation requests cost money
