### ISSUE TITLE
Ablity to display names only in English alphabet. Also BTTV not displaying the original account names.

### ISSUE THREAD

**Issue by notabot33** [night/BetterTTV#1472]
https://blog.twitch.tv/localized-display-names-e00ee8d3250a#.b66oqebrw

The new name feature doesn't display the original account name in BTTV making chatting and moderating more difficult.
Also the way it is currently implemented in normal twitch feels too cluttered with having both names displayed next to each other, it would be nice to have the option to choose to display either english only, non-english only or possibly both. 

![pimbiiq 1](https://cloud.githubusercontent.com/assets/20174691/17930709/85808b90-69ff-11e6-9991-560f8eb1256d.png)

**Comment by night** [comment]
You can now click on names in chat to see their real name.
