### ISSUE TITLE
Missing Bot Tags

### ISSUE THREAD

**Issue by Aaron128l** [night/BetterTTV#1475]
Recently there are no Bot tags being displayed for both the default list and channel specific bots. 

![65rolmd](https://cloud.githubusercontent.com/assets/12077192/17957299/c2163516-6a4d-11e6-9508-6171e77d4249.png)

**Comment by AlcaDesign** [comment]
Sometimes the bot badge will toggle between messages.

![image](https://cloud.githubusercontent.com/assets/7132646/17958778/d418229c-6a61-11e6-880e-c91dc415958d.png)

**Comment by night** [comment]
Fixed by a4adb71c03b81eff2caef005f640326a6ed0fdf0

**Comment by thinkpad4** [comment]
Still happening.  Nightbot is showing as mod not BOT
