### ISSUE TITLE
Personal emotes not available in stream

### ISSUE THREAD

**Issue by Pepperpotty** [night/BetterTTV#1477]
Myself and another noticed today that our personal emotes from BTTV pro aren't available to use in stream.

**Comment by voloshink** [comment]
As in, you are not able to use your personal emotes in a particular stream?

**Comment by Pepperpotty** [comment]
Yes, in any stream. They are not there in the bttv emote menu and I can't use them. The same for another user I spoke to too.

**Comment by voloshink** [comment]
what's your twitch username

**Comment by Pepperpotty** [comment]
Pepperpotty

**Comment by Slikrick** [comment]
See if this occurring, i believe it should be fixed now.

**Comment by Pepperpotty** [comment]
Yes it is fixed now! Thanks!
