### ISSUE TITLE
Robot Emoticons bug

### ISSUE THREAD

**Issue by Specx** [night/BetterTTV#148]
"Robot Emoticons  —  BetterTTV replaces the robot emoticons with the old JTV monkey faces by default" 

This option seems to have backwards controls. When it's turned off the JTV Monkey emotes are enabled and when you turn it on, it defaults back to the twitch robot emotes..

**Comment by night** [comment]
If you turn on Robot Emoticons, it shows robot emoticons.
If you turn off Robot Emoticons, it shows the old JTV monkey faces.

**Comment by vendethiel** [comment]
I'll admit the phrasing is weird and confused me as well.
