### ISSUE TITLE
Emote-Autocomplete based on usage

### ISSUE THREAD

**Issue by Totalschaden1997** [night/betterttv#1480]
So I use the Tab autocomplete for almost all the emotes but every time i try to do a "panicbasket" I have to write at least "panicb" to only use a single TAB and not have to look it up in the list, even tho I never used the "panicvis" on purpose. 
Same with "mcatDance" and "mcatDab".
That's why I'd love to see autocomplete prioritize emotes (maybe even user names?) based on the amount they're being used.

Thanks :3

**Comment by night** [comment]
Thanks for the request. This is actually a feature of our emote menu now. If you open the emote menu via hotkey and press enter (or select an emote via arrow key), you can quickly choose your frequent/favorite emotes.
