### ISSUE TITLE
Navigating Completion Tooltip with arrow keys does not work

### ISSUE THREAD

**Issue by serg06** [night/BetterTTV#1481]
This has happened to me every time I've tried to use BTTV over the past year:

When multiple options appear when typing @someone's_name in Completion Tooltip, I can't navigate completions using arrow keys. When I press down to go to the next one, the tooltip disappears and reappears with the same selection.

Not only that, but I don't have the option to use Twitch's default auto-completion, which does not have this issue.

Chrome version 52.0.2743.116 m.

**Comment by Stoupedog** [comment]
This is because the arrow keys are reserved for other keybinds, you can use Tab and Shift+Tab to cycle through users/emotes. (See #1417 + #1427)
