### ISSUE TITLE
Chat just "disappears" (doesn't appear)

### ISSUE THREAD

**Issue by Leifman27** [night/BetterTTV#1484]
Well this is awkward... and literally started today (yesterday or like for years i have never encountered this or anything similar to it)
basically when i open a stream (with bttv on obviously) the chat does connect or appears to, however i literally see an empty gray box (because of the dark bttv option) and literally i can't see anyone type or if i type something myself, it is completely blank and when i type something it doesn't appear.
the even more odd thing is that people appear to do see what i type, only myself not being able to see anything written in chat or that i write myself. even doing /mods etc' dont appear for me, but i appear to be connected?
it is 100% a new bttv bug as if i open the same twitch channel incognito (without bttv loaded) chat seems fine.
beats me how it came to be but it is super weird lol

**Comment by Leifman27** [comment]
Here is a picture of how it looks for me : http://i.imgur.com/rwqsGP0.jpg

**Comment by Leifman27** [comment]
also important to note it only happens to me on chrome (however i am using an older chrome version)

**Comment by EhsanKia** [comment]
Your chrome is over 2 years old. We unfortunately don't support old versions of browsers. Is there any reason you're using such an outdated version? You do realize that it's a huge security risk and there are critical security update you are missing that can easily get you hacked?

**Comment by Leifman27** [comment]
yep, i am on windows xp (yes that old operating system that is probably "out of date" as well)
and with chrome there is a way to make this build i am using to use hardware acceleration (which is officialy not supported in windows xp by chrome) which makes a big difference (on newer builds/current chrome its not possible)
also it worked fine till yesterday, hopefully its just some bug that will sort itself out.
and lecturing me about "getting hacked" or security risks is honestly irrelevant. i've been around for a long time, and a strong believer in "if you had a good av/firewall and know every single process that is running on ur machine and its rights then ur good" and i can back it up by never having a single issue since when windows xp officialy released.

**Comment by night** [comment]
To be fair I think this is the bug from a while back where chat stops displaying, but now it's happening when you join a chat. I haven't had time to look into it, but this happened to me yesterday.

**Comment by Leifman27** [comment]
i remember it happened once in a full moon way back sometimes.. but it was never a "constant thing" as now literally no matter how many times i open a channel and which, every single time its like it just doesnt display the chat or what i type to me. while i am actually able to type and other ppl to see what i type.
its just too weird, and now seems to be "global" and "constant" for whatever reason

**Comment by Leifman27** [comment]
night, not sure if this helps but i noticed something regarding this bug:
it seem's then when i first open a tab and load some stream, because technically "the chat" usually loads first (before the video buffers/loads) i do see the chat load for a brief second and some msgs. but the second that the video starts loading/buffers the bug occurs and everything disappears

**Comment by night** [comment]
ah, so the issue is what ehsan said. It's because your Chrome is outdated. Object.assign is only available as of Chrome 45, which is over a year ago. If you're on Chrome 36, you should consider upgrading to Windows 10 to get newer versions of Chrome.

**Comment by Leifman27** [comment]
but it worked fine till yesterday :( damn. was hoping whatever was changed is possible to still be adjusted. 
guess ill have to deal without bttv or somehow load the chat via firefox and use it chatless on chrome.

**Comment by thinkpad4** [comment]
Leifman27, you can use SlimJet, just Google Slimjet, It is built on Chromium and they have tweaked it to work for the time being on XP still. Version 11.0.5.0 supports XP but Version 10.0.8.0 is more stable on XP.   Version 10 is built on Chromium 50 while Version 11 is built on Chromium 51.

**Comment by EhsanKia** [comment]
I completely agree about the best AV being "common sense", and I'm entirely with you that if you are smart and safe you will not get infected, but I completely disagree with your conclusion. Keeping your software up to date **is** part of being smart. You are only considering one vector of attack which is running bad executable, but you need to realize that your browser itself, which looks like a normal safe process, could be an attack vector. As for saying "I've never had a problem", a good hacker will not let you know that they stole your information, and just because it hasn't happened yet doesn't mean you shouldn't care. 

But anyway, you are right than it's not our job to lecture you on that, so feel free to do what you like, but as developers we are also not required to try to support old outdated browsers with limited functionalities.

**Comment by Leifman27** [comment]
EhsanKia, considering this happened over-night and that the chat literally seems to load but just "doesnt appear to me" after years of using this "out-dated browser" that night seemed to think was "not supported" not ago... i cam in here to maybe find out if there was some daily update/anything that might have caused it.
i have no idea what kind of change on bttv side caused this or made it happen, for all i know it was a bug that could have been an easy fix to get my version of chrome to not have the issue as it never had before...
i mean, thats the purpose of reporting a bug is it not? regardless of what "you are using" and rather that its a bug that regards bttv itself.
if you don't care too much about it because of my version of chrome or w/e its up to you, i wasn't demanding you to fix it or pressuring you to lol, its your choice. only sucks as i had hoped it wouldn't be a big thing and you would care enough to fix it.
it's fine tho, like i said ill find a workaround, and load the chat via firefox popup if necessary.
and thinkpad4, it is not about "not being able to install the latest chrome version" as it is possible for me on xp.. that was never the issue.
i just don't want to and choose not to be cause the latest chrome version is not able to "hack/force" to enable hardware acceleration on windows xp which i am able to using my current version.
chrome has never officially supported hardware acceleration on windows xp, and being able to figure out how to enforce it on my current version is a much more important thing to me than having twitch chat load up/work.

**Comment by night** [comment]
We only support the latest version of browsers, sorry. We are not going to be kept behind by supporting browsers which do not support new technologies.

**Comment by Leifman27** [comment]
i guess just as you said, and i hold no grudges and thanks for all you do anyways. for now ill just mix up chatbot from firefox and use chrome as i used to till today with bttv.

**Comment by Leifman27** [comment]
IT'S WORKING AGAIN :+1: 
Hallelujah! guess i got lucky. 
chat works again on my beautiful old chrome version for whatever reason (i swear a few hours ago i checked and it didn't work)

**Comment by EhsanKia** [comment]
Just to be clear, what happened is that we used a utility function that was only added in newer version of Chrome. This is why it "died overnight". The "solution" for you would've been to not use that function, which sometimes is just not possible, or a huge pain in the ass. That's why we generally say that we don't support old versions. If it works, good, if it doesn't, unless you want to code a version that does work yourself, we aren't going to go out of our way to support every old version. Hope this makes what happened clearer.

**Comment by Leifman27** [comment]
Gotcha, and i do respect the work you put in bttv and everything you do, really.
I am just super happy that even after you pretty much left me with a feeling that i should get used to chat never appearing/loading again (and to be honest i already came to terms with it and already found a solution for chat alone) It actually got fixed/came back.
I'm just happy its back to the usual self and that's all there is to it :)
