### ISSUE TITLE
Chat stopped working

### ISSUE THREAD

**Issue by Toxilisk** [night/BetterTTV#1486]
With BetterTTV from this moment i cant chat with others and also i dont see any messages from users. Can you guys fix this?

**Comment by voloshink** [comment]
Not really, unless you give us more information about your platform and the issue.

**Comment by Toxilisk** [comment]
![0b790330b889fa7961419a4635b8c971](https://cloud.githubusercontent.com/assets/21314493/18058687/2cc4ba6c-6e1e-11e6-90d5-f567e297870c.png)
There's problem. I just cant even see chat. Im using Windows 7 (64bit)

**Comment by voloshink** [comment]
Any other extensions you have installed?

**Comment by Toxilisk** [comment]
https everywhere, adblock, frigate cdn and betterttv. That's all

**Comment by voloshink** [comment]
have you tried seeing if it works when you disable the other extensions

**Comment by Toxilisk** [comment]
Yep, i still cant see chat

**Comment by voloshink** [comment]
any errors relating to bttv in the console?

**Comment by Toxilisk** [comment]
console? where can i find it?

**Comment by voloshink** [comment]
Ctrl + Shift + J

**Comment by Toxilisk** [comment]
![123](https://cloud.githubusercontent.com/assets/21314493/18059389/7370b116-6e21-11e6-8037-b19300def386.png)
There's only one error i found

**Comment by Toxilisk** [comment]
Also without betterttv channel's name written in small letters. Can it be a problem?
![without](https://cloud.githubusercontent.com/assets/21314493/18059495/d8861668-6e21-11e6-9083-96e5e8fe206a.png)
![ttv](https://cloud.githubusercontent.com/assets/21314493/18059498/d9cf11c8-6e21-11e6-8109-d0411c18a989.png)

**Comment by night** [comment]
Upgrade your browser. It's too old.
