### ISSUE TITLE
Asian names in chat showing only displayname without username

### ISSUE THREAD

**Issue by 0x041E** [night/BetterTTV#1488]
Since twitch allow asians(from my experience works for koreans but probably other asian languages too) to use display name to have names using characters they use in chat the default twitch displays display name(username) like this
![twitch](https://cloud.githubusercontent.com/assets/12925543/18097948/72ff92aa-6ee0-11e6-9059-5889f3fcffe0.png)
But Bttv show it like this
![bttv](https://cloud.githubusercontent.com/assets/12925543/18097975/8d467430-6ee0-11e6-8352-1aa0441d5f81.png)
See how the (username) is missing? Since the display name can contain basically anything in case of asian names so without displaying the (username) it basically allows impersonation because if you don't look at profile of the user you can think it's someone but it can be someone else

**Comment by night** [comment]
we have chosen not to display usernames because it takes up too much space in the line. You can click on someone's name to see their username.

**Comment by 0x041E** [comment]
Could it at least be an option to allow display of username? Also this way the name completion with @ doesn't work for these names without username
