### ISSUE TITLE
Resizing message box

### ISSUE THREAD

**Issue by frezen9** [night/BetterTTV#1489]
I think it would be cool if we could resize the message box, because the small windows gets really annoying, when i'm trying to write a bigger message (it's just two rows, at least for me)

**Comment by NBruderman** [comment]
Maybe there is a way to make the box bigger as the message getting longer... Just an idea

**Comment by frezen9** [comment]
Yeah, exactly! Something like that. I mean you can scroll through the whole message, right, but that's just not very convenient with the small bax, especially if you're used to fast scrolling like me

**Comment by night** [comment]
I think the average user is not writing more than a short message, so I think the use-case here is pretty low. There's a lot of resize logic that currently depends on the chat textarea being a fixed height, so this would require a lot of work to fix relative to the amount of people who would find it useful. Additionally, you can resize chat already to make it wider, which affects the width of the chat textarea. I suggest relying on that instead.
