### ISSUE TITLE
Regular list

### ISSUE THREAD

**Issue by Mrbysco** [night/BetterTTV#149]
I would like to request a new option. For mods to be able to see who's regular (nightbot)

**Comment by Naththo** [comment]
What do you mean who's regular? I'm not quite sure what you mean by that.

**Comment by Mrbysco** [comment]
Nightbot adds regulars... which can use certain commands if they are set to be used by regular.
Only there isnt a way to check if persons are on the regular list. (yet)

**Comment by night** [comment]
This will likely never be integrated in BetterTTV. Loading full lists of users is something that should be avoided, and querying per user is far too resource intensive for most end clients.
