### ISSUE TITLE
Audio Only Mode Suggestion

### ISSUE THREAD

**Issue by WolfElemental** [night/BetterTTV#1493]
I think it would be great to have an Audio Only Mode, similar to mobile.

**Comment by NBruderman** [comment]
I don't think it's needed, as here you can just minimize the window, which isn't possible on mobile, hence this feature...

**Comment by EhsanKia** [comment]
Well in theory audio only uses less bandwidth, which could be desirable on bad networks.
I have myself tried many times in the past to get this working. The API for getting the audio feed is there, but the default player doesn't support it. I haven't yet tried with the new player, so I'll have to test again to see if I can have in support now. There is a site called TwitchAudio which kinda does it, but going to another site isn't really the best user experience. I guess we can leave this as a possible feature until I get time to look into it.

**Comment by night** [comment]
duplicate of #996
