### ISSUE TITLE
Moderator is banning chatter when clicking WHISPER button 

### ISSUE THREAD

**Issue by Miamisweetie** [night/BetterTTV#1504]
This has happened to me a few times already, I go to whisper someone, use the whisper option off the chatter's name and it bans the chatter from the channel.   Quite embarrassing when the Broadcaster notices and calls you out in the middle of his stream, asking why I'm banning this chatter

![ban accident - whisper button](https://cloud.githubusercontent.com/assets/22019573/18262210/755f1ff6-73cd-11e6-961f-8c028e90f4a8.PNG)

**Comment by night** [comment]
It works fine for me. Ensure you're not using other extensions that also modify the Twitch website.
