### ISSUE TITLE
Trouble loading chat

### ISSUE THREAD

**Issue by angelsinthewindow** [night/BetterTTV#1506]
I has been having problems loading up chat a couple times on its own. I will come into a page, and it will say it loaded up Chat but then anything after will not show up. I can post but it will not show my posts, and very rarely when I refresh it will fix but not all the time.

**Comment by CounterPillow** [comment]
I see the same issue here, occasionally chat shows the backlog but then shows no further chat messages. Refresh usually fixes the issue for me though.
Browser is Chromium, I also use uMatrix, uBlock and FFZ.

**Comment by angelsinthewindow** [comment]
It sadly is not always fixing it for me. I use Chrome and only use BTTV and FFZ. I never heard of the other two you use though CounterPillow.

**Comment by night** [comment]
Are you able to reproduce the issue with other extensions disabled?

**Comment by angelsinthewindow** [comment]
No. The only extension that I disabled was BTTV and it works fine after that. I haven't tried disabling others but I only have two extensions for twitch and one doesn't even use the chat.
