### ISSUE TITLE
Anon Chat issue

### ISSUE THREAD

**Issue by Daisenki** [night/BetterTTV#1507]
Hi,

the Anon Chat setting doesn't work right for me, I'm using Version 6.8R55 (FF 48.0.2) and if I join a stream I'm showing in the viewer list although it's "On". To fix this, I switch from On to Off and back to On. 

Can you check this? Thanks!

**Comment by night** [comment]
Does this issue only occur in Firefox?

**Comment by Daisenki** [comment]
I don't know, I'm using only Firefox.

**Comment by night** [comment]
I am unable to reproduce this on Firefox. You might try disabling other Twitch addons you may have installed, since they may affect ours.
