### ISSUE TITLE
Another bug? ...

### ISSUE THREAD

**Issue by SrgtDonut** [night/BetterTTV#151]
Sometimes the theatre mode pause and volume buttons won't show up at all. Here's a picture of what I am talking about: http://imgur.com/0FTINtc

**Comment by cletusc** [comment]
I don't know if it's related, but typically you need to hover over the player itself to show those. The screenshot you provided is exactly how it should show if you don't hover your mouse over the player.

**Comment by night** [comment]
As stated above, hover over the player..
