### ISSUE TITLE
Can't upload emotes due to a Java error

### ISSUE THREAD

**Issue by WackyWocky** [night/BetterTTV#1511]
Attempting to upload an emotes gives me the "Uploading..." image for about 20 seconds, then it disappears without actually uploading the emote. I can press "Upload" again, but it just continues like that. I've tried without any addons, cleared cache/cookies and on multiple devices (Even on my cellphone via the 4G network), still nothing. Pasting the errors from the Java console here, and sending the log file along as well. 

[manage.betterttv.net-1473459274943.txt](https://github.com/night/BetterTTV/files/464945/manage.betterttv.net-1473459274943.txt)

CONSOLE:
angular.js:9827 PUT https://api.betterttv.net/2/emotes net::ERR_SPDY_PROTOCOL_ERROR(anonymous function) @ angular.js:9827m @ angular.js:9628f @ angular.js:9344(anonymous function) @ angular.js:13189$eval @ angular.js:14401$digest @ angular.js:14217$apply @ angular.js:14506(anonymous function) @ angular.js:21443dispatch @ jquery.js:4430r.handle @ jquery.js:4116
angular.js:11607 TypeError: Cannot read property 'status' of null
    at emotes.js:286
    at angular-file-upload.min.js:2
    at angular.js:13189
    at l.$eval (angular.js:14401)
    at l.$digest (angular.js:14217)
    at l.$apply (angular.js:14506)
    at l (angular.js:9659)
    at S (angular.js:9849)
    at XMLHttpRequest.e (angular.js:9800)(anonymous function) @ angular.js:11607(anonymous function) @ angular.js:8557(anonymous function) @ angular.js:13197$eval @ angular.js:14401$digest @ angular.js:14217$apply @ angular.js:14506l @ angular.js:9659S @ angular.js:9849e @ angular.js:9800

**Comment by night** [comment]
This looks like an issue with whatever device you're using to upload with. SSL errors are typically not our issue.
