### ISSUE TITLE
Clicking on a channel from the following page occasionally fails to load the page

### ISSUE THREAD

**Issue by xingped** [night/BetterTTV#1515]
If I'm on my "Following" page and click on a channel to go to it, occasionally the page will fail to load and will just be stuck on an empty page (with the incorrect URL). I've tested this behavior with and without BTTV on and it consistently happens with BTTV enabled and never happens with it disabled.

Chrome v52, Windows 7

**Comment by night** [comment]
What other extensions do you use? It's probably one of them conflicting.

**Comment by xingped** [comment]
The only other extension that could possibly be affecting it is FrankerFaceZ as that runs on twitch as well. I have AdblockPlus disabled on twitch.

**Comment by night** [comment]
That addon has had conflicts in the past multiple times, so it sounds possible.

**Comment by xingped** [comment]
Hm, you're right. Can't reproduce the problem with FFZ disabled and BTTV enabled. Ah well, FFZ gets the boot! Back to BTTV for me! Thanks!
