### ISSUE TITLE
Twitch's Default Theatre Mode

### ISSUE THREAD

**Issue by cygh** [night/BetterTTV#1520]
I was wondering if you were planning on adding a function that allows you to view streams in Twitch's default theatre mode colour scheme. The only thing stopping me from using BTTV is its dark theme that's automatically applied in the theatre mode. It hurts the hell out of my eyes.

**Comment by night** [comment]
Unfortunately there are no plans, sorry. Our dark theme is how we envision a good dark theme to function. It's not for everyone, and it's too difficult to manage multiple themes as-is.
