### ISSUE TITLE
Please add comma removal upon a mention

### ISSUE THREAD

**Issue by uurha** [night/BetterTTV#1525]
When typing a message to another user in a streamer's chat, BTTV automatically places a comma after "@username" in the beginning of a message. Please add an option to remove this feature! Or make a spase between @username and comma, cause @username with comma together is not highlighted to @username.

**Comment by voloshink** [comment]
>cause @username with comma together is not highlighted to @username.

This is not correct, the comma does not affect highlighting and enforces proper grammar

**Comment by uurha** [comment]
@voloshink sometimes on twitch mobile app, and in browser its not highlighted. I don't know how it posible, but its real

**Comment by voloshink** [comment]
post a screenshot when it happens and i'll reopen this issue
