### ISSUE TITLE
Show number of live following channels in extension bar

### ISSUE THREAD

**Issue by floriegl** [night/BetterTTV#1526]
I think it would be cool if the number of live followed channel would be show in the extension bar (right of the url bar). For example if 2 channels are live there should a small 2 in the right bottom corner of the BTTV icon and if you hover over the icon you should be able to se the names of the channels  (like Fingertip https://chrome.google.com/webstore/detail/fingertip/gnmlbkjjolecdapfbfcelgfjaclffiin).

**Comment by voloshink** [comment]
I don't think there's a reason to add this when there are other extensions already providing the functionality(i use Twitch Now, personally)

**Comment by floriegl** [comment]
@voloshink  Fingertip is broken for about 4 days and if only 8 people are using it there is no hope for a fix. My suggestion would provide a use for the icon in the extension bar, too. Also I want it too show your following channels and not like Fingertip where you have to create a list which is not synced across devices.

**Comment by night** [comment]
BetterTTV only runs in the context of the page, not the browser's context. You would need to use a different extension, unfortunately.
