### ISSUE TITLE
Chat Delay on BetterTTV with Chat Delay disabled.

### ISSUE THREAD

**Issue by Apolloftw** [night/BetterTTV#1527]
I'm getting my chat message delayed by 2-6 seconds when the channel doesn't even have chat delay enabled. Example: https://www.twitch.tv/tipofthehats I am getting my chat messaged delayed when they don't have it enabled. And its only with BetterTTV enabled that it's happening.

**Comment by night** [comment]
I cannot reproduce this, and I do not see evidence of this. Is it possible they had delay turned on and then turned it off?
