### ISSUE TITLE
Add "User has been Banned/Timed out" message option for non-moderator users

### ISSUE THREAD

**Issue by Oxxygen** [night/BetterTTV#1529]
A recent update to BTTV removed the timeout/ban message for non-moderator users which would display a chat message when a user was purged/timed out/banned. 

Submitting this issue as a feature request to have it re-added for non-moderator users. Perhaps it could be a toggleable option that is disabled by default (much like "Show deleted messages").

Tweet chain referencing this change: https://twitter.com/TheManiacD/status/778037558257123328

**Comment by voloshink** [comment]
I thought this was a twitch bug and users were not supposed to be exposed to that information, we'll see how it pans out

**Comment by TheManiacD** [comment]
I was the one that composed that tweet. Having that as a setting would be nice to have.

**Comment by aroboto** [comment]
The change to auto-hiding the deleted messages makes the "Remove Deleted Messages" option redundant now. I much preferred having the <message deleted> to having all messages hidden or having the messages striked through.

**Comment by PenguinOfLight** [comment]
I understand that in some chats it can become ridiculous to see all of the purged messages, but it should be an option to turn it off or not.
Oh wait, it already was. We call it "Removed Deleted Messages." This change was redundant and should not have been included, because it already *was* included.

**Comment by Mitsuma** [comment]
Make "Remove Deleted Messages." on by default if you want but do not remove the option completely. I don't understand who thought it was a good idea to remove this useful feature, which was an option in the first place.

**Comment by WizardCM** [comment]
Adding my voice to this - please don't force users to not see something they normally see without your extension, especially if you're not going to provide a config option.

**Comment by night** [comment]
> Oh wait, it already was. We call it "Remove Deleted Messages." This change was redundant and should not have been included, because it already was included.

Please be aware that sarcastic/rude replies do not help your case and are not appreciated conduct here. We welcome constructive criticism but will lock this thread if we continue to receive such unconstructive replies.

**Comment by Kolatra** [comment]
Yeah, I'm not a fan of this change. I don't see the point of it in the end.

Even if you don't want to remove it, adding it as a config would be absolutely incredible. :)

**Comment by Nareese** [comment]
Adding a +1 for returning timeout and ban messages to non-mod users, preferably on by default and configurable for disable for people who find them spammy, but if not then as configurable to re-enable them, please.  Users are used to seeing these messages to know that moderators have seen and acted on problem users.  Not having it can result in BTTV users complaining to mods about users that have already been dealt with.

**Comment by ceriathstudios** [comment]
We got recently blamed for "censoring" messages. That guy was a troll tho, but he is somehow right i guess. Really do not like the option, neither as mod nor as non-mod. Please bring back the option we can turn on and off how we prefer it :)

**Comment by aroboto** [comment]
I think a good compromise would be to revert to the old way of it being controlled by the "Remove Deleted Messages" but to have that option enabled by default, would still allow people to exercise their personal preference but would get more people using the option.

**Comment by DAOWAce** [comment]
Was this ever fixed?

I just noticed during the GDQ streams that messages were outright disappearing instead of becoming "message deleted".  Tried to search about it and found a reddit thread which linked to this with people complaining.

My "remove deleted messages" option is disabled.

**Comment by Oxxygen** [comment]
@DAOWAce Yes, this issue has been resolved and marked as closed. The change was [reversed on 9/24](https://github.com/night/BetterTTV/commit/af2d76ea08eb2ed47ddeed42ff823607d4e77df4), the day the ticket was closed.

**Comment by Kolatra** [comment]
I'm seeing the messages in the GDQ stream, something else on your end is changing that.

**Comment by DAOWAce** [comment]
Weird.. the only way I could get the messages to show up is by enabling the "show deleted messages" option.

If that's disabled, even though "remove deleted messages" is disabled too, I don't see any of <message deleted> or "user has been timed out" text.

Haven't changed my BTTV settings since like mid 2016; not sure what's up with it..
