### ISSUE TITLE
Dashboard Chat

### ISSUE THREAD

**Issue by searker** [night/BetterTTV#153]
When the dark style is active, the chat in the dasboard is not always dark - sometimes it´s white, sometimes dark.

**Comment by night** [comment]
I cannot reproduce this. Try disabling other browser add-ons to see if one is incompatible. Also provide reproduction steps, where necessary.

**Comment by searker** [comment]
Am 16.01.2015 um 18:35 schrieb Night:
>
> I cannot reproduce this. Try disabling other browser add-ons to see if 
> one is incompatible. Also provide reproduction steps, where necessary.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/night/BetterTTV/issues/153#issuecomment-70290396>.
>

I´d like to tell you how, but im afraid i can´t since it does only 
appear randomly.
However, when it does appear, it will also only disappear randomly - 
Clearing the cache or deleting cookies didnt help at all - The only 
"safe" method to make it work again is to reinstall BetterTTV.
It is not cause by other addons; i already tried disabling them.

I´ll make a screenshot the next time it happens - I hope i´ll remember 
to do so :)
