### ISSUE TITLE
Requesting feature for BTTV

### ISSUE THREAD

**Issue by ShadowStryker112** [night/BetterTTV#1531]
Hello,
I would want to suggest a new feature for this already good extension. 
As a moderator, for me it would be so helpful if there was a way to keybind a custom timeout. Yes I know there is the "shift-click" option but being able to change the value of the timeout in the BTTV menu for the "t" button for example to be like 30 min not the usual 10. There is already a button next to the names but being able to timeout these cancer kids spamming porn links for more than 10 minutes (without typing the command and without banning them) would be great .
This is the first time I write a request so sorry if it does not make sense.
Good day!

**Comment by aroboto** [comment]
Have you tried using the menu when right clicking a name?

**Comment by night** [comment]
As the "shift-click" option states, you can leave it off and right click on names instead. Custom timeout lengths as keybinds is not something we think makes sense, sorry.
