### ISSUE TITLE
Option for a better following page

### ISSUE THREAD

**Issue by NeKzor** [night/BetterTTV#1532]
I know this has been requested many times before but here is the reason why it should be done:
That "Based on your viewing history" section replaces your "Most recent videos" in your following page. Having live channels, live hosts, live games and most recent videos all on one single page isn't too much to ask for, right?

**Comment by night** [comment]
I mean in general most people on Twitch do not care for VoDs, so the reason Twitch probably added this section is to put more interesting/popular/trending content up that might engage people in VoDs more. I tend to agree with their decision on this.

**Comment by NeKzor** [comment]
So you actually watch VoDs that Twitch forces you to click on? I don’t because I should be the one who controls what I want to see and not a stupid algorithm which shows me VoDs that I've already watched or other games from channels that I'm not interested in. I think you misunderstood something. Twitch didn’t add a section, they replaced the old section which is actually important because it shows you past broadcasts and highlights that you’ve missed. What's the point to hide one of the greatest features of this website?
