### ISSUE TITLE
Very slow chat load up

### ISSUE THREAD

**Issue by nimularud** [night/BetterTTV#1541]
When I open any channel, chat is just empty for like 3 minutes, my own messages doesn't appear ether. After some time messages start to appear and chat works as normal. This issue doesn't present when bttv is diabled or then I use different browser.

Browser - firefox 49.0.1

**Comment by night** [comment]
I cannot reproduce this. Do you see a "BetterTTV Loaded" message in chat when it loads? If not, it sounds like you have some other extension installed that's conflicting. Try disabling all other extensions and seeing if the problem persists. You might also try clearing your cookies and cache.

**Comment by nimularud** [comment]
Clearing cookies helped. Still, it was very strange, "BetterTTV Loaded"
message appeared for me but nothing else. Sorry for bothering.
