### ISSUE TITLE
Chat messed up

### ISSUE THREAD

**Issue by brandons101** [night/BetterTTV#1542]
So when i don't have better twitch tv my chat opens open regularly but when i have better ttv chat doesn't
 show up and i have to click the button to show it, when i have everything on chat is hidden and i have to push the same button to show it, i just want chat to show up regularly this only happens when i have better tv installed 
Thanks
![chat closed](https://cloud.githubusercontent.com/assets/22417868/18810155/e744846a-825c-11e6-8348-a93f572ca63a.PNG)
![hidden chat](https://cloud.githubusercontent.com/assets/22417868/18810156/ed1c5d04-825c-11e6-8784-aeaf65fddc55.PNG)

**Comment by night** [comment]
Clear your cookies and cache (from the beginning of time) and the problem should fix itself.
