### ISSUE TITLE
BetterTTV does not save my settings

### ISSUE THREAD

**Issue by Syvbers** [night/BetterTTV#1545]
I have a really big issue with the BetterTTV settings. Every time I close my browser my BetterTTV settings getting deleted completly. I´m currently using the newest version of Opera as my browser and don´t want to swich it. I´m a new moderator in a really big channel so that I really need the support from BetterTTV or I can´t work properly at all.

**Comment by EhsanKia** [comment]
Make sure your browser isn't clearing data on exit.

http://www.howtogeek.com/137681/how-to-automatically-clear-private-data-when-you-close-your-browser/ (scroll down to opera)
