### ISSUE TITLE
@cant write to people

### ISSUE THREAD

**Issue by YeLLeZ** [night/BetterTTV#1547]
Hello, i cannot write to somebody as @nickname ... sometime ago it was ok,but now is bugged.
Without BTTV - i can do it, when i write @ - its auto select nickname, but with BTTV it doesn't. Please help me :(

**Comment by voloshink** [comment]
press tab after typing @ to cycle names. If you want to see the tooltip, enable Completion Tooltip  in the bttv settings

**Comment by YeLLeZ** [comment]
Got it, thanks a lot.
