### ISSUE TITLE
*Request*  Smooth chat scrolling for B.T.T.V.

### ISSUE THREAD

**Issue by vrimvrim** [night/BetterTTV#1551]
it would be AWESOME and make chat SO much more easier to read if you guys implemented a smooth chat scrolling feature for BTTV. 

having messages ( especially in large channels ) smoothly scroll upwards instead of instantly jutting up would make reading busier chats immensely easier, allowing for your eye to much more easily track, and read messages as they smoothly scroll up instead of having to keep re-finding messaged via scanning the page over and over again.

(but what about speed? spam? etc?) - it would still be easier to read, and to keep up with possible delay, make the smooth chat scrolling go faster based on how many messages per (time frame) there are.

**Comment by night** [comment]
Smooth scrolling animations are extremely CPU intensive. In channels where there's a lot of chat, it's impractical to do any animations.
