### ISSUE TITLE
Hiding chat erases chat options

### ISSUE THREAD

**Issue by BodhiWolf** [night/BetterTTV#1559]
Windows 7 Home
Google Chrome

I clicked on the cog to hide chat. 
When I restored chat, the options to select highlighted/banned words etc disappeared.

The only options remaining are:
-Edit appearance
-Time stamps
-Hide chat
-Popout

**Comment by night** [comment]
I cannot reproduce this. Can you show a gif of it happening?

**Comment by BodhiWolf** [comment]
I've never made a gif before. Here's a before and after:
http://imgur.com/a/TaoSg

You can see that the scroll bar with the additional options disappears. All I do is hide chat, then show it again.

**Comment by BodhiWolf** [comment]
While this is still happening, it's fixed by refreshing the page. This wasn't the case before.

**Comment by EhsanKia** [comment]
Is this still happening? If so, can you try this.

1. Open console by going ctrl+shift+j
2. Clear console with ctrl+L
3. Enable logging by typing `BetterTTV.settings.save('consoleLog', true);`
4. Hide chat, bring back chat, check if it's broken
5. If so, copy everything that is now in the console and send it here.

**Comment by night** [comment]
closing because we cannot reproduce this issue. If you're still having issues, follow the suggestion above.
