### ISSUE TITLE
BetterTTV encountered an error reading chat

### ISSUE THREAD

**Issue by Apsnr** [night/BetterTTV#156]
I dont know if this is a known issue, but i am receiving the following message in twitch chat when i am trying to type something. 

"BetterTTV encountered an error reading chat. The developer has been sent a log of this action. Please try clearing your cookies and cache"

I have already cleared the Cookies/ cache / Browsing history and still having the same issue . The twitch chat works fine if i disable BetterTTV

Hope that helps

**Comment by night** [comment]
https://community.nightdev.com/t/chat-cant-be-read/2785/8?u=night
