### ISSUE TITLE
Feature Request: Click Screen to Pause

### ISSUE THREAD

**Issue by ConnorWalsh7** [night/BetterTTV#1561]
I always prefer when video players have the option to click anywhere on screen to pause and resume a video, as apposed to hitting the small "play/pause" button on the bottom bar. I watch a lot of twitch vods as apposed to the actual live stream so I pause more frequently than most people would during a live stream (I assume)

**Comment by night** [comment]
We are considering a hover pause (with a timeout) or a hotkey.

**Comment by teak** [comment]
he talking about the video player not chat.

**Comment by night** [comment]
lol, well I didn't really read
