### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Solace127** [night/BetterTTV#1562]
Function to revert back to old twitch ui please.

**Comment by CptObvious1994** [comment]
I second this. This new layout makes no sense. Unimportant information like number of videos, number of followers, and number following is now above the stream in huge font. The title of the stream and the game being played has been shrunk down and placed under the stream. This is the exact opposite of a logical layout. I don't care how many videos a streamer has archived, but I very much care to know the title of the stream and what game is being played.

**Comment by night** [comment]
closing in favor of #1565
