### ISSUE TITLE
Monkey emoticons not working.

### ISSUE THREAD

**Issue by Maxmonie** [night/BetterTTV#157]
"BetterTTV replaces the robot emoticons with the old JTV monkey faces by default"

It seems this feature is not working anymore.
I clearly have the feature enabled, but I'm still using the "regular" twitch emotes with the robot faces, instead of the monkeys.

Hope it gets fixed soon.
Thanks.

**Comment by night** [comment]
https://community.nightdev.com/t/chat-cant-be-read/2785/8?u=night
