### ISSUE TITLE
Emote List in Popout Chat not fixed to bottom of window

### ISSUE THREAD

**Issue by Foxhan** [night/BetterTTV#1574]
![image](https://cloud.githubusercontent.com/assets/22552567/19008793/0c0eba52-876e-11e6-917b-b9541ad21454.png)

**Comment by night** [comment]
paging @cletusc

**Comment by cletusc** [comment]
Fixed by [cletusc/Userscript--Twitch-Chat-Emotes/e78f4ca550157e0aa68bfcfcfb12eb2058766ebe](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/commit/e78f4ca550157e0aa68bfcfcfb12eb2058766ebe)
