### ISSUE TITLE
remove twitch prime from the left and to have an option to have the old twitch look

### ISSUE THREAD

**Issue by EnderHawk** [night/BetterTTV#1575]
they just added a thing called twitch prime and now theres even more icons on the left and alot of people including my self want the old twitch look again if that could be a setting it would be great

**Comment by sudieken** [comment]
Yes please. I don't give a crap about this "Free with Prime" junk they're advertising.

**Comment by Stoupedog** [comment]
See #1573

**Comment by realdomdom** [comment]
@Stoupedog This is about blocking the advertising for it, i believe, not about blocking the badges.

**Comment by sudieken** [comment]
Yeah this has nothing to do with the badges. In the left sidebar there are now advertisements for prime.

**Comment by EnderHawk** [comment]
this i not about the badges its about the ads for the ingame items and stuff on the left
