### ISSUE TITLE
Chat Being Deleted

### ISSUE THREAD

**Issue by pailswails** [night/BetterTTV#1576]
Hello! 
This extension is fantastic, however I do have one problem that suddenly started. Upon joining a certain chat, the messages that were just said appear for a second, and then disappear. However, this does not occur in all the other channels that I have checked so far. So I disabled the BetterTTV extension, which fixed the issue. But I'd like to keep the extension, and be able to read what was said previously in chat. Perhaps is it a setting in this specific streamer's channel, but some feedback about this issue would be very much appreciated.
Thanks!

**Comment by RandomGOTI** [comment]
Are you by any chance using the anon chat feature ?

**Comment by pailswails** [comment]
No, I have it set to off.

**Comment by pailswails** [comment]
Actually, I turned it on, and then turned it off again. Seemed to fix the problem. Thanks!
