### ISSUE TITLE
Emote Spam Glitch

### ISSUE THREAD

**Issue by legendofbaus** [night/BetterTTV#158]
Apparently this is happening in chat using BTTV, not sure if someone is trolling or what not but I figured I'd send it to you: http://gyazo.com/9569bde5c6628881482c93702f5b28c5

I'm not the only one seeing this and people are saying they are not sending that many emotes. Night, are you trolling us or is it just a bug in BTTV? lol

**Comment by night** [comment]
If you're still seeing emotes attached to some messages, clear your
cookies and cache.

**Comment by legendofbaus** [comment]
I'm still getting emote spam after clearing cookies and cache.

**Comment by legendofbaus** [comment]
Also, the BTTV emotes are not showing up in the Twitch Chat Emote box. Not sure if the two are connected.
