### ISSUE TITLE
Improved emote menu button disapeared

### ISSUE THREAD

**Issue by UnholyRapido** [night/BetterTTV#1580]
I'm using firefox 49. Button was on it's place few hours ago then it's gone without any error. Tried unistalling addon and reenabling this options in settings.
Help or fix would be great
Thank you!

**Comment by night** [comment]
Yes. It's been disabled until the maintainer can fix breaking problems affecting some users. Sorry for the inconvenience.

**Comment by Tester798** [comment]
But it was working great about 12 hours ago, why it got disabled then?
Can't you just embed it in your code or make your own emotes menu? It's not that hard.

**Comment by night** [comment]
this is now fixed
