### ISSUE TITLE
Emote Menu

### ISSUE THREAD

**Issue by Oscar172** [night/BetterTTV#1585]
Hey! My "Emote Menu" wich i have enabled in the settings doesn't work. I've tried to reinstall BetterTTV a couple of times now, but it still doesn't work. I guess it's a bug?

**Comment by Stoupedog** [comment]
The emote menu's been temporarily disabled due to it causing problems for some users
(See #1580)

**Comment by Oscar172** [comment]
okey! thanks for fast reply :)

2016-10-01 18:25 GMT+02:00 Zack <notifications@github.com>:
