### ISSUE TITLE
i cant see the bttv emotes tab

### ISSUE THREAD

**Issue by TheMink** [night/BetterTTV#1589]
i recently have not been able to see or use my bttv emotes tab in the chat ui. i have tried disabling and reenabling the browser extension and importing a backup of my settings

**Comment by Tester798** [comment]
Yes, just opened twitch and I see bttv emotes button is not available anymore.

**Comment by fuwafoowa** [comment]
Exactly the same for me.

**Comment by night** [comment]
duplicate of #1580
