### ISSUE TITLE
BTTV specific emotes missing

### ISSUE THREAD

**Issue by TrentSterling** [night/BetterTTV#159]
Emoticons like D: and GabeN have stopped working for me on 2 separate machines. 

BetterTTV Emotes are enabled in the settings. I've cleared cache and cookies, and even tried reinstalling the plugin in chrome.

Same results in FireFox. BTTV emotes aren't working.

**Comment by Chiisato** [comment]
I can confirm this, I have betterTTV emotes enabled in the settings, I've cleared cache and cookies, even tried to re install the plugin, still the same issue. Tried using only BetterTTV-addon and nothing else, still not working. Also, click to insert emotes are not working, tried the standalone version and nothing.

**Comment by cletusc** [comment]
@Chiisato, I will be handling the emote menu in #160. This issue will remain for what the OP reported. Twitch may have just pushed a potentially breaking update that affects both this and #160.
