### ISSUE TITLE
Support auto-resub of 'free' Prime sub

### ISSUE THREAD

**Issue by TonyHoyle** [night/BetterTTV#1592]
The free prime channel sub doesn't auto-resub, which means lots of people who subbed to channels with it will forget in a month.

Suggest BTTV has a setting to automatically resub when it can (when you visit the channel, for example) or at least a reminder popup.

**Comment by NBruderman** [comment]
I think a reminder is the proper way to do it... I think making it auto re-sub is too intrusive

**Comment by EhsanKia** [comment]
I don't think this is something BTTV can or should do.

**Comment by klonamy** [comment]
I support the reminder idea.
It leaves you a choice. :)
