### ISSUE TITLE
"Automatic Theater Mode" bug

### ISSUE THREAD

**Issue by kazraz** [night/BetterTTV#1594]
When "Automatic Theater Mode" is enabled and you exit theater mode the video player disappears completely leaving only the channel's description but the audio remains. Twitch recently changed the home page of all users so this probably has something to do with it. After removing Auto Theater Mode I was able to enable and disable theater mode without problem.

**Comment by night** [comment]
We tested this, and it's actually a Twitch race condition bug.

**Comment by night** [comment]
I take that back, we're computing player height incorrectly for theater mode. This should be fixed.
