### ISSUE TITLE
Split Chat colors aren't sticking to the text

### ISSUE THREAD

**Issue by BrianG2k** [night/BetterTTV#1597]
Split Chat colors are flashing as each new line of text comes in rather than sticking to a line of text. If I sent a message to chat, that message background color should not change color. Otherwise it defeats the purpose of making it easy to track test as it scroll.

**Comment by night** [comment]
When does that start happening?

**Comment by BrianG2k** [comment]
i _think_ it starts happening when an emote goes past and gets cut off on the right side of chat. will try to pay more attention and report back

**Comment by BrianG2k** [comment]
also might be when someone gets timed out

**Comment by night** [comment]
If you have any repro steps, please let me know. It seems fine to me.

**Comment by BrianG2k** [comment]
trying to track it down. it happens both with and without FFZ enabled. Safari Version 10.0 (11602.1.50.0.10) OS X 10.11.6 no Flash installed.

**Comment by BrianG2k** [comment]
there doesn't seem to be any rhyme or reason. it just happens over time. could be time outs or bans. could be the red hi lights that stick up to the top from keywords, could be the groups chats notifications (that are also broken), -- those are the only things happening in my instances of using BTTV.
