### ISSUE TITLE
Feature Request - Hide Twitch Prime icons on leftmost UI bar

### ISSUE THREAD

**Issue by FFearMe** [night/BetterTTV#1600]
![twitch_prime_icons](https://cloud.githubusercontent.com/assets/22601402/19050738/91659bfe-8975-11e6-9c31-0e8eb47f0864.PNG)

A feature request similar to one currently being implemented to hide clutter on leftmost UI bar. Removal of twitch prime icons.

**Comment by Aaron128l** [comment]
duplicate of #1583

**Comment by FFearMe** [comment]
Thanks for making me aware that it has been addressed!
