### ISSUE TITLE
More Favorite Emotes viewable in Emote Menu

### ISSUE THREAD

**Issue by UncleElias** [night/BetterTTV#1601]
Right now we can only see a limited number of Emotes on one line in the Emote Menu based upon the width of the of the Emote Menu.

I don't know if the emotes need to be word wrapped or there needs to be a flexible line limit. At any rate, I have many more favorite emotes than I can see in the Emote Menu's Favorites section.
![bttvfavemote](https://cloud.githubusercontent.com/assets/22605282/19058728/b0834f9a-89a7-11e6-8e9d-a352dd152325.PNG)

**Comment by cletusc** [comment]
This is being tracked in [cletusc/Userscript--Twitch-Chat-Emotes#69](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/issues/69).

**Comment by davr** [comment]
unfortunately the place it's being tracked is no longer maintained :'(
