### ISSUE TITLE
Host Button Missing :/

### ISSUE THREAD

**Issue by Katryoshka** [night/BetterTTV#1602]
I logged onto twitch today to see that..... The host button is gone! D:

I tried refreshing, closing my browser completely, restarting, nothing.

All Im using is Fankerz FaceZ and Better TTV :C

http://i.imgur.com/EIhKqbI.png  <--- Picture of le Host Button being a Ghost

**Comment by voloshink** [comment]
How are you on the old channel layout

**Comment by voloshink** [comment]
Looked into it, looks like twitch still sometimes serves the old channel layout to their users. So once they stop this should be resolved
