### ISSUE TITLE
Preview Window Bug 2

### ISSUE THREAD

**Issue by GKid94** [night/BetterTTV#1606]
Can you fix the bottom and upper side of the Preview window like you did with the left and right cuz its goin down now
![2016-10-05](https://cloud.githubusercontent.com/assets/18757054/19095136/741068fc-8a94-11e6-8002-ea62b88f004e.png)

**Comment by EhsanKia** [comment]
I don't get the issue. With left and right it would actually go outside the screen and there was literally nothing you could do about it. In this case, it's still in the page, maybe slightly too low, but you can simply scroll down a bit and get it centered if you'd like. It's not a breaking bug nor is the previous half outside the page. It's honestly not really possible to get it better than this. Just scroll down two ticks and you're good

**Comment by GKid94** [comment]
I tried to scroll and nothing happens
