### ISSUE TITLE
Hide Prime Promotions - Returns after refreshing page.

### ISSUE THREAD

**Issue by nguyendex** [night/BetterTTV#1616]
The Prime Promotions come back after refreshing the page when Hide Prime Promotions is on.

**Comment by thinkpad4** [comment]
Yep, just noticed that too

**Comment by voloshink** [comment]
yeah, i fucked up. i made a pr, should be fixed next time bttv is pushed out, sorry about that

**Comment by night** [comment]
fixed by e9e77a59f16b031799ec008e901ebafdeeff78e3
