### ISSUE TITLE
PLEASE

### ISSUE THREAD

**Issue by fhysics** [night/BetterTTV#1618]
I love to watch Ice_Poseidon's stream, but he has an absurd amount of chat spam. If there was some way to filter people copy and pasting their message to the message limit, or filter chat so no caps lock messages show, or any messages over 10 emotes, anything at all. Watch his stream, see what these spammers do and see if there is some way to block these spammers. I've spent entire streams ignoring users in his chat and it's just never ending. If there is another way that BTTV can't do for whatever reason, please let me know.  It's torture.

**Comment by night** [comment]
It is not BetterTTV's role to function as a chat spam filter, sorry. It's resource intensive to filter chat in real time, which would have a negative impact on most users' computers.
