### ISSUE TITLE
Auto-Hide Chat?

### ISSUE THREAD

**Issue by kbourne87** [night/BetterTTV#1619]
Is there any way you can make a feature that automatically hides chats in certain channels? Every time I go to check out a huge stream like a GDQ or The International, EVO, or something, I find myself trying to slam options and try to hide chat before an avalanche of emotes and copypasta slow down the video player. My not be easy, but you've done so much for my Twitch experience so far. Thank you!

**Comment by night** [comment]
You can hide chat by closing the right sidebar. There's no way to set this per stream, however. Since we store states in local browser storage, it's not practical to keep a list of customizable settings per stream when they could be easily wiped when users clear cookies.
