### ISSUE TITLE
Tabbing on localized name will close tab-completion

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#1622]
Using nothing but the tab key:

![](https://i.gyazo.com/1a538c27a4710cdbad78e0c7fed76f4c.gif)

The localized name is "`足フェチ_`" and the username is "`footfetshh`." Tabbing to that name and then pressing tab again will automatically accept that localized name instead of continuing through the list.

**Comment by voloshink** [comment]
It's probably relying on the displayname = username rule which twitch broke
