### ISSUE TITLE
BTTV not being loaded on clips.twitch.tv

### ISSUE THREAD

**Issue by Stoupedog** [night/BetterTTV#1623]
BTTV is not being loaded on clips.twitch.tv, this is shown in console:
![c27b46e49bf76088df90ba5624d2b942](https://cloud.githubusercontent.com/assets/9131477/19209986/c8e04e3e-8d72-11e6-85bf-03ffcfb74800.png)

**Comment by Aaron128l** [comment]
Cause e9e77a5 thanks Teak.
