### ISSUE TITLE
Old Twitch Layout

### ISSUE THREAD

**Issue by KierenE** [night/BetterTTV#1624]
Please make a feature to replace the new twitch layout with the old. I can't stand it lol.

**Comment by voloshink** [comment]
We might make a feature to clean up the new layout but i don't think we should have an option for the old layout. This would mean every time we add a feature we have to make sure it works on both layouts which is just busywork.

**Comment by KierenE** [comment]
Ah I see how that could be a mess. Thanks for considering cleaning it up at
least!
