### ISSUE TITLE
Client-side audio channels

### ISSUE THREAD

**Issue by TomNaughton** [night/BetterTTV#1625]
So I noticed whilst watching heychrissa's stream that I didn't want to listen to the music requested by people but I wanted to hear Chrissa. What if the music playlist is controlled server-side and played on the clients? So that I can mute the music but still hear the streamer.

**Comment by EhsanKia** [comment]
This isn't really something for BTTV to add. It's been requested for OBS/Twitch. I believe OBS sort of supports this, but Twitch would need to add it too, and then they would need to put an interface for controlling music and stream audio separately. But yes, it's not really something for BTTV to do.
