### ISSUE TITLE
Host Button Disappeared 

### ISSUE THREAD

**Issue by STARBURSTKILLER** [night/BetterTTV#1626]
Is it just me or did the host button disappear when was in another channel the host button would be right beside follow settings sub etc.. but now its not there its still enabled on bttv i miss having it :(

**Comment by voloshink** [comment]
Are you on the old channel layout

**Comment by STARBURSTKILLER** [comment]
im not sure how would you figure out

**Comment by voloshink** [comment]
post a screenshot of anyone's channel page

**Comment by STARBURSTKILLER** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/22718955/19216883/736e9b20-8d9c-11e6-8a88-621d9b710e1f.png)

**Comment by voloshink** [comment]
yeah, you're still on the old one. For some odd reason twitch still routes 10% of the users to the old page. I'll try and see why it's broken on the old layout.

**Comment by STARBURSTKILLER** [comment]
k thanks :) , does twitch change it automatically to new layout or do i have to do something?

**Comment by voloshink** [comment]
Don't think there's anything you can do about it, although you can try clearing your twitch cookies/cache to see if that rerolls you.

**Comment by STARBURSTKILLER** [comment]
ah cleared the history/cookies from chrome and got the new channel layout thanks for your help :)
