### ISSUE TITLE
Reduce chat refresh rate

### ISSUE THREAD

**Issue by MS-Sync** [night/BetterTTV#1631]
Hi guy (first thanks for your hard work, i'm loving BBTV :D)
I was wondering if it is possible to reduce the chat refresh rate. Like instead of having message popping every millisecond, an option to make it 1s.
I ask you this because often my stream is lagging because of the intense CPU usage of the chat (with emotes). Hidding it resolve the problem but the chat is part of the Twitch's life.
Hope you will make it 👍 
Nico :)

**Comment by night** [comment]
Messages do not come in every millisecond already. We render once every 250 milliseconds, which is more than slow enough for most computers. Unfortunately our render speed is not configurable, and we have no plans to make an option for it at this time, sorry.
