### ISSUE TITLE
Twitch Problems

### ISSUE THREAD

**Issue by GKid94** [night/BetterTTV#1641]
Since yesterday the Twitch player has become smaller and so does the preview video, what is happening and how do i fix that the way it was??? And by the way i tried restarting Chrome and the issue is still there :(
![2016-10-11](https://cloud.githubusercontent.com/assets/18757054/19253430/4a73fc3c-8f4b-11e6-9895-24db51064f78.png)
![2016-10-11 1](https://cloud.githubusercontent.com/assets/18757054/19253439/5388238e-8f4b-11e6-912e-7d846c81b4c3.png)

**Comment by night** [comment]
We match default twitch's video player sizing, and the directory preview was made smaller.
