### ISSUE TITLE
Option to disable showing a streamer's cover image above the video player when scrolling up.

### ISSUE THREAD

**Issue by mefich** [night/BetterTTV#1645]
The new Twitch UI has a very annoying new feature. When you scroll up, it opens an area with a streamer's channel cover image above the video player. I would be nice to have an option to prevent it from opening.  
![twitch channel screen](https://cloud.githubusercontent.com/assets/12255125/19279514/21e8e29a-8ffb-11e6-822c-8707ce833152.png)

**Comment by night** [comment]
While we intended to do this, there is no entry point we could find to disable Twitch's scroll bar listener, which breaks our fixes.
