### ISSUE TITLE
Bankheist twitch chat games

### ISSUE THREAD

**Issue by Billybobble** [night/BetterTTV#1647]
Apologies if this has been requested before, I'm still getting to grips with all available features/options.
During a lot of streams I watch they have bankheist games or variations, they are a bit spammy but not necessarily unwelcome. I just wish there was a way BTTV could help separate those 'game' comments to 'real' user comments?
Thanks
Billybobble

**Comment by voloshink** [comment]
You could always just blacklist the commands so they don't show up in chat

**Comment by Billybobble** [comment]
I don't mind them, I play along myself a fair bit, but they do clutter the chat from actual chat. It would be nice if they had some sort of colouration like if someone tags you in a comment just to have a bit more clarity in the chat. Thanks for the reply.

**Comment by voloshink** [comment]
Probably not going to happen. We would have to constantly maintain and update a list of commands that bots use, people will keep asking for their commands to be added to the list. Basically, not worth the work.

**Comment by Billybobble** [comment]
Okay that makes sense I guess, it's a shame but hey I thought I'd enquire about a possible solution. Thanks for the support.
