### ISSUE TITLE
Resizing chat no longer resizes video player.

### ISSUE THREAD

**Issue by CptObvious1994** [night/BetterTTV#1649]
The video player no longer shrinks when you drag the edge of the chat to make it bigger. The chat just expands over the video player, covering part of the right side and the settings, clip, theater mode, and fullscreen buttons.

**Comment by night** [comment]
works for me.. disable other extensions if you have any

**Comment by CptObvious1994** [comment]
I tested that before submitting this. That's why I submitted it as a bug, because I knew it wasn't due to any other extensions.
