### ISSUE TITLE
Ability to change highlight colour.

### ISSUE THREAD

**Issue by Gigabyte5671** [night/BetterTTV#1655]
It would be nice to have the ability to change the highlight colour to something a bit less harsh than red.

**Comment by EhsanKia** [comment]
In the future it'd maybe nice to have a much more advanced highlight feature with multiple custom colors and such, but I doubt this will come anytime soon, so in the meantime, I recommend using an extension like Stylish to customize the color on your end for yourself.

If you need help with the css, I'd be happy to help.

**Comment by night** [comment]
duplicate of #237
