### ISSUE TITLE
Permission to uploadmore than 5 emotes

### ISSUE THREAD

**Issue by Ladymeowss** [night/BetterTTV#1657]
Hello,
I would like to have the opportunity to add more than 5 emotes in my bttv account, or to work with bttv in creating more emotes, in any way, i love sharing my work and allowing people to use it, 5 is just not enough content,  it is more like a request, If it is not possible please inform me other ways i can do this,
Thank you.

**Comment by Stoupedog** [comment]
[(answered on the forum)](https://community.nightdev.com/t/permission-to-have-more-than-5-emotes/8919/2?u=stoupedog)

In future, please don't ask the same question in two different places.

**Comment by Ladymeowss** [comment]
Sorry i wasnt sure what topic it is, thx for replying.
