### ISSUE TITLE
Chat not autoscrolling

### ISSUE THREAD

**Issue by twsx** [night/BetterTTV#1658]
With BTTV active, my chat seems to sometimes stop autoscrolling.
The "More messages below" notice doesn't appear either, so often I don't even notice for quite a while.

It seems to appear randomly so I have no idea how to reliably reproduce it. As such, I can't be 100% sure that it is a BTTV issue, but I've been watching streams for a couple of hours with BTTV off and the problem didn't appear again, while it definitely usually would have happened within that a time frame.

Chrome 53.0.2785.143 m (64-bit) on Windows 10, and the only other Twitch-related plugin I have installed is FFZ.

**Comment by EhsanKia** [comment]
We have a new feature that freezes chat when you're holding the CTRL key. There's a related bug that's being fixed in #1650 which may solve this for you. Can you confirm that you are not holding CTRL or getting in a state where the CTRL key is stuck? Maybe that patch will fix your issue too.

**Comment by twsx** [comment]
I don't really know about CTRL usage. Obviously I'm using the key regularly while doing various things while watching a stream. I doubt that it ever gets "stuck" in that sense though, as I'd probably notice that.

If this seems to be an existing issue that's being fixed, I'm happy though. Besides, I wouldn't know how to apply that fix in the other thread anyway

In the meantime, I'll turn off FFZ and see if the problem persists, and report back in a day or two. Thank you for the info!
