### ISSUE TITLE
@mods to highlight for anyone logged in as a mod

### ISSUE THREAD

**Issue by Toocanzs** [night/BetterTTV#1661]
When a message contains "@mod" or "@mods" and you are a moderator of the channel, then make this message highlighted like the @username feature.

Examples
"@mods can you deal with @thisguy"
"any @mods here?"

Would be quite useful for users to alert mods who may not be paying full attention to the chat.

**Comment by teak** [comment]
You can add "@mods" to your highlight list.

**Comment by Toocanzs** [comment]
> You can add "@mods" to your highlight list.
See the reason I want this is not because I am a moderator, but because I am generally just a viewer. If this was a standard, then any user could notify the mods easily. Right now most people will say something like "Hello mods?" "any mods?" "MODS PLEASE", but unless they have their highlights set up like you suggested this doesn't help.

**Comment by teak** [comment]
BTTV can't make this standard. The only way would be if Twitch implemented it.

**Comment by Toocanzs** [comment]
Maybe I've misunderstood, but isn't highlighting a BTTV feature? I'm asking for this to be a standard for BTTV users, I could care less about normal twitch users. 

I don't see how BTTV couldn't do this, seeing as it can tell when you are logged in as a mod, and it can highlight chat by specific keywords, then why couldn't it highlight for @mods if you are a mod?

**Comment by teak** [comment]
Highlighting is a Twitch feature implemented slightly differently in BTTV. I'm not saying BTTV can't do it, I'm saying people won't use it unless its universal across the the site.

**Comment by Toocanzs** [comment]
Well, I guess I just disagree then. people who don't use BTTV could still use @mods to alert mods using BTTV, and I don't see how something not being universal has stopped anything in BTTV to be honest. People use non-universal emotes all the time.

**Comment by EhsanKia** [comment]
Personally I'm a bit in between on this. On the one hand, I agree that it could be useful, and let's be honest most people use BTTV and we can set standards.

On the other hand, this feature could be abused and become very annoying, in which case we would have to make it optional, which renders the feature useless.

So yeah, in theory, it's a good idea, in practice, I think it'll be used more for bad than good.

**Comment by Toocanzs** [comment]
I don't see how optional makes something useless. Most of the things BTTV provides are optional, right? 

In regards to it being used to annoy mods, I don't think that's really a problem, seeing as if you are spamming it, then you are spamming mods, and they can just time you out. 

Worst case some people are annoyed by it and either turn it off in the settings or time out the annoying people. 

Best case, streams with only a few mods who aren't paying as much attention get notified when some spammer is ruining the chat, or any other nuisances. 

The way I came up with this idea is when I was watching an Overwatch tournament rebroadcast, and the chat was mostly dead because no one cares to talk about rebroadcasts except for a few people. The mods weren't paying attention because there was really not much need to. Some guy comes along and starts spamming random things to annoy the rest of the users having a conversation, and I highlighted the username of a mod I know has the chats of a ton of streamers open, and the problem was solved instantly. 

It's kinda awkward to highlight mods names, because you might not be sure who is afk, so you may have to highlight a few. Highlighting a few only adds to the spam. "@mods" would consolidate this very well.

**Comment by voloshink** [comment]
I like this idea, although i can see how people might spam it. Making it optional could work, i suppose.

**Comment by night** [comment]
It's an interesting idea, but it would be most likely abused for spam. Making it defaulted to On would cause us too many complaints, unfortunately. Mods are welcome to add "@mods" to their highlights list if they want to opt-in to a highlight like that, but we can't force it upon users due to potential backlash.
