### ISSUE TITLE
Highlight messages sent from usernames in a list

### ISSUE THREAD

**Issue by Blagatt** [night/BetterTTV#1669]
We should be able to set a list of usernames for which the messages would be highlighted.
I saw other people suggesting to auto-highlight messages sent from followed/subscribed users, that would be quite good as well.

**Comment by voloshink** [comment]
You already can set custom highlights

![](http://i.imgur.com/HhVGHvY.png)

**Comment by Blagatt** [comment]
But that doesn't highlight messages **sent from** users set in that list, even with the curly braces

**Comment by voloshink** [comment]
I see what you mean. I think highlighting every message by a certain person ( or subs) for example could make the chat look pretty ugly, though. Maybe if we use a less bright color it could work.

**Comment by Blagatt** [comment]
I agree.

**Comment by EhsanKia** [comment]
You can though? Just put their name surrounded by parenthesis. So if you put "(ehsankia)" as a highlighted keyword, every message from the user ehsankia will get highlighted.

**Comment by Blagatt** [comment]
Oh right... I didn't see those were parenthesis (but instead curly braces, which is why it didn't work), thanks!
Now it would be interesting to change the colour of those highlighted messages as we discussed above.
And also, have an option to auto-add the user's followers and subs to that list.

Otherwise this issue can be closed.
