### ISSUE TITLE
[Feature Request] Disable/Hide Chat when going to Channel

### ISSUE THREAD

**Issue by aprimadev** [night/BetterTTV#1676]
I saw this issue here which was closed: https://github.com/night/BetterTTV/issues/1619

However, Night appears to misunderstand what I'm assuming to be the actual request. Closing the right sidebar does not actually disable chat. It merely hides it from view. This can suck on low-performance machines because on larger channels when there are 100,000 people spamming in chat, your browser/computer get laggy. However, there IS an option when clicking the chat settings button to actually "Hide Chat." This not only hides it from view, but *disables* chat until you manually re-enter the chatroom. Being able to have this enabled by default would be a much-appreciated feature to have!

**Comment by night** [comment]
Actually, you appear to not understand. The most expensive part of chat is rendering to the DOM and scrolling chat. Both of these functions do not occur when the chat is hidden.
