### ISSUE TITLE
[Feature request] auto-chat send or alert?

### ISSUE THREAD

**Issue by mopedchik1337** [night/BetterTTV#1677]
hello, please add a function alert when streamer(host) starting a giveaway. For example he writing a word and people in chat must enter this word for the win a prize. (beststreamer1337): type !win for the win. And your extension will notice me or write for me in chat !win. Thx for advance lul.

**Comment by mopedchik1337** [comment]
i found "highlight function" but i need an alert with sound or with big notification when streamer writing a !win word (or something) lul thx again

**Comment by voloshink** [comment]
set the highlight keyword for that word. You can enable the settings to receive notifications and play a sound on highlight

**Comment by mopedchik1337** [comment]
thanks for fast answer. but where i can set option to receive notifications and play a sound on highlight? I set a highlight word its working fine but idk where i can find notification alert? thx for advance

**Comment by voloshink** [comment]
in the betterttv settings
