### ISSUE TITLE
how to switch accounts on bttv?

### ISSUE THREAD

**Issue by emirupunk** [night/BetterTTV#1679]
I made a bot account for my channel and connected that acc to bttv, and now that I've switched back to my main account I cant use bttv with that account (its still managing my bot channel). I haven't been able to find any option to log out of bttv or switch which account is connected/in use. I tried uninstalling bttv on my browser and reinstalling it.

**Comment by voloshink** [comment]
im confused, are you talking about the addon or the site? why would uninstalling the addon remove you from the site. If you want to log out of the website, try removing the connecting in your twitch settings on that twitch account.
