### ISSUE TITLE
Paragraph of text in chat user is unbanned

### ISSUE THREAD

**Issue by Savb98** [night/BetterTTV#1681]
When a mod unbans a user, the text below gets posted for the other moderators instead of just "user has been unbanned by user"

http://imgur.com/a/jTNZi

**Comment by voloshink** [comment]
4Head

**Comment by EhsanKia** [comment]
I'm confused, is this still a bug or was it fixed?

**Comment by Savb98** [comment]
It's fixed for me so I closed it.
