### ISSUE TITLE
BTTV emotes are not showing, yes they are enabled

### ISSUE THREAD

**Issue by sheetzy** [night/BetterTTV#1686]
any and all bttv emotes are just not showing, they are not even in the emote menu, there is not even a tab for bttv emotes, it just says "all" i have double checked the settings and they are in fact turned on.

**Comment by Stoupedog** [comment]
As long as the `BetterTTV Emotes` setting is toggled on, you should be able to see BTTV emotes in chat. Keep in mind you also have to enable the `BetterTTV GIF Emotes` setting to see gif's. 

BTTV emotes don't show up in the Twitch emote menu, you should be able to use them by typing the emote name in chat, or you can enable the BTTV Emote Menu in settings.

<img src="https://i.imgur.com/L4WyKer.png">
<img src="https://i.imgur.com/wfb1zo4.png">
