### ISSUE TITLE
BTTV Emotes made by users with localized names will not link correctly from chat

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#1687]
The emote ["GoldChamp"](https://manage.betterttv.net/emotes/57d73be3f72aaebc3486c6e2) was uploaded by "fishnothing" with the localized username "匚丹丅" but clicking the emote will link you to https://twitch.tv/匚丹丅 which doesn't work.

![image](https://cloud.githubusercontent.com/assets/7132646/19614925/35bd393a-97bf-11e6-9ce7-2df4fae6053c.png)

**Comment by EhsanKia** [comment]
Semi relevant request, can we make it so clicking on BTTV emotes goes to the emote page? From there users can go to the creator's channel if they want to, but it's very useful being able to access the emote directly. It promotes emote sharing and quickly using emotes you like.

**Comment by EhsanKia** [comment]
Hmm, this is actually don't server-side so you would need to fix it in the API, night.

https://api.betterttv.net/2/channels/redkangarew

The same `return display_name.toLowerCase() === name ? display_name : name.capitalize()` that we use everywhere I guess.

**Comment by EhsanKia** [comment]
As mentioned above, I can bypass this issue entirely by linking people straight to the emote page (from where they can go to the user's channel).

Example: https://manage.betterttv.net/emotes/56f098f077f1eeb534a226ed

This works great, the only issue is you NEED to be oauthed to access that page... So that's a really bad user experience.

**Comment by AlcaDesign** [comment]
This bug still has not been fixed.

**Comment by night** [comment]
it actually has been

**Comment by AlcaDesign** [comment]
I beg to differ. I saw someone use another emote created by the same user and it still linked to https://twitch.tv/匚丹丅

**Comment by night** [comment]
You would need to be more specific as to what emote and where

**Comment by AlcaDesign** [comment]
The emote ["goldenLUL"](https://manage.betterttv.net/emotes/579e404e63b6f48c20f51213) by [fishnothing AKA "匚丹丅"](https://www.twitch.tv/fishnothing) used in some channel other than mine, yours, and fishnothing's, possibly as a personal emote, shortly before I made this comment: https://github.com/night/BetterTTV/issues/1687#issuecomment-260236300.

**Comment by night** [comment]
should be fixed
