### ISSUE TITLE
Add Speed controls to VOD playback

### ISSUE THREAD

**Issue by argash** [night/BetterTTV#1688]
It would be a HUGE boon to streamers if you could [add this](https://www.reddit.com/r/Twitch/comments/58q29k/speed_controls_for_vod_playback_would_be_nice/d92wrkl/) to BTTV so that we could more quickly playback our VODs looking for highlights.

**Comment by EhsanKia** [comment]
I plan on adding this feature to my [TwitchPlayerPlus](https://github.com/EhsanKia/TwitchPlayerPlus) addon. Not sure if we'll ever merge those into BTTV, but playback rate is something I care very much and definitely want, too.

I watch a lot of youtube videos at 1.25 or 1.5 myself so I would use this a lot. I'll also put the respecting hotkeys of shift+> and shift+<.

**Comment by night** [comment]
this was added a while ago
