### ISSUE TITLE
Mod Tools - Ban Option

### ISSUE THREAD

**Issue by LinksMistress** [night/BetterTTV#1691]
I moderate for a few channels on Twitch and myself and several other mods cannot use the ban option provided with BTTV (the menu opened when clicking on a name in chat). All other options (purge, timeouts, permits) work without issue but we cannot ban. We've tried shifting around settings but we cannot seem to use this button. 

If there is a certain setup that we should have, please let us know. I'm not sure if it's a compatibility issue between BTTV and Twitch because we never had issued and within the last month, multiple mods have reported the same issues just with banning.

**Comment by Slikrick** [comment]
I can not reproduce what you are describing. Perhaps try clearing your cache/cookies and report back whether there is still an issue. Also there is another option related to mod cards called "Mod Card Keybinds" which would let you simply press "b" to ban someone after opening up the modcard.

![ban_gif](http://imgur.com/lFPubYo.gif)

**Comment by LinksMistress** [comment]
I have cleared my cache and cookies, the button (as depicted in your clip) still isn't working. Attempted to clear everything and reinstall bttv, that also didn't work. However, the keybinds work so this gives me the tools I need to moderate. I appreciate your assistance.

**Comment by EhsanKia** [comment]
Do you get any errors in console or anywhere when you try to use it?

**Comment by night** [comment]
Check that you don't have any third party extensions installed that are conflicting.
