### ISSUE TITLE
Right-click mod meter improvements

### ISSUE THREAD

**Issue by forbidinjustice** [night/BetterTTV#1693]
The right-click "ban/timeout/purge" meter isn't very intuitive. It could be better designed, perhaps snapping to preset increments. It's so "fine" that it's difficult to move my mouse down and select 30 minutes, for example. I doubt anyone needs to time someone out for exactly 47 minutes. The space could be utilised for more useful options.

**Comment by EhsanKia** [comment]
For most use cases, you can use the keyboard shortcuts. P for purge which is 1 second, T for timeout which is 10 minutes, B for ban which is permanent. Those 3 cover 99% of the usecases honestly. Right click is more for when you want something more specific hence the fine grained detail. Though you can also do purge and ban pretty quickly with it too.

**Comment by forbidinjustice** [comment]
Perhaps then it would be possible to keybind the shortcuts to the right-click menu as well?  The difference is the 2-3 second delay in response when you left-click.  (I assume it's due to retrieving info about the user.)  The right-click menu responds instantly so key commands would be much faster.

**Comment by EhsanKia** [comment]
Do you have "Double-Click Auto-Complete" enabled? Try turning that off. It should be pretty instant.

**Comment by forbidinjustice** [comment]
That did speed things up a little bit, still a slight delay but nothing I can't deal with, I guess.  Thanks
