### ISSUE TITLE
Chat Messages cant be scrolled up without a mouse with scroll button

### ISSUE THREAD

**Issue by BrotUndSaft** [night/BetterTTV#1694]
Hello Dev Team,

BTTV is by far the most amazing Twitch extension I have ever seen. It makes Twitch way more exciting and those GIF-Emotes are out of the world. It makes my job of moderating many channels way easier by that interface. 

But sadly i have come across some bugs which won't let me enjoy BTTV to maximum. Followins are the bugs I have noticed. Please let me know if there is already a solution and sorry for occupying your time with this post in that case :)

1. Scrolling up a private whisper is not possible without a mouse with mid button to scroll. So I can not see older chats in the conversation.

2. If in Dark Theme, some emotes have this white margin around them and look poorly edited. So it seems like the theme has not been optimised with emotes. e.g. emote "BCWarrior"

Thank you for taking your time to reading this and keep up the good job.

Cheers,
BrotUndSaft

![bcwarrior](https://cloud.githubusercontent.com/assets/23026528/19638365/e51c5ed6-99d3-11e6-8e2a-7d453d27295b.PNG)

**Comment by night** [comment]
> Scrolling up a private whisper is not possible without a mouse with mid button to scroll. So I can not see older chats in the conversation.

Twitch controls that, not us.

> If in Dark Theme, some emotes have this white margin around them and look poorly edited. So it seems like the theme has not been optimised with emotes. e.g. emote "BCWarrior"

We do not modify emotes to look good on dark themes, sorry.
