### ISSUE TITLE
Add number of months to loyalty badge alt text

### ISSUE THREAD

**Issue by bradgrafelman** [night/BetterTTV#1697]
The alt text ("original-title") for the new loyalty subscriber badges is still just "Channel Subscriber". However, the class of the div identifies the minimum number of months (e.g. 3+ months is "twitch-subscriber-3").

Request BTTV to modify that alt text to incorporate the number of months.

**Comment by EhsanKia** [comment]
Just to be clear, it won't be exact. Anything between 3 months to 6 month will show at twitch-subscriber-3

Might may it show "Subscriber for 3+ months

**Comment by bradgrafelman** [comment]
Good point - I definitely wasn't clear about that.

**Comment by thinkpad4** [comment]
Ehsan yeah making it Subscriber for 3+ months would be best or make it the range, Subscriber for 3 - 6 months

**Comment by night** [comment]
Twitch shows "1-Year, 2-Year Subscriber".. we should duplicate this

**Comment by EhsanKia** [comment]
Where is that? And yeah, I'll probably write a custom string for each of the 5 possibilities.

**Comment by GavoTrav** [comment]
I'm assuming the text comes from here. https://badges.twitch.tv/v1/badges/channels/23161357/display

**Comment by EhsanKia** [comment]
Oh nice, that makes my life much easier. I think they recently changed that because I remember it didn't use to show the proper text there.
