### ISSUE TITLE
z-index: 5 emotes conflict with bits panel (Holiday CSS)

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#1700]
![image](https://cloud.githubusercontent.com/assets/7132646/19674112/429febc8-9a4b-11e6-8fd4-1f8df638303b.png)

**Comment by night** [comment]
i dunno man, the emotes make the cheers popup seem more fun

**Comment by AlcaDesign** [comment]
You're right, I'm sorry.
