### ISSUE TITLE
Emotes are over "More messages below." button.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1702]
![image](https://cloud.githubusercontent.com/assets/14076068/19696660/cd4ba71c-9af0-11e6-8feb-209d2e60e6f7.png) 
This may cause accidental clicks on emotes instead of button.

**Comment by SouthApple** [comment]
I saw this as well. It's not locked to Twitch, Sub, or BTTV based emotes.

**Comment by thinkpad4** [comment]
Noticed it as well
