### ISSUE TITLE
Twitch Chat Avatars

### ISSUE THREAD

**Issue by Hishighness420** [night/BetterTTV#1703]
Hi, first just wanna say love TTV. I was thinking it might be cool if there was an option to show people's Twitch avatars next to their name in chat, much like the mod sword and turbo and sub emotes show there now. Dunno if that's even possible but I thought it would be nice, add some color and creativity to the chat.

Thanks for your time.

**Comment by night** [comment]
It's unfortunately not very practical, sorry. There's already too little space due to the amount of badges people have.
