### ISSUE TITLE
whispers

### ISSUE THREAD

**Issue by BaddKitty79** [night/BetterTTV#1706]
When I want to send a whisper in twitch chat to someone it automatically ignores the user and i have to return to their name to unignore them. Is there a fix for this? and i'm not using the /w in chat either I'm clicking on the name in chat and selecting the whisper icon and when i do this it automatically ignores them in whispers and chat and i have already checked to make sure i'm not selecting a different icon like ignore which is right beside it...just a heads up i know of others that have this issue

**Comment by EhsanKia** [comment]
I can't reproduce unfortunately. The left icon properly opens a whisper on my end, the right one properly ignores them.

**Comment by night** [comment]
You might be using other third party extensions for Twitch, so try disabling them and seeing if it still happens.
