### ISSUE TITLE
Mod Ban & Timeout buttons

### ISSUE THREAD

**Issue by Frosttyn** [night/BetterTTV#1707]
A lot of mods I know, including myself, have moment when we hit the ban/timeout button on accident. Would like a setting to turn them off and on.

**Comment by EhsanKia** [comment]
Which ones? The ones on the left of the chat lines?

It's right under chat settings > mod tools > mod icons

![screenshot 2016-10-27 at 8 59 38 am](https://cloud.githubusercontent.com/assets/1619970/19775002/ca4e8140-9c23-11e6-9f97-a760ef55ff66.png)

**Comment by Frosttyn** [comment]
50 Shades of Derp
