### ISSUE TITLE
Beam.pro support, feature request

### ISSUE THREAD

**Issue by Nixxen** [night/BetterTTV#1708]
Beam.pro is growing, but still doesn't have any custom emotes apart from the beam integrated emotes.
There's the PolyExtend plugin that will bring the Twitch emotes over to beam, but that's pretty much it (and PolyExtend breaks Twitch chat, so there's that...).

This is a three-way feature request.
1: Adding BetterTTV functionality to Beam.Pro chat
2: Adding Twitch.tv emote functionality to Beam.pro chat
3: Adding Beam.Pro emote functionality to Twitch.tv chat

Before anyone goes ahead and say the obvious - Yes, I know this is called Better Twitch TV, and not Better Beam Pro. It is however the best emote database around, and pretty much everyone has it installed already.

**Comment by night** [comment]
We do not have enough time to support more than just Twitch, sorry.
