### ISSUE TITLE
Preserve srcset / 2x subscriber loyalty badges on hidpi screens

### ISSUE THREAD

**Issue by tmtrademark** [night/BetterTTV#1709]
Howdy.

Now that loyalty badges are a thing, it would be great if BTTV preserved or implemented the higher resolution icons on hidpi screens. Currently when BTTV creates the `subscriber_badges` `<style>` element in `helpers.js` it just uses the 1x version of the image. Can a media query be added to use the other images as well?

**Comment by EhsanKia** [comment]
That's my bad. I was lazy when I implemented the badge api and only included 1x.
I'll add 2x and 3x support.
