### ISSUE TITLE
Chat doesn't stay paused when typing in the chat box

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#1710]
After scrolling up the chat resumes scrolling when typing in chat box

**Comment by EhsanKia** [comment]
Not sure if this is a bug or as intended. When you're typing in chat, you wanna make sure you've caught up with chat maybe?

**Comment by thinkpad4** [comment]
But what if you are responding to something that has flew by and need to respond to the question by referring to it?  Having to keep scrolling up to it when responding is annoying

**Comment by AlcaDesign** [comment]
I've been getting this for a while. Pressing any key even when not focused on the chat input will make the chat scroll back down.

**Comment by night** [comment]
PRs are welcome

**Comment by EhsanKia** [comment]
I don't mind fixing this if it's a confirmed bug.

**Comment by thinkpad4** [comment]
I don't remember it doing that before so I would call it a bug
