### ISSUE TITLE
Better Viewer List don't work correctly

### ISSUE THREAD

**Issue by EEman** [night/BetterTTV#1713]
some days ago Better Viewer List stop working
button doesn't change

**Comment by EhsanKia** [comment]
Works fine on my end. Can you confirm that it's still turned on in the options, and that you don't have any other conflicting extensions installed (such as FFZ)?

**Comment by hieblmedia** [comment]
I have noticed the issue also a few days ago.
Browser: Chrome 54.0.2840.71 m (Win10 64bit)

I have disabled alle Chrome extensions, except BBTV.
And re-installed BBTV. But the Input Field is not visibile anymore.

**Comment by EhsanKia** [comment]
What do you mean the input field? The search bar at the top? Or the BVL button missing like EEman was having?

**Comment by hieblmedia** [comment]
Yes, i mean the search bar at the top of the viewer list.
I have tried the Firefox Extension and the searchbar is also not visible.

**Comment by EhsanKia** [comment]
Can you take a screenshot of what you see?

**Comment by hieblmedia** [comment]
Sure, see: http://screencast.com/t/mrwcG4VW4CI

**Comment by EhsanKia** [comment]
Well that's not BVL, that's the old player list.

Can you check that you indeed have it enabled in your settings? "Better Viewer List"
Can you then check if the button you click to open it has 3 bars or 4?

**Comment by hieblmedia** [comment]
The option is definitely enabled. Also toggled multiple times and reloaded site. 
Also checked other options can be toggled. This was successfully.
The button has 3 bars.

Also checked on Opera now - same result.
Maybe this has stopped working after the last layout changes on twitch.

**Comment by EhsanKia** [comment]
Something is definitely preventing the button from showing up. The issue is it works fine on my end so it's hard for me to debug an issue I can't reproduce. My guess though is that it has to do with the fact that your browser is set to German.

That's actually probably the issue, right at https://github.com/night/BetterTTV/blob/master/src/js/features/better-viewer-list.js#L231
`$('a.button[title="Viewer List"]')` probably fails because you have german title on that button.

I'll try to write a workaround for it then.

**Comment by hieblmedia** [comment]
I have tested now in some other languages.
The title attribute is translated. So the button only can replaced in english with this selektor.
FYI: You can find the language swtich link on the small Navigation "More at Twitch" on left sidebar.

An alterantive selector can be (tested in console):
`$('.chat-buttons-container a.button:has(.svg-viewerlist)');`
or with including the old one as fallback:
$('a.button[title="Viewer List"], .chat-buttons-container a.button:has(.svg-viewerlist)').eq(0);

Thanks in advance.

**Comment by EhsanKia** [comment]
Yeah I'll use a different one. Didn't anticipate different languages. Thanks, will fix tonight.
