### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tciaran** [night/BetterTTV#1715]
I would like to suggest a feature to disable the notification in chat that "Your friend has started watching the stream".
Some people enjoy hanging out and lurking and don't necessarily want to use anon mode because they may be in multiple channels, just to avoid being called out.

**Comment by EhsanKia** [comment]
I believe that feature is attached to the friend list's "Share My Activity" setting:

![](http://i.imgur.com/gYcj2uG.png)

**Comment by tciaran** [comment]
Oh. Thanks EhsanKia, guess I missed that one!
