### ISSUE TITLE
Request: Hide/Diable "Friends Joined the Channel"

### ISSUE THREAD

**Issue by DoctorMontalban** [night/BetterTTV#1716]
It's an annoying new feature letting you know your friend has joined the channel you're watching. The ability to toggle that off would be awesome, if possible. 

Great work, great tool. Keep up the awesome stuff.

**Comment by thinkpad4** [comment]
Wait, that's a thing?

**Comment by EhsanKia** [comment]
Yes, it's a new feature added a few days ago.

If someone on your friend list starts watching a stream that you are watching, AND they have "Share Activity" enabled, a small message in chat says "X has started watching this stream".

If you don't use the friend feature, or if your friends don't share their activity, then you will never see this.
