### ISSUE TITLE
[Feature Request] Limit amount of badges

### ISSUE THREAD

**Issue by Owltruism** [night/BetterTTV#1717]
I think it would be good if there was an option to limit other people's badges / icons to 1. (2 if they're a mod). Because all these badges (prime, bits, and now loyalty badges) are getting out of hand. It makes chat too cluttered.

**Comment by EhsanKia** [comment]
With a couple rare exceptions, the maximum emotes you can have in a chat right now is 3: Mod, sub, bits/prime).

As you mentioned, mod and sub are probably needed. As for the third, if you use the "Disable Bits" option in BTTV, it'll hide bit badges, though not the prime one. I doubt we'll put an option just for that, but feel free to use Stylish extension to specifically hide that badge. It's a fairly easy css line to do that.
