### ISSUE TITLE
Subscriber filter for the viewer list

### ISSUE THREAD

**Issue by EcstasyMuffin** [night/BetterTTV#1720]
Hey I just thought it would be good addition to the ways you can filter through who is watching. This would be especially useful with large streams with thousands of people. Thank you.

**Comment by AlcaDesign** [comment]
The API used to get the list of people in the chat doesn't explicitly return subscribers. Only people who have typed in chat post-page-load would be able to be filtered in this way. It's not reliable because of that.

**Comment by EcstasyMuffin** [comment]
Oh well. I just figured it was worth a shot.
