### ISSUE TITLE
Automatic Theatre Mode screws up fullscreen on Chrome.

### ISSUE THREAD

**Issue by thesaderic** [night/BetterTTV#1721]
When it's activated and I go fullscreen it shows like this.
<img width="960" alt="screenshot 2016-11-01 22 48 58" src="https://cloud.githubusercontent.com/assets/23202660/19912950/71dc3eb0-a085-11e6-8273-5694cd1ffc93.png">

After I deactivate it and reload the page it works normally.
<img width="960" alt="screenshot 2016-11-01 22 50 28" src="https://cloud.githubusercontent.com/assets/23202660/19912975/a0eeaba2-a085-11e6-866d-d4feb0a5e31a.png">

PS: it also happens if you go to theatre mode before going fullscreen too even with automatic theatre mode off.

**Comment by night** [comment]
If you test on default Twitch, this happens there. Therefore, this is a Twitch issue.
