### ISSUE TITLE
Better twitch messes up display resolution

### ISSUE THREAD

**Issue by MrNinja418** [night/BetterTTV#1722]
When BTTV is enabled, it makes my display resolution different than the video resolution of the broadcast. This causes black bars to appear at the top and bottom of the stream. When BTTV is disabled it goes away completely. I've also tried this on different browsers, so i'm assuming it's a BTTV problem. Not sure if this is a known issue, but if not please consider trying to fix it.

**Comment by AlcaDesign** [comment]
Duplicated of #1719
