### ISSUE TITLE
Save Settings Button

### ISSUE THREAD

**Issue by FaintWhispering** [night/BetterTTV#1725]
It would be much appreciated if there was simply a button to save settings rather than it autosaving, only to come back later to find that the settings had reset. It's a hassle to reinput them. Thank you.

**Comment by AlcaDesign** [comment]
Probably need to find out why your settings are disappearing, but there is a way to backup and import your settings in the "Backup/Import" tab of the BTTV settings.

**Comment by FaintWhispering** [comment]
Oh, thank you.

**Comment by night** [comment]
Configure your browser to not clear cookies on close in the browser settings to fix the not saving issue.
