### ISSUE TITLE
Stream continues to play after leaving the channel.

### ISSUE THREAD

**Issue by aroboto** [night/BetterTTV#1729]
Tested without BTTV loaded and was not able to reproduce. Recorded video of the bug, only addon enabled was BTTV and browser cache was cleaned before. Bug occurs when you click on a stream in the browse channels page and quickly click on browse channels again.

https://streamable.com/ct7x

The playback only stops on refresh.

**Comment by night** [comment]
This is a race condition on Twitch's site, not something we can fix. We do not touch the Twitch player.
