### ISSUE TITLE
Feature Request: Auto-complete streamer-name

### ISSUE THREAD

**Issue by FurRiffic** [night/BetterTTV#173]
If you just join a stream, the streamer him/herself will probably not have talked yet in chat, but you would most likely want to greet him/her with their name.
I would like to request that, next to the normal `<tab>` auto-complete list, filled with people who have chatted, it also by default adds the name of the current streamer to that list.

A second feature that is a bit comparable with this is if you could make a list with names / words it can auto-complete for you. The way I see it, you would get a popup box similar to the blocked words / highlighted words box, in which you can type words / names that get added to the `<tab>` list in each stream, even before anyone has said a word.

**Comment by night** [comment]
The former has been implemented.

The latter will probably not be implemented as I don't think it has that many uses.
