### ISSUE TITLE
Reseting Problem

### ISSUE THREAD

**Issue by GKid94** [night/BetterTTV#1731]
When i clear the cache in Chrome and when i open Twitch it resets and turns off all the TTV options the i tweaked on, how do i keep the options on when i clear the cache? 😕

**Comment by EhsanKia** [comment]
Are you sure you're ONLY clearing cache in chrome? As in like this:

![](http://i.imgur.com/c3i9wLC.png)

BTTV settings are stored in cookies and if you clear those, your settings also get cleared. One solution would be to back them up and load them afterwards. The settings menu has a "Backup/Import" tab:

![](http://i.imgur.com/Z3gjun0.png)
