### ISSUE TITLE
Mute Specific People in Chat

### ISSUE THREAD

**Issue by jpalson** [night/BetterTTV#1736]
I would really love to see a client-side mute of specific people in chat. I would totally use this feature to its fullest extent!

**Comment by night** [comment]
You can already ignore people from the user cards and with `/ignore` in chat.

**Comment by jpalson** [comment]
:o thank you!

**Comment by AlcaDesign** [comment]
And in the cases where you cannot ignore a user, there's always the blacklist. Use parenthesis around a username to disregard that user entirely. "`(username)`"
