### ISSUE TITLE
new feature idea

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#1742]
can you disable showing the bit notification ontop of the chat now twitch just recently released a new update for bits and its really annoying

**Comment by notdom** [comment]
if I may chime in, wouldn't just hiding the div for the pinned cheer solve the problem? or does it repopulate each time a new "top" cheer is cheered?

**Comment by AlcaDesign** [comment]
Duplicate of https://github.com/night/BetterTTV/issues/1740
