### ISSUE TITLE
issue with a full screen

### ISSUE THREAD

**Issue by spell09** [night/BetterTTV#1745]
http://i.imgur.com/iHVgz84.png when i'm trying to watch in a full screen mode, some part of the screen was staying like a black bar. Instead of the place where is chat must be. Its only causes when i switch from theatre mod to full screen mode.

**Comment by EhsanKia** [comment]
Duplicate of #1721, though maybe we should fix it for Twitch since that's always what we end up doing... fixing their broken site for them.

**Comment by spell09** [comment]
sorry, didn't saw a closed topic

**Comment by night** [comment]
This was already fixed...
