### ISSUE TITLE
Blocking Recommended Channels 

### ISSUE THREAD

**Issue by ponguso** [night/BetterTTV#1752]
Make a setting that turns off the blocking of recommended channels, I like that feature from regular twitch and I don't really know why the recommended channels don't appear when using BTTV

**Comment by aroboto** [comment]
There is already a setting for this change "Featured Channels  —  The left sidebar is too cluttered, so BetterTTV removes featured channels by default" to on.

![kxlyhx0 1](https://cloud.githubusercontent.com/assets/22084203/20232979/0ae78854-a864-11e6-8e9a-8228f63965ac.png)

**Comment by ponguso** [comment]
I have it off but the recommended channels are still removed :(

[image: Inline image 2]

**Comment by aroboto** [comment]
You have to turn it on for the channels to be there.

**Comment by ponguso** [comment]
I'm sorry you had to deal with someone as stupid as me -_- thanks for your
help!
