### ISSUE TITLE
Theater mode/auto theater mode bug on macbook

### ISSUE THREAD

**Issue by mgs2master2** [night/BetterTTV#1754]
Hello there, 
I am trying to use the auto theater mode on my mac, it will go to theater mode and immediately go back, no matter what, it won't stay to that setting. 

I am using a Macbook Air 13 inch, with MacOS Siera version 10.12.1 on chrome browser on with the newest update to chrome (chrome 54.0.2840.96 64-bit)

Thank you

**Comment by night** [comment]
It sounds like you have two extensions installed that are both automatically launching theater mode, which conflicts.
