### ISSUE TITLE
Chat Filter Function

### ISSUE THREAD

**Issue by SusanTN** [night/BetterTTV#1755]
It would be nice to be able to block messages and unblock messages containing specific keywords/patterns from Twitch Chat Channels 

IE: https://loots.com/t/XXX/razer-kraken *** Learn more! *** Support the stream at https://loots.com/XXX ***

With this request I would have a input box and submit button to add a pattern along with a list box and a remove button to remove one or more patterns. Hold shift to select consecutive patterns hold control to select multiple individual patterns

In this example I could add loots.com and all messages containing loots.com would be hidden in the chat going forward. 

Would also be good for blocking bot messages or annoying users by adding their username/display name to the list. 

It would probably be best to add this on it's own tab.

**Comment by night** [comment]
There already is a blacklist in the chat settings, but it is not that intuitive at this time.. There are numerous issues open to improve the blacklist and highlight features, but they won't be added until we've rewritten the extension. You can see all the open issues at https://github.com/night/BetterTTV/issues?q=is%3Aissue+is%3Aopen+label%3Ahighlights%2Fblacklist

**Comment by EhsanKia** [comment]
Just to clarify, as Night was saying, while the interface not as clean as you suggested, this is doable right now.

Simply click the cog under chat, select "Set Blacklist Keywords", then in the input box, type "loots.com", or the name of the bot in parenthesis.

**Comment by SusanTN** [comment]
I think you do not understand, I don't want this for my channel, I want to have this ability in all channels. My request is a user function to allow the a personal filter list of things to remove from chats. Not something for the channel owner or mods only.
