### ISSUE TITLE
Can't connect my channel to discord

### ISSUE THREAD

**Issue by nerdshit** [night/BetterTTV#1758]
Hi,

I've got the problem that I only get a black screen when I want to connect bttv with my discord. Nothing happens then.
![bildschirmfoto 2016-11-14 um 11 52 12](https://cloud.githubusercontent.com/assets/23451003/20262050/d8222628-aa60-11e6-8dec-ba8aebd560fa.png)

**Comment by Aaron128l** [comment]
Works fine on my end. This page can also be accessed at: https://manage.betterttv.net/

**Comment by nerdshit** [comment]
Thank you so much Aaron! This helped me!
