### ISSUE TITLE
Bits Icon incorrectly renders in dark mode.

### ISSUE THREAD

**Issue by IndubitablyBengt** [night/BetterTTV#1759]
When using the dark mode, the bits icon, specifically the gif for a pinned bit donation was the case I observed, renders with an outline of white pixels, which it does not do in Twitch's own theatre mode:
[Dark mode](https://streamable.com/jnjn)
[Theatre Mode](https://streamable.com/skyu)
Seems like twitch has two different gifs of the icon, one for normal mode and one for theatre, and BetterTTV doesn't trigger the switch to the dark optimized set, though I could be wrong.

**Comment by AlcaDesign** [comment]
Yes, there is a light version and a dark version

Image  | Name | Min bits | Background | Scale | Link
---- | ---- | ---- | ---- | ---- | ----
![](https://static-cdn.jtvnw.net/bits/light/animated/gray/1) | grey | 1 | light | 1 | https://static-cdn.jtvnw.net/bits/light/animated/gray/1
![](https://static-cdn.jtvnw.net/bits/dark/animated/gray/1) | grey | 1 | dark | 1 | https://static-cdn.jtvnw.net/bits/dark/animated/gray/1
![](https://static-cdn.jtvnw.net/bits/light/animated/purple/1) | purple | 100 | light | 1 | https://static-cdn.jtvnw.net/bits/light/animated/purple/1
![](https://static-cdn.jtvnw.net/bits/dark/animated/purple/1) | purple | 100 | dark | 1 | https://static-cdn.jtvnw.net/bits/dark/animated/purple/1
![](https://static-cdn.jtvnw.net/bits/light/animated/green/1) | green | 1000 | light | 1 | https://static-cdn.jtvnw.net/bits/light/animated/green/1
![](https://static-cdn.jtvnw.net/bits/dark/animated/green/1) | green | 1000 | dark | 1 | https://static-cdn.jtvnw.net/bits/dark/animated/green/1
![](https://static-cdn.jtvnw.net/bits/light/animated/blue/1) | blue | 5000 | light | 1 | https://static-cdn.jtvnw.net/bits/light/animated/blue/1
![](https://static-cdn.jtvnw.net/bits/dark/animated/blue/1) | blue | 5000 | dark | 1 | https://static-cdn.jtvnw.net/bits/dark/animated/blue/1
![](https://static-cdn.jtvnw.net/bits/light/animated/red/1) | red | 10000 | light | 1 | https://static-cdn.jtvnw.net/bits/light/animated/red/1
![](https://static-cdn.jtvnw.net/bits/dark/animated/red/1) | red | 10000 | dark | 1 | https://static-cdn.jtvnw.net/bits/dark/animated/red/1
![](https://static-cdn.jtvnw.net/bits/light/animated/gold/1) | gold | 100000 | light | 1 | https://static-cdn.jtvnw.net/bits/light/animated/gold/1
![](https://static-cdn.jtvnw.net/bits/dark/animated/gold/1) | gold | 100000 | dark | 1 | https://static-cdn.jtvnw.net/bits/dark/animated/gold/1

**Comment by EhsanKia** [comment]
Honestly, I don't even know how pinned cheers work, and I think this one might be annoying to fix... If someone else who understands this wants to give it a try...

**Comment by night** [comment]
Fixed in beta
