### ISSUE TITLE
To show nickname in Chinese and English at the same time

### ISSUE THREAD

**Issue by tonnyyeh345** [night/BetterTTV#1761]
In original chat room, it will show both of them. But in BetterTTV's chat room it can't show them at the same time.

**Comment by xgerhard** [comment]
Duplicate #1488

**Comment by EhsanKia** [comment]
We only show one of the two, as we don't like how cluttered the chat looks with both showing.

If you click on someone's name, the popup shows both the username and their chinese name.
You can toggle which one you see with "Disable Localized Names", but there is no way to show both in chat.
