### ISSUE TITLE
when clicking on names it will pick a random button (timeout purge ban ignore) 

### ISSUE THREAD

**Issue by htownlax25** [night/BetterTTV#1762]
I have noticed many times now as well as a few co mods that use betterttv when I click on a users name it will pick a random action. I have no idea how or why this happens but if anyone had any advice that would be awesome ! please email me at leafstk@gmail.com with questions

**Comment by night** [comment]
I cannot reproduce this. Make sure you're not using additional browser extensions that conflict with ours.

**Comment by htownlax25** [comment]
Such as?
