### ISSUE TITLE
Disabling Twitch's "cut off audio" reminders in videos.

### ISSUE THREAD

**Issue by KristiyanDimov** [night/betterttv#1764]
When you want to rewatch a previous saved stream through the videos tab Twitch always reminds you that portions of the audio have been cut off due to copyright. This cutting is an automated system and it does this to almost every video. After the first few dozen of those reminders they start to get annoying. Maybe have it as an option or an "always turned-on feature" to remove those reminders.

**Comment by whitecrownclown** [comment]
@night It seems Twitch saves a boolean in the sessionStorage that prevents the notification from showing up once you dismiss one. Should we close this issue?

**Comment by night** [comment]
It looks like Twitch has started doing this natively, making this request obsolete.
