### ISSUE TITLE
Ability to pop out the chat replay in VODs

### ISSUE THREAD

**Issue by Kingbigb2** [night/BetterTTV#1766]
I like having the chat popped out on my second monitor. But, this is not a feature in BTTV or Twitch. It would be useful if you were able to pop out the chat replay you get when you watch a VOD.

**Comment by ryankhart** [comment]
I second this.

**Comment by night** [comment]
looked into this and it's not easily possible.. we'd basically have to rebuild their entire chat replay system, which I don't think we want to do.
