### ISSUE TITLE
Twitch scrolls down when exiting fullscreen if channel header is disabled

### ISSUE THREAD

**Issue by IndubitablyBengt** [night/BetterTTV#1771]
When exiting fullscreen mode with the new channel headers, Twitch scrolls down:
https://streamable.com/8lhb
When this is turned off, you can see that when exiting fullscreen, Twitch is programed to scroll down to hide the banner:
https://streamable.com/o0cb
As you can see, for a moment it is at the true top of the page before it scrolls itself back to hide the banner.
So, when the banner is disabled, this autoscroll is unnecessary and simply scrolls the player up out of view.

**Comment by night** [comment]
🤔 that's kinda lame. @EhsanKia want to take a look?

**Comment by EhsanKia** [comment]
I can replicate it. It's a bit annoying, though not the end of the world. I'll see if there's a clean fix...
