### ISSUE TITLE
Disable Bit Pinning

### ISSUE THREAD

**Issue by CmdrStryker** [night/BetterTTV#1773]
When someone sends a certain amount of bits (amount set by the streamer) it pins the message to the top of the stream. I would like an option to remove it because I find it extremely annoying. The only current way to turn that off is to turn bits off completely, which I don't want to do.

**Comment by AlcaDesign** [comment]
[D](https://github.com/night/BetterTTV/issues/1765)[u](https://github.com/night/BetterTTV/issues/1763)[p](https://github.com/night/BetterTTV/issues/1756)[l](https://github.com/night/BetterTTV/issues/1751)[i](https://github.com/night/BetterTTV/issues/1750)[c](https://github.com/night/BetterTTV/issues/1749)[a](https://github.com/night/BetterTTV/issues/1746)[t](https://github.com/night/BetterTTV/issues/1742)[e](https://github.com/night/BetterTTV/issues/1740)
