### ISSUE TITLE
Modify size of text field on whisper chat

### ISSUE THREAD

**Issue by wily-wolf** [night/betterttv#1774]
I often write long messages on whisper chat and I can't properly view what I am writing cause after 1 line of text, the space in the text field ends. 
Is it possible to add a custom text field so we can change the size while we are writing? Even only in vertical direction would be great

**Comment by XxBonf1r3xX** [comment]
+100.

**Comment by XxBonf1r3xX** [comment]
In the meantime you can give a try for my Stylish script. :)

https://userstyles.org/styles/136190/make-whisper-window-bigger-on-twitch
