### ISSUE TITLE
Remove pinned bits

### ISSUE THREAD

**Issue by QuirionKats** [night/BetterTTV#1779]
I'd love to permanently get rid of the pinned cheers.

**Comment by AlcaDesign** [comment]
[D](https://github.com/night/BetterTTV/issues/1765) [u](https://github.com/night/BetterTTV/issues/1763) [p](https://github.com/night/BetterTTV/issues/1756) [l](https://github.com/night/BetterTTV/issues/1751) [i](https://github.com/night/BetterTTV/issues/1750) [c](https://github.com/night/BetterTTV/issues/1749) [a](https://github.com/night/BetterTTV/issues/1746) [t](https://github.com/night/BetterTTV/issues/1742) [e](https://github.com/night/BetterTTV/issues/1740) [d](https://github.com/night/BetterTTV/issues/1773)

**Comment by QuirionKats** [comment]
Okay, should've looked for duplicates, my bad.
On that note; all the other "tickets" with this same suggestion have been closed for either a reason I don't know or "you can already hide bits".

I'd like to hide ONLY the pinned bits; I just don't want them to be pinned.
I still want them to appear in chat.
