### ISSUE TITLE
Bits not showing in chat.

### ISSUE THREAD

**Issue by buddhaPJS** [night/BetterTTV#1783]
I have tried clearing my cache and cookies, checked BTTV settings to make sure that "Hide Bits" was turned off and everything is set as it should be. Was able to see bits all day today until about 5pm and now bits no longer show in chat even when i cheer them myself. 
Using google chrome. When I uninstall or disable BTTV bits show up just fine.

**Comment by EhsanKia** [comment]
Can confirm it's really broken right now, looking into it.

**Comment by buddhaPJS** [comment]
every time i join a channel i receive this notice "BetterTTV encountered an error reading chat. The developer has been sent a log of this action. Please try clearing your cookies and cache.
BetterTTV v6.8 Loaded." 
On Google Chrome Extensions it says that I have v6.9 Installed. I don't know if this helps.

**Comment by buddhaPJS** [comment]
is there any way you can explain this to me as a layman in coding... i am able to open up inspect with Chrome and look at the coding informatino but i dont understand what I need to change or how to get to the screen cap that you posted for what I believe? was the cheer fix?

**Comment by EhsanKia** [comment]
I've already found the problem and fixed it. Gotta wait for it to be pushed to everyone though. That might take some time, sorry about that.

**Comment by buddhaPJS** [comment]
no worries, thank you for the quick response
