### ISSUE TITLE
The issue remains.

### ISSUE THREAD

**Issue by zTKS** [night/BetterTTV#1788]
My issue was claimed to be invalid yet when disabling betterttv the issue is fixed. A bit fast to mark is as invalid.

This is with the chrome extension. I have also tested this with every other extension disabled and the issue is still there.

"I've noticed as of recent that bit icons next to names and possibly even the icon to send bits all are gone or disappear when hovered over, even with the 'Hide Bits' option turned off."

**Comment by night** [comment]
I tested locally and cannot reproduce. Clear your cookies and cache and see if it fixes your problem, or provide us with reproduction steps.

**Comment by EhsanKia** [comment]
Can you describe the issue in more detail, and maybe with images/gifs?

So the bit badge shows, and when you hover, it disappears? Same with this? ![](http://i.imgur.com/QuBzffR.png)

That honestly doesn't make sense as badges have no hover effects.

**Comment by zTKS** [comment]
The icon you have shown in that image is not there at all.

Badges next to people's names are there until you hover over them, then they disappear.

The only thing bits related that seems to work correctly is when the message with the bits in pinned to the top of the chat.

I will prove gifs and images soon.

**Comment by EhsanKia** [comment]
Are you completely sure this is OFF?
!()[http://i.imgur.com/LLeJrg4.png]
