### ISSUE TITLE
Request: Message button under stream player

### ISSUE THREAD

**Issue by wily-wolf** [night/BetterTTV#1794]
It would be nice to have a quick "send message" button like the host one under twitch player. Since twitch deleted the quick toggle, it's more difficult to send a private message directly to the streamer.

**Comment by EhsanKia** [comment]
Seems like Twitch is slowly killing the message system and replacing it with whipsers. Chances are it'll be gone soon honestly.

**Comment by wily-wolf** [comment]
Yeah, I have the same feeling, but it's always the primary form of communication with some streamers, since they blocked whispers from strangers (most big streamers do that) and let people message them. Then a lot of whispers are difficult to manage without a dedicated page.

**Comment by night** [comment]
messages are deprecated afaik.
