### ISSUE TITLE
Clicking a name in chat expands too much and is un-removable 

### ISSUE THREAD

**Issue by nighthawkj2** [night/BetterTTV#1799]
https://gyazo.com/08e55dcca13c9ec2276d4cdaec9bcda0

**Comment by AlcaDesign** [comment]
Same here 
![image](https://cloud.githubusercontent.com/assets/7132646/20732842/2a549b3c-b656-11e6-8728-3af96953926f.png)

**Comment by EhsanKia** [comment]
Can confirm, update from Twitch broke our mod cards, I'm at work now but I'll try to get a fix in asap unless someone else can fix it faster.

**Comment by thinkpad4** [comment]
Will you make them small like they were?  Not having that giant image, right?

**Comment by s-alexsinger** [comment]
EHSAN PLEASE FIX

**Comment by evindtv** [comment]
same

**Comment by EhsanKia** [comment]
Fixed.
