### ISSUE TITLE
Emote Icon Drawer disappeared

### ISSUE THREAD

**Issue by renaissance247** [night/BetterTTV#180]
Sometime in the last couple days the Icon under the chat to click on and popup a box with all the emoticons has disappeared I went to the Settings and it's still set to On, so I don't know what the problem is. I've turned it off and reloaded, but nothing. Is this a glitch? Was it removed? Is there an update to the extension I need? Everything else seems to be working fine.

**Comment by teak** [comment]
duplicate of #160
