### ISSUE TITLE
Moderator actions do not display who did it if they type out /timeout

### ISSUE THREAD

**Issue by MiniorDebry** [night/BetterTTV#1802]
First was done without BTTV  in incognito in a /timeout second with BTTV http://i.imgur.com/Uypc46H.png using mod card works fine but without it using /p, /t, and /timeout do not show the person who TO'd them.

**Comment by thinkpad4** [comment]
I noticed that too

**Comment by EhsanKia** [comment]
Could you explain the setup a bit more. So when you use /timeout in BTTV, the other people with BTTV won't see the timeout? Or no one sees it, bttv or not?

**Comment by MiniorDebry** [comment]
sorry on delay was busy, basically if you have BTTV and do a a /timeout others with BTTV can not see you timed them out, effectively bypassing moderator actions for BTTV users. I'll need to test it again to see if non BTTV people also see it or not

**Comment by night** [comment]
I do not see how this could be a BetterTTV issue the way you've described it. Please provide a detailed repro and clear explanation if you're able to.

**Comment by MiniorDebry** [comment]
Instead of trying to explain it, I just recorded what I did to test it using incognito mode on chrome. https://www.youtube.com/watch?v=wBYTM7Lh4K4 This should show how it works better than me trying to explain it.
