### ISSUE TITLE
Pinned cheers when entering channel cannot be dismissed

### ISSUE THREAD

**Issue by Apolloftw** [night/BetterTTV#1805]
When I enter a channel and try to dismiss a pinned bits 
cheers message it cannot dismiss itself. It requires a mod to remove it or a new pinned cheers message when I am in chat for it to be able to be dismissed by me.

**Comment by EhsanKia** [comment]
I'll look into this.

**Comment by EhsanKia** [comment]
Will fix this tonight, still haven't had time unfortunately will all the other things breaking recently.

**Comment by breon** [comment]
You are a saint among men. <3
