### ISSUE TITLE
Chat broken

### ISSUE THREAD

**Issue by aule10** [night/BetterTTV#1808]
The chat is really broken. first i had problem getting the stream to get bigger, disabled BTTV clicked the chat away, enabled it, the stream is now big, Now i cant get the chat back.

**Comment by aule10** [comment]
Even more problems have come up. When i try go fullscreen the window is the same size with a big black box around it.

**Comment by EhsanKia** [comment]
Should be fixed now.

**Comment by night** [comment]
duplicate of #1808
