### ISSUE TITLE
Alpha chat badges affects coloring of all chat badges

### ISSUE THREAD

**Issue by Slikrick** [night/BetterTTV#1813]
Previously it didn't modify the sub badge coloring, so the icons would show up correctly colored: ![](http://i.imgur.com/MthzVMA.png)
![](http://i.imgur.com/FdvJLrx.png)

Also affects my bttv badge: ![](http://i.imgur.com/zY2A500.png)

This means the original color of the badge shows up correctly in dark mode, but is inverted on light mode.

**Comment by EhsanKia** [comment]
probably need to make this CSS rule more specific
https://github.com/night/BetterTTV/blob/master/src/css/betterttv.css#L304

or change something here:
https://github.com/night/BetterTTV/blob/master/src/js/chat/helpers.js#L749
or here:
https://github.com/night/BetterTTV/blob/master/src/js/chat/templates.js#L8

**Comment by EhsanKia** [comment]
I can't reproduce this.
