### ISSUE TITLE
Chat overlapping stream window

### ISSUE THREAD

**Issue by stefazenon** [night/BetterTTV#1816]
Since the new chrome update and twitch implementation that being if you scroll down, the stream window becomes a black box while the chat is fully extended. When the chat is is fully retracted the stream becomes small to fit the window and if you fullscreen the stream it stays like that. if you hide chat completely it does nothing to fix it!
![bug](https://cloud.githubusercontent.com/assets/24326065/20854890/a147bc74-b8ef-11e6-82dc-59e7b48b2cd8.png)
![bug2](https://cloud.githubusercontent.com/assets/24326065/20854909/d454fcc6-b8ef-11e6-9929-c62311d7c31f.png)

**Comment by stefazenon** [comment]
![bug3](https://cloud.githubusercontent.com/assets/24326065/20855052/fa9b78a0-b8f0-11e6-98b1-190fd3ce4aa5.png)

**Comment by voltaek** [comment]
I'm having a similar issue where chat is fighting with theater mode

**Comment by Houdini7** [comment]
Ditto. Hiding chat leaves the video un-changed in size in theater mode, and shows parts of the underlying background.

**Comment by EhsanKia** [comment]
Should be fixed now.

**Comment by night** [comment]
duplicate of #1806
