### ISSUE TITLE
disable channel header

### ISSUE THREAD

**Issue by macxron** [night/BetterTTV#1818]
Hi, I have a problem with disable channel header function, when I click it to activate it, its changes the channel header to a white box and does not disable it, please help, I attach a screen shot of the issue

![dd](https://cloud.githubusercontent.com/assets/24350096/20857047/f5c2f170-b920-11e6-8e51-b05207751b68.jpg)

**Comment by EhsanKia** [comment]
Yes, as you can see my the recent issues, a lot of things broke in the latest update. We're working to fix them.

**Comment by EhsanKia** [comment]
Should be fixed now.
