### ISSUE TITLE
BTTV Fullscreen bug

### ISSUE THREAD

**Issue by AstralBlader** [night/BetterTTV#1820]
while in fullscreen the videoplayer switches as normaly to fullscreen but the Video itself stays at first the normal size, then it rescales to a messed up resolution... here you can see how it looks like:
https://cdn.discordapp.com/attachments/191563660718505985/254576571589984256/unknown.png
(the top part of the video thats black is just the offset of my 2 monitors, on the screen the video alligns just fine to the top of the screen; the bottom part and the left and right side has those issues)
Only fix: disabling BTTV from addons ...
Using chrome.

**Comment by AstralBlader** [comment]
Video stats of twitch showing the normal values ...
But feels like the MaxScale is set to video's resolution

**Comment by naymikm** [comment]
I too have the same exact bug

**Comment by night** [comment]
duplicate of #1810
