### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by faatipuskevit** [night/BetterTTV#1825]
While the bttv is enabled i cant watch streams at fullscreen. It doesnt go bigger than as I show in the screenshot. If you need any other information i can give it. Just tell me how to do it. Have a nice day.
![screenshot taken with print screen](https://cloud.githubusercontent.com/assets/7822906/20861669/b7ca2baa-b9a6-11e6-9126-91e872a567bc.png)

**Comment by EhsanKia** [comment]
Should be fixed now.

**Comment by night** [comment]
duplicate of #1810

**Comment by faatipuskevit** [comment]
Thanks!
