### ISSUE TITLE
DarkenTTV option

### ISSUE THREAD

**Issue by usctzen** [night/BetterTTV#1828]
Hi,

First, good job. BetterTTV is a nice product. 

On the options DarkenTTv says "A sleek, grey theme which will make you love the site even more". On my Chrome, The background is black and not grey. I would have liked it better in grey. Is this normal or am I missing something ?

Thanks anyway for a good product.

**Comment by lindenkron** [comment]
It's grey, something is probably wrong on your end. 
If your colors are different than these 2: https://gyazo.com/d08ac191135403940746b5502839ed9f
The colors appear to be: e1e1e1 & 141414.
Black is 000000 :)

-lindenkron

**Comment by AlcaDesign** [comment]
Black and white are considered to be part of "grey" anyways 😉 Check your monitor contrast settings.
