### ISSUE TITLE
exiting full screen issue

### ISSUE THREAD

**Issue by MingLikeALee** [night/BetterTTV#1830]
hi!

After watching a stream in full screen and exiting the browser window goes crazy it jumps to the very top of the page and you need to scroll down to see the video properly again. Started noticing it like a week ago not sure if it was after the firefox 50 update or the bttv changes, but disabling bttv fixes the issue.
Anyone else having this problem?

**Comment by EhsanKia** [comment]
Can you explain it in more detail. You have a fullscreen stream, how do you exit the browser window? You press esc? close fullscreen? ctrl+w? do you have multiple windows?

**Comment by MingLikeALee** [comment]
hey!

Both pressing esc and clicking on the exit icon give the same result: jumping to the top of the page like pressing 'home'. One window or multiple windows/tabs, same thing happens. Disabled every other extensions, still the same.

I started noticing this problem since the "you can't resize the chat window" update. Weird.

**Comment by EhsanKia** [comment]
Ok, so if I understand correctly, when you leave fullscreen, it takes up to the top where the big header image is and you can't see the video? I think I can fix that.

Also, do note that you can disable the top header entirely with "Disable Channel Header" setting.

**Comment by MingLikeALee** [comment]
Yep you got it right. And thanks for the heads-up I just tried the header disabling setting and it fixed the issues since there was no roomto jump to the top any more. :)

cheers
