### ISSUE TITLE
Being able to remain ''unnoticed''

### ISSUE THREAD

**Issue by Soltaire** [night/BetterTTV#1832]
Hello there! 
Sometimes, when I'm not in a mood to be in chat, I just want to watch the stream.
But since I have some friends on twitch and I'm a moderator, therefore, once I join some stream, people start to greet me, which can get really annoying at times. Even when I remove my friends -> Once I timeout someone, my name is visible, and it goes on and on and on. It might sound like an irrelevant thing, yet... Is there a way to remain these features.

**Comment by EhsanKia** [comment]
There's a setting called Anon chat. It basically logs you off of chat. You will not appear in the viewer list or in the friend list.
