### ISSUE TITLE
An option to display both username and localized name

### ISSUE THREAD

**Issue by a2364983** [night/BetterTTV#1833]
I'm a Chinese user. It will be great if there's an option to enable displaying both username and localized name, just like Twitch default. I know there's a "Disable Localized Names" option in setting, but it won't display both. Thanks!

**Comment by Stoupedog** [comment]
Duplicate of https://github.com/night/BetterTTV/issues/1488

**Comment by EhsanKia** [comment]
Note that you can still see the other name in the card you get when you click on the name.
