### ISSUE TITLE
Twitch Mini Player

### ISSUE THREAD

**Issue by Axeden** [night/BetterTTV#1834]
Hi it would be very great if u can make an option to disable this annoying new mini player from twitch. Thank you.
![twitch](https://cloud.githubusercontent.com/assets/24405855/20917156/1cd0d004-bb90-11e6-8a4f-4a87ff99f18c.png)

**Comment by Stoupedog** [comment]
Duplicate of https://github.com/night/BetterTTV/issues/1809
