### ISSUE TITLE
Can't see or interact with Twitch player UI

### ISSUE THREAD

**Issue by masatti** [night/BetterTTV#1837]
Like the title says, I can't access the Twitch player UI (play/pause, fullscreen, video settings, theater mode). 

If I disable BetterTTV or turn on "Automatic Theater Mode", I can see the controls again when I hover over the player. Without doing this, hovering does show [this](https://vgy.me/zW7bi3.png) aka. the name of the streamer (top-left) and the red live circle (top-right) but no controls for the player.

**Comment by masatti** [comment]
Solved it! I just disabled the setting in BetterTTV called "Disable Channel Header". I enabled this but a few days ago, and it's worked fine until now. Weird.

**Comment by EhsanKia** [comment]
Sorry about that, you're part of a (pretty small) new experiment which puts the nav bar under the stream (as you can see in your screenshot). It's a pretty new change and I haven't had time to fix it yet (though I think #1827 might fix it). In the meantime, if you want to disable the experiment, you can enter the following in your console:

`Twitch.experiments.overrideExperimentValue('CPR_SUB_NAV', 'control');`

**Comment by AlcaDesign** [comment]
It'd be sweet if there was some UI to override experiments. ![](https://static-cdn.jtvnw.net/emoticons/v1/41/1.0)

**Comment by EhsanKia** [comment]
Isn't that something you were working on / tracking?
I'm not sure it would be something for the masses (aka on BTTV),
but I would definitely love a userscript, for advanced users, that lists available experiments and let's you toggle them.

**Comment by AlcaDesign** [comment]
Yes, I am somewhat tracking it [here.](https://github.com/AlcaDesign/Twitch-SiteOptions/commits/master) I could possibility look into making it, but I don't know much about the ember stuff, `Twitch.*` API, etc. ... If all there is to it is the `Twitch.experiments.*` functions then it'd be relatively easy. I could imagine a button on the BTTV settings modal for Twitch experiments though. I'm currently away on a trip so I don't have my full dev setup.

**Comment by masatti** [comment]
When I enter the command into my javascript console, it just says "undefined". What's up?

**Comment by AlcaDesign** [comment]
`undefined` means that there was no return from the command which is the default functionality.

**Comment by masatti** [comment]
Oh, thanks. It's doing nothing for the header or nav bar, though.

**Comment by EhsanKia** [comment]
@masatti it's not instant, but should apply after you refresh.

**Comment by EhsanKia** [comment]
Ugh, they renamed it to CPR_SUB_NAV_V2, so do this and refresh:
Twitch.experiments.overrideExperimentValue('CPR_SUB_NAV_V2', 'control');

**Comment by EhsanKia** [comment]
This will be fixed with #1827.
