### ISSUE TITLE
chat?darkpopout on light mode

### ISSUE THREAD

**Issue by xgerhard** [night/BetterTTV#1838]
This issue was reported in Discord yesterday:
Some sites embed Twitch chat with a ?darkpopout parameter to force the dark Twitch chat style.
For example: https://www.bungie.net/en/Community/Stream/andrewssk5

If you use BTTV light mode and load the page the chat will be barely readable and the chat input box will look bad. 

It would be nice if BTTV either ignores the forced ?darkpopout and loads in the style based on the user setting, or if BTTV could load in the Dark mode on page load when it's forced, without changing the user setting.

**Comment by j3ddesign** [comment]
This bug seems to have returned - When embedding chat in an iframe using the `darkpopout` url param bttv enforces its own theme, leaving light theme backgrounds with unreadable white text.
