### ISSUE TITLE
Is enlarge chat removed?

### ISSUE THREAD

**Issue by Bren002** [night/BetterTTV#1839]
Been gone since the mini player was released

**Comment by EhsanKia** [comment]
Sadly, we had to get rid of it as it was a lot of work maintaining that feature and it wasn't used by many. In the latest update, Twitch made pretty big changes to the channel page with the new update which broke a lot and we had to get rid of it, at least for now, as fixing it will take a lot of effort.

**Comment by Bren002** [comment]
Damn FeelsBadMan I liked it because high view channel chat would go slower since  it was bigger than defualt

**Comment by EhsanKia** [comment]
What you can do is popout the chat and then you can resize it all you want. Not as clean but sorta does what you need.
