### ISSUE TITLE
Channel header always disabled

### ISSUE THREAD

**Issue by KetsuoTaberu** [night/BetterTTV#1846]
Whether the option to disable the channel header is on or off, the channel header is disabled.

Off:
https://puu.sh/sJiuT/e141a80f25.png

On:
https://puu.sh/sJiwa/8b806b7ad5.png

**Comment by EhsanKia** [comment]
Is this true even after you refresh?

**Comment by KetsuoTaberu** [comment]
Yes, this is persistent even after a refresh.

**Comment by night** [comment]
you're in a twitch experiment.. we have no ability to fix this.
