### ISSUE TITLE
Stream Preview

### ISSUE THREAD

**Issue by simplywoolfie** [night/BetterTTV#1847]
So I've recently noticed Twitch has implemented stream preview when you click off a stream. Once you click off a stream a box in the bottom left corner appears with the stream running. I find this extremely annoying  because not only I have to close the stream itself but the preview as well. Is there a feature you could add to get rid of it?
https://gyazo.com/91e577bea165bc11f5049d3a84076744

**Comment by EhsanKia** [comment]
Duplicate of #1809 

td;dr: Twitch is adding it soon.
