### ISSUE TITLE
Betterttv Not working.

### ISSUE THREAD

**Issue by CanadianWolfGamer** [night/BetterTTV#185]
When i go to a channel my chat does not chow up. Everything is there but its like no one is talking in chat but when i go back to default twitch chat. Its perfectly fine. When i try to type something it does not pop up at all. its just a blank chat all the time.

**Comment by night** [comment]
Try clearing your cookies and cache

**Comment by CanadianWolfGamer** [comment]
Nope that didnt work

**Comment by night** [comment]
Check you have no other addons installed which conflict with BetterTTV

**Comment by CanadianWolfGamer** [comment]
i dont. i only have Bettettv app

**Comment by night** [comment]
Can't fix
