### ISSUE TITLE
Feature request: Harassment & racism reporting

### ISSUE THREAD

**Issue by anuzis** [night/BetterTTV#1851]
Appreciate all the great work on BetterTTV. The only feature from standard Twitch that I'm missing is the ability to report harassment & racist comments when blocking a user. It appears BetterTTV instant ignores a user with one click which I understand is a convenience for some. If harassment reporting could be a feature I enable from the settings I'd appreciate it.

**Comment by night** [comment]
We have to do it that way because we have no ability to call the report user function in the correct context Twitch's ember framework expects, sorry.
