### ISSUE TITLE
host button vanished

### ISSUE THREAD

**Issue by drats666** [night/BetterTTV#1852]
the host button seemed to have vanished. even after disabling it and enabling it again it doesnt show up. not sure what changed but this was one of my most used features.
seemed to disappear both on chrome 54.0.2840.99 m (64-bit)
and opera 41.0
http://prntscr.com/dhv5t9
http://prntscr.com/dhv5ze

**Comment by drats666** [comment]
http://prntscr.com/dhv5t9
http://prntscr.com/dhv5ze
just some screen shots to show that the button is missing

**Comment by EhsanKia** [comment]
You're in the new nav bar experiment (notice the nav bar is under the player rather than on top).

You can force disable the experiment with the following in console:

`Twitch.experiments.overrideExperimentValue('CPR_SUB_NAV_V2', 'control');`

**Comment by EhsanKia** [comment]
It's a 5% rollout so we don't fully support it yet. Maybe we'll add support for the new nav soon.

**Comment by drats666** [comment]
so the "nav bar fai... i mean experiment doesnt support the host function? but yet still had it listed as an option? -.-

**Comment by EhsanKia** [comment]
That's Twitch pushing a new experiment, not us.

Unfortunately we can't support every tiny experiment Twitch decides to roll out for a small fraction of users, we're just a handful of small developers maintaining BTTV in our spare time.

**Comment by drats666** [comment]
can you please tell me how to access the console you mentioned? when i search i only find things for streaming software which i dont stream.

**Comment by EhsanKia** [comment]
ctrl+shift+j

**Comment by drats666** [comment]
resolved thank you
