### ISSUE TITLE
Ability to Modify Google Translate API Url

### ISSUE THREAD

**Issue by swiftyspiffy** [night/BetterTTV#1857]
Currently BTTV has an awesome translate feature. As a understand, because Google Translate is a paid API, the access to this feature is limited and has a cooldown (makes sense). I was wondering if it'd be possible to have the ability to source the translations from our own web server (emulation of the current BTTV Translate request wouldn't be difficult). I understand this may be sort of niche request, and as such ignore it, but it might reduce load on your translate api url and would allow individuals to translate as much as they want using their own service. Additionally, broadcasters could fund their own Google Translate service allowing for more effective moderators.

Thanks!

**Comment by thinkpad4** [comment]
I like this idea

**Comment by EhsanKia** [comment]
Can't you just put a line in your host files that redirects the google translate domain to whatever local ip your translate server is running off?

**Comment by swiftyspiffy** [comment]
That's what I'm doing at the moment, but it's cumbersome to have all mods in a channel do it.  The idea was brought to me by a fairly large streamer, so I figured he probably wasn't the only one to think of it. Just a thought though.

As to how to implement it, not really sure. Doesn't seem like a candidate for the BTTV settings menu, but if it could be manually set somewhere, maybe? I don't know.

**Comment by EhsanKia** [comment]
I can make it an option you can set in your chrome console, but honestly that's much much easier than modifying your host file.

**Comment by swiftyspiffy** [comment]
I think that would suffice. The instructions for fellow mods would be at a browser level, instead of an OS level, so we have that going for us.

Thanks!

**Comment by night** [comment]
You are welcome to make a fork and distribute it privately to your mods provided the only modification is to the translate API. However, we are not looking to make API calls to BetterTTV customizable. In the next version of BetterTTV being worked on we'll actually have an API class which will make this customization unclean, so we would require you to fork anyways. We may at some point give Pro users more translations, but for now there's no definite plans. It all depends on how much of a demand there is, and there really isn't much of one.
