### ISSUE TITLE
Emotes in "Friend-Joining" notification do not display

### ISSUE THREAD

**Issue by kevronicoal** [night/BetterTTV#1858]
I recently added BetterTTV to Chrome, in which I also have been using FFZ version 1.57 (according to my Chrome extensions). Has some cool features, but I noticed that the emotes when a friend joins the stream I'm watching (or if I join a stream my friend is already in) do not display. Rather, they just display the emotes name (i.e. "Your friend *** has started watching! HeyGuys", where the emote is not displayed).

Not sure if the extension intends to do that, but even though it's a small bug, it feels "off" to me.

I currently have BTTV Ver. 6.9 (it says 6.8 in Twitch chat when I enter a stream), FFZ Ver. 1.57, and Chrome Ver. 56.0.2924.21 beta (64-bit) (though, BTTV is disabled for now).

**Comment by EhsanKia** [comment]
I noticed that too, should be a simple enough fix.

**Comment by EhsanKia** [comment]
Hmm, I looked at the code for this one, not sure if it's worth doing. It does feel a bit off, but honestly, having an emote in "Announcement" messages also feels strange.
