### ISSUE TITLE
Do it for microsoft edge

### ISSUE THREAD

**Issue by ShacoIsMyLife** [night/BetterTTV#1860]
I'm a user of Chrome but with the update of edge for the extensions i want it in edge

**Comment by Stoupedog** [comment]
Duplicate of https://github.com/night/BetterTTV/issues/1435

**Comment by EhsanKia** [comment]
Does Microsoft Edge have Greasemonkey yet?

**Comment by Stoupedog** [comment]
Oh yeah, looks like it does now. 👍 

@ShacoIsMyLife You can install BTTV on Edge through another extension called Greasemonkey, which you will first have to install from [here](https://www.microsoft.com/store/apps/9nblggh5162s).

Once you have that installed, you can install BTTV through tampermonkey. Go to https://nightdev.com/betterttv/, click 'for another browser' and click Userscript.
