### ISSUE TITLE
Backslash in twitch username breaks chat replay bttv

### ISSUE THREAD

**Issue by drksx** [night/BetterTTV#1861]
With BTTV on Safari 10.0.1 and macOS Sierra 10.12.1, If a username in chat has a backslash ("\") character in it, and you click their username in chat replay, the little popup info box with follow, profile, whisper and message buttons and chat history becomes stuck, the buttons on the info box don't work, and you can't get the info box to disappear by clicking the X.

**Comment by drksx** [comment]
github removed the backslash charater i typed between the quotation marks...

**Comment by EhsanKia** [comment]
How can a username have a \\ character? That's not allowed by twitch? Or do you mean you set a nickname on the user with a backslash? I tried that and it still works fine for me. Cannot replicate.

(Also, for reference, you have to type `\\` for it to work)

**Comment by Stoupedog** [comment]
I have actually noticed this once before as well, no idea how they got the name, but I remember having the same issues. (Can't remember the name unfortunately, it definitely just had a random `\` in the middle of it though.)

**Comment by drksx** [comment]
I don't know how they got the name, and i also thought it impossible. for example, the user sox04champ whose profile is at twitch.tv/sox04champ shows in chat as having the username sox04champ\s

**Comment by drksx** [comment]
since, as you say, it should be impossible, perhaps their name really doesn't include the backslash, and bttv is only displaying it improperly?  i don't know.  all i know is clicking their name, which appeared as sox04champ\s locked up bttv.

**Comment by drksx** [comment]
<img width="488" alt="screen shot 2016-12-11 at 02 53 pm" src="https://cloud.githubusercontent.com/assets/5153080/21082839/c65b53f4-bfb1-11e6-9694-28f557ec1d37.png">

**Comment by drksx** [comment]
that screenshot was taken from the video at https://www.twitch.tv/realkraftyy/v/106155478 if you want to check. maybe you'll see something different than i do.

**Comment by EhsanKia** [comment]
Hmm, that person definitely has a space at the end of their name, it even shows on Twitch API... Seems more like a bug with Twitch allowing for that than us. I'll see if I can fix the bug on our end, but this shouldn't even exist.

**Comment by drksx** [comment]
oh i thought it just had a backslash, but apparently backslash-s is code for a space. well that explains why he looks like sox04champ under certain circumstances.

**Comment by EhsanKia** [comment]
Yeah, I guess for the meantime don't click on those users, and if you do, you can click on another user's name to close it. Sorry this is a very small edge case and the bug is mostly with Twitch, not us.
