### ISSUE TITLE
Issue with BTTV specific channel emote's not showing

### ISSUE THREAD

**Issue by rakunvar** [night/BetterTTV#1862]
Hey! Hoping this is the correct area to post this. I've noticed for awhile now that I cannot see Channel specific BTTV emotes any longer. I've tried full cache clear's, BTTV reinstalls, removing other add-ons/extensions, turning off/on just about every setting, multiple browsers, etc. I'll attach an example of the emotes I no longer see.

Thee Streamerhouse section of emotes is what I don't see, no matter what channel I'm on the BTTV Spec. Chan. emotes won't show. Maybe I'm just having a blonde moment and missing something simple... Any help would be awesome!
![screenshot_2016-12-11_at_9 39 24_am](https://cloud.githubusercontent.com/assets/4373199/21081156/e9998fd4-bf8e-11e6-961e-f0c15ce1422d.png)

**Comment by EhsanKia** [comment]
They show up fine on my end. Maybe try doing a refresh, opening the browser console and see if there's any relevant errors. If you don't know what to look for, paste it in a [gist](https://gist.github.com/) and send a link here.

**Comment by EhsanKia** [comment]
And note that in your screenshot, the channel emote should be ABOVE the global BTTV emotes. As shown here:

![](http://i.imgur.com/5tT39uu.png)

**Comment by rakunvar** [comment]
@EhsanKia  Wasnt sure if there was a way to PM you, hopefully posting the gist here works. https://gist.github.com/rakunvar/bc404772032e2e0367b6f25fac04396b  Did both Chrome and Firefox on the Gist. Like I said i've tried quite a few things already so hopefully this points in the right direction.

**Comment by EhsanKia** [comment]
Wait, can you take a screenshot of what you do see?

**Comment by rakunvar** [comment]
Assuming you meant of the Emotes I see :) http://imgur.com/a/FP9SN Basica;lly just the regular BTTV ones, and Channel/Twitch sub ones. That whole Streamerhouse section is missing when Im there, or like in my channel my BTTV ones aren't there either. Lemme know if you need anything else ^^

**Comment by EhsanKia** [comment]
those are screenshots of Twitch's emote menu, not ours? BTTV emotes won't be in there.
The emote menu will be under the chat box (if you have it enabled in BTTV settings)

**Comment by rakunvar** [comment]
Apparently I had a massive blonde moment the last few days from being overly tired... You're of course right, I don't even know how I was this brain dead lol..My Apologies for wasting your time with this, I knew they were there to, just completely oblivious to it recently -.-
