### ISSUE TITLE
How can I get information about smileys that appear on top of the other?

### ISSUE THREAD

**Issue by rutony** [night/BetterTTV#1865]
Like this, SoSnowy, IceCold..
http://i.imgur.com/FI7CddX.png

There's no information about what these emoticons output over the other
https://api.betterttv.net/2/emotes

**Comment by EhsanKia** [comment]
These are little holiday specific Easter eggs by us. They are not permanent (only available for a period of time) and they are part of the Global BTTV emotes. We don't really provide guides or a list of them, they are mostly a fun secret there for users to discover and play with.

These are only done by us and users cannot upload their own, if that was your question.

**Comment by night** [comment]
Such is the caveat of special emotes which break the norms. You can copy/paste the emotes as a workaround in the meantime.
