### ISSUE TITLE
BTTV global emotes disappeared

### ISSUE THREAD

**Issue by TheCoderjoe** [night/BetterTTV#1866]
BTTV has been working just fine for a long time, but suddenly the BTTV global section of my emotes menu is missing and the emotes from that section are not being converted in chat. The BTTV Channel section is still there and those work just fine. I have quadruple-checked my settings, uninstalled and reinstalled, etc. and cannot get them to show back up. I also made sure that section wasn't hidden using the emote menu's edit mode (though testing it on the channel emotes shows they still work in chat, so I don't think that is it.)

Browser: Chrome 54.0.2840.99 m
BTTV version: BetterTTV v6.8R55

**Comment by EhsanKia** [comment]
Can confirm, looking into it.

**Comment by EhsanKia** [comment]
For the time being, turn off "Disable Channel Header".

**Comment by TheCoderjoe** [comment]
That does indeed bring it back.
