### ISSUE TITLE
BTTV Emotes not working

### ISSUE THREAD

**Issue by Synergii** [night/BetterTTV#1869]
Emotes such as LUL or FeelsBadMan are not showing in chat. Only the letters show but not the actual image. 
Does anyone know how to fix this problem?

**Comment by thinkpad4** [comment]
Turn off Disable Channel Header temporally. That seems to fix it

**Comment by Synergii** [comment]
@thinkpad4 That workerd, never would have thought of that. Thank you so much!

**Comment by thinkpad4** [comment]
np, Twitch pushed some changes today that broke things

**Comment by Synergii** [comment]
Hopefully they come up with a fix soon

**Comment by thinkpad4** [comment]
The Nightdevs are working on it, no worries

**Comment by EhsanKia** [comment]
Duplicate of #1866
