### ISSUE TITLE
My BTTV emotes are not working when I manually type them in

### ISSUE THREAD

**Issue by K3x707x** [night/BetterTTV#1870]
As the title says. I type in BTTV emotes and they dont work. I uninstalled BTTV and re-installed it, which is what a friend suggested. But it still wont work. Pls look into this because I dont have time to open up the menu and search for the emote while trying to moderate and keep up with chat. Thx

**Comment by thinkpad4** [comment]
Turn off Disable Channel Header temporally. That seems to fix it

**Comment by K3x707x** [comment]
Ok ill try that. thx

**Comment by thinkpad4** [comment]
Np

**Comment by EhsanKia** [comment]
Duplicate of #1866
