### ISSUE TITLE
BTTV EMotes Not Working (Firefox)

### ISSUE THREAD

**Issue by Maverickroll** [night/BetterTTV#1875]
This started the other day. I noticed no BTTV emotes were working, such as LUL or FeelsBadMan. You just see the text not an emote. Some folks said deleting cookies and cache fixed it, others pointed to turning off the "Disable Channel Header" option fixed it. And for about a day, turning off "Disable Channel Header" did fix it but now the issue has returned. I have that feature turned off and again BTTV emotes are not showing up.

I've tried deleting cookies and cache several times. Using latest build of Firefox, latest version of BTTV, all other features of BTTV appear to work except emotes.

I've also tested it in Chrome. Latest version of Chrome, latest version of BTTV, works fine in Chrome however I'm a Firefox user, Chrome is my backup browser as a last ditch effort for a website that just won't load properly in Firefox, which isn't often.

Yes, I've also made sure the options for BTTV Emotes (normal & GIF) are enabled. As well as the Emote Menu option is enabled (that is gone as well). I've tried toggling them off and on, deleted cache / cookies multiple times. Completely uninstalled and reinstalled the extension itself. Really don't want to have to use Chrome to watch Twitch. From my googling this has been a common recurrence in 2016, plenty of reports of this feature just up and not working at all.

**Comment by EhsanKia** [comment]
If you can look through your console and find the proper error message that would help us, if not I'll test on Firefox tonight..

**Comment by Maverickroll** [comment]
Where exactly do I find this console? F12? If so under what section?

**Comment by night** [comment]
Try disabling other extensions and seeing if one is conflicting with ours. I cannot reproduce this issue, so it must be a localized issue to your computer.
