### ISSUE TITLE
Danmaku Mode

### ISSUE THREAD

**Issue by YvesEffini** [night/BetterTTV#1880]
Can you add a feature to where we can enable and disable danmaku chat mode through the BTTV settings, not just by another standalone chrome extension

**Comment by EhsanKia** [comment]
This is a very specific feature very few people need, and belongs to a separate script/extension. Adding random small features to BTTV leads to [feature creep](https://en.wikipedia.org/wiki/Feature_creep) and lowers the overall quality of the extension.
