### ISSUE TITLE
title and played game auto-update is broken again(?)

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#1881]
I noticed that in the past days it doesn't get auto updated in my browser.

**Comment by EhsanKia** [comment]
Can you just take a screenshot of what you see on the channel page (is the tool bar under or over the stream?).

**Comment by thinkpad4** [comment]
I still have the old layout, title under the video and sub button over it and the auto-update is working for me

**Comment by EhsanKia** [comment]
Strange, I tested it last night on my own channel and it worked fine.
Are you sure it's not refreshing?
