### ISSUE TITLE
Support for new 'Cheermotes'

### ISSUE THREAD

**Issue by Stoupedog** [night/BetterTTV#1882]
Twitch's newly added animated ['Cheermotes'](https://twitter.com/Twitch/status/809522913963573248) don't currently show with BTTV enabled. 

![](https://i.imgur.com/qUlQI50.png)

**Comment by EhsanKia** [comment]
Yeah I'm at work but might be able to code something up tonight, unless someone else wants to have a go.

**Comment by EhsanKia** [comment]
I can give pointers if anyone else want to look at it since I wrote the original Cheer support.
