### ISSUE TITLE
BTTV offsets video; breaks layout

### ISSUE THREAD

**Issue by Iberis** [night/BetterTTV#1883]
The same offset exists at the bottom. It's pretty annoying.
![1](https://cloud.githubusercontent.com/assets/1470376/21249529/f688c562-c33e-11e6-811b-0b51af1083cd.PNG)
![2](https://cloud.githubusercontent.com/assets/1470376/21249530/f68885ac-c33e-11e6-97de-1c9b51d04716.PNG)

**Comment by EhsanKia** [comment]
do you have "Disable Channel Header" on or off?

**Comment by evodoc** [comment]
It happens on my end too, but it seems only with Firefox (50.1.0). I have disable channel header off. As a workaround enlarging then minimizing the left side panel fixes it.

**Comment by EhsanKia** [comment]
Very strange, if that option is off then I have no idea what would trigger this.
I'll test it on Firefox tonight and see if I can replicate the issue...

Twitch's changed their player position system to allow for miniplayer and it's a huge mess.

**Comment by Iberis** [comment]
I'm not sure when or why this happened but the offset is gone now. I did try restarting my browser before reporting this bug, so I have no idea what changed. Disable Channel Header was off, I didn't even realise that was an option.

**Comment by EhsanKia** [comment]
The new patch we just push should (hopefully) fix this. Please confirm.

**Comment by evodoc** [comment]
It still happens.

**Comment by Iberis** [comment]
I'm not having any issues so far, but it disappeared and reappeared before so idk.

**Comment by Iberis** [comment]
The offset is at the bottom now, which is an improvement at least.
![unbenannt](https://cloud.githubusercontent.com/assets/1470376/21312172/0c4556c8-c5eb-11e6-94f4-75fab8db4c7c.PNG)

**Comment by Aaron128l** [comment]
The bug occurs when the offline banner appears with Disable Header Enabled. Forcing the player up in the wrong position and allowing the offline banner to appear.

**Comment by Iberis** [comment]
Except we dont have that option enabled

**Comment by EhsanKia** [comment]
1. Is the stream offline?
2. Does it fix itself if you resize the window or collapse/open side bar?
3. Does the channel have a "Last Broadcast" banner at the home?

**Comment by Iberis** [comment]
1. Online
2. Yes
3. I don't think so?

**Comment by evodoc** [comment]
It seems I was wrong, it's not a Firefox-only issue. And it also happens with offline streams.

**Comment by Iberis** [comment]
Can confirm that the offset happens without a last broadcast banner anywhere.
