### ISSUE TITLE
Remove the "MiniViewer" that appears when leaving a channel.

### ISSUE THREAD

**Issue by bjhanish** [night/BetterTTV#1884]
Twitch currently does not offer us the option of disabling the little pictire-in-picture overlay that appears when navigating away from a channel to any other non-channel destination on their webpage.   For persons with non-standard monitor sizes it little window can cover an enormous amount of the screen we were intending to view.   It would be nice to be able to disable this "feature" entirely, permanently.

**Comment by Stoupedog** [comment]
You can already disable the mini player from the settings menu at the bottom of a stream, which disables it everywhere on Twitch.

![](https://i.imgur.com/gLLd3BV.png)
