### ISSUE TITLE
Old dashboard

### ISSUE THREAD

**Issue by Merdiin** [night/BetterTTV#1887]
I want the old dashboard with this new features.
Because this is just terrible with my screen resolution...
Or this new dashboard, but with a smaller resolution..

I hope you understand me :)

**Comment by Merdiin** [comment]
Delete this post please.

**Comment by Slikrick** [comment]
Twitch already supports showing the old dashboard https://www.twitch.tv/<username>/dashboard?show_previous=true

**Comment by EhsanKia** [comment]
Can you take a screenshot of what it looks like at your resolution?
I don't see how the new one is any worse. If the issue is having 3 columns,
you can collapse panels you don't need and stack everything to be in 2 columns.
