### ISSUE TITLE
BTTV command now clashes with Twitch command.

### ISSUE THREAD

**Issue by aroboto** [night/BetterTTV#1889]
/followers is now a Twitch moderation command enabling chat restricted to followers of the stream only. Clashes with the /followers bttv command that retrieves the number of followers on a channel.

**Comment by thinkpad4** [comment]
When did Twitch add that?

**Comment by aroboto** [comment]
today

**Comment by thinkpad4** [comment]
Could make /followon and off turn it on and redirect /followers to be BTTV only.  Like /sub and /suboff

**Comment by gapbl4** [comment]
you can use .followers .followersoff instead
