### ISSUE TITLE
Bits not showing up in chat

### ISSUE THREAD

**Issue by StaticXNation** [night/BetterTTV#1890]
I keep getting this message in chat while trying to send bits to a streamer "BetterTTV encountered an error reading chat. The developer has been sent a log of this action. Please try clearing your cookies and cache." and I can't see others bits in chat when someone else sends bits.

I have tried clearing my cache and cookies and it didn't work. I have even tries enabling and disabling the "Hide bits" option and that did nothing.

I am on Google Chrome.

**Comment by EhsanKia** [comment]
Yep, Twitch just pushed a change literally a day after I fix it, changing how their templates work..

Fixing it now.
