### ISSUE TITLE
Chat and other problems

### ISSUE THREAD

**Issue by tenroy6** [night/BetterTTV#1894]
I don't know what is causing it. But I have to reload streams for chat to always load CORRECTLY only on BTTV. 

Also, it seems that when I hide chat in theatre or full screen I have to rego into chat. It says welcome. Why am I not always in chat? If this isn't you I apologize ^^ but can you make it so chat just stays on... So I'm always in it and it won't bug out...?

**Comment by gapbl4** [comment]
Works fine for me on Chrome. What's your browser?

**Comment by tenroy6** [comment]
Chrome aswell :/


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by gapbl4** [comment]
For me chat disconnects only when I hide it manually, which is fine.

**Comment by EhsanKia** [comment]
I think chat disconnecting when you hide it is how Twitch works too? And the chat problems I believe that also happens on Twitch side.
