### ISSUE TITLE
On some occasions, the chat is not scrolled down fully

### ISSUE THREAD

**Issue by Rezaldy** [night/BetterTTV#190]
http://i.imgur.com/X7ja6Oo.png

The arrow is pointing to the scrollbar, which as you can see is fully scrolled down. My message (RizkyBizniz) is only partially visible.

This does not happen on all messages, but mostly on messages with multiple lines.

I know it's annoying to find stuff that only happens "sometimes", but for me it's annoying to only be able to read part of a message and then have to either scroll down (Move hand to mouse mid conversation = already annoying, I'm a lazy gamer) or wait for another message so that it scrolls down correctly.

If you guys could at least take a look at this, that'd be great.

**Comment by samfun123** [comment]
I think the reason this is happening is because the emote is on a newline but it doesn't take this into account

**Comment by teak** [comment]
This is due to the changes in the way emotes are loaded. The emote height is not taken into account until it is loaded, and they are loaded asynchronously. This issue happens on any line with an emote, but is exaggerated if the text spans two lines. I'll look into this soon..

**Comment by vendethiel** [comment]
Would `.scrollIntoView()` onto the last line work?

**Comment by teak** [comment]
The scroll event would have to be triggered after the emotes are loaded. I havent looked into this yet, but im not sure there is an easy way to know when they finish loading. This may just be a simple css change, I dont know yet..

**Comment by night** [comment]
This is a difficult issue to solve when height/width of images is not already known. I'm not sure if Twitch's default chat is also affected by this, but here's the scroll code they utilize:

    _scrollToBottom: _.throttle(function() {
        var e = this,
            s = this._$chatMessagesScroller;
        a.run.next(function() {
          setTimeout(function() {
            s && s.length && (s.scrollTop(s[0].scrollHeight), e._setStuckToBottom(!0))
          })
        })
    }, 200)

Apart from underscore's throttling and the setTimeout that forces the function to run asyncronously, it seems identical.

@vendethiel ````.scrollIntoView()```` is not useful here, as that is for the entire window to scroll, when we need a div to scroll.

**Comment by vendethiel** [comment]
oh, right. eh

**Comment by teak** [comment]
95% of emotes are the same height. We could just set a min-height on lines that contain emotes.

**Comment by Rezaldy** [comment]
Is it not possible to call scrollTop() (like in Night's snippet) on this._$chatMessagesScroller afterwards again when a line contains an emote? Cause as I said, simply scrolling down manually makes the full message visible, until the next time I bump into it. 

The problem isn't that it just cuts off and is not visible anymore until someone else sends a message, but it's just that the chat itself is not scrolled down fully when the second line of a message contains an emote.

Is the height of the emote sent really a factor in this?

(3AM here, pardon me if I sound stupid.)

**Comment by Rezaldy** [comment]
You know, this actually worked, maybe it can be called when a chat line contains an emote:

`$(function () {
    var s = $('.tse-scroll-content');
    var height = s[1].scrollHeight;
    s.scrollTop(height);
});`
