### ISSUE TITLE
Localizing BTTV (in my case to Turkey)

### ISSUE THREAD

**Issue by MTTurk** [night/BetterTTV#1902]
Hello guys, I directly jumped in the site and started to writing without reading the rules etc. but I'm really excited about this idea. 

Problem: Non-English streams usally does not use lots of emojis or memes in Twitch or BTTV.
Cause: Non-English communities does not have the same humour as English communities.
My Suggestion: Localizing BTTV via adding local humour symbols, emojis, memes etc.
Example: In Turkey we have this "Caps" instead of "memes" which is basicly the meme image and the text on bottom in a red bar.

![16](https://cloud.githubusercontent.com/assets/24641389/21298012/869df29e-c592-11e6-9c73-85af4b5f7a98.jpg)

This is an example caps. The red bar says "Forgot my wallet."

So there are some characters that is used frequently. For example:

- Devlet Bahçeli (politician)
- İlber Ortaylı (historian)
- Canan Karatay (nutritionist)
- İbrahim Tatlıses (singer)
- Zekeriya Beyaz (phony clergyman)
- Aziz Yıldırım (sports team president)
- Kemal Sunal (comedian/actor)
- Erman Toroğlu (soccer commentator)
- Bülent Yapraklıoğlu aka "AhsenTV Muhabiri" (reporter of a religious channel)
- Necati Şaşmaz aka Polat Alemdar (mafia series actor)

Any photo of them will do it. Also there is some classic Caps backgrounds like meme templates. Another thing is cliche Turkish symbols. For Example:

- Tea in a little glass
![cay-bardagi-nasil-temizlenir_646x340](https://cloud.githubusercontent.com/assets/24641389/21298217/54a4ca84-c596-11e6-95f3-0d7786e29c1d.jpg)

- A local music instrument called Bağlama
![baglama](https://cloud.githubusercontent.com/assets/24641389/21298265/3bc3c28a-c597-11e6-85aa-5107bd581a83.jpg)

- A special bread that is only produced at Ramadan aka "Ramazan Pidesi"
![1091597_620x410](https://cloud.githubusercontent.com/assets/24641389/21298346/b360cd14-c598-11e6-928f-67f417d9e5ce.jpg)

- A local manifactured card called Şahin

![modifiye-sahin-2](https://cloud.githubusercontent.com/assets/24641389/21298358/dffcaa64-c598-11e6-924c-3349d9352b26.jpg)

Anyways, you get the idea. If you add these to BTTV, Turkish users will have at least %487.33 better chat experience. I guarantee it.

**Comment by night** [comment]
We do not take global emote requests, sorry. You and others can upload and share any emotes at https://manage.betterttv.net already.
