### ISSUE TITLE
[Feature request] Two-toned chat background for people you follow

### ISSUE THREAD

**Issue by Geotherm** [night/BetterTTV#1905]
Please could you add an option to highlight messages in twitch chat from people you follow? Doesn't have to be flashy, just a slight change of tone.

I have a long list of friends who I follow and it'd be nice to see their messages in other, big channels easier as the chat scrolls by.

Thanks!!!

**Comment by night** [comment]
we would rather not have to maintain a list of who you follow, sorry.

**Comment by Geotherm** [comment]
Can you not detect who is followed depending on whether or not you click to "follow" or "unfollow" when you click on their name?

If not, no big deal. Thanks for your response :)
