### ISSUE TITLE
[Suggestion] Label if user follows you

### ISSUE THREAD

**Issue by KITTMaceWindu** [night/BetterTTV#1907]
Hey there,

I'd like to suggest a feature for BetterTTV. It's a small label next to the "Follow" button in the upper right corner on the Twitch page that tells you if a user is following you like it is on Twitter. I think it's sometimes nice to know and wouldn't annoy anyone if it's just shown when follow status is true and hidden when follow status is false.

**Comment by night** [comment]
It makes sense on a site like Twitter where follows are used for friendships essentially, but on Twitch there is a separate friends system. I don't really see the point of including this on channel pages as a result.
