### ISSUE TITLE
possible new feature if possible? 

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#1913]
i was just wondering is their a way to make a spam feature on bttv that if the same message in twitch chat keeps being spammed it will not show if it is turned on because i fine it very annoying when i just want to enjoy a chat on a stream and i can't because spam is okay in that channel

**Comment by AlcaDesign** [comment]
Perhaps it could be "/localr9kbeta"?

**Comment by gamernation89** [comment]
Yeah I would appreciate that because I just can't stand all the spam and this would be a extremely useful feature and I know many would use it if you implemented it for the next update

**Comment by night** [comment]
duplicate of #78
