### ISSUE TITLE
Click to play/pause issue

### ISSUE THREAD

**Issue by lPsykol** [night/BetterTTV#1917]
The feature doesn't work even after deleting and redownloading, closing and opening google chrome, and restarting my desktop.

**Comment by night** [comment]
Yeah, Twitch renamed its player service, which breaks this. It will get fixed..

**Comment by Quixboy** [comment]
I cleared my cookies and now when re-enabling all the features, this specific option doesn't work anymore. As far as I know nothing of the basic solutions don't work.
