### ISSUE TITLE
Ability to remove "Latest Uploads" on Following page

### ISSUE THREAD

**Issue by stoicite** [night/BetterTTV#1918]
Is it possible to have an option to remove the Latest Uploads listing in the Overview tab on the Following page?
![latest](https://cloud.githubusercontent.com/assets/24768660/21473423/063fd016-cad0-11e6-9250-8fc3a253429e.jpg)

**Comment by night** [comment]
If you just want the live channels, there's a setting for that in the BetterTTV settings already.
