### ISSUE TITLE
Chat in dashboard doesn't load bttv channel, personal, etc. emotes.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1919]
Only the default global twitch + bttv list appears in dashboard chat. It probably loads twitch sub emotes, but I'm not subbed to anyone on twitch.

**Comment by night** [comment]
I cannot reproduce this. It works fine for me.

**Comment by gapbl4** [comment]
Yeah, works fine for me now. Had this problem for few days tho.
