### ISSUE TITLE
pin the streamer's messages

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#1920]
If a stream with lots of viewers goes down the chat usually goes crazy spammy, so it's very hard to spot what the streamer's is writing in chat trying to inform the people (like he's coming back soon or he won't come back at all). So in this case for example this feature would be useful.

**Comment by AlcaDesign** [comment]
The streamer or a responsible moderator could enable slow mode and/or sub-only mode (which does work in not-partnered channels and only allows the streamer and moderators to type).

**Comment by EhsanKia** [comment]
We also have /localsub and /localmod for when you want to enable submod for yourself only.

**Comment by night** [comment]
really also a dup of #94
