### ISSUE TITLE
Feature Request - Remove minimized video

### ISSUE THREAD

**Issue by Enzymic** [night/BetterTTV#1921]
Twitch added that new feature that minimizes the video player when you scroll down, or go to your 'following' page, etc. I couldn't find an option in the default settings to turn it off. If this is something you can add that'd be great!

**Comment by gapbl4** [comment]
You can easily disable mini player by default
![image](https://cloud.githubusercontent.com/assets/14076068/21486764/56ba8710-cbcb-11e6-9fcc-3ee8ff980915.png)
