### ISSUE TITLE
Can't see chat messages in firefox. 

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1923]
Chat messages, as well as previously typed messages, very often completely do not appear in chat. However pinned highlights appear. Here's what I see in console, don't know if that helps 
![image](https://cloud.githubusercontent.com/assets/14076068/21511187/5b67e21a-ccae-11e6-8328-f5a2fae9c2df.png)

**Comment by night** [comment]
Can you click the triangle on the left of the error to get a stack trace?

**Comment by gapbl4** [comment]
I don't get TypeErrors anymore.

This is how page loading looks

![](http://i.imgur.com/0Oxe63u.gif)

**Comment by Bren002** [comment]
I also get this problem chat doesn't appear then I gotta reload one or two times

**Comment by night** [comment]
Without any stack trace errors it's difficult for us to track down this issue, unfortunately. I'm also going to defer this as a dup of #1898
