### ISSUE TITLE
Chat and Sidebar on the wrong side of the screen.

### ISSUE THREAD

**Issue by ThibaultVlacich** [night/BetterTTV#1924]
For whatever reason, the chat is on the left and the sidebar on the right. It only happens when BetterTTV is loaded. Any idea? It started a few days ago.

[Screenshot](http://i.imgur.com/OLGVi83.png)

**Comment by ThibaultVlacich** [comment]
Well, I just found a settings to have the chat on the left side. I haven't enabled this settings but well, the "bug" is now fixed.

**Comment by EhsanKia** [comment]
When did this happen? There used to be a feature that let you drag the chat across, but it was removed a few days ago due to people accidentally doing it. But that shouldn't happen anymore.
