### ISSUE TITLE
Emote Menu - (Made by Ryan Chatham)

### ISSUE THREAD

**Issue by Tritoneko** [night/BetterTTV#1925]
Hey there, I just started using this emote menu, and I noticed the pin emote menu to chat option. However, I noticed if you move out of the emote menu to see chat again and then use the emote menu again, the pin is removed and you have to select it again for it to be locked to spam emotes. 

I would like to see an option where if you select the pin to lock the emote menu in place to spam emotes, when you switch back and forth between the two displays (chat and emote) it stays pinned.
> So you can open the menu, select a couple emotes in quick succession and then switch back to chat menu to finish your sentence if you wish. 

I think this would be an awesome update to it, more options are usually very nice : ) Cheers!

**Comment by night** [comment]
Feature requests for the emote menu can be made over at https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/issues
