### ISSUE TITLE
Add Chat delay (Slow-down)

### ISSUE THREAD

**Issue by ziichu** [night/BetterTTV#1931]
Add chat delay for better chat modding , especially when the chat is moving fast

**Comment by Stoupedog** [comment]
Chat delay is something the streamer can enable in their [twitch settings](https://www.twitch.tv/settings/channel), which creates a delay between users posting messages and the messages being viewable to chat, giving time for moderators to timeout/purge messages before everybody else sees them.

However, I think the feature you're looking for already exists in BTTV, called [Chat Freeze](https://twitter.com/BetterTTV/status/784622831980126208).

**Comment by ziichu** [comment]
Yes that's it. 
thank you very much
