### ISSUE TITLE
Whispers respond feature doesn't work.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1932]
When I type "/r " it just says "You have not received any whispers" in both channel and popout chats. I can't even remember if it had ever worked for me.

**Comment by AlcaDesign** [comment]
It doesn't work unless you receive the whisper inline with the chat as opposed to in a separate box on the page devoted to that 1-on-1 conversation. Pop-out chat works with this.

**Comment by gapbl4** [comment]
That's how it works for me.
![](http://i.imgur.com/BKG3tqz.gif)

**Comment by gapbl4** [comment]
It clearly says "/r -- Type '/r ' to respond to your last whisper" in /help . How else should I expect it to work?
