### ISSUE TITLE
Would like to split stream and chat vertically.

### ISSUE THREAD

**Issue by ebber22** [night/BetterTTV#1933]
It would be nice with an option to have the stream play on top of the screen and have the chat under the stream, so that you can get more use with screens in portrait mode instead of landscape.

Edit: I would like it to look like [this](http://i.imgur.com/Y6ywaZ7.png) and have a setting or a button to change the orientation.

**Comment by EhsanKia** [comment]
Just pop out chat and can arrange it any way you'd like on your screen. I don't think it's a useful enough case to have a whole option for.

**Comment by night** [comment]
We do not do heavy modifications to the channel view any longer, sorry.
