### ISSUE TITLE
Theater mode option to maximize video when using vertical monitor?

### ISSUE THREAD

**Issue by FacksMachine** [night/BetterTTV#1934]
When viewing twitch through a vertical screen, I have always wished for an option (especially in theater mode) to have the video portion of the screen as big as it would be if you had collapsed both sidebars, but with the chat sidebar below the video. I can't imagine this being requested very often, but it couldn't be too hard to implement. I've attached an example screenshot I mocked up in gimp. Thanks for the consideration.
![example](https://cloud.githubusercontent.com/assets/24885738/21599525/d5a1bdc6-d13b-11e6-9c04-6efd9bd2ebff.png)

**Comment by night** [comment]
We are unwilling to do hefty page modifications like that, sorry. We used to, but Twitch uses the sidebar for player calculations.
