### ISSUE TITLE
Having buttons instead of a slider when using the "Shift-Click Custom Timeouts" feature

### ISSUE THREAD

**Issue by Dakeiz** [night/BetterTTV#1935]
It would be really cool to have buttons instead of the slider (or at least let us choose between Button or Slider).

**Comment by EhsanKia** [comment]
you already have a few buttons when you click on someone's name. Purge for 1 second, time out for 10m, 1-hour and permanent ban.

**Comment by Dakeiz** [comment]
But the slider's so f*cked up that sometimes you can't even ban someone for 7 days.

**Comment by EhsanKia** [comment]
Then that's the bug that should be fixed, rather than just adding more buttons.

**Comment by Dakeiz** [comment]
I think adding buttons instead of a slider (or give the option for people to choose) would be better. Of course, that's my opinion.

Thanks for closing the thread, so I guess we'll never see that coming. Whatever.
