### ISSUE TITLE
[Feature request] Favorite channels

### ISSUE THREAD

**Issue by iLostMyRedPill** [night/BetterTTV#1938]
As an active twitch user for many years, my list of followed channels has grown quite a bit. And that's OK.
But there are some channels that are more important to me than others. For example the ones I'm a mod in.

If I could add followed channels to some kind of "favorite channels list" and have those channels listed on top of my followed channels, regardless of number of current viewers, it would help a great deal to see the channels that are most important to me.

**Comment by night** [comment]
if there are channels you don't watch anymore, you should unfollow them.. I don't think adding another list when you've already curated one makes sense..
