### ISSUE TITLE
[Feature request] Time format option

### ISSUE THREAD

**Issue by Ragowit** [night/BetterTTV#1940]
I would love to have an option that allow me to have 12 or 24 hours format on the time stamps.

I have noticed that if I set Google Chrome to run in Swedish, it is in 24 hour format that I want. But I don't want Google Chrome in Swedish. I want to keep Google Chrome in English, but with 24 hour format on the time stamps.

**Comment by gapbl4** [comment]
Also would be a nice option to enable 0 in single digit hours to have same width for chat messages

**Comment by Rulqu** [comment]
I have chromium browser and Finnish as locale yet it still is in 12 hour format.

**Comment by Rulqu** [comment]
Same thing in Chrome.
