### ISSUE TITLE
"More messages below." button is missing on Chat Replay (VODs)

### ISSUE THREAD

**Issue by Wucco** [night/BetterTTV#1943]
Browser: **Google Chrome 55.0.2883.87 m**
BetterTTV version: **6.9**

I watch a lot of VODs and sometimes scroll up the chat to freeze it. When I want it to go back I have to manually scroll down to the bottom. What is even worse is that even though I get to the bottom, the chat is still frozen in place. I have to scroll down multiple times before it's back to normal.

I have looked through the BetterTTV options but didn't find anything related to the issue. I have also disabled the addon, to make sure it is responsible, before posting.

**Comment by night** [comment]
chat replay doesn't have a more messages option, this is just how twitch does it.
