### ISSUE TITLE
[Feature Request] Option to disable Mini Player

### ISSUE THREAD

**Issue by joelunder** [night/BetterTTV#1944]
Twitch added a new feature in the "Mini Player", and turned it on with no way to disable it. I greatly prefer the old format, where if I scrolled down, the video stayed at the top of the page, and if I navigated away from a stream, that stream closed. 

An option to disable that player (optionally in each circumstance, I'm sure some people like the feature in one instance or the other) would be awesome.

**Comment by Stoupedog** [comment]
Duplicate of #1884
