### ISSUE TITLE
Quick Add to "Blacklist" for phrases, words, etc.

### ISSUE THREAD

**Issue by jessepink** [night/BetterTTV#1945]
If possible, it'd be nice to be able to highlight and right-click (or some other decided upon mechanism) to show a context menu for that highlight item and add it to the current list of black listed items in chat... while not extremely difficult, getting rids of chat spam is a bit more difficult than it needs to be.

**Comment by night** [comment]
custom context menus are not really fun to handle, so I do not really want to handle this, sorry. People like to highlight and copy/paste/etc.. and there's also plugins which add to the native ctx menu
