### ISSUE TITLE
Localized names.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1946]
I'm not sure if localized names looked like that on twitch from the start or it's just a recent change.

![](http://i.imgur.com/N6ohoar.png)

But it would be nice to have an option where I can see both localized and original name in chat, just like in bare twitch.

**Comment by EhsanKia** [comment]
Please search before making a new post:
#1833 
#1761 
#1488

**Comment by gapbl4** [comment]
I think that current state of nickname options removes functionality, not makes it better. For some people it's more convenient when you can both know that chatter has localized name on first glance in chat, and in addition you can see what name to type in response. Being able to see only one name out of two at a time does not exactly make it better, not for everyone.
