### ISSUE TITLE
Issue with cheers

### ISSUE THREAD

**Issue by Robjan** [night/BetterTTV#1947]
Heya

Recently came across [this issue](http://i.imgur.com/BkjvU2j.png) regarding cheering/bits.
The icon for unpinning them for mods overlaps the dismiss button. We've had a few issues where mods accidentally unpinned cheers when they were just trying to dismiss them. I made sure it isn't related to Twitch itself because the buttons for quickly dismissing/unpinning don't even appear without BTTV.

Thanks
RJ

**Comment by EhsanKia** [comment]
It's definitely BTTV.

It's hard for us to test these features because we need we need a channel with bits enabled, a pinned cheer and be mod in it to test this. I may try to fix this by looking at your image but if you can submit a fix it'd probably work better.

**Comment by Robjan** [comment]
I honestly wouldn't know how to fix this. It's basic af HTML I guess so
it'd be as simple as reducing the pixel height, but.. I don't even know
where to start. Totally new to Github.

2017-01-06 22:32 GMT+01:00 Ehsan Kia <notifications@github.com>:

**Comment by night** [comment]
this is fixed
