### ISSUE TITLE
add a follower mode indicator 

### ISSUE THREAD

**Issue by ksthiele** [night/BetterTTV#1951]
Twitch now has a follower mode, but it's not showing until you try to write something in chat.

It should be shown on above chat were "slow mode" and "sub mode" are shown.

I don't know what the symbol could be, maybe a chick because they follow you around?

**Comment by thinkpad4** [comment]
I second this request, I too would like a follower mode indicator

**Comment by night** [comment]
this is indicated in chat settings for mods and in the message area for viewers not following
