### ISSUE TITLE
Option to disable/ignore twitchnotify messages.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1952]
It's quite spammy and ruins offline chat experience when events like GDQ are hosted with all their subs. 
Unfortunately its not possible to "/ignore twitchnotify" , I just get "There was a problem ignoring this user". Can't ignore with bttv blacklist either. 

![](http://i.imgur.com/IqQqCPo.png)

**Comment by gapbl4** [comment]
There's an option in FrankerFaceZ, but it's not compatible with BetterTTV.

![](http://i.imgur.com/a8Wp2R5.png)

**Comment by night** [comment]
You can add twitchnotify in the beta/v7 to your blacklist to filter it.
