### ISSUE TITLE
TV monitor fullscreen bug

### ISSUE THREAD

**Issue by Schanzation** [night/BetterTTV#1954]
A new weird issue has occured. When watching previous streams on twitch on my TV and I press fullscreen, it now looks like this:

http://imgur.com/a/aYY2V   - Only small window in top left corner. On my PC monitor it doesnt happen. Also on live streams everything is ok on both monitors. Here for example this problem occurs. https://www.twitch.tv/harryhook/v/113372205 . I am using chromium based browser. When I disable BetterTTV everything is normal again.

**Comment by night** [comment]
I cannot reproduce any issues like this, sorry.
