### ISSUE TITLE
Following, Recommendations line separator color.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1959]
Twitch changed Following column, line separator color looks a bit off.
![](http://i.imgur.com/oh23iot.png)

**Comment by night** [comment]
color looks fine.. if anything the spacing is weird

**Comment by gapbl4** [comment]
That color doesn't fit to the scheme with other lines being grey

![](http://i.imgur.com/WfLjUAM.png)

**Comment by Stoupedog** [comment]
Looks like this is fixed now:

![](https://i.gyazo.com/4415d1c86d1062f1eeb3a31a44b8eabe.png)
