### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by CreepLPlay** [night/BetterTTV#196]
I thought the possibility to change the line spacing would be really cool, because I already thought that the comments are really near to each other, when I have the "Split Chat"-function turned on. Would be really nice in my opinion^^

**Comment by night** [comment]
Can you elaborate? Alternating on Split Chat is why we are able to group messages so closely, as otherwise it's harder to differentiate one message from another.

**Comment by CreepLPlay** [comment]
Like a slider, to change the line space a little bit, because it looks compressed to me (in my opinion). I dunno if I'm the only person, but I really enjoy the chat more when every message has a little bit space to each other.^^
![93e369c82c6a230b89e4ad673fba1441](https://cloud.githubusercontent.com/assets/10670229/5886986/c0488e84-a3b9-11e4-85f0-43e02df323ad.png)

**Comment by night** [comment]
Splitting chat with alternating colors is what allows us to place messages closer together in a more compact form. If you want more spaced messages, turn off Split Chat.
