### ISSUE TITLE
Bits Trashcan Icon

### ISSUE THREAD

**Issue by mackenzie** [night/BetterTTV#1961]
Currently, if you turn Mod Icons off, it removes the ability to delete the pinned bit message for everyone (aka, the little trashcan). Usually, I just wait for others to do it, but it would be nice if you could figure out a way to make BTTV ignore the removal of the trashcan.

I think I said that clearly.

Thanks just the same.

**Comment by EhsanKia** [comment]
Oooooh so that's why I never see the trashcan...

**Comment by night** [comment]
this is fixed
