### ISSUE TITLE
new feature idea

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#1963]
please make an option that can let us disable the recommended list that is not added below the following list .. they added that like 2 days ago and i am getting really annoyed with it because i do not like how it takes up my following list room and i really don't like the change... so can you please make a disable recommnded list or something

**Comment by AlcaDesign** [comment]
You could choose the "Default to Live Channels" option. It'll bring you to [/directory/following/live ("Channels")](https://www.twitch.tv/directory/following/live) instead of [/directory/following ("Overview")](https://www.twitch.tv/directory/following)
