### ISSUE TITLE
stream lags after typing in chat

### ISSUE THREAD

**Issue by daniandl** [night/BetterTTV#1967]
After typing anything in chat (sending), the stream will start to desync, slow down and then freeze for a second. This builds up a delay until the user refreshes the page.

Using HTML5 player

**Comment by night** [comment]
It sounds like your computer may not be powerful enough for Twitch, rather than our extension causing you issues.

**Comment by daniandl** [comment]
A 4.4ghz and GTX 960 can't run your extension?

**Comment by EhsanKia** [comment]
What other extensions do you have installed.
