### ISSUE TITLE
New feature - emote support to bypass ban of emote phrase.

### ISSUE THREAD

**Issue by DannyGG1** [night/BetterTTV#1969]
As you've seen on twitch.tv, agdq stream has been going on. Their ban list has been increasing by the day, and along with the collateral damage haHAA was banned. It is a tragic moment. I don't know the best way to bypass banning a phrase, but one way could be different phrases could result in the same emote. Basically make a betterttv emote be able to be shown aside from its original phrase. The censorship of betterttv emotes should stop! FeelsBadMan haHAA rip FeelsBadMan

**Comment by night** [comment]
We do not care to cause drama, sorry.
