### ISSUE TITLE
Blacklist keyword won't block :thinking:

### ISSUE THREAD

**Issue by evodube** [night/BetterTTV#1971]
Blacklist keyword won't block :thinking:

**Comment by Aaron128l** [comment]
Works fine remember that you have to put the emoji in the text box, not `:thinking:` as BetterTTV converts that when a message is sent.

**Comment by evodube** [comment]
How does one put a image into a text box? Curious, every other keyword blocks, except this one. Perhaps it's conflicting with the two ":" in it.

**Comment by EhsanKia** [comment]
They're not technically images. Emoji's are actual characters, just like letters. They are part of the unicode spec, which has the characters from all languages, all symbols, and now emojis.

Just copy " 🤔 " and paste it in there like you would copy any text.
