### ISSUE TITLE
Upon entering into fullscreen, all previous Chrome notifications appear

### ISSUE THREAD

**Issue by jerhms** [night/BetterTTV#1972]
If someone has ever mentioned me in a channel within Chrome `("@jerhms test")`, and I go fullscreen in a YouTube video or Twitch stream they reappear _all at once_ . It won't do it once I close that instance of chrome though. 
Thanks lads.

**Comment by night** [comment]
That sounds like a chrome bug, if anything. Notifications are fire and forget, and we will never resend them.

**Comment by EhsanKia** [comment]
I'm not sure what causes this bug but I get it all the time too. It might also have to do with multiple monitors.
