### ISSUE TITLE
So I've had this small issue forever about twitch panels with betterttv

### ISSUE THREAD

**Issue by P3ndu1uM** [night/BetterTTV#1974]
I have these settings 
[bttv_settings (txt because zip or the backup file type doesn't work).txt](https://github.com/night/BetterTTV/files/706399/bttv_settings.txt.because.zip.or.the.backup.file.type.doesn.t.work.txt)

and when I exit theatre mode (I have theatre as default), Everything seems out of place.(though, the scrollbar i featured in the video seemed a bit odd too...) 

I displayed what the issue looks like here, since it's about ui, panels and visuals, i suppose that's good enough.
Video displaying the issue: https://youtu.be/_lmjz4tiaaU

**Comment by night** [comment]
I'm not particularly sure how you managed to get into that visual state. Technically it's not possible to hide the left sidebar, and yours is never showing. Do you use Stylish or any other extensions which affect Twitch? Try disabling them and seeing if the problem still exists.

**Comment by P3ndu1uM** [comment]
Thank you, this solved it! :) 👍
