### ISSUE TITLE
Time that Stream has been up for

### ISSUE THREAD

**Issue by Satcho** [night/BetterTTV#1975]
I think that where the viewer count is on twitch, next to it, you should add an option to show the amount of time that the stream has been live for. I know streamers have uptime commands and stuff now, but I think that this would be a great idea to add, especially because it would save a lot of chat spam.

**Comment by matt3541** [comment]
Rather than !uptime, you can do /uptime. Though this prevents chat spam, I do like your idea.

**Comment by night** [comment]
We feel that the uptime of a stream does not provide really any value other than "that's cool".. for that reason we have a command instead of it being in the UI (we do not like to clutter the UI).
