### ISSUE TITLE
Add an epic emote

### ISSUE THREAD

**Issue by syndrome5** [night/BetterTTV#1977]
It's a well-known french TV presentator with epic exclamation.
All french people know this and it would be good to use it.
https://puu.sh/tooY2/b0bbcd3b08.png
little video : https://www.youtube.com/watch?v=XE6YaLtctcI

**Comment by AlcaDesign** [comment]
This repository is not for suggesting emotes. Also, this emote appears to be an already existing emote in a partnered streamer's channel.
