### ISSUE TITLE
[Feature Request] Make username clickable on Twitch main page

### ISSUE THREAD

**Issue by Marci010101** [night/BetterTTV#1978]
![pic](https://cloud.githubusercontent.com/assets/22853782/21997917/352053e2-dc32-11e6-8eea-4f70371397d2.JPG)
(Yeah, I know clicking on the profile icon takes you to the streamer's site)

It's very little problem, but I think clicking on the streamer's name to get to his/her site is more obvious than clicking on the profile pic.

**Comment by Aaron128l** [comment]
There is already link you can click that says "**Click here** to watch and chat!"

![image](https://cloud.githubusercontent.com/assets/12077192/22173409/2b39ba58-df7f-11e6-9fdc-e9d65b8cee7a.png)
