### ISSUE TITLE
BTTV global emotes not showing.

### ISSUE THREAD

**Issue by tokyoroyalty** [night/BetterTTV#1979]
My BetterTwitchTV isn't showing any of the BTTV global emotes. BTTV channel emotes are fine for some reason. 
Also, hovering over any emotes with my mouse doesn't display the name of the emote, channel of the emote (if it's a sub emote) or any of the usual information. 
I assume all of these issues are related since it all started happening a few days ago at the same time.

**Comment by Stoupedog** [comment]
All of those things work for me, try following the steps on the [BetterTTV Debugging post on the forums.](https://community.nightdev.com/t/betterttv-debugging/3685?u=stoupedog)
