### ISSUE TITLE
BTTV chat features don't load on dashboard chat after collapsing/reopening

### ISSUE THREAD

**Issue by Stoupedog** [night/BetterTTV#1983]
![dashboard chat bttv](https://cloud.githubusercontent.com/assets/9131477/22087777/cff2f2f8-de44-11e6-93f9-ea5bc4e21938.gif)

**Comment by night** [comment]
This is annoying to fix.. also broken for show/hide chat

**Comment by night** [comment]
This is fixed in beta.
