### ISSUE TITLE
problem with saving the settings

### ISSUE THREAD

**Issue by maweass** [night/BetterTTV#1985]
hi, i've been having this problem for so long so i wondered if there's a way to solve it. i set my betterttv settings almost everyday. because my bettertv settings reset everday. and my bettertv is the latest version, any solution?

**Comment by EhsanKia** [comment]
What browser are you using? Check your browser settings and make sure you don't have it set to clear cookies every time you close it.

This shows how to enable it for all browser:
http://www.howtogeek.com/137681/how-to-automatically-clear-private-data-when-you-close-your-browser/

You want to the do opposite of that. You want to NOT clear cookies and local data. That's where your settings are stored. If you clear them, your settings get deleted.

Alternatively, if you do want to keep that option, BetterTTV has a menu for saving and loading your settings so you can very quickly load them back the way you had it.

**Comment by K2177** [comment]
I don't get it why on earth would you want to save the settings into cookies aswell as require a user not to delete their cookies. That's insane... This kind of settings system prevents me from using the addon properly. This cookie issue has seemingly been around a year with several discussions about it, why not change it to actually work properly?

**Comment by EhsanKia** [comment]
And where do you recommend we store the information.

**Comment by maweass** [comment]
i am using google chrome and it was already set the opposite of that. it seems like there isn't any problem with saving the settings nowadays. thanks for the answer.
