### ISSUE TITLE
Unable to Load BTTV, Support Forums Or BTTV Settings At Times.

### ISSUE THREAD

**Issue by Firedingo** [night/BetterTTV#1987]
I'm not sure what I can do to fix my problem. I can't get BTTV to load at all, on the few occasions I managed to get something it was a broken version of BTTV, the settings page would not load and I can't load the community forums page for support. It's just like my browser can't find the page at all.
I've tried just about everything I can think of including:
-restarting our router
-restarting my PC
-disabling everything add-on wise except BTTV
-uninstalling and reinstalling BTTV
-removing cookies

I'm honestly not sure what I can do anymore to fix this issue. If you have some advice that would be appreciated.

**Comment by night** [comment]
Follow the instructions at https://community.nightdev.com/t/betterttv-debugging/3685/1 when this issue occurs again.
