### ISSUE TITLE
Sent message history (on / off) feature.

### ISSUE THREAD

**Issue by MoDog0** [night/BetterTTV#1988]
Would it be possible to get the ability to turn on and off the recent message history in the "send a message" box.
When typing messages I often use the up and down arrow to edit the message, usually due to spelling mistakes. However as of now now up and down filter though recently sent messages, making it hard to edit the current message. I checked the setting page and did not see the option to turn off the recently sent message feature.
~MoDog0

**Comment by dannoe** [comment]
There's a command for this feature:
`/linehistory on/off -- Toggles the chat field history (pressing up/down arrow in textbox)`

**Comment by MoDog0** [comment]
I know this was closed but /linehistory off/on no longer works. I just noticed my chat entry has linehistory on again and I am getting the error " Unrecognized command: /linehistory" when I try to turn it back off.
