### ISSUE TITLE
Black List of games - Not in view

### ISSUE THREAD

**Issue by fernandohg** [night/BetterTTV#199]
Is there a way to filter the page: "twitch.tv/directory/all", so the name of games in a black list , dont appear in the directory/all channels.

For example: i dont like games like: LOL, WOW, heartstone, dota , starcraft etc.  I put them in a blacklist and they dont show up in the directory/all.

I'm not sure if "BetterTTV" can modify these aspects of TwitchTV but it would be awesome to have a feature like these.

**Comment by night** [comment]
Duplicate of #70
