### ISSUE TITLE
Ability to block channels

### ISSUE THREAD

**Issue by Dunravin** [night/BetterTTV#1992]
Hello BTTV

I would really like the ability to block channels appearing in my feed. The current set up at Twitch does not provide this, only the reverse where a channel can block viewers. 

It would be preferable to be able to block a channel from the feed like screens and not have to go into the channel to effect the change.

Many thanks!

**Comment by a13ph** [comment]
@dunravin this works really well for me:
https://openuserjs.org/scripts/LinogeFly/Hide_unwanted_streams_on_Twitch#supported-pages
chrome extension version:
https://chrome.google.com/webstore/detail/hide-unwanted-streams-on/kpgfplcjhleaadnmjmkjddcmekdhdiia

**Comment by night** [comment]
duplicate of #70
