### ISSUE TITLE
Scroll Bar Windows Style

### ISSUE THREAD

**Issue by tocafita** [night/BetterTTV#1993]
Some times my Twtich get the default scroll bars from windows beside the "slim"ones from twtich. 
Screenshot: http://imgur.com/cF4lP7F
![scrollbar](https://cloud.githubusercontent.com/assets/4885298/22265177/c0e0b48c-e22f-11e6-88e9-f63c2be77fe6.png)

**Comment by Orrielel** [comment]
Can relate, same thing.

It's a new(?) overflow-y rule with scroll for the elements with class `tse-scroll-content` that causes it.

**Comment by night** [comment]
Browser/OS/Versions please.. I cannot reproduce..

**Comment by EhsanKia** [comment]
I believe this was a bug by Twitch which got fixed.

**Comment by night** [comment]
This is confirmed happening on default Twitch on Firefox.. not our bug.. you'll need to complain to Twitch.
