### ISSUE TITLE
Feature Request: Hide Recommended Channels in Left Sidebar

### ISSUE THREAD

**Issue by JavaJoeCoffee** [night/BetterTTV#1997]
Hi BTTV is great, but it could be greater-est.

The Left Sidebar is blowing up and is so big it now has a scroll bar (so ugly). Being able to Hide (or truncate) the "Recommended Channels" list might help that.

**Comment by night** [comment]
They are already hidden by default.. Did you accidentally enable them in the BetterTTV settings?
