### ISSUE TITLE
BTTV Emotes

### ISSUE THREAD

**Issue by KoopaTheTurtle** [night/BetterTTV#1999]
BTTV emotes dont appear. I had BTTV emotes working fine, closed browser as i went out and came back like an hour later and BTTV emotes no longer show in chat. I have uninstalled and reinstalled BTTV with no luck :/

**Comment by b4n4n4** [comment]
I have the same problem but only with VODs, on live streams the emotes work. And it's like that since yesterday.

**Comment by KoopaTheTurtle** [comment]
I have the emote menu enable and BTTV Emotes on in the settings and the emote list doesn't show any BTTV emotes

**Comment by KoopaTheTurtle** [comment]
And apparently they work now :/

**Comment by macintorge** [comment]
The same happens to me.

**Comment by night** [comment]
BetterTTV emotes broken in VoDs issue is now fixed.
