### ISSUE TITLE
(Possible bug with BTTV)

### ISSUE THREAD

**Issue by CD33KS** [night/BetterTTV#2000]
When watching a stream with BTTV active, it will freeze the entire tab when hovering mouse over left side of the twitch page (Following, Games, Discover, Channels, Videos, Creative) and takes a few seconds to recover and moving you mouse up and down the list rapidly will freeze the stream and chat until you move your mouse away from them.

**Comment by night** [comment]
I cannot reproduce this. If you are getting this consistently, then please send me a chrome profiler log when this is happening through Discord so I can analyze what's consuming your resources. You can join our Discord server at https://discord.gg/nightdev if you need help.
