### ISSUE TITLE
BetterTTV emotes only work in pop out chat

### ISSUE THREAD

**Issue by marganis** [night/BetterTTV#2002]
So BetterTTV emotes dont work in "normal" chat, I have to pop out the window and then all emotes work fine. I have reinstalled the addon, I am using google chrome.

**Comment by night** [comment]
I cannot reproduce this issue. If you're having issues in VoDs, that was already fixed.

**Comment by LazyBoot** [comment]
I was also having the same issue, but it went away when I disabled all my other extensions.
However after I turning all of them back on I can't reproduce anymore.

**Comment by LazyBoot** [comment]
Had the issue reappear on me, and I think I've narrowed it down to an issue with an adblocker (I think it's the easyprivacy list blocking spade.twitch.tv, but not sure)

**Comment by EhsanKia** [comment]
Which adblock extension do you use?

**Comment by LazyBoot** [comment]
uBlock
