### ISSUE TITLE
Twitch panels are very small (this time I dont think stylish is the source)

### ISSUE THREAD

**Issue by P3ndu1uM** [night/BetterTTV#2004]
So my twitch has just shrunk in box sizes when it comes to everything. I'll just leave a video and you'll see what i mean by small divboxes/boxes/panels. I show a comparison with the browser I use and mc edge.

video: https://youtu.be/SHK7XB4Da7o

From my previous problem, i double checked stylish and im almost certain it has nothing to do with this, i even turned it off for the video, the dark style comes from bttv.

bttv settings: 
[bttv_settings 123.txt](https://github.com/night/BetterTTV/files/736068/bttv_settings.123.txt)

**Comment by EhsanKia** [comment]
ctrl+0
