### ISSUE TITLE
error reading chat

### ISSUE THREAD

**Issue by cosmic-witch** [night/BetterTTV#2005]
I've gotten the error about being unable to read chat, tried clearing my cache and cookies and still getting the error.

**Comment by HerbMon** [comment]
I'm having the same issue, sometimes a few old messages load, BTTV has an error reading chat, and then loads, but no new messages are showing in chat and I'm unable to send messages in chat (starts a new line) until I disable BTTV.

**Comment by night** [comment]
This should now be resolved.
