### ISSUE TITLE
BTTV chat error, only displaying emotes and unable to send messages with "Enter" on my computer

### ISSUE THREAD

**Issue by tyler29674** [night/BetterTTV#2008]
<img width="1271" alt="screen shot 2017-01-27 at 8 17 41 pm" src="https://cloud.githubusercontent.com/assets/25396725/22393007/c018b04a-e4cd-11e6-9996-5747e4cc2f33.png">

**Comment by dapeton** [comment]
Having the exact same problem, bump

**Comment by tonteasy** [comment]
I am also having this problem.

**Comment by night** [comment]
duplicate of #2005
