### ISSUE TITLE
BTTV Channel Emotes Not Working

### ISSUE THREAD

**Issue by ghoulkreap** [night/BetterTTV#2015]
Emotes like LUL or haHAA load fine, but channel emotes (such as Forsen's channel emotes like nymnCorn or monkaS) won't load. Any solutions? 
![vv](https://cloud.githubusercontent.com/assets/25403676/22397429/1856b9bc-e5ac-11e6-84b6-cffcdaf6a460.PNG)

**Comment by night** [comment]
This looks like a replay. This has been fixed as of 686729c4e432186cdc879f910f51e0b31ae04536
