### ISSUE TITLE
Option to replace "Watch Live" with "Watch Full Video" on clips.twitch.tv

### ISSUE THREAD

**Issue by LunaWasHere** [night/BetterTTV#2016]
I was wondering if it was possible to  create an option to switch this button: http://puu.sh/tEJBE/8065cf06d1.png
with this button: http://puu.sh/tEJCv/90d7656b6c.png on the Clips website.

**Comment by night** [comment]
Clips do not have the context of the video they originated from, so unless Twitch were to add that capability it's not possible.
