### ISSUE TITLE
An option to follow the streamer with /follow command

### ISSUE THREAD

**Issue by XxBonf1r3xX** [night/BetterTTV#2019]
Would that be possible to add? I hate to click on Follow button because 99% of time it's broken and it will unfollow the streamer after a while by itself. I think Twitch will register one click and after a while it will register second click to unfollow the streamer.

With this command we would not have that issue because we can't unfollow the streamer with /follow command, to unfollow we would have to use /unfollow command.

**Comment by EhsanKia** [comment]
The follow button works just fine for me and never unintentionally unfollows anyone. If you're experience issues with it, it makes more sense to try and fix the button rather than add a different way of following channels.
