### ISSUE TITLE
Move chat to left side and the left bar to the right

### ISSUE THREAD

**Issue by dminer78** [night/BetterTTV#202]
Hello, I looked a bit and I didn't see this. I have two screens and it would be really useful to have chat on the left side of the screen instead of the right. I usually do something on my main and if chat is on the left then I can just glance instead of looking to the far right.

**Comment by night** [comment]
This would most likely require tons of modification to the page resizing function and CSS, and since in most countries you read from left to right this establishes an odd flow for the navigation of the site. We are not considering this despite it being requested multiple times.
