### ISSUE TITLE
Vivaldi closes when BetterTTV is enabled

### ISSUE THREAD

**Issue by ckorn** [night/BetterTTV#2020]
With the BetterTTV extension enabled Vivaldi just closes randomly after some time. There is no crash dialog in Windows the browser is just closed.

BetterTTV Version is: 6.9
Vivaldi version is: 1.6.689.40 (Stable channel) (32-Bit)

**Comment by night** [comment]
I mean, that sounds like a bug you should report to Vivaldi.. Stuff running in the window context shouldn't cause a browser crash.
