### ISSUE TITLE
FF51 bugged using BTTV

### ISSUE THREAD

**Issue by daveimagery** [night/BetterTTV#2021]
I'm not a techie, but I noticed just recently, FF will stop responding, and buttons are slow to work on twitch.  Made a vid illustrating the problem.

https://youtu.be/oLk7dlYugII

**Comment by Artorp** [comment]
It's an issue with Firefox on Twitch.tv, BTTV isn't related. You ran Firefox in safemode with BTTV disabled yourself.

We'll have to contact Twitch.TV about this issue. FYI I tested twitch.tv in both v50 and v47 of Mozilla Firefox, and it was still very slow compared to Google Chrome.

**Comment by daveimagery** [comment]
Well now I'm confused.  When I switched to safemode, that didn't really 
seem to determine much.  I could barely get twitch to load at all.  I 
attributed that (perhaps incorrectly) to flash not being loaded in that 
mode.  I know Twitch now uses html5 for video, but the the UI is still 
flash.  Now today when I disabled BTTV, it was a lot better.  FF stopped 
doing the not responding thing, and the button highlights appear much 
faster.  Then again, I'm just a dumb redneck, and have no clue what I'm 
talking about.  lol :)

Thanks for your fast reply.  I absolutely love BTTV, pretty much can't 
live without it.

**Comment by notorwarren** [comment]
I have this problem as well on FF51 64 bit.  With BTTV, the side buttons on the left are slow to respond just like in daveimagery's video.  However with it disabled everything works fine like it should.

**Comment by night** [comment]
It's not BetterTTV causing this. Default Twitch suffers from the same issues. Just because it works when disabled once doesn't mean it is our fault. It's something that happens some of the time, usually getting worse over time and with more page navigations that you make.

**Comment by daveimagery** [comment]
Sounds like someone is in denial, and may also need some Vagisil?
