### ISSUE TITLE
Emotes not displaying unless reloading site

### ISSUE THREAD

**Issue by Skytis** [night/BetterTTV#2022]
When I join a stream, the BTTV emotes won't display (I'll just see the text as if they were disabled).
It says in chat BTTV has been loaded and things like line-split work, but the emotes don't. I tried opening the stream again in a new tab, didn't help, the only thing that fixes it is reloading the website once.
After reloading it works (I think) until I restart my PC. At least exiting Chrome and starting it up again won't make the problem reoccur.

I'm not the only one with this issue and it's most likely not my OS/browser's fault as this problem existed for months on Windows 7 and I'm now on Windows 10 (clean install) and still experience this.

Using latest versions of Chrome and BTTV, also running FFZ.

**Comment by EhsanKia** [comment]
Try without FFZ and see if it still happens.

**Comment by Skytis** [comment]
Disabled FFZ, still happened, no idea what else could cause interference.

**Comment by Senpos** [comment]
Experiencing this thing for two days, i suppose. Sometimes, BetterTTV emoticons are missing in chat and in Emote Menu. I am fixing this by hard page reload and re-applying my backup file with BetterTTV settings.

I am not sure, but this began once i updated my Chrome to version 56. I may be wrong.

**Comment by night** [comment]
Without a way to reproduce issues we have no means to fix them. Please try to figure out if it's a setting you enabled or an extension you have running that is causing these issues.

**Comment by night** [comment]
We've had a couple reports that uBlock (perhaps any Adblock) seems to cause this issue sporadically. If you run one of these extensions, try disabling it and then seeing if you can still reproduce the emotes not loading.

**Comment by Senpos** [comment]
Unfortunetly, couldn't reproduce it step by step. 
By the way, yes, i have installed uBlock Origin. 

Here is what uBlock got: http://i.imgur.com/lh0f9Kl.jpg

Restarting the page fixes this sometimes.

Will try to play around it a bit more.

**Comment by jrhwr** [comment]
What if we whitelist the bttv domains on uBlock? I'm definitely not turning that off.

**Comment by EhsanKia** [comment]
That might work as a temporary solution. We should definitely like to get to the bottom of this though.

**Comment by Rudolpher** [comment]
It happens with all extensions disabled except BTTV. I can reproduce it with CTRL+F5 refreshing twice. It works first time, then stops working second time. Very random what it affects tho - 
Always: Auto-complete emotes stop working, BTTV emotes not visible in chat.
Sometimes: Enhanced emote menu empty as is view list if it happens.

The emote thing happens with default setting.
Can send log on pm or similar if wanted, but I don't see anything different between refresh of it working, and refresh of it not working.

**Comment by Hemipheistos** [comment]
Glad i am not the only one with this issue. I am trying since a few days to get to the bottom of this without any success. I also reported this on the BTTV Forum. But for some reason the post got deleted there, without any notice (strange).

I did a fresh install of Chrome without any synchonization settings and a brand new user.
Only extension now is BTTV and this issue still persists.

Win 10 Professional - Chrome 56.0.2924.87 (64-bit)

**Comment by thinkpad4** [comment]
Been getting this a lot lately too

**Comment by SoggyWenis** [comment]
I have uBlock disabled on Twitch because I have Prime and this problem still persists

**Comment by joipod97** [comment]
Tried everything above like many other users and I'm still experiencing the same problem as others. I'm a mod and it's making this very frustrating.

**Comment by jrhwr** [comment]
ok. who could instruct is on debugging? one night i got a non-responsive script from bttv when trying to click on the directory at the left of the page.

**Comment by night** [comment]
We're aware of this issue, but the only fix is to wait until we release v7. It could be days, it could be weeks. It's basically a complete rewrite of the entire extension.

**Comment by night** [comment]
If you're still having issues, we released a beta version of BetterTTV v7, which is a complete rewrite. It should address these race issues plaguing the extension for so long.

To try it out, enable the beta from the BetterTTV settings. Note: Currently when you turn on the beta, there's no way back. If you want to go back, you need to clear your cookies (thus losing your settings). If you want to save your settings just in case, make a backup before turning on the beta.
