### ISSUE TITLE
Fullscreen (vods broken) BUG

### ISSUE THREAD

**Issue by LukeDavies367** [night/BetterTTV#2023]
Hello,
Sorry if this as been posted all ready.  As it 31-01-2017 (18:00PM (GMT) this is a bug i'm getting. (Google chrome is up-todate) 
![sdsd](https://cloud.githubusercontent.com/assets/11139937/22477982/08ed5e3c-e7e0-11e6-86ab-a75d95c30e2c.png)

ONLY when i watch vods (Stream isn't live but recorded) I have to disable BBTV so it's just using Twitch to make it go full screen.

**Comment by EhsanKia** [comment]
Can you give exact steps to replicate the bug?

**Comment by LukeDavies367** [comment]
Go to anyone channel "videos" and click any video;

e.g.
https://www.twitch.tv/videos/118747614 then click "Full screen" it does same thing as image above does. (Unless it just happens to me)

**Comment by EhsanKia** [comment]
Hmm, doesn't happen for me. Maybe some specific settings?

**Comment by LukeDavies367** [comment]
Really? It only happens when i have BTTV active (Below picture is all i have active) If it just me no problem ill just disable bttv when watching vods, Thank you for helping tho EhsanKia.
 
![ff](https://cloud.githubusercontent.com/assets/11139937/22519714/4e9e8fae-e8a9-11e6-9880-2cc345e0284d.png)

**Comment by Stoupedog** [comment]
This seems to be happening if the screen is below a certain resolution, this has been happening on my laptop (MacBook Air) for a while now but I couldn't figure out why it worked fine on my pc until now (same bttv settings) (Also both using the most up to date version of Chrome) 

I also tested this in Firefox and fullscreen seemed to work fine with both resolutions.

**Comment by LukeDavies367** [comment]
Stoupedog, Ye i can full-screen normal when i turn bttv off. (So it's just running on twitch) but as soon as i load up bttv it doesn't work, Its all good for live shows tho it really only vods that the screen breaks.

**Comment by EhsanKia** [comment]
would it be high dpi devices maybe?

**Comment by Stoupedog** [comment]
It appears when launching full screen on a smaller/lower resolution device, the page (with BTTV enabled) 'scrolls down' which sets `data-mini=true` on the player div, causing the mini-player css to load. I actually managed to get this bug to happen with BTTV disabled by entering fullscreen and scrolling down, it seems the only way BTTV is affecting this is by scrolling the page automatically.

**Comment by EhsanKia** [comment]
I think I know where the issue is.

**Comment by LukeDavies367** [comment]
o sweet, Ye i have no idea how to code, Ill have to wait for the pros to fix it in next patch haha

**Comment by LukeDavies367** [comment]
UPDATE; Clicking fullscreen icon it does "picture above" but double click picture is seems to work fine (For time been) This is with BTTV active!
