### ISSUE TITLE
theater mode

### ISSUE THREAD

**Issue by gayelephant** [night/BetterTTV#2024]
I have the 'automatically enable theater mode' function enabled but wont actually go to theater mode. I check the setting every time and it remains enabled.

**Comment by EhsanKia** [comment]
https://github.com/night/BetterTTV/blob/1f3951daff1cb66a9e4b55b0009d1a959ed5e793/src/js/main.js

line 216 and 235 is the issue, and I think it makes more sense to move that check inside the plugin.
