### ISSUE TITLE
BTTV Emote menu pop up and icon arent working 

### ISSUE THREAD

**Issue by K3x707x** [night/BetterTTV#2026]
The BBTV emote pop up and icon under the chat bar isn't working for me. I can type in the emotes and they work. I have uninstalled and reinstalled multiple times to see if that will fix it. I have checked all the BBTV settings to make sure thats it not something like a setting that just wont allow it. Im at a loss here....

**Comment by EhsanKia** [comment]
Could you provide more details? Does the button not show up at all? Does the button show but not open the menu? Is there any errors in the console (ctrl+shift+j)? Do you have Emote Menu enabled in the settings?

**Comment by K3x707x** [comment]
It's not showing the button at all. The settings are all on for emotes and gifs and anything that has to do with emotes. Just to make sure I didn't miss one I enabled them all for emotes. I am currently at work, but when I get home I'll double check again and get back to you.

**Comment by EhsanKia** [comment]
Yes, it's a setting called "Emote Menu" specifically. Double check and if it still doesn't work I'll try to look closer.
