### ISSUE TITLE
Expand blacklisted keywords for system messages

### ISSUE THREAD

**Issue by ceriathstudios** [night/BetterTTV#2027]
It would be great if it would be possible to use blacklisted keywords with things like hosts and subs.

Maybe that is already possible and i just did something wrong, but what i tried to accomplish is to blacklist a specific user trying to spam chat by hosting and unhosting.

Any help is appreciated.

Best regards
~ceriath

**Comment by EhsanKia** [comment]
Not sure if this will work, but try out putting "(twitchnotify)" in there, it should block out subs, and maybe alerts too.

**Comment by ceriathstudios** [comment]
ew, yeah i already thought of that, but that would just straight block everything. Not really what i want to do here honestly

**Comment by EhsanKia** [comment]
Might have to reroute those messages through the blacklist filter.
Also, this is very similar to https://github.com/night/BetterTTV/issues/1952

**Comment by ceriathstudios** [comment]
That would be awesome. So you could remove all by blacklisting (twitchnotify) or just special ones by blacklisting other names

**Comment by ceriathstudios** [comment]
Finally had some time to take a look into the sourcecode: 
The blacklist is applied after messages are checked if they are just notifications, and those just return immediately if they are. So in handlers.js swapping lines 492-497 in front of the notification check starting at 455 should actually do the trick.
