### ISSUE TITLE
Chat does not work in Firefox while logged in

### ISSUE THREAD

**Issue by warcode** [night/BetterTTV#2028]
Firefox Developer Edition 53.0a2 (2017-02-02) (64-bit)
BetterTTV 6.8.5

While not logged in the chat appears as normal and functions perfectly.

While logged in only the 

> BetterTTV v6.8 Loaded.
> 22:20 Welcome to XX's chat room!

as well as system messages like bans and timeouts appear.

**Comment by night** [comment]
We do not support developer or beta versions of browsers, sorry. Generally bugs upstream (in the browser itself) can cause bugs downstream (like BetterTTV), and they usually get ironed out before released to everyone.
