### ISSUE TITLE
Estimated Earning

### ISSUE THREAD

**Issue by stdscatchemall** [night/BetterTTV#203]
Why would you include this option? Not only is it rude to the broadcaster because they don't like telling people how much they make, but it's also against Partner Contracts to discuss the amount of money they make.

I find it extremely rude that you would include something like this.

Can you at least add a toggle to it if you are going to include it, because I don't like being rude.....

**Comment by night** [comment]
What are you.. talking about? BetterTTV has no "estimated earning" anywhere.

**Comment by stdscatchemall** [comment]
![Image of Estimated Earnings](http://i.imgur.com/xbRibeg.png) It's even styled by BTTV, which I guess could be a coincidence. Sorry for going on a hate speech immidately as i based it off the BTTV styling. Guess I have to figure out what added that now.

**Comment by night** [comment]
That is *not* BetterTTV

**Comment by stdscatchemall** [comment]
Ok. Very sorry for hate speeching. Twitch wouldn't do this because it would void Partner Contracts So.

Again, Very sorry :(

**Comment by DTittel** [comment]
The style sheets are written so they are generalized little details like
that are not customized individually.

That may be a partner / team feature (can you offer some context was that
on your channel or a member of your Twitch Team's channel?).

**Comment by stdscatchemall** [comment]
It's on all streams. Not just one. It's not an extension for Twitch, I checked for it. It's really... REALLY weird....

**Comment by DTittel** [comment]
Could you email me a list of your browser extensions dtittel @
mods.twitch.tv curious whats adding this
