### ISSUE TITLE
Fullscreen exit with disabled channel header issue

### ISSUE THREAD

**Issue by juress** [night/BetterTTV#2032]
Hi,

if you disable channel header and exit fullscreen by doubleclicking, you get rolled down as if the header is still there, if you exit fullscreen by pressing ESC you are correctly aligned.
![bttvfsexit](https://cloud.githubusercontent.com/assets/1379003/22619262/5dc40064-eaf1-11e6-9ae0-90f58db31a8d.png)

**Comment by EhsanKia** [comment]
We're away of this issue, I'll see if I can come up with some solution today.
