### ISSUE TITLE
[Feature request] Better player control buttons

### ISSUE THREAD

**Issue by Gladrat** [night/BetterTTV#2033]
Hi ! First of all, thank you for your work !

Maybe i'm the only one, but i think twitch player control buttons (play/pause, mute/unmute, etc.) can be improved by enlarging their size. Especially on (large) TV, those buttons are sometimes hard to point on.

I think it would be really really helpfull to create an option ("TV Mode" ?) that make them float in the middle of the page and with a bigger size.

For example : http://imgur.com/a/Fp1Uw

Love you guys !

**Comment by night** [comment]
If you are watching Twitch on a TV, I'd recommend getting a Chromecast instead.
