### ISSUE TITLE
emotes are broken and other.

### ISSUE THREAD

**Issue by animorph127** [night/BetterTTV#2036]
So emotes for bttv are broken. Bttv emotes aren't even showing up both in chat or in the emote section. Also i've had a problem with needing to reload every time i go into a chat for about 2 months now. So not only do i have to reload i also have to sometimes put the screen in theater mode even though i have it enabled to do so everytime

**Comment by night** [comment]
We were performing API maintenance..

**Comment by animorph127** [comment]
ah ok, i noticed the emotes came back
