### ISSUE TITLE
Translation feature

### ISSUE THREAD

**Issue by Shyrshadi** [night/BetterTTV#2037]
I feel like the translate feature is rather pointless when you are only allowed to request one translation every five minutes. Most of the streams I watch don't need translation, but when I watch, for instance, Korean StarCraft II pros play, most of their chat is in Korean. Most of the time I'll tab back and forth between Google Translate and keep up more or less but was super excited to find the translate option in Better TTV. However, I was equally disappointed by a 5 minute cooldown.

I'm not sure this is an issue you can address with your current system but, in my opinion, it would be a major benefit to foreign viewership.

Thanks for all you do :D

**Comment by EhsanKia** [comment]
Sadly, the translate API is quite expensive and it's not really possible for a free extension like BTTV to offer it for the millions of users. One thing you can do though is use Google Chrome's page translation and it actually works quite well.

**Comment by Shyrshadi** [comment]
alright, thanks for the information :) 

    On Monday, February 6, 2017 8:38 PM, Ehsan Kia <notifications@github.com> wrote:
 

 Sadly, the translate API is quite expensive and it's not really possible for a free extension like BTTV to offer it for the millions of users. One thing you can do though is use Google Chrome's page translation and it actually works quite well.—
