### ISSUE TITLE
Feature Request: Remove white shadow in chroma key mode.

### ISSUE THREAD

**Issue by LiquidPlutonium** [night/BetterTTV#204]
The white shadow/Background on text in chroma key mode is mostly useless and is more trouble than it's worth to streamers who use it for transparent chat overlays, it's always making keying out the black spaces annoying.

Normally: 
![test](https://cloud.githubusercontent.com/assets/10779898/5985111/0a8fd082-a8ac-11e4-9e08-d4559daf9120.PNG)
With Removed white shadow: 
![test2](https://cloud.githubusercontent.com/assets/10779898/5985112/0ce59a7e-a8ac-11e4-8f95-ad59d668287e.PNG)

**Comment by night** [comment]
Chroma keyed chat is something that will probably be removed from BetterTTV. You should switch to something like https://nightdev.com/obschat instead.
