### ISSUE TITLE
BTTV Making Twitch Unresponsive

### ISSUE THREAD

**Issue by rootbear75** [night/BetterTTV#2042]
BTTV makes twitch unresponsive after having it open for multiple days.  I've tested this a couple times by removing BTTV and repeating the same scenario, and every time, having BTTV enabled eventually causes chrome to freeze and lock up when returning focus to a twitch page after being tabbed away from it in another window.

I've attached a screenshot of Twitch itself using over a GB of RAM with BTTV enabled, and only 25% of that without it enabled.
With BTTV:
![screenshot at 08-51-51](https://cloud.githubusercontent.com/assets/2320924/22701852/b921fdde-ed13-11e6-91b8-5452f5f845c5.png)

Without BTTV:
![screenshot at 08-59-47](https://cloud.githubusercontent.com/assets/2320924/22701882/ca07025c-ed13-11e6-9088-722c8e190e0f.png)

This has become such a problem that i've been forced to remove BTTV because the inconvenience of having to restart chrome every time BTTV leaks is annoying as heck.

**Comment by rootbear75** [comment]
Bump for no comment yet.  I have other people who have dropped BTTV for other plugins such as FFZ because of the above described issues.

**Comment by TheSixStringSamurai** [comment]
I have the same issue with chrome. The twitch page becomes unresponsive to input after about an hour.

**Comment by PhillMcKraken** [comment]
I also have been seeing this for about two weeks or so now. Never had an issue before. 

Disabling BTTV makes everything responsive again. I tried doing profiling, but cant see anything obvious. I also enabled debug logs, but nothing spits out. Its very strange.

See attached gif showing lag in action. Note, video was PAUSED during this time but it doesnt seem to matter.
![lag](https://cloud.githubusercontent.com/assets/20247733/23099365/46a2129c-f62a-11e6-8ec9-2931629e14e7.gif)

**Comment by night** [comment]
We're aware of this, but the only fix is to wait until we release v7. It could be days, it could be weeks. It's basically a complete rewrite of the entire extension.

**Comment by imsomony** [comment]
Is there anything we, as users, can do to help you troubleshoot and resolve things @night ? Or are you aware of the issue(s) and resolutions, and it's just a matter of time to recode?

**Comment by night** [comment]
Anyone who wants to help aid in porting features is welcome. Otherwise there's not much anyone can do to help. You can track progress at https://github.com/night/BetterTTV/commits/v7 There is much left to do.

**Comment by night** [comment]
Twitch seems to have fixed this on their own. Closing this.
