### ISSUE TITLE
Friends Chat Badge

### ISSUE THREAD

**Issue by Miltontheepic** [night/BetterTTV#2043]
Hello,
I have always wanted a chat badge for your twitch friends. So you can see your friends in chat. Any chance it will be possible

**Comment by night** [comment]
We don't think there's much value to adding badges to friends.. You should already know who a friend is.. the purpose of badges is to give status to people you may not know.

**Comment by EhsanKia** [comment]
The issue is there's already way too many badges. The max right now is 4-5 and it's ridiculous. Adding more badges just makes the issue worse.
