### ISSUE TITLE
Would it be possible to make /unpin function like x'ing out and/or dismissing pinned cheers when a mod?

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2051]
I remember /unpin working at one point, but now it doesn't.  Typing /unpin to clear pinned cheers is faster for me then clicking the dropdown and then clicking the dismiss button

**Comment by night** [comment]
That command is not ours, but Twitch's. If it broken, then they broke it. You should verify if it works on default Twitch.

**Comment by EhsanKia** [comment]
Seems like it doesn't work in Vanilla twitch either.

**Comment by thinkpad4** [comment]
Can one be made for BTTV?

**Comment by EhsanKia** [comment]
Alright, full story short, Twitch had /unpin command, only worked for mods, we added command on BTTV which makes it work for everyone (locally), then twitch added a SECOND kind of pinned cheers and a SECOND command called /reset (wtf is that name anyway), and that one doesn't go through BTTV at the moment.

Basically, I'll fix it soon.

**Comment by night** [comment]
classic

**Comment by EhsanKia** [comment]
/localunpin in V7 does this for both kinds of pinned cheers.
