### ISSUE TITLE
Emote tooltip displays the old name of the channel

### ISSUE THREAD

**Issue by ThibaultVlacich** [night/BetterTTV#2052]
Hello,

We recently had a channel rename (~ a month ago), and weirdly, the tooltip BetterTTV adds when hovering an emote of our channel still displays the previous name of the channel.

**Comment by Slikrick** [comment]
I believe hover tooltips are sourced from twitchemotes.com, so you would need to contact the owner of the site to get that changed up. https://twitter.com/bgeorge is his twitter, or use the contact form of that website.

I gathered this from [this tweet](https://twitter.com/BetterTTV/status/753044314352066560) that basically had the same problem as yours.

**Comment by ThibaultVlacich** [comment]
I fixed the bug myself by going on twitchemotes.com and searching for both the old name and the new name of the channel. It seems to have updated their database.
