### ISSUE TITLE
[Feature request] Option to disable the PIP player that displays when navigating away from a channel

### ISSUE THREAD

**Issue by IndubitablyBengt** [night/BetterTTV#2054]
[Here is a video clarifying if it is unclear.](https://streamable.com/sm8dq)

**Comment by Stoupedog** [comment]
There is already an option to disable this in the cog wheel settings menu in the bottom right of any stream. (Mini Player)

**Comment by IndubitablyBengt** [comment]
Got it, sorry for the thread, it's a hard thing to Google I really couldn't find an answer as I didn't know what to call the feature.
