### ISSUE TITLE
Link Hosts Directly to Hosted Target

### ISSUE THREAD

**Issue by authorblues** [night/betterttv#206]
On my following directory, please add the option to make hosts link directly to the channel that they are hosting, rather than to their own channel providing the host. If A hosts B, the host link in my following directory should take me to B, not to A.

**Comment by ericchase** [comment]
This request is from 2015 and from what I can see it hasn't been implemented yet. This is an easy fix, which I've done with a userscript. Is there a guide on how to contribute to BetterTTV?

**Comment by night** [comment]
Host mode is being removed on Oct. 3, making this request obsolete.
