### ISSUE TITLE
Fix Forward on Videos

### ISSUE THREAD

**Issue by JustusKempfer** [night/BetterTTV#2061]
When I watch videos on Twitch and I want to skip through them using right Arrow, Twitch does weird things, if I'm spamming it, which makes it basically useless to me. Would be nice if there would be a feature to normalize this feature of the Twitch player.

**Comment by night** [comment]
It can't be fixed, sorry. The way moving forward in Twitch videos works is by loading video parts in the future, which are segmented chunks of video. When you move forward you are loading different chunks starting at different times.
