### ISSUE TITLE
Bttv menu not appearing

### ISSUE THREAD

**Issue by JxKobex** [night/BetterTTV#2063]
I have had this issue previously but it eventually worked itself out. The title really says it all the menu does not appear for me at all. I use chrome and I have uninstalled and re-installed several times.

**Comment by Stoupedog** [comment]
Make sure you have 'Emote Menu' setting enabled in the BTTV settings, it's not enabled by default even if emotes are enabled.

**Comment by JxKobex** [comment]
There is no menu for me to enable anything though. It does not appear

**Comment by Stoupedog** [comment]
Oh sorry I misread your issue. So to clarify, if you expand the twitch menu in the bottom left you don't see the 'BetterTTV Settings' option?

![](https://i.imgur.com/1sIeJD6.png)

Have you tried the steps on the [BetterTTV Debugging post](https://community.nightdev.com/t/betterttv-debugging/3685?u=stoupedog) on the forum?
