### ISSUE TITLE
PLEASE make an option to be able to delete whispers

### ISSUE THREAD

**Issue by WagsFTW** [night/BetterTTV#2065]
First and foremost: BTTV is superbly an awesome program.  Thank you very much for developing it.

I would LOVE to see an option to be able to delete your whispers. I don't want to turn them off completely, which I know BTTV has that, but I would like to delete the ones I don't want. PLEASE consider this as a future feature. Thank you for your time.

**Comment by Slikrick** [comment]
Why do you need to delete them? Twitch already allows you to [clear out conversations from in the whispers menu with an "X"](https://i.imgur.com/ZFJxbIg.png) and as you said BetterTTV can hide the whispers altogether.

BetterTTV can't *delete* whispers, twitch is the only thing that would have access to that data.

**Comment by WagsFTW** [comment]
That's the problem, the x does nothing. Nothing happens when I click it. 

As far as why I want them deleted, same reason I keep my emails sorted and my inbox clutter free. No reason to have year old whispers cluttering up the place lol

**Comment by night** [comment]
You are able to close whisper conversations as already described. It's not possible to delete them, however, as Twitch doesn't have that capability.
