### ISSUE TITLE
Add the ability to pin channel owner/selected user chat messages to top.

### ISSUE THREAD

**Issue by WeededDragon1** [night/BetterTTV#2066]
If you enable the option to pin highlighted messages, any messages with your keyword(s) are pinned to the top of your chat window. It would be nice to pin certain people or the channel owner to the top too. In some instances the channel owner will link something in chat, but chat is going too fast for anyone to see. Pinning their messages to the top would be a solution to this issue.

**Comment by Slikrick** [comment]
You can already specify usernames you wish to be highlighted in your highlight settings

>Type some highlight keywords. Messages containing keywords will turn red to get your attention. Use spaces in the field to specify multiple keywords. Place {} around a set of words to form a phrase, **and () around a word to specify a username**. Wildcards are supported.

So if you put the owner or a moderators username surrounded by () in your highlights they will show up as highlighted messages.
