### ISSUE TITLE
 Highlight Users

### ISSUE THREAD

**Issue by dragonx2x1** [night/BetterTTV#2068]
It would be nice to have a way to set certain users to a chosen highlighted color, that way as you get to know people in a stream, you can categorize users by for instance trolls, helpful people, spammers, etc...

**Comment by AlcaDesign** [comment]
This could be useful **and** aesthetic if only the usernames were colored based on the category.

**Comment by dragonx2x1** [comment]
Exactly.

**Comment by night** [comment]
duplicate of #237
