### ISSUE TITLE
Customize buffer size

### ISSUE THREAD

**Issue by Ystenes** [night/BetterTTV#2073]
Is there any possibilities for a custom buffer size in Twitch? It will be easier to sync the chat to the video, assuming you have a decent internet connection.
Hope you can find a way to implent this in BetterTTV

**Comment by night** [comment]
Twitch controls video buffer size internally, and we have no access to that. Additionally, the buffer size already automatically grows the more you buffer.

**Comment by EhsanKia** [comment]
If you look at the stats, 70% of the delay is the encoder which is server side, only a small percentage of it is the buffer, so realistically, you'd go from like 15s to maybe 10s at best.
