### ISSUE TITLE
Lag/delay when typing in chat

### ISSUE THREAD

**Issue by kallebornemark** [night/BetterTTV#2075]
I'm getting a noticeable delay between pressing enter and seeing my message appear in chat. It seems like it mostly happens in channels with lots of users, but I'm not sure. Disabling the extension removes the lag.

**Comment by night** [comment]
The channel you're in probably has chat delay turned on. It is a known bug that we queue them to be printed instead of immediately printing them, but effectively nobody else sees what you posted until it shows for you too.
