### ISSUE TITLE
Scrolling on viewer list autoscrolls to bottom

### ISSUE THREAD

**Issue by fuelhauler** [night/BetterTTV#2076]
When scrolling past a certain point on viewer list, it auto scrolls to the bottom. Happens when scrolling with mouse or keyboard and when scrolling up from the bottom.

Tested and found not to be a problem with vanilla Twitch.

**Comment by kallebornemark** [comment]
Just to pitch in, the same thing happens when scrolling upwards.

**Comment by night** [comment]
You can downgrade to vanilla viewer list by disabling "Better Viewer List" in the settings.
