### ISSUE TITLE
More Personal Emotes For Subscribers??

### ISSUE THREAD

**Issue by StylezStreams** [night/BetterTTV#2080]
I feel that having more than just 5 "Personal Emote" spots should be available for people who are Subscribed to the BetterTTV service. Maybe have it equal to the amount of Emotes a channel can have (25 Total) or possibly less, just more than 5 would be a great idea for people who pay $5 a month for the Service, because more emote slots on your own personal channel is the only real benefit that people get for $5 a month, so incorporating more "Personal Emotes" would allow for more people to purchase the subscription, as well as more users could appeal to that benefit. Instead of only benefiting Streamers that use BetterTTV.

**Comment by ARSNoodles** [comment]
I 100% agree. I feel very limited with the personal emotes that are at my disposal. I am constantly switching them out so I can use one emote over the other. And as a strictly viewer and not a streamer, having 25 emotes to use in my channel does absolutely nothing for me. I don't see why the personal emote count is so low. No one is winning in this situation.

**Comment by casthekiller** [comment]
I 100% agree 25 personal emotes would be amazing or even 10

**Comment by night** [comment]
now you can get up to 25 personal emotes, 1 extra for every consecutive month of the subscription for the life of the subscription. you can check your limits at https://manage.betterttv.net/emotes

**Comment by ARSNoodles** [comment]
But I can only use 5 at a time still. Honestly what was the point of this?

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 23, 2018 at 9:01 PM, Zack<notifications@github.com> wrote:   
now you can get up to 25 personal emotes, 1 extra for every consecutive month of the subscription for the life of the subscription. you can check your limits at https://manage.betterttv.net/emotes

**Comment by night** [comment]
@ARSNoodles not sure what you mean
