### ISSUE TITLE
Enable the "You Follow" side panel to persist in twitch.tv/directory/following

### ISSUE THREAD

**Issue by jnnoack** [night/BetterTTV#2082]
When browsing your [following directory](https://www.twitch.tv/directory/following), it only shows the channels/hosts/games that are LIVE, with no list or side panel that lists all the channels you follow, including offline channels. Here's what the following directory currently looks like:  
  
![twitch - following directory no pane](https://cloud.githubusercontent.com/assets/25932367/23174468/1c2d3e02-f822-11e6-86cf-110a4a7378d6.png)  
  
However, if you browse the [general directory](https://www.twitch.tv/directory) or a [specific game's directory](https://www.twitch.tv/directory/game/Overwatch), you'll see a "You Follow" pane on the right side of the screen that lists every channel you follow, regardless of the broadcast status. Here's an example of the side panel:  
  
![twitch - you follow pane](https://cloud.githubusercontent.com/assets/25932367/23174604/8d93d5e2-f822-11e6-9b0d-6f54462b1fc3.png)  
  
Is there a way to make this side panel appear when browsing [twitch.tv/directory/following](https://www.twitch.tv/directory/following)?

**Comment by night** [comment]
This is not possible, sorry. The state is not in the context of that page.
