### ISSUE TITLE
Feature Request: Custom Timeout Setting

### ISSUE THREAD

**Issue by dangercrow** [night/BetterTTV#2084]
It'd be nice if you could set your timeout in the mod action icon (i.e. the ban/timeout buttons next to a message) to be a custom time.
I, for one, spend a lot of time purging, and a lot less time doing 10m timeouts. The ability to customise the timeout to a few seconds would be really useful.

**Comment by EhsanKia** [comment]
Those buttons are set by Twitch. You can enable and use the hotkeys for rapid purging (click their name and hit P on your keyboard). There's also a purge button in the modcard that opens. There's also another option that allows you to right click on their name and do a custom timeout very quickly.

**Comment by dangercrow** [comment]
![image](https://cloud.githubusercontent.com/assets/2048203/23261687/677a3c80-f9cf-11e6-95e4-1d398ec35657.png)

These buttons (above)? Not present in vanilla twitch (below)

![image](https://cloud.githubusercontent.com/assets/2048203/23261698/753f0a4e-f9cf-11e6-9695-43f3debab95f.png)

**Comment by dangercrow** [comment]
Also, looks like in takeover.js:84 onwards, we add the mod icons (settings.showModIcons and related)

**Comment by dangercrow** [comment]
I figure rather than asking someone else to implement it, I could actually just give this a go.
I'll make a pull request this weekend (or earlier, if I find time).

**Comment by xgerhard** [comment]
They are on vanilla: Cog wheel -> enable mod icons. In takeover they are shown if the setting is unknown.
