### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ronaldjeremy** [night/BetterTTV#209]
a button to the right of "viewer list", that lets you one-click "clear my chat"

**Comment by night** [comment]
Check the chat settings..

**Comment by ronaldjeremy** [comment]
I am talking about a ONE CLICK button.

Right now, it is a 3 click ordeal and a complete pain to do -- you have to click settings (which then brings up a dialog that mostly hides the chat so you miss entries just before you clear them), then click "clear my chat", then you have to click settings again to get the settings to go away.

Just a trash can, that appears to the right of the settings icon at the bottom, is what i would really like to see.  Similar to how if you turn on "Twitch Chat Emotes", a new icon appears at the bottom of the chat.  Like that, but a trash can that with one click the chat clears.
