### ISSUE TITLE
Time format wrong

### ISSUE THREAD

**Issue by Rulqu** [night/BetterTTV#2096]
I use Finnish locale but the Chrome and Chromium browsers are still showing 12hour time format. I know that this has been reported multiple times as a feature request (#1940,#1431,#1004) but if a locale that should show 24hour format doesn't work then something is wrong.

**Comment by night** [comment]
Selecting a timezone won't be possible in v7 due to how we're changing our extension, so this is not going to be possible moving forward, sorry.

**Comment by pkpn** [comment]
This means we can only have timestamps in 12h format from now on? Guess this addon has gotta be replaced. :(
