### ISSUE TITLE
Emotes Menu disappears...

### ISSUE THREAD

**Issue by samphai** [night/BetterTTV#2097]
Hi, i thought it might be interesting for you to know that whenever i clear my cache or history in CHROME browser the Emote Menu on Twitch disappears. I am not sure if this really is a bug but thought i let you guys know. 

![bttv-bug](https://cloud.githubusercontent.com/assets/8985583/23459627/cebe6ea0-feb3-11e6-880b-2a72a3551c44.png)

**Comment by xgerhard** [comment]
You should checkout this related post: #1731
