### ISSUE TITLE
Notifications with left side chat

### ISSUE THREAD

**Issue by temeZer** [night/BetterTTV#2102]
Notifications go beyond the browser window while using left side chat.

![1](https://cloud.githubusercontent.com/assets/25180740/23581333/812f0e42-011a-11e7-80ed-17c6fe0d3623.png)
![2](https://cloud.githubusercontent.com/assets/25180740/23581337/898b2300-011a-11e7-94b9-de2f322ff6e6.png)

**Comment by night** [comment]
👌

**Comment by EhsanKia** [comment]
Yeah, noticed that last night, will fix right away.
