### ISSUE TITLE
[Feature Request] Remove "Recommended" from Sidebar

### ISSUE THREAD

**Issue by alicelookingglass** [night/BetterTTV#2105]
Recommended friends, recommended channels... too much clutter!  I'd love it if we could switch them off! 😁

**Comment by AlcaDesign** [comment]
[Duplicate](https://github.com/night/BetterTTV/issues/1147)

**Comment by alicelookingglass** [comment]
I saw that one.  It only mentioned the friends (in fact, it says "remove only the recommended friends"), but I am asking for a complete removal of any recommendations.

Thanks for your attention.

**Comment by night** [comment]
We already remove recommended, but it does not always remove. This is already fixed in v7.
