### ISSUE TITLE
Feature Request: Replace box art/Custom Box art

### ISSUE THREAD

**Issue by Maverynthia** [night/BetterTTV#2107]
Since it takes a long time to never for the Twitch staff to update the box art for a game and the palce holder is pretty ugly.
Can there be a feature that a user can input their own box art for the site. Either linking to an Imgur or their own computer?

**Comment by night** [comment]
This is unfortunately something we do not want to maintain, sorry. We don't wish to maintain it for similar reasons they don't maintain their own box art. In other words, it's a lot of effort for little gain.

**Comment by Maverynthia** [comment]
Even if it's on a personal basis? Geez.
