### ISSUE TITLE
Suggestion: Visible uptime.

### ISSUE THREAD

**Issue by Sundheden** [night/BetterTTV#2110]
I know you can see the uptime by typing /uptime, but I would love to have it visible all the time. The uptime could be fetched on site load, and then change locally, or refresh at a set interval in case of interrupted/resumed stream. 

Mockup: 
![image](https://cloud.githubusercontent.com/assets/9757648/23672131/ee3e0740-036d-11e7-96b0-2ed26d019194.png)

**Comment by night** [comment]
I don't see the use case of why this is useful information to know at a glance.
