### ISSUE TITLE
Suggestion: A way to move chat below player in theatre mode.

### ISSUE THREAD

**Issue by Irvatar** [night/BetterTTV#2111]
If you use one screen and watch streams, you can set your browser with a stream to just half of your screen, but then your player is really small if you count chat on the side. http://i.imgur.com/ZLGUp1w.png 

I was making it work by using chat in popout and setting in under the stream on one side of the monitor like this http://i.imgur.com/isjtjQ5.png It was the best i could do when watching live. 

Unfortunately it doesnt work if you watch VODs, You cant popout chat replay with them. 
And so i thought, what if there should be an option to change the chat to bottom of the screen. It could look the way it is on mobile, player to the top and chat underneath. 

I would love that option, for right now if you change your browser size to really small in theatre mode the chat just dissapear, but it could just switch places from side to bottom and you get rid of big black bars problem on top and bottom of your player.

With this i have to say. I don't know if its possible or if this requires so much work its just not worth it. But if its doable I would be awesome to be included.

**Comment by night** [comment]
While this would be interesting, we are no longer making heavy UI mods to Twitch pages, sorry. They become brutal to maintain when Twitch constantly changes their codebase.
