### ISSUE TITLE
Emote Menu Doesn't Display all Emotes Anymore

### ISSUE THREAD

**Issue by Zylice** [night/BetterTTV#2113]
![untitled](https://cloud.githubusercontent.com/assets/26289132/23732985/7b245350-04ca-11e7-8e74-f01b16263121.jpg)

**Comment by night** [comment]
This is a bug due to race conditions in v6. It's already fixed in v7.

**Comment by Zylice** [comment]
Okay. Thanks for the response. Will v7 be released in the near future?
