### ISSUE TITLE
Disable autoplay

### ISSUE THREAD

**Issue by rhazor** [night/BetterTTV#2114]
There is a feature to disable autoplay for front-page, but can we have a disable autoplay for all channels when launching it?

Situation: E.g. I go to the channel just to load the chat and launch the video stream itself via livestreamer on my video player because I am on a slow 6 year machine, so to save sources. So each time I have to pause the stream.

Offtopic: Also I had Disable host ticked once, now after turning it off, whenever streamer hosts someone, the host stream does not load (this is on browser, not livestreamer).

I use both BTTV and FFZ on Firefox 52.0 x64 Win10

Cheers!

**Comment by night** [comment]
grouping this with #1996
