### ISSUE TITLE
Private messages in full screen mode

### ISSUE THREAD

**Issue by 7VIIlI** [night/BetterTTV#2117]
It would be amazing if we could chat with our friends, selected people, while watching in fullscreen mode.
I don't know how hard it would be to implement it.. still interesting. 
Thanks ! :)

**Comment by EhsanKia** [comment]
Try theater mode?

**Comment by 7VIIlI** [comment]
I was about to delete my post as I just realized it was possible. Havn't used twitch in a while ..
