### ISSUE TITLE
BetterTTV for iPhone/iPad Jailbreak

### ISSUE THREAD

**Issue by MrShadoe** [night/BetterTTV#212]
I would like to suggest a potential jailbreak source on cydia for twitch. I have no idea how to do it, its just an idea.

**Comment by cletusc** [comment]
I'd lean towards this is probably not gonna happen. BTTV is a browser-based addon for Twitch and can't be injected into the Twitch app on mobile.

**Comment by DTittel** [comment]
Not going to happen. For 1 thing trying to modify the existing App would probably be more work than writing a separate one. Second the team struggles to find time to maintain BTTV as it is, currently we would like to rebuild BTTV from scratch but don't have the time for that.
