### ISSUE TITLE
BetterTTV does not work in the <iframe>

### ISSUE THREAD

**Issue by CoolCmd** [night/BetterTTV#2120]
Hi, I am developer of the "Twitch 5" extension.
[Chrome](https://addons.mozilla.org/firefox/addon/twitch_5/)
[Firefox](https://chrome.google.com/webstore/detail/twitch-5/knankefoajngclnjgnelanfohgihifpc)

My extension loads Twitch.tv chat into `<iframe>`. Chat works fine, but BTTV does not work at all, although I see `<script src="https://cdn.betterttv.net/betterttv.js">` in the `<head>`.

The (bad) workaround is to delay `betterttv.js` injection, for example, for 1 second. So I think code inside the `betterttv.js` miss some sort of synchronization with the loading important Twitch.tv resources.

_________________

And another bug. BTTV, injecting `betterttv.js`, adds `Math.random()` to the URL. As a result, on most Twitch.tv pages file `betterttv.js` downloading **6** times. HTTPS and `cache-control` already prevent excessive caching, so `Math.random()` is superfluous.

**Comment by night** [comment]
BetterTTV loads in Chrome and Firefox extensions on page load. If you load our script before then, it will not have the necessary globals to load.

> As a result, on most Twitch.tv pages file betterttv.js downloading 6 times.

This is the result of Twitch using IFrame hacks to avoid CORS preflights. We are aware. It will eventually be addressed.

> HTTPS and cache-control already prevent excessive caching, so Math.random() is superfluous.

The `.random` exists to ensure there is no caching on our cdn's edges for the script. When we push out changes to fix problems, we like them to be instantly resolved.

**Comment by CoolCmd** [comment]
I know when to inject a script.

I followed the advice from issue #2112. The version 7 beta worked in the <iframe>. 

When is it planned to switch version 7 from the beta to release?

**Comment by EhsanKia** [comment]
We just entered beta this weekend. It entirely depends on how smoothly the beta goes, how many bugs there are and how stable the whole thing is. There's also a few features that are still missing so as you can imagine people will complain if we force the new version on them while it's not feature complete.
