### ISSUE TITLE
Unable to click any usernames in chat.

### ISSUE THREAD

**Issue by dadams4** [night/BetterTTV#2121]
Expected behavior when clicking usernames in chat:
![expected](https://cloud.githubusercontent.com/assets/17885483/23819831/00008b42-05da-11e7-8abe-571bfa2e4d59.png)

A popup appears with the option to follow, add as friend, or whisper the selected user.  The above is from Google Chrome Version 57.0.2987.98 and BTTV version 6.9.  BTTV is not enabled in the above screenshot.

In the screenshot below, the same version of Google Chrome is being used:
![unexpected](https://cloud.githubusercontent.com/assets/17885483/23819853/6888e92a-05da-11e7-8e54-cf94f6f398e2.png)
The red line below my username was not added by me, it appears when I click on any username in chat.  The popup that appears in the first picture when BTTV is not enabled does not appear when BTTV is enabled.

**Comment by night** [comment]
When you click on names with BetterTTV, we display our own moderator cards. We underline the user in chat to make their messages more visible. If you are unable to see the moderator card, perhaps you have some other extension installed preventing its proper execution. I cannot reproduce any issues on my machine, so it seems to be functioning normally.
