### ISSUE TITLE
Twitch Popout Whispers not showing

### ISSUE THREAD

**Issue by TockCustom** [night/BetterTTV#2124]
Hey folks,

Over the last week or so, I haven't been able to see incoming whispers showing up in my Popout Twitch Chat window while broadcasting. I wasn't sure if this was a BTTV issue or a Twitch Chat issue. I'd love for this to work like it used to ask its the best way for my mods to relay info to me while streaming.

They used to show up in chat with the appearance of: 
"Username > TockCustom - "Hey make sure you drink water"
And it would be highlighted like when someone tags you in chat.

Hope this makes sense. Thanks for any help guys!

Tock
http://www.twitch.tv/tockcustom
www.tockcustom.com

**Comment by CreepyCastleTV** [comment]
I have had the exact same issue for a week now. This happened in the past and was eventually fixed so I thought I'd wait 1 week but yeah I'm also guilty of not thinking to try the regular twitch pop-out chat. Did you try that Tock?

**Comment by night** [comment]
Twitch broke this, not us. Please report it to them.
