### ISSUE TITLE
Slow mode/Timeout problem

### ISSUE THREAD

**Issue by warzz** [night/BetterTTV#2127]
I subscribered a channel on twitch. Well.. not a problem yet but I can't write without timeout on the chat. There are not choices about my problem on the setting of BetterTTV. I realy want to use BetterTTV because this application so good but this has not mean to me. Can you help me?

**Comment by night** [comment]
I don't understand.

**Comment by warzz** [comment]
I mean, I was subscribered to the channel on twitch. Broadcaster apply slowmode for non-subscribers. For instance, 20 seconds. When I uninstall betterttv, I can write to chat without slowmode. But. If I install the betterttv, I can't this.
