### ISSUE TITLE
Randomly getting "Media not supported" Error, requires closing/killing tab

### ISSUE THREAD

**Issue by rsharp7879** [night/BetterTTV#2128]
This just started happening recently, I'm on Chrome Version 56.0.2924.87 (64-bit) on OS X. I haven't changed any settings recently. Saw others were having the issue as well: https://www.reddit.com/r/Twitch/comments/5an8ga/media_resource_not_supported_html5_player/

**Comment by night** [comment]
This is not a bug in BetterTTV, so we are not able to fix it.
