### ISSUE TITLE
Expanded Followers

### ISSUE THREAD

**Issue by Jeezeus** [night/BetterTTV#213]
I would like to see my followers list on the left hand side become expandable a la viewing subfolders in windows explorer. This would allow users to view all followers currently streaming without leaving the stream they are in or opening a new tab.

**Comment by DTittel** [comment]
Do you mean something like [Twitch Now](https://chrome.google.com/webstore/detail/twitch-now/nlmbdmpjmlijibeockamioakdpmhjnpk?hl=en)?
