### ISSUE TITLE
[Feature Request] Manually sort offline followed channels

### ISSUE THREAD

**Issue by DingoDjango** [night/BetterTTV#2133]
I use the followed channels list very often, and I also view VoDs semi regularly. In the current list you have online channels at the top, the playlist beta (which I would love to be able to remove), and offline channels.

As far as I know, the offline channels are sorted by follow time, so that the most recent follow is always at the top. I think it would be nice to have a sorting option for those, maybe have a button to click to "favourite" a channel and it will always by at the top of the offline list (or have its own section).

**Comment by night** [comment]
You must be in a Twitch experiment, since I do not see offline channels nor the playlist beta under the following page. We typically do not act on experiments until they are pushed out to everyone.

**Comment by DingoDjango** [comment]
Maybe I should clarify: not the following page, per se, the following list on the browsing page. The playlist feature is definitely a beta but I don't think the offline list is an experiment.

I'm talking about the sidebar in the https://www.twitch.tv/directory page.
Here is a screenshot to demonstrate: http://i.imgur.com/oT2toPd.png

The list of the channels under "OFFLINE" is what I am referring to, and it's ordered by most recently followed first.
