### ISSUE TITLE
Block feature

### ISSUE THREAD

**Issue by TheLimeGlass** [night/BetterTTV#2134]
If you ignore a username make it so their chat doesn't show up for you. Or add a /block command since there isn't one. I thought this was a feature because it's so commonly used on every chat system, but the ignore is only for whispers.

This would be an awesome feature that many would use.

Or make it like Discord where it automatically covers their chat like a deleted message.

**Comment by night** [comment]
This is already a thing.. type `/ignore username` to ignore someone

**Comment by night** [comment]
it actually does.
