### ISSUE TITLE
obstructing overlay on mouseover in theater mode

### ISSUE THREAD

**Issue by costia** [night/BetterTTV#2138]
http://i.imgur.com/WH6hyns.jpg
http://i.imgur.com/TUmugH6.jpg
There is a very distracting frame that appears when the mouse is over the video in theater mode.
In many cases it is right over the streamer's face.
Is there a way to disable it?

Edit:
Sorry. apparently not bttv. Strange. Doesnt appear in incognito mode.

**Comment by night** [comment]
it's not BetterTTV doing this. you prob have something else installed.
