### ISSUE TITLE
Settings Feature request: pop-out chat window containing ONLY chat messages

### ISSUE THREAD

**Issue by jlsjonas** [night/BetterTTV#214]
a great option would be to have a pop-out chat window containing only the chat, preferably with an overflow:hidden toggle.

Great plugin already though! :+1:

**Comment by night** [comment]
Can you explain what the use case of this would be?

**Comment by jlsjonas** [comment]
being able to resize the chatwindow if you're broadcasting it using chromakey (since you don't want the chat message input showing)
I use your obs chat too but still prefer the style of the BTTV dark theme + chroma key as overlay during (some of) my game(s)

**Comment by night** [comment]
OBS and XSplit both allow you to crop sources, so this isn't really necessary.

**Comment by jlsjonas** [comment]
it's not really necessary but it would be a nice feature (to be able to resize the window as you go, by just resizing the actual window.
up to you though :p
