### ISSUE TITLE
v7 beta issues

### ISSUE THREAD

**Issue by DragonQuiz** [night/BetterTTV#2141]
1. Can't take out/hide top cheer and recent broadcast
2. When someone gets t/o it the word isn't crossed out
3. Can't @ someone in chat 
4. When you get highlighted a box forms around your username http://i.imgur.com/4U1DnR4.png
4. BetterTTV emote badges aren't shown
5. ~When using the up arrow key previous messages aren't appearing~ Not a bug, the feature was removed
6. Mod stuff showing on channel mods, but not for anyone else (not a mod in witwix channel and won't work) http://i.imgur.com/vWOgy57.gifv

_Using latest chrome version: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36_
_FFZ is not enabled_

**Comment by EhsanKia** [comment]
1. I can work on bringing that feature to beta
2. not sure what you mean
3. What exact feature are you referring to. Is it tab completing  users by typing @ first? I can add that
4. I can fix that
5. Not sure what you mean by that one either
6. I'll add that one back too
7. I'll look into that one

**Comment by EhsanKia** [comment]
Fixed 3 and 4, gonna do 1 and 6 tomorrow.

**Comment by EhsanKia** [comment]
1. is half completed, there's now a /localunpin command
3. is fixed
4. is fixed
5. is fixed I think?
6. is coming soon
7. should be fixed
