### ISSUE TITLE
Some v7 beta issues

### ISSUE THREAD

**Issue by Priio** [night/BetterTTV#2145]
1. I can't mod or unmod users by using "/mod user" or "/unmod user" in chat. I type it in and nothing happens. Using .mod or .unmod works though.

2. I can't hit tab to complete emojis and twitch emotes, only works with BTTV emotes.

3. I found that if I tab to complete an emote, and that emote is at the end of my message, I need to hit enter twice for my message to send. Hitting enter the first time does nothing.

4. Can't tab to complete some BTTV emotes like (ditto) or (puke). Same goes with the "[...](https://manage.betterttv.net/emotes/553b27a61f145f087fc15c93)" shared emote. I assume its because they begin with a symbol. 

I'm on Mac using the latest version of chrome. No other extensions enabled.

**Comment by night** [comment]
all legit bugs, thanks

**Comment by EhsanKia** [comment]
Fixed 2, 3 and 4. Though not sure if I'll support tab completing "..."

**Comment by EhsanKia** [comment]
Everything here is fixed except emoji completion.
