### ISSUE TITLE
A few more v7 beta issues

### ISSUE THREAD

**Issue by Priio** [night/BetterTTV#2147]
1. The /part and /join commands return "Unrecognized command" when entered in chat. Not sure if those features were just simply removed, but they still show up in the /help response.

2. Clicking on the non-localized portion of a username in chat doesn't bring up the mod card. It'll only come up when you click on the localized part. 
For example, in the pic below, clicking on " ジョン" brings it up, but clicking on "(notprio)" won't.
   <img width="341" alt="screen shot 2017-03-20 at 2 25 56 am" src="https://cloud.githubusercontent.com/assets/24820100/24090229/9ee8cae4-0d14-11e7-817f-f424603cb7c5.png">

3. Also seen in that pic above, it looks as if the moderation buttons in the mod card (permit, timeout, ban) don't show up if the user has a localized name.
 
4. Pressing Follow or Unfollow on the mod card seems to do nothing.

5. This one is pretty minor but I noticed a little line that shows up between badges when you hover over them. It looks like it only happens when the user has more than one badge. The badge on the far right never seems to have the issue, just all the badges that precede it.
    <img width="182" alt="screen shot 2017-03-20 at 2 33 08 am copy" src="https://cloud.githubusercontent.com/assets/24820100/24090419/61d692ce-0d16-11e7-9fa4-d62f9929e711.png">

6. Not sure how much of an "issue" this one is, but when banning a user through chat and tab completing their name, the first time you hit enter it changes the initial auto-completed name into the display name version instead of just sending the ban command. Same when using the default timeout command and not adding a time length. You have to hit enter twice in order to ban a user when u tab complete their name. The conversion to display name is nice during normal chatting, but its inconvenient when performing mod actions.
The example below shows a localized name in the test, but the same thing happens with any other user.
<a href="https://gyazo.com/8e6a7a68c4a0304be61d4cfccb5dcb73"><img src="https://i.gyazo.com/8e6a7a68c4a0304be61d4cfccb5dcb73.gif" alt="https://gyazo.com/8e6a7a68c4a0304be61d4cfccb5dcb73" width="336"/></a>

**Comment by night** [comment]
> The /part and /join commands return "Unrecognized command" when entered in chat. Not sure if those features were just simply removed, but they still show up in the /help response.

This will be fixed in the next release.

> Clicking on the non-localized portion of a username in chat doesn't bring up the mod card. It'll only come up when you click on the localized part.

This is already fixed.

> Also seen in that pic above, it looks as if the moderation buttons in the mod card (permit, timeout, ban) don't show up if the user has a localized name.

Different bug, will be fixed in next release.

> Pressing Follow or Unfollow on the mod card seems to do nothing.

It seems Twitch's API rejects out request.

> This one is pretty minor but I noticed a little line that shows up between badges when you hover over them. It looks like it only happens when the user has more than one badge. The badge on the far right never seems to have the issue, just all the badges that precede it.

Cool CSS bug.

> Not sure how much of an "issue" this one is, but when banning a user through chat and tab completing their name, the first time you hit enter it changes the initial auto-completed name into the display name version instead of just sending the ban command. Same when using the default timeout command and not adding a time length. You have to hit enter twice in order to ban a user when u tab complete their name. The conversion to display name is nice during normal chatting, but its inconvenient when performing mod actions.
>The example below shows a localized name in the test, but the same thing happens with any other user.

Pressing enter twice is a bug we're aware of.
