### ISSUE TITLE
Anonymous chat

### ISSUE THREAD

**Issue by PSportz** [night/BetterTTV#2149]
Hi, my options for anon chat has disappeared. Tried reinstall the extension but it's still not there. Hope that feature isn't gone?

**Comment by PSportz** [comment]
![skarmklipp 2017-03-20 10 46 00](https://cloud.githubusercontent.com/assets/11179731/24094838/a7235148-0d5a-11e7-8499-cc7b7ce356fb.png)

**Comment by night** [comment]
You are on the beta. The beta does not have Anonymous chat. If we get enough feedback that people still want it we will reimplement it.

If you need it, you can clear your cookies to revert to the non-beta.

**Comment by PSportz** [comment]
Thank you! Yes i hope people still want it to be there. I use it very regularly, it's nice to have while browsing smaller channels and you don't want to feel rude for joining and not say anything ;) 
The "activate beta" button haven't been at top for long has it? Cause Anon chat always was on top so i figure lot's of people mistakenly activated beta lately then? 

Anyway thanks again
