### ISSUE TITLE
host button not showing up

### ISSUE THREAD

**Issue by D3XxXx** [night/BetterTTV#2150]
Hello,
When opening a channel in a new tab (from either twitch.tv or twitch.tv/directory) or entering the full address to a channel, the Host button does not show up (unless you go into setting, disable and re-enable host button in BTTV settings)
If opening the channel in the same tab (twitch.tv or twitch.tv/directory) the host button shows up.

**Comment by EhsanKia** [comment]
This is fixed in the next version of BTTV.
