### ISSUE TITLE
Video preview

### ISSUE THREAD

**Issue by DirtyMcGirt** [night/BetterTTV#2151]
When a video is clipped, in BTTV, you don't get a video preview, example.. http://puu.sh/uRGgN/e01574f0c8.png

However, in standard Twitch chat, you get this nice video preview, example http://puu.sh/uRGo8/4a7dc65ab5.jpg

I think it would be great to have this feature on BTTV.

Thanks

**Comment by EhsanKia** [comment]
This is fixed in the next version of BTTV.
