### ISSUE TITLE
v7 Beta issue: CTRL & Chat

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2155]
Pressing CTRL with the mouse over the chat will add `50px` to the `padding-bottom` on `div.chat-lines`'s inline style. The chat also automatically scrolls to the bottom making copy and pasting difficult. Sometimes "More messages below." will appear even though the chat is actually moving upwards.

**Comment by night** [comment]
This is not a bug. This is to pause chat.

**Comment by AlcaDesign** [comment]
Well it definitely doesn't pause the chat.
