### ISSUE TITLE
Cannot use @ to tag and links are deleted automatically

### ISSUE THREAD

**Issue by MissZenith** [night/BetterTTV#2156]
I just upgraded my pc with an SSD and upon downloading Chrome and BTTV, I opted into beta BTTV. Ever since then I cannot use @ to tag someone in chat and it automatically deleted my links in channels I am whitelisted in, on my end only. Others can see them fine. Am I missing something stupidly obvious?

**Comment by EhsanKia** [comment]
@ completion popup is not yet completed (you can still tab complete their name, there's just no popup. So I can go @Mis and press tab to complete the rest.

The link deletion, not sure what you mean, can't replicate.

Note that this is a beta and features missing/not working is expected.
