### ISSUE TITLE
BTTV settings bug report

### ISSUE THREAD

**Issue by GamerGramma** [night/BetterTTV#2161]
Just a heads up. I don't know if there are others that have come across this problem or not, but every time I go on Twitch to watch a stream, I notice that I have to reset my BTTV setting of the "Hide Prime Promotions", it's starting to get annoying. Can anything be done about it? Is there something I can do to fix it? 
Thanks for your time :)
GamerGramma

**Comment by EhsanKia** [comment]
Do all your settings reset or just that one?

**Comment by night** [comment]
it's just not being loaded when loading the channel page properly.. so it's a race in v6.. it's fixed in v7 (our current beta).
