### ISSUE TITLE
Host button missing

### ISSUE THREAD

**Issue by Xemnote** [night/BetterTTV#2164]
My host button has been disappearing for a few days now. I go into my settings and it does say it is on so I will turn it off and on and it will re-appear but if I refresh or change streams then it will vanish again while still saying it is on in my settings.
![image](https://cloud.githubusercontent.com/assets/26581967/24168640/ce1343f8-0e72-11e7-8039-d730f03fa398.png)

**Comment by night** [comment]
If you don't mind being a guinea pig, this is fixed in our beta version (you can enable it in the same settings screen). It's missing some features, and may have other bugs, but we have better integration for bug tracking to help us fix things faster in the beta.
