### ISSUE TITLE
Feature Request : Smooth scrolling chat

### ISSUE THREAD

**Issue by PadawanBraid** [night/BetterTTV#2168]
Sometimes chat can fly by fast and it's hard to keep up. A smooth scrolling chat would make user's text boxes easier to keep track of.

**Comment by EhsanKia** [comment]
Do you mean user scrolling, or auto scrolling?

For the former, that's browser specific.
For the latter, I'm fairly sure it would have the adverse effect. Your eyes can read text much better if it moves in jumps than when it's scrolling, especially if you don't have a 144hz monitor.

**Comment by PadawanBraid** [comment]
I'm reffering to twitch chat during streams. And I disagree, I think it's easier to follow the Star Wars slow scroll versus lines of text constantly jumping up.

**Comment by EhsanKia** [comment]
Because that's an insanely slow scroll.

Try reading this: https://www.testufo.com/#test=framerates-text

**Comment by PadawanBraid** [comment]
Your example is an insanely fast scroll. Wouldn't it be possible to meet in the middle?

**Comment by night** [comment]
we do not control the scrolling in v7 onwards, so this is not possible anyways.
