### ISSUE TITLE
Can't downgrade back from beta to v6

### ISSUE THREAD

**Issue by rhazor** [night/BetterTTV#2178]
Uninstalled/Installed/Reinstalled, cleared caches, etc. Installing from .xpi file the installed version is 7.0.0beta in BTTV settings tab:
![ysqlfvp](https://cloud.githubusercontent.com/assets/22996586/24266352/1e2793f6-100f-11e7-9aed-9ee866784361.png)

But in addons page it says its 6.8.5"
![2](https://cloud.githubusercontent.com/assets/22996586/24266513/acd513d0-100f-11e7-8767-57962291c428.png)

But its 7.0 really, because its missing half the features the 6.8.5 has. E.g. this is how it looks now:
![3](https://cloud.githubusercontent.com/assets/22996586/24266428/62ed94ae-100f-11e7-8c27-c61deec6f72e.png)

I tried installing right from https://www.nightdev.com/betterttv/ or downloading the .xpi file for Firefox and installing manually. I also installed the .xpi on Web Developers Edition of Firefox and it installed the correct version and reports 6.8.5 in both addons tab and BTTV settings.

**Comment by night** [comment]
clear your cookies.

**Comment by rhazor** [comment]
OK I cleared twitch.tv and nightdev.com cookies, and reinstalled again. Didn't change.

**Comment by night** [comment]
You cannot delete individual cookies, you have to clear them all. we store settings in local storage

**Comment by rhazor** [comment]
This will break all my logins in other 100 websites that are unrelated in any way to bttv.

**Comment by EhsanKia** [comment]
You need to clear local storage as well as cookies. You don't have to do it for every site.

Go to Twitch, ctrl+shift+i to open the console, and go to the Applications tab, Then select Clear Storage and if you want you can unselect everything but local storage.

**Comment by rhazor** [comment]
solved.
