### ISSUE TITLE
Colon-emojis are not formatted before sending (Beta)

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2181]
I see the emoji as it should appear, but the :colon:'d version is sent instead so others with regular BTTV or no BTTV will not see the emoji. I don't know about others with the beta.

Also some emoji that are sent as actual emoji and not :colon:'d do not get exchanged for the image on my side:
![image](https://cloud.githubusercontent.com/assets/7132646/24282901/4fef8ed6-1030-11e7-844f-4d8db188d325.png)

It appears to be that if they're next to each other, they're not changed. "`👀👀`" vs "`👀 👀`"

**Comment by EhsanKia** [comment]
Coming soon ™️
