### ISSUE TITLE
Balloons do not allow click-through (Beta)

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2182]
![](http://i.imgur.com/5SOZ5Jr.png)

Unlike before, hover over a balloon will not allow it to go away and you cannot click through it.

**Comment by EhsanKia** [comment]
Move your mouse away?

**Comment by AlcaDesign** [comment]
Sure, that fixes it, but this is an easy problem to fix. Does anyone need to be able to select the text of the balloon? Probably not. The balloon background is also exactly the same as the other background unlike before.

**Comment by night** [comment]
This is how Twitch does its titles natively.. it's not performant for us to add event listeners to them to change this behavior.

**Comment by AlcaDesign** [comment]
All you need is to add this to `.balloon`:
```css
pointer-events: none;
```

**Comment by night** [comment]
in any case, one could also argue the opposite case, they want to select them.. Unless you have an argument for why you should be able to click through I don't see us fixing this nonissue

**Comment by EhsanKia** [comment]
If it's a simple CSS fix, why don't you PR it? I do agree with the styling, I definitely liked better how it looked before, if you can replicate that look that would be nice. The way it blends with the background now is kinda annoying.
