### ISSUE TITLE
setting for chat preloading

### ISSUE THREAD

**Issue by MaxKruse** [night/BetterTTV#2183]
due to BTTV (i assume the chat preloading) my chat window sometimes looks like [this](http://lithibae.s-ul.eu/iEs0CW1r).

since chat preloading (the part before "Welcome to Streamer's chat!") doesnt even show my own messages and in generell not being that usefull, an option for this seems reasonable.

**Comment by night** [comment]
This is fixed in the beta, which you can enable in the BetterTTV settings..
