### ISSUE TITLE
Can't use the enter key.

### ISSUE THREAD

**Issue by bobotje** [night/BetterTTV#2184]
Hi

I use latest BetterTTV (v7) and now I'm not able to use the enter key in chat.

Sincerely
PieterVMB (Twitch)
bobotje (Github)

**Comment by night** [comment]
BetterTTV v7 rewrites the entire extension to rely on default Twitch chat. It does not support new lines, and this is how it works on default Twitch.

**Comment by bobotje** [comment]
Maybe I didn't make a clear explanation. It's not for making a new line (that's shift+enter) but sending the message.
