### ISSUE TITLE
Twitch chat display bug

### ISSUE THREAD

**Issue by notryn** [night/BetterTTV#2186]
Using waterfox 52.0.1 (64-bit), BetterTTV v6.8R55.

When selecting a channel, the channel will load properly but chat will not display properly.  The top of the chat channel will display the highest donation of bits, though without the message (unless the down arrow is clicked to display more).  User timeouts and subscriptions still show, but not any actual user chat.  Attempting to pop out the chat will sometimes redirect to https://www.twitch.tv/undefined/chat?popout= rather than the correct channel name.  The undefined channel is actually populated with users (mostly spam bots) but is not the chat channel desired.  The correct chat can be reached by opening a separate window and pointing it to https://www.twitch.tv/<channelname>/chat?popout= .  Sometimes popping out chat will actually lead to the right channel, but not always.  

I can fix the issue by disabling BTTV, reloading, then re-enabling and reloading again.

**Comment by EhsanKia** [comment]
This is fixed in the nxet version of BTTV (V7) which is currently in beta. It's a full rewrite of the extension which will be going live soon and hopefully addresses all these chat issues.
