### ISSUE TITLE
BetterTTV bug

### ISSUE THREAD

**Issue by TheSurvivalist68** [night/BetterTTV#2187]
When I turn on dark mode for Twitch it only turns dark mode on for chat, it used to make all of Twitch dark mode. I don't know how to fix it and I don't know how to turn it on if it is in another place. If you have anything that will help, please tell me so I can get this figured out.

**Comment by EhsanKia** [comment]
That's default Twitch behavior, which BTTV is probably not running?

Make sure it's properly installed in Chrome and enabled.

**Comment by TheSurvivalist68** [comment]
Turns out due to a recent update it was disabled on Twitch or something, thanks for the help, I checked and tried to reinstall and that came up, so it's working now.
