### ISSUE TITLE
[Feature Request] Keyboard shortcuts J and L for skipping backward and forward in VOD

### ISSUE THREAD

**Issue by ryankhart** [night/BetterTTV#2191]
I noticed that you already have the YouTube style keyboard shortcuts (i.e. K to play/pause) as an option, but J and L still do not skip backward and forward in the Twitch VODs. I understand why, because there are no clickable elements on the page to skip backward or forward, only a scrub bar. However, I believe it would be possible to make it work by setting J and L to both bring the video player into focus and then simulating a keyboard press of the left or right arrow respectively.

**Comment by ryankhart** [comment]
Here is some untested Javascript code that I think might work. However, I'm inexperienced with making Chrome extensions so I don't know how to test it yet.

document.documentElement.focus();
document.getElementById("test").onclick = clicked;

function fireKey(el) {
    var key;
    switch (el.id) {
        case "left":
        key = 37;
        break;
        case "right":
        key = 39;
        break;    
    }

    if (document.createEventObject) {
        var eventObj = document.createEventObject();
        eventObj.keyCode = key;
        el.fireEvent("onkeydown", eventObj);
    } else if (document.createEvent) {
        var eventObj = document.createEvent("Events");
        eventObj.initEvent("keydown", true, true);
        eventObj.which = key;
        el.dispatchEvent(eventObj);
    }
}`

var keyCodes = require('../keycodes');

module.exports = function() {
    function handleKeyEvent(keyup) {
        if (keyup.ctrlKey || keyup.metaKey || keyup.shiftKey) return;
        if (!$('input, textarea, select').is(':focus')) {
            if (keyup.keyCode === keyCodes.k) {
                $('#player').find('.js-control-playpause-button').click();
            } else if (keyup.keyCode === keyCodes.f) {
                $('#player').find('.js-control-fullscreen').click();
            } else if (keyup.keyCode === keyCodes.m) {
                $('#player').find('.js-control-volume').click();
            } else if (keyup.keyCode === keyCodes.j) {
                $('#player').find('.js-control-fullscreen-overlay').click();
                fireKey("left");
            } else if (keyup.keyCode === keyCodes.l) {
                $('#player').find('.js-control-fullscreen-overlay').click();
                fireKey("right");
            }
        }
    }

    if (bttv.settings.get('playerKeyboardShortcuts') === true) {
        $(document).on('keyup.playerControls', handleKeyEvent);
    } else if (bttv.settings.get('playerKeyboardShortcuts') === false) {
        $(document).off('keyup.playerControls');
    }
};

**Comment by night** [comment]
You can use the arrow keys to perform the same action. Unfortunately due to how the events work, it's isolated from the events you're firing in the example.
