### ISSUE TITLE
Host/Unhost button

### ISSUE THREAD

**Issue by sinnx3** [night/BetterTTV#2194]
[V6.8] Host/Unhost button does not retain visibility (despite being toggled on) if say the user refreshes the page (only can confirm in Google Chrome). 

So say a user toggles it on it's visible, but then has to refresh/reload the page unlike the rest of BTTV settings it doesn't load (remain visible) and the user has to go into BTTV settings and toggle it off then back on again for it to show up again.

**Comment by DreamSpawn** [comment]
I have the same issue, only some times the button shows up on its own. I haven't yet discovered the pattern to this though.

**Comment by EhsanKia** [comment]
#2167
#2164
#2150
