### ISSUE TITLE
BETA BUILD: @ tab completions

### ISSUE THREAD

**Issue by jnnoack** [night/BetterTTV#2195]
Every time I try to tab complete emotes that begin and end with ":" (such as ":thinking:"), the "@" tab completion tool tip does not pop up, nor can you cycle through the names without the tool tip. Once it does this, I have to refresh the page a few times. Not sure what else is causing it.

**Comment by EhsanKia** [comment]
Tooltip has not been implemented for emojis/emotes yet in the beta. The beta clearly states that certain features may be missing.
