### ISSUE TITLE
BetterTTV settings disapear

### ISSUE THREAD

**Issue by Neisitun** [night/BetterTTV#2197]
The BetterTTV settings disapear after hiding and unhiding the chat.

**Comment by night** [comment]
Are you on the beta version? If not, this is fixed on that. You can enable it in the BetterTTV settings.

**Comment by Neisitun** [comment]
well I just tried again, and the settings again disapear. Where should I
"enable it" ? Dont see where is the option.

**Comment by EhsanKia** [comment]
If it disappeared, that mean it's turned on. If you see version 7.0.0, you're on the beta.

**Comment by Neisitun** [comment]
BetterTTV v6.8R55

**Comment by Neisitun** [comment]
Normal
https://gyazo.com/62c7b3edf68ec1910dbbc415b9a812e3

Hided chat
https://gyazo.com/6a3820ad7f7dbf5330f296847c79e170

Chat back but settings are gone
https://gyazo.com/80fe7cf703fa2bd77d37ae64d933c1ba

**Comment by Neisitun** [comment]
(Have to reload the page to get settings options back)

**Comment by EhsanKia** [comment]
If you're on "BetterTTV v6.8R55" then you did not switch to the beta. The beta is 7.0.0.

**Comment by Neisitun** [comment]
I guess i'm misunderstanding. Should I change and go to 7.0 to do not have
this "bug" ?

**Comment by Neisitun** [comment]
On my google settings it's written 7.1
