### ISSUE TITLE
No way to disable up/down self-sent history in Chat

### ISSUE THREAD

**Issue by alystair** [night/BetterTTV#2200]
It get's really annoying when you're typing a multi-line text and press up from memory only for it to load your previously sent chat message. There should be an option to disable this feature as it's no good for low volume rooms and spam can just be done by copy/paste

**Comment by EhsanKia** [comment]
There's plan for fixing that in the future version of BTTV which is currently in beta.

**Comment by alystair** [comment]
Hope it's in the next release, thanks!

**Comment by AlcaDesign** [comment]
If you just press the down arrow, it'll revert back to your typed in message.

**Comment by alystair** [comment]
@AlcaDesign - yeah that's lovely but it breaks UX when you're accustomed to navigating a multi line piece of text.

**Comment by EhsanKia** [comment]
Yeah definitely agree with you. The proper way (which I'm implementing) is that it only goes to previous if your cursor is at the very start of the sentence message box.
