### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by wazzaa91** [night/BetterTTV#2201]
Hello, just started using this, it is awesome. What about putting option to hide "posts" and go straight to "info" tab on channels or vice versa ? Something like this Option 1 Hide "Posts" ; Option 2 Hide "Info"?

**Comment by night** [comment]
It's not something we can really do. Twitch is pushing social media (it wants to be Twitter/Facebook), and the site is probably going to be getting more of these feeds which replace other things.
