### ISSUE TITLE
Emote limit

### ISSUE THREAD

**Issue by TheDowntimeProject** [night/BetterTTV#2202]
I have added a few emotes which i have almost instantly removed as they were not up to scratch. however my 20 weekly limit has been filled and cant submit more even tho in total i have 8...

**Comment by EhsanKia** [comment]
We get huge submission queues that we have to go through every day, so we need to throttle the submission rate to stop it from getting out of control. You'll have to wait a week, and in the future, please make sure your submissions follow all the rules before submitting it to avoid having to resubmit over and over.
