### ISSUE TITLE
[v7, Chrome] Hide Group Chat display issue

### ISSUE THREAD

**Issue by Px05119** [night/BetterTTV#2206]
After enabling "Hide group chat" on the v7 Beta, chat will start loading incorrectly when initially visiting a channel. Reloading the page will help, but is only a temporary fix, as the issue will appear at random later on, normally after a system reboot. A screencap of how chat loads is at https://gyazo.com/6b8b0462a8c2e078c6c7f74a1ee90f41

**Comment by EhsanKia** [comment]
Hmm, started experiencing that too today.
