### ISSUE TITLE
twitch chat jumping up and down

### ISSUE THREAD

**Issue by ziichu** [night/BetterTTV#2207]
hi there 

my twitch chat keeps jumping up and down continuously , and i have to refresh or clear chat or disable betterTTV to fix it and it keeps happening, 

XPS 15 (9560)  
chrome Version 57.0.2987.133 (64-bit)
BetterTTV 7.1
 video for a better explanation > https://www.dropbox.com/s/gmnor3alzkl61xo/112.avi?dl=0

thank you

**Comment by ziichu** [comment]
the chat is totally fine when i disable betterTTV

**Comment by notheowner** [comment]
I can confirm this

**Comment by night** [comment]
Use the BetterTTV Beta.. enable it in the settings.

**Comment by ziichu** [comment]
will try it , thank you

**Comment by ziichu** [comment]
enabled beta mode fixed it for a while ... but its back again , only on windows , my Mac is fine
