### ISSUE TITLE
[Feature Request] [v7] Previous Message Repeat & deleted messages

### ISSUE THREAD

**Issue by notheowner** [night/BetterTTV#2209]
1. In v6 you could press the UP arrow and it would fill the exact previous message.
2. Also when a message was deleted you could click on it, to see what was in it.

Should we expect these features to be back in V7, they were really nice!

**Comment by EhsanKia** [comment]
1. is coming
2. #2177

**Comment by notheowner** [comment]
My bad for not checking the second one.
