### ISSUE TITLE
Version 7.0.0 Chrome Issues

### ISSUE THREAD

**Issue by SoWhoYou** [night/BetterTTV#2211]
Things I've noticed that were working, but are now not working in the latest update/updates...

1) Hover over links to get info about the links, no longer works.
2) Chat Log Size, Used to be able to change the scroll back length but now you cant.

Those are the only 2 things I can think of right now, but yeah they were very useful and no longer work :(

**Comment by EhsanKia** [comment]
Just to be clear, it's not that "they're not working", 7.0 is a complete rewrite from the ground up so not all features have been ported yet, hence why it's still a beta.

Can't give you a timeline for 1, but 2 most likely won't happen. The new extension modifies Twitch's chat instead of rebuilding it from scratch (which was a huge pain to maintain), so we don't have access to scrollback anymore.

**Comment by SoWhoYou** [comment]
Is there a way I can downgrade to an older version?

You say you don't have access to scrollback anymore... what exactly does that mean? I thought that part was all client side, I don't see how that could possibly be sever (twitch) side, because I make twitch bots and I've never once seen anything in the twitch api that has anything to do with that.

IDK maybe I will start digging into the source for this one day and see if I can start tweaking and/or adding and/or updating things. Thanks for the fast reply by the way, I'm actually impressed with that to be honest.

**Comment by EhsanKia** [comment]
You need to clear your cookies/localstorage.

Before, we would remake the whole chat ourselves, and that means we can store as many messages as we want. Now, we modify the messages that are already there, and that's controlled by Twitch's client side code. Yes, it's on the client, but it's hidden behind Twitch's code we is very messy to modify without re-implenting completely.

Feel free to dig through Twitch's code and see if you can find a way to increase how many messages they store.

**Comment by SoWhoYou** [comment]
Thanks for the Downgrade info, this should hold me over for a while, just a quick question though...
Now that I'm back on v6.8R55 is the plugin going to try to update to v7+ automatically or will it stay at v6.8R55? I honestly don't even know how I got v7+ installed in the first place.

**Comment by EhsanKia** [comment]
The only way to get v7 is to turn it on in the options afaik (at the very bottom of the settings list in v6.8)

**Comment by SoWhoYou** [comment]
Well I guess I must have turned that on one day and didn't realize it.
Thanks for all the help though! Keep up the good work!
