### ISSUE TITLE
Custom @name

### ISSUE THREAD

**Issue by homezonebenny** [night/BetterTTV#2213]
Hi,
when someone write your stream channel name into the chat, it get marked "red" for example so that you as a streamer can see this.
Like if the stream channel is www.twitch.tv/ABC
and someone writes:
"Hi @ABC" or just "Hi ABC" it get marked.

Now it would be cool to add custom names the chat mark feature reacts too.
Like the streamers name. If the streamers channel is "ABC" and the name of the streamer is "Robinson" people can type:
"Hi @Robinson" or "Hi Robinson" and it's marked too.

This could be a text field in the betterTTV settings, where you can enter names listening to seperated with comma:
Robinson, Robin, Roberinio
something like that.

Hope the feature request is understandable :)

**Comment by Nareese** [comment]
This feature already exists:   Set Highlight Keywords, accessible from the gear menu button in on chat.   If the list is blank, it defaults to just the current user's name, so if you put other things in there, put the user's name as well.  The list is just space separated, not comma.  From your example, enter

`ABC Robinson`

for the highlight keywords.  Read the instructions on the dialog for more details.

**Comment by homezonebenny** [comment]
Interesstingly I did that and it don't work. Maybe because I use a - in my name.
For example:
Robin-son
If the Twitch Name is twitch.tv/Robinson
and you change it in the settings to: Robin-Son
it somehow don't work correct. And it's buggy somehow.

When I edit the list like:
robinson ABC bla blub
into:
robin-son ABC bla blub

It reset my name from Robin-Son (like in twitch settings configurated) to "robinson".
Doesn't matter how often you change it back to: Robin-Son
it still stays on "robinson" without - in it.

Only solution was to remove all the settings out of the browser with:
CTRL SHIFT DEL
Delete cookies / website / plugin datas

And then let it on default:
robinson

When you set something into the list:
robinson ABC

it instantly change your twitch chat name from
Robin-Son
to
robinson

So somehow this is bugged.
When it shows "robinson" instead of "Robin-Son" it's still "Robin-Son" in another browser when loged in.
So it's not changing the twitch settings. It's just changing the chat name when you are using betterTTV Addon.

So for me, the list is not working, and much worse, it destroy the showed name?!
