### ISSUE TITLE
Scrolling up to pause chat not working

### ISSUE THREAD

**Issue by vpr555** [night/BetterTTV#2221]
Scrolling up just forces chat to the bottom, it used to pause with two clicks of the mouse wheel. 

Using Chrome 58.0.3029.41 beta (64-bit) with BTTV v6.8R55.

No settings were changed (by myself) in BTTV, it just stopped working on its own.

**Comment by EhsanKia** [comment]
Can you check what the behavior is on vanilla Twitch? I'm fairly sure this is something they broke. You have to click on the chat after scrolling up for it to properly pause. I'm not sure if this is something we can fix but we can look.

**Comment by vpr555** [comment]
@EhsanKia Loaded Twitch in an incognito tab, logged in (man vanilla Twitch is so ugly), and the way you described it is how it is behaving. Seems like an odd design choice on their part. 

I hope it can be fixed, it was so convenient and I used it for so long that it became second nature.

**Comment by night** [comment]
Use the hotkey ctrl when hovering chat to pause it.
