### ISSUE TITLE
[Feature Request] Set Blacklist Keywords/Hide Bits for Chat Replay

### ISSUE THREAD

**Issue by Voye** [night/BetterTTV#2223]
To make twitch chat more bearable I use these features a lot for online streamers, but I stray away from watching vods because there's so much stupidity said in certain messages. 
I've been looking around for something like this for a while, and if you could make it happen it would make my year

**Comment by EhsanKia** [comment]
Blacklist works in Replay in the new BTTV which is currently in beta (V7).
