### ISSUE TITLE
[v7] Hide bits does not hide badge and cheer amount.

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#2224]
The Hide Bits feature is hiding the cheer image, but not the amount (.js-bits-emote-amount) in messages. Also, less important, and probably harder to fix, it is not hiding the user's cheer badge.

**Comment by EhsanKia** [comment]
I believe leaving the amount was on purpose. The annoying part from it is the image, the text is simply a number and is acceptable. The badge showing seems like a bug that should be pretty easy to fix.

**Comment by Nareese** [comment]
IMO, having just a bunch of random numbers there without context (because the image that identifies them as cheers is gone) just looks extra spammy, especially when people do large numbers of smaller cheers to make up a large amount in order to spam on-screen tip jars.  You end up just seeing something like "100 100 100 100 100 100 100 100 100 100".  Conversely, I guess if the message consists of nothing but cheers, if you hide both the image and the text amount, you're left with just a blank message, which is also problematic.  

¯\_(ツ)_/¯

I just report em.  Your guys call.

**Comment by EhsanKia** [comment]
Might be able to use the tags data to collapse the whole spam into a single one, that would reduce spam greatly.

**Comment by Nareese** [comment]
updating:  badge issue resolved by PR #2270

**Comment by night** [comment]
we needed to leave some indication in chat that there are bits, so we're deciding to just hide the images and leave the amount for now.

badges are fixed, so this is resolved.
