### ISSUE TITLE
Whisper Chat - Switch sides

### ISSUE THREAD

**Issue by homezonebenny** [night/BetterTTV#2226]
Would be nice to have an option to change the sides of the /w chat.
That means from right to the left side.
Sometimes a streamer use the cam or something important on the right side.
Or a game GUI have something important on the right side.
So it would be nice to move the whole whisper thing to the left side.
This means the little button (which contains all the whispered persons list) and the open whispers.

It would be good if this would be accessable directly from the whisper menu / whisper chat.
Like an arrow left / right. Because it's a bit bad if you have to open the settings, and search the point to set it to on/off.

So you can basically switch it left / right PER stream.

**Comment by night** [comment]
We have an option to hide it when you have no whispers open, but there's no way to move it entirely.
