### ISSUE TITLE
Emote menu

### ISSUE THREAD

**Issue by jonydikov** [night/BetterTTV#2229]
"Emote Menu — Get a more advanced emote menu for Twitch. (Made by Ryan Chatham)" is on, but it dissapeared today. What should I do?

**Comment by EhsanKia** [comment]
We pushed an update that temporarily disables is as it was breaking twitch for many (Seems like some Twitch update broke something). That being said, it seems to work fine on V7 beta, which we will be migrating to very soon, so you can always turn on the beta.

**Comment by jonydikov** [comment]
Thanks for so quick answer. Just waiting for turning menu on.

Best regards
