### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TripingPC** [night/BetterTTV#223]
Hi Night!

So, I was thinking about this the other day, but there should be an option in BTTV to automatically add the @ before a username when using auto-completion.

Thanks for considreing it!

**Comment by night** [comment]
Have you tried placing a '@' before tab completing?

**Comment by TripingPC** [comment]
I have and it works. But itd be nice for BTTV to add the @ by itself when
usîng tab completion.

**Comment by voloshink** [comment]
The point is to let people tab complete without adding a @ in front when they don't want it. Typing @ before you press tab isn't that big of a price to pay.

**Comment by TripingPC** [comment]
I perfectly understand that, but certain people might prefer having it auto
added as goes for the fact that some people prefer to turn on DarkenTTV and
others not.

2015-02-28 0:28 GMT-05:00 Kirill Voloshin <notifications@github.com>:

**Comment by voloshink** [comment]
We have to weigh issue likes this vs are there enough to people to actually warrant the space in the setting, is it worth the time it would take to implement it. Something like this could be added once the settings code gets refactored.

**Comment by vendethiel** [comment]
If we were to add the "@" at all time (which is not required by either twitch or bttv, AFAIR), this'd prevent people from autocompleting names in commands.
