### ISSUE TITLE
Can't chat

### ISSUE THREAD

**Issue by joecain21** [night/BetterTTV#2230]
So I turned on beta mode and ever since I can't type in chat. Is there anyway that I can undo Beta? I can't see it in the settings anymore. I un-installed and re-installed and nothing changed.

**Comment by EhsanKia** [comment]
Very strange, can you give a bit more information? This is the first instance of this happening that we've heard of. What browser/OS are you on?

**Comment by joecain21** [comment]
In on Google Chrome. I was typing and it gave a message that it isn't
responding. Reconnecting in 2 seconds.

**Comment by night** [comment]
I mean, if you're getting a "reconnecting in 2 seconds" message then twitch chat is not connecting. That's not something we control.
