### ISSUE TITLE
Bttv Emote menu not showing

### ISSUE THREAD

**Issue by BlazerJake** [night/BetterTTV#2237]
I have the setting enabled and i cleared cache and disabled some other extensions on chrome. There are multiple errors and warnings (screenshot attached).
![javalog](https://cloud.githubusercontent.com/assets/25261756/24789377/bd6e346a-1b40-11e7-94c2-86173862b150.jpg)

**Comment by aroboto** [comment]
The emote menu on v6 of BTTV was disabled due to it causing issues on Twitch, the emote menu works fine in v7 so if you are desperate for it back consider switching to the beta.

**Comment by BlazerJake** [comment]
Thank you!
