### ISSUE TITLE
[v7] Arrow keys to input sent message history

### ISSUE THREAD

**Issue by Ninja101** [night/BetterTTV#2238]
In v7, it doesn't appear to have the sent message history available on up/down arrows.

**Comment by Entrexx** [comment]
Mirror of #2228 it has been imlemented a few hours ago.
I've noticed one thing that's different though, can't tell if it's intended or not.

Now if you use the 'Arrow Down' key for the first time it jumps to the end of the current message. You have to push 'Arrow Down' again to actually get to the previous message.

https://gfycat.com/FaroffJampackedJunco

**Comment by EhsanKia** [comment]
Yes, this is the new implementation I made and it works as intended. People always complained on multiline messages that they couldn't navigate the message properly without it going back and forth. The new implementation allows you to use the up and down arrow to navigate the message properly, and only goes to previous/next if you're at the start/end of the message. May feel strange at first but it's a much more solid experience.
