### ISSUE TITLE
Chat Doesnt go Grey color 

### ISSUE THREAD

**Issue by anefodiasmenos** [night/BetterTTV#2242]
http://prntscr.com/etoxaz i just press the Beta Thing that bttv has on the options and now on the chat is wierd white And its Not cool is there any option? 
I unistall it from extensions and reload it and it keeps that is there any choise to deselect the beta?

**Comment by EhsanKia** [comment]
Do you have any other extensions installed?

**Comment by EhsanKia** [comment]
Will use #2247 to track this
