### ISSUE TITLE
[v7] Chat Message History Issue and Right-Click Custom Timeout Selector

### ISSUE THREAD

**Issue by Priio** [night/BetterTTV#2244]
1. If I hit enter with no text entered, it seems to count that blank message towards the chat history when pressing the up arrow to scroll through previous messages. For example, I send the message "Hi" and then hit enter 5 times on a blank line, I would have to hit the up arrow 6 times to get back to the "Hi" message. 

2. I'm not sure if the feature was just removed, but right clicking to bring up the custom timeout selector is gone. I remember using it the first couple days of the beta but I'm not too sure on that as my memory sucks. Anyway, I'd like to request it being added to v7 if possible.

Using latest version of Chrome on macOS Sierra

**Comment by EhsanKia** [comment]
Good catch on both, will fix soon.
