### ISSUE TITLE
Feedback on the Beta version

### ISSUE THREAD

**Issue by OfficialwobY** [night/BetterTTV#2246]
Hey there HeyGuys

I've been using beta for few days so far. I really like the tab to complete with whispers but now i just want to talk about what i came across that could be fixed/added.

1. Opt out of beta button/switch. I was expecting you had that when i switched to beta to try it out. I really need some features that aren't in beta as of right now.
2. Custom timeout graph thingy. I'm a mod on a decently big channel, it's not summit like level but we get 1200 viewers on average. I use it all the time.
3. Double click to tag. When i double click the account infos thingy pops out, i already timed out few people cuz i'm used to the non-beta version. Also sometimes when I double click it tags people like "@user," and sometimes it does it like "@user ,". It's not a "game" breaking bug but t bugs me a bit :/
4. I miss the blue buttons.
5. Emote suggestion tooltip, it's not there anymore. The tooltip only shows up when you do "@" and then it  only shows usernames
6. Host button. Sometimes it's there, sometimes it's not.
7. There one small thing that's a bit weird to me, so i have "chat" as a highlighted word and when i join the chat and "Welcome to the chat room!" or when I disconnect from chat "Reconnecting to chat" message pops out it highlights it. It didn't use to do that.
8. I remember some bots having a bot like badge instead of the mod sword.
9. When friends start watching, the "Your friend <username> just started watching" doesn't appear

I'll probably find more things that i like with the non-beta BTTV. If i do i hope i can edit this.
I know i'm talking about small, not "game" breaking things but it's probably cause i can't opt out of beta and now i'm making a big deal out of nothing and that really bugs me :/ I love you guys anyways, this extension is a life saver #bleedPurple
My apologies if there's any typos or there's something you don't understand, english is not my native. language.

EDIT: When i do /part and then try to join again with /join i get this "You can't send messages when Anon Chat is enabled. Type /join or disable Anon Chat in options."

**Comment by EhsanKia** [comment]
1. Sadly it's difficult as we convert your settings to v7 format. You can go back by clearing your cookie/localstorage on Twitch, but again, you should backup your bttv settings before moving to beta so you can restore them. At this point though we should be close enough in features that beta is usable, as we'll start rolling it out very soon

2. This was working, it broke very recently, fix coming soon

3. Not sure what you mean? Double click should work. The space comma seems like an issue I can look into. The first time you click, the modcard opens, but on the second click, the mod card closes and mention happens. 

4. Most likely will never happen. It's a huge pain the maintain. I personally never saw the point (twitch's main color is purple, why would you want blue, it doesn't fit at all), but yeah I don't think Night wants to maintain it anymore. You'll forget it existed in a few days.

5. This one hasn't been implemented yet. Didn't think many people used it, having to tab twice seems fairly annoying. Try using it as it is now, might add it back in the future

6. That seems like a serious issue and first I hear of it. If you can find proper steps to replicate, it'd help a lot.

7. Yes, the new way we handle messages is different. You can now also highlight/blacklist notification messages from twitch too (such as sub and host notifications).

8. Badges are coming soon

9. Uh, that doesn't sound normal, I can look into it

10. I'll look into the /join issue, i think I know what broke it

Thanks for all the feedback, it definitely helps a lot. Note that this is a full rewrite from the ground up. Some things have been rethought from scratch, so give em a try before instantly dissing them. Some silly/useless things may be gone but may come back too. We're still fixing some small remaining bugs before release.

**Comment by OfficialwobY** [comment]
@EhsanKia found one more thing. When I get timed out or banned i don't get the "You got banned" notification thing in chat. It's completely removed.

Answer on the 1st point.
- I backed up my settings but even when i load them it's still in Beta
Answer on the 3rd point.
- When i click once modcards open, but when i click twice it tags the user but modcards open as well
Answer on the 6th point.
- I have a bookmark to the "http://www.twitch.tv/directory/following" and first time i load a stream it's not there. After a refresh or going back to Following directory it shows up. It works fine after that. 

Saw the note in changelogs that Beta is a full rewrite, I've been using BTTV for a year or two and it's been the most useful extension I've used. Good job, keep it going guys!
I really liked blue buttons but i don't mind not having them so it ok.
RIP Blue buttons you'll be remembered BibleThump

**Comment by OfficialwobY** [comment]
@EhsanKia found another one. When I want to tag people but i gave them a different nickname it tags them with that nickname instead of their real username

**Comment by Pathetisad** [comment]
Are the old JTV mod badges going to reappear in V7?

**Comment by OfficialwobY** [comment]
@EhsanKia @night it always pops out when i double click gfycat.com/NimbleSilentAmurminnow

**Comment by EhsanKia** [comment]
No need to tag people, we read all posts here... and yes I'm looking into it.
