### ISSUE TITLE
[Firefox] [V7 Beta] Some bugs and feedback

### ISSUE THREAD

**Issue by Timmyfox** [night/BetterTTV#2247]
* In channels where the link filter is enabled (Twitch settings > Channel & Videos > Delete links in chat), any posted links show up as <deleted message> even though "Show Deleted Messages" is enabled in BTTV settings. It used to work just fine in V6.

* Changing to Theater Mode, the chat will remain white despite everything else on the page going dark. Have to manually change to "Dark theme" in BTTV settings to make the chat match the rest of the page.
 
* Host button seems a bit inconsistent; Sometimes it shows up just fine, other times there's just a blank spot where it's supposed to be (turning the setting off and back on will make it reappear, however).
 
* The `/linehistory` command is completely broken it seems; I noticed the other day that it had reverted to the original behavior (even though it's one of the first things I disabled, I hate that feature) and I was unable to use the command to re-disable it.
 
* The feature to play a sound when you get mentioned or a whisper appears to be missing?

**Comment by EhsanKia** [comment]
1. Not sure exactly what you mean but I'll experiment with it and see.

2.Good catch will fix

3. Can't really replicate but I'll look through the code

4. I closed the brand new message history but I forgot to hook it to that command. Try the new version to see if you like it better but I'll add /linehistory soon.

5. Yeah forgot that one. We can add it back.

**Comment by Timmyfox** [comment]
1. Basically, the "Show deleted messages" doesn't seem work if the channel is set to auto-delete any links, it will show as "deleted message" regardless.
