### ISSUE TITLE
Banned Message

### ISSUE THREAD

**Issue by DrUnKeNTiGeR** [night/BetterTTV#225]
When someone is timed out or banned the message goes away no matter what setting i have chosen.

**Comment by night** [comment]
"Show Deleted Messages" shows you removed messages.

**Comment by DrUnKeNTiGeR** [comment]
Yes however no matter if this setting is off or on it removes the message.... If someone is timed out or banned I don't see the message or "message deleted " the message just disappears

**Comment by teak** [comment]
There is a second setting "Remove Deleted Messages", make sure this is toggled off..

**Comment by DrUnKeNTiGeR** [comment]
Im a derp thank you!
