### ISSUE TITLE
[Bug Report] | 20 Emote Weekly Limit - Only 13 Submitted.

### ISSUE THREAD

**Issue by TheCreativeJenn** [night/BetterTTV#2252]
[**Edit**] | Ehsan Kia, I fixed the link, so it should be viewable now. Regarding the burst of submissions, it wasn't my intention to overwhelm you or the Emote Approvers, however this was solely what I've been working on altogether to rebrand my Twitch channel and throughout the social media I'm part of. Sorry for any inconvenience - I'm only going by the issue of why I can't get past Emote [# 12] under the week cooldown.

Hello!

So basically the title speaks for itself. I asked TeakTop on Twitter about the issue, but haven't heard back - solely thinking that it wasn't the best way to handle this potential bug. I am a BTTV Pro User and I've designed 25 emotes exclusively for BTTV, however [this is the error](http://orig01.deviantart.net/f43a/f/2017/100/6/7/bttv_error_by_thecreativejenn-db5ckd2.jpg) that continues to be shown whenever I try to re-add the 13th emote amongst ones that still need to be reviewed.

I hope this can be resolved soon! I'm at a total loss of what to do other than wait a week for what can be a consistent error.
Jenn 2017

**Comment by EhsanKia** [comment]
First, your image seems to be broken, but as for your issue, you can wait for Night's reply, but in general, we would appreciate if you could submit emotes more as they come rather than in a huge burst

**Comment by night** [comment]
Every attempt counts against you, so failed uploads and rejected emotes count against your quota. We deal with a lot of submissions per day, all manually approved, so we do not have the bandwidth for people to submit to us unlimited emotes. You will need to wait a week before submitting more, sorry.

**Comment by TheCreativeJenn** [comment]
Thanks, Night.

Again, I'm sorry for any misguided approach with the process of my emotes. I can understand you deal with a lot of submissions per day, that's nothing I expect to be an exception for. Just.. as a BTTV User, the prompt saying "You can only upload 20 emotes per week. Try again next week." after being asked to resubmit an emote that failed to appear on Review as shown in my link above has me confused and a bit aggravated because I couldn't tell if it was a bug or my browser.

Thank you!
Jenn 2017
