### ISSUE TITLE
Weird Spacing for Mods/Turbo/Prime People

### ISSUE THREAD

**Issue by endPCE** [night/BetterTTV#2253]
http://i.imgur.com/ezkm4xi.png
http://i.imgur.com/6wuNS3z.png

I don't really know what is causing this, but I figure its something to do with BTTV. Running v7.0.0

**Comment by SocietyX** [comment]
I am also having weird formatting in the chat thus far. Not sure if it's just Mods/Turbo or not but here is screenshot of mine .. 

https://gyazo.com/f3152094c2446a0c89d0ac28213e83cb

**Comment by night** [comment]
@Aaron128l

**Comment by Aaron128l** [comment]
Sorry about that. With `inline-block` display span tags will add automatic whitespace that is proving a little difficult to remove. Clearly the way I tried to compensate for it causes issues. I'll start working on a better way to handle it.
