### ISSUE TITLE
Is there a way to possibly finally make the whispers "Disable/Enable Do not Disturb" feature "remember"/"stick" ?

### ISSUE THREAD

**Issue by Leifman27** [night/BetterTTV#2254]
I mean, i've even tried to post it on twitches reddit and ask about it for probably a year (over since the entire whisper system has been changed to what it is today)
It is super annoying to do every single day, every single twitch tab, every time you refresh.
The "Enable Do Not Disturb" that practically tells the current whisper system to not "open new boxes of whispers" every single time someone whispers you and makes it at least moderately sane to use simply does not remember/stick if you open some new tab/twitch window in another browser etc'.
You have to keep doing the "Enable Do Not Disturb" every single time, i clearly mean this : 
http://i.imgur.com/32SNtMX.png
So much like many things that twitch fucks up and never gets to fixing or at least hearing that it bothers people A LOT (and i am sure it is not such a big feature/thing to do.. just to make a cookie or w/e that remembers if you have that option selected to remember for future sessions) I can only wish and ask if it is possible to fix with bttv possibly.
Please save me from the daily OCD and needless headache of constantly having to enable the do not disturb across multiple tabs/browsers etc' ;_____;

**Comment by Leifman27** [comment]
Please? ;'(

**Comment by night** [comment]
I wasn't even aware they have a do not disturb feature. Is there a reason why you don't just disable whispers from non-friends at https://www.twitch.tv/settings/security?
