### ISSUE TITLE
Set Font

### ISSUE THREAD

**Issue by k-a-cox** [night/BetterTTV#2259]
I don't know if it was the updated twitch layout or the beta version of bttv, but the set font button doesnt pop up options. The font size one does still

**Comment by jaaneh** [comment]
Font and Font Size works fine here.

**Comment by night** [comment]
Swap to the beta in the BetterTTV settings, it is working fine there.

**Comment by k-a-cox** [comment]
I swapped to beta, and it isn't working on my computer. Is there a way to refresh the bttv settings (ie reset to plugin defaults)?

**Comment by EhsanKia** [comment]
What exactly isn't working? You should try to figure out the problem as we will be switching to the beta soon for everyone, so going back will only solve the problem temporarily. What browser are you on, are there any errors in the console?

**Comment by k-a-cox** [comment]
I cleared the cache and reset my settings and it seemed to fix. It must have messed up as I had a few tabs of twitch open when I switched over to beta.
Thanks for the offer of help though.
