### ISSUE TITLE
Change the Nav Bar Color on New Theme

### ISSUE THREAD

**Issue by kbourne87** [night/BetterTTV#2260]
Can you update dark mode to make the upper nav bar black instead of purple? 

The CSS I'd like to see would be something like:

.flex flex--nowrap top-nav__nav-items-list {
  background: #000;
}

.flex__item top-nav__drawer-anchor flex ember-view {
background: #000;
}

.flex__item js-top-nav-logo top-nav__logo{
background: #000;
}

**Comment by SaiyanOfDarkness** [comment]
How come this is still a thing?

I thought this would have been implemented a while ago.  This purple bar is god damn annoying.

**Comment by EhsanKia** [comment]
The "color" is annoying? or the bar itself. We're most likely never going to get rid of the bar. It's a big part of Twitch's new navigation, and trying to re-implement the old layout would be a huge undertaking. Most of us also don't really see an issue with it.

As for the color, it may be a bit bright, and we may consider skinning it, but I don't how it's "god damn annoying"

**Comment by SaiyanOfDarkness** [comment]
It's annoying in the sense that it's like watching a movie and someone decided to leave a light on that you can't turn off. 

The top bar can easily be changed. Why wouldn't you though to match the Dark Theme

**Comment by EhsanKia** [comment]
You can always use theatre mode. Simply press alt+t and all the distractions go away!

**Comment by SaiyanOfDarkness** [comment]
Yeah, but not everyone likes to use Theatre Mode, it makes looking at 720p streams more blurry than their normal default size resolution.

I thought putting this in wouldn't be that difficult for Dark Mode?

**Comment by night** [comment]
this is no longer necessary
