### ISSUE TITLE
BetterTTV - Version 7.0.0Beta Disadvantages 

### ISSUE THREAD

**Issue by DeadThepleb** [night/BetterTTV#2262]
- Emotes/text are small and glitch out when you're typing in the chat room
- Top bit badge donator unable to dismiss 
- Overall performance is downgraded and lags when you're entering a channel or typing in a chat room

**Comment by EhsanKia** [comment]
1. Not sure what you mean, you'll need to show images or video
2. Either disable bits entirely or /localunpin in chat
3. That's not normal, the new rewrite is much cleaner and fast.

**Comment by night** [comment]
Closing due to lack of response and non-reproducible behavior.
