### ISSUE TITLE
[v7] Cannot use /join in anon chat

### ISSUE THREAD

**Issue by Px05119** [night/BetterTTV#2263]
Title says it all. When using anon chat (either in settings or using /part) and trying to disable it with /join I get this:
8:30  You can't send messages when Anon Chat is enabled. Type /join or disable Anon Chat in options.

If I do this with /part, that means I have to go into settings, enable anon chat, then disable it to join chat.

**Comment by EhsanKia** [comment]
The fix has been made and will be pushed in the next release.
