### ISSUE TITLE
Mute Keyboard Shortcuts Not Working

### ISSUE THREAD

**Issue by Ladish** [night/BetterTTV#2264]
I tried the option for Keyboard Shortcuts. Fullscreen and play/pause work just fine; however I can't mute the stream by pressing M. 

I'm using BetterTTV v6.8R55 with Chrome 57.0.2987.133

**Comment by night** [comment]
They work on the beta, so enable the beta in the BetterTTV settings to fix this.

**Comment by EhsanKia** [comment]
Nah twitch changed css classes on the player and the mute selector broke (on v7 and v6.8)

**Comment by Ladish** [comment]
Enabling beta does not fix the problem for me either.

**Comment by night** [comment]
It is fixed now in beta.
