### ISSUE TITLE
[Feature Request] Hide top nav bar

### ISSUE THREAD

**Issue by caboose211** [night/BetterTTV#2265]
With new twitch layout and the live followed channels on the left now. I would like to be able to hide the nav bar at the top.

**Comment by EhsanKia** [comment]
It won't quite be doable without major modifications, as a lot of important features are up there. The bar doesn't take much space, and you can watch streams in Theater Mode to get rid of the clutter anyway. Doubt this will happen. We'd have to maintain a whole fork of the layout.
