### ISSUE TITLE
[FeatureRequest] always show all live followed channels on the browse page

### ISSUE THREAD

**Issue by rxy95** [night/BetterTTV#2267]
With the new layout, only the ca. 5 highest viewer channels you follow show up in the sidebar on https://www.twitch.tv/directory/all . i would like to have an option to show all live followed channels without haveing to click on 'load more'.

**Comment by night** [comment]
Have you tried using the following page instead and enabling the "Default to Live Channels" option in the BetterTTV settings?

**Comment by rxy95** [comment]
I want to have both popular  (unfollowed) channels and  my followed channels on the same page. this is no longer possible with the new layout (at least not with all followed channels loaded)
