### ISSUE TITLE
Is anyone's viewer list bugged

### ISSUE THREAD

**Issue by Bren002** [night/BetterTTV#2269]
When I scroll down it just goes to the very bottom.

**Comment by EhsanKia** [comment]
Yes, sorry, this is an issue in an underlying library we use, and it's an issue with Chrome.
https://github.com/shama/view-list/issues/9

Will try to look if I can come up for a fix for it myself since the maintainer of that library doesn't seem to be active.

**Comment by thinkpad4** [comment]
That dev is still active on other repos, and you can find his Twitter from his website @EhsanKia

**Comment by night** [comment]
since we're not longer maintaining our own viewer list this is no longer an issue
