### ISSUE TITLE
Chat Scroll Spazzy

### ISSUE THREAD

**Issue by hherman1** [night/BetterTTV#2272]
Observe:

https://streamable.com/xzrzd

This only happens while I have bttv installed. It seems new messages have something like a 50% chance to trigger the chat to scroll all the way to the top, which makes it impossible to try and read the chat (esp. when you might want to read it most, when something actually happens), and basically makes the heart of the extension useless! (since what is BTTV without chat?).

This happens the same on my other computer as well, so I know its not just me.

**Comment by night** [comment]
Enable the beta in the BetterTTV settings.
