### ISSUE TITLE
Suggestion: ChromePlugin manifest change

### ISSUE THREAD

**Issue by BarryCarlyon** [night/BetterTTV#2276]
I took a look at BTTV's chrome plugin manfiest file to borrow the matches/excludes and spotted this:

            "exclude_matches": [
                "*://*.twitch.tv/*.html",
                "*://*.twitch.tv/*.htm"
            ]

I think

            "exclude_matches": [
                "*://*.twitch.tv/*.html*",
                "*://*.twitch.tv/*.html",
                "*://*.twitch.tv/*.htm"
            ]

Is better to prevent BTTV trying to load on the API Crossdomain Receiver at 

> https://api.twitch.tv/crossdomain/receiver.html?v=2

(I was trying to load jQuery in what I was testing and couldn't for a bit figure out what was tripping till I saw my plugin was trying to load on the crossdomain URL)

**Comment by night** [comment]
This is fixed in v7.2 of the Chrome extension.
