### ISSUE TITLE
[Suggestion] Add keyboard shortcut for "Anon Chat" option

### ISSUE THREAD

**Issue by Gewath** [night/BetterTTV#2277]
Anon chat lets you join chats anonymously without being able to chat. Which is great, apart it takes 6 mouse button clicks in separate locations to disable it, then another 6 coordinated mouse button clicks to re-enable it, if you want to post one message. That's a total 12 mouse clicks per message.

In contrast, a two key keyboard shortcut is four clicks per message, without a need to move your hands from the keyboard or aiming a mouse. In addition I'd assume it'd be stupidly easy to implement. Thoughts?

**Comment by EhsanKia** [comment]
/join and /part in the chat are the fast and temporary shortcuts for Anon Chat.
