### ISSUE TITLE
[V7] Arrow Key Message History

### ISSUE THREAD

**Issue by Entrexx** [night/BetterTTV#2279]
I've noticed one more thing that's different in V7. Before you could add a message to the message history without actually sending it by pressing 'Arrow Down'. Useful for messages that you want to send later for instance when the streamer died ingame and has time to look at chat.

If I type a message now and press 'Arrow Down' the message just disappears. Can't tell if it's supposed to be like this.

Example: https://gfycat.com/HoarseGreatCrocodileskink

**Comment by EhsanKia** [comment]
Probably easy to add I guess

**Comment by Entrexx** [comment]
The original issue still exists. One other thing I've noticed is, that if you take a message from the message history, edit that and then press 'Arrow Down' it will add the message to the history but cut off the last character.

**Comment by night** [comment]
it's not released yet.
