### ISSUE TITLE
betabug

### ISSUE THREAD

**Issue by AnastasiaUna** [night/BetterTTV#2282]
2 days after i switched to beta i could not see my paid for bttv personal 5 emotes in whispers if i use them, i now have to have 2 channels open to see them in whispers. if i type it in one tabs whispers it shows the emote only in the other tabs whisper and vice versa . so if i try to only be in one stream, im bugged and only see the words not the emote but in my settings it shows they are there .much thanks for if it can be fixed.

**Comment by night** [comment]
This is fixed as of last night.
