### ISSUE TITLE
Reopening of #2272: Chat scroll spazzy

### ISSUE THREAD

**Issue by hherman1** [night/BetterTTV#2283]
The issue: #2272

I have now enabled the beta and it has not fixed the issue:

https://streamable.com/uvcw0

Frustrating!

**Comment by EhsanKia** [comment]
Can you list the other extensions you have installed?
chrome://extensions

**Comment by hherman1** [comment]
- Advanced REST client 9.14.64.305-stable
- AlienTube for YouTube™ 2.6
- Reddit Comments for YouTube
- ARC cookie exchange 0.0.3
- BetterTTV 7.1
- Bypass Paywalls 1.0.3
- Checker Plus for Gmail™ 20.1.1
- Chrome Regex Search 1.0.7
- Extensions Reloader 1.14
- Google Docs 0.9 
- Google Docs Offline 1.4
- Google Keep Chrome Extension 3.1.16302.1110
- Google Sheets 1.1
- Google Slides 0.9
- HTTPS Everywhere 2017.4.5
- Imagus 0.9.8.50
- Javadoc Search Frame 1.6.1
- LastPass: Free Password Manager 4.1.45
- Multi Forward for Gmail 3.0
- React Developer Tools 2.0.12
- Reddit Enhancement Suite 5.4.3
- Save to Pocket 2.1.32
- Sense (Beta) 0.9.3
- SSH for Google Cloud Platform 1.11
- Tampermonkey 4.2.7 (no scripts on twitch though)
- uBlock Origin 1.12.1
- Universal Party Parrot 0.0.3

I'd be surprised if any of these interfered.

**Comment by EhsanKia** [comment]
Well it's pretty easy to check, try either disabling all others, or simpler, enable BTTV in incognito (Where all extensions are disabled by default) and try there. As a bonus, all cookies and localstorage will be cleared there too so you get a blank slate.

**Comment by night** [comment]
Note that since we do not touch scrolling on the twitch chat in the beta it cannot be us.
