### ISSUE TITLE
2 beta v7 issues

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2284]
First, Scrolling up in beta doesn't pause the chat.  When I place the mouse over the chat and mousewheel up the chat doesn't pause, only when I click on the chat while it is scrolled up quickly will the more messages below shows.  This is very hard to do in fast moving chats.

Second, when using tab complete, emote codes are mixed into the selection of names instead of coming after all relevant usernames are tabbed through

**Comment by EhsanKia** [comment]
1. That's a twitch issue, alternatively, hold control which is BTTV's chat freeze feature.

2. Hasn't it always been like that? There used to be an option for putting emotes before names, but I don't remember an option for putting names before emotes. Will be adding more tab complete options later when we get the new settings menu.

**Comment by thinkpad4** [comment]
The scrolling up issue didn't happen on v6.  I just hover the mouse over the scrolling chat and wheel up and it pauses

**Comment by EhsanKia** [comment]
That's because V6 reimplemented chat from scratch, V7 uses default Twitch chat.

**Comment by thinkpad4** [comment]
Any chance of re implementing that aspect to v7?

**Comment by Extremecodgod21** [comment]
how can i go back to version 6.8?

**Comment by voloshink** [comment]
clear cache and cookies on twitch
