### ISSUE TITLE
Username colors are wrong in theatre mode

### ISSUE THREAD

**Issue by Brottweiler** [night/BetterTTV#2287]
The 2nd bug in https://github.com/night/BetterTTV/issues/2247 was fixed, but the username colors in theatre mode are the ones of having dark theme disabled, so they are too dark against the chat background. 

Check the blue color specifically here to notice it: https://i.imgur.com/htsLJ1g.png

This is using **v7 beta**. Before v7, the username colors would get brighter when enableing theatre mode, it no longer does. It does if you enable dark theme though.

**Comment by EhsanKia** [comment]
good catch.
