### ISSUE TITLE
Emote completion box not working

### ISSUE THREAD

**Issue by aohqoi12341** [night/betterttv#2288]
When typing the start of an emote, usually a list of emotes starting with what you typed will pop up but this isn't working for me anymore. I've tried uninstalling and reinstalling but the problem still remains.

eg: when typing "Ka" a box would appear above the chatbox listing emotes like "Kappa, KappaClaus, KappaPride" etc. and you would be able to cycle through them by pressing tab.

**Comment by Ludricio** [comment]
Even tho it might be faster, I like being able to view what available options I'm actually cycling through. :/

**Comment by ThibaultVlacich** [comment]
Here's a suggestion to keep the best of both (the fast autocomplete and the menu):
* When tapping TAB it autocompletes to the first match AND open the menu.
* You can continue to cycle through autocompletes suggestions by pressing TAB or click on a suggestion in the menu 
* If you press ENTER or SPACE, it close the menu and you can continue to write your message.

**Comment by night** [comment]
We added this in a recent update!
