### ISSUE TITLE
Loading sign doesn't turn off

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#2293]
For a while, after the stream reloads, the loading circle in the middle of the screen doesn't go away after the video continues. Sometimes it happens, sometimes it doesn't. However, it happens both on the stable and beta versions.

![untitled](https://cloud.githubusercontent.com/assets/6445601/25277466/70406768-26a7-11e7-93dc-50911682b036.png)

**Comment by night** [comment]
Why is this our bug? It would have to be Twitch's
