### ISSUE TITLE
Emote description doesn't go dark on dark mode

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#2294]
![untitled](https://cloud.githubusercontent.com/assets/6445601/25277884/2e192ecc-26a9-11e7-9e6f-a28f92742cc6.png)

**Comment by night** [comment]
seems fine for me. give repro steps

**Comment by EhsanKia** [comment]
After some random testing, seems to happen in theatre mode, I wonder if it's related to the other issue. Though, I'll be honestly, I kinda like the white tool tips better, maybe if they were a bit transparent. Still need to do a proper BTTV css for those.
