### ISSUE TITLE
Emote description get cut off by the stream title

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#2295]
![untitled](https://cloud.githubusercontent.com/assets/6445601/25277986/96104998-26a9-11e7-83bd-e376a40efd02.png)

**Comment by Runer112** [comment]
This happens in even more situations for me. Just about anything cuts off the emote description, including the (bounding box for) the line of text above.

**Comment by night** [comment]
I can fix the line issues in whispers, but fixing the rest of the situations is a pita due to how these work. Anyone is welcome to put in the time to create an algorithm to auto position these upon hover, but I don't have the time at present.

**Comment by Runer112** [comment]
@night What exactly has been fixed? I'm mainly concerned about the situation I mentioned, because it makes seeing the source of BTTV emotes basically impossible. This is what I currently see when I hover my mouse over any BTTV emote in chat:

![bttv_2295](https://cloud.githubusercontent.com/assets/6608979/25627618/2e8f12aa-2f31-11e7-9d2c-9539aeb66147.png)

**Comment by EhsanKia** [comment]
Not sure how that happens for you because I can't replicate, it shows up properly on top on my end. Do you have other extensions installed?

**Comment by Runer112** [comment]
I've tried disabling all other Chrome extensions and the issue still occurs. I even went so far as to create a fresh instance of Chrome on another computer with none of my history/settings/etc and install only BTTV, and it's the same.

**Comment by Runer112** [comment]
Making a fresh comment because it would be bad if this edit gets lost:

I believe I've finally discovered the trigger condition for the issue. This happens for the chat replay in VODs, not for live chat in live streams.

**Comment by EhsanKia** [comment]
Oh, alright. Can you make a new issue and specify that there.
