### ISSUE TITLE
Disableing theatre mode enables dark theme temporarily

### ISSUE THREAD

**Issue by Brottweiler** [night/BetterTTV#2296]
- **Version**: v7

----

1. Have dark theme disabled
2. Open a stream
3. Enable theatre mode
4. Exit theatre mode

Dark theme should now be enabled visually. It's not enabled in the settings, and refresing the page disables dark theme, but if you would enable and exit theatre mode again, dark theme is back.

**Comment by EhsanKia** [comment]
Can reproduce, probably as result of:
https://github.com/night/BetterTTV/commit/3186edfc3edc9b795900f6a6c4fedfabcaa105bf

**Comment by night** [comment]
heheheeeheh
