### ISSUE TITLE
Tooltips cover up Mod Icons so you can't click them

### ISSUE THREAD

**Issue by Grimicus** [night/BetterTTV#2298]
I keep having a problem with the mod icons in chat where the tooltip pops up and then I can't actually click on it.  It makes it very difficult to click especially as chat is moving.  They used to not have tooltips, so this is something new.

I am using Chrome 57.0.2987.133 an BTTV 7.0

**Comment by night** [comment]
I cannot reproduce on the beta. If you have not already, enable the "BetterTTV Beta" in the BetterTTV settings.

**Comment by Grimicus** [comment]
There is no choice for 'BetterTTV Beta' in the settings anywhere I can see.   The changelog tab says this:
Changelog

Version 7.0.0beta
This is a complete rewrite of the extension. It should resolve most bugs reported to us as of late.

In chrome extensions, it says I am using BetterTTV 7.2

Here's some screenshots showing the problem, though the computer I originally reported about actually has the tooltip covering the button I am attempting to use, despite that, there is a still an issue thought not as bad.

The red arrow shows where I am mousing, and the timeout completely blocks the entries above
![timout_mouseover](https://cloud.githubusercontent.com/assets/27870686/25308242/298a0bc6-2765-11e7-8435-7b8c15238a92.jpg)
If I move the cursor up, the timeout blocks my mouse as shown below in red.  I cannot click on the button underneath.
![timeout_tooltip_mousover](https://cloud.githubusercontent.com/assets/27870686/25308250/47c94278-2765-11e7-8267-8053f9aafaff.png)

I have these settings enabled in bttv settings:
Better Viewer List 
BetterTTV Emotes
BetterTTV GIF Emotes
Completion Tooltip
Dark Theme
Hide Recommended Channels
Show Deleted Messages
