### ISSUE TITLE
Draggable Elements Width/Height Changes

### ISSUE THREAD

**Issue by Entrexx** [night/BetterTTV#2299]
The Viewer List (Better Viewer List enabled) changes it's width when it's being moved.

Example: https://gfycat.com/LimpingWatchfulAsiandamselfly

**Comment by Aaron128l** [comment]
On the same topic of the viewer list. The header can be dragged into the nav bar of the new layout preventing the ability to move it. 

https://i.aaron128l.com/1yUm13A.png

**Comment by EhsanKia** [comment]
Fixed Aaron's issue, but the original issue, honestly, nothing I can do about it for now. Twitch decided to add fixed width and height CSS to .ui-draggable-dragging (which applies to ANY dragging element on the whole site), with !important on them... Pain in the ass to override that.

**Comment by AlcaDesign** [comment]
Mod cards too
![](https://i.gyazo.com/586dc6243277e8530e1043fc3bd96c8f.gif) [MP4](https://i.gyazo.com/586dc6243277e8530e1043fc3bd96c8f.mp4)

**Comment by night** [comment]
twitch fixed it
