### ISSUE TITLE
Popout not loading BTTV

### ISSUE THREAD

**Issue by Asuzara** [night/BetterTTV#2301]
Hi,
I have this problem for several weeks now. Whenever I popout my chat, Bttv is not loading for it 90% of the times. Sometimes I refresh around 10 times and suddenly it is working, most of the times it doesn't. As I use popout as a streamer too, this is very frustrating. Can't see name highlights, whispers are shown white on white background, can't see bttv emotes etc....
I have the problem on both newest Firefox and Chrome, have deleted cache and cookies multiple times already, have reinstalled bttv too. Any help?
Cheers

**Comment by Nareese** [comment]
Scroll to the bottom of the BTTV settings panel and activate Version 7 beta.  Report any issues with it here.  It will be much more stable, especially specifically for pop out chat.
