### ISSUE TITLE
Having an issue with auto scrolling

### ISSUE THREAD

**Issue by Kontaru** [night/BetterTTV#2303]
When I try to scroll up in chat, it automatically scrolls me back down when a new message shows up. What is even more strange is that I have been using BTTV for 4 years, and have literally never had this issue until a few days ago. No clue what could have triggered it.

**Comment by blinxs** [comment]
happening to me as well

**Comment by Tatobson** [comment]
Having the same issue

**Comment by Kontaru** [comment]
Not a fix, but I find that if I scroll up and immediately hit my middle mouse button, I can free scroll again, and then I have to click "more messages below" right about the text box in order to continue auto scrolling. I hope a proper solution crops up eventually.
