### ISSUE TITLE
Blue Button and highlight Glitch

### ISSUE THREAD

**Issue by blinxs** [night/BetterTTV#2305]
About a week ago I turned on my pc and open twitch to watch my favorite streams. I noticed the blue buttons have turned purple and when someone other then me @'s another person its no longer highlighted. I looked to see if I turned these settings off but the ENTIRE setting was missing. Very confused on why. This messes with me alot. Along with that the chat seems glitchy as I can no longer see if someone got timed out or banned. Being a mod in a few small channels this is a problem. Any one else having this??

**Comment by EhsanKia** [comment]
Sadly, support for blue buttons is gone, as Twitch keeps changing their layout (and making purple more and more pronounced as their primary color), and it has become a futile and time wasting attempt trying to keep up with them.

I'm not sure what the second issue is, could you give a more detailed example and maybe a screenshot?

**Comment by blinxs** [comment]
To explain the highlight one. In these 2 screen shots 

https://gyazo.com/ab02d1cda41278fd627aa43c883caa58 https://gyazo.com/d24f8fb312d2306b151ab1bb7025e5e0 

someone other then me @'d these 2 and the names are not highlighted. 

But when I @ some one the names are. 

https://gyazo.com/ceaf3f34b75326308d92d77bb1d6ebe0 

It's not a big deal or any way important just something I noticed the same day. 

And the time out and ban one when some one is timed out or banned in chat the darker-ish chat that says "(username) has been timed out" no long pops up. Again not important just wondering.

**Comment by night** [comment]
fixed by a2ccd981f09e417cd30191d75abf7f07f3b308f9

latter issue is intentional
