### ISSUE TITLE
Deletet Message turn into light grey

### ISSUE THREAD

**Issue by BlutWolf17** [night/BetterTTV#2306]
Hey I got a problem wit BetterTTV (Version : 7.2) , when I delete messages it turns into light grey and that is annoying because I must check them again and the colour is to light for me.

Screenshot: https://puu.sh/vt0Au/045ce7d554.png

I dont have any other plugins in my Browser.
How can I fix it?

**Comment by night** [comment]
This is as intended. I am able to read them fine as-is.
