### ISSUE TITLE
BTTV Beta

### ISSUE THREAD

**Issue by eKoyz** [night/BetterTTV#2308]
I am not in the beta for bttv, and it is still taking some features away. I downloaded my settings to see if they were right, and beta says false. The Tab Emote priority is removed from my settings, and it is not letting me scroll up in chat. If I could get some help I would appreciate it.

**Comment by Nareese** [comment]
The beta is currently automatic for ~10% of users.  It is likely that you are one of them.

Prioritizations for tab completion has not been implemented in version 7 yet, and has been frequently requested (#2122 for example).

Issues with scrolling (apparently Chrome specific) have also been reported (#2300 and others).

**Comment by EhsanKia** [comment]
Tab completion options will come after we finish cleaning up all the more pressing issues in the beta. Scrolling in chat is a Twitch issue and I was really hoping they would fix it but it doesn't look like it so I guess we'll fix it for them, as always.

**Comment by eKoyz** [comment]
OK sounds good. Thanks for the info.
