### ISSUE TITLE
Stop chat scroll when selecting text

### ISSUE THREAD

**Issue by acrisci** [night/BetterTTV#231]
When I am selecting text to do a copy pasta, the chat will continue to scroll and mess up my text selection. It would be nice if the chat would stop scrolling when I am selecting text to make it easier to copy and paste.

As a workaround, I can scroll up a bit and it will stop the chat scroll, but it would be nice to not have to do that extra step.

**Comment by night** [comment]
You scroll up to pause chat. That's sufficient for all chat pausing needs.
