### ISSUE TITLE
Host button continuously disappearing.

### ISSUE THREAD

**Issue by Demogarose** [night/BetterTTV#2313]
needs to be disabled and re-enabled manually to re-appear
![bug report](https://cloud.githubusercontent.com/assets/12262575/25319328/9cb6d920-286a-11e7-8dfc-22c6d52cedf0.png)

**Comment by night** [comment]
Scroll to the bottom of your settings, and enable the beta. This is fixed in the beta.

**Comment by Demogarose** [comment]
Hmm, enabled Beta, This happened: 
![bug report 2](https://cloud.githubusercontent.com/assets/12262575/25320037/5763c0de-2871-11e7-97f4-8a6d6598ee4c.png)
