### ISSUE TITLE
Left Ctrl chat pause issue

### ISSUE THREAD

**Issue by IStealthI** [night/BetterTTV#2314]
The beta has made it more difficult to mod as when you press Left Ctrl now you need to be hovering over the chat with your mouse now, and even when you do that you can't press time out buttons on the side of the users name and when you try to do that it opens up another tab of the twitch channel you're in, you can't deny or approve auto mod messages, and can't double tap a users name to @ them. Overall it makes it very hard to mod when chats are going fast and makes mods more prone to making misclicks.

And a couple small notes, when you add a reason to a time out it doesn't show, I'm not sure if it shows for other mods without the beta or even with it.
And when you try to type out a time out it doesn't pop up autocomplete options for a user.

**Comment by night** [comment]
fixed in 2fb72f12afcf3b75990b872a922f9e343be44d8d

ctrl will soon toggle pause instead of requiring you to keep pressing it, resolving this. 

reasons are sent.. they just don't show to yourself I guess
