### ISSUE TITLE
Add gap between badges. v7

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#2315]
![image](https://cloud.githubusercontent.com/assets/14076068/25329690/84556df8-28e5-11e7-8fc2-82d3d44805ba.png)

**Comment by night** [comment]
https://nightdev.com/i/ss-QqO7LiRBHxIvdYagkbZQN386S.png

looks fine on my screen.. clear your cache.

**Comment by gapbl4** [comment]
I forgot to disable ffz to see how it looks. 
This happens when ffz extension is enabled, but only on v7.
