### ISSUE TITLE
Can't click on certain things.

### ISSUE THREAD

**Issue by ApeFest** [night/BetterTTV#2316]
While in browse for example I can't click on almost any game or switch to "popular/creative" etc. When I turn off BetterTTV everything works again but stops when I turn it on. I can open things in a new window and refresh it a couple of times and it will eventually load though.

**Comment by night** [comment]
I cannot reproduce these issues. Ensure you're using our beta by enabling the "BetterTTV Beta" in the BetterTTV settings (bottom of the list).

If that doesn't work, try disabling all other extensions to see if another extension is conflicting with ours.
