### ISSUE TITLE
Dark mod auto un-selecting itself in v7.0.0

### ISSUE THREAD

**Issue by Fire0x** [night/BetterTTV#2317]
Dark Mode doesn't stay on when go from 1 stream to another  in v7.0.0

**Comment by Rgern100** [comment]
For me too, 7.00

**Comment by Nareese** [comment]
This is related to a fix ([c920973](https://github.com/night/BetterTTV/commit/c920973b7b705f1e74caf11a615d919b46bc1f8c)) for a previous issue (#2296)
