### ISSUE TITLE
twitch chat jumping up and down 

### ISSUE THREAD

**Issue by ziichu** [night/BetterTTV#2318]
hi there
I made an old issue #2207 for this same subject 

my twitch chat keeps jumping up and down continuously , and i have to refresh or clear chat or disable betterTTV to fix it and it keeps happening,

XPS 15 (9560)
chrome Version 57.0.2987.133 (64-bit)
BTTV 7.2 
video for a better explanation > https://www.dropbox.com/s/gmnor3alzkl61xo/112.avi?dl=0

I enabled beta mode and it fixed it for a while and now its back again . **the main cause seems to be when you scroll up to check old messages then scroll down again** 

thank you

**Comment by EhsanKia** [comment]
Try disabling other extensions and see if this still happens.
