### ISSUE TITLE
Chat font bug

### ISSUE THREAD

**Issue by Elkracho** [night/BetterTTV#2319]
Hello,
I have the vanilla chat font and changing the font on twitch doesnt do anything. I also tried to reinstall BTTV. pls help 

screenshot: http://prntscr.com/f09nut

**Comment by EhsanKia** [comment]
What font did you enter? It works fine for me. Try entering "monospace" and see if that works.

**Comment by Elkracho** [comment]
i tried that also but it changes nothing.

**Comment by Antzer** [comment]
I switched to "BETA" and get this also

**Comment by night** [comment]
I cannot reproduce any issues.
