### ISSUE TITLE
Dark theme canceling.

### ISSUE THREAD

**Issue by Draesy** [night/BetterTTV#2320]
Just meet a new (to me) bug. Whenever i open new twitch page (new streamer i mean) dark theme in off position. Every time it need for go to the settings and manually change this to "ON". Same with "Theatre mode". Video with bug included.
[2017-04-25 01-07-52.zip](https://github.com/night/BetterTTV/files/953330/2017-04-25.01-07-52.zip)

**Comment by night** [comment]
duplicate of #2317
