### ISSUE TITLE
Revert twitch layout option in BTTV

### ISSUE THREAD

**Issue by Mrdongman** [night/BetterTTV#2331]
Many users are feeling unsatisfied with recent Twitch layout changes. Could there be an option in BTTV to revert the layout to the old version? I for one am unhappy with the unhidable/unrevertable huge purple navigation bar at the top of the screen and the removal of the right most sidebar.

Some have also voiced concern over the new left sidebars functionality.
https://www.reddit.com/r/Twitch/comments/67d4hb/can_the_followed_channels_sidebar_be_functional/

Old layout vs new layout.
http://imgur.com/a/Ko4dG

**Comment by night** [comment]
We disagree that the new layout is bad compared to the last. The only change we would be in favor is the sidebar layout prior to the most recent. With that being said, we no longer like to do heavy UI mods to the Twitch site any longer since they are a pain to maintain.
