### ISSUE TITLE
"Shift+Tab" should work like "Tab" like in previous versions!

### ISSUE THREAD

**Issue by neokjo** [night/BetterTTV#2333]
With the latest version you can't auto-complete with Shift-Tab anymore.
In Chat Clients like Chatty this is used for emote-autocomplete.
Now with the latest update Shift+Tab just do nothing.

Would be a small usefull change to bring it back in the latest version

Edit: Subemotes seems to work with Shift+Tab atm. Only Twitch Global and BTTV Emotes not Complete with Shift+Tab

**Comment by EhsanKia** [comment]
I'm not sure what you mean. The behavior of shift tab is same as before, and also consistent with all other software. Tab goes to the next suggestion, and shift+tab goes to the previous suggestion. It simply reverses the order.

**Comment by neokjo** [comment]
If you have disabled "Completion Tooltip" - "Tab" and "Shift+Tab" both should complete the emote/nickname. but at this moment, this only work for subemotes,

**Comment by EhsanKia** [comment]
I see the bug. There's a small bug where if the list only contains one element, shift+tab won't properly work. Otherwise, if there are more than 1, tab goes to the first, shift+tab goes to the last.
