### ISSUE TITLE
Pressing Ctrl in chat window scrolls chat to latest message

### ISSUE THREAD

**Issue by dutchgecko** [night/BetterTTV#2334]
BTTV version: 7.2

Using popout chat.

I noticed in v7 that holding down the ctrl key stops chat scrolling. However, in a recent update this appears to be broken, and instead the chat scrolls immediately. Holding down the ctrl key causes the "More messages below" popup to flash repeatedly at the bottom of the window.

Unfortunately this bug can interfere with the reproduction of copypasta.

**Comment by Nareese** [comment]
ctrl to pause chat is now a toggle.  Press it once to freeze.  Press it again to release.

**Comment by EhsanKia** [comment]
In hindsight, I could see this being a problem for when someone wants to copy something with ctrl+c

**Comment by dutchgecko** [comment]
For reference the offending commit is 2fb72f12
