### ISSUE TITLE
Some of my BTTV settings are missing.

### ISSUE THREAD

**Issue by Rokassss** [night/BetterTTV#2336]
Several days ago suddenly my bttv setting options gone missing. Here's an example how it should look like: http://prnt.sc/f0f5pt and here's how it looks now: http://prnt.sc/f0egp5 . I tried reinstalling BTTV, clearing cookies and cache, but it did not help. I'm using Google Chrome.

**Comment by Rokassss** [comment]
Very rarely, like 1 out of 10 times it goes back to normal until I open another stream

**Comment by thinkpad4** [comment]
You are part of the group that has been moved to BTTV v7 Beta

**Comment by night** [comment]
Some features have been removed, sorry.

**Comment by Rokassss** [comment]
Do you plan on adding some of them back? Like Blue Buttons for example I've really got used to it. Also there is no way to opt out of beta I assume?

**Comment by EhsanKia** [comment]
Blue buttons most likely not coming back, too much effort to maintain for something so frivolous. Not sure what you mean by time on chat, that should still be there?
