### ISSUE TITLE
Can't Disable Beta Option.

### ISSUE THREAD

**Issue by blehblahblue** [night/BetterTTV#2338]
I want to disable the beta option. After clearing the BTTV/Twitch cookies the beta option is actually disabled, but once I log in to my twitch account it gets toggled back on and it's turned back off if I log out. 

I've tried completely clearing all BTTV/Twitch cookies and reinstalling the extension multiple times.

**Comment by night** [comment]
You don't, sorry. v7 is being rolled out, currently 1 in 4 people have it.

**Comment by blehblahblue** [comment]
My chat is laggy though :(

**Comment by night** [comment]
In what way is it laggy? CPU usage is less than v6 by far. This is way lighter weight.

**Comment by blehblahblue** [comment]
Basically in any stream that has a fast moving chat, my entire twitch tab lags like it becomes unresponsive, not just the chat. Even stream itself freezes up if there's too much spam. 

This was never an issue for me before v7.0, and it's 100% not an issue with my PC hardware .
