### ISSUE TITLE
Bring Back the old Chat from V6.8 pls

### ISSUE THREAD

**Issue by Adgj533** [night/BetterTTV#2339]
please bring back old chat, this version 7 i selected remove the black background option but its not working. its so annoying seeing all the bits and "your friend has started watching"
thanks

heres a pic
http://imgur.com/dgokMAr

**Comment by night** [comment]
> please bring back old chat, this version 7 i selected remove the black background option but its not working.

This is new to v7. We are not yet choosing the change it.

> its so annoying seeing all the bits and "your friend has started watching"

Both already exist in v7
