### ISSUE TITLE
Copy emoticons in text selection to clipboard

### ISSUE THREAD

**Issue by acrisci** [night/BetterTTV#234]
When an emoticon is among the text in a selection, the text to produce the emoticon should be substituted for the emoticon picture in the clipboard when the selection is copied.

That way we could do copy pastas that have emoticons in them.

**Comment by vendethiel** [comment]
I don't think we could do that because of, well, how browsers work.

**Comment by acrisci** [comment]
I know how browsers work because I have worked on websites as part of my day job. This sounds totally possible to me. I know there is a clipboard api.

Would you accept pull requests if I get it to work in a reasonable way? Or are you just not interested in my feature requests?

**Comment by teak** [comment]
There is no "Clipboard API". Any site you have seen manipulating the clipboard is using a third party plugin such as flash player.

**Comment by acrisci** [comment]
@teak http://www.w3.org/TR/clipboard-apis/

    document.addEventListener('copy', function(e){
        e.clipboardData.setData('text/plain', 'Hello, world!');
        e.clipboardData.setData('text/html', '<b>Hello, world!</b>');
        e.preventDefault(); // We want our data, not data from any selection, to be written to the clipboard
    });

http://caniuse.com/#feat=clipboard

**Comment by vendethiel** [comment]
I see no reason to refuse a PR that adds it **and** teaches me something in the process :).
