### ISSUE TITLE
New chat messages sometimes don't scroll all the way down if they contain emotes

### ISSUE THREAD

**Issue by Flandre5carlet** [night/BetterTTV#2343]
Hey there,
I'd like to report an issue that's been observed by me and a few other friends who use BTTV (new v7 version).
When a new message appears at the bottom of the page, sometimes - not always - it does not scroll down all the way and gets "cut off", if that message contains an emote. Observed mostly with BTTV emotes, not sure if it happens with regular twitch emotes or FFZ emotes.
![43cb83e131130a09c5c9e452e49a7036](https://cloud.githubusercontent.com/assets/12631741/25459978/5ce32e42-2ae1-11e7-92ef-0f4f5ac857ca.png)

**Comment by night** [comment]
once you've loaded the emotes they work fine.. it's initial load where your browser doesn't have it cached and does not know the dimensions that it is an issue.. i think i want to make v3 of our api report dimensions again to get around this

**Comment by Flandre5carlet** [comment]
Hmm, that's odd. It keeps happening with BTTV emotes even after they've been loaded, on my end. I reckon reporting dimensions would fix that however, yeah.
