### ISSUE TITLE
Chat time stamp ahead one hour

### ISSUE THREAD

**Issue by Krzdaze** [night/BetterTTV#2344]
I've noticed my chat time stamps are off by an hour. The time stamps are accurate if I disable the BTTV extension and refresh the page.

![chattimestamps](https://cloud.githubusercontent.com/assets/28071162/25459908/46d0d6a8-2aa6-11e7-8d96-35eaf2e2db0b.png)

Browser: Chrome Version 58.0.3029.81
Extension: BetterTTV v6.8R55
OS: Windows 10 1703

Hopefully this is enough information but if it's not, let me know! Love the extension for Twitch!

**Comment by night** [comment]
upgrade to the beta in the BetterTTV settings.
