### ISSUE TITLE
The BTTV settings are unusable when accessing them from an embedded chat

### ISSUE THREAD

**Issue by Flandre5carlet** [night/BetterTTV#2345]
Hey there,

When accessing the BTTV settings from the dropdown menu in a chat that's embedded in a non-Twitch page, the settings menu opens centered over the chat and does not open in a separate popup. This makes the settings unusable and impossible to close as well, without refreshing the page.
![8f8276a86b3ebfb9838c9efc92392668](https://cloud.githubusercontent.com/assets/12631741/25460076/f54e2e8e-2ae1-11e7-9594-d53f28081ac8.png)

Note that the screenshot ends at the edge of my screen on the right (the embedded chat is on the right of the page, much like a standard twitch page) - while on the left, the embedded stream takes priority over the settings menu.

**Comment by night** [comment]
heh. we didn't port the embed/popup settings.. prob wont be a good experience until new settings ui is implemented
