### ISSUE TITLE
BTTV Highlighting On Caps/No Caps

### ISSUE THREAD

**Issue by firedingo** [night/BetterTTV#235]
Since twitch doesn't allow duplicate usernames and the only thing you can change is the capitalisation of the name. Would it not make sense for the highlighting to naturally assume firedingo & Firedingo are the same thing in this case?

**Comment by night** [comment]
Highlights are already not case sensitive.

**Comment by firedingo** [comment]
Well they were acting case sensitive for me which was quite weird.
