### ISSUE TITLE
BTTV beta version - 7.0.beta for Chrome

### ISSUE THREAD

**Issue by 33herms58** [night/BetterTTV#2354]
When I select **"Hide Bits — Bits can be annoying. Disable 'em in chat with this (we can't block 'em on stream, sry)"** - to **"ON"**, there is no effect in chat. I can still see bits, and bit badges. I mod for many channels and bits can be a bit spammy, so that makes my job that much more difficult on busy streams. Any solutions to this glitch/bug, help would be greatly appreciated! Thank you.

**Comment by night** [comment]
I cannot see the badges in v7, but the text of bits will remain in chat due to how we are hiding bits in chat messages (we hide the GIF, nothing more). The latter we are still brainstorming on. We don't want empty messages in chat, and performance of parsing chat lines matters.
