### ISSUE TITLE
Monospace font does not work anymore

### ISSUE THREAD

**Issue by AistoBasBistoC** [night/BetterTTV#2355]
I used to use the "monospace" font on my Twitch chat, but now it no longer works. I tried Lucida Console, but it looks weird without the monospacing and the bolded names don't look good at all.

**Comment by night** [comment]
It probably does work, but you may just need to increase the font size back to 13.333px since we changed it to 12px.

**Comment by AistoBasBistoC** [comment]
I have set the font size to 13.333, however the monospace font still does not work. Also, I am in the v.7.0.0 beta group, it seems.

**Comment by EhsanKia** [comment]
I've seen quite a few people report that custom fonts don't work, but it works fine on my end. Hard to debug what we can't reproduce the issue sadly. Do you have any other extensions installed?
