### ISSUE TITLE
Please bring back the <message deleted> in chat

### ISSUE THREAD

**Issue by popcornea** [night/BetterTTV#2360]

**Comment by EhsanKia** [comment]
it's still there?

**Comment by popcornea** [comment]
I cant see it in chat when someone gets timed out

**Comment by EhsanKia** [comment]
What happens to the message? Do they fully disappear? What are your options set to? There's two specific options for configuring this.

**Comment by popcornea** [comment]
They just turn grey, yesterday when someone was timedout there would be a message in chat showing who was timed out

**Comment by EhsanKia** [comment]
Yep that's an option, look at the settiNgs

**Comment by Nareese** [comment]
I think he is talking about the additional "...has been timed out [...]" and "...has been banned." messages, which are in fact no longer available.  Night mentioned in chat the other day that he thinks they are spammy.  ¯\\\_(ツ)\_/¯
