### ISSUE TITLE
Scrolling up chat

### ISSUE THREAD

**Issue by JustToReportChatProblem** [night/BetterTTV#2361]
Hi, I just wanted to report that scrolling up the chat no longer "Stops" the chat.

Before you could scroll up the chat and it'd stop scrolling down to the latest message. So if I wanted to read what person X said 30 messages ago it'd be close to impossible to find out.

This also makes it even harder to join in on the copy pastas.

I can't respond here because I apparently had to make an account here and I've never used this website so didn't feel like using real mail.

**Comment by night** [comment]
This is already fixed on our beta.
