### ISSUE TITLE
[New Feature] Pause chat scrolling on mouse hover

### ISSUE THREAD

**Issue by SYN1ST3R** [night/BetterTTV#2362]
This feature helps me a lot in moderating channels when the chat is moving quickly.

**Comment by voloshink** [comment]
You can use ctrl to toggle chat scrolling already

**Comment by SYN1ST3R** [comment]
I'm using Chrome v58 and I'm getting the auto scrolling bug which makes it
impossible to highlight a message in chat using mouse. Using Ctrl doesn't
help. I've switched to Firefox until it gets fixed. Also hovering over chat
(FFZ has this) is more convenient since I don't have to press another
button.

**Comment by LouieGreen** [comment]
Chrome v58.0.3029.81 here, CTRL works fine for pausing chat scrolling.

**Comment by night** [comment]
we finished out v7 rollout so this is already fixed.
