### ISSUE TITLE
BetterTTV can't load after login

### ISSUE THREAD

**Issue by gamania31610** [night/BetterTTV#2363]
Before I login,chat room will show"BetterTTV v6.8 Loaded",and the Chinese ID won't show their origin account

[http://i.imgur.com/r5awMFN.jpg](http://i.imgur.com/r5awMFN.jpg)

But after I login,BetterTTV doesn't load,and show the origin account,and when I use "Automatic Theater Mode",the chat room won't become black

[http://i.imgur.com/aY18POr.jpg](http://i.imgur.com/aY18POr.jpg)

**Comment by EhsanKia** [comment]
BTTV is actually loaded.

This is a mix of a bug and something that changed.

Bug: with automatic theatre mode, dark skin doesn't load properly, you have to leave and re-enter theatre mode.
Change: we show both localized and username now.

**Comment by gamania31610** [comment]
Can I only show localized ID but no username?
