### ISSUE TITLE
BTTV chat working everywhere except Dashboard and Popout 

### ISSUE THREAD

**Issue by Bundif** [night/BetterTTV#2364]
It's almost been around a month since I noticed that BTTV chat doesn't work in my dashboard when I'm streaming...I finally got fed up with it recently and started googling all the possible fixes to no avail. I DID however notice that it works when I'm in any other channel (in this case my own):
![bttv works](https://cloud.githubusercontent.com/assets/28159041/25542218/e1cc8a60-2c51-11e7-997e-82c4b9c83bab.PNG)

 but it does NOT work when in the dashboard AND when it's popped out! :(
![bttv doesnt work](https://cloud.githubusercontent.com/assets/28159041/25542220/e46d991c-2c51-11e7-85b2-68708d41de7b.PNG)

**Comment by night** [comment]
Simply enable the beta in the BetterTTV settings and all will be resolved.
