### ISSUE TITLE
White div in dark mode

### ISSUE THREAD

**Issue by xsarkor** [night/BetterTTV#2365]
White title element [Screen Shot](https://lh3.googleusercontent.com/-FNotzLPYFuM/WQOtrb1ljlI/AAAAAAAABY8/66MpjIGJ82o_HhmCt_PPSwj7vfG-XxRvgCHM/s0/chrome_2017-04-28_23-01-18.png)

**Comment by Fire0x** [comment]
My friend has the same issue and so do I (after looking at mine it happening to me as well)

**Comment by SaiyanOfDarkness** [comment]
Yeah I'm getting that too http://i.imgur.com/ITo2d1A.png

**Comment by Rezaldy** [comment]
To any dev seeing this post:

Apparently Twitch added a `.c-background` class to the `.metadata-box` div. It's got a nice `!important` rule in there that's overwriting the background. Fun times.

Also, there's a `.brick` class that adds a border that looks very weird, done by BTTV.

**Comment by EhsanKia** [comment]
Twitch definitely loves their !important rules...

**Comment by teak** [comment]
fixed in v7 branch

**Comment by Consti2tion** [comment]
I'm on v7 Beta and it's not fixed http://prntscr.com/f23pdw
