### ISSUE TITLE
their is a bug with darken mode

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2366]
their is a bug with darken mode that it will not darken the title only.. i cleared all my cache my third party app settings, anything that i could clear and it still there... please fix this 
![screenshot 21](https://cloud.githubusercontent.com/assets/19208617/25547608/253c900e-2c36-11e7-9920-5b8f8809cc39.png)

**Comment by Slikrick** [comment]
Duplicate of #2365
