### ISSUE TITLE
2 Bugs Reported

### ISSUE THREAD

**Issue by heartofbladez** [night/BetterTTV#2367]
Bug 1: Currently in Dark Mode but certain section is still in white (no way I found of fixing it)
Bug 2: I have the Host Button feature turned on but when I load twitch it doesn't appear (fixed by turning the feature off and back on again)
![bug](https://cloud.githubusercontent.com/assets/28165184/25548366/fe9e1aea-2c39-11e7-8918-8a2407e76b12.JPG)

*Update: Bug 2 was a issue on my end (I think)

**Comment by SaiyanOfDarkness** [comment]
I get he white Div area.. but not the host button issue.

**Comment by thinkpad4** [comment]
I'm getting the same as saiyan
