### ISSUE TITLE
Readding ability to set scrollback amount

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2369]
I like have it set to 300 lines not 150

Thanks

**Comment by EhsanKia** [comment]
Not possible with the new chat.

**Comment by thinkpad4** [comment]
Any chance of it returning in the future?

**Comment by EhsanKia** [comment]
Like I said, it's not possible on our end. It would be Twitch's call to add it.

**Comment by thinkpad4** [comment]
Wish Twitch hadn't screwed up so much that it forced you to used their default chat instead of the better chat we used to have.
