### ISSUE TITLE
Multiple Highlight Types (Different Colors & Sounds)

### ISSUE THREAD

**Issue by woo991** [night/betterttv#237]
I mod for a chat room and have problems with knowing what someone is talking about with highlights. I have people who talk to me personally and people who need mod support. i find it would be much more helpful if people say woo(my username) it would be red and if someone says mod/mods it would be green. or whatever i wanted it to be. having this would be helpful for mods and streamers.

**Comment by night** [comment]
fixed via 3a5bdd2f3b806bcf7c996a292b030a4fccf280d6
