### ISSUE TITLE
Right-Click custom timeouts interferes with copying a person's name

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2372]
I can't copy highlighted names from the chat cause the custom timeout thing pops up,

**Comment by EhsanKia** [comment]
ctrl+c?

**Comment by night** [comment]
why do you need to copy them is the better question

**Comment by night** [comment]
if it's just to paste into the textbox.. double-click to do that

**Comment by thinkpad4** [comment]
No it's to copy the name to paste in google for example
