### ISSUE TITLE
Title Bar not changing in dark mode

### ISSUE THREAD

**Issue by TheT0m** [night/BetterTTV#2373]
Title bar under the twitch stream is not turning grey when dark theme is used. 

![before](https://cloud.githubusercontent.com/assets/26510971/25552309/c245cbe8-2c5b-11e7-9cd7-52b6174706b1.png)
![after](https://cloud.githubusercontent.com/assets/26510971/25552310/c4a20cf8-2c5b-11e7-8483-a69875b8db5c.png)

**Comment by EhsanKia** [comment]
Please search before making a new post.

#2365
