### ISSUE TITLE
Dark theme does not use correct color for section directly below stream

### ISSUE THREAD

**Issue by shadowstrafe** [night/BetterTTV#2375]
The section directly below the stream video with the title, game, channel, view numbers etc. has a white background instead of a dark one when using the dark theme.

Browser: Chrome 57.0.2987.133 (64-bit)
BTTV: BetterTTV v7.0.0

![2017-04-29](https://cloud.githubusercontent.com/assets/13525017/25552664/687e49d8-2cd2-11e7-9677-cfef1bc03974.png)

Offending section from twitch's stylesheet

    .c-background {
      background: white!important;
    }

**Comment by EhsanKia** [comment]
Please search before making a new post.

#2365

**Comment by 12llcalvin** [comment]
This issue has not been resolved...
![image](https://cloud.githubusercontent.com/assets/9178398/25552882/0dff6faa-2c73-11e7-9ff9-897d1781eca3.png)

on BTTV v7 beta just Screenshoted this.

**Comment by EhsanKia** [comment]
Yes, the fix hasn't been pushed yet, but it's been reported 7 other times.

**Comment by 12llcalvin** [comment]
When will this fix be pushed?
