### ISSUE TITLE
How to install old verison?

### ISSUE THREAD

**Issue by Satont** [night/BetterTTV#2378]
No functions like in 6.8, i want to use old version :(

**Comment by ZaViN4C** [comment]
Yes, I miss the **chat interface** and blue buttons.

**Comment by voloshink** [comment]
this is not possible

**Comment by Satont** [comment]
so where is other funcrions? does it possible to return it?

**Comment by voloshink** [comment]
depends on what functions you are talking about

**Comment by ZaViN4C** [comment]
But it is possible to bring back the old chat interface? Like this: http://imgur.com/a/I5oyv ? (That's my only screen of the old interface)

**Comment by Satont** [comment]
so now i cant see timeouts and ban messages in chat
all nicknames have a background 
![img](https://satont.xyz/s/s76.png)

**Comment by night** [comment]
timeout and ban messages were removed from chat from non-mods as they serve really no purpose but add noise.

nicknames with backgrounds on light themes will be fixed to match the dark theme

v6 is not gonna be coming back, sorry friends
