### ISSUE TITLE
BTTV Beta

### ISSUE THREAD

**Issue by Afireee** [night/BetterTTV#2379]
The time I tried to click on the BTTV Beta, Some parts of the twitch chat settings is ruined (specifically the Font, Font Size, can't see the emote suggestions when pressing Tab and can't determine if one viewer got timed out or banned). I wanted to change it back to normal, but there is no button 

Edit: I tried clearing cache and cookies, but didn't work

**Comment by Nareese** [comment]
There is no beta anymore.  v7 is now the released version of BTTV.

The font and font size can both be set from the gear menu button (the old default size was 13.33, the new default is 12, FYI).  The tab completion suggestions popup has not been re-implemented.  It may be at some point in the future after all the bugs are cleaned up.  The timeout and ban messages were removed.
