### ISSUE TITLE
Autocomplete Missing

### ISSUE THREAD

**Issue by zerogott** [night/BetterTTV#2380]
Hey,
is the Autocomplete for Emotes/Name missing for someone else since v7?
Name autocomplete with @Name works fine :/

**Comment by Ludricio** [comment]
Having the same problem, it works using tab to cycle through them, they simply just won't show. It doesn't work with @Name for me tho.

I tried removing BTTV and it works correctly with vanilla, but returns as soon as I add BTTV again.

**Comment by night** [comment]
duplicate of #2288

also @ mentions do show the tooltip
