### ISSUE TITLE
JTV chat badges

### ISSUE THREAD

**Issue by Cephyric-** [night/BetterTTV#2382]
In 7.0.0 you removed the option to change mod, global mod, admin and staff badges into the JTV style badges. Is there is specific limitation in the new version that forced you to remove these, or did you just do it on a whim? I much preferred the JTV badges to the current Twitch ones

**Comment by voloshink** [comment]
we changed how we handle twitch chat, we no longer use our own chat which means features like alpha badges etc. are gone
