### ISSUE TITLE
Language tab 

### ISSUE THREAD

**Issue by XtrLoLz** [night/BetterTTV#2383]
Hi, I don't know if this is something you can do about, but when you have "Hide Recommended Channels" ticked there is no way to access the languages at the top unless you disable the feature.
Here with it ticked: http://i.imgur.com/XVETYW0.png
Here's without: http://i.imgur.com/TaGne0q.png
Definitely not a big deal but if it can be fixed, it would be cool.

Thanks in advance!

**Comment by night** [comment]
spoopy

**Comment by night** [comment]
actually, this is already fixed in twitch's new layout, so this is a wontfix
