### ISSUE TITLE
Bits badges appearing in 7.0 with FFZ installed

### ISSUE THREAD

**Issue by CaptainTeapot** [night/BetterTTV#2384]
Hello
I've noticed that Bits badges next to usernames appear despite being disabled in the BTTV settings in 7.0 when FFZ (1.56) is installed. This was not the case in 6.8.5.

**Comment by night** [comment]
cool I guess.. I wonder what they do to break it

**Comment by Brimcon** [comment]
Bits also appear in chat with 7.0.
