### ISSUE TITLE
Not getting comma

### ISSUE THREAD

**Issue by SweShine** [night/BetterTTV#2385]
When I write a name and press tab I get a space instead of comma that I used to get earlier and i dont get the bar with all the names :( . This really bother me! Can anyone please help me?

**Comment by night** [comment]
This might be intentional. @EhsanKia would know

**Comment by ThibaultVlacich** [comment]
The " i dont get the bar with all the names" is clearly a regression from v6.x
Now tab only cycles through names, before it was also showing a menu with all the possible autocompletes.

**Comment by night** [comment]
The tab completion popup is tracked at #2288

Further, this change appears to be intentional.
