### ISSUE TITLE
BTTV v7 white mode chat messages timeout/ban grey

### ISSUE THREAD

**Issue by corgiderp** [night/BetterTTV#2389]
For the white mode, difficult to see subscribers notifications, timeout/banned messages, and moderator actions due to grey text on grey background. Please restore color to the light theme.

Previous
![1](https://cloud.githubusercontent.com/assets/28211339/25561313/55c170ee-2d37-11e7-9c60-0ca8d0ddb0ef.png)

Current
![2](https://cloud.githubusercontent.com/assets/28211339/25561315/5f0b6cea-2d37-11e7-8c6a-4b2f9752672a.png)

Timed out message (v7)
![3](https://cloud.githubusercontent.com/assets/28211339/25561328/a4947ca2-2d37-11e7-9247-dde1d9482b7f.png)

**Comment by night** [comment]
Notification changes are intentional changes to match what Twitch is doing.

Timed out messages are completely readable on my screen.
