### ISSUE TITLE
Cooldown timer of slowmode in the "Chat" Button doesn't work anymore

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#2392]

**Comment by night** [comment]
this is removed in v7. if we get enough feedback that people want it back we'll reconsider adding it

**Comment by bluehazel123** [comment]
would like to have it back myself

**Comment by TobiasXy** [comment]
Me too. That was a super useful feature!

**Comment by NBruderman** [comment]
Of course I'm interested too, that's why I opened this in the first place :)

**Comment by DTM450** [comment]
Would like to have it back as well it was a useful feature

**Comment by night** [comment]
twitch now supports this natively
