### ISSUE TITLE
Hitting Tab > Enter too fast sends text before autocomplete has occurred

### ISSUE THREAD

**Issue by sielver** [night/BetterTTV#2393]
Especially annoying with emotes' autocompletion.

e.g. typing "Keep", then hitting Tab > Enter really quick will send "Keep" instead of "Keepo". Didn't happen before.

Sorry if this was already mentioned.

**Comment by night** [comment]
This unfortunately can't be fixed due to how text input changes work in Twitch's textbox. We are filling in the data synchronously, but Twitch is not loading it into their internal text area value in the same manner until a change handler is called, which is asynchronous.
