### ISSUE TITLE
Disable Frontpage Autoplay. 7.0.2

### ISSUE THREAD

**Issue by Reerso** [night/BetterTTV#2394]
Hi,  "Disable Frontpage Autoplay " does not work in ver 7.0.2.

**Comment by mattj456** [comment]
Works for me.

**Comment by Reerso** [comment]
Strange, on BBTV Discord there is a MOD with the same problem.

**Comment by Reerso** [comment]
The problem is only with Safari browser, it work fine with Chrome.

**Comment by Nareese** [comment]
Not a mod, but also doesn't work for me in latest Chrome (pure, literally nothing else loaded except BTTV).  It also doesn't work for me in a very old version of FF, but I'm always hesitant to report anything from that.  There is possibly some other undefined factor that is causing it to work sometimes and not others, but it's not Safari specific.

**Comment by night** [comment]
What version of the homepage? It works fine on the new one for me.

**Comment by Reerso** [comment]
Homepage? It is BBTV Ver 7.0.2 ind Safari browser.

**Comment by Nareese** [comment]
For me this was on the current/old version of the homepage in both cases.  Chrome gave me the new homepage briefly once last night, and then it went away again, and that's the one and only time I've seen it.

**Comment by Reerso** [comment]
For me it is on the new version.
You can get the new version back if you delete your twitch cookies.

**Comment by Reerso** [comment]
I also have the problem in old version twitch page.

**Comment by night** [comment]
this is the new homepage: ![](https://nightdev.com/i/ss-z0cv9vCad7GAyORryCl9KJjkB.png)

**Comment by Reerso** [comment]
Yes, and it is there Disable Frontpage Autoplay does not work..

**Comment by Reerso** [comment]
.
