### ISSUE TITLE
An option to click an online friend and go to their channel, rather than open a whisper chat

### ISSUE THREAD

**Issue by mattj456** [night/BetterTTV#2395]
Currently to visit a friend's channel you have to hover their name on the sidebar and click the small pop-out window with more information. I think it would be more useful to be taken directly to their channel by clicking their name. Not everyone may agree with this which is why I think it should be a menu option.

**Comment by night** [comment]
I think the majority of friendships are between non-broadcasters, so I think the correct click action would be a whisper window. However, if other people pile on in disagreement perhaps we can add this.

**Comment by Entrexx** [comment]
A little workaround for this:
Just hover over their name in the friends list and then click the banner inside the popup window. It will take you to their channel.

**Comment by mattj456** [comment]
I noted that already - it becomes tedious to navigate this way often. Possibly an option to switch the function of the two clicks would work well
