### ISSUE TITLE
[Feature Request] Dynamic word cloud view for Twitch chat

### ISSUE THREAD

**Issue by SheinH** [night/BetterTTV#2396]
# CrowdCast
If you aren't familiar with [CrowdCast](https://www.brutefarce.net/crowdcast/), it's an existing Chrome extension that displays what is essentially a dynamic word/emote cloud for phrases and emotes that are being repeated in Twitch chat. It looks like this:
![image](https://cloud.githubusercontent.com/assets/5853497/25567953/783565f6-2dc6-11e7-8627-bf4e3e61fcc4.png)
For streams with large numbers of viewers, Twitch chat can become a torrent of messages that move far too quickly to read on an individualized basis. For these streams, CrowdCast is very useful in gauging what people are saying as a collective. 
### Fullscreen mode
![image](https://cloud.githubusercontent.com/assets/5853497/25568018/f66aa70a-2dc7-11e7-9282-7c491d394b35.png)
There is also a fullscreen mode in which CrowdCast acts as a nice overlay for the stream, allowing users to see what the chat is saying without being too distracting or taking up real-estate. 

Other features are shown in the site for CrowdCast which I've linked to above.
# Reasons for Integration with BTTV
### Better execution
Though, the idea behind this extension is great, the execution is lacking. The existing CrowdCast extension is often buggy at times and clunky to use. It sometimes has the effect of causing twitch chat not to load. It also does not automatically change to its dark theme upon enabling theater mode on the base site. Finally, CrowdCast could use a better design for the word bubbles. I believe that you guys could take this existing idea and execute it far better. 
### Less extensions to install
Integration with your existing extension would also be tremendously useful. As a user, it sucks to have two extensions for watching Twitch when I have far too many installed already on Chrome. Having two extensions for Twitch also means having three separate menus for the base site, BTTV, and CrowdCast, making for a cluttered UI.
### More platforms
Currently, CrowdCast is only for Chrome, but it would be great for this feature to be brought to Safari, Internet Explorer, or Opera.

I hope you guys could take a look to see if including this feature is possible. Thank you for reading this.

**Comment by night** [comment]
We aren't able to integrate closed source code into our codebase like this, unfortunately. We also like to envision a world where multiple extensions can coexist without trampling on each others' features. This does something unique and I'd rather not replicate it unless provoked. We'll keep it in mind for the future but it's wontfix for now.
