### ISSUE TITLE
Emote autocompletion priority option removed?

### ISSUE THREAD

**Issue by ojji** [night/BetterTTV#2397]
I had this option on which allowed me to type 'Wu' and tab-complete to the WutFace twitch emote. Now instead I have to cycle through usernames until I find the right selection, which is extremely annoying to me especially in crowded chats where most likely there are users with names similar to Twitch emotes. Did I miss something or this option got removed completely?

**Comment by EhsanKia** [comment]
It will be back soon.

**Comment by Nokanah** [comment]
Mine worked fine until today, now have all sorts of issues on twitch.  Have to turn off html5 just to watch anyone and my bttv does absolutely nothing, when I go to the settings screen I have no options or settings to modify.

**Comment by Latias4Ever** [comment]
I'm having the same issues as Nokanah, my settings window is completely empty, and I can't autocomplete emotes, it just says "No matches".

Screenshot of the settings window: http://prntscr.com/f9v603
