### ISSUE TITLE
Double-clicking user's name adds it twice in chat box

### ISSUE THREAD

**Issue by touchnova** [night/BetterTTV#2403]
With BTTV v7, when I double-click a user's name to add them in a message reply, their name gets added twice in the chat box.  For example, it looks like:
**@UserNameXYZ, @UserNameXYZ**

I didn't experience this with previous versions and I've not seen any other comments about this issue, so I'm wondering if it's just on my end...if that's possible.  I'm using latest version of Firefox and BTTV v7.0.0 script loaded through Greasemonkey.

**Comment by EhsanKia** [comment]
Probably a bug, try refreshing for now, will try adding a check.

**Comment by touchnova** [comment]
Wow, seems to have worked.  I've been experiencing the double names for a few days...during that time I had refreshed, CTRL-F5'd, turned the script on/off and it was always adding two names on double-click.  However, since your comment it's properly adding just one name.  Thanks for your quick attention.

**Comment by night** [comment]
are you using any other extensions?

**Comment by touchnova** [comment]
Other extensions related to Twitch?  No.

**Comment by touchnova** [comment]
Can confirm I've not had issues with this for past few days.  Thank you for your attention and fix!
