### ISSUE TITLE
Image hover does not work

### ISSUE THREAD

**Issue by meinkrahe** [night/BetterTTV#2404]
Image hovering does not seem to work anymore whenever I hover over links that feature images or gifs such as puush or waa.ai.

**Comment by Nareese** [comment]
Further info on this.  I tested this against an imgur link (http://i.imgur.com/fNjkUSb.png) and each time I mouse into the link, I get two of this error in the console, presumably from the api call.

`Unhandled promise rejection Object { status=200, data=undefined}`

I didn't really know what an appropriate link to test the link_resolver api call, but presumably it's the same.

PS:  While you're in there fixing it, can you also re-add the option to turn it off (was chatImagePreview in v6).
