### ISSUE TITLE
Bug tab emotes

### ISSUE THREAD

**Issue by Fodastiicc** [night/BetterTTV#2405]
When i press tab to auto-complete an random emote like "Kappa" before this att i just write "Ka" ,press TAB and choose a "Kappa" from a list of emotes that start with "Ka" , but now just auto-complete in chat automatically, this is really bad.
And my emotes in private chat just disappear.
Desktop notifications disappear too.

**Comment by EhsanKia** [comment]
You can keep pressing tab to cycle through.
