### ISSUE TITLE
Chat colors not updating in theater mode

### ISSUE THREAD

**Issue by mgarlan** [night/BetterTTV#2406]
For the last few days the chat colors have stopped updating correctly when in theater mode (i.e. automatically changing to dark mode). As far as I can it tell, the symptoms are the same as in the closed issue #1220.

I'm currently using BTTV v7.0.3 in Chrome.

**Comment by mgarlan** [comment]
After a little more investigation, it looks like this only occurs when Automatic Theatre Mode is enabled. Manually changing the stream to theater mode seems to be behaving correctly.

**Comment by EhsanKia** [comment]
I've noticed that too. Definitely a big issue.

**Comment by night** [comment]
Can you explain chat colors?

**Comment by mgarlan** [comment]
Assuming that the Dark Theme is turned off, the expected behavior is for non-theater mode chat to have black text on white background, and when theater mode is turned on it automatically switches to white text on black background. In this case when it automatically goes into theater mode it is failing to change chat to the new colors. Additionally, the actual chat text appears to be somewhat grey, which makes it hard to read. As far as I can tell it looks exactly the same as the screenshot posted in issue #1220.

Manually exiting and entering theater mode seems to fix things, however one thing I've noticed is that once I do this the stream will be in permanent dark mode whether it's in theater mode or not, despite Dark Theme being turned off.

**Comment by EhsanKia** [comment]
Basically, automatic theatre mode kicks in too fast and dark mode doesn't have time to detect it.
