### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by AgadorSpartacus** [night/BetterTTV#2407]
First bug-  When I scroll down the viewer list the scrolling starts to automatically scrolls all the way down extremely fast and I can't stop it.

Second bug-  I was subscribed to a streamer but their emotes were locked as if I wasn't subscribed. I asked the streamer and they said it showed I was subbed.

Third bug- On the left hand side of the screen where it shows the channels I'm followed to, some do not show up. I have to click on the browse page, and look at the right hand side to see all of the streamers that I follow.

**Comment by AlcaDesign** [comment]
1. Duplicate #2269 
2.
    - Assuming that you **just** subscribed to that channel, you will need to reload once to visually have access to the emotes. That's how Twitch's system is set up.
    - You may be at the end of the subscription in which the API stops reporting you as being subscribed but another system has you on the grace period. You may still appear subscribed by the chat badge and emoticon access.
3. I would attribute this to a Twitch bug or otherwise and not BTTV.

**Comment by night** [comment]
Alca is correct.
