### ISSUE TITLE
User timedout/banned message not showing

### ISSUE THREAD

**Issue by jukeboxjedi** [night/BetterTTV#2409]
Whenever someone was timed out or banned, previously there was a message in chat saying so. Now it doesn't show up anymore.

**Comment by Furbeh** [comment]
Seconded

**Comment by night** [comment]
It shows for mods. We removed it because it was spammy for non-mods.

**Comment by Furbeh** [comment]
I, as a non-mod, enjoyed it due to being able to know how punishing timeouts are for others, without having to punish myself.

If it shows for mods already (I assume non-natively with Twitch), would it be reasonable to request it being an option for non-mods in the settings?
