### ISSUE TITLE
Audio Notifications

### ISSUE THREAD

**Issue by Rumik** [night/BetterTTV#241]
Hi there,

Can you please add audio notifications when someone sends a message? This would be really helpful for people with smaller channels who don't constantly have one eye on a separate screen with the chat in it, instead diverting the streamer's attention to the chat when needed.

Thanks!

**Comment by night** [comment]
This is not a feature we will be looking to implement, sorry. It would probably be far too annoying for most to use, and since the use case would apply to handful of users it isn't worth the time to make or maintain going forward.
