### ISSUE TITLE
chat delay appears to break message removing

### ISSUE THREAD

**Issue by 3ventic** [night/BetterTTV#2410]
Messages timed out by bots during 2-second chat delay aren't removed in my BTTV chat, vanilla one behaving correctly. See timed out zalgo perfectly visible in the chat vs. a manually timed out message (after delay) in screenshot 2.

![image](https://cloud.githubusercontent.com/assets/3998628/25684179/ac428870-3068-11e7-918b-9d8d2fa15731.png)

![image](https://cloud.githubusercontent.com/assets/3998628/25684159/8af618b2-3068-11e7-8908-3a8d9faa23e1.png)

Browser Name: Opera
Browser Version: 44.0.2510.1449
Browser Platform: Windows 10
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1449

Default BTTV settings, fresh installation of both browser and extension.

**Comment by EhsanKia** [comment]
Uh, I thought the messages weren't even sent to the user if they got timed out before the delay? Or are you a mod in that channel?

**Comment by 3ventic** [comment]
I am not a mod on the channel on this account (or staff/admin/glomo for that matter).

**Comment by night** [comment]
simple solution is throw the message delete to twitch if chat delay enabled

**Comment by MattiSony** [comment]
Any ETA on this? Seems like a pretty serious issue as malware links and other messages doesn't get deleted.
@EhsanKia the chat delay is handled client side i'm pretty sure FYI.
