### ISSUE TITLE
BTTV emote description cut off in chat replay

### ISSUE THREAD

**Issue by Runer112** [night/BetterTTV#2411]
Specifically in the chat replay for VODs (not the live chat for streams), the emote description that shows up when hovering over a BTTV emote gets cut off by just about any other page element, including other lines of text:

![bttv_2295](https://cloud.githubusercontent.com/assets/6608979/25627618/2e8f12aa-2f31-11e7-9d2c-9539aeb66147.png)

Originally mentioned in #2295, but this seems to warrant a separate issue.

**Comment by EhsanKia** [comment]
Hmm, tooltips in vods now show downwards... In vanilla twitch too.

I'm guessing this was actually a Twitch problem, and the way they fixed it is by making the tooltip open downwards instead... Wow.

**Comment by Runer112** [comment]
What is the resolution of this issue? It's not tagged with something like invalid/cantfix/wontfix, but there's also no linked commit fixing the issue.

**Comment by EhsanKia** [comment]
It was a twitch issue and they "fixed" it by making the tooltip pop under. Is that not the case for you?

**Comment by Runer112** [comment]
Yes, that is the case for me. Twitch's emotes use this "fix" so are fine. BTTV emotes do not use this fix, so are not fine, as demonstrated in the screenshot.

**Comment by EhsanKia** [comment]
Oh, right. My bad I misunderstood the issue, sorry.

**Comment by elevenletters** [comment]
Why is this closed? The issue still hasn't been fixed.

**Comment by night** [comment]
This is as good as it gets for now.

**Comment by Runer112** [comment]
Why can this not be fixed? The description hover works fine for BTTV emotes in live chat, so BTTV emotes don't inherently have a problem. And it works fine for non-BTTV emotes in chat replay, so chat replay doesn't inherently have a problem. Combined, it seems rather unlikely that there is an inherent problem preventing this from working.

**Comment by night** [comment]
The issue was fixed, and broke with a Twifch update. It's refixed. Open a new issue in the future...
