### ISSUE TITLE
[Request] "Always" Load More followed channels

### ISSUE THREAD

**Issue by Loomies** [night/BetterTTV#2412]
I don't care for the social features and always get annoyed having to click Load More to see more than my top 5 followed channels on the left side of the bar. I tried to look in BTTV settings but didn't see it

**Comment by zokkix1** [comment]
I'd also love to see this feature added!

**Comment by crucia1** [comment]
yeah, it's very annoying, please add this function

**Comment by night** [comment]
this was added on the new twitch site
