### ISSUE TITLE
Chat doesn't show when localsub is enabled

### ISSUE THREAD

**Issue by clarityat3am** [night/BetterTTV#2416]
Noticed today that my own chat doesn't show when localsub is enabled even though I'm a sub in the channel I was using it in. Chat shows just fine when it's not enabled, though.

**Comment by Nareese** [comment]
Tested this, same result.  Note that the test does get sent to the channel, it just doesn't show for the sender when localsub is enabled.

**Comment by clarityat3am** [comment]
Came back to check on this. I'm using localsub again today and still don't see my own chat. :(

**Comment by Nareese** [comment]
The fix mentioned above has been submitted, but not yet accepted by night, merged in, and released.  It will be fixed in an upcoming release once night approves it.

**Comment by clarityat3am** [comment]
Ah, ok! Didn't know the process. Thanks for clarifying!

**Comment by EhsanKia** [comment]
Yeah, sorry about the delay it's been a very busy week and there's a lot of small issues related to the new version. Once we iron out all of them hopefully it should be a much smoother ride.
