### ISSUE TITLE
File Use

### ISSUE THREAD

**Issue by moosepaw** [night/BetterTTV#2425]
Is there an easy way to make this extension used in file mode instead of http protocol? It seems the img src's inherit the 'file:', which breaks the links.

**Comment by night** [comment]
What do you mean?

**Comment by moosepaw** [comment]
Let's say I type Kappa into google search, the extension works just fine. But say I save the outer html of that page just loaded, copy it into a text file and save it as html, then load it using the same browser, the img src links for the emotes get prefixed with file: . So instead of //bbtve...dsjdj you get file://bbtve...dsjdj, which is a broken link. 

Is there an easy fix for this? Thanks for any response.

**Comment by night** [comment]
I think you have the wrong extension. This extension only works on Twitch.
