### ISSUE TITLE
Setting for different language

### ISSUE THREAD

**Issue by Kirayao** [night/BetterTTV#2432]
Currently in the setting, we could set the font type and font size.
But it doesn't apply for all languages, seems like only to ASCII only?

![image](https://cloud.githubusercontent.com/assets/1212154/25861164/d9e6ce48-351e-11e7-9fa6-7bc474147e10.png)

**Comment by Kirayao** [comment]
Sorry, I just tried with a Chinese font and it applies to both English and Chinese characters.
However, could we could a separate setting for different condition?

**Comment by night** [comment]
unfortunately fonts do not always support all characters, so your operating system will fill in the missing characters with a different font. we have no way to detect that or separate them, sorry.
