### ISSUE TITLE
[Feature] Option to remove the hideous new Twitch layout :|

### ISSUE THREAD

**Issue by Ninja101** [night/BetterTTV#2433]
Any chance we can get the option to set the old layout back? This new layout... 😢

**Comment by voloshink** [comment]
doubt it

**Comment by VirtuallyJesse** [comment]
I don't see why there can't be an option to hide the top bar & show it on mouseover. FFZ did it because the people wanted it, why not BTTV?

**Comment by night** [comment]
I'm personally not sure why people dislike the new layout, so I'm not in support of this. I get people dislike change, but I'm surprised people knock this new design that's actually decent.
