### ISSUE TITLE
[Bug] Hide Recommended Channels

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2434]
So I have Hide Recommended Channels turned on, and it works for both Recommended Channels and Channels Your Friends Like.

However sometimes when refreshing they still appear despite having the option enabled.

**Comment by KTScientist** [comment]
I have the same problem ,every time i open a stream i have to check and uncheck Recommended Channels

**Comment by night** [comment]
duplicate of #2399
