### ISSUE TITLE
The emote M&Mjc  it does not work

### ISSUE THREAD

**Issue by kamikaze19** [night/BetterTTV#2438]
The emote M&Mjc  it does not work

**Comment by infintieice** [comment]
Yes it does.

http://i.imgur.com/c1V0IX4.jpg

Clear your cache, maybe?

**Comment by kamikaze19** [comment]
http://imgur.com/a/DiJ8L

I see it but in the global chat it does not. On all channels

**Comment by night** [comment]
it's a BetterTTV emote.. whatever system the broadcaster is using is not BetterTTV.
