### ISSUE TITLE
[Bug] colon (punctuation) in chat overlapping name.

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2442]
The : at the end of chat names is overlapping with the last character of each name.  And it does not do it with BTTV disabled, so I believe this is a BTTV issue.

http://i.imgur.com/wYGrWw1.png

**Comment by koitsu** [comment]
Can confirm this (i.e. it's not you).  This appears to be caused by the following CSS at https://cdn.betterttv.net/css/betterttv.css?v=7.0.3 --

```
.chat-line .colon, .conversation-chat-line .colon {
    margin-left: -3px;
}
```
Related HTML is <span class="colon">:</span>

Removing the margin-left rectifies the issue.
