### ISSUE TITLE
All my emotes disappears

### ISSUE THREAD

**Issue by Fodastiicc** [night/BetterTTV#2443]
i have no bttv emotes! 
http://prntscr.com/f6w8zu
and yes, i have gifs emotes on, and this channel have this emotes

**Comment by Nareese** [comment]
The BTTV API server is currently down.  Not sure whether it is a server problem or whether it's just maintenance.  It is a temporary problem, but some BTTV features like emotes and link hover preview will be unavailable until the server is back up.

**Comment by night** [comment]
We were performing maintenance. This is since resolved.
