### ISSUE TITLE
Getting blank lines in chat instead of the link to clips

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2449]
I have Hide Chat Clips — Hides clips embeds in chat turned ON but I should still be seeing the link to the clip at least.  Using the latest Chrome

**Comment by night** [comment]
we simply hide the clips.. twitch removes the link from the message itself.

**Comment by thinkpad4** [comment]
Something changed between when you added the option to hide the chat clips and now.  I remember the links still showing.  Twitch must of changed YET another thing
