### ISSUE TITLE
Dark mode black name issue

### ISSUE THREAD

**Issue by PaganKim** [night/BetterTTV#2453]
The issue im having might not be a bug , but more so something that feels clunky to  me , i have my name set to full black or #000000 on hexadecimal , but in dark mode it  is more like a light grey and that frustrates me because its not what i set it to , i assume its so its easier to see my name in chat and its supposed to be a QOL type of thing , but in the future could there be an option to toggle this feature in the settings because its inconvenience

**Comment by night** [comment]
duplicate of #1017
