### ISSUE TITLE
Support for Yandex.Browser user agent on download page

### ISSUE THREAD

**Issue by resure** [night/BetterTTV#2454]
Hi. Looks like betterttv download page doesn't correctly handles user agent of Yandex.Browser (it's pretty popular browser in Russia, based on Chromium). In fact, it works perfectly with extension for Chrome, so it should be safe to just treat Y.Browser as Chrome at that page.
Examples of UA: 
- `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 YaBrowser/17.3.1.840 Yowser/2.5 Safari/537.36`
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.137 YaBrowser/17.4.1.718 Yowser/2.5 Safari/537.36`.

**Comment by night** [comment]
this should be fixed
