### ISSUE TITLE
Twitch streams fail to load video content with BTTV enabled on Firefox 53.0.2 (64-bit)

### ISSUE THREAD

**Issue by Uro1** [night/BetterTTV#2455]
With BTTV enabled Twitch streams fail to load on Firefox 53.0.2 (64-bit) also latest 32bit Firefox fails to load Twitch streams with BTTV addon enabled.

I have tried refreshing Firefox (64bit & 32bit, seperately), reinstalled all plugins one by one, checking for issue and as soon as BTTV is added and enabled streams' video content does not play.

Disabling BTTV in Firefox Addons fixes this issue.

**Comment by night** [comment]
check your console for errors, and then post to us the error

**Comment by Uro1** [comment]
Do you want the whole console's output from a twitch page?

**Comment by Uro1** [comment]
Here is everything in the console window upon a refresh:

JQMIGRATE: Migrate is installed with logging active, version 1.4.1  global.js:4
JQMIGRATE: jQuery.browser is deprecated  global.js:4
console.trace():  global.js:4
document not ready yet, trying again in 500 milliseconds...  global.js:16
console.trace():  global.js:4
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!  lost_in_house
Cannot play media. No decoders for requested formats: application/vnd.apple.mpegURL, application/vnd.apple.mpegURL, application/vnd.apple.mpegURL, application/vnd.apple.mpegURL  lost_in_house
TypeError: asm.js type error: arguments to a comparison must both be signed, unsigned, floats or doubles; double and fixnum are given  player-core-min.js:1:237209
[Emote Menu]  "(v2.1.4) Initial load on https://www.twitch.tv/lost_in_house"  global.js:16

**Comment by night** [comment]
> Cannot play media. No decoders for requested formats: application/vnd.apple.mpegURL, application/vnd.apple.mpegURL, application/vnd.apple.mpegURL, application/vnd.apple.mpegURL lost_in_house

is the reason it doesn't load.

We don't touch the video player in such a way that would cause this error, and unfortunately since I cannot reproduce this error I have reason to believe it's not our extension causing it.

**Comment by Graeme-L** [comment]
Experiencing the same problem with the same error message on the console on Windows 10/Firefox 64-bit 53.0.2. It only occurs with HTML5 video. Switching to Flash bypasses the issue.

Black screen with BTTV and HTML5. Disabling BTTV and refreshing the page, HTML5 video plays as normal.

**Comment by Tiuqu** [comment]
> is the reason it doesn't load.

no it's not, upon disabling bttv and refreshing, the same error shows in console, yet video plays normally

additionally, when bttv is active, the video box shows the live dot like normally it would, but there are no quality options

and finally, trying to open video stats with bttv active creates the following console error:

> TypeError: this.br is null[Learn More] player-core-min.js:1:886756
> 	PlayerCore</</f.prototype.nn https://cvp.twitch.tv/1.8.2/player-core-min.js:1:886756
> 	PlayerCore</</f.prototype.getPlaybackStatistics https://cvp.twitch.tv/1.8.2/player-core-min.js:1:884576
> 	value https://player.twitch.tv/js/player.js:22:927
> 	o/c.getStats https://player.twitch.tv/js/player.js:30:18364
> 	Oe https://player.twitch.tv/js/player.js:20:17730
> 	Ie/< https://player.twitch.tv/js/player.js:20:18129
> 	i/< https://player.twitch.tv/js/player.js:8:5258
> 	c https://player.twitch.tv/js/player.js:59:4363
> 	i/</</< https://player.twitch.tv/js/player.js:80:9045
> 	n/</</< https://player.twitch.tv/js/player.js:79:10725
> 	value https://player.twitch.tv/js/player.js:33:3680
> 	t/< https://player.twitch.tv/js/player.js:33:2109
> 	dispatch https://web-cdn.ttvnw.net/global.js:2:23479
> 	add/g.handle https://web-cdn.ttvnw.net/global.js:2:20206
> 	n https://cdn.betterttv.net/betterttv.js:317:7107

**Comment by Tiuqu** [comment]
nvm, deleting twitch cookies seems to solve all issues
