### ISSUE TITLE
Twitch HTML5 not working in Firefox

### ISSUE THREAD

**Issue by jnnash** [night/BetterTTV#2457]
The video quality options do not seem to load and HTML5 playback doesn't start.
Everything else appears to be working fine.

http://imgur.com/a/MrOor

Firefox 53.0.2 (64-bit)
BTTV 6.8.5

**Comment by xgerhard** [comment]
Looks like duplicate of #2455 
Try clearing Twitch cookies

**Comment by jnnash** [comment]
Ah, didn't see that issue when I did a search.
Seems to have solved it though so thanks for pointing me to it!
