### ISSUE TITLE
T-Shirt Merch Panel

### ISSUE THREAD

**Issue by Sleekness** [night/BetterTTV#246]
The T-Shirt Merch Panel on dark theme is fixed only on user channel, but not on the profile page.
User channel (fixed) - http://i.imgur.com/d45bdR6.png
User profile page (not fixed) - http://i.imgur.com/2gCOvPs.png
@matthewjk123 or whoever was fixing this panel

**Comment by matthewjk123** [comment]
@Sleekness Thanks! I'll make the change right now! :D

**Comment by vendethiel** [comment]
247

**Comment by teak** [comment]
Can some please fix the miss aligned bar at the bottom :P
