### ISSUE TITLE
BTTV doesnt let streams load

### ISSUE THREAD

**Issue by TheTopManager** [night/BetterTTV#2461]
![black screen](https://cloud.githubusercontent.com/assets/28788824/26216224/35d2385e-3bfb-11e7-891b-b0f790863508.png)

This is what it looks like when i have BTTV on, but as soon as i disable the extension the stream starts working again. I tried disabling all settings one by one and even with everything turned off it still wont load the streams.

**Comment by night** [comment]
dup of #2458
