### ISSUE TITLE
BetterTTV is now incompatible with uc browser?

### ISSUE THREAD

**Issue by kenny6131** [night/BetterTTV#2462]
Hi.
When betterttv is enabled on my browser (uc browser) i just cant see or hear anything in twitch. 
In google chrome this is not a problem but i love UC.

**Comment by EhsanKia** [comment]
Never heard of UC browser, but there's currently an issue with Firefox + html5 + BTTV. We're looking into it but it doesn't affect everyone. Seems to be an experiment Twitch is slowly rolling out to some people.

**Comment by kenny6131** [comment]
I see. Well thanks. I just want you know about this issue cause uc browser is not so popular.
Thanks again.

**Comment by night** [comment]
dup of #2458
