### ISSUE TITLE
still wont highlight when my name is called out

### ISSUE THREAD

**Issue by BlueKnightGamingTV** [night/BetterTTV#2475]
i recently changed my url on twitch and it wont show my name highlighted when someone mentions me
but when i uninstall bttv it works fine

**Comment by MellowNebula** [comment]
You just need to update your highlights list in BTTV settings with your new name....

**Comment by BlueKnightGamingTV** [comment]
where do i go to change that?

**Comment by Nareese** [comment]
On the chat "gear" menu, "Set Highlight Keywords".  Put your name in there.

**Comment by BlueKnightGamingTV** [comment]
Thank you very much!!
