### ISSUE TITLE
BetterTTV Emotes

### ISSUE THREAD

**Issue by GoldAssasson** [night/BetterTTV#2478]
I have the betterTTV emotes on but it is not showing, and even refreshed to make sure and its still not there.
![bug](https://cloud.githubusercontent.com/assets/28216963/26388720/9bae5ddc-401b-11e7-84f0-2e930a14cb30.png)

**Comment by night** [comment]
The emote menu option is called "Emote Menu"

**Comment by GoldAssasson** [comment]
ok thank you I didn't see it last time I installed betterTTV
