### ISSUE TITLE
Emoticon menu doesn;t appear

### ISSUE THREAD

**Issue by Humanitarian1** [night/BetterTTV#248]
Sometimes the emoticon icon disappears. BTTV is loaded and I can access the settings and access all of the other BTTV features but there's no emoticon menu to click on

**Comment by night** [comment]
I cannot reproduce this issue. Make sure you have no other conflicting Twitch add-ons installed. If you don't, please provide more info (browser, OS, where this happened, if it's reproducible [and how to reproduce it])
