### ISSUE TITLE
@MyName is my old acc name

### ISSUE THREAD

**Issue by DovahTiim** [night/BetterTTV#2484]
I changed my name in my twitch account and if someone send a @myname message its not notifice me but if they use my old name like @oldname its notifice me

**Comment by Nareese** [comment]
Enter your new name on "Set Highlight Keywords" on the gear menu.

**Comment by DovahTiim** [comment]
thank you ^^
 

Gesendet: Samstag, 27. Mai 2017 um 18:47 Uhr
Von: Nareese <notifications@github.com>
An: night/BetterTTV <BetterTTV@noreply.github.com>
Cc: DovahTiim <dovah.tiim@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [night/BetterTTV] @MyName is my old acc name (#2484)


Enter your new name on "Set Highlight Keywords" on the gear menu.
