### ISSUE TITLE
Enter not working properly

### ISSUE THREAD

**Issue by elisorri** [night/BetterTTV#2489]
Pressing enter in chat just brings me to the next line in the chatbox instead of sending the message

edit: refreshing did not fix it but ctrl+f5 did

**Comment by swiftyspiffy** [comment]
Are you certain you weren't holding shift when you hit enter?

**Comment by Antzer** [comment]
Just noticed this myself, just happened to me

**Comment by wozp22** [comment]
okay control and F5 didnt work for me either, that usually solves problems with twitch but not this time, any more help/advice anyone?

**Comment by Kyzachable** [comment]
I am having this problem as well.

**Comment by wozp22** [comment]
I just disabled this extension for now and that sorted it, hope you can fix this soon betterttv :/

**Comment by night** [comment]
It works on my machine. If Twitch is rolling out code removing this then it's Twitch breaking it, not us. You should try with BetterTTV disabled to confirm.

**Comment by Kyzachable** [comment]
I disabled it in my chrome extensions and it stopped happening, then when I re-enabled the BTTV chrome extension it started happening again. I even disabled everything in my BTTV settings and it still happened. What else could be causing it?

**Comment by ceriath** [comment]
referring to this thread and also personal experience it really seems to be bttv 
https://redd.it/6dwxh2

**Comment by night** [comment]
Well we haven't shipped an update for 4 days and there are no error logs happening massively right now, and coupled with the fact that I cannot reproduce this issue it's likely another issue. Try disabling other extensions you have installed. Perhaps one of them updated, breaking the functionality.

**Comment by Antzer** [comment]
Reproduced with franker turn off and fixed 100%

**Comment by night** [comment]
Closing this since it's confirmed not a bug on our end.
