### ISSUE TITLE
Anon Chat

### ISSUE THREAD

**Issue by VanDC** [night/BetterTTV#2492]
When I have Anon Chat on, on Twitch then I can be seen in the viewing list anyways. I closed Twitch yesterday with it on, and had it on when I turned on the first stream, but people could see me. I haven't had 'Share my activity' on, only 'Anon Chat', but apparently it didn't work.
Please fix it :)
Thank you.

**Comment by Sonder13** [comment]
I'm having the same issue as well. Thanks for the work towards a quick fix!

**Comment by night** [comment]
duplicate of #2402
