### ISSUE TITLE
Notification popup issue

### ISSUE THREAD

**Issue by aznxknight** [night/BetterTTV#2495]
I am using Bettertwitch with opera browser and I come across a notification popup issue that i cannot get rid of. It tells me to: "Follow and get notified when "X" stream is live" - Turn on notifications.
It appears on the top left corner and it stays there indefinitely with no way to get rid of it. The only way to make it disappear is to refresh the stream but this is annoying because it pops up every 20 minutes or so.
If i turn off bettertwitch the notification still appears however it auto disappears by itself. But with BT turned on it doesn't auto turn off like it's supposed to.
Is there anything I can do about this?

**Comment by night** [comment]
The notification only shows when a stream is offline, not live. It doesn't auto disappear for me with BetterTTV disabled.
