### ISSUE TITLE
Darkmode not working on notifications

### ISSUE THREAD

**Issue by holypalaswe** [night/BetterTTV#2497]
Fresh install of BTTV on a fresh Chrome-browser, darkmode not working on the notifications-tab and not on the pulse chat-box on pulse (twitch.tv frontpage), background is white with text that is bright and hard to see. Screenshot below.

http://i.imgur.com/KwgN7FW.jpg

**Comment by night** [comment]
There is a PR open addressing this already https://github.com/night/BetterTTV/pull/2491
