### ISSUE TITLE
Comma after tab complete when the name is first still a possibility to bring back?

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2498]
It is proper grammar, Night even said so https://github.com/night/BetterTTV/issues/499

Thanks

**Comment by deniz87** [comment]
Can't wait for this. Also pressing tab few times doesn't work anymore. It just picks the first person on the tab list. This turns me off and its been ages this issue hasn't been fixed...

**Comment by night** [comment]
this wont be making a return
