### ISSUE TITLE
Ability to view a chat of whitelisted users

### ISSUE THREAD

**Issue by alca019** [night/BetterTTV#2500]
I would love an option to see chat messages only from white-listed users.  I'm thinking of using this in channels with thousands of viewers and unreadable chats, where blacklisting or hiding certain users isn't feasible.

**Comment by night** [comment]
This isn't really feasible due to how we filter chat. Twitch renders 150 messages at a time and we simply filter by hiding messages you don't want to see. A majority of hidden messages would render you an empty chat.
