### ISSUE TITLE
Can't distinguish between watched and unwatched VODs with Dark Theme

### ISSUE THREAD

**Issue by sooqua** [night/BetterTTV#2502]
This issue has been raised before #1083 but it was misunderstood and closed.
The problem is that, even with the vanilla theme, sometimes it's hard to distinguish between watched and unwatched VODs if the thumbnail is dark enough. But with the dark theme, it's almost impossible!

**Comment by sooqua** [comment]
I think the right solution would be to add a "watched" watermark.

**Comment by lackofwords** [comment]
A quick fix is just to make the opacity darker.
or just adjust it to whatever you feel like, even toss an img to overlay it if you wish.

just append to the src/css/betterttv-dark.css
```
.video-watched .meta, .video-watched img {
	opacity: .15;
}
```

**Comment by night** [comment]
this isnt an issue on the new twitch site
