### ISSUE TITLE
Screen is black for BetterTTV

### ISSUE THREAD

**Issue by DrMicro** [night/BetterTTV#2503]
Screen is completely black on every live stream.

![a2cdccb8dfa278743ecaa9edf9e0484b](https://user-images.githubusercontent.com/29263613/26902262-de314df4-4bd8-11e7-9ce9-bd6ff21397f4.png)

![bcc21c5133a6a55df3b2dfa6ce30dad8](https://user-images.githubusercontent.com/29263613/26902274-e92e6a70-4bd8-11e7-84d3-c636cc58f6e4.png)

**Comment by Nareese** [comment]
I cannot reproduce this in latest Chrome.  If you have not already done so, please verify that the problem does not occur with BTTV disabled.  If it still happens with BTTV (and any other twitch modifying extensions you might be using) disabled, please provide additional details:  Browser and version, OS and version, BTTV version (from BetterTTV Settings->About, not the extension version), and any information from the console log that might be helpful.

**Comment by DrMicro** [comment]
I have just updated chrome and it's fixed now. It wasn't only on BTTV so it was on normal Twitch as well, but thanks for the help and I'm sorry if i wasted your time.

**Comment by Nareese** [comment]
No problem, glad you got it resolved.
