### ISSUE TITLE
Twitch & BTTV Overlay clash

### ISSUE THREAD

**Issue by Tritoneko** [night/BetterTTV#2505]
To Whom It May Concern,

I am getting a terrible overlay when using BTTV in chrome right now where the extension overlay seems to just move upwards into the right-hand corner instead of actually being a 'pop-up' window. This is terribly annoying as it The logout button right on top of my username. 
I'm unsure if this is just a new overlay form from twitch or a bug with BTTV's overlay, but if you might be able to look into that that would be greatly appreciated. 

![2017-06-08](https://user-images.githubusercontent.com/24821960/26956066-12136d22-4c70-11e7-9b47-8a510176e794.png)

Cheers.

**Comment by night** [comment]
I have no idea what "overlay" means, but we don't have an overlay

**Comment by Tritoneko** [comment]
If you don't know what overlay means then you cannot speak for the extension in saying you don't have one. It could very well be another word for something you do indeed have.
Regardless, as I've said before, it must be a twitch update causing the problem I've encountered.
Thanks for your assistance.
