### ISSUE TITLE
Twitch Prime Loot

### ISSUE THREAD

**Issue by BootieTrap** [night/BetterTTV#2506]
Twitch Prime Loot notifiacation isn't showing up. Unable to claim Twitch Prime Loot

**Comment by Nareese** [comment]
Ensure that you don't have the "Hide Prime Promotions" option enabled.  If you don't, please make sure that your Chrome is fully up to date.  Go to Menu->Help->About Google Chrome to force an update check.

**Comment by BootieTrap** [comment]
Hide Prime Promotion was the problem. Thanks
