### ISSUE TITLE
Can't Chat/Emotes Don't Appear

### ISSUE THREAD

**Issue by CharlieWil524** [night/BetterTTV#2507]
I can't send messages in chat that I've typed. When I hit enter nothing happens (whatever I typed stays in the "Send a Message" box at the bottom of twitch chat, doesn't dissapear and doesn't send). I disabled BTTV and I could chat while it was disabled, but the issue came back as soon as I reenabled it.
Also, no BTTV emotes appear in chat,  the option to enable them in BTTV settings doesn't appear, and they don't appear in the emote menu (only prime. global, and favorite emote categories). Idk if I somehow messed this up, but I don't remember changing anything in the settings or doing anything that could cause either of these bugs.

**Comment by Nareese** [comment]
Please sure that your Chrome is fully up to date.  Go to Menu->Help->About Google Chrome to force an update check.  Updating Chrome has resolved this issue for everyone else who has reported this problem.

duplicate of #2504

**Comment by CharlieWil524** [comment]
That fixed it thanks!
