### ISSUE TITLE
Dark Mode - Whisper list text hard to read

### ISSUE THREAD

**Issue by dansa** [night/BetterTTV#2508]
![image](https://user-images.githubusercontent.com/5786317/26995859-64ea5a60-4d6f-11e7-8e29-26a2627842b8.png)

Probably caused by color declaration of following block (overwriting/disabling it solves the issue)

```
.conversations-content {
    color: #19171c; 
    height: 4.2rem;
    position: absolute;
    bottom: 0;
    left: 1rem;
    right: 1rem;
    z-index: 100;
    pointer-events: none;
    padding-right: 4rem;
}
```
With declaration removed;
![image](https://user-images.githubusercontent.com/5786317/26996012-2b0ea0ca-4d70-11e7-8ee4-19b82e01fafc.png)

**Comment by gamernation89** [comment]
i am confused is this something i have to do to fix the issue or is this something on the devs side that they have to fix them selfs because its really an annoying bug right now
