### ISSUE TITLE
hide followed channels

### ISSUE THREAD

**Issue by gamernation89** [night/betterttv#2509]
can you make a feature that i can hide the followed channels because i want to see my friends list only and not the channels i follow when i am watching a stream and i go to my following section i want to to check on that... i would really appreciate this

**Comment by ericchase** [comment]
I liked this idea, so I added it to my script.

To implement it, I created an array to hold the names of live streams, and removed any hosted streams with matching names.

**Comment by night** [comment]
Thanks for the request. As of 2022 Twitch no longer has a friends list, so this feature request no longer appears useful to implement.
