### ISSUE TITLE
feature request (sub-only)

### ISSUE THREAD

**Issue by toorbak** [night/BetterTTV#251]
I'm gonna get right to it:
○ An option that let's us to turn the chat into sub-only without being the broadcaster.
To clear up: option that let's you to only see the subscribers in chat even when it's not sub-only.
(if you are gonna make this happen, please put the toggle in the options menu under the chat and not in the BTT main option menu.)

**Comment by teak** [comment]
This is already possible. Type '/localsub' and '/localsuboff' to turn it back off..
