### ISSUE TITLE
Channel emotes are usable in group chats

### ISSUE THREAD

**Issue by Lordmau5** [night/BetterTTV#2511]
When you open a Twitch chat, for example CohhCarnage's chat, you can see his channel emotes.

However, if you now switch to a group chat, those emotes are still loaded in for you and you can still use and see them in that group chat.

GIFV showcasing how to reproduce it (Might need to scroll out a bit to see the full height of the GIFV):
http://i.imgur.com/8o3YUW2.gifv

I only had BTTV installed for this. No FFZ or FFZ:AP.

**Comment by night** [comment]
eh, i don't think i care enough to fix this. group chat is a pita to support, nobody uses it, so i dont want to
