### ISSUE TITLE
Prime loot "Crown Button" on top right disappears

### ISSUE THREAD

**Issue by Altentio** [night/BetterTTV#2514]
I don't know if it's bttv problem or chrome, but whenever i switch to firefox where i have only ublock running, the prime loot icon is there. On chrome the prime loot crown icon shortly appears and then disappears. I don't really have any other extensions running that affect twitch other than BTTV so I am reporting this here first-hand. here is a list of my Chrome extensions: Twitch Now, Magic Actions for YT, BTTV, Ublock

**Comment by Nareese** [comment]
Ensure that you have the "Hide Prime Promotions" setting turned off.  If it is off and still not showing up, ensure that your Chrome is fully up to date (current version is 59.0.3071.86, Menu->Help->About Google Chrome to check and force an update if needed), and disable all other add-ons, especially Twitch Now, which certainly qualifies as  "an extension that affects twitch".  If it still does not show at that point, report back.
