### ISSUE TITLE
Auto-join chat on message send when anonymous

### ISSUE THREAD

**Issue by TimeBomb** [night/BetterTTV#2515]
If the user has anonymous chat enabled, it would be great if there was an option to automatically join chat when you type a message in chat. I want to stay anonymous most of the time, but when I type a message in chat, that means I'm okay with joining chat. Losing my message and having to type `/join` before being able to chat is a bit cumbersome. Thanks.

**Comment by night** [comment]
You can press up to get your most recently sent message.

**Comment by TimeBomb** [comment]
Cool, though auto-joining would be a nice feature [request] for intuitivity's sake. Cheers.
