### ISSUE TITLE
No BetterTTV Emotes Setting...

### ISSUE THREAD

**Issue by DerBrunoBaumann** [night/BetterTTV#2518]
I cleared Cache, reinstalled BTTV but the emotes are gone..
maybe I am too f**king tired to get it up I am not getting it fixed.
Could someone help me?

**Comment by Nareese** [comment]
Ensure that your Chrome is fully updated (latest version is 59.0.3071.86, Menu->Help->About Google Chrome to check and force an update if needed). This has resolved these issues for everyone who has reported them.

Duplicate of #2504

**Comment by DerBrunoBaumann** [comment]
Thank you very much! That helped indeed! 
Never would've figured..
