### ISSUE TITLE
Autocomplete Issues (CTRL+TAB)

### ISSUE THREAD

**Issue by ryanbraganza** [night/BetterTTV#252]
https://community.nightdev.com/t/autocomplete-issues-ctrl-tab/3163

While using firefox I have the habit of using CTRL+TAB to cycle through tabs, but recently this problem started to haunt me: If I CTRL+TAB out of a Twitch Chat it still acts as if I simply pressed TAB, even if I have not entered a single letter, cycling through namesat the same time I leave the tab. Could this be corrected so it ONLY cycles if you use TAB or SHIFT+TAB?

**Comment by night** [comment]
A pull request was accepted that improves the functionality of the tab completion, and allows you to disable the visual suggestions that popup. The feature will be pushed live probably later today.
