### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by telobeans** [night/BetterTTV#2522]
After downloading I no longer can talk in chat unless I use an emoticon.

**Comment by night** [comment]
sounds like you have a conflicting extension. disable all other browser extensions.

**Comment by telobeans** [comment]
idk if I ever replied to you.

"Yes that worked! I am impressed by your quick diagnosis! " - is what I
would have said back then if I replied in a timely manner.


 Thank you for your timely answer. BTW bttv is still great, thank you for
that too.
