### ISSUE TITLE
Notification when your prime sub is available again

### ISSUE THREAD

**Issue by marci4** [night/BetterTTV#2529]
Hello everyone,
Right now Twitch is not notifiying you when your free twitch prime sub is available again.

It would be great, if BetterTTV could add a notification for that case.

It would also be great to remind someone for some time, e.g.
*Remind me when this streamer goes live again to use my prime sub
*Remind me in 3 days

Greetings
marci4

**Comment by night** [comment]
unless it broke, the sub button will have a crown instead of a dropdown to represent that it's available for use.

**Comment by marci4** [comment]
To be honest I did not realize this!

Since there is an indication, even a bad one, feel free to close this thread!
