### ISSUE TITLE
gif emotes

### ISSUE THREAD

**Issue by MathiasDC** [night/BetterTTV#2530]
The gif emotes are not showing anymore and the setting is gone from the list.

![image](https://user-images.githubusercontent.com/12392042/27319237-b40ec512-5590-11e7-899f-206ec9b91a5a.png)

**Comment by MathiasDC** [comment]
the normal bttv emotes aren't working as well, i already reinstalled bttv and reconnected on manage.betterttv.net, i also tried clearing my cache but nothing worked so far.

**Comment by Stoupedog** [comment]
Make sure your browser is fully up to date then try again
