### ISSUE TITLE
[Request] Prime Subscription Reminder

### ISSUE THREAD

**Issue by MisterRabbitHead** [night/BetterTTV#2532]
Hello, i have an idea! 

Can you add "prime subscription reminder" to BTTV? So that people will know when their sub runs out soon in a specific channel. Because i know worst part of prime subs for a streamer is viewers not resubbing/forgetting to renew their sub.

I admire your work and wish you the best.

**Comment by night** [comment]
We replace the sub button dropdown icon with a crown when your prime sub is available to use. It's subtle but noticeable if you know to look for it.
