### ISSUE TITLE
Strawpoll spits JSON into box after voting

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2533]
![](http://i.imgur.com/VfwN7lR.png)

Voting works correctly as far as I can tell but it shows JSON instead:

```javascript
{
    "success": "success",
    "returnUrl": "/embed_1/13269828/r"
}
```

**Comment by night** [comment]
i mean this sounds like a them problem, not an our problem.

**Comment by AlcaDesign** [comment]
Oh, is that in the embed?

**Comment by night** [comment]
you should report this to them i guess?

**Comment by branchard** [comment]
We may be able to use their API instead of using embed poll.
https://strawpoll.zendesk.com/hc/en-us/articles/218979828-Straw-Poll-API-Information

**Comment by night** [comment]
Their API is for creating polls, not voting. Embedding is the only way.

**Comment by branchard** [comment]
Ok :confused:
