### ISSUE TITLE
Exclude /clear from saving chat history?!

### ISSUE THREAD

**Issue by Lalikos** [night/BetterTTV#2537]
Hey there,

when someone is getting purged/timed out etc. their messages getting deleted, but viewers with BTTV still have the chance to see them. This usually wouldn't be a problem, unless someone is giving away a users/streamers private information. Purging them attracts some viewers attention to this specific message. With BTTV saving the chat history, BTTV users will have the chance to click on it to see, what they said. This can lead to unpleasant remifications. It would be awesome if mods could use the /clear command to clear the chat for EVERYONE! Hopefully you can come up with a solution.

**Comment by night** [comment]
We won't support clearing chat, sorry. It used to be abused back in the day by mods to silence opinions, so nobody can abuse it any longer since it doesn't clear for people using the extension.
