### ISSUE TITLE
lines with emotes added by clicking on emote menus don't get added to history

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#2538]
When sending a line of chat text that contains emotes that were entered by clicking on them in the emote menu (either twitch's or BTTV enhanced menu, although the enhanced menu seems less reproducible at times), the line is lost from chat history, and up arrow will not recall it.  If the emotes are typed manually or tab completed, the history recall works fine.  The line is not added even if there is other plain text on the line with the emotes.  Just clicking anything on the emote menu triggers the behavior.

I have no idea whether this is a twitch chat history thing or something BTTV handles, but after a user reported it in discord and another user managed to figure out how to reproduce it, I am passing along the report and letting you guys figure out if it is something that can be fixed.

**Comment by Antzer** [comment]
Looks like twitch did this themselves

**Comment by night** [comment]
im not able to reproduce this now

**Comment by Nareese** [comment]
still 100% reproducible for me with latest Chrome and latest (git current master/unreleased) BTTV. /shrug

**Comment by night** [comment]
then you may have another extension interfering.. the way the code works is it appends to history the chat line on send.. so i see no reason it would break like this anyways

**Comment by Nareese** [comment]
No other extensions.  Literally a pure Chrome install with only BTTV loaded.

**Comment by night** [comment]
then your steps to reproduce were not clear. provide step-by-step instructions

**Comment by Nareese** [comment]
And... mechanic's syndrome!  Actively verifying my reproduction steps (making sure I'm not presuming anything) revealed the problem.  The problem actually has nothing to do with emotes.  The problem only occurs when you click the "Chat" button to send.  If you hit enter, it works fine.  Since my hand is already on the mouse when clicking in emotes from the menus, I'd always just moved down and clicked the "Chat" button, rather than the extra step of having to click in the text area and hit enter.  It also happens if you type the emotes, or any other text, for that matter, by hand, and use the button to send (which, why would anyone do that, but it further verifies that it is using the button that is the problem).

Sorry for the confusion.

For clarity sake, exact reproduction steps:

1/ Enter any text or click on emotes from menus to create a line of text and send it with the "Chat" button
2/ up arrow to recall it.  Fails.

**Comment by night** [comment]
please open a new issue for this since the chat button isnt triggering onsendmessage
