### ISSUE TITLE
Stream wouldn't load, Unknown displayed

### ISSUE THREAD

**Issue by Jonuik** [night/BetterTTV#2545]
JQMIGRATE: Migrate is installed with logging active, version 1.4.1
web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:15 document not ready yet, trying again in 500 milliseconds...
player.js:1 Uncaught (in promise) undefined
api.betterttv.net/2/channels/five0antho Failed to load resource: the server responded with a status of 404 ()
web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:4 console.trace
i @ web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:4
five0antho:1 Uncaught (in promise) Object
web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:15 [Emote Menu]  (v2.1.4) Initial load on https://www.twitch.tv/five0antho
video-edge-c2b314.lax03.hls.ttvnw.net/v0/CoUCRp9_7iWj7SxihM0gxJWpyM2PxLDJ8T…Pvz_c8p1v2ZCZD0EhAuKuOvFot0Ygbl0cfyBMdDGgxo2Bf0kTL304mLZ_M/index-live.m3u8 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
video-edge-c2b314.lax03.hls.ttvnw.net/v0/CoUCuGskQZGgMELhiNMfyibV8FxYvW_Vl4…rm6yuFAmcgwf5toEhA5R9ZTe3qmjpA1tK63hJtIGgwpyLlt_Auz_jyGevM/index-live.m3u8 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
video-edge-c2b314.lax03.hls.ttvnw.net/v0/CoUC2gQWLwLv27qlEgz4aMWH80eKIfBaz8…t4fv2SJ-Ym1Ob_vEhDoae2vNALlII9f7809qlFsGgwuWXRrqNc3B-DLfv0/index-live.m3u8 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
video-edge-c2b314.lax03.hls.ttvnw.net/v0/CoUCkp_OzexaJhHWKhE4dlyVtLVMGpMvZC…MpGPrZ4ogUoJ1A5EhAjK2ag4X83-Ifq4DuxFfiMGgxm-8z5a1QMdHqefwc/index-live.m3u8 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:4 console.trace
i @ web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:4
get @ web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:4
(anonymous) @ web-cdn.ttvnw.net/global-c031c658ad0eba9a6677edd67c9451aa.js:9
a @ cdn.betterttv.net/betterttv.js:315

**Comment by night** [comment]
you are having issues loading twitch. contact twitch support.

**Comment by Jonuik** [comment]
The issue was with connection to Bttv so I figured I would send it to you guys if there was a fix.
