### ISSUE TITLE
twitch chat no longer in 24h timestamps

### ISSUE THREAD

**Issue by PhoenixTV1337** [night/BetterTTV#2548]
my twitch chat timestamps used to be 24h time but now its 12h for some reason and its getting kinda annoying

**Comment by 28Black** [comment]
Same here. I used to have time stamps in 24h format, now I noticed that they're in 12h format which is kind of annoying! Hopefully the dev can fix it soon.

**Comment by night** [comment]
we now rely on native twitch chat instead of rolling our own.. twitch changes too quickly and chat kept breaking. for that reason this is no longer possible.

**Comment by 28Black** [comment]
This is understandable, keep up the good work!
