### ISSUE TITLE
unable to see one or more chatters

### ISSUE THREAD

**Issue by 0Pinger** [night/BetterTTV#2549]
noticed today that two people were chatting and I couldn't see one of them, if I loaded twitchtv on another browser[waterfox] without BTTV I could see the second chatter.

I then unloaded BTTV and refreshed the stream and could see him again, re-enabled BTTV and I could see the chatter finally

using:
Opera 46
BTTV extension from https://nightdev.com/betterttv/

only had 2 black listed phrases,  !enter !gamble
blocked user was: rmkz

**Comment by night** [comment]
We dont have any code in our codebase which would cause this to happen unless you're blacklisting what they're saying.
