### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by CravingGaming** [night/BetterTTV#255]
I noticed the notifications went from white to black and showed up in the top left instead of the bottom right. Any way we can choose which one we prefer? I used to have the old white one in the bottom right and it moved to the top left which my computer screen is sadly cracked and I don't even see those notifications anymore. I would just like to suggest a button to choose which one we would like to use.

**Comment by Sleekness** [comment]
You can select which notifications you want to have. Go to BTTV settings > Desktop Notifications (Off = notifications in the top left, On = Desktop Notifications, The 'White' ones. 
It changed because maybe you deleted your browser cookies which resetted your BTTV settings.

**Comment by CravingGaming** [comment]
Yeah I just turned them off & on and found out the problem. Turns out
Google Chrome was denying them. Must not have seen it before, but thanks
for the help anyways.
