### ISSUE TITLE
Badges & emotes outside of message history box

### ISSUE THREAD

**Issue by xgerhard** [night/BetterTTV#2551]
Mod card chat history shows badges & emotes outside of the box on light theme.

![](http://i.imgur.com/pWikBoz.gif)

**Comment by night** [comment]
seems fine on my machine:

https://nightdev.com/i/ss-Rk5QrG2dcUctv5X55j2jNvaqg.png
https://nightdev.com/i/ss-DhaDQRm5aL4e5qLwhIv6JLOUO.png
