### ISSUE TITLE
12-hour timestamps

### ISSUE THREAD

**Issue by Matihood1** [night/BetterTTV#2555]
I can't seem to set the timestamps to use the 24-hour. My browser locale is set to Polish and Polish only and in Poland we use 24-hour clock (in the Chrome browsing history the 24-hour clock is used as well) so it's certainly not it.
http://i.imgur.com/V4IbL0k.png - My browser locale settings
http://i.imgur.com/R8Y5egZ.png - Chrome browsing history

**Comment by Nareese** [comment]
Duplicate of #2548.

BTTV version 7 uses twitch's native chat, so the timestamps are whatever twitch's chat supplies, and BTTV no longer offers the option to override them.

**Comment by Matihood1** [comment]
Thanks for a quick response. So I guess it's Twitch's fault. Topic can be closed.
