### ISSUE TITLE
Completion Tooltip not being dark while using Dark Theme

### ISSUE THREAD

**Issue by AlucardX8** [night/BetterTTV#2557]
Hello, I'm not sure if it's only me, or maybe it's just the Firefox [54.0.1 (32-bit)] BTTV Add-on that has this issue, but when using the Completion Tooltip along with the Dark Theme, the box is white instead of dark (just as it used to happen with the Notifications menu)

![white completion tooltip](https://user-images.githubusercontent.com/30022007/27994529-bc35702c-6474-11e7-96b0-d68df16b6128.png)

**Comment by dansa** [comment]
Not a BTTV issue, it's FFZ overwriting BTTV Dark mode styling here unfortunately.

**Comment by AlucardX8** [comment]
Ah, thx for the answer, guess I'll wait for an update then.
