### ISSUE TITLE
Chat shows room selection on channel load.

### ISSUE THREAD

**Issue by aroboto** [night/BetterTTV#2559]
Chrome Version 59.0.3071.115 
BetterTTV v7.0.18

When opening a channel the chat automatically loads to the room selection menu instead of showing the chat. Cleared cache, cookies and reset bttv to default settings.

**Comment by night** [comment]
works fine on my machine. try disabling all other browser extensions

**Comment by aroboto** [comment]
Disabled all other extensions, have even reinstalled Chrome and installed BTTV as the only extension. Getting the issue logged in and logged out.

I can reproduce each time by going to the directory and refreshing the page, go to a game category, click on a channel and I get the room selector instead of chat. Same if I go to a channel from my follow list.  I don't get the issue if I don't refresh. 

But if it can't be reproduced by others ¯\_(ツ)_/¯

**Comment by laurencee** [comment]
I have the same issue, disabled BetterTTV and everything works as expected. Turned off every setting in BetterTTV and it still pops up the chat room window every time the chat initially loads.

**Comment by night** [comment]
it seems twitch changed the design for this and it's broken in this way. it must have been a slow rollout.

**Comment by CREED122** [comment]
Yes I can conform this bug! it happens to me too! I had W7 with lots of problems so I thought it just one of many I have, then I installed fresh W10 ( with formatting everything) and still get the same problem! so it is diffidently from BETTERTTV.
