### ISSUE TITLE
Turning Emotes Off Doesn't Work

### ISSUE THREAD

**Issue by CandiceJoy** [night/BetterTTV#256]
The title says it all.  I turn off BTTV emotes and yet they're still there.  I turn them back on, still there.  I turn them back off, still there.  I literally cannot get rid of them without uninstalling the extension.  Tested on 2 separate computers in Chrome.

**Comment by night** [comment]
Turn what off exactly? What are you trying to removed, and what are you toggling. There are multiple settings that can sound like they do what you want, but they don't.

**Comment by CandiceJoy** [comment]
The little monkey emotes and the trollface :D, etc.  It's the BTTV Emotes.  The setting that says, you know, "use our emotes".  Here is a screenshot.  Notice that the settings window was opened after typing those things in chat (and I disabled the Turbo emotes before I did the test).  I cannot make those emotes go away and return to the original Twitch emotes no matter what I do.

**Comment by voloshink** [comment]
Have you tried the "Robot Emoticons" toggle? The emotes you described are not bttv emotes, they are just replacements for the built in twitch emotes.

**Comment by CandiceJoy** [comment]
Oh.  Might I suggest renaming it "JTV-Style Emotes" instead of that, then?  Having the default of changing the emotes and being brand new to Twitch, this was not at all remotely apparent to me.

**Comment by voloshink** [comment]
The whole settings page will be getting a rework, so the options will probably be renamed to better reflect what they actually do during that rework.
