### ISSUE TITLE
Video is off center?

### ISSUE THREAD

**Issue by MrTommo999** [night/BetterTTV#2561]
so i updated Windows 10 today, and it seems that BTTV isn't happy, it keeps off centering it. i can't see why or how it is doing it, but i disable BTTV it seems to fix it. but then i can't watch it due to no black theme :( has anyone else got the problem, or know a fix?

**Comment by night** [comment]
That's a Twitch bug. You can verify it by changing to a different language than English with BetterTTV disabled.

**Comment by MrTommo999** [comment]
how do i that?

**Comment by MrTommo999** [comment]
so to point out THIS DOESN'T WORK. i changed my language into EVERYOTHER one and it STILL doesn't work. so any more ideas? i still think its something to do with the Stop Net Neutrality rules as it doesn't do this in full screen and theater mode. sorry i can't keep it in those modes to just to watch streams -_-

**Comment by night** [comment]
The point is that it's a twitch bug, not our bug, so it's not our problem.

**Comment by MrTommo999** [comment]
so its your software with twitch thats causing the bug, so how it is NOT your problem? this feels like abit lazyiness, its like a modder for minecraft blames the minecraft software for his mod not working as a they added a line of text -_-

**Comment by night** [comment]
If you reread the first reply, it happens on default Twitch on any non-english language. All BetterTTV does it remove the bar, which causes the same effect as using a different language on Twitch. It's not our bug, it's not our code causing the bug.

**Comment by EmilPrusaczyk** [comment]
Is there a way to disable this functionality in bttv so that I can just make the bar display: none with stylish?

**Comment by dansa** [comment]
The bar is already made display: none; through the close button added by bttv though.

**Comment by SW1FT** [comment]
@EmilPrusaczyk For now, you can set:
```
.player { bottom: -45px; top: 20px; }
```

Sadly, this adds black bars to the bottom and top of the video, but at least you get the full screen without the part top cut.
