### ISSUE TITLE
Player too high

### ISSUE THREAD

**Issue by xsarkor** [night/BetterTTV#2562]
Look 
[SS](https://lh3.googleusercontent.com/-PlsaU-Mcnhs/WWZi6mS7SQI/AAAAAAAABjQ/an3jH-kdYYElfa_8TBJaMxwlpy3qxYZfACHMYCw/s0/chrome_2017-07-12_19-56-41.png)

**Comment by night** [comment]
https://github.com/night/BetterTTV/issues/2561
