### ISSUE TITLE
Localized names and @mentions

### ISSUE THREAD

**Issue by James2Because1WasTaken** [night/BetterTTV#2563]
Is there a chance that messages containing mentions with my localized username would be highlighted as if I was mentioned with my original username? Here's what I'm talking about: 
Highlighted:
![1](https://user-images.githubusercontent.com/30127684/28136496-00de60f6-675b-11e7-8083-b136f5a2c7ab.png)
Not highlighted:
![2](https://user-images.githubusercontent.com/30127684/28136497-00def8c2-675b-11e7-9d2f-723246913b9b.png)
I understand that this might not be possible due to whatever reason, I just want to ask.

**Comment by aroboto** [comment]
Have you tried putting your localised name in the highlight keywords option? You'll find it on the cog wheel menu in chat.

**Comment by James2Because1WasTaken** [comment]
@aroboto I haven't. Thank you so much, I didn't even realise there was such an option! But having it added by default might be a good function.
