### ISSUE TITLE
resub and subbing 

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2566]
i just noticed this and i was wanting to know if this is a bug with the white layout in the dark mode 
![screenshot 179](https://user-images.githubusercontent.com/19208617/28192367-b73f3d18-6803-11e7-9cf8-3594360bd2ec.png)

**Comment by Nareese** [comment]
Yup, confirmed.  They screwed this up when they rolled out the net neutrality stuff.  When they rolled that back last night, they briefly fixed this, but now it's broken again.

The offending style from their application.css
```
.special-message .system-msg {
    background: #efeef1;
}
```

Note that in theater mode, their dark theme overrides that with:
```
.theme--dark .special-message .system-msg {
    background: #201c2b;
}
```
