### ISSUE TITLE
Tab emote completion

### ISSUE THREAD

**Issue by Russiandat** [night/BetterTTV#2568]
When attempting to Tab complete an emote, it searches for usernames and doesn't even attempt to complete the emote. This is after I cleared my cache and cookies, and readjusted my settings to before. Tab complete emote prioritization IS enabled through the BTTV settings ( http://i.imgur.com/4yAxHuz.png)

Here is what it looks like when I press TAB to complete an emote in chat.  http://i.imgur.com/RDBc2mt.png

To me, it looks like it is attempting to search for user names.

**Comment by Nareese** [comment]
Twitch made a change to their code today which removed a function that a lot of emote related functions depended on.  This has broken tab completion for emotes, and the enhanced emote menu, both of which rely on that removed function.  Night and the developer of the emote menu are both aware of the issue and will be looking into it.  This is a fairly major change of functionality on twitch's side though, so I can't estimate how long it will take to figure out a new method of doing what these features need.

**Comment by Russiandat** [comment]
Ahh that is most unfortunate, but Thank you for the timely and informative reply!
