### ISSUE TITLE
Follower Count in Moderator Cards

### ISSUE THREAD

**Issue by RuEmileo** [night/BetterTTV#257]
I have a question or I guess a suggestion. You know when you click on someones name in chat and you see the name/follow/message/block etc is there anyway to add in a followers/following count on to that through BTTV? The reason I asked is because sometimes when I mod for streamer I check for bots during giveaways and wanted to know if it was easier to click their name and see how many people they are following to help determine if they were a bot. 
![f292a5eb027ed1ff490e6bfa2eb653f1](https://cloud.githubusercontent.com/assets/11223923/6407850/bc243e26-be16-11e4-84a9-7f3011121cc7.png)

**Comment by night** [comment]
Well, it would probably look a lot better than that screenshot, heh.

The purple "Message" text is a bug, and shouldn't be happening. It's barely readable, and should be a light grey. I'll open a separate issue about that.

**Comment by RuEmileo** [comment]
Lol well thank you for the consideration

**Comment by night** [comment]
Closed by #516
