### ISSUE TITLE
Hide whisper box should also remove "player-whispers-padding" style

### ISSUE THREAD

**Issue by Dwedit** [night/BetterTTV#2575]
Currently, twitch has the whispers box add padding to the video frame.  Sometimes I like to shrink the player window, and the whispers box padding just adds wasted space.

In the HTML, there's this tag:
div id="player" class="player player-whispers-padding theme--dark"

We want to eliminate the "player-whispers-padding" class, or at least remove the actual padding from the CSS style.

Chrome's inspector says the CSS looks like this:

.app-main.theatre .player-whispers-padding {
    margin-bottom: 4.2rem;
}

EDIT: Seems that removing the margin also breaks playback controls, unless you also hide the element with class "conversations-wrapper".

**Comment by night** [comment]
We don't like to mess with the player sizing anymore, sorry. Twitch keeps doing funky stuff with its positioning and anytime we touch it something breaks soon thereafter. In other words, it's a rabbit hole and is why we stopped doing chat resizing.
