### ISSUE TITLE
[Feature request] Save settings data internally

### ISSUE THREAD

**Issue by incognidoer** [night/BetterTTV#2581]
I would like to use betterttv while browsing in incognito-mode.
Saving settings in cookies makes this impossible (well, annoying enough to have to import every time).
Include twitch cookie settings (stream quality, window size, etc.) while at it ;)

Thank you

**Comment by night** [comment]
it's simply not gonna happen, sorry. we're not gonna produce and maintain extensions for every browser's storage formats.. localstorage is a standard and it's good enough
