### ISSUE TITLE
Scrollback feature

### ISSUE THREAD

**Issue by Nathsters** [night/BetterTTV#2582]
I remember there used to be a scrollback amount feature in bttv in chat settings. Is this planned to be implemented again since the rework if so and if not can it be? Thanks.

**Comment by Nareese** [comment]
BTTV version 7 depends on Twitch's chat for as much as possible for reasons of maintainability, and Twitch does not expose any way for us to change the scrollback amount, so unfortunately, this feature is no longer possible.
