### ISSUE TITLE
Host Button not Appearing on my Stream

### ISSUE THREAD

**Issue by tombadguy** [night/BetterTTV#2585]
Hey there -

I don't know if this is an issue with BetterTTV or Twitch, but on my stream, the Host button does not show up. The Share button is there, but no Host button. The Host button appears on other streams, just not mine. If this is something with BetterTTV, can you help me out?

Thanks!

- Tom

**Comment by AlcaDesign** [comment]
How would you host your own channel? If you just wish to _unhost_ on your channel, type `/unhost` in the chat

**Comment by tombadguy** [comment]
To clarify, there is no Host Button for viewers to click to host my channel, in other words, other people can't see a Host Button on my stream. I have the BetterTTV Host Button turned on.

**Comment by AlcaDesign** [comment]
You having the button enabled only affects your view of Twitch, not the view for other users. BTTV is purely an extension for your browser and there is only minimal connection between BTTV users, namely emotes and definitely not the appearance of host buttons. You are misunderstanding what that setting is. If you wish your viewers to also see the button, recommend them to install BTTV and enable the feature or inform them how the `/host` command works normally.

**Comment by tombadguy** [comment]
So host buttons only appear if you actually have BTTV installed, gotcha. THAT'S all I needed to know.
