### ISSUE TITLE
Line on the right side of chat (via Dashboard)

### ISSUE THREAD

**Issue by RFGaming101** [night/BetterTTV#2586]
Just noticed this recently, but the chat via the Dashboard has a white line in dark mode.
https://i.gyazo.com/7185a0f5b7f175bdf04d2cdeb7d87cb2.png

**Comment by RFGaming101** [comment]
On Google Chrome 59.0.3071.115, 64-bit, Win10

**Comment by mattj456** [comment]
The textbox for "Channel Feed" is white as well, should be dark
