### ISSUE TITLE
Show Deleted Messages?

### ISSUE THREAD

**Issue by shiiroo** [night/BetterTTV#2588]
The show deleted messages is broken, Cause when someone message gets removed it shows the `<message deleted> `

Please fix. Thank you :)

**Comment by Nareese** [comment]
Two questions:

1/ Are you seeing `<message deleted>` or `<deleted link>`?  (You probably said, but unless you enclose it in back quotes ( ` ) like I did above, you can't type things inside angle brackets... it disappears).  If necessary, leave the brackets off your response to make sure it shows up.
2/ Which browser are you using?

**Comment by night** [comment]
im not able to reproduce this. it may be an additional extension you have installed conflicting
