### ISSUE TITLE
Chat button doesn't trigger onsendmessage

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#2591]
Re-opening a previous issue re: chat history being lost, with an updated explanation.

When entering text or emotes into chat and sending them by clicking on the "Chat" button, the history for the line is lost and cannot be recalled with up-arrow.

Per night's comment in the previous thread, "the chat button is not triggering onsendmessage."

previous issue for reference. #2538

**Comment by night** [comment]
this is no longer an issue on the new twitch site
