### ISSUE TITLE
Show Deleted Message isn't working

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2595]
Unless it was just a rare occasion, someone's link was remove by Nightbot, and I have Show Deleted Messages on but it still said <message deleted>

**Comment by night** [comment]
Hooking into Twitch for showing deleted messages has a race condition and as such is best effort. If it fails to hook in then it wont show deleted messages. Browsers which are slower to render like Firefox seem more susceptible to this than others, like Chrome.

**Comment by retsamyar** [comment]
reopen. or another extension will

**Comment by night** [comment]
this shouldn't be an issue now with new twitch
