### ISSUE TITLE
Chat on Safari Mac with version 7.0.25 doesn't work correctly

### ISSUE THREAD

**Issue by DeanDavis** [night/BetterTTV#2596]
Chat seems to work fine when loading the page but when I tab off then tab back to Twitch the chat immediately stops working properly.

All messages are blank likes and it doesn't auto scroll. If I manually scroll up I see chat messages from the time I tabbed off but all new chat messages are all blanks.

Safari version 10.1.2 (12603.3.8)

Chat worked fine on Aug 1, 2017 so I assume this issue was introduced with version 7.0.25.

Just checked the commits and saw Aug 2, 2017 commits had fixes for dark mode. I am running dark mode. So, I turned off dark mode and chat works fine.

Sorry to keep updating but I was able to get chat to malfunction with dark mode turned off. But, I can't currently recreate the steps to do it. If I can recreate consistently I'll update again.

Next update: Completely uninstalled BTTV and after some time the normal Twitch Chat bugged out in a similar way. So that this point I have to believe Twitch made some chat modification that are broken on Safari.

I would table this "bug" until Twitch gets it act together on Safari.

![screen shot 2017-08-02 at 10 15 09 am](https://user-images.githubusercontent.com/12413449/28877886-bba8e742-776b-11e7-8330-c2ecafe25507.png)
![screen shot 2017-08-02 at 10 14 54 am](https://user-images.githubusercontent.com/12413449/28877890-c059ec32-776b-11e7-82c4-8ede171fef41.png)

**Comment by andergrx** [comment]
I'm having the exact same problem with Safari version 10.1.2 (12603.3.8) and started noticing the issue Aug 1 or July 31 (can't remember for sure). 

I did notice the chat exhibiting buggy behavior when I uninstalled BTTV as well.  I'm not sure what changes Twitch has made, but it is quite frustrating to have Chat die all the time.

**Comment by 25katiecirketfan95** [comment]
I'm having the exact same issue as well. Started noticing it on 2 August.

**Comment by night** [comment]
I'm not able to reproduce this on my mac, so it's either another extension you have installed or Twitch itself.
