### ISSUE TITLE
Emotes that match username are shown as highlight

### ISSUE THREAD

**Issue by haxandsnax** [night/BetterTTV#2597]
We're affiliates and our prefix was chosen for us, so we can't change it. The issue is we have an emote named Snax and our prefix (haxand) + Snax = our full username. When subs use the emote it shows up as bold text and highlight instead of the emote.

![image](https://user-images.githubusercontent.com/29994959/28885518-318be582-7784-11e7-8ef9-124a507cf41a.png)

Doesn't seem to be an issue if I disable BTTV, so I think something with BTTV highlighting is the culprit.

**Comment by night** [comment]
You can edit your highlights in the chat settings.
