### ISSUE TITLE
I cant see any emotes

### ISSUE THREAD

**Issue by guamorim** [night/BetterTTV#2599]
i already cleared my cookies and reistaled the addon and i cant see any emotes from bttv.

the option "BetterTV Emotes" is turned on.

**Comment by night** [comment]
What emote are you seeing in chat that isn't showing properly?

**Comment by guamorim** [comment]
everyone, except the emojis

**Comment by guamorim** [comment]
it's working now, thx for your attention

**Comment by vantekarui** [comment]
the option "BetterTV Emotes" is turned on but I can´t see some emotes like PepeHands or FeelsDarkMan
