### ISSUE TITLE
Disable Hosting no longer working :-(

### ISSUE THREAD

**Issue by RealFarknMcCoy** [night/BetterTTV#2601]
Yesterday, when I went to Twitch.tv, the "disable hosting" wasn't working. I went into BTTV options and disabled/re-enabled it, and it appeared to work then. Today, when I went into Twitch.tv, disable hosting was again not working. I tried disabling/re-enabling it (twice), and it is still not working.

**Comment by Nareese** [comment]
Confirmed.  Seeing the behavior as described in clean latest Chrome.

**Comment by eyegouch** [comment]
same^ new installation of Chrome+bttv did not fix it

**Comment by Wikk1dd** [comment]
Same problem here, still unresolved can someone please address this.

**Comment by ziichu** [comment]
Same here ...

**Comment by HighSpy** [comment]
Nothing worse on twitch than having some random person whos been hosted blasting out of my speakers.   Been broken for several days for me also.

**Comment by CaptainSikay** [comment]
Yes, same issue.
About a week ago it stopped working.

**Comment by Codereaders** [comment]
Same here, disabling Host Mode dosen't work.

BetterTTV v7.0.25
Opera 47.0.2631.55
Windows 10 64-bit

I tryed the BTTV Extension for Opera (v 6.8) as well as the one from Chrome Store (v 7.2)

**Comment by AustinBrock** [comment]
Confirmed.  Really annoying.

**Comment by Gewath** [comment]
Disable hosting is possibly the #1 feature of BTTV and has been missing for a long time. Make Twitch watchable again

**Comment by Slikrick** [comment]
The issue appears to be that twitch removed the thing BetterTTV was relying on to do this, I will try and take a look at this to see if I can fix it.

**Comment by cavac** [comment]
Is it a detection problem?

There is this nice <h3> element you could use:

```
<h3 class="card__title js-hosting-card-title">
                Hosting 
                <strong>danlesac</strong>                
</h3>
```
