### ISSUE TITLE
Theater mode

### ISSUE THREAD

**Issue by Jonuik** [night/BetterTTV#2603]
When entering theater mode I will occasionally be unable to see the pause/play, volume, settings, clip, theater mode, and fullscreen "utility bar" at the bottom of the stream/window.

**Comment by night** [comment]
this would have nothing to do with us since we do not render player controls

**Comment by Jonuik** [comment]
After a bit of testing it appeared that it just happens by chance that the two times I disabled BTTV I didn't have that problem but then it continued to happen when removing it another time. But thank you for looking into it.
