### ISSUE TITLE
Support for Twitch Beta website https://go.twitch.tv

### ISSUE THREAD

**Issue by brianwjung** [night/BetterTTV#2605]
With the official release of the Twitch Beta page (https://go.twitch.tv), can support be added for this domain?

**Comment by night** [comment]
This requires a complete rewrite of the extension, so it will take some time

**Comment by brianwjung** [comment]
That’s understandable. Is there going to be a separate repository for that?

**Comment by night** [comment]
I spent the majority of my weekend working long hours to make this work. There's now a branch with code making the beta site functional. If you visit the beta site you’ll see BetterTTV now functions on it. Not everything works, and it’s very much a work in progress.

**Comment by brianwjung** [comment]
Awesome! I'm honestly just glad to have dark mode on the beta site. Well, that and the obvious BTTV emotes :)

**Comment by Thehail** [comment]
Please, add the autofill emotes next! :)

**Comment by SaiyanOfDarkness** [comment]
I hope most of the issues is caused just because of the non support for the domain.. like how the emote button doesn't appear under chat.

**Comment by Thehail** [comment]
Cannot get back to old website anymore. Needs an update soon.

**Comment by night** [comment]
BetterTTV works on the new site, but it does not yet contain all of its old features. Due to complexity in integration with a react-based site it is unlikely all features will return or work in a stable way.

**Comment by night** [comment]
New release published tonight porting the emote menu.

**Comment by Thehail** [comment]
I miss the autocomplete emotes and the chat status (such as slowmode time, subscribers only room, etc). Hope we get this soon :(

**Comment by night** [comment]
host button, chat commands, dismissing pinned bits, showing deleted chat messages, and video player shortcuts have been readded tonight

**Comment by night** [comment]
the remaining todo items for features have been finished. if there's anything still missing please open new issues for each.

**Comment by mikkymit** [comment]
My tab completion stopped working randomly :(
