### ISSUE TITLE
Dark Mode not applying in Past Broadcasts

### ISSUE THREAD

**Issue by Archronos** [night/BetterTTV#2616]
Dark mode does not apply in Past Broadcasts, which makes the section very hard to look at

![image](https://user-images.githubusercontent.com/30966508/29245377-659407c0-7fd0-11e7-9ee4-64c83c9a5ea4.png)

**Browser**: Firefox 54.0.1
**BTTV**: 7.0.25

**Comment by aroboto** [comment]
![a0p6uoe 1](https://user-images.githubusercontent.com/22084203/29246124-5194c4dc-7fe7-11e7-9cc6-4f044566ee0f.png)

Also doesn't apply in the same way on the uploaded video section.

**Comment by lackofwords** [comment]
Seems like these cards shows up only on Creator dashboard videos. Such as when you're looking at your own Past Broadcasts, Highlights, Uploads, etc.
Basically any media bit that has the option for the Creator to edit the video.

the css class selector(s) you're looking to edit are;

.card (the container for these videos)
.card--bordered (draws a 1px border for the container)
.card__body (the bottom block containing the text and buttons)
.card__title (styles the title of the card, e.g. video title)
.card__info (styles the description and details, e.g. date, time, etc)

**Comment by night** [comment]
fixed by https://github.com/night/BetterTTV/commit/9dce2fbc03316376398b34c40da3a524608f8ae6
