### ISSUE TITLE
Messages that should have been deleted, are still visible even with "Remove Deleted Messages" turned on

### ISSUE THREAD

**Issue by PikalaxALT** [night/BetterTTV#262]
Chrome 40.0.2214.115 (Official Build) m on Windows 8.1

DarkenTTV: On
Remove Deleted Messages: On
Split Chat: On

**Comment by voloshink** [comment]
Can't reproduce the bug. Have you cleared your cache?

**Comment by PikalaxALT** [comment]
Hey Kirill. I guess I should not have reported the problem as being caused by your extension based on an n of 1. Turns out the problem was on the moderator's end.

- Scott Norton
scnorton@mail.med.upenn.edu

**Comment by voloshink** [comment]
Glad to hear it's resolved.
