### ISSUE TITLE
Safari Shows Version as 6.8

### ISSUE THREAD

**Issue by spaz926** [night/BetterTTV#2622]
Like the title says even on the newest binary Safari is showing the version as 6.8

![screen shot 2017-08-14 at 4 22 03 am](https://user-images.githubusercontent.com/990135/29265988-ac3e15d4-80a8-11e7-87eb-3b4e18fb7dc5.png)

**Comment by night** [comment]
that's the latest version of the extension we've released. you can check your version within the betterttv settings' about screen

**Comment by spaz926** [comment]
Thanks for that info. I was just afraid Safari was doing something weird with the extension and not allowing it to update. Glad to know I'm on the current version.

May I ask why the extension version and actual version differ?
