### ISSUE TITLE
Hide the colon

### ISSUE THREAD

**Issue by nmynarcik** [night/BetterTTV#2628]
It's already shifted and colliding into usernames, might as well hide it?

![](https://puu.sh/xc9tX/8d5a19784d.png)

**Comment by AlcaDesign** [comment]
I'm not seeing that

![image](https://user-images.githubusercontent.com/7132646/29431315-1f5945be-835d-11e7-811e-1877dbbaf4fb.png)

Are you using any other extensions that style Twitch? Say FFZ or something?

**Comment by nmynarcik** [comment]
No other extensions. I can try and see if it's something external that is causing it.

**Comment by nmynarcik** [comment]
Updated screenshot: 
![](https://cl.ly/1l0F3E3A3d38/Image%202017-08-17%20at%203.30.58%20PM.public.png)

**Comment by AlcaDesign** [comment]
Yes, I see that in whispers too. This happens as part of BTTV to fix a gap in Chat Replay that would look like this without it:

![image](https://user-images.githubusercontent.com/7132646/29433199-cbc35064-8363-11e7-9598-10b1e00de6c2.png)

Here's the affecting lines:

https://github.com/night/BetterTTV/blob/c69be8dd96b49122899a1b19b23ea3630608cb0c/src/css/betterttv.css#L2472-L2475

I think the second line of the selector (`.conversation-chat-line .colon`) is no longer needed but I don't know where else this might be used around the site but I think "conversation" is their internal word for "whispers." I'll open a PR to remove it and if it gets shot down then it's probably used somewhere else.

**Comment by night** [comment]
fixed by 04be68ea86fc0fc40782c71e636d436093031f59
