### ISSUE TITLE
Add the ability to nickname other users.

### ISSUE THREAD

**Issue by drepwn** [night/BetterTTV#263]
I suggest adding an ability to rename or nickname twitch users so they appear as what you want to call them. IE- nick "xxxdarkqu1cksc0pezxxx" as "dark" (ridiculous ex. to show potential usefulness)

**Comment by voloshink** [comment]
This is already a feature of bttv. You can click on a name in chat and then click the pencil next to their name

**Comment by drepwn** [comment]
holy crap. thats amazing. BTTV is so ahead of the curve, it's the only plugin to use.
