### ISSUE TITLE
hosted mode

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2632]
![screenshot 561](https://user-images.githubusercontent.com/19208617/29443532-cfab989c-83a6-11e7-9e72-e52cb7991e55.png)
disabling hosted channels is not working correctly because it will not disable hosted channels and i have it set to on and i even tried turning it off and putting it back on and it didn't affect it 
![screenshot 560](https://user-images.githubusercontent.com/19208617/29443530-cbda6bda-83a6-11e7-9802-8a5c92115c54.png)

**Comment by night** [comment]
duplicate of #2601
