### ISSUE TITLE
Leaving theater mode via back button forces BetterTTV Dark Theme

### ISSUE THREAD

**Issue by MrPickles** [night/BetterTTV#2644]
When watching a stream in theater mode, if the previous page was another page in twitch.tv, pressing the back button on the browser (i.e. not explicitly pressing the "Exit Theater Mode" button) will go back to that page, except it will have the BTTV dark theme, even if that setting is disabled.

**Comment by night** [comment]
This is not worth fixing for the old Twitch site, sorry. Twitch's new beta site won't have this issue with BetterTTV.
