### ISSUE TITLE
Close button on the minimized player doesn't work

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#2648]
When I press the back button, and go to the main page of twitch while watching a stream,
a small player still shows the stream on the bottom left side. However, when I try to close it,
by pressing the Close ("X") button, it doesn't respond. I need to refresh the whole page in order to close it.

Edit: I saw another bug report of the same issue few days ago, and I can confirm it's the same problem. I have no conflicted mods, and this thing never happened to me before

**Comment by night** [comment]
We do not touch the minimized player, so it's not us.
