### ISSUE TITLE
When using "Auto" quality, every time the player changes resolution, it pops the title and settings line

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#2649]
Every time the "Auto" quality switches the quality by itself, it makes the whole button and top layers to pop off, and when it happens every few seconds, it makes the stream annoying to watch. It does not happen when the Mod is disabled, so this is not the intended behavior. It was fine in the past.

**Comment by night** [comment]
We do not touch the player in a way that would cause this. The player is encapsulated.
