### ISSUE TITLE
getting wrong chat of watching channel

### ISSUE THREAD

**Issue by JEMICSGO** [night/BetterTTV#2652]
hello

i get some wrong messages on chat saying your friend started watching you while no one is there 

i get the same message everyday

can you help please ?

thank you

(Your friend iambossasbitcchh is also watching!  
![untitledsss](https://user-images.githubusercontent.com/31402332/29764963-577a2c7a-8bea-11e7-83f0-3ce12c9daf98.png)

)

**Comment by night** [comment]
that would be a twitch bug.. we dont send those messages
