### ISSUE TITLE
Vods wont load when BTTv is Enabled

### ISSUE THREAD

**Issue by Tmini76** [night/BetterTTV#2654]
When I click on some VODs it tries to load the video but after a few seconds the buffering symbol disappears and just says "unknown". Disabling BTTv and then clicking the VOD it loads just fine. This problem happens on some VODs, and others load and play just fine. But when it doesn't work reloading the page & clearing cache doesn't fix the VOD, the only way I can get the ones that don't play to work is to disable BTTv.

**Comment by night** [comment]
I cannot reproduce this.
