### ISSUE TITLE
Video shrinked in theater mode on widescreeen

### ISSUE THREAD

**Issue by bunyi** [night/BetterTTV#2658]
Video is shrinked down on widescreen monitor in theater mode even is there enough space for full screen size.  Previously it worked, but it broke down after some update.

Chrome with bttv:
http://imgur.com/a/6L2E7

Without bttv video size is ok:
http://imgur.com/a/1vdVG

**Comment by Slikrick** [comment]
It seems to be caused by the whispers button, as we don't touch the video player at all, do you have the  (BetterTTV) setting on that hides the whisper menu if you have no new whispers? I will look into this though.

**Comment by bunyi** [comment]
I don't have this option enabled. Also I discovered that this bug occurs only when I'm logged in, even without bTTV, so this looks like general Twitch site bug. I reported this.
So unless you have plans to temporary fix this behaviour in the extension itself, then probably the topic is to close.

**Comment by night** [comment]
This would appear to be a Twitch bug. We do not resize the player at all (we use to, but removed it long ago because dealing with resize edge cases like this made us hate our lives).
