### ISSUE TITLE
Add an option to overwrite the new global LUL emote

### ISSUE THREAD

**Issue by elvador** [night/BetterTTV#2659]
BTTV LUL > Twitch LUL

**BTTV:**
![BTTV LUL](https://cdn.betterttv.net/emote/567b00c61ddbe1786688a633/3x)

**Twitch:**
![Twitch LUL](https://static-cdn.jtvnw.net/emoticons/v1/425618/3.0)

**Comment by Nareese** [comment]
BTTV's version now on LuL

https://twitter.com/BetterTTV/status/903847835900174336
