### ISSUE TITLE
Unlinking a deleted Discord server not working

### ISSUE THREAD

**Issue by MawiaJ** [night/BetterTTV#2662]
I made a test server on Discord to test various bots before using them on my actual server. I deleted the server without realising I probably should've unlinked BTTV first, and now the unlink button does absolutely nothing. I hope to be able to link it on my actual server.

**Comment by Slikrick** [comment]
Github is for bug reports, not support. Use the proper support forms on https://nightdev.com/support

**Comment by night** [comment]
this is the right place to report bugs

**Comment by night** [comment]
should be fixed
