### ISSUE TITLE
Beeping everytime I write something

### ISSUE THREAD

**Issue by Astinox** [night/BetterTTV#2666]
Hey guys,
so for about 4 to 5 days I am experiencing an issue I did not have before. Everytime I do write a chat message OR someone else says my name, I do hear a beep in chat.

I have disabled this feature from start on. What I tried to fix it was:

- Reinstalling BTTV
- Turning it on (in settings) and hoping it's reversed
- Disabled it again to check it

Nothing of this works. If I uninstall BTTV, there is no beeping. I get this everytime I write (so my name appears in chat) and someone else writes my name in chat. My specs:

- Windows 7 64Bit 
- Version 60.0.3112.113 (Official Build) (64-bit)

I hope there is a way to fix this.

**Comment by night** [comment]
Turn off the highlight sound in the BetterTTV settings...

**Comment by Astinox** [comment]
This is the reason why I am writing this. I did it. This is a screenshot from my current state (as I said above, I tried turning it on/off) and it kept beeping.

http://prntscr.com/ghlfbh

I wouldn't ask for support if it was just turning off a setting.
