### ISSUE TITLE
[BUG] Can't chat after emote auto complete

### ISSUE THREAD

**Issue by Blazerian** [night/BetterTTV#2667]
So after i press Tab to auto complete an emote it's like the chat isn't focused so pressing enter doesn't post the message.
it happens every time i do it

**Comment by Suicude** [comment]
I have exactly the same problem. Using Chrome. Closing Chrome fixes it until I auto complete again. Be it Emotes or Names.

**Comment by Blazerian** [comment]
I have found that if you use the popout chat it works perfectly. it's the built in browser that has that. i refresh to fix the bug but if i press tab it just freezes.

**Comment by night** [comment]
it's probably due to some other extension you have installed. it works fine on my machine and we've not changed anything in BetterTTV for some time now.
