### ISSUE TITLE
Add Regular Expressions to Highlight/Blacklist

### ISSUE THREAD

**Issue by rue92** [night/betterttv#267]
I'd like to request adding regular expression support for highlighting text/users in chat. For some this allows highlighting username variants without typing out all permutations. Another potential (though unlikely) use would be for highlighting game series, e.g. `[Ff]{2}(\d*|[IVX]*)`. I can see this requiring a relatively large rewrite though due to use of () and {} in the configuration already. Just a thought :D. 

P.S. I didn't actually test that regex, so don't blame me if it's wrong! :P

**Comment by vendethiel** [comment]
Yeah, considering the current state of the highlighting, this isn't possible. A rewrite may allow that, but we need to warn users properly not to use if they're not really tech-savvy.

**Comment by skerg** [comment]
I would like to second this request. It would be especially useful to have when blacklisting messages.

**Comment by metarmask** [comment]
:+1: This would be really useful.

You could add it to the settings with an explaination: "Regex Keywords -- Use regular expressions in keywords. Only enable if you know what you are doing."

**Comment by Codonbyte** [comment]
You could do what Chatty does and precede regular expressions with reg::{regex goes here}.
