### ISSUE TITLE
Highlighting Certain Words

### ISSUE THREAD

**Issue by gakiloroth** [night/BetterTTV#268]
Hi! Thanks alot for this excellent Chrome extension. I only have one request, would it be possible for certain words to be highlighted, in a similar fashion to message being highlighted when our username is mentioned? 
Thanks for all you've done!

**Comment by night** [comment]
You can add highlighted words via the chat settings.

**Comment by gakiloroth** [comment]
Oh, thank you very much! I thought there was a feature, but assumed it
wasn't there when I couldn't find it. Thank you!
