### ISSUE TITLE
Some new BTTV emotes doesnt work

### ISSUE THREAD

**Issue by mouseck999** [night/BetterTTV#2682]
I don't know for what reason but recently some new emotes in different Twitch chat's stopped working. Or better to say: I haven't seen them working on my pc, only in youtube videos etc.

For example: PepeHands,PagChomp,Hyperbruh. All of these emotes doesn't seem to work on my pc.
I tried reinstalling my BTTV on chrome/firefox, didn't helped.

Thank You

**Comment by Dabarti** [comment]
Those emotes will not work with BTTV. You will need to install FFZ (FrankerFaceZ) in order to see or use them.
