### ISSUE TITLE
'Chat on videos' released, BTTV for chat no longer works on VoDs

### ISSUE THREAD

**Issue by DAOWAce** [night/BetterTTV#2683]
https://blog.twitch.tv/chat-on-videos-feature-expanding-to-all-videos-9d71167d8b52

Went to resume my VoD today, discovered a busted chat panel. https://i.imgur.com/CyYFeBY.png
 White, no BTTV emotes and it acted like you could still chat (without any functionality to tweak your chat).  Found out they apparently updated it to this awful system.

Anything we can do to revert back to the old 'chat replay' system?

**Comment by mbollier** [comment]
@DAOWAce from the settings cog you can toggle it back to "show me only messages posted during the original broadcast" which should more or less mirror the previous system

**Comment by TheRealDannyyy** [comment]
I can confirm that this new chat system breaks the dark design of BTTV, both inside and outside of theatre mode on my end.

I'd also very much appreciate an option to fully hide the "post a message" textbox + button (to show more of the chat like it used to be), if possible.

**Comment by DAOWAce** [comment]
@mbollier  That does nothing but hide "after the fact" messages in the chat.  It doesn't affect any functionality at all.

> I'd also very much appreciate an option to fully hide the "post a message" textbox + button (to show more of the chat like it used to be), if possible.

Yes, this is one of the bothersome things (besides dark theme breakage) since it now acts like a live stream chat.. without any of the functionality.  Would really like to see this option so it isn't taking up so much space.

**Comment by dodgedlol** [comment]
Hi, I'm having the same problem. Twitch chat is white on VOD's, any fix coming soon? Thanks in advance! Will donate for a fix. <3

**Comment by Wanngus** [comment]
It seems to still be broken on Opera Browser. Even on fresh install of the browser.

**Comment by luxomberg** [comment]
BTTV emotes on VODs still seems broken on Chrome. I can see BTTV emotes on live streams, but not on VODS. Attached is a screenshot with console log.
![bttv_capture](https://user-images.githubusercontent.com/32260662/30800038-b5a109c8-a219-11e7-8fd5-bcbc5796b606.JPG)

**Comment by DAOWAce** [comment]
My emotes are working on chrome, but the chat is still abysmal to try and read without user colors and a different look to the theme now.

Why did Twitch think this was a good idea..

**Comment by mbollier** [comment]
@DAOWAce are you not seeing user colors still? It was fixed on Friday

**Comment by mad-hero** [comment]
I have to reload the page several times before the bttv emotes start to work. It is inconsistent.

**Comment by DAOWAce** [comment]
@mbollier For VoDs? No, all the usernames are white, which makes reading things a problem.

But that's twitch's end; BTTV never controlled user colors.  I kinda wish it did now.  VoD chat is a complete pain to read without it and split chat.

**Comment by mbollier** [comment]
@DAOWAce on Twitch's end this was fixed last week. I would suggest viewing a VOD in a "clean" browser (either incognito with no plugins or a totally clean install) to see if this issue is persisting for you. If it is, can you share some details like the VOD you're watching, browser, OS, etc?

**Comment by Daniil1288** [comment]
@mbollier, usernames in chat replay (or whatever it's called now) are white with BTTV's dark theme turned on; without BTTV (disabling the extension works for me) the colours are present.
