### ISSUE TITLE
Chat when watching vods is no longer black 

### ISSUE THREAD

**Issue by doihavetodothis** [night/BetterTTV#2684]
TriHard

So the issue is that since today or so, the chat when watching a vod turns white while everything else is correctly black themed
![bttvbugreportwhitevodscreen](https://user-images.githubusercontent.com/32113049/30618045-1143755c-9d99-11e7-8d3c-6f3ef0c5c261.png)

**Comment by dodgedlol** [comment]
Yes can confirm, not working for me either. Any fix coming soon? Thanks in advance, will donate for a fix.

**Comment by s1ndrom** [comment]
It's not working anymore, will it be fixed anytime soon?

**Comment by night** [comment]
duplicate of #2683
