### ISSUE TITLE
Purple in dark mode

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2686]
seems Twitch has dark mode on that conflicts with BTTV dark mode making things more purple
Something was just changed in the last few hours
this is for the normal site not beta

 it looks like this now https://i.imgur.com/3HRPTnV.jpg
and it should look like this https://i.imgur.com/lneqKA6.jpg

No "other" extensions are active

**Comment by night** [comment]
You will need to use the Twitch beta site. We only will support our legacy dark theme on the non-beta site (it's too much work to refactor for something going away soon).

**Comment by Gehrm** [comment]
How does one "use the Twitch beta site"? Is the "legacy" dark theme mean that you do not have a dark theme for the beta?
