### ISSUE TITLE
Can't turn off monkey emotes

### ISSUE THREAD

**Issue by meisme** [night/BetterTTV#269]
On Saturday it worked and I could disable the monkey emotes, today the language of the settings screen has been changed and no matter if I have the Robot Emoticons  setting to On or Off they show up in chat. Even after reloads.

**Comment by Nathsters** [comment]
Mine does this too I just adapted to it.

**Comment by voloshink** [comment]
Try clearing your cache and downloading and reimporting your settings.

**Comment by night** [comment]
The setting "On" means that Robot Emoticons are "on" and will be shown. "Off" means you do not want Robot Emoticons, in which case blue monkey emotes are instead shown. If you are seeing brown monkeys, those are turbo emoticons.

**Comment by meisme** [comment]
Clearing the cache fixed the issue, thanks.
