### ISSUE TITLE
[Request] Filter out Communities or Games in Browse

### ISSUE THREAD

**Issue by SoManyDeads** [night/BetterTTV#2691]
For some reason Twitch thought it would be a great idea to merge communities and games into a new sorting feature called Browse. The ideas for the two are completely different, which makes sorting them together quite frankly annoying. As an example one day https://puu.sh/xFQ26/5dd1fba7fc.jpg this was the result of some of the upper rankings. One stream was in all 3 community groups that propelled them all to the top of the sorting algorithm. When I use twitch browse I usually go through looking for some games that I am interested in, so things like "VarietyStreamers" "Positivity" or a game community named after a game that already exists are just muddying up the results. Pleasemake an option to divide the two as it's current incarnation done by twitch appears to be completely backwards from a content standpoint.

**Comment by SoManyDeads** [comment]
If anyone else is interested I made a adblock filter that removes them (not their footprint). unfortunately adblock does not allow for the removal of a second generation parent, or parent at all for that matter. So for filters in adblock/ublock you can do the following and it will just cycle them out.

      www.twitch.tv##a[href*="communities"]

I tried some stuff with extensions (I don't really know javascript), and I was able to get "some" success but I found out I broke something on the twitch page. Basically it removed the js scrolling on the page and thus, makes the entire idea kind of useless. I was having random success with it, but was having troubles with the timing of execution. If twitch loaded their js first it would work (1 in 100 felt like) if mine loaded first it wouldn't work at all. So I tried just throwing a delay in, which worked... but only for the first few results. setting a polling style idea up seems to break the page scrolling. Anyway if someone else wants to give it a go, here's my stuff.

manifest.json

    {
	  "manifest_version": 2,
	  "name": "Twitch Browse Communities Removal",
	  "version": "0.1",
	  "content_scripts":[
	  {
		"matches": ["https://www.twitch.tv/directory"],
		"js": ["jquery-2.2.4.min.js", "content.js"]
	  }
	]
    }

content.js

    var myVar = setTimeout(coolStuff, 1000);

    function coolStuff() {
	clearTimeout(myVar);
	var el = document.querySelector("a[href*='/communities/']");
	while (el != null) {
		el = el.parentElement;
		el = el.parentElement;
		el.parentElement.removeChild(el);
		var el = document.querySelector("a[href*='/communities/']");
	}
    }

**Comment by SoManyDeads** [comment]
Second quick update, I found that by using loading the page, and then making the window smaller it would force the scrolling to work for the page. Using setInterval instead of setTimeout I was able to have it update and filter the items throughout the entire list. It's kinda jumbled together but at least it's something for people who dislike communities being in the same section as games. Also if you wanted to filter for the reverse, you would only need the change the following

    var el = document.querySelector("a[href*='/communities/']");

to

    var el = document.querySelector("a[href*='/games/']");

updated code for contents.js

    var myVar = setInterval(coolStuff, 1000);

    function coolStuff() {
    var el = document.querySelector("a[href*='/communities/']");
    while (el != null) {
	el = el.parentElement;
	el = el.parentElement;
	el.parentElement.removeChild(el);
	var el = document.querySelector("a[href*='/communities/']");
    }

    }

**Comment by night** [comment]
#70

**Comment by SoManyDeads** [comment]
His idea is completely different than mine, I am not looking to specifically boycott a streamer and remove their availability. https://www.twitch.tv/directory <-- This is what I want to filter, for some reason a while back Communities (The Twitch variety that you can stream to) and Games (the game the streamer is playing) were separate ways to filter what you want to look for. These have since been merged into one category where you have Communities and Games mashed together sorted by most viewed. My request is that you can filter between the two, or having a different link for each style so that when you browse you can look at the games list without the results being polluted by communities which are not game specific (or vice versa, if you want to watch a community stream, you don't have game streams everywhere).

**Comment by SoManyDeads** [comment]
In the twitch beta they are separated again, not required to do anything.
