### ISSUE TITLE
Show deleted message option is missing

### ISSUE THREAD

**Issue by tabarjack** [night/BetterTTV#2692]
It was there, then was broke, now it's missing.

![bttv1](https://user-images.githubusercontent.com/359023/30873456-56434624-a2bb-11e7-964d-64e75a7b737b.PNG)
![bttv2](https://user-images.githubusercontent.com/359023/30873457-56436c80-a2bb-11e7-8ee2-63d96c01d4f0.PNG)

**Comment by night** [comment]
it is not broken: #2605
