### ISSUE TITLE
BTTV Emotes do not work in VODs

### ISSUE THREAD

**Issue by Blakewhat** [night/BetterTTV#2693]
Twitch has a new twitch video chat thing

**Comment by night** [comment]
They work fine.

**Comment by b4n4n4** [comment]
Actually, sometimes they don't work, it's totally random if they will show up, sometimes i need to refresh like 5 times before they start showing.

**Comment by Blakewhat** [comment]
https://i.imgur.com/wZ6IUSi.png Never working for me

**Comment by Weeeishy** [comment]
Im experiencing the same thing. Some vods work with bttv emotes and some not.
