### ISSUE TITLE
Loading Screen to sign in to BetterTTV is forever loading. 

### ISSUE THREAD

**Issue by Ziircx** [night/BetterTTV#2694]
![stuck on this screen](https://user-images.githubusercontent.com/32369557/30980543-4c8310e8-a436-11e7-8b10-db7e268ea254.png) I hate it I can't access the emotes I put in and want to put new ones for my channel. I can't sign in so I can't do anything for my channel with betterttv. It is annoying please help!

**Comment by udpPigeons** [comment]
Do you have any other extensions installed?

**Comment by Ziircx** [comment]
Yes I have ad blocker and twitch giveaways

**Comment by Ziircx** [comment]
I tried turning them off and it still doesn't load

**Comment by night** [comment]
I cannot reproduce any issues.
