### ISSUE TITLE
"Play Sound on Highlight/Whisper" no longer working

### ISSUE THREAD

**Issue by udpPigeons** [night/BetterTTV#2697]
It did at the beginning, but now even after turning it on and off, it will no longer highlight if someone messages me. I don't have any word whitelists or blacklists. I tried removing the extension and readding, but that doesn't clear the extension data.

Any ideas? I'm fine clearing the extension data, if anyone can instruct me on how.

**Comment by night** [comment]
Check your highlights list in the chat settings. It works fine here.

**Comment by udpPigeons** [comment]
Thank you, @night; I appreciate the comment. I thought I had tried that, but perhaps I didn't.
