### ISSUE TITLE
Using Twitch's Own Dark Mode with BTTV's Disabled Causes Chat to be White

### ISSUE THREAD

**Issue by DacioRomero** [night/BetterTTV#2698]
I've been using BetterTTV's dark mode for a long time, but I noticed that Twitch has their own now, so I disabled BetterTTV's and enabled Twitch's which causes chat to be white. Probably some sort of CSS styling issue where BetterTTV applies the white style to chat to disable the dark theme.

**Comment by night** [comment]
#2686

**Comment by DacioRomero** [comment]
Not exactly a duplicate, this is specifically referencing that the chat is white. Here's an [image](https://imgur.com/pyR1qQk) illustrating my specific issue and an [image set](https://imgur.com/a/ygp0d) of all possible combinations of Twitch's own dark mode, the BTTV plugin, and BTTV's dark mode all enabled and disabled.

**Comment by DacioRomero** [comment]
@night Hey this isn't a duplicate.

**Comment by Cephel** [comment]
@night This is not a duplicate, having the exact same problem.
