### ISSUE TITLE
Emote autocomplete is not working

### ISSUE THREAD

**Issue by Zabrios** [night/BetterTTV#2700]
Had this problem since yesterday. Can't even seem to autocomplete an emote when I hit tab, and the autcompletion options in the BetterTTV settings menu seems to be missing

**Comment by d07RiV** [comment]
Are you using the beta version of Twitch (go.twitch.com)? Not all BTTV work for it yet, you should probably switch back to the old version if you want them (click on the arrow in top right corner and uncheck "Beta Site").

**Comment by night** [comment]
#2605
