### ISSUE TITLE
Font family applied incorrectly

### ISSUE THREAD

**Issue by d07RiV** [night/BetterTTV#2701]
The font prompt suggests putting in monospace as one of the options, but doing so results in `font-family: "monospace"` style being applied, which is not a valid font family name (should be without quotes). Perhaps exceptions should be made for generic font names (serif, sans-serif, monospace, cursive, fantasy, system-ui)?

**Comment by night** [comment]
pull requests welcome

**Comment by d07RiV** [comment]
Okay hope I didn't mess up your code style too much.
