### ISSUE TITLE
Embedded polling option missing

### ISSUE THREAD

**Issue by yeeeeeee3** [night/BetterTTV#2704]
I'd like to disable them, but the button seems to be missing.
Using bttv 7.0.29 and Firefox 56.0 64-bit

**Comment by night** [comment]
You cannot disable them. Since only mods can post poll links it shouldn’t need to be disabled.

**Comment by yeeeeeee3** [comment]
I meant that I don't want to see the polls to be shown on top of chat. Previously there was a button that said "See polls posted by the broadcaster embedded right into chat" and you could disable them so you didn't see the popup for polls.
