### ISSUE TITLE
Theater Mode switches Dark Theme

### ISSUE THREAD

**Issue by BrunchLP** [night/BetterTTV#2707]
Dark Theme off
   -> Theater Mode on
      -> Leave it in Theater Mode for some amount of time. It happened sometimes within seconds and 
           sometimes the bug didn't occour at all
         -> Leave Theater Mode
            -> Twitch is now in Dark Theme without it being set to on
               -> You have to turn Dark Theme on and then off again to have the site normal again

**Comment by night** [comment]
on the Twitch beta site or the non-beta site?

**Comment by Masquara** [comment]
This happens for me on the non-beta site

**Comment by night** [comment]
sounds like a bug in twitch.. leaving their theater mode should disable their dark mode unless you've turned it on
