### ISSUE TITLE
[Request] option to relocate "watching now/viewer count" to under chat box *pics*

### ISSUE THREAD

**Issue by Trashhand** [night/BetterTTV#2708]
hello,

i like many others, want to stream with the least amount of windows/programs open on my 2nd monitor.  (dont want a 3rd)  im asking for this feature request because although the program im forced to use for twitch chat works well, i do not prefer its chat format, nor cluttered viewer count option on the windows' title bar.

ld rather not use chatty.  i would prefer to use the default twitch pop out chat w/ the BTTV enhancements - but i need that viewer count! can you help? if not on BTTV, maybe on Nightbot's dashboard which i already use?

ive included a link to what my feature request would look like, and what my setup is.

viewer count: https://imgur.com/a/ObS13
2nd monitor layout while streaming: https://imgur.com/a/JHSiE

thanks

**Comment by night** [comment]
from a ui standpoint it doesn't make sense for us to relocate a viewer count to the chat as it has nothing to do with the chat. sorry friend.

**Comment by Trashhand** [comment]
hey thanks for the reply,

if it doesnt make sense for you on bttv... would you consider adding it to the nightbot dashboard?
