### ISSUE TITLE
Disable name colors description text phrasing

### ISSUE THREAD

**Issue by Logarek** [night/BetterTTV#2709]
The description text for the "Disable name colors" option states "(useful for those who may suffer from color blindness)".

"Suffer" isn't really the best word to describe a disability, I'm not suffering because I'm colorblind, I just live with it. You're better off saying "(useful for those living with color blindness)".

**Comment by night** [comment]
i think you're reading too much into it.. this is a common idiom for people with a medical condition. it is fine as-is.
