### ISSUE TITLE
Blacklist doesn't work with default emotes

### ISSUE THREAD

**Issue by Tuhljin** [night/BetterTTV#2711]
I added a bunch of emotes, both default and BTTV, to my blacklist and I've found (after some investigation) that the default emotes are not blacklisted. I remember this worked in the past but it's been broken for several weeks if not a few months now.

For instance, as a test, I added both "LUL" and "LuL" and only the BTTV version is filtered.

**Comment by night** [comment]
#2605

**Comment by Tuhljin** [comment]
I assume that means that you'll have it working once the rewrite is complete, but just as an FYI, the filter not catching default emotes was an issue for me for a while before the beta rollout. (I suppose they might still be related if you started coming out with new builds in anticipation of that, or something, but I would assume not. Either way, so long as it works after the rewrite, that doesn't particularly matter.)

Thanks for your hard work!
