### ISSUE TITLE
Some emotes are not displaying correctly

### ISSUE THREAD

**Issue by ddosyourtoaster** [night/BetterTTV#2714]
Emotes are not showing correctly, the emotes which are not working are emojis like 🤔 and 🔫. Emotes like monkaS and haHAA show correctly

This is an example:
![image](https://user-images.githubusercontent.com/32559016/31259426-009b0c44-aaa3-11e7-9841-523217956d82.png)

These are my BTTV settings:
https://pastebin.com/SkiZkCDx

**Comment by night** [comment]
#2605
