### ISSUE TITLE
Emotes not loading when loading VOD (from link)

### ISSUE THREAD

**Issue by sparcut** [night/BetterTTV#2718]
**NOT** the same problem as emotes "not working in VOD chat at all".

As seen in the screenshot, emotes have not been loaded, this seems to happen when going to a VOD link or reloading a VOD page. 

![chrome_2017-10-08_12-08-36](https://user-images.githubusercontent.com/16233822/31313314-1d48633a-ac2b-11e7-8301-49cba73704fb.png)

**Reproduce:**  Go to a VOD (that has custom emotes in), copy/paste into new tab _OR_ refresh page, emotes should not be working/loaded.

**Fix:** Can be fixed by navigating to anywhere on the channel that has live chat, then navigating back to the VOD, then emotes will be loaded and working again.

**Comment by night** [comment]
#2605
