### ISSUE TITLE
Pale Moon compatibility

### ISSUE THREAD

**Issue by daedrot** [night/BetterTTV#2721]
I'm using pale moon and i wanted to add bttv to it, so that i can watch streams directly from there without switching to different browser, but i didn't find any way to do so. Is there any? If not, are there going to be any pale moon versions of bttv in the future? Thank you.

**Comment by night** [comment]
Pale Moon has deviated from what Firefox supports extension-wise, so we unfortunately no longer support Pale Moon. Until Pale Moon supports WebExtensions we're not willing to maintain an extension just for them (just doesn't make sense when they hold too small of the browser market share).
