### ISSUE TITLE
BBTV emotes sometimes break in VODs.

### ISSUE THREAD

**Issue by Daanial11** [night/BetterTTV#2729]
The BBTV emotes sometimes don't load in the VOD chat and I have to restart my browser for them to work again.

**Comment by night** [comment]
I cannot reproduce this on the non-beta site. We do not yet support the beta site's VoDs.

**Comment by TheRealDannyyy** [comment]
@night I would like to request to re-open this issue.
I'm experiencing the same problem where BBTV emotes randomly stop working in VoDs (non-beta).

Is there a way to help you guys out with this, console log or something?
(Tested in this VoD: https://www.twitch.tv/videos/187110623)
