### ISSUE TITLE
BetterTTV not working. Java errors.

### ISSUE THREAD

**Issue by grunt0** [night/BetterTTV#2730]
Using Opera 48, Win 10, 64-bit. Installed latest Opera, java and BetterTTV. Finally checked java console today on Twitch (as per debugging guide) and it throws these errors:

![java_errors](https://user-images.githubusercontent.com/32914912/31746226-88497c58-b466-11e7-86cd-dc9b2e8c5869.png)

Was using it just fine not so long ago (1-1.5 months). Twitch recognizes it as installed (has the BTTV logo on it), but it does not work. Not even its settings can be opened (don't appear).

**Comment by TheLucky007** [comment]
Make sure that you are not in the Beta site as BetterTTV is under development for the beta.

**Comment by night** [comment]
I'm not able to reproduce this on the beta site. It's possible Twitch was having issues (since the error is coming from their JavaScript).
