### ISSUE TITLE
Linehistory is a terrible feature and I can't turn it off

### ISSUE THREAD

**Issue by Knobibrot** [night/BetterTTV#2732]
I sometimes want to edit some words in the beginning of my message and so I use the up-arrow to navigate to the top. Intuitively, I simply hold up, expecting it to scroll to the top and then stop there. However, with BTTV, Twitch scrolls past that point to my earlier messages and it is impossible to scroll down again to retrieve my draft. This is incredibly frustrating and discourages me from using the chat. I've read that you can type /linehistory off to disable this feature but this command is not recognized. So I have no choice but to uninstall this BTTV because this situation is simply unacceptable. Btw, it would also be unacceptable if I needed to type this command every time I opened a tab.

Suggestions:
-Don't scroll to past messages if the user hold the up-arrow, only if he presses the up arrow while already at the top of his message.
-Let the user get back to his draft by pressing down when the latest message is selected. This is absolutely essential.
-Make the linehistory feature something you can enable or disable in the settings.

**Comment by night** [comment]
We are not going to build a way to turn it off, sorry. If you want a draft feature then open a feature request for that specifically.

Also, holding down a key is not known to us. The browser actually treats that as you pressing it repeatedly.
