### ISSUE TITLE
Adding S/H sub categories might help improve the settings

### ISSUE THREAD

**Issue by 11Thor11** [night/BetterTTV#2733]
nightdev site said to go here for feature requests so i was thinking about adding sub categories settings it might help make it a little clustered as well it might be easier to find with show/hide function. because of a issue of it being too clustered you don't want to add too many things as well and make one giant list.

Chat
- Disable Localized Names
- Disable Name Colors
- Hide Chat Clips
- Hide Friend Activity in Chat
- Split Chat
- Show Deleted Messages
- Remove Deleted Messages

Emotes
- GameWisp Emotes
- BetterTTV Emotes
- BetterTTV GIF Emotes

also could be used for bits unless that's all one thing
top cheer, get bits by the sub button, bits in the chat box

**Comment by night** [comment]
This is already planned for the new settings screen.
