### ISSUE TITLE
Custom emotes stopped appearing

### ISSUE THREAD

**Issue by Pett1806** [night/BetterTTV#2736]
My custom emotes for BTTV no longer work, I can't see them or use them although BTTV is loaded and global emotes are also loaded. I tried clearing out cookies already and disabling my extensions, following the troubleshooting I read from other users. I saw something about showing the java or something with ctrl+shift+J but I couldn't really figure out what I could do there so I didn't mess around with it. 
![capturar](https://user-images.githubusercontent.com/33109682/32032731-73f49518-b9e7-11e7-9b2c-9140192cabb5.PNG)

**Comment by night** [comment]
I'm not able to reproduce this. Try disabling other browser extensions to see if it helps (it's possible some other extension is breaking ours).
