### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by Madgio** [night/BetterTTV#2737]
Hello,

Have not been able to see bttv emotes/gifs recently, such as PepePls, haHAA, etc. I have them enabled and I have tried disabling/reenabling them and refreshing the page, but no luck. Also, I am using twitch beta.

**Comment by DragonQuiz** [comment]
BetterTTV for the Twitch beta site is under development, so for the time being if you want to see BetterTTV emotes/gifs please switch over to the normal site.

**Comment by night** [comment]
BetterTTV should partially work on the Twitch beta site (it works in live chats, not VoDs or whispers yet). If you are not able to see them there then it could be another browser extension conflicting or an error occurring. If it's an error we need a console screenshot.
