### ISSUE TITLE
Chat Box Color Not Displaying Properly in Dark Mode when BTTV is enabled.

### ISSUE THREAD

**Issue by iiizzzunicorn** [night/BetterTTV#2738]
I've been having this issue since Twitch released their own dark mode to the site. I don't know what's happening, but BTTV seems to cause an issue where the chat still displays white when I'm in Twitch Dark Mode. I do not have BTTV Dark Theme enabled. And the glitch doesn't happen when I disable BTTV so I know the issue is related to it. 
<img width="1200" alt="screen shot 2017-10-27 at 5 35 21 pm" src="https://user-images.githubusercontent.com/33167640/32129529-411864c4-bb3d-11e7-973a-3ce9ed7b80cd.png">

**Comment by sparcut** [comment]
Disable Twitch dark theme and use BTTV dark theme for the time being, it is practically the same.

**Comment by TeaWallet** [comment]
Well I want to have the twitch dark mode not the BTTV one it's wayy to dark
The twitch one has this little purple touch to it

**Comment by iiizzzunicorn** [comment]
@TeaWallet Agreed. Dark Theme on BTTV used to be okay, but ever since Twitch made a new layout, the grey does not look good matched up with the new dark purple. The dark purple blends in so much better. BTTV should really fix this issue.

**Comment by night** [comment]
Use the Twitch beta site. The old site with BetterTTV will not receive feature changes, only bugfixes (and this is not really a bug).
