### ISSUE TITLE
This annoying bug

### ISSUE THREAD

**Issue by TeaWallet** [night/BetterTTV#2740]
Every time I turn on BetterTTV the chat turns white
I want to have the original twitch dark theme not the custom BetterTTV one because It's too dark
![glitch_twitch](https://user-images.githubusercontent.com/33190965/32140668-72d07d94-bc82-11e7-92e9-6ccc3c105199.PNG)
IS there a way to have the original twitch dark theme applying on my chat without having it turned white???

**Comment by night** [comment]
You would need to use the Twitch beta site. We only will support our legacy dark theme on the non-beta site (it's too much work to refactor for something going away soon).
