### ISSUE TITLE
Name Color(s) coming up Incorrectly with BTTV Enabled (Image Included)

### ISSUE THREAD

**Issue by Crystallyne** [night/BetterTTV#2743]
I'm picky about the color of my Username in chat.  I have it set for a light grey (#CCCCCC) and I know for a fact that other people see it as that color.  However, for me, my name always comes up as a dark grey!  I'm pretty sure BTTV is messing with other people's name colors as well, but I have no way to confirm that without bugging a bunch of people.

This probably seems like a small thing, and silly to complain about.  But it really is starting to irritate me!  I thought it was because of Twitch Beta, but I have disabled that and still having this problem.  The only way to fix it is to remove BTTV from my browser.  (I'm using Chrome on Windows 10.)

I have searched the settings thoroughly, and I can not find an option that might affect this.  So I can only assume that this is a bug.

EDIT: So...in the course of writing this message, I had temporarily removed BTTV from my browser.  After submitting it, I reinstalled it, and was back on the Twitch page.  ...My name is now coming up with the correct color.  O_o  I...guess that was all I needed to do to fix it?  Hopefully this permanently fixes the problem...

EDIT 2: Sure enough, the next day I log back into Twitch after restarting my computer, and the issue is back.  I also figured out a way to compare name colors side by side using 2 different web browsers.  The screen shot below shows "without BTTV" on the left, and "with BTTV" on the right, and I've included arrows pointing out the name colors that are being altered by BTTV.  (Please let me know if the image doesn't come up.)

![image](https://user-images.githubusercontent.com/32418385/32359333-96370b78-c00a-11e7-9076-1118134bec33.png)

**Comment by Nareese** [comment]
BTTV has always included a feature which modifies name colors for readability based on the dark or light theme, to prevent, in the most extreme cases, unreadable white names on white background or black names with black background, but it also shifts other colors.  You are correct that there is no setting to change how this operates, but it is intended behavior, and not a bug.

**Comment by Crystallyne** [comment]
Thank you for the response, Nareese.  Is there any way to add this as an option that we can turn on and off?  Even with that as a feature, I still get names I can't read, and I've gotten used to it.  I'd personally rather choose whether to have this feature on or off.

**Comment by night** [comment]
There looks to be a conflict between Twitch's dark theme and ours. Try disabling theirs and enabling ours. This will eventually be fixed.

**Comment by ltdowney** [comment]
I am disabling BetterTTV because of this functionality. The animated emotes are fun, but unconfigurable, undesired modifications to the user experience are not.

**Comment by pavelnazimok** [comment]
I also just installed BTTV and got confused with my custom color being changed. I think there should at least an option for this. I want to see the colors as it is and not how BTTV decided to show them.

@night Switching color themes doesn't achieve anything. So it doesn't seem like it got 'eventually fixed' during more than the past 3 years.
