### ISSUE TITLE
Incoming raid message does not display with BTTV

### ISSUE THREAD

**Issue by petergyang** [night/BetterTTV#2744]
I work at Twitch - the incoming raid chat message for the feature we launched today does not display if a user has BTTV activated. 

https://help.twitch.tv/customer/portal/articles/2877820

![image](https://user-images.githubusercontent.com/2383268/32357092-c1f10c0a-bff6-11e7-9682-1343386b4773.png)

**Comment by night** [comment]
I think we discussed this and it turned out it was not BetterTTV causing this behavior. Please comment if this is not the case.
