### ISSUE TITLE
BTTV Emotes Randomly Stop Working In VoDs

### ISSUE THREAD

**Issue by TheRealDannyyy** [night/BetterTTV#2745]
**Useful Information:**
- Windows 8.1 (64bit)
- Chrome v62 / Firefox v56.2
- BTTV v7.0.29
- VoD Example: https://www.twitch.tv/videos/187110623
- Twitch "Non-Beta" Version

**Problem Description:**
I've noticed that BTTV Emotes sometimes randomly stop working in VoDs. 
Same as in issue #2729, I have to restart the Browser or my PC to get them back to work.

**Console Log:**
![bttverror](https://user-images.githubusercontent.com/15656049/32412646-5d8e5b1e-c1fe-11e7-9bbb-91bfce2faf4e.PNG)
_*This is everything I could find on my own, will provide more if requested._

**Comment by runer112** [comment]
I don't get the console error seen by @TheRealDannyyy, but this same issue happens to me. Windows 10, Chrome 61, BTTV v7.0.29, *both* beta and legacy twitch VODs.

**Comment by Daanial11** [comment]
Hey @TheRealDannyyy thanks for referencing me, I get the same exact console error when this issue occurs.

**Comment by TheRealDannyyy** [comment]
@runer112 Thanks for the info. Hard reloading works but I think it would be better if we'd get a "hard reload" option inside BTTV itself.

@Daanial11 Np, I hope we'll get a response from the Dev's soon.

**Comment by night** [comment]
We are only going to be updating BetterTTV for the new Twitch site, and will be removing legacy site support soon. VoD chat support in BetterTTV for the new Twitch site will be released later today.

**Comment by TheRealDannyyy** [comment]
@night Thanks for the heads up, will review the fix in the new version.
