### ISSUE TITLE
BTTV not loading

### ISSUE THREAD

**Issue by Fleximex** [night/BetterTTV#2747]
I got a PC where I can't get BTTV to load whatever I do. I'm on Chrome and reinstalled it (also different versions) multiple times. Used incognito mode. Disabled all other extentions. Used the userscript version of BTTV. None work.

No emotes; no settings menu.

I get the following error in the console:

index.js:118

Uncaught TypeError: ["betterttv in apply","wrapped(betterttv)"].contains is not a function
    at Object.shouldSendCallback (index.js:118)
    at o._send (raven.js:1557)
    at o._processException (raven.js:1344)
    at o._handleStackInfo (raven.js:1250)
    at o.captureException (raven.js:388)
    at a (raven.js:324)

Thanks in advance.

**Comment by night** [comment]
I am not able to reproduce this error. Try disabling other browser extensions as one might be conflicting with ours.
