### ISSUE TITLE
Can't find better tv emote menu

### ISSUE THREAD

**Issue by irenelinlin** [night/BetterTTV#2750]
I've been using bettertv emote for a while on twitch, but today I can't find the emote menu, and I checked the setting, the bettertv emote is on, can you check what's wrong with that?
![_20171107210853](https://user-images.githubusercontent.com/33454842/32495270-f70b18e2-c3ff-11e7-8846-9889a2920693.jpg)
![_20171107210916](https://user-images.githubusercontent.com/33454842/32495271-f73af45e-c3ff-11e7-8239-78e3f0ca198b.jpg)

**Comment by CrystalCastles** [comment]
Twitch began to roll out the new site rewrite (go.twitch.tv), and some features haven't been implemented yet. Switch back to the legacy site for now if you want all functionality.
![legacy](https://user-images.githubusercontent.com/5546927/32531915-b5d6b9a2-c414-11e7-99e6-717bc72e2335.jpg)

**Comment by night** [comment]
The emote menu does not yet function on the new site. As is stated in the settings, we are aware of missing features.
