### ISSUE TITLE
time frame?

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2751]
do you know when you are going to have the full bttv working for the new version of twitch?

**Comment by night** [comment]
Nope. I only work on this in my spare time. Other people haven't volunteered to help port over old features, so it's gonna be done when it's done.

**Comment by ahjorth** [comment]
@night You should stick a notice on the readme or something. Maybe a list of what needs to be changed, what the progress is etc. If BTTV needs a complete overhaul, maybe a contribution guide to let people know what your ideas are

**Comment by night** [comment]
@ahjorth there's a todo of modules that need to be ported at https://github.com/night/BetterTTV/blob/new-twitch/src/index.js#L9 .. anything in master is old twitch
