### ISSUE TITLE
[beta/new site] Word "watch" changing to blank space when typed by user in firefox

### ISSUE THREAD

**Issue by aroboto** [night/BetterTTV#2752]
When you type the word "watch" no quotes it appears as a blank space when using Firefox 56.0.2 and on the new beta/re-written site. Other users see the word as normal.

![hlvqqhb 1](https://user-images.githubusercontent.com/22084203/32588848-353ca176-c509-11e7-86b0-f70f0a71d505.png)

![uthjbou 1](https://user-images.githubusercontent.com/22084203/32588911-8952119c-c509-11e7-8e0e-655219266dc1.png)

**Comment by night** [comment]
happens without BetterTTV installed, making it a Twitch bug.

![image](https://user-images.githubusercontent.com/2942184/32599699-28d4a7ba-c4f2-11e7-85b1-7b542e3837fc.png)
