### ISSUE TITLE
BetterTTV Emotes are not showing

### ISSUE THREAD

**Issue by JeanBG** [night/BetterTTV#2756]
I enabled the BetterTTV Emotes on Twitch, however I am not able to see which are available to use, both emotes and gifs. The emotes do show in chat, but the old tab that could be opened with all of the emotes is no longer there.

**Comment by Faithless74** [comment]
Same here. Pls help!

**Comment by night** [comment]
The emote menu does not yet function on the new site. As is stated in the settings, we are aware of missing features and they will eventually make a return when we have time to port them.
