### ISSUE TITLE
Button for twitch emote menu not showing

### ISSUE THREAD

**Issue by REALSaltLakeLOL** [night/BetterTTV#2757]
The little button I usually click to open up the bttv emote menu is not showing up. It was there yesterday, but it's not there now. I've done nothing different, haven't installed any new addons to my browser. Nothing.

I have tried disabling and enabling the app. Uninstall/reinstall, and it's still not showing up. I have made absolutely sure it's turned on in settings. I've gone through and turned settings on and off over and over, refreshing the page each time. Nothing seems to be working.

**Comment by night** [comment]
The emote menu does not yet function on the new site. As is stated in the settings, we are aware of missing features and they will eventually make a return when we have time to port them.
