### ISSUE TITLE
Feature: Display all messages on the bottom from the start

### ISSUE THREAD

**Issue by Broxzier** [night/BetterTTV#276]
An option to:
Instead of having to build up from the top to reach the bottom, new chat messages, including the very first, will be displayed on the bottom of the chat, and 'pushed' upwards whenever there comes new ones (much like most chats in games work).
Currently when a chat message is received, it appears at the top by default (left image) and builds down, while user messages could also be building up from the bottom (right image). In this case the "Welcome" message was not moved down, though this wouldn't be a problem.
![btt_suggestion](https://cloud.githubusercontent.com/assets/9705046/6565575/53eeb9aa-c6b1-11e4-93b0-db91bf3e03c9.png)

**Comment by night** [comment]
Messages already build up from the bottom.. Or am I missing something?

**Comment by Broxzier** [comment]
As seen in the screenshot, they appear at the top first, and build up to the bottom, then it scrolls down automatically. What I was suggesting is that from the very beginning the chat messages would appear on the bottom (with the white space on top) instead, just like most chats in games have.
