### ISSUE TITLE
The "split chat" option looks ugly with the new layout.

### ISSUE THREAD

**Issue by Dewku** [night/BetterTTV#2761]
The split chat option is one of my favourite options of BTTV, it makes reading the chat easier and you can easier differentiate between two messages. With the new Layout however it looks uglier than before. With the old layout, we had one grey and another grey, which was slightly darker. In the new layout, we have light purple and dark purple, and I think the colors are too different. What I think should be done is make one of the colors lighter or darker, so that they are more similar to each other.

**Comment by gendalv** [comment]
I can't read the light lines at all  in the dark theme..

**Comment by dagonar** [comment]
Are you refering to this bug? #2869 
There is a PR for it already.
