### ISSUE TITLE
[Feature Request] Subscription Timer

### ISSUE THREAD

**Issue by Ekiph** [night/BetterTTV#2762]
It would be nice to be able to see how long you have left on a subscription, on the channel that you are already subbed.

It could be located on the drop down that you get when you press the Subscribe Button.

**Comment by LukeDavies367** [comment]
There is a way;
https://www.twitch.tv/subscriptions
Benefit Info & it should tell you like my sub runs out to someone on

"Benefits will end on: Dec 10, 2017"

**Comment by night** [comment]
Twitch now includes this information in the sub dropdown.
