### ISSUE TITLE
[Feature Request] Original BTTV Darkmode

### ISSUE THREAD

**Issue by TheHerbMon** [night/BetterTTV#2764]
It seems Twitch Beta is officially rolling out, and myself and others I know really don't like the official Twitch "Dark Mode". I'd like to see the original BTTV Dark Mode return, personally I find it much easier on the eyes rather than this purple mode twitch came up with.

**Comment by recon88** [comment]
Yes please! I just got the new update and it hurts my eyes. I even avoided switching to Twitch's new layout to keep the previous BTTV dark mode. Another toggle would be nice so we can decide what's better for us.

**Comment by Perska** [comment]
From [BetterTTV on Twitter](//twitter.com/BetterTTV/status/930540465694294016):

> Our dark mode won't be making a return, unfortunately. It was always a PITA to maintain, and with 
Twitch having their own there's not enough reason to have one. Deleted messages module is not yet ported.

So I guess that's not coming back

**Comment by recon88** [comment]
Well, that was the only reason I had BTTV. Removing it then. Thanks for the link.

**Comment by TheHerbMon** [comment]
Oh no.. that's rather disappointing. Looks like I'll have to bring the issue up with Twitch somehow. The purple mode really is bad, it adds unnecessary blue light into a mode that's supposed to keep blue light to a minimum.

**Comment by recon88** [comment]
@TheHerbMon I just discovered the Chrome addon "Stylish" which provides restyling for sites.
There's a dark/black style for Twitch available. It's not that dark but better than the purple eye hurting thing: https://userstyles.org/styles/140262/dark-twitch-by-norwin

**Comment by LiquidWater** [comment]
yeah dark twitch is super ugly after they deployed the beta and broke bttv.

**Comment by Senpos** [comment]
@Perska Oh, sad news. I liked that Dark Mode so bad. :(

**Comment by TheHerbMon** [comment]
@recon88 Yeah I use stylish for some things, however on Twitch it's buggy. Good news though, FrankerFaceZ released a grey mode and you can have it enabled alongside BTTV, it even has options to bring back BTTV-like split chat!

**Comment by recon88** [comment]
@TheHerbMon The style I linked above is working fine for me with BTTV. No issues at all :)

**Comment by TheHerbMon** [comment]
@recon88 The whisper window has no background, it's just transparent.

**Comment by recon88** [comment]
@TheHerbMon Oh you are right. I'm never using whispers so I didn't notice that. But am sure the dev will fix it if someone reports it.
I guess it's up to you what you prefer. For me it's stylish because I don't want another extension like bttv installed.

**Comment by SaiyanOfDarkness** [comment]
@recon88 I had taken that style and modified my own version.  Which was more plain looking without the background image, and it removed the channel name above the chat, as well as top cheer automatically.

https://i.imgur.com/A0jhjGh.png

https://pastebin.com/jjLezz0b

**Comment by recon88** [comment]
@SaiyanOfDarkness looks nice :) I modified it as well for my needs and am pretty satisfied with the result. But thanks for sharing!

**Comment by SaiyanOfDarkness** [comment]
@recon88 Yeah only problem is.. twitch keeps changing their theme so I have to go in and manually make adjustments.  I had everything the way I liked it, but they changed for example.. ".pinned-cheer__bounding-box"  to something like "pd-y-1.pd-x-2.flex-nowrap.flex-row.flex.pinned-cheer__headline--clickable.pinned-cheer__headline"

Makes it less enjoyable making a theme for this site.  It's either use their shitty purple look or don't go there anymore.

**Comment by recon88** [comment]
@SaiyanOfDarkness well I have no issue with changing the theme every now and then :D Still better than looking at the shitty puprle. Guess that's why the BTTV devs are no longer in the mood to keep old dark theme.

**Comment by night** [comment]
I don't have time to maintain a custom dark theme and I personally don't mind Twitch's, so this is a wontfix.
