### ISSUE TITLE
Emote menu button missing

### ISSUE THREAD

**Issue by TenofClubs** [night/BetterTTV#2767]
Hello BetterTTV devs,

Relieved to see that you guys have updated to stay with the changes on Twitch but I have two questions:

1)Where'd the emote menu go? There used to be a settings option for enabling the button, but it's not there either. 

2). I want to donate/support but I can't afford BTTV Pro. You guys used to accept paypal, right? Where do I go for that?

**Comment by xgerhard** [comment]
1) Duplicate #2757 
2) I think BTTV pro is the only way at the moment, maybe try sub for a single month?

**Comment by night** [comment]
We don't accept donations, sorry.
