### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by moishinetzer** [night/BetterTTV#277]
Hello there! i had an idea! 
If someone gets timed-out or if the chat is in slow mode, you get a notification when you can speak again!
Also if you get banned, when you get unbanned you get a notification.

I really like BTTV and really appreciate all of your hard work, after all i am a programmer myself!
if you like the idea it would be great to know!
Thank you again!

**Comment by night** [comment]
There's no hooks that tell us when a timeout or ban ends, so it's not possible to offer this as a feature.
