### ISSUE TITLE
Host button gone with update???

### ISSUE THREAD

**Issue by LordNemesis25** [night/BetterTTV#2776]
Since last update, the host button is no longer showing up. Can we get this fixed asap? this is one of the main things I use this for.

**Comment by Senpos** [comment]
Duplicate #2766 

For now just type `/host channel` in your chat.

**Comment by LordNemesis25** [comment]
I know that but it just makes life easier. Do we have any idea when this might be repaired?

**Comment by night** [comment]
There's no ETAs for feature ports. I work on this in my spare time, which is not much time. Follow #2605 for updates.
