### ISSUE TITLE
[Feature Request] Default Options Menu for Extension

### ISSUE THREAD

**Issue by mutely** [night/BetterTTV#2779]
Instead of having to go to twitch to change your options, why not have options configured on the extension itself. Meaning...your settings won't change when you clear cookies, history, etc.

**Comment by Senpos** [comment]
Also, syncing settings would also be nice. At least in the way its done in [uBlock ](https://github.com/gorhill/uBlock/wiki/Cloud-storage)(manually upload / download via cloud storage)

**Comment by night** [comment]
The reason we use localstorage and in-site settings is so we don't need to maintain browser extensions. Everything is updated via our CDN at present, and we have no plans to change this (it's helpful when we need to expedite updates).
