### ISSUE TITLE
emotes not working

### ISSUE THREAD

**Issue by imransamsuddin** [night/BetterTTV#2782]
i refreshed my chrome so many times . the bttv emotes doesnt work

**Comment by HyperActiveHub** [comment]
Have you checked your bttv settings? they might have reset, which means that you have to re-enable emotes and gif emotes.

**Comment by imransamsuddin** [comment]
i always check my bttv settings whenever i open my twitch . maybe its because of my Adguard Adblocker ?

**Comment by HyperActiveHub** [comment]
i wouldnt think so. I thought i had this problem, but it turned out that it was FrankerFaceZ emotes that wasnt working, obviously, since i hadn't installed the chrome add on.

**Comment by imransamsuddin** [comment]
i really dont know whats the problem . sometimes the emotes working and sometimes the emotes doesnt work .

**Comment by HyperActiveHub** [comment]
Huh. Sorry man, cant help you.

**Comment by night** [comment]
Unless you have reproduction steps there's unfortunately nothing we can do.
