### ISSUE TITLE
Emote menu 

### ISSUE THREAD

**Issue by PhishingBear** [night/BetterTTV#2785]
I can NOT get BTTV emotes. Yes i did go to Btttv menu the option for 
Emote Menu — Get a more advanced emote menu for Twitch. (Made by Ryan Chatham)
IT is NOT there in chat. at the top of menu it says
🚨 🚧 ⚠️ BetterTTV for Twitch's new site is incomplete. We know things are broken/missing. ⚠️ 🚧 🚨
How long will this be like this? What do i have to do to get the BTTV emotes back????
?????

**Comment by night** [comment]
Emote menu was just ported tonight.

**Comment by PhishingBear** [comment]
Thank You Soooo, much.....
Phishing Bear 

    On Sunday, November 19, 2017 11:20 PM, Zack <notifications@github.com> wrote:
 

 Emote menu was just ported tonight.—
