### ISSUE TITLE
BTTV channel emotes trigger highlight by their channel name

### ISSUE THREAD

**Issue by xgerhard** [night/BetterTTV#2786]
If someone uses one of your BTTV channel emotes, it will highlight the chat message and added to the pinned messages. Looks like its looking for words to highlight in the full emote message:

"$emotecode 
Channel: $channel
BetterTTV Channel Emotes"

https://imgur.com/wwwTyrR

**Comment by night** [comment]
hmmmm

**Comment by night** [comment]
pushed a fix for this
