### ISSUE TITLE
API & fetching channels

### ISSUE THREAD

**Issue by sparcut** [night/BetterTTV#2789]
I'm not sure if you mind, but the BTTV api has and is being used outside of BTTV. (I assume you're aware of this) Firstly, how do you feel about this?

Secondly, would you able to have the ability to fetch multiple channels per request?

For instance, the example I was thinking of was the [`IPTV-Extension`](https://github.com/Strimmerz/IPTV-Extension), it allows users to load BTTV emotes from multiple channels. However, this means it will query there is a shit ton of requests that can be limited if there was the ability to fetch multiple channels.

e.g.
- The extension is for Ice Poseidon's YouTube stream.
- Requests are made when a client with the extension loads Ice's chat.
- By default, there are 6 channels (more can be added or removed in options).
- Ice viewers have varied a bit, but let's say there are 4,000 unique viewers that have the extension.
- So assuming they have default options (most would), and they only loaded the page once, the number of requests would be 4000*6 = **24,000** requests

So, having the ability to query multiple channels would save 20,000+ requests per Ice stream.

And that's being modest. Would be exponentially more when he gets more viewers (hasn't been doing very well recently), then also doesn't account for all the time's people have loaded the channel/chat when not streaming, to use chat or check if live etc.

Anyway, your thoughts on the API and channels would be appreciated.

**Comment by night** [comment]
Our API is not documented and is not for public consumption. Any use of it outside of our extension is unsupported and we will not take feature requests for it. We reserve the right to deny anyone access to our API at any time. If we feel there is abuse happening we will block access to our API.

**Comment by sparcut** [comment]
@night Is there any possibility of it being open in the future? Like, for instance, TwitchEmotes.com.
