### ISSUE TITLE
bttv disables custom username colors

### ISSUE THREAD

**Issue by kyodjinn** [night/BetterTTV#2801]
With bttv enabled, my username color changes to a default one.
![](https://screenshots.firefoxusercontent.com/images/d879de5a-fafa-4dd0-bfaf-91cb70ebdbb0.png)

When it's disabled, the correct color shows.
![](https://screenshots.firefoxusercontent.com/images/67960c9d-b910-4487-b774-589b81112c58.png)

**Comment by night** [comment]
you seem to be using a custom theme.. unfortunately we don't support custom themes and this is not fixable.

**Comment by kyodjinn** [comment]
What do you mean by custom theme? I'm only using the official Twitch dark mode. If you're talking about the custom color, all Twitch Prime users are able to choose specific color hex codes for their username.
