### ISSUE TITLE
Multiple Emote Menu's...

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2802]
Not sure what's causing it, but sometimes the Emote Menu isn't working when I click on it.. then when I click on the Settings gear .. I see multiple Emote Menu buttons.  Not sure if anyone else has seen this yet.

![image](https://user-images.githubusercontent.com/24264268/33239257-999797a4-d263-11e7-98fa-5e40c25600e6.png)

**Comment by night** [comment]
open an issue at https://github.com/night/Userscript--Twitch-Chat-Emotes/
