### ISSUE TITLE
BTTV doesn't work

### ISSUE THREAD

**Issue by Fl4me20** [night/BetterTTV#2808]
I've been using BTTV for 1 year by now, and I've never had problems, but today I was using it and after approximately 1 hour of using it, it just stopped working. I even tried restarting Chrome and my PC, but it didn't work.

**Comment by AllxHS** [comment]
having similar issues with bttv myself, my emotes wont work at all for bttv unless i run chat in legacy popout

**Comment by night** [comment]
dup of #2807
