### ISSUE TITLE
No longer works in any capactiy. (Firefox 57.0 Qauntum 64bit)

### ISSUE THREAD

**Issue by Alpha17x** [night/BetterTTV#2816]
BetterTTV does not appear to do anything outside of appearing in the addons list. It will install, it is not disabled as a legacy plugin, however, it does nothing.  No menu exists in association with the stream menu gear.

Uninstalled BetterTTV and purged all associated files, including the residuals left behind. Re-installed after a cold boot.  Same result.

I'm assuming Quantum is not supported yet.

**Comment by night** [comment]
dup of #2807
