### ISSUE TITLE
Christmas emotes don't overlap with global Twitch emotes

### ISSUE THREAD

**Issue by bladestorm91** [night/BetterTTV#2820]
For example IceCold overlaps fine with BTTV emotes, but for global emotes it just moves to the side.
Edit: It seems that FFZ conflicts with BTTV's Christmas emotes, while I wouldn't know where the fault would be, I would guess that it isn't anyone's responsibility to fix this conflict.

**Comment by DayBr3ak** [comment]
It's working fine for me. How do you use it? `Kappa IceCold` is perfect.

**Comment by night** [comment]
FFZ must change the DOM structure of the emotes, which is not something we support..
