### ISSUE TITLE
Theatre Mode not working correctly with left side chat enabled

### ISSUE THREAD

**Issue by JadeFoXx** [night/BetterTTV#2821]
Version: v7.1.5
Activating the theatre mode while having left side chat enabled shifts the player to the left, the left side of the player gets cut off by the chat and on the right side is a blank column (see attached screenshots).

![chrome_2017-12-01_17-18-21](https://user-images.githubusercontent.com/11271640/33492001-25bb3072-d6bc-11e7-8cd5-8229b2e23e52.jpg)

![chrome_2017-12-01_17-18-25](https://user-images.githubusercontent.com/11271640/33492038-4007c620-d6bc-11e7-83ae-2107657bd0e4.jpg)

**Comment by JulienComtois** [comment]
I'm having the same issue.

**Comment by Notjubby** [comment]
same issue.
