### ISSUE TITLE
Christmas emotes malfunction

### ISSUE THREAD

**Issue by Vltrykin1** [night/BetterTTV#2825]
Trying to use the temporary Christmas emotes, but they do not want to co-operate. 
![screenshot_13](https://user-images.githubusercontent.com/34176108/33509901-cf541672-d76a-11e7-8d00-fe4faa638e45.png)
This is the result I receive when I try to use the Christmas emote with a sub emote. I have tried re-installing BTTV and refreshing my cache, but neither of them have fixed this issue. I also can confirm it's both Legacy chat and Twitch chat that are having this issue.

**Comment by DayBr3ak** [comment]
Check if you do have another extension enabled (ex. FFZ); It conflicts with BTTV christmas emotes. Just disable that extension.

**Comment by wizjany** [comment]
More specifically, they aren't working on twitch.tv/<channel>/chat (e.g. when using popout chat), but are working on the normal channel page.

**Comment by night** [comment]
we are not supporting legacy twitch pages (including their legacy chat) for new features, sorry.

**Comment by wizjany** [comment]
Oh, i didn't even realize there were two different popout chats. That works, thanks.
