### ISSUE TITLE
Setting to disable the mini player

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2826]
Seems twitch is forcing the mini player on even if you have it turned off.  A option in BTTV to disable that would be welcome.

Thanks

**Comment by DayBr3ak** [comment]
#2830 add a pr for this.

**Comment by night** [comment]
![image](https://user-images.githubusercontent.com/2942184/33538271-24c73af2-d875-11e7-8ccd-3ed7ddf6f4b3.png)

this is a twitch setting. if they broke it you should file it as a twitch bug.
