### ISSUE TITLE
Disable Host Mode

### ISSUE THREAD

**Issue by miniberger** [night/BetterTTV#2829]
Disable Host Mode makes it so a streamer can no longer see their own panels on their channel to edit them as need be. This was not a problem before Twitch's API change. When i turn the extension off, or the host mode off, the panels return so this is an issue with the extension setting.

**Comment by DayBr3ak** [comment]
I Just tried to host somebody else with that option and it works. No panels disappear. 

I only use BTTV on twitch with chrome 62.

**Comment by night** [comment]
I'm not able to reproduce this issue. Please provide reproduction steps or we won't be able to assist you.
