### ISSUE TITLE
I don't really know if this is possible but..

### ISSUE THREAD

**Issue by gakiloroth** [night/BetterTTV#283]
IS it possible to have a little bar to see the current slowtime / r9k mode of chat ( for moderation purposes)? If this is already implemented (like the last request I made) sorry! Your extension helps ALOT. Thank you!

**Comment by night** [comment]
Since the status of slow mode and r9k mode is only emitted in chat when it changes, you would have to be in the room when a status is changed to see it. This isn't too practical, as the real use case for showing the status would be upon entry to a chat.
