### ISSUE TITLE
Hide whispers does not fully hide the button in Theater mode

### ISSUE THREAD

**Issue by jwannebo** [night/BetterTTV#2839]
It leaves the "bottom" CSS attribute set to a non-zero value on the player div. This leaves a black bar at the bottom of the player in theater mode.

`.video-player--theatre.video-player--logged-in .video-player__container `
is set to 
`4rem`

**Comment by night** [comment]
this is fixed via #2845

**Comment by dfarley1** [comment]
I'm running into this issue again. I have the "hide whispers" setting enabled and tried "Clear Cache and Hard Reset" the tab. Here's a pic of the offending div:
![twitch_black_bar](https://user-images.githubusercontent.com/5204693/105102552-cc40e800-5a63-11eb-8f17-3e9b87f8e7b1.png)

Setting `.video-player__container--theatre-whispers` to `bottom: 0rem` fixes the issue.
