### ISSUE TITLE
BTTV Not Capitalizing Chat Usernames

### ISSUE THREAD

**Issue by EchoFTW** [night/BetterTTV#284]
I just realized that the chat isn't capitalizing Usernames like it should. Running Version 41.0.2272.89 m of Chrome with the latest version of BTTV (6.8R32). 
![screenshot_4](https://cloud.githubusercontent.com/assets/11496247/6660815/c5b05f88-cb77-11e4-9835-91671e0c0e7e.png)

The N in my name as well as the FTW should be capitalized normally.

**Comment by night** [comment]
This was a result of the socket servers being down. Display names should be functioning normally again.
