### ISSUE TITLE
[Feature Request] Emote Predictive Typing

### ISSUE THREAD

**Issue by caznosaur** [night/BetterTTV#2841]
It would be cool if while typing the name of an emote in Twitch chat, a small pop-up with a preview list of the names and thumbnails of the emotes available to the user would come up based on the predicted results of what the user has typed. That way a user can quickly see if the emote they want to use is available in the channel they are in or if they spelled it incorrectly. Users also might be able to discover new emotes this way.

**Comment by DayBr3ak** [comment]
Twitch kind of does this when you type `:<emote>`. But you don't get bttv emotes

**Comment by night** [comment]
tab completion is in master, and twitch does autocompletion with you use a sentinel value like `:` and `@`
