### ISSUE TITLE
Emote menu favorites line wrapping

### ISSUE THREAD

**Issue by sparcut** [night/BetterTTV#2842]
Currently emotes in favourites section are hidden when adjusting depending on how wide emote menu is expanded. It would be more intuitive for favourite emotes to line wrap, since its a bit counter-intuitive to have to expand emote menu if you have. Since favourites are meant to kinda me like "quick access".

Can't remember if this is the same menu used before Twitch's move to react, but I'd be able to look at rebuilding it if you guys are busy and not already working on it.

<hr>

**Edit**: Just saw that it's not BTTV's, it's a [Userscript Emote Menu](https://cletusc.github.io/Userscript--Twitch-Chat-Emotes/). Are you guys going to need to make a custom BTTV emote menu, you know if they going to update it?

**Comment by cletusc** [comment]
I'm planning on updating it (I'm the author) but don't currently have the time to fully review all changes that @night has proposed to get it functional. My time is very limited lately.

**Comment by sparcut** [comment]
@cletusc Do you have any info regarding the cause of the current bugs. Would be more than happy to contribute.

**Comment by night** [comment]
This would be a feature request on the emote menu repo, not here.
