### ISSUE TITLE
Offline followed channels no longer hidden

### ISSUE THREAD

**Issue by dansa** [night/BetterTTV#2853]
Looks like twitch changed the href on offline followed channels from linking to `/videos/all` to `/videos/[latest vod number]`

**Comment by night** [comment]
I am not seeing this on my end. Maybe Twitch was experimenting with it and turned it off?

**Comment by dansa** [comment]
No idea, but it's still happening for me. 

![image](https://user-images.githubusercontent.com/5786317/33832057-c9ca8db4-de7a-11e7-8c7a-9883f6014f5d.png)
