### ISSUE TITLE
BTTV Chat Username Capitalization Broken?

### ISSUE THREAD

**Issue by ImPizzaboytony** [night/BetterTTV#286]
Default twitch chat does not automatically capitalize all the proper letters that it normally should. It used to be with BTTV installed, the letters in names that should be capitalized would normally automatically capitalize. When BTTV was updated within the past update or two, the capitalization broke. For example, the proper capitalization in my name is ImPizzaboytony. Normally BTTV would know that and capitalize it, but recently it was left it as Impizzaboytony. This is really annoying because it made reading names in my chat ALOT easier with the letters capitalized when I am streaming. This is in another chat of what I mean. http://prntscr.com/6hks9o

**Comment by vendethiel** [comment]
#284
