### ISSUE TITLE
My Twitch Chat is not working propertly... 

### ISSUE THREAD

**Issue by Sallymera** [night/BetterTTV#2867]
Here is the Screen on imgur ... i dont know how to repair it... https://imgur.com/a/NLTV7
Its not readeable or how to say it ...

**Comment by DAOWAce** [comment]
Chat splitting option doesn't seem to respect dark mode anymore.

New update from the 11th just came through.  Was wondering wtf happened to Twitch.

Hope this can get hotfixed quickly.. makes chat pretty much unreadable, and using twitch not in dark mode is NotLikeThis
