### ISSUE TITLE
Chat Split bug

### ISSUE THREAD

**Issue by Lavassin** [night/BetterTTV#2869]
![c64777a5cb0438e89a570ba124df3fd1](https://user-images.githubusercontent.com/32739138/33967160-49565cfa-e030-11e7-9d92-3f3640d6ae8d.png)

**Comment by xgerhard** [comment]
Duplicate #2867

**Comment by Lavassin** [comment]
That was from a month ago. Wasn't sure if it was the same thing

**Comment by beachcamp** [comment]
It's not the same thing, although he is correct there is a pull request that should address these issues.
