### ISSUE TITLE
name highlight visual glitch

### ISSUE THREAD

**Issue by edman3d** [night/BetterTTV#287]
when someone's comment mentions your name and lights up red, it now also changes the background color of the text to like, lime green and the text to white making it impossible to read (unless you select it to invert the colors).

**Comment by teak** [comment]
the text should turn white.. Can you provide a screenshot?

**Comment by edman3d** [comment]
I will provide one later tonight after work

**Comment by edman3d** [comment]
follow up on that text glitch, I haven't recently installed any new
extensions. Browser is Chrome (haven't tested elsewhere) . img1:
http://i.imgur.com/z0327ws.png  img2: http://i.imgur.com/Je2Odnh.png

**Comment by night** [comment]
There's two buttons below the textbox which do not belong to BetterTTV. Have you tried disabling other addons that affect Twitch and seeing if you still have this issue?

**Comment by edman3d** [comment]
Yup, it was some twitch face mod that I installed because I was sick of
seeing the face code for all the new faces or whatever. Sorry to bother,
and thanks for the great extension.
