### ISSUE TITLE
Split Chat Bug

### ISSUE THREAD

**Issue by StrykerSwat** [night/BetterTTV#2871]
While "Split Chat" is enabled some messages in chat are while and others stay black while I have "Dark Theme" enable.
![split chat problem](https://user-images.githubusercontent.com/34526077/33969405-5cef0466-e02a-11e7-84ba-6fc76e149adc.png)

**Comment by Quostin** [comment]
I am also having this problem. Had to switch to turning the split chat to off...

**Comment by Stoupedog** [comment]
Duplicate of #2867
