### ISSUE TITLE
Fullscreen mode is not full screen when BTTV is enabled

### ISSUE THREAD

**Issue by HellGreen** [night/BetterTTV#2874]
For some time I have had a problem where my Twitch streams are not fully fullscreen. I have narrowed it down to being an issue with BTTV when I use theatre mode.

My browser is Chrome (Version 63.0.3239.84 (Official Build) (64-bit))
BTTV is v. 7.2.1
The issue has been present for a few months.
It is present on both my main monitor, my secondary monitor and my living room TV. All displays use 1920x1080 as resolution. Main monitor runs at 120Hz, rest at 60Hz.
Note: The issue only appears if I'm using Theatre Mode in BTTV. If I am in normal mode and go fullscreen, it works as expected.
To enter fullscreen mode, I double click the video, but it also fails clicking the fullscreen button in the player.

The full screen mode has different results on each monitor.
Main monitor: borders appear left, right and bottom (https://i.imgur.com/1UgqQjj.jpg)
Secondary monitor: borders appear top and bottom (https://i.imgur.com/wHVcnVE.jpg)
TV: borders appear bottom, maybe one side too - i don't have a screenshot atm.

Please let me know if you need any further info.
Thanks,

**Comment by night** [comment]
what other settings do you use on BetterTTV? we don't really modify css much to cause issues like that

**Comment by HellGreen** [comment]
I am attaching my settings file. I have enabled/disabled several settings, but I don't recall which ones. Would you like me to reset my settings, and see if that helps the issue?
[bttv_settings.zip](https://github.com/night/BetterTTV/files/1563288/bttv_settings.zip)

**Comment by night** [comment]
You have no settings enabled from your backup that would cause issues, and I cannot reproduce any issues. It might be an issue with Twitch's players such that you still have theater mode enabled when going fullscreen. As this would be a player issue for them it's not something we can fix.
