### ISSUE TITLE
Can't access BetterTTV via embedded chats

### ISSUE THREAD

**Issue by Degree234** [night/BetterTTV#2878]
Some time ago, I forgot when, I have been unable to access the settings for BetterTTV when I am in a website other than Twitch that has the chat embedded. I have been able to do this before but now I can't. I can't even access the emote list because it's not there. Now if I go to twitch then everything works fine, but when I go to another website nothing works quite right

**Comment by night** [comment]
the emote menu packaged in the legacy extension was the wrong version. should be fixed.
