### ISSUE TITLE
Press Esc to clear chat input box

### ISSUE THREAD

**Issue by ryanbraganza** [night/BetterTTV#288]
This is a feature request.

If I have some text in the chat input, it would be nice to be able to quickly clear it by pressing Esc.

e.g. if I start autocompleting a name, I press Esc once to dismiss the popup and then press Esc again to clear the chat input

I could try and put together a PR for this, if you agree that it's something you'd merge.

**Comment by night** [comment]
I'm not sure that escape provides any extra value than ctrl/cmd + a
