### ISSUE TITLE
Chat pausing is broken

### ISSUE THREAD

**Issue by PVCmechanic** [night/BetterTTV#2880]
Pausing chat only works while the chat window has not reached full capacity.

**Comment by night** [comment]
this is really a twitch issue, not really ours

**Comment by saurfangg** [comment]
Sorry to necro this, but are you sure? On Firefox, without BTTV I'm able to pause by scrolling up the chat but if BTTV is enabled it doesn't seem to work. Is there something that BTTV does with chat interaction that might interfere? Only thing I enable on BTTV is GIFs really.
