### ISSUE TITLE
Opera's Plugin not working

### ISSUE THREAD

**Issue by Iztooi** [night/BetterTTV#2889]
Hello,
I tried to post on the nightdev forum but I received no reply.
Maybe here it will have more success.
I'm using the latest version of Opera and BetterTTV version 6.8 (despite the website shows that the latest version is 7.1.9) but I don't see the plugin working.
I noticed that it stopped working shortly after twitch upgraded their site replacing it with the beta version.
Can you check what's wrong?

**Comment by night** [comment]
6.8 is the latest extension version, and it should work just fine
