### ISSUE TITLE
Bunny Ears Emoticon for Easter

### ISSUE THREAD

**Issue by hipstercamelhumper** [night/BetterTTV#289]
Giving that Easter is coming up, I think it would be a fun idea to incorporate the same kind of feature as the SantaHat during the holidays, but instead with bunny ears on top of the emotes.

**Comment by night** [comment]
If someone provides the emoticon in 28x28, 56x56, and 112x112 sizes we may consider it.

**Comment by hipstercamelhumper** [comment]
Here is the image: http://imgur.com/a/8zDa1
Hope you consider the idea, Twitch would love it OpieOP
|   |
|   |  |   |   |   |   |   |
| Imgur0 Points 0 ups 0 downs  |
|  |
| View on imgur.com | Preview by Yahoo |
|  |
|   |


Thank you for your time.  


     On Wednesday, March 18, 2015 9:02 AM, Night <notifications@github.com> wrote:
   

 If someone provides the emoticon in 28x28, 56x56, and 112x112 sizes we may consider it.—

**Comment by Nathsters** [comment]
What would the text for the emote be?
