### ISSUE TITLE
BTTV Emotes don't work

### ISSUE THREAD

**Issue by Libr3** [night/BetterTTV#2892]
Global emotes work, just not the channel emotes and gifs, the console is giving the following errors:
![capture](https://user-images.githubusercontent.com/34953291/34451091-40beff2c-ed67-11e7-9d3e-e2a927eaeb35.JPG)
![capture1](https://user-images.githubusercontent.com/34953291/34451093-4813d720-ed67-11e7-85c1-4e774cffc45e.JPG)

Everything else works.

**Comment by night** [comment]
none of those errors are ours. additionally, i cannot reproduce this

**Comment by Libr3** [comment]
Ok thanks, it's probably my internet.

On 5 Jan. 2018 11:06 am, "Zack" <notifications@github.com> wrote:

none of those errors are ours. additionally, i cannot reproduce this

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/night/BetterTTV/issues/2892#issuecomment-355445282>,
or mute
the thread
