### ISSUE TITLE
Incorrect work of betterttv

### ISSUE THREAD

**Issue by whitedma** [night/BetterTTV#2894]
Hello. Since last update of twitch, betterttv has losted almost all its functions like autocomplete of smiles using the 'tab' in general. In addition, there is no more button 'betterttv settings' on directory page on twitch. To use it I must open my profile's page. A changelog contains next important update: 
'Changelog
Version 7.1.9 (Dec 14, 2017)
fixes issues caused by Twitch renaming CSS classes', but there is no fix obviously. Betterttv still not work properly.

As regular user of twitch and a big fan of betterttv I hope a developers can find a way to make betterttv such great as it was a few month ago. 

Best regards, Ivan

**Comment by night** [comment]
Both of these are already fixed but not yet shipped.

**Comment by whitedma** [comment]
Yeah, now it works. Thx.
