### ISSUE TITLE
I Can just click tap anymore to send quick emotes 

### ISSUE THREAD

**Issue by samiksamom** [night/BetterTTV#2895]
im just wondering if you guys can add that like the old patches before the twitch patch that scrowed this add one can you pls add this Feature.

**Comment by night** [comment]
we pushed an update tonight readding this

**Comment by samiksamom** [comment]
I Love you guys ty for the update when i saw it i was very happy ty :D

2018-01-08 10:26 GMT+03:00 Zack <notifications@github.com>:
