### ISSUE TITLE
Linehistory

### ISSUE THREAD

**Issue by danielzaiser91** [night/BetterTTV#2896]
Arrow up doesnt give me my last typed line/chat message.
/linehistory on did not work (i found this command in a post from 2015, so i guess it has been removed)

How do i get linehistory back? Do i have to uninstall reinstall or is it a removed feature? 

i am seriously missing it

**Comment by night** [comment]
We recently merged in changes that re-add this feature to the extension, but it's not yet deployed. Once I'm finished with all these changes I'll cut a release.
