### ISSUE TITLE
[7.2.0] modcard keybinds apparently not working

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#2899]
Testing modcard keybinds with "i", "w", and "Esc" does not seem to function.  I don't have access to a stream with mod perms to test those.  Using clean latest Chrome.

**Comment by Luddz123** [comment]
Sup, i found another bug, when you open viewer list then click a name it looks like this https://gyazo.com/b0c60af9bd88411ca6ea12f8282fc5e4 :)

**Comment by thinkpad4** [comment]
Only seeing the ban and timeout options not the purge, 8 hour 24 hour options https://i.imgur.com/4AfJ6J1.jpg nor the permit option
