### ISSUE TITLE
Browser extension version# doesn't match release version#

### ISSUE THREAD

**Issue by DrizztD** [night/BetterTTV#2912]
I've noticed that the version number indicated in chrome or firefox addon/extension list never matches the version that was last downloaded/updated.

Example: 
today it says I have version 7.0 / last updated Jan 8, but the log shows the Jan 8 release should be v7.2.0
Just updated to the Jan 11 release (7.2.2), but it still displays 7.0

**Comment by night** [comment]
Extensions simply never match latest version and the extension version can be ignored.
