### ISSUE TITLE
Expand followed channel on the sidebar

### ISSUE THREAD

**Issue by JingKirby** [night/BetterTTV#2915]
It would be nice if we could expand followed channel on the sidebar. I only keep the followed channel visible and hide the friends and promoted one so it's empty and it would be useful to see if someone else I'm following is online without changing page. I assume other people would like to extend the friends instead. I think options to see 10 channel, 15, 20 or filling the sidebar would be great but seeing 15 is probably the most useful one.

**Comment by night** [comment]
there's a setting already for this.

**Comment by JingKirby** [comment]
I have never seen that expand button before today. Anyway I have to click it every time because it won't save the fact that I want it to stay expanded (to do so I have to click the arrow to expand the sidebar, click show more 2 times and click back the arrow to collapse the sidebar) and it would be nice to have the offline channel not show up in the followed channels in the sidebar.
