### ISSUE TITLE
Full color blind support on video player

### ISSUE THREAD

**Issue by Ethicmeta** [night/BetterTTV#2917]
Hey folks,

I recently attempted, and all but completed, building out a color blind selection Twitch extension tool before realizing the iframe separation basically removes that as a possibility. I didn't want the tool to go to waste, so I figure you guys might be interested in implementing it.

Basically, it applies an svg filter based on the selected deficiency and can be set to focus any element (body, iframe, chat, whatever).

Is this something you folks might be interested in?

You can find the repo at https://github.com/Ethicmeta/Colorblind-Mode

**Comment by night** [comment]
unfortunately while I can understand the use of this I don't think it's something that belongs in our extension as it's extremely specific to certain UI elements. Twitch would need to do this natively to be maintainable.

**Comment by Ethicmeta** [comment]
@night how would this be difficult to maintain? All this does is apply a css filter to an element or class. In this case itd be directly to video-player__container. Alternatively you can leave it as I have it setup and add the css to the body element which would apply the filter to the entire page.
