### ISSUE TITLE
new Bttv Emotes ??

### ISSUE THREAD

**Issue by ShotgunFlappe** [night/BetterTTV#292]
-NoCopyrightSounds logo 
-a pile of Doritos
-Syndicate Project's logo 
-Shrek's face 

love the idea of bttv, it makes twitch look alot nicer bttvHeart :p

**Comment by vendethiel** [comment]
Sounds like these would be best suited to the new ["Per-channel BTTV emotes"](https://manage.betterttv.net/) features!
