### ISSUE TITLE
Please let us chose whether BTTV changes name colours in chat. 

### ISSUE THREAD

**Issue by BlaireShadowpaw** [night/BetterTTV#2920]
BTTV is washing out all the username colours in my chat, I've tried with both BTTV and FFZ, and with only one or the other, and its BTTV doing this. I believe this is listed as a feature. Please give us an option to not have this.

**Comment by night** [comment]
We chose not to add an option for this because it makes the chat considerably better against hard to read names.

**Comment by BlaireShadowpaw** [comment]
Someone wise once said that if you can't remove it, its a bug, not a feature. 

It doesn't make my chat hard to read with names as they are, and bttv is screwing up the colours that people have chosen, especially when they can choose their hex code.
