### ISSUE TITLE
Default Directory sorting

### ISSUE THREAD

**Issue by Jimdm3** [night/betterttv#2923]
Currently when viewing https://www.twitch.tv/directory the default sorting method is "Show me Games and Communities sorted by Relevancy"(https://i.imgur.com/OlxP26X.png) can a feature be added to sort it by custom options. In this case I'd prefer the old method of Games and Popularity with the possibility of removing the option box at the top of the page.

**Comment by night** [comment]
it looks like twitch remembers your preferred sort now
