### ISSUE TITLE
BTTV appears to be bugging whispers.

### ISSUE THREAD

**Issue by fsdfkjhsd** [night/BetterTTV#2930]
On a page where BTTV is applying its stuff, receive more than a few whispers (possibly from more than one person) and the browser becomes unresponsive.

Meanwhile, another browser sitting on a dashboard or followers page (where by the theming/fonts etc it looks like BTTV is not involved), everything is fine. Have learnt to just immediately close all whispers where BTTV is involved and deal with them on a page where BTTV isn't involved.

It appears to be BTTV related, but like all things in life, is just my best guess ;)

**Comment by night** [comment]
> another browser sitting on a dashboard or followers page

this is twitch's old site, which is completely different code

> On a page where BTTV is applying its stuff, receive more than a few whispers (possibly from more than one person) and the browser becomes unresponsive.

i'm not able to reproduce this
