### ISSUE TITLE
Resub button dissapear with host mode disabled

### ISSUE THREAD

**Issue by deoillidan** [night/BetterTTV#2935]
if im disableing the host mode in btttv the button and message to resub dissapear too. if im enable the host mode and i get to the other channels that were hosted i see and can use the resub button again. if im disable it the button disappear. i contacting the twitch support about it and they say im still subbt and send me the ability to announce the sub again thats when i see it cause the button showed up a few secounds and then disappear because i had the host mode disablked all the time. just letting you know :)

**Comment by night** [comment]
I'm not able to reproduce this.
