### ISSUE TITLE
Suggestion: Feature to opt-out of auto joining a raid

### ISSUE THREAD

**Issue by dagit** [night/betterttv#2936]
Raids were changed so that the viewer is now required to click to opt-out of the raid.

This can be a problem, if for example, the stream is paused then the viewer will still get included in the raid and the new stream will start playing. Or maybe you have the channel up but you missed the raid notification and you simply don't want to have your browser window forcibly redirected.

It would be nice to have some features to control this behavior. Some ideas:

  * If the stream is paused, then don't join the raid
  * Global BTTV setting to control whether the user opts-in or opts-out of raids

Thanks!

**Comment by SanBest93** [comment]
registred here just to +1 this one

**Comment by slyngse** [comment]
this is very important raiding as it is now without a way to auto opt out is completely broken

**Comment by Ghouldude** [comment]
+1 This is my least favorite thing Twitch has added in a long time.

**Comment by JohnWayne01** [comment]
+1 it is a feature twitch has added that I don't care for at all (though it's smart on their end, shuffling afk viewers to an active channel gives more ad revenue)

**Comment by jacobmix** [comment]
I like to open up the raided channel in a new tab so i can still follow the chat in the first stream, and such.
+1

**Comment by Gewath** [comment]
BTTV's Disable Host Mode option is the main reason I use the extension. Disable Raids is a logical necessity for the app; it does the exact same thing, for an identical Twitch "feature". As of now, it's like having a 50% chance of "Disable Host Mode" working or not, depending on whether the streamer opts to host or raid. Make Twitch watchable again.

**Comment by ZeeStorm** [comment]
Hi there. I write a lot of custom code to customize websites using a chrome plugin, and the raids absolutely frustrate me to no end. So I wrote some that works for raids that will auto-leave a raid when the message pops up. It checks every 5 seconds for the message to appear. May not provide the best scenario, but it at least stops the raid. Maybe BetterTTV can implement this as an option:

```
const watchForRaid = () => {
	let btnLeave = document.querySelector('.chat-room__notifications > [data-test-selector="raid-banner"] button.tw-button');

	if (btnLeave) {
		btnLeave.click()
	}
};

window.watchForRaidInterval = window.setInterval(watchForRaid, 5000);
```

**Comment by wolfrunner86** [comment]
man i would love this feature, i hate coming back to a stream and being moved to a different usually loud and annoying stream.

**Comment by lsalvoni** [comment]
Need this please, I hate twitch raids with a passion and would pay for this feature or donate. 👍🏻

**Comment by Scontoni** [comment]
@night So it has almost been two years since this issue was raised, is there any update??
It seems like a relatively simple fix considering there is already an option to disable host mode and @whitecrownclown linked a pull request that would add this feature almost a year ago!

**Comment by eldorel** [comment]
From what I can tell the PR for this was reviewed, then modified to meet the concern from that review.

@night Is there some other issue with PR #3394 that needs to be addressed before it can be incorporated?

**Comment by alexandremix** [comment]
Hello does this feature exists in 2021?

**Comment by LuminairPrime** [comment]
Bump for disabling raid following!
