### ISSUE TITLE
Emote menue still randomly becomes "empty"

### ISSUE THREAD

**Issue by TheGloriousArgonaut** [night/BetterTTV#2937]
There was a fix floating around on github but it seems to randomly work , and when the issues occurs you have to always install the fix. The fix is never permanent.

Bottom line theres 100% still an issue with BTTV new rollout and ( from my investigation) primarily on firefox.

![image](https://user-images.githubusercontent.com/12703229/35424031-e41fa0b0-0205-11e8-89ed-0b467317aec8.png)

here are my current addons for firefox, 

![image](https://user-images.githubusercontent.com/12703229/35424059-03215788-0206-11e8-96e2-b1c7db096230.png)

If anyone has a definitive method to fix this let me know, issue still happening frequently as of January  2th 2018.

**Comment by xgerhard** [comment]
Duplicate #2901
