### ISSUE TITLE
Enhanced emote tooltips partially broken.

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#2939]
The enhanced tooltip display showing the source channel (if any) and provider are partially broken at the moment.  BTTV channel emotes work (shows both the channel and the provider) and BTTV global emotes work (shows "BTTV Global emote" as the provider).  All others, as far as I can see, are not working at the moment, and show just the emote code with no additional data.

edit to add:  For clarity, it would appear that anything serviced by the tooltip generator in emotes/emote.js (BTTV global, BTTV channel, BTTV personal) is OK, and anything serviced by replaceTwitchEmoticonTooltip in chat/index.js is not.  I tried some trivial debugging and aside from seeing that the if blocks wrapping the calls to replaceTwitchEmoticonTooltip are never being entered, I wasn't able to immediately figure out why.

**Comment by night** [comment]
well, twitch is now lazily rendering them .. how annoying

**Comment by night** [comment]
![image](https://user-images.githubusercontent.com/2942184/35489945-a81977f6-0450-11e8-9973-4a1ca7ab791d.png)

yeah, this is a pita to deal with.. not worth my time atm

**Comment by night** [comment]
this is no longer needed because twitch has their own popouts
