### ISSUE TITLE
Overlaping Font in new Twitch Chat

### ISSUE THREAD

**Issue by Schnubbirunkel** [night/BetterTTV#2940]
I installed the BTTV plugin and changed the font and font size but now every setting with these two looks like this: 
[https://imgur.com/a/j0uIB](url)

I tried it with firefox and chrome (same problem) and with different fonts like impact, arial black and others 
and i've tried font sizes from 30 to 45. Nothing helped.

I dont use any other plugins with my browsers. 
Any ideas what this could be?

**Comment by night** [comment]
Instead of relying on that large of chat font sizes, I suggest using page zoom instead.
