### ISSUE TITLE
Emote menu lazy loading causing icons to not show when scrolled down

### ISSUE THREAD

**Issue by bspotswood** [night/BetterTTV#2941]
If you open the emote menu and scroll down at all from the top, then close it by any means (clicking out, clicking on the open button, clicking an emote), when you go back in you'll be scrolled down but it seems that the lazy loader isn't letting anything load back up. This may also have to do with the updateEmotes() method being called inside of UIMenu's toggledDisplay() method. I haven't debugged it further to see if removing that would resolve the issue.

This is annoying if you are trying to click a series of emotes that are not near the top and don't have the menu pinned. They will show again if you scroll them out of view and back in, but once the menu is hidden and displayed again then the issue occurs again unless you're scrolled to the top.

![lazy-load-scroll-issue](https://user-images.githubusercontent.com/1064979/35495798-54756500-0488-11e8-8932-c7a55c769518.png)

**Comment by Daisenki** [comment]
I don't see this issue fixed right now. The emote menu is loading very slow and only if you scroll down and up inside, it's really annoying with a lot of subs and emotes.
