### ISSUE TITLE
Chat not working in theater mode

### ISSUE THREAD

**Issue by Rakuryo** [night/BetterTTV#2943]
So I'm using the latest Firefox version and as soon as I enter the theater mode on any twitch channel this happens (Dark Design used here btw if its important to the issue)
![screenshot-2018-1-30 twitch](https://user-images.githubusercontent.com/35966048/35574920-64fade9c-05db-11e8-9018-bffd03f15fb5.png)
As you can see the left side where the chat should be i just completely blank and i can't do nothing with it.
Also when not using the "Left Side Chat" feature the Theater Mode works as intended

**Comment by night** [comment]
im not able to reproduce this. make sure you're not using other twitch extensions that may conflict with ours.
