### ISSUE TITLE
Highlight username when you move your mouse over it or its mention.

### ISSUE THREAD

**Issue by d3jv** [night/BetterTTV#2944]
Sometimes its really needed when you are searching for context in chats with lots of viewers.

**Comment by night** [comment]
can you elaborate? this is too vague for me to understand.

**Comment by d3jv** [comment]
Just to be clear, it's a suggestion, I dont know how to tag it as such

---------- Původní zpráva ----------
Od: Zack 
Datum: 5. 2. 2018 v 11:13:38
Předmět: Re: [night/BetterTTV] Highlight username when you move your mouse 
over it or its mention. (#2944)


can you elaborate? this is too vague for me to understand.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/night/BetterTTV/issues/2944#issuecomment-363039599), or 
mute the thread
