### ISSUE TITLE
Maxthon BetterTV emoticons menu issue 

### ISSUE THREAD

**Issue by argotha** [night/BetterTTV#2946]
For some reason BetterTV emotes menu is bugged in Maxthon. It looks like this 
![maxthonsnap20180201144324](https://user-images.githubusercontent.com/4603129/35676805-46cfe532-075e-11e8-9804-29bb49d5f8f2.png)
In other browser it looks ok (from SeaMonkey).
![maxthonsnap20180201144437](https://user-images.githubusercontent.com/4603129/35676860-71bca6cc-075e-11e8-9bd6-036cf5068615.png)
I tried to clean cache and cookies but it didnt help.

**Comment by night** [comment]
we use a browser api called IntersectionObserver that they clearly haven't implemented properly, lol. not sure it's something we can fix

**Comment by night** [comment]
closing this as it's probably a maxthon issue
