### ISSUE TITLE
"Auto Expand Followed Channels List" is broken.

### ISSUE THREAD

**Issue by XtrLoLz** [night/BetterTTV#2948]
The option "Auto Expand Followed Channels List" doesn't seem to do what it's supposed to. I always have to press load more manually.

**Comment by night** [comment]
cc @SexualRhinoceros

**Comment by SexualRhinoceros** [comment]
Something something beta went and mucked up the code. I'll PR a fix later tonight

**Comment by kortisova** [comment]
Still doesnt work for me. When I enable auto expand in settings, channel list expands. But after I reload or close/open twitch, channels dont expand automatically.

**Comment by wndrrr** [comment]
same
