### ISSUE TITLE
Bug with "hide friends"

### ISSUE THREAD

**Issue by dinaricahoroskop** [night/BetterTTV#2950]
Hi. I have Firefox 58.0.1 (64-bit) and the "hide friends" option isn't working as intended.
If i click on hide friends, it hides "recommended friends". And if i already have the "hide recommended friends" option enabled, the "hide friends" option doesn't do anything. Already tried reinstalling the browser and clearing the cache/appdata so i doubt its something on my end.

**Comment by night** [comment]
it seems to be working for me
