### ISSUE TITLE
Moderation timeout menu!

### ISSUE THREAD

**Issue by BeatBattles** [night/BetterTTV#2951]
![57ef79833c776104cac9a8c1bb96e885](https://user-images.githubusercontent.com/36091127/35760672-cb07550a-084f-11e8-8013-dccb7f3e76b7.png) First time you click on someone it shows this menu but then if you click a second time you get this menu 
![f224bcd90c715b852124c3b054f13655](https://user-images.githubusercontent.com/36091127/35760707-0211c652-0850-11e8-905f-4d19e0fc5d1e.png)

**Comment by night** [comment]
fixed in master
