### ISSUE TITLE
Log in Bug

### ISSUE THREAD

**Issue by Kirsinn** [night/BetterTTV#2954]
Hi. I got a problem with the log in service. When i try to log in i get redirected to a page on my browser, but the page stays on "Redirecting" and i can't log in. I hope you can resolve this bug.
P.S. Sorry for my bad english, i'm Italian
![log in problem](https://user-images.githubusercontent.com/36178036/35837338-af79fb74-0ae5-11e8-832e-6579b9063892.PNG)
.

**Comment by night** [comment]
try accessing the site directly instead at https://manage.betterttv.net
