### ISSUE TITLE
[FEATURE] Discord Emote Sync

### ISSUE THREAD

**Issue by Technoblazed** [night/BetterTTV#2955]
This is more of a feature request than an issue, but not something that can be directly PR'd because of how the system works. 

It'd be cool if when BTTV emotes are synced with the server, if there was some sort of option to add gif emotes through the animated emotes feature for nitro users.

**Comment by night** [comment]
we now will sync gif emotes too

**Comment by Technoblazed** [comment]
Awesome sauce
