### ISSUE TITLE
monkaS not working

### ISSUE THREAD

**Issue by thelimitlessone** [night/BetterTTV#2958]
All emotes of better twitch tv are working besides monkaS. Used frequently chat. There is only one other person in the chat that is apparently having the same issue. I tried uninstalling and reinstalling, along with switch all of the setting on and off but there is no monkaS still. Hovering over the text monkaS does not have any information displayed like it should be an emote, but instead acts as regular text. In the emote menu monkaS in not there and I cannot unhide it or hide it as such. Any fix?
https://gyazo.com/51ef6b3862f47804613d8f9c9a6c5702

**Comment by night** [comment]
it's probably not a BetterTTV emote if it's not in the emote menu.
