### ISSUE TITLE
emotes from other channels

### ISSUE THREAD

**Issue by viniiciussantos** [night/BetterTTV#2959]
Before when I'm was watching someone stream and someone else send a emote form another channel in chat if I click on the emote it gonna open a new tab redirecting me to the "someone else" channel. Now this feature isnt working for me anymore.

**Comment by Nareese** [comment]
This issue is directly related to the issue in #2939, as the click to go to channel functionality is handled by the same code that handles the extended tooltips.  When that one is fixed, this one will be as well.
