### ISSUE TITLE
[Feature Request] Highlight Chat Users for Modding

### ISSUE THREAD

**Issue by baconbastrd** [night/BetterTTV#2961]
I would love a feature for BTTV where a mod has the ability to tag a username to be highlighted in chat. This would make it easier to watch the behavior of people who may need to be timed out or eventually banned. Sometimes, in a busy stream, it is easy to miss something suspect. This would be the ultimate convenience for moderation.

**Comment by night** [comment]
You can do this already in the chat settings -> edit highlight keywords prompt
