### ISSUE TITLE
Chat Scrolling Firefox

### ISSUE THREAD

**Issue by saimkaan** [night/BetterTTV#2973]
Hey,
i have a problem when i use BTTV in chrome the scrolling in chat works fine but when i use it in firefox i scroll up and it does not stop the chat it keeps moving. Asked my freinds and they have the same problem in firefox. Is there a fix for firefox users?

**Comment by PabloSzx** [comment]
I can relate, please try to fix it

**Comment by night** [comment]
this is a twitch problem, not our problem
