### ISSUE TITLE
First notice message masked by cheers if the message is too long

### ISSUE THREAD

**Issue by BeatBattles** [night/BetterTTV#2974]
![notice alert masked by cheers](https://user-images.githubusercontent.com/36091127/36220832-03b9ae8c-118a-11e8-8d7c-57115d4733f4.png)

As the title says, it happens when you level up, if the top cheer bar is there and someone notice you but the message is too long, it appears behind the cheer bar and you have to click the ''x'' to see it! this message was supposed to say ''user just advanced to streamer Level 5!'' but just shows ''Level 5!''

**Comment by night** [comment]
im not able to reproduce this
