### ISSUE TITLE
My shared BTTV emotes no longer work

### ISSUE THREAD

**Issue by GPFault** [night/BetterTTV#2975]
I've had two BTTV emotes on my channel for a long time:

SylverMicDrop
SylverLethal

And they no longer work for me, or for anyone else either.

I have BTTV enabled, and tried clearing cache/cookies, etc... These aren't working for anyone else in my channel either. They show up in the BTTV manager as enabled and in use by other channels as well.

Can anyone help?

Channel = http://www.twitch.tv/sylvermyst

Thanks in advance.

**Comment by night** [comment]
they show up fine in your chat for me
