### ISSUE TITLE
Enable disabling of repeat emotes in BetterTTV settings

### ISSUE THREAD

**Issue by CodyFitzpatrick** [night/BetterTTV#2978]
It would be great if you could hide comments in chat with repeated emotes, i.e. if someone prints the same emote multiple times in the same message, you only see the emote once in their message. This would slow down scrolling in highly active Twitch chats and enable you to read more messages.

Here's an example of it in-action: ![disable repeat emotes example](https://user-images.githubusercontent.com/5438023/36505017-48e1f636-1720-11e8-851d-55120ce9a81c.png)

**Comment by night** [comment]
duplicate of #1922
