### ISSUE TITLE
version different for newest and chrome store?

### ISSUE THREAD

**Issue by wong8888** [night/BetterTTV#2980]
on official website is write 7.2.8
but on chrome store still write 7.2.1?

**Comment by Nareese** [comment]
These are two different version numbers.  7.2.1 is the version number of the latest extension for Chrome.  The extensions for other browsers can (and often do) have different version numbers.  All the extension does is load the latest version of the actual BTTV code from the network.  7.2.8 is the latest version of BTTV itself.  You can see this by going to BetterTTV Settings -> About.
