### ISSUE TITLE
BetterTTV not showing up in chat

### ISSUE THREAD

**Issue by FlaShFTW** [night/BetterTTV#2983]
So this happens quite often to me when I join my first stream or change a stream, but usually I don't see the BTTV settings until I refresh a stream. This time, I'm just not getting anything at all, but I get the settings when I use the legacy pop out chat or go to my personal settings in the twitch.tv console which is weird.

**Comment by SaiyanOfDarkness** [comment]
Already known..

https://github.com/night/BetterTTV/issues/2982
