### ISSUE TITLE
Gray box appears on left side of screen

### ISSUE THREAD

**Issue by mastressalita** [night/BetterTTV#2996]
After the new Twitch update, a gray bar is appearing on the left side of the screen, where the side bar appears, like the following image: 

http://bl.canadia.info/misc/twitch2.jpg

Since I normally use FFZ to disable the sidebar, this bar appears right over the video display, as in this image:

http://bl.canadia.info/misc/twitch1.jpg

The gray bar does not appear while in Theater Mode. Disabling the BTTV plugin fixed the issue. 

Browser Used: Firefox 64-bit 56.0.1

**Comment by night** [comment]
BetterTTV does not add any ui elements to the left sidebar, so you are mistaken that it's BetterTTV.
