### ISSUE TITLE
BTTV takes away native desktop notification option (and possibly others)

### ISSUE THREAD

**Issue by Scorne9000** [night/BetterTTV#2999]
I was wondering for a long time why I stopped getting desktop notifications. I noticed that BTTV took out their option for these notifications, so I figured that Twitch added it themselves. I found out that this is true, but the option doesn't show up in the Twitch settings while BTTV is enabled.  When I uninstalled BTTV, the Twitch settings page appeared as it should. I want desktop notifications, but I really like BTTV, so I don't want to just get rid of it. Any solution would be appreciated.

**Comment by night** [comment]
I'm not sure what you're talking about, but BetterTTV does not hide UI for that. You can find notification settings at https://www.twitch.tv/settings/notifications
