### ISSUE TITLE
Telling mods/broadcaster who Timed Out an user?

### ISSUE THREAD

**Issue by rafaelvargas** [night/BetterTTV#300]
I'd really like twitch to tell us who "Times Out" the users...
"(USER) has been timed out.. by (MOD)" -- is this possible with BTTV?
IDK, just a suggestion :)

**Comment by vendethiel** [comment]
Nope. We don't have that info.

**Comment by DTittel** [comment]
First off this would be a bad feature if offered to non-mods of a channel.
it would basically suggest that mods who actually do what the caster asks
them to help with should be "witch hunted".

Aside last I checked this isn't possible with the current implementation.
While something hacky might be possible such a feature would be best
implemented directly into the Twitch chat server.
