### ISSUE TITLE
Ctrl not working on chat

### ISSUE THREAD

**Issue by Khrome-XO** [night/BetterTTV#3000]
I recently tried left clicking CTRL to stop chat from scrolling but it didn't work. Tried refreshing, but no luck.

**Comment by thinkpad4** [comment]
@Khrome-XO It half works, when the mouse cursor is over the chat part ctrl pause works, when the cursor is anywhere else it doesn't work

**Comment by thinkpad4** [comment]
I've tried it on several browsers and a few other computers and ctrl pause still only works when the cursor is hovering on the chat, not the text box at the bottom, the chat

**Comment by Khrome-XO** [comment]
@thinkpad4 If I could show, I would. It doesn't work for me ;-;
