### ISSUE TITLE
"Show Deleted Messages" Option won't work.

### ISSUE THREAD

**Issue by riggedorlicious** [night/BetterTTV#3003]
Today, on February 26, 2018, I wanted to see deleted messages because I was just curious what it would show me.  So, I go into the BTTV options and I see the "Show Deleted Messages" option there and I noticed that is was already enabled. I switch it off and I reload the page. Just like before I go to the settings and switch it on, once again I reload the page. Still can't see deleted messages.

**Comment by av798902** [comment]
To add to this, the prevention of chat clearing is also not functioning recently.
