### ISSUE TITLE
Let side chat friend/follower mouse-over popup

### ISSUE THREAD

**Issue by Roxaslenobody** [night/BetterTTV#3004]
When mousing over friends the popup box that shows up with left side chat doesn't show up, unlike how it does if left side chat is disabled, http://prntscr.com/ik99hq is the thing i'm talking about that shows up when i disable left side chat and mouse over following icons, or friends, it worked before then twitch changed a something, then was fixed again, but once again stopped working

**Comment by night** [comment]
this is not something we can easily fix due to how twitch renders these.. they globally position them with fixed widths
