### ISSUE TITLE
Request: Hide top cheer

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#3012]
Title basically.. these new weekly top cheers.. come in tier 1, 2 and 3.

Would be cool if we could hide these.

**Comment by SaiyanOfDarkness** [comment]
To add to that.. it should be something related to .tw-z-default.pinned-cheer-v2

**Comment by ArielRosenfeld** [comment]
i think this bug meant only filter the cheers on the top of the channel but allow cheers otherwise
