### ISSUE TITLE
Chat disappearing w/ BTTV Dark Theme

### ISSUE THREAD

**Issue by CplDarkeye** [night/BetterTTV#3013]
When ever I hit enter, or the chat button to send my message in chats, the chat just vanishes and I have to refresh, it seemingly has something to do with the dark theme setting, if i turn off twitch's dark mode and turn off, and turn on dark theme in bttv, the chat vanishes, but if i just turn on twitch's dark mode it works fine.

**Comment by Mitsuma** [comment]
Happens without dark theme.  
A few days ago it would collapse the chat to the right without an option to show it again (the arrow disappeared too).
Now it collapses up and I can't see the chat 

![](https://i.imgur.com/vgD8lEW.png)

**Comment by night** [comment]
you are probably using some other extension with BetterTTV that is breaking chat.
