### ISSUE TITLE
BetterTTV Settings on Dashboard

### ISSUE THREAD

**Issue by jaa121** [night/BetterTTV#302]
Hello!
I found a bug (maybe). Buttons in settings on Dashboard are mismatched. Check screenshot: 

![screen](https://cloud.githubusercontent.com/assets/11669792/6855365/cecbcc50-d3f7-11e4-9b3b-18e62143a5be.png)

**Comment by metarmask** [comment]
Yeah, it happens when they are popped out: #322
I searched for duplicates but thought it would contain "popped out" or "popout". Closing mine now.
