### ISSUE TITLE
Twitch Prime Loot Icon

### ISSUE THREAD

**Issue by punkiiff** [night/BetterTTV#3023]
Hi! Thank you for the extension, enjoying it very much.

Just wanted to report a bug wherein BetterTTV hides the Twitch Prime Loot Icon, making it impossible to claim the offers. Obstruction of this includes claiming them from any link or direction (like twitch.amazon.com), as well as from the main Twitch page itself. I have confirmed for myself that disabling BetterTTV brings back the Loot Icon and functionality.

**Comment by Nareese** [comment]
I am unable to replicate this.  Note that there is an option in the BetterTTV Settings to `Hide Prime Promotions` that will hide that icon.  Ensure that option is `Off` if you want to see the icon.
