### ISSUE TITLE
[7.2.14 Chrome] "Disable Host Mode" breaks profiles

### ISSUE THREAD

**Issue by Px05119** [night/BetterTTV#3025]
Like the title says. When Disable Host Mode is enabled, and a streamer is hosting someone, their profile fails to load. I've had maybe a 1 in 10 chance of getting a profile to load during hosting with that option enabled. If they're not hosting someone, the profile loads fine. Issue persisted even after a complete reformat and install of Win10 and Chrome (for unrelated reasons)

**Comment by night** [comment]
im not able to reproduce any issues with this feature.

**Comment by Px05119** [comment]
I'm able to reproduce this in an incognito window, ZERO extensions aside from BTTV, only enabling the "Disable Host Mode" feature.. Load a page that's hosting someone,  no profile. Issue is not invalid, please re-open
