### ISSUE TITLE
Hide Twitch Extensions does not hide streamlabs extension

### ISSUE THREAD

**Issue by Fuglypump** [night/BetterTTV#3026]
as title says, the extension's overlay is still there and as far as I know I can't get rid of it.

**Comment by xaxxon** [comment]
Not working on mobalytics.gg extension on iwilldominate twitch stream

![image](https://user-images.githubusercontent.com/143986/37241648-8ded2112-2411-11e8-81ca-12dbf207a8ed.png)

**Comment by SaiyanOfDarkness** [comment]
Thanks for that...

I decided to add "www.twitch.tv##.extension-container" to my ublock extension for the time being .. at least for streamlabs stuff, not sure if it works for others too though.
