### ISSUE TITLE
- Bug ? - " Auto Expand Followed Channels List " 

### ISSUE THREAD

**Issue by Saftbefehl** [night/BetterTTV#3031]
Hey BTTV 
I really enjoy you Extension, since we can use the BTTV Emotes again, even more :) but i noticed something, what really bothers me. I dont know if it's a Bug or ment by your Devs. 
I had " Auto Expand Followed Channels List " enabled for ever, but since a few Days/Weeks it also expands the " Channels you Follow " List on the left side and its not possible for me to see if i there are any Friends online (because i follow more than 20 Channels).
I appreciate your work and i'd love to see a workaround for this Problem :)

**Comment by night** [comment]
that is what this setting does. if you dont want it to expand them then disable the feature.
