### ISSUE TITLE
Twtich Chat not pausing when you scroll up in Firefox

### ISSUE THREAD

**Issue by Hobskins** [night/BetterTTV#3032]
As title says the chat does not pause whenever you scroll up to view what someone said.

I do understand there is a hot key to hold ctrl that is supposed to pause the chat after you scroll, however that does nothing.
I have disabled BTTV and the scroll pausing works just fine when it's disabled.
Will have to keep it disabled until this is resolved. :(
Firefox version: 59.0 (64-bit)

**Comment by Hobskins** [comment]
It seems like this issue only happens in chats that are moving very quickly(Spam chat)

I switched to another channel and the chat pauses just fine.

**Comment by saimkaan** [comment]
No its broken in all chats. you just have to wait long enough and it will start scroling up again :/ Still no fix 3 month now -_-

**Comment by night** [comment]
This is not our bug to fix. This is a Twitch feature they should fix.

**Comment by theslimshaney** [comment]
Just curious, what's the bug and why does it only happen with the addon installed?
