### ISSUE TITLE
Gift sub firing as Clear Chat

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3034]
While watching a stream last night, I noticed that every time someone gifted a sub (the streamer's events monitor in OBS would show it and the streamer would announce it), no gift announcement showed in chat, and instead, BTTV showed the "Chat Cleared (prevented by BTTV)" message.  Guessing that Twitch has renumbered the TMIActionTypes again, but I don't know where to find that list in Twitch's guts to confirm...

**Comment by RandomRocker** [comment]
Yep can confirm, I was in a stream and thought "they're clearing the chat a lot" but realized they coincided with gift subs that weren't shown in chat.

**Comment by marcsances** [comment]
Can confirm as well, all mods had to turn off BTTV to avoid chat being cleared continuously.

**Comment by demortes** [comment]
Copy pasta from discord: Greetings. We're seeing a bug on a stream. Every time someone Gifts a sub, BTTV reports "Chat cleared by moderator (Prevented by BTTV)". Unmodded incognito window in chrome shows the gift message.
