### ISSUE TITLE
Shared BetterTTV-emotes do not work in a channel's chat if channel was entered through another channel hosting it

### ISSUE THREAD

**Issue by smol-fi** [night/BetterTTV#3038]
[Both are in the same channel, though left one has been entered through a host link.](https://i.imgur.com/ypaeVhy.png)

By host link I am referring to [this](https://i.imgur.com/M1fLFz4.png).

As you can see, global BTTV-emotes work as intended, but shared emotes do not. This is obviously only an issue on the user's end that has joined the channel though a host link.

I have managed to consistently reproduce this bug simply through following host links to a channel's chat.

This was tested on Firefox 59.0 using the Firefox-addon version of BetterTTV v7.2.16.

**Comment by night** [comment]
i think any channel to channel navigation will cause this because a new chat load is not triggered.
