### ISSUE TITLE
[bug] apparently somethings changing my name colors?

### ISSUE THREAD

**Issue by sweagboi** [night/BetterTTV#3039]
i thought this was a problem with FFz but apparently not
i dont even see any settings to change this so i dont know what to do

top is what the color should be, bottom is what it keeps changing to
![capture](https://user-images.githubusercontent.com/37525568/37694844-8fcfc826-2c87-11e8-81eb-b48ad0541511.PNG)

**Comment by night** [comment]
this is intentional to make hard to read names easier to read.

**Comment by sweagboi** [comment]
well an option to turn it off would be very appreciated because i never had problems reading names before and it makes them obnoxiously bright
