### ISSUE TITLE
Fix links broken by twitch

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#304]
As far as I know if you put a link in twitch chat that has , (comma) in it gets broken, is it possible for bttv to fix that?

**Comment by voloshink** [comment]
Can you give an example of a link that's broken

**Comment by evodoc** [comment]
For example: http://steamcharts.com/cmp/214490,209660,232050
it becomes: http://steamcharts.com/cmp/214490
The same thins happen with ;

**Comment by voloshink** [comment]
Can reproduce, would need to change the linkyfy regex

**Comment by night** [comment]
We use Twitch's link regex, so you may wish to report this bug to Twitch. http://www.twitch.tv/bug_reports/new
