### ISSUE TITLE
Twitch name change => @ mentions and replies aren't highlighted or pinned to top of chatbox. 

### ISSUE THREAD

**Issue by snugghash** [night/BetterTTV#3040]
Steps to reproduce:
Enable Highlight mentions, pin highlighted
Change twitch name
No longer highlights mentions and replies to new name.

Browser: firefox.
Not fixed from reinstall, restart firefox.

I can probably contribute a PR to fix this over the weekend, if no one wants to work on this or this if this is too much work.

**Comment by Nareese** [comment]
On the chat "gear" wheel, select `Set Highlight Keywords` and enter your new user name.

**Comment by snugghash** [comment]
Hm, thanks. I see my old name is already there, I assume it's added automatically? Or did I forget I ever did this O.o

Either way, is the ability to do this automatically a thing we need?

**Comment by Nareese** [comment]
When you initially install betterttv and the variable is not set, it will pick up your current username and set that as the default.  If your username changes (a feature that did not exist at the time BTTV was written), you have to manually change it.  Given that it's trivial to update, and that the highlight list can contain things other than your name, making it non-trivial to detect that your name changed, I personally don't think it needs to be automatic, but if you're ambitious, feel free to code a PR and see what night thinks.

**Comment by snugghash** [comment]
Got it.
Found the piece that should be changed to make it automatic, but it's a headache to check for changed usernames though.
```
function defaultHighlightKeywords(value) {
    if (typeof value === 'string') {
// Check for twitch.getCurrentUser() existing as a word in value
        return value;
    }
    const currentUser = twitch.getCurrentUser();
    return currentUser ? currentUser.name : '';
}
```

**Comment by night** [comment]
we won't automate a fix for this because setting your username as a highlighted keyword is simply a default value that we won't update after you've set a custom one.
