### ISSUE TITLE
suggesting an improvement 

### ISSUE THREAD

**Issue by Tank1812-1** [night/BetterTTV#3041]
can u plz add an on/off button so i can disable bttv if i dont want to use it???

**Comment by Nareese** [comment]
This is a browser function:  In Chrome, select the menu -> More Tools -> Extensions, and click the switch on the BetterTTV panel to turn it on or off.  I don't use modern Firefox, but last I looked, it had something similar on the Add-ons panel with a "Disable" button for each add-on.
