### ISSUE TITLE
Popout chat and BTTV settings when watching a VOD

### ISSUE THREAD

**Issue by chaosblad3** [night/BetterTTV#3044]
I'm honestly not sure why this isn't just natively a part of Twitch, but there really needs to be an option to "popout" the chat when watching a past broadcast (VOD), currently the popout chat option is only available in the chat settings menu when viewing a stream live like so: https://i.imgur.com/tbGgAvJ.png but when watching a past broadcast the entire settings menu gets replaced by this: https://i.imgur.com/XHuuqtn.png removing not only the popout chat option but also all of the BTTV options.

**Comment by night** [comment]
such a feature is impossible as there's not a way to sync up a popout chat to the video player as it's built. popout chat does not support vod chat at all.
