### ISSUE TITLE
Chat-relevant selectors are broken (emotes don't work, can't adjust chat font size, etc.)

### ISSUE THREAD

**Issue by garyking** [night/BetterTTV#3051]
Since a few hours ago, I can't adjust the font size of Twitch chat with BTTV in Chrome.

The relevant line of code is [here](https://github.com/night/BetterTTV/blob/250e7535b1ff04479973c936766dca2ac33e1256/src/modules/chat_font_settings/index.js#L29). I assume that the changes made [here](https://github.com/night/BetterTTV/commit/250e7535b1ff04479973c936766dca2ac33e1256) will have to be done again, too.

It seems like `div[data-test-selector="chat-room-component-layout"]` doesn't exist anymore, so the CSS rules are not applied. The `div` was changed to a `section` tag.

Full tag:

```html
<section role="complementary" aria-labelledby="chat-room-header-label" data-test-selector="chat-room-component-layout" data-a-target="chat-theme-dark" class="tw-full-width tw-full-height tw-overflow-hidden tw-flex tw-flex-column tw-flex-grow-1 tw-flex-shrink-1">
```

**Comment by Nareese** [comment]
Thanks for the leg work finding this, Gary.  I've submitted a PR to make these adjustments.  I have it running successfully in my dev instance and it does resolve all the issues.

**Comment by garyking** [comment]
@Nareese Is the `section` selector even necessary? Can't it just search using the `[data-test-selector]` attribute? It will certainly be slower without `section`, but if this selector only runs on page load, then it won't be a problem. If it's run on every chat message or something though, then yes then the tag would be necessary.

**Comment by Nareese** [comment]
I think in general, more specificity is better than less, although I agree in this case, it is extremely unlikely that there would ever be a collision on that particular data somewhere else.  I have no idea what the performance impacts would be.  If night wants me to change it to just the attribute selector with no tag, I can certainly do that.  I was just going with the same level of specificity that was used last time.
