### ISSUE TITLE
BTTV Emotes not working in the chat

### ISSUE THREAD

**Issue by MihaiIDK** [night/BetterTTV#3053]
I can see the emotes in Emote Menu, they are enabled and all but they do not appear in chat. Sorry if this issue was discussed before.

**Comment by Shelmor** [comment]
Same. Also the tab autocompletion doesn't seem to work.

**Comment by garyking** [comment]
This is probably related to #3051.

**Comment by MattM007** [comment]
Yea, I am experiencing this issue as well.
