### ISSUE TITLE
Hide New Viewer Greeting broken

### ISSUE THREAD

**Issue by Daisenki** [night/BetterTTV#3060]
Hide New Viewer Greeting does not work anymore (Firefox 59.0.2 - BTTV Version 7.2.18 (Apr 3, 2018))

![say hi](https://user-images.githubusercontent.com/22057956/38409640-729f0368-3982-11e8-923a-9fa5805168e6.JPG)
![on](https://user-images.githubusercontent.com/22057956/38409635-703fb3ec-3982-11e8-8425-5a503bfec548.JPG)

**Comment by Senpos** [comment]
@Daisenki 
This promotion was not implemented before and is not implemented in fix. 
It is not easy to catch this popup, but will try my best.

**Comment by Nareese** [comment]
Unfortunately, `.user-notice-line` is used by more than just the new viewer greeting.  It is also used minimally by subscription announcements, leading to the report in #3071.  I don't know what the right fix for this is at this point.  As near as I can see, it's yet another case of twitch removing a  unique identifier from something and leaving it unable to be differentiated from other things.

**Comment by Senpos** [comment]
@Nareese Oh, Lord. 
Well, probably we should use message text to determine if it's "greeting" or not. 

Shame on you, Twitch :( 

Thanks for informing, @Nareese
