### ISSUE TITLE
Disable Homepage Autoplay did not work (once)

### ISSUE THREAD

**Issue by Wizib** [night/BetterTTV#3061]
Hi,

I disabled Homepage Autoplay last time I was on Twitch. When going back on Twitch today, the featured broadcaster played automatically. I checked my BTTV to make sure it was disabled, and it was. I then closed the BTTV settings menu and reloaded the page, trying to recreate the problem, but it worked as intended (no autoplay).

I just thought I should let you know.

**Comment by night** [comment]
I cannot reproduce this
