### ISSUE TITLE
Cheers issue

### ISSUE THREAD

**Issue by Zer0SumGame** [night/BetterTTV#3063]
BTTV is preventing me from cheering in chat. I have no other Twitch extensions, I cleared my cache.

I just wasted 8 bucks on bits I can't spend.

Thanks for that, lads. Top level programming.

**Comment by night** [comment]
i mean you probably enabled the `hide bits` option (which is disabled by default, mind you) and are complaining about our programming when it's really user error.

**Comment by Zer0SumGame** [comment]
I don't have hide bits enabled. I never turned it on.
