### ISSUE TITLE
Make left sidebar's "Show More" feature an account setting

### ISSUE THREAD

**Issue by TETELIOTAI** [night/BetterTTV#3064]
Twitch has a native Show More option that allows you to see more than a handful of stream icons in the left sidebar, but the setting gets forgotten whenever Twitch closes.  Allowing users to make this feature permanent would be fantastic.

**Comment by night** [comment]
there's already a setting for this in BetterTTV

**Comment by TETELIOTAI** [comment]
Well I'm thoroughly embarrassed for not doing my homework on this, but it seems like the function may not be working as intended.

I made this [video ](https://youtu.be/iGTB7IO198Q)showcasing how it appears in my browser; it only seems to have any effect when I toggle the option on while the left sidebar is open.  Refreshing the page resets the setting.
