### ISSUE TITLE
Mod icons are not properly hidden

### ISSUE THREAD

**Issue by xgerhard** [night/BetterTTV#3065]
Reported on Discord: As a moderator mod icons are shown next to the broadcaster, other mods and yourself.
For example: https://imgur.com/a/vSMbZ

Twitch probly changed the name of the element: https://github.com/night/BetterTTV/blob/e1e9284a71d637c11e2f2f4ab59b3b0a2bb1533b/src/modules/chat/index.js#L227

**Comment by Smatify** [comment]
Not only on users, but also for subnotifications:

![](https://i.smatify.com/75tgrXVD.png)

**Comment by Nareese** [comment]
Ya, presumably that class was on the div that wrapped all of the icons, and that is indeed gone, replaced by absolutely nothing uniquely identifiable, following the trend recently of removing actual useful identifiers from containers in general.

The individual icons have `.mod-icon` on them, and I changed the above selector to that in my dev instance, and it ... kinda... removes them correctly for me at least on myself in my own chat.  There is one empty div for me between where the mod icons were and the owner icon that slightly messes up spacing.  I will test it further in a chat where I'm mod and if it looks generally OK, I will make a PR for it, unless night gets to it first.

**Comment by Nareese** [comment]
OK, having tested it on a channel where I have mod, it seems to be OK... there is that minor spacing issue from the leftover empty div, but meh.  I submitted a PR for it anyway.
