### ISSUE TITLE
BTTV red error report

### ISSUE THREAD

**Issue by wzrdstk** [night/BetterTTV#3068]
Hi, I am not seeing any BTTV emotes despite troubleshooting everything in the debugging post. Here is a screenshot of the Javascript console and the apparent red errors.

Could these errors cause me to not see BTTV emotes?

![image](https://user-images.githubusercontent.com/38377982/38768628-ba11945c-3fab-11e8-9dc0-97cea0e32c13.png)

**Comment by night** [comment]
these are not BetterTTV errors
