### ISSUE TITLE
suggestion about moderator tools bar (not an issue)

### ISSUE THREAD

**Issue by joneau** [night/BetterTTV#307]
maybe there could be an option to hide the moderator tools bar from the gear button from settings. As sometimes a damn misclick and poof, somethin happens which shouldnt. least id like to avoid that kind of situations, (etc. cleared chat by accident or just enabled slow mode. brings goosebumps once that happens onlive...)

**Comment by night** [comment]
There's really not much of a reason to be inside the chat settings unless you're trying to modify.. settings. There isn't a point to hiding these settings. You should just be more careful.
