### ISSUE TITLE
When enabling twitch dark theme betterttv also enables dark theme

### ISSUE THREAD

**Issue by 33Fraise33** [night/BetterTTV#3073]
When I go to the homepage and enable the dark theme from the twitch settings everything looks as it should be, but then going to my dashboards changes the colors to the grey dark theme of betterttv. 

I'd like to be able to choose between the betterttv dark theme or the twitch dark theme.

**Comment by night** [comment]
Twitch’s dashboard is also a legacy page, which is still on the old Ember framework. Until they upgrade that page it will remain in this state

**Comment by 33Fraise33** [comment]
Hello, 

It seems to be related with that last reply. On all other pages it uses the dark theme of twitch itself but on the dashboard it's the grey betterttv theme.
