### ISSUE TITLE
[Feature Request] Emote Hover Info

### ISSUE THREAD

**Issue by SonOfDiablo** [night/BetterTTV#3077]
I think I remember this being a feature before the new twitch chat, but I might be wrong.

What I'm thinking is that when you hove over an emote it will show what channel the emote is from.
Possibly making it a link to the channel too if possible.

This would be a neat little quality of life feature.

**Comment by Nareese** [comment]
Twitch unfortunately broke this a while back when they changed how emotes are rendered.  There is already an issue open for this, and you can track it here:

duplicate of #2939
