### ISSUE TITLE
"resume watching" bug

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#308]
To reproduce:
- go to a channel that is hosting somebody
- click "View [insert hoster's name here]'s info" at the bottom of screen
- expand left panel (it will automatically switch to the hosted stream)
- contract left panel

At the bottom of the screen there will be the "Resume Watching" button which will do nothing when pressed, only gets replaced by the the original  "View [insert hoster's name here]'s info" Maybe depends on screen resolution? I'm using 1680x1050 here.

**Comment by night** [comment]
This is a minor bug caused by BetterTTV resizing the page when the sidebar is toggled. You can click on the "Resume Watching" again to fix the issue.

**Comment by night** [comment]
I can no longer reproduce this. Perhaps it was a Twitch bug.

**Comment by evodoc** [comment]
I can still reproduce it the same way.
