### ISSUE TITLE
Can the Twitch Stream Chat be hidden from BetterTTV settings?

### ISSUE THREAD

**Issue by erik8ghb** [night/BetterTTV#3082]
I’m using BetterTTV chrome extension. Can the Twitch Stream Chat be hidden as highlighted in red box from BetterTTV settings?

<img width="254" alt="untitled" src="https://user-images.githubusercontent.com/9939302/39287336-d2fba508-4955-11e8-9913-2df2b71d435d.png">

**Comment by night** [comment]
duplicate of #2914
