### ISSUE TITLE
Improper display of text, after resizing

### ISSUE THREAD

**Issue by BinaryEx** [night/BetterTTV#3083]
![image](https://user-images.githubusercontent.com/38753114/39299204-d95e0ba2-4950-11e8-8fc9-38c72002c5e5.png)
![image](https://user-images.githubusercontent.com/38753114/39299241-f17d72ae-4950-11e8-851c-698547bafab9.png)

**Comment by night** [comment]
this is working as intended. we don't support font sizes that large.
