### ISSUE TITLE
show subscriber notifications only in the relevant chat

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#309]
If you are hosting a channel the sub notifications are shown in the hoster's channel too. Can this be filtered?

**Comment by night** [comment]
Is there a reason you'd want them filtered? I'm hesitant to add a feature to filter a specific piece of chat.

**Comment by evodoc** [comment]
If a popular streamer is being hosted it can make the hoster's chat kind of spammy, and since the hosted streamer's chat itself can not be seen on the hoster's channel, it doesn't make much sense to show his/her subscribers either, **especially with the hoster's subscription icons**.

**Comment by night** [comment]
Right, well you can "/ignore twitchnotify" in chat if you don't want to see these.
