### ISSUE TITLE
BetterTTV Global Emotes keep appearing after an emote 

### ISSUE THREAD

**Issue by souzouker** [night/BetterTTV#3095]
" xxxxxxxxxxx
  BetterTTV Global Emotes "

 this keep appearing after any emotes https://imgur.com/VX28GQU and i don't know why it started to do this , sometimes it puts a random channel name.I've tried to reinstall bttv but it didn't work, i can't also open my bttv settings, do you have any ideas how to help mee?

**Comment by night** [comment]
if you see this text then our CSS is not being loaded properly. make sure you dont have other browser extensions installed. if you don't, then try clearing your cookies/cache
