### ISSUE TITLE
Every @username is highlighted.

### ISSUE THREAD

**Issue by BlueSheep123** [night/BetterTTV#3099]
![image](https://user-images.githubusercontent.com/13058118/39898679-d326fbe6-5485-11e8-8da6-76d61270f07e.png)

![image](https://user-images.githubusercontent.com/13058118/39898692-e14cc1f6-5485-11e8-9d67-efb4a1845e7b.png)

**Comment by MrMadakey** [comment]
Yeah this is also happening to me right now, apparently twitch added a new feature. If you could please enable a feature to disable this that would be fantastic!
