### ISSUE TITLE
Chat settings have two vertical scroll bars

### ISSUE THREAD

**Issue by CoolCmd** [night/BetterTTV#3105]
Firefox 59
![2scrollbars](https://user-images.githubusercontent.com/684851/39957191-650c2b9a-55f7-11e8-98c2-3c51b29d650f.png)

**Comment by night** [comment]
that would be a Twitch bug, not a BetterTTV bug

**Comment by CoolCmd** [comment]
I do not see this issue if BTTV is  disabled. Probably you incorrectly inject markup.
