### ISSUE TITLE
Prevent Hard To Read Chat Colours wont work.

### ISSUE THREAD

**Issue by MrSirViking** [night/BetterTTV#3106]
Ever since twitch made the new version of twitch many month ago,  my bttv just wont do the prevent hard to read chat colours. So if i am using theatre mode and a person with a black name comes in the person keeps the black colour. So white names on white background and black names on black background. Then about 2 month ago i reinstalled windows and bttv and all but the issue still persists. I posted on the forums about it but it was removed, and someone said i should post it in bugs.  So here it is.  I am on windows 10 Pro latest version and on Firefox 60.0 64bit. 

Here is an image: [https://s31.postimg.cc/cfpsc87a1/Bug.jpg](url)

**Comment by night** [comment]
im not able to reproduce this issue, so i'm guessing you have another extension installed that conflicts with ours. turn off or uninstall all other extensions and see if the issue persists.
