### ISSUE TITLE
Add a sound notification for whispers

### ISSUE THREAD

**Issue by ChrisM-Rogers** [night/BetterTTV#3107]
I've been using Twitch a lot lately and one of the things Twitch doesn't do well is informing you that you have a new whisper. They literally have made is whisper quiet. 

I'd like to see this extension add a small sound pop to signal a new incoming whisper (with the option to turn this off or on of course).

I'd also like to see support for a browser notification in the form of a visual dot (possible on Chrome at least) to the tab to visually signal there is something waiting for me there.

I may look into doing this myself soon after my studies are over with and submit a PR, but in case someone else beats me to it, I thought I'd make it a feature request in the meantime. 🙂

**Comment by night** [comment]
we used to have a sound, but we removed it since chrome will mute audio from background tabs
