### ISSUE TITLE
Prevent hard to read chat color names wont work.

### ISSUE THREAD

**Issue by MrSirViking** [night/BetterTTV#3110]
So the issue is this: Ever since twitch did their site update some month ago now, prevent hard to read chat name colours wont work. Meaning when watching twitch in theatre mode black names stay black instead of being corrected to some sort of Gray. then two month ago i reinstall my computer and it still does not work. Now i made a bug report of this and got told it must be some extra extension i have on that does it. So i decided to install chrome, since i use Firefox normally. So installed Chrome with BTTV as the only extension. and it still wont work. It just wont correct the colours. I simply cant figure out why. 
I am running Firefox 60.0 with latest BTTV on windows 10 pro.  
Here is how it looks: https://s31.postimg.cc/tnynzprcp/Bug.jpg As you can see there is a totally black name in the middle there. 

Thanks

**Comment by night** [comment]
What does it look like on Chrome for comparison? I cannot reproduce this on Chrome or Firefox personally.

**Comment by MrSirViking** [comment]
This is what it looks like on chrome https://s7.postimg.cc/xgygtee1l/Bug.jpg   And i am not saying there is something wrong with BTTV. Just that something is not working right with me and i am trying to find some help with what it could be that is causing it. :)

**Comment by night** [comment]
you have other extensions installed on both your browsers. disable all other browser extensions and try again

**Comment by MrSirViking** [comment]
All extentions turned off in chrome: https://s7.postimg.cc/tdkgy114p/Bug.jpg  Still not working right :)

**Comment by night** [comment]
unfortunately since I cannot reproduce this issue and nobody else has reported the issue there's not much I can do to assist you. You're welcome to post console logs or reproduction steps, but otherwise you're SOL.
