### ISSUE TITLE
Can't seem to update the extension

### ISSUE THREAD

**Issue by Billy0909** [night/BetterTTV#3113]
I noticed only the global emotes work and nothing else. So I looked into it and saw that it was out of date (my current version is 7.2.1 but the latest is 7.2.24) so I did everything I could think of. I reinstalled chrome removed the extension and re-installed it, but it stayed at 7.2.1, i'm not sure if i should contact chrome support or submit a ticket here so here I am.

**Comment by Billy0909** [comment]
Well I guess the channel emotes work now all I did was turn off all settings and restart chrome and it fixed it after turning them back on.

**Comment by Nareese** [comment]
The version of the extension (for each different browser) and the version of BetterTTV itself have nothing to do with one another.  The current version of the Chrome extension is 7.2.1.  You can see the version of BetterTTV itself by going to BetterTTV Settings -> About.  The current version of BetterTTV is 7.2.24.
