### ISSUE TITLE
Feature Request: assign editors to manage your channel

### ISSUE THREAD

**Issue by mellengaming** [night/BetterTTV#3114]
It would be nice to have an editor feature like ffz where you could select certain people to be able to manage your channel's emotes. I mod for a very busy streamer that i don’t like to poke every time a new emote comes out. Here is a pic of ffz’s version of it https://i.imgur.com/oMSI1ns.png

**Comment by VulpesHD** [comment]
Still waiting for this implementation.

**Comment by quetech2** [comment]
Hello!  Would also like to bump this feature request.  I would like my mods to be able to add/remove emotes, but I myself mod for a large channel with 1-2k avg viewers and the streamer is a very busy person.  I make animated emotes for them and other streamers, and would love to be able to upload those for them and not bug them every time.

Just curious, is this something being seriously considered for the near future?  Thanks for all you guys do!  :D

**Comment by Dorkrow** [comment]
Please bump this request. I'm sure it would be super useful. :)

**Comment by StephenFierce** [comment]
Can we get this feature? I think a lot of streamers would get the premium if they didn't have to manage all those emotes :)

**Comment by night** [comment]
This has shipped. Broadcasters can assign editors at https://betterttv.com/dashboard/editors

**Comment by quetech2** [comment]
Thank youuuuuu!!
