### ISSUE TITLE
App keeps breaking

### ISSUE THREAD

**Issue by Yonto** [night/BetterTTV#3119]
Every hour or so the emotes just suddenly stop working, and the only way to fix this is by clearing cache/history, which then means I have to go through the settings again.

Browser used: Google Chrome.

Tried reinstalling bttv and chrome, issue still resides.

**Comment by TheRealDannyyy** [comment]
Can also reproduce this issue using FireFox.
In my case this only seems to happen in some VoDs with theater mode enabled.

**Comment by night** [comment]
without reproduction steps im not able to reproduce and fix this.
