### ISSUE TITLE
BTTV icon not showing up

### ISSUE THREAD

**Issue by arsenal009** [night/BetterTTV#3121]
Hey guys, the BTTV icon doesn't show up for me anymore since a few days ago.
I'm talking about the icon next to the gear icon & the chat viewer list icon.
I already tried uninstalling & reinstalling but it did nothing.
Any idea how to get the BTTV icon to show up again?

Thanks

**Comment by night** [comment]
If you mean the emote menu, make sure you enable the "emote menu" in the BetterTTV settings.
