### ISSUE TITLE
disable host mode not sticking

### ISSUE THREAD

**Issue by harleqz** [night/BetterTTV#3123]
For the last week or so, disable host mode has not been working properly. channel's hosts will start playing on their own or if the page is refreshed, and if I go into BTTV's settings and disable and re-enable "disable host mode" it will turn off the host.. for about 20 minutes, before the host will start playing again. Incredibly frustrating and I can't find any recent information (as in from 2018 at least, all I'm finding are posts from 1-2 years ago) that this is a problem for anyone else.

**Comment by Nareese** [comment]
duplicate of #3116
