### ISSUE TITLE
"Theater mode" for clips

### ISSUE THREAD

**Issue by ckolderup** [night/betterttv#3126]
The default view for a clip on clips.twitch.tv is just small enough on MOBAs that it's hard to tell what's going on without full-screening the clip every time. I'd love to see a "theater mode" (along with an auto-toggle) offered by BetterTTV to make the clips viewing experience suck less.

**Comment by whitecrownclown** [comment]
@night If we were to do this, which approach would you pick? Iframe communication, cookie storage only for that specific setting or some other option? I'd like to open a PR if it's still relevant and do one of the two.

**Comment by night** [comment]
It looks like Twitch moved most clips to the Twitch website, making this feature request obsolete.
