### ISSUE TITLE
Rare Twitch VoD-Chat Crash

### ISSUE THREAD

**Issue by TheRealDannyyy** [night/BetterTTV#3128]
## Technical Details
- Windows 7 SP1
- BTTV version: v7.2.26
- Chrome M67
- Chrome Canary M69

## Problem Description
BTTV randomly crashes in VoDs, sometimes it crashes instantly but it's mostly random and occurring after 2h+ watching time. It requires a complete browser restart in order to stop it from instantly crashing which occurs after it crashed once. Since this issue is a pain to reproduce, the logs below might help.

**Error Log (Text):**
[BTTV_Error.log](https://github.com/night/BetterTTV/files/2058449/BTTV_Error.log)

**Error Log (Screenshot):**
![bttv_error](https://user-images.githubusercontent.com/15656049/40785941-1a707b84-64ea-11e8-9a08-29ee041f0646.png)

## Steps to Reproduce Bug
1. Install BTTV for Chrome
2. Visit this example VoD: https://www.twitch.tv/videos/263936122
3. Watch VoD or randomly seek in the VoD (in my case with _theater mode_ enabled)
4. Notice that the chat crashes randomly
5. Also notice that reloading the VoD now results in an instant chat crash
(restarting the browser fixes the instant crash issue)

## Expected behavior
BTTV should work fine in VoDs and shouldn't crash.

**Comment by night** [comment]
Do you have actual proof it's BetterTTV? Those stack traces show no signs of tampering from BetterTTV. It's failing to construct a URL, which means Twitch is failing to generate a valid URL (most likely for its video player, which we do not touch).

**Comment by TheRealDannyyy** [comment]
That's everything I could gather I'm afraid. Any suggestions on how to debug this properly?

**Comment by night** [comment]
I'm not able to reproduce using the steps you provided, unfortunately. If you have steps that work, feel free to reply.

**Comment by TheRealDannyyy** [comment]
I'm guessing that this might be a brower+Twitch issue anyway, since I can't reproduce it in Firefox.

Will get back once I got a reliable way to reproduce and if BTTV is really at fault.
