### ISSUE TITLE
BetterTTV breaks the TAB name completion (sort of)

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#313]
To reproduce:
Write in the chat: "m test", place the cursor right after "m" and press TAB (feel free to replace "m" with an other character based on what users are online in that channel). Nothing will happen; but if you have bttv disabled it will offer you the people's name starting with the character "m".

**Comment by voloshink** [comment]
Bttv implements its own tab completion, it's not the same as the twitch tab completion. The bttv tab completion only looks at the last word of the input.

**Comment by night** [comment]
Nothing here is broken. This is just how BetterTTV implemented tab completion. BetterTTV replicates Twitch's chat functionality, and we do not use Twitch's. This prevents BetterTTV from breaking as much when Twitch changes chat code.
