### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by resttarrr** [night/BetterTTV#3132]
Double left clicking on a stream would normally make the stream fullscreen. 

I don't know what happened but a few days ago that stopped being true. It would just put the "theatre mode" icon or remove it. When I disable betterttv it works as intended but with it turned on it just puts the theatre mode or removes it. It's very annoying and I don't want to delete the extension so is there a way to fix this bug?

**Comment by night** [comment]
i'm not able to reproduce this issue. additionally, double clicking on the player is a twitch player feature, not a BetterTTV feature.
