### ISSUE TITLE
Huge white bar

### ISSUE THREAD

**Issue by Lokermann** [night/BetterTTV#3134]
Whenever I open the BTTV Emote Menu, a huge white bar pop up and blocks 75% of my screen. 

I have no clue where, and how to fix it.

If anyone knows, let me know.

Thanks

**Comment by xgerhard** [comment]
Screenshot: https://imgur.com/ZWTmOpL
Not sure where in the code the inline style for emote menu is generated, removing the inline style `postion: relative` seems to fix it, since its overwriting the absolute position.

**Comment by Nareese** [comment]
Additional info from a user on Discord is that the problem does not occur in theater mode.

**Comment by Gahnik** [comment]
Also having similar issue with the large white space, it pushed my emote menu up and got it stuck even with theater mode.
Screenshots: https://imgur.com/gallery/dZ2h7rf

**Comment by Lokermann** [comment]
Well, the big ass bar is gone, guess that Twitch fixed it
