### ISSUE TITLE
Highlight from @ in chat

### ISSUE THREAD

**Issue by HaibaneKuramori** [night/BetterTTV#3138]
I was wondering if there was a way to change the color for the giant highlight that goes in chat around a message if someone @'s you.  The red is kinda ugly..  If I can't change it to pink, can I turn it off?  Is that possible?  I love that I can see all the other emotes, but the red color hurts me inside.

**Comment by night** [comment]
the color is nonconfigurable at this time. you can edit your highlights list in the chat settings to remove highlights.
