### ISSUE TITLE
'Auto Expand Followed Channels List' doesn't show subscribed channels list

### ISSUE THREAD

**Issue by kyodjinn** [night/BetterTTV#3139]
When 'Auto Expand Followed Channels List' is enabled, subscribed channels will not show up in the sidebar.

Example: I'm subscribed to scarra (who is online), but his stream is not showing up in the sidebar under Subscribed Channels. Disabling 'Auto Expand Followed Channels List' fixes the issue.
![image](https://user-images.githubusercontent.com/12821446/41074174-be48db7c-69d4-11e8-9e02-5dfda925ac12.png)

**Comment by night** [comment]
that must be an experimental feature Twitch is testing, since I don't see that in my sidebar. unfortunately I can't fix something I can't use.
