### ISSUE TITLE
Cannot switch to the Command Center on the overwatchleague stream

### ISSUE THREAD

**Issue by jonathanpchan** [night/BetterTTV#3141]
Attempting to switch to the Command Center on overwatchleague channel with BetterTTV enabled will switch and then quickly switch back to the standard stream. Once BetterTTV is disabled switching works as expected.

Using betterTTV 7.2.1 and Chrome Version 67.0.3396.79

**Comment by night** [comment]
Unfortunately that feature is behind a paywall and I'm not about to waste money just to reproduce a bug. lol.
