### ISSUE TITLE
Disable Homepage Autoplay pauses stream

### ISSUE THREAD

**Issue by alex-hk** [night/BetterTTV#3145]
With disable homepage autoplay enabled, when entering a stream before the homepage autoplay starts, the stream pauses instead.

Disable homepage autoplay also takes about 10 seconds to pause the homepage autoplay.

**To recreate:**
Turn on Disable Homepage Autoplay
Open homepage
Click on any stream
After a few seconds, the stream pauses.

Running BTTV v7.2.28 and Chrome 669.0.3359.181

**Comment by night** [comment]
this is a race condition that won't be fixed due to how it's implemented.
