### ISSUE TITLE
Twitch Prime Abos not available 

### ISSUE THREAD

**Issue by Stevenb1993** [night/BetterTTV#3146]
With the BTTV Application active the Twitch Prime Abonnements don't work anymore 
![gid hub](https://user-images.githubusercontent.com/40304304/41484701-1265626a-70de-11e8-8011-91c44ee81f47.png)

**Comment by Nareese** [comment]
There is an option in the BetterTTV Settings for `Hide Prime Promotions`.  Ensure that you have that turned off.

**Comment by night** [comment]
cant reproduce this
