### ISSUE TITLE
Emote tab completion broken

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3151]
With a new release of the site, Twitch removed chatController.chatService.selfEmotes, which breaks getTwitchEmotes() in the tab completion module (again).

**Comment by deniz87** [comment]
Came here to check if this issue was opened. Such helpful feature!

**Comment by theyuvalshor** [comment]
Happens to me too..
I hate having to use a colon.

**Comment by Grego7** [comment]
Yeah, same problem, only BTTV and Iphone emotes completion are working now with Tab.

**Comment by SaiyanOfDarkness** [comment]
Yeah this sucks.. I use this so much.. hoping it gets fixed soon.

**Comment by deniz87** [comment]
Wait, why is this closed? This is the main one.

**Comment by Nareese** [comment]
The issue is closed because the patch that fixes it has been applied.  It will be available when night updates the version and publishes it.

**Comment by deniz87** [comment]
Great! That's good to know!

**Comment by theyuvalshor** [comment]
awesome! thanks!

**Comment by mikkymit** [comment]
This is happening again.  I cannot tab complete anymore.  Cleared all cache and reinstalled BTTV and still having issues.  Please help!
