### ISSUE TITLE
"Tab Completion Emote" does not work

### ISSUE THREAD

**Issue by Eduardinholoko** [night/BetterTTV#3152]
The "Tab Completion Emote" command does not work, when I press TAB it does not complete the Emoji, just Nicknames.
![screenshot_1](https://user-images.githubusercontent.com/40523695/41811474-9a811e10-76e6-11e8-83cd-a95f86723b40.png)

**Comment by Eduardinholoko** [comment]
(firefox)
![image](https://user-images.githubusercontent.com/40523695/41811484-d1189bf6-76e6-11e8-9059-e8f4eed84a5e.png)

**Comment by samfun123** [comment]
Duplicate of #3151
