### ISSUE TITLE
Bttv refusing to connect after switching ISP

### ISSUE THREAD

**Issue by WoolsyMammoth** [night/BetterTTV#3155]
i moved apartments and setup a new ISP and now BTTV refuses to load. I can see the settings on my twitch dashboard (I am a pro member) but regardless of how many times I click the "connect to twitch" on the settings tab or on the actual Bttv website, i get a reload of the page with the "Welcome Guest" at the top. I have all ad blocks disabled and have attempted to change browsers and/or clear cache data. Nothing will let me log in. 
![bbtvsettings2](https://user-images.githubusercontent.com/40546588/41822441-4be17a3c-77b5-11e8-9557-36b5d5d6fc1e.JPG)
![bttv settings](https://user-images.githubusercontent.com/40546588/41822442-4bf263ce-77b5-11e8-8a8f-c0769214c33b.JPG)
![bttvsettings3](https://user-images.githubusercontent.com/40546588/41822443-4c027138-77b5-11e8-8f90-25f410acbbe2.JPG)

**Comment by night** [comment]
Connections to Twitch's API were timing out. This should be fixed now.
