### ISSUE TITLE
Uploading Emote Errors - bug

### ISSUE THREAD

**Issue by artheobear** [night/BetterTTV#3156]
I uploaded 2 emotes today and they went through, but I tried to upload 3 more to reach my max 5 emotes, but there was an error message saying png file is corrupted... so I save a new file and try to upload them again and then it says I reached my max 5 uploads...???? Now I have to wait 5 days to upload again? That is a complete nightmare... I don't want to repeat this issue 5 days then 5 days again... Please help!

**Comment by night** [comment]
we limit to 5 attempts per week at this time. otherwise people endlessly reupload emotes we've rejected
