### ISSUE TITLE
Disable Homepage Autoplay doesn't work after a recent frontpage revamp 

### ISSUE THREAD

**Issue by ayymirai** [night/BetterTTV#3157]
Twitch recently modified the front page of the site, so "featured broadcasters" are now in a "carousel" as their code calls it and the previous option to stop them from autoplaying no longer affects the featured broadcasts in their new place.

Reproducing:

1. in BTTV settings enable "Disable Homepage Autoplay"
2. Go to https://twitch.tv
3. Featured broadcaster starts to play, rather than getting paused.

BetterTTV v7.2.29, Firefox 60.0.2

**Comment by theweird1ne** [comment]
This also occurs in Chrome 64bit Version 67.0.3396.87
Note: It doesn't stop the home page video, but stops each stream when I start watching.
