### ISSUE TITLE
Some emotes size incorrectly in Twitch chat

### ISSUE THREAD

**Issue by Vafarien** [night/BetterTTV#3159]
FFZ emotes appear fine in BTTV emote selection menu, normal sizes, and previews.
But once posted in Twitch chat they appear as tiny pixels, not readable/distinguishable.
These images are just one example of some emotes shrinking to tiny unreadable sizes.

![image](https://user-images.githubusercontent.com/2349950/42032665-25eef520-7a8f-11e8-9f7d-b7167bd27dd1.png)
![image](https://user-images.githubusercontent.com/2349950/42032682-30e17eee-7a8f-11e8-9e2c-48b4a2849747.png)
![image](https://user-images.githubusercontent.com/2349950/42032909-f28756b8-7a8f-11e8-8447-298a0028f72f.png)

**Comment by Vafarien** [comment]
Google Chrome: Version 67.0.3396.99 (Official Build) (64-bit)
Windows 7 64-Bit SP1 (HomePremium)
BetterTTV: 7.2.1

**Comment by DmitryScaletta** [comment]
@night please fix your BTTV API.
For example the `Pog` emote.

**FFZ API**
![](https://i.imgur.com/hKd9TEW.png)

**BTTV API**
![](https://i.imgur.com/ArI6czO.png)

Don't return 4x resolution for emotes that don't have it.
