### ISSUE TITLE
TMIActionTypes renumbered again.

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3161]
Looks like Twitch has once again renumbered TMIActionTypes, which breaks most things that rely on that list, including ritual and sub hiding, and chat clear blocking.  Since I'm not sure where you get the comprehensive current list for these, I can't PR it myself.  It would be great if we could get them to expose this list from their own code so we didn't have to keep updating this, especially since they seem to like updating it in the most breaking way possible (renumbering things in the middle of the list).

**Comment by xereau69** [comment]
7.2.30 will not install on Chrome.  Perpetually stuck at 7.2.1.  Reinstalled Chrome.  Deleted all cookies and data.  The options menu is gone in twitch chat.  Can't see any bttv emotes.
