### ISSUE TITLE
An disappearence of the BTTV emoties menu

### ISSUE THREAD

**Issue by FareWel1** [night/BetterTTV#3162]
Hello. So, my problem is an disappearence of the BTTV emoties menu. All is correctly installed, everything working good, and i can see another's users emoties in chat, and i can use the emoties by writing them in chat i.e. "Clap", "monkaS", "gachiBASS" and it's working. But i have not a button for choising the emoties. Just no button for a emoties list. 
I have checked “on” BTTV emotes, I cleared all my internet history and cookies and cache. 
Am I missing something obvious?

**Comment by LeotomasMC** [comment]
is the setting that says "Emote Menu — Get a more advanced emote menu for Twitch. (Made by Ryan Chatham)" turned on as well? Thats the setting that shows the BTTV emote menu button (its a little :D face user the chat box next to the settings button and user list button). If its not turned on, it wont show this button

**Comment by FareWel1** [comment]
Yes. I tried to turn it off and on again, and .... it's fixed. Why it is
not working before - i have no idea. But thanx a lot and sorry for taking
your time.

All the best.

2018-06-29 23:46 GMT+07:00 LeotomasMC <notifications@github.com>:
