### ISSUE TITLE
Stream Description on Left Side Chat 

### ISSUE THREAD

**Issue by mumiaazul** [night/BetterTTV#3165]
When you activate the Left Side Chat on BetterTTV, your followed channels goes to the right side, but it doesn't show the description of the channel in that mode.

**Comment by night** [comment]
Can you elaborate and/or provide a screenshot of the issue?

**Comment by Aaron128l** [comment]
Hovering over will show the titles of the stream:

![](https://i.aaron128l.com/DbiN3mk.png)

Better yet there is no easy way to fix this with CSS alone due to just a static tooltip with generated styles.
```html
<div class="tooltip-layer" style="transform: translate(0px, 107px);width: 241px;height: 42px;">
    <div class="rich-content-tooltip">
        <div class="tw-absolute">
            <div class="tw-border-b">
                <div class="rich-content-tooltip__pointer-target">
                    <stuff/>
```

This also effects the hover on friends as well.

**Comment by night** [comment]
ah yes. this bug. unfortunately it's a cantfix type of issue
