### ISSUE TITLE
Mod option of timeout/ban -slidebar missing

### ISSUE THREAD

**Issue by Peelotar** [night/BetterTTV#3166]
When using the Twitch with BetterTTV on Mozilla Firefox, I've had this really useful mod option, where you can rightclick chat-usernames of the channel and it opens a slide-bar of timeout lenght/ban options.
(Picture of the option mentioned: https://cdn.discordapp.com/attachments/454605888817332234/454607720734261258/unknown.png).

For some reason this hasn't been available for me the last couple of days and I would want it back.
Is the option missing because my settings somehow, or is it a bug?

**Comment by night** [comment]
Do you use other Twitch extensions? It’s possible one of them is conflicting with ours to cause this condition

**Comment by night** [comment]
closing due to no response

**Comment by Reecon** [comment]
Hi, I have the same problem. I disabled all other add-ons in firefox, and with just BTTV enabled (v7.2.31) there is still no right-click mod menu for me.
