### ISSUE TITLE
[Feature Request] Make it so people can appeal their ban from BTTV shared & uploaded emotes (Streamers Perspective)

### ISSUE THREAD

**Issue by FunkiestWheat74** [night/BetterTTV#3167]
**Make it so people can appeal their bans from BTTV please!**

It would be great if you could give chances to banned users who would still like to use BTTV shared emotes for their channel again, it feels very one-sided, so please give us the option to appeal bans (maybe a **strike system**?), because a permanent ban from a 3RD party extension for Twitch is pretty **excessive** for your users. Just a suggestion, nothing more.

Thank you for your time reading this.
-Banned User
FeelsBadMan.

**Comment by night** [comment]
this isn’t the place to discuss policy changes.
