### ISSUE TITLE
Can't watch 2 streams at once

### ISSUE THREAD

**Issue by quelaan69** [night/BetterTTV#3169]
I have 2 streams open on 2 screens, only the stream on selected window plays normally, while the other starts to buffer. When I change selected window/tab buffering and playing swaps places. Only the selected one plays normally. 
Problem stops when I disable bttv.

I'm using the most recent firefox and windows 7. I was using both ffz and bttv. But only disabling bttv stopped the problem.

**Comment by night** [comment]
we don’t have logic that automatically pauses the video player, so I can’t see how it’s related to us.
