### ISSUE TITLE
Betterttv emotes, besides phone emoji emotes, aren't loading

### ISSUE THREAD

**Issue by Stormer0119** [night/BetterTTV#3170]
For some reason, anything but the phone emoji emotes aren't loading. I have cleared cookies, I have no other addons installed, and every other aspect of BTTV is loading. I have the Java script 

Failed to load resource: the server responded with a status of 404 ()
adservice.google.com/:1 Failed to load resource: the server responded with a status of 404 ()
pagead2.googlesyndication.com/:1 Failed to load resource: the server responded with a status of 404 ()
api.betterttv.net/2/emotes:1 Failed to load resource: net::ERR_CONNECTION_RESET
admiralbahroo:1 Uncaught (in promise) Object
api.betterttv.net/2/changelog:1 Failed to load resource: net::ERR_SSL_VERSION_INTERFERENCE
cdn.betterttv.net/betterttv.js:222 [Emote Menu]  (v2.2.0) Initial load on https://www.twitch.tv/admiralbahroo
admiralbahroo:1 Uncaught (in promise) Object
api.betterttv.net/2/channels/admiralbahroo:1 Failed to load resource: net::ERR_CONNECTION_RESET
null:1 Failed to load resource: the server responded with a status of 404 ()
3cdn.betterttv.net/betterttv.js:222 getClip() is deprecated. Use getPlaylist().getClip() instead.
e.(anonymous function) @ cdn.betterttv.net/betterttv.js:222
2cdn.betterttv.net/betterttv.js:222 getClip() is deprecated. Use getPlaylist().getClip() instead.
e.(anonymous function) @ cdn.betterttv.net/betterttv.js:222
getClip @ player.twitch.tv/js/player.js:28
d @ player.twitch.tv/js/player.js:28
playVideoContentPart @ player.twitch.tv/js/player.js:28
(anonymous) @ player.twitch.tv/js/player.js:11

Yes I was watching Bahroo when I got this, shoosh.

**Comment by night** [comment]
> api.betterttv.net/2/channels/admiralbahroo:1 Failed to load resource: net::ERR_CONNECTION_RESET

log shows issues connecting to our server. if you're still having issues, it might be caused by an adblocker-ish extension blocking our connections or some kind of firewall.
