### ISSUE TITLE
(Feature Request) Enhancement BetterTTV Pro Account Gives ability to use BetterTTV emotes on Twitter and Youtube 

### ISSUE THREAD

**Issue by JmoneyGamer** [night/BetterTTV#3176]
Hear me out because this feature will benefit both everyone who uses BetterTTV emotes if you have a pro account. and everyone who made better. I wonder why you guys have never thought of adding this feature but make it so users can connect their twitter account or youtube account so u can use your BetterTTV emotes on twitter in dm's and tweets you make or if you use an emoji on someone's tweet instead add a menu for Twitter and Youtube so u can use BetterTTV on twitter and youtube if you have a pro account this will get u guys to get lots more money if you able to use your own emotes when u comment on someone's video and etc. And all u guys would need to do is add a emote menu like on twitch
![screenshot 63](https://user-images.githubusercontent.com/41284032/42748085-ce437ef0-88ac-11e8-875c-483fc2c739d2.png)
Just make it for youtube and twitter they already have emoji's and emotes and emoji's aren't that different

**Comment by night** [comment]
It would take significantly more effort to make our extension operate on other platforms. We have enough trouble keeping up with Twitch changes as-is. Gonna have to pass on this, sorry.
