### ISSUE TITLE
Disable Auto-Play on Home Page

### ISSUE THREAD

**Issue by JungleSurgeon** [night/BetterTTV#3178]
Windows 8.1.  Using Chrome.

The featured channel on Twitch's home page continues to play after selecting Disable.

I tried un- and re-selecting all preferences, re-installing BTTV, and re-installing Chrome.

**Comment by night** [comment]
I'm not able to reproduce this.

Do you have this homepage? 
![image](https://user-images.githubusercontent.com/2942184/43041015-03cb6e4c-8d09-11e8-869d-c3169d4ad3a6.png)
