### ISSUE TITLE
disable host mode not working- STILL

### ISSUE THREAD

**Issue by harleqz** [night/BetterTTV#3179]
The disable host mode has not been functioning properly for months and now it has stopped working altogether. as much as I love the streamers I watch, I don't enjoy the people they host most of the time and don't want to worry about them randomly playing when I've fallen asleep to a stream or am listening to one while I do other stuff.

**Comment by Wikk1dd** [comment]
Experiencing the same issue, I have it set to disable host mode with 5 pinned streamers in chrome, Found all 5 hosting and autoplaying the video this morning, Checked all settings turned it off and back on and no change, Please address this fix asap

**Comment by darius07** [comment]
The same issue is present in Firefox. Turning it off and on has no effect.

**Comment by TwitchKappa** [comment]
it works for a couple days and then twitch breaks it again. it's not really bttv fault

**Comment by bunbunlov** [comment]
mmn. i been usin dis tampermonkey script. streamers is yr streamers in lowercase. not ideal, but functional.

pls don't ask about the =1 thing.

also if this is in bad taste posting this here, sries :3

`// ==UserScript==
// @name         twitchlov
// @namespace    http://oh.kh/
// @version      0.1
// @description  nuh
// @author       bunbunlov
// @match        *.twitch.tv/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    window.setInterval(function(){
        var streamers = ['nicholena'];
        var lov = false;
        var naem = document.getElementsByClassName('qa-display-name')[0].text.toLowerCase()
        var vids,v;
        for(var s in streamers){
            if(streamers[s].indexOf(naem)==0){
                lov=true;
            }
            if(!lov){
                vids = document.getElementsByTagName('video');
                for(v in vids){
                    if(vids[v]!=1){
                        vids[v].volume=0;
                    }
                }
            }else{
                vids = document.getElementsByTagName('video');
                for(v in vids){
                    if(vids[v]!=1){
                        vids[v].volume=1;
                    }
                }
            }
        }
     },10000);
})();`
