### ISSUE TITLE
Can't see Message deleted

### ISSUE THREAD

**Issue by vMidway** [night/BetterTTV#3187]
I can't click on the message deleted message anymore, and i haven't could do that in a long time now, i thought it would've been fixed over time but it doesn't seem like it

**Comment by doubledgedboard** [comment]
If you're using BTTV + FFZ I noticed recently that FFZ is now affecting the BTTV message deleted setting.

e.g. if you're using FFZ, BTTV will no longer turn `<message deleted>` back to the original message.

**Comment by vMidway** [comment]
What is FFZ?

**Comment by doubledgedboard** [comment]
FrankerFaceZ, an extension similar to (but not necessarily compatible with) BetterTTV

**Comment by night** [comment]
extensions sometimes conflict with ours, so you would want to ensure you're using only our extension
