### ISSUE TITLE
Left Side Chat Subscribe Button Bug

### ISSUE THREAD

**Issue by Blechkelle** [night/BetterTTV#3198]
Hello i noticed that when the Left Side Chat option is enabled i cannot see the subscription box because its on the right side of the button. 

![screenshot_3](https://user-images.githubusercontent.com/35072021/43862600-6aa246ea-9b5a-11e8-8f96-6377e39206f5.png)

**Comment by night** [comment]
this is not something we can fix due to how twitch designed their popouts
