### ISSUE TITLE
No way to disable linehistory

### ISSUE THREAD

**Issue by LuisBerserker** [night/BetterTTV#3201]
/linehistory off doesnt work :"Unrecognized command: /linehistory"
and there is no option in the settings
please add one of the above :)

**Comment by night** [comment]
this setting was removed because a setting for it should not be needed. it only existed because users were unable to navigate using arrow keys in the input box when editing a message, which we fixed in the v7 rewrite a long time ago (when we removed this setting).

**Comment by LuisBerserker** [comment]
Well if i want to go to the top of my message and i press up once too often(or hold it for too long) i lose everything i wrote. That is annoying if i want to have a long, carefully written message. I understand your choice, but ask you to consider readding the command. Thank you for making BTTV a thing either way.

**Comment by night** [comment]
You don't lose everything. You press down and it reappears.
