### ISSUE TITLE
Pin Highlighted Messages bugged/issue

### ISSUE THREAD

**Issue by Lordchech** [night/BetterTTV#3204]
I was receiving Pinned highlighted messages just fine until recently it has stopped working. I've tried updating and clearing cache, turning the setting on and off makes no difference. Any reason for this?

**Comment by xgerhard** [comment]
From what I've noticed, all words set in the "Highlight Keywords" setting work and get highlighted/pinned as expected, except the exact username match.

Maybe something with the Twitch mention span changed?

**Comment by Digikid13** [comment]
I found out the cause of this, and I have a PR up for it ☺️
