### ISSUE TITLE
Split chat in dark mode

### ISSUE THREAD

**Issue by L1ght5h0w** [night/BetterTTV#3216]
I have dark mode activated and Split Chat on. Normally this works fine, with the chat messages alternating dark purple then light purple, or what ever color it is. Today (8-22-2018) it is alternating dark purple then white, making the white background chat impossible to read.
I tried disabling/re-enabling dark mode and toggling split chat on/off, as well as reloading the page several times, with no luck.
[Example](https://i.gyazo.com/c5972224730fa22966238d67d6d1cef4.png)

**Comment by DovahkiinM** [comment]
Same problem on chrome with the new update today

**Comment by CornyRiegel** [comment]
^

**Comment by L1ght5h0w** [comment]
Thank you Nareese
