### ISSUE TITLE
/popout chat no BTTV settings option 

### ISSUE THREAD

**Issue by knowfear1337** [night/BetterTTV#3218]
Odd issue, when i want to change settings i have to open a new tab just to use the options.
I use streamlink so i just have chat in a popout and i was toying with the idea of switching to chatty or hexchat IRC but neither of them have the awesome emote menu ...

pictured problem
https://imgur.com/a/ikeWneS

**Comment by night** [comment]
this is working as intended. we dont support popout/embed chat for settings for now

**Comment by knowfear1337** [comment]
any particular reason why ? 
BTTV and the emote menu are great and i think i almost exclusively use the poped out chat even before when it was just /chat at the end dunno why they changed it.
but as long as all the settings carry over and work [which they do] then i guess ill just have to live with opening another tab if i ever have to change something
