### ISSUE TITLE
Having problem with dark theme

### ISSUE THREAD

**Issue by klocek1234** [night/BetterTTV#3219]
After turning on dark theme in setting I have like white and black chat fragments. 
for example https://i.imgur.com/KaDqemX.png

**Comment by xFirez** [comment]
Same.

**Comment by fossilz** [comment]
This is an old bug re-surfacing. If you turn off Split Chat in the settings it should be ok until it's fixed.

**Comment by derpyderpaderp** [comment]
Can confirm this being an issue.

**Comment by Nareese** [comment]
duplicate of #3216

**Comment by klocek1234** [comment]
thx
