### ISSUE TITLE
Left Click Timeout on MAC comes up with other options

### ISSUE THREAD

**Issue by ZrMzx** [night/BetterTTV#3229]
Hi,

When clicking on a name to timeout on a MAC with BTTV it also comes up with some options whites freezes your input and you are unable to do the timeout.
<img width="458" alt="screen shot 2018-08-25 at 9 43 49 am" src="https://user-images.githubusercontent.com/23144061/44612439-f0288100-a84b-11e8-9090-e5a464afd980.png">

If you guys could some how make it so theses options don't come up that would be great for MAC users.

**Comment by night** [comment]
this is not something we can fix as it would be classified as a browser bug. we prevent that action and it is the browser's responsibility to handle the prevention.
