### ISSUE TITLE
One edition to make it easier for moderators!

### ISSUE THREAD

**Issue by jon99867** [night/BetterTTV#323]
Hey,

I love using BTTV for moderating because it makes it so easy to time people out quickly. However, because the chat moves very quickly sometimes, when I try timing out someone, the chat moves and I end up timing out someone else. Can there be a way in which if I hover my mouse over the mod icons in chat, would it let the chat window "stand still" or freeze? 

Thanks!

**Comment by night** [comment]
Try scrolling chat up.

**Comment by jon99867** [comment]
But I can't always scroll up. If the message is at the bottom of the page, I have to hope that my scroll both doesn't go over the message.

**Comment by amamut** [comment]
@jon99867 Scrolling the chat up freezes the messages. Once its frozen you can scroll up or down to find the message. If you scroll ALL THE WAY down to where you are seeing new messages then chat won't be frozen anymore.

**Comment by jon99867** [comment]
@amamut I get that, but the issue I'm specifically referring to is if the message is at the very bottom of the chat. For those messages, I don't have the option to scroll up to freeze the chat, because otherwise, I can't even timeout the person in the first place.

Sorry if this whole thing seems a bit silly. It's just something that would make it easier on me, that's all.

**Comment by night** [comment]
@jon99867 Logically speaking here, if chat is moving that slow you shouldn't have an issue timing them out anyways. If you completely want to prevent an accidental timeout, enable the the moderation card keybinds in the BetterTTV settings and click on a persons name and press "t" to time them out.

**Comment by jon99867** [comment]
True, @night. I guess I forgot about that. Sorry about this whole issue, and thanks for your understanding.
