### ISSUE TITLE
The extension is completely bugged for me.

### ISSUE THREAD

**Issue by Kilowog01** [night/BetterTTV#3232]
The settings button no longer appears to me.
Unchecked options are working and vice versa

Things I've tried:
Reinstall the extension
Delete cache
Restart the computer
Restart firefox

I believe that simply deleting the extension's configuration file would already make this work, but I have no idea how to do this.

**Comment by night** [comment]
clear cache again and see if the issue persists

**Comment by Kilowog01** [comment]
I cleared the cache again and the issue persists...
