### ISSUE TITLE
Some things not working

### ISSUE THREAD

**Issue by derpyderpaderp** [night/BetterTTV#3235]
So far host channel isn't working, twitch's emotes are not included in tab completion. I have cleared cache and reset chrome, not fixed. reinstalled betterttv and still same exact issues. Happening in the latest version of chrome. I am unaware if this is happening in firefox.

**Comment by SaiyanOfDarkness** [comment]
I'm pretty sure this is related to a recent update they made.  I had to change my custom css style in the past few days.

**Comment by zewm** [comment]
Getting the same problem on my end. No custom emotes and no tab completion.

**Comment by night** [comment]
duplicate of #3233
