### ISSUE TITLE
I keep getting this error 

### ISSUE THREAD

**Issue by kilroych** [night/BetterTTV#3236]
cdn.betterttv.net/betterttv.js:222 webgl context not available TypeError: Cannot read property 'getExtension' of null
    at cvp.twitch.tv/2.6.3/mediaplayer.min.js:1
    at new i.MediaPlayer (cvp.twitch.tv/2.6.3/mediaplayer.min.js:1)
    at player.twitch.tv/js/player.js:40 

e.(anonymous function) | @ | cdn.betterttv.net/betterttv.js:222
-- | -- | --

**Comment by night** [comment]
It's an error in Twitch's player. The reason it says `betterttv.js` is because we wrap the window error handler so we automatically receive errors from clients.
