### ISSUE TITLE
Show Deleted Messages not working.

### ISSUE THREAD

**Issue by lemont34** [night/BetterTTV#3244]
Used to work, but a few days ago it just stopped working.
The messages will turn into message deleted even if I have Show Deleted Messages ON.
No matter how many times I turn it off and on it just wont work anymore.
![58647](https://user-images.githubusercontent.com/42845220/44867265-f12d3880-acb9-11e8-9be1-49ed55dcd10d.JPG)

**Comment by Nareese** [comment]
duplicate of #3233
