### ISSUE TITLE
Disable Host Mods

### ISSUE THREAD

**Issue by Bwaida** [night/BetterTTV#3247]
Disabling host mode does not seem to work correctly. You turn in on and it just keep switches back from the host to the channel over and over again.

**Comment by night** [comment]
not able to reproduce

**Comment by Grasnek** [comment]
I'm having the same issue, see #3255

**Comment by krixalis** [comment]
Same issue here.

**Comment by night** [comment]
what other extensions are you using? have you tried disabling those?

**Comment by Grasnek** [comment]
I have a lot of extensions, (not all are always loaded at the same time)
Addons I usually have running:

Adblock Pro
Avast Online Security
BetterTTV
Deluminate
Google Calendar
Google Hangouts
Google Mail Checker
Google Translate
uBlock Origin

When I deactivate all but BTTV, relaunch Chrome, then test the stream that's **playing reruns & hosting another channel at the same time**, it still flips back and forth.

I've also noticed that the BTTV options in the cogwheel menu below the chat don't always show. Reloading the twitch page fixes that.

**Comment by TwitchKappa** [comment]
at 1st it didn't make sense why twitch was continually breaking host mode disable. now with the wave of unblockable ads it makes sense. every time a streamer hosts someone else, it gives twitch the excuse to hit every viewer with a new wave of pre-roll ads, whether the viewer wants to see the new streamer or not. blocking host mode denies them that revenue.

also yes it is currently broken as of right now.
