### ISSUE TITLE
Hide Event/Rerun Purple bar.

### ISSUE THREAD

**Issue by Caplooo** [night/betterttv#3251]
This thing takes up space on the screen and moves the video 2 centimeters down.

![screenshot_1](https://user-images.githubusercontent.com/42878669/44936551-73c6fe00-ad75-11e8-8163-40f4ba9a4078.png)

**Comment by billysielu** [comment]
Related: #3424

**Comment by Feky** [comment]
Anytime soon this is annoying and can't hide it?

**Comment by night** [comment]
it looks like twitch has made this less intrusive, so this is no longer needed
