### ISSUE TITLE
PogU Is Broken... PepeHands

### ISSUE THREAD

**Issue by Amnesiac9** [night/BetterTTV#3257]
My PogU won't show up, I have frankerfacez enabled, monkaS monkaHmm and others work, I have blacklisted gachiBASS and a few !Commands that get spammed but thats it. 

What else can I do?

**Comment by deniz87** [comment]
Try refreshing your browser...
Close topic if it fixes it.

**Comment by Amnesiac9** [comment]
Yeah forgot to mention I tried that, lol, would be kinda sad if I went and posted a github issue before trying to restart my browser.

I'll try reinstalling the extention later, anything else I can try?

**Comment by deniz87** [comment]
Your issue is obviously not global and looks like there is an issue on your end.
I would open a topic at the [bttv forum](https://community.nightdev.com/c/betterttv) for support instead of reporting it here.
Good luck!
