### ISSUE TITLE
Uptime issue

### ISSUE THREAD

**Issue by deniz87** [night/BetterTTV#3261]
The uptime counter under the video player doesn't show up when you switch channels. (not everytime but in a few switches randomly) 

"/uptime" command also returns _"Unrecognized command: /uptime"_ error.

The counter shows back up in 60secs but the /uptime command still returns as Unrecognized command.

_Unless you refresh the browser._

**Comment by night** [comment]
I'm not able to reproduce this, but it is possible if our patching (of Twitch's chat) fails. There's not really anything we can do to make it more reliable than it is (and it already is fairly reliable). It can take up to a few seconds after you load a stream before we patch the chat (we wait for things to load first).

**Comment by night** [comment]
Also the "uptime counter" is not a feature BetterTTV provides. We only provide the /uptime command. If other extensions are installed they may affect the reliability of our patching.
