### ISSUE TITLE
Messages only get deleted after another message is sent

### ISSUE THREAD

**Issue by tovello** [night/BetterTTV#3262]
Hello, I think I found a bug and it's causing problems. I have my own bot with a small script to /timeout people who type !vanish but the message doesn't get instantly deleted. The message only changes to <message deleted> whenever another message is put in chat and it scrolls up. 

I am certain this is caused by bttv because whenever I disable the extension and try it again the message  gets instantly changed into "message deleted" The problem is that sometimes the chat doesn't go that fast so people type !vanish and for a long period of time nothing happens. 

I think this could also cause problems if you have certain phrases blacklisted. The "delay" is very annoying. Can someone look into this please? 

With kind regards, 
Ben

**Comment by tovello** [comment]
?

**Comment by night** [comment]
I'm not able to reproduce this. Do you use other browser extensions? If so, one of them could be conflicting with ours.
