### ISSUE TITLE
Non-webextensions version

### ISSUE THREAD

**Issue by WalrusInAnus** [night/BetterTTV#3274]
I am using Pale Moon browser, which is a derivate of Firefox 52 ESR. Basically, the browser does not use webextensions.
Could you provide a version that would install on that please?

**Comment by samfun123** [comment]
I made a userscript which should do the same thing as the extension which you can find [here](https://github.com/night/BetterTTV/issues/3158#issuecomment-423497937).

**Comment by WalrusInAnus** [comment]
I have no idea what userscript is and what to do with it though :(

**Comment by WalrusInAnus** [comment]
Thank you!

**Comment by WalrusInAnus** [comment]
Actually, when I click on the file, it opens it like the browser was a file viewer :(
