### ISSUE TITLE
Babel Reference Error on gulp watch

### ISSUE THREAD

**Issue by scott-p53** [night/BetterTTV#3276]
After cloning the project, running npm install and then gulp watch I've run into this error 

> Caught exception:  { ReferenceError: [BABEL] /home/user/Documents/projects/BetterTTV/build/index.js: Unknown option: /home/user/node_modules/react/index.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

I've attempted to add babel-preset-react to the package.json and to the presets in gulpfile.js. However, this did not solve the issue as suggested on stackoverflow. Any suggestions on how to fix this?

I'm currently running on Ubuntu 18.04.1 with 6.4.1 for my npm version

**Comment by night** [comment]
you have node modules in your user folder conflicting with our node modules. i would recommend wiping your user node modules.

**Comment by scott-p53** [comment]
After wiping the node modules in my user dir I now have this error

> Caught exception:  { Error: Couldn't find preset "react" relative to directory "/home/user" while parsing file: /home/user/Documents/projects/BetterTTV/build/index.js
    at /home/user/Documents/projects/BetterTTV/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19

**Comment by night** [comment]
definitely something is messed up with your installation or dependencies. a clean install of our repo's deps works fine (as is confirmed by CI building fine)

**Comment by scott-p53** [comment]
I'll try completely reinstalling node/npm and seeing if that fixes it

**Comment by scott-p53** [comment]
Wasn't able to figure out exactly was causing it even after I did a clean install of both node and npm. I did find a hacky work around where I installed babel-preset-react in the directory /home/user/ and gulp watch completed successfully after that.
