### ISSUE TITLE
"Auto Expand Followed Channels List" doesn't work on https://www.twitch.tv/directory

### ISSUE THREAD

**Issue by Malow** [night/BetterTTV#3277]
As per topic. When in a channel the follow-list on the left hand side auto expands just fine, but when at the "browse" page it does not. Also since a couple of weeks back Twitch changed so that "Show more" doesn't show all the rest, but only loads another 8 entries. I always want my entire follow list expanded so would be nice if you could change so that the "Show more" button is automatically continuously pressed until there's nothing left to show.

BetterTTV v7.2.43
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

Thanks

**Comment by night** [comment]
Not really something we can fix right now unfortunately. If you look how Twitch's UI for that functions, it always shows a "Show More" button even if there are no more to show (clicking it after all are loaded results in no more results being added). We would only be able to handle this better if that button was stateful.

**Comment by Vafarien** [comment]
I there some way to add a small Text/CSS clickable button that functions the same as the "show more" clickable interaction?
![image](https://user-images.githubusercontent.com/2349950/46269681-99bbfb80-c4f7-11e8-91b6-e18d02246afa.png)
that can be clicked while collapsed like this?
![image](https://user-images.githubusercontent.com/2349950/46269754-f28b9400-c4f7-11e8-822a-f1e4a1cb3180.png)
If i manually click 'show more' and collapse it back like this, it already remains scrollable.
![image](https://user-images.githubusercontent.com/2349950/46269795-354d6c00-c4f8-11e8-8b8d-223d57a5da7d.png)

(i.e. a plus symbol? [+] )

**Comment by Malow** [comment]
@night Ah ok. I noticed the behavior of this functionality changed slightly with version 44. It seems that now the "Show more" gets automatically pressed twice when you're on a channel, which is definitely an improvement at least :)

The functionality still doesn't work at all for the https://www.twitch.tv/directory URL though, which is the main-part of this issue IMO.
