### ISSUE TITLE
why do my bottom buttons disappear when twitch chat scrolls down?

### ISSUE THREAD

**Issue by fearlessmango** [night/BetterTTV#3281]
It just started happening today but it seems whenever the twitch chat starts scrolling down from people chatting, the three buttons on the bottom disappear.

In the first picture is when I just load into the stream, everything is fine.
![why](https://user-images.githubusercontent.com/43656718/46176547-d11f7380-c27d-11e8-99f5-4ada43b2df7f.png)

Then as people start chatting and the chat starts scrolling down, the bottom buttons disappear
![why2](https://user-images.githubusercontent.com/43656718/46176567-e4cada00-c27d-11e8-8a07-a88a851a3ff6.png)

The only way to reset it is to refresh the stream

**Comment by regmebaby** [comment]
This happens even if the BTTV-Plugin is disabled. So it's a problem caused by Twitch.

**Comment by regmebaby** [comment]
Seems to be fixed.
@fearlessmango Can you confirm that?

**Comment by fearlessmango** [comment]
yeah looks fixed today
