### ISSUE TITLE
Host shows as undefined

### ISSUE THREAD

**Issue by riddlew** [night/BetterTTV#3283]
After installing BTTV, the link right above a video being hosted that shows "Hosting <username>" returned "https://www.twitch.tv/undefined" instead of the channel of the person being hosted. The link above chat that says "Go to channel" still links properly, just not the text above the video of the person being hosted. Turning off BTTV removes this error.

**Comment by night** [comment]
Do you have "Disable Host Mode" enabled? It works fine on my machine both enabled and disabled.

**Comment by riddlew** [comment]
It is not enabled. When I turn it on, the hosted channel doesn't display so that's right. But with disable host mode off, it just gives the link "undefined".

**Comment by night** [comment]
What other browser extensions are you using? Have you tried disabling those and seeing if you can reproduce it still?

**Comment by riddlew** [comment]
AdBlock, LastPass, BTTV, Link Klipper, Reddit Enhancement Suite, ScriptSafe, Tabs Outliner, and The Great Suspender. I have tried disabling them and it still had the same result. I also tried installing BTTV on Chrome on a separate computer with no other addons and the result was the same. Turning BTTV off removes the undefined problem, and turning it back on brings it back. I also tried turning every setting off in BTTV but the issue is still there.

**Comment by riddlew** [comment]
I just found out that it only happens if I load a streamer's direct page vs clicking it from the following page. If I type in a streamer's URL  and they're hosting someone, the person being hosted has a link of twitch.tv/undefined. However, if I go to my following page and click on the person that's hosting someone, it no longer shows the person being hosted as undefined. 

So Streamer A is hosting Streamer B, typing twitch.tv/StreamerA shows they're hosting Streamer B but the link to Streamer B is undefined.
Going to the following page, click on Streamer A's stream. Streamer A's page loads and now the link to Streamer B correctly shows twitch.tv/StreamerB.
