### ISSUE TITLE
Connecting w/ twitch acount

### ISSUE THREAD

**Issue by WaveShredder** [night/BetterTTV#3284]
When trying to connect my Twitch Account with BTTV, it gets caught in a redirect loop and doesn't log me in.

Has this been brought up or addressed yet?
![2018-09-30 13_05_26-window](https://user-images.githubusercontent.com/36644778/46262123-d95ff480-c4b1-11e8-8ab6-2189ca4a0e74.jpg)
![2018-09-30 13_04_42-window](https://user-images.githubusercontent.com/36644778/46262124-d9f88b00-c4b1-11e8-8b3e-f90cb34bcf10.jpg)

**Comment by night** [comment]
I'm not able to reproduce this. In general, we do redirect back to Twitch if we were unable to exchange the authorization code for a valid token.
