### ISSUE TITLE
[Feature request] Open the channel when clicking on an offline channel in the sidebar

### ISSUE THREAD

**Issue by ThibaultVlacich** [night/BetterTTV#3289]
Hello.

Currently on Twitch, when you click on an offline channel in the sidebar that have videos you've not seen, it opens the last video.

This is really annoying and I'd prefer that it redirects to the channel that I click on, and not that it directly opens the last video available. Could this be doable?

**Comment by night** [comment]
my sidebar only shows live channels.. so i'm not able to reproduce this.

**Comment by ThibaultVlacich** [comment]
Even if you click on "Show more". You're probably following a lot of channels, so there's enough live to fill the list.

Here's a screenshot:
![capture](https://user-images.githubusercontent.com/334940/48719380-a5858d80-ec1d-11e8-8827-6ad090691b02.PNG)
