### ISSUE TITLE
A Gifting Feature to give BTTV Pro to Other users

### ISSUE THREAD

**Issue by FeelsOkayJojo** [night/betterttv#3295]
I think it would be awesome if you can purchase BTTV Pro for other twitch users that have connected their accounts to BTTV and maybe send them an email or twitch message that they've been gifted it. Some problems with it I think would be finding the users though. Would be an awesome feature nonetheless.

**Comment by unknownids** [comment]
Is there any update on this feature? Seems like a relatively simple thing to add that would get used frequently.

**Comment by rcwdev** [comment]
I would still love to see this become a feature. I know several smaller communities, including myself, that would find this very useful. Maybe even for specific periods of time, similar to how Twitch allows you to gift a subscription for an extended period. May be too much to ask, but I'd still love to see it implemented.

**Comment by night** [comment]
You can now send gifts at https://betterttv.com/dashboard/pro
