### ISSUE TITLE
BTTV Emote Menu gone

### ISSUE THREAD

**Issue by IPracZ** [night/BetterTTV#3299]
My BTTV Emote menu is gone and I don´t really know why. I already tried deleting my cookies and I even removed the Chrome extension and added it back into Chrome. None of it worked. Please help.

**Comment by Nareese** [comment]
Ensure that the setting `Emote Menu` (separate from `BetterTTV Emotes` or `BetterTTV GIF Emotes`) is turned on.  If it is turned on and you still don't get the menu, you probably have some other extension that is conflicting.  Try disabling other extensions to see if that resolves the issue.
