### ISSUE TITLE
"Following" Icon in chat?

### ISSUE THREAD

**Issue by brotherbroadway** [night/BetterTTV#330]
Hello NightDev,

I've been wondering, if there could be an option to turn on a small Purple/Blue Heart in front of a user's name one is following.

So, e.g. if somebody is in chat I am following, I see that with a Purple/Blue "Following" Heart in front of his name.

That would be awesome!

Thanks in advance.

-brotherbroadway

**Comment by vendethiel** [comment]
I think this'd require us to query twitch everytime someone talks, tho? I don't think we have this information as-is, but I very well could be mistaken, the twitch part is not my strong point
