### ISSUE TITLE
Turning on Anon Chat shows "The raid has been cancelled" system message

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3300]
Interestingly, I can only reproduce this when attempting it in a channel other than my own.  When I try it my own channel (not broadcasting), it just silently fails.  In neither case is the sendChatAdminMessage in changeUser() seen in chat.

TMIActionTypes renumbered?

**Comment by CauzYolo** [comment]
Same here, sub gift message are displayed as raid cancelled message

**Comment by Nareese** [comment]
Yes, that's entirely possible.  If they're renumbered the action types list (again), then all sorts of "special" message types will probably be broken until night has a chance to update the list.

**Comment by Nareese** [comment]
Another symptom, ban and timeout icons are appearing on sub and resub messages (but only if there is no custom message).
