### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by axylotol** [night/BetterTTV#3302]
Dark mode turned on but its not turning on 
![image](https://user-images.githubusercontent.com/44319440/47820074-c51e4a00-dd32-11e8-86c5-7a534fc0a908.png)

**Comment by Nareese** [comment]
Check the dropdown under your name at the upper right and verify that Twitch's Dark Mode is turned on.  It is possible for the Twitch setting and the BTTV setting to get out of sync temporarily (reloading the page should resync them).  Also turning the BTTV setting off and back on again should also resync them.  After making sure that both locations are on, and in sync, if you are still not getting the dark mode theme, you have some other extension interfering.  Note that BTTV does not supply the bulk of the dark mode functionality, that is entirely twitch's.  All the BTTV setting does is toggle twitch's own setting.  

For whatever its work, I can only reproduce this by turning off the Twitch setting and then looking at BTTV's settings where it will still be on.  Reloading the page or toggling the BTTV setting resyncs them, and turning the setting off and on from the BTTV panel always works as well.  Other than that, I cannot reproduce this.
