### ISSUE TITLE
Disable Host Mode fails v.7.2.45

### ISSUE THREAD

**Issue by AMacCo** [night/BetterTTV#3305]
Enable/re-enable, still fails, 100%
I don't seen an open issue for this at the moment. 
Firefox 63.0.1 (64-bit)
BetterTTV v7.2.45

**Comment by Bloodadept** [comment]
Also failing on Chrome version: 70.0.3538.77 (64bit), BetterTTV v 7.2.1

**Comment by night** [comment]
When you say "fails," what does that imply? I'm not able to reproduce any issues myself.

**Comment by Bloodadept** [comment]
I can leave a stream open, come back after it's finished and a /host has been run and the video of a different streamer has loaded. It's exactly like what it sounds like. disabling of the Host mode stopped working

**Comment by bntaylor929** [comment]
![nightbttvdisablehostmodebug](https://user-images.githubusercontent.com/45475057/49264957-2f470f00-f405-11e8-9c88-4cc50e6cc751.png)
I can confirm this issue is still occurring today with BetterTTV v7.2.45.

**Comment by Nareese** [comment]
I can confirm that as of tonight, I am now seeing this behavior as well, consistently reproducible, vs 2 weeks ago (or 1 days ago) where I also wasn't able to reproduce it, so perhaps Twitch has rolled it out more widely.  Also with Chrome Version 70.0.3538.110 more or less completely clean install (no other twitch modifying addons)

**Comment by me5647** [comment]
Disable host stopped working for me last night. Chrome version 70.0.3538.110, BTTV v7.2.45.
