### ISSUE TITLE
right-click shortcut Ban/Purge widget does not work on firefox

### ISSUE THREAD

**Issue by AvocadoGuy** [night/BetterTTV#3307]
The right click ban/purge menu does not work for me. Im using firefox 63.0.1 with BTTV version 7.2.45 installed on windows 10. Right clicking on a username is supposed to bring up the ban/purge slider widget, (as it still does in chrome on my computer), but on my firefox right clicking on a username only brings up the standard firefox system menu (which has "save page as", "view source", normal firefox menu). The BTTV plugin is loading correctly, the other functions do work fine, however this shortcut does not. I tested to make sure its not just covered up by the firefox menu by pressing escape to close the firefox menu, but that didnt help.. the BTTV slider widget is not appearing at all to begin with. I asked a friend with firefox+bttv(his system was linux) and he reported the same problem, no widget.

**Comment by Nareese** [comment]
One thing that occurred to me after I chatted with you earlier is that Firefox has a config setting to disable right click events from the DOM.  To check, open about:config, and in the search box, enter "context", and it should return `dom.event.contextmenu.enabled`, make sure that is not set to false.

**Comment by AkitakeKun** [comment]
This is the case for me as well, the right click menu of BTTV does not work and gets overwritten by firefox's.
Will use Chrome temporarely for moderation.

**Comment by AkitakeKun** [comment]
Why was this closed?
