### ISSUE TITLE
Using emotes from bttv or twitch emotes menu replaces selected username in chat

### ISSUE THREAD

**Issue by VitekNo1** [night/BetterTTV#3311]
Well. How it happens. I doubleclick user in  chat, so it becomes @username, then i open bttv or twitch emote menu and click on any emote, and emote name replaces selected name of user, like i planning to send it to nobody. Annoying.
I tried it on chrome and opera, this happens in both browsers,
And tried with no bttv add installed, emotes work the right way.

**Comment by VitekNo1** [comment]
And yes, i tried it on chrome and opera, this happens in both browsers,
And tried with no bttv add installed, emotes work the right way.

**Comment by ItsCaptainModz** [comment]
![image](https://user-images.githubusercontent.com/45275337/48924758-9276f580-ee89-11e8-9c1d-f8dfdd7b81f2.png)

**Comment by ItsCaptainModz** [comment]
[https://i.gyazo.com/d13b23cf4701af37d1aa2240425ce72b.gif?_ga=2.108375366.534673295.1542930564-40532491.1535424855](Watch this to understand the bug)

**Comment by ItsCaptainModz** [comment]
Watch this GIF to understand how the bug: https://i.gyazo.com/d13b23cf4701af37d1aa2240425ce72b.gif?_ga=2.108375366.534673295.1542930564-40532491.1535424855
