### ISSUE TITLE
the host button is gone when  on a a pc but when on a moble it is there.

### ISSUE THREAD

**Issue by jaxsta101** [night/BetterTTV#3313]

**Comment by Px05119** [comment]
Host button is missing on both Firefox 63.0.3, as well as Chrome versions 70.0.3538.102 and 70.0.3538.110. Tried the standard "turn it off and back on" and that didn't work.

**Comment by Chrionz** [comment]
Missing as well for me. Chrome versions 70.0.3538.102 as well as 70.0.3538.110

**Comment by mainlinx** [comment]
Same, And no one is caring about it? It has been broken for over 2 months now

**Comment by night** [comment]
I will look into this when i have time this weekend.

> It has been broken for over 2 months now

it has only been broken for a week.
