### ISSUE TITLE
Automatic Theatre Mode When Channel is Live

### ISSUE THREAD

**Issue by mortyobnoxious** [night/betterttv#3315]
When **Automatic Theatre Mode** is enabled, it always opens with Theatre Mode which seems unpractical.
Is it possible to add an option to switch to Automatic Theatre Mode only when the channel is live?

**Comment by Bilge** [comment]
This. Automatic Theatre Mode should not engage when a stream is offline.

**Comment by night** [comment]
since twitch's channel page redesign this looks to be a nonissue
