### ISSUE TITLE
[Feature Request] Badge in chat for supporters / BTTV Pro Subscribers

### ISSUE THREAD

**Issue by jimmydorry** [night/BetterTTV#3316]
Per title, having a vanity badge in chat for BTTV supporters would be nice. It should also increase up-take on that service.

**Comment by Nareese** [comment]
night has responded previously on this idea here:  https://community.nightdev.com/t/badge-for-betterttv-pro-subscribers/9961

**Comment by jimmydorry** [comment]
Thanks. That's a real shame.

**Comment by night** [comment]
indeed. i appreciate everyone's support but pro isn't meant to be a cash grab for fame and glory. it merely offers some hidden perks to those who subscribe to help me cover costs for nightdev expenses (betterttv, nightbot, etc.)
