### ISSUE TITLE
Chat Image Preview Cut Off in Popup/IFrame

### ISSUE THREAD

**Issue by Irontheater** [night/BetterTTV#332]
I love the new feature, but in Windowed mode, only half the image is visible, with the other half being outside the chat the window.

It would be great if the image was just centered to the chat window.

**Comment by amamut** [comment]
@Irontheater The image preview shows up in relation to where the mouse pointer is and moves with the pointer. Have you tried mousing over the farthest right tip of the URL to view the preview?

**Comment by night** [comment]
@amamut You may also consider pull requesting a change that bounds the preview by the edges of the window.

**Comment by amamut** [comment]
@night I'll take a look
