### ISSUE TITLE
[Feature Request] Opt out of name color fix

### ISSUE THREAD

**Issue by sweagboi** [night/BetterTTV#3320]
i use both FrankerFaceZ and BTTV and the fact that FrankerFaceZ lets me change how colors change but BTTV doesn't is _really_ annoying.
i got amazon prime so i could have any color i wanted (and the other features obviously) but BTTV changing it makes it so theres no point in changing my color. i know its an accessibility thing, but defaulting to on and allowing some people to turn it off would make a lot of other people happy

**Comment by night** [comment]
We prefer to not make an option, sorry. The volume of people that complain about this is such a low number that it's not worth maintaining an option and cluttering the options menu.

**Comment by vergil01** [comment]
So instead you prefer to clutter your issues tab on github with the same issue from multiple users adding more work to yourself clearing those up, closing and leaving links to this thread. Ok.
