### ISSUE TITLE
Channel currency not accumulating properly 

### ISSUE THREAD

**Issue by codycee25** [night/BetterTTV#3324]
I'm a subscriber of EdgarAlanBro on Twitch. If I use his command in chat "!bux" it shows the correct amount (2000+) of his channels currency "bux". I'm on mobile so if i click the puzzle piece to redeem my "bux" it shows i only have 1641 bux. Its been stuck like this for weeks.

**Comment by night** [comment]
what does this have to do with our browser extension?
