### ISSUE TITLE
Bug: Hide Recommended Channels / Friends Always On

### ISSUE THREAD

**Issue by GreatGeniusKojumbo** [night/BetterTTV#3328]
On Google Chrome for me recommended channels/friends is always hidden regardless of whether the setting is on or off. It appears for just a moment when the page loads and then vanishes. I've tried disabling FrankerFaceZ and can confirm this only happens when BTTV is enabled. So as far as I can tell, there's no interacting with other extensions causing this.

**Comment by night** [comment]
I'm not able to reproduce any issues with the feature. Recommended friends and channels only show when the option is disabled, not enabled.
