### ISSUE TITLE
duplicate emote menu button

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3330]
At some point last night (12/11/18) the emote button started being duplicated beside the "Chat" send button.

![emenu](https://user-images.githubusercontent.com/10347279/49904065-0f690f80-fe37-11e8-80fd-891ce76427ea.PNG)

I had a look at the UIMenuButton.attach code, and tried manually executing the selector it uses to find the element to append to, and it looks to me like it only returns the userlist button, so I don't know how that's happening.  Also noteworthy, if you disable `Emote Menu`, it will only hide the one beside the userlist button, and the one beside the Chat button remains there.  If you refresh, neither reappears, and enabling the option on a page where it was loaded disabled will then display both of them again.

**Comment by vormav78** [comment]
Same thing here. I was about to make a post about it after 2 days of having this issues and having tried multiple things to fix it.

It is to be noted that when you click on the left icon, it highlights the right one instead.

![image](https://user-images.githubusercontent.com/8343604/49987657-12045b80-ff42-11e8-9f39-c0ecb7d7b20e.png)

**Comment by chrisjsy** [comment]
same issue 
![capture](https://user-images.githubusercontent.com/12655207/50038402-f8811380-0016-11e9-9fcc-7c2cb5923f7f.PNG)
