### ISSUE TITLE
Add option to limit video resolution to stream resolution

### ISSUE THREAD

**Issue by T3rm1** [night/BetterTTV#3339]
The effective width and height of the video tag can grow bigger than the actual resolution of the stream.

For example on my WQHD screen the video has a width/height of 1940x1091 while the video is streamed with 1920x1080. The reason for this is how the size is calculated:
```
height: calc(100vh - 16rem)
width: width calc(100% - 40px)
```
This forces the browser to resize the video and make it a little blurry.

It would be nice if BBTV could set the max-width/height to 1920/1080 in this case.

**Comment by night** [comment]
Unfortunately due to how Twitch's player is implemented it's non-trivial to change their dimension logic. We use to do this kind-of stuff in the past but it was always breaking and inconsistent.

**Comment by T3rm1** [comment]
I think it is quite easy. Just check if the elements size is slightly bigger than a common solution and the overwrite the width and height. What exactly is the problem you see? Maybe I can help.

**Comment by DaRkL3AD3R** [comment]
I'm just here to say I'm glad someone else is getting that annoying 1940x1091 resolution causing unnecessary blur on a 2560x1440 monitor. The frustrating thing is at some point in the past it used to display perfectly at 1080p but it no longer does. And when you try to google search for this issue, it's like no one knows it exists. You're the first person I've seen also with this issue.

**Comment by henriklb** [comment]
Please reconsider adding this

**Comment by henriklb** [comment]
@night
