### ISSUE TITLE
BetterTTV causing tab to crash

### ISSUE THREAD

**Issue by Smagjus** [night/BetterTTV#334]
I observed crashes at specific points of a stream when BBTV is active. The crash also seemed to hit 30+ other users (all bttv users?) at the same time as shown in the attached screenshot:
![wd6brwm 1](https://cloud.githubusercontent.com/assets/10572675/7102718/d97d5238-e089-11e4-8e53-5dd153750c70.jpg)

The tab in Chrome does no longer crash when I disable the extension. With the extension it happens about every 10 to 20 minutes and then it hits all users simultaneously. The stream in question is http://www.twitch.tv/riotgames. The stream itself had audio issues. Maybe that is relevant.

**Comment by night** [comment]
BetterTTV doesn't crash your browser. Upgrade to Chrome Beta or wait for Chrome 42 to release: http://venturebeat.com/2015/04/07/this-link-will-crash-your-chrome-tab/
