### ISSUE TITLE
Hide recommended channels is broken

### ISSUE THREAD

**Issue by livrim** [night/BetterTTV#3341]
Problem with recommended channels.
![bttv](https://user-images.githubusercontent.com/46114158/50407733-74c8e300-07dd-11e9-8cbf-ffd1ad2ea68f.png)

**Comment by night** [comment]
I'm not able to reproduce seeing recommended channels in the sidebar. Can you translate the exact header to English, as I cannot read the language you're screenshotting.

**Comment by livrim** [comment]
![1](https://user-images.githubusercontent.com/46114158/50455356-bf696d00-094d-11e9-9eb3-892343d17b54.png)
![2](https://user-images.githubusercontent.com/46114158/50455357-bf696d00-094d-11e9-8686-7dc3ea59a37e.png)

1. Main twitch.tv site.
2. Browsing game list.

**Comment by livrim** [comment]
Problem resolved thanks ;)
