### ISSUE TITLE
Username color recalculation On BETTERTTV

### ISSUE THREAD

**Issue by qewerka** [night/BetterTTV#3347]
Hello, I am using BetterTTV for twitch. Can you please turn on the option to change the Username color recalculation . I am using dark mode and my chat color is black and if I send a message to any live channel I see GRAY color instead of BLACK and its really annoying I want to see MY color which I have chosen and not GRAY. I am not sure If I will be using the extension while the problem is still on. Consider it :) Have a nice day.

**Comment by geisterfurz007** [comment]
https://github.com/night/BetterTTV/issues/3345 Essentially the same thing, I think (just for organisation purpose for bttv; maybe one can be closed).

**Comment by qewerka** [comment]
And If I turn on/off on the TWITCH(color recalculation) it do nothing..It beats with the extension !

**Comment by xgerhard** [comment]
duplicate of #3320
