### ISSUE TITLE
Chat member names incorrectly colored

### ISSUE THREAD

**Issue by MuyDeprimido** [night/BetterTTV#3351]
chat messages are automatically colored to whatever is the closest simple analog to the original color is. For example, my color is BF81FF, but it's just a regular twitch purple when I have BTTV activated. The only things in bttv i have activated are the emote options and disabling whispers and extentions. Please help!

**Comment by geisterfurz007** [comment]
Might be the same as https://github.com/night/BetterTTV/issues/3320 in which case there won't be a fix.
