### ISSUE TITLE
Disable autoplay for embedded streams

### ISSUE THREAD

**Issue by Regnander** [night/BetterTTV#3358]
A few months ago, Gamepedia started including embedded Twitch streams at the bottom of their wiki articles. Read more about it [here](https://kotaku.com/how-a-twitch-owned-wiki-may-be-inflating-streamers-view-1829919268) and [here](https://www.reddit.com/r/LivestreamFail/comments/9d954q/twitch_is_literally_viewbotting_themselves/).

As an example, [here is a link to an article on Gamepedia's help wiki that explains how to create articles](https://help.gamepedia.com/Starting_a_new_page). Scroll all the way down to watch an embedded Twitch stream of a random game start playing:

![1](https://user-images.githubusercontent.com/17113053/51430418-81ddc400-1c1b-11e9-8431-30fe8fb467da.png)
_(The gui language is in Swedish)_

My issue with this is that I have no interest to watch random Twitch streams while I'm browsing wikis, so I'm requesting an option to disable autoplay for embedded streams.

**Comment by night** [comment]
BetterTTV only runs on Twitch's domain per extension config. Not possible to change this.
