### ISSUE TITLE
Play Sound on Highlight (Broken?)

### ISSUE THREAD

**Issue by Mountainman1990** [night/BetterTTV#336]
Play sound on highlight does not seem to work I have tried multiple things including refreshing after activating it, opening a different window and tab as I was told by someone that you need to be in another window for it to work, also I have asked multiple people to try it. Would love if you can get this to work as I am often multitasking and sometimes doing other things away from my screen and this would help alot.

Regards,
   MountainMan1990

**Comment by night** [comment]
Audio plays only when your window is out of view (ie tabbed out or in a different browser tab)

**Comment by Mountainman1990** [comment]
Ive tried that also and it still does not work Ive tried it while in a game ive tried while in another window and tab. I said that in the original post

**Comment by teak** [comment]
You also need to have desktop notifications turned on...

**Comment by Mountainman1990** [comment]
(FacePalm) AHH that makes sense I suppose. Maybe put that in the description of the sound on highlight in the setting. Seriously tho I know alot of people that were trying to get this to work thank you :)
