### ISSUE TITLE
Disable Homepage Autoplay not working.

### ISSUE THREAD

**Issue by deadscreem** [night/BetterTTV#3360]
I have Disable homepage Autoplay enabled and its now not working.
I've tried deleting cookies and site data and then redoing my bttv settings and its still not working. Twitch must have changed something.

**Comment by oregoncrete** [comment]
Chiming in, another case of autoplay still happening.

**Comment by xGarzilla** [comment]
One more up. 100% not working.

**Comment by tskitzo** [comment]
+1 not working

**Comment by FoxySox** [comment]
Yep, also not working,  Windows 10, Chrome version  71.0.3578.98

**Comment by Baarten** [comment]
Me neither. Firefox 65.0, macOS 10.14.2, BetterTTV 7.2.50. 

Also, when I click fast enough on a livestream, it pauses that livestream.

**Comment by MRatnam** [comment]
Not working on Chrome 72.0.3626.81 for Win 7 x64.

**Comment by DJZenose** [comment]
Not working on Chrome Version 71.0.3578.98, Win 10 x64

also @Baarten do you have the following setting active?
Click to Play/Pause Stream — Click on the twitch player to pause/resume playback
- if not, then probably best to see if an issue already exists open a new issue

**Comment by Baarten** [comment]
> also @Baarten do you have the following setting active?
> Click to Play/Pause Stream — Click on the twitch player to pause/resume playback
> 
>     * if not, then probably best to see if an issue already exists open a new issue

Apparantly it's a wontfix unfortunately: #3145.

**Comment by burt-macklin1** [comment]
+1 not working

**Comment by Jonatino** [comment]
This is still happening.
