### ISSUE TITLE
Left side chat expand/collapse unavailable

### ISSUE THREAD

**Issue by nivekastoreth** [night/BetterTTV#3361]
When left side chat is disabled, the following two buttons are visible:
* Left Nav Toggle: `side-nav__toggle-visibility`
* Right Chat Toggle: `right-column__toggle-visibility`

However, when left side chat is enabled, the `right-column__toggle-visibility` element seems to have the correct x/y position, but is invisible.  I'm unsure if this is a z-layering issue or if there is something going on with the translation of the image that's moving it outside the render area.

Actual display (no button visible)
![image](https://user-images.githubusercontent.com/786082/51764671-baf6b800-20a3-11e9-812e-dd01ed591e30.png)

Firefox element select showing position:
![image](https://user-images.githubusercontent.com/786082/51764399-1ffdde00-20a3-11e9-961b-8648f98c7ce9.png)

**Comment by night** [comment]
I'm not able to reproduce this. Make sure you disable other Twitch extensions to ensure it's not another extensions causing woes.
