### ISSUE TITLE
[Feature Request] Hide "Rerun" VoD's from /directory/following

### ISSUE THREAD

**Issue by ghost** [night/BetterTTV#3368]
Would it be possible to have an option to block "Rerun" VoD's on Twitch's Following directory? They're distracting and I always think there are more channels streaming than there really is.

**Comment by Kobberholm** [comment]
I would love to see this feature also applied to the sidebar (if this already exists, I have not been able to find it).

**Comment by night** [comment]
duplicate of #2496
