### ISSUE TITLE
DARK MODE

### ISSUE THREAD

**Issue by gearking** [night/BetterTTV#3371]
I keep having to turn it on everytime I start twitch it started doing this the tenth of february

**Comment by whitecrownclown** [comment]
@gearking Could you give some more details? I'm asking because it seems to work alright for me.

**Comment by gearking** [comment]
It’s all good now. Not sure what was going on but I kept having to change
that setting and the BTTV gif emotes setting every time I got on. It’s
working fine now. Thanks.

**Comment by Chocapic** [comment]
Having the exact same issue. Didnt install anything recently but for the past few days eveerytime I open a stream I have to reactive the dark mode
