### ISSUE TITLE
Can't @ people 

### ISSUE THREAD

**Issue by CookieCrusher** [night/BetterTTV#3383]
Bttv was working fine, then while watching a stream i try to @ someone to answer their question. When I typed the @ then the first letter to let it auto fill nothing popped up.  I tried refreshing the page and even restarting the brower, didn't fix it.  I then tried disabling my addons, this fixed it.  I did some testing and figured out it was the bttv addon that was causing me to not being able to @ people.  Whenever it was off i was able to @ people without any problem.

**Comment by whitecrownclown** [comment]
@CookieCrusher What version of bttv are you using? This has been recently fixed in 7.2.49

**Comment by CookieCrusher** [comment]
I’m using version 7.2.51 it still doesn’t work

**Comment by night** [comment]
ensure you have `Completion Tooltip` enabled in the settings.

**Comment by CookieCrusher** [comment]
I'm retarded i had it off, didn't even know it was a setting thanks.
