### ISSUE TITLE
Add an option for moderators to replace ban button/cmd with long timeout 

### ISSUE THREAD

**Issue by Niseg** [night/BetterTTV#339]
Everyone that have been a moderator know this issue of people requesting unbans and stuff like that. The best solution I've found is to just time out people for a week. If they want to come back they'll wait it out .

This is why it would be a very useful for mods to replace perma-ban button with a set time ban. another option is to add a week or month timeout in the popup , today i just /timeout <user> 600000. it would be nice if there is like /wto for week timeout /mto month timeout .

Maybe add an ability that instead of mass unban replaces all bans with long timeouts. (unless it's available) . It shouldn't be too hard . the reasoning is that most people that get banned are banned for legit reasons and should have their chat rights suspended for a reasonably long period of time .If a streamer can just do /convertbans in end of stream people who were recently banned will still get punished while ones that served their time will get free.  it will also be nice that long timed out people will get their punishment in days and hours instead of seconds ( most people are not programmers or computers )

**Comment by night** [comment]
As far as I've been made aware, Twitch is already taking steps to improve the punishment system (including the tracking of moderator actions).

There's not a point to replacing the default functionality if only some of the users will utilize it. In reality, a timeout is meant to be a short amount of time, and a ban is meant to be a permanent offense.

While you may specify longer times in a timeout, it hasn't been confirmed if timeouts are even stored in a permanent database. If not, the timeouts are reset if Twitch restarts whatever process that holds the state of a timeout. At that point, the user is not timed out any longer. A ban, however, is stored in a database, and will remain permanent.

Additionally, the /massunban feature does what it's meant to. Many streamers will reset their ban list on a monthly basis, and that fulfills the use case for having a "long" timeout. If you have concerns about bans being permanent, I suggest bringing it up with the broadcasters in channels you help moderate to see if they would be willing to schedule mass unbans.
