### ISSUE TITLE
Dark mode keeps turning itself off.

### ISSUE THREAD

**Issue by IamKilt** [night/BetterTTV#3404]
I have the most up to date version of bttv and I usually have dark mode set to permanently on. But for some reason, every day I turn on my computer dark mode is magically off. I don't know if this is something on my end or if twitch adding its own dark mode option somehow broke bttv's dark mode option. I've tried clearing my cache, reinstalling bttv, and reinstalling chrome. None of those have fixed the issue. It's not something that outright breaks bttv, but it is annoying to have to reapply dark mode every time I turn my pc back on.

**Comment by adac7786** [comment]
can confirm this issue started happening a few weeks ago on my end as well

**Comment by itsazhuhere** [comment]
I don't know exactly how it works under the hood, but I'm pretty sure that Twitch's option to turn dark mode on or off overrides the BetterTTV flag.  This can probably be fixed, but I think it's a lot easier to just set the dark mode to on under your profile at the top right of the site.  Twitch saves the dark mode option, so it'll stay dark mode permanently.

**Comment by IamKilt** [comment]
Tried it already. Turned dark mode off on BTTV, turned it on on twitch itself. Same issue.

**Comment by adac7786** [comment]
any chance you set your state to invisible on twitch? i turned it off about a week ago out of suspicion and had no issues since so far.

**Comment by nosville22** [comment]
2 years later, same issue
resetting cookies helped temporarily
