### ISSUE TITLE
Fullscreen Video /w Transparent Chat Draggable Overlay

### ISSUE THREAD

**Issue by suidin** [night/betterttv#342]
Hi, I love your extension and would like to suggest a new mode similar to theatre mode.
In this mode the video is fullscreen and the chat window is "on top" of the video.
To make the video still viewable, the chat should be semi-transparent, draggable and resizable.
This is what it could look like:
http://imgur.com/a/yUyug
I wrote a chrome extension for myself but now I think other people may like it aswell.
Since I'm not really a programer I wrote it very poorly and I dont think my code would help you much to implement something like this properly. Also I have no idea how to make it compatible with BTTV.
I hope you consider this. Thank you.

**Comment by MrRoboto12345** [comment]
I know this is dead, but have you though about putting the extension on the Google Chrome store? I would love it!

**Comment by night** [comment]
Thanks for the request. BetterTTV does not like to do heavy site modifications as of v7 as they tend to be brittle and can break the Twitch experience when Twitch updates their site. For this reason we are not likely to implement and support a feature such as this.
