### ISSUE TITLE
Hide Squad Streaming banner

### ISSUE THREAD

**Issue by kirkdmo** [night/betterttv#3424]
With Twitch introducing the new "Squad Streaming" feature, it's rather annoying having the banner visible across the top of the stream. Would be nice to have an option to hide the banner.

**Comment by Timeeee** [comment]
@night any news on this?

**Comment by billysielu** [comment]
Related: #3251

**Comment by Feky** [comment]
Anytime soon this is annoying and can't hide it?

**Comment by night** [comment]
it looks like twitch has made this less intrusive, so this is no longer needed
