### ISSUE TITLE
[Feature Request] Follower Badge

### ISSUE THREAD

**Issue by Mastlive** [night/BetterTTV#3425]
Sorry, my English is not so good.
Can you make Follower Badge like Subscribe Badge or Mods Badge?
That would really help, especially for beginners streamers, who offer some benefits for being followed, because now you have to click on nickname and check manually if someone has follow, which requires a break in stream. It’s wise to use every minute productively, because "time is money".

**Comment by night** [comment]
follower badges are not something we will build, since it would require many API calls to gather this kind of information and would not work at scale
