### ISSUE TITLE
Enabling GameWisp Emotes Causes Twitch To Become Insecure

### ISSUE THREAD

**Issue by ShariJoosten** [night/BetterTTV#3428]
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit).

Enabling BetterTTV option GameWisp Emotes causes the url bar in Google Chrome switch from "secure" to "insecure" as soon as you enable this. If you disable it, you first have to completely close Google Chrome and restart it. When you then go back to twitch it will finally say "secure" again.

**Comment by datagutt** [comment]
The SSL certificate at the Gamewisp API endpoint (https://api.gamewisp.com) seems to not have been renewed.
Since the service is "shut down" it might be be hard to get them to fix the certificate, but since the servers are still up i guess it might be worth a shot to contact them about renewing it.

**Comment by night** [comment]
more likely I’ll remove their emotes
