### ISSUE TITLE
Not working right now

### ISSUE THREAD

**Issue by jfo84** [night/BetterTTV#3429]
I don't see the extension in my address bar and the transformations in chat aren't working. I tried a fresh install to no avail. Any ideas?

**Comment by night** [comment]
issues today were caused by networking issue with our datacenter which were never resolved. we migrated to a different one and it's fixed now.

**Comment by Vafarien** [comment]
Access to XMLHttpRequest at 'https://api.betterttv.net/2/changelog' from origin 'https://www.twitch.tv' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jfo84** [comment]
No worries, @night. Thanks for all your work on the project!
