### ISSUE TITLE
Some emotes not working fine

### ISSUE THREAD

**Issue by doukn** [night/BetterTTV#3430]
I was able to do so couple of days ago. GIF'S are working fine but things like "Pog" doesn't seems to show up. I cleared my cookies and cache and reinstalled a few times. Even in pop up chat emotes aren't showing. Dark mode is working fine too. Here's a bunch of error codes i got.  
![download](https://user-images.githubusercontent.com/49411587/55745461-f288c580-5a3f-11e9-95ca-c0c30112fc40.png)

Edit : "videoyun" is the channel name on twitch which i am trying to use emotes in

**Comment by night** [comment]
duplicate of #3429
