### ISSUE TITLE
Emotes work fine, but cant log in to edit.

### ISSUE THREAD

**Issue by TheRealTecknos** [night/BetterTTV#3431]
I can't connect to change my emotes, and tried clearing cache and cookies. currently have v7.2.54 in case it may be a missing update problem.

**Comment by Vafarien** [comment]
i'm also experiencing this issue.
The
https://api.betterttv.net/2/changelog
responds with a: {"status":500,"message":"error fetching changelog"}

**Comment by night** [comment]
duplicate of #3429
