### ISSUE TITLE
Requesting a feature (Volume Slider Always Expanded) when player controls are shown on mouseover

### ISSUE THREAD

**Issue by Jaladhjin** [night/BetterTTV#3434]
A.. a'hem competitor has this 1.. just 1 feature I like you don't..

But I love BTTV so much more & will continue to use it even without it.

The value is so handy because I can even quicker tweak the volume on a stream I'm watching as loud things happen or something gets quiet.

Would you consider adding that feature ?

**Comment by whitecrownclown** [comment]
@Jaladhjin We have a PR open that makes this kind of redundant https://github.com/night/BetterTTV/pull/3379

**Comment by night** [comment]
I don't get why you would need this specific feature.. if loud things happen you could immediately mute by pressing "m" instead. adding a toggle for this is unnecessary bloat imho
