### ISSUE TITLE
Can't Resize Emote Menu

### ISSUE THREAD

**Issue by mosentok** [night/BetterTTV#3437]
I can't resize my emote menu. This began about a week ago.

There are JS errors when I try to resize the emote menu. The errors I see are about either the 'top' or 'left' property somewhere:

script.min.js:8 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLAnchorElement.r (script.min.js:8)
    at HTMLDocument.dispatch (script.min.js:6)
    at HTMLDocument.m.handle (script.min.js:6)
    at HTMLDocument.e (raven.js:376)

I've performed some troubleshooting to no avail. Disabling all extensions except BTTV. Disabling all emotes in BTTV settings except BTTV emotes. Disabling/enabling BTTV emote menu. Full refresh twitch.tv. Clearing cache. All in both Chrome and Firefox. Same JS errors.

**Comment by A1F3Y** [comment]
Has this been fixed? Mine still bugged out.

**Comment by JopskyDopsky** [comment]
Same here, If anyone know a solution it would be really useful ;)
