### ISSUE TITLE
Twitch.tv Readable Colors Safari Bug

### ISSUE THREAD

**Issue by Przemas1000** [night/BetterTTV#3438]
I'm using BTTV 0.0.2 with Tampermonkey v4.7.5826 on Safari 12.1 with macOS Mojave 10.14.4. Everything works fine but the option "Readable Colors" is automatically enabled. It doesn't matter whether I have the box ticked or not, the option is enabled regardless. Nickname colors are changed, and if I disable the option, nicknames by messages already sent go back to normal colors. Then, the next messages sent get their colors changed anyways. Hope my description wasn't too confusing.

**Comment by Nareese** [comment]
Readable Colors is Twitch's readable colors option.  BTTV has it's own readable colors feature, and there is no option to turn it off.  This is intentional, and not a bug.  See #3320 for night's most recent official response on this.
