### ISSUE TITLE
Theater mode bug.

### ISSUE THREAD

**Issue by Gaalidas** [night/BetterTTV#3439]
I enabled automatic theater mode, but it keeps bumping me out of theater mode when i open a new stream.  It does this regardless of the automatic theater mode option being enabled or disabled.  I am simply kicked out of theater mode when BetterTTV activates.

**Comment by night** [comment]
i am not able to reproduce this behavior.

**Comment by Gaalidas** [comment]
Nor am I as of a few days after posting it.  I consider it a fluke.
