### ISSUE TITLE
Features - Automated translate - Following list

### ISSUE THREAD

**Issue by lDied** [night/BetterTTV#344]
Just two rather specific features I would love available, firstly is to automatically translate messages if possible. Finally to be able to display a list of followed channels in the side-pane.
Thanks
ID_ied

**Comment by DTittel** [comment]
The second feature would add a lot of weight to BTTV I suggest looking at the extension Twitch Now if you're using chrome they do a good job with giving you a following list in browser. As for the translating I don't think passing every chat message to Google Translate will turn out well in active chats.

**Comment by night** [comment]
Translation was just removed as Google broke the API we were using for free, and it wouldn't scale (cost to use Google's paid API + resource usage (tons of messages per second) would make it impossible).

As Dylan already mentioned, you can use that extension.
