### ISSUE TITLE
Disable Homepage Auto Play not working properly.

### ISSUE THREAD

**Issue by xGarzilla** [night/BetterTTV#3446]
Like that title says it's not working properly. 

When you first arrive to the page, nothing will play, but if you scroll down to where you cannot see the "Featured Streams" and then back up to be able to see them, the video starts playing automatically.

**Comment by night** [comment]
it is working properly, but unfortunately Twitch is pausing/playing as you scroll the page, which negates our functionality. because of this, it cannot be fixed.
