### ISSUE TITLE
Theater mode

### ISSUE THREAD

**Issue by jaa121** [night/BetterTTV#345]
Hello!
Automatic Theatre Mode is good but i would have added ability to block the button bar (when your mouse is on window a button bar appears) and somewhere streams title.

**Comment by night** [comment]
Please elaborate, as I'm not exactly sure what you mean.

**Comment by jaa121** [comment]
I meant to block this bar:
http://i.imgur.com/iYHyXwU.gif

**Comment by cletusc** [comment]
That isn't possible to remove. That is part of the Twitch flash player and we can't actually change the layout for that.
