### ISSUE TITLE
FFZ emotes broken

### ISSUE THREAD

**Issue by stbennet** [night/BetterTTV#3450]
With FrankerFaceZ Emotes enabled in the settings on BetterTTV v7.2.56 & Firefox v66.0.3, FFZ emotes are not appearing in the chat when typed out even when the streamer has them enabled.

**Comment by xgerhard** [comment]
Are you still experiencing this? They should work fine again.

**Comment by stbennet** [comment]
The latest patch fixed this issue, thank you!
