### ISSUE TITLE
[Feature Request] Pre-load GIF emotes that are enabled in channel

### ISSUE THREAD

**Issue by Rulesy** [night/BetterTTV#3451]
A toggle option to pre-load // cache all available gif emotes when you load a chatroom/stream. This would allow parody emotes to be in sync. [This emote](https://cdn.betterttv.net/emote/55898e122612142e6aaa935b/1x) and [this emote](https://cdn.betterttv.net/emote/59dbfe8b4ebd8047f54d6c39/1x) will start at the same time if they are loaded for the first time in the same message. For a comparison see [this image](https://i.imgur.com/GFNOmRx.gif) and [this image](https://i.imgur.com/4VKTPOk.gif).

**Comment by night** [comment]
After looking into this, it appears it is not possible. Chrome (at least) groups images of the same source to the same image reference, and animates them together. This means messages with the same emote cannot all be in sync if we want emotes to be in sync within them.
