### ISSUE TITLE
Unable to open a minimized chat with left side chat on

### ISSUE THREAD

**Issue by vyrelis** [night/BetterTTV#3452]
If you have left side chat toggled on, but use the small arrow at the top to minimize it, the arrow to open it back up doesn't appear. You have to toggle LSC off, open chat, turn it back on.

**Comment by night** [comment]
I am not able to reproduce this. If you use other browser extensions, try disabling those to see if it fixes your issue.

**Comment by vyrelis** [comment]
Possibly only a problem when viewing a stream in theater mode

**Comment by night** [comment]
I'm not able to reproduce this in theater mode either. If you can give reproduction steps we can look into this further. But for now it looks like a non-issue.
