### ISSUE TITLE
[Feature Request] Ability to mute words, just like in twitter.

### ISSUE THREAD

**Issue by xABDulRaHManZz** [night/BetterTTV#3453]
Hey, thought of this while I just got the latest episode of game of thrones spoiled for me in chat, maybe if we could mute words we would have a better chance of avoiding them. thanks.

**Comment by Nareese** [comment]
Gear menu -> Set Blacklist Keywords.  Not that that will actually solve your problem, but ¯\_(ツ)_/¯

**Comment by xABDulRaHManZz** [comment]
Never knew it existed l, ty
