### ISSUE TITLE
Embed Polling - Moderators

### ISSUE THREAD

**Issue by davidgauch** [night/BetterTTV#346]
A lot of the times in larger streams it's the moderators job to make and post the Strawpolls. It would be nice if you added a functionality to allow them to get pinned because sometimes the polls get lost in a flood of comments.

**Comment by jaa121** [comment]
This option is already. ("Embedded Polling" in settings):
![yepk9dc](https://cloud.githubusercontent.com/assets/11669792/7216026/11fcd0a0-e5f0-11e4-92ef-278440bdd16c.png)

**Comment by night** [comment]
@jaa121 I believe he is mentioning that only stream owners can post strawpolls. It's intentionally made to be owner-only, but at the moment I cannot remember why.

**Comment by davidgauch** [comment]
Yeah, that's what I meant @night, I don't see how it could be abused, but I do see that it might make the code simpler to write.
