### ISSUE TITLE
I cant download it.

### ISSUE THREAD

**Issue by mynameatlas** [night/BetterTTV#3462]
I go to the chrome store. Not there.
I go to the actual website. Download Button Brings me to an Error Screen.
I go anywhere on the internet and it doesn't work.

**Comment by Nareese** [comment]
At 3am PST last night, Google removed the extension from the web store, for reasons that are not yet clear.  night has contacted them for further information, but it is unknown when or even if this issue will be resolved.  

In the interim, you can install Tampermonkey (Greasemonkey for Chrome), and install the userscript version of the BTTV loader by clicking on the "for another browser" on the betterttv website and selecting Userscript from the options on that page.

**Comment by Nareese** [comment]
Update:  The extension has been restored to the store, at least for the time being.

`night: it should be back up now, but im not sure if it's going to get re-removed`
