### ISSUE TITLE
Block various pop-ups when a channel isn't live

### ISSUE THREAD

**Issue by Theonefoster** [night/betterttv#3464]
When a channel isn't live and you visit their page, Twitch puts various annoying pop-ups on the page which try to shove content in your face and which need to be dismissed. These include:

* "{Streamer} isn’t streaming right now. Watch their latest highlight or explore related content" <list of recent clips / videos> (this one locks the rest of the page until you dismiss it)
* A "Watch Now" thumbnail linking to their latest video, overlaid on the video panel with an X button to dismiss
* When you dismiss the "Watch Now" thumbnail link, the whole video panel is overlaid with a huge youtube-style "More from {streamer}" panel with a list of their latest videos.

These pop-ups are annoying and it'd be nice if we could block them through BTTV. I don't want content being shoved in my face without asking for it. Seems like a simple option to add to the BTTV settings panel: "Block content suggestion popups" or similar. 

The bottom two bullet points refer to boxes which are overlaid on the video and don't affect the rest of the page, so you can kind of ignore them if you don't want to click them. However the first bullet point refers to a box which takes over the whole page and requires you to click the X before you can interact with the rest of the page (clicking links, using chat etc) so definitely needs an option to block as it's more aggressive.

**Comment by night** [comment]
with Twitch's latest redesign this feature request no longer makes sense since the page is changed when streams are not live
