### ISSUE TITLE
Some BTTV gif emotes not loading (shows broken jpg sprite instead)

### ISSUE THREAD

**Issue by MeegsMachine** [night/BetterTTV#3465]
Some BTTV gif emotes have not been loading. Some gif emotes work perfectly fine, and the broken ones work if I click them, but break again if I refresh. I've tried reinstalling the extension, gif emotes enabled and have deleted cache, all to no avail

https://imgur.com/a/sEIbalK

**Comment by MeegsMachine** [comment]
![Screenshot of console error](https://user-images.githubusercontent.com/45133281/58041459-1146a580-7b30-11e9-92b0-ffe073c5256e.JPG)

**Comment by Nareese** [comment]
`net::ERR_BLOCKED_BY_CLIENT` is indicative of something in your browser deliberately blocking access to the resource.  Ad blockers and other "Internet/Browser Safety" type extensions are the most likely cause.  Disable all extensions other than BTTV.  If everything starts working correctly, then you can start turning other extensions back on until it breaks again and then you've found the culprit that is interfering.
