### ISSUE TITLE
Firefox Developer Bug

### ISSUE THREAD

**Issue by damooch** [night/BetterTTV#3467]
The emote button/menu for BetterTTV often disappears completely and I have not figured out how to bring it back. At complete random it will go away or come back. Also when having the chat reversed coming to a channel the chat will start at the bottom and you have to scroll all the way up to resume normal chat scrolling.

![betterTTV Emote menu gone](https://user-images.githubusercontent.com/20118403/58076420-6d78ec00-7b67-11e9-9bd1-397db6805352.png)

**Comment by night** [comment]
We unfortunately do not support development versions of Firefox as they tend to have bugs which only occur in the development versions. When/if this still occurs in Firefox stable we will be able to devote time to investigating/fixing it.
