### ISSUE TITLE
[Feature Request] The option to see stream uptime under the video and in directory

### ISSUE THREAD

**Issue by Jd-19** [night/BetterTTV#3468]

**Comment by Nareese** [comment]
The directory suggestion has been suggested before, and is still open as a request (duplicate of #2196), but it's been open for more than 2 years now, and as such, I wouldn't hold my breath for it to be implemented soon.  The uptime under the video has been suggested multiple times and rejected each time as UI clutter (see #628 #1014 #1088 #1698 #1975 #1989 etc).
