### ISSUE TITLE
Option to make every other message have a light gray background is not there

### ISSUE THREAD

**Issue by FrostClaw** [night/BetterTTV#3469]
I had to restore my Google Chrome settings meaning I had to redo BetterTTV and when I did I no longer see the option to make every other message have a gray background. I do not know if this is a fluke or was taken away just wanted to be sure because this was a very nice/helpful option to see and read messages better.

**Comment by Nareese** [comment]
The option is most definitely still there.  It's called `Split Chat`.  It is literally impossible for BTTV to be functioning correctly in general, and all the other options be there, and that one not be.
