### ISSUE TITLE
Ability to Follow Teams

### ISSUE THREAD

**Issue by spikel222** [night/BetterTTV#347]
As we know there are teams on twitch, and today I was watching a caster who talked about an upcoming  event he is doing with his team where they will be casting 48 hours. So I was wondering would it could be possible to make something that allows twitch users to follow teams . Like with the team "Main Menu" (The team who is doing the event I spoke of before) have a folder with there logo an it and how many people of "Main Menu" are live or even a tab on the following page labeled "Teams". I feel it will allow to follow events such as that or even watch people of the same team with out as much hassle seeing as a lot of casters vary in viewers, and subscribers. As a twitch user there is nothing more that I want than less hassle.

Have a good day, 
Spikel222

**Comment by night** [comment]
Twitch used to have this functionality, but I guess they removed it. Maybe if @NoxiusInfernus ever finishes his pull request #49 we might be able to integrate into that. It would ultimately depend on him maintaining it though.

**Comment by NoxiusInfernus** [comment]
I thought it was finished about 8 months ago hehe ... I sync'ed up my fork, and yulp, still working. Nothing to maintain if it's not broke hehe.

**Comment by night** [comment]
@NoxiusInfernus feel free to integrate this feature request into your PR, if you don't mind.

**Comment by NoxiusInfernus** [comment]
It's already a feature :)

**Comment by night** [comment]
@NoxiusInfernus any updates?

**Comment by night** [comment]
teams are basically deprecated on twitch in favor of communities, which have follow buttons
