### ISSUE TITLE
Audio and Video issues? 

### ISSUE THREAD

**Issue by HoneyTLBadger** [night/BetterTTV#3470]
Not an issue I've experienced myself, but someone I know did. I'll paste his description here:
"Question, friends. Does it make sense to anyone that when I download and install BTTV, it breaks my audio and video services on my PC, so much so that I have to reset my PC to default to fix it?
Each other time, I've installed BTTV and about 2 or 3 days later it breaks everything."
-
"Audio services will become unresponsive and will show that they are "stopping" under the services tab. Can't force stop or start them when it happens. My video issue is that every source of video, be it YT, Twitch, Netflix, etc., all just constantly buffer. Doesn't matter which browser, either. Even deleting and reinstalling browsers doesn't do anything. Once it breaks, it's broken. When I have the buffering issues, all player options are missing, too. It's like the codec is broken, all together. It's a really weird issue. They don't seem to exist together, always. Sometimes when I finally fiddle enough with one to get it "fixed", the other breaks and vice versa."

**Comment by night** [comment]
I'm not sure why installing BetterTTV would cause this unless your computer is on the brink of its hardware failing or maximum resources. In general, BetterTTV can use quite a bit of CPU in chat when there are many GIF emotes being shown.
