### ISSUE TITLE
BetterTTV does not work on VoDs

### ISSUE THREAD

**Issue by Thelodger** [night/BetterTTV#3471]
Hi there,

Useful Information :

- Tested on Windows 7 and Windows 10
- Latest version of Chrome and Firefox
- Latest version of BetterTTV

Problem description :

BetterTTV settings don't appear and are not applied on VoDs

**Comment by night** [comment]
not all features work on VoDs, but emotes do. you can access settings by clicking on yourself in the upper right of the website.
