### ISSUE TITLE
[Feature Request] Add option for old square avatars

### ISSUE THREAD

**Issue by brussell98** [night/BetterTTV#3472]
Twitch switched to circle avatars which are visually unappealing to some people. An option to switch to the old style CSS would be appreciated.

**Comment by Nareese** [comment]
In the event that night considers this worthy of inclusion, the appropriate css to restore square avatars is:

`.tw-border-radius-rounded { border-radius: 0%!important; }`

(the new twitch default is 50%)

If not, and/or in the interim, interested persons can use a third party CSS override tool like Stylus to add the above rule for themselves.

Note that at the moment, I have loaded twitch channel pages about 10 times trying to test for these things, and I've gotten rounded avatars only three times out of those 10 loads, so I would say it's not yet clear whether this change is intended to be permanent and the change is not yet fully live.

**Comment by night** [comment]
I would recommend using Stylus if you need this, since adding a feature toggle for this seems like it wouldn't be worth it. The majority of users don't care if an avatar is square or circular.
