### ISSUE TITLE
chat_link_preview breaks link wrapping

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3473]
A user on discord (hat tip: DragooMind) reported that hovering over a link, triggering link preview, breaks the wrap on the link making it unreadable in full without horizontal scrolling.  I had also noticed this behavior before, but hadn't looked into it.

It is caused by the div that chat_link_preview.tooltip constructs having the `tw-tooltip-wrapper` class added to it.  This class contains `display: inline-flex` which is what breaks the wrapping.  That attribute is not required for the proper functioning of the tooltip, and toggling it off in chrome debugger restores the proper wrapping, while the tooltip remains functional.

Not sure what the least hacky way to resolve this is... I will test some possible solutions and possibly submit a PR later if I get to something I'm happy with.

**Comment by night** [comment]
i've decided to remove link previews for now.
