### ISSUE TITLE
Mods-Badges / Space-Bug

### ISSUE THREAD

**Issue by Snipy2k4** [night/betterttv#3477]
Hello,

When you activate the mod symbols on Twitch for purge and timeout, there will appear a space symbol before all the mod badges (besides the own name).

I believe that BetterTTV removes the buttons (ban/timeout/purge) in front of the others mods badges and this leaves a space symbol. 

I would therefore ask for a Fix, thx

![c93f1492-587f-4e6e-8f87-12d3a84d3b30](https://user-images.githubusercontent.com/39011942/58925367-8ed0ff00-8747-11e9-900f-02530323aead.jpg)

**Comment by Nareese** [comment]
This is caused by the fact that BTTV deletes only the mod icons, and not the div that holds them, and the div that holds them has `.tw-mg-r-05` on it which forces a .5rem right margin.

**Comment by Snipy2k4** [comment]
when will this be fixed?

**Comment by night** [comment]
probably not anytime soon, since it only affects a handful of users and would require a sketchy solution which could break easily

**Comment by Snipy2k4** [comment]
I do not understand why you have no solution for that ?! Visually, that just looks stupid.

How about if you include the option that Mods and Co have the icons in front of the name. That's the same in the regular view.Why did you remove the icons in the app if this causes such a bug?

**Comment by night** [comment]
This doesn't look to be an issue any longer in 2022.
