### ISSUE TITLE
Emote button is not there

### ISSUE THREAD

**Issue by Hacksource1337** [night/BetterTTV#348]
The "click to insert emote" button is not on my twitch page is it just me?
![problem](https://cloud.githubusercontent.com/assets/12011380/7217063/73046070-e60e-11e4-8bed-996e4d21da17.png)

**Comment by jaa121** [comment]
You have this option enabled in the settings?
![9do6iod](https://cloud.githubusercontent.com/assets/11669792/7217304/91d39250-e622-11e4-979d-c9491cdeac34.png)

**Comment by Hacksource1337** [comment]
Yes I have
