### ISSUE TITLE
Addon not even showing in chat settings

### ISSUE THREAD

**Issue by atunnard** [night/BetterTTV#3480]
This appears to the be error in the console;
[Exception... "Favicon at "https://cdn.betterttv.net/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 199"  data: no]
    onStopRequest resource:///modules/FaviconLoader.jsm:199

**Comment by semoog** [comment]
Probably the same issue as https://github.com/night/BetterTTV/issues/3479 and the favicon just happens to be missing as well
