### ISSUE TITLE
betterTTV broken?

### ISSUE THREAD

**Issue by mechoriet** [night/BetterTTV#3481]
the whole menu and setting window is gone
and the emotes are not showing

from what DevTools show me all the files from bettertv load 
and no errors that i can see in the console 

Browser: Chrome Versie 75.0.3770.80 (Officiële build) (64-bits)

**Comment by semoog** [comment]
https://github.com/night/BetterTTV/issues/3479

**Comment by mechoriet** [comment]
^ twitch probably changed something

**Comment by robotrono** [comment]
yeah, bttv is not working

**Comment by night** [comment]
This is fixed with our latest release.
