### ISSUE TITLE
New sidebar clutter: Popular Channels

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3484]
With today's update twitch added a new "Popular Channels" section of clutter to the left sidebar.  As far as I can tell, there is absolutely no uniquely identifiable trait in this section which could be used to block it, unlike every other section around it, so just posting this here as a long term goal to hopefully figure out how to kill this.  For the moment I am using

`.simplebar-content > div > .tw-full-width.tw-flex-grow-1 > .tw-mg-b-2`

which seems very fragile.

**Comment by andrew-anguiano** [comment]
You could potentially do it with a `nth-child` selector, but that may not be any less fragile... Bummer there's no unique class on that section. I guess you could also do something with jQuery but that seems kinda icky too.

**Comment by Darktowertr** [comment]
Recommended channels new name. Probably the least-watched broadcasters changed it because they cried. Please bring an update to prevent this.

**Comment by Scrxtchy** [comment]
> Recommended channels new name. Please bring an update to prevent this.

![image](https://user-images.githubusercontent.com/12771982/59156113-5cbdf500-8ad9-11e9-9c4d-94c8fd02db49.png)
🤔
https://github.com/night/BetterTTV/blob/8d5dda3951ae96fc9a97d25a8b5ca70432ae4ce6/src/modules/hide_sidebar_elements/style.css#L1-L5

**Comment by night** [comment]
I do not see popular channels in the sidebar
