### ISSUE TITLE
BTTV Emotes not working

### ISSUE THREAD

**Issue by Rkaincat** [night/BetterTTV#3487]
My BTTV, emotes and emote button specifically, aren't working and I went through all the instructions at https://community.nightdev.com/t/betterttv-debugging/3685
(minus the firewall cuz I couldn't figure that out) so I checked the JavaScript console for any red errors and found a bunch(its all jibberish to me) so I'm posting it here as it said. Hope I'm doing this right.

**Comment by Rkaincat** [comment]
I miss BTTV emotes ;-; It's been so long v-v

**Comment by antreaskar** [comment]
thanks for the help!!!
