### ISSUE TITLE
Add a setting to disable Auto squad mode

### ISSUE THREAD

**Issue by yanivkr** [night/betterttv#3490]
When watching a stream that is in a squad, If you dont cancel in 30 seconds it auto transfer you to squad mode, add an option to disable it

**Comment by breon** [comment]
Twitch seems to be testing several different implementations of the squad stream banner...
- Auto join squad stream, with option to opt out
- Display squad stream banner, with option to dismiss banner
- Display squad stream banner, without option to dismiss banner

I haven't see the auto-join option in a long time. I think that the third option is what they rolled out with the new site launch.

**Comment by Feky** [comment]
This feature would be nice to the implant. There is squad banner above the stream and it's annoying and there is no way to remove it.

![sdasd2](https://user-images.githubusercontent.com/3746977/72025976-3718ea00-327a-11ea-89c9-10dd211ee530.png)

**Comment by night** [comment]
it looks like twitch has made this less intrusive, so this is no longer needed
