### ISSUE TITLE
Better TTV emotes problem

### ISSUE THREAD

**Issue by Creedastic** [night/BetterTTV#3494]
Hi. How do I make that nice big button with emotes appear back? It had a big smiley face on it, and it was down under the Twitch's smaller smiley face tab button near the chat. Recently, it disappeared. It also disappeared with older versions of this extension, but I dont know how to restore it. I clicked on the BTTV Settings, and I turned the Emote Menu ON, but the button still doesnt appear :/. Please help me. Also, how can I be able to add emotes to my channel so that I see them displayed in every chatroom? For example, I want to add the RareW emote so I can see it. I clicked on the My Account tab, I added the RareW emote, but when I type it in chat or when someone else types it, I still see the text only, and not the emote. Why? What is the solution? Thank you.

**Comment by NismoGraphics** [comment]
For what I can see, it seems that some features has broken due to a new update.
If you're using twitch canary, pretty much all of the BetterTTV features are gone.
_We'll see what happens._

**Comment by NismoGraphics** [comment]
Nevermind about canary, everything somehow repaired itself.

**Comment by Creedastic** [comment]
To me, it hasn't repaired itself at all. I still can not see the emote menu anywhere. Help?

**Comment by night** [comment]
It works on my machine. If you're having issues be sure to clear cookies + cache, and make sure "Emote Menu" is enabled in your BetterTTV Settings.

**Comment by Creedastic** [comment]
I just cleared them. Everything on anything containing twitch in it, I just cleared all the data. I also uninstalled the add-on, and reinstalled it. And when I returned, I re-turned the Emote Menu button to On, but I still don't see it anywhere. :(

**Comment by Creedastic** [comment]
Nevermind. It worked. I wasn't really clearing everything. Now I did and after reinstalling the addon it worked. Thanks.
