### ISSUE TITLE
Automatic Theatre mode removes Sidebar in Following directory

### ISSUE THREAD

**Issue by Chris92de** [night/BetterTTV#350]
See title.

**Comment by night** [comment]
@amamut Perhaps you could take a look into this.

**Comment by amamut** [comment]
@Chris92de Can you please give a little more detail into this issue and how you reproduce it? I am not sure what the issue is. Theatre mode should remove the sidebar as it expands the video to the edge. Maybe I'm misunderstanding.

**Comment by Chris92de** [comment]
Hello,
basically when I have the option turned on and go to
twitch.tv/directory/following/live, it removes the sidebar as well, which
it should only do on channels.
I haven't tested this on settings or any other subpage just yet, but I
expect the same behavior.
Am 20.04.2015 04:05 schrieb "Alex Mamut" <notifications@github.com>:
