### ISSUE TITLE
[Feature Request] Get rid of the own country listing when you browse categories

### ISSUE THREAD

**Issue by DrowningElysium** [night/BetterTTV#3503]
As someone from the Netherlands at the top of the browsing list I always get some Dutch channels. I really would never want to watch this stuff, so I'd like an option to get rid of them and just list it from most popular to less popular.

**Comment by night** [comment]
This is probably just an experiment as I do not see such listings when I browse. Unless this is something Twitch rolls out to everyone we won't act on it.
