### ISSUE TITLE
BTTV Emotes are blurry on Chrome when using the zoom feature

### ISSUE THREAD

**Issue by jaKz9** [night/BetterTTV#3505]
When using a 125% zoom on Twitch using Chrome as browser, the emotes are blurry, whereas on Firefox with a 133% zoom they are crispy as expected. The emotes are fine when NOT using the zoom feature, however that is quite annoying as I'm using a 1440p monitor. Is this something BTTV can fix or is it down to some internal setting in Chrome?

**Comment by night** [comment]
this isn't a thing we can fix. emotes are loaded via srcset, which is a browser-specific implementation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset
