### ISSUE TITLE
Users in chat hidden under Hide Room Selector

### ISSUE THREAD

**Issue by SM1ThaYe** [night/BetterTTV#3509]
BTTV 7.2.1 on Chrome 75.0.3770.142 (Official Build) (64-bit)

Two days ago Twitch changed the location of the list of users in chat from the bottom-right to the top-right.

But if you had Hide Room Selector enabled this would also remove this list (now called "Users in Chat") as it's now in the same header.

Setting description either needs updating to also include Users in Chat or if possible a separate setting, this is to avoid confusion.

Below is the new location of Users in Chat outlined in red top-right of Twitch window.

![Users in Chat](https://user-images.githubusercontent.com/46424376/61585756-9e6fa000-ab5b-11e9-9598-9c14214a5d8a.png)

**Comment by SaiyanOfDarkness** [comment]
This needs to be separated into its own button and placed down at the bottom of chat..

**Comment by iPot** [comment]
I agree with SaiyanOfDarkness. The viewer list should be at the bottom of the chat like before so we can hide the Room Selector while still having the viewer list.
