### ISSUE TITLE
Incorrect personal emote slot number.

### ISSUE THREAD

**Issue by ReeverM** [night/BetterTTV#3512]
It seems that with the redesign of bttv, the "Personal Emotes" section under the Dashboard shows the total number of personal emotes you're able to get (25) instead of the current maximum you are allowed to add (in my case 6).

The issue is purely visual, I'm not able to add more than 6 emotes but I believe it would be more helpful to show the user maximum instead of the global maximum and I'm relatively sure it behaved this way in the past.

**Comment by night** [comment]
This should now be fixed.
