### ISSUE TITLE
Search emotes after update?

### ISSUE THREAD

**Issue by SomeNewbie12** [night/BetterTTV#3515]
I cannot figure out how to search emotes outside of the Top or Trending for the personal emotes after the recent BTTV website change, is the feature even still there?

**Comment by Nareese** [comment]
From the Discord support channel:

> Rick: The whole site was redone, search is not back *yet*, and we are currently seeing how users feel about the new design and features. We think there is a better way to have emote discoverability than search, which would often get clogged and was only useful if you had the exact emote code.

So it is possible that the search functionality will be restored at some point.  night has said he would like to get to feature parity with the old site, but it's not there yet.

**Comment by SomeNewbie12** [comment]
> From the Discord support channel:
> 
> > Rick: The whole site was redone, search is not back _yet_, and we are currently seeing how users feel about the new design and features. We think there is a better way to have emote discoverability than search, which would often get clogged and was only useful if you had the exact emote code.
> 
> So it is possible that the search functionality will be restored at some point. night has said he would like to get to feature parity with the old site, but it's not there yet.

Ah okay, that kinda sucks, not gonna lie. Thanks for the reply!
