### ISSUE TITLE
[Feature Request] Top Poster badge

### ISSUE THREAD

**Issue by Seremendal** [night/BetterTTV#3516]
A badge for top posters in BTTV (uploaders in https://betterttv.com/emotes/top page) 
And/or a badge for trending posters (uploaders in https://betterttv.com/emotes/trending page)
And/or badge for Global posters (uploaders who have emotes in https://betterttv.com/emotes/global)

**Comment by night** [comment]
What do you mean by "poster?"

**Comment by Seremendal** [comment]
> What do you mean by "poster?"

The person who uploads the emote.

**Comment by night** [comment]
I see. Unfortunately I don't think we have plans to offer badges. Offering any kind of incentive like this would only make it a competition, which I don't really want to happen.
