### ISSUE TITLE
Words blacklisting feature is missing?

### ISSUE THREAD

**Issue by CustomPhase** [night/BetterTTV#3517]
As far as i understand its supposed to be in the cogwheel menu below the chat, but theres nothing there. Maybe localization related issue, since im using Russian as my language? It shouldnt be, right? Couldnt find anything blacklisting-related in the main BTTV settings window as well.
![image](https://user-images.githubusercontent.com/10864826/62007943-19911180-b16d-11e9-9a63-702d44efd4e2.png)

**Comment by Nareese** [comment]
Some BTTV functionality, including blacklist keyword configuration, is not available on VODs.  It will still block lines containing blacklisted words (if it doesn't, it's a bug), you just can't configure it from a VOD.

**Comment by CustomPhase** [comment]
> Some BTTV functionality, including blacklist keyword configuration, is not available on VODs. It will still block lines containing blacklisted words (if it doesn't, it's a bug), you just can't configure it from a VOD.

Got it, thanks!
