### ISSUE TITLE
Hide Twitch Extensions is not working

### ISSUE THREAD

**Issue by Seksl** [night/BetterTTV#3522]
Even with Hide Twitch Extensions on, the Prime Subscription & Loot Reminder buttons still appears over the video player.

**Comment by Nareese** [comment]
duplicate of #3519.  An update to resolve this was made about an hour after you posted this, and this issue should now be resolved.

**Comment by Halvhjearne** [comment]
if this is supposed to be fixed, then i suggest you take a look at it again.
it still does not work, the extension is still visible, but now there is no option to remove it at all, unless i disable this.

**Comment by night** [comment]
fixed by a207ef1776601c2f0e3afec19e1d6b353d252cd4
