### ISSUE TITLE
Add option to move chat user list button back to next to the emote button

### ISSUE THREAD

**Issue by PointyDev** [night/BetterTTV#3535]
Hey there,

So recently (last month with the chat overhaul afaik?) the user list button moved to the top header of chat, meaning the "Hide Chat Header" also hides this button. This inconveniences me as I prefer the header not being there. Perhaps add a new option to move it back or just automatically move it if the header is hidden?

![](https://pointy.needs-to-s.top/bS453hC.png)

Thanks,
Elliott

**Comment by night** [comment]
Given the launch of Twitch points this is not something I think I will add. It gets very messy to deal with this when Twitch is trying to add new stuff there.
