### ISSUE TITLE
Mod Card Bug

### ISSUE THREAD

**Issue by Lpz3nc** [night/BetterTTV#3536]
When I inspect a name in the viewer list (by clicking on it) I can see the channels details and followage and sub status and stuff. Then the next time I click on it the viewer, some of that channels information is gone
![chrome_2019-08-07_23-15-51](https://user-images.githubusercontent.com/53795071/62659186-fa636280-b96a-11e9-8c43-ba1374b8d478.png)
![chrome_2019-08-07_23-16-51](https://user-images.githubusercontent.com/53795071/62659191-fcc5bc80-b96a-11e9-8a27-a358679611b7.png)

**Comment by Nareese** [comment]
Can confirm I also see this behavior when clicking multiple times on a name in chat as well, so it's not confined only to the viewer list.

**Comment by Civrock1** [comment]
Noticed the same issue today.
