### ISSUE TITLE
Ability to purchase more shared emote slots to exceed 50 slots for $5 more?

### ISSUE THREAD

**Issue by bitcornfarmer** [night/BetterTTV#3538]
I would like the ability to purchase say another 50 emote slots for a total of 100 shared emote slots for even say $5/mo more.  Is this something your team can look into and to help expand your business model even.  

Thank you for your consideration.

**Comment by Mysteriousdewd** [comment]
Please. I was gonna contact you on discord to ask if this is possible. I've been subscribed to BTTV Pro for over 2 years straight and would like to see more rewards for long term subscribers. More emote slots after a year, two years, three, etc. Like 50 a year would be really cool and appreciated. I know Frankerz has a one time payment and they give certain people more slots but its not known how people get them. BTTV would benefit from this to encourage people to continue their long subs.

**Comment by iEshGH** [comment]
I'd like this too and I know many streamers that would actually use this.

**Comment by night** [comment]
Instead of purchasing more, I've decided to just give people more emotes. I've bumped the base amount from 25 -> 50, and the longer you stay subscribed the more emotes you get. We now give you 2 extra channel and shared emotes per month (up to 100 both).
