### ISSUE TITLE
Sound Notification when Followed Channels Go Live

### ISSUE THREAD

**Issue by Maxhype** [night/BetterTTV#355]
Time to time you miss the notification because there's no sound notification.

**Comment by Maxhype** [comment]
I don't want to create new topic for this because this is also sound related, I would also love a sound notification for new messages.

**Comment by MrFJ** [comment]
This. The chrome notifications don't stay up for nearly long enough and even if they did that doesn't help if I'm not at the computer... Sound notifications would be awesome! :)

**Comment by night** [comment]
no longer applicable
