### ISSUE TITLE
Picture In Picture

### ISSUE THREAD

**Issue by oswaldoacauan** [night/BetterTTV#3550]
Would be nice to have a button to enable the native PiP from Chrome.

`document.querySelector('div.player-video video').requestPictureInPicture();`

If I have the time I will try to implement and open a PR for that :)

**Comment by MuhamadOmr** [comment]
i want to mention that google already have Picture-in-Picture chrome Extension 
https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg

**Comment by PointyDev** [comment]
[This](https://github.com/amarcu5/PiPer) may be something worth looking into for some existing implementation, specifically [this](https://github.com/amarcu5/PiPer/blob/master/src/common/scripts/resources/twitch.js).
