### ISSUE TITLE
Emote List not showing up in chat

### ISSUE THREAD

**Issue by CRizzyS550** [night/BetterTTV#3553]
So before when you were in someones channel that has BTTV enabled you could see the BTTV emotes they had. However now I can't see them. The only emote lists that are available are Sub Emotes and FrankerFaceZ emotes. The only way to get the emotes is to now click the global emote button. 
<img width="806" alt="Screen Shot 2019-08-26 at 1 35 09 AM" src="https://user-images.githubusercontent.com/19923147/63667520-1c017e00-c7a2-11e9-9aec-1b15ec64c710.png">
<img width="298" alt="Screen Shot 2019-08-26 at 1 35 23 AM" src="https://user-images.githubusercontent.com/19923147/63667521-1c017e00-c7a2-11e9-9f7b-10eb9d886b91.png">
<img width="336" alt="Screen Shot 2019-08-26 at 1 37 34 AM" src="https://user-images.githubusercontent.com/19923147/63667522-1c017e00-c7a2-11e9-8700-99b9768585db.png">

P.S I have cleared all my cookies and data in deleted and reinstalled BetterTTV in the hopes I could redo the settings and stuff but still not working.

**Comment by night** [comment]
![image](https://user-images.githubusercontent.com/2942184/63673533-59154280-c799-11e9-9403-1090b2aa431b.png)

from your screenshot the channel emotes are listed.

**Comment by CRizzyS550** [comment]
> ![image](https://user-images.githubusercontent.com/2942184/63673533-59154280-c799-11e9-9403-1090b2aa431b.png)
> 
> from your screenshot the channel emotes are listed.

That's not the list they used to be on. In photo #2 they Used to be on that list. Never on the other thing. I wanted to know why they're no longer on the normal list in Photo 2 instead of having to go to the emoji list in photo 4
