### ISSUE TITLE
The Ability to see what Channels are using the emote you made.

### ISSUE THREAD

**Issue by Canadian-bacon1867** [night/BetterTTV#3557]
Now I don't know what happened but you used to be able to see which channels had enabled emotes you made and shared publicly.

I loved this feature because It would introduce me to new channels and I'd interact with that streamer and their community, it made me a lot of new friends and I'd love to be able to do that again.

**Comment by night** [comment]
This is a feature we used to have on the old website, and have not yet re-added it. It will be coming back soon™

**Comment by night** [comment]
This was re-added a while back
