### ISSUE TITLE
Blacklist messages by message length

### ISSUE THREAD

**Issue by jeremyhill-up** [night/BetterTTV#3558]
BTTV is great, I love it. I have a feature request, which is to expand the blacklist functionality a little bit. Either/or of these would be excellent:

1. Full regex support, or
2. Blacklisting messages based on message length

Fortunately a lot of streamers block the "░░░▒░█────▄▀░░░░░░░░▀" junk, but I'd love to be able to do it on my end for the streamers who don't.

**Comment by night** [comment]
Duplicate of #141
