### ISSUE TITLE
[Feature Request] Clicking emote automatically pastes it in chat

### ISSUE THREAD

**Issue by zulxer** [night/BetterTTV#356]
So I was thinking it would be cool to add a toggle-able future that automatically pastes / puts the emote that you click fromt the chat into your chat box. Maybe not a very important feature, but would be pretty cool to see it added for lazy people like me. 
Here's a (bad) example, you can't really tell that I'm clicking but I think you get the point

http://i.imgur.com/zuNmkJ9.gifv

**Comment by Maxhype** [comment]
+1

**Comment by cletusc** [comment]
Being able to click all emotes would probably give the impression that they can use the emote as well, whereas the emote menu will only show what the user can _actually_ use. This would require knowing if the emote is usable by the user before attaching any click handlers, or, if the logic is moved inside the click handler, making that function call with every click and possibly displaying a message saying that can't use it.

I am -1 on this as it doesn't provide much value for the amount of work it would probably take to implement.

**Comment by night** [comment]
@cletusc 's emote menu is as close as you will get to this.
