### ISSUE TITLE
[Feature Request] Keep Emote Menu Open 

### ISSUE THREAD

**Issue by janjanjanjan** [night/BetterTTV#3562]
When you open the emote menu, you can pick an emote, but afterwards the menu closes immediately. 

Would it be possible to keep the emote menu open, so that it is possible to choose multiple emotes in one go?

Thanks for your consideration :)

**Comment by Nareese** [comment]
In the lower right corner of the Emote Menu, there is a "pin" icon.  Click that, and the menu will stay open until you unclick the pin, or click on the Emote Menu button to close it.

**Comment by janjanjanjan** [comment]
Thank you! I didn't know this option existed. Sometimes it's easier than you think ;)
