### ISSUE TITLE
[Feature Request]: Reduce Visual Noise From Channel Points

### ISSUE THREAD

**Issue by JaRail** [night/BetterTTV#3563]
Twitch is testing out a new points feature. Basically it's Embers from Mixer, where you can spend loyalty points to highlight your chat messages, etc. Another comparison would be to loyalty bots such as the discontinued Revlo Bot.

One of the things Channel Points does is add a "click here to claim bonus" button to chat. It's a little green gift box that just keeps bouncing until you click it. It also counts up your points every 5 mins. So an animated "+20" or something. There are notifications in chat whenever you collect enough points to spend on a new reward. It's a lot of visual noise.

More info and screenshots on the help page: https://help.twitch.tv/s/article/channel-points-guide

Given this just launched, it's hard to say how they'll evolve it. Seems likely the BTTV users won't want all the extra visual noise. Some filtering features could be really nice.

**Comment by night** [comment]
I'll have to see how this plays out, but I agree that embers is a bit over the top on mixer and I'd hate to see that on Twitch too.

**Comment by Px05119** [comment]
I was actually going to look into making a post about this. My issue however is that the green box covers up the emote menu. Would like to see either an offset between the channel points system and emote menu so all is visible, or an option to move the emote menu between the settings cog and channel points (if not hiding said points system entirely, which would be best imo)
![Channel Points](https://user-images.githubusercontent.com/25652184/64666200-64b46a80-d423-11e9-8d5a-8ed39d6aee43.png)

**Comment by SephirothWS** [comment]
I am just going to have to comment and agree with this particular request. The ability to either hide all of the animations and flashy business of this new points system would be wonderful. Got a friend of mine who gets extremely irritated by the box bouncing around and all the flashy animation effects from it counting up points. I also don't like all of the additional fluff added into the chat itself.

**Comment by jacelync** [comment]
I would do anything to be able to remove the highlights from the "highlight your message" feature.
