### ISSUE TITLE
[Feature request] Change number of showed followed channels

### ISSUE THREAD

**Issue by AlexWayfer** [night/BetterTTV#3564]
I have many followings, about 20.

And periodically there are more than 5 live of them.

The height of my monitor is large enough, so I'd like to see around 7-8 (customizable) followed channels in standard (collapsed) mode.

**Comment by night** [comment]
There's already an option to expand that sidebar list in the settings.

**Comment by AlexWayfer** [comment]
> There's already an option to expand that sidebar list in the settings.

I saw. This issue is not about expanding. I follow around 30 channels, I don't want to see and scroll them all.
