### ISSUE TITLE
[Bug] "Auto Expand Followed Channels List" expands "Recommended Channels"

### ISSUE THREAD

**Issue by AlexWayfer** [night/BetterTTV#3565]
There is no mention of expanding "Recommended Channels" in the setting "Auto Expand Followed Channels List".

**Comment by night** [comment]
This might be due to the selector being the same for both, which is tricky to fix. Do you want to just hide Recommended Channels? That is its own option already.

**Comment by AlexWayfer** [comment]
> Do you want to just hide Recommended Channels?

No.
