### ISSUE TITLE
Reverse Chat Messages Direction not working after 7.2.65 release

### ISSUE THREAD

**Issue by RubenPHP** [night/BetterTTV#3567]
The Reverse Chat Messages Direction was woking great before 7.2.65 release. Maybe is a problem on my side, but just after the new release, the "Reverse Chat Messages Direction" don't work anymore. 
The messages are reversed, top first last bottom, but the scroll doesn't work, it's stuck at the first messages.

Thanks.

**Comment by jaredgiangrasso** [comment]
@night I can take a stab at this if you'd like!
