### ISSUE TITLE
Bttv Is Broken

### ISSUE THREAD

**Issue by GoboPa** [night/BetterTTV#3569]
Two days ago my twitch started acting up. (Saying that it failed to load module over my chat) And the day after my bttv completely broke. (As Shown in the linked images). Ive uninstalled and reinstalled the extension many times. Unmarked ffz emotes. Disabled all other extensions, adblocks and what not. Even uninstalled and reinstalled chrome itself. I am out of ideas and i cant find this problem anywhere.
![3435d3997f592e1c2222a47f44c5beee](https://user-images.githubusercontent.com/55036859/64481309-fc515900-d196-11e9-9033-bdbb5e0d74d1.png)
![005481c0eae5723ba3043e0001e577ba](https://user-images.githubusercontent.com/55036859/64481310-03786700-d197-11e9-89b7-edbba1322ba7.png)

**Comment by GoboPa** [comment]
You can see that the emotes work, but there is a weird like description of them underneath each one, which destroys the chats due to all the bttv emote spam. Then in the settings screen for bttv, it looks like that, a weird source-esk menu, that doesnt scroll so most of the settings are even unreachable, not that that matters.

**Comment by night** [comment]
This looks like the stylesheets are not loading. Try clearing your cache, and if issues persist disabling other extensions like Adblock etc.
