### ISSUE TITLE
Theres a problem with one emote

### ISSUE THREAD

**Issue by Overhunter1** [night/BetterTTV#357]
The emote know as :/ is broken and not showing up or anything please fix this

**Comment by vendethiel** [comment]
That does seem to happen here as well

**Comment by cletusc** [comment]
If what you are talking about is the emote menu, it may be related to cletusc/Userscript--Twitch-Chat-Emotes#78 where the `:/` emote is moved into the turbo section.

Can either of you clarify exactly what the issue is--emote menu, chat, etc.?

**Comment by night** [comment]
Emotes are implemented server-side by Twitch.
