### ISSUE TITLE
Highlighted messages ignoring blacklist keywords + emotes

### ISSUE THREAD

**Issue by delphinkid** [night/BetterTTV#3574]
Chat messages using the "Highlight My Message" feature introduced with channel points ignore blacklisted keywords and display the messages regardless of whether they contain phrases in the blacklist.

**Comment by night** [comment]
unfortunately this is hard to fix given the limited release of channel points (meaning we can't easily test/fix this)

**Comment by delphinkid** [comment]
I understand, thank you for responding. For the time being I have worked around the issue by blocking the highlighted text element with uBlock origin, in case anyone else is having the same issue.

**Comment by breon** [comment]
Any channel can now request to be part of the channel points beta. They are rolling it out to additional channels soon. My guess is around October 15th, as that's a date they mentioned that points may reset for existing channels. https://www.twitch.tv/beta/channelpoints

**Comment by Cyberbeni** [comment]
This is also true for sending message in sub only mode.
