### ISSUE TITLE
bttv's ui elements in chat are misaligned

### ISSUE THREAD

**Issue by CoolCmd** [night/BetterTTV#3576]
7.2.67

![bttv](https://user-images.githubusercontent.com/684851/65028296-868e7f80-d944-11e9-81a1-4893e6481c1d.png)

**Comment by CoolCmd** [comment]
BTW chat already has a state indication. `#bttv-channel-state-contain` is redundant?

**Comment by night** [comment]
it looks like twitch moved the chat settings icon, which displaces everything
