### ISSUE TITLE
bttv settings are inserted in wrong place

### ISSUE THREAD

**Issue by CoolCmd** [night/BetterTTV#3577]
firefox 69, bttv 7.2.67
![bttvs](https://user-images.githubusercontent.com/684851/65043589-d892cd80-d963-11e9-90a5-dd61d75adff2.png)

**Comment by night** [comment]
this only occurs since you're a mod, and is tricky to fix due to how react is lazily rendering this view.

**Comment by CoolCmd** [comment]
FrankerFaceZ do not have this problem. u can use its method to insert setting.

**Comment by IVLeague** [comment]
Second this. Twitch changed its chat settings and the menu is no longer scrollable so I can't see the BTTV settings at all in channels I mod. Even when I switch to non-mod view the BTTV settings are still up top and are partially cut off in Chrome. 

Also, I don't see any BTTV settings at all in my own channel's chat settings menu, not sure if that's supposed to be like that or not.
