### ISSUE TITLE
BTTV Emotes not showing in chat

### ISSUE THREAD

**Issue by Scyrine** [night/BetterTTV#3580]
After adding emotes to my twitch chat and several tries of attempting to make it work, the emotes aren't showing (the ones i added to the chat) except for the global BTTV emotes. is there a fix to this? 

![snao 2](https://user-images.githubusercontent.com/55466394/65084902-accf1200-d97a-11e9-8a1a-02ae6c8adc41.PNG)
![snap 1](https://user-images.githubusercontent.com/55466394/65084903-accf1200-d97a-11e9-8a6b-e074212cd640.PNG)

**Comment by night** [comment]
Emotes take 10-30 minutes to show up.
