### ISSUE TITLE
2 little things 

### ISSUE THREAD

**Issue by Monkey151546** [night/BetterTTV#3581]
"new prime loot" is back at the top of the screen, when browsing twitch or when not in theatre/full screen mode

and I cannot scroll twitch's setting menu below the chat anymore, it doesn't let me, I tried on my main monitor and I couldn't see everything, then I tried on my second monitor which is a bit smaller and I couldn't scroll either (I saw another post about the setting menu , I don't know if it's related, if so sorry.

**Comment by AlexWayfer** [comment]
For "2 little things" please create 2 little issues.

**Comment by AlexWayfer** [comment]
> the former issue is a duplicate of #3589 I believe

I think, no.

Probably it's about icon in header:

![image](https://user-images.githubusercontent.com/6510020/65422773-0ec2c800-de10-11e9-8898-db3df86c8e78.png)

(I saw also the red badge with number there, just clicked on it)

**Comment by Monkey151546** [comment]
> the former issue is a duplicate of #3589 I believe, and the latter is not reproducible for me

sorry for bringing it back up, about the "cannot scroll the settings menu" i just tested again, at 100% i see all the settings, i use 125% that is why i can't see all of them/can't scroll. (by 100% and 125% i mean the quick zooming with mouse CTRL + up)
