### ISSUE TITLE
Reverse Chat Messages Direction buged?

### ISSUE THREAD

**Issue by elBokeron** [night/BetterTTV#3583]
Hi!

I loved the "Reverse Chat Messages Direction" option you guys introduced a few months ago, but somehow, it doesn't seems to work for me anymore since the end of August... When I use it now, the chat actually stops and I have to scroll it up manually in order to see the new messages. Autoscrolling is not working.

Are you aware of this? Does anyone else reported it?

Thank you!

**Comment by night** [comment]
This issue was already fixed. Please make sure you're on the latest extension version, 7.2.67
