### ISSUE TITLE
Countdown to last ! command (feature request)

### ISSUE THREAD

**Issue by volcom543** [night/BetterTTV#3584]
I have no idea how to make this into a Feature request.

I would love to have a feature to have a countdown for last ! command. Would be great for channels with gambling and not having to guess the time down of when you can gamble again. 

could narrow it down more and add a whitelist to what ! command you want it to countdown from.

**Comment by night** [comment]
Unfortunately this feature would be way too specific for something we can build into BetterTTV. We really only build features with wide appeal.

**Comment by volcom543** [comment]
No problem I understand :)
Thank you for replying though, appreciate it.


On Sep 23, 2019, at 4:00 AM, Zack <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately this feature would be way too specific for something we can build into BetterTTV. We really only build features with wide appeal.

**Comment by volcom543** [comment]
Came to a more basic thing, have the option to add “seconds” to timestamps maybe?

On Sep 23, 2019, at 4:00 AM, Zack <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately this feature would be way too specific for something we can build into BetterTTV. We really only build features with wide appeal.
