### ISSUE TITLE
Feature/site fix: don't show "LIVE" for channels that also show "Rerun"

### ISSUE THREAD

**Issue by Vagmer** [night/BetterTTV#3587]
Twitch site shows white text on red background "LIVE" marker (that shows "Live Now" on mouseover) in some places even for channels that it also marks as a built-in rerun (distinguished by page CSS). This does mean that the channel isn't offline, but it is misleading. This is probably why - other than memeing - confusion as to whether the stream is a rerun or not seems to be pretty common in chats despite the page clearly saying "rerun" in two places. I think the "LIVE" marker on reruns used to happen on more pages like channel lists but right now I can only see this behavior on the channel page while watching a rerun so it may have been improved. At any case you should never see "LIVE" and "Rerun" for a channel at the same time, obviously... so this should receive an on-by-default fix option(s) in BTTV. I propose options to either remove the "LIVE" marker in these cases or allow editing it to customized text, background color and text color:

vanilla Twitch
![image](https://user-images.githubusercontent.com/12949474/65372612-169d3380-dc7b-11e9-8fa0-4de07578c856.png)

BTTV fix option 1
![image](https://user-images.githubusercontent.com/12949474/65372799-3cc3d300-dc7d-11e9-9cd3-83b1afd2333b.png)

BTTV fix option 2
![image](https://user-images.githubusercontent.com/12949474/65372810-6c72db00-dc7d-11e9-9081-1965cc581141.png)

Related to/would reuse code used to implement #3376, #2496.

**Comment by night** [comment]
I don't think this is worth fixing. This is probably an oversight on Twitch's behalf too as they don't reference reruns as LIVE in their directory UIs. Additionally, most users looking for live streams do so from the directory/sidebar/following/notifications
