### ISSUE TITLE
Newly added BTTV emotes not showing

### ISSUE THREAD

**Issue by GeChSo** [night/BetterTTV#3588]
Whenever new BTTV emotes are added to a channel, they aren't shown. This happens both in normal Twitch chat and in Chatterino. I can still see BTTV emotes added to a channel before the 20th of September though. I also can't autocomplete these emotes.
I already heard from multiple people that they have the same issue, but at the same time, I also heard from people who can see these new emotes.

Example:
![unknown"](https://user-images.githubusercontent.com/55624331/65373178-66c7c600-dc7a-11e9-9ed9-368556087edd.png)
The second emote of the user TensaZS1 is an emote that was added yesterday to the channel "NymN". It is called "BIGFUCKINGKAPP" (Emote: https://betterttv.com/emotes/5d84d4dec0652668c9e4edda). This screenshot was sent to me by TensaZS1, which means that he can see the emote.

![Unbenannt](https://user-images.githubusercontent.com/55624331/65373176-66c7c600-dc7a-11e9-8dfd-1ca4d5c4e05c.PNG)
Meanwhile, when I try to type the emote, I can't see it. (Both screenshots are from the same channel).

The screenshot was taken on the 20th of September at 17:13 CEST. Now, on the 21st of September at 14:25 CEST, around 21 hours later, I still cant see the emote.

Edit: NymN removed it from his channel again, but this was posted before he removed it.

**Comment by night** [comment]
Emotes are currently cached for 10-30 minutes, so it takes 10-30 minutes before they will show up.

**Comment by GeChSo** [comment]
Well, they didn't though. So I don't see why you closed this thread and labeled it as "invalid", even though it is a problem occurring.
