### ISSUE TITLE
Community Gift Chests

### ISSUE THREAD

**Issue by IVLeague** [night/BetterTTV#3589]
Can we get an option to hide this community gift chest thing at the top of chat? It takes up a ton of room and doesn't go away
<img width="357" alt="Screen Shot 2019-09-22 at 4 38 03 AM" src="https://user-images.githubusercontent.com/55558707/65384768-2dcc3780-dcf4-11e9-8546-be5a39ab2f17.png">

**Comment by IVLeague** [comment]
This isn't the same thing as the new prime loot that post was talking about. New prime loot is an icon on the purple header at the top of the page. This is community gift chests that is in the actual chat and takes up a ton of room.

**Comment by IVLeague** [comment]
No longer needed. FFZ does this.

**Comment by AlexWayfer** [comment]
> No longer needed. FFZ does this.

But it's still the issue for BetterTTV.

**Comment by IVLeague** [comment]
> > No longer needed. FFZ does this.
> 
> But it's still the issue for BetterTTV.

I mean there are plenty things that are an issue that BTTV doesn't touch that FFZ does...

**Comment by Brcrwilliams** [comment]
This box annoyed me enough that I created a new module to hide it. #3705
