### ISSUE TITLE
Every time I open a new Twitch page my previous settings are reverted

### ISSUE THREAD

**Issue by respectabiggle** [night/BetterTTV#3590]
The most obvious one is night mode, but other small things like "turn off suggested friends" etc. have reverted to what I assume are default settings.

Any help greatly appreciated!

**Comment by night** [comment]
Ensure your cookies are not set to clear on browser close in your browser settings.

**Comment by respectabiggle** [comment]
Oh wow yes that's it.  Thank you thank you thank you.
