### ISSUE TITLE
Can Someone please help me? thanks 

### ISSUE THREAD

**Issue by lockettmp4** [night/BetterTTV#3594]
![bttv](https://user-images.githubusercontent.com/55815165/65644759-8ab53f80-dfcb-11e9-9453-81f32fa3cbde.PNG)

**Comment by xgerhard** [comment]
Hi, this does not look like the BTTV emote menu, so not sure if we can help.

**Comment by lockettmp4** [comment]
Hi, this is just showing tha all my gifs are not working and most of emotes that don't have the normal size have the same problem. is there anything I can do ?

**Comment by xgerhard** [comment]
Try disabling other browser extensions except BTTV.
