### ISSUE TITLE
[Feature Request] click an emote in chat to append it to the message input

### ISSUE THREAD

**Issue by alanhussey** [night/BetterTTV#3599]
It'd be nice to be able to click on an emote in chat and have it be automatically appended to my chat message. I already have to hover the emote to learn its name, and clicking it is much easier than keeping it hovered and transcribing the name.

**Comment by night** [comment]
Clicking on an emote is already an action which exists, so it cannot be replaced. You can already copy/paste the emote into chat, which I think is a more normal behavior.
