### ISSUE TITLE
Show Follower count on channel page

### ISSUE THREAD

**Issue by hectic-noam** [night/betterttv#3602]
Life was good when I could open a twitch channel and see the amount of followers they had.
Now I have to click on the word Followers and wait for a new page to load up.

BTTV could make my Twitch experience SO MUCH BETTER if I could just get back what Twitch took away: https://cdn.discordapp.com/attachments/326719968706166785/629035968208568320/unknown.png

Thank you.

**Comment by Fireztonez** [comment]
Totally agree for the Followers count, I really hope BTTV will add an option to add-back that old feature to twitch, because this is very annoying to have to click on Followers question to be able to see the information.

I still hope Twitch will add back that information, but unfortunately I don't think this will append :(.

**Comment by Osyruu** [comment]
It's not BetterTTV's job to do it, it's Twitch's job to do it.

**Comment by hectic-noam** [comment]
> It's not BetterTTV's job to do it, it's Twitch's job to do it.
It's not BetterTTV's job to make Twitch better ???

**Comment by Fireztonez** [comment]
@Osyruu 
Strange reply yeah... BetterTTV is not supposed to be an addon to make Twitch better, add somes options, add somes emotes and stuff...

I can't imagine adding this kind of things is really hard, Twitch show the information on multiples place  already.

And just to say, everyone I talk to complains about Twitch's decisions to remove the number of Followers on the main page of the channel, so I'm pretty sure this option would be used by many people.

it's disappointing to see such a closure from BetterTTV, for such a request. Me who thought maybe has become support, you disappoint me greatly and say that it cuts me my desires to give.

**Comment by night** [comment]
> it's disappointing to see such a closure from BetterTTV, for such a request. Me who thought maybe has become support, you disappoint me greatly and say that it cuts me my desires to give.

nobody commenting on this thread is associated with the project. users associated with the project have "collaborator" next to their names in comments.

**Comment by PointyDev** [comment]
I think a good place to put total followers would be next to total views and current viewers so it doesn't appear out of place on the channel navbar. Perhaps use a heart icon similar to the one in the follow button.

![](https://pointy.needs-to-s.top/87zdFSe.png)

**Comment by night** [comment]
it looks like twitch re-added follower count to channel pages
