### ISSUE TITLE
[bug] Panel Button Language

### ISSUE THREAD

**Issue by Osyruu** [night/BetterTTV#3603]
Hello, I'm French and wanted to tell you that when I edit the panels below my channel we do not see the buttons to save the panel.
![langFRAPanelButton](https://user-images.githubusercontent.com/22823858/66142358-8f9a7480-e605-11e9-8594-7f32eda9ff01.png)
But when I put Twitch in English it appears perfectly.
![langENGPanelButton](https://user-images.githubusercontent.com/22823858/66142352-8d381a80-e605-11e9-9bea-bbd99e79143e.png)

PS: I do not know if it's BTTV or Twitch doing that, but I think it's Twitch and not BTTV. I'm asking this here just in case

**Comment by night** [comment]
This looks like a bug with Twitch, not BetterTTV
