### ISSUE TITLE
BetterTTV Not working in Chrome

### ISSUE THREAD

**Issue by CRizzyS550** [night/BetterTTV#3605]
So I have installed and uninstalled the extension. This problem is happening on both my Mac and Windows 10 PC. Now sometimes if you refresh a stream 20 or so times then you MIGHT get the Better TTV menu to show up but most of the time there is nothing there but the default Twitch Settings. I don't know what else to do. When it does show up that 1 in random chance then it works as it should but otherwise it never shows up at all.
![betterttv1](https://user-images.githubusercontent.com/19923147/66265359-0e98d400-e7e3-11e9-978d-bd11f35500c5.PNG)
![betterttv2](https://user-images.githubusercontent.com/19923147/66265360-0e98d400-e7e3-11e9-8850-2a6067c50c09.PNG)

**Comment by night** [comment]
Disable FFZ.
