### ISSUE TITLE
Pause when opening extension menu

### ISSUE THREAD

**Issue by zorgling** [night/betterttv#3606]
When "Click to Play/Pause Stream" is enabled and you click on an extension pop-up to open it's menu, the stream pauses (which isn't what I intend to do typically) and hides the extension pop-up (because that doesn't show unless the stream is playing).  It would help if these features didn't conflict and result in unintentional stream pausing and unnecessary hassle in disabling individual stream extensions.

**Comment by night** [comment]
It's probably hard to fix because to make the video player clickable we have to make the extension overlay clickable. This is likely why Twitch doesn't support this natively. If you're like me, however, you just want to hide the extensions anyways.

**Comment by zorgling** [comment]
Yeah, I figured it would be hard to fix.  I also hide ~99% of extensions, but I have come across a few good ones so I don't disable the extension overlay that way I can know when a good extension is being used.

**Comment by night** [comment]
This looks fixed now, as click to play/pause no longer functions when twitch extensions are on the player.
