### ISSUE TITLE
Dark Mode turns off whenever viewing a site with embedded Twitch Chat and BTTV enabled

### ISSUE THREAD

**Issue by garyking** [night/BetterTTV#3608]
On Twitch, I enable Dark Mode. I have BTTV enabled.

I go to a site with an embedded Twitch Chat, like [this one](http://nba4free.com/stream/nbatv/). ([Instructions on how to embed Twitch Chat](https://dev.twitch.tv/docs/embed/chat).) By default, embedded chats use the light theme, unless the `src` includes `?darkpopout`.

When I refresh the Twitch website, dark mode is turned off.

This bug does not occur if the BTTV extension is disabled in Chrome.

As a temporary fix, is it possible to disable BTTV in chat embeds, on sites other than twitch.tv?

**Comment by Scrxtchy** [comment]
Is it still appropriate to have the bttv dark mode toggle if there's one now natively on the twitch UI?
Has felt a redundant option for quite a while now

**Comment by night** [comment]
It is redundant but some people may get lost without it, and so it remains.
