### ISSUE TITLE
Can't add emotes I upload to my Personal list of emotes

### ISSUE THREAD

**Issue by di00ib** [night/BetterTTV#3610]
The box to add emotes to my personal list is grayed out and says, "Only available for manually approved emotes at this time." The only reason I pay for BTTV is to add my custom emotes to my personal list.

What do I need to do to get my emotes I upload into my personal list? Do they need to be manually approved? Or something else?

Please get back to me on this.

Thanks.

**Comment by Nareese** [comment]
Eventually there will probably be a UI element to request manual approval for personal emotes, but there isn't at the moment.  For now, you can use the "Report Emote" function, and specify the reason as "Submitting for manual approval for personal emote".

**Comment by night** [comment]
If you try to click the button it will now prompt you to submit it for manual review.
