### ISSUE TITLE
Approved Emote Doesn't Work

### ISSUE THREAD

**Issue by topsideJC** [night/BetterTTV#3615]
I have an approved emote from a while ago, and I gave it time thinking it may have still been processing. But, today the problem persists even on other people's channel who've added it to their shared list.

 It simply doesn't work in the chat, yet it had no problems getting approved. BTTV code is "JCwave" if you want to test it. 

Thanks for any help in advance.

**Comment by xgerhard** [comment]
Hiya,
Is this your emote: https://betterttv.com/emotes/5d8a2466d2458468c1f48790
Seems to work fine in your channel:
![jcf4c9c554e1f1be8dff66749d69aef355](https://user-images.githubusercontent.com/13732765/67095631-aec50480-f1b6-11e9-8672-df5bbed9a3a3.png)
And as far as I can see, this emote has not been enabled in other channels.

**Comment by topsideJC** [comment]
Thanks for the response, my friend and I was trying it in our channels and
they weren't working, but the others were working just fine. I've updated
my extensions and used new ones as well. It may just be on my end.
This is what I see on my side:
[image: Emote bug.png]

It's not really a big deal, it was just weird. The fact that it works for
you should mean at least other people should see it when it's used. Thanks
for the response again.

**Comment by topsideJC** [comment]
I don't mean to blow you up on this email but, all of a sudden it's
working. For some reason it doesn't work for me when it's the First emote
used. But if I type a message, then use the emote it works. Weird idk,
sorry for wasting your time. haha
Thanks again. :)
