### ISSUE TITLE
Automatically claim bonus channel points

### ISSUE THREAD

**Issue by pointydev** [night/betterttv#3616]
Heya,

So one of my favourite streamers just got channel points, and I noticed the bonus button that pops up from time to time. I think a good feature would be to automatically claim these points for the user so they don't miss out if, for example, they go AFK. Would love to see it!

Thanks,
Elliott

**Comment by night** [comment]
this is a cool idea.

**Comment by Ansem93** [comment]
I would love that too!

**Comment by henry-ns** [comment]
I'm developing an extension for this, and I thought BTTV should have.

link: https://github.com/henry-ns/twitch-farm

is in development but can be used
