### ISSUE TITLE
VIP Chat Tags

### ISSUE THREAD

**Issue by Izlsnizzt** [night/BetterTTV#362]
VIP status - A custom icon the channel dev can delegate to, well, anyone in the channel. /vip <name>, /novip <name> to remove. This would allow people like me to give a special badge for 10k tokens, and also allow for more tracking with the bot (if accessible via an API).

-CohhCarnage

**Comment by hipstercamelhumper** [comment]
Fucking love this idea. Reminds me of the !addreg command by nightbot but finally being granted a visible badge. Chat hierarchy ftw

**Comment by GavoTrav** [comment]
Its a good idea! someone like lirik was talking about i the other day "I wish there was like a VIP tag that I could give people without making them mod.."

**Comment by night** [comment]
Closing this since Twitch has these natively.
