### ISSUE TITLE
[Website] Install or download userscript version redirects to homepage

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3623]
When attempting to access the userscript version of the extension loader (Safari or Other, `https://nightdev.com/betterttv/other/betterttv.user.js`), a 302 Moved Temporarily is returned with a redirect back to `https://betterttv.com`, which then shows up in the address bar as `https://betterttv.com/#bypass=true`.

**Comment by night** [comment]
this is now fixed
