### ISSUE TITLE
Channet Point Emotes

### ISSUE THREAD

**Issue by LysolPionex** [night/BetterTTV#3624]
It'd be neat to show the channel point emotes (Kappa_BW, Kappa_HF, Kappa_PK, Kappa_SG, Kappa_SQ, Kappa_TK) the way FrankerFaceZ are shown.  The emotes are there already (e.g. [bogaH_BW](https://static-cdn.jtvnw.net/emoticons/v1/1917874_BW/2.0), [bogaH_HF](https://static-cdn.jtvnw.net/emoticons/v1/1917874_HF/2.0) etc...).

**Comment by night** [comment]
Can you elaborate?

**Comment by night** [comment]
unfortunately we do not wish to build bypasses for revenue/points products due to concern over how Twitch would respond to such features being in BetterTTV. in the past they have threatened legal action for similar kinds of changes.
