### ISSUE TITLE
I can't use the Emote Menu for BTTV

### ISSUE THREAD

**Issue by Chubbss** [night/BetterTTV#3629]
I am able to open the BTTV emote menu for twitch, but when I click on emotes, nothing shows up on the message area, I can type in it, but I can't use the menu, how do I fix this? Thank you!

**Comment by Drox88** [comment]
I am also having this issue, emote menu is working but when I click on any of the emotes (even normal twitch and frankerz) they don't go to the chat box once clicked.

**Comment by LowLietStrong** [comment]
Perhaps this is also connected, double-clicking on the nickname also does not work

**Comment by ThiagoScala** [comment]
Same bug here too

**Comment by IGARIS** [comment]
Same bug(((

**Comment by morganeee** [comment]
When can this be fixed ?

**Comment by night** [comment]
it already is fixed. you can check for extension updates in chrome/firefox to force update.
