### ISSUE TITLE
Pinned Chat Message

### ISSUE THREAD

**Issue by Izlsnizzt** [night/betterttv#363]
Pinned messages - /pin <message> to make one, /unpin to remove, and another /pin updates the existing if applicable. Basically just like a pinned tweet, but it's a pinned chat line from the channel owner with a time on when it was posted.

This would allow one-way communication from the broadcaster to the audience via chat that everyone would be able to read, as no matter how fast chat is going, it would be stuck right there at the bottom.

-CohhCarnage

**Comment by Maxhype** [comment]
+1.

**Comment by EhsanKia** [comment]
I like the idea, but I think that it'd make people rely too much on the fact that viewers have BTTV installed. What I mean is, pinned messaged would usually be important information you expect everyone to see, yet, anything without BTTV would be missing it, so you can't rely on the fact that everyone sees it, which partly makes it a lot less useful.

**Comment by Izlsnizzt** [comment]
We design features for BTTV users, if people choose not to use it they could potentially miss out on a lot of stuff, bttv emotes for example, I fail to see how this is a valid argument. Many casters actively promote the use of BTTV for their channel, whether people choose to use it or not is up to them.

**Comment by CravingGaming** [comment]
Good idea, but I thought it would be better to have it instead of the "Welcome to _____'s chat room!" message.

**Comment by moistmann** [comment]
I really like this idea, it would be amazing to be able to have a pinned message for say what difficulty they are playing on or that any spoilers said is an auto ban so be careful among other things like things that are linked to the title of the stream as in "streaming on my new computer" it could show the specs for the people interested, all of this meaning there would be less repeated questions asked/answered meaning chat would have a lot less spam, have a slower but much more enjoyable chat experience

**Comment by night** [comment]
it looks like Twitch has released their own form of pinned messages for chat, making this request obsolete.
