### ISSUE TITLE
Option to disable channel point highlighting and /me

### ISSUE THREAD

**Issue by pointydev** [night/BetterTTV#3634]
Heya,

So recently I've found that people are using the newly added channel point highlighting feature that much that it's becoming annoying, so I think an option to disable the highlight client side while retaining the message would be a good idea. Alongside this, a similar option for `/me` highlighting would also fit well.

![](https://pointy.needs-to-s.top/2p6CZKW.png)
![](https://pointy.needs-to-s.top/NvwYa4x.png)

Thanks,
Elliott

**Comment by BravadoRL** [comment]
Agreed. The most annoying feature Twitch has ever made. I'm glad that some streamers disable the feature. but being able to block them from all channels would be nice.

**Comment by billysielu** [comment]
Detail lost from #3702 being closed as a duplicate:
The "Clear My Chat" function does not fully clear the "Redeemed Highlight My Message" messages.
