### ISSUE TITLE
Firefox Emotes menu blank on second tab stream - only favorites emotes displayed

### ISSUE THREAD

**Issue by neotheeone** [night/BetterTTV#3638]
Emotes menu blank on second tab stream - only favorites emotes displayed
Reproduction steps:
1. Open Firefox v69.0.3 or newer version (reproducible on older versions as well)
2. Enter any Twitch stream.
3. Click on Emotes menu button (At the bottom left side of chat - closest to the whispers button)
4. Emotes are displayed as expected.
5. Open a second tab in Firefox.
6. Enter another random Twitch stream.
7. Repeat step #3 (click Emotes menu button)
8. Favorites emotes will show up and maybe some of the top emotes only.
9. In order to fix the view, exit Emotes menu and click the emotes menu button again.
10. Another workaround, scroll up and down on the partly empty space of emotes, until it gets populated gradually with the rest of the emotes.

Please note, when browser enters the first stream, on the first tab, the Emotes menu opens successfully and displays all emotes almost instantly, without the need for all the workarounds that are required on all the next opened tabs/streams.

https://cdn1.imggmi.com/uploads/2019/11/1/7907761601507d9f5e08214b33050076-full.png

Win10 Home 64bit
Firefox 69.0.3 64bit
BTTV for Firefox 7.2.71

Kind regards.

**Comment by night** [comment]
Please try upgrading Firefox to 70+ and seeing if the issues persist. There might be a Firefox bug in your older version that is fixed in the newer version.
