### ISSUE TITLE
Anon Chat not working correctly

### ISSUE THREAD

**Issue by LinkUK** [night/BetterTTV#3639]
When joining a channel, user is visible in chat list. 

Turning Anon Chat off and then back on shows the correct messages in chat (logging out/logging in) and then user dissapears from chat list.

Started a couple of days ago, this has to be done whenever changing channels

**Comment by night** [comment]
I'm not able to reproduce any issues. Can you provide exact reproduction steps?

**Comment by LinkUK** [comment]
Certainly, am still having this issue on Firefox 70.0.1 using BTTV 7.2.71

With Anon Chat turned on, join a channel, "logging you out of chat....welcome to the chat room" is displayed in chat. After a few moments/minutes, user still appears in the chat list. If you change channels, user is still there in the chat list.

Turning Anon Chat off, then back on, seems to resolve this, with the user becoming invisible shortly after. All the correct messages from BTTV are displayed in chat (logging in/out)

The user then seems to stay logged out of chat when changing channels until you close and reopen the browser, at which point the above steps are needed to become "Anon" again

Hope this helps, will try to provide any other information you need. Cheers

**Comment by LinkUK** [comment]
This issue appears to have resolved itself as of today. Not had any issues with Anon chat with any channels. Will close and resubmit if it happens again.
