### ISSUE TITLE
Option for a abnormal latency to broadcaster warning

### ISSUE THREAD

**Issue by pointydev** [night/BetterTTV#3640]
Heya,

So I thought it'd be a good idea to add an option to show some form of warning when the player is too far behind depending on the stream mode (e.g. 40s for normal latency, 10s for low). It gets frustrating opening advanced stats every time I think I'm too far back, so some sort of warning might be useful.

Thanks,
Elliott

**Comment by night** [comment]
it's an interesting idea, but this feels like unneeded bloat. latency exists to prevent buffering, and you wouldn't accrue latency without buffering
