### ISSUE TITLE
Frequent stream VOD freeze caused by Twitch when the user is logged in and possibly exacerbated problems for BTTV users [Chrome, Windows 10]

### ISSUE THREAD

**Issue by thetiby** [night/BetterTTV#3641]
Repro steps:

1. go to https://www.twitch.tv/videos/502461022?t=0h5m40s
2. hover the VOD controls so you can see the seconds
3. at 6:00, the timer, video, and audio stops and resumes a few seconds later, having jumped ahead

I recorded a performance profile in Chrome to debug this and found a BTTV script with a huge overhead. Disabling BTTV and doing the above steps fixed the issue. 

![image](https://user-images.githubusercontent.com/2418978/68093304-f200c200-fe9c-11e9-8a78-712349d46637.png)

I only started noticing these recently and predominantly on this streamer's VOD's, but it might be reproducible with others as well.

I like BTTV, so hopefully, this report is helpful. 

---
Chrome, Version 78.0.3904.70 (Official Build) (64-bit), Windows 10 pro

**Comment by night** [comment]
I'm not sold it's BetterTTV causing these issues. The box you've highlighted shows that function call took 92 microseconds, and BetterTTV does listen to player events in a way that could cause it to be part of a stack trace during player events. If you upload your performance profile I can take a closer look, but I'm unable to reproduce this on that VoD at that timestamp.

**Comment by thetiby** [comment]
Further looking into it, I noticed this similarly strange behavior: when loading the VoD URL in step1 above, it would skip from 5:40 to about 6:00 or even more (7:12, etc).

I tried it in incognito, thinking some other extension was causing it (at this point I had BTTV disabled) and it didn't happen: the VoD started playing from the correct timestamp.

However, once I logged into Twitch in that incognito window, the same skipping behavior happened when reloading the VoD at that timestamp. Thus, I think the underlying issue is with Twitch when a user is logged in.

However, I did try to enable only BTTV in that incognito window and reload the VoD. To my surprise, the VoD froze completely (the page was still responsive) and didn't even resume as it did previously (I was still logged into Twitch). Only after I clicked pause and play did the VoD resume, having skipped a lot. Thus, I think that BTTV has problems caused by an underlying Twitch.tv bug that happens when a user is logged into Chrome.

If you can't repro this one either, please close this issue. It might just be isolated to my system so it doesn't matter.
