### ISSUE TITLE
Auto Expand Followed Channels List - Not working

### ISSUE THREAD

**Issue by BillyCurtis** [night/BetterTTV#3646]
When **Auto Expand Followed Channels List** is enabled and you refresh, it hides the channel list in the side bar.  but if you manually click "Show more" then the following list will come back.

This doesn't happen when viewing the homepage or channel
### Example 
![](https://i.gyazo.com/a4d48f387f9c744658e11b2b67fd504a.gif)

**Comment by night** [comment]
This might actually just be an issue in Twitch's site code. When the page loads we automate clicking on "Show More," so likely us clicking Show More too soon is caused it to render a blank list.

**Comment by lfmnovaes** [comment]
I can confirm the exact same issue on my side too when the option "Auto Expand Followed Channels List — Automatically clicks the "Load More" option for you" is marked as ON.
Using Firefox 71.0b8 (64-bit) at win10.
