### ISSUE TITLE
Suggestion/Request: Have an option to make a certain resolution permanently set.

### ISSUE THREAD

**Issue by IamKilt** [night/BetterTTV#3647]
I like to have twitch on on my second monitor while I do stuff on my first. And when I do that Twitch has this wild idea that I don't want it to be at 720p. So they bump it down to 480. No matter how many times I set it to 720, auto quality turns itself on. is it possible to add in a way to turn auto quality off? Or just let me permanently set my stream at the quality I want? It's real annoying to have to go in and reset the quality every time twitch decides that I should be watching at a lower quality.

**Comment by night** [comment]
this is already built into Twitch's player. if your settings do not persist ensure you do not clear cookies on browser close.
