### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by iAreNubcake** [night/BetterTTV#365]
Certain color combinations are difficult to easily read, and I think adding the ability to define your own styles would be useful. Specifically, when tagged in blackened chat, the background is dark red and the text is black. For people with low contrast sensitivity, it's difficult to quickly read what was said.

Changing the color would help, but I figure it'd make sense to add styling options for common things. Namely text color, highlight color, highlight text color, link color, etc. Having an option for Normal, Dark, and Blackened would be nice.

**Comment by night** [comment]
Blackened chat is only for Chroma-keying chat, and will eventually be phased out. You should only use "DarkenTTV" in the BetterTTV settings, which does not do black on red text, but rather white on red.

**Comment by iAreNubcake** [comment]
Well even without the granular control of controlling specific colors within the app, wouldn't it be rather feasible to use a default stylesheet that can then be edited and used in place of the default? Stylebot/Stylish work to a point, but there are some issues (overriding !important flags, mostly), and that feels like a hackish fix to me anyway.

I wasn't aware that Blackened was being phased out. For now, I'll use Stylebot as I have been, but I feel that being able to edit the stylesheet isn't unreasonable.
