### ISSUE TITLE
[Feature Request] - Popout, Chat, Fetch etc.

### ISSUE THREAD

**Issue by mortyobnoxious** [night/BetterTTV#3651]
Hi, I have a few feature requests, if you consider adding:
- Popping out **player** directly from "live channel card" as in picture below.
- Popping out **chat** directly from "live channel card" as in picture below.
- Fetching direct URL of a stream by using https://pwn.sh/tools/getstream.html API

![image](https://user-images.githubusercontent.com/42044258/68881949-3010a800-071f-11ea-8e3b-c9fe1de31bae.png)

- being able to set width, height and position for popup window would be great:
for example: width=750,height=422,left=900,top=5

**Comment by night** [comment]
thanks for the suggestions, but these seem to be a bit too specific to be useful to most of our users
