### ISSUE TITLE
Paid for pro, money charged, didn't get it.

### ISSUE THREAD

**Issue by JerryTheDoctor** [night/BetterTTV#3653]
Hi there, paid for bttv-pro, money been charged but in the end the message appeared "There was an error processing your payment"

**Comment by Nareese** [comment]
Please use the contact form at https://nightdev.com/contact and select "Billing Issue" for the reason, and supply all of the appropriate details, username, date, time, transaction ids if you have them, etc.  The more information you can provide, the easier it will be for night to look into what happened.
