### ISSUE TITLE
Emotes not showing

### ISSUE THREAD

**Issue by viktorsheesh** [night/BetterTTV#3655]
My BTTV emotes work fine in chat, but they are not showing up in my emote menu, which is pretty annoying. How can I fix this problem? I already reinstalled BTTV.
I'm using Firefox

**Comment by xgerhard** [comment]
Hiya, are you using the BTTV emote menu? You can enable the emote menu in the BTTV settings, you can access it by clicking the smiley icon underneath the chat input field.
