### ISSUE TITLE
Click to Play/Pause option not respecting 'off' for resuming play

### ISSUE THREAD

**Issue by DAOWAce** [night/BetterTTV#3656]
This issue has been annoying me for a while, but right now (as of the last few months) it seems like the "Click to Play/Pause Stream" option only works when pausing the stream, not resuming it.

With the option on, clicking anywhere on the video will pause/play.
With the option off, you must click on the button (or press spacebar) to pause, however **clicking anywhere will still resume the video**.

It used to work properly, but ever since the redesign IIRC it's only half worked.  Didn't see an issue about this specifically.

Just, exceptionally annoying because I click on the video to refocus the window and that causes it to start playing when I don't want it to.

**Comment by night** [comment]
that's how the new twitch player functions, and is not caused by betterttv

**Comment by DAOWAce** [comment]
Then why is the option called "play/pause" instead of just "pause"?

It's clearly not functioning correctly from a user standpoint; both as it's named, and compared to how it used to function before the Twitch redesign/player update.

Hardly a case for an 'invalid' issue unless you're completely unwilling to work on this feature.

If I knew how to do any of this stuff I would've worked around it on my end and submitted a PR with the fix.
