### ISSUE TITLE
Hiding whispers doesn't remove the space under the video player in theatre mode

### ISSUE THREAD

**Issue by TR3MIC** [night/BetterTTV#3658]
### Summary
When hiding whispers, the space under the video player in theatre mode doesn't disappear anymore. The CSS rule in `src/modules/conversations/style.css` needs to be updated to reflect the new class name and DOM (apply the `bottom: 0rem;` to `.highwind-video-player__container--theatre`).

### Detail story
When hiding whispers, I was thinking why the spare space under the video player in theatre mode wouldn't be removed. I though about suggesting the idea, but before doing that I took a look at the code. I found out that it was already present in the CSS file, but the class name of the player is wrong and the DOM has changed a little (Twitch probably changed it).

It's now `.highwind-video-player__container--theatre` directly. The `bottom: 0rem;` is still valid.

**Comment by Kaisirak** [comment]
This issue has surfaced again.

And .video-player__container--theatre-whispers is set to 4rem instead of 0rem
