### ISSUE TITLE
Toggling Twitch's dark theme does not update BTTV setting

### ISSUE THREAD

**Issue by Stevoisiak** [night/BetterTTV#3662]
**Issue:**
If dark theme is enabled or disabled through Twitch's profile menu, the dark theme setting in BTTV will not be updated.

**System:**
- Windows 7 Professional, Service Pack 1 (64-bit)
- Firefox 70.0.1
- BetterTTV 7.2.71

**Steps to reproduce:**
1. Open https://www.twitch.tv/ while logged in.
2. Have dark theme disabled in both BetterTTV settings & the Twitch profile menu.
3. Click top-right profile icon, then toggle Twitch's dark theme on.
4. Refresh page.

**Expected Results:**
Both BetterTTV & Twitch list dark theme as on.

**Actual Results:**
BetterTTV lists dark theme as off. Twitch lists dark theme as on.

**Screenshot:**
![BTTV dark theme off, Twitch dark theme on. Page uses dark theme.](https://user-images.githubusercontent.com/1330770/69659548-6bc73e00-104c-11ea-9374-d59b611fcc44.png)

**Additional Details:**
- The bug seems dependent on which setting was changed last.
  - If BetterTTV's dark theme is changed, Twitch's setting will be updated after refreshing.
  - If Twitch's dark theme is changed, BetterTTV's setting will not be updated after refreshing.
- If both BTTV & Twitch's settings are changed, (in that order), they will [cancel each other out](https://user-images.githubusercontent.com/1330770/69659928-3ec75b00-104d-11ea-8936-3ced4fcdbeff.png) until the page is refreshed.

**Comment by night** [comment]
The dark theme setting is synced between Twitch and BetterTTV. If you toggle Twitch's it will toggle BetterTTV's, and if you toggle BetterTTV's it will toggle Twitch's.

When you toggle dark theme on Twitch the BetterTTV setting toggle doesn't update until the page is refreshed. This is a minor display bug and imho isn't worth the trouble of fixing right now.

**Comment by Stevoisiak** [comment]
> When you toggle dark theme on Twitch the BetterTTV setting toggle doesn't update until the page is refreshed.

The bug I am reporting is that the BetterTTV setting isn't updating, even after refreshing the page.

**Comment by night** [comment]
@Stevoisiak the BetterTTV setting does update. can you provide repro steps proving otherwise?
