### ISSUE TITLE
Feature Req: Ability to sort followed ch sidebar in reverse order.

### ISSUE THREAD

**Issue by firereverie** [night/BetterTTV#3665]
Hopefully this is the right place to put this, if not I apologize in advance and I'm sure someone will correct me. 

Anywho, just a feature request, pretty much as the title states; have the ability to sort the followed channels sidebar in reverse order, so the followed channels with the fewest viewers appear at the top. 

Thanks!
-fire

**Comment by night** [comment]
it isn't possible to reverse sort this list without changing the renderer of this component, which BetterTTV will not do (we make surface level styling changes, not drastic functionality changes)
