### ISSUE TITLE
Disable Host Mode — Disables hosted channels on Twitch - not working bug

### ISSUE THREAD

**Issue by XykoZ** [night/BetterTTV#3666]
Setting Disable Host Mode to On, does not disable host mode forwarding.
This used to work. Currently not working in v7.2.71 and Chrome 78.0.3904.97
I note this seemed to have appeared previously https://github.com/night/BetterTTV/issues/3305

**Comment by Bacnaw** [comment]
I have the exact same problem. Anoying as hell.
Version: 
Version 7.2.72 (Dec 4, 2019)
fixes #3636
fixes #3658
updates hide chat header setting text
updates holiday emotes to support native Twitch emotes

**Comment by diredesire** [comment]
Same for me
Version: 7.2.72
FireFox 71.0

**Comment by night** [comment]
I'm not able to reproduce this. It may have been fixed with https://github.com/night/BetterTTV/commit/801b18b689504030f846ae0b47f4df7ce4149148
