### ISSUE TITLE
Badge-free chat mode

### ISSUE THREAD

**Issue by olo2552** [night/betterttv#3667]
The fact, that everyone achieves more and more emotes in front of their nickname concerns me more and more as badges gets easier and easier to get.

For me, the ideal solution would be to leave mod & streamer emote as they were before, but remove subs / vips / cherrers etc. 

Are we interested to provide distraction-free (read badge-free) chat mode setting? I could code this up, since it could be easy first PR and wouldn't require much project-specific knowledge, while giving value, while giving value on the channels with smaller audience, where percentage 'special' viewers is very high.

**Comment by ZeldaZach** [comment]
Might be nice to have a config option to indicate which badge(s) to block and/or show (not sure if a white list or black list would be more appropriate here).
