### ISSUE TITLE
Option to disable automatic notifications when following

### ISSUE THREAD

**Issue by pointydev** [night/BetterTTV#3668]
Heya,

As you know, Twitch automatically enables global notifications when you start following a channel. I think it might be a good idea to add a feature that allows you to disable this so that you can selectively turn on notifications for channels you like. I see a real application for this as I know a lot of people are in a similar predicament.

Thanks,
Elliott

**Comment by IVLeague** [comment]
You can already just click the bell right after you follow and you won't get notifications. You can also tailor notification settings in your twitch settings. Such as where you get them like via email, app, on twitch itself, or smart notifications which will only go off wherever you're active.

**Comment by pointydev** [comment]
@IVLeague 
> You can already just click the bell right after you follow and you won't get notifications.

I know that, and a feature like this would automate it, just like a lot of the other automations in BTTV.

**Comment by night** [comment]
I actually think the bell icon Twitch has works good enough. I don't really see a need to automate it.
