### ISSUE TITLE
Disable Homepage Autoplay no longer working

### ISSUE THREAD

**Issue by Cavey74** [night/BetterTTV#3669]
I am using version 7.2.72 of BTTV on version 71.0 of Firefox and 78.0.3904.108 of Chrome and the disable homepage autoplay setting is no longer working in either of them.

**Comment by tntc4** [comment]
I'm using v7.2.72 of BTTV for Chrome and this option is no longer works.

**Comment by Evolvedruid** [comment]
Same issue for me , v7.2.72. please fix asap

**Comment by lilchina** [comment]
Same here BetterTTV v7.2.72 Disable Homepage Autoplay doesn't work for Firefox version 71.0
