### ISSUE TITLE
Left side chat is now underneath channel list

### ISSUE THREAD

**Issue by MGough** [night/BetterTTV#3670]
The chat is moved to the left side, however the channel list stays on the left and sits above the chat (z-index), meaning that it covers part of the chat.

Looks like it's just related to a new Twitch design.

Previously I think that it swapped the chat and the channel list?

Browser: Firefox 71.0
BetterTTV Version:  7.2.72

**Comment by night** [comment]
I'm not able to reproduce this issue. Twitch may have fixed it.

**Comment by justnice980** [comment]
It's also been happening to me for over a week. I just turned the feature off in the meantime. Screenshot attached. [https://imgur.com/yzXRBDE](url)

**Comment by MGough** [comment]
Yeah I'm seeing the same as @justnice980 .

Is there any more info that might be useful to you ( @night ) in order to try and reproduce it? Of course it's possible twitch are just serving us a different UI as part of some kind of A/B test or similar

**Comment by MGough** [comment]
My knowledge of the complex CSS used is lacking, however I have found that the `side-nav` class does which has a CSS property set by BetterTTV doesn't appear to work anymore due to it not being a flex element:
> order has no effect on this element since it’s not a flex item.
> Try adding display:flex or display:inline-flex to the element’s parent

That appears to be preventing it from being moved to the right side of the screen using `order: 3;` here https://github.com/night/BetterTTV/blob/master/src/modules/chat_left_side/style.css#L10
