### ISSUE TITLE
bug da tela pequena

### ISSUE THREAD

**Issue by akarinnp** [night/BetterTTV#3673]
Ao pressionar o BetterTTV Settings na www.twich.tv, ela não abre por completo tendo uma minuscula tela, impossibilitando seu uso. Já tentei de tudo mas não consigo arrumar.
![image](https://user-images.githubusercontent.com/58597314/70326700-ea259c00-1813-11ea-98bb-d8fd86c68648.png)

**Comment by night** [comment]
You need to zoom in the page, or reset page zoom to the default.
