### ISSUE TITLE
Twitch TV came up with a new annoying way to annoy us VOD please help!

### ISSUE THREAD

**Issue by Eneitilyn** [night/BetterTTV#3683]
Just check out this picture... ["Twitch bs"](https://i.imgur.com/3KE2YTI.jpg) They are automatically playing VODs without ANY consent from the viewers just like how youtube used to do now I dont mind this kind of thing as long as there is some kind of option to disable this absolutely GENIUS "feature" of twitch but the button for it is NOWHERE to be found in the interface and I got no other choice but to simply either pause before the very end of the VOD or just dont ever leave my PC while having a VOD playing in the background otherwise its gonna automticaly go through the whole catalog of VOD's of a streamer by itself =,=

**Comment by night** [comment]
There's already a setting for this called "Disable VoD Recommendation Autoplay"
