### ISSUE TITLE
Click to Play/Pause Stream not working 

### ISSUE THREAD

**Issue by jt415gz** [night/BetterTTV#3684]
'Click to Play/Pause Stream' does not function on Firefox 71.0 and on Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by khandy77** [comment]
Can confirm on Mac and PC.

**Comment by jBbL81** [comment]
Not working for me as well.

**Comment by night** [comment]
fixed by 801b18b689504030f846ae0b47f4df7ce4149148
