### ISSUE TITLE
bttv auto expand doesnt work, and vod auto play disable doesnt work

### ISSUE THREAD

**Issue by dragonema** [night/BetterTTV#3686]
Auto Expand Followed Channels List colapses and doesnt show anything, basaclly it works the oposite way it should. And vod auto play disable does not work at all.

**Comment by xgerhard** [comment]
Hiya, this was fixed yesterday, so make sure to check you have the latest version: 7.2.73 (check the about tab in your BTTV settings).
You can also try to clear your cookies & cache to see if that fixes it.
