### ISSUE TITLE
Emote menu closing after selecting one emote

### ISSUE THREAD

**Issue by IVLeague** [night/BetterTTV#3689]
Can we have it so the emote menu does not close after clicking on one emote? This is such a pain and I feel it contributes to me not using the BTTV emote menu anywhere near as much as I'd like.

**Comment by Nareese** [comment]
In the lower right corner of the menu is a "pin" icon.  Click it, and the menu will remain open until you unclick the pin and click another emote, or click the emote menu button itself.

**Comment by IVLeague** [comment]
Thank you!
