### ISSUE TITLE
BTTV bug

### ISSUE THREAD

**Issue by foreveranonymous** [night/BetterTTV#369]
I have had "Robot Emoticons" turned off for quite some time, but at complete random a few months ago the JTV monkey emotes came back. I never turned the JTV emotes on, and it's still not on, but they're showing up in chat anyway.

**Comment by night** [comment]
JTV monkey emotes are blue. If you are seeing brown monkeys, those are turbo emotes which we will not block.

I cannot reproduce a bug, so make sure you actually have the setting toggled properly. On = Robot Emoticons, Off = Monkey Emoticons
