### ISSUE TITLE
[Feature Request] Add option to auto expand followed channels sidebar

### ISSUE THREAD

**Issue by Hiroo17** [night/BetterTTV#3690]
I don't mean the "Auto Expand Followed Channels List — Automatically clicks the "Load More" option for you" feature, but the actual sidebar.

Thanks.

**Comment by Rysters21** [comment]
I want this option so bad. I hate clicking the "Keep Expanded" button anytime I come back to twitch or when I refresh.

**Comment by night** [comment]
I'm not seeing this behavior locally, and the position I configure persists across sessions. Have you tried clearing your cookies/cache?

**Comment by Hiroo17** [comment]
I think Twitch fixed it themselves.
