### ISSUE TITLE
Left side chat is partially blocked

### ISSUE THREAD

**Issue by PairedPrototype** [night/BetterTTV#3691]
Since Twitch changed some stuff on the site a week or so ago, the channel list overlays about 50px of the chat when using Left Side Chat.
![image](https://user-images.githubusercontent.com/16809256/70857019-1eb5e980-1edf-11ea-9e94-662fd7e4e8fc.png)

**Comment by xgerhard** [comment]
Hiya, have you tried clearing your cache/cookies this appears to be fixed already.

**Comment by PairedPrototype** [comment]
It did try that, but it did nothing at first. Turns out I left it on the clear cache from the last 24 hours. Changing that to a little later appears to have fixed it! Thanks 😊

I also wasn't aware Chrome cached extension styles 🤔 Might be a good idea to get a cache-busting method put into the build process.
