### ISSUE TITLE
BetterTTV Logging In

### ISSUE THREAD

**Issue by EloraHD** [night/BetterTTV#3697]
So I was enabling BetterTTV on streamlabs OBS so some of my friends could use it but it doesn't seem to be working, It does on the Twitch website itself but not OBS. I log into twitch and go to better ttv settings and it tells me to log in, I click log in and it ask me to authorize the login and I am instantly in, but when I try logging in better ttv on streamlabs obs, it just stays on "LOGGING IN" and loading infinitely. No option to Authorize anything.  https://gyazo.com/ec4e2b945a95e89421f5111e7f3050a0

**Comment by night** [comment]
Do you use Kaspersky? If so, we've had multiple reports that they are breaking our login flow. You may need to disable it to login.

**Comment by EloraHD** [comment]
I am not using Kaspersky
