### ISSUE TITLE
Disable auto play is just not working.

### ISSUE THREAD

**Issue by Shadybliss** [night/BetterTTV#3700]
I've tried installing the app a couple times now. It just doesn't want to stop the auto play videos on the home page.

It will instead stop the stream im trying to watch when i first load it up and i have to press play a few times before it stops trying to auto stop it lol.

**Comment by night** [comment]
I'm not able to reproduce any issues with this feature. Can you provide reproducible steps showing it's broken?

**Comment by Shadybliss** [comment]
Hey, i was in the middle of making a video for showing the issue. But i then noticed there was an update to the extension that fixed this issue. I have since updated it and its working as intended now. Sorry to bother you!
