### ISSUE TITLE
[Bug] Import function doesn't import blacklist and highlight keywords

### ISSUE THREAD

**Issue by BradyThe** [night/BetterTTV#371]
Basically what topics says. They backup file contains those information, but doesn't import those. I have to open the file manually and c&p it.

**Comment by night** [comment]
Please upload your settings file to https://gist.github.com/ and post a link here. I suspect there's an issue in the file's formatting, rather than an issue with the import script.

**Comment by BradyThe** [comment]
It seems indeed to be a problem with the file's formatting. I created the backup file a while back, decided to test it with a new one, and of course it works now. My apologies.
