### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by mephistophiel** [night/BetterTTV#3710]
I  cant login better ttv  every time I tried on chrome browser when i connect with my twitch account it keeps freezing on logging in screen and just loading scroll keeps turning. what can i do ? another browsers same but my friends or another guys do not have this kind of problems? my adblock isnt open and vpn either

**Comment by xgerhard** [comment]
Please see this comment: https://github.com/night/BetterTTV/issues/3697#issuecomment-568562114

**Comment by mephistophiel** [comment]
> Please see this comment: [#3697 (comment)](https://github.com/night/BetterTTV/issues/3697#issuecomment-568562114)

Im not using Kaspersky

**Comment by night** [comment]
Try using a different device and see if the issues persist. It could be due to some browser extension or firewall/internet security you use.
