### ISSUE TITLE
1st badge not registering as a subscriber

### ISSUE THREAD

**Issue by Siulaim** [night/BetterTTV#3711]
People with the 1st badge don't show up in chat if you have localsub mode on. Also worth noting, the user in this example was a moderator, so if someone has localsub on, they also won't see messages from mods or bots (I'm guessing) that aren't non-first badge subs.

![local sub issue hawkz](https://user-images.githubusercontent.com/59422383/71646752-58de0400-2cb1-11ea-8ca4-d5f9c7836898.png)
![local sub issue siu](https://user-images.githubusercontent.com/59422383/71646753-58de0400-2cb1-11ea-88f2-0e368ac1624f.PNG)

**Comment by night** [comment]
fixed by bfaab26e7a52a424f563bd77346f45f409b07c11
