### ISSUE TITLE
Hide hype train

### ISSUE THREAD

**Issue by sewil** [night/BetterTTV#3715]
A new feature was released on Twitch recently called hype train which I guess is a way to try and make viewers to donate more for a random emote. There seems to be no limit how many times this can be triggered and it covers about 30% of the chat and is very distracting. A setting to hide this feature would be much obliged.

**Comment by NashwanBeiruti** [comment]
Can we please get this new feature added. It really takes away from the chat experience

**Comment by tzx613** [comment]
Please, for the love of god, that hype train banner is so horribly distracting, annoying and dumb. I need it gone

**Comment by gertjanmaas** [comment]
Just looked at the html code of a hype train popup. It uses the same popup as the Community Gift Chest, which already has a pull request ( #3705 ). Can we get this pull requests approved asap?
