### ISSUE TITLE
[bug] Slowmode countdown interferes with channel points UI when the emote menu module is enabled

### ISSUE THREAD

**Issue by pointydev** [night/betterttv#3717]
Heya,

When the slowmode countdown is visible and you have the BTTV emote menu enabled (so the icon is visible), if you get channel points or a bonus is available, this visual bug happens:

![](https://pointy.needs-to-s.top/5e8ToWY.png)
Thanks,
Elliott

**Comment by night** [comment]
i can't seem to reproduce this. please provide steps to reproduce this behavior
