### ISSUE TITLE
Move chat under the stream for a bigger window in theater mode.

### ISSUE THREAD

**Issue by Deetrox** [night/BetterTTV#372]
One con that I've found of twitch's theater mode is the black bars above and below the stream when you're not full screen. 
Like this: http://i.imgur.com/emLPSm7.png4

When you minimize the chat the stream gets bigger, albeit still with black bars.

Like this: http://i.imgur.com/GHUFQ1x.jpg4

But if you slid the stream to the top, and put the chat underneath it, the window would be perfect.

If the Betterttv Dev could add some options to the theater mode that would make it possible that would be amazing.

**Comment by night** [comment]
There's no way to change black boxes, sorry. You can size the window to be 16:9 if you do not want to see them.
