### ISSUE TITLE
Emotes do not show properly in chat and only show their input command.

### ISSUE THREAD

**Issue by Fyuukra** [night/BetterTTV#3721]
I fell asleep on my chair with Twitch open in my background. Now some emotes appear as their input instead of being shown the image or gif. This issue probably occurred during Xmas but I'm not entirely sure at this point.
![Screenshot (4)](https://user-images.githubusercontent.com/59895902/72385865-f55aca00-36e5-11ea-9b0c-fb8dfdb704a4.png)

I have tried the general solutions and tried to search for one, I don't think this is a settings bug though.

**Comment by xgerhard** [comment]
Hiya, have you checked your settings and made sure the emote settings are enabled (especially the FFZ emote setting, since it looks like these are all FFZ emotes?).
