### ISSUE TITLE
Automatic theatre mode doesn't work in Edge

### ISSUE THREAD

**Issue by Cyberbeni** [night/BetterTTV#3722]
Edge Version 79.0.309.65 (Official build) (64-bit)
Windows 10 Home, 1909, 18363.535

**Comment by night** [comment]
im not able to reproduce this with the latest code we have in our repo. might be related to b410ed0cfcc9a9d599ef510712220d8af1471bf6

**Comment by Cyberbeni** [comment]
Yeah, it works correctly in 7.2.75 for me too.
