### ISSUE TITLE
[bug] Unintended behavior with the module to hide community highlights

### ISSUE THREAD

**Issue by JorgWieme** [night/BetterTTV#3728]
This may or may not be intended, but I assume this was not intended. When enabling the module to hide community highlights, the twitch build-in [polls ](https://help.twitch.tv/s/article/how-to-use-polls)are no longer visible. You cannot vote nor see the text, the only thing that is left is an empty widget. 

This was added in #3705

**Comment by night** [comment]
This is intended. All community toasts are hidden with this enabled, and because of the generic naming scheme Twitch uses for these we are not able to unhide specific ones.
