### ISSUE TITLE
I cant remove emotes cause they got removed or reported

### ISSUE THREAD

**Issue by MTDJuanMaa** [night/BetterTTV#3729]
im a editor on pokelawls channel and these 4 emotes count as a slot i cant remove them help 
https://betterttv.com/emotes/5e2075ec88e62a5f14dc9ae7
https://betterttv.com/emotes/5e13117db974112104802939
https://betterttv.com/emotes/5de4c197e7df1277b606c5c2
https://betterttv.com/emotes/5d6ee3aaa32edb714a9ddd3e

**Comment by sasukeruless** [comment]
i got the same problem no answer since 9 days..
