### ISSUE TITLE
Bttv host mode still not working.... 

### ISSUE THREAD

**Issue by Masterokay** [night/BetterTTV#3735]
I've noticed this problem is around art least 5-6 year's and I still didnt see a fix. 
It's the same problem since 2015. 
Bttv disabling host mode works maybe 1 day at most and then it breaks. 
Sometimes disabling and re enabling it seems to work. 
Other times it doesn't. 

Has anybody found anything ?

**Comment by night** [comment]
disabling host mode is best effort and will never work 100% of the time due to the nature of how Twitch's website work.
