### ISSUE TITLE
"hide community highlights" don't work ?

### ISSUE THREAD

**Issue by Monkey151546** [night/BetterTTV#3736]
it doesn't seem to work for me even though i have it enabled , i still see the highlight message "Redeemed Highlight My Message 100" and then highlighted message. i tried turning it off and back on while looking at the chat and nothing happens ,the highlighted message is still there and so it the redeem message. is it happening to anyone else ?

**Comment by Nareese** [comment]
The `Hide Community Highlights` setting hides the "Hype Train", the dialog that appears at the top of the chat window when those events are active (and a few other related things that use that same top of chat dialog box).  To hide the highlighted "redeemed" rewards, the setting you want is `Disable Channel Points Message Highlights`

**Comment by Monkey151546** [comment]
ooh i didn't  see that one ! thank you :)
