### ISSUE TITLE
Twitch whispers won't update without refresh

### ISSUE THREAD

**Issue by InvoluntaryLag** [night/BetterTTV#3737]
For some reason starting around a month ago my twitch whispers won't update unless I refresh the page or open twitch in a new tab. I am not sure if this is a Twitch issue or BetterTTV issue so submitting this to both.

Browser: Chrome
Extensions: Nimbus Screenshot and Honey.
I also have FrankerFaceZ, and Ecosia but I was seeing this issue before I added them.

**Comment by night** [comment]
I'm not able to reproduce any issues with BetterTTV and whispers. Have you tried disabling extensions one-by-one and seeing if the issue persists?
