### ISSUE TITLE
fuzzy autocomplete

### ISSUE THREAD

**Issue by Brink2Three** [night/betterttv#3738]
Hey all! 

I'm essentially looking to simplify autocompleting people who's names have difficult to decipher beginnings to their name (for example, lnamepersonl vs InamepersonI look the same, but one is a capital i, and the other is a lowercase L. I'd like to be able to "namep" and have their name show as an autocomplete option. 

Thanks you guys! Y'all make modding chats a lot easier. :)

**Comment by night** [comment]
Thanks for the request. Because we leverage Twitch's autocomplete system for mentioning other users, we are not able to support fuzzy matching within their system. As an alternative, you can always doubleclick on a user's name in chat to mention them quickly
