### ISSUE TITLE
[Feature Request] Mute an user for the current session (or X min)

### ISSUE THREAD

**Issue by pmrt** [night/betterttv#3739]
I've often come across situations where I don't want to see messages from a particular user because he's being a pain in the ass or he's spamming 'X' question over and over again but I don't want to block him, all I want is to mute the user for the current session or for the next 10 minutes.

IMO a feature to block users, store the list and then unblock them in the next session (ie. muting) or a watcher to check every X time for the expired blocked users would be really interesting.

**Comment by night** [comment]
you can already ignore users from chat with `/ignore`, but it does not have a timeout. regardless, you could take an approach such that you occasionally prune your ignores list.
