### ISSUE TITLE
[Bug] Name edit button has disappeared

### ISSUE THREAD

**Issue by Dragoonseal** [night/BetterTTV#3740]
**Technical**

OS: Windows 7
Browser: Google Chrome Version 79.0.3845.130 (Official build) (64-bit)

**Description**

The button next to people's names on Mod Cards, used to edit names, has disappeared. Had someone else verify it's gone for them too.

It's incredibly useful for moderation purposes to keep track of certain people, I'd love to have it back.

**Comment by DrArmageddon24** [comment]
I noticed that too. We need this

**Comment by Dragoonseal** [comment]
I didn't notice right away, but there's another Mod Card feature that disappeared at the same time as the name edit button. The viewer count and total channel view numbers no longer show up below the profile picture.

Those were helpful for being able verify official channels/streamers, and get an idea of their size.
