### ISSUE TITLE
[Bug] Click to Play/Pause Stream not working

### ISSUE THREAD

**Issue by cliffordboulton** [night/BetterTTV#3750]
Noticed this since Wednesday, 5th Feburary.
Browser: Chrome Version 80.0.3987.87 (Official Build) (64-bit)
Chrome did update on Thursday 6th as well. Re-installing the extension didn't help.

**Comment by night** [comment]
This is already fixed but chrome has not approved the extension update. You can use another browser like Firefox if you need the update now.
