### ISSUE TITLE
[Feature Request] Allow highlighting of specific usernames

### ISSUE THREAD

**Issue by VoidRaven42** [night/BetterTTV#3752]
I feel the ability to highlight specific users in chat for moderation purposes (similar to highlight words) would be. I understand this may not be useful for everyone, but in chats where you want to focus on the stream, highlighting users who have a history of being disruptive would be useful.

**Comment by Nareese** [comment]
The highlight feature already supports username highlighting.  From the text on the `Set Highlight Keywords` dialog:

`Use spaces in the field to specify multiple keywords. Place {} around a set of words to form a phrase, <> inside the {} to use exact search, and () around a single word to specify a username. Wildcards (*) are supported.`

So `(Username)` will highlight messages from Username.
