### ISSUE TITLE
No BetterTTV emotes

### ISSUE THREAD

**Issue by NightLift** [night/BetterTTV#3755]
Hi, I've got no BetterTTV emotes showing anywhere in my emote menu. 

Got BetterTTV Emotes enabled
       BetterTTV GIF emotes enabled
       Emote menu enabled
       FrankerFaceZ emotes disabled (enabled doesn't change anything)

I'm running the 7.2.75 version on Firefox. Uninstalling/Reinstalling doesn't change anything.

Thank you for your time !

**Comment by night** [comment]
What emote menu are you checking? Emotes only appear in our emote menu, not Twitch's.
