### ISSUE TITLE
[Feature Request] Increase old Chat messages

### ISSUE THREAD

**Issue by Berndlauerbach** [night/BetterTTV#3756]
Can u make the Twitch-Chat be scrollable for longer time or keep only the messages from and directed to one for a longer time?

**Comment by Nareese** [comment]
Twitch does not expose any method on their chat client for us to set the amount of scrollback history, and there is no way for us to prevent (ie. preserve) messages from being deleted when they reach the top of the scrollback, so unfortunately, there is no way for us to implement these features.
