### ISSUE TITLE
Emote is being wrongly detected as duplicate emote 

### ISSUE THREAD

**Issue by Nnoggie** [night/BetterTTV#3757]
Im trying to upload a gif emote to bttv but when i try it gives me this error:
https://cdn.discordapp.com/attachments/412878982053101589/678611824685482004/bh4N2IM.png
The emote i want to upload:
https://cdn.discordapp.com/emojis/671666082502672384.gif?v=1
The emote that it supposedly is a duplicate of:
https://betterttv.com/emotes/5b37cc1805e329206af6de84

**Comment by night** [comment]
we tweaked the upload system to improve duplicate detections. this should now be fixed.
