### ISSUE TITLE
Hanging on Logging In via Streamlabs

### ISSUE THREAD

**Issue by kngklla** [night/BetterTTV#3766]
When inside of the BetterTTV settings Channel tab, I click login and it hangs on Logging In.

**Comment by xgerhard** [comment]
Do you use Kasperspy by change, try disabling it. 

If that doesn't work, try accessing BTTV through your regular browser, if that works then there isn't much we can do.
Also you can enable BTTV emotes in Streamlabs OBS through: setting -> appearance 
You only need to access the BTTV website to manage emotes.

**Comment by night** [comment]
This is because Streamlabs is not allowing our login popup. This is their issue, not ours. You can use actual OBS instead (instead of Streamlabs' variant), as they do support our popups natively
