### ISSUE TITLE
[Feature Request] Moderation enhancements

### ISSUE THREAD

**Issue by Dragoonseal** [night/BetterTTV#3770]
In no particular order, various issues that I run into while modding that I'd love to see improvements to:

**1) @ Autocomplete for sub notifications**
Normally when a subscriber or gifted sub is announced in chat the names get added to the @ autocomplete list. Which is great, makes it easy to greet them. But Twitch has new announcements that don't trigger names being added to the autocomplete, making it a pain to @ them. The three messages I've seen look like this:
_Person1 is continuing the Gift Sub they got from Person2!
Person1 Extended their Tier 1 subscription through April!
Person1 Converted from a Twitch Prime sub to a Tier 1 sub!_

**2) Mod cards open where ever you clicked the name**
Mod cards constantly shift position, opening up where your mouse is when you click a name. Often this is at the bottom or middle of the page when clicking a recent new message. This leads to new messages getting covered and mod cards half way off the bottom of the screen. So you're constantly having drag mod cards to the top of the screen all the time, especially when checking chat history. It gets super frustrating.

It would be a huge help if Mod cards opened up at the top of the page by default or at the location you last dragged a Mod card to. Similar to how the cards open when using the /user command.

**3) Highlighting names on Mod cards is super fiddly**
Maybe I'm nitpicking on this one, put I'm constantly copy/pasting names while moderating and it's surprisingly fiddly and hard to do from Mod cards. You can't click on the name at the top of the Mod card because that links you to the channel. You can't click and drag over the name either since it just drags the link around. You can't click and drag in front of, after, above, or under the name because that just drags the Mod card around. If you're not a mod you can't click and drag on or around names in BTTV's Mod card chat log drop down (you can't highlight/copy ANY of the log text, annoyingly), that just drags the card around.

The only two ways I can manage to:
If you ARE a mod then you can actually highlight name/text inside of Twitch's drop down logs.
Or, there's about 5 pixels just above names on Mod cards that you CAN click on normally, which lets you drag and highlight the name, this is about the only reliable way to highlight names for copy/pasting, and has an annoyingly small margin of error.

**4) The rename button on Mod cards can be hidden if a Twitch user has too long of a name.**
If their name is too long then the rename button can either get hidden behind the popout/close buttons, or just get pushed off the Mod card entirely. This can be gotten around by highlighting the name (which again, is fiddly) and then pressing Tab twice.

**5) The rename button freezes the stream**
This also applies to the "Set Blacklist keywords," "Set Highlight Keywords," "Set Font," and "Set Font Size" buttons. Pressing any of them brings up a centered text input panel, and the stream stops buffering once they do. Once the buffer runs out (which can happen within 0.5 of a second) the stream freezes and won't continue until the text input panel is closed. And once the panel is closed the stream starts playing again with delay equal to how long you had the text panel open. If you had the panel open a minute, now you have 1 minute stream delay, so you need to pause/play to catch up. Additionally, often you close the panel the stream glitches and hangs indefinitely, again forcing a pause/play.

So the last 2/3 issues combine to be a nuisance because renaming people turns out to be one of the most underlooked but _most_ used and powerful tool I use as a mod. I use it to add tags to people's names so they are easy to notice in a busy chat. Things like Person1 [Troublemaker], Person2 [Official Dev], Person3 [Beggar], Person4 [LAST CHANCE], etc. Lets me easily keep track of anyone that needs more eyes on.

So typically this goes like: Click a name, drag the Mod card to the top of the screen, copy the name after some fiddling, paste the name somewhere and edit a tag onto the end of the name, copy the new name + tag, press the rename button on the Mod card, paste and press enter quickly to hopefully avoid the stream pausing/freezing. The process is so unnecessarily time consuming and mechanically demanding.

It would be a **huge** boon if the name edit button 1)Didn't freeze the stream and 2)Autofilled their name into the text panel and not force us to copy/paste it in.

Another enhancement that would be a big help would be if Moderators could @Chat, @Everyone, or something similar and it highlighted the @ for everyone (everyone that has BTTV at least). It's annoying that Twitch doesn't have a feature like this built in, but I'll take what I can get.

Sorry this was long. Thanks for humoring my ranting.

**Comment by night** [comment]
Apologies for the delay in response. Please split each of these up into individual feature requests so we can track them separately.
