### ISSUE TITLE
"Hide Offline Followed Channels" doesn't work

### ISSUE THREAD

**Issue by barbaduk** [night/BetterTTV#3772]
This feature is just not working: Hide Offline Followed Channels — Removes offline followed channels in the sidebar
FF 73.0.1

**Comment by Theonefoster** [comment]
Same here. Offline followed channels are always visible regardless of the setting. 

Toggling it off/on and reloading doesn't help either. 

Firefox 73.0.1

**Comment by Theonefoster** [comment]
Update on 10th of March (7.2.76) has resolved this for me.

**Comment by barbaduk** [comment]
> 
> 
> Update on 10th of March (7.2.76) has resolved this for me.

Not for me

**Comment by night** [comment]
I'm not able to reproduce issues with this feature. Please provide steps to reproduce this issue.
