### ISSUE TITLE
bttv emote menu not loading for firefox.

### ISSUE THREAD

**Issue by ennui1f** [night/BetterTTV#3775]
I know this has been asked and resolved before but im having major trouble trying to fix the issue.
I reinstalled firefox, the bttv extension. I made sure the BTTV emotes/gif emotes were enabled in the settings. I cleared my cookies and cache(which i believed caused the problem in the first place).
i opened my console and i see this error 
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://50ab09b9-1bf0-4b0f-b890-09fe5431ab5c/betterttv.js
Source Map URL: betterttv.js.map.

From here i don't understand how to fix it. i read through about 8 forums on how to fix Source map errors but i just couldn't wrap my head around how to execute it. I'm not even sure that's the correct error for why the BTTV emote list icon isn't showing, but it's the only one i saw in the console that had "BTTV" in the warning log. 
I'd appreciate any help and thank you in advance.

**Comment by night** [comment]
Source maps errors are not an actual error occurring, and can be ignored. You probably just need to enable the "Emote Menu" setting in the BetterTTV settings.

**Comment by ennui1f** [comment]
Thanks for disregarding everything i said. You dont think i checked that already?
how about not being a pos and assuming i didnt check the most obvious thing.
And your the DEV? 
hecking asshole.
