### ISSUE TITLE
Resurface of issue #3658

### ISSUE THREAD

**Issue by Magpiiez** [night/BetterTTV#3776]
Not sure whether you get notifications on previously closed issues or not, so feel free to close if you do and you're already aware.

Issue [#3658](https://github.com/night/BetterTTV/issues/3658) (Hiding whispers doesn't remove the space under the video player in theatre mode) seems to have resurfaced after the latest version 7.2.75.

Kaisirak [commented](https://github.com/night/BetterTTV/issues/3658#issuecomment-584294970) with some additional info too.

Hope this info helps

**Comment by night** [comment]
This is no longer a BetterTTV issue, but rather a Twitch bug. BetterTTV no longer has the option to autohide the whispers icon, since Twitch moved it to the upper right of the page.
