### ISSUE TITLE
BTTV no longer working

### ISSUE THREAD

**Issue by breon** [night/BetterTTV#3778]
I noticed that my custom font size wasn't working, then I noticed that BTTV wasn't in my twitch options. Chrome did update today. I'm not sure if this is a chrome issue or twitch issue. BTTV hasn't had a release since Feb 7, so it's probably not release issue with BTTV.

Chrome `Version 80.0.3987.132 (Official Build) (64-bit)`

![Screen Shot 2020-03-09 at 4 26 19 PM](https://user-images.githubusercontent.com/183894/76259045-c747c100-6222-11ea-9305-c1aa719c7121.png)

**Comment by vesterlay** [comment]
Same on firefox

**Comment by joko100200** [comment]
Same here i refreshed and it disappeared from the settings popup.

**Comment by pointydev** [comment]
Also tested with `BetterTTV 7.2.75 on Chrome Dev 82.0.4077.0`, guessing a Twitch update broke something.

**Comment by Vilelandre** [comment]
Same problem on Firefox

**Comment by night** [comment]
this is fixed as of version 7.2.76. update your browser extensions. chrome update is pending chrome webstore review.

**Comment by ijjop** [comment]
> this is fixed as of version 7.2.76. update your browser extensions. chrome update is pending chrome webstore review.

And access to version 7.2.76 is found how?

**Comment by Nareese** [comment]
> And access to version 7.2.76 is found how?

If you are using Firefox you can force an update by going to Addons -> Check for Updates, going to the "Available updates" tab, clicking on the ... for BetterTTV and selecting Update.  If you are not in a rush, the browser will eventually do this on its own.

If you are using Chrome, or Opera with the chrome extension, the chrome version is still pending review, and until they publish it, you can't upgrade.  Once it is published, again, you can force the check or it will eventually auto update.

If you are using the userscript version on any platform, the update is automatic and immediate, always, and you don't need to do anything except refresh any open Twitch pages you have.

**Comment by breon** [comment]
Working in Chrome. Thanks!
