### ISSUE TITLE
BTTV settings not working 

### ISSUE THREAD

**Issue by UwU-Monztor** [night/BetterTTV#3781]
My bttv settings do not open and it's been happening since like 1 week ago, i've even uninstalled chrome and obviously BTTV but keeps happening  : / (i'm not to good with english but i hope you can understand me)

**Comment by RafaMC97** [comment]
Same problem. 
At first it was only not working in a specific channel. After I cleaned cache and reinstalled the extension in firefox it is not working at all.

**Comment by Darktowertr** [comment]
I'm just having this issue in the extension on the Chromium Edge page. It seems that the version is not up to date. I temporarily added the Chrome extension.

**Comment by night** [comment]
Make sure you’ve upgraded to version 7.2.76. If you're on Chromium Edge you can swap to our Chrome extension that we link to from https://betterttv.com. The edge add-on store version is 4 versions out of date. We're working to get a new version out there too, however.
