### ISSUE TITLE
BetterTTV Login with Twitch Account in Streamlabs OBS

### ISSUE THREAD

**Issue by Natsukoz** [night/BetterTTV#3788]
I have constantly tried to log into BetterTTV on Streamlabs OBS using my Twitch Account but it gives me an infinite Login buffering and never goes through any solutions? I believe this is why my BetterTTV will not show up under emotes when I stream 

![2020-03-19](https://user-images.githubusercontent.com/62378602/77054041-9b0c0d00-69a5-11ea-8d1f-4a475185ebf2.png)

**Comment by night** [comment]
You would need to reach out to Streamlabs support. This is supported in the real OBS, however, so you may consider swapping to OBS instead of using Streamlabs' fork of it.
