### ISSUE TITLE
Firefox / Mac : PIP broken when BTTV extension activated

### ISSUE THREAD

**Issue by kasimodem** [night/BetterTTV#3789]
macOS 10.15.3 (latest this day)
Firefox 74.0 (latest this day)
BTTV extension 7.2.76 (latest this day)

Hi,
Picture in Picture mode blue icon appears in the right of the Twitch stream window, but is not clickable. As soon as I disable the BTTV extension, it works normally.
PIP works well on all other sites, like YT.

Thanks for your work.

**Comment by night** [comment]
That button is a Firefox built-in functionality that BetterTTV does not implement. I can't explain why disabling BetterTTV fixes it for you, but I tested on your exact same setup (Firefox 74 on 10.15.3) and could not reproduce. If BetterTTV was interacting with PiP in Firefox, we would actually render our own PiP button. Maybe you have an addition extension installed that somehow conflicts?
