### ISSUE TITLE
the icon in the menu entry in clear mode (as in not dark mode) is buggy

### ISSUE THREAD

**Issue by roger21** [night/BetterTTV#3790]
hey

the icon for the "BetterTTV Settings" entry on the menu of the profile picture is buggy in clear mode:
when you moseover it, it turns mostly white and so become invisible (since in clear mode) not like the others icons on the menus than stay dark on mouseover.

in dark mode it is white and stay white on mouseover, in clear mode it is dark and become white on mouseover.

**Comment by night** [comment]
it looks correct on my machine. you may be using another extension which further modifies twitch in a way we do not support.

**Comment by roger21** [comment]
i don't

so here is another try:

clear mode not bttv entry mouseover (ok): 
![a](https://user-images.githubusercontent.com/892186/77244240-2807ce00-6c13-11ea-9e25-b5762862c0d2.png)

clear mode bttv entry mouseover (wrong):
![b](https://user-images.githubusercontent.com/892186/77244245-3950da80-6c13-11ea-9e67-c3af61270348.png)

dark mode bttv entry (ok):
![c](https://user-images.githubusercontent.com/892186/77244251-48d02380-6c13-11ea-801b-e586903c3849.png)
