### ISSUE TITLE
[Feature Request] Option to disable mod card keyboard shortcuts

### ISSUE THREAD

**Issue by Dragoonseal** [night/betterttv#3795]
I'm not sure if this is a vanilla Twitch thing or a BTTV feature, because I can't find documentation about it anywhere, or what the keys even are, but mod cards have keyboard shortcuts.

I'm sure it's helpful to some people, but to me they're a hindrance. I've accidentally !permitted, ignored, banned, or timed out many people via the hotkeys because I've forgotten to click back to the chat text field before I start typing, or clicked but missed the field.

Would appreciate an option in the settings to disable them.

**Comment by Civrock1** [comment]
Agreed. I've permitted on accident several times due to hidden keyboard shortcuts... options to change or disable would be great.

**Comment by night** [comment]
in general we do not like to add settings unless absolutely necessary. i would recommend getting in the habit of pressing escape before you start typing
