### ISSUE TITLE
Optimization for the Emote Menu

### ISSUE THREAD

**Issue by Bobandal** [night/BetterTTV#3797]
I noticed that the Emote Menu of BTTV pulls all emotes (Twitch, FFZ, BTTV) using the middle size (2) URLs.
This in my opinion is rather silly as the emotes are statically sized to 28x28, with is the smallest size (1).

Unless I'm missing something, I would suggest to pull the smallest version of the emotes to reduce server load.

**Comment by night** [comment]
Higher quality images allow you to see the details better, and do not add to our "server load" since these are static images we serve from a storage bucket.
