### ISSUE TITLE
[Bug] Disable Host Mode Not Working

### ISSUE THREAD

**Issue by treisdorf** [night/betterttv#3799]
I have BTTV on two machines, one running Chrome, the other running Firefox. On both, even though I have Disable Host Mode active, I still get dragged along when the streamer hosts someone. Super annoying when I've fallen asleep to a nice, quiet streamer who hosts some loudmouth nutjob whose base vocal level is not much below an army of howler monkeys and who insists on blaring death metal.

**Comment by xZora** [comment]
Both Disable Host Mode and Disable Homepage Autoplay have not been working for me for several weeks/months now. Using Chrome version 81.0.4044.92 and BTTV version 7.2.77.

**Comment by night** [comment]
I just tried this on my machine and it works one both entry to streams and when host mode is enabled when viewing a stream. Unfortunately without reliable reproduction steps we can't fix issues.
