### ISSUE TITLE
gif emotes in clips

### ISSUE THREAD

**Issue by spirgiuz** [night/BetterTTV#3802]
gif emotes are still displayed in clips even though they're turned off in bttv settings.
oh i guess you can't access user settings from a clip? 
https://github.com/night/BetterTTV/blob/1a241eca04fa35b5f14a69fd091e29f67b8890bf/src/modules/clips/index.js#L39

**Comment by night** [comment]
As you found in the code, this is intentional since there are no user settings available on the clips page.
