### ISSUE TITLE
/unbanall not working on channels with lots of Bans

### ISSUE THREAD

**Issue by LiveLaden** [night/BetterTTV#3805]
AdmiralBulldog tried to unban people on his channel, and it didn't work, he asked me to try on my channel since it's small, and it worked, all 31 people got unbanned, on his channel, only 2 people got unbanned, and there is prob thousands banned by now. This is what he got

Fetching banned users...
Starting purge of 2 users in 5 seconds.
This block of users will take 0.7 seconds to unban.

AdmiralBullBot OpieOP Here's a hint, "E__" OpieOP
admiralbulldog removed ban on jackrabbit35.
admiralbulldog removed ban on break0ut.
This block of users has been purged. Checking for more..
Fetching banned users...
You have no banned users. Total Unbanned Users: 2

**Comment by night** [comment]
This system works by querying Twitch's API for banned users, so if it returns "You have no banned users" then that's because Twitch reported 0 users in the banned users list. It returns the same data Twitch queries at https://dashboard.twitch.tv/settings/moderation/banned-chatters
