### ISSUE TITLE
Allow emote searching by typing ":" (Like in discord)

### ISSUE THREAD

**Issue by Aksumxd** [night/betterttv#3807]
Would be useful :)

**Comment by pharo3** [comment]
Came here to suggest the same thing.

Apparently FFZ already has this feature but it would be nice to have it on BTTV too.

**Comment by raulcraveiro** [comment]
That's the only thing that stops me from using BTTV

**Comment by night** [comment]
This behavior was added to a previous version of BetterTTV, so this request is complete.
