### ISSUE TITLE
[bug/emoteupload] False positive 

### ISSUE THREAD

**Issue by TormentDubz** [night/BetterTTV#3808]
Uploading emote https://i.nuuls.com/u1Vv-.gif "hypoclap" results in "invalid emote: duplication" and links to clearly discernible emotes

**Comment by night** [comment]
Unfortunately your emote is too similar to be uploaded. I would recommend making more modifications to customize your emote.

**Comment by TormentDubz** [comment]
All of these are accepted however, clearly more than 10 of the same emote https://betterttv.com/emotes/shared/search?query=hyperclap

**Comment by night** [comment]
emotes uploaded from before we implemented automatic duplicate detection may remain
