### ISSUE TITLE
Blocking thumbnails from games doesn't work anymore.

### ISSUE THREAD

**Issue by Pyjamaa** [night/BetterTTV#3809]
It seems like the "Block Thumbnail" function doesn't work anymore.
Doesn't do anything when I click it whether I'm in the game directory from the game I want to block or on my following page.

It tried to reload the page F5 and Crtl+F5 still doesn't work.

My specs:
Chrome Version 80.0.3987.149
Bttv **Version 7.2.77**
Windows 8.1

Edit: Blocking games from appearing in your following list also doesn't work anymore.

**Comment by whitecrownclown** [comment]
@Pyjamaa There's no `block thumbnail` functionality afaik. Could you provide a step by step or screenshots of what's not working? Thanks!

**Comment by Pyjamaa** [comment]
> @Pyjamaa There's no `block thumbnail` functionality afaik. Could you provide a step by step or screenshots of what's not working? Thanks!

Here: https://imgur.com/KqlxPrX
Or is this a thing from ffz?
If yes sorry I'm dumb.

**Comment by whitecrownclown** [comment]
Yes, I've checked and it looks like it's a feature from FFZ. Please close this issue as it's not relevant for BTTV.

**Comment by Pyjamaa** [comment]
I'm so sorry.
I couldn't really figure out where this feature was coming from.
