### ISSUE TITLE
Info section layout is incorrect after exiting automatic theater mode

### ISSUE THREAD

**Issue by Cyberbeni** [night/BetterTTV#3811]
Without BTTV:

![2020-04-11 (1)](https://user-images.githubusercontent.com/8356175/79049301-22eedb00-7c23-11ea-8438-240d6bd41f1c.png) 

With BTTV and automatic theater mode and quitting theater mode, part of the info section is covered by the chat:

![2020-04-11](https://user-images.githubusercontent.com/8356175/79049328-41ed6d00-7c23-11ea-920a-db13ee39edf7.png)

**Comment by whitecrownclown** [comment]
@Cyberbeni I've only managed to reproduce this when you go into Theater Mode with chat hidden and then toggle it back on and exit Theater Mode. This is more of a Twitch issue than a BTTV one.

**Comment by night** [comment]
BetterTTV does not modify the page layout with theater mode. That's a Twitch feature and a Twitch bug.
