### ISSUE TITLE
Random black bar across the bottom of screen

### ISSUE THREAD

**Issue by NathDavies** [night/BetterTTV#3812]
Hey, just so you know there appears to be somethin in the code that is causing there to be a strange black bar all across the bottom of the screen about 1/10th the vertical height of the screen that covers of the bottom options of the stream on the firefox version, or at least my firefox version of BTTV. On other computers without BTTV on the same version of Firefox i've not seen the issue at all. I've identified the source as a piece attached to the code for the emote button. It is created by an element saying       "    <embed id="createConv" src="//object.center/button">    " easy fix is deleting it from the loaded code but it's just a bandaid. I have bugger all idea as to diagnose exactly how the issue is being caused so I figured I'd let you all know.

**Comment by night** [comment]
I'm not able to reproduce any issues with Firefox and the emote menu. It's possible you have some other browser extension installed conflicting with ours, or it's a configuration issue with your specific Firefox install.
