### ISSUE TITLE
[Bug] Click to Pause - Randomly Stops Working

### ISSUE THREAD

**Issue by cyberofficial** [night/betterttv#3813]
# Issue
When switching on the feature [Click to Pause]
The feature will randomly stop working on different streams.

# Video
https://youtu.be/SVLC4K5MxLE

# Personal Steps on trying to fix
- Removing plugin, then installing
- clearing all cache/files
- Tried using a the mobile USB version of Opera same issue with clean install
- *edit, Also paused/removed all script blockers, issue didn't fix

# Version Info
BTTV: Version 7.2.77 (Mar 22, 2020)
Opera: LVL 1 (core: 67.0.3575.130)

**Comment by night** [comment]
It might be related to the Twitch extensions on the player. Have you tried disabling Twitch extensions in the BetterTTV settings?

**Comment by cyberofficial** [comment]
Yea that fixed the issue haha, that works. Thanks.
