### ISSUE TITLE
Feature Request: Multi-stream button

### ISSUE THREAD

**Issue by metazoxan** [night/BetterTTV#382]
Sometimes I want to Multi-stream but setting one up requires another extension and is annoying to really set up. Besides that I don't exactly like the look of the extension (I feel Better TTV could make a sleeker one) I found and some Better TTV functions don't seem to quite work with it (although the only one I've seriously noticed 100% doesn't work is the minichat).

So what would be awesome is if there was a button to start up a multi-stream actually on the page and maybe have a feature where a list pops up including everyone you are following and you can add them to the multi-stream simply by clicking their names or something along those lines.

Also the multi-streams I've seen don't include the "watching now" and "total views" numbers and I actually like to see those. This is just a minor request but if those could be made to show up in the Multi-stream that would be a cool little feature.

**Comment by night** [comment]
The Twitch website doesn't feature enough room to provide a multi-stream experience, not to mention the pure amount of changes that would be required to the UI to implement such a system reliably. There's already third party websites that integrate multistreams in a much better way than we probably could, so I suggest using those.

Fire has an interesting version of a multistream page: http://incendiary.media/multichat.html#/fire:cv/night:cv

It allows you to drag and resize each how you want them.
