### ISSUE TITLE
Feature to see a user's chat history has disappeared

### ISSUE THREAD

**Issue by 3sdz6eidhrfi2uea** [night/betterttv#3821]
Hi,
I'm not sure if this feature is from BTTV or Frankerfacez.
In case it's from BTTV I report it here. Basically we used to be able to click on a user in the chat, then we would click on an arrow which would display the chat history of this user(Only from messages that are in the buffer).

Is it gone for good or it's just broken atm ? Thank you.

**Comment by Nareese** [comment]
This bug was fixed in the latest version (7.2.78, you can check this via BetterTTV Settings -> About) released last night.  If your browser hasn't automatically updated, you may need to manually update your extensions/addons to get the latest version.

**Comment by 3sdz6eidhrfi2uea** [comment]
I am indeed using chrome. I'll just wait then, thank you.
