### ISSUE TITLE
[Feature Request] The Ability to Track Conversations in BTTV

### ISSUE THREAD

**Issue by Natexgloves** [night/betterttv#3822]
I would love to see a feature that lets us hover over an @[name] that would then highlight their previous messages in chat.

For example, I'll always see a message like

> Natexgloves: `@otheruser` what do you mean? That's a terrible idea.

Instead of (or while) scrolling up to find `@otheruser`'s original message, I'd love for the last message to be shown or highlighted in some way when hovering over the reply tag.

**Comment by Dragoonseal** [comment]
You actually used to be able to click the **@otheruser** bit in people's messages and it would bring up **@otheruser**'s mod card.

It was super helpful, would definitely love to see it make a return.

**Comment by Scrxtchy** [comment]
This has been added as a native feature on the twitch chat client as is rolling out on selected partner channels.
(It has been gaining a negative reception)

![image](https://user-images.githubusercontent.com/12771982/90399643-9f685d80-e0de-11ea-8c16-4b6813fe6e5e.png)
src: https://twitter.com/lowco2525/status/1292933791623913473

**Comment by night** [comment]
yes, this is solved by twitch's threading feature
