### ISSUE TITLE
[Bug] Chat expands vertically when 1 character is entered up to 3 characters

### ISSUE THREAD

**Issue by Xseleon** [night/betterttv#3824]
### Issue 
---

The chat in BetterTTV expands when 1-3 characters are entered and can be distracting when trying to type in the chat.

**No Text:**
![noText](https://user-images.githubusercontent.com/63925884/80136513-cdde8d80-856f-11ea-8ec5-96789cfbc7d1.PNG)

**One, Two and Three Characters:**
![oneChar](https://user-images.githubusercontent.com/63925884/80136858-4c3b2f80-8570-11ea-918c-672f5c6ffe0b.PNG)

![twoChar](https://user-images.githubusercontent.com/63925884/80136868-4fceb680-8570-11ea-83e1-1ff74e8d5996.PNG)

![threeChar](https://user-images.githubusercontent.com/63925884/80136877-53fad400-8570-11ea-9503-8c73b801fa6c.PNG)

**Many Characters:**
![manyChar](https://user-images.githubusercontent.com/63925884/80136895-5a894b80-8570-11ea-8899-e88a14633c4f.PNG)

**Comment by night** [comment]
I cannot reproduce this. if you use another extension it could be related to that extension

**Comment by Xseleon** [comment]
> 
> 
> I cannot reproduce this. if you use another extension it could be related to that extension

I should have mentioned it happens in Firefox, if you're not using that browser. I also checked again after disabling all my extensions besides BTTV, but the problem persists.

**Comment by night** [comment]
I tried firefox as well, but still unable to reproduce.
