### ISSUE TITLE
Don't see emotes

### ISSUE THREAD

**Issue by Heizl** [night/betterttv#3825]
Hey!
i added new emotes to my Stream like "monkaT" and they don't show up. I waited for several days, weeks and nothing happend. Today I reseted it and added them all new. Even doh it didn't worked with all emotes. monkaT isn't in my emote pool, but the some other ones are.
I don't know what to do now.
Thanks in advance!

- Heizl_

**Comment by night** [comment]
Our emotes do not show up in the Twitch emote menu, but if you type them they will appear. You can enable our Emote Menu in the BetterTTV Settings, which they will appear in.
