### ISSUE TITLE
Bug with PIP button missing because of mini-player

### ISSUE THREAD

**Issue by iPot** [night/betterttv#3829]
There's a bug I've been seeing for a while now, everytime the mini-player gets activated or shown the PIP button, when you hover on the video player, would suddenly disappear until I refresh the page.

**Comment by whitecrownclown** [comment]
@iPot Can you please provide more info on this? I can't reproduce this issue.

**Comment by iPot** [comment]
@whitecrownclown Do you know the mini-player found on the Video Players Settings (gear icon)>Advanced>Mini Player?

That gets activated if you scroll down at the bottom of a channel or if you go to another place on Twitch like the Following section or even Browsing section using the same tab where you were watching a livestream.

The problem is the PIP button that was added by BTTV, which is just next to the Settings (gear icon) on the Video Player, disappears when the Mini Player gets activated.

**Comment by whitecrownclown** [comment]
@iPot I understand now, thanks a lot for the details! I'll have a look over this.

**Comment by night** [comment]
looks to be no longer an issue with redesign
