### ISSUE TITLE
Feature Request: Default Quaility Option Choice

### ISSUE THREAD

**Issue by MrJokester** [night/BetterTTV#384]
If its possible I think it be nice if you could put an option that lets a user choose there default quality option, youtube did something like that at one point I don't know why it stopped, but for me I personally have decent internet and put it on source but I know for others there internet might be bad and can't even handle Medium quality. So make it so you theres like a Set Default Quality pull down menu and than a list of quality options, I have no idea if it could be done or not but I think it would be awesome.

**Comment by night** [comment]
Twitch already saves your default quality. If it isn't saving, then your Flash Player is configured to not remember these settings and you should instead change that.
