### ISSUE TITLE
 problems with emotes

### ISSUE THREAD

**Issue by NicolasLisboa** [night/betterttv#3840]
hi i need help i can't access emojis on twittch already activated "BetterTTV Emotes" "BetterTTV GIF Emotes" "Emote Menu" "FrankerFaceZ Emotes"

**Comment by night** [comment]
I'm not sure what "can't access" means, but make sure you enable "Emote Menu" in the BetterTTV settings, which will allow you to use our Emote Menu (not Twitch's).
