### ISSUE TITLE
holding shift should keep emote menu open

### ISSUE THREAD

**Issue by RMcD94** [night/betterttv#3844]
works for twitch emotes why not bttv

**Comment by Nareese** [comment]
While this is possibly a useful feature enhancement request, if you are not already aware, there is a "pin" icon in the lower right of the BTTV emote menu, and clicking on that pin will keep the menu open until you click it again and click another emote, or until you manually close the menu by clicking on the emote menu button again.

**Comment by RMcD94** [comment]
thanks i didn't know that
