### ISSUE TITLE
Feature request: Emote blacklist

### ISSUE THREAD

**Issue by laagone** [night/BetterTTV#385]
You blacklist a certain emote, and now instead of seeing the emote, you only see text. Mockup: http://puu.sh/hrjJ3/c45808cf18.png Similar to the feature on Chatty.

This would be useful if you don't like a certain emote, but you can still see the rest of the message as opposed to blacklisting the emote as a word with "Set Blacklist Keywords".

**Comment by night** [comment]
There wouldn't be an "emote" blacklist per say, but you could blacklist emoticon codes. If so, that would be a duplicate of https://github.com/night/BetterTTV/issues/67
