### ISSUE TITLE
Add Personal Emotes to the API  

### ISSUE THREAD

**Issue by Roger-Chavez** [night/betterttv#3853]
Please add Personal Emotes to the API so that BetterTTV Pro members can easily use their personal emotes in apps like chatterino.
Someone requested it from their end but they said it's out of their hands since personal emotes aren't part of the API https://github.com/Chatterino/chatterino2/issues/1415#issuecomment-553730302

**Comment by night** [comment]
They will never be part of the API because loading personal emotes via API does not scale. Other clients would need to reimplement our websocket handling: https://github.com/night/betterttv/blob/master/src/socket-client.js

**Comment by Roger-Chavez** [comment]
ok, thank you for your time
