### ISSUE TITLE
Font and Font Size Not Working

### ISSUE THREAD

**Issue by nolyd3** [night/betterttv#3859]
Attempting to change the font or font size within the chat menu is not working atm.

**Comment by Nareese** [comment]
duplicate of #3855

**Comment by AlbrechtProud** [comment]
I have the same issue. MacOS Catalina and Firefox

**Comment by mseals1** [comment]
I have the same issue, using Chrome.

**Comment by dragonpixies** [comment]
Same issue on Chrome and Firefox on Win8. Uninstalling/reinstalling didn't work :(
