### ISSUE TITLE
Pin Highlighted Messages

### ISSUE THREAD

**Issue by XEONFillo** [night/betterttv#3860]
It doesn't work

**Comment by XEONFillo** [comment]
Sorry but I don't understand what I have to do

**Comment by Nareese** [comment]
There is nothing you can do.  It's a bug.  It will be fixed when night has time to evaluate the PR and merge it.  Thank you for your report.

**Comment by XEONFillo** [comment]
Ah ok. Perfect
Thanks

**Comment by guniu** [comment]
I have Version 7.2.79 that says this is fixed, but it still doesn't work for me.
