### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by JillianMPlayz** [night/betterttv#3865]
Hello, I noticed recently that the chat disappears when using the option to have chat on the left side of the player. I found a fix where I just had to disable it but I wanted it back so I changed it to be on the left again and now the only fix is to get rid of the extension. Because I have the left side chat disabled but its acting like is on. I would still love to use the left side chat. so if you could find a fix that would be much appreciative!

**Comment by Nareese** [comment]
duplicate of #3852
