### ISSUE TITLE
Hide Offline Followed Channels

### ISSUE THREAD

**Issue by Thornton19** [night/betterttv#3868]
Hide Offline Followed Channels does not seem to be working after the new Twitch update. 

If you manually hide them using the "show less" option, they reappear once more as soon as the page is reloaded. Attempted disabling/enabling the extension. Also tried restarting the browser. Confirmed BetterTTV is up to date.

Firefox v76.0.1

**Comment by escapepods** [comment]
I am also experiencing this issue.

**Comment by Darxide23** [comment]
Already fixed and waiting to go live. https://github.com/night/betterttv/pull/3842

**Comment by THEDARKK** [comment]
No work with Google Chrome (83.0.4103.61)

**Comment by Darxide23** [comment]
Works fine for me. Chrome 83.0.4103.61

**Comment by SwimmingLink** [comment]
I just wanted to update that I'm on Chrome Version 84.0.4147.13 (Official Build) dev (64-bit) for Windows and this is still not working for me.

**Comment by Darxide23** [comment]
Make sure you have the setting enabled properly? That's all I can suggest since I rushed to check it out as soon as I got notified of the update and it works perfectly.

**Comment by SwimmingLink** [comment]
I guess stating that I also have "Auto Expand Followed Channels List" enabled might be the cause of it? Same setup I've had for a long time, but it only started being an issue after the recent Twitch update.

**Comment by Thornton19** [comment]
Yeah I'm still experiencing the issue when pairing it with the "Auto Expand Followed Channels List" option. 

Confirmed that both settings are turned on in bttv settings. I've updated all addons and tried on the most recent versions of chrome and firefox.

**Comment by Darxide23** [comment]
As an update: I had been using the old style of Twitch. Today, they forced the new layout on me apparently because I can't get the old style back and now I'm again seeing offline channels listed. So there is also probably part of the discrepancy here.

**Comment by night** [comment]
Due to Twitch's redesign they stopped linking offline channels to direct videos. The result of this is that we are no longer able to simply hide offline channels, making the fix to this nontrivial.

**Comment by mpcallahan** [comment]
Looks like for offline channels the channel icon has class "side-nav-card__avatar--offline" applied. Could it be used to detect which ones are offline and which ones aren't?

**Comment by Darxide23** [comment]
> Looks like for offline channels the channel icon has class "side-nav-card__avatar--offline" applied. Could it be used to detect which ones are offline and which ones aren't?

At that point, why not just add it to your AdBlock filter?

**Comment by escapepods** [comment]
> > Looks like for offline channels the channel icon has class "side-nav-card__avatar--offline" applied. Could it be used to detect which ones are offline and which ones aren't?
> 
> At that point, why not just add it to your AdBlock filter?

That would just hide the streamer's icon from appearing. The issue is that a child-div contains the offline selector, not the parent. The parent selector is identical to the online channels now.

**Comment by Darxide23** [comment]
> That would just hide the streamer's icon from appearing. The issue is that a child-div contains the offline selector, not the parent. The parent selector is identical to the online channels now. Hiding that selector would just remove the icon, but the parent div containing their name and online status would remain.

You can still make a filter for that. You can setup filters that follow "If div contains [element] then hide parent" logic so if the child div has "--offline" you hide the parent div and the whole container goes away.

**Comment by escapepods** [comment]
Ah, good to know! Thanks for that. I'll use AdBlock instead.

**Comment by BeRightBaack** [comment]
I also used uBlock to remove offline channels from the list. But since filter from post above didn't work for me (it doesn't work in collapsed mode and sometimes randomly shows icons for a second and then removes them again, same happens if I move mouse over showed icons and so on) i made a different filter.
`www.twitch.tv##div.side-nav-card__avatar--offline:upward(2)`
This works in both modes and haven't had any issues with it so far

**Comment by THEDARKK** [comment]
Thank you BeRightBaack

**Comment by TheLavian** [comment]
Using Firefox, not Chrome and this is still a problem.
![Clipboard01](https://user-images.githubusercontent.com/52756197/85947430-c5a33400-b99e-11ea-9f00-2f634907152a.jpg)

**Comment by justinmedina** [comment]
just reinstalled chrome and BTTV and clicked the hide offline followed channels button a couple times, refreshed page and still not working
![Untitled](https://user-images.githubusercontent.com/67798372/86485545-f7adf080-bd26-11ea-9446-f9f75faa1aa2.png)

**Comment by Darxide23** [comment]
> 
> 
> just reinstalled chrome and BTTV and clicked the hide offline followed channels button a couple times, refreshed page and still not working

Please stop posting about this. If you could read above, this doesn't work on the new Twitch yet. Only the old layout. There's an adblock script to hide the offline channels, too. You could save yourself a lot of time making useless posts if you just read up.

**Comment by BanderDave** [comment]
Adding as I didn't see it mentioned. When I have the option off on chrome, the followed channel list doesn't appear at all. Sorry if this is already known.

**Comment by mpcallahan** [comment]
Maybe the best thing to do is hide this option from the menu altogether until a way to make this work is available.

**Comment by alattepanda** [comment]
I have been having this issue on Chrome since the last big Twitch update. It is still an issue. Just for the record

**Comment by TheLavian** [comment]
Why are these issues being marked as closed when they haven't been fixed yet?

**Comment by night** [comment]
because it is fixed. update your extension :)

**Comment by TheLavian** [comment]
> because it is fixed. update your extension :)

Done - sorry,

D'oh! 🤦‍♂️
