### ISSUE TITLE
Real-time Chat Statistics

### ISSUE THREAD

**Issue by Rasmushejlesen** [night/betterttv#387]
I was thinking if there could be a feature where u could see, like how many comments in chat per minute or something like that, could be cool.

**Comment by Yrlish** [comment]
I love statistics. Statistics are awesome.

**Comment by EhsanKia** [comment]
Would this be better as a command (such as /stats) or live updating and always showing up? I feel like most people wouldn't care about it, and at the same time, having an option to toggle it is also overkill.

**Comment by Yrlish** [comment]
@EhsanKia Disabled by default? :) Also, I don't think a command for this would be good.

**Comment by night** [comment]
Thanks again for the request. Given this has been open for years and there has not been much traction I think this might add clutter/bloat and may not be useful to most folks.
