### ISSUE TITLE
Subscriber Indicator

### ISSUE THREAD

**Issue by cyberixae** [night/betterttv#3876]
Regular Twitch UI has become so confusing I typically do not know whether or not I have a valid subscription until I post a chat message to see if I have the subscriber emoji or not. Could you implement a feature that would show me my current subscriber status ( and or emoji ) without posting a message to the chat first?

**Comment by xgerhard** [comment]
Hiya, you could check by looking at the subscribe button. It will either say "Subscribe" if not subscribed, or "Gift a sub" when subscribed.

**Comment by cyberixae** [comment]
I know. But it also says things like "Continue Subscription" and "Resubscribe" and I keep forgetting which ones mean my subscription is still active and which ones mean it has really expired.

**Comment by night** [comment]
if it doesn't say "gift a sub" then you are generally not subscribed
