### ISSUE TITLE
Emote Selector 

### ISSUE THREAD

**Issue by SrgtDonut** [night/BetterTTV#388]
The emote selector w/o BetterTTV is wider than with BetterTTV on. http://puu.sh/hti7d/0fea54250c.png

**Comment by Izlsnizzt** [comment]
Twitch's vanilla emote selector is a fixed width element, if you chat chat scaled in BTTV the emote selector will not scale to fit the new dimensions.

**Comment by night** [comment]
Use our emote selector instead..
