### ISSUE TITLE
Right click mod options not showing up

### ISSUE THREAD

**Issue by RiggedyRekt** [night/betterttv#3890]
I recently saw that twitch updated their layout and with that it took my mod options away (the one where a bar shows up with delete all the way to ban after right clicking a name). The browser I am using is opera, tried this on 3 channels (including my own) that I am a mod on and nothing changed. The only way I found out how to make them show up is if I am in mod mode, pop out chat, or theater mode. All of these options do not suit me as well as the normal setup.

I also checked the script of betterttv and it said there error, I am not sure if it helps but...

**Comment by Doge322** [comment]
On chrome it only works when using theater mode
