### ISSUE TITLE
BTTV Personal emotes don't show up for certain people

### ISSUE THREAD

**Issue by Sleepywalker69** [night/betterttv#3899]
Been watching various livestreamers with chat onscreen and noticed my personal emotes are not showing for them. Other BTTV emotes show up just not my personal ones, I see them myself when I type them though.

**Comment by night** [comment]
It's possible whatever on-screen tool they are using does not support personal emotes. The only on-screen tool we build and maintain an integration with is [KapChat](https://nightdev.com/kapchat).
