### ISSUE TITLE
[Bug] Custom nicknames disappear after a few weeks

### ISSUE THREAD

**Issue by GrapeJelly** [night/betterttv#3904]
I've set some custom nicknames for users and noticed that after a while they disappear and revert to their regular name. I'm guessing this happens after about 2-3 weeks. I'm using Chrome on Windows.

**Comment by night** [comment]
It isn't possible for nicknames to be reverted unless your settings for BetterTTV are being cleared. If you run cleanup tools on your computer they can sometimes clear cookies/storage for websites in your browser, which will delete BetterTTV storage too.
