### ISSUE TITLE
Edge Add-on many releases behind Chrome extension

### ISSUE THREAD

**Issue by Quitch** [night/betterttv#3906]
https://microsoftedge.microsoft.com/addons/detail/icllegkipkooaicfmdfaloehobmglglb
https://chrome.google.com/webstore/detail/betterttv/ajopnjidmegmdimjlfnijceegpefgped

The version on the Microsoft Edge Addons page (the default for Microsoft Edge chromium) has not been updated since the 10th March.

I'm not sure if this is because it has been forgotten, the account shown isn't an official one, the individual maintaining this has moved on, or because Microsoft have a longer approval process. But given that this can lead to resolved bugs appearing unresolved for a (admittedly small) portion of the userbase, this should either be updated, or if it is not going to be actively maintained, be withdrawn which then forces uses to the Chrome extension (which will work in Edge) and thus ensures they are receiving an up-to-date version.

**Comment by night** [comment]
The edge extension loads our JS bundle remotely, so it doesn't matter if the extension version is behind as it always serves the latest version. Other browser manufacturers, like Chrome and Firefox, do not allow us to remotely load JS bundles from our CDN. You can check the actual running version in the BetterTTV Settings > About tab.
