### ISSUE TITLE
Prevent temporarily the chat from scrolling down

### ISSUE THREAD

**Issue by cyberixae** [night/betterttv#3908]
Sometimes it is impossible to read the chat history because new messages keep appearing. It would be cool to have a button to disable scrolling or some other solution to problems caused by the scrolling.

**Comment by night** [comment]
You can temporarily prevent autoscrolling already by scrolling up in the chat. There is a limited backlog, however, so you may encounter old messages being removed if you pause scrolling in an active chat for too long.

**Comment by cyberixae** [comment]
To anyone else suffering from this problem. The solution is to get a scroll wheel. The chat pause feature ignores the scrollbar but seems to work if you use a physical scroll wheel.
