### ISSUE TITLE
BetterTTV gif emotes not working

### ISSUE THREAD

**Issue by MiciTTV** [night/betterttv#3909]
According to this webpage: https://community.nightdev.com/t/betterttv-debugging/3685
I needed to check my javascript console, and share the results here when experiencing issues, which I am. 

here is an image (I believe) of the red codes I am getting: 

![image](https://user-images.githubusercontent.com/65772380/82673226-cd561700-9c41-11ea-9371-ee91062d04d3.png)

Please help? Thank you in advance :)

**Comment by whitecrownclown** [comment]
@MiciTTV There's no issue I can see from your console. Are you sure you've enabled the gif emotes?
<img width="795" alt="Screenshot 2020-05-22 at 17 06 46" src="https://user-images.githubusercontent.com/8309417/82676232-b8cc4b80-9c4e-11ea-87de-e8d4bd67c512.png">
