### ISSUE TITLE
[Feature Request] Chat Timestamps

### ISSUE THREAD

**Issue by TheDonutDen** [night/betterttv#3910]
Would like to see the enable chat timestamps feature added

**Comment by Monkey151546** [comment]
It's already a thing, click chat settings below chat (gear wheel kinda) and check "show timestamp"

**Comment by TheDonutDen** [comment]
@Monkey151546 Right, but that is just a regular Twitch setting. Currently I have to set it every single time I am in a new Twitch tab/session/etc because of how Twitch operates. 

I was requesting to have the chat timestamps feature added to BTTV settings so that I could have that state saved rather than having to renable it every time for convenience. Kind of like how with BTTV, I no longer have to renable the Dark Theme (also a Twitch setting) for every new Twitch tab/session/etc.

**Comment by night** [comment]
You should not need to set it every time. If you do, then that would imply your Twitch cookies/storage is being cleared. You may need to configure your browser not to clear this data on browser close.
