### ISSUE TITLE
Auto Theatre Mode

### ISSUE THREAD

**Issue by Monkey151546** [night/betterttv#3911]
hello, I made a thread about this last week I believe and it has been closed but I'm still experiencing this issue, I'll add more details ; if you click a channel you follow on the left side, auto theatre mode will work , but if you pick a channel from say, League of Legend game list, it will not work. Also if you are on twitch and a channel you follow go live, at upper right corner you will see for exemple "Night just went live" with Watch and Close as options, if you click Watch it will bring you to Night's stream and auto theatre mode won't kick in even tho the setting is on. 
I hope this helps. 
PS: thanks for the hard work you guys put on this

Edit : if you type the streamer's name in the URL, auto theatre mode will also work

**Comment by night** [comment]
I assume this is related to the Twitch channel redesign. Unfortunately since my account is not in the experiment I cannot fully test the redesign, but it is working reliably from what I am able to test. Until I'm able to reproduce this it's not able to be fixed.
