### ISSUE TITLE
anon chat setting not working for bttv

### ISSUE THREAD

**Issue by sw00nie** [night/betterttv#3913]
hi, i recently turned on the anon chat setting. when i tried to turn it back off, i noticed my twitch wasn't displaying what channel i was in anymore. i've tried everything, restarting browser, reinstalling bttv, etc. does anyone know how to fix this? it's driving me nuts!

**Comment by night** [comment]
I'm not able to reproduce any issues with anon chat. Please provide steps to reproduce your issue.
