### ISSUE TITLE
BTTV emotes navigation bar doesn't appear

### ISSUE THREAD

**Issue by merian-1** [night/betterttv#3915]
Since I reinstalled the BTTV extension in my new browser (Opera GX), the BTTV emotes navigation bar does not appear there as FFZ does [(image 1)](https://imgur.com/9bI0fRF) instead, it is shown down the chat in a different button [(image 2)](https://imgur.com/X5jPgjT)  [(image 3)](https://imgur.com/ABBLk2T). In my old browser (Google Chrome) it didn't happen, all the emotes extensions were shown together in the emotes navigation bar.

links to the images
https://imgur.com/9bI0fRF (image 1)
https://imgur.com/X5jPgjT (image 2)
https://imgur.com/ABBLk2T (image 3)

**Comment by night** [comment]
BetterTTV's emote menu is a separate entity from Twitch's emote menu. You may be using a different extension which shows our emotes in that menu, but we are unable to provide assistance with third party extensions.
