### ISSUE TITLE
Select Channel Notification

### ISSUE THREAD

**Issue by MrFivon** [night/BetterTTV#392]
Hey,
if I turn Notifications on now, I get them for every followed Channel. It would be nice if i could select the channel like I can do on the Twitch Email Notification :)

**Comment by night** [comment]
If you don't want a notification, I suggest unfollowing the channel. The point of following a channel is generally because you want to watch them. Implementing this would requiring us to poll an extra API for every channel that went live, which is not something we want to implement.
