### ISSUE TITLE
No red highlight / highlight sound anymore

### ISSUE THREAD

**Issue by Derasiel** [night/betterttv#3936]
I thought I fixed it by myself but not really. So, I turned on then off or off then on, every settings (depending on their condition before).

![image](https://user-images.githubusercontent.com/37622648/83352601-f2870b80-a34c-11ea-90b2-55434d186806.png)

For justinfan12345's message, it appears to work well since it's me with my account typing, we see this nickname because I turned on then off anon chat. The problem is that nobody other than me see this message, I tried to send the @ on my phone and we clearly see that it does not work.

**Comment by night** [comment]
You probably need to re-add your username to the highlights list in chat settings
