### ISSUE TITLE
audio alert or different color for personal user name mention

### ISSUE THREAD

**Issue by mpsii** [night/BetterTTV#394]
Currently, you can highlight chat messages with a list of words. But, it would be good to have an audio or different color highlight for a mention of your personal user name.

**Comment by Maxhype** [comment]
I wish that audio notification would always make a sound even when I'm not tabbed out from chat. Now it only makes a sound when I'm tabbed out from cha which I don't like so much. I want sound notification tabbed out or not.

**Comment by night** [comment]
Duplicate #237
