### ISSUE TITLE
Follower Channels Side Bar and Left Side Chat

### ISSUE THREAD

**Issue by jt415gz** [night/betterttv#3945]
When left side chat is turned On, the Follower Channels side bar fails to switch to opposite side of window. It basically gets stuck on the left side along with the now switched left chat window.

Windows 10 64-bit
Firefox 77.0.1 64-bit
![Screenshot_1](https://user-images.githubusercontent.com/58667737/83763181-4df71900-a62d-11ea-96e7-2ea3c3e303c0.jpg)

**Comment by night** [comment]
this is already fixed in the latest update.
