### ISSUE TITLE
Request Highlighted pin messages custom

### ISSUE THREAD

**Issue by DanielChavesSimao** [night/betterttv#3946]
Streams like Faker's have a translator that types in chat so i highlight he's username and pin the highlighted messages but I wish I could customize the font and the background of the pinned msg because that's the only thing in the chat that matters.
![image](https://user-images.githubusercontent.com/55005033/83786137-b0b9d600-a668-11ea-9c51-4743d6a9aeb9.png)

It's hard to read like this. Ty.

**Comment by night** [comment]
we most likely won't offer a way to customize this further. i would recommend either forking betterttv to modify it for your use or use an extension like stylish to modify our css on the fly
