### ISSUE TITLE
Feature Request: Left Sidebar stays collapsed

### ISSUE THREAD

**Issue by mparmpuni** [night/betterttv#3947]
So twitch made the left side bar to collapse/expand on mouse hover which is incredibly annoying when moving around multiple windows/tabs.

If it's possible to lock it collapsed or expanded it will be nice.

Tried blocking the element in ublock but the channels and friends disappear as well.

This is the filter if it helps `www.twitch.tv##.tw-z-above.tw-full-height.tw-flex-shrink-0.tw-c-background-alt.side-nav--hover-exp.side-nav--collapsed.side-nav`

**Comment by night** [comment]
im not able to reproduce this
