### ISSUE TITLE
I can't see the message if i'm tagged in it

### ISSUE THREAD

**Issue by rexus85** [night/betterttv#3948]
The problem is that i can't see someone message if he/she tagged me and i haven't the options active. i tryed all solution backup/uninstall/reinstall/ try to set off all options and then set all on and then resett my options ( of course i tryed to see if was a my problem but when i uninstall bttv i can see the message)

**Comment by night** [comment]
You can edit your highlight keywords with your twitch username in the chat settings to fix that.
