### ISSUE TITLE
messages rating

### ISSUE THREAD

**Issue by OptimalNickname** [night/betterttv#3949]
I think massages rating will add new experience to chatting. It would be nice if registered users can put "+" or even emotes to other users messages like in discord chat. And auto clips or highlights can be created for messages with best rating. I dont think twitch will implement this any soon.

**Comment by night** [comment]
we generally don't have a way to attach metadata to messages sent in chat. the exception there is emotes because they are literally replaced in the message text itself. having metadata like images in chat text would not really work (there are text length limitations, moderation limitations, etc).
