### ISSUE TITLE
Can't add shared emotes to channel

### ISSUE THREAD

**Issue by Creadolly** [night/betterttv#3951]
I downloaded BetterTTV a while ago and was able to use the Add To Channel button on shared emotes then. The emotes I added then still work but when I click the button to add more, it doesn't work. The button doesn't even change to Remove From Channel. I've logged out and back in and I've reinstalled it but it just doesn't work.

**Comment by night** [comment]
Are you sure you aren't just out of additional emote slots? You can see your usage on the dashboard.
