### ISSUE TITLE
Hide Offline Followed Channels 

### ISSUE THREAD

**Issue by flaxo2608** [night/betterttv#3957]
![cc](https://user-images.githubusercontent.com/66755358/84326562-7fb43680-ab7d-11ea-996c-2c191b73a27b.PNG)

![ccc](https://user-images.githubusercontent.com/66755358/84326609-a07c8c00-ab7d-11ea-8cf0-4c3b3a0f0bfd.PNG)

**Comment by TheKiller158** [comment]
same problem !

**Comment by Nareese** [comment]
duplicate of #3868

**Comment by flaxo2608** [comment]
oh yes my bad..

**Comment by lilchina** [comment]
same here 
![twitch bug](https://user-images.githubusercontent.com/58664301/84568687-b9846900-ad46-11ea-9950-22ccbb3e1a4d.JPG)

**Comment by Rheetro** [comment]
I got exact same problem - it's turned on but offline channels still showing? Tried different browsers, same result :(

**Comment by lilchina** [comment]
I  did this until they patch it
 first you need ublock Orgin plugin it's free. . I  already had it . It removes  the offline
just delete the last line when it's fixed 
place in UO My Filters 

www.twitch.tv##div.side-nav-card__avatar--offline:upward(2)
