### ISSUE TITLE
Disable stream autoplay option when not in chat on the new UI

### ISSUE THREAD

**Issue by tezJR** [night/betterttv#3960]
It wastes bandwidth. To be clear, not homepage autoplay, but viewing a channel's Home, About, Schedule, or Videos page when they're live. Is this doable?

**Comment by night** [comment]
I don't see this as a worthwhile feature. When a stream is live users are most likely not on their home screen, but rather on their stream screen. If you're browsing other content you would want to probably keep the stream rolling when clicking around, especially since they removed the mini player.

**Comment by tezJR** [comment]
[A significant amount of people disabled the miniplayer.](https://old.reddit.com/r/Twitch/comments/7gr3t4/cant_turnoff_mini_player/) Now no one has the option. I don't want stream running when browsing past videos.

**Comment by tezJR** [comment]
Also, Comcast, which serves a good portion of the US, will re-activate data caps soon. Would you please reconsider my request to add this? I see it as similar to disabling channel host mode.
