### ISSUE TITLE
BTTV emotes button dissapeared

### ISSUE THREAD

**Issue by ph55** [night/betterttv#3962]
Emotes are shown but there is no button with emotes menu (on bottom left).
I've seen that Twitch layout changed slightly. Maybe it's related? Or chrome update?

![image](https://user-images.githubusercontent.com/1386622/84557223-de221600-ad31-11ea-94b0-7bb4518c21df.png)

**Comment by night** [comment]
You may have reset your settings, so go to the BetterTTV Settings and enable "Emote Menu" again.

**Comment by ph55** [comment]
Jesus I'm stupid KEKW
