### ISSUE TITLE
[Feature Request] Fly-out Followed Channels Panel

### ISSUE THREAD

**Issue by pvogt** [night/betterttv#3965]
For some reason Firefox Developer Edition browser has a fly-out ability for the Followed Channels panel when watching a channel.
Meaning, when the Followed Channels panel is collapsed to only show the Icons of the followers, hovering your mouse over the collapsed panel will 'fly out' (expand) to show more info about the streamers.
No other web browsers, not even other versions of Firefox browsers, has this ability. This was tested without Betterttv add-on.
If this feature can be added to the add-on so other web browsers has this ability would be nice.

**Comment by night** [comment]
This could be an experiment Twitch is trying, but in general there are already popout when hovering the left sidebar.
