### ISSUE TITLE
Access to BTTV API blocked by CORS on betterttv.com

### ISSUE THREAD

**Issue by nickmykkanen** [night/betterttv#3967]
This occurs when uploading a new emote:

`Access to XMLHttpRequest at 'https://api.betterttv.net/3/users/<userID>/emotes' from origin 'https://betterttv.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

The website UI displays an unknown error. The above message is taken from the console error in DevTools.

I am attempting to upload the emote for a channel that I have editor access to, but the same error occurs if I try to upload to my own channel as well.

Windows 10 1909 Version 10.0.18363 Build 18363
Chromium Edge 83.0.478.45 (Official build)

**Comment by night** [comment]
That can occur if there was an internal service error during your request. I would recommend trying again.
