### ISSUE TITLE
Emote menu positioning

### ISSUE THREAD

**Issue by MrTipson** [night/betterttv#3968]
The emote menu's positioning gets broken when resizing the window (the offset is set in pixels when you move it around).

Steps to reproduce:
 * have the browser window not cover the entire screen (so you can resize from the sides)
 * open the emote menu and place it close to the right (or bottom) edge of the screen
 * move the border of the window so the previous positioning of the emote menu is no longer in the browser window 
 * the emote menu should no longer be accessible without resizing the window back and moving it on screen

Proposed solution: 
 * set the elements position in percentage values in order to always stay in the same spot proportionally

**Comment by night** [comment]
The positioning of the window is absolutely defined to support dragging it around the screen, so this won't be fixed.
