### ISSUE TITLE
colors in dark mode

### ISSUE THREAD

**Issue by ssOwl** [night/betterttv#3969]
When dark mode enabled, colors become little different, so i need to watch only in alt+t mode to have dark background and normal colors. But when switching channels my eyes hate me.
Dark mode disabled:
![image](https://user-images.githubusercontent.com/63245691/84678656-19029480-af52-11ea-9468-763552448fef.png)
Dark mode enabled:
![image](https://user-images.githubusercontent.com/63245691/84679241-de4d2c00-af52-11ea-9594-13a8a3cd4ae9.png)

**Comment by night** [comment]
This is working as intended to force usernames into better contract ratios, making them easier to read and preventing users from trolling with hard to read names.
