### ISSUE TITLE
BetterTTV emotes not appearing under the chat.

### ISSUE THREAD

**Issue by beekerino** [night/betterttv#3973]
![f5aae1eb7fda783d8b89019eaf1d6640](https://user-images.githubusercontent.com/67033214/84844624-9afcc700-afff-11ea-8f0d-7d08b7a3d930.png)

EMOTES ARE ENABLED IN  BETTERTTV SETTINGS

![36a4f15fde01b17118171ba1085ef3c8](https://user-images.githubusercontent.com/67033214/84844671-b4057800-afff-11ea-9e8d-8b1a2b4362d6.png)

**Comment by Nareese** [comment]
The option that controls this feature is called `Emote Menu`.  Ensure that it is turned on.
