### ISSUE TITLE
"Host Button" setting not displaying anything anymore

### ISSUE THREAD

**Issue by thegeees** [night/betterttv#3975]
i have tried turning it off and on again
![image](https://user-images.githubusercontent.com/67125413/85072687-67fa3500-b1b1-11ea-9e84-0c22ce1d10fc.png)
![image](https://user-images.githubusercontent.com/67125413/85072491-1e114f00-b1b1-11ea-8ecd-65036c18edfe.png)
i'm pretty sure the host button that's gone was bttv's, it was useful because i could see who i was hosting and add to autohost
sorry if it's not that one
thanks

**Comment by night** [comment]
It does appear for me, but it's inconsistently appearing.
