### ISSUE TITLE
BetterTTV causes latency in chat

### ISSUE THREAD

**Issue by RdNetwork** [night/betterttv#3978]
For a few days (weeks ?) now, BTTV causes a werd phenomenon on Twitch for me: chat messages are displayed way after they were actually posted. Usually between 3 and 6 seconds, I'd say.

I can clearly see this on streams where the chat is displayed on the streamer's layout: messags appear on the stream before they even appear on my own twitch chat...

The problem seems to disappear once BTTV is disabled and browser is rebooted.

(Windows 10, Firefox 77)

**Comment by night** [comment]
BetterTTV does not post messages to chat, it mutates messages after posted to chat. With that in mind, it's not possible for it to directly cause rendering delays. Streams you watch may have chat delay enabled, which enforces that moderators see chat before normal users.
