### ISSUE TITLE
[Feature Request] Show Profile Pics next to usernames (inspired by Mixer)

### ISSUE THREAD

**Issue by RayBenefield** [night/betterttv#3992]
A lot of streamers like myself are coming over from Mixer and one of the things that I really miss is having profile pictures for each user. It makes visually reading chat so much easier and something that I would love to see as part of this extension. If this is possible, it would make a huge difference for Mixer streamers.

**Comment by night** [comment]
Twitch doesn't provide profile pictures in their chat APIs, so we would not be able to render this user information
