### ISSUE TITLE
[Feature Request] Hide bit emotes from certain channels from the emote menu/emote autocomplete 

### ISSUE THREAD

**Issue by Joseph-kane** [night/betterttv#3993]
With alot of people coming forward lately about certain streamers being abusers, the bit emotes displayed in the emote menu and the emote autocomplete(typing ':' in the chatbox) can be a horrible reminder for many people of the abusers they had supported in the past. Currently bit emotes are permanent and there is no way to ever remove them once you have them unlocked, so it would be great to have a feature to either hide bit emotes from specified channels or an option to just hide certain bit emotes from the emote menu and the emote autocomplete.

**Comment by night** [comment]
You can already hide emotes in BetterTTV's emote menu, but we do not have control over the tab completion that Twitch implements.
