### ISSUE TITLE
Readable Colors

### ISSUE THREAD

**Issue by ScriptedEngineer** [night/betterttv#4001]
Readable Colors bug! BTTV interferes default twitch setting Readable Colors!
![image](https://user-images.githubusercontent.com/42481954/85806907-6ad0c900-b761-11ea-93b2-8dcfd7e01f1d.png)
![image](https://user-images.githubusercontent.com/42481954/85806916-71f7d700-b761-11ea-9c04-91abba241714.png)

**Comment by night** [comment]
We intentionally recolor hard to read usernames.
