### ISSUE TITLE
[Feature Request] Customization of Highlight Color, Font Size, Weight, and Style

### ISSUE THREAD

**Issue by luckofthelefty** [night/betterttv#4003]
As a user, I need to be able to change the highlight color of the keyword feature, so that I can see the text easier in chat.

Currently, the highlight color is only red, and after to talking to some streamers, some of them reported that it is difficult to read the text in darkmode.

BENEFIT HYPOTHESIS:
Adding a color selection will provide a more user friendly interface and allow people who have difficulty seeing the red highlight.

Before
![image](https://user-images.githubusercontent.com/15348451/85821370-5ffc4100-b72d-11ea-8e13-f6a2420e8ceb.png)

After

![image](https://user-images.githubusercontent.com/15348451/85821457-9043df80-b72d-11ea-9577-8cffc36919d5.png)
![image](https://user-images.githubusercontent.com/15348451/85821509-a782cd00-b72d-11ea-98d6-f4228adba72c.png)

Also maybe an option to set font size and weight and style:
![image](https://user-images.githubusercontent.com/15348451/85821688-08aaa080-b72e-11ea-87a1-e5f9cd044ca8.png)

**Comment by night** [comment]
duplicate of #237
