### ISSUE TITLE
(DMCA related) Music player through BetterTTV.

### ISSUE THREAD

**Issue by Weapon404** [night/betterttv#4007]
Here's an idea:

Have a music player built in the BetterTTV extension, which would allow streamers to play music to their viewers (through the extension). This would result in streamers avoiding a DMCA while providing a better auditory experience to the viewers that have BetterTTV installed.

I'm not sure if this would be even possible, but feel free to do anything with this idea.

**Comment by night** [comment]
This doesn't feel like a service that makes sense in BetterTTV, but streamers could use something like plug.dj instead.
