### ISSUE TITLE
Chat Bug 

### ISSUE THREAD

**Issue by Jesolz** [night/betterttv#4014]
As the title suggests, even after the june 21 bttv update my twitch chat is still bugged. I can only see it if i use theater mode.

https://prnt.sc/t9b3bk           here's a screenshot of what i see.

**Comment by night** [comment]
I cannot reproduce that issue, and BetterTTV does not modify the page CSS in a way to make chat look like that. Maybe you have the page zoomed in and need to reset zoom, or maybe you need to clear cookies/cache or uninstall other extensions.

**Comment by Jesolz** [comment]
Thanks for the response, i dislike that u guys tagged my request as "
invalid" , its a very real bug indeed, i dont understand. Anyway, i tried
following your suggestions and none seems to work. It's not about the zoom,
nor the cache, nor cookies. Cleared everything and uninstalled chrome
again. Same bug repeats itself and i cannot type into chat, just as the
screenshot i posted shows. Last option would be to uninstall " other
extensions", would you care to elaborate more on that ? thanks.

Il giorno dom 5 lug 2020 alle ore 23:02 Zack <notifications@github.com> ha
scritto:
