### ISSUE TITLE
Two player-in-player buttons and no way to disable it

### ISSUE THREAD

**Issue by Ockaie** [night/betterttv#4020]
There are two player-in-player buttons and they are black. All the other buttons are white.
![image](https://user-images.githubusercontent.com/19565458/86517412-07adf900-be29-11ea-832e-ec4f5ea99c0b.png)
I can't disable it either, which isn't really an issue. Just a missing feature.

I'm on Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by Ockaie** [comment]
Sorry, this problem was persistent and I was having it for a few months, so I had assumed that other's were also having this issue.
It seems to have disappeared for the first time, but from time to time it reappears when I refresh the page.
I think it had something to do with FFZ having their own PiP-button. There will be three PiP-buttons then.
I'm not entirely sure how to replicate this bug.

**Comment by night** [comment]
icon color is fixed by 98e932ce4610722dd2ae97f5dbdc3154c9dea5b3 

BetterTTV cannot insert two icons into the dom for pip.. since we always check if there exists an element before insertion. you may have another extension running where you need to disable the pip feature or uninstall it.
