### ISSUE TITLE
Hide Recommended Channels

### ISSUE THREAD

**Issue by GreensaPenguin** [night/betterttv#4023]
i have Hide Recommended Channels on but it still is showing them Hide 
i have even reload the page

https://prnt.sc/tdqs75

**Comment by Nareese** [comment]
Can confirm, Twitch released an updated site today that removes the content specific class `.recommended-channels`, and any other content specific identifiable classes.  The only way I can see to address this is an nth-of-type selector, which is fragile.
```
div.side-bar-contents div.side-nav-section:nth-of-type(2) {
    display: none !important;
}
```
I don't know if night would want to use that for that reason.  I include it here for reference and for anyone who wants to use stylus to fix it, understanding it could break at any time.

**Comment by ceiphr** [comment]
Firefox v78.0.1 for Ubuntu 20.04 LTS. Can confirm, same issue.

**Comment by AiSatan** [comment]
Well, for now I added adblock custom rule:

`twitch.tv##.side-nav-section:nth-of-type(2)`

**Comment by ysy1184** [comment]
> Well, for now I added adblock custom rule:
> 
> `twitch.tv##.side-nav-section:nth-of-type(2)`

This filter is working right now. Thank you.
