### ISSUE TITLE
Left-Side Chat.

### ISSUE THREAD

**Issue by FollowSonik** [night/betterttv#4029]
Yo! Excuse me, what happened with left-side chat BetterTTV option?

![image](https://user-images.githubusercontent.com/11148271/87206300-1b1e0000-c312-11ea-9441-74b3d18d6158.png)

**Comment by MoDog0** [comment]
I am having the same issue started about the same time as Sonik opened this issue.
Left side chat results in followed channels etc bar being on the left side with left side chat.
I have recommended channels set to hidden and they are showing up as-well.
