### ISSUE TITLE
BetterTTV fails to load chat correctly

### ISSUE THREAD

**Issue by BlackWhiteX** [night/BetterTTV#403]
Lately BTTV has been having problems, with the chat only loading one line on top and new messages overwriting that single line. I managed to solve it by clearing cache & cookies, but it reappeared after some time on a page refresh. 
![untitled](https://cloud.githubusercontent.com/assets/12122883/7457195/b441c282-f282-11e4-94e4-d236b07b426c.jpg)

**Comment by night** [comment]
This is an age-old sign that you're using some other add-on that is breaking BetterTTV.

**Comment by BlackWhiteX** [comment]
Do you have any idas on which add-on that could be? I haven't installed any recently...

**Comment by cletusc** [comment]
Disable all other addons other than BTTV. Check to see if it works. Enable one-by-one, checking to see if it works after you enable one.
