### ISSUE TITLE
Automatic Hosting While Offline

### ISSUE THREAD

**Issue by ImQreative** [night/BetterTTV#404]
I had an Idea and I want to know if it can come to fruition...
I am streaming for around 2-3 hours a day and the times I am offline, I want to be hosting the people I support...
I dont know if this is against twitch terms so if it is I apologize.
I wanted to know if you could add an option to, when your offline, host a random person that you are following thats online. It might be a tall order, and its just a thought...
Hope to hear from you soon!

**Comment by night** [comment]
Because BetterTTV does not run when you close your browser, there is no easy way for us to handle the hosting of random streams. Bots like [Moobot](https://moobot.tv) offer the ability to randomly host streams when you are offline, so I suggest giving that a look.
