### ISSUE TITLE
Opera Compatibility

### ISSUE THREAD

**Issue by Iovebug** [night/betterttv#4056]
Hiya! Currently testing out Opera GX as it's " gamer browser" (not bad honestly) however some BTTV Functions do not work. Notably the Hide Recommended Channels, Hide Offline Channels, and Hide Friends. Emotes and other options seem to work. 

Copy of my settings attached.
I installed BTTV via https://addons.opera.com/en/extensions/details/install-chrome-extensions/
[bttv_settings.zip](https://github.com/night/betterttv/files/4990722/bttv_settings.zip)

**Comment by Iovebug** [comment]
Link to Opera GX
https://www.opera.com/gx

**Comment by night** [comment]
The features that are not working are just bugs in the extension. Look at the other issues reported at https://github.com/night/betterttv/issues
