### ISSUE TITLE
BTTV Not Working in Stream Manager Chat

### ISSUE THREAD

**Issue by MacDaddyTV** [night/betterttv#4059]
BTTV Stopped working in stream manager a few days ago (its still working on regular channel pages).

BTTV just straight up doesn't show up in chat on my stream manager; I can scroll down, in chat settings, to where BTTV settings should be but there is just blank space (see attached). None of my BTTV settings are being applied and emotes are not working. I have tried pop-out chat but the same issue occurs.

![Chat](https://user-images.githubusercontent.com/69038975/89028366-17cfd000-d324-11ea-82fc-9b6bc2a9ae38.PNG)

**Comment by ThePigguUwU** [comment]
I am having the exact same issue atm. I am joining in hoping to see the solution, if it pops up. But its at least a bit comforting to know this isn't just happening to me.

**Comment by ThePigguUwU** [comment]
why did this get closed!? My Stream manager is STILL not showing BTTV emotes

**Comment by night** [comment]
Because it's fixed in the latest release. Update your extension
