### ISSUE TITLE
Moderator user card actions retain previously selected user

### ISSUE THREAD

**Issue by Civrock1** [night/betterttv#4067]
Noticed this previously but thought it was a fluke, but it happened again today so I figured I'd report it. Unfortunately I cannot replicate it reliably, not sure what the trigger is exactly.

Steps used when it occurred tonight:

1. Click on USER1 in chat; opens USER1's user card.
2. Click on USER2 in chat; opens USER2's user card (replacing USER1's user card).
3. Use 1h timeout button in USER2's user card.
4. USER1 got timed out instead of USER2

**Comment by night** [comment]
this is fixed with 278d4e43298c8dd6938e2f372e1212d92002caa8
