### ISSUE TITLE
[Feature Request] Unfollow without opening stream

### ISSUE THREAD

**Issue by Ugator** [night/betterttv#4068]
It would make uncluttering the following list much easier if I hadn't open the stream page to unfollow streamers I'm not interested in anymore. Similar to the "See all recent videos" that pops up for offline channels.

**Comment by night** [comment]
we might do #2910 but we have no intentions of building new surfaces within Twitch's website of managing your followed channels. You can see your followed channels at: https://www.twitch.tv/settings/notifications
