### ISSUE TITLE
Customize chat position

### ISSUE THREAD

**Issue by NoZomIBK** [night/betterttv#4074]
At the moment i can have the chat left or right of the stream or popped out. But when i move twitch to my secondary (vertical) screen, the stream is too small with the embedded chat and always popping the chat out is annoying.
it would be nice to have the option to move the chat below the stream, if the window width is smaller than the height.

**Comment by night** [comment]
this is quite difficult to do with Twitch's page due to how they render things. The only reason we accomplished a flipped view is due to how browsers allow that with styling.
