### ISSUE TITLE
[Feature Request] Show in-game ranks in twitch chat

### ISSUE THREAD

**Issue by ukupcjik** [night/betterttv#4079]
Hello, I really think what this is a good idea! You must add this feature =) Users link their accounts dotabuff\opendota\overbuff\cs go ranks etc with twitch and in chat near usernames show  in-game ranks? or maybe in a pop-up window

BlessRNG

**Comment by night** [comment]
While this is a neat idea, I don't think this is a good feature for BetterTTV as it falls outside the scope of which BetterTTV operates.
