### ISSUE TITLE
TWITCH NICK

### ISSUE THREAD

**Issue by AzaylOFF** [night/betterttv#4082]
Colors of nicknames in chat are changing

For example: Red = Orange Cyan = Blue
![photo_2020-08-10_21-52-10](https://user-images.githubusercontent.com/69480237/89819263-c9a4a300-db53-11ea-95f4-c647b651e4e9.jpg)
![photo_2020-08-10_21-52-38](https://user-images.githubusercontent.com/69480237/89819281-d1fcde00-db53-11ea-815f-2f39091efef7.jpg)
I have a red nickname

**Comment by night** [comment]
this is working as intended. we change the color slightly on hard to read names to improve readability
