### ISSUE TITLE
Cant use emotes

### ISSUE THREAD

**Issue by Valeria099** [night/betterttv#4085]
betterttv and Frankerface emotes dont work, they dont show up. I picked my emotes that i wanted but in the cat there is no section called betterttv.. sooo I can't use em

**Comment by Currey958** [comment]
Yeah I cant use emotes as well. I tried uninstalling and the reinstalling the extentions but that didnt help either.

**Comment by night** [comment]
I am not able to reproduce any issues with emotes.
