### ISSUE TITLE
Allow disabling Click to Reply

### ISSUE THREAD

**Issue by Eppu** [night/betterttv#4088]
In a recent update Twitch added a feature where users can click on any message in a chat, which then allows them to directly reply to a message, starting a new discussion thread. 

![kuva](https://user-images.githubusercontent.com/12832880/90162753-c7ce2000-dd9d-11ea-9968-85972e06e746.png)

However, the feature also effectively blocks things like highlighting text in a message, and also increases the amount of misclicks (at least for me, running Firefox 79.0 on Windows 10). It would be great if the option to disable the click-to-reply feature could be considered for BTTV as well.

Sorry if this is a duplicate!

**Comment by kevinjpetersen** [comment]
It also adds annoying icons to the left of it! I'd be nice to disable that too!

![image](https://user-images.githubusercontent.com/1038017/90275455-a2571a00-de62-11ea-9bf3-3a264ebeb5b8.png)
