### ISSUE TITLE
[BUG] PiP icon appears broken

### ISSUE THREAD

**Issue by NBruderman** [night/betterttv#4089]
It became a white line for some reason

![Untitled](https://user-images.githubusercontent.com/6445601/90183469-35894480-ddbc-11ea-9459-08c618ff233c.png)

**Comment by tinchox1717** [comment]
the icon is backm dont know what you did OP but i cant remove it.

**Comment by whitecrownclown** [comment]
@tinchox1717 The PiP button is shown if the browser supports picture in picture. There's no configuration toggle for it in BTTV.

**Comment by andrew1-1** [comment]
I have same issue as OP, white line instead of the normal PiP icon. It's been like this since the past couple of days
