### ISSUE TITLE
(Not an issue but rather a suggestion) How about a search bar?

### ISSUE THREAD

**Issue by TheSunPraiser** [night/betterttv#4091]
There's a search bar for the "Shared Emotes" but that category doesn't have the Emotes I'm looking for. I want to add the YEP emote to my stream but it's only available if I scroll for hours through the "Top Emotes" or the "Trending Emotes" when I should just easily be able to search for the emote I want.

**Comment by night** [comment]
Due to how trending and top emotes are generated we are not able to perform a search on them at this time. Both of these lists are actually derived from shared emotes though, so you should be able to search for the same emotes by using the shared emotes search.
