### ISSUE TITLE
Recommended Channels

### ISSUE THREAD

**Issue by Baaliefiy** [night/betterttv#4092]
I have Hide Recommended Channels switched on but it's still showing recommended channels in my side bar.
Screen grab added.

![recommended](https://user-images.githubusercontent.com/21089186/90238819-70bc5f80-de1e-11ea-9683-438b5d4054fe.PNG)

**Comment by Nareese** [comment]
duplicate of #4023

**Comment by MBoBr** [comment]
Same.
