### ISSUE TITLE
Add setting for Clear Chat handler and default to false

### ISSUE THREAD

**Issue by brandinarsenault** [night/betterttv#4095]
The /clear command is a powerful moderation tool that can be used to very quickly deal with a lot of moderation issues in a chat. We encourage many users to use BTTV, and we remove one of our moderation tools by doing so. The CLEAR_CHAT case in BTTV (index.js line 49) is hardcoded without a setting. We should add a setting toggle for this case and only prevent the default action if the setting is set to on. This setting should be toggled off by default, so we can continue using this moderation action.

Thank you for your consideration.

**Comment by night** [comment]
https://github.com/night/betterttv/pull/4096#issuecomment-683368383
