### ISSUE TITLE
Please add option to hide the "channel leaderboard" above chat.

### ISSUE THREAD

**Issue by kedryte** [night/betterttv#4098]
The area that says "Cheer now to be #1!" and "Gift a Sub now to be #1!" takes up a lot of room, especially in narrow browser windows. Can we get an option to hide it?

The relevant CSS class is `.channel-leaderboard` I think.

**Comment by Nareese** [comment]
We hide the channel-leaderboard container when the option `Hide Bits` is on, so you can use that if you like.  If that will hide bits related things you don't want hidden, I would suggest using a user styling tool like Stylus to hide that class yourself.
