### ISSUE TITLE
Disable Host Mode — Disables hosted channels on Twitch

### ISSUE THREAD

**Issue by Smeagol001** [night/betterttv#4099]
seems to not work with the chrome extension atleast  i have it "on" but i allways see me joining streams of ppl i not initially watched when the streamer i watched ends their stream

**Comment by Nareese** [comment]
duplicate of #3933 

specifically, see this comment from night: https://github.com/night/betterttv/issues/3933#issuecomment-653938325

Also, this feature doesn't do anything to disable raids, which is the far more common way of moving people to a different channel after a stream ends these days.
