### ISSUE TITLE
Question about browser extension manifests

### ISSUE THREAD

**Issue by akjetma** [night/betterttv#4103]
Hello, I'm just wondering out of curiosity: where are the manifest files located for various browser envs? I'm not very familiar with writing browser extensions, was just wondering how you interface with firefox/chrome etc. 

edit: i should note, i understand that this is browser-agnostic code that gets retrieved from cdn and injected into the page when the browser navigates to a twitch domain, i'm just wondering how this is distributed to extension marketplaces.

**Comment by night** [comment]
BetterTTV is not open source software, so we do not include configuration for redistribution in our repo.
