### ISSUE TITLE
Host Button Disappears

### ISSUE THREAD

**Issue by chrisjsy** [night/betterttv#4104]
occasionally the host button will disappear and I will have to go into better Twitch TV settings turn it off and turn it back on again for it to reappear it's not a massive issue but I would just like to point out that it is happening occasionally

**Comment by Valsis-sf** [comment]
This has been happening to me as well for at least a month.
The button suddenly disappears and, often times, when you go to a new channel, the button doesn't show up. I have to go to the BTTV settings and disable/enable the button for it to show up.
