### ISSUE TITLE
Watcher issues with new channel pages?

### ISSUE THREAD

**Issue by Nareese** [night/betterttv#4105]
While looking into something yesterday, I noticed there were some watchers not firing, so I decided to check them all under as many channel page use cases as I could think of today.  Three watchers are involved in the channel page.  load.channel, load.chat, and load.player.  I tested with the new offline "landing page", clicking "Chat" through from there to the "real" channel page with chat, as well as loading the initial page for an online channel, which bypasses the "landing" page.  

watcher results from various tests:

Load offline channel page (landing page)
load.chat: fires
load.channel: fires
load.player: times out (even though there is ostensibly a player on this page)

Same results if you refresh the offline landing page

Click through "Chat" to normal channel page
route change is detected, but currentPath === lastPath, so routeObeserver returns doing nothing.
no watchers fire

Same thing if you click on the user's avatar from an online channel to go back to the landing page... route change is detected, but because the path doesn't change, no watchers fire.

Refresh normal channel page
load.chat: fires
load.channel: times out
load.player: fires

Initial open online user
same as refreshing offline normal channel page:
load.chat: fires
load.channel: times out
load.player: fires

The main issue here is load.channel not firing a lot of the times when it probably should.  I don't know if this is actually affecting anything, because the only things that currently watcher.on('load.channel') are the host_button, which also on's load.chat, so it gets it one way or the other, and watcher itself, which watches it in channelObserver, but again, also watches load.chat.

Anyway, again, I don't know how much of an issue any of this is, but I noticed them timing out, so I thought I'd document it for whoever has time to look into it more deeply and see what if anything needs fixing.

**Comment by night** [comment]
this isn't a major issue.. the timeout results in the load still occurring, but it was slow. i improved the predicates in 278d4e43298c8dd6938e2f372e1212d92002caa8 but you will still see this from time to time (when state is not changing in a route update).
