### ISSUE TITLE
[Feature Request] Automatically changing video speed based on displayed buffer

### ISSUE THREAD

**Issue by StoneColeQ** [night/betterttv#4121]
I made a similar request a while back but it was worded poorly: https://github.com/night/betterttv/issues/4078#issue-674676869

What I want is a script that can read the current buffer then change the video speed to compensate, not changing the buffer itself. Regular html5 video speed controllers works on the player but I would prefer an automatic way to sync multiple streams.

**Comment by night** [comment]
there's no reason to make a new request. your comments are seen still on the old request
