### ISSUE TITLE
Auto !play and other commands

### ISSUE THREAD

**Issue by Lucas559-noob** [night/betterttv#4124]
Some streamers that I follow make marbles on stream, so it would be nice if it automatically sent a message with `!play`, I've already seen a script that activates if the game marked in the stream is marbles on stream and not another, and also custom commands, which follow the same logic as marbles in stream, but without this game, or after some message in the chat (since the command will be for a streamer bot minigame).

**Comment by night** [comment]
While this is a neat idea, I don't think this is a good feature for BetterTTV as it falls outside the scope of which BetterTTV operates.
