### ISSUE TITLE
BTTV Button Disappeared After Clearing Browser Data

### ISSUE THREAD

**Issue by maxlimitz** [night/betterttv#4125]
In Google Chrome 84 I cleared browsing data (history, cookies, cache and everything else) for one Google Chrome user (Max) and the BTTV button for emotes disappeared for all Google Chrome users (Max, Steve and others). OS X 10.11.6 (El Capitan).

**Comment by night** [comment]
You need to enable the "Emote Menu" setting in the BetterTTV settings.
