### ISSUE TITLE
Recommended channels on sidebar seem to have come back

### ISSUE THREAD

**Issue by wormosteeze** [night/betterttv#4127]
![image](https://user-images.githubusercontent.com/18333790/92028321-b29f3e00-ed18-11ea-91a9-924f107dc535.png)

I have made sure to toggle off/on, toggle off reload, toggle on reload. Am I the only one having this issue? I am on 7.2.86 which appears to be up to date.

**Comment by Nareese** [comment]
This would appear to be a bug related to the sidebar being collapsed.  As a temporary workaround, if you open the sidebar and refresh. that will clear the clutter, and then you can close the sidebar again, and they will stay gone... until you refresh with the sidebar closed again.
