### ISSUE TITLE
Twitch and BTTV errors

### ISSUE THREAD

**Issue by ISTmiguel** [night/betterttv#4128]
I've been having problems  the last few days with BTTV (it doesnt appear in twitch settings) and also twitch itself , error 2000 which stops loading the video every few min which makes me to have to refresh it very often.

ive tried to disable extensions one by one but it was a bit inconclusive (sometimes twitch worked sometimes not, and bbtv usually didnt work at all) so i disabled them all and twitch was working, but i obviously didnt have bttv extension anymore so no bttv settintgs.. I also cleared my cache and cookies multiple times.. so after a couple of hours trying i disabled everything
After this, and so far.. error 2000 disappeared so im figuring it might have to do with extensions. I also re installed bitdefender.. (i had no problems before) and tried to add an exception for twitch.tv

But now I installed BTTV only and it still doesnt show on twitch settings.. so what might be the problem? I opened up my javascript console so i could share with you (screenshot below)
https://prnt.sc/uajt1w
https://prnt.sc/uajvxw

Can anyone help me with this? Sorry if my english wasnt very great, tried my best.

Miguel

**Comment by night** [comment]
There are no errors in those screenshots pointing to issues with BetterTTV. Unfortunately it's not clear what specifically is not working with BetterTTV, but you should be able to find BetterTTV's settings under the user dropdown in the top right of the website or within the chat settings when on a channel page.
