### ISSUE TITLE
Recommended Channels Always Hidden

### ISSUE THREAD

**Issue by gregs007** [night/betterttv#4130]
I have "Hide Recommended Channels" disabled (I like seeing recommended channels). For past few days I haven't been able to get them to show. The only solution is to disable the BetterTTV chrome extension.

Windows 10, latest version, Chrome 85.0.4183.83 64-bit

**Comment by gregs007** [comment]
I guess the chome extension is deprecated when you're using Frankerface and enable the BetterTTV addon within that addon? Confusing to say the least. Removed the chrome extension and now everything is fine. BetterTTV emotes work. Considering the BetterTTV website encourages you to download the extension as soon as you arrive, it might be wise to clue people into this nuance.

**Comment by Toesbeforebro** [comment]
Did you figure out how to fix it?
