### ISSUE TITLE
Subscriptions button in collapsed in menu mode

### ISSUE THREAD

**Issue by inooid** [night/BetterTTV#414]
I am not sure if this is intentionally, but it would be really useful to me if there could be a 'subscriptions' button in the menu whenever the menu is collapsed in. I am watching Twitch on my smaller second monitor, so I always use the collapsed in menu, so I have more space for the stream and chat.

When it's collapsed out, the 'subscriptions' button is visible.
![before](https://cloud.githubusercontent.com/assets/1291263/7607159/78731060-f95f-11e4-9f62-b2c13988ce17.png)

When in collapsed in mode, the subscriptions button is invisible. 
![after](https://cloud.githubusercontent.com/assets/1291263/7607376/1a36b6ee-f961-11e4-8d5c-9165e64957e3.png)

**Comment by inooid** [comment]
It turns out this is something that is made by Twitch default and not BetterTTV specific. Thought it might be useful to some users, so will see if I can make a pull request to still add a link to subscriptions. Your call though @night, if it's beneficial enough to add.

**Comment by night** [comment]
I mean, it's not really a necessary page in my opinion. The pages I access every time I'm on Twitch are the following page and the directory, which Twitch already has covered in the sidebar. The subscriptions page is pretty much only useful for managing your existing subscriptions, which explains why Twitch doesn't prioritize it. I'm gonna mark this wontfix for now.
