### ISSUE TITLE
Chat not loading

### ISSUE THREAD

**Issue by Racer10** [night/betterttv#4147]
BTTV: 7.2.76
Microsoft Edge: 85.0.564.51

For some reason if I install BTTV Twitch chats just don't load for me and I can't send messages. This applies to all channels, dashboard view, and mod view.

If I clear my browser cache chat loads for about 5 minutes then messages stop coming in and I can't chat anymore.
Removing BTTV then refreshing the page instantly resolves but installing again does the same as clearing cache, 5 minutes then no more chat.

Already tried disabling all other extensions as well and this seems to have no impact.

**Comment by meafloaf** [comment]
Having the same issue

**Comment by Lucas559-noob** [comment]
When it happened to me I deactivated a script called twitchtoolbox and the chat started showing again, I think is because 2 things are trying to change the same thing, and then it cancel the load of chat

**Comment by night** [comment]
I am not able to reproduce this. I would recommend recording a video and opening the browser console in the video so we can see errors that occurred.
