### ISSUE TITLE
Cannot login on Brave Browser 

### ISSUE THREAD

**Issue by TeitokuIppan** [night/betterttv#4149]
When attempting to login to your Twitch account on BTTV, it'll go through the Twitch authorisation stage but then afterwards, it does not actually login. It'll get stuck on a constant repeating loop of logging in, authorising and then asking to login again.

This is on Brave Browser Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit) on Windows 10 64 bit.

**Comment by night** [comment]
i'm not able to reproduce this behavior. Usually these kinds of issues are related to temporary errors either on our end or Twitch's.
