### ISSUE TITLE
Images, Gifs and videos in chat like at Hitbox

### ISSUE THREAD

**Issue by Oblimix** [night/BetterTTV#415]
Has probably been requested a billion times already, but thought I'd give my opinion on what Hitbox does great and what Twitch is lacking.

Some channels love sharing images and gifs in order to have a laugh, and I'm sure a lot of people would love to have this feature enabled on twitch too.

Having it disabled by default would probably be best, and possible to enable whenever you feel like it.
Channel owner could then specify permissions, like owner only, mods only, or if everyone could use it. 

Of course, I'm not even sure if it's possible to make, but I'm throwing it in here.

**Comment by night** [comment]
While this might be cool on smaller channels, any channel with an active chatroom would make this a terrible feature. You can already mouseover image/gif/gifv links in chat to get a preview, if you desire.
