### ISSUE TITLE
Why does the Emotes not show up when i add them?? 

### ISSUE THREAD

**Issue by shepyboi** [night/betterttv#4150]
i can add 15 Emotes to my Channel but they wont show me in the list and i cant use them, idk what i can do i reinstalled everything but same problem

here are to screenshots, i have 12 emotes added to the list but, 2 emotes are showing me that i didnt add in xD

https://prnt.sc/ul8fmr

**Comment by night** [comment]
Broadcasters assign their own emotes for their own chat. Emotes you add to your channel only show up in your channel's chat on Twitch. You are likely seeing the 2 emotes the broadcaster you're watching added to their chat.
