### ISSUE TITLE
Font size is too big...

### ISSUE THREAD

**Issue by zikhem** [night/betterttv#4151]
I dont know if this has happened to someone else, but, with the BetterTTV settings, you can change the font size, I changed it too much and now ts TOO BIG so now I cant even chat nor access the settings to revert the font size, as you can see... I need a fair amount of help... (Also, if I reinstall the BetterTTV extension, it is the same)

**Comment by Lucas559-noob** [comment]
you can access the options? can go to set font size? try opening the chat in popout and make it full screen

**Comment by zikhem** [comment]
How can I open the chat in popout?

**Comment by zikhem** [comment]
nope, I cant access the options because the letters are so big they take up the entire chat and the chat bar (with the options) goes under the chat and becomes unclickable, so no, I cant change the font size again to revert it

**Comment by night** [comment]
if you're unable to revert your settings you can always clear your cookies, which will reset the BetterTTV settings back to their defaults.
