### ISSUE TITLE
Add Annual and Lifetime Price alongside the Monthly Price

### ISSUE THREAD

**Issue by DIGITALv7** [night/betterttv#4154]
Hello. I was wondering if you could add an annual price alongside the monthly prize for BTTV. It'll be better for many people to just make a 1 time payment for 12 months or add a Lifetime price which I'd like to have. Thank you for your time and help. I appreciate it.

**Comment by night** [comment]
Thanks for the request. We've now added a yearly plan to the website, which is available at https://betterttv.com/dashboard/pro
