### ISSUE TITLE
Discord Connection Sync

### ISSUE THREAD

**Issue by Not-Arcane** [night/betterttv#4156]
When I disconnect the bot from Discord via the Dashboard, the button does not update. I need to reload my web page for it to update so I can re add the bot to my Discord server.

**Comment by night** [comment]
it does disconnect, but if you have many emotes it may take some number of seconds to disconnect. clicking disconnect multiple times will effectively do nothing, since the task is already running. we'll update this in the next dashboard deploy to improve the button to give a loading state
