### ISSUE TITLE
user settings dropdown missing

### ISSUE THREAD

**Issue by cavemanbash** [night/betterttv#4161]
thought it was me so reinstalled it, the addon installs shows for the first half a minit in the cog on twitch then dissapears and all its functions go along with it. Have to reopen twitch and it sometimes returns briefly but mostly not
![bttvev1](https://user-images.githubusercontent.com/72073690/94542576-e0f13a00-0240-11eb-896f-64e9b7268c52.PNG)
![bttvevi2](https://user-images.githubusercontent.com/72073690/94542626-ed759280-0240-11eb-9afe-c528c94325d8.PNG)
![bttvevi after refresh](https://user-images.githubusercontent.com/72073690/94542655-f6fefa80-0240-11eb-868a-50cf22caaa7b.PNG)
![10 seconds after refreshing](https://user-images.githubusercontent.com/72073690/94542678-fbc3ae80-0240-11eb-8d4e-9bc8ca1dfb90.PNG)
images show install settings ,not showing, refreshed, 10 seconds after refresh

**Comment by night** [comment]
i can tell betterttv is loaded since the chat shows badges as rounded. it looks like the setting menu option is just missing.
