### ISSUE TITLE
BTTV emotes doesn't apear partly

### ISSUE THREAD

**Issue by Mariogomez123123** [night/betterttv#4162]
Hey!

I uploaded a couple of months ago some emotes in BTTV and they appeared normal in the chat. Today I uploaded a couple more emotes, but they don't show in the Chat when I use the Emote code. They are clearly uploaded and I waited for 30 minutes (maybe it takes some time to process). Does the Emotes need longer to upload or is this a bug?
Thanks in advance!

**Comment by night** [comment]
You need to refresh the page for the emotes you added to become available in your channel's chat.
