### ISSUE TITLE
Youtube Support

### ISSUE THREAD

**Issue by RustedBuckett** [night/betterttv#4163]
It would be great if BetterTTV also supported Youtube livestreams. Currently there are a few options, however -> Doesn't support Firefox :((

**Comment by Notabotnev** [comment]
I for one would love to see this added in the near future. There are a crap ton of users on youtube, and I'm sure the use of emotes would make things a lot more accessible and fun for some. Of course there is the logistics to consider as well. Supporting another site would be pretty expensive, as far as hours sunk into the code goes.

**Comment by cnodi** [comment]
would be nice if bttv also comes on youtube because i don't watch twitch that often 👍

**Comment by JudahDeNose** [comment]
Look, I know it’s called Better **Twitch** TV, but YouTube Live Streams gain a larger market share every year. I would love to see support for BTTV to come to YouTube. One of the best parts about Twitch is the emote culture, and I would love to see that come to YouTube. Currently there is no good alternative to BTTV for YouTube, making you uniquely poised to become that.

Live Streamers continue to jump over to YouTube, and even more are getting started there. It is only a matter of time before someone develops Custom Emote Support on YouTube, and I believe it should be you.

[From this article](https://blog.streamlabs.com/streamlabs-and-stream-hatchet-q4-live-streaming-industry-report-a898c98e73f1), you can see that YouTube Live Streams are growing, and growing fast.

[In Devin Nash's new video](https://youtu.be/rM4uuotgpmA), he talks about how YouTube Chat is very different from Twitch Chat, which is off-putting to streamers approaching the platform. I think BTTV would help with the transition that many streamers are taking. 

Thank you for coming to my Ted Talk.

**Comment by arrowgent** [comment]
with the new update, we also need a way to link our youtube account to BTTV.  preferably a dual link to a single account?
twitch + youtube in one account on BTTV
other services can do similar

**Comment by night** [comment]
fixed via https://github.com/night/betterttv/commit/b544aee0395f04af17521fd936b79da9a0755b94

@arrowgent there will be a way to link a YouTube account on the BetterTTV website soon. It’s blocked on approval from Google.
