### ISSUE TITLE
How to remove deleted messages?

### ISSUE THREAD

**Issue by subz390** [night/betterttv#4165]
Please help, I've tried several ways to remove deleted messages and nothing works.
See screenshots below for details.

Configure setting to `Remove Deleted Messages` however deleted message remains.
![201001-152014 Remove Deleted Messages not working as expected](https://user-images.githubusercontent.com/11546815/94821891-fcec0b80-03f9-11eb-8a77-1e392507cefc.png)

Blacklist configured to remove deleted messages
![201001-145403 blacklist keywords](https://user-images.githubusercontent.com/11546815/94819156-d5477400-03f6-11eb-927d-4774d83d02d2.png)

However nothing happens, the messages still remain in chat
![201001-145212 blacklist not working](https://user-images.githubusercontent.com/11546815/94819263-f4460600-03f6-11eb-99dc-5780c834a440.png)

**Comment by KL13NT** [comment]
It seems there's an extra full-stop `.` at the end of the actual message, when there isn't one in your blacklisted phrase, could you try adding it? @subz390

**Comment by subz390** [comment]
Ok I'll test this, but including the full-stop doesn't make any sense (to me).

1. Why wouldn't `Remove Deleted Messages` in settings be sufficient or is this for something else?  or am I missing out having to reboot, change channel, flip some random thing everyone else but me knows to do because it's obvious to the universe except me that's why it's not explained anywhere, kind of thing.

2. and why should matching the whole message in Blacklist matter?  It's designed to be partial matching due to the natural organic nature of messages in chat, I mean unless you've figured out how to predict what everyone is going to say all the time, how can you expect us to blacklist complete messages.  So unless I missunderstand the syntax of `{<>}`  why should including the full-stop even matter?  I could just as well use `{<message deleted>}`.

**Comment by KL13NT** [comment]
I can answer for number 2 only, I'm not a maintainer after all. 

In the instructions it says `Use {} to form a phrase, use <> inside {} to use *exact* search`. Exact search matches *exactly*, meaning it wouldn't match if there's a 1 character of difference between your blacklist and the sent message. I'd suggest removing the `<>` around the phrase, that way it'll match any message that *includes* the given phrase, without *exactly* 100% matching it.

**Comment by subz390** [comment]
ok I understand.  I think `Remove Deleted Messages` option is working, can't tell really as there's no way I can see how to except that I don't see the messages in chat, however it's not a case of switching it on they dissapear, switching it off they reappear, it's like you switch it on, they still there... and mysteriously the next time you login, at some random time in the future, maybe chat is behaving, or maybe it's still toxic and it's working.  The idea is solid, however the implementation and UI is terrible.
