### ISSUE TITLE
[Request] Option to revert font

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/betterttv#4169]
This new font is wide and hurts my eyes looking at for extended period of time.  Would be cool if we had the option to choose Roobert (the old font).

**Comment by Nareese** [comment]
Yes, they released an update yesterday that adds the font "Inter" to the front of the global fonts list with their :root css variable `--font-base`.  I don't know if this is something that night would want to override (and currently there is no easy way to make this an "option" that people can customize as they choose).  In the interim, or as an alternative, people who find the new font objectionable (and I completely agree!) can use a custom CSS override tool like Stylish to override their variable definition
```
:root {
    --font-base: Roobert,"Helvetica Neue",Helvetica,Arial,sans-serif !important;
}
```
to revert this change.

**Comment by night** [comment]
You can configure the chat font in the chat settings, but site-wide fonts are a bit tricky to maintain reliably. If you're hard pressed I would recommend Nareese's suggestion.
