### ISSUE TITLE
Large space between lines in chat when I change font size

### ISSUE THREAD

**Issue by GoRnoStayStandin** [night/betterttv#4170]
It happens a month ago and I thought that it's problem with my computer or browser. But after reinstall plugin and browser the problem was not solved
![12](https://user-images.githubusercontent.com/57696403/95006338-298c6700-0636-11eb-9f23-57514a79047c.jpg)
![13](https://user-images.githubusercontent.com/57696403/95006339-2abd9400-0636-11eb-9739-d28b2c2cda9e.jpg)

**Comment by Nareese** [comment]
This is intentional, to prevent the bug described in #4054.
