### ISSUE TITLE
Even more emotes!

### ISSUE THREAD

**Issue by grandmazc00kies** [night/betterttv#4173]
Would be amazing to see even more emote slots for the long time supporters 100 is amazing for uploads and general slots but would be awesome to see it keep going up. Maybe more personal emotes and general/upload slots never enough emotes can be used!

**Comment by night** [comment]
We combined the shared + channel slots to give users overall more emote slots. You can also upload extra emotes just to your inventory, making it easier to swap emotes out and keep older emotes around without deleting them.
