### ISSUE TITLE
fullscreen emote menu

### ISSUE THREAD

**Issue by ellysfrinzi** [night/betterttv#4175]
When I open the betterttv emote menu, it opens in fullscreen mode, if I try to click the arrows that adjust the size I can only move it to the left of the screen, up or down. Please help.

**Comment by thatspogger** [comment]
Same

**Comment by OpenThatVodka** [comment]
same

**Comment by SlightlyZelus** [comment]
Same

**Comment by corgrath** [comment]
I have the same problem.

I am on Firefox 81.0.1 (64-bit).
Problem started with the October 5th update (today).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/472514/95130664-35bf1400-075d-11eb-84d0-61f85ee1c6e1.gif)

**Comment by trashy-cloud** [comment]
I have the exact same issue. 

It starts off in fullscreen and has a horizontal scrollbar on top. If you try and slide it, the top of the emote menu "shifts" behind the chrome search bar and the emotes cant be accessed which are located there. 

One can resize the menu but it is stuck to the top left side of the window and one can only shift it towards there or fullscreen it. 

It happened just now, I zoomed in to my chrome window with my touchpad and when I zoomed out to normal size the menu started doing this. 

I tried restarting my computer, switching the extension on and off, reinstalling bttv, and also turning on and off most settings in the bttv settings menu.

**Comment by Marshazzle** [comment]
Likewise. The menu opens a full screen menu of all channel emotes with no proper scrolling or resizing.

**Comment by nabfel** [comment]
Same

**Comment by Rednawander** [comment]
is there already a prediction for them to fix this bug? of the menu cover the screen?
