### ISSUE TITLE
Emote Menu takes up entire screen (Version 7.2.88)

### ISSUE THREAD

**Issue by poopdiq** [night/betterttv#4177]
![image](https://user-images.githubusercontent.com/72418666/95138152-c7f7f580-0726-11eb-9e67-2b17464dd593.png)
As of Version 7.2.88, the emote menu no longer takes up a small closeable window on top of Twitch chat, but opens a full screen menu that can't be closed unless you click on an emote.

**Comment by night** [comment]
This is already fixed. Please update your browser extension
