### ISSUE TITLE
Emote Menu opens up in a fullscreen format when it shouldn't

### ISSUE THREAD

**Issue by Araelynn** [night/betterttv#4178]
For whatever reason, when I click the button to open the emote menu it will open up and cover my entire screen. 
If I'm in a moderator view for a channel I moderate for, and I click the top bar to try to reposition it, it will vanish until I refresh the webpage. 
Resizing it does nothing but make the top bar disappear behind the address bar at the top of Chrome. 
When I refresh the webpage it defaults back to the fullscreen one, which when NOT in a moderator view of a channel, can be resized/repositioned but it never saves the position and will return to a full screened version once the page has been refreshed.
I've cleared my cookies and cache, resetting all of my settings to default, which fixed nothing.
I don't know what else I should say about this issue, but I couldn't find anything about anyone having this same issue as me.

**Comment by blurryflor** [comment]
I am also having this issue on Chrome!

**Comment by night** [comment]
This is already fixed. Please update your browser extension
