### ISSUE TITLE
"Disable VoD Recommendation Autoplay" not working in firefox

### ISSUE THREAD

**Issue by k0zyrev** [night/betterttv#4180]
firefox 81.0.1 
bttv 7.2.89

If I open any offline channel, I'm getting a vod autoplaying and on the contrary, if I open an offline stream, it won't start autoplaying when the stream actually starts, I'd have to reload the page.

edit: I have several accounts, and on two of  them vods start to play no matter what, for the others - vods don't autoplay no matter if the option enabled or not. (tested with firefox containers if that's of any importance)

**Comment by night** [comment]
VoD recommendations are the videos Twitch queues up after you finish a VoD, so this feature actually doesn't control that behavior.
