### ISSUE TITLE
Add option to disable chat stop on ctrl

### ISSUE THREAD

**Issue by k0zyrev** [night/betterttv#4181]
Use-case: changing keyboard language in ctrl+shift in windows, using ctrl+shift+[button] as global hotkey for other applications. Sometimes I'd press ctrl intermittently and unintentionally stop chat scrolling.

**Comment by CoolCmd** [comment]
also `ctrl+w` closes browser tab.

**Comment by Meowvalent** [comment]
This also affects mac with "cmd" keys

**Comment by romestylez** [comment]
Yes please ! This feature is just annoying. Also when using the Windows key the chat stop.

Please give us an option to disable this. After i found out its BetterTTV related i deactivated the plugin as im using STRG and the Windows key also very regulary its annoying when the chat stopped everytime.

**Comment by PaulDoesDev** [comment]
Yeah this is really annoying when switching windows with CMD + Tab on Mac or tabs with Ctrl + Tab on Windows. Please add an option to disable it

**Comment by romestylez** [comment]
Pleaseeee add this feature its so annoying chat stops everytime youre using Windows key or CTRL :(
