### ISSUE TITLE
Hide Recommended Channels not working.

### ISSUE THREAD

**Issue by vycktor06** [night/betterttv#4183]
Title. BTTV 7.2.89 - Chrome 86.0.4240.75.

![v3g5gfA](https://user-images.githubusercontent.com/58626434/95352403-9737cd80-0898-11eb-874d-13291ffb234f.png)

**Comment by heeheex2** [comment]
Seems like twitch is replacing it with "Popular Channels"? Or at least that's what mine just changed into a few hours ago. No way for me to see recommended channels at all, I assume this has to do with that. (Also a way to remove the popular channels column would be a nice feature :) )

**Comment by kajoken** [comment]
Same issue here with Firefox
BTTV v7.2.89 - Firefox 81.0.2 (64-bit)
![twitch](https://user-images.githubusercontent.com/72881333/96018926-20787280-0e4c-11eb-8175-5658a4f2c570.png)

**Comment by Aaron128l** [comment]
The issue only exists in the narrow icon view. The selectors will need to more *precise* all the icons classes are the same.

**Comment by PaulDoesDev** [comment]
Also seeing this

**Comment by Px05119** [comment]
This is now an issue for me running Chrome 87.0.4280.141 x64 as well as Chrome 88.0.4324.96 x64. Both browsers running BetterTTV 7.2.91. Expanding the sidebar then toggling the setting will temporarily fix the issue, but it still breaks when a new page is loaded with a collapsed sidebar.

**Comment by Hexerin** [comment]
Still an issue on Firefox. Aaron128l appears to have #4425 as a solution, will that be added to the extension in an update?

**Comment by solemn-core** [comment]
Still not working on chrome 98.0.4758.81

**Comment by blehdadsfa** [comment]
I figured it out.

Expand the sidebar.  Reload the page.  Recommendations go away.  Minimize the sidebar.

**Comment by ToeiRei** [comment]
As soon as the sidebar collapses, things go haywire.
