### ISSUE TITLE
BTTV emote menu

### ISSUE THREAD

**Issue by Oliverfx1234** [night/betterttv#4184]
The botton to open the emote menu dont apear under my twitch chat 
![Udklip](https://user-images.githubusercontent.com/72624265/95615472-95bcff80-0a68-11eb-8571-e0de769054a0.PNG)

**Comment by Jelle303** [comment]
having same problem here

**Comment by scarletnerded25** [comment]
I'm also having this same problem.

**Comment by kc1r74p** [comment]
@Oliverfx1234 @Jelle303 Did you check that in the settings cogwheel-> BetterTTV Settings, that you have the "Emote Menu" enabled?
![grafik](https://user-images.githubusercontent.com/7422353/96027449-2ffdb880-0e58-11eb-9669-e90125332fe5.png)

I also currently have the issue that it works on twitch.tv, but on embeded palyer/chat the popout emote menu is not visible.
But this may be unrelated to this.

**Comment by Oliverfx1234** [comment]
> @Oliverfx1234 @Jelle303 Did you check that in the settings cogwheel-> BetterTTV Settings, that you have the "Emote Menu" enabled?
> ![grafik](https://user-images.githubusercontent.com/7422353/96027449-2ffdb880-0e58-11eb-9669-e90125332fe5.png)

![Udklip](https://user-images.githubusercontent.com/72624265/96040899-4a8d5d00-0e6b-11eb-934c-441f454b1178.PNG)
Here you can see my settings

**Comment by night** [comment]
scroll down and enable the option quite literally named "Emote Menu"
