### ISSUE TITLE
Font settings broken

### ISSUE THREAD

**Issue by TooManyAccountsToRemember** [night/betterttv#4186]
Font settings are busted. I was able to size up, but can't size down. Very inconvenient.

**Comment by xgerhard** [comment]
Hiya, what do you mean you can't size down, what is happening? Seems to work fine here.

**Comment by TooManyAccountsToRemember** [comment]
I can size up the font but it won't go back down, and the scale breaks
using settings in chat.

**Comment by night** [comment]
The functionality seems to be working fine for me. Without specific reproducible steps we are unable to look into this matter further.
