### ISSUE TITLE
Betterttv automatically enable readable colors

### ISSUE THREAD

**Issue by chappiebelle** [night/betterttv#4189]
I have been using the regular twitch for a long time, readable colors off, everything original. I decided to set up betterttv because I was curious about its emotes, but it ruined the colors. To get these colors to the original, a setting needs to be found. I would like to see the colors in their real form.

**Comment by xgerhard** [comment]
Hiya, this feature can't be disabled.

see: https://github.com/night/betterttv/issues/3320#issuecomment-447686024
