### ISSUE TITLE
Feature: Disable "floating" animation in Theater Mode

### ISSUE THREAD

**Issue by Senpos** [night/BetterTTV#419]
When you are in "Theater Mode" and moves mouse over the player, control panel (Stop / Play / Volume etc) is floating up with that nasty animation, i'm getting sick a lot. Could be great to disable that animation and just show / hide control panel as it is.

**Comment by cletusc** [comment]
This is not actually possible as the player can't be changed like other parts of the page. Unfortunately the only thing I recommend is keeping your mouse away from the player.

**Comment by night** [comment]
It's unfortunate, but the actual flash player is doing this. We cannot modify the flash player's functionality. You'd have to ask Twitch to change it.
