### ISSUE TITLE
"Anon chat" setting does not work in the popout chat and in the <iframe>

### ISSUE THREAD

**Issue by CoolCmd** [night/betterttv#4190]
betterttv 7.2.89, chrome 86

steps to reproduce:
- turn on "Anon chat" setting.
- open a popout chat, for example [https://www.twitch.tv/popout/leemon_games/chat](https://www.twitch.tv/popout/leemon_games/chat)
- wait 2-3 minutes.
- you will appear in the chatters list. :open_mouth:

this also happens in [this](https://chrome.google.com/webstore/detail/bhplkbgoehhhddaoolmakpocnenplmhf) browser extension.

interesting fact. `betterttv.js` file is inserted on `document_idle`, i.e. between `DOMContentLoaded` and `load` events. but if it is loaded later, for example on `load` + 1 second, then "Anon chat" setting will work as expected.

**Comment by CoolCmd** [comment]
update: delayed insertion on some machines broke the "GIF emotes" setting: emotes stopped animating. so one of the two settings does not work. i do not know how to workaround this shit...

**Comment by night** [comment]
I'm not able to reproduce this behavior locally. You do get logged into chat briefly whenever the page loads, but we disconnect you and reconnect you as an anonymous user.

**Comment by CoolCmd** [comment]
@night You closed the bug too early. I can always reproduce this issue. More details:
You extension disconnecting the user **before** he completes connection.

The chat without issue:
```
Welcome to the chat room!
BetterTTV: [Anon Chat] Logging you out of chat...
Welcome to the chat room!
```
The chat with issue:
```
BetterTTV: [Anon Chat] Logging you out of chat...
Welcome to the chat room!
```

Try  to open the popout chat directly, do not open twitch.tv website.
Maybe my ping to Twitch servers is higher when yours, or Twitch servers are under higher load in my region...

The extension should wait for the user to connect before disconnecting it.
