### ISSUE TITLE
Settings window does not fit in the narrow <iframe>

### ISSUE THREAD

**Issue by CoolCmd** [night/betterttv#4191]
BTTV settings window in the 340px wide <iframe> (for example in [this](https://chrome.google.com/webstore/detail/bhplkbgoehhhddaoolmakpocnenplmhf) browser extension) is useless as the window width is much larger. If you are interested in fixing this problem, I can provide the CSS source code, with which the window will look like this:

![width](https://user-images.githubusercontent.com/684851/95846852-9ef1e900-0d54-11eb-9557-be1eed2fce53.png)

You will be able to add this code to your project.

**Comment by night** [comment]
This issue is now resolved.
