### ISSUE TITLE
Readable Colors bug

### ISSUE THREAD

**Issue by Tenyth** [night/betterttv#4192]
Hello, 
the option "Readable Colors" isn't working properly with BetterTTV, I already contacted twitch staff, to try to fix the problem, but they told me that it's actually a third-party software which is causing it. I only have BetterTTV, so I'm quite sure this is the right place to make a report. The bug consists in the option working for the first few messages, and showing the extremely bright colors again after a couple of seconds. I've got screenshots in which i caught the bug, if they'll be needed, I'll send them to you. Thanks for your attention. Bye bye.

**Comment by night** [comment]
This behavior is working as intended. BetterTTV converts hard to read username colors to more readable colors, preventing people from trolling. This functionality is not customizable.
