### ISSUE TITLE
Twitch webpage recommend channel disappear

### ISSUE THREAD

**Issue by LouisJhuang** [night/betterttv#4196]
On the Chrome browser, I`m enable the BetterTTV, Then the Twitch webpage recommend channel disappear.
I have highlighted the plug-in with a red box. (See Figure 1 and Figure 2.)

[figure 1]
disappear
![image](https://i.imgur.com/KeCLHOH.png)

[figure 2]
When disable the BetterTTV, appear.
![image](https://i.imgur.com/LIEPeaQ.png)

**Comment by night** [comment]
You can toggle "Hide Recommended Channels" in the BetterTTV settings

**Comment by LouisJhuang** [comment]
> You can toggle "Hide Recommended Channels" in the BetterTTV settings

I understand, Thank you!
