### ISSUE TITLE
Add setting to not freeze chat on meta

### ISSUE THREAD

**Issue by cathrinevaage** [night/betterttv#4197]
This is a feature request for adding setting for disabling the feature that pauses chat scroll when you click the meta key.
On a mac, the cmd key is the meta key. Unlike on windows with `alt + tab`, the hotkey to switch between programs, is `cmd + key`. This causes the the chat to be paused quite frequently, and without intention.

**Comment by jcrippen** [comment]
I get the “Chat paused due to scroll” from pressing `ctrl`. I have some keyboard shortcuts with this and they constantly pause chat when I don’t want them to. I’d also appreciate being able to disable this feature.

**Comment by night** [comment]
duplicate of #4181
