### ISSUE TITLE
pinned highlighted messages not working

### ISSUE THREAD

**Issue by demonmod** [night/betterttv#4198]
it USED to work..it hasn't for a couple weeks now. wth?

**Comment by xgerhard** [comment]
Hiya, are you sure the setting is enabled, seems to work fine here.

**Comment by demonmod** [comment]
i eventually removed the whole extension, closed browser, reinstalled
extension. that fixed it!! i can only assume other extensions were
interfering with it?  i'm not 100% sure, but i am happy it works again.
thanks a bunch for getting back to me!   J
