### ISSUE TITLE
FR: change favicon when streamer is ending stream

### ISSUE THREAD

**Issue by cheater** [night/betterttv#4200]
When you have multiple streams open in tabs, it would be advantageous to have a visual indication that one of the streams is ending, so you can switch over, as often some of the more interesting stuff happens by the end of the stream. For this reason, the tab's icon should change. BTTV should monitor chat for something like `!ending` from mods, and then change the favicon. It should change back to normal if `!notending` is used.

**Comment by night** [comment]
This feature is unfortunately a little too niche of a use case than what I think would be useful to most users, since it would require interfacing with bots in chat.
