### ISSUE TITLE
Colors in dark mode

### ISSUE THREAD

**Issue by ssOwl** [night/betterttv#4206]
I don’t understand why in dark mode it’s impossible to choose whether I need readable colors or not. I like the default twitch colors, not these modified ones. I made a bug report on this topic, but they told me that this is not a bug, but the dark mode specifically changes the colors of nicknames, so please give me a switch button, do I need it or not.

**Comment by justyn45** [comment]
My friends keep telling me dark mode doesn't affect the color on their screens, but I am experiencing the same issue. I can't see the nice blues in dark mode.

**Comment by xgerhard** [comment]
Hiya, that's not a bug but a feature, which can't be disabled. BTTV modifies name colors for readability based on the dark or light theme.
