### ISSUE TITLE
Player refresh

### ISSUE THREAD

**Issue by Lucas559-noob** [night/betterttv#4209]
Sometimes I get something like download canceled(error #1000a) idk I saw somewhere a script to reload the player and not the link, is possible to add a refresh player?

**Comment by auto200** [comment]
This should be easy to do, there already is an separate extension that i use and it often works but not 100%.
https://chrome.google.com/webstore/detail/twitch-autorefresher-erro/hhiipkcjbemmanpfdfdkhmfjpliniomn
