### ISSUE TITLE
Highlight/Whisper Notification too loud, sound is annoying, happens too often.

### ISSUE THREAD

**Issue by cheater** [night/betterttv#4210]
Hi, first of all I really love BTTV I appreciate everyone working on it.

Due to the way audio in my setup works, I have to set videos (including twitch) to somewhat quiet (about 20% on the volume slider) and then turn up the physical volume knob on my speakers. The highlight notification sound is very loud compared to everything else on my computer, and I would like to be able to make it quieter. I would also like to be able to use my own .wav file because the sound is pretty annoying. It's a very grating click, I would like to be able to change it to something nicer. Finally, I'd like a limit on how many notifications can happen from one tab at a time, e.g. "A maximum of ___ notifications within ___ minutes".

I appreciate there might be more important things to implement, I'll turn off the feature for now.

Thanks!

**Comment by night** [comment]
Thanks for the feedback. We do not have any planned changes for the notification sounds at this time, but you could use your computer's volume mixer to turn down the audio setting of your browser to lower the volume to a more comfortable setting.

**Comment by cheater** [comment]
Hi @night, sorry, I think you have not read my report - I can't use my computer's volume mixer to turn down the volume of the browser. The alerts produced by BTTV are MUCH LOUDER than the audio being played back on the stream, and that's a problem. I understand that you do not have any planned changes for the notification sounds at this time, that's why I made the report, so that you would. I really honestly feel 100% unheard with your reply.
