### ISSUE TITLE
See emote for a user

### ISSUE THREAD

**Issue by kavisherlock** [night/betterttv#4211]
Is there not a way to see the bttv emotes on a user's twitch channel using their twitch name on betterttv.com? Seems like such a basic feature

**Comment by nakomaru** [comment]
There is such a page, but AFAIK it can't be easily accessed by their username directly.

Until such a feature exists, you can use a search engine as a workaround currently: [google search](https://www.google.com/search?q=site%3Abetterttv.com+%22moonmoon%27s+emotes%22)

This will give you the link to their user page with their channel's list: [channel list](https://betterttv.com/users/574e63ce66a2002d3bcc6f92)

**Comment by Nareese** [comment]
You can use, to take your example, https://betterttv.com/channels/moonmoon

**Comment by kavisherlock** [comment]
Aah excellent. I didn't now there's a URL for /channels
The google search thing only seemed to work for more popular channels
Thank you guys!
