### ISSUE TITLE
[Feature] A button that create a clip saved on the user's computer instead of the twitch servers

### ISSUE THREAD

**Issue by Mrcubix** [night/betterttv#4212]
The recent influx of DMCA takedown, force streamers to disable their clips and sometimes, their vods.
This new feature would work like normal twitch clip with a preview and a way to crop it, but instead of being saved on twitch server, it will be saved on user's hard drive.
This would allow users to clip on channels and where clips are disabled, and instead of the streamer being responsable of the clips that are made, users that share them will be responsable.

**Comment by night** [comment]
This is not something BetterTTV would be useful for, since video processing is performed on Twitch servers. You would need to have some sort of desktop software which can download video chunks and process them.
