### ISSUE TITLE
Left Side Chat - Bug

### ISSUE THREAD

**Issue by dauletalzhanov** [night/betterttv#4215]
Left side chat doesn't show the names of the following and recommended channels. 
![chrome_xHydHVBygN](https://user-images.githubusercontent.com/35165187/97415055-f4bab980-192e-11eb-8f19-cd60032936ee.png)

**Comment by elmakong** [comment]
i believe this is because the channels is collapsed.
in other note, the hover popup for title of stream is gone when using left side chat.

**Comment by night** [comment]
As stated above, you just need to uncollapse the followed channels sidebar
