### ISSUE TITLE
Toggle disable/enable channel emotes

### ISSUE THREAD

**Issue by mellen1826** [night/betterttv#4217]
It would be nice to be able to disable emotes that I upload. For example if I upload a bunch of halloween versions of some emotes I currently have to delete them all to go back to the normal version. And then upload them all again next year and do the same for christmas etc

**Comment by alazymeme** [comment]
+1, Would love to see this - such example scenarios like seasonal events. You might want to add a Christmas/Halloween version of another emote.

**Comment by Bobber-bob** [comment]
Yes I was about to make this topic too as I requested this feature at nightdev.com
Which is this topic: https://community.nightdev.com/t/option-to-uncheck-your-own-submitted-emote/28539

Right now I want to uncheck my Christmas pepeJAM emote (which is used by 700 users currently) and not delete it.

**Comment by night** [comment]
We recently added a "Live" checkbox to emotes uploaded to the dashboard. This allows you to enable/disable which emotes are shown in your stream.

**Comment by ALazyMeme** [comment]
> We recently added a "Live" checkbox to emotes uploaded to the dashboard. This allows you to enable/disable which emotes are shown in your stream.

That "Live" checkbox seemingly unlists the emote also?

Reference: https://betterttv.com/emotes/5eec9d2af54be95e2a8571a3
Live checkbox is currently off, I'm also unable to turn it back on. Visiting the link also does not work:

![image](https://user-images.githubusercontent.com/12804673/193402004-658e6335-ddfb-4ac8-acdd-797d59595409.png)
