### ISSUE TITLE
User Name all lowercase despite changing display name capitalization on twitch 

### ISSUE THREAD

**Issue by BostonTom** [night/betterttv#4218]
Started happening to me a week ago no matter what i change the display name on twitch in chat shows only all lowercase (bostontom instead of BostonTom) when i disable bttv it goes back to showing BostonTom which i have set on twitch's setting looked all over bttv to see if i had a setting checked off and saw nothing 
![bttvbug](https://user-images.githubusercontent.com/73873646/97957449-39a07f00-1d79-11eb-8690-cd6c716af13e.png)

**Comment by night** [comment]
You may have set a nickname for yourself by accident. You can reset it by clicking on yourself in chat, clicking on the pencil icon, and then clearing the nickname you configured.
