### ISSUE TITLE
Gif emote/twitch?

### ISSUE THREAD

**Issue by Sarah34x** [night/betterttv#4220]
So I have twitch open, and my gif emote doesnt show anyone knows why?

**Comment by alazymeme** [comment]
Have you enabled gif emotes in the betterttv settings?

**Comment by Sarah34x** [comment]
I tried that and its still not showing.

**Comment by night** [comment]
Emotes only work in your channel, and only if you have the extension installed with the BetterTTV Emotes and BetterTTV GIF Emotes options enabled in the settings.
