### ISSUE TITLE
Feature request - Option to disable/ hide certain player buttons (picture in picture/ theatre mode etc)

### ISSUE THREAD

**Issue by CrypticDan** [night/betterttv#4228]
I'd like to see an option to disable/ hide buttons in the Twitch player. I never use picture in picture (think it's already part of BTTV?) or theatre mode so an option to disable/ hide those buttons in the Twitch player would be nice. I used to use uBlock Origin to manually block those buttons but it doesn't seem to work anymore.

**Comment by night** [comment]
We generally do not like to add settings to our extension as it makes it harder for new users to configure the extension. I would recommend continuing to remove them using third party tools like the one you listed.
