### ISSUE TITLE
Emote list?

### ISSUE THREAD

**Issue by IIIpl4sm4III** [night/BetterTTV#423]
Can we get an option for a list of global-only / available-to-you emotes? You could click a button and click the emote you want out of a giant list to put into your chat box.

**Comment by voloshink** [comment]
This is already in betterttv, you can enable it by going to the settings and enabling the option at the bottom called "Twitch Chat Emotes"

**Comment by cletusc** [comment]
We should probably change that title of that setting as it really isn't ideal anymore.

@night Can you change the setting name and setting description to the following please?

> **Emote Menu**
> Get a more advanced emote menu for Twitch. ([Made by Ryan Chatham](http://cletusc.github.io/Userscript--Twitch-Chat-Emotes))

**Comment by voloshink** [comment]
i always remember that it needs changing and then instantly forget.

**Comment by IIIpl4sm4III** [comment]
Ah, thank you.
