### ISSUE TITLE
Feature Request: Capital letters not necessary when typing name for emote

### ISSUE THREAD

**Issue by SamuelKelly-Edwards** [night/betterttv#4234]
Make emotes still show even when typed with incorrect capitalisation, 
Eg. for the OMEGALUL emote, make it also pop up for just typing omegalul. 
Also work for any other emote that has a capitol letter in it.

**Comment by night** [comment]
That isn't possible as many emotes are normal words. You can optionally tab complete emotes names though.. just type the first few letters and press tab on your keyboard.
