### ISSUE TITLE
Feature suggestion: "Reload Player" button.

### ISSUE THREAD

**Issue by KandiPanda** [night/betterttv#4236]
Basically, an added button below the player to reload it without reloading the entire page (and by extension clearing chat history and the like in the process).

Would definitely be useful for those "Error 1000/2000/whatever" screens, but would also likely help with catching up in laggier streams more than doing a pause/play cycle does. (Also seems likely to help in the occasional "robovoice audio glitching" streams, where refreshing the page usually fixes it even though pause/play cycling doesn't.)

Could probably look at how the video player in channels (or in channel moderator pages) deals with changing hosts or doing an unhost/host for ideas on how to implement the player reload, since it doesn't reload the entire page for those things?

**Comment by night** [comment]
Due to how the player gets loaded, the only way to fix issues like that robovoice would be to reload the entire page (which recreates the page context).
