### ISSUE TITLE
Feature Request: add highlighting and ping sound support for replies.

### ISSUE THREAD

**Issue by nzall** [night/betterttv#4238]
I don't really understand why, when someone mentions me using @username on Twitch, I can make it be highlighted in red and hear a ping notification, but when someone does the same using the Twitch reply feature with the button next to the chat message, it's indistinguishable from other messages apart from a barely noticeable text section.

**Comment by night** [comment]
Are they mentioning you in the reply, or they are just replying to you without a mention?

**Comment by nzall** [comment]
They're not mentioning using @username or something like that. They just press the reply button.

**Comment by Soulivan71** [comment]
Good idea
