### ISSUE TITLE
Issue with the Anon chat

### ISSUE THREAD

**Issue by Flupsy640** [night/betterttv#4239]
After i join the anon chat and disable it, I cannot join the chat again even i can't used my channel points nor chat commands, please fix it as soon as possible

**Comment by mouseck999** [comment]
Looks like overall "Anon chat" feature doesn't work properly anymore. It says that I'm logged out of chat, but after 30s I can see myself on the viewers list.

**Comment by CoolCmd** [comment]
See [this issue](https://github.com/night/betterttv/issues/4190#issuecomment-734473238) which was incorrectly (in my opinion) closed.

**Comment by mouseck999** [comment]
Looks like it is fixed for me, at least now it works.
