### ISSUE TITLE
Small video player when using left side chat

### ISSUE THREAD

**Issue by Nyessir** [night/betterttv#4243]
My player is smaller than it should be and the rest of the area is filled with black. Just started happening recently. 
![Screenshot 2020-11-23 161630](https://user-images.githubusercontent.com/29931196/100021572-4d9f3580-2da7-11eb-8586-7f95ba0a74ae.png)

It only happens when I am using Left Side Chat option from BTTV settings

**Comment by GummyEater** [comment]
My friend is having this issue right now. We came to the same conclusion, it has to do with something it better ttv subtracing from the 100% width of the css div.

**Comment by GummyEater** [comment]
From what I can see from the latest commit, babel was updated causing the css to mess up. 

.persistent-player

The above is the incorrect css class. 
![image](https://user-images.githubusercontent.com/26776609/100021932-4deffe80-2db0-11eb-8269-c1dba75eeac1.png)

**Comment by blckassassin** [comment]
Also having this issue with left side chat for a few weeks now.

**Comment by ThaFuRiouSOne** [comment]
Same issue here, Changing back to right side chat fixes this for now.

**Comment by AmericanNightmare** [comment]
Same here.

**Comment by acinematicss** [comment]
what worked for me was to drag the window so its not maximized anymore then drag window to maximize it again and the player goes back to normal with left side chat. But just today it hasnt been working so hopefully that might work for others.

**Comment by PoopsMcButt** [comment]
> what worked for me was to drag the window so its not maximized anymore then drag window to maximize it again and the player goes back to normal with left side chat. But just today it hasnt been working so hopefully that might work for others.

Same here. Resizing, swapping theater mode, or virtually anything that adjusted the video size itself would fix it. Not anymore.

**Comment by azakhi** [comment]
Have the same issue and resizing isn't helping on Opera GX.

**Comment by jkrx** [comment]
Have the same issue. Left side chat triggers it. I'm using Firefox

**Comment by MoDog0** [comment]
Having the same issue, left side chat and chrome, doing anything to adjust the video size was working to fix the issue however within the last 24 hours something has changed and this no longer works.

**Comment by burt-ie** [comment]
I also have the same problem, no matter what browser I use.

**Comment by JackDigitalx** [comment]
I know its been going on for over a month now.  When are these fixes going into effect?? Cause this is REALLY obnoxious and has been ignored for WAY too long.
