### ISSUE TITLE
Chat colors still bright for me after deactivating the "Readable Colors" option

### ISSUE THREAD

**Issue by ShadowDevilsAvenged** [night/betterttv#4247]
So I am currently at a chat room and after I activated BTTV, the chat username colors are automatically bright so when I turn off the "Readable Colors" option, it turns the chat username colors back to name then if someone types again, it reverts back to the bright colors. I'm not sure if anyone else has wrote about it, but if no one hasn't done it, then here it is

**Comment by night** [comment]
BetterTTV has its own functionality for recoloring usernames, which cannot be disabled. We enforce this behavior to prevent people from intentionally trolling users. If people know they can't, they won't.
