### ISSUE TITLE
Anon chat not working again

### ISSUE THREAD

**Issue by mouseck999** [night/betterttv#4255]
Hello,

Few days ago I noticed that BTTV feature "anon chat" wasn't working correctly. It was fixed for a few days I think, at least I didn't noticed that it would not work, but now I noticing it again not working

First I join stream with chat, no errors, BTTV says that it logged me off correctly
![chrome_r1BEScoEss](https://user-images.githubusercontent.com/32072217/100808337-e24f0680-342b-11eb-90b5-b0de07a9b941.png)

Then after 2-3min I check list of people in chatroom and I see mine in it.

![chrome_vOiQqHdjqS](https://user-images.githubusercontent.com/32072217/100808371-ef6bf580-342b-11eb-8aff-9165b1b70af0.png)

Don't know if this problem is only for me, but would be nice if possible to fix it.
I'm using Win 10, Google chrome on PC

Thank you.

**Comment by night** [comment]
The user list is usually out of date by some amount of time. When you connect to chat we disconnect you and reconnect you as an anonymous user. In that time period Twitch may join you to chat for a bit even though you quickly joined and then left.
