### ISSUE TITLE
BetterTTV gifs NOT working through emote wall?

### ISSUE THREAD

**Issue by dominikpapic** [night/betterttv#4256]
BetterTTV gifs are not working through StreamLabs Emote Wall. They work normaly in chat, but not on Emote Wall. On emote wall they stay frozen or look like static images. I'm using Brave browser and tried as Chrome extension and as Other. Tried re-installing and everything. There is only that problem.

**Comment by Nareese** [comment]
We do not make and do not support StreamLabs products here.  If you want support with a StreamLabs product, you will need to ask StreamLabs for that.
