### ISSUE TITLE
DMCA.... 

### ISSUE THREAD

**Issue by ToxicSuede** [night/betterttv#4257]
Lots of DMCA seems to legally arise from the streaming of copyrighted material to a wider audience. My suggestion is to distribute it instead. 
Betterttv offers the streamer the ability to send out linnks to songs or audio (or video for that matter) clips that is loaded on the local viewers computer instead of streaming the normal way. That way I as a viewer can access for example spotify's songlink on my local computer and the streamer doesn't send it. Or it can be alink to a youtube sound or whatever. 
This can also be saved in the vod so that the music/soundclips can be loaded locally from other sources than the VOD itself
This way, it doesn't violate the https://www.deviantart.com/sixmonthslate/art/Paramount-VHS-Copyright-Notice-background-1995-603146815
And there might be some changes in the MCA laws to make them more in time with our current place in evolution!

**Comment by night** [comment]
This unfortunately falls outside the wheelhouse of a browser extension for Twitch since it would require a deeper platform integration.
