### ISSUE TITLE
"Hide bits" should also make the right padding of chat input smaller

### ISSUE THREAD

**Issue by Cyberbeni** [night/betterttv#4258]
I am using uBlock to set fix height (before it automatically scaled) and set right paddig for the chat input. But I think other people would also benefit from it, if the "Hide bits" option also made the right padding smaller in the chat input, so typing multiline message doesn't look awful (keeping the padding for the emote menu still makes it look a bit weird but still not as bad as having the original padding)

Context: "Hide bits" also hides the bits button on the right side of the chat input.

**Comment by night** [comment]
Because the padding is programmatically calculated (they compute the padding and set it on the dom element), it would likely be a mistake for us to overwrite its value to be smaller as Twitch is expecting it will add or remove icons here at whim.
