### ISSUE TITLE
Emojis not being converted to images if there is no space between them

### ISSUE THREAD

**Issue by TETYYS** [night/betterttv#4259]
If you post two emojis right next to each other without a space, they will not be converted to images, like posting an emoji normally or two emojis separated by a space will.

![GuWwtFa3Wt](https://user-images.githubusercontent.com/3091645/100932024-f2321d80-34f3-11eb-8e78-17f732bfa4d8.gif)

BetterTTV 7.2.90

**Comment by night** [comment]
This behavior is not considered a bug, and is a result of how emojis are sent. Emojis are unicode characters, and BetterTTV can only replace emotes (and therefore emojis) separated by spaces.

**Comment by TETYYS** [comment]
sad to see inconsistent behavior in FFZ and BTTV
