### ISSUE TITLE
Disable Pop-Out Button Feature

### ISSUE THREAD

**Issue by PropHat** [night/BetterTTV#426]
Hello.

If there was any way of disabling the pop-out button built into Twitch that would be swell as hell. I keep accidentally clicking it which hinders my viewing experience for a few seconds while I close the new window and the stream buffers back up.

I would be eternally grateful if this has the potential to be pulled off.

Thank you!

**Comment by Powersource** [comment]
We can't modify the button directly since it's in the flash player but maybe we could put something over it to prevent clicking it? Even if it's not the prettiest solution.

**Comment by teak** [comment]
Just don't click on it? I don't know anyone who has this problem. Were not going to use a hack solution to fix something that isnt an issue.

**Comment by night** [comment]
Twitch's API ToS states not to obstruct the default player functionality, so there's nothing we can do.
