### ISSUE TITLE
Video playback grinding to a freeze after 5 seconds.

### ISSUE THREAD

**Issue by EdwardFingerhands** [night/betterttv#4267]
This started just over a week ago. Without fail the video will rapidly lose fps the video and audio stop.
Collapsing chat and pause/unpause will fix it, but I can't use chat.

My PC is not slow and below 30% on cpu/gpu and below 80% memory/ram, and I never had any issues before a week ago.

It does not happen when BTTV is disabled. Disabling gif emotes does not help.

**Comment by night** [comment]
We are not able to reproduce this behavior. Unfortunately without steps to reproduce or a performance dump we won't be able to figure out if it is BetterTTV. You may try disabling other browser extensions that affect Twitch, as sometimes there can be conflicts between extensions.
