### ISSUE TITLE
Global Emote Suggestion: EZ

### ISSUE THREAD

**Issue by sundeepkaler** [night/betterttv#4268]
I suggest EZ be made into a global emote, since you can't search for it using the new search query in the site redesign. It's a legacy feature that it's a 2 character emote code, but it's inaccessible now. The only way to add the emote currently is if you already have the link to the emote. https://betterttv.com/emotes/5590b223b344e2c42a9e28e3

**Comment by night** [comment]
We do not accept global emote suggestions at this time.
