### ISSUE TITLE
Reload page AFTER you close the settings window

### ISSUE THREAD

**Issue by Yrlish** [night/BetterTTV#427]
Hi!

I find it heavily annoying when changing settings in BTTV, by that I mean multiple of them. Because some needs a refresh of the page (understandable), but it's annoying when it instantly reloads the page when changing it. Why not wait to reload til I close the settings window and if it needs to reload, reload there.

Thanks,
Yrlish

**Comment by night** [comment]
We have planned to restructure the entire settings system, but there's not an ETA of when it will happen. As part of the upgrades, this would be a feature.

**Comment by Yrlish** [comment]
Great! :D
