### ISSUE TITLE
How to highlight all @

### ISSUE THREAD

**Issue by mpratt14** [night/betterttv#4272]
I was just wondering if there was a way to highlight all mentions, any chat line with the @ symbol in it

**Comment by Nareese** [comment]
To the best of my ability to determine based on personal experience, testing, and reading the code, this is not possible.

Twitch messages, internally, are not simple text... they are made up of "fragments" of specific purposes... some is just plain text, but there are also mentions (the current user and other users treated separately), links, emotes, etc... all of these are processed separately.  When BTTV sees a mention fragment, it strips the username only out of the fragment data and matches against that,  Hence, the "@" of a mention fragment is not part of the text that can be matched against...  so it is not possible to do things like "@*".

**Comment by mpratt14** [comment]
so matching by the character is not possible, but what about a systematic way to identify whether a chat entry has a username / mention in it?

**Comment by Nareese** [comment]
No, there is no way to achieve any kind of "selective" matching, not of mentions, anyway.  The fragments are all converted to something "plain text ish", emotes to their code, links to plain text, mentions to the username only, etc, and then merged together with the plain text fragments, and then your keywords are matched against that merged text.  The only type based matching the highlight system supports is matching the username of the sender (with the `()` syntax). and again, that's not a text match, but a match against the actual sender username from the internal message data.

**Comment by mpratt14** [comment]
can you link me where matching happens in the code, im just curious

**Comment by Nareese** [comment]
The high level match occurs on onMessage at https://github.com/night/betterttv/blob/01e3c68c3874629237e24ccfbf9f28fa3832854b/src/modules/chat_highlight_blacklist_keywords/index.js#L238, the conversion from fragments to text happens at https://github.com/night/betterttv/blob/01e3c68c3874629237e24ccfbf9f28fa3832854b/src/modules/chat_highlight_blacklist_keywords/index.js#L151 and there are various other supporting functions throughout that file.

**Comment by mpratt14** [comment]
Yeah I can see how it's not possible at the moment

looks like there would have to be a new function like isReply that gets called a similar way with a new setting

```
function isMention($message) {
    return $message.parent().hasClass('some_class');
}
```

```
        if (fromContainsKeyword(highlightUsers, from) || messageContainsKeyword(highlightKeywords, from, message)
            || (isMention($message) && settings.get('highlightMentions')) {
            this.markHighlighted($message);
```

im not a programmer so idk if theres a cleaner way
maybe ill try this if i have the time

**Comment by mpratt14** [comment]
following from this

https://www.w3schools.com/jquery/traversing_find.asp

I think the function would be

```
function isMention($message) {
    return $message.find("span").hasClass('mention-fragment');
}
```

and maybe it would be better to have a separate if before the rest but idk
