### ISSUE TITLE
Dark Mode isnt saving, and forces to White Background on refresh/back button

### ISSUE THREAD

**Issue by Hoolighan** [night/betterttv#4274]
https://gyazo.com/e66b768edf8f3d4c2edc8767e2df6463

**Comment by night** [comment]
that toggle is not BetterTTV's. You can report that bug to Twitch directly.

**Comment by Hoolighan** [comment]
It is also happening with BTTV. Same issue

**Comment by Hoolighan** [comment]
https://gyazo.com/547d5a69c5668ff6de5f06e912096aa3
