### ISSUE TITLE
Feature Request: Change chat font size

### ISSUE THREAD

**Issue by craighton** [night/BetterTTV#428]
I like to throw Twitch up on to a TV from across the room, it'd be cool if there was an option to increase the font size so that I could read it from far away.

**Comment by Powersource** [comment]
Doesn't the regular browser zoom work?

**Comment by craighton** [comment]
Yes and no. 

Yes it works. 

But not really because it breaks some of the page elements.

**Comment by night** [comment]
Duplicate of #57
