### ISSUE TITLE
GIF Emote setting for specific channels

### ISSUE THREAD

**Issue by olikran** [night/betterttv#4281]
My PC just can't handle big spammy chats with GIF Emotes but I have to switch them on manually when I join smaller chats. Could it be possible to link the setting to a specific channel? Say I disable them in forsens stream but enable them in a smaller stream without going to the settings everytime.

**Comment by night** [comment]
Thanks for the feedback. We are not able to support channel-specific settings like this at this time just due to how the settings system is structured.
