### ISSUE TITLE
Twitch Going Blank

### ISSUE THREAD

**Issue by SpasticCat2001** [night/betterttv#4282]
Every time I go on Twitch with BTTV downloaded, nothing works. At first, I thought it was Twitch because the stream I was trying to watch had just a blank screen, but I could still see the chat rolling, but no one else was having the problem. Then when I uninstalled BTTV and refreshed it a couple of times, the problem went away.

**Comment by night** [comment]
It was likely a cache issue, since refreshing updated your cache.
