### ISSUE TITLE
Feature Request: raise chat on right to avoid hiding behind windows 10 notifications

### ISSUE THREAD

**Issue by Tom00214** [night/betterttv#4285]
I was wondering if anyone else finds it annoying when windows 10 notifications go off that it hides the chat window for a little bit if you have chrome window maximized on main screen and chat on right side.  Would be nice since windows does not have any way to change where the notifications appear if we could raise up the chat a little bit to avoid those notifications from hiding what we are typing that moment.  Just a thought since anytime i get a discord notification for example, i have to wait for it to disappear or close it myself before i can see my chat before sending it (maybe I'm the only one who is bothered by this lol).  Thanks!
![pop-up-covers-chat](https://user-images.githubusercontent.com/76116221/102371166-e7fc2e80-3f8b-11eb-8043-4992058de0bb.PNG)

**Comment by night** [comment]
This is a verify specific problem that is unfortunately not related to BetterTTV. I would recommend resizing your browser window instead.
