### ISSUE TITLE
Black and white boxes

### ISSUE THREAD

**Issue by Thefirebeast** [night/betterttv#4288]
Today when I got on to watch some twitch vods i noticed weird boxes. Im using the browser "Brave"
Dark Mode
![issue2](https://user-images.githubusercontent.com/33950487/102552044-1e1dd900-4086-11eb-8858-83f8ae16aba3.png)
![issue1](https://user-images.githubusercontent.com/33950487/102552045-1eb66f80-4086-11eb-9c73-1b790c46978d.png)
Light Mode
![issue3](https://user-images.githubusercontent.com/33950487/102552049-1fe79c80-4086-11eb-9654-d2b3786f1d0e.png)

**Comment by Gabanders** [comment]
I only see one white box on the right side of the gear icon, which covered the picture-in-picture button.

I managed to fix it by installing the Stylus extension and using this custom CSS on twitch.tv:

    #bttv-picture-in-picture   
    { background: none !important; }
