### ISSUE TITLE
Feature Request: Hide Notice Message (Grey Messages)

### ISSUE THREAD

**Issue by CorentiOS** [night/betterttv#4292]
Hello, I have a feature request about removing the Grey Messages you can see in chat

These messages has the class : user-notice-line class, and are in grey.

We can see in the photo it's better to hide this to avoid chat spamming
![image](https://user-images.githubusercontent.com/43886135/102700079-83222c00-424a-11eb-8000-4ff727ac6cdb.png)

**Comment by night** [comment]
this should already be supported via the "Disable Channel Points Message Highlights" feature
