### ISSUE TITLE
Separate Predictions from "Hide Community Highlights"

### ISSUE THREAD

**Issue by Ddhuet** [night/betterttv#4293]
Currently a lot is lumped into the Hide Community Highlights toggle. Most of it is spammy garbage like Hype Train, but Predictions seem different enough to warrant a separate toggle. It is a very popular feature in tournament streams, and unrelated to the other Community Highlights aside from positioning.

**Comment by Blinkenn** [comment]
If you're going to separate it out, then put another setting to be able to hide it. While some might like that one notification showing up, others may not want any community highlight to show.
