### ISSUE TITLE
Hiding channel point claims

### ISSUE THREAD

**Issue by angauber** [night/betterttv#4294]
When a user claim an award using channel points a message pop up in the chat.
It gets really painful when people are spamming those

I could not find any BTTV option to hide them but I am not sure if such thing already exists ?

Looking at the html classes that would be all elements with `user-notice-line` that contains `channel-points-reward-line__icon`

**Comment by Nareese** [comment]
The only option that currently exists for this functionality is `Disable Channel Point Message Highlighting`, which, as the name implies, disables the "Highlight My Message" channel points reward.  I think that reward probably accounts for 90%+ of the "spam" of channel points rewards.  Disabling other channel points rewards that have messages may be more problematic, but give that a try and see if it helps.
