### ISSUE TITLE
Emote unavailable on Twitch (Chrome)

### ISSUE THREAD

**Issue by b00quets** [night/betterttv#4298]
I checked the BTTV settings, and the emotes selection is set to 'ON'.

**Comment by acuuno** [comment]
I have same issue. I don't have that icon for emotes

**Comment by b0rt0rt0rt** [comment]
Also having this issue in Chrome. Have toggled On/Off with no change, have logged Out/In with no change, have restarted Chrome with no change, have rebooted laptop with no change. FIX?

**Comment by night** [comment]
i'm not able to reproduce any issues with emotes
