### ISSUE TITLE
"Highlight/Whisper Notification — Plays a sound for messages directed at you" - doesn't work

### ISSUE THREAD

**Issue by okaytestokaytest** [night/betterttv#4301]
Receiving whispers and mentions in chat doesn't play sound for me when the feature is enabled.
I am currently using Opera browser, but I have tried it on Chrome too, but no sounds.
Tab isn't muted, stream isn't muted.  I have reinstalled in extension as well.
I was given this link: https://cdn.betterttv.net/assets/sounds/ts-tink.ogg on discord, and I can load the sound from here and hear it.

**Comment by night** [comment]
Unless you already have sound coming from a tab, Chrome prevents new sounds from playing without user interaction being present. Unfortunately this is not something we can fix as it's a Chrome limitation.
