### ISSUE TITLE
Suggestion: Auto-dismiss Twitch Drops notifications

### ISSUE THREAD

**Issue by serg06** [night/betterttv#4309]
Every time I dismiss this message, it comes up 1% later. Super annoying. Would be great if we could get rid of it permanently.

![image](https://user-images.githubusercontent.com/1350889/103967509-28387200-5130-11eb-8bf0-069080b0c40c.png)

**Comment by serg06** [comment]
If anyone else sees this: You can block it with uBlock origin by adding the following line to My Filters:

```twitch.tv##.community-highlight-stack__card```

**Comment by night** [comment]
it's possible this is an experiment twitch ran, but I am not able to reproduce this notice locally.
