### ISSUE TITLE
please fix UI clunkiness when adding emotes to channel

### ISSUE THREAD

**Issue by Crusader2010** [night/betterttv#4311]
Hi.

After adding an emote to the channel, the link/button to add another one disappears. You need to do like 4-5 additional clicks just to find that page again and get to add another emote after the first.

Also, please add a way to search for emotes when trying to add them to the channel.

Thanks

**Comment by night** [comment]
Thanks for the feedback. After you upload an emote we take you to that emote's page, which is the resource you created. Additionally, you can already search for emotes on our shared emotes page: https://betterttv.com/emotes/shared
