### ISSUE TITLE
Suggestion: Enable "Restore PogChamp" Feature

### ISSUE THREAD

**Issue by poshdevops** [night/betterttv#4317]
Twitch decided to replace PogChamp in retribution for someone's personal views. PogChamp wasn't a direct representation of the person's personal views, nor does it even make sense to assume such a thing. It would be nice if we could restore PogChamp to the way it was before Twitch decided to unnecessarily politicize an emote.

Thanks.

**Comment by Bobber-bob** [comment]
Or make it so that if you select a PogChamp emote in BTTV for your channel, that it overwrites the Twitch PogChamp emote (or any other emote for that matter).

**Comment by superben1755** [comment]
I actually agree with this request. It would be nice if the BTTV channel emotes could "override" both Twitch default and BTTV global emotes. That way someone could have the old PogChamp if they wanted, and they could replace the global pepe emotes with something else if they didn't want those.

**Comment by BopItFreak** [comment]
I agree! I want PogChamp back!

**Comment by night** [comment]
Thanks for the feedback, but we do not own the rights to this emote and are unable to restore it for that reason.
