### ISSUE TITLE
Add Subscriber Mode into the MOD TOOLS pop-up window

### ISSUE THREAD

**Issue by Maxhype** [night/BetterTTV#432]
![untitled](https://cloud.githubusercontent.com/assets/12036035/7756103/955699a6-0001-11e5-937a-8e9eaceea084.png)

My suggestion:

Mod Icons
Slow Mode
Subscriber Mode

**Comment by night** [comment]
We are not considering extending the length of the settings menu at this time, as it's already far too cluttered. There's shortcut commands of "/sub" and "/suboff" if you want to quickly toggle subscriber-only mode.
