### ISSUE TITLE
Add an option to disable global bttv emotes

### ISSUE THREAD

**Issue by alazymeme** [night/betterttv#4321]
I made this issue because this issue [here](https://github.com/night/betterttv/issues/4318) made me lose braincells.

Something like this would be cool; either that or the ability to change the default emotes (only to other global emotes). You might want a spooky monkaS on halloween or something.

**Comment by superben1755** [comment]
wow rude. Anyway, looks like we have given 3 options for how to address the same issue in the last 3 Issues:
1. Have BTTV channel emotes take precedence over BTTV global emotes (and Twitch emotes) so we can override emotes we do not want
2. Give the option to remove certain BTTV global emotes
3. Give the option to remove all BTTV global emotes

**Comment by night** [comment]
Thanks for the feedback, but we have no plans to add the ability to toggle individual emotes.
