### ISSUE TITLE
Dark theme and color bug 

### ISSUE THREAD

**Issue by Doctorizm** [night/betterttv#4323]
![resim](https://user-images.githubusercontent.com/77509790/104770798-2f8bfb00-5782-11eb-9f89-e8bbb698cf43.png)

Some colors is in bug - red and blue for exp İf ı close dark theme colors will be back to normal but if ı a open colors is fade ı like deep red so if you can fix it that will be great (sory for bad english )

I explain problem with my turkish 

Bazı renkler bugta - kırmızı ve mavi örnek - eğer karanlık temayı kapatırsam renkler normal haline geri dönüyor ama açarsam renkler daha solgun bir hale dönüyor. Sorunu çözebilirseniz çok sevinirim

**Comment by night** [comment]
This behavior is working as intended. We prevent hard to read usernames in chat.
