### ISSUE TITLE
"Hide Whispers" option does not hide button in Theater Mode

### ISSUE THREAD

**Issue by dfarley1** [night/betterttv#4326]
Reopening of #2839, I'm experiencing this issue using v7.2.91. Here's a picture I captured a couple days ago:
![twitch_black_bar](https://user-images.githubusercontent.com/5204693/105102552-cc40e800-5a63-11eb-8f17-3e9b87f8e7b1.png)

Setting `.video-player__container--theatre-whispers` to `bottom: 0rem` fixes the issue until I reload.

**Comment by night** [comment]
it's possible twitch fixed this, as I cannot reproduce it.
