### ISSUE TITLE
Chat-messages disappear

### ISSUE THREAD

**Issue by Friisenborg** [night/betterttv#4329]
I've been using both BTTV and FrankerFaceZ for a while now with no problems, but recently, I ran into a completely new problem. When I watch streams with the extensions on, I can no longer see the chat-messages of other people, I can only see my own. If I go onto mobile, I can see that other people chat, meanwhile nothing shows in the browser with the extensions. If I uninstall BTTV on Chrome, I can see chat again. I have tried using Firefox instead, but I heavily dislike this browser and any other browser, hence why I am asking for help here. 

Any ideas how to fix it?

**Comment by night** [comment]
You may have improperly configured BetterTTV. You can clear your browser cookies to reset your BetterTTV settings.

**Comment by Friisenborg** [comment]
Still doesn't work, I tried clearing my browser cookies for BetterTTV
