### ISSUE TITLE
I have a request 

### ISSUE THREAD

**Issue by caporal** [night/BetterTTV#433]
hi !
can you make a full screen mod with the chat in the corner in png format please ?

**Comment by DTittel** [comment]
Chat as a png? A png is an image.

**Comment by caporal** [comment]
yes my english isn't perfect 'i'm french', transparent chat in the full screen if you prefer, i think that streams will be more comfortable that way

**Comment by cletusc** [comment]
-1, there is already theater mode with F11.

**Comment by DTittel** [comment]
I also don't see a use for this what does this add vs Theater mode?

Regards,

Dylan

Dylan Tittel | UWaterloo ECE Student, and Twitch Global Moderator |
dylan@dylantittel.com | (226) 989 - 4223
