### ISSUE TITLE
Suggestion: Option to disable auto play on channel pages.

### ISSUE THREAD

**Issue by Musouka42** [night/betterttv#4331]
I love the options to disable auto play on the homepage and the vod recommendations after a video ends.  It would be really nice to also be able to disable auto play on channel pages when browsing past broadcasts.  I am chronically behind in watching my favorite streamers, so I'm always watching past broadcasts, but Twitch automatically starts playing the latest broadcast at the top of the page when you browse, which marks it as partially watched, and makes it more difficult to figure out which ones I've actually seen and which I haven't.  So I would really love to see an option to stop the auto play on those pages.

Thanks for all your hard work on this amazing extension!

**Comment by Feldherren** [comment]
I have a similar (or the same) issue/feature request, but it's that the currently-selected video will autoplay, muted, when you first interact with the tab.

**Comment by night** [comment]
I'm not able to reproduce this.

**Comment by Musouka42** [comment]
> I'm not able to reproduce this.

Hello Night.

I'm not sure why you wouldn't be able to reproduce this, so I'm assuming there is some confusion on what I mean.  I'm talking about how the latest broadcast automatically starts playing at the top of any page on a streamer's profile.  For example, on [this page](https://www.twitch.tv/pedguin).  [Here](https://ibb.co/VNF7F1v) is a screenshot to demonstrate what I mean.

Please let me know if you have any further questions or still cannot reproduce this behavior.

**Comment by night** [comment]
The description of this was not really clear. This is superceded by #4405

**Comment by Musouka42** [comment]
I apologize for not being clear in the original post.

Again, thanks for all the hard work you put into this project.
