### ISSUE TITLE
when I hover over the gif smileys they do not display a preview

### ISSUE THREAD

**Issue by davevin** [night/betterttv#4332]
when I hover over gif smiles, they do not display a preview. And they are not added to the favorites. how to fix?
![Screenshot_4](https://user-images.githubusercontent.com/52295305/105904889-6c7daa80-602a-11eb-9e54-2a76dfdaf978.jpg)

**Comment by night** [comment]
It may be caused a different extension you have installed conflicting with ours. I'm not able to reproduce this.
