### ISSUE TITLE
Mute the tab, not the stream

### ISSUE THREAD

**Issue by infranscia** [night/betterttv#4335]
So I recently learned that if you mute the stream video, you don't count as a viewer, which can be a problem for newer/lesser known streamers.

Muting the TAB lets you lurk while still counting as a viewer.

If possible, I'd like if the BTTV extension could be changed so if you have 'mute invisible streams' on, it'll mute the tab, not the stream.  If nothing else, it might be nice to put a warning under the 'mute invisible steams' option so people will know what'll happen, in advance.

**Comment by night** [comment]
It isn't possible to mute the tab instead of the stream, as we can only mute individual audio contexts we are aware of (not additional ones being created).
