### ISSUE TITLE
Use my channel emotes in other channels

### ISSUE THREAD

**Issue by infranscia** [night/betterttv#4336]
So lately, I've found myself wanting to use my custom emotes in other chats.  Sort of like if I were using subscriber emotes from one channel in another channel.

I'll understand if this is complicated, but I'd basically like to be able to use BTTV/FFZ emotes connected to my account in other channels, as well as private chats.

Personally, I don't entirely want others using my emotes... not right now, anyway.  You could probably add permissions, though I'll understand if just starting with doing your OWN BTTV/FFZ emotes - not emotes from other channels - would be a good idea.

(I'll also admit, I also like the idea of leaving out permissions for others to use them... if only so that they'll have more incentive to add my own emotes to _their_ channels. X3)

**Comment by xgerhard** [comment]
Hiya, have you checked out BTTV Pro? https://betterttv.com/dashboard/pro
That will give you the option to select a few BTTV emotes which you can use globally on Twitch.
