### ISSUE TITLE
Chat bar badge

### ISSUE THREAD

**Issue by TheSigge989** [night/betterttv#4338]
Twitch thought it would be a 
good reason to add the badge setting in the chat bar,
It would be really good if you guys could add a feature to hide the badge (sub badge) in the chat bar,
![ef55ab00ac2a337814fb3733f656f5e9](https://user-images.githubusercontent.com/50048342/106371283-ebdce800-6362-11eb-8ed2-dfb2128ccdf7.png)

**Comment by night** [comment]
this looks to have been an experiment that they've since turned off.
