### ISSUE TITLE
Turn off Follow / Unfollow buttons

### ISSUE THREAD

**Issue by aw3rque** [night/betterttv#4341]
I'm a little clumsy person. And as a result, I unfollowed the twitch channel I have been following since 2018 by wrongly pressing the unfollow button. It would be nice to have a hide button.

**Comment by GbaLog** [comment]
now twitch asks when you press "Unfollow" button.
but I'd rather disable the unfollow button altogether.

**Comment by night** [comment]
Twitch now asks for permission to unfollow, which resolves this concern.
