### ISSUE TITLE
Twitch Video Player

### ISSUE THREAD

**Issue by Gamingtime15** [night/betterttv#4344]
In chrome specifically, when you highlight the video the options dont appear anymore. To for example, pause the video, turn down the volume etc. I have to use space to pause the video in order to turn it down or M to mute it. This doesn't happen on Microsoft Edge for example but I dont want to use Edge. The video should help to highlight the issue. Sorry for the scuffed Double Monitor.

https://user-images.githubusercontent.com/78568315/106960132-88243780-6733-11eb-9e70-c318a4c31247.mp4

**Comment by night** [comment]
If anything this is a Twitch bug, not a BetterTTV bug.

**Comment by Gamingtime15** [comment]
yeah no mate, I uninstall BTTV and it fixes itself. Its something with BTTV
not Twitch or Chrome. Sorry to say, it may be a niche problem but its still
a problem.
