### ISSUE TITLE
Hide Certain Streamer/People We follow From Our Following List

### ISSUE THREAD

**Issue by MiAmorAmy** [night/betterttv#4345]
I believe it is necessary to get this option to be able to hide certain streamers or people we follow from our following list! It would be really helpful!

**Comment by xgerhard** [comment]
Hiya, why wouldn't you just unfollow them, if you want to hide them?

**Comment by MiAmorAmy** [comment]
> Hiya, why wouldn't you just unfollow them, if you want to hide them?

Oh well the thing is, sometimes you follow certain people just to support them! I dont usually watch some streamers but you know i wanna follow them cause they are friends even though i actually dont watch their stream...

**Comment by night** [comment]
We have no plans to hide from your followed list. I would recommend unfollowing streams you don't care about.
