### ISSUE TITLE
Colon ( : ) emote completion/search is not working for BTTV Emotes

### ISSUE THREAD

**Issue by Error9998** [night/betterttv#4346]
As title says. I disabled other extensions (FFZ) to make sure there was no interfering and it still didn't work.

**Comment by xgerhard** [comment]
Hiya, you can use tab to cycle through/autocomplete BTTV emotes.

**Comment by Error9998** [comment]
> Hiya, you can use tab to cycle through/autocomplete BTTV emotes.

I know that, but I am used to using colon to cycle through them. Is it not a thing anymore?

**Comment by Nareese** [comment]
It never was a thing.  BTTV does not interface with Twitch's emote menu, and therefore does not and has not ever used the : prefix to access emotes.  It is why we supply our own emote menu.  If you had that functionality previously, it was being supplied by some other extension.

Also, duplicate of #3807
