### ISSUE TITLE
Hosts and followed games

### ISSUE THREAD

**Issue by rtcom1** [night/BetterTTV#435]
A cool feature would be to be able to switch the hosts and followed games on your following page quite often i get 2 rows of people i follow and another 2 of people hosting and the games i follow get booted off screen.

**Comment by night** [comment]
Already exists.... Enable "Default to Live Channels" in settings

**Comment by rtcom1** [comment]
partially but then it removes the followed games. I want to see channels i follow and games i follow. I couldn't give a hoot about hosts
