### ISSUE TITLE
Scroll Volume not working

### ISSUE THREAD

**Issue by UKhichariya** [night/betterttv#4353]
![image](https://user-images.githubusercontent.com/75837974/107604673-d3b87300-6c56-11eb-8aeb-ca6220a0fc95.png)
It is what the title says. The Volume Scroll on twitch isn't working.

**Comment by night** [comment]
I'm not able to reproduce this. Ensure you're scrolling on the video player, not the rest of the page.

**Comment by mackingtosh** [comment]
I can confirm, not working for me either
