### ISSUE TITLE
Unable to upload new emote

### ISSUE THREAD

**Issue by tfermm** [night/betterttv#4356]
When I try to upload a new emote I get an error in console saying  

```Access to XMLHttpRequest at 'https://api.betterttv.net/3/users/<my user id>/emotes' from origin 'https://betterttv.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

I have tried clearing my cache, I have tried 3 different browsers as well.

**Comment by night** [comment]
I'm not able to reproduce this
