### ISSUE TITLE
Suggestion: Random PogChamp

### ISSUE THREAD

**Issue by EvilEtho** [night/betterttv#4358]
With Twitch finally setting a default PogChamp emote, I think it would be cool to have an option to do the original idea day9tv had. 

> Yo @Twitch suggestion for PogChamp: create a database of streamer and/or general faces.  Whenever someone types PogChamp, display one of those faces at random.  Would give a really nice crowd feel to a chat spamming PogChamp and allow the meaning to be tied to all of us instead.

Then Users can upload their own Pogchamps to your database [Or pull the ones that already exist] and then your extension will just replace PogChamps at random.

Also the system wouldn't have to sync, so all users will see different faces.

**Comment by deefdragon** [comment]
It would also be nice to be able to set the list to _any_ twitch emote that ends in pog as a default/starting point.
Unfortunately, getting that list may be a bit difficult. 
The old endpoint that I would have checked to get the ID list ([here](https://dev.twitch.tv/docs/v5/reference/chat#get-all-chat-emoticons)) is deprecated. 
I don't expect twitch to expose it again for likely obvious reasons. 
There is a website that archives all twitch emotes that may be worth looking into however.

**Comment by deefdragon** [comment]
I was wrong. The twitch API being the _fun_ that it is, you had to add a specific header to tell it to use V5. I grabbed the data, and there are currently 61363 emotes that match the regex `.*[pP][oO][gG].*` 

Given the url for an arbitrary emote is `https://static-cdn.jtvnw.net/emoticons/v1/<ID>/1.0` it should be easy enough to add a file with the array of pog emote IDs, pick a random one every time a pog is placed in chat, and replace it.

@night is there a proposal acceptance process that gets done or anything? Or is it do the work and if its not absurd it gets accepted? If it isn't obvious based on the question, I am thinking about seeing if I can tackle this in a few weeks once I have some time to spare. I loved this idea when Day9 originally asked about it.

**Comment by night** [comment]
Twitch's emotes endpoint is deprecated and going away. We also do not have permission to use paid subscriber emotes in this manner, and as such it may be a legal issue to support such a feature.

**Comment by deefdragon** [comment]
It should be noted that ALL of that API is "deprecated" but is in an effective state of being treated as fine until twitch gets their act together on the new one. In any event, I was planning on just using it to grab a list to hard code so as to not require a user to download multiple megs of extra data to parse on their own. 

On The legal issue: If permission is requested and given, can this issue be reopened?
