### ISSUE TITLE
Hide Promoted/Featured streams in the feed

### ISSUE THREAD

**Issue by Aldodzb** [night/betterttv#4359]
I have noticed these last days that twitch is now adding a promoted/featured stream in the first place in our feed.

It would be nice to have an option to hide those streams.

Here an image of what I mean: https://i.imgur.com/O2QHDct.png

"Promocionada" means Promoted/Featured.

Thanks.

**Comment by night** [comment]
Due to past legal pressure from Twitch, we do not block ads or promoted content on Twitch. You may wish to use Adblock or Ublock instead.
