### ISSUE TITLE
Be able to add gif-s as Personal Emote

### ISSUE THREAD

**Issue by kozaka-tv** [night/betterttv#4364]
Now, we may only add non gif Emotes as personal. It would be great if we could add also (animated) gifs to personal emotes.

Idk that this is technically not possible or it is only your decision! :)

Thank you!

**Comment by night** [comment]
We used to support GIFs when we launched personal emotes, but due to abuse we quickly added this restriction and it will likely not return.

**Comment by kozaka-tv** [comment]
Oh...not good! :) But you change the approval process recently to be more
like Auto Approved. I assume this automation will not work with animated
gifs!?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
