### ISSUE TITLE
bettertv emote menu won't load on firefox fresh install

### ISSUE THREAD

**Issue by Kerellian** [night/betterttv#4367]
using firefox 85.0.2 (64-bit) Fresh install and the bettertv emotes won't load. I have checked the settings and they are enabled in the menu . I tried disabling then clearing cookies and cache then re enabling them. and they still do not work. I tried searching for others with this issue but didn't find anything like mine that had any solution or wasn't marked as invalid. not sure what i am doing wrong here and help would be much appreciated

**Comment by night** [comment]
I am not able to reproduce this.
