### ISSUE TITLE
[SUGGESTION] Subscriber Only Emotes 

### ISSUE THREAD

**Issue by codeOCE** [night/betterttv#4374]
As an affiliate it can be a bit rough to only have 1 emote per tier and eventually up to 5 emotes for tier 1 subs. I would love to have the ability to allow only subscribers to use certain emotes that I upload to BTTV.

**Comment by xgerhard** [comment]
Having BTTV emotes behind a paywall doesn't sound like a good idea to me, think this is more something you should request to Twitch.

**Comment by night** [comment]
Thanks for the feedback. Unfortunately there are legal concerns with allowing users to sell access to content on BetterTTV, so we will not be able to consider this request for the time being.

**Comment by codeOCE** [comment]
> Thanks for the feedback. Unfortunately there are legal concerns with allowing users to sell access to content on BetterTTV, so we will not be able to consider this request for the time being.

Ok. No worries, thank you for your reply!
