### ISSUE TITLE
Emote and Gif Emotes do not show up when...

### ISSUE THREAD

**Issue by Tizzam** [night/betterttv#4376]
Version 88.0.4324.190 (Official Build) (64-bit)
I have noticed that when the Dark Reader extension is active on Twitch, the emotes do not show up. Turn it off, they are back. 
not sure if this is new or old, but I just installed Dark Reader a couple of days ago...possibly conflicting with Twitch dark mode.

**Comment by night** [comment]
Unfortunately because that other extension may change the DOM of the Twitch site in a breaking way, we are unable to support it. You may wish to file a bug report with the other extension.
