### ISSUE TITLE
Can't Upload Emote I Purchased

### ISSUE THREAD

**Issue by SteveTheChimp** [night/betterttv#4378]
I purchased an emote from Own3d.tv https://www.own3d.tv/product/twitch-sub-emote-gorilla-lol/ but I can't upload it to my channel as someone else bought it as well and didn't enable sharing. Please fix this quickly as I would like to use the emote I purchased.
![GorilLUL112](https://user-images.githubusercontent.com/79723898/109353715-c00e2e80-784a-11eb-9a04-870967b5eb2e.png)

**Comment by night** [comment]
Unfortunately emotes can only be uploaded one time to our platform. You may wish to seek out a refund or contact the uploader to request they enable sharing.
