### ISSUE TITLE
How can i add betterttv support to my chatapp

### ISSUE THREAD

**Issue by tanay-pingalkar** [night/betterttv#4380]
I am using emoji mart

**Comment by Nareese** [comment]
BTTV is a web browser extension that works with Twitch's web site.  We support all major web browsers that support javascript.  We do not support any other platforms or applications.

**Comment by tanay-pingalkar** [comment]
Will you please add support for dogehouse.tv

**Comment by Nareese** [comment]
Better **TWITCH** TV is specifically written from the ground up to support Twitch's website and is only capable of supporting Twitch's web site.  It's not a question of "adding support" for some other site.  It would require completely rewriting our application. We have no intention that I am aware of to ever support any other platform.  So... no, I would say it is extremely unlikely that we will ever "add support" for dogehouse.tv.
