### ISSUE TITLE
Personal Emotes not Working/Showing

### ISSUE THREAD

**Issue by 1337Trevor** [night/betterttv#4381]
I've had bttv pro for a few months now and never have been able to use my personal emotes. It says you get 5 personal (non gif) emotes and +2 for every month you are subscribed to bttv pro. I currently have emotes selected as personal emotes and they show up in my dashboard on the bttv website but when I go on twitch they are no where to be found in my emote menu and when I just type the emote name out my friends and other users in the chat say it doesn't show. I have friends who use the personal emotes and they have no clue what my issue could be. I've looked online for solutions but they all seem to be old ones from years back that have been supposedly fixed but in my case I'm not able to use them.

**Comment by Nareese** [comment]
In order for personal emotes to function, your browser must be able to contact our socket server on a persistent web socket.  This web socket is used to inform other BTTV users in your channel that you are present, and what your personal emotes are, if any.  If your browser is for some reason unable to connect to this web socket, your personal emotes will not work.

I don't know how comfortable you are using your web browser's developer tools to look at what might be happening here, but you can open the developer tools in most browsers by pressing F12 and that will open them in a window on the right of your window.  Select "Console" from the menu at top (or possibly bottom, also, you may need to hit the >> button on the menu to see more entries if Console is not visible for some reason).  You should see a > or >> prompt at the bottom of the console area. 
Enter `BetterTTV.settings.set('consoleLog', true);`.  Then refresh the page, and watch the console logging that it will show.  You should see a message that says `BTTV: SocketClient: Connecting to server` followed very shortly after by `BTTV:  SocketClient: Connected to server`.  You should NOT see a message that says `BTTV: SocketClient: Disconnected from server`.  If you do not see the "Connected" message, or you do see the "Disconnected" message, that would be a confirmation that your browser is blocking that connection for some reason.

It would be difficult for us to know why.  The first thing I would recommend is that you temporarily, just for testing, disable all other extensions in your browser, especially things like ad blockers, internet "privacy" or "security" extensions, etc..., and try again, and see if your emotes work, and what debug messages you see in the console log.  If your emotes work in that configuration, then you can try re-enabling other extensions one at a time, until it breaks again, and that should help you to find out which extension might be blocking it.
