### ISSUE TITLE
Mute Invisible Streams occasionally will unmute all your open Twitch Tabs

### ISSUE THREAD

**Issue by CyberTechDude** [night/betterttv#4382]
When Mute Invisible Streams is turned on, occasionally it will unmute all the streams you have open. A temporary fix is cycling through each tab. This will usually mute them back but sometimes it takes several tries to get them muted again. This is occurring on the Chrome browser.

BetterTTV Extension Version = v7.2.91
Chrome Version: 88.0.4324.190

**Comment by night** [comment]
The way we must mute the player is by setting the player element to volume zero. If Twitch recreates the video element, it would reset the mute state. Is it possible your internet is dying and Twitch resets the player state?
