### ISSUE TITLE
Search Improvement - Search by Suffix and Substring

### ISSUE THREAD

**Issue by QMulo** [night/betterttv#4383]
It would be nice to search emotes by suffix or substring. There are a number of popular emotes that share a suffix - such as `-JAM`, `-Hands`, or `-STEER`.

There are also cases where a streamer specializes in one game and wants to find all the options for that specific game/character - like `feelsMarioMan`, `pepeMarioHands`, `marioS`, etc

Currently, searching on "Shared Emotes" only allows you to search by the prefix - `monka-`, `pepe-`, `cat-`, etc.

Most search engines allow searching by suffix or substring using an asterisk - `*STEER` or `feels*man` or `*mario*`. I think this would be a great update to explore shared emotes that would be relatively easy to implement.

Related to this suggestion:
https://github.com/night/betterttv/issues/3841

**Comment by kjakman** [comment]
This would be *very* helpful - spending time scrolling through all the emotes to find the right one is a vibe impediment

**Comment by night** [comment]
Infix search has been re-added as of today, meaning that results will now be returned when matching in the middle or end of the emote code.
