### ISSUE TITLE
Do not automatically collapse chat

### ISSUE THREAD

**Issue by icnocop** [night/betterttv#4388]
Hi.

Thank you for BetterTTV.

I'd like to request the ability to keep the chat expanded.

The chat will automatically collapse in Firefox when I resize the browser window to a smaller size.

This causes the chat to collapse and get disconnected, and I this may make me miss some chat messages.

I'd like the chat window to stay expanded until I explicitly collapse it.

Thank you.

**Comment by night** [comment]
Thanks for the feedback, but adding a setting for this is likely not something we would do. Window resizing is not something users do frequently, and the cost of uncollapsing chat is quite low enough already.
