### ISSUE TITLE
"Disable Homepage Autoplay" don't work

### ISSUE THREAD

**Issue by Arktikus** [night/betterttv#4389]
The Disable Homepage Autoplay function don't work every time. I turned it own, reloaded site and sometimes and not working. Tested it in Firefox Browser newest Addon update is installed.

**Comment by bbcmpc** [comment]
Can confirm that the feature is not working with:
Brave v1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
BetterTTV v7.2.91

**Comment by night** [comment]
I am not able to reproduce this issue in latest Chrome or Firefox.
