### ISSUE TITLE
Streamelements Kappagen Issue BTTV Gif Emotes!

### ISSUE THREAD

**Issue by KillPainHaters** [night/betterttv#4396]
Does anyone know how to fix animated gif emotes appearing on kappa gen streamelements preview screen. All my emotes appear static on the site when they are gif that should appear on screen is that normal? I went into the setting on twitch and changed it from static to animated already but my emotes on streamelements for kappagen appear static still. Any help is greatly appreciated. Thank you

**Comment by Nareese** [comment]
We do not make Kappagen and we do not support Streamelements products here.  If you are having issues with a Streamelements product, you will need to speak to them for support.
