### ISSUE TITLE
Add support for pronoun badges in chat

### ISSUE THREAD

**Issue by xenein** [night/betterttv#4398]
this is a suggestion for a future feature: 

So there is: https://pronouns.alejo.io/ offering a twitch sign on and several browser plugins. The idea is like

1. sign in with your twitch account on https://pronouns.alejo.io/
2. enter your pronouns
3. download the browser plugin
4. plugin shows pronouns for all users who did (1) and (2) in twitch chat next to the badges for VIPs, mod, ...

That's all neat, but: without the plugin there is no indication that users actually published their pronouns.
BetterTTV is used by a lot of folks on twitch I assume, so I'd love to see an option to query and display the pronouns from the other plugin via bttv. This would raise awareness that this feature does exist and would enable more folks to use it.

**Comment by night** [comment]
Unfortunately there is limited real estate in chat lines, and adding full length word support inline would take up too much space.
