### ISSUE TITLE
Rename button(pencil icon) don't show

### ISSUE THREAD

**Issue by vitamin300cc** [night/betterttv#4400]
Looks like display cards got a layout update. But currently the rename button don't show.
![Screenshot_3](https://user-images.githubusercontent.com/80501455/110889175-42552300-8320-11eb-8f36-1d2bf91b4cf6.png)

**Comment by vitamin300cc** [comment]
It just happened, on this day, I was checking on my twich.

**Comment by vitamin300cc** [comment]
It already fixed, thank you.

**Comment by Nareese** [comment]
Yup, the new modcard layout has broken pretty much everything BTTV adds to it... nickname button, user stats (account creation date, followers, views), mod action buttons and the current session chat history.
