### ISSUE TITLE
Message removing by 'non-mod chat delay' does not work when 'Show Deleted Messages' is enabled.

### ISSUE THREAD

**Issue by LabyrinthEar** [night/betterttv#4406]
By enabling Show Deleted Messages (BTTV setting) seems that prevent message removing from non-mod chat delay (Twitch setting).

**Comment by night** [comment]
This sounds like it is working as intended. When you show deleted messages, messages are never removed from the chat.

**Comment by LabyrinthEar** [comment]
Then it shouldn't work that way in my opinion. I understand all other features that changes and alter the view of Twitch but that one interfering directly to a channels preference setting which should be respected.
