### ISSUE TITLE
Resumen de estadísticas en el chat

### ISSUE THREAD

**Issue by BryanGris** [night/betterttv#4408]
Antes podías ver tus propias estadísticas y las de los demás con solo dar click en el nombre. ahora solamente es posible ver las estadísticas de los demás y no las propias. 

![1](https://user-images.githubusercontent.com/80677028/111130366-2383a600-8545-11eb-9067-b7ddea87a952.PNG)
![2](https://user-images.githubusercontent.com/80677028/111130368-241c3c80-8545-11eb-9224-1037a6f87207.PNG)

**Comment by night** [comment]
This issue is already fixed. Please update your browser extension.
