### ISSUE TITLE
Option to Disable "Restore Chat by pressing Up or Down"

### ISSUE THREAD

**Issue by Azihayya** [night/BetterTTV#441]
As an obsessive text editor, this feature is ABSOLUTELY PARAMOUNT to my decision to stick with BTTV or cut it from my browser- I love the notification features, but whenever I want to edit text quickly, not being able to use the arrow keys is a huge problem for me.

As a basic principle, if it's a feature of BTTV, it should appear in the Settings to be potentially disabled.

**Comment by night** [comment]
There's already an option.. "/linehistory off" in chat.

P.S.: Your rhetoric needs work. You essentially said "add this or I leave," which for us we really wouldn't care either way. You won't win many arguments when you threaten to leave. You should instead focus on explaining the necessity of the feature and the benefits of adding it (for everyone, not just yourself).

**Comment by Azihayya** [comment]
Rated 1 Star.

**Comment by night** [comment]
Oh no! What shall we ever do?!

Maybe you should heed my advice above, instead of continually making threats. As I already stated, that method of getting what you want doesn't work here (and never will).

**Comment by Azihayya** [comment]
You can just know, that this one person had a terrible experience submitting feedback. I'm in no way trying to 'get what I want' from you or your programming abilities- I was simply stating that having that feature is paramount to my experience. I worded it in no way that was rude at all, and below that I state that as a basic principle, if it's a feature of the program then it should be a setting. That's ALL the rhetoric that will ever be necessary to "prove to the developer that the feature is necessary" -- all that I needed to know is that it was a feature. 

I just want to let you know that you're very rude.
