### ISSUE TITLE
Create auth token with permissions

### ISSUE THREAD

**Issue by Braayy** [night/betterttv#4415]
Hi! So i want to create a app that adds and removes a list of bttv shared emotes at once.

To do that i've analized the requests that the betterttv website makes to the API (the add/remove shared emote endpoint) and saw that betterttv API uses jwt to make the authentication.

So because there is no auth token i need to use the user jwt to make the requests, but this is **very dangerous** because the user token should never be used directly by the user only by the website.

So the user need to extract and copy the user token and paste in my application, but if the user accidentally paste in the wrong spot (like he forgot to clean the clipboard and send the user token to someone via a message app) it could lead to someone hacking him.

**So my question is**: Am i allowed to make this app? Because it uses the BetterTTV API but there is no documentation.
i'm using a forced delay between each request to not overload the BetterTTV API.

**And my proposal is** to create the ability to the user create auth token with permissions, like on the dashboard page.

So if this token gets stolen, it could only add/remove shared emotes of the channel and the user could revoke access to it.

**Comment by night** [comment]
We do not support using our API in this way the moment, but you could open a feature request to ask for something like OAuth2 support if we document and support our API more broadly.
