### ISSUE TITLE
BTTV Emotes not showing on Clips

### ISSUE THREAD

**Issue by pepega-h** [night/betterttv#4416]
I can't say exactly when this started happening, but I think less than 1 month ago, BTTV emotes no longer appear on Clips. Other emote extensions are still showing, and i have not changed any BTTV settings.

I am using Firefox (ive tried a new firefox profile too) but i experience the same issue in Chrome.

Has anyone else noticed this?

Thanks!

**Comment by night** [comment]
i am not able to reproduce this on the twitch.tv or clips.twitch.tv pages for clips. another extension may be manipulating the Twitch standard DOM, which breaks our extension (which expects it to be identical to Twitch native)
