### ISSUE TITLE
Channel Points

### ISSUE THREAD

**Issue by TwistzzFF** [night/betterttv#4418]
Dear BTTV team,

How about a function where you can see in a ranking how much Channel Points a person has already collected in total and how many ChannelPoints the person at the moment owns.
Whether it is possible to do this is another ...

Would be cool if you could do it if it was possible!

Sincerely, TwistzzFF

**Comment by Nareese** [comment]
This is not possible, as Twitch does not provide any API access to know how many channel points a given users has, much less a total they've ever had, nor is there any way to know how they compare to other users on the channel, who may or may not be present in the channel at any given time.

**Comment by TwistzzFF** [comment]
Ok Thank you for Answer 🙌

Nareese ***@***.***> schrieb am Do., 18. März 2021, 23:20:
