### ISSUE TITLE
Make Disabling/Enabling built-in features like "Chat History" more obvious.

### ISSUE THREAD

**Issue by Azihayya** [night/BetterTTV#442]
This isn't a subject that requires a whole lot of rhetoric - in any situation, I'm just offering my experience. I'm the kind of person who knows quite a lot about rhetoric and where it should be applied.

**Comment by night** [comment]
And yet you open another issue request instead of replying to the old one.

**Comment by Azihayya** [comment]
I thought it was closed. It says it's closed.
