### ISSUE TITLE
all ttv emotes broken

### ISSUE THREAD

**Issue by diosimos** [night/betterttv#4422]
have cleared cache, uninstalled bttv, reinstalled, restarted computer, yet emotes are still showing up as broken images.
![c00972f29f03d88498bdd292a87ecb36](https://user-images.githubusercontent.com/73646672/111883354-64efd780-89c3-11eb-8bbe-061e72356278.png)

**Comment by Pacmanarea51** [comment]
Same issue here

**Comment by Vitti-alb** [comment]
you use malwarebytes on browser? try to deactivate

**Comment by brettmanjones** [comment]
That did the trick, had the same issue. Thanks!

**Comment by night** [comment]
This looks to be an issue caused by the Malwarebytes browser extension. You may need to report this false positive to their team, but otherwise as a temporary solution you may disable their extension or add our blocked domain to its allowlist.
