### ISSUE TITLE
GIF emotes are a still image all of a sudden

### ISSUE THREAD

**Issue by YornOW** [night/betterttv#4423]
any gif emotes in chat are just a still image, I do not know why this is happening and I cant seem to find an answer on here. Yesterday it worked perfectly fine but this issue appeared today. I already reinstalled ffz and bbtv but this didnt fix it.

**Comment by ZbigniewJez** [comment]
Just did a reinstall and it started to work again. Check if you can have it repaired too.

**Comment by night** [comment]
gifs cannot be stale in our browser extension. you may have another extension installed which is conflicting with ours.
