### ISSUE TITLE
I can’t log in to my account on the betterttv website.

### ISSUE THREAD

**Issue by scoffy12** [night/betterttv#4426]
Hello, I’m streaming on twitch.
I have a problem, I can’t log in to my account on the betterttv website.
my nickname is "scoffy_"
I pay a subscription every month, everything used to work.
Have you ever encountered this? and what to do?
![23111](https://user-images.githubusercontent.com/81149920/111958238-0bd88e80-8afe-11eb-84e0-ac3417226111.png)
![43234342423](https://user-images.githubusercontent.com/81149920/111958243-0c712500-8afe-11eb-9ab5-6894370f940c.png)
![34243432423](https://user-images.githubusercontent.com/81149920/111958247-0c712500-8afe-11eb-81c6-8de1d3dfd969.png)

**Comment by night** [comment]
your account is banned due to chargebacks being issued for your payments
