### ISSUE TITLE
Icons/emotes not displaying

### ISSUE THREAD

**Issue by chocoemo** [night/BetterTTV#443]
I've made sure it was bttv causing this issue by disabling bttv to double check, but I can't see emotes or badges of any kind that are placed next to people's names as shown in the image. I'm not sure if this is just a bug for myself or if anyone else if having the same issue, but I thought it might be a good thing to send over. 

Also, the blank messages are the emotes "venHeyGamers" and "CatBag" 

(This has happened in every chat as of about two hours ago)

![](http://img.prntscr.com/img?url=http://i.imgur.com/01sLu8v.png)

**Comment by teak** [comment]
Try uninstalling other addons you may have (FrankerFaceZ, AdBlock). Also try clearing your browser cache.

**Comment by chocoemo** [comment]
I removed all other addons and still continue to have the issue and I had already cleared cache as well as cookies. I just did so again just in case. The icons eventually load/start working but it takes probably about half an hour to an hour if I stay in one chat.
