### ISSUE TITLE
Settings not persisted accross restarts and browser tabs on Firefox when "delete cookies and site data when Firefox is closed" is enabled

### ISSUE THREAD

**Issue by madmox** [night/betterttv#4432]
I'm using firefox with "delete cookies and site data when Firefox is closed" option enabled and I don't want to disable this option for security reasons. I'm OK with logging in to Twitch every time I restart the browser (that's the whole point of it).

1st problem is that BTTV settings are not persisted accross FF restarts. I find this strange because other FF extensions allow me to persist settings accross restarts even with the Firefox cookie setting enabled. An example would be the extension [Social Fixer](https://addons.mozilla.org/en-US/firefox/addon/socialfixer/) for Facebook: I'm logged out of Facebook when restarting the browser, but I don't need to reload the extension's settings.

2nd problem is that the settings are not even persisted accross _browser tabs_ (BTTV settings are reset if I open Twitch in a new tab), although my Twitch session of course **is** persisted accross browser tabs (I'm still logged in in the new tab).

Both problems disappear when unchecking the "delete cookies and site data when Firefox is closed" setting, but as I said above, I don't want to disable this setting for security reasons.

**Comment by night** [comment]
This is due to how BetterTTV persists settings for cross-browser compatibility. We store settings in local storage, which allows BetterTTV to work in every browser with identical code. If you turn on these Firefox settings, you prevent websites from storing permanent data in your browser for the website. We may add [setting sync](https://github.com/night/betterttv/issues/766) at some point to help with this, but I don't have an idea of when that may be.

**Comment by madmox** [comment]
You missed the main issue in my post. Using local storage with "delete cookies and site data when Firefox is closed" should only prevent persisting settings accross browser restarts. **It should not prevent browser tabs of the same window to share these settings.**

I found a workaround though: in firefox, you can disable "delete cookies and site data when Firefox is closed" while still using custom settings for browser history, ticking "clear browser history when browser is closed" and selecting "cookies" & "site data" in the associated settings modal. This clears local storage and cookies when browser is closed as expected, but does not prevent local storage from being shared accross browser tabs.

Maybe the initial "no local storage shared accross tabs" is a firefox bug...
