### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Elyssy** [night/betterttv#4433]
If I enable the "Pin Highlighted Messages" switch, my browser using high CPU. (After 15 March Update)

Browser: Mozilla Firefox 87.0 64-bit
CPU: AMD Ryzen 3 2200G
GPU: AMD iGPU (2200G with Radeon Vega 8)

Note: It doesn't matter if the message is pinned or not. Same happening with Popout chat. 
Off Switch:
![resim](https://user-images.githubusercontent.com/19249969/112695835-d208de80-8e95-11eb-802b-4668d758312f.png)

On Switch:
![resim](https://user-images.githubusercontent.com/19249969/112695963-041a4080-8e96-11eb-8381-f464b93b0314.png)

**Comment by night** [comment]
You might be getting bamboozled. The pinned highlights message doesn't actually perform much additional computation. The majority of CPU usage comes from GIF emotes playing in BetterTTV. If you turn that off, you will use much less CPU in spammy channels.
