### ISSUE TITLE
The emote menu does not show up even when the emotes are enabled.

### ISSUE THREAD

**Issue by JolliIGIANT63** [night/betterttv#4435]
I've never had this problem till recently and I have no idea why it would start doing this but it is kinda annoying bc I can't use any channel GIF emotes :'
![Bttv PpP](https://user-images.githubusercontent.com/81464087/112715742-2b7e0700-8eb0-11eb-9c7c-185bf5a602b5.png)
![Bttv Settings (2)](https://user-images.githubusercontent.com/81464087/112715840-cecf1c00-8eb0-11eb-82fd-01475857c071.png)

(

**Comment by Nareese** [comment]
The setting to enable the emote menu is, unsurprisingly, `Emote Menu`.  Ensure that you have that setting turned on.
