### ISSUE TITLE
New poll system

### ISSUE THREAD

**Issue by TroyDota** [night/betterttv#4438]
Hi, recently a few streamers have complained to me about how strawpoll is lagging or does not update results fast enough. So I made my own one. https://poll.komodohype.dev/
Would it be acceptable if I made a PR for this repo adding it to the regex detection similar to strawpoll.

A poll like
https://poll.komodohype.dev/60619a063ec7460e45b15503
embeds easily with 
https://poll.komodohype.dev/embed/60619a063ec7460e45b15503

the source code for this is https://github.com/TroyDota/poll-frontend and https://github.com/TroyDota/poll-api

**Comment by night** [comment]
We have no current plans to add support for additional polling sites. We may actually remove support for strawpoll at some point since Twitch's built in polling looks to be better?

**Comment by TroyDota** [comment]
Ah, well we had a channel point reward where viewers would link a poll to ask the community. Regardless thanks for the resp.
