### ISSUE TITLE
Add more "items" to the Backup file

### ISSUE THREAD

**Issue by MattWolf6** [night/BetterTTV#444]
adding Blacklist Keywords, Highlight Keywords, Scrollback Amount and Nicknames to the backup file would be great, since it doesn't save them (for me at least)

**Comment by night** [comment]
Backup files already store this information (or should, for that matter). If you have a backup file that is not properly importing all your settings, upload the contents to a private gist (https://gist.github.com) and add the link to our contact form at https://nightdev.com/contact so we can look into the issue.
