### ISSUE TITLE
Disable Host Mode Autoplay feature broken

### ISSUE THREAD

**Issue by Lockesmith** [night/betterttv#4443]
When I load a channel's page who is currently hosting another channel, it plays the hosted stream, even when I have Disable Host Mode Autoplay turned on.

**Comment by night** [comment]
I'm not able to reproduce this behavior locally.

**Comment by Lockesmith** [comment]
It's still an issue for me.

If I leave the page when the channel raids, then use the browser's Back button, it immediately starts playing the channel they raided (& are hosting.) Also, if I stay on a channel's page when they're offline, & they start auto-hosting a channel, it starts playing the hosted channel.

**Comment by Lockesmith** [comment]
@night can you reopen this issue, since it's still an issue for me? Maybe the additional info I provided 15 minutes ago can help you reproduce it.

**Comment by night** [comment]
In the future, please include specific reproduction steps.
