### ISSUE TITLE
Personal emotes are not visible in Steramlabs plugin

### ISSUE THREAD

**Issue by kozaka-tv** [night/betterttv#4444]
Maybe this is not the best place to put the problem I saw in many streams, but Streamlabs page is like not really user friendly, and even I am not using it...but...

You can add to your stream a plugin/something (I am using Streamelements, but also Streamlabs has) to show the Emotes written into the chat live on the screen. This works with BTTV Emotes also! But if I am enter a personal Emote into the chat of a streamer who is using the Streamlabs plugin to show chat Emotes in the stream, the Emotes are not visible in the stream, personal Emotes will be not shown live in the stream (non personal...stream BTTV Emotes are working). It is visible only in chat (Streamers approved that personal Emotes are in chat visible).

Who can fix this problem?

**Comment by Nareese** [comment]
> Who can fix this problem?
Streamlabs.   Or Streamelements.  Or whoever actually makes the program that you're having problems with.  Not us. This has literally nothing to do with us or our extension.  If the emotes show up in Twitch chat, then BTTV is working perfectly.

Personal emotes are handled by a completely separate system from other emotes.  People making third party programs to display our emotes must implement that system if they want personal emotes to work.  If you have issues with the functionality of third party programs, you will need to take that up with whoever makes them.  Again, it has nothing to do with us, and there is nothing we can do about it.

**Comment by kozaka-tv** [comment]
Ok, I will try...but as I mentioned :) I am not using Streamlabs but my personal emotes are just not working with it, and it is annoying.

Thank you for the fast answer!
