### ISSUE TITLE
{Feature RQ} Auto Translate 

### ISSUE THREAD

**Issue by marioandluigi878** [night/BetterTTV#445]
when pepole double click a sentence in twitch it auto translate to their language for example if a spanish speaking person goes into a english speaking chat when the streamers/mods/viewers double click on what they said it auto translate for them into their language

**Comment by night** [comment]
Translation was removed for the time being. If it returns it would unfortunately only be offered as part of a paid plan in BetterTTV (since translation comes at a cost per lookup).
