### ISSUE TITLE
Multitwitch BetterTTV Settings

### ISSUE THREAD

**Issue by etmiranda** [night/betterttv#4460]
I'm watching two streamers on https://www.multitwitch.tv/ and despite having BetterTTV set to dark theme, the chats are showing in light theme.
![dark-theme-on](https://user-images.githubusercontent.com/3160644/115081823-e3f90280-9ed2-11eb-99a9-46d0d1e30bac.jpg)
![light-theme-multitwitch](https://user-images.githubusercontent.com/3160644/115081829-e4919900-9ed2-11eb-91dd-c76d5d4130e8.jpg)

**Comment by Nareese** [comment]
BetterTTV does not have a Dark Theme any more.  It uses Twitch's Dark Theme, and that setting is a leftover that simply follows and toggles Twitch's Dark mode setting.  It would appear that multitwitch.tv does not recognize Twitch's Dark theme setting.  There is nothing we can do to fix this, and you should take the issue up with multitwitch.tv instead.  Apparently some people have already done so, see also:  https://github.com/bhamrick/multitwitch/issues/30

**Comment by etmiranda** [comment]
Ah, thank you! I didn't know about that project. I'll close this. :)
