### ISSUE TITLE
Paid subscription doesnt count as being subscribed.

### ISSUE THREAD

**Issue by filipeastini** [night/betterttv#4461]
Hello,

After 7 months (Yea, I am this type of guy that buy a subscription and forget about it) it seems like my Pro Status doesnt count. Every month I got billed U$4.99 , but it still shows "get subscribed" and my emote counts is of non-subscriber.

![bug2](https://user-images.githubusercontent.com/6516555/115154267-5e02c600-a050-11eb-8958-be9c3ef35673.png)
![bug1](https://user-images.githubusercontent.com/6516555/115154270-5f33f300-a050-11eb-95cc-997439ecb9d2.png)

**Comment by Nareese** [comment]
I mean... it's right there in the payment history.  The last time you were billed was Feb 5th... almost 2 and a half months ago.  You are not currently subscribed.  If you want your subscription benefits back, re-subscribe.

**Comment by night** [comment]
For account issues please reach out to our support team: https://nightdev.com/contact
