### ISSUE TITLE
Left Side Chat hides chat options

### ISSUE THREAD

**Issue by Owl-Buster** [night/betterttv#4463]
When Left Side Chat is on, the regular chat options are cut off by the stream, and the option to collapse the chat is not longer visible/useable. (example screenshots included below) Both of these issues seems to have only started happening in the last day or so, I imagine due to the latest release of BTTV (just a guess).

Example of chat options being cut off - https://gyazo.com/c3bf631a5c8201652bd9cbebea796d05
Example of collapse chat option being hidden - https://gyazo.com/090fb7561ec33e6ab42c09b7816c9972

**Comment by movedoa** [comment]
This seems to only happen in theatre mode.
