### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by FatSkinnyKid** [night/BetterTTV#447]
I cant connect with my twitch.

**Comment by DTittel** [comment]
Could you please elaborate?

**Comment by FatSkinnyKid** [comment]
it gets stuck on "logging you in..."

**Comment by DTittel** [comment]
Where though is this on the manage.twitch.tv page?

**Comment by FatSkinnyKid** [comment]
when im in that window where it says "About, Setting etc.." and im under "channel" i cant connect my tiwtch

**Comment by FatSkinnyKid** [comment]
twitch
