### ISSUE TITLE
Tab Completion Emote Priority

### ISSUE THREAD

**Issue by namzor** [night/betterttv#4472]
whatever i set this option to it still prioritize emotes in chrome/windows

**Comment by night** [comment]
I am not able to reproduce this behavior when testing locally.

**Comment by namzor** [comment]
I've removed the extensions, and installed it again, it doesnt matter if the slider is on or off it behaves the same either way. is there a file i can check what its set as or how can i troubleshoot this? the streamers name doesnt even show up no matter how many times i tab, its only emotes, so it makes the extension kind of more of a hindrance than an addition to the browser. as soon as i remove BTTV i can tab complete the streamers name without problems (notice im not using @ first)
