### ISSUE TITLE
black/white readable colours 

### ISSUE THREAD

**Issue by babybophop** [night/betterttv#4486]
this feature i used to love as im colorblind but last few day in chat the names are fine but the text is no longer white i have seen a range of coulers and as im a active mod for a few streamers this makes modding very hard

**Comment by night** [comment]
I am not able to reproduce this behavior locally. If you're still having trouble, make sure you've enabled the "Disable Name Colors" setting in the BetterTTV settings. If problems persist, try disabling other extensions you may have installed (they can sometimes conflict with BetterTTV by changing the page DOM structure).
