### ISSUE TITLE
Auto activate Javascript

### ISSUE THREAD

**Issue by Mrnoname1000** [night/BetterTTV#449]
I mainly watch Twitch Plays Pokemon, and it's a whole lot more enjoyable with [this script](http://jpgohlke.github.io/twitch-chat-filter/) activated. Would it be possible to implement this script or a way to enter custom scripts?

**Comment by night** [comment]
I suggest installing TamperMonkey (https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) and then  installing this UserScript into TamperMonkey.
