### ISSUE TITLE
OAuth2 Support for the API

### ISSUE THREAD

**Issue by gempir** [night/betterttv#4491]
Albeit undocumented, Bttv has a very useful and well designed API and using it programmatically would be really nice.

Related issue about this https://github.com/night/betterttv/issues/4415

Personally, I'm not sure if OAuth2 is the most-straightforward solution to this Problem, but since Night suggested it in the reply I'm asking for it here.

I know this isn't an easy or small task, but I just wanted to have this issue open to signify mine and other people's interest in it.

**Comment by night** [comment]
Thanks for the request. BetterTTV has added an experimental OAuth2 API we're open to sharing with interested third parties. If you have a compelling use case for integration, please [reach out to us](https://nightdev.com/contact?product=betterttv&topic=business_development).
