### ISSUE TITLE
Option to revert /me to coloured text

### ISSUE THREAD

**Issue by Rosuav** [night/betterttv#4492]
Twitch recently changed ACTION messages (/me) to show with italicized text. This violates a lot of expectations, including that an ACTION should read as a full sentence instead of separating the name from the text ("MyName waves hello"), and has resulted in significant amounts of backlash. Until/unless Twitch revert this change, it would be very helpful to be able to change this client-side.

(Unfortunately this can't fix the new-user problem, so I would still like Twitch to fix this properly. But it would help a lot of us.)

**Comment by night** [comment]
duplicate of #4488

**Comment by Rosuav** [comment]
Wait, how come I couldn't see that one when I searched? That's weird
