### ISSUE TITLE
Editor page error message

### ISSUE THREAD

**Issue by cutecrait** [night/betterttv#4503]
It'd be cool to add an error message to the editor page.
I tried adding my mod, but it just gave me the red exclamation mark.
By means of network analysis and trying to add aceu as a test, i found out that the user has to have logged into better ttv once before, else the request to the bttv api yields "user not found".
This isnt really an issue, but I think a lot of people had this problem in the past.
Either an error message or a simple preemptive warning on the page would do the trick.

**Comment by ExALPHAxOMEGAx3** [comment]
Having the same issue

**Comment by ExALPHAxOMEGAx3** [comment]
ok i fixed it just log out and in again it works
