### ISSUE TITLE
BTTV causes Twitch Giveaways extension not to work

### ISSUE THREAD

**Issue by Maxhype** [night/BetterTTV#451]
https://chrome.google.com/webstore/detail/twitch-giveaways/poohjpljfecljomfhhimjhddddlidhdd?utm_source=chrome-app-launcher-info-dialog

When above extension is enabled Twitch Giveaways extension is not working.

**Comment by night** [comment]
We don't have the ability to fix this, sorry. BetterTTV follows the exact same DOM format as regular Twitch chat, but the method of DOM manipulation being watched by that add-on breaks when BetterTTV takes over. You can complain instead to the author of the add-on: https://github.com/darsain/twitch-giveaways/issues

**Comment by Maxhype** [comment]
Please read the last post in this thread:

https://github.com/darsain/twitch-giveaways/issues/7

**Comment by night** [comment]
Please read the date on the last post in that thread.
