### ISSUE TITLE
Left chat mode bugged on Safari in theatre mode

### ISSUE THREAD

**Issue by Ursadorable** [night/betterttv#4517]
Using Safari 14.1 with TamperMonkey.

While in theatre mode with left chat turned on, the chat window is a little mangled at the top.

*note* Right side chat works fine.

![image](https://user-images.githubusercontent.com/16415742/118333692-5f95a180-b4c9-11eb-9f4d-18a2684a7a5a.png)

Additionally, if you try to access the gear menu, it's partially chopped off.

![image](https://user-images.githubusercontent.com/16415742/118333820-a71c2d80-b4c9-11eb-94da-51bdb3d78e73.png)

**Comment by night** [comment]
I'm not able to reproduce this in theater mode or normal mode with safari 14.1. It is possible you have some other extension installed which is conflicting with ours. If not, please post specific steps to reproduce.
