### ISSUE TITLE
change the color of the "Chroma Key Mode"

### ISSUE THREAD

**Issue by TheGloriousArgonaut** [night/BetterTTV#452]
do you think it would be possible to change the color of the "Chroma Key Mode"? I use this feature allot but the default black chroma color actually distorts allot of twitch tv emoticons I like seeing. If it would be possible to change the chorma key color to a color of you choosing besides the default "black" that would be awsome! Keep up the great work, BTTV has improved my twitch expereince by leaps and bounds, you are doing gods work. ;) much <3 - TGA

**Comment by night** [comment]
We will be discontinuing the Chroma Key mode soon, so I wouldn't advise using it. Use our OBS Chat instead: https://nightdev.com/obschat
