### ISSUE TITLE
Picture in picture written

### ISSUE THREAD

**Issue by thiagohass** [night/betterttv#4535]
![Screenshot_1](https://user-images.githubusercontent.com/84355029/118563395-da1e2580-b744-11eb-87bd-44a1506bdee3.png)

I would like to report the BUG where the writing of PICTURE IN PICTURE appears, I left an image as an attachment.

**Comment by night** [comment]
We rolled out an update for this, but it is still pending release on Firefox. You may need to update your extension if it hasn't been updated already.
