### ISSUE TITLE
Bot indicator not aligned correctly

### ISSUE THREAD

**Issue by radoon** [night/betterttv#4536]
Bot indicator is displaying on multiple lines instead of inline with the bot's chat message. Likely linked to the twitch css update.
![image](https://user-images.githubusercontent.com/4379909/118564576-cadfad80-b72d-11eb-9ff5-a2919c6c3cc3.png)

**Comment by night** [comment]
We rolled out an update for this, but it is still pending release on Firefox. You may need to update your extension if it hasn't been updated already.
