### ISSUE TITLE
Setting Suggestion - Ignore Followed Offline New Videos Sorting

### ISSUE THREAD

**Issue by NeoAcario** [night/betterttv#4538]
How about a setting for BTTV that sorts offline by PURELY alphabetical.. ignoring the 'New Videos' setting for offline channel filter? 

Having to scroll through 5 pages of New Videos for off line followed channels when trying to find an off line pre show channel has been driving me nuts for months.

**Comment by night** [comment]
That isn't a sorting method supporting by Twitch's API, so we wouldn't be able to support it
