### ISSUE TITLE
BetterTTV settings not showing up

### ISSUE THREAD

**Issue by zoelouisexo** [night/betterttv#4539]
Nothing is showing up no matter how many times i've reinstalled - i've tried it on firefox as well as chrome and it's the exact same issue.

Anyone know how to fix this? I've cleared my cookies and cache, i've logged out, logged in, disconnected betterttv from my twitch account, reconnected it, deleted the extension and re downloaded it and yet i still don't have the betterttv settings, just the normal settings menu that twitch uses.

**Comment by somepasta** [comment]
It's not just you, it seems something on twitch's side has changed since yesterday. But you can still access the BetterTTV settings by clicking on the chat settings menu.

**Comment by zoelouisexo** [comment]
Thank you! Hopefully it gets fixed soon.
