### ISSUE TITLE
"JTV Monkey Emotes" Setting not persistent

### ISSUE THREAD

**Issue by kd8lvt** [night/BetterTTV#454]
Whenever a refresh occurs (which means after every time I set the setting to "off" in the first place) the JTV Monkey Emotes setting gets set back to true. I haven't observed any other settings getting set back to their defaults, but I don't change much. Just the black background, JTV emotes to false, and alpha chat tags. There is no crash log, as it isn't a crash, so I'll have to give you the old-fashioned way of "Heres my specs etc." I have Windows 8.1, with Firefox version 38.0.1 As well as this, I have tried upgrading to the newest version of BTTV, to no avail. I'm excitedly waiting for a patch for this, as, well, I don't find blue monkeys very attractive for emotes.

Thank you for your time,
    kd8lvt

**Comment by saiyr** [comment]
Experiencing the same on Chrome as of this morning. Same with BTTV Emotes.
