### ISSUE TITLE
No autocompletion anymore

### ISSUE THREAD

**Issue by spychest** [night/betterttv#4540]
Hi,

When I'm writting "@" it doesn't ask me for autocomplete anymore. Is that normal or is it a bug ?

Thank you.

**Comment by Dracowrath1** [comment]
I'm having a similar issue, along with typing : to find emotes not working, and when I try to access the settings for better ttv in twitch, the option is nonexistant.

**Comment by eltharynd** [comment]
yes... you can see the autocomplete bottom (around the chat text-input) popping out but the top part is missing....
there a bunch of errors in console.
Reinstalling plugin didn't work for me.. 

![image](https://user-images.githubusercontent.com/32698314/118723816-26916000-b82e-11eb-9d1f-52d85d598645.png)

**Comment by Lugzx** [comment]
> Hi,
> 
> When I'm writting "@" it doesn't ask me for autocomplete anymore. Is that normal or is it a bug ?
> 
> Thank you.

Host button is gone for me too.

**Comment by burtek** [comment]
Twitch changed class names for many elements, it's not a browser thing. Devs here need to update extension with new classnames

@Lugzx that's already reported in #4537

**Comment by night** [comment]
that's not a feature of BetterTTV. you likely use a different extension which has broken.
