### ISSUE TITLE
BetterTTV emotes does not show in Streamlabs overlay

### ISSUE THREAD

**Issue by iFranchie** [night/betterttv#4542]
I'm using Streamlab OBS software to stream on twitch, and I'm reading the comments from a built-in chat overlay. However, BetterTTV emotes are not working on that chat overlay, while it is working on twitch, Streamlabs chat, and the chatbox inside the stream.

here is screenshot for further clarification

![2021-05-20 07_53_50-Streamlabs OBS](https://user-images.githubusercontent.com/84491259/118921556-0c947200-b941-11eb-97ec-5fd5e35e4cf7.png)

**Comment by Nareese** [comment]
We do not make Streamlabs OBS, and we have nothing to do with any BTTV functionality in their software.  If you are having issues with a Streamlabs product, you will need to ask them for support.
