### ISSUE TITLE
Host button disappeared

### ISSUE THREAD

**Issue by SharkiB** [night/betterttv#4543]
The 'Host Button' has recently disappeared within the last 2 days. I updated my Microsoft Edge and that was when it happened, I think.

**Comment by robonxt** [comment]
+1. BTTV also disappeared from the chat settings

**Comment by dmreins** [comment]
Disappeared from both chrome and edge for me - approx the same timeframe.  I checked settings and host button is still enabled.

**Comment by TitoLeproso** [comment]
Same here with Opera browser (Chrome Extension)

**Comment by Namaretuklefu** [comment]
Same here - Mozilla firefox. Looks like twitch made changes to their player so it ruins everything else. again...

**Comment by night** [comment]
duplicate of #4537
