### ISSUE TITLE
Left Chat - video player not in full size

### ISSUE THREAD

**Issue by AgentEpsilonn** [night/betterttv#4544]
Video player is not in full size. Problem is resolved when turning off left side chat. Only occurs when it is turned on.

![Twitch - Video glitch](https://user-images.githubusercontent.com/84542841/119044528-2ba9f880-b96f-11eb-8a0a-fa8171bcb3e7.jpg)

**Comment by MoDog0** [comment]
Same Issue here. Turning left side chat off corrects the issue, however then left side chat is off :(

**Comment by night** [comment]
I'm not able to reproduce this behavior on Chrome. Please post reliable reproduction steps or we are unable to fix any issues.
