### ISSUE TITLE
Left Chat + Collapsed Following List Causes Following List to Never Open in Chrome

### ISSUE THREAD

**Issue by jGonne** [night/betterttv#4546]
With a collapsed following list and Twitch Chat being set to left side, the following list cannot be expanded again when hovering over it. The only way to expand the following list to see the names of the viewers, the number of viewers, etc is by setting the following list to stay expanded. The following images show what happens before hovering over the list, initially hovering over the list, and hovering over the list after a second, respectively.
![Before hovering the list](https://user-images.githubusercontent.com/84649293/119245129-c90a5580-bb44-11eb-8c85-f4602021ffca.png)
![Initially hovering the list](https://user-images.githubusercontent.com/84649293/119245131-cb6caf80-bb44-11eb-95eb-20e6b2d6672d.png)
![Hovering the list after a second](https://user-images.githubusercontent.com/84649293/119245133-cd367300-bb44-11eb-80d2-ad9642d63905.png)

**Comment by night** [comment]
I'm not able to reproduce this behavior on Chrome. Please post reliable reproduction steps or we are unable to fix any issues.
