### ISSUE TITLE
split chat issue

### ISSUE THREAD

**Issue by psych0se** [night/betterttv#4548]
Hello, in the mod view the chat with activated split chat is displayed as follows.

https://media.discordapp.net/attachments/229484052929970177/845973870489108530/4508859944eafba5b37bf196471f7a8f.png

Browser: Google Chrome

**Comment by Rerdan** [comment]
Yours looks better than mine. For me, it's unreadable now: https://imgur.com/a/p46msjs

Using Brave. It's fine on Chrome, currently.

**Comment by canadianakin** [comment]
I am encountering this issue on Edge browser as well. Strangely, I am only seeing it with embedded chat and not on Twitch itself.

**Comment by uaiz** [comment]
Same is happening to me. It's ok in non-mod chat, it's a white background and white font in mod chat.
