### ISSUE TITLE
(IMPORTANT) can't log in/authorize Twitch account 

### ISSUE THREAD

**Issue by Kartik-45** [night/betterttv#4549]
I'm using the new Brave Browser(Best Browser in the world) and I can't log in/authorize Twitch account!!!

https://user-images.githubusercontent.com/80390916/119260000-74231980-bbee-11eb-9912-3ae97f4e2fc5.mp4

**Comment by night** [comment]
I'm not able to reproduce this behavior. It is meant to open a popup, but perhaps you have somehow disabled popups in your browser.

**Comment by Kartik-45** [comment]
I have pop-ups on but didn't record anyways the issue is I cant log in with my Twitch account on brave  browser
