### ISSUE TITLE
Left Side Chat shrinks the player

### ISSUE THREAD

**Issue by storyofsaint** [night/betterttv#4550]
Whenever I enable Left Side Chat, the Twitch player sadly shrinks. This provides a bad experience on the site and it's only been happening recently so I assume it's a bug.

Attached two screenshots, one with left side chat, one without
![Screenshot 2021-05-23 200459](https://user-images.githubusercontent.com/65004716/119273305-2dd7b580-bc02-11eb-9567-5579a4244db1.png) 

![Screenshot 2021-05-23 200627](https://user-images.githubusercontent.com/65004716/119273346-5eb7ea80-bc02-11eb-83a9-f80f3d723755.png)

**Comment by night** [comment]
We are not able to reproduce this behavior. Try disabling other browser extensions which may conflict with ours.

**Comment by storyofsaint** [comment]
I disabled all of my extensions and it's still happening
