### ISSUE TITLE
Host Button not showing in Firefox 88.0.1, shows in Edge, Opera, Chrome..

### ISSUE THREAD

**Issue by Tameth** [night/betterttv#4563]
Only in Firefox the host button is not appearing from what I can see..
The update fixed the problem except for Firefox..

**Comment by Nareese** [comment]
The newest version (7.2.99) is not yet available for Firefox, because they are currently requiring a manual review for every new version, and they have not yet reviewed it.  It should be available "soon™"

**Comment by Nareese** [comment]
Firefox has now released 7.2.99.  If your browser has not automatically updated, you should be able to force a manual update now from your Addons page.

**Comment by Tameth** [comment]
Thank You !..
