### ISSUE TITLE
BTTV button missing in Twitch, under chat

### ISSUE THREAD

**Issue by ATaleTold** [night/betterttv#4564]
Firefox 88.0.1, 64-bit
Windows 10
Started about 3 weeks ago.

BTTV emotes still work. I can still type in an emote and it will show up in Chat, but the button's not working.

I've tried deleting all cookies and cache from the last month, but still not working.

Is there anything that I can do to fix this?

**Comment by Nareese** [comment]
Ensure that the setting `BetterTTV Emote Menu` is turned on, especially if you have cleared cookies and cache, as the default setting is off.
