### ISSUE TITLE
Filter Twitch Drop messages

### ISSUE THREAD

**Issue by Ruby437** [night/betterttv#4566]
Twitch drops spam the entire chat whenever they become available so I'd appreciate an easy way to filter the default message 
`I just claimed <item>! Thanks for the Drops @Channelname`

Also, it would be kind of neat if we could disable the automatic message it puts into your Send box whenever you claim a drop.

**Comment by Freso** [comment]
Seems like Twitch’s behaviour on drops has changed, so I don’t think this is relevant anymore.

**Comment by Ruby437** [comment]
This is correct.
