### ISSUE TITLE
Tampermonkey not working with BetterTTV and FrankerFaceZ

### ISSUE THREAD

**Issue by Mrnoname1000** [night/BetterTTV#457]
When BetterTTV, FrankerFaceZ, and Tampermonkey are installed, the [Twitch Plays Pokémon Chat Filter](http://jpgohlke.github.io/twitch-chat-filter/) doesn't filter right. I've tried the bookmarklet and it seems to only clear what has already been received in chat.

**Comment by night** [comment]
BetterTTV implements its own chat handler, so unless other extensions have built support for our parsing they may not be compatible.
