### ISSUE TITLE
Blacklist Specific Emotes

### ISSUE THREAD

**Issue by FreshCutFries** [night/betterttv#4585]
It would be nice to be able to disable specific emotes. I've hesitated using this extension for years because I don't want to see Pepe ever, but it's spreading to the point where it's difficult to ignore.

**Comment by Nareese** [comment]
See this response from night to a similar question:  https://github.com/night/betterttv/issues/4318#issuecomment-799006099

**Comment by FreshCutFries** [comment]
It'd be nice to hear some reasoning behind this? Too much work? Or just actively hate people that don't want to see a hideous frog??
