### ISSUE TITLE
Grey emotes

### ISSUE THREAD

**Issue by Alibeg** [night/BetterTTV#461]
Instead of the grey emotes like this - ;) my bttv inserts this - ^;)$

**Comment by night** [comment]
I cannot reproduce any issues. Clear your cookies/cache, and remove any other add-ons that affect Twitch.

**Comment by Alibeg** [comment]
Thanks for the quick reply, but clearing cookies/cache doesn't help and I don't have any other add-ons. I know other users who get this issue as well. Some of them have just installed bttv.

**Comment by night** [comment]
Unfortunately since default emotes are parsed by the chat server, then it would have to fall under a Twitch issue. Check that the issue doesn't happen after refreshing or disabling BetterTTV.

**Comment by Alibeg** [comment]
Strangely it happens even without BTTV installed, must be a twitch issue I suppose, sorry for taking your time and thanks :) Have a lovely day :)

**Comment by cletusc** [comment]
Just an FYI that if this is when using the emote menu that BTTV provides, then it is an issue with the emote menu. I've had several reports saying the menu was bugged on those emotes and haven't had a good chance to look into it.
