### ISSUE TITLE
[Feature Request] Moving Community Highlights

### ISSUE THREAD

**Issue by lukhuber** [night/betterttv#4613]
If chat direction is reversed, community highlight cover the first 2-3 messages. An option to move the community highlights to the bottom of Twitch chat would be great or if chat direction in changed, it should automatically move the community highlights to the respective opposite site.

**Comment by night** [comment]
Thanks for the suggestion. We intentionally leave the other UI as-is for other areas around chat when reversing chat direction. I think moving static parts of the UI like this may result in confusion.
