### ISSUE TITLE
Emotes disappearing in moderator view

### ISSUE THREAD

**Issue by MightyFrenchCow** [night/betterttv#4615]
Hi,

I've talked to several other moderators and we all have a bug with BTTV : in the moderator view, after a random number of minutes, some of our emotes disappear. If I write the emote manually, I don't see it in chat but the viewers can see it. To see the emote again, I need to refresh the page.

At first I thought it was because I was using both BTTV and FFZ but after discussing with other moderators, some of them told me that they were experiencing the same bug without using FFZ. I've never experience this bug when being a simple viewer, only in moderator view.

It's not a major issue but an annoying one. I hope it will get fix someday.

Have a nice day !

**Comment by night** [comment]
Do you have any sort of reliable way to reproduce this? In general, unless we have a means to reproduce this behavior locally it's generally impossible to fix.

**Comment by MightyFrenchCow** [comment]
I've asked one more time to other moderators and apparently some of them that experienced this bug without BTTV (or FFZ). So the bug is probably from the moderator view itself and not BTTV. I close this issue.
