### ISSUE TITLE
Add settings segments/groupings

### ISSUE THREAD

**Issue by deefdragon** [night/betterttv#4619]
BTTV has many settings that allow a user to customize the appearance of twitch. The current list however, being alphabetical only, makes it a bit hard to find the correct settings and configure as wanted. 

I suggest the creation/addition of groups (likely in drop-downs) in the settings to allow for the sorting of the options. Ideally, these groups would be multi-layered for example:

- `Chat`
  - `Content`
    - Hide Bits
    - Show Deleted Messages
  - `Look and Feel`
    - Disable Name Colors
    - Reverse Message Direction
    - Split Chat
- `Layout`
  - Hide Friends
  - Hide Offline Followed Channels
- `Player`
  - Automatic Theatre Mode
  - Disable Host Mode Autoplay

**Comment by dclstn** [comment]
#4500 Implements grouping and most likely will be merged soon

**Comment by deefdragon** [comment]
Ah, missed that. Love the re-design. Do the groups allow sub-groups?
> Settings now have an attribute "category" to help with organizing

Implies they only have one level of category.

Regardless, I will close this ticket when #4500 is merged in.

**Comment by dclstn** [comment]
> Ah, missed that. Love the re-design. Do the groups allow sub-groups?

Sub-groups won't be a thing however some settings will be merged into checkbox groups, the sidebar for example will be a checkbox group containing the ability to toggle certain sidebar elements.

Glad you like the design!

**Comment by night** [comment]
Closing this as this work shipped last year.
