### ISSUE TITLE
Re-examine #3320 (Name Colors)

### ISSUE THREAD

**Issue by deefdragon** [night/betterttv#4620]
#3320 now has 9 duplicates that have been closed referencing it, and at least one that was closed without reference as a duplicate. The original reason for the closure was 

> The volume of people that complain about this is such a low number that it's not worth maintaining an option and cluttering the options menu.

_https://github.com/night/betterttv/issues/3320#issuecomment-447686024_

I believe that it has become apparent that a reasonably large number of people are requesting this issue to the point that it should be seriously reconsidered.

The original feature request to change the name colors to colorblind-friendly (https://github.com/night/betterttv/issues/546) even had a comment requesting it be an option instead of just the default.

As to the options clutter, I made #4619 because I think the options need to be re-organized anyway.

**Comment by night** [comment]
There already is a setting for this: Readable Name Colors
