### ISSUE TITLE
No longer have access to majority of emotes on channel or personal emotes 

### ISSUE THREAD

**Issue by JonnyJoestar** [night/betterttv#4626]
![image](https://user-images.githubusercontent.com/51154861/122939486-91711200-d36b-11eb-8eae-7db3322d30b2.png)

**Comment by Nareese** [comment]
Addtional emotes and personal emotes are features for subscribers of BetterTTV Pro.  Since those features are not available to you, it is likely your subscription has lapsed.  Check your subscription status.  https://betterttv.com/dashboard/pro

**Comment by JonnyJoestar** [comment]
I was under the assumption with the wording on that page that you keep them after. Kinda sucks. thanks
