### ISSUE TITLE
Links with %20's are broken

### ISSUE THREAD

**Issue by Mrbysco** [night/BetterTTV#463]
Without Bttv the links work that contain "%20"
With BTTV the "%20" gets replaced with spaces making the links invalid.

**Comment by Mrbysco** [comment]
I used a bot that can learn commands to learn a command of a modpack I manage. For me it displays with spaces. For another person without bttv it displays proper.
http://www.twitch.tv/mdiyo and type !modpack <-- reproduce

**Comment by night** [comment]
I am not able to reproduce this issue, both over flash and websockets for Twitch's chat. There was an issue on Twitch's end last night with double decoding, so this may have been that same issue and it may be fixed.
