### ISSUE TITLE
let mods/editors pay bttv pro

### ISSUE THREAD

**Issue by vinaldi** [night/betterttv#4631]
Hi, as the title says i would suggest to add the possibility for the mods (or in general the editors) to let them pay the subscription of bttv pro.
I know that this isn't a thing that a lot would be intrested in, but i think it would be a nice add.

**Comment by DorCoMaNdO** [comment]
You can gift BTTV Pro, I don't recall this being possible some time ago but for at least a month now it's been possible, been done in a channel I moderate.

**Comment by night** [comment]
Thanks for the suggestion. We added gifting to solve this use case recently.
