### ISSUE TITLE
Host button no longer appears

### ISSUE THREAD

**Issue by Px05119** [night/betterttv#4632]
Host button doesn't appear on BetterTTV 7.2.99 running within Chrome 91.0.4472.124.

**Comment by OtakuAnime-M** [comment]
Google Chrome Version 91.0.4472.114 (Official Build) (64-bit), BetterTTV v7.2.99
also has no host button

**Comment by BlackLotus69** [comment]
Opera v77.0.4054.146, BetterTTV v7.2.99 also has no auto host button

**Comment by imarquitoo** [comment]
Google Chrome Version 91.0.4472.114 (Official Build) (64-bit) //// BetterTTV v7.2.99 the host button is not appearing
![host button](https://user-images.githubusercontent.com/86538298/123527892-820e0380-d6a0-11eb-9707-1880f3a21628.png)

**Comment by gtbmusicislife** [comment]
The host button also doesn't appear on BetterTTV v7.2.99 on Microsoft Edge Version 91.0.864.59 (Official build) (64-bit)

**Comment by PXAbstraction** [comment]
Same issue and versions as imarquitoo.
