### ISSUE TITLE
Can't chat

### ISSUE THREAD

**Issue by MrMeeseeks33477** [night/betterttv#4647]
I was messing around with the Better TTV settings, and saw "change text size". I decided to set it to 99999 to see what it would look like, but now all I see is a white background where the chat should be. I can't send or see messages, and I can't change it back because the settings button isn't there anymore. I can turn off Better TTV, but I like the emotes and want to keep it. The only thing I can think of to fix it and keep the extension is to uninstall and re-install, but I don't really want to do that. Is there anything I can do other than that? If so, please respond to this.

**Comment by DorCoMaNdO** [comment]
BTTV settings are accessible from the avatar menu in the top right.
