### ISSUE TITLE
Add API integration for mod access selection

### ISSUE THREAD

**Issue by EyalMK** [night/betterttv#4656]
So, it's a pretty basic idea but I don't know Twitch's policy on API restriction for this 3rd party addon.
Add API integration for Twitch's channels moderation settings to allow users to add moderators they want that can add/remove BTTV emotes, etc... for the channel. Like Nightbot's system.

P.S: if this feature already exists (wouldn't be surprised), or if Twitch's policy doesn't allow it, I'd appreciate some elaboration on the matter :)

**Comment by night** [comment]
Users can already add editors on their dashboard over at https://betterttv.com/dashboard/editors
