### ISSUE TITLE
Darken TV + Theater mode

### ISSUE THREAD

**Issue by nylights** [night/BetterTTV#466]
Darken TV is off. But when I put theater mode it goes Dark.

**Comment by night** [comment]
So turn on DarkenTTV in the settings..

**Comment by nylights** [comment]
Sorry, I wasn't very clear. DarkenTTV was off (chat is white). And I thought it should stay off if I click Theater mode. However, Theater Mode turns the feature on automatically.

**Comment by night** [comment]
Theater mode in native Twitch darkens the chat, so we must darken it too.
