### ISSUE TITLE
2 Extra shared emotes for renewed monthly subscription not added

### ISSUE THREAD

**Issue by F1ickontwitch** [night/betterttv#4660]
I had auto renewal for my subscription but since my card denied it then I readded paypal as the payment method and it finally charged it for this new month but it didn't give me my two additional slots, this also happened one time before but didn't mind it. I'm guessing since it declined it the system to give me the extra shared emotes negated it, but I did pay for this month again so I should be getting the extra 2 shared emotes. 

![](https://i.gyazo.com/a8a43dc62e9dd9f6786b3f34f59625d8.png)

![](https://i.gyazo.com/8cc6da974489ed38c84fcbe6121fe9ad.png)

**Comment by night** [comment]
Additional slots are assigned on time subscribed, not when a payment occurs. You will need to wait until the exact time you originally subscribed to get the additional slots.
