### ISSUE TITLE
7TV emote support

### ISSUE THREAD

**Issue by DorCoMaNdO** [night/betterttv#4662]
Can't see any mention of it in other issues, not sure if there's a reason for that other than the service being relatively new, but it'd be neat if 7TV emotes could be made accessible to BTTV users just like FFZ emotes are.

**Comment by heeheex2** [comment]
Agreed, the bttv emote menu is the best, so being able to see 7tv emotes would be extremely convenient.

**Comment by TemDevz** [comment]
bump

**Comment by dclstn** [comment]
Please see: https://github.com/night/betterttv/pull/4840#issuecomment-922406564
