### ISSUE TITLE
Issue with duplicate emote detected

### ISSUE THREAD

**Issue by gaminganimator07** [night/betterttv#4670]
![gaming animator 2021_hello-02](https://user-images.githubusercontent.com/87352750/125390397-712fe400-e368-11eb-9954-c03e82c62d4d.png)
Every emote I try to upload says its a duplicate of the emote:
https://betterttv.com/emotes/5879919fc1869d57085758b7

My emotes don't look like that as they are of my character.... I'll attach one of them....
![gaming animator 2021_hello-112](https://user-images.githubusercontent.com/87352750/125390323-4fcef800-e368-11eb-91b8-e9c972cb854e.png)

**Comment by night** [comment]
You need to make your emote more significantly different in order for the system to detect it as unique. You have too much whitespace/transparency.
