### ISSUE TITLE
Suggestion: Feature to opt-out of auto joining a raid

### ISSUE THREAD

**Issue by SpottedGiraffes** [night/betterttv#4676]
This was posted 3 years ago with no update.  So I figured I'll try reposting to see if this gets any traction.  Super annoying feature that auto opts you in to joining a raid (as a viewer) unless you click a prompt.  If you are tabbed somewhere else, away from the computer at the time, or have fallen asleep to a chill streamer you like this can be very annoying.  Please help.

**Comment by night** [comment]
duplicate of #2936
