### ISSUE TITLE
Problems with disabled color of usernames

### ISSUE THREAD

**Issue by Youvula** [night/betterttv#4678]
When I start flipping through the chat with this feature, the colors come back. Cleaned the cache. And tried in another browser. Nothing helps. Thank you in advance.

**Comment by night** [comment]
What do you mean by flipping through the chat?

**Comment by Youvula** [comment]
When I scroll through the chat to find the message above for example.

**Comment by Arthrowpoda** [comment]
Yeah I have the same problem. If you reload the page or change to a different stream the colors are disabled again.

**Comment by night** [comment]
I see. It looks like our styles are getting removed on scroll.
