### ISSUE TITLE
Make the subscribe, follow and chat buttons whatever colour we want

### ISSUE THREAD

**Issue by VixenSlayer** [night/BetterTTV#468]
Make it so we can choose what colour we want the subscribe, follow and chat buttons whatever colour we want. I.E. Red, blue, green, orange etc

**Comment by night** [comment]
While we might eventually add more customizability to the theme, it most likely won't be soon and isn't on our roadmap at this time. Maintaining theme changes with just our default themes is already enough work, and we're too busy to take on more style changes that we need to then maintain. I suggest looking into [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en), which allows you to add your own custom CSS to any website.
