### ISSUE TITLE
Settings backup/restore issues

### ISSUE THREAD

**Issue by Nareese** [night/betterttv#4689]
This morning, a user in discord reported that "the new settings panel was not backing up blacklist keywords".  In the process of testing this, I discovered two issues:

1/ attempting to import a legacy backup file into the new settings panel does indeed fail to import blacklist keywords, and, without having done a full analysis of it, most other settings fail to import as well.  This is not a super old backup, it was made a month ago, in the 7.2.99-100 timeframe.  Importing a backup made with 7.3.x works successfully, except for...

2/ Reset to Default will set Twitch back to light mode if dark mode is enabled.  Restoring a current (just made) backup that has `bttv_darkenedMode: true` does not set it back to dark mode, and the dark mode setting in the settings panel remains off and must be manually turned back on (either via BTTV or Twitch).

**Comment by dclstn** [comment]
#4685 addresses this

**Comment by night** [comment]
fixed via dbe1dcb5bbf7760c2f4bb8635bf72f3047e3eb42
