### ISSUE TITLE
Add setting for timestamps (and also pls fix backup issues)

### ISSUE THREAD

**Issue by cvictajr** [night/betterttv#4690]
I'd hope the timestamps setting in chat could be added onto settings!
Then it would be great to have that saved in backup settings.

Also,

I noticed the Dark Mode setting isn't properly saving or loading in settings backup/imports.
That's the one I've noticed; I'm not sure what else might not be properly working anymore.

**Comment by night** [comment]
Timestamps are actually a Twitch feature, so it's not something we place in the backup. As for backups not working properly, that's likely due to using an old backup. The import system doesn't support them, but that is tracked in #4689
