### ISSUE TITLE
Hide Recommended Channels Removed?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/betterttv#4692]
So before the UI update, there was the option to Hide recommended channels.  I no longer see it.

There is still an open issue with the option, but not sure if could ever get fixed  https://github.com/night/betterttv/issues/4183

**Comment by Nareese** [comment]
The setting for this feature is now on the Directory Settings tab (second tab), under "Sidebar", and the wording has changed the logic around, it's the "Featured Channels" setting, which now has a description of "Show recommended channels in the sidebar", so the settings should be unchecked to hide those sections (that one setting covers multiple sidebar sections, "recommended", "popular", and "simliar").
