### ISSUE TITLE
Not Seeing any Sub/Gifter Bages across all channels (desktop)

### ISSUE THREAD

**Issue by RosannyDisla** [night/betterttv#4702]
I was watching twitch just fine today, however, after coming back a couple hours later, I noticed the chat was missing their sub and gifter badges. Their names were very spaced out and this was happening even after clicking on another channel. I checked my frankerfazez settings to check if there was an issue there but all the badges settings were visible. However, after trying to check my bttv settings, I couldn't even find the option in my twitch options. Bttv just disappeared from my options when clicking on my profile but its still connected on my twitch profile and still turned on on my chrome extensions. I tried switching my wifi, redownloading bttv, and logging back in to twitch but the problem remains. I attached screenshots of what my chat looks like and my twitch profile options. This issue is only on my macbook but NOT on my phone.
<img width="369" alt="Screen Shot 2021-07-27 at 9 10 43 PM" src="https://user-images.githubusercontent.com/88066145/127247574-c7946339-0467-41b2-82ea-42d1b65fdc59.png">

<img width="1433" alt="Screen Shot 2021-07-27 at 8 53 16 PM" src="https://user-images.githubusercontent.com/88066145/127247428-5ca6a8a0-9051-4b0f-b944-42c68b888330.png">
<img width="1436" alt="Screen Shot 2021-07-27 at 8 54 29 PM" src="https://user-images.githubusercontent.com/88066145/127247456-071a5247-e467-4700-a00f-5d670d68fabe.png">

**Comment by dclstn** [comment]
Can you open the console with `CTRL + SHIFT + I` and see if you're recieving an error?

**Comment by RosannyDisla** [comment]
> Can you open the console with `CTRL + SHIFT + I` and see if you're recieving an error?

I tried, but nothing happened. I dont know if it has to do with me having a macbook.

**Comment by night** [comment]
BetterTTV doesn't perform any mutation to badges. Since they are displaying the area where they should render, my guess would be that you are unable to retrieve the images from Twitch's content distribution network.
