### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by Spuner** [night/betterttv#4704]
Can you make the mini-player window in Picture in Picture mode inactive? It is impossible to play and watch at the same time, since when you move the sight in games, the player window is activated.

**Comment by night** [comment]
You can already disable this natively from the Advanced menu of the Twitch player.

**Comment by Spuner** [comment]
You don't understand the question. I do not want to disable picture-in-picture, I asked - is it possible in a picture-in-picture mode to make the mini player window is inactive, so that when you move the mouse in the game mini player window is not activated.

**Comment by night** [comment]
I'm not sure what you mean, but once you enable Picture in Picture you're operating within a browser feature (not BetterTTV's) so your limitations or to whatever your browser supports. Chrome and Firefox have quite different picture in picture implementations, for example.

**Comment by Spuner** [comment]
I can record a video so you can see what I'm talking about.
