### ISSUE TITLE
Auto reload/refresh player after stream error

### ISSUE THREAD

**Issue by J-91** [night/betterttv#4708]
would be a cool feature, thanks

**Comment by dclstn** [comment]
I find this very unlikely to be added as building features to work around bugs is just gonna introduce more bugs.

**Comment by J-91** [comment]
it's not a bug issue is it? I thought it would be similar to auto-claiming channel bonus points

**Comment by night** [comment]
Thanks for the suggestion. This does feel like a bug in Twitch's player, or perhaps something they are intentionally doing to thwart adblock users. Due to the latter, we are unfortunately not comfortable fixing this (as it may anger Twitch).
