### ISSUE TITLE
BetterTTV Settings no longer accessible

### ISSUE THREAD

**Issue by Px05119** [night/betterttv#4709]
Probably another Twitch update, but BetterTTV settings can no longer be accessed from either the chat settings cog nor the top right menu. BetterTTV functionality (such as emote menu and chat commands) does still exist. Issue is on Chrome latest (92.0.4515.107) with Win10, however it's also reported on Discord as occurring in Firefox v90 and Chromium 92.0.4515.70.

**Comment by dclstn** [comment]
Can you check the console, and see if you're recieving an error whilst reloading twitch.tv

`CTRL + SHIFT + I` to open the console in Chrome.

**Comment by Px05119** [comment]
Screencap of console, but I've always had that 404 error.. 
![image](https://user-images.githubusercontent.com/25652184/127591636-969fd48f-8fd6-4e2a-ad96-57ee05b657f2.png)

**Comment by night** [comment]
I am unable to reproduce this behavior. Without a way to reproduce this behavior it's gonna be near impossible to fix. If you're still having issues, try disabling other browser extensions to see if it'd caused by an incompatibility with a different extension.

**Comment by Px05119** [comment]
I think you should probably re-open this ticket before someone makes a new one. As I already had stated in my second message, ALL extensions were disabled (even ones that didn't touch Twitch) and I'm still having this issue. It also appears to becoming more widespread on Discord.

**Comment by Talkashie** [comment]
I'm having this issue now, as well. Makes the extension basically unusable. Using Firefox 90.0.2, other extensions disabled.

**Comment by dclstn** [comment]
A few follow-up questions:

- can you recall when you started facing this issue?
- do you remember what you changed before this started happening?
- and does removing `bttv_settings` in local storage seem to resolve your problem?

**Comment by Px05119** [comment]
> A few follow-up questions:
> 
> * can you recall when you started facing this issue?
> * do you remember what you changed before this started happening?
> * and does removing `bttv_settings` in local storage seem to resolve your problem?

I started having the issue at LEAST a week ago when I opened the Github issue, but after the new settings panel was implemented. I realized the issue when someone else posted it on the Nightdev discord server and I went to verify for myself as I'm usually thrown into website updates but I don't normally access the settings panel.
That said, I changed absolutely nothing other than the fact that I actually looked for the settings panel.
Removing 'bttvsettings' seemed to nothing.

**Comment by Talkashie** [comment]
> A few follow-up questions:
> 
>     * can you recall when you started facing this issue?
> 
>     * do you remember what you changed before this started happening?
> 
>     * and does removing `bttv_settings` in local storage seem to resolve your problem?

Started seeing this issue shortly after the blacklist and whitelist options were moved to the settings menu. Maybe around a week? I hadn't changed anything, to my knowledge. Not sure where to find bttv_settings. I've checked through my AppData folders (Local, LocalLow, Roaming) and see nothing related to BTTV

**Comment by derpyderpaderp** [comment]
Same issue with brave browser. It started today, worked last night 11pm central time. I have not added or changed anything.

**Comment by derpyderpaderp** [comment]
Another thing I noticed is the emote menu came back after enabling developer mode. Nothing else is there, bttv isn't even listed in the settings area.

**Comment by derpyderpaderp** [comment]
Also this is the errors in console. I am unsure of which ones pertain to bttv but I guess all of them woudn't hurt. [Imagee 1](https://i.imgur.com/5CngxMI.png) [Image 2](https://i.imgur.com/K8HIsju.png) [Image 3](https://i.imgur.com/9QfkZSH.png)

**Comment by AHauntedArmy** [comment]
so i'm having this issue as well, i'm using firefox 90.0.2 64bit with privacy badger, ublockorigin and noscript. this started happening for me after i cleared my cache, cookies and other related stuff through ccleaner. the settings menu re-appears after removing the extension, restarting the browser, and, re-installing the extension. after closing the browser by going to menu > exit, and reloading the browser, the settings menu is missing. i do also have firefox set to clear cookies at close so i have to re-sign in every time i load firefox.

hopefully this helps with reproducing the issue.

**Comment by Retro-Jack** [comment]
This is still a problem.
Steps to reproduce:

1. Start Brave browser
2. Start Twitch
3. Go to preferred channel
4. Click cog
5. No TwitchTTV settings
6. Click top right icon
7. No TwitchTTV settings

This topic really needs to be re-opened and addressed properly.

**Comment by night** [comment]
As stated in the original response, unless we have a way to reproduce the issue it cannot be fixed. Here's "proof" it works normally in brave browser on the latest extension version, 7.3.6.

https://user-images.githubusercontent.com/2942184/132133249-b4066da9-5e64-4b39-890c-dd2f9d9c18c6.mov
