### ISSUE TITLE
Window misplacement and dashboard popunder button

### ISSUE THREAD

**Issue by TsukiZero** [night/betterttv#4719]
First, the BTTV settings window is moved far too down, to the point the info/about button gets hidden.
second is that the fourth button in the settings window acts as a dashboard popunder.

**Comment by night** [comment]
x 4724

**Comment by night** [comment]
@dclstn can you look into this?

**Comment by night** [comment]
fixed via https://github.com/night/betterttv/commit/b07ece7cf3e717200c10ab9b15e1e42267452890
