### ISSUE TITLE
Save Keywords in backup file

### ISSUE THREAD

**Issue by BlackWhiteX** [night/BetterTTV#472]
I was wondering whether it would be possible to add Blacklist & Highlight Keywords and Scrollback Amount to the downloadable backup file. Since I find myself cleaning cookies often, I think it would be good having those custom values in the backup file as well...

**Comment by voloshink** [comment]
Those values are already saved in the backups

**Comment by BlackWhiteX** [comment]
Oh, that's weird, because it somehow doesn't work for me...

**Comment by voloshink** [comment]
can you check if your back up contains the blacklisted and highlighted words?

**Comment by BlackWhiteX** [comment]
I checked it, the file does actually contain the words. But somehow those settings are not applied when importing the file into BetterTTV...

**Comment by voloshink** [comment]
I just tested and both blacklisted and highlight words imported properly

**Comment by BlackWhiteX** [comment]
Ok, I'll try to reinstall the addon & clear cookies/cache again. Maybe that does the trick this time...
