### ISSUE TITLE
BTTV not appearing in Brave Browser on M1 Mac

### ISSUE THREAD

**Issue by DevelopWithJJ** [night/betterttv#4720]
Currently running Big Sur 11.4 on a MacBook Air. BTTV settings aren't appearing for some reason. They do appear when I'm using Chrome on Mac, and they also appear when I'm using Brave on my PC. [https://ibb.co/7CLLvfv](URL) <- Mac [https://ibb.co/sVvtPht](URL) <- Windows

**Comment by Px05119** [comment]
Good luck. Already made a ticket last week and it was closed with "I don't have this issue" https://github.com/night/betterttv/issues/4709

**Comment by gjwebber** [comment]
I am having the same issue today, but with Firefox. I installed the latest Firefox browser 90.0.2 (64-bit), the extension is installed, but I have no settings appearing in the chat menu.

Using the Javascript console I can interact with BetterTTV object, so something is in there, but again no menu is appearing.

**Comment by gjwebber** [comment]
Update: The emotes are working, as well as the name highlighting. It is just the menu which is not ever visible. @DevelopWithJJ can you confirm if it's the same for you?

**Comment by EmbitiousDev** [comment]
Likely linked to #4709, if you can't provide a step-by-step guide on how to reproduce the issue reliably it won't be fixed as the devs don't know where to look for. It's as if you were shown a perfect black cube and told: "there's an issue with it, fix it," and you have to guess what it is and find the solution while blindfolded in a dark room.

**Comment by DevelopWithJJ** [comment]
Hi @gjwebber!

How did you find the BTTV object in the console? I can see the BTTV-add-on with FFZ, but I'm not sure how to find the BTTV object. I can see the emotes as well. I don't think I have name highlight on, so I can't confirm if that setting is working for me.

**Comment by rudsonalonso** [comment]
I had the same problem in the edge browser, but I fixed it by clearing the cache from the beginning (Google Translate)

**Comment by night** [comment]
This is hopefully fixed by the latest version, 7.3.4.

**Comment by gjwebber** [comment]
> 
> 
> Hi @gjwebber!
> 
> How did you find the BTTV object in the console? I can see the BTTV-add-on with FFZ, but I'm not sure how to find the BTTV object. I can see the emotes as well. I don't think I have name highlight on, so I can't confirm if that setting is working for me.

At least in Firefox, I brought up the console by pressing ctrl + shift + K. On that command line I could type "BetterTTV" and interact that way. Wasn't helpful beyond seeing something was actually there. I think you have to be on Twitch for to be available.
