### ISSUE TITLE
Twitch Smiley Icon disappearance after August 6th Chrome extension update.

### ISSUE THREAD

**Issue by ManicGlitter** [night/betterttv#4724]
The emoji icon has disappeared from Twitch - this was noticed August 6th at 4am Central. I couldn't see the settings menu either. I tried restarting the browser to no avail. The extension's store page indicated there was an update dated August 6th. Store support page eventually led me here.

**Comment by night** [comment]
I am unable to reproduce this behavior. If you're still experiencing this issue please post the specific version you have installed.
