### ISSUE TITLE
Highlight Keywords (Adding multiple words)

### ISSUE THREAD

**Issue by KinqWolf** [night/betterttv#4741]
**Multiple words are not added. Instead of typing one by one, we want to write all the words on a single line.**

**Comment by night** [comment]
It's possible we can handle pasting many words separated by new lines, but it is unlikely we will change the ui to be a single line again as it's just not user friendly.

**Comment by night** [comment]
@dclstn can you look into this?

**Comment by dclstn** [comment]
#4765 adds functionality for this

**Comment by night** [comment]
fixed via https://github.com/night/betterttv/commit/2f1e66d0301225d18693e776969cc5c50a2ac892
