### ISSUE TITLE
TTV settings

### ISSUE THREAD

**Issue by Here1230** [night/betterttv#4742]
Keep login me out of twitch/ resetting my settings.

**Comment by Nareese** [comment]
Sounds like you have configured your browser to "Clear site data on close" (Chrome: Settings ->  Privacy and Security -> Cookies and other site data -> Clear cookies and site data when you close all windows, Firefox: Settings -> Privacy & Security -> Cookies and Site Data -> Delete cookies and site data when Firefox is closed), or you have some other third party browser "cleanup" extension that does the same thing.  BetterTTV (and Twitch, and many other sites) use cookies and local storage (site data) to store your login session and settings.  If your browser deletes those, then logout and lost settings will result.

**Comment by Alyetama** [comment]
> Sounds like you have configured your browser to "Clear site data on close" (Chrome: Settings -> Privacy and Security -> Cookies and other site data -> Clear cookies and site data when you close all windows, Firefox: Settings -> Privacy & Security -> Cookies and Site Data -> Delete cookies and site data when Firefox is closed), or you have some other third party browser "cleanup" extension that does the same thing. BetterTTV (and Twitch, and many other sites) use cookies and local storage (site data) to store your login session and settings. If your browser deletes those, then logout and lost settings will result.


I use "clear history when Firefox closes" by default, and I want to keep it this way. All my other installed extensions retain my settings, except for betterttv.

**Comment by night** [comment]
Thanks for the feedback, but BetterTTV currently maintains its codebase as a user script for cross-browser support. We do not currently support browser-specific storage layers for add-ons. We have some improvements down the road related to setting retention, but in the short term I don't see this changing anytime soon.
