### ISSUE TITLE
 Localized Usernames  Show localized display names in the chat window

### ISSUE THREAD

**Issue by MAACBS** [night/betterttv#4743]
Isnt working for me. The first or two options when I tab are nicknames and not emotes.

**Comment by Nareese** [comment]
Localized usernames is not the option you are looking for.  That option displays an "english" username when users have their display name configured to non-english characters.  The option to prioritize emotes over nicknames for tab completion is further down on the Chat Settings tab, "Tab Completion Emote Priority".  Turn that on, and emotes will come first when you tab.

**Comment by MAACBS** [comment]
Thank you. I really thought that I searched every option but it's clearly not
