### ISSUE TITLE
Hide bot icons

### ISSUE THREAD

**Issue by Mine-Modder** [night/betterttv#4745]
BetterTTV replaces the mod icon of some bots with a bot icon:

![screenshot](https://user-images.githubusercontent.com/83986705/129455734-5edcb4de-034e-4a5c-a06b-5a5d44e04c99.png)

I would like an option in the BetterTTV settings to disable this feature and display the usual mod icon (sword).

**Comment by xgerhard** [comment]
Why, isn't it usefull to know if an user is a bot? It will only add a bot icon for a few known bots, and if you have a custom bot in your channel you can add it here: https://betterttv.com/dashboard/bots
