### ISSUE TITLE
Logging into channel still not working

### ISSUE THREAD

**Issue by thezombiunicorn** [night/BetterTTV#475]
I cleared my cookies/cache and restarted my browser but it still doesnt work:

http://i.gyazo.com/ce4674c610389ef9dcec0b35a6e2a3a6.gif

**Comment by voloshink** [comment]
Do you get the same issue when accessing the website https://manage.betterttv.net ?

**Comment by thezombiunicorn** [comment]
Yes, same issue.

**Comment by night** [comment]
What happens on the website itself? Have you tried a different browser?

**Comment by night** [comment]
If you're still having issues, you can continue to reply to this issue.

**Comment by thezombiunicorn** [comment]
It does the same loading for a bit on the website then prompts me to log in
with twitch again. I cant get it to even install on firefox (which might be
antivirus software, but i have it disabled and it still wont install :?)

Best,

*Natalie Casanova*
Twitter: @TheZombiUnicorn <https://twitter.com/TheZombiUnicorn>
YouTube: TheZombiUnicorn <http://www.youtube.com/user/thezombiunicorn>
Twitch.tv: ZombiUnicorn <http://www.twitch.tv/zombiunicorn>
