### ISSUE TITLE
Export/backup function can't handle umlauts

### ISSUE THREAD

**Issue by jlntrt** [night/betterttv#4751]
Hey there,

in case you entered keywords that should highlighted in chat containing umlauts or other special characters, then backup/export your BTTV settings, the umlauts and special characters are saved as "�".

In my case I want to highlight the German word "fußball" (football). The exported json (.backup) file has the value "fu�ball". This is the case with German umlauts like ä, ü, ö as well.

Tested with version 7.3.5

**Comment by EmbitiousDev** [comment]
The file is probably saved with the encoding setting set to `ANSI` when it should be `UTF-8`.
While waiting for an update, you probably can manually fix the � and other mishaps, and re-save the file under `UTF-8` encoding.

**Comment by jlntrt** [comment]
Thanks @EmbitiousDev . I already fixed it manually and checked the encoding of the exported file too. Interestingly it is utf-8 encoded, when I open it with vscode.

**Comment by night** [comment]
@dclstn can you look into this?
