### ISSUE TITLE
Auto completion for emotes...

### ISSUE THREAD

**Issue by furkaneroi** [night/betterttv#4772]
There should be auto completion feature for emotes when you type a spesific keyword at the beginning so things dont get complicated when typing non-emote words. For example when i write *Pepe a small menu should popup which suggests emotes that start with Pepe.

**Comment by night** [comment]
We do have auto completion, but there is not a UI to accompany it at this time. You can type a few letters and press tab to complete the word. If the matched word is not correct, you can press tab again (or shift + tab to go back).
