### ISSUE TITLE
Hovering someone's name in chat should highlight their previous messages

### ISSUE THREAD

**Issue by maxpaj** [night/betterttv#4788]
Hovering someone's name in chat should highlight all their previous messages in chat. 

This should make it easier to see the history of what someone has been talking about if they haven't been using the thread-functionality in Twitch. With the current implementation, you'd have to scroll up and try to find their messages by looking at the names.

**Comment by night** [comment]
You can click on a user in chat to see their previous messages, which I think offers are more solid experience when trying to navigate fast moving chats
