### ISSUE TITLE
Meme version of existing emote being detected as duplicate

### ISSUE THREAD

**Issue by mschoenfisch** [night/betterttv#4790]
I made a meme version of [PAGGING](https://betterttv.com/emotes/609fa4e467644f1d67e8686c) called LAGGING that is basically PAGGING with a stuttered framerate and parts of the image loading in at different times but it's being detected as a duplicate. Is it possible to get around this? New version attached for comparison
![LAGGING](https://user-images.githubusercontent.com/45896281/132605922-250bfb92-09a8-426a-b0b1-757e9a629532.gif)

**Comment by night** [comment]
A hashing algorithm is ran on emotes to check for duplication. In some rare cases very similar emotes can be determined to be too similar. We unfortunately do not have a manual override mechanism at this time, and you may need to make your version more unique to work around it.
