### ISSUE TITLE
Host Button disappeared

### ISSUE THREAD

**Issue by gtbmusicislife** [night/betterttv#4791]
The host button disappeared on Microsoft Edge Version 93.0.961.44 (Official build) (64-bit) and Google Chrome Version 93.0.4577.63 (Official Build) (64-bit).  I cleared the cache on both browsers because sometimes it fixes the issue and it didn't

**Comment by night** [comment]
fixed via https://github.com/night/betterttv/commit/c48e36da4eec3bbaa675178b4d3678a875bc43e9
