### ISSUE TITLE
YouTube comments featuring emojis are "duplicated"

### ISSUE THREAD

**Issue by PrincessOzma** [night/betterttv#4792]
Since updating BetterTTV to include emote functionality on YouTube, I've found that existing YouTube comments somehow 'duplicate' themselves across videos if containing emojis. For example, if I click on a video, which contains a comment saying, "This is hilarious 😂" and then click (within the same tab) on a second video, which contains a comment saying, "That part at the end was great," it will instead read "This is hilarious 😂 That part at the end was great".

The comment seems to only duplicate itself to one comment on the second video, and the process will continue across videos, though it retains only the first comment. For example, if a third video contains a comment saying, "More videos like this please," it will read "This hilarious 😂 More videos like this please". The comment which it duplicates _to_ appears to be random, because returning to the same video will often result in the comment from the first video attaching to a different comment. 

I am currently using the most up-to-date version of Chrome (Version 93.0.4577.63 (Official Build) (64-bit)) on Windows 10.

**Comment by night** [comment]
Thanks for the report. I would assume YouTube is recycling DOM elements in some way to cause behavior like this. I'm not sure how we can quickly fix it, so in the meantime we will rollback support for YouTube comments.
