### ISSUE TITLE
Host or Unhost Buttons Fail To Display Any Longer... 

### ISSUE THREAD

**Issue by Euther** [night/betterttv#4794]
Hi there. I am running Version 7.4.0 and have the host button enabled. 
Do not see it on my twitch channel viewer. 
Also, when viewing my own channel, I do not see an unhost button.

I am running Google Chrome: Version 93.0.4577.63 (Official Build) (64-bit)

thx
Euther

**Comment by AlfaTelevision** [comment]
Hi in to Version 7.4.0 the host button enable do not see it on my twitch channel viewer
