### ISSUE TITLE
Host-Button missing

### ISSUE THREAD

**Issue by Janus2201** [night/betterttv#4796]
Yesterday the Host-Button was a the bottom right corner below the videoplayer.
Today the Host.Button is missing.

Disabeling the Host-Button feature in the BTTV settings, completely reloading Chrome and re-enabling the Host-Button featrue in the BTTV settings doesn´t solve the issue.
![Host button](https://user-images.githubusercontent.com/90571019/132997138-db5e7787-cdb7-41b1-b3b8-b075109d124e.jpg)

**Comment by night** [comment]
This is already fixed in v7.4.1 which is pending release.
