### ISSUE TITLE
Personal BTTV emotes not working since new patch

### ISSUE THREAD

**Issue by chriigu** [night/betterttv#4798]
Worked perfectly fine yesterday.

According to the BTTV emotes website my subscription is active and working perfectly fine. However in the emote menu on twitch the personal emote section is missing and typing one also doesn't show the emote. Channel and Global emotes are fine.

**Comment by dclstn** [comment]
Hot fix coming out shortly.

**Comment by night** [comment]
This is fixed in v7.4.1 and higher
