### ISSUE TITLE
Since the new update, personal BTTV emotes are not working

### ISSUE THREAD

**Issue by PoppySins** [night/betterttv#4799]
I have subbed to BTTV for ages, and I now have 21 personal bttv emotes I cannot use since the latest update. This feature is 99% of why I subscribe to this feature and I am looking for a fix so that I can use the emotes I am so used to having.

**Comment by dclstn** [comment]
dupe of #4798,

Sorry for the inconvenience

**Comment by night** [comment]
This is fixed in v7.4.1 and higher
