### ISSUE TITLE
YT comments are duplicated onto other videos.

### ISSUE THREAD

**Issue by Marijn1009** [night/betterttv#4802]
Hello,

After giving betterTTV permission to view and edit YT data, I been seeing duplicated comments. 
In the picture below, the comments with the fire icon are bugged. To the left of the fire is the original comment on a video I watched previously (and is no longer open). To the right of the fire is the new comment to the video I'm currently watching. 

Just throwing this issue out here.

![image](https://user-images.githubusercontent.com/81243086/133052062-5bc6ce5a-19c4-487b-988c-68a6095592ee.png)

**Comment by night** [comment]
We reverted comment support in v7.4.1 due to this issue already. Please upgrade to v7.4.1 or higher.
