### ISSUE TITLE
Youtube: Resizing breaks the emotes

### ISSUE THREAD

**Issue by Frozander** [night/betterttv#4812]
Issue:
- Join a Youtube Live Stream
- Emotes work
- Resize browser window until chatbox moves either under the stream or the side of the stream
- Emotes stop working
- Resizing back to the original size does not fix the issue

I suspect it is because Youtube changes the chat div, when screen size is changed, extension breaks.

Edit: The issue sometimes does not happen but it generally happens. So if it doesn't break the first time, doing it again breaks it.

**Comment by night** [comment]
This appears to be an issue with the extension's background logic. It will be fixed in the upcoming 7.4.2 release
