### ISSUE TITLE
Youtube: Scrollbar within chat message with emotes

### ISSUE THREAD

**Issue by robmonte** [night/betterttv#4814]
Sometimes, longer youtube chat lines that use BTTV emotes aren't having their chat size increased when the emote gets inserted, causing a scrollbar to appear inside the comment. See the screenshot below:

![image](https://user-images.githubusercontent.com/17119716/133132339-5147cf8a-de26-4412-afd1-d43313519dca.png)

This is a scrollbar on the chat line itself only, and not the overall chat scrollbar.

**Comment by night** [comment]
this is fixed via https://github.com/night/betterttv/commit/4b8e95eb7ed356427cf628a81859b0b31bbfcfa7
