### ISSUE TITLE
Strange bug where Youtube comments are replicated in other Youtube comments below different videos

### ISSUE THREAD

**Issue by BurningOakTree** [night/betterttv#4817]
<img width="308" alt="bttv1" src="https://user-images.githubusercontent.com/90655822/133163245-109623ef-cb48-44f9-bba9-c12e96c01e82.PNG">
<img width="472" alt="bttv2" src="https://user-images.githubusercontent.com/90655822/133163249-c431bb25-ed4f-49c8-a375-49b0f8391b28.PNG">

**Comment by Nareese** [comment]
This was a bug in 7.4.0, and the code to support emotes in comments (as opposed to live stream chat) was disabled in 7.4.1.  Make sure you update your extensions/addons if you don't have that version.

**Comment by BurningOakTree** [comment]
> This was a bug in 7.4.0, and the code to support emotes in comments (as opposed to live stream chat) was disabled in 7.4.1. Make sure you update your extensions/addons if you don't have that version.

Okay, thank you. I just updated
