### ISSUE TITLE
Errors on Google Chrome

### ISSUE THREAD

**Issue by kilroy98** [night/betterttv#4819]
Google Chrome: 93.0.4577.82 (Official build) (x64). BetterTTV: 7.4.2

When i join on main page in Twitch.tv i see this error for BetterTTV on ext.list. 
![wsf2WgWfw](https://user-images.githubusercontent.com/13346898/133219192-f32071da-86d5-409f-8e90-cf5feb8e4178.png)
After join on anyone channel, appear new errors.
![dgJkLOpd](https://user-images.githubusercontent.com/13346898/133219815-f81d9a15-6660-4922-bfd6-45aa7d5eaeba.png)
![d23IOknd](https://user-images.githubusercontent.com/13346898/133220578-81eb55b5-eec1-44b8-929f-5514652133bf.png)
![w28@jnlM](https://user-images.githubusercontent.com/13346898/133221308-768ecb4d-2c35-4f49-9225-5b0fe0d2e527.png)

Recent errors appear randomly

**Comment by night** [comment]
All these errors are Twitch site errors. They likely show in the extension errors list because Chrome is injecting our content script and is watching for errors on the page, but these are nothing to worry about.
