### ISSUE TITLE
Only 1 emote at a time

### ISSUE THREAD

**Issue by Doinkyou** [night/betterttv#4821]
idk if there is a setting to fix this but with the new update it only allows me to use 1 emote then it auto closes and makes me re-open the menu to select another emote. is this a bug or if there is a setting change let me know

**Comment by night** [comment]
If you hold shift, it will stay open

**Comment by Doinkyou** [comment]
> If you hold shift, it will stay open

Is there a way to perm fix it?

**Comment by night** [comment]
There is not a way to permanently pin it at this time.
