### ISSUE TITLE
Left side chat + new emote menu is a just about unusable combination

### ISSUE THREAD

**Issue by smol-fi** [night/betterttv#4823]
Version 7.4.3 on Chromium 92.0.4515.159

It simply extends outside the viewport of the window, sorry if picture does not adequately show that.

![https://files.catbox.moe/7dh9cx.png](https://files.catbox.moe/7dh9cx.png)

+ consider allowing letting us hide old BTTV emote menu button from settings, two is distracting/annoying

**Comment by night** [comment]
good catch on left side chat. this update is only rolled out to people using the user script. we will get this fixed before wide release.

there's always been two emote menu buttons, but one of them was twitch's. the old emote menu button showing is temporary, and we plan to remove it in a future update.
