### ISSUE TITLE
FF Min Version increase

### ISSUE THREAD

**Issue by Scrxtchy** [night/betterttv#4826]
v7.4.2 was released to AMO with a supported version of 42.0 or higher 
![image](https://user-images.githubusercontent.com/12771982/133382885-ab539c18-d3df-407d-a58b-4e7536ca6e19.png)

However, the extension logs an error when using browsers as old as 76
```
TypeError: chrome.permissions.onAdded is undefinedbackground.js:38:1
    <anonymous> moz-extension://71b3a698-dc5d-45d1-b934-cc52edf893c6/background.js:38
```

This is due to the permissions.onAdded API [was only added in Firefox 77](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/onAdded#browser_compatibility) (with Polyfill available for previous versions).
There has probably been a lack of this kind of _mininum supported version_ checks for the extension

However, the extension still functions mostly normally on firefox 76, you will just never get youtube support

**Comment by night** [comment]
this will be fixed in the next release
