### ISSUE TITLE
Option to video seek using the Mousewheel Up/Down

### ISSUE THREAD

**Issue by K24A3** [night/betterttv#4827]
I have multiple monitors running twitch and other things such as work and games.
I have a Chrome extension in Youtube (Youtube(TM) Mouse Controls) where I can simply move the mouse to the monitor playing youtube and use the mouse wheel to seek the video forward and back 5 seconds.

I have not found an extension for twitch that does the same thing, so I'm having to click and pause the twitch video to get focus, then un-pause it, and then reach out to the keyboard and press the arrow keys to seek... and at the same time the other app I was using on the other monitor has lost focus so I have to click that app to gain focus again. It's something that takes me 1 second to do in youtube, but 5-10 seconds in twitch.

It would be fantastic if I could simply use the mouse wheel Up/Down to seek the video when the mouse is hovering over the twitch video area, and scroll down the page when the mouse is hovering outside of the main video area .

**Comment by MartijnWelker** [comment]
It would have to be combined with some modifier key or it will conflict with [scroll volume control](https://github.com/night/betterttv/blob/master/src/modules/video_player/index.js#L60). How about `ctrl+scroll`?

**Comment by MartijnWelker** [comment]
`ctrl+scroll` already controls browser zoom so I opted for using `alt+scroll`
