### ISSUE TITLE
BTTV Emote menu

### ISSUE THREAD

**Issue by felixS45** [night/betterttv#4828]
Hello,

is it possible to reanable/add the option for old version of the "more advanced emote menu"?

I like to use the default twitch emote menu and use the "old advanced" menu to pick BTTV ans FFZ emotes. The new version, as i can tell, replaces the default one. Or maybe give an option to have the default twitch menu and the new advanced at the same time.

Thanks in advance!

Best Regards 
FelixS45

**Comment by night** [comment]
We are not going to be reverting to the old version as it was built by a third party that stopped maintaining it. The new emote menu is something we build and maintain. We understand that it's new and would appreciate constructive feedback and suggestions to make sure it's the best it can be.

**Comment by felixS45** [comment]
Thanks for the answer! 

I basically would like access the default twitch emote menue and some other menu for BTTV emotes and FFZ emotes. So by giving the option to have both at the same time would fix it for me. Making the "new" emote menu button appear there where the "old" one used to be would be my suggestion. 
My only issue with the new one was that it replaced the default one. 
For the short amount of time i used the new one i really liked it compared to the old one, it loaded faster and was more responsive. And it doesnt cover up the entire chat while using it.

Thanks for working on these extensions and the response!

Best Rsegards 
FelixS45

**Comment by aidanw** [comment]
I too would like access to the default twitch emote menu available alongside the bttv one (as it was before). 

The new menu is more sluggish than the default, and hides my subs emotes below the bttv ones.

**Comment by i-Punch** [comment]
The default twitch channel emotes should always be the first thing in the menu imo. 

The new menu is much slower, does not put the channel emotes at the top, does not show you channel emotes if not unlocked and closes after every click (I know we can hold shift but it's not intuitive.)

PLEASE move the button back where it was and give us access to the normal twitch menu, it would solve most issues.

I love BTTV as a whole, but this menu is not there yet.
