### ISSUE TITLE
Twitch emote menu only shows unlocked channel emotes

### ISSUE THREAD

**Issue by pandavolta** [night/betterttv#4831]
Many people choose to sub/resub to channels (or sub at higher tier) based on emotes available. Currently if the BTTV "more advanced emote menu" is turned on, the menu only shows _unlocked_ emotes for the channel you're viewing. The advanced menu has to be turned off in BTTV settings to see locked emotes.

**Comment by night** [comment]
Thanks for the feedback. This was definitely an oversight that we'll get ironed out.

**Comment by night** [comment]
This issue is resolved as of a few updates ago.
