### ISSUE TITLE
@betterttv error modo emotes

### ISSUE THREAD

**Issue by cristiantouro** [night/betterttv#4832]
Pls you can leave the previous version of emotes mode. The new version apart from being bug is super difficult to find the emotes

**Comment by night** [comment]
We are not going to be reverting to the old version as it was built by a third party that stopped maintaining it. The new emote menu is something we build and maintain. We understand that it's new and would appreciate constructive feedback to make sure it's the best it can be.

**Comment by cristiantouro** [comment]
A system could be made to block the menu like the previous one to be able
to put several icons without closing the menu

**Comment by cristiantouro** [comment]
A system could be made to block the menu like the previous one to be able to put several icons without closing the menu

**Comment by cristiantouro** [comment]
In the previous menu there was a padlock to block and that the icon menu will not close
