### ISSUE TITLE
bttv emote menu

### ISSUE THREAD

**Issue by zhestyk** [night/betterttv#4833]
Hello!
With the emote menu update and moving to another location, there is no way to fix and stretch the menu as you want.

How can I return to the old version of the emote menu or return to the old version of better ttv? Maybe there will be an update with the choice of the old or new interface?

**Comment by night** [comment]
We are not going to be reverting to the old version as it was built by a third party that stopped maintaining it. The new emote menu is something we build and maintain. We understand that it's new and would appreciate constructive feedback to make sure it's the best it can be.
