### ISSUE TITLE
New emote menu category priority feature

### ISSUE THREAD

**Issue by TyllerAllen** [night/betterttv#4834]
I would like to be able to click and drag the different emote categories to be above/below each other in my preferred priority.
Some channels have lots of BTTV and FFZ emotes that you have to scroll past to get to the current channel's sub emotes, which should take priority imo.

PS. Could we get a 'feature' label under issues since both 'Report Bugs' and 'Submit Ideas' buttons lead to this page.

**Comment by night** [comment]
We added emote menu category sorting to a recent update of BetterTTV. You can now drag emote menu categories on the left sidebar to custom sort your categories.
