### ISSUE TITLE
Emote menu closing after selecting one emote (2)

### ISSUE THREAD

**Issue by GraidenLOL** [night/betterttv#4836]
I've searched all the options, maybe not too well. I would like to pin the emote menu as it's now joined with the BTTV now. This was also addressed in #3689 - https://github.com/night/BetterTTV/issues/3689. Thank you!

**Comment by dighawaii** [comment]
I select multiple emotes quite often. This behavior is exceptionally frustrating.

**Comment by night** [comment]
Thanks for the feedback. We removed the "pin" capability, but you are able to press `Shift` when selecting an emote for the menu to remain open.

**Comment by GraidenLOL** [comment]
> Thanks for the feedback. We removed the "pin" capability, but you are able to press `Shift` when selecting an emote for the menu to remain open.

Thanks, that's awesome! I knew I should've read better.

**Comment by adaliddelretraso** [comment]
same problem, dis is so weird

**Comment by night** [comment]
We've documented this behavior in the footer of the new emote menu, which should help people discover the new behavior.
