### ISSUE TITLE
Mobile gesture menu.

### ISSUE THREAD

**Issue by kintrex** [night/betterttv#4838]
Hello!
I would like the gesture menu to return that could be moved, enlarged and reduced to suit the person. Also on that menu were all the compact emotes.
Now when I want to open this menu, it comes out: ”This button has moved! Click the other :) button in the chat box to access BetterTTV's emote menu.”.
The truth is that that menu was the best there was for people who used emotes frequently because you always placed it in a place that did not bother you and it was useful when using emojis and being able to see the chat without being covered by the menu.

Thanks for reading it, and I would like you to implement this menu again. ;)

**Comment by night** [comment]
In the latest version of the extension, 7.4.5, we have restored access to the native Twitch emote menu.
