### ISSUE TITLE
Moderator mode bugged

### ISSUE THREAD

**Issue by Hjarta86** [night/betterttv#4839]
Looks like in the normal mode of Twitch the emote icons are correct, but when I switch to the moderator view the Twitch emote icon is "overwritten" by the BTTV one and I can't see the normal emote view anymore.....this happened on Chrome and Opera

Nomal mode with all icons
![normal mode](https://user-images.githubusercontent.com/90899142/133753678-f7b3853f-b374-4506-a2de-252a74af7699.png)

Moderator mode missing icons below
![moderator mode](https://user-images.githubusercontent.com/90899142/133753681-59f6b0c3-9f97-4ea2-9278-2f470dbbf386.png)

![Screenshot_13](https://user-images.githubusercontent.com/90899142/133754298-4721bf6d-f749-4d8a-9ad6-9d7155f62ad5.png)
)

**Comment by dclstn** [comment]
fixed via #4844
