### ISSUE TITLE
Emote Menu has dark font on dark background when using Twitch's light theme.

### ISSUE THREAD

**Issue by Codelefant** [night/betterttv#4841]
![grafik](https://user-images.githubusercontent.com/11066012/133798174-696a227e-769e-4edc-aa69-15b91c2a0b92.png)
As shown in the screenshot, the new emote menu uses a dark font when Twitch is set to light mode. This makes the text hard to read.
I also tried refreshing the cache, unsuccessfully.

I would expect the font color to be dependent on the emote menu's theme rather than the Twitch theme.

Thanks and have a nice day!

**Comment by DewArmy** [comment]
It would be great if it would switch from light/dark theme with the rest of twitch.

**Comment by night** [comment]
This issue is already fixed in the current release, 7.4.5
