### ISSUE TITLE
Black text on dark emote menu when using Light Theme

### ISSUE THREAD

**Issue by GabeIggy** [night/betterttv#4848]
The new emote menu is great, but it renders poorly on if you use light theme.

![image](https://user-images.githubusercontent.com/5295686/133868957-ec9ef71f-2c2e-4346-ad33-9d782264a8f6.png)

A quick solution is to use white backgrounds on the emote menu whenever light mode is active. (since characters are already black colored)

**Comment by night** [comment]
This is fixed as of version 7.4.5
