### ISSUE TITLE
Quick Whispers

### ISSUE THREAD

**Issue by CravingGaming** [night/BetterTTV#485]
Something similar to hotkeys for banning someone, but click their name and press "w" and it auto types /w <username> in the chat box?

**Comment by night** [comment]
#486 adds a whisper moderator card hotkey, adds /r to reply, and fixes some spotted issues with tab completion

**Comment by CravingGaming** [comment]
How exactly does the "/r for reply" work? Also, I was hoping the whisper hotkey wasn't specifically for mods...

**Comment by voloshink** [comment]
once you recieve a whisper you can just start typing "/r " and it will fill out the whisper for you and let you put in a message. The W hotkey is not mod only, just the name of the setting because the other binds are mod only.

**Comment by CravingGaming** [comment]
Oh that's nice, but I can't use the W hotkey when I'm not mod...

**Comment by voloshink** [comment]
It works for me, even when im not a mod in a room

**Comment by CravingGaming** [comment]
Alright it's working now... thanks! :D

**Comment by voloshink** [comment]
Awesome
