### ISSUE TITLE
Emote menu missing in mod view

### ISSUE THREAD

**Issue by gigili** [night/betterttv#4853]
BTTV: `7.4.5`
Google Chrome: ` 93.0.4577.82 (Official Build) (64-bit)`
OS: `Windows 10 Pro 21H1`

For the past few days I noticed that there is no emote menu icon  next to the chat button when inside of moderation view on Twitch. There is only the regular twitch emote menu button which does not have the BTTV emotes in it. 

When on a regular twitch channel page (non mod view) I get the emote menu icon next to the chat button with new UI.

This is how it looks when in mod view:
![bttv-mod-view-no-emotes](https://user-images.githubusercontent.com/2153382/133922818-a7cf393d-c93d-4738-a6e5-7a860e52279b.png)

This is how it looks when not in the mod view
![bttv-non-mod-view-emotes](https://user-images.githubusercontent.com/2153382/133922820-7938dc6a-226e-4928-839b-7dc94dc6ae10.png)

Here are bttv settings:
![bttv-emote-settings](https://user-images.githubusercontent.com/2153382/133922900-0fcc9fc1-e80c-47b0-8667-16e0cef4862c.png)
![bttv-emote-settings-about](https://user-images.githubusercontent.com/2153382/133922901-c25d604a-7dc7-43ed-af20-654264ffca8d.png)

**Comment by dclstn** [comment]
Fixed as of 7.4.6

**Comment by gigili** [comment]
How long those it usually take for updates to become available on the extension store?

Noticed the new release was made 7 hours ago, but the chrome extension store doesn't have it yet.

**Comment by dclstn** [comment]
It'll take atleast a day for the extension to be approved, in the meantime you can install the latest build with our [userscript](https://nightdev.com/betterttv/other/betterttv.user.js) using a userscript manager.

Apologies for the inconvenience!

**Comment by gigili** [comment]
All good, no need to apologize. You're all doing an amazing job and we appreciate all that you do. :)
