### ISSUE TITLE
Separate emotes menu not functioning.

### ISSUE THREAD

**Issue by kpcenti** [night/betterttv#4866]
Pressing the Smile Icon next to the setting cog tells me "This button has moved! Click the other :) button in the chat box to access BetterTTV's emote menu.". Pressing the Smile icon by the bits icon gives me the BetterTTV emotes menu. I'm on Version 7.4.7. 
According to [this](https://community.nightdev.com/t/betterttv-overriding-twitch-emote-menu/31265/3) & [this](https://community.nightdev.com/t/please-give-us-an-option-to-use-the-old-emote-menu/31258/13) 7.4.5 is suppose to have the menus separated.

**Comment by night** [comment]
You are not on 7.4.7 if you are seeing that text. You can check your actual version from the BetterTTV Settings -> About tab. The changelog screen shows all changelogs we've published.

**Comment by kpcenti** [comment]
I definitely was on 7.4.7, the only reason I found that was because I checked the change log in the setting. I even copy pasted the Version and it's number in t he initial post. It must have been bugged until I restarted my browser a few times, since it works now.. thanks i guess
