### ISSUE TITLE
Restoring lost function to the emote menu

### ISSUE THREAD

**Issue by jh4c** [night/betterttv#4869]
In the old emote menu, we had the ability to favourite emotes and hide unwanted emotes, which helped to both streamline the use of the menu and to avoid unwanted imagery in our chat feeds. (I personally would be happy to never see any version of pepe again.)

We also had a channel's own BTTV emotes in a separate block from the general ones, whereas now they are all mixed together which makes finding anything an ongoing challenge as you move from channel to channel.

Could either or both of these functions be reinstated?

**Comment by night** [comment]
> we had the ability to favourite emotes

This behavior still exists. You can Alt + Click emotes to add/remove from favorites. We also track frequently and recently used emotes, and the next update will further improve that functionality.

> hide unwanted emotes

Hiding individual emotes is not something we wanted to carry forward into the current iteration. We may introduce the ability to hide a category though, which feels more useful.

> We also had a channel's own BTTV emotes in a separate block from the general ones, whereas now they are all mixed together which makes finding anything an ongoing challenge as you move from channel to channel.

This change is already WIP. See #4846
