### ISSUE TITLE
Ability to move the modal around

### ISSUE THREAD

**Issue by codicoscepticos** [night/betterttv#4870]
Not being able to drag around the modal, is a difficult experience, because when you open it, it covers the chat. Would like to both having it open all the time, and still be able to see the chat (and for that, of course, would require the ability to move the modal around).

**Comment by night** [comment]
Since the emote menu is now only open when it is being used, it doesn't make sense to allow it to be dragged any longer. You are able to temporarily keep the emote menu open to select multiple emotes by holding shift.
