### ISSUE TITLE
Emote Menu is hidden ?

### ISSUE THREAD

**Issue by Jotapegs** [night/betterttv#4871]
My Menu Emote is hidden and i dont know why.... sure i have some pluggins but when i tried using BTTV in incognito it didnt solve my problem. (most of my puggins are not enabled in incognito). Someone know what its causing this ?

Video: https://gfycat.com/CluelessSelfassuredKentrosaurus

**Comment by Jotapegs** [comment]
My extension list and others

![chrome_cWGAr9OpuY](https://user-images.githubusercontent.com/20832004/134389559-ebcd05e5-9ef9-4d14-8dfb-c14074f8e4fd.png)
![chrome_JyP0ZUSRr1](https://user-images.githubusercontent.com/20832004/134389569-715456b3-feeb-47c4-a40d-a5e70a5b8961.png)
![chrome_lq6oNxtPzU](https://user-images.githubusercontent.com/20832004/1343
![chrome_65YvtzArnY](https://user-images.githubusercontent.com/20832004/134390112-7a35ce99-33f3-44e9-b476-930f800283a1.png)
89575-15027aa0-5e63-48f7-a2d4-d6f57dcf4820.png)
![chrome_Mxikn4lb6J](https://user-images.githubusercontent.com/20832
![chrome_wk0qy2Bgf9](https://user-images.githubusercontent.com/20832004/134390106-19b40317-f8c7-48d0-95ad-b1eeb05d3131.png)
![chrome_PbAx9JRJoO](https://user-images.githubusercontent.com/20832004/134390109-b77b0378-3890-4ce5-a475-3acc424686f7.png)
004/134389758-81dd4c8b-2e69-4b95-a8bc-f8db04d09bb1.png)
![chrome_NwWkMh4GX8](https://user-images.githubusercontent.com/20832004/134390119-50dc94c9-b4c3-4f97-b804-5a43c697b675.png)

![chrome_LN6Okt8oWi](https://user-images.githubusercontent.com/20832004/134390101-ae9e7068-d776-4ebf-9ee0-5cecc1914a5f.png)
![chrome_IfiBZKV2eX](https://user-images.githubusercontent.com/20832004/134390127-08194928-e49a-422f-8d3a-318fc77ab261.png)

**Comment by Punkichu** [comment]
> My Menu Emote is hidden and i dont know why.... sure i have some pluggins but when i tried using BTTV in incognito it didnt solve my problem. (most of my puggins are not enabled in incognito). Someone know what its causing this ?
> 
> Video: https://gfycat.com/CluelessSelfassuredKentrosaurus

was having same problem in all channels but my own, i have to open the bttv settings TURN OFF EMOTE MENU and turn it back ON again,  but i have to constantly do this over and over, it will disappear if i refresh or randomly  but this is my current fix

**Comment by night** [comment]
this is fixed in the 7.4.7 and higher releases

**Comment by Jotapegs** [comment]
![chrome_gFBpEYOhze](https://user-images.githubusercontent.com/20832004/134547172-d018b0a2-687e-47d0-8d91-22be39d20683.png)

**Comment by night** [comment]
If you are not seeing the emote menu and are on the 7.4.7 release, you may have accidentally disabled it in the settings. Make sure you turn on the "Emote Menu" setting in the BetterTTV settings.

**Comment by Jotapegs** [comment]
u r right ... its fixed. ty.
