### ISSUE TITLE
Another key or custom key for Emotes autocomplete

### ISSUE THREAD

**Issue by jaylay99** [night/betterttv#4872]
TAB is great for autocomplete emotes but the issue is that it also autocomplete usernames, it'd be great if we could have a key for username and one for emotes so I never accidentally autocomplete a username over an emote.

**Comment by night** [comment]
We've extended BetterTTV usernames and emotes to sentinel-based autocomplete. You are now able to use `@` or `:` to locate only users and only emotes, respectively.
