### ISSUE TITLE
Vertical Scrollbar Visible in chat.

### ISSUE THREAD

**Issue by cyraid** [night/betterttv#4875]
Hi there, I'm not sure if this is a Twitch thing, but on a recent update to chrome, the vertical scrollbar is now visible.
![image](https://user-images.githubusercontent.com/7562753/134617099-ff80be8c-06ff-4a51-9a8d-265ac02f8252.png)

If you scroll it just moves the "Send a message" placeholder just a tad bit.

**Comment by marcusronnback** [comment]
Yeah this is probably not related to BTTV since it does not dissapear when you disable the addon. But I have the same issue 🙃
