### ISSUE TITLE
Ability to resize the new Emote menu

### ISSUE THREAD

**Issue by AlexWayfer** [night/betterttv#4891]
Hello.

Nice new menu. But I'd like to see a bigger selection on my QuadHD monitor.

It can be via cursor, like with the old one, or maybe via number settings (in pixels).

I tried to change it via custom stylesheets, but content is JS-dynamic, so it's not too helpful.

**Comment by night** [comment]
Thanks for the suggestion, but for performance reasons we removed the ability to resize the emote menu. In the current version we changed the behavior to dynamically render only emotes in view. This improved performance of the emote menu dramatically on most machines.
