### ISSUE TITLE
Personal emotes not being displayed through BTTV extension

### ISSUE THREAD

**Issue by Luzifer** [night/betterttv#4892]
### Observed behavior

Emote name is shown in a fresh browser installation with fresh BTTV extension installation while fresh FFZ installation with BTTV Emotes Addong does show the emote.

### Expected behavior

Personal emotes are shown in both cases.

### Version information

- BTTV Version: 7.4.9
- FFZ Version 4.29.2 / BTTV Emotes Addon Version 3.2.8
- Chrome Version: Version 94.0.4606.54 (Official Build) beta (64-bit)

### Observations about the websocket:

The observations were made with clean profiles for both installations.

#### BTTV
(Using `wss://sockets.betterttv.net/ws`)
```diff
> {"name":"join_channel","data":{"name":"twitch:485884564"}}
> {"name":"broadcast_me","data":{"provider":"twitch","providerId":"485884564","channel":"twitch:485884564"}}
```
These are the only messages transmitted through the socket, socket is still connected.

#### FFZ
(Using `wss://sockets.betterttv.net/ws`)
```diff
> {"name":"join_channel","data":{"name":"tezrian"}}
> {"name":"broadcast_me","data":{"name":"tezrian","channel":"tezrian"}}
< {"name":"lookup_user","data":{"name":"luziferus","channel":"tezrian","pro":true,"subscribed":false,"emotes":[...],"glow":false}}
```

Notice the `join_channel` and `broadcast_me` are sent in a different format and the incoming message, when my user `luziferus` sends a BTTV personal emote in a message, is missing when using the BTTV extension.

**Comment by night** [comment]
The behavior you see on BetterTTV is correct, but it's possible there was a service issue when you opened this issue. If you're still having issues, let us know.
