### ISSUE TITLE
Light theme in theatre mode

### ISSUE THREAD

**Issue by ReFruity** [night/BetterTTV#491]
Dark theme hurts my eyes. In addition, some emoticons are displayed with an ugly white outline.

**Comment by night** [comment]
I mean, isn't the point of a theater to be dark? If you just want a larger video player, you can achieve nearly the same effect by closing the left sidebar.

Because Twitch natively makes it dark, we do the same.

**Comment by ReFruity** [comment]
No, it's not the same. Look at all the margins that make the video look so much smaller. Actually I wanted to write a tampermonkey script to fix it a while ago, but then the theater mode came. Now it becomes annoying again.

Eh, whatever I'll write it myself after exams.
