### ISSUE TITLE
Set Highlight Keywords freezes broadcast.

### ISSUE THREAD

**Issue by undeadgraduate** [night/betterttv#494]
When I go to add or remove highlighted words, after a few seconds the stream I am watching starts buffering. It only stops it after I start typing and it reloads the stream when I close it. I'm not sure if this is unavoidable by how the highlight list is updated but it does it at all qualities.

Also I hope this wasn't a duplicate, I didn't see anything open or closed about this issue.

**Comment by night** [comment]
This isn't something we can fix at the moment. We would have to not use standard popup inputs to fix the issue, since those are the fault. This will eventually be handled when the settings system is upgraded, but there's not an ETA at this time.

**Comment by matt-tingen** [comment]
A workaround for this is to popout the chat and adjust settings from there. That way the `prompt` occurs in a separate window from the stream.

**Comment by night** [comment]
This should be fixed as of our settings menu redesign.
