### ISSUE TITLE
Slower streams/afk chats

### ISSUE THREAD

**Issue by tobyadog** [night/BetterTTV#495]
An idea for slower chats, or ones that you afk in. Perhaps you could play a small sound every time a message is sent. It would be useful in offline streams where your away from chat, not directly looking at it. I know there already is a sound feature in beta, but it only works when someone says a highlighted word. If what I ask is possible it would help a lot since most people don't constantly monitor chat during slower streams, or when your away in an offline chat. -Thanks!

**Comment by night** [comment]
I mean, a notification for every message sent definitely sounds annoying. You can play sounds when being highlighted already, which makes more sense. You can add keywords like "hello" or "hi" to probably get notified when people say hello.

**Comment by tobyadog** [comment]
Ok no probs! thanks for the reply
