### ISSUE TITLE
Change individual emoticons

### ISSUE THREAD

**Issue by BlackQuests** [night/BetterTTV#496]
Sometimes there're emoticons that I like better in the original twitch chat, although it is a minor thing I still hate the monkey (sorry). Example of a emote that I would like to change to the original twitch emote is the ":P" emote. When I turn off Bttv emotes it will still display the monkey version (bug maybe). Just a little idea which you can skip if you want.

**Comment by night** [comment]
There is already an option to disable the JTV monkey emoticons...
