### ISSUE TITLE
Suggestion (BTTV website): add 'copy as markdown' button 

### ISSUE THREAD

**Issue by mrsideshowjack** [night/betterttv#4979]
# Suggestion:
Add a copy as markdown button so I can more easily annoy my colleagues with BTTV gifs in pull requests

## Implementation
Example of `.btn-outline-secondary`:
![Screenshot 2021-11-01 at 5 32 06 pm](https://user-images.githubusercontent.com/9937136/139714453-fdced0cc-5a2f-4a2d-bf6b-fcd4dd698a34.png)

Would add `![popCat](https://cdn.betterttv.net/emote/614d129eb63cc97ee6d30157/3x)` to the clipboard, with the header text as the alt text

![](https://cdn.betterttv.net/emote/57ba587cd5219dd112c160a6/3x)

**Comment by night** [comment]
Thanks for the feedback. Usage of emotes in markdown isn't a supported use case for us at this time, but I imagine if we did want to support this we'd have better support in the form of our browser extension.
