### ISSUE TITLE
Mention button missing in user GUI

### ISSUE THREAD

**Issue by makedir** [night/betterttv#4982]
Please add a mention button in the GUI when you click on a user to easily and quickly access @username via mouse click.
![image](https://user-images.githubusercontent.com/6721083/140057971-4c206af3-63c0-44c0-a63d-101bb4999eb0.png)

**Comment by night** [comment]
We tend to prefer less UI clutter. In this case autocompletion is your friend. You should be able to type `@` in the text box to see a list of relevant users (and the user should be near the top). You can also type a few characters and press enter or tab to select them.

**Comment by makedir** [comment]
Adding a button is NOT CLUTTER. It is LOGIC AND MAKES SENSE. To add a button at that place. There is even empty space, not used space. Adding a single button wouldnt hurt it would just add usage quality.

Then give an option to hide that button by default.
