### ISSUE TITLE
Add a respons button to highlighted mentions

### ISSUE THREAD

**Issue by makedir** [night/betterttv#4984]
Please add a @response button to highlithed messes on the top.

**Comment by night** [comment]
We tend to prefer less UI clutter. In this case autocompletion is your friend. You should be able to type `@` in the text box to see a list of relevant users (and the user should be near the top). You can also type a few characters and press enter or tab to select them.

**Comment by makedir** [comment]
Stop being ignorant please. This is NOT CLUTTER. This is a simple little feature which would make the entire experience 1000x times better. There is no way to simply and quickly answer someone who wrote to you and you see the highlight.

Please dont be the typical ignorant developer. I tend to be that too so I know what that means.

Typing with @ is not an option with thousands of people in a chanel or 10 of thousands.

The highlight mechanism is a clean easy way to quickly anwers, by clicking on it.
