### ISSUE TITLE
Replace Keywords feature

### ISSUE THREAD

**Issue by wnbaum** [night/betterttv#4986]
Like the Blacklist Keywords feature in the Chat Settings section, I think it would be useful to have a Replace Keywords feature. This would find text keywords in messages and replace it with whatever the user wants. This could replace unwanted messages with something else, or replace an emote with another that you prefer.

**Comment by night** [comment]
Thanks for the feedback. This doesn't sound like something we would likely implement, as mutating text input is unreliable.
