### ISSUE TITLE
Highlighted Streamers Frontpage

### ISSUE THREAD

**Issue by zhg271hgld** [night/betterttv#4987]
hi all!

please give us an option to blackbox or completely disable the highlighted streamers on the top of the frontpage. not recommended ones further below. just the highlights. there is stop autoplay, but that only does half the trick.

once the paid-option arrives to highlight streams it becomes inevitable anyway to have such a function i guess.

https://ibb.co/j3SVB4K

i usually jump on the frontpage to get a grip on what's going on atm on twitch. recommended channels etc.

but the wild mix of featured streamers, that i actually never ever click on, is a bit annoying.

if it's recommendations based on my likings: it's really bad. if it's not, it has no justification to be there for me.

thank you!

(tried to grey out the streamers and their names - not shitting on anyone in particular)

**Comment by night** [comment]
As Twitch uses these for promotions we are not willing to hide them from view (we will not block ads due to past legal concerns)
