### ISSUE TITLE
No comma after autocompletion

### ISSUE THREAD

**Issue by Sandoz1** [night/BetterTTV#499]
I absolutely love Better TTV but the only thing that throws me off is the comma after I use tab for autocompletion. Normally I use tab + type first few letters and then I select the right name. Now I can't do that anymore. I have to type the first few letters first, then hit tab and then it autocompletes for me. Worst thing is that it places a comma after the username "@peter, " instead of "@peter". Can this be changed please? Or at least give us an option for it.

**Comment by night** [comment]
The comma placement enforces proper grammar usage when addressing someone as the first word of a sentence, which is why this automatic comma placement exists. When you tab complete names in other parts of the sentence, we do not place commas.
