### ISSUE TITLE
Request customizable video stats overlay

### ISSUE THREAD

**Issue by jewshawn2** [night/betterttv#4999]
At some point twitch had a transparent "video stats" box.  Can you make the box transparent instead of a solid background?  Also customize what is displayed.  For example I just want to see the following stats so it takes less space in the upper left corner:

FPS | 29
Skipped Frames | 42
Buffer Size | 2.61 sec.
Latency To Broadcaster | 3.06 sec.
Latency Mode | Low Latency
Playback Bitrate |  2059 Kbps

Or maybe better if bttv can overlay it's own video stats box over the player.  This is a useful feature when watching IRL streamers where viewers can fall behind (over 10-20s Latency To Broadcaster) due to the streamer dropping frames.  Twitch calls themselves the leader in live streaming yet doesn't have a red live button feature like youtube.  Thanks for all the work done for bttv.

![bttv](https://user-images.githubusercontent.com/12043078/141495708-2ae4eb5a-4904-4627-98dd-9ce85c101409.JPG)

**Comment by night** [comment]
Thanks for the feedback. This sounds like something that may be too unique to your situation and is not likely something many users would find helpful. I'd recommend exploring extensions like Stylebot to add your own customizations to the Twitch site.
