### ISSUE TITLE
[Submit Idea] Enable auto hide chat

### ISSUE THREAD

**Issue by Baltimora** [night/betterttv#5001]
Add checkbox for Enable auto hide chat.

![image](https://user-images.githubusercontent.com/29725694/141613101-4b888220-3ec7-44f6-8a59-76d8f9d15cdd.png)

![image](https://user-images.githubusercontent.com/29725694/141613198-e84d32b0-86a9-4b02-94f7-24cb26651173.png)

**Comment by night** [comment]
You can automatically hide chat by clicking the collapse sidebar button.
