### ISSUE TITLE
Different fonts for other languages

### ISSUE THREAD

**Issue by ahmafi** [night/betterttv#5003]
Can we have an option to set different font settings for other languages, for example Arabic and Persian are shown very bad with the default font, the text is so small and unreadable. Most of Persian community are using English letters right now because of this problem.
I can probably help on this myself if there is a plan for adding this feature.

**Comment by night** [comment]
Thanks for the feedback. This use case may be a bit too specific to your needs and that is not something we generally add to BetterTTV. It may be a better idea to find or create a font which looks correct on your desired languages and set that as your font.
