### ISSUE TITLE
Volume Gain above 100%

### ISSUE THREAD

**Issue by Joecascio2000** [night/betterttv#5022]
I've noticed some streamers have their mic volumes too low and the twitch stream is very quite. The solution is to max out my local volume but then if I play a Youtube video or something else and it's so loud.

Long request, short, similar to Enhancer for Youtube extension, it would be awesome if their was a volume boost / volume gain option/toggle for each stream.

**Comment by night** [comment]
Thanks for the feedback. There are already numerous browser extensions which do this for all of your tabs. It might be a better idea to pick those extensions up rather than us adding this specifically for Twitch. We tend to try and focus on Twitch-specific enhancements.
