### ISSUE TITLE
[Feature suggestion] Sound notification for whenever streamer changes category

### ISSUE THREAD

**Issue by skylimitua** [night/betterttv#5024]
-Streamer is playing a boring game
-I don't pay attention/mute the stream because of forsenbajs voice chat cancer
-Streamer stops playing game, starts plaing different game
-I am Clueless because stream is muted
-Streamer changes category on twitch because different game
-ding
-I am now aware and watching the stream
-PogChamp

**Comment by night** [comment]
Thanks for reaching out. Due to modern browser limitations we are not able to play sounds from tabs which are not already playing sound, as browsers require sounds be associated with user actions. Due to these limitations we wouldn't be able to build a good, consistent experience.
