### ISSUE TITLE
[Suggestion] Scrolling chat, nicovideo style?

### ISSUE THREAD

**Issue by Aku-dono** [night/BetterTTV#503]
I just started using this extension and already I love it. Good job :+1: 

I wanted to ask if it was possible to add scrolling text as part of Twitch's full screen mode, so I could see what the chat is saying without closing full screen. Not sure how doable that is, though, considering Flash Player's limitations... 

Good work, anyway.

**Comment by night** [comment]
Use Theater mode instead if you want chat side-by-side with video
