### ISSUE TITLE
BetterTTV extension doesn't show up in Firefox Toolbar

### ISSUE THREAD

**Issue by CubzCreator** [night/betterttv#5037]

**Comment by Nareese** [comment]
This is normal. There is no need for the extension to put a button on the toolbar, as the extension itself has no settings or options.  If it does show up (for example in Chrome), and you click on it, it just shows a message that the button doesn't do anything and you can feel free to hide it.  All of the configuration of the extension is managed from the BetterTTV Settings menu entry on the chat "gear" menu or on your profile menu under your profile picture in the upper right.
