### ISSUE TITLE
A setting that automatically sets the resolution of streams to source quality

### ISSUE THREAD

**Issue by 32423d** [night/betterttv#5044]
Could you please add a setting that automatically sets the resolution of streams to source quality. This is already accomplished with the script referred to as "Enhance twitch" (https://greasyfork.org/en/scripts/375467-enhance-twitch) on greasyfork.com but adding this feature to betterttv minimizes the need to install extra scripts to use this feature.

**Comment by night** [comment]
After reviewing Twitch functionality again it appears Twitch automatically sets the resolution to source if you've manually set it once. If you are not seeing this behavior, you may need to configure your browser to remember cookies on close.
