### ISSUE TITLE
[Suggestion] adding emotes to comment sections on youtube videos

### ISSUE THREAD

**Issue by Hupetlive** [night/betterttv#5057]

**Comment by Nareese** [comment]
Emotes in Youtube comments was a part of the initial release of Youtube support, but it was found to be bugged in a way that seriously broke comments in general (see this issue/comment https://github.com/night/betterttv/issues/4792#issuecomment-917673179).  night was not able to see a way to easily fix it, so emotes in comments were removed at that time.  I assume they are something he would like to add back in some day, but no ETA.
