### ISSUE TITLE
Bug The invisible chain points

### ISSUE THREAD

**Issue by gorkaliam** [night/betterttv#5062]
It's been a while since I noticed that the channel points are no longer visible on Twitch, but by using another browser or simply by disabling BetterTTV they reappear
![Screenshot_1](https://user-images.githubusercontent.com/53339962/144756487-36d38c9b-7c3d-4a37-9c0d-6b376e80e216.png)
![Screenshot_2](https://user-images.githubusercontent.com/53339962/144756489-d72c5192-ff4b-43b5-97d1-f767fe359f60.png)

**Comment by Nareese** [comment]
Check your settings.  Chat Settings -> Channel Points -> Channel Points (Show channel points in the chat window), make sure that setting is checked.  If it is unchecked, then channel points will be hidden as you show.

**Comment by gorkaliam** [comment]
Thanks you !!! Perfects 🥇
