### ISSUE TITLE
Causes Error #2000 as of 12/6/21

### ISSUE THREAD

**Issue by eM-Krow** [night/betterttv#5068]

**Comment by barnumbirr** [comment]
Confirmed on my end (Firefox 94/95). Disabling BTTV extension makes `Error #2000` nearly disappear.

**Comment by night** [comment]
Twitch will not clarify when or how this error occurs, but the most likely cause of error 2000 is use of an adblocking extension. BetterTTV does not block ads nor does it prevent playback of ads in the Twitch player.

**Comment by barnumbirr** [comment]
> Twitch will not clarify when or how this error occurs, but the most likely cause of error 2000 is use of an adblocking extension. BetterTTV does not block ads nor does it prevent playback of ads in the Twitch player.

As much as I understand Twitch's stand making this neatly impossible to debug, I don't think adblocking extensions are the culprits here: I don't use any of those extensions and simply disabling the BTTV extension and reloading the page fixes the issue.

**Comment by eM-Krow** [comment]
Oh I just noticed this was BetterTTV, I thought I was on the TTVLOL github, my bad. BetterTTV does not cause this issue, and it's a TTVLOL issue. However the issue has resolved itself.
