### ISSUE TITLE
BTTV on Opera GX Browser

### ISSUE THREAD

**Issue by TinyQuacks** [night/betterttv#5071]
Hi! I got the Opera GX browser and added the BTTV extension but I have a problem, I can see the BTTV settings in the chat but when I enable the "Emote Menu" I don't get the smiley face next to my chat. I have the latest update and I can still see the BTTV emotes in chat. 
I removed every extensions I had on the Opera GX and removed the BTTV extension completely, then I added only the BTTV back but that didn't work, and I've tried reinstalling Opera Gx.
It works fine on my Chrome. 

Update: My boyfriend just got BTTV on his Opera GX and it works just fine for him but it's still not working for me.

**Comment by night** [comment]
Opera GX is just Chrome, so it isn't possible for it to work on Chrome but not Opera GX when installed on both. You may want to check and see if there is a "BetterTTV Settings" button showing in the chat settings, and that you are logged in on Twitch.
