### ISSUE TITLE
BetterTTV Anon Chat Not Working Properly

### ISSUE THREAD

**Issue by likuanza** [night/betterttv#5072]
**Joining chat anonymously without appearing in the userlist has been always available, however recently it shows user name in the chat list and the feature does not serve the purpose of itself.** 

**To describe the issue in more details;**
-When user joins a channel, "logging you out of chat....welcome to the chat room" statement pops up. Shortly after, user name still appears in the chat list.
-Although user appears in the user chat list, user unable to send message.
-Turning Anon Chat off, then back on, seems to resolve this, with the user becoming invisible again shortly after. All the correct messages from BTTV are displayed in chat (logging in/out)
-When user browsing through other channels; in the very first channel -> user invisible, all other channels -> user visible.
-If user closes the tab or browser, user name is still visible in the chat list. (this might be irrelevant because it takes a bit time to dissapper on the chat list even the feature is off)

**Info-->**
_Opera GX Version LVL 3 (core: 82.0.4227.25)
BetterTTV Version 7.4.15 • Dec 7, 2021
Reference case number #2402, #3639_

**Comment by night** [comment]
I am not able to reproduce any issues. You are likely seeing lag time between being in the member list and not being in the member list. Twitch does not update the memberlist in realtime (it can be delayed up to 5 minutes).
