### ISSUE TITLE
"Click To Play"- Option Doesn't Work When The Stream Has A Twitch Extension

### ISSUE THREAD

**Issue by StargamerXD** [night/betterttv#5109]
As said in the title, when the stream has a Twitch extension added, the "Click To Play" - option to pause/resume the stream doesn't work right. It only works when clicking on the black bars of the player. I am not sure if it only happens on some extensions, not all.

**Comment by Nareese** [comment]
Pretty sure this can't easily be fixed.  When extensions are active, the Twitch player puts an overlay across (most of?) the entire surface of the player that eats mouse events and does not pass them through if they don't hit an extension.  For now, and probably forever, you will have to choose between click to play and disabling Twitch player extensions.  Reference: https://github.com/night/betterttv/issues/4375#issuecomment-799033363
