### ISSUE TITLE
(feature request) Stop auto scrolling

### ISSUE THREAD

**Issue by partytown** [night/BetterTTV#511]
sometimes its very annoying when im trying to read a long message thats a bit up in the chat but when a new message comes up in chat it automaticly scrolls down to the bottem message which makes it impossible almost to read a message that you missed in a busy chat

**Comment by DTittel** [comment]
Last I checked if you click after scrolling up it pauses the autoscroll

**Comment by partytown** [comment]
wow i didnt know that was a feature... thanks for the help xD
