### ISSUE TITLE
BetterTTV not keeping chat when removed by mod

### ISSUE THREAD

**Issue by Linerider99** [night/betterttv#5121]
iv double checked to make sure BTTV is active

**Comment by Nareese** [comment]
I am unable to reproduce this.  I tested with Deleted Messages set to Show, and watched a channel until I observed both a deleted message, and a time out, and both messages remained, greyed, in chat.  The messages are probably being deleted by some other extension, or some other extension is interfering with BetterTTV's ability to prevent them from being deleted.  Disable all other extensions, especially other Twitch modifying extensions, and test again.
