### ISSUE TITLE
[Feature Request] Disable/Ignore PMs while chroma key is active

### ISSUE THREAD

**Issue by Wizzard-of-light** [night/BetterTTV#513]
With the new twitch PM feature a lot trolls abuse this feature to send undeleteable messages over the PM system. As a broadcaster I don't want spam to be on stream seemingly unmoderated. I don't want to turn off the PMs completely either, as there are a lot things people want to tell me...
Would it be possible to implement a feature to turn off the display of PMs while a chroma key is active?

**Comment by teak** [comment]
I recommend setting "Block whispers from people you don't follow" in your Twitch settings. If you dont want to do that.. Our [OBS Chat](https://nightdev.com/obschat/) service does not receive whispers and is really a better solution for on screen chat...
