### ISSUE TITLE
Animated emotes have colors broken in Opera GX

### ISSUE THREAD

**Issue by NotDave410** [night/betterttv#5131]
Chrome extension is natively added to Opera GX.

When displaying animated chat emotes, the emote will be a white silhouette of the animation instead of proper colorings. Tried it in a quarantined instance of the browser with no other extensions active, still just displays as above. Chat badges also appear to be broken, with white elements in the badge showing as black (or potentially as transparent textures showing the background I can't tell)

Thanks.

**Comment by NotDave410** [comment]
Actually only effects color emotes, black/white emotes are fine even when animated.

**Comment by notjank** [comment]
I am having the same issues, here's a pic 
![Screenshot 2022-01-17 010236](https://user-images.githubusercontent.com/97873040/149723128-4fb85faf-5348-4336-89d3-a15d32f636e4.png)

**Comment by notjank** [comment]
Here's one more example
![image_2022-01-17_011632](https://user-images.githubusercontent.com/97873040/149724307-ed1466aa-41b1-4746-b974-66d02af0ab3a.png)

**Comment by NotDave410** [comment]
NotJanks examples are exactly what mine looks like.

**Comment by NotDave410** [comment]
![bug](https://user-images.githubusercontent.com/97726521/149879956-8824226e-1406-448f-8328-b027990c4f8e.PNG)

Peep the Drakes, pepelaugh and those mizkif emotes at the bottom to see what I am talking about.

**Comment by dclstn** [comment]
Hi, this seems to be a problem with how Opera GX is forcing dark-mode. Can you try right-clicking the site you're on and disabling force dark page, I hope this helps!

**Comment by NotDave410** [comment]
Force dark pages has been disabled the whole time. Toggling it on and off, no diff between the two w/regard to chat.

**Comment by dclstn** [comment]
> Force dark pages has been disabled the whole time. Toggling it on and off, no diff between the two w/regard to chat.

Can you navigate to opera://settings/content/forceDarkMode and ensure twitch is not listed beneath enabled, and if not does disabling the extension fix the colour invertion?

**Comment by NotDave410** [comment]
That did it! It wasn't listed under enabled, but I manually put twitch under the disable section and that did it.

**Comment by notjank** [comment]
apparently it was forcing dark mode on my end, tysm
