### ISSUE TITLE
Wrong highlighted nickname

### ISSUE THREAD

**Issue by scrashnebula** [night/betterttv#5140]
Only in obs studio chat (with betterttv on) i see highlighted message if people tag my previous twitch nickname and that doesn't happen with my new nickname
Old Nick : scrashtv
New Nick: ScrashNebula
![2](https://user-images.githubusercontent.com/97913455/149826878-5b7e2903-76f1-4636-a013-e0de0f396e14.JPG)

**Comment by dclstn** [comment]
Hello, you can fix this by opening the BetterTTV settings menu and navgiating to "Highlight Keywords", and updating your username, hope this helps!

![image](https://user-images.githubusercontent.com/43322006/149827555-baebb666-a919-49af-9883-6e0fd0d028ca.png)
