### ISSUE TITLE
A feature that updates emote appearance based on holiday

### ISSUE THREAD

**Issue by Jckpt** [night/betterttv#5142]
Every year streamers and editors have to change those holiday emotes back and forth which is a tedious and time-consuming task that could be automated.

It would’ve been cool if there was an opt-in feature for updating the emote appearance based on holidays like Christmas or Halloween, from date X to date Y. I can think of 2 ways of implementing this:

1. Emote appearance updates itself on a specific day
2. Emote changes to another author on a specific day

The first approach would require some extra work to do from the emote creator and this would also lead to potentially 3x bigger required storage per emote.

The second approach would credit the creator of the Christmas/Halloween version of the emote and wouldn’t cause unnecessary duplicates. The second approach also creates a subproblem, who will be choosing holiday emotes?

- The creator of emote - this would probably cause less diversity, but the streamer/editor wouldn’t lose that much time choosing all of the versions of the emote. Also if the emote creator selected holiday emotes that you don’t like you would be forced to opt-out of this feature.
- Streamer/editor - this would require more time to set up from the streamer/editor but you only need to do this once.

Probably the best way of doing this is combining both of these approaches, setting chosen holiday emotes by the creator of the original emote as default and giving an option to streamer/editor to change them.

**Comment by night** [comment]
Thanks for the feedback. I think this would be better solved by having the system proposed by #4899, which makes it easier for broadcasters and editors to manage more than just the emotes live on their channel.
