### ISSUE TITLE
Some BTTV options suddenly not working in VODs

### ISSUE THREAD

**Issue by ashamefuldog** [night/betterttv#5143]
...for me, at least. I'm using the Chrome extension, and split chat, play sound when a message is highlighted, and pin highlighted messages to the top of chat were working fine for me yesterday, but suddenly aren't anymore, at least not in VODs (which is where I do most of my twitch-viewing). 
 
Split chat, at least, still seems to work in _live_ chats, haven't had a chance to confirm if the others do, or whether or not other features stopped working in VODs. Wondering if anyone else has this issue. Tried clearing my cache just to see, didn't seem to work.

**Comment by brett1337** [comment]
no emotes are working for me in VODs, my guess is an extension interaction. I have 7TV, TTV LOL and Twitch Adblock

**Comment by night** [comment]
These have been broken for a while, but thanks for reporting.
