### ISSUE TITLE
[easy][website] Add 'Userscripts' app to suggested script engines for Safari

### ISSUE THREAD

**Issue by gorup** [night/betterttv#5152]
Repro:
- go to https://betterttv.com using the Safari browser (i'm using Safari 15.2 on Montery macOS 12.1)
- click Download for Safari
- See `Safari users need to install TamperMonkey`

Suggestion
- Change `Safari users need to install TamperMonkey` to `Safari users need to install TamperMonkey or Userscripts`

The app store URL to use is https://apps.apple.com/us/app/userscripts/id1463298887

Userscripts is open source & **FREE**!

 Also it works, I just installed userscripts, then clicked the install link that brings you to the bttv userscript ([this](https://nightdev.com/betterttv/other/betterttv.user.js)), then I clicked the userscript plugin icon on my browser, which then had something like 'install this script?' or whatever.

If you want me to provide screenshots/detailed guides, I can, but I think adding Userscripts to that list would be a good start!

**Comment by night** [comment]
thanks for the heads up. we've swapped over the recommendation to Userscripts.
