### ISSUE TITLE
Wrong colors in BTTV settings

### ISSUE THREAD

**Issue by CoolCmd** [night/betterttv#5153]
Version 7.4.17 (Firefox) has wrong colors in setting if light theme is active. 7.4.15 is OK.

On site:
![site](https://user-images.githubusercontent.com/684851/151517579-2a5895ea-f3b4-4faf-be30-922ac99c60f5.png)

In IFRAME the situation is even worse:
![iframe](https://user-images.githubusercontent.com/684851/151517758-07cf0009-8b2b-42e8-8230-f3f96a7f7801.png)

**Comment by pkdev08** [comment]
Is there a way to add a toggle switch to have an option to use the dark or light menu? I use the light twitch theme but actually prefer the dark mode on the menu's.
