### ISSUE TITLE
Emote visuals cannot be loaded

### ISSUE THREAD

**Issue by ahmtsytplt** [night/betterttv#5174]
After updating to Windows 11, some emotes started to crash. It's not only bttv emotes, also emojis like :yawning_face: gets crashed.

OS: Windows 11
Browser: Chrome ver: 97.0.4692.99 (64 bit)

Console log:

GET https://twemoji.maxcdn.com/v/13.1.0/svg/1f3ac.svg net::ERR_NAME_NOT_RESOLVED
Image (async)
value @ betterttv.js:formatted:49042
value @ betterttv.js:formatted:49078
(anonymous) @ betterttv.js:formatted:48942
_ @ betterttv.js:formatted:66493
a.emit @ betterttv.js:formatted:19483
(anonymous) @ betterttv.js:formatted:71736
_ @ betterttv.js:formatted:66493
a.emit @ betterttv.js:formatted:19478
O @ betterttv.js:formatted:65173
S @ betterttv.js:formatted:65205
(anonymous) @ betterttv.js:formatted:65271

GET https://static.twitchcdn.net/config/manifest.json?v=1 net::ERR_NAME_NOT_RESOLVED
(anonymous) @ betterttv.js:formatted:68312
(anonymous) @ core-fb140f0a7e5d2c175bc2.js:1
(anonymous) @ vendor-a6dc8516e513bafae90a.js:1
(anonymous) @ vendor-a6dc8516e513bafae90a.js:1
(anonymous) @ vendor-a6dc8516e513bafae90a.js:1
l @ vendor-a6dc8516e513bafae90a.js:1
e.getManifest @ core-fb140f0a7e5d2c175bc2.js:1
(anonymous) @ core-fb140f0a7e5d2c175bc2.js:1
(anonymous) @ vendor-a6dc8516e513bafae90a.js:1
(anonymous) @ vendor-a6dc8516e513bafae90a.js:1
(anonymous) @ vendor-a6dc8516e513bafae90a.js:1
l @ vendor-a6dc8516e513bafae90a.js:1
checkForUpdates @ core-fb140f0a7e5d2c175bc2.js:1
r @ betterttv.js:formatted:68967

Visual: 
_Updated image_
![Screenshot 2022-01-30 164051](https://user-images.githubusercontent.com/16436187/151705135-5c2cf6b6-6f39-4f07-8723-4e26a1ecbb2e.png)

**Comment by night** [comment]
If the name is not resolving, then it sounds like your DNS is having woes. Have you tried swapping to Cloudflare or Google DNS?
