### ISSUE TITLE
Idea: Add toggle to disable context menu

### ISSUE THREAD

**Issue by HBIDamian** [night/betterttv#5178]
So it's easier to use betterttv, I suggest adding a toggle so users can disable context menu. 
This would be easier in order for moderators to use betterttv's moderation features, such as `<div id="bttv-custom-timeout-contain">`. Otherwise, this would happen, which makes moderation slower.
![image](https://user-images.githubusercontent.com/10010369/152052736-f9d5c425-9c09-4ffe-a6c1-670e46334a22.png)

Through playing around in DevTools, I've found that something like this works nicely. 
```js
var chatbox = document.querySelectorAll(".stream-chat");
chatbox.forEach(el => el.addEventListener('contextmenu', event => event.preventDefault()));
```

**Comment by night** [comment]
We already do prevent the context menu when right clicking on usernames to open the custom timeout selector. If you have reliable steps to reproduce a context menu, please provide them. A video may be helpful as well.
