### ISSUE TITLE
Missing channel points view on Firefox 96.0.3 (64-bit)

### ISSUE THREAD

**Issue by Crusader2010** [night/betterttv#5179]
Hi,

I'm currently having an issue with channel points not showing up. Here are a few pictures i've taken:
[BTTV settings](https://ibb.co/z67vqtQ)
[Channel chat](https://ibb.co/ysf6b4g)

What I tried:
- deactivating and reactivating BTTV settings with hard refresh afterwards (CTRL+F5)
- force closed and reopened firefox
- cleared cache and cookies
- restarted computer

Then only moment when they seem to be showing properly is when I'm logged out of twitch. The moment I log back in, they disappear. I can see predictions just fine (when they pop up), but not the channel points.

**Comment by night** [comment]
Are you talking about bits? you are screenshotting the chat input, and channel points live below it.

**Comment by Crusader2010** [comment]
Your comment made me look for it further, and it seems that the points don't show up when the browser window is maximized. If I resize it, I can see that row below the chat textbox. Curiously, this wasn't happening before. One of the last firefox updates probably changed something, since I wasn't having this issue last week. 

Any ideas regarding this? Could it be related to BTTV or should I contact firefox/twitch about it?

**Comment by night** [comment]
our update did not change styles related to channel points, only styles of our UI. if you disable all browser extensions does it show up then?

**Comment by Crusader2010** [comment]
I've disabled everything, including ad blockers, and doesn't change anything.

**Comment by night** [comment]
If that's the case then it may be a Twitch bug I'm afraid.. and that's not something we can really help you out with. As a last effort you might try resetting page zoom (ctrl + 0)

**Comment by Crusader2010** [comment]
I understand. Thanks for your time and sorry this wasn't actually BTTV related. (Resetting the zoom didn't work either)
