### ISSUE TITLE
Twitch Giveaways not working together with BTTV

### ISSUE THREAD

**Issue by Altentio** [night/BetterTTV#520]
http://www.twitch.tv/bensam123/v/6685820
The time on past broadcast is around 2h 10min - 2h 15min. 
I don't know which application he's using but I guess it's called Twitch Giveaways. 
The user has to turn off the BTTV for Twitch Giveaways to work. Don't know if it's a problem with your end or theirs. I will report to both developers.

**Comment by night** [comment]
You're welcome to refer to the recent discussion at https://github.com/darsain/twitch-giveaways/issues/7#issuecomment-113806905

We haven't changed anything that would break the add-on, and the add-on recently broke due to its author changing its DOM listening method.
