### ISSUE TITLE
settings TODO for emote menu override version mismatch

### ISSUE THREAD

**Issue by Nareese** [night/betterttv#5200]
With the somewhat unplanned 7.4.20 update to account for the impending kraken deprecation, the temporary hard coded override to enable the emote menu that checks version !== '7.4.19' is now force enabling the menu again.  Issue first reported on the forum [here](https://community.nightdev.com/t/emote-menu-setting-keeps-defaulting-to-on-after-every-refresh/32182).

**Comment by night** [comment]
fixed by 7b0919c5acaa66682265106250b5a8ec50b2a24a
