### ISSUE TITLE
Feature Req: Nickname Users

### ISSUE THREAD

**Issue by KensonPlayz** [night/betterttv#5206]
It would be a really cool feature to add for us streamers (and viewers) to have a nickname that shows instead of their username. That way you could put in a viewers in-game name so you can more easily remember them! Even if it was a BTTV Pro feature, I'd sub just for that.

**Comment by SerenityDevelopment** [comment]
I would sub for just that feature alone myself. This is a cool idea and I think it would really work out well especially for streamers that meet a lot of their viewers in-game and need a way to remember who they are.

**Comment by Nareese** [comment]
BetterTTV already has this feature, and has had it for as long as I can remember.  Click on the user's name to open their mod card.  Click on the pencil icon beside their name.  Enter nickname.

**Comment by KensonPlayz** [comment]
It isn't very easily noticeable then. If there was a tooltip that said it was for nicknaming, that'd be nice.
