### ISSUE TITLE
BTTV Pro button not working when clicking on the page

### ISSUE THREAD

**Issue by eBridgette** [night/betterttv#5211]
Hello! I want to subscribe to BTTV Pro, but when I go to Dashboard > BetterBTTV Pro , and click on the, "Subscribe for $4.99/Month," button, it doesn't do anything but I also do not have a pro account so I don't already have it. Just wondering if this is broken. I'm using Chrome browser on a Windows 10 PC. Thank you for your time.

**Comment by night** [comment]
I'm curious if you have Adblock or other extensions installed which may be preventing us from loading the payment window. Have you tried incognito mode or a different browser?

**Comment by eBridgette** [comment]
Ah good idea! So I tried disabling my Ad Blocker on Chrome and no luck, but it worked right away on Firefox and got it rolling. Thank you so much!!
