### ISSUE TITLE
Whitelist TwitchTheater.tv from "chat disabled when obscured" feature

### ISSUE THREAD

**Issue by metalj** [night/betterttv#5214]
Hello there everyone! I am the developer/owner of TwitchTheater.tv. It was brought to my attention that a BetterTTV feature implemented not long ago is causing issues for some streamers that use my website as part of their streams. At first I thought this was a new security feature implemented by Twitch, but was surprised to see the console log pointing to the BetterTTV extension. Can my website be excluded/whitelisted from this feature? Thanks for being such an awesome part of the community for more than a decade!

**Comment by night** [comment]
You may have been misinformed. BetterTTV does nothing of the sort.
