### ISSUE TITLE
"Click To Play" problem

### ISSUE THREAD

**Issue by DaniKris19** [night/betterttv#5215]
Sometimes "Click to Play" works and sometimes it doesn't. When I click the Twitch player it pauses, but sometimes it had a little buffering, then the video continues playing. Another problem is when the player actually pauses, changing tabs would make it play again.

**P.s.** I have "Video Ad-Block, for Twitch" installed directly from the Chrome web store. And my BetterTTV setting is Player Extensions and Prime Promotions off.

**Comment by night** [comment]
If there are Twitch Extensions laid over the player, then it prevents the click feature from working. You may need to turn off the Twitch Extensions in the BetterTTV settings.
