### ISSUE TITLE
Colon button no longer allowing BTTV emotes to show up

### ISSUE THREAD

**Issue by Xanfer** [night/betterttv#5217]
For a long time using BTTV, when i would want to type in an emote accessed from BTTV starting with (:) it would show both regular emojis and BTTV emotes. however, when my browser needed to be hard reset, i lost this setting and have no way of re-enabling the feature.

**Comment by night** [comment]
This feature is not something BetterTTV provided, so likely some other extension you had/have installed managed this. It is something we may add in the future, though.
