### ISSUE TITLE
Feature request: put unsent messages back in text box

### ISSUE THREAD

**Issue by flarn2006** [night/BetterTTV#522]
I hate when I send a long message and it says that it failed to send for some reason, like that I was banned for a couple minutes or that I sent it too early and slow mode is active. Especially if there was only like 1 second left on either timer, in which case I wonder why it doesn't just wait that second and send it. I think whenever you send a message, BTTV should remember that message, and then if it gets a response that it didn't send right after, it should put that message back in the text box so you just need to press Enter to try sending it again. That way I won't need to scroll up, select the message and copy it.

**Comment by DTittel** [comment]
Did you try pressing the up arrow when in the chat box?

**Comment by flarn2006** [comment]
No I did not; thanks! Is that added by BTTV or is that always on Twitch?

**Comment by EhsanKia** [comment]
Default twitch uses up arrow to reply to the most recent whisper, history with up arrow is a BTTV feature.
