### ISSUE TITLE
Idea: Allow viewers to see total emote count(s)

### ISSUE THREAD

**Issue by TheGnare** [night/betterttv#5226]
As a viewer who has a lot of subscriptions to Twitch streamers (and out of mostly morbid curiosity), it would be neat to be able to see a total count of available emotes - perhaps even separated into "Twitch Emotes" and "BTTV Emotes"?  Just a small number at the bottom of the emote menu would probably suffice :)  

It would also be neat to have a ## (perhaps in parentheses) in the section/heading for a given streamer as you scroll through the emote menu, denoting how many emotes you have for that streamer.

**Comment by night** [comment]
Thanks for the feedback. This is not something I think would be super valuable, as emotes are not a vanity metric but rather a list of assets you can utilize.
