### ISSUE TITLE
Tab completion doesn't work for emotes AND usernames at the same time - its either/or

### ISSUE THREAD

**Issue by Heggyyy** [night/betterttv#5228]
It used to be so that you can both complete usernames and emotes at the same time with that, being able to prioritize one or the other coming first. Seems to not work.

I can either enable Emote prio and start typing KEK and press Tab for example, but let's say I want to tag a person with a username KEK-something-something. It wouldn't do that. It would just complete emotes and nothing else, even when pressing Tab. 

Tab should either prioritize emotes or usernames, depending on what you choose and from there on go forward.
Example: You prioritize emotes.
Typing KEK and pressing tab would cycle through emotes, but when these have all cycled through, it goes onto usernames. That way both can be completed with a tab. I can't do that for some reason.

**Comment by AnyMEmdq** [comment]
For me this feature NEVER worked as intended. whether I have it on or off, it only autocompletes emotes, no matter what I do, and it has caused me to uninstall the extension twice, as it is a pain in the ass as a mod to have to cycle through tons of emotes to find the person I want to address my message to. I am able to cycle through the emotes, though (again, having it off, atm), but never get a username

**Comment by night** [comment]
Thanks for the report. I am unable to reproduce any issues with tab completion locally. It seems to cycle through known users and then emotes by default, and with the tab completion priority setting the inverse (emotes and then users).

Please note that only known users are able to be tab completed. Known users are those which has spoken in chat while you have been in chat.
