### ISSUE TITLE
Rechat Integration and Theater mode on VODs

### ISSUE THREAD

**Issue by ajack38** [night/BetterTTV#523]
Both of these combined would allow for watchers of VODs to be immersed in the VOD, as well as being able to keep an eye on chat.

**Comment by night** [comment]
Does ReChat not work with BetterTTV already?

**Comment by ajack38** [comment]
In regards to highlighting users or words, and even blacklisting words, no.

**Comment by night** [comment]
Unfortunately we'd have to build an entire chat completely for video pages and add in a dependency for ReChat, and that's far too much work for little reward (very few people watch VoDs, and Twitch is primarily live streams).
