### ISSUE TITLE
Option to keep emote menu open after selection

### ISSUE THREAD

**Issue by krytton** [night/betterttv#5230]
I find it a bit cumbersome to hold shift whenever I want the emote menu to stay open, but there isn't any other option to stop it from closing. I found two other issues about this [here](https://github.com/night/betterttv/issues/3844) and [here](https://github.com/night/betterttv/issues/3689), and in both cases it was pointed out that there is a pin in the bottom right of the menu, but I don't see anything. Can this option be reintroduced? Maybe in the settings menu? It's the only thing that's stopping me from using the BTTV emotes menu.

**Comment by night** [comment]
We have no current plans to offer a permanent emote menu on the page any longer as it affects page performance. You could use hotkeys like Alt+E in combination with shift clicking to open the emote menu quickly as-needed.

**Comment by krytton** [comment]
I'm sorry but using keyboard combinations, especially shift-click, just isn't feasible for me in the long term. Please reconsider adding this option.

**Comment by krytton** [comment]
Okay, I understand. But I'd be really grateful if you reconsidered adding it as an option, at least, as keyboard combinations just aren't feasible for me.
