### ISSUE TITLE
Feature Request: disable new popup emote menu / emote previews

### ISSUE THREAD

**Issue by doubledgedboard** [night/betterttv#5257]
Twitch added a new feature recently where when typing an officially supported twitch emote (e.g. PogChamp), once you type the entire name of the emote it pops up a menu to display what it will look like, and then once you hit tab it actually replaces the text in the input box with the emote itself. (so "PogChamp" becomes the actual PogChamp emote graphic _before_ hitting enter to send the message)

This has considerable performance impact for many users and trying to paste an emote multiple times in the same message can cause the browser to lock up.

So a feature to disable it entirely might improve performance.

**Comment by night** [comment]
Thanks for the feedback. This is unfortunately not something that is easy to disable without breaking other functionality in the chat input, like autocomplete.

**Comment by zooba** [comment]
For anyone else (like me) who stumbles across this, seems like this is the Twitch issue to upvote: https://twitch.uservoice.com/forums/310201-chat/suggestions/44910226-return-the-ability-to-show-text-in-chat-box-instea
