### ISSUE TITLE
Feature request: "Frequently used emotes by other people" tab in the emotes menu

### ISSUE THREAD

**Issue by furkaneroi** [night/betterttv#5267]
It may not be efficient to hold the emote records in your servers but i thought it would be very useful to use the same emotes as other people some times.

Or maybe you can implement the feature locally so the extension can observe the most used emotes **(by other people)** in our own machines.

**Comment by night** [comment]
Thanks for the request. Unfortunately because BetterTTV does not track its users, we are not able to implement such a feature at this time.
