### ISSUE TITLE
Feature Request: Show chat even if a user is banned

### ISSUE THREAD

**Issue by regmibijay** [night/betterttv#5269]
Basically the idea is to be able to read chat even if you are not logged in or have been banned. I have noticed the missing chat or "you have been banned so you can not see all of the chat anymore" kind of ruins the whole stream experience.

**Comment by dclstn** [comment]
dupe of #3803

**Comment by regmibijay** [comment]
that issue is  locked and the solution mentioned there to use Anon Chat does not work (tested with v7.4.22)
