### ISSUE TITLE
[Question] Notification Settings

### ISSUE THREAD

**Issue by wilflare** [night/BetterTTV#527]
Sorry to bother but I'm a little confused.
(1) Dependency - Is BetterTTV independent of the notification settings in Twitch? I can't seem to find an option to enable just notification in Twitch (there's only Mobile Push and Email available)
(2) Conflict with Twitch Now? - I read/understand that BetterTTV does Desktop notifications and In-tab(?) notifications as well. Will either conflict with Twitch Now?

**Comment by night** [comment]
BetterTTV has no dependency on Twitch for our notifications. When you're on Twitch we periodically check for live channels for you and notify you in-tab (or via desktop notifications if enabled).

BetterTTV does not conflict with Twitch Now as far as I know, but I do not use that add-on so I have no clue.
