### ISSUE TITLE
BTTV losing Twitch Settings in Firefox 98

### ISSUE THREAD

**Issue by Jaster95** [night/betterttv#5271]
I have the problem in Firefox 98 that BTTV deletes the Twitch settings after a while. 
Audio settings are set to 50 %, the Chat settings are losing after a while and Warning for adults in stream shows up.
After I disabled BTTV it works with the twitch settings.

Will there be a fix for this because the problem is a bit annoying.

**Comment by night** [comment]
BetterTTV does not delete Twitch settings. Firefox losing settings has been reported in #4762 but is not able to be reproduced by us. It's likely some Firefox browser issue, rather than a BetterTTV issue. You might try reinstalling Firefox.
