### ISSUE TITLE
Feature Request: automatically reload stream player after decoding error occurs.

### ISSUE THREAD

**Issue by WhyWasMy-UsernameTaken** [night/betterttv#5272]
Like the settings for automatically loading and playing the front page, hosted, and recommended players, I suggest a feature to be added where BTTV will by default reload the player after encountering a decoding error such as Decoding Error 3000.
Thank you for all your time and the wonderful service you offer freely. I appreciate it,
-UsernameTaken

**Comment by night** [comment]
Thanks for the feature request. We unfortunately are not be able to accommodate features which inhibit or block adsense blocking functionality on Twitch.
