### ISSUE TITLE
Theater mode

### ISSUE THREAD

**Issue by Jarrjan** [night/BetterTTV#528]
Hi BetterTTV

Just want to start off with saying that i love what you are doing with the plugin.

I just found out about the "theater mode" functionality and its awesome as a feature in itself. The bug that i would like to report is about the dismissal of the info text that explains how to turn of theater mode. There is a "dismiss" text, but its unclickable, and i can't seem to find another way to dismiss the info text, so it just stays visible at the top left, which is a tad annoying. 

Would be great if you could patch it so that the dismissal option works.

Im using safari Version 8.0.6 (10600.6.3).

Thank you in advance and keep up the good work!

**Comment by night** [comment]
Theater mode is not a BetterTTV feature. When you hover over the player, this text appears and the player controls appear. Move your mouse off the player to dismiss both.
