### ISSUE TITLE
BTTV + Safari - Flash = tiny video playback 

### ISSUE THREAD

**Issue by BrianG2k** [night/BetterTTV#529]
I'm using Safari Version 8.0.7 (10600.7.12) and the latest version of BTTV on OS X 10.10.4
When I view a channel the video starts out at the normal size and then once all the BTTV stuff loads the video becomes extremely small. I can click on Theater Mode and it will become the proper size but I really prefer to not use Theater Mode. I have no other Extensions enabled. I've restarted my browser and I've also resized it. I also tried hiding all sidebars within the page. Nothing seems to help.

I do NOT have Flash installed and I am using all the HTML5 features that Twitch now provides.

**Comment by teak** [comment]
The new HTML5 features added by Twitch are for CHAT only. You still require flash for the player.

**Comment by BrianG2k** [comment]
Works fine without BTTV. Only when BTTV is my video tiny.
