### ISSUE TITLE
Feature Request - Chat delay

### ISSUE THREAD

**Issue by OneVoltTen** [night/betterttv#5293]
Twitch chat is frequently 3 seconds delayed behind the stream video. Could there be an option (slider) to manually adjust the chat delay?
This would make watching streams (am in Australia) far more enjoyable.
Would be fine if the option would reset after a certain time or after reload.

**Comment by OneVoltTen** [comment]
If this won't be added could you please advise what file I would need to edit to do this - assume it would be: https://github.com/night/betterttv/blob/master/src/watchers/chat.js

**Comment by night** [comment]
Chat delay is a moderation feature that some Twitch streams employ. We have no current plans to override this Twitch feature.
