### ISSUE TITLE
BTTV on Safari makes my video tiny

### ISSUE THREAD

**Issue by BrianG2k** [night/BetterTTV#530]
I'm using Safari Version 8.0.7 (10600.7.12) and the latest version of BTTV on OS X 10.10.4
When I view a channel the video starts out at the normal size and then once all the BTTV stuff loads the video becomes extremely small. I can click on Theater Mode and it will become the proper size but I really prefer to not use Theater Mode. I can turn off BTTV and video is always proper size. Also when BTTV is not installed, the video size is as expected.
I have no other Extensions enabled. I've restarted my browser and I've also resized it. I also tried hiding all sidebars within the page. Nothing seems to help.

I expect the video to play at it's normal size when using BTTV on Safari.

If it matters, I do NOT have Flash installed.

**Comment by teak** [comment]
This should now be fixed. Sorry for the confusion.
