### ISSUE TITLE
Feature Request - Option to delay the chat especially on VODs

### ISSUE THREAD

**Issue by azab0b** [night/betterttv#5308]
Sometimes the streamer disconnects (F), without the stream ending. The VOD chat ends up delayed the same length as the streamer was disconnected for the rest of the VOD. 
So my request is to have an option to set a video delay for example 1 minute, so the chat can catch up and be synced with the video

**Comment by night** [comment]
Thanks for the report, but unfortunately we have no easy means to control playback of the chat Twitch is rendering. BetterTTV can modify page elements after they render, but we do not control the display of elements.
