### ISSUE TITLE
auto-complete emote codes by TAB

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#532]
Feature request: auto-complete emotes by pressing TAB just like nicknames.

**Comment by DTittel** [comment]
Illogical then we have to decide that one takes priority over the other, when usernames start with the same character. Tab complete should remain limited to usernames

**Comment by evodoc** [comment]
Then for a different hotkey?

**Comment by night** [comment]
I do not think we want to add tab completion for emotes. Without a way to distinguish between emotes and usernames, it would just be confusing.
