### ISSUE TITLE
Showing email adress when submitting emote

### ISSUE THREAD

**Issue by Heelpa** [night/betterttv#5321]
Hello

How come that it is a standard thing when you upload an emote, to show email address as well. I think its weird, as there is not even an option to edit it when you upload. I've seen more people accidentaly leaking their email address on stream, because of this. Why not make it optional at least to show when uploading?

Regards Heelpa

**Comment by night** [comment]
Thanks for the feedback. Many users have multiple email addresses. We show the email address due to user confusion as to where we will notify them upon approval of their emote.
