### ISSUE TITLE
messages being filered in pop out chat only

### ISSUE THREAD

**Issue by ArchAngel7774** [night/betterttv#5345]
Messages that bttv allows me to see in a chat window still attached to a twitch stream appear as always, but some time in the last few months any time I use pop out chat, such as when I am live, all I get is "***" when something is filter. My mods still see the message but I can not.
I've played with setting in twitch, bttv, and frankz. nothing changes this. not for my channel or any other channels, but it only happens in the pop out window.

**Comment by night** [comment]
BetterTTV does not replace text with `***`. That is Twitch's chat filtering system you need to reconfigure.
