### ISSUE TITLE
Missing a TON of Emotes

### ISSUE THREAD

**Issue by SParkForces** [night/betterttv#5348]
I do not know if it just me, but I have tried using emotes like catJAM and it is not working :( KEKW worked when i tried it in a different channel, but a bunch of the other ones dont show up, they only show the words.

I wasn't sure if maybe it's because the streamer you're watching has to have certain emotes enabled on their channel, or? I just was curious as to why it wasn't working for me.
![betterttv](https://user-images.githubusercontent.com/104747390/166181229-9a7361cd-347b-42f3-9ef1-77214411eb10.PNG)

Please help, I just want my cat themed emotes back 😿

**Comment by kaguyomi** [comment]
same shit goes for me

**Comment by night** [comment]
You can verify you have BetterTTV Emotes and BetterTTV Animated Emotes enabled in our settings. If both are enabled, then they are not BetterTTV emotes you are not seeing.
