### ISSUE TITLE
Automatic theater mode stopped working

### ISSUE THREAD

**Issue by Omarock92** [night/betterttv#5361]
Just now, it was working an hour ago.

**Comment by Dinshu1337** [comment]
Same issue. Firefox, windows 10. Tried removing and readding extension, turning the option on and off, restarting browser, clearing cache, cookies, history, no luck.

**Comment by rowbawts** [comment]
Same here, Firefox on Linux (Fedora 36) and I'm using the user script version with Tampermonkey.

**Comment by Ree1981** [comment]
Same. Latest stable Chrome release, Windows 10.

Hoping it would be fixed ASAP. I'm so used to the way it looks in theater mode I have to press the button each time now. >_<

**Comment by Far-Se** [comment]
> Same. Latest stable Chrome release, Windows 10.
> 
> Hoping it would be fixed ASAP. I'm so used to the way it looks in theater mode I have to press the button each time now. >_<

Here is a script i've made, it forces theatre mode, also has stream preview in sidebar, shows time/viewers in left corner and displays sidebar when you move mouse close to it:
https://gist.github.com/Far-Se/3f00d4370a849a37e9858720dafb0d0d
You need to have tampermonkey installed.

**Comment by Kyrazhi** [comment]
I've still been experiencing the issue of auto-theatre mode not working after this update. It'll work sometimes, but sometimes it'll open in theatre mode and then immediately exit to regular view.
Currently on Firefox, restarted PC and browser and got the add-on update.

**Comment by MrTOFT** [comment]
it's a shame auto theater mode don't work anymore.latest chrome and windows 10. now i have to put theater on everyn stream again. very annoying

**Comment by Omarock92** [comment]
It's fixed for me today, update your extension.

**Comment by MrTOFT** [comment]
no matter what i do, it doesn't work for me. auto theater is not working. and it is the right version. guess i just have to miss that theater mode

**Comment by MrTOFT** [comment]
i think i have gotten it working again somehow by doing auto t mode off and on again and put theater mode on before closing.  that seems to do the trick

**Comment by Kyrazhi** [comment]
@Omarock92 like I said, I did double-check I got the update for the add-on.
@MrTOFT I just tried giving that a couple of tries, it seemed to work at first but it's back to opening in theatre mode, then immediately exiting out of theatre mode again.
Is the add-on trying to click the theatre button twice?

**Comment by MrTOFT** [comment]
> @Omarock92 like I said, I did double-check I got the update for the add-on. @MrTOFT I just tried giving that a couple of tries, it seemed to work at first but it's back to opening in theatre mode, then immediately exiting out of theatre mode again. Is the add-on trying to click the theatre button twice?

try to be patient, i find i try more times with it. try to be a little patient and it a little longer to see if it works. i was impatient myself :P

**Comment by MrTOFT** [comment]
> I've still been experiencing the issue of auto-theatre mode not working after this update. It'll work sometimes, but sometimes it'll open in theatre mode and then immediately exit to regular view. Currently on Firefox, restarted PC and browser and got the add-on update.

yea me to. sometimes it works but not always. a lot of times i have to put threater mode on myself sadly. not always working sadly

**Comment by R1dyk** [comment]
Haven't been fixed for me neither. 

I suggest re-opening this issue and testing it. 

@MrTOFT i tried your method, but still it doesn't work.

**Comment by fragande** [comment]
I'm also experiencing this (Firefox 100.0.2, bttv 7.4.28, W10). It works only if I click directly on a channel in the followed list (left pane). Any other way is broken (for example opening in a new tab or clicking on a channel from the Browse page).

**Comment by R1dyk** [comment]
Exactly for me, I open the channel -> TM is activated -> stream loads -> goes back to normal (no TM)
