### ISSUE TITLE
Tab emote autocomplete doesnt work

### ISSUE THREAD

**Issue by Aroeloe** [night/betterttv#5362]
The tab emote autocomplete has been a bit wierd for the last week or so. And now it just doesnt work.

**Comment by night** [comment]
I am not able to reproduce any issues with this functionality locally. If you're still having issues, please provide steps for us to reproduce it.

**Comment by Aroeloe** [comment]
i installed 7tv for some other chat than i mainly watch but it made it so
it's only active when i press the extension icon. When 7tv is not active
but installed, the tab autocomplete doesnt work.
