### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by Meteayy** [night/BetterTTV#537]
I have a long username and people tend to call me by shortening it. A feature that colors the message if there is a specific word in it would me nice. like "User" instead of "@username".

**Comment by OurFlagIsMined** [comment]
You can do so by adding your nickname to the 'Set Highlight Keywords' list (under the cogwheel settings menu). To add more than one item to the list, just separate each token with a space (e.g. 'ourflag meteayy mete').
