### ISSUE TITLE
BTTV emotes in chat.google.com (mail.google.com/chat)

### ISSUE THREAD

**Issue by jeffreyxchan** [night/betterttv#5372]
During the workday, I use chat.google.com (alias for mail.google.com/chat) in the web browser, and I was thinking it'd make the workday more fun if I could have bttv emotes in the chats. Does anyone know if it's even possible/feasible to implement something like that?

I also noticed there was a previous issue about having emotes in FB Messenger. I was wondering if it was closed because FB messenger is a mobile/native app. Is it not possible to do this for the FB Messenger browser application?

**Comment by night** [comment]
Thanks for the feedback, but unfortunately BetterTTV doesn't have a concept of global emotes we could load into chats like GMail. BetterTTV associates emotes with Twitch channels, and while we can offer adjacent support for other social media presences those sites must also map 1:1 with channels.
