### ISSUE TITLE
Auto Theatre Mode is not working after newest update

### ISSUE THREAD

**Issue by R1dyk** [night/betterttv#5379]
I've been experiencing this issue for ~1 month. The option to enable Theatre mode by default is not working properly, after going to a channel It's never in TM. 

Running on:
Chromium: 101.0.4951.67 (Official Build) (64-bit)
BetterTTV 7.4.25

**Comment by FlatlineTV** [comment]
Yup, same here! Been trying to figure it out.

**Comment by night** [comment]
duplicate of #5361

this is already fixed in the latest update.
