### ISSUE TITLE
Bug: latest automatic theatre mode fix #5361 broke profile page

### ISSUE THREAD

**Issue by alexxfra** [night/betterttv#5381]
When you have the automatic theatre option enabled, and navigate to a channel subdirectory, (e.g. https://www.twitch.tv/asmongold/videos) the latest VOD starts in theatre mode with no option to exit out of it.

With the option disabled, there are no issues.
[imgur example](https://imgur.com/a/3h0EqGg)

**Comment by night** [comment]
This is fixed as of the latest update.
