### ISSUE TITLE
Theatre Mode made vods Inaccesable

### ISSUE THREAD

**Issue by undeterminedcos** [night/betterttv#5383]
I've had theatre mode on for god knows how long now and two days ago, I started not to be able to access any past stream videos from anyone I followed. I tried using incognito mode and the issue didn't occur. It was only when I talked to a friend that he suggested looking at my BTTV setting, auto player wasn't the issue, so I turned off theatre mode and that worked.

 I don't know why it's been doing this but I wanted to bring attention to it since it only ever used to make it so I had theatre mode open when I clicked on a profile that went live.

**Comment by night** [comment]
This is fixed as of the latest update.
