### ISSUE TITLE
videos on channel homepages auto-play in theater mode, blocking everything else.

### ISSUE THREAD

**Issue by Tor-Saxberg** [night/betterttv#5387]
There's a bug that auto-plays any video on a twitch channel's homepage in theater mode, but there is no theater mode button on the player, so it's impossible to exit the player to view other parts of the homepage, such as previous broadcasts. When I disable betterttv and reload the page, the problem resolves. when I re-enable it and reload, the problem returns.

in bttv settings, I have auto-theater mode on, but all three auto-play options are off. 
I'm using Brave 1.34.81, Chromium: 97.0.4692.99,  MacOS 12.3.1

**Comment by SuperBupDX** [comment]
i made a post about this as well and happy its not just me, except i just had to disable auto theater, then it all worked. Imma wait til next update to reenable it

**Comment by night** [comment]
This issue is already fixed in the latest update.
