### ISSUE TITLE
Viewer list

### ISSUE THREAD

**Issue by FairlyAveragePlayers** [night/BetterTTV#539]
When looking at the viewer list, it will show no names but have the length as tho it was showing in both black and white background.

**Comment by night** [comment]
Do you have a picture? What other add-ons are you using for Twitch?

**Comment by FairlyAveragePlayers** [comment]
![black and white](https://cloud.githubusercontent.com/assets/13206551/8533404/6f9da2e6-23fa-11e5-9545-fb432c48d7a7.png)
The only other addon is twitch giveaways. I have me and a buddy in along with my bot and neither of the 3 are showing up?
If you need more info I will be glad to give as much as I know XD.
Thanks,
FAP

**Comment by night** [comment]
Well I cannot reproduce this issue. Try clearing your cookies and cache.

If that doesn't work, try the following:

Paste ```chrome://extensions/``` in your address bar and press enter, and then disable everything but BetterTTV. Then, check if it works. If so, another extension is breaking the viewer list.

**Comment by FairlyAveragePlayers** [comment]
The only other one i had, except the basic google included ones, is adblock plus and that seems to be the problem.

https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb?utm_source=chrome-app-launcher-info-dialog
This is the version.

Thanks,
FAP

**Comment by night** [comment]
Generally Adblock itself is the reason Twitch breaks. Adblock also breaks the Nightbot panel. There's nothing we can do when Adblock breaks things.
