### ISSUE TITLE
Feature Request: Friends

### ISSUE THREAD

**Issue by katcnav** [night/betterttv#5398]
I’m really going to miss seeing when my friends are online and connecting through the streams we watch. Would it somehow be possible for BTTV users to see the activity of BTTV users they follow, assuming you both have the feature enabled?

**Comment by night** [comment]
Thanks for the feature request. Unfortunately Twitch decommissioned all friends and presence systems they were previously maintaining. We do not have plans to duplicate this behavior at this time.
