### ISSUE TITLE
BetterTTV Emotes Bug

### ISSUE THREAD

**Issue by JohnCryman** [night/BetterTTV#540]
Everytime I deactivate the BetterTTV Emotes,
the chat is restarting and nothing happens.

Even if the emotes were already deactivated,
they stay there, even in the new chat.

**Comment by night** [comment]
The "BetterTTV Emotes" setting only disables BetterTTV emotes, not Twitch emotes.

**Comment by JohnCryman** [comment]
I mean in this case, the special icon of the application

Not the twitch emotes

**Comment by night** [comment]
Unless you can prove otherwise, the feature is working as intended per my own testing.

**Comment by JohnCryman** [comment]
i solved the problem by myself, reinstalling the app in firefox seemed to solve the problem ^^

**Comment by night** [comment]
Cool!
