### ISSUE TITLE
Auto-theater mode not working

### ISSUE THREAD

**Issue by trizzo8** [night/betterttv#5415]
Issue is NOT fixed. Using Google Chrome, auto-theater will not work unless you refresh the page.

**Comment by Kyrazhi** [comment]
@andrewrmoy describes the issue exactly. It seems to start off working then immediately exits. I'm in the same situation with Firefox and I've double-checked the versions and made sure I have the latest updates for everything.
@night please don't close this as already fixed, it clearly is not.
