### ISSUE TITLE
Host Button in Twitch default is [OFF]  

### ISSUE THREAD

**Issue by bononista** [night/betterttv#5418]
Recently something changed in BTTV and every time I log in I have to go to the default list and toggle the HOST button on twitch to the ON position. When I log off of twitch and back in, the setting is back in the [OFF] position, and i have to go in and change it each time.  

The Host Button should be on by default, or if not, upon setting it so the toggle is in the ON position, it should remember that setting and always be on until the user goes back and toggles it to OFF.

**Comment by night** [comment]
You may wish to double check that your browser settings/cookies are not configured to reset on browser close, as that's usually the cause of settings being wiped. Because BetterTTV does not have this enabled by default, you will need to reconfigure BetterTTV on every launch.

**Comment by bononista** [comment]
Hello.
They are not set to reset site preferences upon closing.  

I'll just uninstall the BetterTTV add-on instead. The Host Button appeared each time on Twitch before installing BetterTTV. 

***@***.***

    On Sunday, June 5, 2022 at 09:37:21 PM PDT, Zack ***@***.***> wrote:  
 
 


You may wish to double check that your browser settings/cookies are not configured to reset on browser close, as that's usually the cause of settings being wiped. Because BetterTTV does not have this enabled by default, you will need to reconfigure BetterTTV on every launch.
