### ISSUE TITLE
[Feature] Add a tab to the site to see 2 character emotes 

### ISSUE THREAD

**Issue by Flameruin** [night/betterttv#5419]
Only one I know is EZ emote (which can be found from 'Top Emotes') and I have no idea if more exist since you can't search for them using the new search query in the site redesign.

I would suggest a tab that shows all emotes of 2 (and 1 if they exist) characters length and only them since there is no way to reach them unless you have the link for them.

**Comment by night** [comment]
Thanks for the feedback. Unfortunately emotes of that length are rare/deprecated and not supported for new emotes being uploaded in the system. While it would be nice if they were queryable, we have to balance functionality with scalability in mind for search results.
