### ISSUE TITLE
suggestion: esport chat mode

### ISSUE THREAD

**Issue by RSKcsgo** [night/betterttv#5428]
Betting sites score are a few minutes ahead of the livestream score. This makes users spoil the score in chat, which ruins the enjoyment of the match. This has been a plague in esports forever.
A few years ago, I tried to manually blacklist all types of score possibilities, which didn't work so well because there are thousands of score possibilities.
The idea is to create an esport chat mode on-off button that blocks all numbers in the chat.

**Comment by night** [comment]
Thanks for the suggestion, however this is a pretty difficult issue to fix as there are numerous ways to represent numbers which filtering can bypass. You might need to hide chat entirely?
