### ISSUE TITLE
Host Channel button doesn't move Exit Watch Party button

### ISSUE THREAD

**Issue by divinerabbitdps** [night/betterttv#5429]
Obviously some things on the page need to be moved around to allow space the "Host Channel" button, the "Exit Watch Party" button seams to have been missed.

Here's screenshots of the buttons, and inspect element.  Also have the full page source if that helps.

![2022-06-09_20-47-03](https://user-images.githubusercontent.com/99097629/172973928-eca7406d-bd3e-436a-aba2-ca0db7ccd3e6.png)
![2022-06-09_20-47-00](https://user-images.githubusercontent.com/99097629/172973929-22683119-8773-4799-aa7c-936a0df7555d.png)

**Comment by night** [comment]
upon investigation this appears to be a Twitch bug:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/2942184/179438689-f8540cbe-f2eb-43e2-ac62-dca66325df73.png">
