### ISSUE TITLE
sidebar issue

### ISSUE THREAD

**Issue by shinjikun10** [night/betterttv#5440]
issue(s): 
sidebar isn't expanding when being hovered by mouse; auto 'Load More' also doesn't work

browser and version:
Chrome Version 102.0.5005.115

steps tried to fix the issue:
uninstalled BTTV; cleared cookies; disabled all twitch-related extensions(FFZ, BTTV, 7TV)

**Comment by jeffreyxchan** [comment]
+1 I'm noticing this as well. (I didn't know this was a BTTV feature until I opened up a support ticket with Twitch and they told me hovering over the sidebar and having it pop out isn't a Twitch feature, it's a feature of a third-party extension.)

**Comment by speeedy1** [comment]
I have the same issue, the sidebar stopped auto-expanding on mouse over 3-4 days ago
when I click the arrow to expand, the "show more" link doesnt work either
browser: chrome 100
I tried with opera 84 too, same thing

**Comment by MithicSpirit** [comment]
Same issue and hiding featured channels doesn't work anymore either.

**Comment by Doomreavr** [comment]
Same issue. First noticed this issue on Tuesday 6/14/22. Whenever I open Twitch in my Firefox browser and I hover my mouse over the left sidebar, nothing happens. I have to click on the Expand arrow which keeps the left sidebar fully open all the time until I re-click the arrow to hide it showing only streamer icons. First, I checked the version of my BTTV to see if it needed to be updated but I had the latest version already installed. Tried clearing my cache and cookies in my browser, closing my browser windows, and then reopening them to Twitch but that didn't work. Same issue. Tried uninstalled BTTV and reinstalling but that didn't work either. 

My BetterTTV version is Version 7.4.29
Firefox version: Version 101.0.1 (64-bit)

**Comment by jimbo1111** [comment]
Same issue, really crippling.  Brave on MacOS

**Comment by PeterCardenas** [comment]
not sure how to fix this in the repo, but currently just running this script to get functionality back
```js
const sideNav = document.querySelector(".side-nav");
const expandBtn = document.querySelector("button[data-a-target='side-nav-arrow']");
sideNav.onmouseenter = e => {
  if (sideNav.classList.contains("side-nav--collapsed")) {
    expandBtn.click();
  }
};
sideNav.onmouseleave = e => {
  if (sideNav.classList.contains("side-nav--expanded")) {
    expandBtn.click();
  }
};
```

**Comment by NatalieGates** [comment]
None of the sidebar features are working.

**Comment by fREAST** [comment]
Don't think this is a BTTV issue, the auto-expanding sidebar was/is a native Twitch feature.

You can turn it back on (until Twitch decides to remove it completely) with FFZ in Debugging and "Twitch Experiments", search for `vxp_left_nav_hover_logged_in` and change it to `treatment` and reload the page, you'll get auto-expand back.

**Comment by speeedy1** [comment]
> Don't think this is a BTTV issue, the auto-expanding sidebar was/is a native Twitch feature.
> 
> You can turn it back on (until Twitch decides to remove it completely) with FFZ in Debugging and "Twitch Experiments", search for `vxp_left_nav_hover_logged_in` and change it to `treatment` and reload the page, you'll get auto-expand back.

thank you ! it works for the auto-expanding
but the show more/show less, still doesnt work

**Comment by Doomreavr** [comment]
> Don't think this is a BTTV issue, the auto-expanding sidebar was/is a native Twitch feature.
> 
> You can turn it back on (until Twitch decides to remove it completely) with FFZ in Debugging and "Twitch Experiments", search for `vxp_left_nav_hover_logged_in` and change it to `treatment` and reload the page, you'll get auto-expand back.

That worked. Thank you fREAST!

**Comment by night** [comment]
This feature is/was not a feature of BetterTTV.
