### ISSUE TITLE
Image preview not working (Firefox 39.0)

### ISSUE THREAD

**Issue by AFlyingHobo** [night/BetterTTV#545]
Ever since it was added, it just never worked on Firefox. For me at least, now it looks like it wants to do it but doesn't. I tried links from imgur jpg and gif but both didn't work. Weird enough gifv from imgur worked but nothing else.
![7d700981d13baeb5bc5dac55a47336f4](https://cloud.githubusercontent.com/assets/13229904/8561899/4bd96186-24f1-11e5-8b76-a5324a24fdb3.gif)

**Comment by night** [comment]
Does it work when you post SSL links?

like http**s**://i.imgur.com/blah

**Comment by punkdude1599** [comment]
Mine don't work either. on Bit.ly links it posts the entire link like i think its suppose to but on imgur and stuff it shows the exact same black box no link description.

**Comment by night** [comment]
I started forcing all non-SSL URLs to SSL. If the image doesn't support SSL, there's nothing we can do in that instance.
