### ISSUE TITLE
Errors  Bttv

### ISSUE THREAD

**Issue by For-ID** [night/betterttv#5459]
![image](https://user-images.githubusercontent.com/72587985/177046937-8008c136-ed10-4ad2-8967-6bf03e7ade11.png)
The problem is as follows, I can see everything from Bttv on TTV except emotes, text in chat doesn't turn into emotes.
![image](https://user-images.githubusercontent.com/72587985/177047311-244d2bcf-5768-4c0b-ae14-f4d46989e859.png)

**Comment by night** [comment]
These errors do not appear related to BetterTTV. If you are not seeing specific emotes, they may not be BetterTTV emotes.
