### ISSUE TITLE
Double Emoticons bugging quick menu

### ISSUE THREAD

**Issue by Mrazulik** [night/betterttv#5473]
![obrazek](https://user-images.githubusercontent.com/108758830/177390982-6bdc2d60-5d06-4aa0-95ed-10c51d90ecf4.png)
 Hello guys I got some problems with your addon. BTTV makes double emotes while searching using colon ( : ) you can see it in picture.
I´m sure it´s BTTV fter running some tests. Its possible I just did oversee a option to turn off double emotes or not.

Thanks for you help.

**Comment by night** [comment]
This isn't really something we can easily fix, and is due to using multiple extensions which are extending Twitch chat with additional emotes. You may want to try removing one or more of them.
