### ISSUE TITLE
Feature Request - Autorefresh Twitch Streams

### ISSUE THREAD

**Issue by F1ReB4LL** [night/betterttv#5479]
Sometimes, when you're collecting channel points it is getting unnoticed that the channel has disconnected/stuck and you're not getting any points until refreshing the page. Is there any chance to implement some kind of 'keepalive' autorefreshes of the Twitch streams? Either forced (like, autorefresh every xx minutes enable/disable setting) or, maybe, some kind of a 'smart' autorefreshing when the points counter doesn't increase for a while.

**Comment by night** [comment]
Thanks for the request. Generally speaking you should not need to refresh the page to keep your stream working. If your internet is unstable, you might find value from one of the many page refreshing browser extensions that other developers have created.
