### ISSUE TITLE
Disable Chat Field History option

### ISSUE THREAD

**Issue by TheTruthOfPerfection** [night/BetterTTV#548]
I would love an option to disable the chat field history for BetterTTV. I find the chat field history to be incredibly frustrating.

I have always used the up arrow key to quickly move between lines of text, when I make a message, or, to move to the start of the message if there is only 1 line. I am not the best typist, so if I want to reword what I am typing, or just want to fix a typo (because OCD), then I want to be able to quickly fix it, which is something I can't do with the chat field history being forced on.

If I press up while typing out a message, then not only does the message get replaced with a message I have previously sent, but If I try to go back to what I was typing by pressing down, everything I was typing will be gone. This is very, frustrating, wastes some of my time, and befouls my mood every time it happens.

If you could add an option to disable the chat field history altogether, or at least disable it while there is text in the message box, that would be wonderful.

**Comment by night** [comment]
You can disable it by typing "/linehistory off" in chat. We apologize that there isn't a visual toggle for it at this time, but it is planned in the future.
