### ISSUE TITLE
Suggestion - Pause stream in case of raid if stream was paused before

### ISSUE THREAD

**Issue by MarcMil** [night/betterttv#5481]
When I pause a stream, because I don't want distraction for now, and the streamer decides to end the stream and raid someone else, the browser changes to the raided channel and the new stream blasts out with full volume.
Twitch should fix this by themselves, but they probably won't, which is why I suggest this feature here.

**Comment by night** [comment]
You might find value from the "Mute Invisible Player," which will mute streams in background tabs.

**Comment by MarcMil** [comment]
Thinking about it, another possibility would be an "Auto opt-out of Raids" option. This way the user does not participate in the raid and thus the playback would not resume automatically.
