### ISSUE TITLE
Feature Request - Attribute to allow for crediting artists

### ISSUE THREAD

**Issue by melinderp** [night/betterttv#5482]
It would be great if were able to credit another user for creating an emote that I upload to BTTV. Maybe a new attribute when first uploading an emote? A free text or maybe a reference type where you search for another user in BTTV?

**Comment by night** [comment]
Thanks for the request. We've added a new Attribution field onto the emote page which allows you to attribute an emote to an artist or designer. It will then show as a tooltip when the attribution icon is hovered on the emote's page.
