### ISSUE TITLE
Auto Play and Auto Stop

### ISSUE THREAD

**Issue by SuperFurias** [night/betterttv#5491]
Please add a way to "auto stop" all videos from automatically playing on twitch, i have many many twitch tabs opened in my browser, with different video of different games (gameplays), but every time i click on one of the tabs wrongly, it starts playing and is quite annoying

**Comment by SuperFurias** [comment]
Something like the chrome extension "AutoplayStopper" that auto stop all videos from autostarting

**Comment by night** [comment]
Thanks for the request. We already have an autoplay setting for certain players on Twitch, but it's unlikely we would create such a feature to pause all video content from autoplaying considering many would not find value from it.
