### ISSUE TITLE
Front page auto-player disabled is not working.

### ISSUE THREAD

**Issue by KMDavis911** [night/betterttv#5495]
I'm not too fond of the front page streams playing on Twitch, so I disable the auto-play function in BetterTTV. But now, for some reason, even after removing and reinstalling it, the front page streams play regardless. This pisses me off. Please fix it.

**Comment by privacyguy123** [comment]
Same here as of today.

**Comment by sunrastar** [comment]
I came to report that same issue, Front-page Player has been auto playing when I have the option disabled in the menu. This issue started 2 days ago.

**Comment by night** [comment]
fixed via 63e94084729bd1b05e4593f03ce4048a371e2380

**Comment by KMDavis911** [comment]
How do I get this fix to work? The front page streams are still playing even with the box unchecked. What do I need to do?

**Comment by night** [comment]
you have to wait for the next update.

**Comment by KMDavis911** [comment]
Any ETA?
