### ISSUE TITLE
Team Tags/Badges

### ISSUE THREAD

**Issue by dajeroen** [night/BetterTTV#550]
Allow people to add team tags for teams on Twitch, these will obviously have to be verified to see if they look normal and/or are not NSFW.

For example: http://www.twitch.tv/team/musicmods - We would love to have a purple music note next to our names.

Thanks

**Comment by DTittel** [comment]
This literally would just clutter chat with badges and add work for the approval team.

**Comment by night** [comment]
Tags are grandfathered and are being discontinued, sorry.
