### ISSUE TITLE
Click to Play Feature Stopped Working

### ISSUE THREAD

**Issue by Goldenlion5648** [night/betterttv#5510]
In the last few days, the click to play feature has stopped working. I tried toggling the feature on and off in the settings, as well as clearing cookies, it still doesn't work. Maybe a chrome update broke it?

**Comment by ckk987** [comment]
Having the same issue on Chrome I tried checking in Firefox and it was working as normal.

**Comment by noviceg** [comment]
same here

**Comment by Goldenlion5648** [comment]
Seems to be working now? Strange
