### ISSUE TITLE
Deleted Messages no longer showing

### ISSUE THREAD

**Issue by whatever-forever** [night/betterttv#5512]
Deleted messages haven't been showing anymore. Just says "_message deleted by a moderator_"

**Comment by madb0x** [comment]
Me too. Same problem. 

I also see that other features of the BetterTTV app are also not working, for example the option to turn off autoplay for live streams on the Twitch homepage. (Option: Front-page Player) I don't have the box checked and the video on the main page keeps playing.

**Comment by pussydestroyer47** [comment]
it happened with me too

**Comment by EnzoDely** [comment]
Same here

**Comment by royoungs** [comment]
Same issue.

**Comment by night** [comment]
fixed via d17d0c65c15d3b885c0eb99c1b9d958d3342de9c
