### ISSUE TITLE
/localsub Unrecognized command 

### ISSUE THREAD

**Issue by MachineEIf** [night/betterttv#5516]
If i try to use /localsub it says Unrecognized command: /localsub i have also removed all other chrome extensions and bttv is the only one and it still doesnt work

**Comment by MachineEIf** [comment]
i also downloaded firefox and installed bttv extension and local sub still did not work

**Comment by MachineEIf** [comment]
also show deleted messages option is not working either

**Comment by night** [comment]
fixed via d17d0c65c15d3b885c0eb99c1b9d958d3342de9c
