### ISSUE TITLE
tab autocompletion not working for emotes that are not on bttv ( twitch emotes)

### ISSUE THREAD

**Issue by notjoker28** [night/betterttv#5518]
it comes up with "no matches." Wasn't sure how to best report this, but I did notice my console was getting these errors maybe this helps? 
![Screenshot 2022-07-20 12 06 36](https://user-images.githubusercontent.com/108376941/179880420-eca9614c-09ef-4eb1-8567-31df88e678b4.png)
![Screenshot 2022-07-20 12 06 52](https://user-images.githubusercontent.com/108376941/179880430-40e04a15-ae6a-4a5c-ab67-6bee88c95a24.png)

**Comment by averageFellow** [comment]
been having the same problem, autocomplete doesn't work with twitch emotes
![image](https://user-images.githubusercontent.com/109647621/179905769-6c1b394d-7dbd-480c-9657-3bd27886a06a.png)

**Comment by c0d3f0rc3** [comment]
I have the same problem, too

**Comment by night** [comment]
fixed via d17d0c65c15d3b885c0eb99c1b9d958d3342de9c
