### ISSUE TITLE
Tab still not completeing twitch emotes.

### ISSUE THREAD

**Issue by Skaithakk** [night/betterttv#5521]
I know the other thread says it was fixed and i've updated and restarted my browser a couple times but it still doesn't work.

**Comment by night** [comment]
You may need to update your extension. This is fixed as of version 7.4.31.

**Comment by derpyderpaderp** [comment]
> You may need to update your extension. This is fixed as of version 7.4.31.

This is 100% not fixed on 7.4.31. Still the same issue.
