### ISSUE TITLE
About tab auto completion bug (only with global twitch emotes)

### ISSUE THREAD

**Issue by Oblivious322** [night/betterttv#5524]
I know there was a post about this before but it was closed and the issue is still not solved for me

**Comment by night** [comment]
Are you certain you are updated to version 7.4.31 or higher?

**Comment by Oblivious322** [comment]
Yes, I do have 7.4.31 version

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by night** [comment]
Can you provide some specific reproduction steps so we can take a closer look?

**Comment by Oblivious322** [comment]
I am sorry im not sure what you exactly mean by reproduction steps, could you explain?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Oblivious322** [comment]
I don’t really know but you can check the current version by going to chrome settings -> extensions -> bttv -> details

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by pussydestroyer47** [comment]
I have version 7.4.31 and I still don't see deleted messages

**Comment by Oblivious322** [comment]
Same

**Comment by howardthepilot** [comment]
Same issue here, and also with the "show deleted message" checked, I still don't see the deleted message.
I'm sure on the latest 7.4.31 version.
![first](https://user-images.githubusercontent.com/7646757/180066390-08efbc82-233b-47f5-bbf3-2070615805fe.jpg)
![second](https://user-images.githubusercontent.com/7646757/180066402-be4de093-7ad7-4db6-b24d-dabca57b20b1.jpg)

**Comment by b2311e** [comment]
Same issue with the emote tab completion not working for default Twitch emotes, and I can't see deleted messages either. Version 7.4.31. Reinstalled from Chrome store to no effect

103.0.5060.114 (Official Build) (64-bit) (cohort: Stable)

**Comment by deanpcmad** [comment]
Same here on Firefox 102.0.1

**Comment by 2ndkirbyever** [comment]
Same issue with emote tab completion not working for Twitch emotes I have access to. Chrome 103.0.5060.134, BTTV 7.4.31

**Comment by Garnzlok** [comment]
I have the same issue of sub/global twitch emotes not being tab completable without the use of ":" I double checked my BTTV version and even reinstalled it earlier today. so i have Chrome  103.0.5060.134 BTTV 7.4.31 I have tried disabling extensions I could see causing issues such as 7TV to no effect, and have tried in incognito. 

I can't give you ways to reproduce it since it just sort of happened with no changes to my settings a couple days ago . and if I knew how to reproduce it I would know how to avoid it. It first happened on the 18th, and has been broken since then.

**Comment by Skaithakk** [comment]
Same here, my thread was closed saying it's fixed, im on the latest version of the extension and on firefox 102.0.1. Tab only completes BTTV emotes and not twitch ones like before
