### ISSUE TITLE
<message deleted by Moderator> not showing deleted messaged. FF 102.0.1 bttv 7.4.31

### ISSUE THREAD

**Issue by variandra** [night/betterttv#5525]
if a chat is removed the <message deleted by moderator> shows and not the greyed out message. this was talked about a little in https://github.com/night/betterttv/issues/5524 this issue but it doesn't have its own thread.
Double checked setting and i have "Show Deleted Messages Changes <message deleted> back to users' original messages." marked.
this happens in every channel. i am not a mod of any channels.

**Comment by night** [comment]
I am not able to reproduce this behavior with version 7.4.31 on Firefox with show deleted messages enabled. If you're still having issues, have you tried restarting your browser after installing the update?
