### ISSUE TITLE
Feature Update Request: Auto Play -> DISABLE Front-page Player

### ISSUE THREAD

**Issue by sydmarf** [night/betterttv#5528]
On the front page, upon completion of viewing a featured clip, **disabled Auto Play** for Front-page Player becomes **ignored** and the Front-page Player **starts** playing.

Mouse wheel-scrolling once on the page, pauses the video player but then after completion of viewing another featured clip the Front-page Player starts playing again and which cannot be stopped anymore using mouse-scrolling.

BTW, featured clips appear titled "**Clips we think you’ll like**" on the bottom-most part of the Front-page only if the user is logged into Twitch.

P.S. Huge fan of this browser extension. Keep up the awesome work. Thank you.

**Comment by night** [comment]
I do not see a featured clip on the homepage, and am unable to reproduce autoplay breaking on the homepage. If you have a  video or specific steps to reproduce this issue we can take another look!
