### ISSUE TITLE
Disable/hide/timeout new 'pin this channel' popup

### ISSUE THREAD

**Issue by Thalenia** [night/betterttv#5535]
New feature on Twitch to be able to pin channels to the top of your follower list (which is fine), but hovering over any channel on your list pops sometimes (usually) up a 'pin this channel' window/toast that doesn't go away or time out.  It would be nice to see this popup able to be disabled.

**Comment by night** [comment]
It looks like this is a bug which they have since fixed? I am not able to reproduce this issue.
