### ISSUE TITLE
HELP! Better TTV works, But when i select to reverse the chat in the options, nothing shows up.

### ISSUE THREAD

**Issue by andrew1ups** [night/betterttv#5537]
im using obs and have relogged into everything just to see if that fixed it. i streamed yesterday and it was fine. today nothing was showing so i turned off better ttv and it fixed the chat issue. but when i selected to reverse the chat again, everything erased and wont show new or old messages. they are still being sent cuz i can see them on slobs, stream elements and chatty. just not obs when having the chat scroll up. this all started today. i have the extention downloaded on chrome as well. please help

**Comment by nickruhle** [comment]
I'm having the exact same issue as the person above. The EXACT same problem. Something is bugged with the reverse chat. Would really like if anyone had an answer! Thanks!

**Comment by jetpackpaul** [comment]
I'm having the same issue as well. I'm on Chrome on a Mac. 
Chrome Version 103.0.5060.134
BTTV 7.4.32

**Comment by SwearinTV** [comment]
This is happening to me as well! Reverse chat is my favorite bttv feature by far - is there any way I can get it to work in the timebeing? thank you so much

**Comment by mumpow** [comment]
reverse chat also isn't working for me. it's as if the chat window doesn't exist or is too short to show the messages - so you can still type in the chat box and the messages get sent, but you can't see anything above.

**Comment by piectomek** [comment]
I got the same problem, that is the most important feature for me.

**Comment by ttartari** [comment]
Same problem here. Love this feature to better read chat without lower my head. Fix it when possible, please. Love your extension!

**Comment by andrew1ups** [comment]
is this the fix?

**Comment by mumpow** [comment]
it's fixed for bttv version 7.4.33, which is what i have now in my chrome
browser, but it hasn't updated in obs yet (for me, that's still on 7.4.32)

i assume eventually the obs one will update, i don't think there's a way to
trigger that manually

**Comment by piectomek** [comment]
It's working again, I didn't have any update. It's just working now, thank You for fixing it!

**Comment by andrew1ups** [comment]
ok mines working. thank u guys so much for the quick fix. appreciate it!

**Comment by toucdark** [comment]
Before the option inverted the chat with the recommended channels, and now the recommended channels does not come out of the right. Will it stay like this? Can you create an option to put the recommended channels on the right?

**Comment by bigbabyjhony** [comment]
> n

updated to version 7.4.35 and it fixed
