### ISSUE TITLE
Modcard timeout and permit buttons gone

### ISSUE THREAD

**Issue by Dragoonseal** [night/betterttv#5540]
Chrome Version 103.0.5060.134
BTTV Version 7.4.32
Win 10

It's just defaulting to Twitch's timeout (10m) and ban buttons. Not BTTV's usual 1s purge, 10m, 1h, 24h, ban, !permit.
My other fellow mods all report the same.

**Comment by candybomberz** [comment]
Same here. Tested everything, deleting cookies, reinstalling bttv, incognito to have a clean browser for testing, nothing worked to bring back those buttons.

**Comment by Lpz3nc** [comment]
still not visible
