### ISSUE TITLE
Feature request: expand left side's following channels

### ISSUE THREAD

**Issue by gitHu6-newb** [night/betterttv#5541]
somewhere in the week of 7/10 or 7/17 twitch compacted the left panel to show just the channel icons. Now I can't just read at a quick glance to see who's online unless individually mouse-overing them one by one. I hope there's a way to expand it again, thank you!

**Comment by VForest** [comment]
Hi, you can expand/collapse the left sidebar using the arrow at the top. I'm not sure if you're looking for more than that though. Let me know.
![image](https://user-images.githubusercontent.com/79280741/182727993-0eed567a-441d-4888-8293-a1ce66ee56cb.png)

**Comment by gitHu6-newb** [comment]
Ah, thanks. It turns out the arrow got hidden and the panel shrunken to the compact size when screen space becomes an issue from my reduced resolution. It returned to normal when I zoomed out enough.
