### ISSUE TITLE
Thousand Console Errors and this affects Twitch playback

### ISSUE THREAD

**Issue by tntc4** [night/betterttv#5558]
This has started months ago, and i decide to disable BTTV chrome extension for a while.
But I want it back, so I try to enable it after last update - still see thousand error per second in browser console and this cause twitch to stuter playback video.
See screenshot I have attached.
I am using Chrome 70.0.3538.77, Windows 7, BetterTTV 7.4.33

![Screenshot_1](https://user-images.githubusercontent.com/3246834/182834766-e11b5ee0-bcb2-43bb-bcb6-7c52392515a2.png)

**Comment by night** [comment]
Your version of Chrome is likely much too old. You may need to try upgrading to a newer version of Chrome.
