### ISSUE TITLE
Chat Layout Left Not Working Properly

### ISSUE THREAD

**Issue by CuddlySpartan** [night/betterttv#5560]
Steps to Reproduce: In BTTV Settings go to Chat Settings -> Chat Layout and select Left.

Expected Behavior: Chat and Followed Channels switch positions (Chat left side, Followed Channels right side)

Actual Behavior: Followed Channels and Chat are both on left side. Going to Theatre mode or hiding chat/followed channels will cause errors where parts of the stream video player are cut off/covered by other elements. 

I've done hard refresh/cache reload (ctrl + f5, shift + f5), uninstalled bttv and reinstalled, and used 3 different browsers (Chrome, Firefox, and Opera GX) and same issue is on all 3.

![image](https://user-images.githubusercontent.com/36866138/182953226-89e7e73d-3d55-4cc0-954e-46d3e119fed3.png)

**Comment by pdeblois** [comment]
Can confirm I am also having the same issue, I can't put channels on the right anymore.

**Comment by zHOw** [comment]
+1 on this #LeftChattersMatters

**Comment by night** [comment]
<img width="145" alt="image" src="https://user-images.githubusercontent.com/2942184/182968906-4bfb7417-45b1-4a7d-add7-0e35b0f8f711.png">

It looks like Twitch pushed a site update which is wrapping their left column with an empty div, which is why this has broken in this way.
