### ISSUE TITLE
Followed / Recommended Channel Bar Not Going Away in Theater Mode on Opera GX with Chat on Left Side

### ISSUE THREAD

**Issue by Blubehriluv** [night/betterttv#5562]
When you have the chat on the left side of the screen it is covering some of the video player.  This is because the followed channels bar on the side is minimized, but still open when it shouldn't be because the site is in theater mode.  The only way to get rid of it is to collapse chat, which also gets rid of the featured channels.  Normally chat can be open in theater mode with nothing beside it.  Swapping the chat from left to right makes the issue go away, but once you switch it back to left the live channels sidebar reappears again.

Using: Latest version of Opera GX, couldn't find the version number.

**Comment by MartiNeo** [comment]
I have the same issue on Windows using latest Google Chrome, BTTV 7.4.33

**Comment by WatchfulSeal** [comment]
Same Issue on Windows 10 using latest Firefox and BBTW

**Comment by trued02** [comment]
Same issue here. With Chat on the left side it no longer moves the "following/recommended" bar to the right as it had done before.. https://imgur.com/a/Nk9e2CT
Chrome Version 104.0.5112.81
BTTV version Version 7.4.33

**Comment by LuanContarin** [comment]
Same issue, Windows 10 with latest BTTV and Brave browser (Chromium 104.0.5112.81). Also, when in theater mode the stream/VoD gets cutted on the left side
![image](https://user-images.githubusercontent.com/57299032/183993047-ed45be4f-af17-4ce5-aa58-e84aa9720945.png)
Actually the bug happens when you enter the stream for the first time, if you refresh the site (F5) it works just fine

**Comment by night** [comment]
I am not able to still reproduce this. If you're still having issues, please let us know.

**Comment by Blubehriluv** [comment]
This hasn't been an issue for me lately (but since I've had this issue, I've reset my computer and reinstalled OperaGX and BTTV).  Maybe reinstalling will help you all.  Must be fixed now, thanks.
