### ISSUE TITLE
Chat not reversed but added to the left.

### ISSUE THREAD

**Issue by nex-hit** [night/betterttv#5563]
Chat is not reversed its added to the left.
Channel tab is still on the left... 😑

Enjoying that switch fonction cause it balances my neck issues...

**Comment by kevinbbbb** [comment]
I noticed this too. There is a further problem with cinema mode when both, channel tab and chat, being on the left side. The channel tab doesn't get minimized automatically but instead the video gets cut on the sides to fit all of the free space.

**Comment by afleece** [comment]
I have exactly the same problem, when you move the chat to the left, the subscriptions are not moved to the right side, as it was before [click](https://imgur.com/a/432l6OG)

**Comment by nex-hit** [comment]
Well on the good notes, its positive that multiple person got the same issue, means mostly its not user-specification related.
Wait and see.
Using firefox, fresh reinstall of the nav did nothing.

**Comment by Yougoshatenshi** [comment]
its been fixed with 7.4.35. See https://github.com/night/betterttv/issues/5560
in Firefox the update is already available. In Chrome its still 7.4.33 but mostly takes longer.

**Comment by nex-hit** [comment]
YES TY, I just noticed that ! 👌
it really helps with disability
