### ISSUE TITLE
Timeout Options missing at modcard

### ISSUE THREAD

**Issue by Lpz3nc** [night/betterttv#5566]
still not visible
Chrome Version 104.0.5112.81
BTTV Version 7.4.35

_Originally posted by @Lpz3nc in https://github.com/night/betterttv/issues/5540#issuecomment-1204366768_

**Comment by Dragoonseal** [comment]
It took a few days from when the fix for #5540 was pushed for it to work for me, but it has fixed the issue for me. Weird that it isn't working for you, I'm on the exact same versions. Maybe different Twitch versions? They do roll out changes in waves sometimes.

Chrome Version 104.0.5112.81 (Official Build) (64-bit)
BTTV Version 7.4.35

**Comment by candybomberz** [comment]
For me it never started working.

Chrome Version 104.0.5112.102 (Offizieller Build) (64-Bit)
BTTV Version 7.4.35

deleted twitch cookies,
deleted bttv and reinstalled,

this is what the box where the buttons are looks like in my browser code

`<div class="Layout-sc-nxg1ff-0 KYZGA"><div class="Layout-sc-nxg1ff-0 aleoz"><div class="InjectLayout-sc-588ddc-0 ktQueN viewer-card-drag-cancel"><div class="Layout-sc-nxg1ff-0 dUJHvk"><div class="Layout-sc-nxg1ff-0 cwkNSa"><div class="InjectLayout-sc-588ddc-0 ktQueN"><button class="ScCoreButton-sc-1qn4ixc-0 ffyxRu ScButtonIcon-sc-o7ndmn-0 nHKTN" aria-label="FatedToFail sperren"><div class="ButtonIconFigure-sc-1ttmz5m-0 fbCCvx"><div class="ScIconLayout-sc-1bgeryd-0 cXxJjc"><div class="ScAspectRatio-sc-1sw3lwy-1 kPofwJ tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 dsswUS"></div><svg width="100%" height="100%" version="1.1" viewBox="0 0 20 20" x="0px" y="0px" class="ScIconSVG-sc-1bgeryd-1 ifdSJl"><g><path fill-rule="evenodd" d="M2 10a8 8 0 1116 0 8 8 0 01-16 0zm8 6a6 6 0 01-4.904-9.458l8.362 8.362A5.972 5.972 0 0110 16zm4.878-2.505a6 6 0 00-8.372-8.372l8.372 8.372z" clip-rule="evenodd"></path></g></svg></div></div></div></button></div></div><div class="Layout-sc-nxg1ff-0 cwkNSa"><div class="InjectLayout-sc-588ddc-0 ktQueN"><button class="ScCoreButton-sc-1qn4ixc-0 ffyxRu ScButtonIcon-sc-o7ndmn-0 nHKTN" aria-label="FatedToFail in Time-Out versetzen"><div class="ButtonIconFigure-sc-1ttmz5m-0 fbCCvx"><div class="ScIconLayout-sc-1bgeryd-0 cXxJjc"><div class="ScAspectRatio-sc-1sw3lwy-1 kPofwJ tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 dsswUS"></div><svg width="100%" height="100%" version="1.1" viewBox="0 0 20 20" x="0px" y="0px" class="ScIconSVG-sc-1bgeryd-1 ifdSJl"><g><path d="M11 9.586V6H9v4.414l2.293 2.293 1.414-1.414L11 9.586z"></path><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-2 0a6 6 0 11-12 0 6 6 0 0112 0z" clip-rule="evenodd"></path></g></svg></div></div></div></button></div></div></div></div></div></div>`

**Comment by candybomberz** [comment]
Ok I just switched to english in twitch language,
and that seems to have made it work again.

**Comment by candybomberz** [comment]
So the aria label selector from the fix is language dependand and thus fails for any non english twitch language.

**Comment by Lpz3nc** [comment]
yes its a language problem thx you for the tip

**Comment by candybomberz** [comment]
I'm not sure if bttv mod functionality actually ever worked in different languages.

I remember having to change language in the past once. But only when you get a new PC or clean your cookies obviously.

**Comment by Lpz3nc** [comment]
it was working for me in german before twitch changed something :D so i hope for a fix
