### ISSUE TITLE
 Emotes won't autocomplete with tab after timeout (or !vanish command). 

### ISSUE THREAD

**Issue by TribleF** [night/betterttv#5568]
I noticed that as well as the others in the stream chat... t gets pretty annoying especially if you use !v often. You have to reload the page before you can tab emotes again.

**Comment by Dragoonseal** [comment]
I'm having tab autocomplete breaking sometimes too, for a different reason. Sometimes when first opening a channel tab autocomplete just doesn't work for an unknown reason, a refresh will fix it. It happens more often if I leave a channel open in a tab when I close the browser and shut down the PC for the night. The next morning that tab will always need a refresh to get tab autocomplete working again.

**Comment by night** [comment]
It might be due to the chat input box getting re-rendered. Do you have exact reproduction steps we can use to test this out?

**Comment by TribleF** [comment]
I mean you just have to enter a chat in any stream, then get timeouted or banned for a few seconds (also works with !v / !vanish many chats have !vanish command which timeouts you for a second to delete your last messages ).
After that try using any emote, for me and some friends it won't be possible to tab those emotes so you have to refresh the page or use emote menu
