### ISSUE TITLE
Feature Update Request: Auto Play -> DISABLE Front-page Player (now with steps)

### ISSUE THREAD

**Issue by sydmarf** [night/betterttv#5569]
Disabled Front-page Player doesn't stay disabled as demonstrated in the following Test Case scenario.

Test Case prepared in:
Windows 10 Pro 64-bit; Version 21H2 (OS Build 19044.1826)

Google Chrome; Version 104.0.5112.81 (Official Build) (64-bit); Incognito Mode
Extensions active: The one and only BetterTTV 7.4.35

The list of reproducible steps as follows:

Step 0-a: [https://i.imgur.com/xA4O9Ga.png](https://i.imgur.com/xA4O9Ga.png)
Step 0-b: [https://i.imgur.com/6qkrmPj.png](https://i.imgur.com/6qkrmPj.png)

Step 1: [https://i.imgur.com/1MpKAsR.png](https://i.imgur.com/1MpKAsR.png)

Step 2: [https://i.imgur.com/rWTmf7U.png](https://i.imgur.com/rWTmf7U.png)

Step 3: [https://i.imgur.com/mQhddoZ.png](https://i.imgur.com/mQhddoZ.png)

Step 4: [https://i.imgur.com/EkqFNDK.png](https://i.imgur.com/EkqFNDK.png)

Step 5: [https://i.imgur.com/nEQlCDm.png](https://i.imgur.com/nEQlCDm.png)

Step 6: [https://i.imgur.com/DGpJIlE.png](https://i.imgur.com/DGpJIlE.png)

Step 7: [https://i.imgur.com/WFZ5C4O.png](https://i.imgur.com/WFZ5C4O.png)

Step 8: [https://i.imgur.com/QBqyWvQ.png](https://i.imgur.com/QBqyWvQ.png)

Step 9: [https://i.imgur.com/8WTKp79.png](https://i.imgur.com/8WTKp79.png)

Step 10: [https://i.imgur.com/k4lBdT8.png](https://i.imgur.com/k4lBdT8.png)

Step 11: [https://i.imgur.com/16R8CCR.png](https://i.imgur.com/16R8CCR.png)

Step 12: [https://i.imgur.com/CdVi35a.png](https://i.imgur.com/CdVi35a.png)

In case, any of the steps don't match with that on the devs' end, it is recommended to go back to Step 1 and then continue from there.

I've been experiencing this behavior for a long time and only recently decided to make a report.

Thanks in advance. <3

**Comment by night** [comment]
This is a tricky issue to solve because we are not able to detect *why* the video started playing, and due to that we can't be sure of the intent of the video play. To prevent the possibility of breaking the play action, I don't think we can/should fix this.
