### ISSUE TITLE
Emotes not working?

### ISSUE THREAD

**Issue by MrPopo98** [night/BetterTTV#557]
when i was on twitch yesterday all of the bttv emotes were working perfectly fine but when i went on today they weren't working i did not change any settings and i have tried refreshing the page and turning the browser (chrome) off and back on and still didn't work. thank you for reading and sorry if i am just repeating what other people are saying if they are.

**Comment by night** [comment]
You need to enable GIF emotes in the BetterTTV settings if you wish to see GIFs in chat.
