### ISSUE TITLE
Directory Settings: Useless/Bugged Features

### ISSUE THREAD

**Issue by ChopstickPhilly** [night/betterttv#5575]
i've noticed that for a while many of the directory settings (at least on my end) don't work properly or have no purpose of still being there. More specifically:

- "Useless" features: Friends List, Recommended Friends (after sunset of Friends function on Twitch)

- Bugged features: Features Channels (no effect when disabled) , Auto-Expand channels (no effect when enabled)

only feature that seems to work properly (again, on my end, let me know if this is something specific to me or not) is Offline Followed Channels

**Comment by kilroy98** [comment]
@night "Featured Channels" and "Auto-Expand Channels" still not work for me,
Browser - Chrome 107.0.5304.88, BetterTTV Extension updated to latest version (7.4.40).
