### ISSUE TITLE
Red Buttons!

### ISSUE THREAD

**Issue by RetroGameMonkey** [night/BetterTTV#558]
In addition to Blue buttons, Red buttons would look really good with the dark theme!

**Comment by night** [comment]
At this time we aren't interested in adding another color. We might eventually let users choose their own, but for now you can use an extension like Stylish to accomplish this in the meantime: https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en
