### ISSUE TITLE
BTTV changes streamer's username in chat to a " symbol.

### ISSUE THREAD

**Issue by 111100001** [night/betterttv#5584]
when i disable BTTV, the username comes back. i don't think there is any conflicting extensions bc i disabled all the other extensions except BTTV and the issue still persists. BTTV in incognito mode works fine without any issues along with the same extensions it was enabled with.

**Comment by night** [comment]
Can you share more information, like the specific stream encountering this issue?

**Comment by 111100001** [comment]
it is fixed, i don't know what i did.
