### ISSUE TITLE
Bonus Channel Points

### ISSUE THREAD

**Issue by Raquel061119** [night/betterttv#5592]
since i have installed Betterttv my button to bonus points desapeard. and i have never recived +50 points because, there is no button. it makes 3 days now. i have re-instaled betterttv, unistalled, everything, and its not a twitch issue, because i already contac them. i dont want to create a new account because im paying the streamer i watch and have a 4 month streak.
hope this can be solved. im not the first person talking about this.

**Comment by ahtee** [comment]
make sure that betterttv auto-claim bonus channel points setting is checked then

**Comment by night** [comment]
You may want to review your settings for Channel Points in the BetterTTV settings window. If you have them disabled, you will not see the UI for channel points. If you have auto-claim enabled, you won't see the bonus popup as it claims them for you.
