### ISSUE TITLE
BetterTTV Pro feauture

### ISSUE THREAD

**Issue by Yasar92** [night/betterttv#5599]
Hello,

I wonder why I cant personalize GIFs as personal Emote to use everyhwere on Twitch, this feature would mean a lot to me, since I as of today am not affiliated with Twitch anymore and want my community to be able to use my "Subscriber Emotes" from before also in other Chats, as they did it a lot. Is it maybe possible to change that?

Thank you and kind regards

**Comment by night** [comment]
Thanks for the request. We actually launched BetterTTV Pro with GIF emote support, but due to abuse we quickly decided static images were safer and have left it that way since. We may revisit it down the road, but for the moment we have no current plans to change this.
