### ISSUE TITLE
Disable chat text box when using anon chat

### ISSUE THREAD

**Issue by bottleblue** [night/betterttv#5600]
When using anon chat anything you type won't go through because you're not connected to chat. If you disable anon chat and then type the same thing you get a duplicate message error which stops you from typing the same thing in the last 30 secs. 

This has screwed me over a few times when there's been a giveaway keyword in chat. I'll forget that I had anon chat enabled. I type the word. It says I'm not connected to chat. I disable anon chat and retype the word but it's timed out for 30 secs and the giveaway ends.

Can you have BTTV prevent you from typing anything in the text box when anon chat is enabled?

**Comment by night** [comment]
Thanks for the feedback. Because you need to be able to type in chat to exit anon chat, we are not able to disable the chat input box.
