### ISSUE TITLE
Some CSS bugs

### ISSUE THREAD

**Issue by Sleekness** [night/BetterTTV#561]
1. On profile page with dark theme this little box next to follow button is not darkened (http://i.imgur.com/mWLSq4e.png)

2. In settings > connections these social media boxes are kind of not darkened fully (http://i.imgur.com/YqHmSa1.png)

3. How about adding blue hover over for when you search a game as a part of 'Blue buttons' option? (http://i.imgur.com/Se0VHeL.png)

4. The emote box on dark theme in theater mode is blue-ish (http://i.imgur.com/Zqr8n5N.png). How about making it the same color as bttv dark theme, like it is when you're not in theater mode? (http://i.imgur.com/QuHbnGM.png). Aswell as making words 'Channel' and 'All' white or grey-ish color instead of purple, like it is when you're not in theater mode..

5. When clicked on user in Viewer List, the follow button should be blue color as a part of 
'Blue buttons' option and 'Message' should be white instead or purple (http://i.imgur.com/lzHszHM.png)

6. When you go to settings page and close the left sidebar the following count shows up on the logo, instead of showing up next to the following page icon. (http://i.imgur.com/wPCCtcK.png)

7. When chat room has any mode set (slow, sub, r9k) the 'Invite a User' button in the group chat is bugged. (http://i.imgur.com/NxrafAw.png)

8. Typo in the setting Disable Whispers. 'Functionalitiy' should be 'Functionality' and 'Recieve' should be 'Receive'. (http://i.imgur.com/WpR77Bo.png)

9. In Twitch Partner Merch box the bottom sentence is bugged and under the green bar. (http://i.imgur.com/hK7vlzg.png)

10. And lastly.. How about as a part of dark theme, making the borders around game boxes dark instead of white? I'm almost positive that BTTV had that some time ago, but then Twitch changed it and it was never darkened on BTTV again. (http://i.imgur.com/tEzusjM.png)

**Comment by night** [comment]
For number 4, this is too much to maintain. Twitch applies a blanket dark theater CSS to chat in theater mode, which we overwrite as much as possible.

**Comment by Sleekness** [comment]
I think you might've missed 7, because that issue still persists, at least for me. 

And you forgot to change 'Message' on mod card in Theater Mode to white instead of purple, it's fine when out of theater mode. (http://i.imgur.com/7CRixFG.png)

As well you forgot to change, that when you follow someone on mod card it would have Blue color heart icon instead of green, like it is on channel page. (http://i.imgur.com/Bdyr7N8.png)

Furthermore, you might think i'm crazy, but the buttons' "boxes" on DarkenTTV underneath the video player aren't quite aligned. In particular 'Subscribe' and 'Theater Mode' buttons seems to be just a litle be bigger or more stretched to bottom. And also under the 99 digits in subscribe button there is some weird little symbol.. (http://i.imgur.com/RRw60y5.png)

One more suggestion.. How about making this white line on DarkenTTV in the following sidebar, the same dark color as the bottom one? Idk, it looks really annoying and I just cant stand that it's white color. ;_; (http://i.imgur.com/LicMeAr.png)
