### ISSUE TITLE
Hype Train is covering the X to close a mention

### ISSUE THREAD

**Issue by hiccups1980** [night/betterttv#5613]
Hi,

Hype Train is covering the X to close a mention.

![Screenshot 2022-09-10 203420](https://user-images.githubusercontent.com/5673109/189497148-55e56bb5-aaae-4c9a-9082-722b25a3d347.jpg)

The X to close the mention is under the hypetrain thingy. Would be nice if that could be fixed. Thanks.

**Comment by night** [comment]
duplicate of #4710
