### ISSUE TITLE
Feature Request - Indicator and maybe a filter option for dashboard “Personal Emotes” in channel “Emotes” gallery.

### ISSUE THREAD

**Issue by Never-Idle** [night/betterttv#5616]
Feature Request - Indicator and maybe a filter option for dashboard “Personal Emotes” in channel “Emotes” gallery.
``This would make it so much easier to select what uploaded channel emotes can be used as "Personal Emotes"; or already in-use personal use...``

Nutshell...
1. In one's main dashboard "Emotes" gallery, It would ideal to see a small icon / indicator of what emotes are already being used as "Personal Emotes".
2. An option to also filter out one's dashboard channel "Emotes"; down to those that can actually be used as personal emotes would be a nice perk.

Something along those lines...

**Comment by night** [comment]
Thanks for the request. We've added an indicator on emotes which you've added as a personal emote in your Dashboard, and added the ability to filter what is shown. To make searching for emotes easier, you're now also able to filter by personal emotes when searching in the shared emote search.
