### ISSUE TITLE
Chat messages

### ISSUE THREAD

**Issue by iZeqq** [night/BetterTTV#563]
Hi, whenever I send a message, the message is sent but the text stay in the wrinting box

![](http://i.imgur.com/vXc9o5S.png)

**Comment by voloshink** [comment]
are there any errors in the console?

**Comment by iZeqq** [comment]
Where can I check it?

**Comment by voloshink** [comment]
If you're on chrome you can press f12

**Comment by iZeqq** [comment]
Ow, nevermind, it appears that it was only doing that on one chat, tried in mine and in another, it work fine, thank's anyway !

**Comment by voloshink** [comment]
If you ever encounter the error again check the log and include the errors you get.

**Comment by iZeqq** [comment]
Alright ! Thanks

**Comment by night** [comment]
This was just a small bug that was overlooked and fixed by https://github.com/night/BetterTTV/commit/b7f3642e614f65bfe9125723ef56ecb1ecca5781 last night, which is why refreshing fixed it.
