### ISSUE TITLE
Nickname readability is questionable - there is an easy solution

### ISSUE THREAD

**Issue by pbaykalov** [night/betterttv#5641]
There are quite a lot of people complaining about readability of nicknames:
https://github.com/night/betterttv/issues/3320

I share same this opinion: BTTV does not make dark and/or saturated nicknames readable as evidenced by these screenshots. There are also some black nicknames which makes them totally unreadable with BTTV installed.

1) BTTV "readable" option enabled and Twitch "readable" option enabled
![1 bttv readable twitch readable](https://user-images.githubusercontent.com/54845956/192097469-0ea3890c-6af9-4511-89ef-432e66ba7169.png)

BTTV's nickname handling overrides Twitch' nickname rendering which is vastly better for dark and/or saturated nicknames:
2) Twitch' readable option reenabled: if I toggle Twitch' own fearture off and on again it works as intended. Therefore, BTTV overrides the perfectly good feature.
![2 twitch readable reenabled](https://user-images.githubusercontent.com/54845956/192097472-900fdb79-418d-4408-b626-bfaa45ffc2a0.png)

Unfortunately, there is no BTTV setting to not override the Twitch nickname colouring.
3) BTTV "readable" off,  Twitch' "readable" on - same suboptimal handling of nicknames
![3 bttv readable off twitch readable](https://user-images.githubusercontent.com/54845956/192097473-2eb3b0c4-f4f9-4637-aee2-a14616e3a265.png)

4) Twitch' "readable" reenabled - same improvement as when reeenabling the option earlier.
![4 twitch readable reenabled](https://user-images.githubusercontent.com/54845956/192097475-c46dc258-d9da-4f1f-b607-9575d2544491.png)

There is an easy fix: if BTTV does not want to replace the color, it should not. I expect that this will allow Twitch' own feature to work well.
https://github.com/pbaykalov/betterttv/commit/87b1a401de0b752a97feeda7de8d0af1aa339903

For users who want to work around the BTTV's bad nickname color handling there is a workaround which will disable several chat functions -- a userscript:

```
// ==UserScript==
// @name         BetterTTV Development
// @description  Enhances Twitch with new features, emotes, and more.
// @namespace    http://betterttv.com/
// @copyright    NightDev, LLC
// @icon         https://cdn.betterttv.net/assets/logos/bttv_logo.png
// @version      0.0.1
// @match        https://*.twitch.tv/*
// @grant        none
// ==/UserScript==

(function betterttv() {
    Element.prototype.__bttvParsed=true
})()
```

**Comment by night** [comment]
There's literally a setting for this already:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/2942184/192105255-99c60234-6c7f-4a34-9921-179b12328993.png">

**Comment by pbaykalov** [comment]
> There's literally a setting for this already:

Setting "readable colors" does not prevent dark and oversaturated nicknames from appearing as evidenced by my screenshots. I have no idea what are you talking about.

**Comment by pbaykalov** [comment]
First screenshot from the issue:


![image](https://user-images.githubusercontent.com/54845956/192105431-609b376b-e512-4a01-aa06-6da60a3329ad.png)

**Comment by pbaykalov** [comment]
much readable

![image](https://user-images.githubusercontent.com/54845956/192105542-538a7b69-59dd-485f-bba7-d385081eef42.png)

**Comment by pbaykalov** [comment]
> There's literally a setting for this already:

![image](https://user-images.githubusercontent.com/54845956/192105969-383ebfdc-c1e7-4d15-8db4-c3544d313345.png)

Too bad it does not work as intended because there is race condition between BTTV and Twitch overwriting the color.
