### ISSUE TITLE
Bug report: no combination of BTTV/Twitch settings prevents unreadable nickname colours

### ISSUE THREAD

**Issue by pbaykalov** [night/betterttv#5642]
No combination of BTTV/Twitch settings prevents unreadable nickname colours no matter how hard I try.

OS: Windows 10 21H1
Browser: Firefox 104.0 64 bit

BTTV settings:
![image](https://user-images.githubusercontent.com/54845956/192142824-b43c90f5-cd63-436a-8bc7-b6a24d817ab4.png)

Twitch settings:
![image](https://user-images.githubusercontent.com/54845956/192142843-0425536d-fad4-48e8-abf3-c41a61720329.png)

BTTV version is on the left, nicknames are dark and saturated. If you uninstall BTTV you will have rendering as displayed on the right picture: nicknames are light and easy to read.

![image](https://user-images.githubusercontent.com/54845956/192161854-e1388f5a-5cf6-4965-add8-beb40257f01d.png)

**Comment by pbaykalov** [comment]
So the culprit of the problem is:
1) "Dark mode" disabled in Twitch menu on top right:
![image](https://user-images.githubusercontent.com/54845956/193093827-51c65116-5455-433a-8e54-1cc226bda2ef.png)
2) Theater mode engaged.

BTTV incorrectly calculates the replacement color because it does not check whether Theater mode is engaged. However, if I turn Dark mode in Twitch menu before engaging Theater mode, BTTV calculates the replacement colour correctly.

**Comment by night** [comment]
this is already fixed via 8067c4dd78584366656f618d9decdcf9db9cd107

**Comment by pbaykalov** [comment]
> this is already fixed via [8067c4d](https://github.com/night/betterttv/commit/8067c4dd78584366656f618d9decdcf9db9cd107)

Works quite well but sometimes I do not get the correct nickname colours until I F5.
