### ISSUE TITLE
More information on mod cards

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#565]
Include more information on the mod cards. I made an extension for myself that crudely adds some information to a mod card. 

#### Example
Shows follower count, views, viewers (would show count if live but didn't add anything to remove this when offline), time since the account was created, and how many channels they are following. I use this information to help determine a troll/bot account.
![Example](http://i.imgur.com/abvv3Pq.png) ![Example 2](http://i.imgur.com/YdTD5bc.png) ![Example 3](http://i.imgur.com/PJLtZs0.png)
BetterTTV's update changed something and now it's kind of over my implementation.

**Comment by conceptionals** [comment]
Honestly I'm not a fan of adding all of this extra information to the Mod cards. [Taking a look](http://gyazo.com/12168a19bfe55e63679616c47e062ce5) at the mod cards now, they already take up a good portion of the chat, and this increases even more once you click to see the user's previous messages. Having all this extra information (and based off of your screenshot you've provided) just makes the Mod cards look really messy. Who really cares how many total followers and total channel views someone has, seriously, this is just really unnecessary/unneeded/etc. And for the part that shows how many viewers they have if live, I think this is also unnecessary to an extent. Yes it could be useful to know if someone is live, but there are better more subtle ways of doing this:

![liveex1](https://cloud.githubusercontent.com/assets/13137308/8728845/1a7dd71c-2bad-11e5-8ef7-202199910717.png) ![liveex2](https://cloud.githubusercontent.com/assets/13137308/8728849/22164fe0-2bad-11e5-9f53-49819cb4c3ed.png)


Now those are not perfect, but I do think they look a lot better than just having another *button* added to the Mod card to know if someone is live and how many viewers.

**Comment by night** [comment]
We are already adding this information to mod cards (see #516).
