### ISSUE TITLE
Feature Request - Chat message counter

### ISSUE THREAD

**Issue by bondomthebest** [night/betterttv#5650]
Please add a feature so that BetterTTV can show the number of messages you have sent in a chat with a specific streamer. Moderators on channels have such a function, but ordinary users do not have such a function =( I would be very grateful if you add such a function!

**Comment by night** [comment]
Thanks for the request. Unfortunately we are not able to know the exact totals you have sent in chat, as we do not log or monitor chat being sent on Twitch. Even if we did count messages you send on your current client, that would not account for other clients or mobile.
