### ISSUE TITLE
Feature Request - Bring back glowing chat names

### ISSUE THREAD

**Issue by Degree234** [night/betterttv#5651]
I saw somebody in a chat that had a glowing name and I REALLY want one! Doing some research I found out that it used to be a thing on BTTV but was removed, but if you had it turned on when it was removed it stayed applied for you. Can we get that back please?

**Comment by night** [comment]
Thanks for the request. Your research may be inaccurate. This was a feature for a select number of original subscribers to the product, but is not something we offer to new subscribers at this time. We have no current plans to offer this feature en masse.
