### ISSUE TITLE
Feature Request: Hide Elevated Chat from view

### ISSUE THREAD

**Issue by dclstn** [night/betterttv#5661]
Twitch has added a new feature called [elevated chat](https://help.twitch.tv/s/article/elevated-chat?language=en_US&). For a period of up to five minutes, a banner will appear above chat or below the video player showcasing a message. I am opening this issue in order to gather a general consensus regarding this non-toggleable feature.

**Comment by night** [comment]
Since this was a 4 week experiment, we have no current plans to build a feature for hiding this. If Twitch ends up shipping this more broadly, we can explore adding a setting then.
