### ISSUE TITLE
[BUG] Opening the "Set Font" menu pauses the stream

### ISSUE THREAD

**Issue by EdVraz** [night/betterttv#5664]
When I open the menu the stream gets paused after 2-10 seconds of having the input field opened and resumes after submitting the information. 

If you need me to provide any additional information tell me :)

**Comment by night** [comment]
Thanks for the report. This is actually not a bug, and is a result of how native `alert`s work in browsers. We may change how we prompt for this input in the future, but for now it is working as intended.
