### ISSUE TITLE
Feature Request: Pause chat when reveiving a mention/reply

### ISSUE THREAD

**Issue by EdVraz** [night/betterttv#5665]
In streams with a lot of viewers (like 2k+), it can get tough to keep track of conversations/own messages. If you look away from the chat you might not see a useful reply to a message that you sent before. Therefore it would be nice to have an opt-in function that interrupts the chat scrolling when a reply is received, so you get a chance to read and eventually reply again.

It would also solve the problem of having to scroll back when seeing a mention but it disappearing again due to chat speed.

**Comment by night** [comment]
I would recommend enabling `Pinned Highlights` in the BetterTTV Settings, which will attach highlighted messages to the top of the window for you.
