### ISSUE TITLE
Feature Request: Add options to hide view counts and/or partner badges

### ISSUE THREAD

**Issue by RocketHog55** [night/betterttv#5667]
I've heard streamers sometimes mention that seeing the view count on screen all the time can lead to them comparing themselves to others and generally having less fun. As a viewer I don't really care about view count (or partner badges) either, so I've made a CSS userstyle for Twitch that hides them.

https://userstyles.world/style/4430/twitch-hide-view-counts-and-partner-badges

You can add this style to BTTV as options for hiding view counts or partner badges if you want.

**Comment by night** [comment]
Thanks for the request. BetterTTV tends to try and enable tweaks that many folks may benefit from. I think a feature like this may best be solved by a custom user style (like already linked).

**Comment by RocketHog55** [comment]
Thank you, I understand, though I'll note that [Altair.tv](https://web.archive.org/web/20220217050551/https://altair.tv/), before it ran out of money, was going to hide view counts by default and not have a partner program, which is where I got the idea for this userstyle from.

**Comment by RocketHog55** [comment]
FYI, I have now actually suggested this style to a few streamers and separated the hide partner badge option to a separate style, and it has now reached over 200 installs. I reuploaded it here: https://userstyles.world/style/7096/twitch-hide-view-counts-and-follower-counts
