### ISSUE TITLE
link highlight 

### ISSUE THREAD

**Issue by voltmasterc** [night/BetterTTV#567]
as a twitch mod it is very impotent to catch links and web url's in chat and smash them into little bits this would be a lot easier if there was a setting to atomically highlight them

**Comment by night** [comment]
Honestly, if you want this much control you should get a chat bot to timeout all links, and then have moderators permit links manually. This way you have better control over the content of the chat, as bots will instantly timeout all potentially bad links.

**Comment by voltmasterc** [comment]
But what if nightbot is already in that chat if I make nightbot join will
that one work for me or will the one already in the room just kick mine out
