### ISSUE TITLE
I can't see OMEGALUL emotes on Twitch

### ISSUE THREAD

**Issue by Aolzarin** [night/betterttv#5678]
Hi,

I have betterTV but I can't see OMEGALUL emotes on XQC Channel.. i've seen these emotes before. 

I need help....
![1](https://user-images.githubusercontent.com/115508290/194959467-c8beacd0-70a2-4ca7-94a5-cfa50513f2da.png)
![2](https://user-images.githubusercontent.com/115508290/194959469-64a6dc1c-af08-4179-ac35-35529e195416.png)

**Comment by lazybunnyisdead** [comment]
Having the same exact problem :/

**Comment by dclstn** [comment]
You may be seeing emotes which are not on BetterTTV.

**Comment by Aolzarin** [comment]
> You may be seeing emotes which are not on BetterTTV.

The OMEGALUL expression is present in BETTERTV, while it could have been seen before, it is no longer visible. (sorry my bad eng.)

**Comment by night** [comment]
What browser version and extension version are you on? Have you tried disabling any other browser extensions you use?

**Comment by Aolzarin** [comment]
Chrome : 106.0.5249.103 (Resmi Derleme) (64 bit) Version

BetterTV: 7.4.40 Version

**Comment by night** [comment]
What channel are you experiencing this issue in?

**Comment by Aolzarin** [comment]
I live on the XQC Channel on Twitch. This emote appeared on his channel before.

**Comment by night** [comment]
That emote is not listed as a channel emote at https://betterttv.com/channels/xqc Broadcasters and their editors are able to add and remove emotes at their own discretion. You would have to take it up with the broadcaster or their editors.

**Comment by Aolzarin** [comment]
ohh, thanks for letting me know. I did not know that.
