### ISSUE TITLE
Deleted messages are no longer showing

### ISSUE THREAD

**Issue by whatever-forever** [night/betterttv#5682]
No longer showing deleted messages. Will just show _"message deleted by a moderator"_

Edit: So it seems like if just the message is deleted it shows _"message deleted by a moderator,"_ but if someone is timed out or banned, the message is just greyed out as usual.

**Comment by whatever-forever** [comment]
This issue seemed like it was fixed, but just started occurring again..

**Comment by night** [comment]
We haven't yet shipped the fix just yet. It will be in the next release.

**Comment by whatever-forever** [comment]
Ah, okay! Thanks! :)
