### ISSUE TITLE
Bug: Chat message input field permanently disappears after typing ":" followed by a letter for the pop up tab emote list.

### ISSUE THREAD

**Issue by tunacanman** [night/betterttv#5684]
Every once in a while when I use the ":" to see the list of tabable emotes, as soon as I type the first letter, ":v", the entire chat box crashes/disappears. Only the chat remains on the right side of the screen. I must refresh in order to chat again. If I type the same thing, after refresh, it will happen again. If I type a different letter(after the colon), it works and then I can type the bad letter without issue. It's only happened a handful of times, so that's all I know so far. I also use FFZ and 7TV.

logs (idk if the first 5 lines are relevant):
​
```
Image (async)
t @ core-e826ce135798cb65bca6.js:1
t @ core-e826ce135798cb65bca6.js:1
newEvent @ core-e826ce135798cb65bca6.js:1
t @ core-e826ce135798cb65bca6.js:1
o @ betterttv.js:118
betterttv.js:118 TypeError: Cannot read properties of undefined (reading 'key')
    at twitch.js:103:59537
    at Array.forEach (<anonymous>)
    at t.getMatches (twitch.js:103:59495)
    at n.getMatches (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1:392041)
    at n.<anonymous> (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1:391091)
    at vi (vendor-1cbe7bc148d476644ff8.js:1:857240)
    at us (vendor-1cbe7bc148d476644ff8.js:1:892203)
    at wu (vendor-1cbe7bc148d476644ff8.js:1:909632)
    at t.unstable_runWithPriority (vendor-1cbe7bc148d476644ff8.js:1:929103)
    at Go (vendor-1cbe7bc148d476644ff8.js:1:853710)
    at bu (vendor-1cbe7bc148d476644ff8.js:1:906298)
    at au (vendor-1cbe7bc148d476644ff8.js:1:902452)
    at vendor-1cbe7bc148d476644ff8.js:1:854001
    at t.unstable_runWithPriority (vendor-1cbe7bc148d476644ff8.js:1:929103)
    at Go (vendor-1cbe7bc148d476644ff8.js:1:853710)
    at Yo (vendor-1cbe7bc148d476644ff8.js:1:853946)
    at Zo (vendor-1cbe7bc148d476644ff8.js:1:853881)
    at tu (vendor-1cbe7bc148d476644ff8.js:1:899038)
    at Object.enqueueSetState (vendor-1cbe7bc148d476644ff8.js:1:857666)
    at w.setState (vendor-1cbe7bc148d476644ff8.js:1:1020116)
    at n.onEditableValueUpdate (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1:391036)
    at features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1:255978
    at features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1:256133
    at o (betterttv.js:118:967056)
(anonymous) @ betterttv.js:118
rs @ vendor-1cbe7bc148d476644ff8.js:1
i.componentDidCatch.n.callback @ vendor-1cbe7bc148d476644ff8.js:1
vi @ vendor-1cbe7bc148d476644ff8.js:1
us @ vendor-1cbe7bc148d476644ff8.js:1
wu @ vendor-1cbe7bc148d476644ff8.js:1
t.unstable_runWithPriority @ vendor-1cbe7bc148d476644ff8.js:1
Go @ vendor-1cbe7bc148d476644ff8.js:1
bu @ vendor-1cbe7bc148d476644ff8.js:1
au @ vendor-1cbe7bc148d476644ff8.js:1
(anonymous) @ vendor-1cbe7bc148d476644ff8.js:1
t.unstable_runWithPriority @ vendor-1cbe7bc148d476644ff8.js:1
Go @ vendor-1cbe7bc148d476644ff8.js:1
Yo @ vendor-1cbe7bc148d476644ff8.js:1
Zo @ vendor-1cbe7bc148d476644ff8.js:1
tu @ vendor-1cbe7bc148d476644ff8.js:1
enqueueSetState @ vendor-1cbe7bc148d476644ff8.js:1
w.setState @ vendor-1cbe7bc148d476644ff8.js:1
n.onEditableValueUpdate @ pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1
o @ betterttv.js:118
setTimeout (async)
(anonymous) @ betterttv.js:118
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1
ss @ vendor-1cbe7bc148d476644ff8.js:1
ku @ vendor-1cbe7bc148d476644ff8.js:1
t.unstable_runWithPriority @ vendor-1cbe7bc148d476644ff8.js:1
Go @ vendor-1cbe7bc148d476644ff8.js:1
xu @ vendor-1cbe7bc148d476644ff8.js:1
j @ vendor-1cbe7bc148d476644ff8.js:1
Zt @ vendor-1cbe7bc148d476644ff8.js:1
betterttv.js:118 12:29:06 AM [ERROR] [error-boundary] [ChatInput] An unhandled exception occurred in the component hierarchy TypeError: Cannot read properties of undefined (reading 'key')
    at twitch.js:103:59537
    at Array.forEach (<anonymous>)
    at t.getMatches (twitch.js:103:59495)
    at n.getMatches (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1:392041)
    at n.<anonymous> (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1:391091)
    at vi (vendor-1cbe7bc148d476644ff8.js:1:857240)
    at us (vendor-1cbe7bc148d476644ff8.js:1:892203)
    at wu (vendor-1cbe7bc148d476644ff8.js:1:909632)
    at t.unstable_runWithPriority (vendor-1cbe7bc148d476644ff8.js:1:929103)
    at Go (vendor-1cbe7bc148d476644ff8.js:1:853710)
    at bu (vendor-1cbe7bc148d476644ff8.js:1:906298)
    at au (vendor-1cbe7bc148d476644ff8.js:1:902452)
    at vendor-1cbe7bc148d476644ff8.js:1:854001
    at t.unstable_runWithPriority (vendor-1cbe7bc148d476644ff8.js:1:929103)
    at Go (vendor-1cbe7bc148d476644ff8.js:1:853710)
    at Yo (vendor-1cbe7bc148d476644ff8.js:1:853946)
    at Zo (vendor-1cbe7bc148d476644ff8.js:1:853881)
    at tu (vendor-1cbe7bc148d476644ff8.js:1:899038)
    at Object.enqueueSetState (vendor-1cbe7bc148d476644ff8.js:1:857666)
    at w.setState (vendor-1cbe7bc148d476644ff8.js:1:1020116)
    at n.onEditableValueUpdate (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1:391036)
    at features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1:255978
    at features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1:256133
    at o (betterttv.js:118:967056) {info: {…}}
(anonymous) @ betterttv.js:118
e.writeToConsole @ core-e826ce135798cb65bca6.js:1
write @ core-e826ce135798cb65bca6.js:1
write @ core-e826ce135798cb65bca6.js:1
e.errorAndReport @ core-e826ce135798cb65bca6.js:1
(anonymous) @ core-e826ce135798cb65bca6.js:1
vi @ vendor-1cbe7bc148d476644ff8.js:1
us @ vendor-1cbe7bc148d476644ff8.js:1
wu @ vendor-1cbe7bc148d476644ff8.js:1
t.unstable_runWithPriority @ vendor-1cbe7bc148d476644ff8.js:1
Go @ vendor-1cbe7bc148d476644ff8.js:1
bu @ vendor-1cbe7bc148d476644ff8.js:1
au @ vendor-1cbe7bc148d476644ff8.js:1
(anonymous) @ vendor-1cbe7bc148d476644ff8.js:1
t.unstable_runWithPriority @ vendor-1cbe7bc148d476644ff8.js:1
Go @ vendor-1cbe7bc148d476644ff8.js:1
Yo @ vendor-1cbe7bc148d476644ff8.js:1
Zo @ vendor-1cbe7bc148d476644ff8.js:1
tu @ vendor-1cbe7bc148d476644ff8.js:1
enqueueSetState @ vendor-1cbe7bc148d476644ff8.js:1
w.setState @ vendor-1cbe7bc148d476644ff8.js:1
n.onEditableValueUpdate @ pages.channel.components.channel-shell.components.chat-shell.components.chat-live-f475f32704edde1ca65c.js:1
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1
o @ betterttv.js:118
setTimeout (async)
(anonymous) @ betterttv.js:118
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-0445826704755fdce4a5.js:1
ss @ vendor-1cbe7bc148d476644ff8.js:1
ku @ vendor-1cbe7bc148d476644ff8.js:1
t.unstable_runWithPriority @ vendor-1cbe7bc148d476644ff8.js:1
Go @ vendor-1cbe7bc148d476644ff8.js:1
xu @ vendor-1cbe7bc148d476644ff8.js:1
j @ vendor-1cbe7bc148d476644ff8.js:1
Zt @ vendor-1cbe7bc148d476644ff8.js:1
sb.scorecardresearch.com/p?c1=2&c2=6745306&ns_type=hidden&ns_st_sv=5.1.3.160420&ns_st_smv=5.1&ns_st_it=r&ns_st_id=1665818883672&ns_st_ec=2&ns_st_sp=1&ns_st_sc=1&ns_st_sq=1&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=hb&ns_st_po=60031&ns_st_cl=0&ns_st_hc=6&ns_st_mp=js_api&ns_st_mv=5.1.3.160420&ns_st_pn=1&ns_st_tp=0&ns_st_ci=41392221659&ns_st_pt=60031&ns_st_dpt=60031&ns_st_ipt=10012&ns_st_et=60031&ns_st_det=60031&ns_st_upc=60031&ns_st_dupc=60031&ns_st_iupc=10012&ns_st_upa=60031&ns_st_dupa=60031&ns_st_iupa=10012&ns_st_lpc=60031&ns_st_dlpc=60031&ns_st_lpa=60031&ns_st_dlpa=60031&ns_st_pa=60031&ns_ts=1665818953072&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=0&ns_st_dbt=0&ns_st_bp=0&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=0&ns_st_dpc=0&ns_st_pp=0&ns_st_br=0&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=China%20IRL%20%7C%20Hangzhou%2C%20Temples%20and%20shit%20%20%20%20-%20!VPN&ns_st_ct=vc&ns_st_ge=Gaming&ns_st_st=waterlynn&ns_st_ce=1&ns_st_ia=0&ns_st_ddt=2022-10-14&ns_st_tdt=*null&ns_st_pu=*null&ns_st_ti=*null&c3=TWITCH&c4=twitch.tv&c6=*null&c7=https%3A%2F%2Fwww.twitch.tv%2Fwaterlynn&c8=waterlynn%20-%20Twitch&c9=https%3A%2F%2Fwww.twitch.tv%2Fvideos%2F1618194310&cs_ucfr=*null:1          GET https://sb.scorecardresearch.com/p?c1=2&c2=6745306&ns_type=hidden&ns_st_sv=5.1.3.160420&ns_st_smv=5.1&ns_st_it=r&ns_st_id=1665818883672&ns_st_ec=2&ns_st_sp=1&ns_st_sc=1&ns_st_sq=1&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=hb&ns_st_po=60031&ns_st_cl=0&ns_st_hc=6&ns_st_mp=js_api&ns_st_mv=5.1.3.160420&ns_st_pn=1&ns_st_tp=0&ns_st_ci=41392221659&ns_st_pt=60031&ns_st_dpt=60031&ns_st_ipt=10012&ns_st_et=60031&ns_st_det=60031&ns_st_upc=60031&ns_st_dupc=60031&ns_st_iupc=10012&ns_st_upa=60031&ns_st_dupa=60031&ns_st_iupa=10012&ns_st_lpc=60031&ns_st_dlpc=60031&ns_st_lpa=60031&ns_st_dlpa=60031&ns_st_pa=60031&ns_ts=1665818953072&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=0&ns_st_dbt=0&ns_st_bp=0&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=0&ns_st_dpc=0&ns_st_pp=0&ns_st_br=0&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=China%20IRL%20%7C%20Hangzhou%2C%20Temples%20and%20shit%20%20%20%20-%20!VPN&ns_st_ct=vc&ns_st_ge=Gaming&ns_st_st=waterlynn&ns_st_ce=1&ns_st_ia=0&ns_st_ddt=2022-10-14&ns_st_tdt=*null&ns_st_pu=*null&ns_st_ti=*null&c3=TWITCH&c4=twitch.tv&c6=*null&c7=https%3A%2F%2Fwww.twitch.tv%2Fwaterlynn&c8=waterlynn%20-%20Twitch&c9=https%3A%2F%2Fwww.twitch.tv%2Fvideos%2F1618194310&cs_ucfr=*null net::ERR_BLOCKED_BY_CLIENT
Image (async)
t @ core-e826ce135798cb65bca6.js:1
t @ core-e826ce135798cb65bca6.js:1
newEvent @ core-e826ce135798cb65bca6.js:1
t @ core-e826ce135798cb65bca6.js:1
o @ betterttv.js:118
setTimeout (async)
(anonymous) @ betterttv.js:118
(anonymous) @ core-e826ce135798cb65bca6.js:1
n @ core-e826ce135798cb65bca6.js:1
resume @ core-e826ce135798cb65bca6.js:1
t @ core-e826ce135798cb65bca6.js:1
o @ betterttv.js:118
betterttv.js:118 FFZ [site.compat_emote_menu]: Emote Menu for Twitch was not found after 60 seconds.
```

bttv settings:
`{"bttv_emotes":{"usageHistory":{"bttv-5bb1ae7ede3ebf66b7591b52":{"recentUses":[1665438450002],"totalUses":1,"score":40},"bttv-62421c9e3c6f14b68843cd97":{"recentUses":[1663830949547],"totalUses":1,"score":20},"bttv-5f08984172ac200523c66dff":{"recentUses":[1663790950332],"totalUses":1,"score":20},"bttv-61dedc4b06fd6a9f5be06315":{"recentUses":[1656837354390],"totalUses":1,"score":0},"bttv-5b7e01fbe429f82909e0013a":{"recentUses":[1654158895659],"totalUses":1,"score":0},"twitch-305954156":{"recentUses":[1642479804127],"totalUses":1,"score":0},"twitch-120232":{"recentUses":[1642479804127],"totalUses":1,"score":0},"twitch-425618":{"recentUses":[1642479804127],"totalUses":1,"score":0},"bttv-566ca06065dbbdab32ec054e":{"recentUses":[1642479804127],"totalUses":1,"score":0},"bttv-566ca38765dbbdab32ec0560":{"recentUses":[1642479804127],"totalUses":1,"score":0},"bttv-566c9fc265dbbdab32ec053b":{"recentUses":[1642479804127],"totalUses":1,"score":0},"bttv-566c9fde65dbbdab32ec053e":{"recentUses":[1642479804127],"totalUses":1,"score":0},"bttv-56e9f494fff3cc5c35e5287e":{"recentUses":[1642479804127],"totalUses":1,"score":0},"bttv-555981336ba1901877765555":{"recentUses":[1642479804127],"totalUses":1,"score":0}},"favorites":[]},"bttv_settings":{"anonChat":false,"autoTheatreMode":false,"splitChat":false,"deletedMessages":1,"reverseChatDirection":false,"pinnedHighlights":true,"timeoutHighlights":false,"highlightFeedback":true,"chatLayout":2,"tabCompletionTooltip":false,"tabCompletionEmotePriority":true,"whispers":true,"showDirectoryLiveTab":false,"channelPointsMessageHighlights":true,"clickTwitchEmotes":true,"darkenedMode":true,"friends":true,"primePromotions":true,"hostButton":false,"playerExtensions":true,"clickToPlay":false,"muteInvisiblePlayer":false,"scrollVolumeControl":false,"blacklistKeywords":{},"highlightKeywords":{"0":{"id":0,"type":0,"status":null,"keyword":"tunacan_man"}},"sidebar":[15,0],"emotes":[3,4],"chat":[127,0],"autoPlay":[7,0],"usernames":[6,1],"channelPoints":[5,0],"version":"7.4.40"}}`

ffz settings:
`{"version":2,"type":"full","values":{"p:0:chat.tab-complete.limit-results":false,"p:0:chat.emote-menu.icon":false,"p:0:chat.filtering.highlight-basic-users":[{"v":{"remove":false,"v":"chluaid","t":"text","c":"rgba(38, 54, 18, 0.67)","s":false,"h":false,"w":true,"p":0},"id":"1665055647018-0.8009316226520773-1"}],"cfg-seen":["i18n.debug.capture","i18n.debug.transform","i18n.locale","i18n.format.date","i18n.format.time","i18n.format.datetime","socket.use-cluster","chat.actions.size","chat.actions.reasons","chat.actions.inline","chat.actions.user-context","chat.actions.room","chat.actions.room-above","chat.actions.rules-as-reasons","chat.badges.version","chat.badges.fix-colors","chat.badges.custom-mod","chat.badges.custom-vip","chat.badges.style","chat.badges.clickable","chat.badges.hidden","chat.emotes.enabled","chat.emotes.2x","chat.fix-bad-emotes","chat.emotes.animated","chat.click-emotes","chat.sub-emotes","chat.emote-dialogs","chat.scrollback-length","chat.delay","chat.pin-resubs","chat.emoji.style","debug.link-resolver.source","debug.link-resolver.test","chat.timestamp-size","chat.font-size","chat.font-family","chat.width","chat.name-format","chat.lines.emote-alignment","chat.me-style","chat.timestamp-format","chat.extra-timestamps","chat.lines.alternate","chat.lines.padding","chat.lines.borders","chat.rich.enabled","chat.rich.want-mid","chat.rich.hide-tokens","chat.rich.all-links","chat.rich.minimum-level","chat.filtering.debug","chat.filtering.click-to-reveal","chat.filtering.process-own","chat.filtering.deleted-style","chat.filtering.display-deleted","chat.filtering.display-mod-action","chat.filtering.ignore-clear","chat.filtering.remove-deleted","chat.automod.delete-messages","chat.automod.remove-messages","chat.automod.run-as-mod","chat.filtering.pad-bottom","chat.filtering.highlight-basic-users","chat.filtering.highlight-basic-users-blocked","chat.filtering.highlight-basic-badges","chat.filtering.highlight-basic-badges-blocked","chat.filtering.highlight-basic-terms","chat.filtering.highlight-tokens","chat.filtering.color-mentions","chat.filtering.bold-mentions","chat.filtering.mention-priority","chat.filtering.mention-color","chat.filtering.highlight-mentions","chat.filtering.highlight-basic-blocked","chat.filtering.clickable-mentions","tooltip.images","tooltip.badge-images","tooltip.emote-sources","tooltip.emote-images","tooltip.emote-images.animated","tooltip.rich-links","tooltip.link-interaction","tooltip.link-images","tooltip.link-nsfw-images","chat.adjustment-mode","chat.adjustment-contrast","chat.bits.stack","chat.bits.animated","chat.bits.show","chat.bits.cheer-notice","ffz.search.matches-only","metadata.clip-download","metadata.player-stats","metadata.stream-delay-warning","metadata.uptime","metadata.viewers","metadata.viewers.no-native","metadata.uptime.no-native","metadata.featured-follow","metadata.host-button","layout.display-bits-button","layout.theatre-navigation","layout.minimal-navigation","layout.discover","layout.prime-offers","layout.hide-discover-luna","ffz.show-new-settings","channel.panel-tips","channel.auto-skip-trailer","channel.auto-click-chat","channel.extra-links","channel.show-celebrations","channel.hide-unfollow","channel.hide-live-indicator","channel.round-avatars","player.hide-event-bar","channel.hosting.enable","chat.scroller.freeze","chat.scroller.freeze-requires-hover","chat.scroller.hover-delay","chat.scroller.smooth-scroll","chat.input.hide-identity","chat.input.show-mod-view","chat.emote-menu.shortcut","chat.emote-menu.modifiers","chat.emote-menu.enabled","chat.emote-menu.default-tab","chat.emote-menu.show-emoji","chat.emote-menu.combine-tabs","chat.emote-menu.stay-loaded","chat.emote-menu.icon","chat.emote-menu.show-quick-nav","chat.emote-menu.tall","chat.emote-menu.show-heading","chat.emote-menu.show-search","chat.emote-menu.reduced-padding","chat.emote-menu.sort-emotes","chat.emote-menu.sort-tiers-last","chat.mru.enabled","chat.tab-complete.ffz-emotes","chat.tab-complete.emoji","chat.tab-complete.emotes-without-colon","chat.tab-complete.limit-results","chat.tab-complete.prioritize-favorites","chat.viewer-cards.highlight-chat","chat.viewer-cards.color","chat.filtering.blocked-types","chat.replies.style","channel.raids.no-autojoin","chat.hide-community-highlights","chat.subs.gift-banner","chat.banners.hype-train","chat.banners.drops","chat.banners.polls","chat.banners.prediction","chat.community-chest.show","chat.bits.show-pinned","chat.points.allow-highlight","chat.points.show-callouts","chat.points.show-button","layout.portrait-min-chat","layout.portrait","layout.portrait-invert","layout.portrait-threshold","chat.points.show-rewards","chat.points.auto-rewards","chat.bits.show-rewards","chat.rituals.show","chat.subs.show","chat.subs.compact","chat.subs.merge-gifts","chat.subs.merge-gifts-visibility","metadata.modview.hide-info","layout.swap-sidebars","layout.side-nav.show","layout.side-nav.hide-viewers","layout.side-nav.show-avatars","layout.side-nav.show-rec-channels","layout.side-nav.show-friends","layout.side-nav.hide-offline","layout.side-nav.rerun-style","whispers.show","layout.theme.global-font","theme.font.size","directory.hidden.style","directory.hidden.reveal","directory.uptime","directory.hide-live","directory.hide-promoted","directory.hide-vodcasts","directory.hide-recommended","clips.layout.big","player.theatre.metadata","player.theatre.no-whispers","player.theatre.auto-enter","player.embed-metadata","player.compressor.enable","player.compressor.default","player.compressor.shortcut","player.gain.enable","player.gain.no-volume","player.gain.scroll","player.gain.min","player.gain.max","player.gain.default","player.compressor.threshold","player.compressor.knee","player.compressor.ratio","player.compressor.attack","player.compressor.release","player.allow-catchup","player.button.reset","player.button.pip","player.hide-mouse","player.mute-click","player.volume-scroll","player.volume-scroll-steps","player.volume-always-shown","player.captions.font-size","player.captions.font-family","player.ext-hide","player.ext-interaction","player.no-autoplay","player.vod.autoplay","player.home.autoplay","sub-button.prime-notice","theme.color.background","theme.color.text","theme.color.accent","theme.color.tooltip.background","theme.color.tooltip.text","theme.color.chat-background","theme.color.chat-text","theme.color.chat-accent","chat.video-chat.timestamps","chat.video-chat.enabled","experiments","i18n.debug.open","socket.info","profiles","backup","clear","provider","home","faq","chat.filtering.syntax-help","feedback","feedback.log","changelog","add-ons","addon-changelog","legal","directory.game.blocked-games","directory.game.hidden-thumbnails","addons.dev.server","addon.7tv_emotes.global_emotes","addon.7tv_emotes.channel_emotes","addon.7tv_emotes.update_messages","ffzap.betterttv.global_emoticons","ffzap.betterttv.arbitrary_emoticons","ffzap.betterttv.channel_emoticons","ffzap.betterttv.pro_emoticons","ffzap.core.remove_spaces","ffzap.core.message_deletion","ffzap.core.enable_highlight_sound","ffzap.core.highlight_sound","ffzap.core.highlight_sound_volume","ffzap.core.highlight_sound_prevent_own_channel","ffzap.core.highlight_sound_types","addon.seventv_emotes.channel_emotes","addon.seventv_emotes.global_emotes","addon.seventv_emotes.unlisted_emotes","addon.seventv_emotes.emote_updates","addon.seventv_emotes.update_messages","addon.seventv_emotes.animated_avatars","addon.seventv_emotes.badges","addon.seventv_emotes.nametag_paints","chat.emotes.limit-size","chat.emoji.replace-joiner","chat.tab-complete.prioritize-prefix-matches","chat.banners.last-events","directory.block-titles","chat.filtering.hidden-tokens"],"p:0:chat.filtering.remove-deleted":0,"p:0:chat.filtering.deleted-style":0,"p:0:chat.viewer-cards.highlight-chat":true,"emote-menu.collapsed":["twitch-564265402","twitch-537206155","twitch-488737509","twitch-472873131","twitch-610186276"],"p:0:addon.7tv_emotes.update_messages":true,"p:0:chat.filtering.display-deleted":"DETAILED","p:0:chat.scrollback-length":120,"p:0:ffzap.betterttv.channel_emoticons":false,"p:0:ffzap.betterttv.arbitrary_emoticons":true,"p:0:addon.7tv_emotes.channel_emotes":true,"p:0:addon.seventv_emotes.animated_avatars":false,"p:0:addon.seventv_emotes.nametag_paints":false,"p:0:chat.filtering.clickable-mentions":true,"p:0:ffzap.betterttv.pro_emoticons":false,"p:0:addon.7tv_emotes.global_emotes":true,"addons.enabled":["ffzap-core","7tv-emotes","ffzap-bttv"],"p:0:chat.tab-complete.emotes-without-colon":true,"p:0:chat.tab-complete.prioritize-prefix-matches":true,"cfg-collapsed":["chat.actions"],"p:0:chat.tab-complete.prioritize-favorites":true,"p:0:ffzap.betterttv.global_emoticons":false}}`

**Comment by night** [comment]
This for the report. The reason you see BetterTTV in the stack trace is because we wrap all window errors for centralized error logging, but it is not the cause of the issue. `twitch.js` is, which is likely a file from a different extension you are using. BetterTTV only executes code from a single file, `betterttv.js`

**Comment by Wissididom** [comment]
I researched a little after checking the Firefox browser console and debugger and saw, that `moz-extension://bb905a45-aee1-4787-bfdb-b73b1fc20ea8/twitch.js` is the file which, when I click on it, leads me to `7TV/twitch.js`.
Then I researched the internet to see if there is a github repo for it I found the following two links:
https://github.com/SevenTV/Extension/issues/291
https://github.com/SevenTV/Extension/pull/300
Although the error message is `TypeError: n is undefined` and `[ERROR] [error-boundary] [ChatInput] An unhandled exception occured in the component hierarchy TypeError: n is undefined` I think it might be the same problem.
**This comment should just be a fyi.** Attaching a screenshot from my browser console tho:
![image](https://user-images.githubusercontent.com/30803034/210106650-ec1d7497-5685-4ad2-837a-af0c0534f590.png)
