### ISSUE TITLE
Auto resize emote uploads

### ISSUE THREAD

**Issue by theballakoala** [night/betterttv#5692]
Please add auto resizing of  images with a height larger than 112px. Having to manually make a separate 112px version of every emote just for bttv is annoying to say the least. Want to make my emotes available on bttv now free slots have been expanded, but don't intend to go through and make resized versions of 30~ emotes for obvious reasons.

**Comment by night** [comment]
The emote upload system will now automatically resize slightly larger images for you if the dimensions make sense.
