### ISSUE TITLE
Suggestion: Re-wording of new "live" feature

### ISSUE THREAD

**Issue by Px05119** [night/betterttv#5694]
With the newest update to BetterTTV we've had a new feature added that we can remove emotes from active slots without deleting them from the service and re-uploading at a later date. However there already has been some confusion. I would suggest a few things to make it easier for users to understand, especially those who don't natively speak English

1) Flip the Sharing and Live checkboxes so the Live one has "priority"
2) Change the word Live to either Active or Enabled, as well as adding to the description that emotes that are not Live/Active/Enabled can't be shared
3) If possible, grey out (but leave checked or unchecked) the "Sharing" option when an emote is not set as Live/Active/Enabled.

I've added a screenshot of these options, in their original configuration, for those who might not have seen this yet.
![unknown](https://user-images.githubusercontent.com/25652184/196737770-cc983e25-6387-4c18-9d6b-655c13f488e5.png)

**Comment by night** [comment]
Thanks for the feedback. We've added an improved description beneath `Live`. `Sharing` has been changed to remain when emotes are not live in the uploader's chat, which should make the feature more usable and easier to understand.
