### ISSUE TITLE
Feature Request: An option to disable uploaded emotes on your own channel, while still having them publicly listed

### ISSUE THREAD

**Issue by brian6932** [night/betterttv#5698]
As someone who likes to make emotes, I don't want to have every single emote I uploaded usable on my channel, and at the same time, I often still want them available publicly.

I understand wanting to lighten the load on your platform's moderators, but I really don't think that outright disabling an already approved, publicly accessible emote, is a good user experience.

It restricts your platform's creative output, standard users have a small enough pool of possible uploads as it is, as opposed to subscribers that are paying to use the publicly listed emotes anyway. The larger the creator pool, and the lower the barrier to entry, the more people would want to subscribe, imo it only seems like a win-win, for subscribers and standard users.

Besides, every other competing platform (7tv/ffz) already allow for this, now that channel and shared slots have been merged, this seems like the logical conclusion.

**Comment by night** [comment]
Thanks for the request. We're already considering this via #5694, so I am going to close this as a duplicate.
