### ISSUE TITLE
small bugs with mod cards

### ISSUE THREAD

**Issue by conceptionals** [night/BetterTTV#570]
I just noticed these bugs today so I'm guessing that they are due to the recent update with the Mod cards. The first bug that I want to point out is whenever you click on a username in the viewer list the bottom half of the mod card isn't fully grey likes it use to be.

![newissue01](https://cloud.githubusercontent.com/assets/13137308/8748847/d26fbb50-2c62-11e5-995c-4d5fa220f954.png)

The next thing that I've noticed is that whenever the page is done loading, and you click on a name in the user list it refreshes the page and then the mod card shows up. [Here is what I mean](http://gyazo.com/bf22013034016fbd1d2c3c5e20c07805). Now this doesn't happen every time and I've only tested the channel owner so not too sure if it happens with any user. Like I said this happens whenever you click on a name in the viewer list after the page is done loading, and even though it doesn't happen every time, I was able to replicate this many times on various channels.

**Comment by night** [comment]
The latter is an issue we cannot fix, as it's an Twitch ember bug (our mod cards are only when clicking names in chat).
