### ISSUE TITLE
Make the minimum emote code length two characters

### ISSUE THREAD

**Issue by Arhammahra** [night/betterttv#5706]
It's so frustrating that we can't use two or three letter words and have to ruin the name by adding extra letters that make no sense, there are literally hundreds of two and three letter words but we just can't make an emote with those words simply because for unknown reasons you guys set the code requirement to minimum four letters. Want to make another emote named "EZ"? oh too bad the devs just disabled that option years ago for some reason.

**Comment by night** [comment]
We intentionally added restrictions on emote codes due to conflicts in the past. Users may not expect type common acronyms or words like "EZ" and see an emote.
