### ISSUE TITLE
Useless statistics still lurking

### ISSUE THREAD

**Issue by avasesl** [night/betterttv#5708]
Twitch removed the channel views statistic in April - the number no longer moves, yet stays in user cards in chats. This is from someone who started streaming this year, followers update, views don't. Maybe just drop the stat from the UI? Didn't see on vanilla twitch, saw when adding bttv
![image](https://user-images.githubusercontent.com/116748923/198085224-5ac14922-051e-4954-8798-17be3b9032d9.png)

**Comment by cbclemmer** [comment]
@night If this is something that needs to be done. I'd like to try doing it

**Comment by night** [comment]
> @night If this is something that needs to be done. I'd like to try doing it

we prob should remove this if it's not useful anymore

**Comment by cbclemmer** [comment]
PR is up #5733
