### ISSUE TITLE
bttv api v3 not working anymore

### ISSUE THREAD

**Issue by makedir** [night/betterttv#5709]
global: https://api.betterttv.net/3/cached/emotes/global
badges: https://api.betterttv.net/3/cached/badges
bttv channel emotes: https://api.betterttv.net/3/cached/users/twitch/121059319
ffz channel emotes: https://api.betterttv.net/3/cached/frankerfacez/users/twitch/121059319
changelog: https://api.betterttv.net/3/cached/changelog

all gone. was the api v3 removed without feedback? or is there a new one.

**Comment by night** [comment]
The API is still functional, but we do not officially support or document the API at this time. You can refer to #3593 for more information.
