### ISSUE TITLE
The lirikHug Emote

### ISSUE THREAD

**Issue by Knuffi69x** [night/BetterTTV#571]
Hey if I disable BTTV the lirikHug emote looks so: http://gyazo.com/a30793d467284d1e3007d7434f8c4fe5

If I enable BTTV it looks: http://gyazo.com/e0f160802e7afe20a5614a1e65e999c6 

How can I fix that? Can you help me?

**Comment by voloshink** [comment]
That is what the emote looks like https://twitchemotes.com/emote/29049

**Comment by night** [comment]
I don't see the problem here.. The emote looks the same?
