### ISSUE TITLE
Include emote dimensions in endpoints related to fetching emotes

### ISSUE THREAD

**Issue by Foretack** [night/betterttv#5712]
Since wide emotes have been introduced, it is no longer safe to assume that every emote will be 112x112px of size, which makes things a bit complicated for some applications as trying to allot the exact space an emote will occupy becomes unworkable.

The other emote providers already include information regarding emote dimensions, for the reason that their emotes won't always be of fixed size.

I think it's about time that bttv incorporates such information in their API, or at least with the endpoints `https://api.betterttv.net/3/cached/users/twitch/{id}` & `https://api.betterttv.net/3/cached/emotes/global` as they are by far the ones needing them the most.

**Comment by night** [comment]
Thanks for the suggestion. We've added `width` and `height` to the emote serialization when they are not 1:1, which should make it easier to identify the correct sizing when needed.
