### ISSUE TITLE
Cannot upload new emote

### ISSUE THREAD

**Issue by blairg23** [night/betterttv#5722]
I try to upload an animated emote and hit "Upload Emote", which spins then goes back to "Submit Emote" w/o uploading anything. No error message. When I check the Developer Console, it says Error 520, but no actual error message.

**Comment by night** [comment]
A 520 status code is not a status code our servers return. It's possible the file being uploaded is too large or that our content distribution network was having an outage. If you're still having this issue, please specify more information about what is being uploaded.
