### ISSUE TITLE
Suggestion: Allow aliasing emote names

### ISSUE THREAD

**Issue by atheridis** [night/betterttv#5736]
When getting an emote that was uploaded by someone else, you're forced to use whatever name they chose. Sometimes there are public emotes that fit the channel very well (due to some inside joke), but will only work with a custom name.

Allowing aliasing emote names for each channel could be very helpful.

**Comment by gempir** [comment]
Another interesting benefit: It can prevent a lot of duplicate emotes in the future because people only reupload an emote just to have another name for it.

**Comment by night** [comment]
We've released the ability to create code aliases for channel and personal emotes.
