### ISSUE TITLE
Automatically switch to mod view when available

### ISSUE THREAD

**Issue by DaeDroug** [night/betterttv#5737]
Would be awesome to have an option that whenever you enter a stream that has the option to be in mod view it switches you to mod view. Pretty simple but would make things a lot smoother for people like me that frequent a lot of streams and is also mod in numerous streams.

**Comment by cbclemmer** [comment]
@night I think this could be done by checking for the `a data-test-selector="mod-view-link"` attribute that would take you to the mod view and auto redirecting, but I'm not sure if it would be randomly removed. It would need a an option in the config, but I'm willing to do it if you think it's worth it.
