### ISSUE TITLE
Having the extension enabled throws Unchecked runtime.lastError

### ISSUE THREAD

**Issue by brentspine** [night/betterttv#5739]
So when having the BTTV extension enabled throws the following error for me in the console:
```Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received```

This sometimes makes the extension not work anymore.
I have the latest version installed as far as I know.

<h2>Specs:</h2>

Browser: Brave
OS: Windows 11 Home
Other Extensions installed: Tampermonkey, Grammarly

**Comment by plicit** [comment]
It might be Tampermonkey which should be fixed in beta v4.19.6170+:

https://github.com/Tampermonkey/tampermonkey/issues/1628#issuecomment-1293880399

**Comment by night** [comment]
This looks unrelated to BetterTTV. If you're still having issues after updating TamperMonkey, please let us know.
