### ISSUE TITLE
Usage of Live Emote Updates

### ISSUE THREAD

**Issue by Nerixyz** [night/betterttv#5740]
I want to add live emote updates to [Chatterino](https://github.com/Chatterino/Chatterino2) ([Draft PR](https://github.com/Chatterino/chatterino2/pull/4147)) for BTTV. Since this WebSocket endpoint isn't documented, I'm asking here if it's okay to use this API.

The implementation sets the User-Agent to `Chatterino/{version} ({commit-hash})`, checks the general structure of the messages, and handles WebSocket ping frames.

Related to #3593, #5630.

**Comment by night** [comment]
Go for it, but also implement `broadcast_me` and `lookup_user` for full compatibility with the service.

**Comment by Nerixyz** [comment]
I've implemented `broadcast_me` now, but since Chatterino doesn't yet implement personal emotes for **any** provider, I wouldn't want to implement it in this PR.

Is the implementation of `lookup_user` a requirement for using the service, or would it be okay to just have `join/part_channel` and `broadcast_me`?

**Comment by night** [comment]
> Is the implementation of `lookup_user` a requirement for using the service, or would it be okay to just have `join/part_channel` and `broadcast_me`?

It would be great if personal emotes worked, but if that is a limitation of the project then it is fine to exclude it for the moment.
