### ISSUE TITLE
Suggestion - Sidebar and chat on the same side

### ISSUE THREAD

**Issue by FruZio1337** [night/betterttv#5745]
Is there even a possibility of having sidebar and chat on the same side? I know that it works when it is bugged (?) I guess but I would love to see it as an option if possible (preferably also on the left side) - [IMGUR EXAMPLE](https://i.imgur.com/o8bZ3XG.png)

**Comment by night** [comment]
Thanks for the request. Unfortunately because of collapsing and resize logic Twitch implements on the page, it is not possible to change the ordering of these columns. We are only able to invert the ordering, not resort them entirely.
