### ISSUE TITLE
Sort/Filter list of enabled emotes on our channel

### ISSUE THREAD

**Issue by susyemeralds** [night/betterttv#5756]
Please allow emotes enabled on our channel to be **sorted by Last Uploaded**
And please allow to **filter animated/static emotes**.

This would help TREMENDOUSLY when figuring out which emotes are uploaded on our Discord Server since it uploads emotes chronologically and since it only allows for a certain amount of static emotes and a certain amount of animated emotes. 

Make sure the top counter for the number of emotes on the page always updates to the number of emotes being shown for when we are filtering them. I want to know at a glance how many animated or static emotes I have enabled. 

I just got the BTTV Pro subscription and I've been loving how convenient it has been having BTTV upload for me so many emotes onto my Discord server. But this extra feature would help INCREDIBLY. 

Thank you so much!

**Comment by night** [comment]
Thanks for the request. We've added the ability to sort by name or date added, and filter for animated or static emotes on the dashboard emotes page.
