### ISSUE TITLE
Add live emote updates to ffz addon

### ISSUE THREAD

**Issue by IZeeLikeEyeZee** [night/betterttv#5759]
Currently you can only see live updates for emotes by using the bttv extension, but I don't wanna use that since the bttv extension has features u can't turn off, that I prefer not to have. But since I'm using ffz with the bttv emotes addon I have to refresh to see new emotes, so please add the live updates to the ffz addon. 👍

**Comment by dclstn** [comment]
Without any webhook implementation from frankerfacez, it seems unlikely for us to implement this feature as there's no guarantee the changes will be "real-time".

**Comment by night** [comment]
We do not maintain third party implementations of our API. You would need to request this as a feature with the third party.
