### ISSUE TITLE
Translation needs improvement!!!!

### ISSUE THREAD

**Issue by crossfire151** [night/BetterTTV#577]
the translation is good idea however every 5 minutes???

no offence but that's shit, not helpful for moderators is it?
because of that I still have to goto a separate translator, if you are going to implement something at least make it fully usable or it renders pointless.

**Comment by cletusc** [comment]
It costs money to translate things through Google's API. It was re-added with the 5 minute limitation as a convenience, but the BTTV devs are actually _paying_ for you to even do it once per 5 minutes.

If you really need it that often, try a separate translation addon ([for Firefox](https://addons.mozilla.org/en-us/firefox/addon/google-translator-for-firefox/) or [for Chrome](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb?hl=en)).

**Comment by night** [comment]
¯\_(ツ)_/¯
