### ISSUE TITLE
Suggestion: Return offline channels to sidebar

### ISSUE THREAD

**Issue by KristjanTammekivi** [night/betterttv#5772]
Twitch decided to hide offline channels and instead show recommendations on the sidebar if there are no online followed channels. Would be nice if it was possible to hide the recommendations and bring back offline channels list.

![image](https://user-images.githubusercontent.com/8754356/204529052-f1ede189-4153-44d8-be26-d44fc4bf6a67.png)

**Comment by dewaldsch** [comment]
I would also Like to have this feature

**Comment by night** [comment]
I am not able to reproduce this. It's possible this is an experiment Twitch is running which is not yet available to everyone or has been rolled back.

**Comment by KristjanTammekivi** [comment]
Yes, sorry, it got rolled back for me this week, forgot to close the issue
