### ISSUE TITLE
Suggestion: Highlight online streamer in left bar

### ISSUE THREAD

**Issue by coffeepete** [night/betterttv#5774]
If it is possible to add this feature I would like to suggest adding a green highlight "dot" (or free chose able color) next to the avatars in the compressed sidebar on the left side. There are many streamers having a non-colored Avatar which makes it hart to see who is online.

Have a look at that example: The first 4 people are online.
![image](https://user-images.githubusercontent.com/119531755/204884077-1c1d9d7d-4754-4544-8822-280cfc84bbdb.png)

**Comment by night** [comment]
Thanks for the request. This doesn't seem very applicable to most channels, which tend to have colored avatars. Additionally, you could uncollapse the sidebar to see a live indicator that Twitch already has.
