### ISSUE TITLE
Search for emotes that can be added as personal emotes

### ISSUE THREAD

**Issue by susyemeralds** [night/betterttv#5779]
Instead of finding emotes that can be added as personal emotes randomly (for BTTV Pro subscribers), please allow to search for emotes that can added as personal emotes with a filter or maybe even better have a tab of ready, potential personal emotes catalog. 

They are so few of them for the moment and they are hard to find! Was a little disappointed by my BTTV Pro subscription when I found that out.

**Comment by night** [comment]
duplicate of #5616
