### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by crossfire151** [night/BetterTTV#579]
I would like to see a new feature called own chat commands (or something related)

So basically a ability to add easy-to-send commands to channels.

A settings side; where you create the commands and give them a name,
then a popup kinda link how the twitch channel setting cog window comes up.

Let me know what you think if this idea

Crossfire151

**Comment by vendethiel** [comment]
What would those do that can't be covered by bots?

**Comment by voloshink** [comment]
/dongers -> ヽ༼ຈل͜ຈ༽ﾉ raise your dongers ヽ༼ຈل͜ຈ༽ﾉ

useful stuff, you know

**Comment by crossfire151** [comment]
that's the point, you add your own commands for example they would communicate with the bot so for instance: /<command>    output:  !<command>
or just a quick send command: click a named command, and it would output what ever command !<command>.

**Comment by voloshink** [comment]
Im not sure what you mean. What do you mean by 'click' a command, where is it located for it to be clicked. '/ output: !' doesn't exactly help either. Could you give a concrete example?

**Comment by crossfire151** [comment]
sure...
firstly you would have a separate settings area where you can input your own command...
window would look something like this:

Command name: Check my points
Command: !points
then you save it

then you will have a settings panel that you can open directly from the chat
which will list your saved commands.

Check my Points
(command)
(command)

ect ect...

clicking a command would instantly send that command to the chat rather than you manually typing that command out, kind of like the !permit (user) already does and the timeouts ect.

get me now? :D

**Comment by voloshink** [comment]
I get the idea. But having the user open a separate window just to send commands feels clunky. The custom text commands idea could be something we would consider, though.

**Comment by crossfire151** [comment]
yeah I see your point but you get the idea something similar if you get what I mean :D

Would be good to see something like the custom text commands :D

**Comment by night** [comment]
I do not see any reason for this except generating for generating spam, which we don't really wish to promote.
