### ISSUE TITLE
Error while trying to click X on Prime Gaming Loot offers

### ISSUE THREAD

**Issue by privacyguy123** [night/betterttv#5798]
```
[GraphQL] One or more GraphQL errors were detected on request 01GMBD7SWEZAKAGFAX9XKE2KDA. updatePrimeOfferStatus: failed integrity check 
Array [ {…} ]
```

**Comment by dclstn** [comment]
https://github.com/night/betterttv/issues/5735#issuecomment-1309211812

> Unfortunately, this appears to be a Twitch issue. You may try clearing your cookies/cache and seeing if that helps.
