### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ICantNameMe** [night/BetterTTV#580]
1. Could you make an option to force the video player to 1280x720 resolution so that I can watch 720p with 1:1 pixel mapping?

2. Could you make it so the video doesn't slide up during theater mode when you mouse over it? Either put more black space at the bottom, or always show the control bar, or whatever, I just hate seeing it slide up and down, and it's the main reason I don't use theater mode.

**Comment by night** [comment]
> Could you make an option to force the video player to 1280x720 resolution so that I can watch 720p with 1:1 pixel mapping?

We used to force this in the past, and people would incessantly complain we didn't work like Twitch's. We're not going to be changing this functionality.

> Could you make it so the video doesn't slide up during theater mode when you mouse over it? Either put more black space at the bottom, or always show the control bar, or whatever, I just hate seeing it slide up and down, and it's the main reason I don't use theater mode.

This is not possible. Twitch implements this in their player, which is flash. We are not allowed to place overlays over the player, as it's against their ToS.
