### ISSUE TITLE
Feature request - Emote search - Sort by most popular 

### ISSUE THREAD

**Issue by RaidinD** [night/betterttv#5801]
Allow for users searching for an emote to sort results by **most popular** (added to the highest number of channels). 
This issue was raised on the forums [20 days ago](https://community.nightdev.com/t/search-feature-request-sort-by-most-popular/33604), but the poster never followed up with the issue here. I, myself tried searching for "most popular" and "popular" to see if there were any issues open but didn't find anything relevant.

As per the original forum post, say for example the user is searching for the emote "GIGACHAD". Aside from scrolling down through the "Top Emotes" page to find it, **searching provides a lot of variants and reuploads separate from the most used**. 

- The version enabled in the most amount of channels is [here](https://betterttv.com/emotes/609431bc39b5010444d0cbdc)
- But, when "GIGACHAD" is searched [it appears near the bottom of the results](https://i.nuuls.com/buWLr.mp4)

Searching through "Trending emotes" or "Shared emotes" produces the same results.

Obviously having the most popular version of an emote isn't for everyone.
But as another example:

- If the user is searching for [this particular variant of "MEGALUL"](https://betterttv.com/emotes/5ff3dbaf3855d304824fa0e0) and specifically want it from its original creator, they have to scroll down once again to near the bottom of the list to see this version. 
- While scrolling there are other reuploads of this emote with slight changes to get past emote duplication.
- In theory, this emote should be near the top of the list since it has been added to over 1000 channels, just under [this variant](https://betterttv.com/emotes/579f9ac281108bf71a550e97) which has been added to over 3000.  

Some users don't want to add duplicates of emotes since they are made to get around emote duplication and as such are altered from the original with changes to hues, saturation, and brightness levels, the dreaded white outline, and missing frames or sped-up animations being common distinctions.

Ideally, the best solution would be to sort emotes by most popular in the search results by default, especially under the top emotes section but a "sort by" dropdown menu where you can change how results come up would be most welcome. This would allow for new filters too. For example, you could have a "New" filter for users to find newer versions of older emotes and "Top" being those added to the most amount of channels.

**Comment by night** [comment]
Thanks for the suggestion. Search is now sorted by popularity, which should make it easier to find what you're looking for.
