### ISSUE TITLE
Feature request - Emote Menu - 7TV Emotes

### ISSUE THREAD

**Issue by naotaXD13** [night/betterttv#5810]
Allow users to see and use emotes from the 7TV extension, both global and channel specific, if they are available on the channel you are watching.

This issue was [raised](https://github.com/night/betterttv/pull/4840) about a year ago, but was dismissed due to the fact that, and I quote,

> [... since 7TV emotes do not abide by the Twitch Terms of Service and our emote guidelines, we are not willing to allow this content on our extension. ](https://github.com/night/betterttv/pull/4840#issuecomment-922406564)

Which is no longer relevant, as a person who actively adds emotes both on BTTV and 7TV, I want to note that 7TV really complies with the Twitch Terms of Service, and the 7TV's emote library also has moderation that checks new emotes on compliance with the rules. A lot of offensive or banned emotes have been removed over the past year for this very reason.

I personally think that this function is necessary for more ergonomic and convenient communication in the live chat, which also eliminates the need for an extra extension (7TV) in the browser. Plus, 7TV has an extremely inconvenient, in my personal opinion, extension and finding the right emotes there is extremely difficult, especially if there are a lot of emotes on the channel, compared to the BTTV extension.

**Comment by EdVraz** [comment]
Yes please I finally want to delete the 7tv plugin

**Comment by IZeeLikeEyeZee** [comment]
My solution is to use ffz with bttv and 7tv emotes as addons, that way you dont get either of the weird stuff that comes with bttv/7tv extensions that u cant disable. FFZ can do everything the other extensions can do and more 🤷
