### ISSUE TITLE
[suggestion] discussion of concept for message highlighting/blacklist overhaul (potentially extendable for other settings)

### ISSUE THREAD

**Issue by Sorontik** [night/betterttv#5816]
I suggest to (more or less completely) overhaul the highlighting/blacklist system to address and implement a couple of tickets.
This concept is also extendable to other functions/settings as explained under 'extension'

## basic draft
My idea would be to define all highlighting in a list of **"Buckets"**
Each **Bucket** aplies to a certain scope ('global', for a certain list of channels, maybe also based on roles like "all channels where you are mod/vip") and defines a list of **rules** for chat messages.

Each **rule** associates a list of **triggers**/conditions to a list of **actions** and if at least one of the triggers 'fires' for a specific message, this rule's actions are applied.

I imagine a couple of different **trigger** types like Keywords, Wildcard patterns, Regex-Patterns, but also more generic algorithmic groups like "sent by broadcaster", "sent by mod", "sent by vip", "mentions broadcaster/mod/vips name" which would automatically access the values for the current channel.

**Actions** would be "set background color", maybe even fg color, font styles etc, or 'hide message' (for blacklist).

In case of multiple matching triggers, three obvious strategies jump to mind:
* the smallest, most specific scopes take precedence
* the bucket-list is ordered by priority
* all applicable action lists are merged and all styles are merged, resolving conflicts by one of the strategies above
  (this would allow to combine rules/styles likes "vips' messages are bold", "mod's messages have a red bg" so if one is vip and mod, their messages appear in bold and with red bg)

This would allow 
* multiple different and customizable highlight-styles like issue #237 requests,
* channel specific keywords like #68 suggests and 
* allows advanced users to use Regular Expression patterns like #267 suggests, without overly increasing difficulty for the average user (who can simply ignore the regex-trigger and stick to keyword or wildcard triggers)
* the blacklist could then be implemented by "hide message" actions in the same system and would automatically benefit from enhancements to the conditions/triggers

## extension

It should be easily extensible on all levels, e.g. by adding new triggers/conditions or new actions ( e.g. "play sound" action for sound alerts).
It should also be possible to later add triggers/conditions which allow for (nested) logical combinations of conditions (for example to not hide blacklisted messages if they are sent by a channel mod or the broadcaster)

It would also allow to add other settings to a bucket to allow for scope-based settings (for example channel-based chat-layouts and direction, emote-sources and so on) which could be added later on, whenever they are implemented.

It would probably make sense to "evaluate" the bucket list and resolve the scopes at channel-loading time and generate a concise list of all settings and rules applicable for the current channel to speed up settings/rules lookup and application.

What do you think of this Concept?

**Comment by night** [comment]
Thanks for the detailed suggestion. While it's possible one could design such a system, it sounds pretty hard for most folks to configure and use. It really reads to me like I'm configuring firewall rules, and while that's something developers are great at I cannot imagine teaching the average user how to do that.

BetterTTV always tries to make the most accessible feature enhancements, which usually means favoring simplicity in its UI. We are working on enhancements to the extension to increase the usability and configuration of highlight/blacklist keywords, but realistically it will not include the level of detail this request proposes. You can track the progress of each of the related issues to know when we solve these requests. We merged regex support earlier today, for example.
