### ISSUE TITLE
Default emotes no longer showing in BTTV extension (Firefox)

### ISSUE THREAD

**Issue by randyr7** [night/betterttv#5837]
For some reason the BTTV extension is no longer showing default emotes that come with any given OS (like this skull for example: 💀). Any reason why that is?

**Comment by night** [comment]
The Twitter Emoji library we were using suddenly went offline today without notice. You need to wait for v7.4.41 to be released on Firefox, which changes the image hosting to our CDN.

**Comment by randyr7** [comment]
and how long do you think that will take?

**Comment by night** [comment]
> and how long do you think that will take?

Firefox reviews tend to take up to 24 hours during the business week.

**Comment by night** [comment]
The update has been approved and is now available.
