### ISSUE TITLE
Reverse Chat not working

### ISSUE THREAD

**Issue by jetpackpaul** [night/betterttv#5841]
Reverse chat has been working fine up until today randomly.

I didn't change any settings, but chat comes through normally with new messages at the bottom even though it says "reverse chat" is selected. 

It will still try to keep the scrolling towards the top of the window, but all new message still appear at the bottom.

**Comment by animalcookiez** [comment]
Yes, I am having the same issue.  The option to move new chat messages to the top also no longer appears in the BTTV settings menu.

**Comment by night** [comment]
this will be fixed in the next release
