### ISSUE TITLE
Aliased Emotes Should Provide Info on the Original Name

### ISSUE THREAD

**Issue by Nerixyz** [night/betterttv#5844]
Emotes in a channel that have a code alias should add information on the original name, so consumers of the `https://api.betterttv.net/3/cached/users/twitch/{id}` API can use this (e.g. when displaying tooltips). 

This could be the JSON returned:

```json5
{
  // ...
  "sharedEmotes": [
    // ...
    {
      "id": "60204552f11f4d6c9759352f",
      "code": "AlienPlsButItsAliased", // code for this channel
      "originalCode": "AlienPls", // optional, only included for aliased emotes
      "imageType": "gif",
      "animated": true,
      "user": {
        // ...
      }
    }
    // ...
  ]
}
```

**Comment by night** [comment]
Thanks for the report. Can you shed more light on the use case here? What would be the intent of providing the original name? Wouldn't that confuse users?

**Comment by Nerixyz** [comment]
I'm mainly thinking of Chatterino. There, a tooltip for an emote with an alias is displayed like this:

```
{name}
Alias of {original}
Channel {platform} Emote
By: {author}
```

<details>
<summary>Example</summary>

![firefox_2023-01-14_19-30-33](https://user-images.githubusercontent.com/19953266/212490117-e838af27-6569-41a5-b44a-fcdeca40529d.png)
</details>

**Comment by night** [comment]
Thanks for the clarification. We've extended the payload to include `codeOriginal`.
