### ISSUE TITLE
SAME ISSUE FROM A FEW WEEKS AGO/ PLEASE FIX

### ISSUE THREAD

**Issue by andrew1ups** [night/betterttv#5846]
https://github.com/night/betterttv/issues/5537  (<--- old thread)

HELP! Better TTV works, But when I select to reverse the chat in the options, nothing shows up.

I'm using obs and have relogged into everything just to see if that fixed it. i streamed yesterday and it was fine. today nothing was showing so i turned off better ttv and it fixed the chat issue. but when i selected to reverse the chat again, everything erased and wont show new or old messages. they are still being sent cuz i can see them on slobs, stream elements and chatty. just not obs when having the chat scroll up. this all started today. i have the extention downloaded on chrome as well. please help

**Comment by night** [comment]
duplicate of #5841

**Comment by andrew1ups** [comment]
ah ok someone already addressed it.
