### ISSUE TITLE
Tab to complete has list of bttv emotes

### ISSUE THREAD

**Issue by Mrbysco** [night/BetterTTV#585]
I've noticed that when I type Fire and press tab to get to someone's name it also lists FireSpeed... Which I dont want to... Its reason I enabled the emotes icon... So I could click to insert.
Is there a way for me to disable the tab to complete emotes... I only want to tab to complete usernames... 

I cant properly moderate with the emotes being in my list xD

-Mrbysco

**Comment by night** [comment]
The tab completion always prefers usernames over emotes. In other words, the first completed items in any tab completion is the usernames that begin with the typed characters.

There is not a way to disable tab completion for emotes, but you can prefix usernames with "@" to only receive usernames.
