### ISSUE TITLE
tagged user ping sound and message pop up doesn't appear

### ISSUE THREAD

**Issue by AbyssalTenacity** [night/betterttv#5868]
**Describe the bug**
tagged user ping sound and message pop up doesn't appear until tagging user timed out

**To Reproduce**
user 1 enable message pop up and user ping sound when @'d
user 2 ping user 1

**Expected behavior**
user 1 should have ping sound and message pop up for being tagged; 
instead this doesn't occur until user 2 timed out

**Desktop (please complete the following information):**

- OS: win 11
- Browser: chrome
- Version: 7.4.41

**Comment by night** [comment]
I'm not able to reproduce any issues with pinned highlights or highlight feedback in the latest version 7.5.0. If you're still having issues after updating, please let us know!
