### ISSUE TITLE
MOD icons are partly covered in the popup panel if clicking the last viewer commented

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#588]
![untitled](https://cloud.githubusercontent.com/assets/11561641/8835884/93b1d902-30bd-11e5-9712-73792301d9ad.png)

**Comment by night** [comment]
Have you tried dragging the moderator popup window higher? It's a movable popup..

**Comment by evodoc** [comment]
Yeah, I've tried moving it, but it'll popup at that place again the next time.
