### ISSUE TITLE
Dark Mode turns on everytime i go into theater mode

### ISSUE THREAD

**Issue by mikkellm** [night/BetterTTV#589]

**Comment by voloshink** [comment]
Twitch has its own dark mode for theatre mode

**Comment by mikkellm** [comment]
So white twitch in theater mode is not possible?

**Comment by voloshink** [comment]
I've never used theatre mode without dark mode in bttv, so i'm not sure if you can disable it

**Comment by mikkellm** [comment]
When i disable it for the first time it turns white until i reenter theater mode. Then it keeps shifting. Would be nice if it could stay white.

**Comment by voloshink** [comment]
Might be that we are hiding that option, i'll look into it, thanks for the report

**Comment by mikkellm** [comment]
Ive also noticed that when youre in theater mode the "Dark Mode" in the "cogwheel" settings popup cant be ticked on unticked. And when i leave theater mode, it says its ticked even though my twitch is white.

**Comment by vendethiel** [comment]
Yeah, you can't disable that, that's twitch's theater mode behavior.

I don't think bttv wants to a offer a "white theater page"

**Comment by night** [comment]
Refer to #491
