### ISSUE TITLE
Few text on main website page that should be added to translation file

### ISSUE THREAD

**Issue by Blueberryy** [night/betterttv#5899]
**Browser choose**
![opera_idUEVE6Ez3](https://user-images.githubusercontent.com/36592509/214286676-828beb4a-399c-4202-ad7c-da108b54879f.png)

**Search**
![opera_KwrhOrWBob](https://user-images.githubusercontent.com/36592509/214286890-3600152b-efc9-403d-9d3a-dc2c8a4be93c.png)

**Comment by dclstn** [comment]
Should be fixed now
