### ISSUE TITLE
A "Fullscreen with Chat" option

### ISSUE THREAD

**Issue by MrRoboto12345** [night/BetterTTV#590]
I would love for this to be considered as an option in the BTTV menu; I know https://github.com/night/BetterTTV/issues/342 mentioned this as a possibility back in April. A fullscreen viewing option for streams with an opaque chat (and invisible background) in the corner of your monitor. If we can have GIF emotes, then I'm sure that we can have this view-mode.

**Comment by night** [comment]
Please do not open a second issue for the same item... This accomplishes nothing but spamming our inboxes.
