### ISSUE TITLE
Emote search keywords does not accept non-latin characters

### ISSUE THREAD

**Issue by daviirodrig** [night/betterttv#5905]
**Describe the bug**
When adding search keywords on a emote, if the tag desired has accents like `cliché` or is non-latin scripts like cyrillic `да` (yes in russian) the tags are not added

**To Reproduce**

1. Go to add search keywords for any emote
2. Try adding a accented word
3. Tags are not updated

**Expected behavior**
Search keywords should accept these characters, so communities on other languages could use this feature as well.

**Additional context**
By looking in the developer console is clear that it is not accepting because of a regex that strictly pass only on latin characters

![image](https://user-images.githubusercontent.com/30713947/215020516-81fd3d8a-f23c-492f-b437-c7b5a74454da.png)

Also, if this is intended behavior a error should be shown to the user, for now the whole request is denied and other tags are not updated as well

**Comment by night** [comment]
i've changed the behavior of the validator to support unicode letters in addition to numbers now. hope it helps!
