### ISSUE TITLE
Blacklist keywords stopped working.

### ISSUE THREAD

**Issue by 02ismywaifu** [night/betterttv#5907]
I don't know if it was caused by a recent update or is it a problem on my side, but I used to paste emotes in "Blacklist keywords" so they won't show up. Stopped working like 3 days ago.

**Comment by night** [comment]
fixed already via 2a9d1fbb3e333a09d45d5c5146f78a4b303702fd

**Comment by 02ismywaifu** [comment]
but what do I do with that

**Comment by night** [comment]
you will need to wait for the next release.

**Comment by 02ismywaifu** [comment]
k, thanks

**Comment by AsheIsAmazing** [comment]
Seems to have regressed, blacklisted words are appearing again on my end with latest version.
