### ISSUE TITLE
Follower/subscriber icons next to names in chat to help moderators track who's following?

### ISSUE THREAD

**Issue by GreyRookTV** [night/BetterTTV#591]
(Not an issue but this is where it directed me to suggest features)

It would be nice if there were little icons next to anyone's name in chat (similar to the TwitchTurbo and moderator-sword incons) who follows/subscribes to the channel, that you could turn on to view as a moderator. That way you can see at a glance who in chat already follows the stream as they chat. If it were color coded based upon how long they've been following for, that'd be even cooler.

**Comment by voloshink** [comment]
Well. subscriber badges are already a thing in both the default twitch and betterttv. I don't really see the point of showing badges for followers, it takes one click to follow a channel, doesn't exactly tell you anything about the person.

**Comment by GreyRookTV** [comment]
Sorry, this thought is geared more towards followers in channels that are not partnered. (You are of course correct about subscribers)

My reasoning: in a busy chat there's sometimes a difference between what we put up with from strangers as opposed to followers. When you have hundreds of followers the names sometimes start to run together. 
As a mod, If someone new shows up and says "you suck" they'd get a time out. If someone who's been following for 5 months shows up and says "you suck" that it's probably a joke and so it takes less time, as a mod, to make the determination about who to purge and who to let be a smart alec. 
Right now to see if someone is a follower I have to go to their channel and look through their list of follows to see if they're a follower. That can take a few minutes and by that time they've already been a jerk in chat or made merry. 
it'd be nice to see as chat progresses who is following and who is not, as part of the chat.

That was my reasoning. 

Cheers! Thanks!

**Comment by night** [comment]
We have no way to know in realtime who is following the channel other than by excessively polling Twitch's API. This is a terrible solution that would just piss them off, so this feature will never be possible.
