### ISSUE TITLE
Unable to activate "Automatically collect bonus channel points" on Firefox

### ISSUE THREAD

**Issue by Inglonias** [night/betterttv#5910]
**Describe the bug**
Unable to activate "Automatically collect bonus channel points" on Firefox

**To Reproduce**

1. Go to any Twitch channel's chat
2. Open BetterTTV settings
3. Click the checkbox to auto claim bonus channel points.
4. Nothing happens and the box will not check. An error is logged to the console.

**Expected behavior**
The checkbox works.

**Screenshots**
![image](https://user-images.githubusercontent.com/2125926/215333672-54f12310-ef76-41fb-8d99-0e0fff80fd60.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home 22H2 (build is 19045.2486)
- Browser: Firefox
- Version: 109.0

**Additional context**

**Comment by night** [comment]
this is already fixed via https://github.com/night/betterttv/commit/d05d784a4d08b01980f5b638b14f052c67ba9f97

in the meantime, you can use the other setting for this underneath the channel points section of settings.
