### ISSUE TITLE
Highlight your username is applied to replies and mentions

### ISSUE THREAD

**Issue by Twichigo** [night/betterttv#5922]
**Describe the bug**
Highlight username also gets triggered by replies and mentions, when you use your own name for it. Additionally, it overwrites any other highlight rules for those messages.

**To Reproduce**

1. Go to 'Highlight Keywords' in BetterTTV settings
2. Add your own Twitch username under a username type
3. Recieve a reply to your message or get a mention in chat
4. Reply or mention will get highlighted with that highlight colour

**Expected behavior**
Highlight username only highlights messages that you send, when you use your username as a rule for it.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Vivaldi
- Version: 5.4.2753.51

**Additional context**
Even after adding your name under the message type, replies and mentions keep using the colour from the username type. Not only the issue adds highlighting in cases you might not want it to, but also prevents from using different colours for mentions and replies.

**Comment by night** [comment]
This behavior was already changed as of https://github.com/night/betterttv/commit/e637772a4641342e6b1acf225e635395464f3bae to only highlight messages when you have a Username highlight for your current user.

**Comment by Twichigo** [comment]
> This behavior was already changed as of [e637772](https://github.com/night/betterttv/commit/e637772a4641342e6b1acf225e635395464f3bae) to only highlight messages when you have a Username highlight for your current user.

While mentions got fixed, replies are still using username highlight colour. The picture below is ONLY with my username under username highlight type.
![34 48 0db3b4565a34](https://user-images.githubusercontent.com/123217314/217703314-c0372b31-a72f-493d-8105-2f3adfd83cb3.png)
