### ISSUE TITLE
BTTV not showing all emotes

### ISSUE THREAD

**Issue by JMD49591** [night/betterttv#5923]
**Describe the bug**
Can't see all emotes.

**To Reproduce**
1. Installed BTTV
2. Added Menu Button
3. Followed steps in [this guide](https://community.nightdev.com/t/betterttv-debugging/3685)

- Cleared all Cookies and Cache
- Disabled all other addons except for BTTV
- Even tried with disabling the Antivirus
- Getting the following output on https://cdn.betterttv.net/cdn-cgi/trace
```
fl=472f447
h=cdn.betterttv.net
ip=188.103.173.115
ts=1675467927.435
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
colo=FRA
sliver=none
http=http/3
loc=DE
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
kex=X25519
```
- Console says (I've only listed the errors):
1. HTTP Read Error, by some amazon.min.js
2. XML Processing Error: blob:https://www.twitch.tv/1f594e2d-5731-4827-bab9-e8946478b399
3. CORS Error with some file from sentry.io
4. Uncaught (in promise) undefined - I find this one the most interesting but there is no file or anything

**Expected behavior**
Can see all emotes.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36740020/216730370-bd2d3cc7-7da9-43a4-9385-fb6e436221a2.png)

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: FireFox
- Version: 109.0.1

**Additional context**
I got a new PC recently. On my old PC (Windows 10) BTTV worked perfectly fine. Now on my new PC - where I've imported all the configurations from my old browser (FireFox as well) - it doesn't.
The only things've I've not exported from my old PC were the browser addons. So I had to install those fresh. But even then, that should not be a problem with BTTV, right?

**Comment by ScrubN** [comment]
Majority of vedal987's emotes are 7TV. Enable 7TV in BTTV settings or install the 7TV extension and see if that fixes the issue

**Comment by JMD49591** [comment]
Seems to have worked.
The reason I've not tried that was because I got the warning. I've not read the full message.
Anyways thanks @ScrubN
