### ISSUE TITLE
7TV overlay emotes not overlaying

### ISSUE THREAD

**Issue by ScrubN** [night/betterttv#5925]
**Describe the bug**
Just like BTTV, 7TV provides overlay/zero-width emotes which aren't handled correctly by the BTTV extension. The flag should be `1 << 8` [in the v3 API response](https://github.com/SevenTV/Common/blob/4139fcc3eb8d79003573b26b552ef112ec85b8df/structures/v3/type.emote.go#L52).

**To Reproduce**

1. Enable 7TV in the BTTV extension
2. Send any regular emote + a zero-width emote such as RainTime or SteerR (both global)
3. See it is not properly overlayed

**Expected behavior**
The emote zero-width emote should overlay the previous emote

**Screenshots**
7TV Extension
![image](https://user-images.githubusercontent.com/72096833/216792822-13946b95-ee8e-4770-aa99-382ed0105896.png)
![image](https://user-images.githubusercontent.com/72096833/216793198-31b6f428-747f-4769-bd96-b9a96bf0d84c.png)

BTTV Extension
![image](https://user-images.githubusercontent.com/72096833/216792832-8d0734dc-518b-405f-b2ae-a7301d317419.png)
![image](https://user-images.githubusercontent.com/72096833/216793200-822fe6a8-5843-400c-befb-eb3be249637e.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Brave 
- Version: 1.47.186 Chromium: 109.0.5414.119

**Additional context**
I tried looking around to submit a PR for this myself but I'm not 100% sure where the 7TV flags are calculated

**Comment by ScrubN** [comment]
Looked a little farther into this. 7TV emote flags aren't acquired and the BetterTTV overlay emotes are [hard coded](https://github.com/night/betterttv/blob/master/src/modules/emotes/style.css), meaning implementing 7TV overlay emotes could be a bit annoying.

**Comment by NBruderman** [comment]
Can confirm this problem exists with the BTTV extension, regardless whether another extension is installed (FFZ or 7TV), as BTTV overrides them.
