### ISSUE TITLE
Not all the emotes I have on BTTV are showing up in Discord.  

### ISSUE THREAD

**Issue by JanetteRaven** [night/betterttv#5927]
Discord is not showing all the emotes I have on BTTV.  I have the slots available but they are not loading.   Attempted to sync it to discord and nothing changed.   I tried to disconnect and reconnect it to my Discord Server and now even less emotes are showing up.   This is on all devices.

**Comment by night** [comment]
The website displays error messages when they occur. I would recommend looking at the dashboard after the sync finishes to see what the error message states.

**Comment by JanetteRaven** [comment]
It never gave me any errors and still hasn't.  It just doesn't load half the emotes I have saved under BTTV.
