### ISSUE TITLE
[Bug] emote menu don't have translations for 7tv global emotes

### ISSUE THREAD

**Issue by Blueberryy** [night/betterttv#5933]
It exist on website but looks like not implemented
![opera_la45JEUfDs](https://user-images.githubusercontent.com/36592509/217308233-6089e278-1b48-48d5-8528-9fd3a9c3cb58.png)
![opera_DxMiqOpGmI](https://user-images.githubusercontent.com/36592509/217308238-09a322a2-3308-4b8e-a02a-01c5ad26e2de.png)

**Comment by night** [comment]
I'm not able to reproduce this in the current live release, 7.5.2. If problems persist, please let us know more information about your setup.
