### ISSUE TITLE
Highlight Keywords is highlighting messages replying to a user in the highlight messages username list

### ISSUE THREAD

**Issue by kli885** [night/betterttv#5937]
**Describe the bug**
Highlight keywords is highlighting (and pinning, if setting is enabled) messages that are replying to messages that fit the highlight keywords criteria. 
Example: In my highlight keywords list, I have it set to highlight messages from the user xQc. If someone replies to a message sent by xQc, that message is highlighted (and pinned).

**To Reproduce**

1. "User1" adds highlight messages from "User2"
2. "User2" sends a message
3. "User3" replies to "User2"
4. "User1" sees that "User3"s message is highlighted (and pinned) 

**Expected behavior**
The reply from "User3" should not be highlighted (and pinned) for "User1"

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge
- Version 109.0.1518.78

**Comment by Twichigo** [comment]
I believe this is the same issue as I noted [here](https://github.com/night/betterttv/issues/5922#issuecomment-1423534302). It can also be your username in the highlighted username keyword and replies to your messages will get highlighted with that when they shouldn't.

**Comment by night** [comment]
This behavior is currently working as intended. #4238 was requested and implemented so people are able to highlight replies in threads referencing them. If this is behavior you find conflicting for your use case, you might open up a discussion requesting a feature to disable this behavior.
