### ISSUE TITLE
None of the emotes is displaying

### ISSUE THREAD

**Issue by Floaingshade** [night/betterttv#5955]
The emotes isn't showing. i have tried removing it and adding it back but nothing works

**Screenshots**
![image](https://user-images.githubusercontent.com/91226402/219559758-07f15d55-70bf-405e-a9b0-d398bfdf2f6a.png)

- OS: [Windows 11]
- Browser [chrome]
- Version [110.0.5481.104]

**Comment by night** [comment]
I am not able to reproduce any issues. Be sure to enable all the emote types under the `Emotes` category in the BetterTTV Settings.
