### ISSUE TITLE
BTTV Feature Request

### ISSUE THREAD

**Issue by jaykoss** [night/BetterTTV#596]
Hello Night! I am an avid Twitch user being a streamer and a long time viewer. I have always found it to be a problem with reading chat due to my poor eye sight. It would be appreciated if you could implement a way to increase chat text size. 

     Sincerely, JayKoss

**Comment by vendethiel** [comment]
Isn't ctrl-scroll enough?

**Comment by jaykoss** [comment]
No because the chat is the only problem, it would make the rest of the text too large

**Comment by night** [comment]
Duplicate of #57
