### ISSUE TITLE
Unable to add channel editor

### ISSUE THREAD

**Issue by ScrubN** [night/betterttv#5967]
**Describe the bug**
I'm unable to add an editor to my channel in the dashboard. I have tried my typical firefox and chromium installs, as well as a completely fresh chromium with no success. The logged error message says the GET request returned 404.

**To Reproduce**

1. Login to https://betterttv.com
2. Go to https://betterttv.com/dashboard/editors
3. Enter the name of a trusted twitch user and click "Add"
4. Editor add box turns red, see console for error

**Expected behavior**
The user is added as a channel editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/72096833/220198613-6290d99e-8669-4e52-9634-c5c45c22465d.png)
_The firefox log contains more details about the Http request, but I'm unsure what information is sensitive._

**Desktop (please complete the following information):**

- OS: Windows 10 22H2
- Browser:
   - Firefox 110.0 (64-bit)
   - Brave 1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit) 

**Additional context**
Although it is not mentioned anywhere, I added the trusted user as a channel moderator to see if that makes a difference.

**Comment by night** [comment]
The person you are adding is not registered on the BetterTTV website. You will need to ask them to register an account first.

**Comment by ScrubN** [comment]
That was indeed the issue. Perhaps it should be displayed somewhere on the website
