### ISSUE TITLE
Firefox - Highlights and Blacklist not functioning

### ISSUE THREAD

**Issue by AsheIsAmazing** [night/betterttv#5971]
**Describe the bug**
On the latest version of firefox, the highlight message and blacklist message features are non-functional and neither highlight nor blacklist messages on both live chat and VODs.

**To Reproduce**

1. Use a firefox browser
2. Set up a highlight message or blacklist message
3. Type the highlighted or blacklisted message into a chat
OR
3. Find a VOD with the highlighted/blacklisted message
4. See that it is not affected by your settings.

**Expected behavior**
The features do what they did up to about a week ago, functioning normally.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 110 (latest)

**Comment by ScrubN** [comment]
Both highlight and blacklist work in live chat for me. Brave 1.48, extension 7.5.2

**Comment by night** [comment]
I am not able to reproduce any Firefox-specific issues. If you have working steps to reproduce, please provide them.
