### ISSUE TITLE
Chat State Countdown Resets on Outgoing Whispers

### ISSUE THREAD

**Issue by arkiolok** [night/BetterTTV#598]
In the chat time counter in slow modes, add support for whispers. It starts counitng even if you whisper to somebody. Fix it. Same problem with the sub mode either. If you chat in sub mode and you are not a sub. It starts counting again.

**Comment by arkiolok** [comment]
And I found out that if you the channel is in sub mode and you whisper somebody, it startes counting again.

**Comment by voloshink** [comment]
"Fix it." Oh, okay, boss.
