### ISSUE TITLE
Anonymous chat showing wrong message

### ISSUE THREAD

**Issue by PrincessRTFM** [night/betterttv#5986]
**Describe the bug**
When I enable anonymous chat, rather than the message I used to see about logging in or out of chat, I get `US$NaN total raised so far for ! NaN more days to show support. Cheer and include . Learn More at ` instead, complete with trailing space.

**To Reproduce**

1. Enable anonymous chat
2. Load a channel and enter chat
3. Wrong message is displayed
4. Use `/join` to enter chat non-anonymously
5. The same wrong message is displayed again

**Expected behavior**
Previously, I saw a message about BTTV logging me out of chat when entering chat, and a different one about logging me into chat when I used `/join`; this is what I would expect to continue seeing.

**Screenshots**
[Both messages are visible here](https://user-images.githubusercontent.com/8753564/222003417-87d9f382-8bae-4dc7-b293-18dbd5e0fbfd.png); the first was upon entering chat, and the second was after typing `/join` into the chat box and pressing enter.

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: firefox 110.0 (64-bit)
- Version: BTTV 7.5.2

**Additional context**
This only changed recently. As little as two days ago, I was seeing the correct messages instead.

**Comment by dclstn** [comment]
Looks to be a bug with all slash commands, thank you for bringing this to our attention.

**Comment by night** [comment]
fixed via df5615a00e71c30785b72af1a8deada4df5df7f3
