### ISSUE TITLE
/chatters command outputs weird text and no chatter counts

### ISSUE THREAD

**Issue by sim-** [night/betterttv#5990]
**Describe the bug**
/chatters command outputs "$NaN total raised so far for ! NaN more days to show support. Cheer and include . Learn More at "

**To Reproduce**

type /chatters

**Expected behavior**
Expected "Chatter count: 1234" or similar

Chrome 110.0.5481.105, mix of extensions or just BetterTTV enabled

**Comment by night** [comment]
fixed via df5615a00e71c30785b72af1a8deada4df5df7f3
