### ISSUE TITLE
$NaN Raid Message

### ISSUE THREAD

**Issue by NoobarDanu** [night/betterttv#5995]
**Describe the bug**
Similar to #5990 whenever someone raids a channel instead of giving the raiders name and how many people have raided the following error pops up

$NaN total raised so far for ! NaN more days to show support. Cheer and include . Learn More at 

**To Reproduce**
Be in a twitch channel when someone raids them.

**Expected behavior**
Expected behavior is to show the persons name and how many people have raided the channel

**Screenshots**
https://postimg.cc/jWHZVRD3

**Desktop (please complete the following information):**

- OS: Fedora Linux 37 (Xfce) x86_64 
- Browser: Firefox 
- Version: 110.0 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Twitch support states it is a 3rd party extension issue and bttv is the only extension enabled when this happens.
https://twitter.com/TwitchSupport/status/1630923310291730432

**Comment by night** [comment]
Bug is fixed as of 7.5.3. Swap to Chrome or Edge instead to get updates faster. Firefox reviews take 1-2 weeks right now.
