### ISSUE TITLE
Just A Question About The Mod Cards

### ISSUE THREAD

**Issue by Outsanity** [night/BetterTTV#600]
In the screenshot below, Left Card is when you click on a name in the chat. Right Card is when you click a name in the viewer list. Is there a way to get that info on the Left Card to show up on the Right Card or is there a reason it can not be done?

![screenshot for reference](http://puu.sh/jeQzd.png)

**Comment by night** [comment]
The viewer list is under Twitch's control, not ours. Because of that, we cannot replace the click handlers without editing their functions. We are not willing to edit their functions, so this cannot be fixed.
