### ISSUE TITLE
BetterTTV Settings not available in YouTube live chat

### ISSUE THREAD

**Issue by r0senove** [night/betterttv#6004]
**Describe the bug**
Previously i can change settings in live chat setting YouTube (triple dot), but now i can't change the settings. I already turn off any extensions at my browser, just BetterTTV extension and still no settings at Live Chat YouTube.

**To Reproduce**

1. Go to YouTube (login or not).
2. Click on any Live Stream that have live chat open.
3. Tap triple dot on that Live Chat upper right corner.
4. No BetterTTV settings anymore.

**Expected behavior**
Can see and changing BetterTTV Settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/64626705/223507171-4aa76bae-c0f1-478b-ba72-e65868bcdc02.png)
*Need to sensor with x letter*

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Chrome & Microsoft Edge
- Version: Windows (Version 22H2. OS Build 19045.2604), Chrome (110.0.5481.178) & Edge (110.0.1587.63)

Thank you!

**Comment by BIGSonnyKing** [comment]
Do not mean to reopen this, as it's been closed and resolved, but I'm also having this problem and can't seem to figure out how upload/install the new code, or to even know where to install it at. Newbie here. Is there any step by step guide showing how to implicate this?

**Comment by night** [comment]
We just haven't released this change yet. It will be in the next version.

**Comment by Fabian9799** [comment]
Seems to be broken again

**Comment by Fabian9799** [comment]
I had the release version installed. Just tried it with the dev version and everything works fine. I was under the impression that it was already in the release version since it was closed over a month ago
