### ISSUE TITLE
emote modifiers dont work

### ISSUE THREAD

**Issue by Fel1xxxxx** [night/betterttv#6005]
Describe the bug
-
im sending this message
![image](https://user-images.githubusercontent.com/108614975/224488935-68c4a001-3cba-441a-92df-012170c9c936.png)
then it appears like this
![image](https://user-images.githubusercontent.com/108614975/224488975-eb174f27-3af8-49d2-bece-48d9b357ca89.png)
but has to appear like this
![image](https://user-images.githubusercontent.com/108614975/224489008-aa940ab7-471c-4f4d-8722-14614d13d3c0.png)
idk what to do
*im writing w!,h!,v!, or z! before the message but then it dissapears but nothing happens to emote

To Reproduce
-
idk how to

Desktop (please complete the following information):
-
OS: Windows 11
Browser: Microsoft edge
Version: 110.0.1587.63

**Comment by dclstn** [comment]
Other extensions break this functionality, iirc 7TV removes the modifier entirely and hasn't implemented any support for it.

**Comment by Fel1xxxxx** [comment]
> Other extensions break this functionality, iirc 7TV removes the modifier entirely and hasn't implemented any support for it.

but chatters do not have this problem, but I have

**Comment by Fel1xxxxx** [comment]
> Other extensions break this functionality, iirc 7TV removes the modifier entirely and hasn't implemented any support for it.

maybe you can somehow set a higher priority for bttv?

**Comment by mparmpuni** [comment]
Sorry for hijacking this but is there an option to turn off these modifiers? I don't like how the emotes look with them. they're big/blurry and distracting. I have turned off the animations until hover but I'd rather turn off just the modifiers. Only using bttv extension.

**Comment by dclstn** [comment]
> Sorry for hijacking this but is there an option to turn off these modifiers? I don't like how the emotes look with them. they're big/blurry and distracting. I have turned off the animations until hover but I'd rather turn off just the modifiers. Only using bttv extension.

A setting should appear in the next patch to toggle these modifiers: ccb22875f7c9bd5c98b67dcba64c60c649a63f44

**Comment by Fel1xxxxx** [comment]
fixed by uninstalling bttv and 7tv as extensions in chrome and adding them as extension in FFZ
