### ISSUE TITLE
Not redeeming channel point chests

### ISSUE THREAD

**Issue by charran15** [night/betterttv#6006]
Using Firefox, the app hasn't been auto redeeming the green bonus channel point chests that appear after watching for so long. I do not have the Youtube portion enabled, though I do have youtube open on a different tab. I do not have another twitch tab open. 

**To Reproduce**

1. Do not have the Youtube option on
2. Have a youtube tab open to any video
3. Go to any stream on twitch.tv and watch for awhile till you start earning channel point chests
4. Observe the chests as they appear and not auto redeemed

**Expected behavior**
Channel Point chests are auto redeemed

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Home
- Browser Firefox
- Version 110.0.1 (64-bit)

**Additional context**
I do have tweetdeck also up with bettertweetdeck installed

**Comment by night** [comment]
First, can you verify that you have enabled the "Auto Claim -> Bonus Channel Points" in the BetterTTV settings? This defaults to Off and sometimes settings can be reset.

If problems persist, can you verify if you have the Twitch tab hidden when the stream is on?

**Comment by night** [comment]
Closing this due to lack of response. If you're still having issues, please let us know!
