### ISSUE TITLE
Followed Streamers Badge

### ISSUE THREAD

**Issue by ExoticWater** [night/BetterTTV#601]
Hi I think you guys should add where whoever you follow gets a badge beside there name and then if you were in there stream or someones stream if they chat it pops up by there name and then you can easily see your followed streamer.

**Comment by samfun123** [comment]
See #591

**Comment by night** [comment]
This does not seem like a useful feature and just adds clutter to the chat. If you just want to know when people you follow chat, you can refer to issue #94
