### ISSUE TITLE
Emotes unlocked with сhannel points

### ISSUE THREAD

**Issue by ten4dinosaur** [night/betterttv#6021]
Then using BetterTV emote picker, emotes unlocked with сhannel points show up as locked.

**Comment by ten4dinosaur** [comment]
Update: It only shows up as locked on the channel where it was unlocked

Example:
  1) Unlock emote using points on сhannel 'A' - emote shows up as **locked**
  2) Go to сhannel 'B' - emote shows up as **unlocked**
  3) Return to сhannel 'A' - emote still shows up as **locked**

**Comment by night** [comment]
Interesting bug.. does the emote work outside of the emote menu? i.e. if you type the emote, does it render in the chat box and post to chat?

**Comment by ten4dinosaur** [comment]
Yes, the emote shows as locked only in BetterTV's emote picker. In other cases: keyboard typing/twitch emote picker/CtrlC+V/chat box/posting to chat, everything works fine

**Comment by ten4dinosaur** [comment]
Also just found. May be this is the case. In channel where emote was originally unlocked, in realty, BetterTV's emote picker shows 2 emote with same name. Let's call them: 1) Type1 = (description: "from <chanel name>"), 2) Type2 = (description: "from channel_points")
"Type1" showed up as locked, "Type2" showed up as unlocked. But if I add "Type2" emote to favorites, BetterTV shows "Type1" emote instead in favorites on the channel where the emote was originally unlocked. And "Type2" emote on all other channels.
So, this is not bug of emote picker itself, but "favorites" implementation bug

**Comment by night** [comment]
That's a good catch. We only store one reference of the emote in memory, so my guess is that the record is being overwritten with its locked derivative. I think we should be able to figure this out now.
