### ISSUE TITLE
Blacklisting keywords does not work anymore

### ISSUE THREAD

**Issue by qinderium** [night/betterttv#6050]
![image](https://user-images.githubusercontent.com/101942890/228246657-dae45ca0-22fd-4a52-8cbc-8f54c4262503.png)
![image](https://user-images.githubusercontent.com/101942890/228251159-89362875-3584-4d74-be69-c8137479e40a.png)

**Comment by l-Crynic-l** [comment]
same for me, tried on firefox, opera gx, and chrome

**Comment by night** [comment]
Do you also happen to use 7TV? We've heard some reports that their extension intentionally breaks BetterTTV and FrankerFaceZ, and you may need to uninstall it to fix this issue. There should be a 7TV emotes option in both BetterTTV and FrankerFaceZ you can enable instead, so you can still enjoy the emotes from their add-on.

**Comment by l-Crynic-l** [comment]
Hey night, thanks for the reply. I tried disabling 7tv and the bttv blacklist works now. Not sure about ffz, in my experience ffz overwrites priority over both bttv and 7tv.

**Comment by Venomisto** [comment]
There probably needs to be a comment in the options menu about this so users know why it's not working, I had wondered why it was broken for a while now. I thought it was just broken for vods because that's what I mainly watch, but disabling 7tc fixed it. Thanks.

**Comment by night** [comment]
We've created and pinned this issue https://github.com/night/betterttv/issues/6060 for more info. Thanks for the suggestion about the options menu. That's something we may need to look into.

**Comment by qinderium** [comment]
> Do you also happen to use 7TV? We've heard some reports that their extension intentionally breaks BetterTTV and FrankerFaceZ, and you may need to uninstall it to fix this issue. 

Thank you pretty boy it works <3
