### ISSUE TITLE
cant clear the chat

### ISSUE THREAD

**Issue by Hosea1337** [night/betterttv#6054]
i have bttv, 7tv and ffz extensions and while 7tv is on i cant use "clear the chat" feature on bttv, can it be fixed by bttv or 7tv is causing the problem?

**Comment by dclstn** [comment]
We've heard some reports that their extension intentionally breaks BetterTTV and FrankerFaceZ, and you may need to uninstall it to fix this issue. There should be a 7TV emotes option in both BetterTTV and FrankerFaceZ you can enable instead, so you can still enjoy the emotes from their add-on.

**Comment by night** [comment]
Please refer to https://github.com/night/betterttv/issues/6060 for more info.
