### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Monkey151546** [night/betterttv#6055]
As the title says, the "set font size" doesn't work, no matter what number i put in, the text stays the same size

**Comment by ScrubN** [comment]
Do you have the 7TV extension enabled? It completely overrides chat rendering, meaning the Bttv extension can't affect chat apearance at all.

**Comment by Monkey151546** [comment]
Yeah I realized it after reading some of the bug threads, I was wondering why font size and split chat were't working.. I know now, thanks

**Comment by night** [comment]
Thanks for the report. We're unfortunately not able to address this, though! Please refer to https://github.com/night/betterttv/issues/6060 for more info.
