### ISSUE TITLE
BetterTTV Emotes such as PauseChamp not showing

### ISSUE THREAD

**Issue by AStar-inthe-Universe** [night/betterttv#6059]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AStar-inthe-Universe** [comment]
![Screenshot 2023-04-03 005353](https://user-images.githubusercontent.com/129720380/229423426-c93a86c6-ba39-4e55-af53-4dc5c80d83c2.png)

**Comment by AStar-inthe-Universe** [comment]
They preview the emotes but they don't post in Twitch chat.

**Comment by night** [comment]
Thanks for the report. We're unfortunately not able to address this, though! Please refer to #6060 for more info.
