### ISSUE TITLE
7TV Incompatibility & Anti-Competitive Behavior

### ISSUE THREAD

**Issue by night** [night/betterttv#6060]
It's unfortunate, but due to a recent update to 7TV it is no longer compatible with BetterTTV and all other extensions affecting Twitch chat.

**To restore BetterTTV's functionality (and any other extensions that you have installed), the only current fix is to uninstall 7TV and enable the 7TV emotes in the BetterTTV settings**.

To learn more, you can continue reading..

This change appeared to be intentional as of the release of their new version 3 update. In this release they are now rendering a new custom chat, bypassing the native Twitch chat that BetterTTV and other extensions rely on. You can learn more about the developer's response [here](https://github.com/SevenTV/Extension/issues/399) where a user reported their other extensions breaking. To quote their lead developer from this issue:

> AnatoleAM commented Mar 28, 2023 3:10AM ET:
> Do not install 3 plugins that all do roughly the same things, that'll solve your problems.

This response leads us to believe that this change was intentional anti-competitive behavior to cause users to uninstall other extensions. This is further evidenced by the introduction of a new "Compatibility" settings page encouraging you to uninstall other Twitch extensions.

BetterTTV prides itself on being less invasive to Twitch's platform by performing primarily style modifications and content changes. This allows other extensions to continue to function as close to native Twitch as possible for better compatibility.

We hope 7TV reconsiders the changes they've made here, but for now you may have to now choose between them 😔

**Comment by Jfamig** [comment]
This is not very poggers of you, night
