### ISSUE TITLE
bttv channel emotes suggestion

### ISSUE THREAD

**Issue by thomas1219** [night/BetterTTV#607]
some channels have specific emotes made for bttv but can only be used if the channel enables a users bttv for use in their chat such as the ditto emote. it would be nice to get rid of the need to have to enable the use of other users bttv emotes and just allow the use of all users bttv emotes on any channel

**Comment by vendethiel** [comment]
I don't get it. You want to make BTTV emotes available for anyone, even if they don't have BTTV installed? That's impossible

**Comment by voloshink** [comment]
I think he's suggesting that we make all custom bttv emotes global

**Comment by cletusc** [comment]
> I think he's suggesting that we make all custom bttv emotes global

...which is a terrible idea and would quickly become crowded, if it's not already.

:-1: -1 from me.
