### ISSUE TITLE
7TV channel specific emotes not being loaded on all channels.

### ISSUE THREAD

**Issue by Nyannika** [night/betterttv#6071]
**Describe the bug**
BTTV fails to load 7TVchannel specific emotes on some channels. Some channels they load just fine, like in my case https://www.twitch.tv/ironmouse the emotes show up with no issues, but other channels like https://www.twitch.tv/pokelawls 7TV channel emotes don't load at all. Neither in the emote menu nor in chat.

**To Reproduce**
1. Open the bttv emote list
2. 7TV channel emotes selection doesn't show up, 

**Expected behavior**
7TV channel emotes should show up 

**Screenshots**
No 7tv channel emotes load in the BTTV emote list.
![image](https://user-images.githubusercontent.com/113811760/229873967-fcabea92-2e7f-4d50-b5d4-01594aa7c21b.png)

Channel does in fact have active 7TV channel specific emotes.
![image](https://user-images.githubusercontent.com/113811760/229874339-6dac814b-0f3f-4650-bd98-22b1ba007885.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 111.0.1, Chrome 111.0.5563.147

**Additional context**

**Comment by night** [comment]
I believe this is fixed via fd727f15b70834caec63bbae9ebd3a2612f1f880, which will be in the next update.

**Comment by ScrubN** [comment]
After adding a single unlisted emote to my personal emote set, the entire set fails to show in the BTTV extension. The set does not contain any deleted content.

Tested on brave 1.50.114 chromium 112.0.5615.49 & firefox 111.0.1, extension 7.5.3.
