### ISSUE TITLE
CORS Error on API Request

### ISSUE THREAD

**Issue by Speedfighter** [night/betterttv#6074]
**Describe the bug**
I try to get emotes from the BetterTTV API by using Axios on an website and i always become CORS Errors.
When i implement these feature to my website it was working fine. This was in october 2022.

**To Reproduce**

With these code i get the errors.

```
const httpBTTV = axios.create({
    baseURL: 'https://api.betterttv.net/3/',
    timeout: 90000,
});

const globalBTTVEmotes = await httpBTTV.get('/cached/emotes/global')
```

**Expected behavior**
A reply from the API with following content: 
```
[
    {
        "id": "54fa8f1401e468494b85b537",
        "code": ":tf:",
        "imageType": "png",
        "animated": false,
        "userId": "5561169bd6b9d206222a8c19"
    },
    {
        "id": "54fa8fce01e468494b85b53c",
        "code": "CiGrip",
        "imageType": "png",
        "animated": false,
        "userId": "5561169bd6b9d206222a8c19"
    },
...
```

**Screenshots**
[Browser Console](https://i.imgur.com/7Tw2Myu.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Opera GX, Edge
- newest Versions

**Comment by night** [comment]
You may need to inspect your CORS configuration, as it should not be issuing an OPTIONS request for this path with a GET.

try comparing your request to something like fetch:
```
fetch('https://api.betterttv.net/3/cached/emotes/global').then(r => r.json()).then(data => console.log(data))
```

**Comment by Speedfighter** [comment]
Yeah thats the problem. I dont know why axios doing this options request but now I use only fetch and the problem is solved.
Thanks for your help
