### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gazaway** [night/BetterTTV#608]
I would like to see an "Automatically Hide Chat" option on BTTV. I feel that it would be great for users that absolutely despise the Twitch.tv chat room experience. It'd be extremely simple to implement and would be quite useful.

**Comment by cletusc** [comment]
This is already able to be done natively. Click the arrow to hide the chat. It should stay hidden on all channels until you unhide it.

![](http://i.imgur.com/Imvuze7.png)
