### ISSUE TITLE
Timestamps on VODs don't send you to their respective moment

### ISSUE THREAD

**Issue by CoolG0110** [night/betterttv#6111]
Sorry in advance if I'm blind and didn't notice some settings related to it / if this is related to a different extension / intended, but basically when I click on a timestamp in any comment of the VOD it doesn't teleport me to that moment of the stream.

i'm using Yandex currently which is basically the same thing as Chrome (and Windows 10 if that's relevant)

![welp](https://user-images.githubusercontent.com/74597482/234114503-7c629a1a-14ca-42c9-b089-2280c094b629.PNG)

**Comment by night** [comment]
BetterTTV does not render these timestamps. You may need to report this bug to Twitch or whatever other extension you may use.
