### ISSUE TITLE
"Disable name colors" does not disable name glows

### ISSUE THREAD

**Issue by shuddertrix** [night/BetterTTV#612]
With "Disable name colors" enabled, name glows (appears to be a grandfathered feature?) still appear.
![2015-07-31_08-39-52](https://cloud.githubusercontent.com/assets/4044049/9007503/fcc1b892-375f-11e5-8740-ed90fdd4aa88.png)

**Comment by night** [comment]
As the description of that feature states, it's meant for people who suffer from color blindness. It doesn't disable name glow.

Glow is a feature for some of my subscribers, most of which have been subscribed since 2013. This feature cannot be disabled, sorry.
