### ISSUE TITLE
Pause when you open the stream

### ISSUE THREAD

**Issue by Spuner** [night/betterttv#6128]
If you disable the automatic playback of the video player on the Twitch home page, the streaming is paused (twice) when you open any stream.

Tested on the latest version of Chrome.

If necessary, I can record a video to make it easy to see.

![Screenshot](https://user-images.githubusercontent.com/30773815/236606298-ac4b52d2-a2ba-4659-b37d-da0dafbb9160.png)

**Comment by ThiaudioTT** [comment]
I tried to reproduce. But everything here worked perfectly.

**Comment by night** [comment]
I am not able to reproduce this either!

**Comment by Spuner** [comment]
I'll record a video today or tomorrow and try to show it on video...

**Comment by Spuner** [comment]
After numerous tests, it became clear that this bug occurs if the browser is set to a language other than English.

Here is a **[video](url=https://mega.nz/file/Ah1DAb6J#lgIjCjcBYwT1MbCNDKAf2KbuPWwkbEN-Yl6tu2Nn4ds)**.

**Comment by ThiaudioTT** [comment]
Reopen the issue, then.

**Comment by Spuner** [comment]
Can't this topic be reopened so as not to create a new one?

**Comment by ThiaudioTT** [comment]
> Can't this topic be reopened so as not to create a new one?

Yes, I think only the @night can do it
