### ISSUE TITLE
Deleted messages in chat not showing up

### ISSUE THREAD

**Issue by Lenkradfreek** [night/betterttv#6145]
I have the following problem:

When I set the deleted messages setting to "do what twitch normally does", deleted messages are actually not deleted but shown as normal messages. The other two options for deleted messages work perfectly fine, only when I select the "do what twitch normally does" setting, it does not show the "this message was deleted" in italic font but it just leaves the message in chat as if it wouldn't have been deleted. I tested this on Firefox and Chrome (both fresh install + cookies deleted) as well as on both of my Windows-PCs.

**Comment by dclstn** [comment]
Fixed via 6bf4f5b880ebbf468f4e30fd12256864d3cd8b24
