### ISSUE TITLE
BetterTv Emotes not showing on overlay in streamelements

### ISSUE THREAD

**Issue by princesspinball** [night/betterttv#6159]
My emotes used to show up on the overlay but now they just display the text version of the emote. I've tried restarting my computer, I even reloaded my chat and emotes setup in Streamelements but it's still not working. I've seen multiple people have this issue but with no solutions.

**Comment by dclstn** [comment]
You should contact StreamElements for help, we cannot provide advice on integrations.

**Comment by princesspinball** [comment]
Can you give me the contact info? The website told me to post here. So, the issue isn't closed because it isn't fixed lol

**Comment by dclstn** [comment]
The issue doesn't pertain to BetterTTV the extension. Stream Elements offers an integration with BetterTTV by displaying our emotes in an overlay setting, closing as there is nothing to resolve here.
