### ISSUE TITLE
7TV Integration Crashes Extension Settings Menu, Preventing Reopening

### ISSUE THREAD

**Issue by Lyceris-chan** [night/betterttv#6173]
**Describe the bug**
When attempting to toggle the 7tv integration option from the settings menu, the bttv menu unexpectedly closes and refuses to reopen. This issue arises solely from toggling the 7tv integration option.

**To Reproduce**
Open the settings menu.
Locate the 7tv integration option.
Toggle the option.
The bttv menu instantly closes and remains closed, preventing further access.

**Expected behavior**
Toggling the 7tv integration option should not cause the menu to close abruptly. The menu should remain open, allowing for continued interaction.

Desktop (please complete the following information):
Chromium
Version 113.0.5672.127 (Official Build, ungoogled-chromium) (64-bit)
Windows 11 22621.1702

[www.twitch.tv-1685185279268.log](https://github.com/night/betterttv/files/11581647/www.twitch.tv-1685185279268.log)

**Comment by night** [comment]
From the logs it looks like your settings storage may be corrupted for either the blacklist or highlight settings. Try resetting your settings to default in the about tab of settings, and seeing if that helps. You may also backup your settings first on that same page if you don't want to accidentally lose them.
