### ISSUE TITLE
Lost of settings after browser closing

### ISSUE THREAD

**Issue by MikeZeDev** [night/betterttv#6174]
**Describe the bug**
title is enough

**To Reproduce**
My Firefox is set up to clean cache cookies and stuff after closing. Doing that clear BTTV settings.

**Expected behavior**
Setting should be preserved, like for any other addons.

I use Firefox 113 but that should no be relevant. 

**Additional context**
I know you use local storage to store the settings. I know about #5707 and the user was kinda rude. 
I also whitelist twitch domains but it makes me stay logged so wiping data at closing lose its purpose.

I have like a crapload of addons, with their own settings. Whatever id do (like using Bleachbit to purge some stuff) i never ever lose any setting. BTTV is the only one with that problem.

Any technical reasons to still use local storage? Would you consider a PR to switch (i dont know anything about extension coding but i could try, maybe)?  Its even stated in Firefox documentation that localstorage shouldnt be used to store extension data, because clearing localstorage is an expected behavior : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage
  
>  Although this API is similar to [Window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) it is recommended that you don't use Window.localStorage in the extension code to store extension-related data. Firefox will clear data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons, while data saved using the [storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) API will be correctly persisted in these scenarios.

Thank for this nice addon anyway.

**Comment by night** [comment]
Thanks for the report, but this appears to be less of a bug and more of a feature request. Feel free to refile this as such under discussions, but https://github.com/night/betterttv/discussions/5853 may be more relevant instead.
