### ISSUE TITLE
BetterTTV starts not all the time

### ISSUE THREAD

**Issue by Hellfighter23** [night/BetterTTV#618]
I have an Problem with BetterTTV.
This Plugin starts not all the time when I`m going to twitch.
I have you can help everyone with this Problem.
I have try to uninstall and a new install.

**Comment by voloshink** [comment]
So the plugin just doesn't load when you go to twitch? which browser are you using?

**Comment by Hellfighter23** [comment]
So the plugin just doesn't load when you go to twitch? ->  Yes
which browser are you using? ->  Google Chrome the nee St Version on Windows 10. I have the same problem on Windows 8.1

**Comment by voloshink** [comment]
Are there any errors in the browser console? you can press F12 to bring it up.

**Comment by Hellfighter23** [comment]
This say my console. When I go to twitch.tv.

JQMIGRATE: Logging is active
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:17 JQMIGRATE: jQuery.browser is deprecated
content.js:15 VK. Startup (background is ready)
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:15 The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
content.js:15 VK. Startup (background is ready)
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 No cast extension found
betterttv.js?0.6327330775093287:52 Uncaught TypeError: $(...).TrackpadScrollEmulator is not a function
http://api.twitch.tv/api/channels/hellfighter19/payout_entity?on_site=1 Failed to load resource: the server responded with a status of 404 (Not Found)
content.js:15 VK. Startup (background is ready)
content.js:15 VK. Startup (background is ready)
http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&correlator=863…ga_vid=2014130410.1438212465&ga_sid=1438557090&ga_hid=798777930&ga_fc=true Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
content.js:15 VK. Startup (background is ready)
content.js:15 VK. Startup (background is ready)
s-dal5-nss-34.firebaseio.com/.lp?dframe=t&id=41703652&pw=vOU6jPtInD&ns=ttv-30:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16 GET http://api.twitch.tv/api/channels/taketv_csgo2/product?on_site=1 404 (Not Found)send @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16p.extend.ajax @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16n._ajax @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30n.get @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30t.default.defineModel.request @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63444t.default.Mixin.create.loadMore @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63444t.default.Mixin.create.load @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63444(anonymous function) @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63443p @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:5n @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:9ne.create @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:9d @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:5create @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63444r @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:6c.findOne @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63444t.default.Controller.extend.setCurrentChannelRoom @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63440e.default.t.default.Route.extend.setupController @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63445_ @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:6r @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:6$.extend.setup @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:7m @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13f @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13f @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13(anonymous function) @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13a @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13p @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13g @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13(anonymous function) @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:13b @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:14y @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:14g @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:14(anonymous function) @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:8r.invokeWithOnError @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:2r.flush @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:2n.flush @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:2s.end @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:2(anonymous function) @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:2
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16 GET http://api.twitch.tv/api/channels/hellfighter19/payout_entity?on_site=1 404 (Not Found)send @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16p.extend.ajax @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16n._ajax @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30n.get @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:31B @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18j @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18xt @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18
content.js:15 VK. Startup (background is ready)
content.js:15 VK. Startup (background is ready)
content.js:15 VK. Startup (background is ready)
content.js:15 VK. Startup (background is ready)
content.js:15 VK. Startup (background is ready)
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: CAP.
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16 GET http://cdn-static.liverail.com/js/companions.js?_=1438557092171 net::ERR_BLOCKED_BY_CLIENTsend @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16p.extend.ajax @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16p.(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16p.extend.getScript @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16n.ensureLiveRail @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:31(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:31F @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18et @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18n.prepareCompanionAds @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:31e.default.t.default.Component.extend.onFlashReady @ emberapp-8ad1bf605ed8fe190b513aae9c96dfd8.js:63439B @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18j @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18D @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18xt @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:18
gpt.js?_=1438557092172:94 GET http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html net::ERR_BLOCKED_BY_CLIENTLe @ gpt.js?_=1438557092172:94(anonymous function) @ gpt.js?_=1438557092172:95(anonymous function) @ gpt.js?_=1438557092172:98
gpt.js?_=1438557092172:82 GET http://pagead2.googlesyndication.com/pagead/show_companion_ad.js net::ERR_BLOCKED_BY_CLIENTe.I @ gpt.js?_=1438557092172:82e.enable @ gpt.js?_=1438557092172:22(anonymous function) @ gpt.js?_=1438557092172:33r @ gpt.js?_=1438557092172:6Qd @ gpt.js?_=1438557092172:33(anonymous function) @ gpt.js?_=1438557092172:33(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:31ad.push @ gpt.js?_=1438557092172:16(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:31(anonymous function) @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:15f @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:15l.fireWith @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:15x @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16t.onload.t.onreadystatechange @ global-c87c4b3ce1ccdbed7a9e853b5402059e.js:16
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
betterttv.js?0.6327330775093287:52 Uncaught TypeError: $(...).masonry is not a functiont.exports @ betterttv.js?0.6327330775093287:52
betterttv.js?0.6327330775093287:51 Uncaught TypeError: Cannot read property 'joinChannel' of undefinedn.exports @ betterttv.js?0.6327330775093287:51(anonymous function) @ betterttv.js?0.6327330775093287:50
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: 353.
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: 366.
proxprice.js:4 GET https://api.betterttv.net/2/channels/taketv_csgo2 404 (Not Found)m.ajaxTransport.send @ proxprice.js:4m.extend.ajax @ proxprice.js:4m.each.m.(anonymous function) @ proxprice.js:4m.extend.getJSON @ proxprice.js:4n.exports @ betterttv.js?0.6327330775093287:51(anonymous function) @ betterttv.js?0.6327330775093287:50
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 build: local
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: CAP.
global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
betterttv.js?0.6327330775093287:52 Uncaught TypeError: $(...).masonry is not a functiont.exports @ betterttv.js?0.6327330775093287:52
VM948:1 GET http://cdn-static.liverail.com/js/companions.js?20131002 net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ VM948:1(anonymous function) @ VM948:1
ad4.liverail.com/:1 POST http://ad4.liverail.com/ net::ERR_BLOCKED_BY_CLIENT
4global-c87c4b3ce1ccdbed7a9e853b5402059e.js:30 TMI.js [irc] WARNING: Could not parse IRC message: CAP.

**Comment by night** [comment]
```
betterttv.js?0.6327330775093287:52 Uncaught TypeError: $(...).TrackpadScrollEmulator is not a function
```

The above is why you're not able to load BetterTTV. Unfortunately I have no idea why, and there's nothing we can do to fix this. Check that you do not have any other extensions installed. It is possible you run another extension affecting the version of jQuery running on the page.

**Comment by Hellfighter23** [comment]
Thanks for your Help.
