### ISSUE TITLE
Bug with bot badge

### ISSUE THREAD

**Issue by kilroy98** [night/betterttv#6192]
**Describe the bug**
The bot badge is not displayed even though it is added to the bots list.

**Screenshots**
![1](https://github.com/night/betterttv/assets/13346898/590f6f14-884c-47ed-bade-304e01f139f6)
![2](https://github.com/night/betterttv/assets/13346898/def6c0cc-afd8-4e64-8e44-55bf983f244d)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 114.0.5735.91

**Comment by night** [comment]
How long did you wait for the change to apply? Sometimes it can take up to 15 minutes and requires a refresh of the page. Bots also only show up on your channel, not other channels your bot is in.

**Comment by kilroy98** [comment]
It has been added to the bots list for a very long time. I know this badge only works on my channel.

**Comment by dclstn** [comment]
Sorry for the delay, the badge only appears if the bot is modded.

**Comment by kilroy98** [comment]
Not quite sure what you mean, but thanks for the reply.

**Comment by dclstn** [comment]
Try `/mod 9kmmrbot`, and see if it appears 👍

**Comment by kilroy98** [comment]
Oh, I thought a little about something else under the word "modded" ))
I added him as a moderator and nothing has changed.
![Screenshot_1](https://github.com/night/betterttv/assets/13346898/dff393e6-dcfe-431f-8b8b-3cd5c418cd47)
