### ISSUE TITLE
Emote changes

### ISSUE THREAD

**Issue by tatygg** [night/BetterTTV#621]
If you're subbed to a channel whose emotes are used in chat, then clicking on that emote should type it in chat, rather than linking to the channel.

**Comment by voloshink** [comment]
Why not just use the emote menu?

**Comment by tatygg** [comment]
just thought it would be a good quality of life change

**Comment by night** [comment]
Clicking on emotes forwards people to the emote owner's channel to allow people to easily subscribe to that channel if they want the emote.

We already have numerous ways to put emotes into chat. You can copy/paste them, you can tab-complete them, and you can use the emote menu. I do not think we need a fourth way.
