### ISSUE TITLE
anonloger

### ISSUE THREAD

**Issue by HcRedline** [night/betterttv#6218]
Hello, the problem is with anonlogger on channel where i have VIP, im still on users list on channel which isn't on  allowed list of channels that bypass anonymous chat, Still have to use command /join to use chat, but im on list before it. Tried to reset that, didn't help.

**Comment by night** [comment]
Thanks for the report. We are not able to reproduce any issues with the anon chat functionality. If you show up in the user list, it can take up to 5-10 minutes to be removed from that list. Twitch does not instantly add or remove users from that list.
