### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Velatoget** [night/BetterTTV#622]
I really think there should be customization hotkeys. My favorite emote is CougarHunt and I would love to hold "Shift 1" or something along those lines to quickly drop CougarHunt / as a wave, or CougarHunt // as a clap.

I think it would be a 10/10 addition. I know I could use other programs, but I'd want it to run in twitch specifically, so it'd be inconvenient.

Thanks for listening! <3 Love your work, keep it up!

**Comment by voloshink** [comment]
You could always use the emote menu and add the emote as your favourite so it always shows up at the bottom of the menu
