### ISSUE TITLE
Mod card Purge and Timeout options disappeared

### ISSUE THREAD

**Issue by Dragoonseal** [night/betterttv#6232]
**Describe the bug**
Open anyone's moderation card and the only options are Twitch's default Ban and Timeout, none of the extended options BTTV adds.

I assume it has to do with today's Twitch update which added the new Hype Chat feature.

Win10
Chrome Version 114.0.5735.134 (Official Build) (64-bit)

**Comment by dclstn** [comment]
fixed by: aebd68d

**Comment by Lpz3nc** [comment]
when the new release with this fix?

**Comment by Dragoonseal** [comment]
@dclstn Is it possible we could get this fix pushed out in an update?

It sounds like a little thing but in a busy chat it's a super pain in the butt having to manually type out timeouts all the time. And it's been almost a month now without the !permit and timeout buttons.
