### ISSUE TITLE
7TV Emotes in chat do not work on clips.twitch.tv

### ISSUE THREAD

**Issue by ScrubN** [night/betterttv#6234]
**Describe the bug**
7TV emotes in the chat replay work on `twitch.tv/user/clips/slug` but not `clips.twitch.tv/slug`.

**To Reproduce**

1. Go to any twitch clip with a chat replay containing 7TV emotes
2. Modify the clip URL from `twitch.tv/user/clips/slug` to `clips.twitch.tv/slug` if required
3. Observe the emote codes in the chat replay instead of the emote images

**Expected behavior**
The emote codes are replaced by their respective emote images.

**Screenshots**
`clips.twitch.tv/slug`
![image](https://github.com/night/betterttv/assets/72096833/d56ae9b1-99fc-4ca1-b18a-9e266e7543c8)
`twitch.tv/vedal987/clips/slug`
![image](https://github.com/night/betterttv/assets/72096833/df79354e-e6e7-4677-8175-a9242eb1434a)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit) 
- Version: 7.5.4

**Additional context**
Checking with several channels it appears to only affect 7TV emotes and not BTTV/FFZ emotes.

Examples links:
[https://clips.twitch.tv/TallTardyAnteaterStrawBeary-5c53U-w48qgIRA4_](https://clips.twitch.tv/TallTardyAnteaterStrawBeary-5c53U-w48qgIRA4_)
[https://www.twitch.tv/vedal987/clip/TallTardyAnteaterStrawBeary-5c53U-w48qgIRA4_](https://www.twitch.tv/vedal987/clip/TallTardyAnteaterStrawBeary-5c53U-w48qgIRA4_)

**Comment by dclstn** [comment]
Hi, the settings do not crossover to other sites.

So any changes made to your settings on `https://www.twitch.tv` won't affect `https://clips.twitch.tv` hence it uses the default setting for emotes, that being just bttv and ffz emotes.

There most likely needs to be an edge case for 7tv emotes to always appear on `clips.twitch.tv`.

If you wish for a temporary fix, you'll need to manually copy over your settings via the console

**Comment by NBruderman** [comment]
> Hi, the settings do not crossover to other sites.
> 
> So any changes made to your settings on `https://www.twitch.tv` won't affect `https://clips.twitch.tv` hence it uses the default setting for emotes, that being just bttv and ffz emotes.
> 
> There most likely needs to be an edge case for 7tv emotes to always appear on `clips.twitch.tv`.
> 
> If you wish for a temporary fix, you'll need to manually copy over your settings via the console

Hmm... Maybe a better solution would be just to crossover the settings specifically to `https://clips.twitch.tv`, and only there? It's a subdomain of twitch, after all. Obviously, only if it's possible and secure.

**Comment by night** [comment]
This appears to be a limitation of the storage implementation rather than a bug. The feature requests at #5853 or #6176 could help here. Perhaps worth opening a feature request to extend a limited settings menu to the clips site too.
