### ISSUE TITLE
Follower Alert?

### ISSUE THREAD

**Issue by fivetwosix** [night/BetterTTV#624]
I, like many other people out there, have one monitor. I was wondering if it could show the most recent follower in chat? Thank you

**Comment by voloshink** [comment]
Not exactly sure what's the point of that, when there are things like https://nightdev.com/followalert/

**Comment by fivetwosix** [comment]
Is that not designed for multiple monitors? I apologize if I'm getting confused...

**Comment by voloshink** [comment]
Guess it is. either way, i don't think we have the information of when someone follows you live, we would have to poll the api.

**Comment by fivetwosix** [comment]
alright

**Comment by night** [comment]
We are definitely not going to add polling for this into BetterTTV. We already get enough flack for making as many API calls as we do.
