### ISSUE TITLE
Updated Nickname done by BetterTTV not showing when user types on other channels

### ISSUE THREAD

**Issue by FrozenCoTTon** [night/betterttv#6256]
When you update a nickname for a username for one channel, it does not reflect on another channels chat

**To Reproduce**

1) Goto Channel A and have User 1 type in chat
2) Update User 1 nickname
3) Goto Channel B and have User 1 type in chat

**Expected behavior**
Channel B and other channels do not show updated nickname

Chrome

**Comment by dclstn** [comment]
I'm unable to reproduce this behaviour, are you able to provide a video/screenshots of what you're experiencing?

**Comment by FrozenCoTTon** [comment]
> I'm unable to reproduce this behaviour, are you able to provide a video/screenshots of what you're experiencing?

Oh okay, it looks like it is all the old nicknames that I've edited before that is not showing up in the other channel, all new ones I did are.
