### ISSUE TITLE
auto claim drops

### ISSUE THREAD

**Issue by dinozhr** [night/betterttv#6269]
on twitch it doesn't auto claim drops after first drop, so if there is 2 or 3 or more drops i have to claim them manually 

Desktop

Browser: [Firefox 115.0.2 (64-bit)]

**Comment by NBruderman** [comment]
Can confirm it also happens on chrome and edge browsers.

**Comment by night** [comment]
Drops are fairly hard to test long term due to viewership requirements. What UI displays differently between a first and second drop?

**Comment by NBruderman** [comment]
The UI shows up the same, the second drop just won't be claimed. And you won't see the dropped claimed banner at the bottom

**Comment by night** [comment]
Do you have any screenshots showing the first vs second?

**Comment by dinozhr** [comment]
@EldritchEevee i usually interact with viewers in chat during drops, but i will test it on a different streamer

**Comment by dinozhr** [comment]
i tried The Elder Scrolls drop it has 2, and first drop didn't auto claim :/ and i checked BTTV setting for auto claim and it was on
![Screenshot 2023-07-25 044948](https://github.com/night/betterttv/assets/139307598/c9c912ad-f9f5-4bde-8e4a-a090b026487d)
![Screenshot 2023-07-25 045034](https://github.com/night/betterttv/assets/139307598/c55dc8f6-0aa4-44d5-8003-df0ea58c16e6)

**Comment by night** [comment]
it looks like twitch has revamped how drops work within streams, so it will require us to rebuild how auto collecting drops works. they no longer provide notifications when drops are completed outside of an onsite notification. claiming drops in-context was removed entirely.

**Comment by dclstn** [comment]
fixed by e61d24a2622ca8405a45e94b6106d5d20008f980
