### ISSUE TITLE
Can't change font size in chat Chrome

### ISSUE THREAD

**Issue by xtryper** [night/betterttv#6272]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by night** [comment]
Thanks for the report. We are not able to reproduce this issue. If you're still having issues, try checking out our debugging instructions at https://community.nightdev.com/t/betterttv-debugging/3685
