### ISSUE TITLE
Request: Play a Sound when ... happens

### ISSUE THREAD

**Issue by jwtuchol** [night/BetterTTV#629]
Such as when someone joins your channel or when someone comments

**Comment by thinkpad4** [comment]
That would get real annoying real fast

**Comment by night** [comment]
We can't know when someone joins your channel. This information is disabled on the Twitch site.

We're not interested in adding a sound for every comment. I suggest using highlights coupled with the highlight audio setting and making keywords that help you stay on top of incoming chat.
