### ISSUE TITLE
BetterTV settings don't appear on moderator screen (Chrome - Linux)

### ISSUE THREAD

**Issue by Pafon22** [night/betterttv#6291]
I have to switch to the regular viewer screen so I can access the settings (it appears in both moderator and non-moderator settings), but I can't be in the mod view (twitch.tv/moderator/channel).

To Reproduce:
Open any Twitch channel from moderator link and try accessing BTTV settings

1. Go to 'twitch.tv/moderator/$(channel)'
2. Click on 'Chat settings'
3. Scroll down to 'BTTV Settings'
4. See error: Step 3 doesn't exist.

Expected behavior:
The step 3.

Mod Screen:
![Captura de tela de 2023-07-25 23-41-27](https://github.com/night/betterttv/assets/22238807/eb087f45-c52a-4948-97a6-e80c8f3f8c71)
![Captura de tela de 2023-07-25 23-43-26](https://github.com/night/betterttv/assets/22238807/4a4c0ea3-4c21-400b-9021-2411d39ba652)

Viewer Screen:
![Captura de tela de 2023-07-25 23-50-13](https://github.com/night/betterttv/assets/22238807/458baa4e-8172-4d7b-ba50-1c18f3d0713a)
![Captura de tela de 2023-07-25 23-51-04](https://github.com/night/betterttv/assets/22238807/60eb9dc4-44f6-434d-9a3d-52af7d4a0113)

- OS: Ubuntu 22.04.2 LTS
- Browser: Google Chrome
- Version: 115.0.5790.102 (official version) 64 bits

Additional context:
I installed it, allowed all permissions and refreshed the page.

**Comment by night** [comment]
Hmm. It seems to appear for me in the moderation view, but it does require you swapping to the non-mod settings first. Have you tried that?

**Comment by Pafon22** [comment]
> Hmm. It seems to appear for me in the moderation view, but it does require you swapping to the non-mod settings first. Have you tried that?

I tried.
It's the Screenshot#1 (Mod URL with settings for 'non-moderator' - has option "see settings for moderators" which forwards to screenshot 2).


Could the problem be the browser version for this OS?

**Comment by ScrubN** [comment]
BTTV settings can be found in the moderator view by clicking non-mod settings
![image](https://github.com/night/betterttv/assets/72096833/cfe6ad3c-b2e3-4cd0-adc0-507fc24598b1)
![image](https://github.com/night/betterttv/assets/72096833/774c4b31-a647-4d77-a800-4f857ae6e902)

**Comment by Pafon22** [comment]
> BTTV settings can be found in the moderator view by clicking non-mod settings ![image](https://user-images.githubusercontent.com/72096833/261812418-cfe6ad3c-b2e3-4cd0-adc0-507fc24598b1.png) ![image](https://user-images.githubusercontent.com/72096833/261812484-774c4b31-a647-4d77-a800-4f857ae6e902.png)

Yes, as said earlier, there are 4 prints (all on the moderator screen).
2 went with the preview option for moderators and 2 by pressing this button you showed preview for non-moderators.

**Comment by Pafon22** [comment]
[Gravação de tela de 19-08-2023 15:17:45.webm](https://github.com/night/betterttv/assets/22238807/f836941c-9f2c-446e-96c4-f24d5868cd5b)
I just discovered the problem, the option is not implemented when switching to my language.
