### ISSUE TITLE
Highlight our own comments

### ISSUE THREAD

**Issue by expllosao** [night/BetterTTV#630]
It's a cool feature that the comments which are directed to us have a red highlight over it, that's why I think that highlighting comments that we've posted ourselves would be also great.
Also, is there a way to change the colours on the chat? Like, changing the highlight to coming comments to blue, or of the deleted comments to some kind of glowing white.

**Comment by night** [comment]
You already can highlight yourself.. Add "(your_username_here)" to your highlight keywords.

We do not have color customizability at this time, sorry. It's a lot of work to make color options, and you can use something like Stylish to do this yourself if you're inclined.
