### ISSUE TITLE
Emotes not showing on twitch vods

### ISSUE THREAD

**Issue by Kovieira** [night/betterttv#6305]
**Describe the bug**
When I added Bttv on OpreaGX the emotes appeared normally on twitch vods, but now they are not showing anymore, only on lives.

**Screenshots**
![twitch](https://github.com/night/betterttv/assets/141492411/695e240e-75b0-45bd-ac68-789c8292b69a)

**Comment by sbates** [comment]
same on firefox 
![image](https://github.com/night/betterttv/assets/843975/0f14a9e8-c781-4656-a064-528b48639694)

**Comment by Boldyrev-Yuri** [comment]
I'm having the same problem in both Google Chrome and Firefox. There are several errors in Google Chrome console, such as:
`[GraphQL] One or more GraphQL errors were detected on request 01H7Q31ZSGCM9W2B39F9R1FRG2. ChatRoomBanStatus: service error Array(1)
(anonymous) @ chrome-extension://a…ped/betterttv.js:94`

**Comment by Legushka26** [comment]
I have the same issue. Emotes like OMEGALUL show up as emotes when watching a live stream, but only as a word when watching a VOD. Even if it's the same channel. Some emotes always show up, but some like OMEGALUL are bugged this way. Same behavior in both Firefox and in Chrome.

Live stream
![sshot-8033](https://github.com/night/betterttv/assets/103005916/75f21055-99ff-4b2a-83c0-0c404b5fcd72)

VOD, same channel
![sshot-8034](https://github.com/night/betterttv/assets/103005916/abfd8e00-89cb-40a9-876a-e715d3e2b65f)

**Comment by night** [comment]
I am not able to reproduce any issues with VoDs. You are likely seeing an issue with the third party extension not rendering emotes. Go into the BetterTTV settings and check to make sure you've enabled all the emote providers you want to see.

**Comment by night** [comment]
Upon further investigation this issue only occurs when navigating directly to a VoD. Navigating from a channel's list of VoDs does not reproduce the issue.
