### ISSUE TITLE
Black bars on top and bottom since the new twitch player update

### ISSUE THREAD

**Issue by stalki** [night/BetterTTV#632]
As the title says, i'm having issue with BTTV and new twitch player update. As you can see in this picture black bars on top and bottom: https://i.gyazo.com/e7278254c8e24459c803c92e3844161a.jpg

I'm using Google Chrome. Tried resizing the chat but it doesn't help. I'm not the only one, my friends are having the same issue. Disabling BTTV removes the black bars.

**Comment by wallrik** [comment]
Can confirm that the black bars disappear when you disable BTTV. [before](http://i.imgur.com/TOFaA1V.jpg) | [after](http://i.imgur.com/p3zVskG.jpg)

**Comment by night** [comment]
Unfortunately since I am not in the experiment group for the new player and there's no way to force the new player Twitch is embedding, there's nothing I can do. Oh well!

¯\_(ツ)_/¯

**Comment by night** [comment]
Fixed by d5f15358cb3344ed389d1df2c14877ecc8e2405b
