### ISSUE TITLE
No sound when mentioned in chat

### ISSUE THREAD

**Issue by theboidiff** [night/betterttv#6337]
Hello, i have the option turned on for sound when someone mentions me in twitch chat but all of the sudden i dont get the sound alert anymore but the option is still turned on. I've reinstalled and everything but nothing works still. Any clue what could be going wrong?

Opera GX
version 115.0.5790.171
Windows 10 64-bit

**Comment by night** [comment]
I am not able to reproduce this issue. If you're having trouble hearing the sound, it may be because browsers mute sounds on inactive tabs these days. Make sure a stream is going on the tab and see if that helps.

**Comment by theboidiff** [comment]
The tab is active, me and my friend are having the issue 


Sent from Yahoo Mail for iPhone


On Wednesday, September 6, 2023, 1:42 PM, Zack ***@***.***> wrote:




I am not able to reproduce this issue. If you're having trouble hearing the sound, it may be because browsers mute sounds on inactive tabs these days. Make sure a stream is going on the tab and see if that helps.
