### ISSUE TITLE
"Upload Emote" button greyed out

### ISSUE THREAD

**Issue by megaphonixmusic** [night/betterttv#6339]
**Describe the bug**
The "Upload Emote" button is greyed out on my main BTTV website dashboard.

**To Reproduce**

1. Go to Dashboard
2. Try to click on "Upload Emote" (greyed out)
4. Error

**Expected behavior**
I expect the "Upload Emote" button to not be greyed out.

**Screenshots**

https://imgur.com/a9HranP

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 116

**Additional context**
I'm underneath the 50 channel-enabled emote limit, so I'm not sure why I'm not able to upload more emotes at this time. My username is Megaphonix on BTTV.

**Comment by night** [comment]
Thanks for the report. This issue should be resolved.
