### ISSUE TITLE
Dark mode issue with new twitch player update

### ISSUE THREAD

**Issue by wallrik** [night/BetterTTV#634]
I'm sure this would be a given once the new player rolls out on a bigger scale, but figured I'd put it on here anyway to have it documented.

The "popout player" and "show/hide video stats" links are colored gray from dark mode on white background. Makes them look like they're disabled.

I have screenshotted the menu and the links selected in source view in this [imgur album](http://imgur.com/a/r0P2I).

**Comment by wallrik** [comment]
I also wanted to add, this can be experimented on without necessarily having the player embedded, because it seems they use the same styles in the [new popout](http://player.twitch.tv/?channel=sodapoppin) window. [[1]](http://i.imgur.com/gzLK7WA.jpg) [[2]](http://i.imgur.com/mfWWUis.jpg)

**Comment by night** [comment]
Fixed by 7eb483b68f0d1e739622839f019716bfd5adc24d
