### ISSUE TITLE
Emote modifier no longer working 

### ISSUE THREAD

**Issue by Stricken49** [night/betterttv#6340]
Since the new version, emote modifiers are not working with Opera and Opera GX. The emote is not modify. I have try several options like w!, but in the chat, only the basic emote, and the modifier appears.

1. Connect on twitch account on Opera or Opera GX
2. Try emote of betterttv with modifiers like w! , h!, etc...

![Chat](https://github.com/night/betterttv/assets/36619540/637c9691-96c9-4310-847a-e336b2273c03)

**Comment by night** [comment]
fixed via 8dcbd86334be090692bfa6b9c410dac084a7c848
