### ISSUE TITLE
Options in settings missing and only available if doing a search

### ISSUE THREAD

**Issue by godzfire** [night/betterttv#6352]
**Describe the bug**
I was trying to figure out why the Prime Loot icon came back up top since I know BTTV has an option to block it. However the option is not present anywhere, the only way I was able to see it is by using the search for some part of the name, like 'Prime Loot', it then showed up. I have no idea how many other settings might also have this issue and aren't showing up for people.

I completely reset and also uninstalled the extension, and that didn't fix anything.

**To Reproduce**

1. I went into the BTTV settings and started looking for the "hide prime promotions" option
2. I went through every available menu, still wasn't showing up
3. Used the search for some part of the name, like 'Prime Loot'
4. Option then showed up

**Expected behavior**
The option would be visible and available in settings without having to search for it.

**Screenshots**
<img width="987" alt="image" src="https://github.com/night/betterttv/assets/2067820/497ba3b0-f1dd-4265-b012-816b1446de94">

**Desktop (please complete the following information):**

- OS: Mac OS 12.6.8
- BrowserL Version 116.0.5845.110 (Official Build) (x86_64) 
- Version: BTTV 7.5.5

**Additional context**
Nothing else I can think of.

**Comment by night** [comment]
Prime Promotions is under the channel settings page, not the chat settings page.

**Comment by godzfire** [comment]
I'm so sorry Night, I must have been blind. My apologies.
