### ISSUE TITLE
BetterTTV buttons showing incorrect

### ISSUE THREAD

**Issue by kilroy98** [night/betterttv#6379]
**Describe the bug**
After last update buttons for access BetterTTV settings showing incorrec.

**Screenshots**
![Screenshot_1](https://github.com/night/betterttv/assets/13346898/ac5cc004-b2f9-4d63-8fbc-cdd6ae9829da)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: 117.0.5938.63

**Comment by ScrubN** [comment]
![image](https://github.com/night/betterttv/assets/72096833/5422e45b-13cf-49da-aa83-906924316c63)

I also noticed this issue. Happens both in channels where I am a moderator and channels I am not.
