### ISSUE TITLE
Add Report to Moderator Cards

### ISSUE THREAD

**Issue by DetJokke** [night/BetterTTV#639]
Hi Forum!

I'm asking for a little button to report, in the menu that pops up when you click a name.

Example: 
https://discuss.dev.twitch.tv/uploads/default/original/1X/253487ddd7a4432a24b3fe35cf0f014288498931.png

I hate that I have to enter a person's profile to report them. I hope it's something that's usefull, and I'm not the only one who's asking for this.

**Comment by dav1dsm1th** [comment]
just raised the same issue, before finding yours.  this would make so much sense (to me).

**Comment by BradyThe** [comment]
I also would like to see this. This would really come in handy in the current situation with the spam bots. Make it configurable in the options, maybe. I would like to see a "Button clicked = Ban + Report with chat message" kind of scenario.

**Comment by night** [comment]
this is fixed
