### ISSUE TITLE
7TV emotes don't show a preview on hover

### ISSUE THREAD

**Issue by Void48** [night/betterttv#6392]
FFZ and BTTV emotes show a preview when you hover over them but 7TV emotes don't

**Comment by night** [comment]
Do you have a screenshot of what hover you're referring to?

**Comment by night** [comment]
The first image depicts FFZ's tooltip, while the second image is how BetterTTV renders similar tooltips. You may need to reach out to FFZ to figure out why 7TV emotes do not show this same tooltip.
