### ISSUE TITLE
I can not remove emote from my dashboard

### ISSUE THREAD

**Issue by JanChess** [night/betterttv#6394]
### Describe the bug

I can not remove emote from my dashboard after it is been removed from bttv and reported (as duplicate)

### Steps to reproduce

go to dash board and press on emote and unTick (remove) it

### Expected behavior

emote to be removed from my dash board so I can add another

### Screenshots

<img width="802" alt="Screenshot 2023-09-22 165821" src="https://github.com/night/betterttv/assets/145780983/914718d2-f864-4b7a-ad0d-f946db3a29af">

### Device information

Widnows 10
compture

**Comment by night** [comment]
This issue should now be fixed
