### ISSUE TITLE
My emote dosnt added on my channel

### ISSUE THREAD

**Issue by Neratha** [night/betterttv#6397]
### Describe the bug

Everything is in the title i cant added any emotes to my channel 

### Steps to reproduce

1. Go to popular emote
2. Choose emote i want
3. Check the mark on my channel to add it (Update emote set > channel)
4. The emote dosnt add in the dashboard channel

### Expected behavior

1. Go to popular emote
2. Choose emote i want
3. Check the mark on my channel to add it (Update emote set > channel)
4. The emote dosnt add in the dashboard channel

### Screenshots

![image](https://github.com/night/betterttv/assets/145855251/380ee869-da4b-46f5-b8ce-de892de08f6b)

### Device information

1. Go to popular emote
2. Choose emote i want
3. Check the mark on my channel to add it (Update emote set > channel)
4. The emote dosnt add in the dashboard channel

**Comment by night** [comment]
I am not able to reproduce this issue. Emotes properly show up on the dashboard after enabling them. If you're still having issues, please provide a video demonstrating the problem.
