### ISSUE TITLE
Channel Points

### ISSUE THREAD

**Issue by ThaSherminator** [night/betterttv#6408]
### Describe the bug

I am having issues redeeming Channel points, collecting the watch bonus and using the predictions, no idea on what is causing this.

### Steps to reproduce

Click on an option to redeem channel wont let redeem my points.
Unable to enter custom amount for the predictions 
Clicking on the bonus bubble wont collect the points

### Expected behavior

Being able to use the channel points
entering a custom amount on a prediction
collecting the bonus bubble points

### Screenshots

N/A

### Device information

Browser is Opera GX

**Comment by inkrotaudio** [comment]
I am also having this issue. Unfortunately it also prevents my from claiming drops, sending re-subscribe chats as well. 

Browser is Opera GX but have seen the same behavior is Google Chrome.

**Comment by night** [comment]
It sounds like Twitch's API is blocking your requests, which tends to happen some of the time. It's not clear why this happens but you may try fully logging out and back into Twitch as a temporary fix.
