### ISSUE TITLE
Date added sort dysfunctional

### ISSUE THREAD

**Issue by susyemeralds** [night/betterttv#6415]
### Describe the bug

The Date Added sort option does not seem to be working anymore?
The order in which it is sorting my emotes is just not my date added, I don't know how it is sorting them.

Which is a real shame because that used to be mighty useful when they got uploaded to Discord. 

### Steps to reproduce

Dashboard > Cogwheel > Sort > Date Added

### Expected behavior

To sort my emotes by the date I added them to my channel

### Screenshots

![image](https://github.com/night/betterttv/assets/118739137/12392113-f830-4764-9830-7e6fc5228449)

Here's an image but you'll just have to take my word for it

### Device information

PC
Windows
Firefox 118.0.1

**Comment by night** [comment]
I believe you must be mistaken. These appear correctly sorted by the date you added them to your channel in ascending order.
