### ISSUE TITLE
Using "Shift + Click" To Input Multiple Emotes Adds Extra Spaces In Between Emotes

### ISSUE THREAD

**Issue by immiwakanai** [night/betterttv#6416]
### Describe the bug

As stated in title, using shift + click to input multiple emotes from the BTTV emotes menu adds extra trailing spaces in between the emotes to varying degrees.  Some emotes adds more trailing spaces than others.

### Steps to reproduce

With BetterTTV extension enabled and BTTV emotes menu enabled:

1) Shift click on any emote multiple times to input several of them
2) Checked using text cursor to keep track of number of trailing spaces in between the inputted emotes

Again, Some emotes have more trailing spaces than others.

These steps were primarily done in Firefox latest build, but I was able to reproduce the same issue in Chrome's latest build too.

### Expected behavior

Should have no trailing spaces in between the inputted emotes.  Using YouTube Chat's regular emotes menu functionality does not have trailing spaces in between the emotes.

### Screenshots

![Bug Screenshot](https://github.com/night/betterttv/assets/147355679/e2db72be-2d7a-4802-93c4-f7c2248f99b2)

GIF version of Bug Reproduction:

![Bug Reproduction](https://github.com/night/betterttv/assets/147355679/d407de74-8eea-4bca-a2f5-d3fda0e6b6e3)

### Device information

PC
Windows 10
Firefox Build 118.0.1 (64-bit)
Chrome Build Version 117.0.5938.150 (Official Build) (64-bit)

**Comment by night** [comment]
This is considered working as intended. BetterTTV's emote parser works slightly different to YouTube's in that we require exact matching on space-delimited inputs. As a result, we place a space between emotes entered via the emote menu.
