### ISSUE TITLE
Highlights not working

### ISSUE THREAD

**Issue by epona2003** [night/betterttv#6420]
### Describe the bug

Highlighted terms, such as my username, don't show up anymore after uninstalling 7TV. I don't know if the uninstallation is related, but that's when it started happening. I still receive sound feedback when someone chats one of the terms, but the word(s) aren't highlighted anymore.

### Steps to reproduce

1. Someone chats a keyword I added to be highlighted
2. I get an audible ping sound
3. I see the word in chat but it is not highlighted

### Expected behavior

When someone types in chat a word you have set up to be highlighted, you should receive a ping sound (if you enabled highlight feedback) and the keyword should be highlighted red (default) or the color you have chosen it to be. 

### Screenshots

![bttv](https://github.com/night/betterttv/assets/147453293/badc5a08-c5e3-439f-848d-119adc864d66)

### Device information

-Device: HP Spectre x360 Convertible 15
-OS: Windows 11 Home 64-bit Version: 22621.2361
-Browser: Google Chrome
-Version: 7.5.8

**Comment by night** [comment]
I am not able to reproduce this behavior. If you're still having issues, try disabling other browser extensions as another is likely conflicting with BetterTTV's operation.
