### ISSUE TITLE
Youtube BTTV emote menu gone with new youtube update

### ISSUE THREAD

**Issue by motionstahp** [night/betterttv#6421]
### Describe the bug

Youtube recently updated the look of their youtube chat and since then, the emote menu has disappeared when enabled. Disabling it brings back the normal youtube emote menu

### Steps to reproduce

1. Go on a youtube livechat since the new website change
2. Look for the emote menu
3. don't find it

### Expected behavior

Expect the emote menu to be visible

### Screenshots

https://cdn.discordapp.com/attachments/631219474539872268/1161245295447904336/image.png

### Device information

Google Chrome Desktop

**Comment by powercore2000** [comment]
Has there been any progress on fixing this bug?

**Comment by happypanda2255** [comment]
This has also been an issue for me on firefox

**Comment by pranjal779** [comment]
If i enable it, I loose the default emotes as well

**Comment by Erionn** [comment]
Having the same issue here, enabling BTTV emote menu causes the button to disappear entirely, using Firefox desktop 119.0
