### ISSUE TITLE
Emote is falsely considered a duplicate

### ISSUE THREAD

**Issue by navarr** [night/betterttv#6423]
### Describe the bug

When uploading the attached emote, it is erroneously considered a duplicate of https://betterttv.com/emotes/551d19ac62e6bd0027aee2d2
![crow](https://github.com/night/betterttv/assets/145128/2d699195-4233-4f57-b960-17b9a697a7af)

### Steps to reproduce

1. Attempt to upload attached emote

### Expected behavior

Attached emote is uploaded successfully

### Screenshots

![image](https://github.com/night/betterttv/assets/145128/a1be3b3a-faa4-4576-a289-cd4b8dfcd55b)

### Device information

- Macbook Pro (M1)
- Ventura 13.6
- Chrome 117.0.5938.149 (arm64)

**Comment by night** [comment]
This is due to a technical limitation of how emotes are compared with each other. I would recommend altering your emote to use different a different color to make it more unique.
