### ISSUE TITLE
Auto Collect Drops

### ISSUE THREAD

**Issue by coinpusherworld** [night/betterttv#6438]
### Describe the bug

Since twitch changed there drops they no longer auto collect if u have the option turned on

### Steps to reproduce

Turned off auto collect drops and turned back on and still not collecting

### Expected behavior

Before twitch updated the drops we could auto claim them and now we cant

### Screenshots

This is with the setting on https://i.imgur.com/dCD7Zg3.png and nothing on drops

### Device information

Windows, using google chrome

### Additional information

I have also followed what was put in discord aswell and its still not working https://i.imgur.com/IksnDW2.png

**Comment by OrionGlow** [comment]
same problem in all browsers: Mozilla FireFox, Edge, Chrome, Opera GX. Addon vers. 7.5.8

DEV, always thk for your support!

**Comment by flamedance58** [comment]
I'm getting the same problem though sometimes it'll pick up the first of a series of drops but it'll forget the rest.
Either way it seems the feature doesn't work properly.

**Comment by ManzanaApple** [comment]
Same problem here. Newest version of Firefox

**Comment by OrionGlow** [comment]
yes, day 18/10/2023 twitch changed API systems drop, with new API... and this is the doors of hell!
in many moment, change API = total remake of all program
i think,, we need to wait many time, and with many PATIENCE...

**Comment by night** [comment]
duplicate of #6269
