### ISSUE TITLE
BetterTTV blocks YouTube Live Streams

### ISSUE THREAD

**Issue by mogoh** [night/betterttv#6453]
### Describe the bug

I tried to watch a live stream on youtube and it did not load. I profiled the the tab and BetterTTV was the process that took all resources.

### Steps to reproduce

Watch a live stream, for example this one: https://www.youtube.com/watch?v=KUmMMLHYH4o

### Expected behavior

Steam should start.

### Screenshots

![grafik](https://github.com/night/betterttv/assets/580975/9a898b31-a91e-4f9b-a724-69f2d93c33f8)

### Device information

Windows 10
Firefox 119

**Comment by night** [comment]
I am not able to reproduce this issue. Are you certain the video not loading is caused by BetterTTV? You may wish to debug the Network tab instead, which will allow you to better trace video resources being served to the YouTube player.
