### ISSUE TITLE
The player doesn't pause when playback is complete

### ISSUE THREAD

**Issue by e-tho** [night/betterttv#6464]
### Describe the bug

It happens with Auto Join Raid and Auto Play disabled on streams/VODs that have raided. This behaviour prevents the system from idling and thus triggering sleep mode.

### Steps to reproduce

Let a VOD from a streamer who has raided run to completion with Auto Join Raid and Auto Play disabled.

### Expected behavior

The player should pause the video when complete.

### Screenshots

![2023-11-11T14:35:33,371303954+01:00](https://github.com/night/betterttv/assets/128100160/30932a4b-56df-4bcf-ab2d-b031ca231123)

### Device information

- NixOS
- Firefox 119.0
- BetterTTV 7.5.9

**Comment by night** [comment]
This doesn't sound like a bug with BetterTTV. The Auto Join Raid feature clicks the cancel button when a raid notification is prompted. The Auto Play setting only effects player state when on a channel's homepage or the Twitch homepage, and this is a VOD. The VOD Recommendations setting could be triggering this, but we are clicking on the Cancel button to play the next video. We don't set the player to pause/play here, so it's an issue with Twitch's player not detecting the end of a video properly.
