### ISSUE TITLE
The emote menu appears truncated

### ISSUE THREAD

**Issue by Rumspringa90** [night/betterttv#6479]
### Describe the bug

When I activate and click the expanded emote menu, the window appears cut off

### Steps to reproduce

Click on the emote menu button below the chat. 

### Expected behavior

Display the full window. Maybe anyone can tell me how to fix it?

### Screenshots

![Screenshot 2023-11-19 123008](https://github.com/night/betterttv/assets/50840355/2ba53a7f-5b52-4111-a7ce-c2b441294fb2)

### Device information

Browser: Opera GX 
Version: 102.0.4880.117

Browser: Chrome
Version: 119.0.6045.160

### Additional information

Deleting cookies from Twitch was unsuccessful

**Comment by night** [comment]
it might be due to the translations. if you change your twitch language to english, does that fix the issue for you?

**Comment by Rumspringa90** [comment]
yes, that fix the issue. 

but on my work PC it works even if it is set to German. The only difference I can think of right now is that I have Windows 11 installed and Windows 10 is installed at work. The browser is the same. 

Thank you!

**Comment by night** [comment]
it looks due to the tip at the bottom. you can dismiss the tip as a temp fix, but it will be fixed in the next release
