### ISSUE TITLE
Thin line appear ontop of animated emotes

### ISSUE THREAD

**Issue by ACMDatabase** [night/betterttv#6497]
### Describe the bug

Since the last weekend a thin line appear ontop of my animated emotes. It flickers and changes shape a lot.
I have tried cropping the image but the line is still there when uploading. It is not on the emote before uploading.

It is especially visible on this emote but it appears on all of the new animated ones that I upload.
https://betterttv.com/emotes/6565c3b35facec2534bff970

I think it might be a piece of the bottom appearing on top of the emote.
This started happening a few days ago.

I am using Windows 10 and Opera GX and uploading them in gif format, (Edit: I tested with webp as well and it still appear).

### Steps to reproduce

1. Upload an animated gif or animated webp.

### Expected behavior

The emote without the line, which does not exist on the emote before uploading.

### Screenshots

![image](https://github.com/night/betterttv/assets/101660803/a0a80719-4e9c-4034-afbd-7b890453d10e)

### Device information

- PC
- Windows 10
- Opera GX

**Comment by ACMDatabase** [comment]
No it appears on all of my emotes that are animated and also the line is not static, if it was something I had forgotten it would not change shape.

**Comment by night** [comment]
Can you attach the source image you're uploading as a zip file?

**Comment by ACMDatabase** [comment]
sure, I am also uploading a video showing that it is the bottom appearing on top. Just give me a second. Here is the source image.
![airPeek alternative 336x336](https://github.com/night/betterttv/assets/101660803/70e1ec99-5daf-41f0-a06a-ed762ec060e7)

**Comment by night** [comment]
when images get downscaled artifacting can occur. have you tried producing a 112x112 image instead, and uploading that?

**Comment by ACMDatabase** [comment]
can I set them individually?

**Comment by ACMDatabase** [comment]
I tried uploading with firefox instead of opera gx but still the same problem.

**Comment by ACMDatabase** [comment]
This is so confusing. 
I reuploaded the dino that I already have up and that also gets the line so now I got a dino with a line and one without. I just cropped it a little so it was exactly the same image.

I then went to FrankerFaceZ uploaded the same emote and it also has the line.
Since frankerfacez has a cropping tool when you upload, I reuploaded again and cropped 6pixels from the bottom and then the line was not there when the emote was done. It's so weird.

It makes me think it is a bug in ffmpeg or what betterttv are using to scale with. It actually seems to be everywhere. airine_e which is who I am making the emotes for also did get the line so it's not just my pc.

I have no idea what to do at this point.

**Comment by night** [comment]
my guess here would be it is an upstream issue with libvips, which I suspect most folks use to resize images. It's possible it will be fixed in a future update to the upstream library, but there's likely something strange about your emote. You could try exporting it using a different color type to see if that helps.

**Comment by ACMDatabase** [comment]
I would appreciate that because I have tried everything from using live2d export to remaking the emote at ezgif, cropping it it, different sizes. When I upload other emotes that did not the lines they now have lines.

**Comment by ACMDatabase** [comment]
thank you very much, this could not have come at a worse time. because I finally got to make emotes for a streamer I look up too and its 16 emotes. of course this had to happen right now.

**Comment by ACMDatabase** [comment]
it only appear on animated emotes and it seems to be related to pixels moving around at the bottom. So making the bottom a static line makes the line go away but instead you have a line at the bottom. But that is a lot better than what it was before.

**Comment by night** [comment]
Upstream found it related to the resize kernel in use by default. We've mitigated the issue by using a different resize kernel. Try uploading it now and see if it's better.

**Comment by ACMDatabase** [comment]
Great :)
The line is gone but it seems like it became really pixelated instead. I'll try again with another.
https://betterttv.com/emotes/656e1ed1dcf92ef459ebb902

**Comment by ACMDatabase** [comment]
It's not a great example but you can see the differense on these two.
This is the old one 
https://betterttv.com/emotes/6564621e2c6f9fcf9d60cdeb

and this is the new one 
https://betterttv.com/emotes/656e1f58dcf92ef459ebb918

**Comment by night** [comment]
That does look much worse. I've reverted our change. The best suggestion I can give you is maybe try leaving a pixel or two of blank space beneath the image before you export it.

**Comment by ACMDatabase** [comment]
Yeah that looked much worse, unfortunatley the line is back again. Thank you for trying though.
Maybe I can do a mask or something, I'm not sure how that works.

**Comment by ACMDatabase** [comment]
would it be possible in the future to set the 3 sizes manually?
