### ISSUE TITLE
Auto-Expand Channels

### ISSUE THREAD

**Issue by magnamundian** [night/betterttv#6509]
### Describe the bug

Option:

_"Auto-Expand Channels"
Clicks the Load More followed channels button in the sidebar for you_

Doesn't expand the channels when the browser window width is less than 1,200 pixels - i.e. when Twitch reduces the width of the sidebar show icons only.

Not sure if technically a bug when the "thin" sidebar doesn't show the "Load More" link, perhaps an option to disable switching to the "thin" sidebar is required?

See screenshot - 17 channels live, only 12 appear in side bar (yes my monitor is in portrait mode)

### Steps to reproduce

With betterttv enabled

1. Resize browser window to width of 1,200 or less so twitch switches to thin sidebar

2. Refresh page, only default top 12 channels are shown

### Expected behavior

additional channels to be shown as if "Load More" click was clicked.

### Screenshots

![Screenshot from 2023-12-06 19-38-50](https://github.com/night/betterttv/assets/153126914/0d65c664-9be0-433d-954c-6a8ef34fe363)

### Device information

PC
Brave 1.60.118
Zorin OS 16.3

**Comment by night** [comment]
Thanks for the report. The auto expand feature simply clicks on the "Show More" button for you. Since Twitch limits what is shown in the collapsed menu, we're not able to expand it in that mode.
