### ISSUE TITLE
If translations are requested too fast, original message is lost.

### ISSUE THREAD

**Issue by MoonSha** [night/BetterTTV#651]
Since you replace the original message with the "nag" message about only requesting 1 every 5 minutes, the original message is lost. It should probably only show that message for a short time, then return to the original un-translated text.

**Comment by night** [comment]
We should probably have tooltip error instead, you're right.

**Comment by dav1dsm1th** [comment]
It would be cool to tooltip so the original isn't lost

**Comment by MattUnderscore** [comment]
+1
