### ISSUE TITLE
BTTV stopped working on YouTube 

### ISSUE THREAD

**Issue by Schmopus** [night/betterttv#6525]
### Describe the bug

None of bttv's functions work while logged into my main YouTube account. I have every setting active (the bttv settings menu shows up), but nothing happens, it doesn't switch to live chat, there is no bttv-Emote menu and emotes in chat do not appear (they are all enabled). 
![Screenshot 2023-12-15 001506](https://github.com/night/betterttv/assets/103822645/c4d6f6a9-74aa-4608-b510-fef291a2701d)

But if I am logged into my secondary YouTube account, bttv works as intended, it automatically switches to live chat, the bttv-emote menu shows up and the emotes in chat do as well. 
![Screenshot 2023-12-15 001617](https://github.com/night/betterttv/assets/103822645/380a8dd9-8e78-4039-8a4e-e8c1d8c479e8)

Twitch is unaffected and works as intended.  

### Steps to reproduce

I don't think it is easily reproducible for other people, that's why I was hesitant to post on here. Sorry if you cant help me because of this.

I can easily reproduce it by switching from my secondary account to my main account. 

### Expected behavior

-

### Screenshots

On the Nightdev forum it says to check the Java console for errors, I'm not tech-savy so i don't know if they say anything.
![Screenshot 2023-12-16 030818](https://github.com/night/betterttv/assets/103822645/4ecb5fc8-b612-4711-9806-68e1e40e9403)
Console on my main account (bttv doesnt work) 

![Screenshot 2023-12-16 032606](https://github.com/night/betterttv/assets/103822645/4c2a99d5-71f9-4edb-b721-7c304bd6af0d)
Console on my alt account (bttv works) 

I have also set the extension to collect errors in the extensions tab of chrome, this is all the YouTube related errors it found (looks like it collected the same thing as in the console) 
![Screenshot 2023-12-16 040755](https://github.com/night/betterttv/assets/103822645/b62576ee-ddef-438c-9bc4-10aedea50fcc)

### Device information

-Chrome
-YouTube 

### Additional information
I have already tried reinstalling bttv, disabled all other extensions, cleared the browser cache and cookies and tested it on Firefox, same issue still persists.

I'm sorry if this is the wrong place, since it seems to be an issue that isn't reproducible.
Thank you for your time anyway

**Comment by mgemerick** [comment]
I can confirm this is also happening to me on Chrome, FireFox, and Edge.

**Comment by redxshadowx90** [comment]
I have also been experiencing thus exact issue too. Have tried everything you listed as well. Hopefully it gets resolved soon.

**Comment by Schmopus** [comment]
It has now also stopped working on my second YouTube Account
