### ISSUE TITLE
Anti-spam Opt-out

### ISSUE THREAD

**Issue by DanseMacabre** [night/BetterTTV#653]
An opt-out menu item is needed for the anti-spam feature.

**Comment by night** [comment]
Is there a reason it needs an opt-out? There's nothing in the list of spam you'd actually want to see, though you can click the message to show its contents already.

**Comment by DanseMacabre** [comment]
I mod a relatively permissive channel and it's annoying to have to click-through to check whether or not it's actually spam.

There have been at least two cases where something marked in <spam deleted> is permitted in the chat.

**Comment by voloshink** [comment]
Added in 9f92532770fe7dfc137b26efbfb7cc92abeea8bf
