### ISSUE TITLE
BTTV in steam web browser?

### ISSUE THREAD

**Issue by ArcanicFlame** [night/BetterTTV#654]
i was looking to use BTTV for my stream but i use the STEAM overlay web browser to have my chat up, i saw that theres "userscript" for other browsers, but i have no clue how i would get that into steams web browser.

i looked through steams various files to figure out what the browsers based off/using and found a "chrome.dll" so im assuming its using chrome? i found some text docs in the various steam folders for the web browser with code in them but im not sure where to go from there or if im barking up the wrong tree here.....

any support in this matter would be great

**Comment by cletusc** [comment]
Steam is using it's own browser, but last I looked it was using the Gecko to render. In other words, until Steam specifically supports browser addons, which I doubt will ever happen, BTTV won't work on it.

**Comment by ArcanicFlame** [comment]
*insert darth vader scream here*
