### ISSUE TITLE
Incorrect emote token

### ISSUE THREAD

**Issue by ScrubN** [night/betterttv#6542]
### Describe the bug

If a given channel has `fish` as an emote and an accompanying bot command `!fish`, any uses of the command will incorrectly be shown as the `fish` emote and the `!` will not be present.

### Steps to reproduce

1. Send any emote but prepended by a `!` (`FeelsOkayMan` -> `!FeelsOkayMan`) in Twitch chat
2. Observe that the token is incorrectly shown as an emote

### Expected behavior

The token `!FeelsOkayMan` should remain as the text `!FeelsOkayMan`

### Screenshots

| BTTV Enabled | BTTV Disabled |
|--------|--------|
| ![image](https://github.com/night/betterttv/assets/72096833/cee9c5fc-aee9-4055-bf59-4a9a7bd11491) | ![image](https://github.com/night/betterttv/assets/72096833/b1a15d8d-661b-4176-b08d-1b319275f624) | 

### Device information

- OS: Windows 10 22H2
- Browser: Brave 1.61.104 Chromium: 120.0.6099.115 (Official Build) (64-bit) 
- Version: 7.5.11

### Additional information

It should be noted that 7TV allows emote names/aliases to start with `!` (for example, [shigetora](https://7tv.app/users/6196be3a6467596b1d626b7c) has emotes named `!boost` and `!play`), and should fixing this issue break tokenizing these emotes, I would prefer to keep compatibility with the emotes as this issue is very minor.

**Comment by night** [comment]
This would actually be considered working as intended, but it looks like Twitch doesn't tokenize its own emotes any longer when surrounded by symbols. As a result, we've gone ahead and removed our support for them too.
