### ISSUE TITLE
i can't see people that say my name

### ISSUE THREAD

**Issue by sas123** [night/BetterTTV#656]
hi. 
the title explains my problem. i can't see messages with my name in it. i tried turning off bttv and then i my problem was fixed but BTTV is life so i cant live without it.

**Comment by night** [comment]
Remove your name from your blacklisted keywords in the chat settings.

**Comment by sas123** [comment]
i tried that but it didn't work, ive tried "reinstalling" it too

**Comment by voloshink** [comment]
Make a backup of your settings and post that.

**Comment by sas123** [comment]
![2015-08-15_21-29-31](https://cloud.githubusercontent.com/assets/12979060/9290456/ca9d9d2c-4394-11e5-84cf-717fb2444acc.png)
![2015-08-15_21-30-50](https://cloud.githubusercontent.com/assets/12979060/9290461/ee6aadf8-4394-11e5-80f7-0bb0604a89f8.png)
![2015-08-15_21-31-24](https://cloud.githubusercontent.com/assets/12979060/9290463/fdd1d564-4394-11e5-8712-4cdaff00d027.png)

**Comment by voloshink** [comment]
no, use the backup/import tab to get a backup file

**Comment by sas123** [comment]
how do i post that here?

**Comment by voloshink** [comment]
open it in a text editor and post the contents

**Comment by cletusc** [comment]
> how do i post that here?

1. Open https://gist.github.com/
1. Drag the backup file onto the webpage.
1. Press "Create secret gist"
1. Paste the link that it redirected to.

**Comment by sas123** [comment]
{"anonChat":false,"alphaTags":false,"autoTheatreMode":false,"bttvChat":false,"bttvEmotes":true,"bttvGIFEmotes":true,"showBlueButtons":true,"chatImagePreview":true,"darkenedMode":true,"showDirectoryLiveTab":false,"desktopNotifications":true,"dblclickTranslation":false,"disableHostMode":false,"disableUsernameColors":false,"disableWhispers":false,"dblClickAutoComplete":true,"embeddedPolling":true,"clickTwitchEmotes":true,"showFeaturedChannels":false,"followingNotifications":true,"groupChatRemoval":false,"hostButton":true,"showJTVTags":false,"showMonkeyEmotes":false,"modcardsKeybinds":true,"alertOtherMessages":true,"highlightFeedback":true,"hideDeletedMessages":false,"showDeletedMessages":true,"splitChat":true,"tabCompletionTooltip":false,"twitchCast":false,"blacklistKeywords":"MomsPotato Moms","chatLineHistory":true,"chatWidth":340,"consoleLog":false,"flipDashboard":false,"highlightKeywords":"","scrollbackAmount":150}

**Comment by voloshink** [comment]
what's your twitch username?

**Comment by sas123** [comment]
MomsPotato

**Comment by voloshink** [comment]
well, your name is still in the blacklist:
"blacklistKeywords":"MomsPotato Moms"

**Comment by sas123** [comment]
wtf, how is that there lol

**Comment by sas123** [comment]
thanks

**Comment by voloshink** [comment]
did you accidentally add it to the blacklist in stead of the highlight list?

**Comment by sas123** [comment]
maybe i did that

**Comment by sas123** [comment]
well its fixed now so
