### ISSUE TITLE
An animated emote is not synced to Discord even after manual syncing

### ISSUE THREAD

**Issue by Polda18** [night/betterttv#6577]
### Describe the bug

I've got 16 emotes at the moment on my BetterTTV emotes set for my channel, 4 of them are animated. That means 12 emotes are static. However, with my Discord account and server attached to my BTTV account, only 15 of them have been synced (all of 12 static emotes and 3 animated out of 4), [`catJAM`](https://betterttv.com/emotes/5f1b0186cf6d2144653d2970) by **MadLittleCat** wasn't for some reason synced.

At first I thought it was simply just a rate limit issue and later sync would help it. But today I did the second sync and nothing changed, the one animated emote is still missing, and there are no errors on my dashboard. That one emote just won't sync no matter what. So I'm safe to rule rate limit out. But the page won't tell me what's wrong. The sync page tells me everything is okay, there's a checkmark and correct latest sync date, which is today. And dashboard has no errors, no messages, nada.

I feel like this is likely just a bug and either the emote is fantom on my BTTV channel and not really there (therefore cannot be used), or the syncing bot for some reason can't see the emote (but is otherwise usable on my channel).

### Steps to reproduce

1. Add emotes (`catJAM` in this case was added from shared emotes library), use like 16+ emotes on your channel.
2. Connect Discord account, add BetterTTV bot to your server
3. Sync emotes
4. One or more emotes won't sync up. No errors in dashboard.

### Expected behavior

Either sync all emotes, or tell me what went wrong with the ones that didn't sync. Do not tell me everything is okay when it clearly isn't.

### Screenshots

![BetterTTV integrations, including Discord](https://github.com/night/betterttv/assets/25118993/b8b1ab24-529f-4386-ab87-d5216c8d0c7e)
BetterTTV integrations, including Discord (notice the Discord sync time)

![Emotes in BetterTTV](https://github.com/night/betterttv/assets/25118993/dddf85fa-4b98-4073-92fd-f2455df15fda)
Emotes in BetterTTV. `catJAM` (the missing emote) is highlighted. Notice no errors in the page.

![Animated emotes in my Discord](https://github.com/night/betterttv/assets/25118993/77ece930-575c-419d-80e5-54442c02343e)
Animated emotes in my Discord (`catJAM` is animated). Notice one animated emote is missing. That's `catJAM`.

### Device information

- Device: laptop PC
- OS: Windows 11, Insider Preview, 64bit
- Browser: Google Chrome v120.0.6099.218
- Discord client: always latest

### Additional information

I wouldn't normally ring a bell, my life doesn't really depend on it, but it would be nice to have it resolved. Related issue #5927 was marked as invalid as the page was supposed to provide an error message on dashboard whenever there was an issue with syncing, but the person in question didn't see any error message and in response re-opened the issue with additional info, and the issue was then closed automatically for inactivity. That person was likely waiting for you to answer, and it took 3 months to be closed automatically for inactivity. That person in linked issue likely had the same issue as me, and likely a lot more emotes than me. And it was all in last year. You have about 4200 closed issues in total for the entire duration of the GitHub repository, and only 3 issues currently open (now 4). I don't believe you are so busy with only 3-5 issues opened that you can't answer one re-opened issue in 3 months. That person in linked issue likely had the same issue as me, and likely a lot more emotes than me. And it was all in last year. Is this issue tracker abandoned or what?

**Comment by night** [comment]
In general when emotes fail to sync it's generally because they are not compatible with Discord. We've added additional error logging to the sync system, so you should now see these errors when individual emotes fail to upload.

> I don't believe you are so busy with only 3-5 issues opened that you can't answer one re-opened issue in 3 months. That person in linked issue likely had the same issue as me, and likely a lot more emotes than me. And it was all in last year. Is this issue tracker abandoned or what?

If problems persist after an issue is closed, users should open a new issue. Closed issues are not actively monitored, meaning we probably will not see a reply to it unless someone brings it to our attention.

**Comment by Polda18** [comment]
It looks like the errors are those: `Emoji too large (Emote: catJAM). Emoji too large (Emote: Shrek). Emoji too large (Emote: PogTasty).`

So Shrek isn't compatible as well, and PogTasty isn't compatible as well. I might be able to replace them with compatible versions. It doesn't help tho that Discord doesn't list maximum supported size. I don't know if it's related to file size (the amount of data) or the dimensional size of the image.

**Comment by night** [comment]
The restrictions are related to file size, since BetterTTV emotes are compatible with Discord's dimension sizes.
