### ISSUE TITLE
Customize BetterTTV Theme Colors

### ISSUE THREAD

**Issue by BisketProject** [night/BetterTTV#658]
Hello My name is OfficialLayersTV and I think it would be cool if you could upload images or have a color picker for BetterTTV!  Anyways I also wanted to know if I could be an emote approver or something else, because I like that kind of work and I like the SwagTag! Thanks, Have a Good One!
~OfficialLayersTV

**Comment by night** [comment]
we no longer support a custom theme at all, so this is not doable any longer.
