### ISSUE TITLE
Emote info not displaying at all (Chrome + BTT v6.8R42)

### ISSUE THREAD

**Issue by Mistrelvous** [night/BetterTTV#660]
For some reason, whenever I hover my cursor over an emote in Twitch, I get no info about that emote whatsoever. I'm using the latest Chrome browser and BTT v6.8R42. I cannot figure out what is wrong.
Here are the 8 BTT settings I have enabled:
-BetterTTV Emotes
-BetterTTV GIF Emotes
-Chat Image Preview
-DarkenTTV
-Double-Click Translation
-Disable Host Mode
-Embedded Polling
-Following Notifications

BTT used to show me the text version of the emote and the channel from which it came from, but now nothing happens at all when I hover over an emote. If I use a different browser like Firefox without BTT installed, I can see the basic information that Twitch gives, like the text version of the emote, but when I use the latest BTT and hover over an emote, I get nothing at all. Same thing happens when I disable the BTT extension in Chrome: I get access to the basic information of the emote from Twitch, but when I enable BTT in Chrome, nothing happens when I hover over an emote. It's really frustrating because the emote information BTT gave was one of the best features of BTT.

**Comment by night** [comment]
It's possible you loaded the extension during a CDN hiccup. Our edge in NJ was down for a little while, so users that geolocate to it were having issues loading stuff from our API, like the emote -> channel relationships. It should be functioning fine right now, however.
