### ISSUE TITLE
 My bettertv is not working on twitch chat.

### ISSUE THREAD

**Issue by dbonfleur** [night/betterttv#6605]
### Describe the bug

It simply doesn't load the emotes to the Twitch chat, I've tried reinstalling it a few times, but nothing changed, when inspecting elements I can notice some errors occurring, but I don't have the knowledge to carry out maintenance.

### Steps to reproduce

1. Go to twitch.
2. Some twitch chat.
3. The chat does not display emotes.

### Expected behavior

BetterTV emotes were supposed to appear in my chat, but nothing happened.

### Screenshots

![image](https://github.com/night/betterttv/assets/54067086/8a60c29b-ca6b-4c53-965c-de9c28a90b4b)

### Device information

Device: Notebook Lenovo.
OS: Windows 10.
Browser: Chrome.
Version: 121.

**Comment by night** [comment]
I am not able to reproduce any issues with emotes loading in chat.

Make sure you've installed the right BetterTTV, as you've been referring to our product as BetterTV and that's not correct.

Additionally, not all emotes you see are from BetterTTV. You may need to turn on additional emote providers in the BetterTTV Settings.
