### ISSUE TITLE
Chat messages added to keyword list not getting highlighted

### ISSUE THREAD

**Issue by MikeBrasser** [night/betterttv#6607]
### Describe the bug

As the title indicates, If a message is added to to the highlight keywords list, the chat message won't get highlighted.

It works however correctly for usernames.

See screenshots & steps to reproduce for more info.

### Steps to reproduce

1. Add word to highlight keywords list (with type: message).
2. Send chat message that contains that word.

### Expected behavior

Should be highlighted (default color is red)

### Screenshots

![image](https://github.com/night/betterttv/assets/40915858/0bdcbc9c-0337-48fc-a53f-83780dc4d46b)
![image](https://github.com/night/betterttv/assets/40915858/09ad6874-a1de-4858-a480-914a22167dba)

### Device information

Browser Chrome v120.0.6099.227

**Comment by night** [comment]
I am not able to reproduce any issues with message highlighting. Did you check to make sure you do not have other browser extensions installed? Other extensions can "take over" the chat, meaning our features may not work properly.
