### ISSUE TITLE
Getting error when attempting to create a new emote

### ISSUE THREAD

**Issue by JonathanVelkeneers** [night/betterttv#6608]
### Describe the bug

Getting CORS error in browser console when trying to create a new emote.

### Steps to reproduce

1. Go to https://betterttv.com/dashboard/emotes/upload
2. Attempt to request an emote
3. Request does not go through and shows error in browser console

### Expected behavior

The request goes through and the emote request is submitted

### Screenshots

![image](https://github.com/night/betterttv/assets/7956514/acaaa477-832a-46f8-8cca-f15920b0525a)

### Device information

Windows PC
Google chrome
adblock disabled

**Comment by night** [comment]
I am not able to reproduce any issues with emote uploading. Usually a 520 error implies there's a temporary issue, and can be related to the Cloudflare PoP you're connecting from. If you're still having issues, and it only occurs with a specific emote, please attach the emote affected and we can look into this further.

**Comment by JonathanVelkeneers** [comment]
> I am not able to reproduce any issues with emote uploading. Usually a 520 error implies there's a temporary issue, and can be related to the Cloudflare PoP you're connecting from. If you're still having issues, and it only occurs with a specific emote, please attach the emote affected and we can look into this further.

I've tested some stuff, when I changed the emote name it resolved the above issue, but gave another one (file to large).
It's weird that the form does not give any errors about an invalid name or too large file before submitting. 

Maybe this is something you could add if possible?
