### ISSUE TITLE
Most features disabled, emotes not working, Pro badge not showing, etc.

### ISSUE THREAD

**Issue by Milianaire** [night/betterttv#6627]
### Describe the bug

Starting yesterday, I noticed that my emotes were not working and my pro badge is disabled. I thought it might be a payment issue so I updated my payment information which seemed to fix the issue temporarily, but now my BetterTTV emote dashboard seems to be glitching out again. Nothing seems to work correctly at all right now. Chrome is my browser and I've uninstalled and reinstalled the browser extension but it didn't fix anything. Thanks in advance for your help!

### Steps to reproduce

No steps.

### Expected behavior

Nothing seems to be working with the application right now. I've noticed a few other people on social media here and there that have experienced similar issues lately.

### Screenshots

![bttv_emotes](https://github.com/night/betterttv/assets/85083030/24c20d93-1f09-4ce8-8e67-e15cba53499a)

### Device information

Chrome

**Comment by night** [comment]
There's some sort of Twitch site update, which is partially rolled out, that BetterTTV is not compatible with. Unfortunately until our development team receives this update we are not able to address the issue.

**Comment by night** [comment]
fixed via b2a07d70a4e613ac616d608ac2392cffeadc85c3
