### ISSUE TITLE
Pressing tab to finish emotes

### ISSUE THREAD

**Issue by Sonjeba** [night/BetterTTV#663]
I know this is already a feature, but when I press tab to auto-complete an emote sometimes It'll auto-complete into a user in the chat. So how about an option to disable tab from auto completing into a username and always go for an emote? Thanks for listening :).

**Comment by thinkpad4** [comment]
Usernames come first in the tab complete list, then emotes

**Comment by night** [comment]
@thinkpad4 is correct. We already tab complete emotes for you, but you may need to type a few more letters to make sure you don't get a matching username. It tends to work better in smaller channels, though, since larger ones have more users.
