### ISSUE TITLE
to get logged out from chat nocht work anymore for me

### ISSUE THREAD

**Issue by Prasao** [night/betterttv#6644]
### Describe the bug

on chrome, opera, microsoft edge this feature is not anymore working, on vivaldi is still working

### Steps to reproduce

he dont log me out

### Expected behavior

no idea

### Screenshots

![image](https://github.com/night/betterttv/assets/160815609/2d96297e-2a1a-4136-9fd3-4887b43f3fe9)

### Device information

Computer
Win11

**Comment by Seekrano** [comment]
Yh, it's not working here either!

**Comment by kilroy98** [comment]
Same problem.

**Comment by Prasao** [comment]
now on brave nocht working to anymore
