### ISSUE TITLE
Chat history with arrow key not working

### ISSUE THREAD

**Issue by bodynar** [night/betterttv#6645]
### Describe the bug

After installing and configuring extensions, chat history does not work
After sending a message in chat - the up arrow key in chat does nothing

### Steps to reproduce

1. Enable "Chat message history" option
2. Write something in chat & send it
3. Press arrow up in chat message input

### Expected behavior

Last message will be copied into text field

### Screenshots

Settings:
![image](https://github.com/night/betterttv/assets/22620134/b71b7292-eb8d-42b2-a926-0b62c647f249)

### Device information

- PC
- OS: Win 10 (22H2 19045.2193)
- Browser: Chrome (121.0.6167.187 (Official Build) (64-bit))
- Version: 7.5.16

### Additional information

Saved settings
[bttv_settings.zip](https://github.com/night/betterttv/files/14375670/bttv_settings.zip)

**Comment by frshhh** [comment]
Same here. Additionally I disabled every addon including BTTV, then re-enabled BTTV. Restarted browser, etc.

- PC
- OS: Win 10 (22H2 19045.4046)
- Browser: Firefox 123.0 (64-bit)
- Version: 7.5.16

**Comment by AnarcoPunkRJ** [comment]
The bug started for me today with version 7.5.17, how do I go back to the previous one?

![chrome_hciSdOq4ko](https://github.com/night/betterttv/assets/161160703/2701199d-e69a-42b6-bb14-1a688098c5c6)

![chrome_zCGrjkK4rR](https://github.com/night/betterttv/assets/161160703/e1fe470b-eacd-49c4-9cac-501fc937eaad)

**Comment by bodynar** [comment]
Thank you, @night 

Now it's working

**Comment by AnarcoPunkRJ** [comment]
For me it was exactly the opposite, it stopped working with version 7.5.17.
I'm using another extension along with BTTV to be able to use the function.

**Comment by LilacAesthete** [comment]
I've currently have had this problem for a few days now. It also includes using down-arrow to clear the text bar when typing. I have deleted the extension as well as resetting BTTV settings to default.

Laptop
OS: macOS Monterey version 12.7.2
Browser: Firefox 123.0 (64-bit)
Version: 7.5.16

**Comment by adrii26** [comment]
Même problème sur chrome et opera

**Comment by bodynar** [comment]
It's broken again for me, @night 

Should we re-open issue?

**Comment by BernardLaurenzo** [comment]
it worked for me for 1 day.... if anyone needs info or help testing i have discord
