### ISSUE TITLE
website is cut in half on the sites

### ISSUE THREAD

**Issue by Scarapter** [night/BetterTTV#665]
yes, i have tried reloading, and disabling BTTV fixed everything, but i want BTTV on
https://gyazo.com/f7ec69372fc0795b9c76f1ea7d813aaa
screenshot

**Comment by night** [comment]
It looks like that chat width somehow set below its minimum. You can clear your cookies/cache to fix it, or you can drag the left side of chat to resize it (fixing the issue).
