### ISSUE TITLE
On MS Edge, my settings aren't being saved.

### ISSUE THREAD

**Issue by texpert25** [night/betterttv#6654]
### Describe the bug

Title sums it up. I have to re-import settings from Firefox after every browser restart, because none of the settings save e.g. auto-claim channel points.

### Steps to reproduce

1. Install BetterTTV on the Microsoft Edge Add-ons store
2. Change a couple settings
3. Restart the browser

### Expected behavior

Well, I expect the settings to save.

### Screenshots

![Desktop Screenshot 2024 02 25 - 19 40 27 98](https://github.com/night/betterttv/assets/154618809/24dc003a-9d31-4421-be68-488b1ce1e341)

### Device information

ASUS TUF Dash F15 - Windows 11
Microsoft Edge (Dev) - issue affects all channels
Version 123.0.2400.1 64bit

**Comment by night** [comment]
You may need to update your Edge settings to stop clearing cookies on close, as that browser feature clears page local storage (where BetterTTV stores settings).
