### ISSUE TITLE
50 Points Not Automatically Claiming, but 10 Points Are

### ISSUE THREAD

**Issue by WilliamTell13** [night/betterttv#6655]
### Describe the bug

10 channel points are automatically being claimed, but 50 channel point bonuses are not being claimed automatically. I have to manually click on the little box every time there is a 50 point bonus. This just started happening over the past few days.

### Steps to reproduce

When there is a 50 point bonus box, it must manually be clicked to claim the 50 points instead of BetterTTV automatically claiming them.

### Expected behavior

For BetterTTV to automatically claim the 50 bonus point boxes.

### Screenshots

![image](https://github.com/night/betterttv/assets/104655992/a8a29554-d0b7-463f-a278-eae8913c018d)
![image](https://github.com/night/betterttv/assets/104655992/d0d6e294-bb01-4d0b-9cfb-fa9bc010c306)
![image](https://github.com/night/betterttv/assets/104655992/1443b532-5206-4096-9add-04973862e21d)

### Device information

Device: PC
OS: Windows 11
Browser: Chrome 122.0.6261.70
BetterTTV: 7.5.17

**Comment by night** [comment]
Just tested this out, and am not able to reproduce this issue on the latest release. The bonus button seems to be clicked as normal. If you're still having trouble, double check that you have the Auto Claim setting enabled in the BetterTTV Settings. Sometimes your settings can be reset!
