### ISSUE TITLE
Message History function

### ISSUE THREAD

**Issue by MatTheoo89** [night/betterttv#6659]
### Describe the bug

Good evening,
the Message History function
Retrieve previously sent messages in chat by pressing up/down with the arrow

This function is no longer active, I tested on 3 PCs but it hasn't worked for 2 days

### Steps to reproduce

I press the up arrow and expect the previous message

### Expected behavior

I press the up arrow and expect the previous message

### Screenshots

no screen

### Device information

Google Chrome Versione 122.0.6261.95
Firefox 123.0

**Comment by AnarcoPunkRJ** [comment]
Same

**Comment by night** [comment]
This issue is already fixed in version 7.5.18. The update is out on Edge and Chrome, but is still awaiting review by Firefox's team.
