### ISSUE TITLE
global ban prevention

### ISSUE THREAD

**Issue by jaromirros** [night/BetterTTV#666]
i know the program chatty has a feature like this, but is a bit clunky to use, basically a way to limit you from sending messages so fast that you get globally banned from twitch.

**Comment by night** [comment]
We used to allow this, but it only promoted spamming chats on Twitch. We originally only added it because moderators were limited to 20 messages per 30 seconds. Since the limit is now 100 per 30 for mods, there's not a reason to add this feature.
