### ISSUE TITLE
Hide Channels Options Not Working

### ISSUE THREAD

**Issue by novastellaris** [night/betterttv#6661]
### Describe the bug

all of the show/hide options for channel types, aside from offline followed channels, does not work. i've tried toggling the options off and on, cleared my cache, and tried temporarily disabling ttv lol pro, but none of these have worked

### Steps to reproduce

1. go to bttv settings
2. go to directory settings
3. scroll down to sidebar
4. toggle sidebar options
5. observe the lack of change in the sidebar

### Expected behavior

toggling options should show or hide certain channel lists

### Screenshots

![image](https://github.com/night/betterttv/assets/162022913/e2b4489a-91d4-4bb5-a534-9b6f5d147c6d)

### Device information

- OS: windows 11
- browser: firefox
- version: 123.0

**Comment by TheDeeGee** [comment]
Can confirm, i'm using Edge myself on Windows 10.

**Comment by frostcone** [comment]
Confirmed. Windows 11, Brave.

**Comment by Sovvv** [comment]
Same issue, Firefox and Vivaldi 6.6

**Comment by theJediFORCE** [comment]
Same on Chrome...It sems to work fine but when I minimize the window which makes the sidebar callapse the suggested and following etc all show up and when expanded they are there until page is refreshed>at full size so the sidebar is not callapsed.

**Comment by dclstn** [comment]
Fixed by d735cf6a28478981b20a115a765c12b8e24f789b
