### ISSUE TITLE
Feature Request: Remove messages based on filters.

### ISSUE THREAD

**Issue by RichMoney** [night/BetterTTV#667]
Back when Twitch Plays pokemon was pretty popular there were a few scripts that would filter out chat based on text. I'd like to see this feature added into BTTV as apparently the chat has changed enough since the old scripts were written that they aren't obviously able to be modified to work with other words.

**Comment by voloshink** [comment]
Please provide some more details, how would it be different from the current blacklist feature

**Comment by night** [comment]
Duplicates: https://github.com/night/BetterTTV/labels/highlights%2Fblacklist
