### ISSUE TITLE
Add a Viewer/follower count to theater mode.

### ISSUE THREAD

**Issue by xNEWT** [night/BetterTTV#669]
![default](https://cloud.githubusercontent.com/assets/13889150/9387569/ce606ea4-4726-11e5-97a4-2a847a80f2d8.jpg)

**Comment by night** [comment]
That seems a bit cluttered to me, sorry. If you want those extra details, I don't really see why just closing the left sidebar doesn't suffice? You then get access to the stats and the title.

**Comment by Akadin** [comment]
How does closing the sidebar show this information? (I'm using the chrome plugin) I have to leave theater mode. And that bar autohide's unless the mouse is over the video I don't see how that is cluttered. You could make it a toggle feature?

**Comment by xNEWT** [comment]
I was thinking this exact same thing, if you moved the counter to the
center of the bar it wouldn't seem as cluttered. And it could also be a
toggled feature.

**Comment by Akadin** [comment]
There is another chrome extension called FrankerFaceZ which adds this function. It works with BTTV so using both together is the workaround for me.
