### ISSUE TITLE
Unable to see any emotes

### ISSUE THREAD

**Issue by SirFireball3521** [night/betterttv#6698]
### Describe the bug

I can't see any betterttv emotes, even though other users in the chat confirmed they could see them.

### Steps to reproduce

Open twitch, go to any channel, type in any betterttv emote, or wait for any other user to send one.

### Expected behavior

I expect the emotes to be there.

### Screenshots

I can get screenshots if needed, but it's really just the text there.

### Device information

Device info: `Linux shellshockmk2 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux`
Firefox info: `Mozilla Firefox 124.0 20240318230340 20240318230340 `
Everything is up to date in terms of the extensions.

### Additional information

I have my console messages here: 
[console-export-2024-3-21_21-24-36.txt](https://github.com/night/betterttv/files/14716894/console-export-2024-3-21_21-24-36.txt)

**Comment by night** [comment]
We're not able to reproduce any issues with emotes being displayed. They may not be BetterTTV emotes that are being used. You can enable additional emote providers in the BetterTTV settings.
