### ISSUE TITLE
Autoplay is always on on the homepage

### ISSUE THREAD

**Issue by At0mFr3d** [night/betterttv#6710]
### Describe the bug

Autoplay on the homepage is always on even though the hook is set correctly

### Steps to reproduce

This is always the case

### Expected behavior

Autoplay on the homepage should be disabled

### Screenshots

![Screenshot 2024-03-31 103615](https://github.com/night/betterttv/assets/103222558/68b2519c-e0ba-4f1d-9d71-133d9db86b45)

### Device information

Windows 11, Version 23H2 Build 22631.3374, Browser Firefox 124.0.1

**Comment by night** [comment]
I'm not able to reproduce this issue using Firefox 124. If you're still having issues, can you provide a video demonstrating the issue? You might also try disabling other browser extensions, as they can sometimes override BetterTTV's features.
