### ISSUE TITLE
Emote menu sometimes does not focus typing input

### ISSUE THREAD

**Issue by ScrubN** [night/betterttv#6723]
### Describe the bug

Sometimes the emote menu does not focus typing input when opened and requires me to click or close then reopen the emote menu to gain focus of the search box.

### Steps to reproduce

- Click anywhere to unfocus the Twitch chat input box
- Click the chatbox as if you were going to write a message
- Open the emote menu with the shortcut <kbd>alt</kbd> + <kbd>e</kbd> immediately following the previous step (speed is key)
- Observe the emote menu's search box does not gain typing focus

### Expected behavior

The emote menu's search box should have gained typing focus

### Screenshots

![brave_hoDCv4OJb4 (1)](https://github.com/night/betterttv/assets/72096833/52c3ced9-7a58-43e7-b766-8eacc9e34e96)

### Device information

- Windows 10 22H2
- Brave 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit) 
- BTTV 7.5.18

### Additional information

I have found that it tends to happen more often when I open the menu very fast after focusing the chatbox, regardless of if I focused the chatbox from clicking it or by alt-tabbing into my browser from another program when I had previously selected the chatbox before switching focus to another program.

**Comment by dclstn** [comment]
Fixed by 6447dec9da0af91b494ffa506a1d066ef7c0686c
