### ISSUE TITLE
Join Channel doc header missing ID

### ISSUE THREAD

**Issue by ScrubN** [night/betterttv#6739]
### Describe the bug

The `Join Channel` header on the [BetterTTV WebSocket](https://betterttv.com/developers/websocket) page is missing the id `channel-join`, causing the page to not scroll when the `Join Channel` navigation header is clicked.

### Steps to reproduce

1. Go to https://betterttv.com/developers/websocket
2. Scroll down the page
3. Click the `Join Channel` navigation header on the left
4. Observe the page does not scroll to the correct section

### Expected behavior

The page scrolls to the correct section

### Screenshots

![image](https://github.com/night/betterttv/assets/72096833/4d0aedb7-df69-4339-b397-9fe7dc35d63d)
![image](https://github.com/night/betterttv/assets/72096833/24990b67-ea5b-4e29-9179-a966cc002e51)

### Device information

- Windows 10 22H2
- Brave 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)

**Comment by dclstn** [comment]
This is fixed now
