### ISSUE TITLE
Auto Play settings don't work for Front-page player

### ISSUE THREAD

**Issue by antyone** [night/betterttv#6740]
### Describe the bug

Front-page player is automatically playing the video even though in the settings it says otherwise

### Steps to reproduce

Go to settings,
find "Auto Play" category,
uncheck Front-page Player,
go to front page of twitch,
front-page video auto-plays

### Expected behavior

Stop the front-page player from auto-play

### Screenshots

![image](https://github.com/night/betterttv/assets/17205651/e77ab1b3-5fe6-4387-9265-e09b11a246f0)

### Device information

Browser - latest firefox on PC

### Additional information

No addons were added nor any settings changed, this just stopped working recently for some reason

**Comment by night** [comment]
fixed via #6744
