### ISSUE TITLE
Mod View Readable Colors 

### ISSUE THREAD

**Issue by fakeadmiral** [night/betterttv#6743]
### Describe the bug

Since the last update on Feb 29, 2024, the "Readable Colors" setting has not been working correctly for me. When activated, all colors become almost unreadable. When it is deactivated, some colors are displayed as normally readable (as if the setting were on), while others are not. I've also tried multiple browsers, cleared the cache, and even reinstalled the plugin. The bug still persists for me.

### Steps to reproduce

Enabling and disabling the setting when in mod view.

### Expected behavior

That the colors are all readable again, as before the update.

### Screenshots

![Screenshot 2024-04-11 173201](https://github.com/night/betterttv/assets/137042473/f55f25af-2042-4c34-9bb4-f643115176ac)

The top line is with the setting disabled, and the two following lines are with the setting enabled.

### Device information

Firefox Developer Edition

**Comment by night** [comment]
Can you clarify the following:

- Do you use Twitch's dark mode?
- Is your system set to dark mode?
- Is BetterTTV set to dark mode?
- Is BetterTTV's readable username colors enabled?
- Is Twitch's readable username colors enabled?

**Comment by night** [comment]
Closing this due to lack of response. If you're still having issues, feel free to open a new ticket with more information.
