### ISSUE TITLE
Persist showing the emote menu button after typing

### ISSUE THREAD

**Issue by dclstn** [night/betterttv#6746]
### Discussed in https://github.com/night/betterttv/discussions/6742

<div type='discussions-op-text'>

<sup>Originally posted by **AomariDev** April 11, 2024</sup>
![slika](https://github.com/night/betterttv/assets/5493998/aa3f51ea-d463-45bb-9c35-d59fd6ddac99)
![slika](https://github.com/night/betterttv/assets/5493998/a0939328-a482-482a-9261-f1fd56a971a2)

As seen in pictures above the emote menu button disappears after typing.

Inspecting and moving it from "picker-buttons" to "message-buttons" seems to make it stay even when typing.

![slika](https://github.com/night/betterttv/assets/5493998/1597358c-bc9b-42bb-a479-283ca6e56a61)

So could it be moved there or something?</div>

**Comment by night** [comment]
this was fixed via cb3dd04871af9639da654f7bad906c682ab0ed79
