### ISSUE TITLE
Force new HTML5 Player

### ISSUE THREAD

**Issue by emrerocky** [night/BetterTTV#675]
There should be an option in the BTTV Settings to force the new HTML5 player, kinda like what this app does: https://chrome.google.com/webstore/detail/twitch-html-5-video-playe/hgcegaapnjdkkaboopicfhllkjkjpdhg?hl=en

Thanks for making my Twitch experience 10x better! :smiley:

**Comment by Ansem93** [comment]
It would be usefull for me too!

**Comment by rtainc** [comment]
Side-note: I'm not sure what all the session IDs are used for on Twitch's end, but I was able to copy my `unique_id` and `session_unique_id` cookies, which gives the browser the HTML5 player. It does not seem to give the browser any login data and seems to be purely for opt-in features. This is, of course, much better than replacing the player after the old one loads in.

**Comment by emrerocky** [comment]
Do you think you could go into more detail on how you did that?  I am very interested!

**Comment by rtainc** [comment]
@emrerocky 
On a browser with the HTML5 player, get a cookie editor (such as EditThisCookie for Chrome), go to http://www.twitch.tv/ and grab your `unique_id` and `session_unique_id` cookies. Then on the Flash player browser(s), run in the dev console (often F12):

    document.cookie = "unique_id=%unique_id%; expires=Thu, 21 Aug 2025 19:52:00; domain=.twitch.tv"; document.cookie = "session_unique_id=%session_unique_id%; expires=Sun, 24 Aug 2016 19:52:00";

(Of course replacing the %unique_id% and %session_unique_id% parts with the ones from your cookies.) When you refresh, that browser will now have the HTML5 player. The only problem I see is that I have no idea what information you give out by giving out your `unique_id` and `session_unique_id` cookies so putting one of ours in BetterTTV's code could be dangerous.

**Comment by emrerocky** [comment]
I tried doing this and it unfortunately didn't work...  Is there anything I have to do to format the unique_id and session_unique_id in the command?  Do I have to split up that command for each id?

**Comment by night** [comment]
You do not need to mess with session cookies to embed the player. There's a Twitch.player API that embeds the player.

**Comment by Nathsters** [comment]
You can download a chrome extension that forces the new player. Think it's
called Twitch HTML 5 player.

**Comment by rtainc** [comment]
@emrerocky 
The `session_id` and `session_unique_id` must be from a browser *with* the HTML5 player.

@night 
That is true, but I'm just providing a (possibly) better solution. Swapping out the embed after loading the page is less than elegant and slows down loading times significantly.

**Comment by cletusc** [comment]
An aside--is these even relevant anymore? Yesterday a huge amount of people (myself included) got HTML5 deployed. Did Twitch roll it out to all?

**Comment by emrerocky** [comment]
I still don't naturally have it.

**Comment by rtainc** [comment]
@cletus I don't have it on one of my browsers still.

@emrerocky That is the correct command but it has to be taken from a browser with the HTML5 player. player.twitch.tv is always HTML5 regardless of session id.

**Comment by emrerocky** [comment]
@rtainc It seems to work when I'm on a channel's page but not on the home page of http://twitch.tv.  Thanks for the help though!

**Comment by rtainc** [comment]
I don't think the home page supports the HTML5 player at all, regardless of
if you have it or not.
