### ISSUE TITLE
Personal emotes not showing up

### ISSUE THREAD

**Issue by Nawi915** [night/betterttv#6754]
### Describe the bug

Ive had this happen a couple times now.
I asked streamers and chatters that have bttv support enabled if they can see my personal emotes.

### Steps to reproduce

Join chat try to use personal emote

### Expected behavior

i excpected to pay for Emotes to show up in chat for others too not only for myself.

### Screenshots

![image](https://github.com/night/betterttv/assets/133819030/2a4cb059-e809-4460-bc09-3da77cf602de)
![image](https://github.com/night/betterttv/assets/133819030/149b8a47-8103-4fb0-9a49-ff47182d0f60)

### Device information

na

**Comment by night** [comment]
If users are not able to see them, they would need to first install BetterTTV. The screenshot shown does not depict usage of the official BetterTTV extension. We unfortunately cannot guarantee that emotes work on any other third party extension.

**Comment by Nawi915** [comment]
im not using bttv either im using frankerfacez because of the 7tv support and they show up for me?

**Comment by night** [comment]
They can work if the third party implements our entire API. As was stated, we can't guarantee they will work on anything but BetterTTV.
