### ISSUE TITLE
"Plugin is damaged"

### ISSUE THREAD

**Issue by fusk-l** [night/betterttv#6755]
### Describe the bug

Not working, plugin is damaged.

### Steps to reproduce

Install.

### Expected behavior

It is working.

### Screenshots

![Skærmbillede 2024-04-17 205632](https://github.com/night/betterttv/assets/6765298/b7782b38-7709-424b-b943-276451107b61)

### Device information

Win11 & Opera.

### Additional information

Remove & re-install does not work.

**Comment by night** [comment]
This looks like it may be an issue with your Opera installation or possibly some antivirus software on your system. I would first recommend reinstalling Opera. If that doesn't work, check to make sure your antivirus software isn't quarantining our extension.

**Comment by fusk-l** [comment]
I installed frankenface, worked fine, so i've just been using that. Bttv is the only plugin complaining and it started recently. 
windows defender hasn't touched the plugin, nor is complaining about it in any way.
I have 5 plugins installed, and everything else in opera is working fine.

**Comment by night** [comment]
Well unfortunately the problem isn't on our end and we're not able to assist. If you search google for "this extension may have been corrupted" you can see dozens of people posting about this for various extensions, not just ours.
