### ISSUE TITLE
Firefox becomes extremely slow

### ISSUE THREAD

**Issue by MightyCreak** [night/betterttv#6764]
### Describe the bug

On Twitch, BetterTTV seems to slow down Firefox up to a point where the OS asks why the application is not responding.

### Steps to reproduce

1. Go to a Twitch channel with Firefox (e.g. https://www.twitch.tv/barbarousking)
2. Enter Studio mode (Alt+T)
3. Enter fullscreen mode in Firefox (F11)
4. Write some text in the chat
5. See that each character gets slower and slower to appear, if you've written a long enough sentence, your OS might ask why Firefox is not responding

### Expected behavior

No slowdown, as it was in a previous version of BetterTTV/Twitch.

### Screenshots

![image](https://github.com/night/betterttv/assets/6382548/2931f305-804d-4e9e-bb0f-827759065ab3)

(see how the CPU is at 100% at the 10s mark)

### Device information

- Device: PC
- OS: Linux (Fedora 40)
- Browser: Firefox 126.0
- BetterTTV version: 7.5.21

### Additional information

May have to wait a few hours until you get the faulty behavior...

Edit 1: 30 mins in and you can see that it starts to slow down (could it be a memory leak?)

Edit 2:
* After a bit more than 2h of stream, it gets really slow when typing in the input box.
* Workaround: refresh the page (and you're good for a couple of hours)

Edit 3: updated the device information

**Comment by MightyCreak** [comment]
So yeah I've had a stream opened for a few hours and Firefox gets really slow. As you can see, the CPU gets to 100% while trying to display the text I've just input (see near the 20s mark):

![image](https://github.com/night/betterttv/assets/6382548/f2742db3-56f2-43f0-ab57-d23d4dacc20b)

The memory is good though (4GB out of 16).

@dclstn: Disabling the emotes doesn't change anything though.

But refreshing the page fixes the issue.

**Comment by MightyCreak** [comment]
I confirm that the same behavior happens on Chrome as well. It just takes more time to get there, and the page is still slightly more responsive than with Firefox, but it definitely happens.

**Comment by night** [comment]
it's hard to know why it is slowing down for just you after a while. You may need to log runtime performance when it is slow to see why it is slow. You can learn how to do that at https://developer.chrome.com/docs/devtools/performance#record You can download your log and [email it to us](mailto:support+github@nightdev.com?subject=BetterTTV%20GitHub%20Issue%206764) so we can examine it.

**Comment by MightyCreak** [comment]
Ok, I'll close this issue: I just realized that I have the exact same behavior with the BTTV plugin disable.

Sorry for the trouble.
