### ISSUE TITLE
/chatters not working

### ISSUE THREAD

**Issue by cigeb** [night/betterttv#6765]
### Describe the bug

Command /chatters not working, i like to see how many chatters on stream to check for possible viewbots.

### Steps to reproduce

/chatters on chat

### Expected behavior

Show how many users there is on chat

### Screenshots

![1](https://github.com/night/betterttv/assets/167875599/caaa273f-debd-408c-89ef-4093d3ccbcf0)

"no match"

### Device information

Chrome

**Comment by cigeb** [comment]
commando /part  -- /join not working either

**Comment by dclstn** [comment]
Fixed by #6766
