### ISSUE TITLE
/join command does not work on Firefox.

### ISSUE THREAD

**Issue by PythonGuy64** [night/betterttv#6769]
### Describe the bug

The /join command does not work on Firefox, but works on Brave. It was working before. Nothing happens when typing /join in the chat.

### Steps to reproduce

1. Enable anonymous mode.
2. Try to connect to a chat by typing /join

### Expected behavior

Connection to the chat.

### Screenshots

![2024-04-24 13_08_25-Window](https://github.com/night/betterttv/assets/52058509/a99241d1-0a83-4cd0-ae66-2d0abb3217c9)
![2024-04-24 13_09_07-Window](https://github.com/night/betterttv/assets/52058509/3dd63ff1-7396-4c06-96a9-02ae8bfec3ff)

### Device information

Laptop, Windows 10

**Comment by night** [comment]
This is fixed in version 7.5.19, which is not yet released on Firefox
