### ISSUE TITLE
BetterTTV emotes won't show up on twitch

### ISSUE THREAD

**Issue by thatssoravenclaw** [night/betterttv#6771]
### Describe the bug

I've uninstalled and reinstalled the Chrome extension. I've logged in and out of BetterTTV and Twitch. I've disabled my firewall and antivirus. I've restarted my computer. The emotes are toggled on in the BetterTTV Twitch settings. I still cannot see my BetterTTV emotes on Twitch. Please advise.

### Steps to reproduce

Added emotes to my channel on BetterTTV website. Went to Twitch and they weren't there.

### Expected behavior

I expected my emotes to be available in my chat

### Screenshots

n/a

### Device information

Device: Laptop - ASUS ROG
Browser - Chrome & Edge (both don't show BetterTTV emotes on Twitch)

**Comment by night** [comment]
We are not able to reproduce any issues. When you add emotes to your channel, keep in mind they will only work in your Twitch channel's chat. Emotes can also take up to 15 minutes to work in the chat due to caching.
