### ISSUE TITLE
BetterTTV on Youtube Issue

### ISSUE THREAD

**Issue by Catta1997** [night/betterttv#6772]
### Describe the bug

After new version (7.5.20) on Youtube there is no "Open BetterTTV Settings" and extension not work (Like auto Live Chat) but the settings button there is and extension work if I open the chat in a new tab 

### Steps to reproduce

Update extension to 7.5.20
open a live
there is no button "open setting" where it should be and prior settings not work

### Expected behavior

button and extension work

### Screenshots

On a new tab:
<img width="248" alt="image" src="https://github.com/night/betterttv/assets/34333654/11b1b4de-238d-4b74-ad02-02970b8b75d0">
On "integrated" chat:
<img width="299" alt="image" src="https://github.com/night/betterttv/assets/34333654/d9660b33-1735-4b67-8532-bed97e2c6113">

### Device information

- Browser Google Chrome
- Device MacBook M3 Pro

**Comment by Beerman-pixel** [comment]
I have the same issue, BetterTTV settings and emote menu not showing up on Youtube and my previously applied settings (jump to live chat immediately, enable timestamps for messages) are reset.

![grafik](https://github.com/night/betterttv/assets/75475315/0163608e-fd73-4555-b5f0-1348272499fa)

im on Windows 10 22H2 and Firefox

**Comment by night** [comment]
fixed via 5a00b306855f06e1e04dff857b343936cceb30e4

in the meantime, you can use the popout chat
