### ISSUE TITLE
Can't remove recommended or similar channels in sidebar. Sidebar Error?

### ISSUE THREAD

**Issue by mothehalf** [night/betterttv#6773]
### Describe the bug

Using Firefox (up to date). I've recently switched from Chrome to Firefox and installed BTTV to watch my favorite streamers with my favorite emotes! But unfortunately since I've switched to Firefox, BTTV doesn't turn off Recommended or Similar channels in the sidebar. I just checked Chrome and it doesn't show any of my subscribed channels on the left bar at all now! But for now I'm more concerned that it's not working on Firefox. I'd love to stop seeing channels I'm not interested in, and I'm not sure how to solve this. 

### Steps to reproduce

Install Firefox, install BTTV, attempt to turn off recommended and similar channels.

### Expected behavior

Recommended and Similar channels will stay, despite what you do.

### Screenshots

![Screenshot 2024-04-27 212640](https://github.com/night/betterttv/assets/168322608/6581e90b-bb08-4901-b8fe-2bef24700bc6)

### Device information

Device: PC Desktop // OS: Windows 11, Version 23H2 // Browser: Firefox (latest update/up to date). Other extensions: Adblock, Adblock plus, privacy badger, ttv lol pro (installed after this problem began to occur), ublock origin). Turning them on/off hasn't changed anything.

### Additional information

Doesn't seem to be a problem on every device/firefox/chrome monitor. Does feel like ever since Twitch has really brought out the adblocker guns that it's even messing with BTTV? Unsure.

**Comment by dclstn** [comment]
I cannot reproduce this, is there any errors in the console and what version of betterttv are you using?

**Comment by night** [comment]
Please upgrade to version 7.5.20 and see if problems persist.

**Comment by mothehalf** [comment]
The update works!!! Oh thank you so much! Sorry to dclstn, I was busy at work and forgot to reply. :) Thank you guys very much!!!
