### ISSUE TITLE
Bttv does not disable front-page player

### ISSUE THREAD

**Issue by DejanRibnikar** [night/betterttv#6774]
### Describe the bug

Front-page player keeps playing. Checkmark in settings does nothing.

### Steps to reproduce

Open twitch.tv

### Expected behavior

Front-page player does not play

### Screenshots

![image](https://github.com/night/betterttv/assets/25691615/8d0d2102-8914-4e90-b96b-3b4111a0be08)

### Device information

Windows 10, firefox

**Comment by dclstn** [comment]
I cannot reproduce this behaviour, for clarification the "checkmark" should enable autoplay, and unchecking should disable the homepage autoplay from playing. If this is still the case, can you share your betterttv version?

**Comment by DejanRibnikar** [comment]
It's latest version, 7.5.18
This has been happening for about a month, before if worked fine.

**Comment by night** [comment]
Please upgrade to version 7.5.20 and see if problems persist.
