### ISSUE TITLE
BetterTTV only working in popout chat on youtube in Firefox

### ISSUE THREAD

**Issue by AomariDev** [night/betterttv#6785]
### Describe the bug

For some reason, both, the emote menu and BetterTTV Settings don't appear on Youtube chat on Firefox browser. Tested it on Chrome and Edge and it works fine there. Also If I popout youtube chat it works fine there only for some reason.

### Steps to reproduce

1. Open any youtube livestream
2. Check chat and see no emote menu nor BetterTTV Settings menu
3. Try popout chat and see the menus are normally appearing there

### Expected behavior

The emote menu and BetterTTV Settings should exist in normal youtube chat and not only in popout chat.

### Screenshots

![Screenshot 2024-05-02 at 17-42-41 【Splatoon 3】Flare vs IRyS Private Matches! w_ Listener Participation 🔥💎](https://github.com/night/betterttv/assets/5493998/41f98f0b-fe1e-41a9-ba2f-88d1acb78e79)
![Screenshot 2024-05-02 at 17-42-29 【Splatoon 3】Flare vs IRyS Private Matches! w_ Listener Participation 🔥💎](https://github.com/night/betterttv/assets/5493998/1f705fb1-8249-4ecb-9eb9-c07bf7815b37)

### Device information

Device information

- Device: PC
- OS: Windows 11
- Browser: Firefox 125.0.3
- BetterTTV version:  7.5.20

**Comment by night** [comment]
This is already fixed in version 7.5.21. Unfortunately you'll need to wait for Firefox to approve that version.
