### ISSUE TITLE
Left side chat overlap stream in cinema mode

### ISSUE THREAD

**Issue by Tobbax** [night/betterttv#6799]
### Describe the bug

Left side chat overlap the stream in cinema mode. They should be side by side

### Steps to reproduce

Change chat to be on the left side
enter cinema mode
see chat it overlap the stream

### Expected behavior

should be side by side

### Screenshots

![bild](https://github.com/night/betterttv/assets/44871092/cdf2e6af-19b7-4189-917e-52662233bdb7)

### Device information

windows
firefox 125.0.3

**Comment by Tobbax** [comment]
I now cant reproduce the bug, seems it fixed it self

**Comment by night** [comment]
cool. thanks for letting us know. if it happens again, feel free to open a new issue!
