### ISSUE TITLE
Channel-Specific Keywords

### ISSUE THREAD

**Issue by night** [night/betterttv#68]
I mod a number of channels, and in those channels I'd like certain keywords to be highlighted (such as "mod", "mods" in case users see something that I have missed). But as you could imagine, this could get annoying on all channels.

At the sametime, however, global keywords are great for things like my username, so I wouldn't want to see that feature change.

Thanks again for the great tool.

**Comment by LeetPete** [comment]
I'd love to see this too, I mod 9 channels all with different rules

**Comment by Izlsnizzt** [comment]
Bump this suggestion for visibility.

**Comment by Cubiss** [comment]
That would be amazing feature. Highlight for modding and blacklist for channels with high spam rate (like Warframe with their 'plat' spam).

**Comment by night** [comment]
fixed via 3a5bdd2f3b806bcf7c996a292b030a4fccf280d6
