### ISSUE TITLE
add a report for spam button to the profile card

### ISSUE THREAD

**Issue by dav1dsm1th** [night/BetterTTV#680]
It would be nice to be able to automatically report a user for spamming as easily as it is to ban them from the profile card - atm it's too many steps, so i don't do it very often (chat is too busy to leave for that long).  If you could simplify the process maybe twitch would kill the accounts more quickly.

**Comment by night** [comment]
Duplicate of #639

**Comment by TheFallenArm** [comment]
Was searchung for this ; that would be really nice since it's a feature implemented by default in twitch and unavailable while BTTV is on :/

**Comment by EhsanKia** [comment]
@TheFallenArm could you show where/how this is implemented on default Twitch? I'm not seeing it on the default mod card. This is what I see:

![](http://i.imgur.com/2zZAGlG.png)
