### ISSUE TITLE
Custom font not working.

### ISSUE THREAD

**Issue by m0lDaViA** [night/betterttv#6810]
### Describe the bug

Custom fonst are not working.

### Steps to reproduce

1. Install bttv
2. Change the font to something else.
3. See the result.

### Expected behavior

Font family should change.

### Screenshots

![grafik](https://github.com/night/betterttv/assets/37399229/ce715192-56a0-4760-9a63-9a68063be82f)
![grafik](https://github.com/night/betterttv/assets/37399229/4c437f2a-a80f-485d-8e44-9904a1bd4796)

### Device information

PC
Windows 11
Firefox

**Comment by night** [comment]
I'm not able to reproduce any issues with custom fonts. Make sure the name you're entering reflects the font's realized name, not the family name. For example, some fonts may require you to specify "Font Name Standard"
