### ISSUE TITLE
Highlight Feedback doesn't play sound

### ISSUE THREAD

**Issue by varistenmurha** [night/betterttv#6821]
### Describe the bug

For a while now the "Highlight Feedback" function has not worked for me. It used to work, but sometime maybe a few weeks ago it stopped. I have tried several times to turn the setting off and on, refreshing the page in between. 

### Steps to reproduce

1. Open chat settings
2. Scroll down to Highlight Feedback
3. Turn setting on

### Expected behavior

Expect chat to play a sound when someone replies to my message

### Screenshots

![image](https://github.com/night/betterttv/assets/167918768/9ff6554d-8978-493d-a71b-24bf6b2f7805)

### Device information

Device: Asus laptop G551JM
OS: Windows 10
Browser: Mozilla Firefox
Version: 7.5.21

**Comment by night** [comment]
Thanks for the report. I'm not able to reproduce any issues with highlight feedback not working on Firefox. You can test this more easily by adding `*` as a highlight keyword and then joining a chat.
