### ISSUE TITLE
Unable to chat in Twitch, "You are sending messages too quickly" error message

### ISSUE THREAD

**Issue by tnxgam3rx** [night/betterttv#6832]
### Describe the bug

When trying to chat in Twitch, after a few messages sent the platform stops letting you send any message giving the error message "Message not sent - You are sending messages too quickly". After disabling the add-on, I can send messages as normal. Also made sure that there wasn't any auto-post settings turned on.

### Steps to reproduce

With the add-on enabled, join any chat and send messages at a usual rate.

### Expected behavior

Twitch chat should not time you out from sending less than 10 chats.

### Screenshots

![image](https://github.com/night/betterttv/assets/16908680/7d724d00-d674-45f2-a744-fd1a6dcd0594)

### Device information

PC using Firefox and BetterTTV version 7.5.21

**Comment by night** [comment]
This is not related to BetterTTV. As the message states, you were sending messages too quickly.

**Comment by tnxgam3rx** [comment]
I only sent 1 message every 3 minutes at most, not only that when I disabled it I was able to post without getting this message. It has nothing to do with how fast I was posting.
