### ISSUE TITLE
Unable to chat in Twitch, "You are sending messages too quickly" error message

### ISSUE THREAD

**Issue by tnxgam3rx** [night/betterttv#6833]
### Describe the bug

hen trying to chat in Twitch, after a few messages sent the platform stops letting you send any message giving the error message "Message not sent - You are sending messages too quickly". After disabling the add-on, I can send messages as normal. Also made sure that there wasn't any auto-post settings turned on.

### Steps to reproduce

With the add-on enabled, join any chat and send messages at a usual rate.

### Expected behavior

Twitch chat should not time you out from sending less than 10 chats in 3 hours.

### Screenshots

N/A

### Device information

PC using Firefox and BetterTTV version 7.5.21

### Additional information

Re-submitting this ticket as the original ticket did not resolve the issue.

**Comment by night** [comment]
We are not able to reproduce any issues with messages sending too quickly using the steps you provided. You might try disabling other browser extensions to see which is incompatible with BetterTTV. If problems persist, you may wish to reset your BetterTTV settings to see if it's a specific setting causing issues.
