### ISSUE TITLE
Chat Layout Bug

### ISSUE THREAD

**Issue by Letsbedeluxe** [night/betterttv#6834]
### Describe the bug

scrolling through chat or in a streamers info section either doesnt work or it scrolls only a little bit when using the left chat layout

### Steps to reproduce

1. Go to bttv settings 2. Click chat layout to left 3. Try to scroll chat

### Expected behavior

Webpage and chat expected to scroll

### Screenshots

![Screenshot 2024-05-27 235435](https://github.com/night/betterttv/assets/171001552/5fb62a5a-ffed-46da-ba33-204fae8d8a31)

### Device information

Google Chrome on Windows 10

**Comment by night** [comment]
Thanks for the report. Unfortunately I'm not able to reproduce any issues with page scrolling when using this feature. If problems persist, try disabling other browser extensions to see if one of them is conflicting with our features. If that doesn't help, posting a short video demonstrating the issue may help.
