### ISSUE TITLE
Recommended channels, offline channels, and (insert streamer name) viewers also watch channels don't go away

### ISSUE THREAD

**Issue by jlnhlfan** [night/betterttv#6837]
### Describe the bug

Here, although settings for recommended channels, offline channels, and (insert streamer name) viewers also watch channels are turned off, for whatever reason, they still show up. When I try to change the settings, it gaslights me into thinking the changes were acknowledged by showing more offline channels.

### Steps to reproduce

1. Go to twitch.tv
2. Go to a random channel you follow.
3. Turn off the settings for recommended channels, offline channels, and (insert streamer name) viewers also watch channels
4. Watch as the settings are ignored.

### Expected behavior

What's supposed to happen is that the recommended channels, offline channels, and (insert streamer name) viewers also watch channels are removed from the left sidebar.

### Screenshots

![Screenshot_May_30_2024_09_16_25_PM](https://github.com/night/betterttv/assets/31529087/4e09065c-480f-4c99-905a-2cfeddf5e7f5)

### Device information

Device: Desktop computer
Operating system: Windows 10 Home
Browser: Microsoft Edge
Version: Microsoft Edge version 125.0.2535.67

**Comment by OGNetheri** [comment]
+1

**Comment by jlnhlfan** [comment]
Updating Edge doesn't change anything.

**Comment by varuvaru68** [comment]
me too. On Latest Google chrome, and BetterTTV ver 7.6.0. Resetting the BetterTTV setting, dosen't change.

**Comment by jazminite** [comment]
+1 - Chrome Windows 11

**Comment by vogt2385** [comment]
Experiencing the same issues. Running latest Chrome (Stable branch), Windows 11

**Comment by night** [comment]
It appears the recently released changes did not appear to address this for native builds, but user script seems fine. Looking into this further.

**Comment by night** [comment]
> 7.6.1 version of the BTTV and Chrome version 125.0.6422.142

Chrome extension should be fixed in the pending release, 7.6.2. If you need a quickly fix, you can swap to the user script version (which is always latest).

**Comment by OGNetheri** [comment]
> > 7.6.1 version of the BTTV and Chrome version 125.0.6422.142
> 
> Chrome extension should be fixed in the pending release, 7.6.2. If you need a quicker fix, you can swap to the user script version (which is always latest).

Roger! I can wait, I'm just informing. 👍🏻
