### ISSUE TITLE
Emote Menu Button Disappears on Refresh or Load New Stream (Twitch)

### ISSUE THREAD

**Issue by houze968** [night/betterttv#6838]
### Describe the bug

This started a few days ago. Whenever I load a new stream or refresh one I'm already watching, the emote button disappears. I can get it to come back by going into the BTTV settings and toggle/untoggle the "Replace Twitch's native emote menu" button

### Steps to reproduce

1. Load new stream or refresh current one watching
2. The generic BTTV emote button is gone
3. Open BTTV settings
4. Scroll to Emote Menu, Replace Twitch's native emote menu is untoggled
5. Toggle Replace Twitch's emote menu
6. Untoggle Replace Twitch's emote menu, standard emote button comes back to chat until the next refresh

### Expected behavior

Replace Twitch's native emote menu untoggled used to show a separate smiley face BTTV emote menu button

### Screenshots

![image](https://github.com/night/betterttv/assets/171382281/7eff2520-a985-4704-b4c2-35aec5ca49bc)
![image](https://github.com/night/betterttv/assets/171382281/f738f425-4f22-4945-b12d-6536388f20e7)
![image](https://github.com/night/betterttv/assets/171382281/c1fc7e8b-7cf7-436b-bfa4-d3e2c0a0223e)

### Device information

Desktop: Windows 10, Edge Chromium v. 125.0.2535.67 (Official build) (64-bit)

### Additional information

Again, this just started within the last few days so I don't know if something with BTTV or something else triggered this behavior.

**Comment by tinyjesse** [comment]
the same is happening to me

**Comment by Nelicopterr** [comment]
I fixed mine by disabling the ffz extension and just having bttv :)

**Comment by houze968** [comment]
Why is a workaround grounds for closing a ticket? It doesn't solve the issue, therefor the bug still exists

**Comment by night** [comment]
> Why is a workaround grounds for closing a ticket? It doesn't solve the issue, the bug still exists, it simply sidesteps it

that's not why it was closed. it's closed because the issue has been addressed pending release.
