### ISSUE TITLE
Setting chat to left and hiding it is irreversible because the arrow is hidden

### ISSUE THREAD

**Issue by WillLBegin** [night/betterttv#6845]
### Describe the bug

Setting chat to left and hiding it is irreversible because the arrow is hidden
![image](https://github.com/night/betterttv/assets/168221966/74d17c8b-1add-4ec0-bc4a-96be8fe4457e)
If I click the arrow here, I can no longer click it to make chat appear again.
![image](https://github.com/night/betterttv/assets/168221966/9cdcb59e-2036-4d0d-b9c5-a57faab6ed3f)
[](url)

### Steps to reproduce

1. Set chat to left
2. Click the top arrow to toggle hide chat
3. Chat is hidden, no arrow to toggle chat again

### Expected behavior

Should have an arrow to show chat after hiding it when setting chat to left side of screen as seen here:
![image](https://github.com/night/betterttv/assets/168221966/048777b0-7011-4971-b7b8-c457610321a4)

### Screenshots

![image](https://github.com/night/betterttv/assets/168221966/74d17c8b-1add-4ec0-bc4a-96be8fe4457e)
![image](https://github.com/night/betterttv/assets/168221966/9cdcb59e-2036-4d0d-b9c5-a57faab6ed3f)
[](url)

### Device information

Newest version of chrome

### Additional information

Edit: added screenshot of expected behavior

**Comment by pwaser** [comment]
I'm having the same issue when using **Chrome**, this only started happening a few days ago. It doesn't happen on Firefox. I disabled all other extensions in Chrome and the issue persists. Please fix it.
