### ISSUE TITLE
Commands not working when 7tv extension is enabled

### ISSUE THREAD

**Issue by MichaelDavidGK** [night/betterttv#6857]
### Describe the bug

When 7tv extension is enabled bttv commands won't work

### Steps to reproduce

Try any command like /followed when 7tv extension is enabled and see that it doesn't work

### Expected behavior

command should display correctly in chat

### Screenshots

![image](https://github.com/night/betterttv/assets/39009683/8ae594ec-3349-49be-a05b-41a9a272965c)
![image](https://github.com/night/betterttv/assets/39009683/eb15dd8f-35ef-44d8-b0c8-1a57c03b6fe7)

### Device information

Windows 11
Firefox Developer Edition 127.0b9 (64-bit)

**Comment by night** [comment]
BetterTTV relies on Twitch's native chat. Since 7TV replaces Twitch chat with their own custom chat implementation, BetterTTV and other browser extensions will likely not be entirely compatible with it. You'll need to uninstall 7TV to use extensions like BetterTTV without conflict.
