### ISSUE TITLE
Emotes stopped appearing and split chat doesn't work in live chats

### ISSUE THREAD

**Issue by Latias4Ever** [night/betterttv#6858]
### Describe the bug

Ever since the update to 7.6.1, emotes have stopped appearing in any Twitch chat, and at the same time, split chat no longer seems to work on live chats, however it still appears in VODs. Pressing Tab to autocomplete names and emotes has also stopped working.

### Steps to reproduce

1. Go to any stream and open its chat.
2. Try to type or post any emote on BTTV.

### Expected behavior

BTTV emotes showing up, split chat working on live chats, autocomplete names/emotes with Tab.

### Screenshots

In a live chat: 
![image](https://github.com/night/betterttv/assets/24550309/7b66f592-bb74-47ca-9f4d-d127f5ecfe92)
In a VOD:
![image](https://github.com/night/betterttv/assets/24550309/786e8295-551c-4733-91d4-6b9129ca2ebd)

### Device information

- Device: PC
- OS: Windows 8.1
- Browser: Brave
- Version: 1.47.186

### Additional information

Due to support for 8.1 being discontinued, I cannot update my browser, so this could be possibly a browser version issue, but the fact split chat works in VODs and BTTV is able to load in general (and I can open its Settings) makes me question that.

**Comment by night** [comment]
Brave 1.47.186 is over a year old, and that could be affecting the extension. The extension should run on Chromium 89 or newer, but we haven't tested that version and it's always possible there was a bug fixed between then and now. If it's affecting solely the live chat, check if disabling 7TV helps. They replace the chat, and BetterTTV as well as other browser extensions rely on native Twitch chat.

Aside, you should really upgrade Windows. Your browser version over a year old, and it is not getting security updates. There have been 0-days released since then.

**Comment by Latias4Ever** [comment]
BTTV is my only Twitch extension, I'm not using 7tv since BTTV has the 7tv emotes setting and that's all I need. After looking at the console, I cannot find any particular error regarding BTTV. In fact, when popping out the chat, I get no errors at all, and the only messages I find in the console are these:

![image](https://github.com/night/betterttv/assets/24550309/c96cfd44-1a77-4b2a-9128-eee7ca8c7d0e)

And yes, I know I should upgrade my Windows, I've been planning to once I build a new PC.

**Comment by night** [comment]
Make sure you're on version 7.6.2 then, since there were known issues with 7.6.1 and 7.6.0

**Comment by Latias4Ever** [comment]
Yes, I'm using 7.6.2.

![image](https://github.com/night/betterttv/assets/24550309/a511710a-7802-41cb-b124-2bb7d56c6560)

**Comment by night** [comment]
I just verified on Brave 1.66.118 and it's working normally on 7.6.2. The only other idea is to make sure you're logged into Twitch, as sometimes being logged out can break certain paths in the runtime.

**Comment by Latias4Ever** [comment]
I am logged into Twitch, however just to check if it's a cookies issue, I enabled BTTV in Incognito and checked to see what would happen with no cookies at all, and the issue persists. Could it be an issue with the Permissions-Policy header that I showed earlier?

Alternatively it could be an issue with Brave's internal GreaseLion script for Twitch, though I don't see how that would cause a problem since it only affects Twitch and not BTTV.

**Comment by night** [comment]
And the emote menu is enabled and doesn't show up on live chats either? What happens if you post an emote from the emote menu?

**Comment by Latias4Ever** [comment]
Emote menu shows up, however I only see Global emotes, no channel-specific emotes, and clicking on an emote doesn't add it to the chat box. Additionally posting an emote only shows the emote's name, and it doesn't appear in the possible emotes list when I start typing it with : .

**Comment by night** [comment]
Got it. Well it sounds like it isn't able to mount into the chat properly. However, since you're using a browser that is > 1yr old and we can't reproduce on the latest version of Brave it sounds like it is a browser-specific issue.

**Comment by Latias4Ever** [comment]
That sounds about right, I just don't understand why split chat works with VoDs but not live chat, and emotes don't work on either. I just don't understand why it fully worked even up to 7.6.0, but suddenly it stopped working with 7.6.1.

Unfortunately I can't exactly swap to FireFox since it'd require migrating too much to it, plus I prefer Brave as a browser in general. Yeah I understand that these issues stem from me being unable to update it, but as I said I'm already planning on getting a new PC with an updated OS.

**Comment by night** [comment]
> I just don't understand why it fully worked even up to 7.6.0, but suddenly it stopped working with 7.6.1.

The release of 7.6.0 swapped from manifest v2 to manifest v3 for the native Chrome extension. If I had to make a guess, the version of Chromium your version of Brave is using is too old to support MAIN world injection. That would explain why settings load and some tweaks that don't rely on mounting into Twitch work.

As an alternative, you could try to use the UserScript version of BetterTTV instead. To do that, you'd need TamperMonkey and developer mode enabled in Chrome. Then, you can download/install from the BetterTTV website by changing the browser to Other.

**Comment by Latias4Ever** [comment]
7.6.0 worked, so I don't think Manifest V3 was the issue, it was only with 7.6.1 that it stopped.

Still, the TamperMonkey method worked instantly, I have split chat and emotes working once again! Thank you, and apologies for spending so much of your time on an issue that's largely my fault for not being able to update Brave.
