### ISSUE TITLE
Recent Mentions List

### ISSUE THREAD

**Issue by IndieManuel** [night/BetterTTV#686]
It would be useful to have a menu displaying the recent mentions of your username in chat.

**Comment by night** [comment]
Please do not make combine feature requests into a single request. This does not work well for us.

> Chat history

The feature you seek is actually called a list of mentions. I will change your feature request to this.

> Highlight color options

Duplicate of #237

**Comment by night** [comment]
Duplicate of #610, not sure how I missed this before.
