### ISSUE TITLE
Search function does not work correctly on keywords

### ISSUE THREAD

**Issue by kozaka-tv** [night/betterttv#6874]
### Describe the bug

I have a Metallica and a PogUHetfield emoji.

- Metallica has the keyword: hetfield
- PogUHetfield has the keyword: metallica

If I search on Metallica, only the Metallica Emoji will be found. But If I search on Hetfield, both Metallica and PogUHetfield will be found.

If I search on Hammett, then again both are visible. Maybe only the first keyword is checked?

### Steps to reproduce

1. go to Browse shared emotes
2. enter Hetfield in the search --> Both Metallica and PogUHetfield is shown
3. enter metallica:
--> Only Metallica is shown

### Expected behavior

If I search for Metallica, also all the emotes with the keyword metallica should be shown

### Screenshots

PogUHetfield:
![image](https://github.com/night/betterttv/assets/4964462/705afb8e-ba72-4f39-b870-6c6dd0e48c04)

Metallica:
![image](https://github.com/night/betterttv/assets/4964462/fe1ca3ef-195c-408c-a033-bea85b721424)

Search Hetfield:
![image](https://github.com/night/betterttv/assets/4964462/6bcb663c-acd6-406f-b4a2-5940ca7e439b)

Search Metallica
![image](https://github.com/night/betterttv/assets/4964462/f6d7f4e8-6ea3-4606-89f2-4db2685e0629)

Search Hammett
![image](https://github.com/night/betterttv/assets/4964462/12a01792-d5aa-46a9-bc81-8d8a64c581be)

### Device information

PC, Chrome

### BetterTTV Version

idk not visible on your web page

### Additional information

How should I know the version?

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Thanks for the report. This issue should be fixed.

**Comment by kozaka-tv** [comment]
Thank you for the fix! Now it working good!
