### ISSUE TITLE
Double Sound Playback with Highlight Feedback

### ISSUE THREAD

**Issue by DAndP3** [night/betterttv#6875]
### Describe the bug

This bug is an extension of the previous issue I reported (Double pinning the highlighted message #6863). Now, when 'Pinned Highlights' is enabled and 'Highlight Keywords' is set to your own username with the type 'Username', messages you send to the chat are pinned once. However, even after fixing the bug, when you have 'Highlight Feedback' toggle on, the message pinning sound still plays twice. (1 message - 2 sound)

### Steps to reproduce

1. Go to 'BetterTTV Settings' > 'Chat Settings'.
2. Configure the following settings:
- Highlight Keywords
  - Type: **Username**
  - Keyword: **[Your username]**
- Highlight Feedback 
  - Play a sound for messages directed at you: **Enable**
- Pinned Highlights (Optional)
  - Pin your highlighted messages above chat: **Enable**
3. Send messages to the chat, and the sound will play once.
4. To observe the issue:
- **Send another message**
- **Wait for another user to send a message**
- **Open the 'chat settings'**
- **Sometimes, the sound will play twice without any additional actions.**

### Expected behavior

When you send a message, the sound should play only once. (1 message - 1 sound)

### Screenshots

![1](https://github.com/night/betterttv/assets/171921497/a41c3c58-c415-4967-bc55-531287a17f4d)

### **Watch with sound:**

https://github.com/night/betterttv/assets/171921497/833f384f-fbe7-4129-9fd1-5bd9eaa29053

### Device information

- OS: Windows 10 Pro x64 (21H2, build 19044)
- Browser: Chrome, Version 125.0.6422.142 (Official Build) (64-bit)

### BetterTTV Version

7.6.4

### Additional information

Previously, I suspected that the sound played twice for the same reason as the message being pinned twice, but it appears that the issue is related to something else.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
This is a good catch! Totally missed this detail when fixing that
