### ISSUE TITLE
BetterTTV doesn't work as intended, and I'm not sure why.

### ISSUE THREAD

**Issue by UnholySheep** [night/betterttv#6877]
### Describe the bug

I'm sorry I can give you a consistent way of showing this, it's been a while since BetterTTV worked like it should. Most of the options don't seem to do anything, sometimes. Sometimes they work, sometimes they don't. For example, I have turned off "show bits in chat", which in some channels it works, in some others it doesn't. Sometimes when I'm switching between streams from the left side pannel, BetterTTV disappears completely from chat-settings, it's like not having it installed.

### Steps to reproduce

I don't know, it's random.

### Expected behavior

To behave in every stream the same way, with the same settings applied.

### Screenshots

https://streamable.com/6blbv1

### Device information

W10 IoT LTSC
Firefox 126.0.1 (64-bit)

### BetterTTV Version

7.6.3

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
You're using an outdated version of BetterTTV. You stated you have version 7.6.3 but 7.6.4 is the latest.
