### ISSUE TITLE
BetterTTV emote icon has disappeared

### ISSUE THREAD

**Issue by MeatyPopsicles** [night/BetterTTV#688]
In both the most recent updated Firefox and Chrome the BetterTTV Emotes button no longer appears. I have uninstalled and reinstalled the extension and it just doesn't show up even though I have it set to On and never changed the setting when it disappeared (see image)

![capture](https://cloud.githubusercontent.com/assets/14116573/9671400/49de9fc4-5258-11e5-998c-88aab6a94532.JPG)

**Comment by night** [comment]
I cannot reproduce this. You most likely do not have the emote menu setting toggled.....

**Comment by MeatyPopsicles** [comment]
It's toggled..it's right there in the image.

**Comment by cletusc** [comment]
The setting for this is "Emote Menu" which isn't pictured in the image above.

**Comment by night** [comment]
The setting labeled "Emote Menu" is not in the image...
