### ISSUE TITLE
Blocking initialization of "Chat settings" menu

### ISSUE THREAD

**Issue by InsaneDoggo** [night/betterttv#6883]
### Describe the bug

Settings menu opens too long

### Steps to reproduce

1. Click to chat settings
2. Experience delay before it opens

### Expected behavior

It should be async request so it opens chat instantly but with minimal functionality/placeholders, while rest of the stuff is loading.

### Screenshots

![image](https://github.com/night/betterttv/assets/7687412/8d2bdd44-bc55-49d9-9e0e-2495c4bef617)

### Device information

Chrome Version 125.0.6422.176 (Official Build) (64-bit)

### BetterTTV Version

7.6.4

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Because BetterTTV wraps window functions for error logging, it isn't clear that the function you've screenshotted is relevant. You'll need to screenshot the function source to verify it isn't a wrapper.

More likely, however, is that you have other browser extensions for Twitch installed that conflict. Try disabling all extensions but BetterTTV and see if the issues persist. You can then re-enable one by one to see which is conflicting.

**Comment by InsaneDoggo** [comment]
I have tested it by toggle off/on btttv extension it has huge impact

**Comment by InsaneDoggo** [comment]
Without performance profiler delay is about 1-2 sec which is still big.

**Comment by night** [comment]
it may be fixed by 088113b42fb1809549b1963e47879f0d38936319, but I cannot reproduce any issues myself

**Comment by night** [comment]
If you can, you can try out the userscript release of 7.6.5 to see if it addresses this issue for you. Otherwise, you'll need to wait for version 7.6.5 to release on the extension stores to test this.

**Comment by InsaneDoggo** [comment]
I've checked sources, it's a lot of query selectors.

![image](https://github.com/night/betterttv/assets/7687412/3b54d53d-67ad-4890-80d7-dc20473b4e70)
![image](https://github.com/night/betterttv/assets/7687412/9db8dddb-9129-43fa-8182-1669215010e7)
![image](https://github.com/night/betterttv/assets/7687412/47ac7ac1-3a6d-4bab-9056-8fa87390221d)

**Comment by InsaneDoggo** [comment]
P.S. waiting for 7.6.5 release to check possible fix.

**Comment by InsaneDoggo** [comment]
Looks fine in 7.6.5. Great job
