### ISSUE TITLE
"highlighted test" ->suggestion

### ISSUE THREAD

**Issue by rossy1005** [night/BetterTTV#689]
Just thought of this while spending quite some time in quite spammed text... It would be awesome to have a way to find your own msgs easier... as in having them highlighted when someone uses @[your name] in their text msgs... The idea behind this came to me because I was replying to multiple people at once and I forgot if I've replied to the message that appeared few lines above or not... and due to spammers it was hard to notice where my message was. .. Would be quite helping I'd say... maybe on same system as the @[your name] work just different colour.. instead of bright red to idk.. yellow/blue/green? something that's easy noticeable... or making your own name glowing for urself?

**Comment by night** [comment]
BetterTTV already stores your outgoing messages. If you need to know what you previously said, you can press the up key (and down) when your cursor is in the chat box.
