### ISSUE TITLE
Already translated Italian strings missing in extension

### ISSUE THREAD

**Issue by Zabriskije** [night/betterttv#6893]
### Describe the bug

I've already reported this on [Discord on 28/11/2023](https://discord.com/channels/229471495087194112/1065446695300780123/1179187928505778186), but some missing translations in the Twitch extension have already been translated and approved. Below is the list of all the missing ones.

#### Chat Settings
**Anon Chat**
- Blacklist channels that enable Anon Chat
**Emotes**
- Emote modifiers allow you to transform emotes in realtime.
**Hype Chat**
- Show hype chat messages in the chat window
**Emote Menu**
- Replace Twitch's native emote menu.

#### Directory Settings
**Sidebar**
- Recently Watched Channels
  - Show recently watched channels in the sidebar
- Recommended Channels
- Similar Channels
  - Show similar channels in the sidebar

### Steps to reproduce

- Set your language to Italian
- Open BTTV on Twitch

### Expected behavior

Approved translations should be on the Twitch extension when a new release is published.

### Screenshots

![bttv](https://github.com/night/betterttv/assets/101254295/7d9f4da7-711d-4252-919e-3a4382f67782)

### Device information

This has been going on for months, but right now:

- Sequoia 15.0 (24A5264n)
- Safari 18.0 (20619.1.15.11.1)

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
translation strings get manually updated. i've pulled in the latest via 6e28c95b9cf8d499deead792ee2a715a578319e9
