### ISSUE TITLE
Standard Emote Menu appears with BTTV Emote Menu

### ISSUE THREAD

**Issue by DAndP3** [night/betterttv#6894]
### Describe the bug

When sending messages too frequently, triggering the message:

> **Message Not Sent**
> Your message is identical to the one you sent within the last 30 seconds.

the standard Emote Menu appears alongside the BTTV Emote Menu.

### Steps to reproduce

1. Go to 'BetterTTV Settings' > 'Chat Settings'.
2. Configure the following settings:
- Emote Menu:
  - Enable a more advanced emote menu for chat: **Enable**
  - Replace Twitch's native emote menu: **Enable**
3. Send a message.
4. Send the same message again to trigger:

> **Message Not Sent**
> Your message is identical to the one you sent within the last 30 seconds.

5. When the message appears, the standard Emote Menu will also appear to the left of the BTTV Emote Menu.

### Expected behavior

The standard Emote Menu should not appear when the BTTV Emote Menu is enabled and set to replace it.

### Screenshots

![1](https://github.com/night/betterttv/assets/171921497/7bb910eb-7115-4ec0-b0fa-fba54363d64e)

https://github.com/night/betterttv/assets/171921497/afeb0af0-163f-4030-ac34-65ee7315cbd1

### Device information

- OS: Windows 10 Pro x64 (21H2, build 19044)
- Browser: Chrome, Version 126.0.6478.62 (Official Build) (64-bit)

### BetterTTV Version

7.6.5

### Additional information

This bug is very similar to the previously fixed issue with the Emote Menu: #6658.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
fixed via 2c10a4c60ca56dbf94a995ad85700c723f08f306
