### ISSUE TITLE
Highlight Keywords not working properly

### ISSUE THREAD

**Issue by DAndP3** [night/betterttv#6895]
### Describe the bug

When 'Highlight Keywords' is set to type '**Message'** or **'Badge'**, messages **you** send to the chat are not pinned.

### Steps to reproduce

1. Go to 'BetterTTV Settings' > 'Chat Settings'.
2. Configure the following settings:
- Highlight Keywords:
  - Type: **Message** or **Badge**
  - Keyword: **[Any]**
- Pinned Highlights (Optional):
  - Pin your highlighted messages above chat: **Enable**
- Highlight Feedback (Optional):
  - Play a sound for messages directed at you: **Enable**
3. Send messages to the chat, and they will not be pinned.

### Expected behavior

The messages you send should be pinned.

### Screenshots

For Keyword type **'Message'**:
![1](https://github.com/night/betterttv/assets/171921497/af27f690-cf48-46a3-80a4-c9a6fded56db)
![2](https://github.com/night/betterttv/assets/171921497/c6ddf389-1a1d-4575-8646-e4168bf2c43e)

https://github.com/night/betterttv/assets/171921497/4d3d51ca-30d9-4825-b356-379668f966f1

For Keyword type **'Badge'**:
![4](https://github.com/night/betterttv/assets/171921497/1a3041de-4fbd-4497-8fad-e46066daa008)
![5](https://github.com/night/betterttv/assets/171921497/c1a340c2-e831-4ef4-9105-11563c5eed0c)

https://github.com/night/betterttv/assets/171921497/5e26e026-e7e9-4c01-bee6-19fb6456d34f

### Device information

- OS: Windows 10 Pro x64 (21H2, build 19044)
- Browser: Chrome, Version 126.0.6478.62 (Official Build) (64-bit)

### BetterTTV Version

7.6.5

### Additional information

I think this bug might have appeared in versions 7.6.4 or 7.6.5 as a result of fixing other bugs related to Message Pinning and Keywords (#6863 and #6875).

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
This is working as intended. Only user keywords can highlight the current user. This is documented in the source code [here](https://github.com/night/betterttv/blob/master/src/modules/chat_highlight_blacklist_keywords/index.js#L191)

**Comment by DAndP3** [comment]
Thank you for the clarification. I understand the intended functionality now.
