### ISSUE TITLE
Repeated messages only pinned once

### ISSUE THREAD

**Issue by DAndP3** [night/betterttv#6896]
### Describe the bug

If a pinned message has the same [time], [username] and [message] as one of the previous messages, it won't be pinned again. For example, sending "1" at 03:01:30 will be pinned as 

> 03:01 [Username] 1

Sending "1" again at 03:01:45 won't be pinned because the [time] (only hours and minutes matter), [username] and [message] are the same.
However, sending "1" at 03:02:15 will be pinned as

> 03:02 [Username] 1

since the [time] is different.

### Steps to reproduce

1. Go to 'BetterTTV Settings' > 'Chat Settings'.
2. Configure the following settings:
- Highlight Keywords:
  - Type: **Username**
  - Keyword: **[Your username]**
- Pinned Highlights:
  - Pin your highlighted messages above chat: **Enable**
- Highlight Feedback (Optional):
  - Play a sound for messages directed at you: **Enable**
3. Send a message (e.g., "1") at a specific time (e.g., 03:01:30). The message pins as expected.
4. Send the same message again within the same minute (e.g., 03:01:45). It does not pin.
5. Send the same message in the next minute (e.g., 03:02:15). The message pins.

### Expected behavior

Every message should be pinned.

### Screenshots

![1](https://github.com/night/betterttv/assets/171921497/d284fcba-fe7f-4ea8-ac92-346837aba6a9)

https://github.com/night/betterttv/assets/171921497/57aa6ae5-2dcf-4887-986d-8b56a42eb107

### Device information

- OS: Windows 10 Pro x64 (21H2, build 19044)
- Browser: Chrome, Version 126.0.6478.62 (Official Build) (64-bit)

### BetterTTV Version

7.6.5

### Additional information

1.This bug was also present in version 7.6.4.
2. This issue likely also affects keywords of types "Message" and "Badge," but I can't check this due to bug #6895.
3. This occurs not only with your messages but also with messages from other users.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
This is working as intended to prevent spammy pinned messages. The goal of pinning messages is to retain a message when you step away. Multiple messages in an ongoing conversation would still be highlighted, but not pinned.

**Comment by DAndP3** [comment]
Thank you for the clarification. I understand the intended functionality now.
