### ISSUE TITLE
Bug: Clicking a user's name in chat during a live stream crashes tab in Chrome

### ISSUE THREAD

**Issue by godzfire** [night/betterttv#6898]
### Describe the bug

In Chrome, during a livestream, if you click on a user's name, it will crash the tab. 
<img width="347" alt="image" src="https://github.com/night/betterttv/assets/2067820/3064f270-706c-4f68-82a5-3e0b8341996f">

If you disable the plugin and then try the same thing, it will work, confirming it's BTTV.

### Steps to reproduce

See above.

### Expected behavior

Clicking the username will open up their profile page.

### Screenshots

<img width="347" alt="image" src="https://github.com/night/betterttv/assets/2067820/f2d4d641-5d00-4175-950f-6828d9a42f68">

### Device information

- Mac Mini 2018
- MacOS Monetary 12.7.4 (21H1123)
- Chrome 127.0.6510.0
- BetterTV 7.6.5

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
I can't reproduce the crash. In my experience though, this is more likely a native Chrome bug. Browser tabs generally cannot cause the page to crash like this unless it's an OOM, which this doesn't sound like it is. Further, you're using Chrome 127, which is a beta version. Beta versions of Chrome can have crash issues like this. Process crashes get reported upstream and it will likely be fixed before it goes to stable.

**Comment by godzfire** [comment]
I use Chrome Canary as my regular browser for Twitch and it's worked fine for the longest time. In the past month it felt like this problem was happening. I held off just to make sure it wasn't just a few days thing, and finally posted the bug today.

I checked today and updated to the current version and of course it's now not crashing. Sorry to bother, should have checked one last time before posting.
