### ISSUE TITLE
Anon Chat

### ISSUE THREAD

**Issue by night** [night/BetterTTV#69]
The ability to join a channel without appearing in chat.

**Comment by vendethiel** [comment]
I'm sorry? This looks pretty impossible from our side, unless we get "dirty" and abuse subdomains (which I think don't even exist) to hide loggedin-ness?!

**Comment by OurFlagIsMined** [comment]
Is there any way to change what login credentials it uses to connect to TMI? The default client just uses a username of `justinfan000000` (where 000000 is any 6 random numbers) and a password of `blah` (though any works) for anonymous logins.
