### ISSUE TITLE
UNABLE to use custom emotes

### ISSUE THREAD

**Issue by IOwnSkittles** [night/BetterTTV#690]
Hi there, I've gone through all the steps in creating my emote, It says it's passed the review and is live but no matter how many times I enter the emote code I never get to see my emotes? can you please help

**Comment by night** [comment]
You need to refresh you chat after an emote is approved. In addition, BetterTTV Emotes and BetterTTV GIF Emotes must be toggled on in the BetterTTV settings.

**Comment by IOwnSkittles** [comment]
To refresh my chat is just to refresh the page or is there a setting to refresh it.

**Comment by night** [comment]
Yes, you just refresh the page.
