### ISSUE TITLE
Shared emote API says "invalid offset"

### ISSUE THREAD

**Issue by Zeilar** [night/betterttv#6901]
### Describe the bug

The following URL produces an "invalid offset" error response:
[https://api.betterttv.net/3/emotes/shared/top?offset=15&limit=50](https://api.betterttv.net/3/emotes/shared/top?offset=15&limit=50)
Seemingly no matter what I use for the offset query parameter.

### Steps to reproduce

[https://api.betterttv.net/3/emotes/shared/top?offset=15&limit=50](https://api.betterttv.net/3/emotes/shared/top?offset=15&limit=50)

### Expected behavior

This worked in the past, I guess the API has changed since then? I found no mention of an offset in the documentation or source code.

### Screenshots

[https://api.betterttv.net/3/emotes/shared/top?offset=15&limit=50](https://api.betterttv.net/3/emotes/shared/top?offset=15&limit=50)

### Device information

Window 11
Google Chrome - Version 125.0.6422.142 (Official Build) (64-bit)

### BetterTTV Version

API v3

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
This is an internal API that we don't document or support for external use. YMMV if you try to use undocumented APIs.
