### ISSUE TITLE
Low viewer games not loading in directory listing - Google Chrome

### ISSUE THREAD

**Issue by unph4zed** [night/BetterTTV#691]
When scrolling down in the games directory (http://www.twitch.tv/directory) lower viewer games fail to load. The issue is not present when I disable BTTV. 
Windows 8.1 
Chrome Version 45.0.2454.85 m (Latest)
![night](https://cloud.githubusercontent.com/assets/14168817/9722877/8687ff20-5572-11e5-85f6-54a0b2448980.jpg)

**Comment by night** [comment]
This just looks like the API failed to load. I can't reproduce any issues on my end.
