### ISSUE TITLE
Sometimes Drops Autoclaim no longer working

### ISSUE THREAD

**Issue by RoonMoonlight** [night/betterttv#6912]
### Describe the bug

As of June 26 2024, the Twitch Drops Autoclaim feature does not work sometimes.

### Steps to reproduce

1. Ensure that Auto Claim Drops are enabled
2. Watch any stream with drops enabled (For me I tried XDefiant)
3. When you go inventory Claim Now button appears instead of being claimed automatically

### Expected behavior

It should be able to claim drops automatically without issues.

### Screenshots

I cannot provide screenshot because it happens sometimes and it is not the best way for explanation

### Device information

Device: Desktop
OS: Debian/Peppermint OS 12 Bookworm
Browser: Firefox
Version: 127.0.2

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
I'm not able to reproduce any issues with drop claiming. Are you sure you met the requirements to claim them at time of earning them?
