### ISSUE TITLE
Mute Invisible Player issue

### ISSUE THREAD

**Issue by DrDerrp** [night/betterttv#6913]
### Describe the bug

When there is an ad playing, audio starts to come through again and then continues after the ad is over. You have to go to another tab after the ad is over to mute it again.

### Steps to reproduce

Step 1. Watch a stream
Step 2. Watch another or open another tab
Step 3. Wait for ad to play on a tab that's not opened. 
Step 4. Go to tab with audio
Step 5. Go to another opened tab.
--Audio still playing--
Step 6. Wait for ad to stop
Step 7. Go to another tab.

### Expected behavior

Audio should not play through at all when the tab isn't opened.

### Screenshots

N/A

### Device information

PC
Windows 10
Chrome Browser and Brave (Latest version)

### BetterTTV Version

Version 7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
I wasn't able to reproduce this issue when testing locally. Do you by chance have a video showing the issue so we can try to reproduce it following its steps?

**Comment by DrDerrp** [comment]
It appears to have fixed itself. I think it may have had something to do with the audio compressor. When an ad would play, it would have audio through the regular volume bar, but stream would come through on the compressor audio bar.
