### ISSUE TITLE
Highlights aren't working at all, and haven't for a long time

### ISSUE THREAD

**Issue by Hexerin** [night/betterttv#6920]
### Describe the bug

Highlights aren't working at all, and haven't for a long time.

### Steps to reproduce

Setup your highlights, then have someone attempt to utilize them. This applies to both custom keywords, replies, and mentions.

### Expected behavior

Any custom keyword, reply, and mention should be highlighted.

### Screenshots

None of these settings work.

![](https://i.gyazo.com/02f94c49d145c21fbdf85099f8a8bede.png)

### Device information

Windows 10 / Firefox (many versions, ongoing issue)

### BetterTTV Version

Version 7.6.5 (possibly older versions as well)

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Highlights are working as normally. If you're not seeing them, you likely have another browser extension installed that conflicts with ours. Try disabling it!
