### ISSUE TITLE
Apparent issue with the points & bits counter

### ISSUE THREAD

**Issue by TsukiZero** [night/betterttv#6921]
### Describe the bug

It might be conflict with FFZ or not, but sometimes the points & bits counter under the chat message "disappears" until refresh. That is to say it won't tell if bonus points have been claimed, how many points you have, and you have to "guess" where the button is (right under the badge button). Its occurrence has no discernible pattern so it can only happen by waiting.

The reason I suspect it might be tied with BTTV is due to me disabling the extension appears to have fixed it.

### Steps to reproduce

Impossible to reproduce consistently due to the nature of the bug.

### Expected behavior

Simple: the button should never vanish.

### Screenshots

Couldn't reproduce the issue due to having disabled the extension to avoid further nuisance, but replicated the effect perceived when it happens by using the Web Tools:
![image](https://github.com/night/betterttv/assets/78157224/f79f263d-f778-497e-874a-1344b823cd8d)

### Device information

PC
Windows 10 64-bit
Firefox 127.0.2 (64-bit)

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
I'm not able to reproduce this issue. Do you have working steps to reproduce this? Does this only happen when hiding bits in the BetterTTV settings?

**Comment by TsukiZero** [comment]
It is very random, it can go a whole day without happening, at times it happens an hour into a channel. Like: Yesterday I didn't see it happen at all, despite having re-added BTTV, and having been on at least 3 channels at once all the time and refreshing them a few times.
