### ISSUE TITLE
Long emote names cut off

### ISSUE THREAD

**Issue by exatedlord** [night/betterttv#6922]
### Describe the bug

When an emote name is too long, the name doesn't seem to wrap or overflow the text.

### Steps to reproduce

Send an emote with a very long name to chat and hover over to see emote details.

### Expected behavior

The stream itself lays over the emote information on hover over, but does not include the emote name.

### Screenshots

![bttv name cutoff](https://github.com/night/betterttv/assets/52119093/9683db97-48aa-429a-b550-a1636de74ec2)

### Device information

Win 11

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
duplicate of #5939
