### ISSUE TITLE
looks like auto theatre mode breaks site

### ISSUE THREAD

**Issue by Makezu90** [night/betterttv#6929]
### Describe the bug

I noticed when i have turned on Auto theatre mode it breaks site when leave from that. it brings huge empty space to under live stream before these stream title and streamer name etc. I noticed this started yesterday randomly..

### Steps to reproduce

Turn on auto theatre mode

then try go to watch some streamer, yes it works normally but when you leave from theatre mode you see that huge empty space when scroll down and check stream title or game or these streamer info things.

### Expected behavior

looks normal and there is no any huge empty space.

### Screenshots

![HFytiBVR9x](https://github.com/user-attachments/assets/8336ccc0-6527-4193-ba6c-3dd33a6a2d98)

### Device information

Windows 11 Pro, 22631.3880

Firefox 128.0

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by Makezu90** [comment]
it works again normally.. 🤔

**Comment by Makezu90** [comment]
it works again normally.. 🤔

**Comment by Makezu90** [comment]
Issue came back.. need help. Tried reinstall, not helped.

**Comment by night** [comment]
This is a native Twitch bug with theater mode. If you press Alt+t when the page loads before the stream info section loads (with BetterTTV disabled) you can reproduce it.

**Comment by Makezu90** [comment]
oh i see now..  thank you for letting me know. 👍

> This is a native Twitch bug with theater mode. If you press Alt+t when the page loads before the stream info section loads (with BetterTTV disabled) you can reproduce it.
