### ISSUE TITLE
/unban command not working with extension

### ISSUE THREAD

**Issue by Oukar** [night/betterttv#6933]
### Describe the bug

While the BTTV extension is active on Chrome, the /unban command does not seem to function. Bans work, unbans do not. This was tested with and without the extension active (and only that one was altered) and it was found as the problem. 

### Steps to reproduce

1) Use Chrome
2) (Optional) Ban user from chat
3) Attempt to "/unban <Username>"

### Expected behavior

Expected behavior: The user will be unbanned.

### Screenshots

![image](https://github.com/user-attachments/assets/c0d1390a-93de-49ad-9fdc-5f84c8d9196e)
Nothing shows in the chat when this is used on a valid or invalid user.

### Device information

Computer
Windows 11
Chrome
Version 126.0.6478.127 (Official Build) (64-bit)

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Thanks for the report. This will be fixed in the next release.
