### ISSUE TITLE
Cannot Rename User. Username reverts to original with space at end.

### ISSUE THREAD

**Issue by Kayla-** [night/BetterTTV#694]
Leave blank does not reset.
Changing the name changes all previous instances of their name but any new posts will be under the bug name with the space. No way to change this persons name or revert it to the original.

Before w/ Bug
![1](https://cloud.githubusercontent.com/assets/7082265/9750281/f43caf62-566b-11e5-92c4-f37a529f66e4.png)

After second instance of bug
![2](https://cloud.githubusercontent.com/assets/7082265/9750285/00231820-566c-11e5-930e-f128b3d35d87.png)

**Comment by night** [comment]
Try without FrankerFaceZ, since I cannot reproduce this.

**Comment by Kayla-** [comment]
Waiting for the user to return so I can test without FFZ. Will comment back once I have data. In the meantime is there any config I can send you for inspection? Perhaps there is a fix. This user is the only user it has happened with so far; and one person before changed their name to mine and they couldnt undo it so they had to reinstall BTTV.

**Comment by night** [comment]
If the issue continues, then it may be because of the space in their display name.

**Comment by Kayla-** [comment]
The weird thing is BTTV truncates all trailing spaces so I have no idea how that space got there.

**Comment by Kayla-** [comment]
Issue continues with FrankerFaceZ disabled. Ive tried to replicate getting a space in someones username through renaming but I cant replicate it. This user appears to be the only one affected. Although mildly annoying, It doesnt affect performance. It would be cool to see if this could be debugged though. Id be willing to send you my configs if there were any.

**Comment by night** [comment]
This should be fixed. Thanks for reporting it.
