### ISSUE TITLE
Anon Chat

### ISSUE THREAD

**Issue by rene0580** [night/betterttv#6950]
### Describe the bug

The removal from Twitch user list in chat worked fine the first couple of days, but i now am looged off from chat and then instantly logged back into chat. A few moments later i am in user list in chat. This happens on every channel and in 2 browsers (firefox and chrome)

### Steps to reproduce

I activated "anon chat" while i used Twitch

### Expected behavior

It would be nice to have a way for anon chat to work again. I have already tried a new installation

### Screenshots

I cannot do that. I cannot show my username and all the other usernames.

### Device information

Windows 11 on Pc

### BetterTTV Version

7.6.5

### Additional information

If you want me to provide any, please let me know.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Try disabling other browser extensions. BetterTTV only has the capability to log out out of native Twitch chat. Other extensions may replace native chat, which we do not support.
