### ISSUE TITLE
Manual chat refresh

### ISSUE THREAD

**Issue by chizdippler** [night/BetterTTV#696]
For users on wifi, sometimes chat doesn't reconnect properly after losing and regaining internet connection. If it is at all possible, a manual chat refresh button or setting would be very useful.

**Comment by night** [comment]
I've never witnessed this myself. If you can reproduce this, make a video and send it to Twitch. Reconnecting manually should never be necessary, and I'm hesitant to add a feature to "fix" a bug. The bug itself should be addressed.
