### ISSUE TITLE
Emote not appearing on channel's public emote list

### ISSUE THREAD

**Issue by thekillernacho** [night/betterttv#6975]
### Describe the bug

hey there... there's an emote (SpeedL by naro) that works on my channel FFTBattleground & appears in my dashboard that a viewer pointed out doesn't actually appear in the channel's emote list.
https://betterttv.com/users/5e4c2434e383e37d5d9dac4e
https://betterttv.com/emotes/5e6216966d485d372b28986a

Trying to remove and readd the emote didn't seem to help - obviously it's not a huge deal, but any idea what's going on?

### Steps to reproduce

1. add SpeedL to a channel
2. open channel's emote list webpage
3. see it is not there

### Expected behavior

the emote appearing on the channel emote list

### Screenshots

![image](https://github.com/user-attachments/assets/7f7d9b77-6bbc-4aac-a459-43f950370376)
![image](https://github.com/user-attachments/assets/e4cffacf-7675-484a-9ba0-4f4671b5316e)

### Device information

Windows, Chrome, Firefox

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Thanks for the report. We've shipped a fix for this and the emote appears normally now.
