### ISSUE TITLE
Anon chat

### ISSUE THREAD

**Issue by AngryCure** [night/betterttv#6986]
### Describe the bug

I have the "Anon chat" option activated, but I still see my name in the viewers list. 

### Steps to reproduce

Go to a stream, activate the anon chat option, check the viewers list. 

### Expected behavior

My name shouldn't appear. 

### Screenshots

![fc](https://github.com/user-attachments/assets/df9cf27a-e511-49f5-a4be-2c0f40d34b0a)
![fk2](https://github.com/user-attachments/assets/b8e53f3c-a769-4691-ba08-c8ec0ed88147)

### Device information

Browser (Google Chrome) 

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
I am not able to reproduce any issues with Anon Chat locally. Make sure you're not using other Twitch browser extensions, as they can replace the chat entirely and that will break features like this.
