### ISSUE TITLE
Tab complete auto completes Nicknames and not Realnames.

### ISSUE THREAD

**Issue by Kayla-** [night/BetterTTV#699]
Self explanatory. I can no longer tab complete real names. It automatically replaces with nickname.
Not sure if intended or bug. Feels more like a bug with forcing nickname replacement.

If this is a feature, could it be toggleable?

Edit: If this is a feature, (Since I think its a fine idea) perhaps ctrl+tab or some other keybind would be better instead of removing the real name tab completion functionality.

**Comment by Kayla-** [comment]
Still autocompleting nicknames for me.
Reinstalled BTTV after a fresh uninstall and issue persists as the only plugin. Realnames tab complete to nicknames. Confirmed persistance with FFZ disabled.

**Comment by night** [comment]
When we push to GitHub, that doesn't mean the changes are live.

**Comment by Kayla-** [comment]
Alright.
