### ISSUE TITLE
Following + Chat on the left when going to stories and going back one page

### ISSUE THREAD

**Issue by WillLBegin** [night/betterttv#6998]
### Describe the bug

On firefox, if I open the new stories feature and then click back on the browser, the chat moves to the left of the page with the option chat on right enabled. It seems like it forgets the option is enabled. Refreshing the page fixes it.

![image](https://github.com/user-attachments/assets/a1bc5985-35d1-4e79-a0af-eac5f8743dc7)

### Steps to reproduce

1. Go to stories
2. Go back 
![image](https://github.com/user-attachments/assets/db2e432f-f0ba-469c-a3a6-8cd075d7cc81)
3. Chat is now left.

### Expected behavior

Chat does not move.

### Screenshots

![image](https://github.com/user-attachments/assets/a1bc5985-35d1-4e79-a0af-eac5f8743dc7)

### Device information

PC, Firefox latest version

### BetterTTV Version

7.6.5

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
fixed via 2cbffc2dce24972a9486993c6e4b20e41bcf1734
