### ISSUE TITLE
Emotes tab not showing?

### ISSUE THREAD

**Issue by BluJasmine** [night/BetterTTV#701]
I have uninstalled and reinstalled Chrome, and have disabled and re-enabled emotes, and the emote icon still isn't showing up. Help!

**Comment by cletusc** [comment]
Please make sure you have the "Emote Menu" setting enabled. Works for me.

![](http://i.imgur.com/5rsAlYL.png)

**Comment by DTittel** [comment]
Did you refresh after turning it on?

**Comment by BluJasmine** [comment]
Yes, several times. I even closed Chrome, and relaunched it, after turning it on.

**Comment by cletusc** [comment]
Gonna need your settings backup.

1. Go to "Backup/Import"
2. Click "Download"
3. Upload the contents of that file to http://pastebin.com/
4. Paste the link here.

**Comment by BluJasmine** [comment]
You need me to do a backup on what? My computer or chrome or what?

**Comment by cletusc** [comment]
In BetterTTV settings window, there is a "Backup/Import" tab. Please go there and follow [my instructions above](https://github.com/night/BetterTTV/issues/701#issuecomment-139451498).

The goal is to get exactly what settings you have enabled--all of them.

**Comment by BluJasmine** [comment]
BetterTV settings - Pastebin.com
|   |
|   |  |   |   |   |   |   |
| BetterTV settings - Pastebin.comBetterTV settings By: BluJasmine on Sep 12th, 2015  |  syntax: None  |  size: 0.95 KB  |  views: 20  |  expires: Never download  |  raw  |  embed  |  report abuse... |
|  |
| View on pastebin.com | Preview by Yahoo |
|  |
|   |

**Comment by cletusc** [comment]
You are really making this harder than it needs to be; I wanted the link to the pastebin, not a copy-paste of part of the pastebin page. Luckily, I found it. The pastebin link is http://pastebin.com/F4Mkv5hD for those following this.

```javascript
{
	"anonChat": false,
	"alphaTags": false,
	"autoTheatreMode": false,
	"bttvChat": false,
	"bttvEmotes": true,
	"bttvGIFEmotes": true,
	"showBlueButtons": true,
	"chatImagePreview": false,
	"customTOShiftOnly": false,
	"darkenedMode": false,
	"showDirectoryLiveTab": false,
	"desktopNotifications": false,
	"dblclickTranslation": true,
	"disableHostMode": false,
	"disableUsernameColors": false,
	"disableWhispers": false,
	"dblClickAutoComplete": false,
	"embeddedPolling": true,
	"clickTwitchEmotes": false,
	"showFeaturedChannels": false,
	"followingNotifications": true,
	"groupChatRemoval": false,
	"hideSpam": true,
	"hostButton": false,
	"showJTVTags": false,
	"showMonkeyEmotes": false,
	"modcardsKeybinds": false,
	"alertOtherMessages": false,
	"highlightFeedback": false,
	"hideDeletedMessages": false,
	"showDeletedMessages": false,
	"splitChat": false,
	"tabCompletionTooltip": false,
	"twitchCast": false,
	"blacklistKeywords": "",
	"chatLineHistory": true,
	"chatWidth": 340,
	"consoleLog": false,
	"flipDashboard": false,
	"highlightKeywords": "blujasmine",
	"scrollbackAmount": 150
}
```

Based on the information from your backup, `"clickTwitchEmotes": false,`, you don't have the menu enabled. Make sure "Emote Menu" is enabled in the BetterTTV settings panel as I originally posted.

![](http://i.imgur.com/yqBw8gW.png)

**Comment by BluJasmine** [comment]
Excuse me, but that is really rude of you to say. I knew nothing of pastebin, and don't know crap about coding or anything, and you telling me I am making this harder than it needs to be is so unprofessional. Not everyone knows a lot about the processes of programs, but you saying that I was making it harder than it had to be, is just really bad. Since I first contacted you, I found out 1 friend committed suicide, and another's wife died from cancer, (it was expected but still), so getting grief from you, when I just asked for help, is beyond bad showmanship. I agree that the problem was easy enough to fix, and I know where to look now, but you should take in to consideration that not everyone is 20 years old, and has an agile mind. Thank you for your help, and I hope and pray I don't have to contact you again.

**Comment by cletusc** [comment]
I apologize if they came off as rude; I just wanted to help. I'm sorry for your recent losses; however, this is not the place to discuss those losses, but instead a place to discuss the issue at hand. I have provided the solution to get this issue resolved. If, after enabling the "Emote Menu" setting as I have instructed, the emote menu does not work still, please let me know and we will continue debugging.
