### ISSUE TITLE
Set stream quality automatically

### ISSUE THREAD

**Issue by mattr0d** [night/BetterTTV#702]
I'm not sure if this exists already since I can't find it but if I could make it so all streams are on Source when I join the channel instead of having to manually update it everytime that'd be awesome

**Comment by melalawi** [comment]
Isn't this something that Twitch.tv keeps track of itself?

**Comment by mattr0d** [comment]
I believe it has some sort of flash based cookie thing though it doesn't seem to be reliable, i was just wondering if there was a way to force it with the bttv plugin

**Comment by night** [comment]
Twitch stores a cookie to keep this data already. It doesn't make sense for us to "fix" this, when it's a flash/browser configuration issue on your end most likely.

**Comment by mattr0d** [comment]
on your plugin thing it says come here for feature requests, i didn't come here for a bugfix, thanks anyway though

**Comment by DTittel** [comment]
The thing is this isn't a new feature as Twitch already has this implemented. If it's not working it's because it's a bug.
