### ISSUE TITLE
Followed Channels list does not swap sides when Chat Layout is changed to being on the Left side of the video player

### ISSUE THREAD

**Issue by ghoulishfiend** [night/betterttv#7031]
### Describe the bug

In the bttv settings, when using the chat placement option under Chat Layout and switching it to be at the left side, the "followed channels" list stays on the left along with the chat that's the only thing that switches sides

### Steps to reproduce

1. Settings cog wheel under chat
2. BetterTTV Settings
3. Scroll down to the "Chat Layout" menu
4. Toggle the option that says "Left"

### Expected behavior

[](https://imgur.com/a/CZjPDUg)

### Screenshots

[](https://imgur.com/a/DiIkJB8)

### Device information

- Device : PC
- OS : Windows 11
- Browser : Firefox
- Version : 117.0.1 (64 bit)

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
I'm not able to reproduce this. If you're still having trouble, it's possible you have another third party extension that is conflicting with ours. Try disabling your other extensions to see if it helps.
