### ISSUE TITLE
Deleted messages no longer show

### ISSUE THREAD

**Issue by whatever-forever** [night/betterttv#7051]
### Describe the bug

Deleted messages are no longer showing even when the setting is on. Instead it just says "_message deleted by a moderator._"

### Steps to reproduce

BTTV setting for Deleted Messages set to 'Show Deleted Messages'

### Expected behavior

Show original message that was deleted.

### Screenshots

![Screenshot 2024-09-27 204539](https://github.com/user-attachments/assets/4800eaf6-6bfc-4b26-8838-b407e76d1751)
![Screenshot 2024-09-27 204549](https://github.com/user-attachments/assets/ee6dc45e-0d2b-4d57-861f-7a29ef4c2502)

### Device information

Windows 11 
Firefox 130.0.1

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by beanchill** [comment]
yeah im having the same exact problem

**Comment by Prasao** [comment]
same problem here in chrome, brave, opera and so on

**Comment by night** [comment]
fixed via e3dad9e925af328c145e662a3e2da8404c2ce3cf

**Comment by beanchill** [comment]
Hi it’s still not working for me

**Comment by night** [comment]
You need to be on version 7.6.7.

**Comment by beanchill** [comment]
Ok, how do I choose that version?

**Comment by makedir** [comment]
Still no update on Firefox store. How to get this update?

**Comment by dclstn** [comment]
> Still no update on Firefox store. How to get this update? Where to download 7.6.7 for FF?

One alternative is installing BetterTTV through a UserScript manager like TamperMonkey

Follow the steps on https://betterttv.com on 'Install Other'.

**Comment by makedir** [comment]
Still no update in FF store, how long does it take?

**Comment by night** [comment]
> Still no update in FF store, how long does it take?

Firefox reviews tend to take about a week. If you need a faster fix, consider moving to Edge/Chrome, since they actually review updates in a timely manner.
