### ISSUE TITLE
Chat Message History no longer functions

### ISSUE THREAD

**Issue by HiddenKnife526** [night/betterttv#7052]
### Describe the bug

Pressing the up arrow when in the chat entry box on Twitch no longer shows the previously sent chat messages. I have confirmed the setting is still on, I have disabled and enabled the BTTV extension, closed and started Firefox, and restarted my computer, but none of this helped.

### Steps to reproduce

1. Go to an active stream
2. Click in the chat "send a message" box
3. Type a message
4. Send the message
5. Press the up arrow key
6. Don't get the previous message as it previously did

### Expected behavior

I should get the previous message that I sent when I hit the up arrow key.

### Screenshots

![image](https://github.com/user-attachments/assets/e7771a60-7d6e-49ea-9eb5-eee0c29ae213)

### Device information

Laptop
Windows 10 Home Version 10.0.19045
Firefox 130.0.1 (64-bit)

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dizzyrune** [comment]
Also experiencing this issue

**Comment by AnarcoPunkRJ** [comment]
Same problem on Chrome.

**Comment by night** [comment]
fixed via e3dad9e925af328c145e662a3e2da8404c2ce3cf

**Comment by AnarcoPunkRJ** [comment]
And how do I apply this fix to my extension?
Thanks

**Comment by night** [comment]
You'll need to wait for 7.6.7 to be published in the extension stores. It can take up to few business days, and the extension stores do not generally review on weekends.

**Comment by AnarcoPunkRJ** [comment]
Thanks :)

**Comment by HiddenKnife526** [comment]
> fixed via [e3dad9e](https://github.com/night/betterttv/commit/e3dad9e925af328c145e662a3e2da8404c2ce3cf)

Thanks for the update. Was it something that changed on Twitch's end that caused that function to break, as I wonder if they also did something that messed with the bonus channel points on certain channels. That one I know isn't an issue with BTTV since it even happens when I disabled the extension.
