### ISSUE TITLE
Tab Completion only works for BTTV emotes and not Twitch emotes

### ISSUE THREAD

**Issue by xavierrocket1** [night/betterttv#7053]
### Describe the bug

I tried typing in subscriber emotes and then using tab completion but it doesn't recognize anything to complete to so it does nothing. However, it still appears to work fine when auto-completing BTTV emotes.

### Steps to reproduce

1. Type a partial emote native to Twitch
2. Press tab
3. Native Twitch emotes do not get completed (or do not appear in the cycle if a mix of BTTV/Twitch emotes would auto-complete)

### Expected behavior

The expectation is that all emotes would auto-complete when tab is pressed like before.

### Screenshots

![image](https://github.com/user-attachments/assets/9d50d755-3b90-4f49-b78d-99073ead2425)

### Device information

Windows PC using Chrome

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
fixed via e3dad9e925af328c145e662a3e2da8404c2ce3cf
