### ISSUE TITLE
cant read deleted messages anymore on Firefox addon

### ISSUE THREAD

**Issue by makedir** [night/betterttv#7065]
### Describe the bug

cant read deleted messages anymore on Firefox addon

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

-

### Device information

-

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment]
Duplicate of #7051
