### ISSUE TITLE
Several quality of life features appear to be broken.

### ISSUE THREAD

**Issue by blackcatmagic1** [night/betterttv#7068]
### Describe the bug

In Firefox 130.0.1, tab to complete emotes does not seem to function with Twitch specific emotes, though it works for extension emotes (bttv, 7tv, etc.), however it does not display the emote visual in the message box (just the emote text). Using : to search for the emote and then tab still works. Pressing tab *does not* cycle through input fields in the browser though; it keeps the cursor in the "Send a message" box, but doesn't complete the emote text (other than when using : to search it).

Chat message history does not seem to be functioning (up/down arrow produces no result).

Viewing deleted messages does not seem to be functioning.

I noticed the tab to complete issue first. As far as I'm aware, I didn't have the other issues until I fully uninstalled BTTV from my browser, restarted the browser, reinstalled the BTTV extension, restarted the browser, and then went back in and set the settings for those features. To be clear, those settings show they are enabled for me in BTTV settings.

### Steps to reproduce

Enable "Tab Completion Emote Priority" in BTTV settings and test the feature in chat (start typing a twitch specific emote and press tab).

Enable the other features to see if they work.

May require a clean install to see results. Reddit seems to indicate people have some problems and not others.

### Expected behavior

That emotes previews show and that when pressing Tab, the emote text fills in. Also that the other features just work.

### Screenshots

If needed I can provide.

### Device information

Firefox 130.0.1 on Windows 10.

### BetterTTV Version

7.6.6

### Additional information

Reports of others with similar issues.

https://www.reddit.com/r/Twitch/comments/1frjlhn/tab_completion_for_global_emotes_no_longer_working/

https://www.reddit.com/r/Twitch/comments/1frfwrc/cant_see_deleted_messages_anymore_with_bttv/

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment]
This is releveant: #7051

Please ensure when you tick "I have checked that I'm using the newest version of BetterTTV available.", you're actually on the latest version of BetterTTV, which as of date is 7.6.7 and not 7.6.6.

**Comment by blackcatmagic1** [comment]
My apologies. It would appear that the Mozilla extension hasn't been updated yet as their page lists 7.6.6 as the latest. I had just assumed it was latest since I had just barely reinstalled it before writing my report. Hopefully they'll have it updated sooner than later.

**Comment by night** [comment]
It already was. It takes up to a week for Firefox to review updates. If you cant wait, then swap to Edge/Chrome, which tend to review updates within 24 hours.

**Comment by Sukigu** [comment]
@night, thanks for the update. I don't believe users have any indication of that anywhere so I hope you understand the confusion, when people try to update their extension and the browser tells them it's already up to date.

I will not change to a Chromium browser but it might be a good suggestion for others. :)
