### ISSUE TITLE
Translate API Error

### ISSUE THREAD

**Issue by a05151988** [night/BetterTTV#707]
When I use translate by double clicking , It showed "Translate API Error" error.

**Comment by night** [comment]
I cannot reproduce this problem. What language do you have selected on Twitch? Have you tried switching languages? In the bottom of the left sidebar is a "more" link. Click it, and then select "Language."

You should get a menu like the following:
![](https://nightdev.com/i/ss-kWHRkGcCc8wDIOJBBsKGCgbQn.png)

**Comment by a05151988** [comment]
My Language setting is 中文 繁體.
And when I  watch some other language and double click a chat line, it show me "Translate API Error".

so it's not support chinese?

thank you for your answer. :)

**Comment by night** [comment]
This should now be fixed.
