### ISSUE TITLE
Auto-claim Bonus Channel Points no longer works

### ISSUE THREAD

**Issue by imheinrichlunge** [night/betterttv#7070]
### Describe the bug

I think the title is over-explanatory, with the new Firefox add-on update, channel points are no longer claimed, not even the 10 points that Twitch automatically gives every 5 minutes.

### Steps to reproduce

1. Go to any channel, stay there for 20 minutes.
2. Points don't appeared to be claimable.

### Expected behavior

The regular behavior.

### Screenshots

NA

### Device information

- Device: PC
- OS: Windows 11
- Browser: Firefox
- 131.0
- UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0

### BetterTTV Version

7.6.6

### Additional information

I reinstalled the add-on, it more or less worked again, but stopped working almost instantly.

### Version Check

- [x] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment]
Reopen if issue persists, but hopefully fixed as of [7.6.7](https://github.com/night/betterttv/releases/tag/7.6.7)

**Comment by imheinrichlunge** [comment]
It solved now, tysm for your work.
