### ISSUE TITLE
Multiple BTTV features stopped working

### ISSUE THREAD

**Issue by DarkeImp** [night/betterttv#7073]
### Describe the bug

I tried to change one setting, turning on emote priority for tab completion, & the extension broke entirely. I tried un/reinstalling twice, relaunching browser, relaunching twitch, nothing fixed it. Things that broke:
-tab completion no longer includes twitch sub or global emotes
-up/down arrow for chat history does nothing anymore
-emote priority for tab completion doesn't work when turned on

### Steps to reproduce

I'm not sure exactly what caused this glitch, I only tried to turn on the feature that prioritizes emotes over usernames for tab completion, and I briefly turned on the feature that replaces the twitch native emote menu with the BTTV emote menu. After toggling only a few options in the BTTV settings 'Chat settings' tab like that, I noticed these main features no longer worked.

### Expected behavior

I expected only for emotes to be prioritized over usernames when I try to autocomplete them with tab but multiple features broke down instead, including that one.

### Screenshots

I'm sorry but I can't capture this with any still images and I don't have a means of making a screen recording.

### Device information

Asus laptop, browser firefox up to date as of Oct 4 2024

### BetterTTV Version

7.6.6

### Additional information

I tried the "Reset settings to default" button and that didn't fix any of it either.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by DarkeImp** [comment]
I want to add that I tried the "Reset settings to default" button and that didn't fix any of it either.

**Comment by maxineq96** [comment]
I didn't change a thing I those things still stopped working for me recently. Additionally I also can't see deleted messages any more. I guess twitch changed something and broke things?

**Comment by andi242** [comment]
should be fixed in 7.6.7 according to other issues opened here.

unfortunately Firefox takes quite a while to approve updates. In Chrome it is already updated.

**Comment by DarkeImp** [comment]
> I didn't change a thing and those things still stopped working for me recently. Additionally I also can't see deleted messages any more. I guess twitch changed something and broke things?

This makes a lot of sense, especially if for you it just broke without you even changing anything. I know Twitch has been changing a lot on the platform recently, including the entire app overhaul, and I had been having issues with native Twitch freezing. That's probably what made everything break down, guess we'll have to wait for patches.
Thank you for letting me know I'm not alone though! I didn't see anyone else mentioning anything went wrong with their BTTV in various chats, even when I brought it up, so I thought I just did something wrong haha.

**Comment by DarkeImp** [comment]
> should be fixed in 7.6.7 according to other issues opened here (e.g. #7068 ).
> 
> unfortunately Firefox takes quite a while to approve updates. In Chrome it is already updated.



> should be fixed in 7.6.7 according to other issues opened here (e.g. #7068 ).
> 
> unfortunately Firefox takes quite a while to approve updates. In Chrome it is already updated.

Thank you so much for this information! I didn't notice that thread at all. Since it seems the update that will patch it for Firefox is on the way, and there's already a working option for Chrome, I'm going to close this Issue. Thank you again!

**Comment by DarkeImp** [comment]
This is a known issue apparently resulting from a lapse in updating to the latest version of BTTV which is not currently available for Firefox. The update appears to be in process for approval and release and it's assumed it will fix the issues once available.
This information is available in the #7068 thread.
