### ISSUE TITLE
Tab does not suggest some emotes

### ISSUE THREAD

**Issue by robo300** [night/betterttv#7085]
### Describe the bug

In chat when I provide beginning of emoji and press TAB some emojis are not completed but instead nickname is.
I checked setting option to prioritize emojis over nicknames.
Maybe its because streamers nick is "Mujstach" and emoji is f.e. "MujstaGargul" so beginning of emoji is actually streamers nickname?
It was working so this issue must have been new. 

### Steps to reproduce

1. Go to plugin setting and turn on prioritizing emojis over nicknames when pressing TAB
2. Go to https://www.twitch.tv/mujstach
3. In chat type "muj" and press TAB
4. Word is completed as "MujStach" instead of emojis starting with "mujsta"

### Expected behavior

Word should be changed to emoji starting with "mujsta"

### Screenshots

![obraz](https://github.com/user-attachments/assets/68ff736a-eaa7-4365-83c5-2d272dd954b0)
then I press TAB
![obraz](https://github.com/user-attachments/assets/a6a88c03-0834-494c-b555-56d65e427a3e)
but there are emojis starting with "muj" 
![obraz](https://github.com/user-attachments/assets/a8e99e03-0287-4f26-9224-aed53bb5e306)

### Device information

Windows 11
Firefox 130.0.1

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment]
Should be fixed as of [7.6.7](https://github.com/night/betterttv/releases/tag/7.6.7)
