### ISSUE TITLE
Images/Gifs appear in chat

### ISSUE THREAD

**Issue by Genericinternetuser** [night/BetterTTV#709]
I think it would be cool if images and gifs would appear in chat, that way you could see the images if the chat is moving too quickly to click on the links.

**Comment by melalawi** [comment]
This isn't a good idea imo, for many reasons.

* In crowded chats most images wouldn't finish loading before they're pushed off the screen, making the feature useless.
* This would mean scaling down most images to fit the chat, and larger ones would end up looking unclear and bad.
* The potential for trolls to post shock images exists.

**Comment by night** [comment]
We've thought about this, but given the nature of Twitch chat I would assume there to be much NSFW content linked. In addition, there is limited space in the chat area and we'd prefer to have more chat lines than let images and other embeddable content take up the space. Many Twitch chats move far too quickly for embeds.
