### ISSUE TITLE
Auto join raids

### ISSUE THREAD

**Issue by Booky06** [night/betterttv#7095]
### Describe the bug

I have auto join raids turned off and for some reason it has still been sending me recently

### Steps to reproduce

go to settings>channel> auto join raids option off 

### Expected behavior

I expect not to be sent to another channel when the streamer raids someone else

### Screenshots

![image](https://github.com/user-attachments/assets/918206eb-923c-4ff9-8d8f-cce131994a61)

### Device information

PC Edge 

### BetterTTV Version

7.6.7

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by maxineq96** [comment]
This is also happening on firefox.

**Comment by EnderShadow** [comment]
I can confirm this is also happening for me on linux firefox

**Comment by ITerminusI** [comment]
Recently this functionality stopped working for me as well (Chrome).

**Comment by Dendraspis** [comment]
According to this code lines:
https://github.com/night/betterttv/blob/96db4c3da62c1c39b2a4289a5fcb8cdf753876ac/src/modules/auto_join_raids/index.js#L7-L8

...and this source:
![image](https://github.com/user-attachments/assets/c26d93df-1731-4aae-a8f0-36287a979a40)

the selector should be changed to something like:
```JS
const RAID_LEAVE_BUTTON_SELECTOR = `${RAID_BANNER_SELECTOR} button[class*="ScCoreButtonPrimary-sc-ocjdkq-1"]`;
```
...or as there is only one button:
```JS
const RAID_LEAVE_BUTTON_SELECTOR = `${RAID_BANNER_SELECTOR} button`;
```

**Comment by Booky06** [comment]
issue still exists

**Comment by Booky06** [comment]
my apologies, the tabs that still auto raided needed refreshed, seems to be fine now
