### ISSUE TITLE
Disabling Auto-join Raids not working

### ISSUE THREAD

**Issue by evertonfragoso** [night/betterttv#7097]
### Describe the bug

The Auto-join raids option does not work when disabled.

### Steps to reproduce

- Disable Auto-join Raids option
- Have a channel start a raid

### Expected behavior

With the option off, it should not follow raids, however it does as a Twitch defaults.

### Screenshots

![Screenshot 2024-10-13 123816](https://github.com/user-attachments/assets/91abae4d-a3ea-457c-a19d-9aa2322560eb)

### Device information

PC with Windows 11
Firefox 131.0 (64-bit)

### BetterTTV Version

7.6.7

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
upgrade to 7.6.8

**Comment by evertonfragoso** [comment]
Thanks, did not notice the releases page here, only checked Firefox addons store
