### ISSUE TITLE
Modification to HTML5 player

### ISSUE THREAD

**Issue by EhsanKia** [night/BetterTTV#710]
I think things like hiding options behind a click or a hover is stupid and serves no purpose whatsoever. Having to hover to see and change the volume, having to click an extra button to see or change quality options. All those anti-patterns when there's so much available space in the control bar.

Since HTML5 player is very customizable, most of these can be changed using CSS and DOM manipulation. Just wondering how open you are to these kind of tweaks in BTTV.

**Comment by night** [comment]
I think everyone these days is shifting to hiding controls on hover. YouTube, Twitch, VideoJS, native HTML5 players in Safari and Chrome, and more players are all using this new method of showing controls.

I think it's safe to say most people prefer the controls to hide.

**Comment by EhsanKia** [comment]
I'm not talking about the overall controls hiding, but rather the *second* hover effect for the volume bar, and also all the extra features hidden in the gear button. Those extra clocks seem unnecessary.

Here's two quick unpolished example (paste in a page with a live html5 player)

    // Sticky volume slider
    $('.js-volume-container').css('width', '13em');
    
    // Move quality option to main bar
    $(".js-quality").insertAfter($('.js-quality-display-contain'));
    $(".js-quality").css({float: "left", margin: "5px"})

**Comment by night** [comment]
I mean, they are unnecessary, but they are cool ![Kappa](https://cdn.betterttv.net/emote/560577560874de34757d2dc0/2x.png)

**Comment by EhsanKia** [comment]
p.s. If you ever change your mind, I'm working on this as a separate project and would be happy on helping merging it into BTTV.

https://github.com/EhsanKia/TwitchPlayerPlus
