### ISSUE TITLE
Site too big for monitor.

### ISSUE THREAD

**Issue by anchuin** [night/BetterTTV#713]
Have this problem in firefox:
http://puu.sh/ket57/51b7a97f47.jpg

Used chrome and the site was fine. Imported the BTTV settings from Firefox and the site looked like this again.
When typing in chat, the site scrolls to the right. It can't be scrolled left again.
Settings can be uploaded, if you tell me where.

**Comment by night** [comment]
Clear your cookies to reset your BetterTTV settings and fix the sidebar.
