### ISSUE TITLE
Disabling auto-join raids still not working in popout chat windows

### ISSUE THREAD

**Issue by maxineq96** [night/betterttv#7131]
### Describe the bug

When auto-join raids is disabled, popout chat windows or tabs still follow the raid.

### Steps to reproduce

1. Have a window or tab with a popout chat, the URL being twitch.tv/popout/[streamname]/chat
2. Have the auto-join raid option in BTTV disabled
3. The streamer starts a raid
4. The stream viewer window or tab does not follow the raid
5. The popout chat window or tab does follow the raid

### Expected behavior

The popout chat window or tab should not follow the raid when the auto-join raid option is disabled.

### Screenshots

I have no screenshots.

### Device information

Firefox 13.0.3 (64-Bit) on ubuntu 22.04.5 LTS

### BetterTTV Version

7.6.8

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Since popout chat separates the chat context from the stream context, we're not able to cancel the raid when in popout chat. You may need to avoid popping out the chat when you want to automatically cancel these raids.

**Comment by maxineq96** [comment]
That makes no sense. BTTV is running and working in the popout chat window. And it was working before. It only stopped working recently.
