### ISSUE TITLE
Line-height issues caused by alignment of emotes

### ISSUE THREAD

**Issue by staaky** [night/BetterTTV#714]
BetterTTV aligns emotes to the bottom of a line, which causes awkward jumps in line-height compared to native Twitch, which aligns emotes to the middle of a line.

I've attached an image comparing native Twitch to BTTV, hopefully showing you why middle alignment of emotes is better (notice the difference in spacing between names).

BetterTTV shouldn't be changing alignment of emotes or line-height, it's actually making it worse.

![betterttv_lineheight_bug](https://cloud.githubusercontent.com/assets/5575/9973762/caf8f0a6-5e78-11e5-8d7c-586d089cd4de.jpg)

**Comment by thinkpad4** [comment]
Looks fine to me

**Comment by staaky** [comment]
Seriously, you don't see the difference?

I love good typesetting, this is triggering my OCD.

**Comment by thinkpad4** [comment]
it's like that so the emote doesn't get cut off or overlap the line below

**Comment by staaky** [comment]
They also don't get cut of or overlap in native Twitch. Unless emotes are extremely huge, which is an edge case, at that point I think it's fine to have some overlap since it's more of a problem with the emotes themselves. Twich doesn't accept huge emotes for a reason.

Messing up the line-height for everything just to work around some edge case with huge emotes seems like a tradeoff not worth making.

**Comment by thinkpad4** [comment]
But this isn't native Twitch.  This is BTTV

**Comment by staaky** [comment]
Well it isn't better. If the point here is avoiding overlapping emotes, don't change the alignment of emotes themselves, this causes a randomness in line-height, which looks bad. Keep emotes middle aligned and slightly increase the overall line-height instead, it's a different solution to the same problem, but it'll look better.

I think increasing the line-height isn't even needed though, since it's also making the line-height slightly worse just to fix an edge case that isn't worth fixing.

**Comment by night** [comment]
The problem is that we also have a "split chat" theme, which makes line heights small. Because Twitch sets overflow to true (to "fix" zalgo text), we have to make sure the emote remains within the bounds of the line or it gets cut off.

You're most welcome to experiment with the CSS and contribute a fix, but it's a difficult problem to middle align all emotes while keeping the line height equal consistently. Not all emotes conform to a height of 28px, as legacy ones may be larger (for both Twitch and BetterTTV).

**Comment by staaky** [comment]
I see, I think the fix would be to make sure that nothing of that "split chat" theme leaks in when it's disabled. Only that theme needs to change alignment of emotes, for now.

Making that theme work with middle aligned emotes would be a different issue. I personally don't use it, but I have some ideas to make that look better, I could look into it.
