### ISSUE TITLE
BettrTTV

### ISSUE THREAD

**Issue by feluria2409** [night/BetterTTV#716]
![unbenannt](https://cloud.githubusercontent.com/assets/14362238/9977035/923b8c5c-5ef9-11e5-921d-c54382e39cad.png)
i do not have BetterTTv emotes. they are avtivated but not showing.

**Comment by cletusc** [comment]
"BetterTTV Emotes" enables the custom emotes to be used in chat; the menu is a separate setting. The correct setting for the emote menu is "Emote Menu"--scroll down a bit more and you'll see it.
