### ISSUE TITLE
Auto Play disabled(/Auto Mute enabled) on first visit of a live stream

### ISSUE THREAD

**Issue by notvio** [night/betterttv#7160]
### Describe the bug

The video **doesn't automatically play** on the **very first** visit of a live stream **when first opening** twitch.tv.

In addtion to that the **audio is automatically set to mute** even when visiting another live stream afterwards although auto play is enabled then.

There're also no options dedicated to enabling or disabling either of these "features" in the BetterTTV Settings>Channel Settings>Auto Play.

### Steps to reproduce

1. Open twitch.tv
2. Open a live stream > Auto Play disabled/Auto Mute enabled
3. Open another live stream > Auto Play enabled/Auto Mute (still) enabled
4. Open twitch.tv in a new tab to reproduce

### Expected behavior

Have live streams automatically playback the video with audio and/or have an option to choose in the settings.

### Device information

**Device**: PC
**OS**: Windows 10 Home (**Version**: 22H2, **Build**: 19045.5011)
**Browser**: Google Chrome (**Version**: 130.0.6723.117)

### BetterTTV Version

7.6.9

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by notvio** [comment]
This issue occurs when toggling the `Channel Settings>Auto Play>Offline Channel Player` setting to `Off`, which according to the description 

> Enable auto play of the **welcome video** or **last stream on offline channels**

 shouldn't affect the playback of **live channels**.

**Comment by night** [comment]
I am not able to reproduce any issues with the settings we offer. If you're still having trouble, please upload a video which demonstrates the issue.

**Comment by notvio** [comment]
I found the source of the issue although I'm unsure as to why it's acting the way it is or rather if it should be.

I've been opening Twitch via a bookmark, which leads to my channel but with the addtion of `?no-reload=true` in the URL, so it won't redirect to Mod View. – Otherwise it works as intended when opening through _twitch.tv_.

I'll just use the latter URL as my bookmark instead, **sorry for bothering**.
