### ISSUE TITLE
auto pop out chat

### ISSUE THREAD

**Issue by xderpity** [night/BetterTTV#717]

**Comment by thinkpad4** [comment]
and?

**Comment by xderpity** [comment]
Like have an option to have twitch pop out the chat every time you view a stream

**Comment by night** [comment]
Automatically popping up pages is a bad idea..

**Comment by norecha** [comment]
Why is that a bad idea? It will be optional, if people don't like it, they won't use it. This is not a pop up ad.
I have two monitors and watch the stream on full screen on one, and chat on the other one. I have to manually pop up chat and move it to second screen all the time. I'd really love this feature
