### ISSUE TITLE
Anonymous chat does not work with moderator status

### ISSUE THREAD

**Issue by pquerner** [night/betterttv#7182]
### Describe the bug

When you have moderator status in a channel, you are still shown in the user list, while anonymous mode is active.

### Steps to reproduce

1. Have moderator status in a twitch channel
2. Activate anonymous function from bttv
3. Join the channel you are moderator in

### Expected behavior

Do not show up in user list as moderator

### Screenshots

-

### Device information

Not needed; Google Chrome or Firefox tested

### BetterTTV Version

7.6.9

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
Can you provide a demo video showing the behavior you're seeing? I'm not able to reproduce this issue as described (enable anon chat, enter into a stream, and see myself not be removed from chat)

**Comment by pquerner** [comment]
Yes of course, here is a little video.

https://github.com/user-attachments/assets/3a609bd2-e9e1-46b5-a2dc-2b199de07eb4

**Comment by night** [comment]
Yeah, unfortunately your test would not yield the correct results because it takes 5-10 minutes to disappear from the user list after leaving chat. You'd also have to be sure you're not in chat on a different window.

**Comment by pquerner** [comment]
Oh okay. I thought Moderators always see the "most up to date" userlist. (Atleast, that is what the icon is lead to believe)
