### ISSUE TITLE
: emote search bug and another quirk.

### ISSUE THREAD

**Issue by blackcatmagic1** [night/betterttv#7183]
### Describe the bug

I have two possibly related bugs.

The first is, under some different circumstances, the colon search for non-twitch emotes (so BTTV, 7TV, etc.), tab completion for those emotes, and emote previews appear to break if the chat on Twitch gets disrupted in some way. The emotes can still be seen in chat and I can type them out manually. If I refresh the page, this will temporarily be fixed.

The second is pretty eclectic. I can't figure out how to reproduce this bug, but it occurs for me several times a day when I'm chatting in Twitch chat. It seems almost random when it appears. Basically, when typing in the chat box on Twitch, the text cursor will disappear and the chatbox looses focus, making any inputs I have not go into the chat box, but do other things as you'd expect when the chat box is not the focus (such as hitting "m" will mute the stream or "f" will enter/exit full screen). When I click back on to the "Send a message" box, the height of the box extends to 2 lines (as you see when typing lengthier entries, except there's no characters in there). The box will remain this way until I refresh the tab. To be clear, this is not a misinput of "tab" or some other key on my part. When this happens, the first bug also occurs and I can no longer do colon searches for non-Twitch  emotes (:monkaW) nor see the preview of the emotes in chat if I do type them out (tab complete is also broken for those emotes). I do see the emotes in the chat if typed out manually and entered or if someone else types them in chat. This doesn't appear to affect Twitch specific emotes, colon searches and tab completes for those emotes, or previews of those emotes. If I refresh the page, this will temporarily be fixed.

### Steps to reproduce

For the first issue, an easy way to trigger it is to click the cog wheel next to the "Chat" button and click "Hide chat", then click "View chat". 100% of the time when I do this, the colon search for non-twitch emotes (so BTTV, 7TV, etc.), tab completion for those emotes, and emote previews stop functioning.

For the second issue, I have no idea how to reproduce this other than to type regularly in chat and see when it happens. As far as I can tell, it only happens when I'm actually typing. I usually get this bug 1-2 times a day, but it seems almost random when it will trigger in the middle of typing.

### Expected behavior

I expect the "Send a Message" box not to randomly lose focus while typing. I also expect to see previews of emotes in the "Send a message" box when I input them and for the colon search and tab complete to work. 

### Screenshots
![bedge1](https://github.com/user-attachments/assets/37f2525c-a13e-4b2d-a15b-2dd3dc33e635)
![bedge2](https://github.com/user-attachments/assets/d1691a56-3bad-4a68-a2b5-9266a0519de2)

### Device information

Device: Desktop PC 
OS: Windows 10 22H2
Browser: Firefox 132.0.2

### BetterTTV Version

7.6.9

### Additional information

I disabled all extensions other than BTTV to test this issue and still had the same results, so I don't think it's the result of any other extension.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
This is likely because the chat view is remounting or rerendering, which is causing the BetterTTV modifications to be lost. We usually catch these and re-render our tweaks, but it's possible we are missing some instances of that.
