### ISSUE TITLE
Turn on default twitch chat look

### ISSUE THREAD

**Issue by iispacecakeii** [night/BetterTTV#720]
I really find your settings useful but I prefer the way Twitch chat look as default, so if you can Put an option where I can get the normal chat view. 

Thanks :)

**Comment by night** [comment]
By default BetterTTV does not modify the look and feel of Twitch, so you are mistaken.

**Comment by iispacecakeii** [comment]
The way Text is highlighted and the way DMs look are different.

**Comment by night** [comment]
These are intentional changes and cannot be toggled. Everything cannot have an option, sorry.
