### ISSUE TITLE
uploading an emote results to a false positive "duplicate emote" error

### ISSUE THREAD

**Issue by ztronzo** [night/betterttv#7200]
### Describe the bug

Trying to upload an emote, I am getting a message 
"invalid image (duplicate emote)"
[View Original Emote](https://betterttv.com/emotes/560f59330de1672225dadabb)

This is the emote I am uploading
![dragon-flying-large3](https://github.com/user-attachments/assets/52169748-2056-403d-99e8-15a6f9064318)

This is a false positive alert, as the emote I am uploading has nothing to do with the suggested "Original Emote".
I believe your checking method needs to be revised, or CRC checks give the same result value on both image files.

### Steps to reproduce

1. Login to BTTV
2. Go to Dashboard -> Emotes https://betterttv.com/dashboard/emotes/channel
3. Click on "Upload Emote" https://betterttv.com/dashboard/emotes/upload
4. Fill in the fields:
Emote Code: MoonstoneDragon3
Approval Notes: This is an emote of the Dragon flying over the Moonstone map
Check on "Live" checkbox

5. Try to upload the gif file I am attaching:
![dragon-flying-large3](https://github.com/user-attachments/assets/1786cf5d-650f-486f-9dc1-573aa94c1c91)

### Expected behavior

Should upload without errors

### Screenshots

![image](https://github.com/user-attachments/assets/8606a75b-2635-4048-889c-7541125ba4b7)

### Device information

Windows 10 64bit
Chrome Version 131.0.6778.87 (Official Build) (64-bit)

### BetterTTV Version

its the dashboard on your current webserver, I have no clue on where to check the versions

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
This is likely because you have empty frames of the emote and we're normalized those to be similar enough to the other emote. You'll want to remove any empty frames to prevent this from occurring.

**Comment by ztronzo** [comment]
just for the record: I didnt remove the empty frames but added just 2 pixels on the dragon's wings on just a few of the frames and it was able to go through
