### ISSUE TITLE
bttv

### ISSUE THREAD

**Issue by pavlosgate7** [night/BetterTTV#721]
bttv is a very helpful add-on and i am pleased it exists but there is on thing i would love it to have and that is to be in the channel/chat but have your pc/laptop off . i know this is very difficult to acheive but it would be the best thing to have on bttv . 
Thank you for reading this message

**Comment by night** [comment]
BetterTTV has no ability to remain in chat when you're computer is offline. It's a browser add-on, not an IRC bouncer.

**Comment by pavlosgate7** [comment]
ohh that is a shame but thank you for your answer .
