### ISSUE TITLE
Update twitch

### ISSUE THREAD

**Issue by mrbobbybooo** [night/betterttv#7211]
### Describe the bug

Update is required to use BTTV (twitch)

### Steps to reproduce

I just opened the app

### Expected behavior

To work like normal

### Screenshots

Won't let me upload a screenshot so here's an imgur https://imgur.com/a/n8DAQKL

### Device information

Samsung galaxy S24 ultra OS Android 15 

### BetterTTV Version

0.41.0 beta

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
BetterTTV does not work on Android, so we're not certain what app you're running or why it is not working.
