### ISSUE TITLE
Notification of a new message is not displayed in the chat room

### ISSUE THREAD

**Issue by korolev1337** [night/betterttv#7216]
### Describe the bug

When a new user writes in a chat, BTTV does not show that this is his first chat message

### Steps to reproduce

I installed the extension and configured it, later I noticed that there were no notifications about a new message in the chat, although this feature is enabled

### Expected behavior

A notification indicating that this is the first message from the user in this chat

### Screenshots

![image](https://github.com/user-attachments/assets/a500e171-ce2f-4e57-802e-4f3cc6599025)

### Device information

Windows 11 (24H2)
Yandex Browser (24.12.0.1810)

### BetterTTV Version

7.6.9

### Additional information

BTTV for some reason does not show a notification that the user wrote to the chat for the first time. This is enabled in the extension settings, but it doesn't work, unfortunately

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment]
If the setting is disabled, BetterTTV hides them. Otherwise it does nothing at all. If the messages are not showing for new chatters, then that would be because Twitch is not attempting to show them. It is possible they removed that feature or it only shows in specific situations.
