### ISSUE TITLE
New Twitch stream information layout breaks BTTV left chat layout

### ISSUE THREAD

**Issue by cgifford99** [night/betterttv#7217]
### Describe the bug

Due to the new stream information layout changes on Twitch, the BetterTTV left chat layout creates a gap between the stream information panel and the sidebar nav. This only started to occur for me yesterday (12/11/2024) when I received the new layout changes.

### Steps to reproduce

1. Have BetterTTV installed
2. Navigate to any stream on twitch.tv
3. In the BetterTTV Settings, change "Chat Layout" to "Left"
4. Ensure chat panel is expanded
5. (Whether the sidebar nav is collapsed or expanded has no impact)
6. -----> See that there is a gap between the stream info and the sidebar nav

### Expected behavior

The stream information panel should stretch to the sidebar nav.

### Screenshots

See the black gap on the right-hand side in the screenshot below:
![image](https://github.com/user-attachments/assets/79cb32ad-9bb1-45f5-b906-03c3dfd80cbf)

### Device information

- Device: PC
- OS: Windows 11 Version 23H2
- Browser: Vivaldi (Chromium)
- Version: 7.0.3495.23

### BetterTTV Version

7.6.9

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by neocromicon** [comment]
I can confirm this, I have the same problem. Thanks for the Work.
