### ISSUE TITLE
New channel page layout

### ISSUE THREAD

**Issue by Jon77u** [night/betterttv#7218]
### Describe the bug

Some of the stream elements are now above the stream instead of below it (includes atleast Stream name, Title, Tags, Uptime and viewer count). For some "everything" directly below the stream were seemingly thrown the top side instead, as can be seen on the second screenshot attached.

Not exactly a bug per say, but regardless it's BY FAR the most traffic (and hate) gaining "channel page" thread on the twitch uservoice site

### Steps to reproduce

be one of the UNfortunate ones who got hit by the experimental twitch changes 
https://x.com/zachbussey/status/1866286947024654617

### Expected behavior

For my streaming platform to not be rendered essentially unusable when I opened it

### Screenshots

![greatest twitch update oat](https://github.com/user-attachments/assets/fdb07833-9bb6-4013-9ad3-d8880393e597)
![twitch experiments](https://github.com/user-attachments/assets/db002f04-c1d4-4c42-8a03-7218a029c723)
![greatest twitch update oat 2 ](https://github.com/user-attachments/assets/ccf503b6-35c1-4e61-9404-a4bd9a75b1a6)

### Device information

I think these are irrelevant for this case as it seems to be more so account related, but anyways:

- PC
- Windows 10 22H2 x64
- All browsers seemingly

### BetterTTV Version

7.6.9

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by destroy** [comment]
Dead extension, use FrankerZ instead

**Comment by dclstn** [comment]
there's an open discussion for this here: #7215

**Comment by destroy** [comment]
"completed" BrokeBack
