### ISSUE TITLE
Chat translator

### ISSUE THREAD

**Issue by fishingtimes** [night/BetterTTV#724]
Not sure if this is where to send the feature requests, but I will put it here anyways. I would love to see a translator plug in for Twitch chat. That way people from other countries could select their language and it would automatically post it translated into the chat. Even maybe a translator for the chat messages where you could click on the message and it would be translated for you.

**Comment by night** [comment]
We would never be able to auto translate text. Translations are expensive, costing $10-$20 per million characters.
