### ISSUE TITLE
Chat gets cut off.

### ISSUE THREAD

**Issue by KJP831** [night/BetterTTV#725]
Every stream I go to the chat gets cut in half.

https://gyazo.com/36a761fa8ff3dc26290485ed90bfbf56

**Comment by anchuin** [comment]
Same issue as https://github.com/night/BetterTTV/issues/713

Proposed fix (clearing cookies) does not work.

**Comment by night** [comment]
Proposed fix does work. If it didn't you didn't clear your cookies properly.

If you don't want to mess with cookies you can drag the left side of chat to expand it.

**Comment by anchuin** [comment]
Dragging the chat actually fixes it permanently, which clearing cookies definitely did not.
Thanks tho.
