### ISSUE TITLE
Video player selected by default

### ISSUE THREAD

**Issue by dadams817** [night/BetterTTV#727]
In the current form of bttv when you switch tabs into a twitch tab, the chat input is automatically selected. A little while back the player itself used to be selected by default (it still is this way in standard twitch). I am a super lurker so I almost never type in chat, but I am often switching tabs while watching streams and it is a little annoying to have to click on the player every time I switch back and want to change volume/mute or fullscreen. An option to have the player selected by default would be amazing for all us lurkers (on the rare occasion I do use chat, alt + enter works just fine).

Thanks

**Comment by night** [comment]
With Twitch's switch to their new player, it does not grab the context when you swap tabs. You can confirm this by disabling BetterTTV.
