### ISSUE TITLE
Slowmode while stream is offline

### ISSUE THREAD

**Issue by Kebabscout** [night/BetterTTV#731]
So, I was in just chatting in the room of the user GeekRemixALot(http://www.twitch.tv/geekremixalot) when I noticed this issue. The room was in slowmode after previous stream and I asked the streamer/mods to take it off. For some reason, even after they took it off, bttv showed the room was in slow and my messages got blocked by the slowmode. After I refreshed the page, the slowmode went off. This has never happened during any streams, only this one time while the channel itself was offline.

**Comment by night** [comment]
It's quite possible this is just an anomaly, since I cannot reproduce this.
