### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by mkjol** [night/BetterTTV#735]
Hay!
Can you add option to turn off auto-aborting clearing chat? ;p (I, know my english isnt really good :/ )
Here is an example of what I mean
![bez tytulu](https://cloud.githubusercontent.com/assets/14931676/10233373/5c9ad064-688e-11e5-8aca-a76d6bcf3051.jpg)

Greets and thanks you in advance!

**Comment by night** [comment]
Duplicate of #524
