### ISSUE TITLE
Toggle chat message timestamps

### ISSUE THREAD

**Issue by edadams** [night/BetterTTV#738]
For people who only participates in busy stream chats, timestamps are nothing but visual clutter (because all visible messages were only sent in the last few minutes).

I would like to request a toggle for chat timestamps that permits users to hide them. The toggle would be **disabled** by default.

I think the the space in the Twitch page layout for chat is already slim without the timestamp taking up even more space, but that might just be me!

**Comment by night** [comment]
There's an option in the chat settings already.

**Comment by edadams** [comment]
I've just realized how blind I was being! BetterTTV had overrode my timestamps setting in the normal Twitch settings menu, and I was scrutinizing the BTTV settings so hard I completely failed to spot it there.

@night It *might* be a bug in that it overrides the user's chosen setting for timestamps, but it really isn't a big deal. Since I can't delete issues, I'll just close this.
