### ISSUE TITLE
Parts of BTTV not working

### ISSUE THREAD

**Issue by MinnesotaWild91** [night/BetterTTV#744]
Hello, I went on Twitch and parts of BTTV were not working for me. Some of the issues include.

- BTTV emotes not working
- Link previews not showing up when hovered over
- Emote names not showing up when hovered over

I've reinstalled BTTV and the problems still show up? Are parts of BTTV down?

Thanks, Keith

**Comment by night** [comment]
We've posted a Tweet: https://twitter.com/BetterTTV/status/651096462365990912
