### ISSUE TITLE
Добавьте функцию/Eng enable

### ISSUE THREAD

**Issue by TsebTra** [night/BetterTTV#746]
Прошу добавить кнопку которая позволяет имитировать нажатие клавиши F11. Просто она часто используема.

Please add a button press which simulates the pressing F11.

**Comment by voloshink** [comment]
Кнопка на клавиатуре быстрее виртуальной кнопки, зачем добавлять кнопку которая будет мешаться в интерфейсе, на которую нужно наводить курсор когда можно просто нажать f11?

**Comment by TsebTra** [comment]
Я и думаю другие кто будет делать так же ![15hbbub](https://cloud.githubusercontent.com/assets/15000538/10315661/46bef020-6c64-11e5-92fb-2f1e111609dc.jpg)
 будут оооочень часто её использовать.

**Comment by TsebTra** [comment]
voloshink понимаешь к чему я? Театр + Ф11 как по мне маст хэв

**Comment by voloshink** [comment]
Я не понимаю зачем нужно кнопка в интерфейсе когда можно просто нажать клавишу

**Comment by TsebTra** [comment]
voloshink по моему так намного удобнее, извините что отвлёк тогда

**Comment by TsebTra** [comment]
Может действительно только я один её использую

**Comment by voloshink** [comment]
Просто пространство на экране довольно огроничено, мы хотим его использовать как можно эфективние, если кнопка просто будет заменять одно действие на клавиатуре, то мне кажется особо смысла в этом нету

**Comment by TsebTra** [comment]
переключатся постоянно с мыши на клаву это как работа с интером в АвтоКаде - непрактично для простого пользователя
А в случае с такой кнопкой было бы намного быстрее а значит и комфортнее. Если это тяжело, а места рядом с кнопками Чат, Настройки и т.д. предостаточно как по мне...

**Comment by voloshink** [comment]
Даже если бы мы решили добавить кнопку, в данный момент мы не может симулировать нажатие 'f11' с js.

**Comment by TsebTra** [comment]
Окей, моё дело предложить, нерационально так нерационально
