### ISSUE TITLE
Double-clicking username urlencodes chat message

### ISSUE THREAD

**Issue by anowlcalledjosh** [night/BetterTTV#747]
e.g.

    what do you think the biggest discovery in mario 64 speedrunning was?

to

    what%20do%20you%20think%20the%20biggest%20discovery%20in%20mario%2064%20speedrunning%20was%3F

**Comment by night** [comment]
I cannot reproduce this. Are you sure it's BetterTTV and not another add-on causing this?

**Comment by anowlcalledjosh** [comment]
Now I can't reproduce it either...
