### ISSUE TITLE
Twitch chat beta issuie

### ISSUE THREAD

**Issue by dums** [night/BetterTTV#748]
Having problems with Twitch Chat Beta, when I logout from it, it automatically logs me back in again, and the possition of the chat makes it that I can't change quality or make it fullscreen if I have Theater Mode.

![twitchchattt](https://cloud.githubusercontent.com/assets/2631120/10342804/25e907c0-6d1b-11e5-9078-ca65c8e186eb.JPG)

**Comment by night** [comment]
If you want to disable it, you should turn it off in the BetterTTV Settings. It automatically logs you in otherwise.

**Comment by dums** [comment]
Where can I find this option, I have been looking everywhere.
