### ISSUE TITLE
HTML5 playback stats fix / sticky values

### ISSUE THREAD

**Issue by Sundheden** [night/betterttv#749]
Since the new HTML5 player came I miss the old styled stats window, where the latency to broadcaster was at the bottom, and I could MOVE the window around, so only that value was visible by dragging most of it out of the video. It was also way smaller.

To fix this, I would LOVE a neat little feature to always show a stat value on screen, some people might like to see skipped frames, playback rate etc too. Personally I find the latency to broadcaster to be VITAL information when interacting with a streamer.

**Please look at my mockup: http://i.imgur.com/U0Hkycu.png**

In this mockup I added checkboxes for what value(s) to keep sticky, option on where to show the values, and the value itself in the chosen position. **If you don't see all the details, look at this descriptive image highlighting them: https://i.imgur.com/WBRtkum.png**

An alternative to this could be to have the latency shown next to the chat button, or similar, if that's easier.

**Comment by Iwasawafag** [comment]
> An alternative to this could be to have the latency shown next to the chat button, or similar, if that's easier.

Another alternative would be muting them visually (by lowering opacity) or maybe having a line between messages, marking which messages crossed this time window and making it easier for the viewer to determine at which messages we can expect streamer to react to at every moment.

**Comment by night** [comment]
Thanks for the request. After the years of this request being open it doesn't seem like there's much traction on it. Most delay to the broadcaster these days is also negligible unless you are buffering constantly. For these reasons we have decided to close this request.
