### ISSUE TITLE
BTTV Chat disappears

### ISSUE THREAD

**Issue by edshot90** [night/BetterTTV#750]
Since a few days the chat on every Twitchstream I have watched dissapeard halfway over the screen.
I have attached a screenshot of it.
First one with BTTV
![withbttv](https://cloud.githubusercontent.com/assets/15040862/10382009/d7c02f14-6e1f-11e5-8446-054fe1fb313a.jpg)
Second, without BTTV
![withoutbttv](https://cloud.githubusercontent.com/assets/15040862/10382008/d7c02ec4-6e1f-11e5-99e0-49f8c851d63f.jpg)

When i deactivate BTTV in the FF Addons tab and reload Twitch.tv its all fine.

I use the newest Firefox (41.0.1) and  BTTV version (Version 6.8R43)

**Comment by night** [comment]
You can either drag the left side of chat or clear your cookies/cache from the beginning of time to fix the problem.
