### ISSUE TITLE
BTTV & Firefox Nightly, let and const compliancy

### ISSUE THREAD

**Issue by MeatyChunks** [night/BetterTTV#754]
Thought I'd let you guys know; It seems like there was a change that caused a load of addons to stop functioning and BTTV got hit too. You can see more info at https://groups.google.com/forum/#!topic/mozilla.dev.platform/XoW35OxqDYI and https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/. Hope this helps!

**Comment by vendethiel** [comment]
We do not use `let` or `const`.

**Comment by MeatyChunks** [comment]
Apologies for the late reply. Am I seeing wrong or is bootstrap.js not full of `const`? Replacing them with `var` gets most of it working from what I can see though I am not sure if this is the full fix. Thanks.

**Comment by night** [comment]
``bootstrap.js`` is generated by Mozilla's Add-On SDK: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm, not us. Most likely this is a Mozilla bug, not one of our own.

**Comment by shavitush** [comment]
@night so we should just wait for the next Nightly updates to get it solved?

**Comment by night** [comment]
@shavitush I was able to get the add-on working in Nightly after rebuilding it with a newer version of Mozilla's jpm tool. I have submitted the add-on update for review with Mozilla, and will push the update live to everyone once approved.

**Comment by night** [comment]
Just an update that we're still waiting on Mozilla to review the add-on. Queue Placement: 25/34

**Comment by night** [comment]
The add-on has been approved and released. If you "Check for updates" in your add-ons area, it will force an update. Optionally, you can also just redownload and install at https://nightdev.com/betterttv
