### ISSUE TITLE
Repeat notifications of the same 2 streams.

### ISSUE THREAD

**Issue by Apolloftw** [night/BetterTTV#755]
I have been getting repeat notifications of the same 2 streams every time I switch to a twitch tab.
http://i.imgur.com/msfaCxq.png
http://i.imgur.com/jmhHGhl.png
http://i.imgur.com/HJ6fjNM.png
http://i.imgur.com/Pew27UV.png

**Comment by MattiSony** [comment]
The 2 channels that's popping up are they in the VOD playlist beta? I've noticed this when a person that's in the VOD Playlist beta and is live it gives me notification for that person like every 5-10 min. Maybe the NightDev can look into it more.

**Comment by night** [comment]
Channels playing playlists shouldn't be generating notifications, which makes me wonder if the API is mistakenly reporting them as non-playlist channels temporarily. I'll have to look into this.

**Comment by MattiSony** [comment]
For me it seems to happen while the channel is live. Not when it's just playing a playlist, so the API is probably being weird while the channel is live and has the Playlist on at the same time.

**Comment by night** [comment]
I have a feeling this may be a Twitch issue with their caching. They appear to be using two different servers to serve the streams endpoint? Some requests have filled out CORS headers and others do not. Unfortunately since I can't seem to reproduce the issue I cannot confirm.

**Comment by flamedog** [comment]
Any way we can log information to share ? :3 Currently using Chrome.. then again if it's a caching problem you may not be able to see anything local ?
