### ISSUE TITLE
Following URL redirect

### ISSUE THREAD

**Issue by JunoJin** [night/BetterTTV#757]
I'm not sure if this is a bug, but going to http://www.twitch.tv/directory/following automatically redirects to http://www.twitch.tv/directory/following/live, going to the "Channels" tab instead of the "Overview" tab. This is on Chrome. Disabling BetterTTV resolves this issue, and enabling it again does not fix this.
Is this something on my end?

**Comment by night** [comment]
You have the BetterTTV setting "Default to Live Channels" enabled..
