### ISSUE TITLE
Current Viewer Amount in Theater Mode

### ISSUE THREAD

**Issue by Trubbel** [night/BetterTTV#765]
This might not be the most necessary feature, but I would love to be able to have the current viewer amount in theater mode. Having to go another monitor and exit theater mode just to check the viewer count gets old after a while.

Maybe something like this,
![viewers_amount](https://cloud.githubusercontent.com/assets/10730122/10483117/c6a15f7a-727d-11e5-898b-53d1bb186f86.png)
Alternate,
![viewers_amount_alt](https://cloud.githubusercontent.com/assets/10730122/10483120/cc43ee66-727d-11e5-9a6f-fda6d9333a8c.png)

**Comment by night** [comment]
We're not interested in adding more clutter to the chat UI, sorry.

If you want to see channel stats, don't use theater mode. You can close the left sidebar for a larger video player, and still see the title and stream stats.
