### ISSUE TITLE
Shared emote limit

### ISSUE THREAD

**Issue by EhsanKia** [night/BetterTTV#773]
Any chance to raise the limit of shared emotes from 5 to something slightly higher such as 10 or 20?

I realize the limit is there to avoid people making multiple accounts to avoid the 5 upload limit, but considering there are thousands of custom emotes, only being able to use 5 is silly.

If you're really set on the limit, maybe make it 10 total limit (uploaded + shared)?

**Comment by Quaesitum** [comment]
I have something that sort of relates to this. Make it so you can disable some emotes and have the max enabled emoted to 5+ then let use have multiple shared emotes that are not used in your own channel

**Comment by night** [comment]
You can now subscribe to BetterTTV Pro for higher limits. Learn more at https://manage.betterttv.net/channel
