### ISSUE TITLE
Emotes not working

### ISSUE THREAD

**Issue by ThaGary** [night/BetterTTV#775]
Some of my emotes dont work anymore also the emote for the black eye emote is really messed up 
![187bb067a7876f288243c4b7b7ed6ce1](https://cloud.githubusercontent.com/assets/13490563/10591775/b3191ad4-767d-11e5-91f0-34e5aaf58cca.png)
![ebd80616dc8801dbc09aa9b508011607](https://cloud.githubusercontent.com/assets/13490563/10591776/b4c9bd34-767d-11e5-811a-49cc87afb351.png)

**Comment by night** [comment]
This is a Twitch bug that Twitch is looking into. We have no way to fix it.
