### ISSUE TITLE
BTTV login bug

### ISSUE THREAD

**Issue by Vagenie** [night/BetterTTV#777]
I cannot get my twitch to connect to the BTTV extension. I am trying to connect through the emote section. My username and password for Twitch is correct. The following is the error I get. {"error":"Bad Request","status":400,"message":null}

**Comment by night** [comment]
I cannot reproduce this. If this error continues, it may be Twitch who is at fault. If the address bar says "api.twitch.tv" then it probably is. We need more information to be able to report this issue to Twitch.

**Comment by Vagenie** [comment]
Ok, it is working for some reason now. I have no idea what I did but I literally tried it just now and I was able to connect the two.
