### ISSUE TITLE
White background…DarkenTTV?

### ISSUE THREAD

**Issue by PixelWolf1** [night/BetterTTV#780]
Even though I have DarkenTTV enabled, there is a white background for the login/signup menu. I don't know if this is caused by a bug or if there's something else wrong. I've tried clearing my cookies, reinstalling BetterTTV, updating my browser, but to no avail. Help would be greatly appreciated.

![untitled](https://cloud.githubusercontent.com/assets/14169499/10675677/961c21e8-78cf-11e5-8439-78eb576f8743.jpg)

**Comment by night** [comment]
While we'd love to fix it, it's impossible to fix. Twitch embeds a secure iframe on the page. The iframe serves a login page with secure headers, which tells browsers essentially "Hey, only allow stuff from Twitch's domain to run here." Because of this, the page cannot be modified.

**Comment by klarstil** [comment]
@night It should be possible in Chrome and Firefox. I'm not sure about Opera, Safari or Userscript (Greasemonkey, Tampermonkey, Violentmonkey, etc.) though.

---

**Chrome:**
You should be able to use the `content_scripts` property in your `manifest.json` to inject CSS or JavaScript files to specific websites:

```
{
    "content_scripts": [{
        "matches": [ "https://passport.twitch.tv/*" ],
        "css": [ "styles-for-the-login.css" ]
    }]
}
```
https://developer.chrome.com/extensions/content_scripts

Another way would be to use the `insertCSS` method of the `chrome.tabs` API: https://developer.chrome.com/extensions/tabs#method-insertCSS
Just make sure you grant permissions for the `tabs`:

```
{
    "permissions": [
        "tabs"
    ]
}
```
----

**Firefox:**
It's a bit more complicated to do the same for Firefox. You have to use the `page-mod` API combined with the `self` API:

```
var data = require('sdk/self').data;

require('sdk/page-mod').PageMod({
    include: [ "https://passport.twitch.tv" ],
    contentScriptFile: [ data.url('style.css') ],
    // ...or
    contentStyle: [
        "div { padding: 10px; color: red }",
    ],
    attachTo: [ "existing", "top", "frame" ]
}); 
```
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-mod
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/self

**Comment by night** [comment]
We do not wish to deal with maintaining add-ons since they require manual uploads for updates, sorry.

**Comment by klarstil** [comment]
Understandable, just wanted to point out the direction how to fix it. It's a minor issue and not worth taking time to manual upload the updates.
