### ISSUE TITLE
Pause chat on mouseover/hotkey

### ISSUE THREAD

**Issue by JiMiKi** [night/BetterTTV#782]
Hey, would it be possible to add a toggle that lets you hold a hotkey and/or mouseover chat to pause it temporarily?

I'm sorry if this is too similar to other feature requests that have been made in the past by others, but I can't stress enough how much I would like to have a feature where chat pauses on a hotkey or mouseover, there used to be a chrome extension for this (paused chat when holding Ctrl) but I uninstalled it a while ago, and after hours of searching for it I can't find it again, hence requesting it as a BTTV feature, even though you've declined similar requests.

**Comment by conceptionals** [comment]
This type of feature already exist with vanilla Twitch. You can temporarily *pause* the chat by scrolling up a little while moused-over chat, and resume by clicking the "More messages below" indicator. 

![b1e7c015a5cd148d1acc4842b5759530](https://cloud.githubusercontent.com/assets/13137308/10682400/eac6e842-78fa-11e5-9628-dbfa0ea6dbe2.gif)

**Comment by JiMiKi** [comment]
Yes, by scrolling up... I realise that's a thing already, but to do so without scrolling was the point, mostly because if you're a little too fast and you scroll up to pause chat the message you want to see might be too far down to be visible (since you must scroll up like... 10+ lines for the pause to activate, otherwise it just pops back down as soon as next message arrives), which just makes it really inconvenient when you have to sit there and search for the message you wanted to read

**Comment by night** [comment]
You only need to scroll up about a single line to pause chat. It's definitely not inconvenient at all, and still provides the functionality required. If you're concerned about seeing name mentions of yourself, you can enable "Pinned Highlights" in the BetterTTV settings.

**Comment by JiMiKi** [comment]
Ah well, it's definitely not 1 line for me, i gotta move a couple of "steps" on the scroll wheel for it to stop scrolling when new messages are posted. Anyways, appreciate the quick reply and I love BTTV even without such a feature! keep up the great work! :)
