### ISSUE TITLE
bttv is great but it has one annoying thing!

### ISSUE THREAD

**Issue by xABDulRaHManZz** [night/BetterTTV#783]
A lot of the buttons are misplaced!, look at the picture.
![dadawdawda](https://cloud.githubusercontent.com/assets/8313429/10683345/8c480298-7949-11e5-9db2-266f38e69a95.PNG)

**Comment by night** [comment]
The font size looks way larger than what it's configured to be, which means you're either zooming in the page or have changed browser font defaults. Try resetting page zoom as well as your browser's default font settings.

**Comment by xABDulRaHManZz** [comment]
i havn't done nothing of what u said, everything is default!
