### ISSUE TITLE
Slowmode timer is not precise

### ISSUE THREAD

**Issue by ozon671games1** [night/BetterTTV#785]
BetterTTV's slowmode timer ticks slower than twitch's slowmode timer
![slowmode](https://cloud.githubusercontent.com/assets/11681316/10711449/394aa000-7a84-11e5-8aa6-aed505418bfb.jpg)

**Comment by night** [comment]
This is unfortunately not something we can fix. We use timeouts in JS, but they are not accurate for time keeping. If your computer is lagging behind or there is a quickly moving chat then the timer may not be accurate. It should still be close enough to give a good judgement of when you can speak again.
