### ISSUE TITLE
Notify when a message's length is too long to send

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#788]
When sending some messages during a subscriber spam, for example, I want to make sure that my message goes through with maximum ![HY](https://static-cdn.jtvnw.net/emoticons/v1/11301/1.0)![PE](https://static-cdn.jtvnw.net/emoticons/v1/11302/1.0).

Messages over [~500 characters](https://tools.ietf.org/html/rfc2812#section-2.3) should notify that it probably won't be sent through.

**Comment by voloshink** [comment]
Sounds like it could be a good adition, what would be the best way to let the user know though?

**Comment by AlcaDesign** [comment]
Either just set the max length on the chat box or a message just like when you host someone, time-out, etc.

**Comment by EhsanKia** [comment]
@voloshink Just a notice probably, aka `serverMessage` in helpers.

**Comment by voloshink** [comment]
Might just end up limiting the textarea to 500 characters, maybe a notice in chat too

**Comment by AlcaDesign** [comment]
A whisper's setup (/w name) should be taken into account, though

**Comment by voloshink** [comment]
is the character limit different for whispers?

**Comment by AlcaDesign** [comment]
No, but typing "/w <name>" would be changed into a whisper event rather than sending "/w <name> <message>" to the server.

**Comment by voloshink** [comment]
I see

**Comment by voloshink** [comment]
I tested it out, for both /me and /w the limit is still 500 total, otherwise the message doesn't go through

**Comment by EhsanKia** [comment]
Is that 500 including the "/w username" and "/me" part or only the messages after it?

**Comment by voloshink** [comment]
500 with the command itself

**Comment by night** [comment]
Twitch limits user input, regardless of command, to 500 characters. It's still [Hacktoberfest](https://hacktoberfest.digitalocean.com)! Feel free to open a pull request that adds a `maxlimit="50"` onto the textarea for chat input.
