### ISSUE TITLE
Emote bug?

### ISSUE THREAD

**Issue by Andrewkun** [night/BetterTTV#791]
I have a lot of missing emotes, I've tried cache clearing, cookie cleaning, re-installing my browser and non them work, I don't know it you can help me, here a picture of some of them missing http://prntscr.com/8vv5d3

**Comment by MellowNebula** [comment]
This is a Twitch issue, not a BetterTTV issue. Something between Twitch and their CDN is borked, it doesn't affect BTTV emotes, should be resolved in the coming days.
