### ISSUE TITLE
Scrolling Over Video to Change Volume

### ISSUE THREAD

**Issue by Forezke** [night/BetterTTV#792]
The ability to adjust the volume of the video player when scrolling with a mouse wheel over the player would be useful.

**Comment by tehmaxhypegaming** [comment]
+1.

**Comment by EhsanKia** [comment]
I usually implement this one pages that have no scrolling, but in this case, if the whole player steals your scrollwheel action, then trying to scroll down to the panels under the stream might get really annoying. Yes you can scroll in the corners, but usually you just scroll roughly in the middle and this would break that.

**Comment by Figzyy** [comment]
+1 

Really want this!
