### ISSUE TITLE
CSS support for tag filter arrows

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#794]
![Example](https://i.gyazo.com/45e7aa17b614f3b1c0a4733ee767ce94.png)

On the [creative game directory](http://www.twitch.tv/directory/game/Creative) and probably others, there is a tag filter.

Example from creative: (at second "page")
```html
<div class="creativetag-list-contain filter-list-contain js-filter-list-contain clearfix">
  <a class=" filter-nav goleft js-goleft"></a>
  <a class=" filter-nav goright js-goright"></a>
  <div class="creativetag-list filter-list js-filter-list clearfix">
    <ul style="left: -1284px;">
      <li><a id="ember3121" class="ember-view active" href="/directory/game/Creative" data-ytta-id="-"><span class="creativetag">All Channels</span></a></li>
    </ul>
  </div>
</div>
```

**Comment by night** [comment]
It's [Hacktoberfest](https://hacktoberfest.digitalocean.com)! Feel free to open a pull request to fix this, since you seem capable to do so. Otherwise we'll get it fixed eventually.
