### ISSUE TITLE
[Feature Request] Add "H" to mod card keybinds for 1 hour.

### ISSUE THREAD

**Issue by Izlsnizzt** [night/BetterTTV#800]
Self explanatory, I often use 1 hour timeouts in event channels, would be nice to have a hotkey for it.

**Comment by voloshink** [comment]
I can add it if night's ok with it

**Comment by night** [comment]
Right click on name -> select 1 hour

**Comment by Izlsnizzt** [comment]
That's the same procedure for things that already have hotkeys, how is this any different?
