### ISSUE TITLE
Emote Help

### ISSUE THREAD

**Issue by synnpai** [night/BetterTTV#805]
Hey!

So I have a strange case as I had a twitch channel name change. My emotes still link to my old channel, and I contacted twitch and they said it was a BTTV thing and not a twitch issue. Is there anything you guys can do to change that? The previous channel is danaejosephine, and the current one is synnpai.

**Comment by night** [comment]
If you got a Twitch name change, simply logging into the control panel reassigns your emotes to your updated name. If this was not an official Twitch name change, you should login to your old account and remove the emotes (and then reupload them under your new account).

**Comment by synnpai** [comment]
The emotes are not BTTV emotes, they are my channel subscription emotes,
not sure if I made that clear. I have tried logging in as Synnpai, it
hasn't reassigned them (although I'm not exactly sure where the BTTV
control panel is located).. The channel 'DanaeJosephine' is not a partnered
channel anymore because it was an official twitch namechange, yet my emotes
(even when uploaded from Synnpai) still link to Danaejosephine.

**Comment by night** [comment]
If you mean the channel information when hovering over emotes, you'd need to reach out to TwitchEmotes instead. We just use their data.
