### ISSUE TITLE
Highlight Keywords Not Highlighting

### ISSUE THREAD

**Issue by jamesk77** [night/BetterTTV#807]
I have tried setting keywords for my username and nothing gets highlighted, not even my default username gets highlighted anymore. I'm using the Safari extension (version 6.8).

**Comment by voloshink** [comment]
could you please export your bttv settings and upload them here?

**Comment by jamesk77** [comment]
is this what you're looking for?

{"anonChat":false,"alphaTags":false,"autoTheatreMode":false,"bttvEmotes":true,"bttvGIFEmotes":true,"showBlueButtons":false,"chatImagePreview":false,"darkenedMode":true,"showDirectoryLiveTab":false,"desktopNotifications":false,"dblclickTranslation":true,"directoryPreview":false,"disableHostMode":false,"disableUsernameColors":false,"disableWhispers":false,"dblClickAutoComplete":true,"embeddedPolling":true,"clickTwitchEmotes":true,"showFeaturedChannels":true,"followingNotifications":true,"groupChatRemoval":false,"hideSpam":true,"hostButton":false,"showJTVTags":true,"showMonkeyEmotes":true,"modcardsKeybinds":false,"alertOtherMessages":false,"pinnedHighlights":false,"highlightFeedback":true,"hideDeletedMessages":true,"customTOShiftOnly":false,"showDeletedMessages":true,"splitChat":false,"tabCompletionTooltip":false,"blacklistKeywords":"","chatLineHistory":true,"chatWidth":340,"consoleLog":false,"flipDashboard":false,"highlightKeywords":"@Karkland Karkland kark","scrollbackAmount":150}
