### ISSUE TITLE
Player Enhancement Suggestions

### ISSUE THREAD

**Issue by Nathsters** [night/BetterTTV#811]
Since the HTML5 controls came out haven't been able to double click to fullscreen and I was wondering if would be possible to add in. Also could it be possible to press 'F' to fullscreen? Either one of those would be greatly appreciated.

**Comment by voloshink** [comment]
Double clicking works for me, goes to fullscreen. Are you sure that's not an issue on your end?

**Comment by Nathsters** [comment]
Yeah I fixed it on my end. It was an adblocker for some reason. Now I would
still like F for fullscreen, M for mute and the sorts.

**Comment by vendethiel** [comment]
I'm afraid we can't control the player :/.
