### ISSUE TITLE
A way to hide mod spam

### ISSUE THREAD

**Issue by havok0159** [night/BetterTTV#812]
On some channels, mods will end up spamming more than regular chat by turning submode/slowmode or whatever on and off. Since these notifications show up in chat, when spammed they will end up completely blocking off the chat. A way to hide these notifications would be really nice.

This would be an example of what I'd like to be able to hide.

![capture3](https://cloud.githubusercontent.com/assets/15723019/11025541/06fde972-86a5-11e5-8ea8-818a9fe6d304.PNG)

**Comment by night** [comment]
It is the broadcaster's responsibility to choose responsible moderators. If a stream you're watching has moderators doing this, you should complain to the broadcaster.
