### ISSUE TITLE
BTTV Feature Suggestion

### ISSUE THREAD

**Issue by TheStandingStreamer** [night/BetterTTV#814]
Hello, 

Have a suggestion for you guys; what about implementing a feature where you can type /f (username) in twitch chat and follow said individual?

kDoGG3n4
TheStandingStreamer

**Comment by night** [comment]
You should just click on their name in chat and follow them instead. I don't think we need two ways to follow people within chat.

**Comment by TheStandingStreamer** [comment]
BTTV,

     Very good point. BUT, let's say I am LIVE...and I say "HEY CHECK OUT
THIS GREAT STREAMER, tronic20tv."  But Tronic20tv is not viewing, so if I
could type /f tronic20tv, then BOOM.  I have followed a Great Streamer.

kdogg3n4

**Comment by night** [comment]
I do not see this as something that would happen often, if ever, sorry. At the very least a streamer would link someone's channel in chat. For the majority of "channel raids" that happen, the streamer also joins in on the raid.

**Comment by TheStandingStreamer** [comment]
BTTV,

    This has nothing to do with RAIDs.   I HYPE other streamers all the
time.  Not just the ones that RAID me.  Sometimes the people I HYPE are not
in the channel.  and it is quicker to type /f handle, then hit a command.
Just Saying.

kdogg3n4

**Comment by night** [comment]
Unfortunately this changes nothing as you're the edge case. The majority of streamers do not do this, so adding a command for following is practically a useless feature for most users. Given our goal is to appeal to the majority (not the minority), it still does not make sense for us to consider this as a feature, sorry.

**Comment by TheStandingStreamer** [comment]
BTTV,
          How can viewers in chat follow someone that is not in chat & the
streamer does not link them, but mentions them?   Plus, it keeps people in
your stream, then having them click a link and leave to follow.  It keeps
the retention of people in your stream, which is what the majority of
streamers want.

 kdogg3n4
