### ISSUE TITLE
Option to filter "subscribed to" messages.

### ISSUE THREAD

**Issue by CrosseyeJack** [night/BetterTTV#816]
When in host mode tmi sends "XXX subscribed to {hostedchannel}".

I fell it would be nice if we had an option to filter to remove these subscription messages.

**Comment by night** [comment]
It doesn't really feel like a needed feature to me, sorry. If you're watching a hosted channel and someone subscribes, the message provides context as to events occurring on the stream you are watching. If enough people ask for this we may reconsider, but given how long hosting has been out and that nobody has asked for this yet I'm not sure there's enough community support to warrant adding this feature.
