### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Menchii** [night/BetterTTV#818]
It would be nice to be able to hide the streamers broadcasting playlists.  I don't want to see who is showing me old vods.  This is similar to how it is already possible to hide hosted channels.  Thank You.

**Comment by night** [comment]
Playlists are built into the video player and cannot be disabled, sorry. This is because Twitch's video player is encapsulated from modification. Host mode works entirely different from playlists, where another player is loaded on the page just for hosting.

**Comment by Menchii** [comment]
Thank you for checking.  Keep up the great work.  Twitch is so much better with your add-on!!
