### ISSUE TITLE
Skype-esque scrollback

### ISSUE THREAD

**Issue by JasonMartin327** [night/BetterTTV#820]
What I'd basically like is a feature that will let you either scroll back indefinitely through the Twitch chat--even when it's been cleared, or even possibly jump back to a certain date and time and see the messages posted in that time, just like in Skype.  If there's an instance where you want to remember a message someone made for quoting reasons, or perhaps look for an important posted link you missed, this feature would be just perfect for that.

**Comment by night** [comment]
That would require us to store chat logs, which is outside of the scope of what BetterTTV provides. While we offer some history as context when you join a channel, for cost and privacy reasons we only store the past 10 messages.
