### ISSUE TITLE
Better Twitch TV Channel Emotes 

### ISSUE THREAD

**Issue by xxsonicdevilxx** [night/BetterTTV#823]
Everytime i try to do a Channel Emote threw Better Twitch TV I get this Message in Chat "BetterTTV encountered an error reading chat. The developer has been sent a log of this action. Please try clearing your cookies and cache." and the emote doesn't show up on my end, but the streamer says it shows on there end. Cleared Cookies and Cache Twice. Didn't work. Also used 2 different browsers and 2 different computer and the same message pops up.

**Comment by night** [comment]
This was already fixed. You need to refresh the page.
