### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by vil-kautto** [night/betterttv#824]
You probably know about this one already, the last line in the chat sometimes shows only half of the message.
![ss 2015-11-16 at 10 15 49](https://cloud.githubusercontent.com/assets/11096385/11193561/fafe36e8-8caf-11e5-93f5-eec309463eba.png)

**Comment by Ghosttt1** [comment]
Anyone know how to fix the bttv tool bar bug, its not showing up and ive done everything to bring it back
