### ISSUE TITLE
Ping support and Split chat for Whispers 2.0

### ISSUE THREAD

**Issue by taylorsamy** [night/BetterTTV#825]
Can you add ping support and split chat for the new whisper chat boxes?

**Comment by voloshink** [comment]
Ping support will probably come later in the beta, the current implementation makes it kind of difficult to avoid pointless or double pings. Haven't looked into split chat yet.

**Comment by GavoTrav** [comment]
@night @voloshink would something like prepending the "whisper number" to the title be possible for now?

something like this work? `document.title = "(1) " + document.title;`
