### ISSUE TITLE
Add a channel's enabled BTTV emotes to the emote list in the chat box.

### ISSUE THREAD

**Issue by MatthewLyonAnimations** [night/BetterTTV#827]
Right now, it looks like the only way to find out what BTTV emotes are enabled on a channel is to look them up on the BTTV website (manage.betterttv.net/channels/[CHANNEL NAME]/emotes). A feature that would be nice to have would be to add a channel's enabled BTTV emotes to the list that becomes visible when you click on the smiley face in the chat message box, possibly as a separate category from the Default and Channel Subscriber emote lists.

**Comment by night** [comment]
Enable "Emote Menu" in the BetterTTV Settings. A new icon will show below chat, which is an emote menu showing both BetterTTV and Twitch emotes (and allowing you to favorite and hide emotes).
