### ISSUE TITLE
Messages - button + notifications

### ISSUE THREAD

**Issue by pczelda** [night/BetterTTV#828]
1) The button to view your Twitch messages (looks like an envelope) doesn't show up in the left sidebar when it's minimized, so you have to unminimize it and cause the Twitch stream video to shrink every time you want to view it. There's plenty space on the left sidebar for one more icon when minimized, so I believe it should have it.

2) Notifications you received a Twitch message while you're in a Twitch stream don't last very long on the screen. I think they should last twice as long, or even better, give plugin users the option of making it last longer if they like how it is, or want to set it for different time lengths.

3) In a side idea, notifications from people using @ to talk to you  in chat could be a different color than ones you use @ for to talk to other people. Maybe even let plugin users choose their own colors from a set group.

**Comment by night** [comment]
> 1) The button to view your Twitch messages (looks like an envelope) doesn't show up in the left sidebar when it's minimized, so you have to unminimize it and cause the Twitch stream video to shrink every time you want to view it. There's plenty space on the left sidebar for one more icon when minimized, so I believe it should have it.

I believe messages will be going away in favor of whispers/conversations sometime in the future, considering Twitch doesn't have messages in the mobile app but is adding whispers/conversations.

> 2) Notifications you received a Twitch message while you're in a Twitch stream don't last very long on the screen. I think they should last twice as long, or even better, give plugin users the option of making it last longer if they like how it is, or want to set it for different time lengths.

Are you using the Desktop Notifications option? What browser are you using? Those last 10 seconds, which should be plenty long for a notification. There might still be a Firefox-only issue where you can't control how long notifications last.

> 3) In a side idea, notifications from people using @ to talk to you in chat could be a different color than ones you use @ for to talk to other people. Maybe even let plugin users choose their own colors from a set group.

This is already requested at #237

**Comment by pczelda** [comment]
1) As long as there's still a private option to talk to people in the long-term sense and my old messages don't get deleted, I suppose that's fine.2) I was talking about the standard notifications that Twitch does when you get a new private message. I haven't tried notifications with the plugin yet. 


    On Sunday, November 22, 2015 11:24 AM, Night <notifications@github.com> wrote:
 

 
1) The button to view your Twitch messages (looks like an envelope) doesn't show up in the left sidebar when it's minimized, so you have to unminimize it and cause the Twitch stream video to shrink every time you want to view it. There's plenty space on the left sidebar for one more icon when minimized, so I believe it should have it.
I believe messages will be going away in favor of whispers/conversations sometime in the future, considering Twitch doesn't have messages in the mobile app but is adding whispers/conversations.
2) Notifications you received a Twitch message while you're in a Twitch stream don't last very long on the screen. I think they should last twice as long, or even better, give plugin users the option of making it last longer if they like how it is, or want to set it for different time lengths.
Are you using the Desktop Notifications option? What browser are you using? Those last 10 seconds, which should be plenty long for a notification. There might still be a Firefox-only issue where you can't control how long notifications last.
3) In a side idea, notifications from people using @ to talk to you in chat could be a different color than ones you use @ for to talk to other people. Maybe even let plugin users choose their own colors from a set group.
This is already requested at #237—
