### ISSUE TITLE
Odd coloration bug with username

### ISSUE THREAD

**Issue by stdscatchemall** [night/BetterTTV#831]
![Weird Bug](http://stdscatchemall.com/Screenshots/2015-11-22_17-34-14.jpg)

The background color of the username in the top left is miscolored from the background.

An inspect element confirms it's from BTTV and not FFZ (Both are installed)

**Comment by night** [comment]
Not our bug, since we don't recolor the left sidebar

**Comment by stdscatchemall** [comment]
The F12 inspect on it shows that the color is toggled by BTTV css... 

![CSS On](http://stdscatchemall.com/Screenshots/2015-11-22_17-46-28.jpg)
The CSS is on as you can see

![CSS Off](http://stdscatchemall.com/Screenshots/2015-11-22_17-46-45.jpg)
Now I toggle it off and the bar goes back to normal...
