### ISSUE TITLE
Chat can't reconnect.

### ISSUE THREAD

**Issue by TigOleBitty00** [night/BetterTTV#833]
Every time i try to go in a stream and say something in chat is says,"Sorry, we were unable to connect to chat. Reconnecting in 2 seconds." I don't know if its BetterTTV or just Twitch itself, but would appreciate any help. Thank you.

**Comment by voloshink** [comment]
It's usually not bttv, sounds like you might be locked out for sending messages too quickly, try disabling bttv

**Comment by TigOleBitty00** [comment]
It still says the same thing.

**Comment by voloshink** [comment]
then you are probably just locked out, give it a few hours
