### ISSUE TITLE
Viewer list is very hard to read on FireFox

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#837]
here is a pic
![untitle5d](https://cloud.githubusercontent.com/assets/6820014/11387132/b5ad5410-92f5-11e5-9ea2-73ae1da6f803.png)  Chrome is fine, white text with the dark chat, but Firefox is dark gray on a little less dark gray

**Comment by conceptionals** [comment]
Hmm just checked what it looks like for me, and I have the same scroll-bars on the bottom and right, but the text color of the usernames isn't black, its a purple color. (screenshot below) However the text color turns white when in theater mode, which I believe is what it's suppose to be (second screenshot). Also after playing around with it I seem to get the dark text color (like the one you have) when I enable Blue Buttons, but that again changes to white when going into theater mode.

![8f5437904fa66c6e7367cafee10486bf](https://cloud.githubusercontent.com/assets/13137308/11387321/04dbb664-92ef-11e5-9566-a3d60a030775.png)
  
![cbf264373bf374f83e9c6489509eeaea](https://cloud.githubusercontent.com/assets/13137308/11387364/4fa04b92-92ef-11e5-9098-e4413d34100d.png)

**Comment by thinkpad4** [comment]
Yeah I have blue buttons on

**Comment by conceptionals** [comment]
This seems to have been fixed now, and yeah it was a Twitch bug, not BTTV.
