### ISSUE TITLE
Usernames becoming unclickable with Google Translate.

### ISSUE THREAD

**Issue by Apolloftw** [night/BetterTTV#838]
Usernames become unclickable when using google translate from the Chrome Browser 
To the usernames clickable again, you have to re-translate the page and click show original.
http://imgur.com/a/YKX2F (This album will be edited to contain only current bugs with BetterTTV).

**Comment by night** [comment]
I'm not sure how we could fix this, sorry. It's not really a bug with our code at all. If you're trying to translate, use BTTV's click-to-translate instead.
