### ISSUE TITLE
viewers count in theater mode

### ISSUE THREAD

**Issue by biji1** [night/BetterTTV#839]
Hello, i wonder if it's possible to add the viewers count when we are in theater mode.

Like this: http://imgur.com/AYaeNbR

**Comment by night** [comment]
We are not considering adding a viewer count to theater mode since it ruins the immersion. If you want to see stream stats, minimize the left sidebar instead.

**Comment by biji1** [comment]
I don't see any left sidebar. I took a random screen to explain my idea, but you can consider adding the view count on mouse hover. For example, you have the label "LIVE" on top right theater when we put the mouse on the screen. It will be nice to also have the count beside it.
