### ISSUE TITLE
How about a Link banner

### ISSUE THREAD

**Issue by Azumaluza** [night/BetterTTV#844]
Ej, Imagine forsen chat, starting to link all the gore and disgusting links, How about a chatbox that pops up, you enter a link and that link won't show up again on chat. Kinda minimizing that spam.

**Comment by voloshink** [comment]
You mean like the blacklist feature that we already have?

**Comment by Azumaluza** [comment]
Didn't sere the option, after googling it found it. Sorry for the troubles...
