### ISSUE TITLE
[Feature Request] Add Discord Integration

### ISSUE THREAD

**Issue by Reaverblade** [night/BetterTTV#849]
Discord is a relatively new Voice/Text chat service that seems to be gaining popularity among streamers.
It may be wise to add some integration, like being able to tie into the streamer's Discord server and show the chat from there, or even tie into the voice chat, so the streamer could voice chat with viewers.

Discordapp.com is the site for this service.

**Comment by night** [comment]
We are considering embedding Discord's iframe widget within panels below streams, but the last time it was looked into it appeared to be a bit complex to do (because of the sorting of panels). I may revisit it when I get more time, since I am very much a fan of Discord.

**Comment by Reaverblade** [comment]
Well, I was thinking of arranging it like chat. Here are my ideas as mock-ups:
https://www.dropbox.com/s/i0lsus2l3sy0d2t/DiscordLowerRight.png?dl=0
https://www.dropbox.com/s/lvndpd4j058fnqh/DiscordUpperRight.png?dl=0

**Comment by night** [comment]
Discord can make a Twitch Extension if they want
