### ISSUE TITLE
Twitch Notify

### ISSUE THREAD

**Issue by DarthHaven** [night/BetterTTV#850]
I leave a tab up of someone I'm following so I would know when they are online, but is there a way to turn off the whole "someone subscribe to this streamer" notification in the chat when they are hosting someone?

**Comment by night** [comment]
There's not a way to turn that off currently. Is there a reason you aren't using our desktop notifications instead? You can then just leave up the following directory and get notified when a stream you follow goes live. It's much more reliable and less resource intensive than a channel page remaining open (ie flash player is not running).
