### ISSUE TITLE
pin highlighted messages

### ISSUE THREAD

**Issue by moistmann** [night/BetterTTV#852]
not so much as adding a new feature as adding more functionality to the already done "pin highlighted messages" option, I mod a rather big channel but also frequent many others as a viewer and I have many highlighted words like "hi" and "hello" among many other variants and was wondering if you would be able to add something like a changeable limit on the amount that shows at the top of the screen, I believe its at 10 right now but as I use a 4K screen I can fit 2 to 3 times as many there without it affecting what I can read in chat and as I can get a lot of highlights quickly I might miss a few more important highlights when I get too many at once (I love that you have it at all and its probably one of my more liked features) while on some of the smaller channels which I often watch on my smaller screens 10 can feel like too much at times and I am usually doing something where I can't access the chat (eg. playing a full screen game) so was wondering if you could add like a slider to change the amount that can be shown up the top, wouldn't need ridiculous amounts but it would be nice to double it for some channels when I am actively modding and lowering it for others

I would also love the addition of being able to save settings for specific channels, like having global settings that are used unless you have some local settings for specific channels, this would allow me if you added the first suggestion to be able to say make the default highlights up the top as 20 for actve modding channels and 5 for non modding channels, as well as adding the potential of having different highlight words for different channels, among many other options.

just my suggestion either way if any of its implemented in any way or not I love your work and think you have made a wonderful piece of code here :D

**Comment by night** [comment]
Adding a setting for max pinned messages is already internally planned pending the settings overhaul.

Per-channel settings do not really make sense for us, since settings are stored in localstorage that people frequently clear (we would end up getting angry users who had all their precious settings data lost when they cleared cookies). If/when we ever do cloud-based settings storage, this is something only then we would look into and consider.
