### ISSUE TITLE
Unable to remove profanity filter from Twitch chat

### ISSUE THREAD

**Issue by pooiyx** [night/BetterTTV#853]
Hi. I have already checked the box "Opt out of globally banned words filter" in my Twitch account settings, but profanity is still filtered for me and I see all filtered words as "***". 
Solving this problem is the reason I installed the BTTV extension on my chrome. But BTTV doesn't seem to help with this because profanity is still filtered for me regardless. 
Please help me solve this problem asap. 
Thanks.

**Comment by voloshink** [comment]
Is the problem happening in a specific channel?

**Comment by pooiyx** [comment]
Nope, this problem happens in all the channels I've been watching.
Examples:
http://www.twitch.tv/woodenpotatoes
http://www.twitch.tv/killchain
http://www.twitch.tv/mattvisual

**Comment by night** [comment]
When you opt out of the banned words filter, that setting applies to YOUR channel. Twitch filters profanity on a per-channel basis serverside, so there's no way to disable it.

**Comment by pooiyx** [comment]
But I've tested this with 2 other people and they both can see all words
unfiltered.

**Comment by night** [comment]
Well BetterTTV does not filter profanity, nor is it even possible for us to unfilter profanity (as was stated, Twitch filters profanity on a per-channel basis serverside). For more information on Twitch's profanity filter or to report issues with it, you should reach out to Twitch support instead: http://help.twitch.tv

**Comment by Spifariffic** [comment]
I was having this issue too. Here's what fixed it for me:
- go to a stream channel
- find the little gear icon (for me, on mobile, you have to poke the screen to show things like clipping and subbing, the gear is next to the sub button)
- click the gear to bring up settings
- under 'chat filters' tap "enable filtering in chat" (will bring up more options)
At this point, you can either turn them off entirely or pick which things you don't want to see in the sliders below.
Hope this helps.
