### ISSUE TITLE
Hide chat box & slow scrolling chat

### ISSUE THREAD

**Issue by Kasero** [night/BetterTTV#854]
Hello,

I like to watch twitch in Theatre Mode + F11 + Dark mode + Split Chat + Hide Group Chat (http://i.imgur.com/j1xQSWO.png) 

If the chat itself could be slow scrolling for each new line for smoother reading and if the chat box could disappear when not hovered over, it should look quite seamless together. As I personally would like to just have the stream and chat on the screen when I'm just watching and not chatting.

Cheers, Kasero

**Comment by voloshink** [comment]
Sounds like a neat idea, but i don't think it's in demand enough to warrant adding. The settings space is getting quite expensive, it's very cluttered as is.

**Comment by night** [comment]
Large streams have chats messaging rates so high that smooth scrolling doesn't really work too well. Smooth scrolling also tends to be more resource intensive, and even at a slower rate it could make the video player lag on slower machines.

We do realize that you might want to have a more streamlined chat view full screen, which is the same feature request as #342. For this reason, I'm going to close this as a duplicate.
