### ISSUE TITLE
Pinning highlighted messages

### ISSUE THREAD

**Issue by LethalBro** [night/BetterTTV#855]
I adore this feature's functionality, but having to manuelly remove the pinned messages can become a chore. So i was thinking if there could be added a possibility to let the user define a length of time, in seconds, for how long the pinned messages stay pinned.

**Comment by voloshink** [comment]
Dupe of #806

Yeah, i agree 100%. I wanted to wait for the new settings to add it, but it seems like it's taking way too long, so i'll try and add it soon.
