### ISSUE TITLE
It keeps saying I have no email address associated with my account when I do

### ISSUE THREAD

**Issue by wykstrom** [night/BetterTTV#856]
Yesterday I added some BTTV emotes and today I tried to add a few more and it is telling me I have no email address associated with my account.  I tried relogging in and reverifying my email address and neither seem to fix this bug.

**Comment by night** [comment]
Unfortunately due to a Twitch API issue emails are not being returned by their API. You will need to wait for them to resolve the problem.

**Comment by wykstrom** [comment]
Thank you!

On Mon, Dec 14, 2015 at 6:58 PM, Night <notifications@github.com> wrote:

> Closed #856 <https://github.com/night/BetterTTV/issues/856>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/night/BetterTTV/issues/856#event-491724278>.
>



-- 
-V-
