### ISSUE TITLE
[Feature Request] Sub System using Gamewhisp/Patreon

### ISSUE THREAD

**Issue by BDRMrTBag** [night/BetterTTV#857]
I've been using Ankhheart's: Ankhbot R2 lately and seeing it has a way for people to be recognised as subscribers outside of Twitch, I was thinking it would be a good idea to let Streamers who aren't partnered use some sort of Sub System in BTTV that allows BTTV users who've subbed, to have a little sub logo to their names just like Twitch's Sub System, so once the subscription is complete on Gamewhisp or Patreon, the streamer adds the name of the account to the Sub System and they get a subscription logo!

**Comment by night** [comment]
Unfortunately we don't want to step on any toes at Twitch by literally duplicating their subscription feature, so we are not willing to support this, sorry.
