### ISSUE TITLE
On/off Whisp chat 2.0

### ISSUE THREAD

**Issue by Pikutinho** [night/BetterTTV#858]
Hi, i dont know if you can do it or not, but please could you guys try a feature that disable the whisp chat 2.0 left side from the main chat? Please :)

**Comment by voloshink** [comment]
I'm working on fixing the disabling whispers feature right now

**Comment by Pikutinho** [comment]
Wow, thank you for the fast answer, hope to see it soon :)

**Comment by voloshink** [comment]
Fixed in 09927de
