### ISSUE TITLE
BTTV Suggestion (Ignore Hotkey)

### ISSUE THREAD

**Issue by ScottieS** [night/BetterTTV#859]
Just a hotkey to add people to ignore list.

**Comment by voloshink** [comment]
How often do you have to ignore people?

**Comment by ScottieS** [comment]
I've been watching channels (GoDaZeD) and I just ignore the spammers so that I can talk to the real chat.

**Comment by night** [comment]
Unfortunately you won't get far doing that, since in larger channels there is usually thousands of people spamming. In large channels, you are ultimately at the mercy of the channel owner. Unless they have a chat bot to enforce rules against spam, the channel will be filled with spam.
