### ISSUE TITLE
Chrome dark mode is bugging the settings menu

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#860]
Dark mode does this
![untitle5d](https://cloud.githubusercontent.com/assets/6820014/11837935/dde1b896-a3b1-11e5-802a-02dde1a44d72.png) I turn that off and the text is normal again.  Just started in the last few hours

**Comment by odivinewraitho** [comment]
http://i.imgur.com/5Jr5AY6.png I am also getting this same issue. turning dark mode off does resolve the issue for me. http://i.imgur.com/ot5mxcq.png

**Comment by teak** [comment]
This issue should now be fixed.
