### ISSUE TITLE
Changing the Font Size!

### ISSUE THREAD

**Issue by xxsonicdevilxx** [night/BetterTTV#861]
I notice last night that my font size changed in chat on twitch.tv and I have the option to change on font size on google chrome, but when I click on the A+ to make it bigger it acts likes the font is getting bigger, but the font in the chat is still the same size. Because it is hard to read chat when it is in small font just like in the Picture.
![options](https://cloud.githubusercontent.com/assets/15862991/11844963/15353474-a3d7-11e5-80fa-f8112a5cd3d0.png)
![chat](https://cloud.githubusercontent.com/assets/15862991/11845035/6967aed2-a3d7-11e5-8522-ed102d7cc145.png)

**Comment by thinkpad4** [comment]
Is it possible to make the font the size it was before?  chat is so tiny now and the jtv badges make the tags very tiny
![untitle5d](https://cloud.githubusercontent.com/assets/6820014/11866104/d4b0fe56-a476-11e5-922c-6abeab17165a.png)

**Comment by MatleyFoSho** [comment]
Would be nice to be able to chose the font size manually

**Comment by night** [comment]
Changing the font size is something requested already in #57. We are working to fix the CSS soon, and may provide an option for changing font size similar to the one pictured above (that appears to be added in an extension that's not BetterTTV).

**Comment by zikhem** [comment]
Hello, I got a problem... I was experimenting and changed my font size WAY TOO BIG and cant even acces the part to write in chat (nor the settings) so I cant change it back, Help please, I wanted to use the inspect page thingey commands but I couldnt...
