### ISSUE TITLE
Auto mute hosted channels

### ISSUE THREAD

**Issue by moistmann** [night/BetterTTV#863]
I believe a feature where it mutes any hosted channels (the feature probably turned off as default) would really be appreciated by many people, especially for those that leave streams open for hours after they have finished. 

No idea how easy it would be to do as I do not know much of twitchs API, and if its on the works/already done or even known but not feasible then sorry for wasting your time :)

**Comment by night** [comment]
You can disable host mode already within the BetterTTV Settings.
