### ISSUE TITLE
Support for native HTML5 streaming in Safari

### ISSUE THREAD

**Issue by night** [night/BetterTTV#87]
Hi,

Just found your awesome extension and absolutely love it. One thing that drivers me nuts with Twitch is the fact it only works with Flash player, which turns my laptop into a small furnace thanks to Flash's stupid CPU utilisation.

Thankfully Twitch provides a beta URL for HTML5 support which uses about 1/4 of the CPU that flash does. The URL for this is http://twitch.tv/<streamname>/hls

It would be AMAZING if there was an option in BetterTTV that enabled this by default and replaced the (shitty) Flash player with the shiny new HTML5. Yes, you can browse to the URL manually but you don't get chat or any of the other 'chrome' on the page so you have to switch between HTML5 and the 'normal' page.

**Comment by pettenstein** [comment]
Any word on this? I would love the possibility to bypass the terrible Flash player!

**Comment by night** [comment]
Twitch is working on an HTML5 player. Since this is Safari-only, it's not worth the time.
