### ISSUE TITLE
GIF Emotes Don't Always Work

### ISSUE THREAD

**Issue by CaseyStellar** [night/BetterTTV#871]
As the title says ^ They've only worked once of recent memory..

**Comment by voloshink** [comment]
Do you have them enabled in the settings?

**Comment by CaseyStellar** [comment]
Yes.

**Comment by voloshink** [comment]
Any particular emotes that are not working?

**Comment by CaseyStellar** [comment]
All of the GIF emotes. I see people type them in all the time but, they never translate to emotes for me in chat. They just stay as plain text.

**Comment by voloshink** [comment]
Could you please export your bttv settings and post them here?

**Comment by CaseyStellar** [comment]
This site doesn't seen to allow uploading the file but, this is what's shown when opened with Notepad++:


{"anonChat":false,"alphaTags":false,"autoTheatreMode":true,"bttvEmotes":true,"bttvGIFEmotes":true,"showBlueButtons":true,"chatImagePreview":true,"darkenedMode":true,"showDirectoryLiveTab":true,"desktopNotifications":true,"dblclickTranslation":false,"directoryPreview":true,"disableHostMode":false,"disableUsernameColors":false,"disableWhispers":false,"dblClickAutoComplete":true,"embeddedPolling":true,"clickTwitchEmotes":false,"showFeaturedChannels":false,"followingNotifications":true,"groupChatRemoval":false,"hideSpam":true,"hostButton":false,"showJTVTags":false,"showMonkeyEmotes":false,"modcardsKeybinds":true,"alertOtherMessages":true,"pinnedHighlights":false,"highlightFeedback":true,"hideDeletedMessages":false,"customTOShiftOnly":false,"showDeletedMessages":true,"splitChat":false,"tabCompletionTooltip":false,"timeoutHighlights":false,"blacklistKeywords":"","chatLineHistory":true,"chatWidth":340,"consoleLog":false,"flipDashboard":false,"highlightKeywords":"caseystellar","scrollbackAmount":150}

**Comment by DragonQuiz** [comment]
can you open bttv in a different browser to see if gifs will work?

**Comment by CaseyStellar** [comment]
I currently use Chrome but, I'll test in Firefox later tonight and post back.

**Comment by voloshink** [comment]
Also, check if you get any bttv related errors in the chrome console when someone uses a gif emote

**Comment by CaseyStellar** [comment]
I don't see anything about an error when people type them in.. They just appear as plain text, not as the emote..

**Comment by voloshink** [comment]
I mean in the chrome console, press F12 to open it

**Comment by CaseyStellar** [comment]
Ohh okay. Wasn't exactly sure that's what you meant. How would recognize the error if there is one?

**Comment by voloshink** [comment]
it would be a red line and it would have "betterttv.js" on the right

**Comment by CaseyStellar** [comment]
Okay. I'll keep an eye out.

**Comment by CaseyStellar** [comment]
Hmm.. Seems like Ghostery blocks something with the gif emotes..

**Comment by voloshink** [comment]
Does disabling it fix the issue?

**Comment by CaseyStellar** [comment]
Yes. Not worth the trade-off though.. Any suggestions? I'll have to send Ghostery an e-mail mind you.

**Comment by voloshink** [comment]
Once i have a chance i'll install it and see if i can figure out the issue, thank you for providing the info

**Comment by CaseyStellar** [comment]
Okay. I'll get to sending Ghostery that e-mail and see what they say..

**Comment by CaseyStellar** [comment]
Also, I don't get any extra emotes when I enable bttv emotes and GIF emotes.. I can use them and I can see them but, they aren't listed in my emote menu..

**Comment by DragonQuiz** [comment]
What do you mean by "I don't get any extra emotes" ? Like the bttv emote selection or the channel ones?

**Comment by CaseyStellar** [comment]
The bttv emote selection. But, it looks like it's working now. Strange day for Casey indeed.

**Comment by night** [comment]
I'm glad you were able to get them working.

**Comment by CaseyStellar** [comment]
Any status with Ghostery breaking the GIF emotes?

**Comment by night** [comment]
You would need to reach out to Ghostery if they are breaking our extension. Since they specialize in content blocking, they would be responsible for fixing the issue.

**Comment by CaseyStellar** [comment]
Alright. I sent them an e-mail.. Hopefully they'll write back soon.
