### ISSUE TITLE
FFZ emotes support?

### ISSUE THREAD

**Issue by kat1337** [night/BetterTTV#874]
You can get BTTV emotes and gifs on FFZ can we we get FFZ emotes?

**Comment by voloshink** [comment]
No

**Comment by WolfyyTV** [comment]
No

**Comment by night** [comment]
Since FrankerFaceZ is compatible with BetterTTV it doesn't really make sense for us to add their emotes at this time. If we get multiple requests for this it's something we may consider, however.

**Comment by faiizow** [comment]
+1 for this idea.

**Comment by Cyberbeni** [comment]
+1 would like to have this

**Comment by Shelmor** [comment]
Well I may be kind of late here but defenately vote for this feature. +1
