### ISSUE TITLE
Auto-hide chat or hide all emotes

### ISSUE THREAD

**Issue by zeroshift0** [night/BetterTTV#875]
Twitch channels with high chat activity affects my computer and network performance.  It's a minor inconvenience to have to manually hide the chat or check to be sure it is hidden each time I visit Twitch.  I am referring to the 'Hide Chat' option in the Chat Options, not simply clicking the tab on the top right, as doing this still leaves the chat running in the background.

Hiding all emotes is a personal preference that I'd like considered but can live without.

**Comment by night** [comment]
High chat activity would hardly affect network performance, so I doubt that statement entirely.

As for affecting your computer when the right sidebar is closed, I pushed a fix to prevent that.
