### ISSUE TITLE
Feature Request - moveable emotes

### ISSUE THREAD

**Issue by Jwh1ttemore** [night/BetterTTV#877]
It would be cool if we were able to drag and drop our emotes into a custom order, for example I would want ;p illuminati and sloth at the top.
Thank you

**Comment by night** [comment]
Unfortunately all emotes are in alphabetical order, but you can set a list of favorite emote in our emote menu. Any feature requests for the emote menu itself should be posted to https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/issues
