### ISSUE TITLE
Missing BTTV Emote Menu

### ISSUE THREAD

**Issue by Soy0** [night/BetterTTV#878]
Not sure what happened but I am missing the 'smiley' button to see all the bttv emotes....

I can still see all emotes and gif emotes, and they are turned on in my settings panel

![wtf](https://cloud.githubusercontent.com/assets/16493617/12057418/72786c84-af06-11e5-87f9-b31948757fb1.PNG)

**Comment by Soy0** [comment]
I have deleted the extension and re-added it as well

**Comment by night** [comment]
You can enable the Emote Menu in the BetterTTV Settings.

**Comment by Soy0** [comment]
wow. skimmed right over that one....my fault.
