### ISSUE TITLE
Channel emotes

### ISSUE THREAD

**Issue by SteelDeoxys** [night/BetterTTV#879]
When I downloaded betterTTV everything worked except the thing I downloaded it for, betterTTV emotes for channels, I can type the emote out but there's no tab for me to click on to use them like the ":)" for normal emotes and the FFZ emotes.

**Comment by cletusc** [comment]
Enable the "Emote Menu" setting.

**Comment by voloshink** [comment]
Wow you're fast, i was gonna type that

**Comment by SteelDeoxys** [comment]
thanks for you help
