### ISSUE TITLE
Link Unshortening

### ISSUE THREAD

**Issue by night** [night/BetterTTV#88]
It would be useful to see the Top Level Domain that a shortened url is pointing to.

example view:

bit.ly/BLAH <google.com>

unshorten.me could be used for this, API has a 100k per IP/API_KEY per day limit.

Optionally a cached list on a night server to prevent 1000+ users in chat all unshortening a link at the same time?

**Comment by amamut** [comment]
@night Why use a third party API when writing a quick GET method in node is trivial (node-curl). You can have it cache on your servers automatically instead of sending a second call. Just thinking out loud here.

**Comment by vendethiel** [comment]
node-curl on bttv?

**Comment by night** [comment]
I didn't make this request, it was just imported from Redmine. Due to CORS in browsers, we would have to use something serverside though.

**Comment by amamut** [comment]
I meant using node-curl on a node js server. Or using curl on any back-end server.

**Comment by metarmask** [comment]
> Due to CORS in browsers, we would have to use something serverside though.

Chrome has a way to make cross-orgin requests: [https://developer.chrome.com/extensions/xhr]("Cross-Origin XMLHttpRequest - Google Chrome")
