### ISSUE TITLE
View all following channels 

### ISSUE THREAD

**Issue by trevbattaglia** [night/BetterTTV#880]
Hey,

I love your extension for twitch. I can't watch without it. 

So I follow a lot of people on twitch, When most of them are online it gives me a view all button so I can see all of them. After you hit it then all the people I follow are listed. I was wondering if you could make something that shows them all by default?

Keep up the good work, Trevor Battaglia

**Comment by night** [comment]
There already is... "Default to Live Channels" in the BetterTTV settings...

**Comment by trevbattaglia** [comment]
RIP. Thanks for letting me know XD Sorry about that
