### ISSUE TITLE
Twitch Emote Issues

### ISSUE THREAD

**Issue by PulseEffects** [night/BetterTTV#882]
For some reason, only when BTTV is installed, I can't see certain emotes in chat. I'm having a few issues with Sub emoticons as well, any suggestions? http://puu.sh/mfARp.jpg

**Comment by night** [comment]
Twitch bug, not our bug..

**Comment by PulseEffects** [comment]
I'm literally only having these issues though whenever I have Better Twitch TV installed though...

**Comment by night** [comment]
You only think that these only happen with BetterTTV installed. The fact is that they do not. It's a CDN issue with Twitch's CDN, and is not something we can fix.

**Comment by PulseEffects** [comment]
Then why is this only happening on my end. Anytime I use these certain emoticons, everyone else can see them except me. And that's only when I have BTTV installed.

**Comment by night** [comment]
It's not only happening on your end. It's happening to everyone. As was stated, it's an issue with Twitch's CDN.

**Comment by PulseEffects** [comment]
Alright, well thank for your time then.
