### ISSUE TITLE
mods/subs appearing as purged with /localsub mode on. 

### ISSUE THREAD

**Issue by Apolloftw** [night/BetterTTV#885]
This bug appeared thanks to AGDQ and the amount of people be purged.
http://i.imgur.com/IsjKkFx.png
With the amount of people being purged, it shows mods and subs appearing as if they have been purged but aren't because the person's previous message wasn't <message deleted>.
This also could be a chrome related error.
This is affecting staff as well: http://i.imgur.com/l7VxhUO.png

**Comment by night** [comment]
We reverted the changes to the system. Let us know if the issue persists.
