### ISSUE TITLE
extra "x has been timed out" messages.

### ISSUE THREAD

**Issue by CrosseyeJack** [night/BetterTTV#886]
commits a3b4f39 & 2413403 added "user has been timed out" messages even if they are omitted from the official client.

Long story short. Got some code that tries to head off Link Spammers and other annoying chat bots before they get to the channel. In Official Twitch Chat and BetterTTV before these commits if the user had not spoke in chat when being TO'ed no message is/was displayed to users.

Since this commit(s) those TO's are now displayed in BetterTTV but not in the Official client or Commit b41eb34

Compare these chats. Left is a3b4f39 and right is b41eb34
![screenshot from 2016-01-03 23-35-15](https://cloud.githubusercontent.com/assets/1392296/12081504/f8085cd2-b272-11e5-9545-04d00df4f07f.png)

**Comment by night** [comment]
https://github.com/night/BetterTTV/commit/a3b4f3958c7ba9c832d73c9ca32fa3066bb882e8#diff-74639eaa1c966500ed446fe62cd925f4R593

That line should prevent users who haven't posted from having a timeout message. Please double-check that this doesn't work.

**Comment by CrosseyeJack** [comment]
Getting the Error
betterttv.js?0.1078709124121815:790 Uncaught SyntaxError: Unexpected token !

which is
```javascript
if (!$chatLines.length) return;
````

Commented out like 790 and got the code to run locally. Anyways...

Slapped in a Console.Log to see what is going on. 

````javascript
$chatLines = $(queuedMessages.concat($chatLines));
console.log($chatLines);
````

which the following output in FF
````
[e.fn.init[0]]
0: e.fn.init[0]
context: document
length: 0
prevObject: p.fn.init[1]
selector: ".chat-line[data-sender="jam_playz"]"
__proto__: p[0]
length: 1
__proto__: p[0]
````

Even if the user has not spoken in the channel they are getting a $chatLines.length of 1 so the "if (!$chatLines.length) return;" check is still passing.

**Comment by night** [comment]
This should be fixed now. Thanks.

**Comment by CrosseyeJack** [comment]
Just confirming that it does appear to be fixed.

Many thanks.
