### ISSUE TITLE
Filter non-subscribers and/or non-turbo users on chat

### ISSUE THREAD

**Issue by mkody** [night/BetterTTV#887]
When watching a popular stream, the chat will obviously become quite _spammy_, but I want to keep reading some reactions and important message that could be sent.

A nice new feature will be to hide message from non-subscriber and (or) non-turbo users (but keep the streamer, moderators and twitch staff).  
Like, if the user has no badges, don't display his message?

Thanks!

**Comment by voloshink** [comment]
Bttv already has a local sub mode. Use /localsub and /localsuboff to toggle it
