### ISSUE TITLE
It doesn't save my settings anymore

### ISSUE THREAD

**Issue by Lightningblade67** [night/BetterTTV#888]
Hello,

I've set up my BTTV but now I want to change a setting back but every time I restart my Firefox it goes back to my older settings. (The setting i want to turn off again is "Default to Live Channels  —  BetterTTV can click on "Channels" for you in the Following Overview automatically").

Thank you in advance.

**Comment by voloshink** [comment]
Make sure the browser isn't set to clear cache/cookies when you close it

**Comment by Lightningblade67** [comment]
Well, like i said it goes back to MY old settings not to the default settings. So it saved my settings in the cookies. But it seems that i can't make permanent changes to it anymore.

**Comment by night** [comment]
Can you export your settings and upload them to https://gist.github.com/ and link them here

**Comment by Lightningblade67** [comment]
Here you are: https://gist.github.com/Lightningblade67/d478d7dd59bd6b7e9e4b (I hope this Link is public) (Also this are the settings that it defaults back to after i closed Firefox)

**Comment by night** [comment]
I don't see any issues with your exported settings. Try clearing your cookies and then importing that settings file and seeing if your issues persist.

**Comment by Lightningblade67** [comment]
Now it goes back to default can't change a single setting. It's probably something wrong with my browser and not with BTTV. I sat my cookie policy to clear all cookies when i close my Firefox but I have twitch.tv as an exception. But now it won't work at all anymore. Do I have to except another site for the BTTV cookie?

**Comment by night** [comment]
I'd recommend disabling clearing cookies on browser close to see if that resolves your problem.

**Comment by Lightningblade67** [comment]
Ok, i found out how to change settings (Strange method): 

You have to set Firefox to save cookies until they expire (Normal Cookie settings) 
Then change the BTTV options
Close and restart Firefox and
Then change the Cookie settings back to clear when Firefox closed (with an Twitch.tv exeption)

Thank you for your fast answers and assistence. Still, I would love you even more if you could find a way to store the settings in the addon itself or in a file on the Computer or smth. (Not that much into programming so i don't know what is possible)
