### ISSUE TITLE
Marked as spammer: <Spam Deleted>.

### ISSUE THREAD

**Issue by OTimmay** [night/BetterTTV#892]
Hi

I believe I've been wrongfully marked as a spammer by BTTV. Apparently my messages show up as "<Spam Deleted>" for those that have activated a certain setting in BTTV (which is quite many people)
Any help will be appreciated :)

(http://www.twitch.tv/otimmay/profile)

Thanks,
OTimmay

**Comment by night** [comment]
https://community.nightdev.com/t/why-are-my-messages-being-detected-as-spam-to-others/7370
