### ISSUE TITLE
DarkenTTV disabling

### ISSUE THREAD

**Issue by Ansem93** [night/BetterTTV#894]
Hi, I don't know why but only the setting of darkenTTV will return on OFF,instead of remain on ON.

**Comment by night** [comment]
Can you elaborate? Your statement does not make sense.

**Comment by Ansem93** [comment]
I mean: BetterTTV seems to doesn't save the settings of only darkenTTV option. All other option are working fine, they keep the settings, but not darkenTTV.
Every time that I change page, or close and reopen the tab, twitch will return white. Still working if I only recharge the page instead.
I think that the fault it's of "twitch now", maybe there is some conflict when I open a stream from this plug in

**Comment by night** [comment]
If you use Firefox and it's configured to remove cookies on close but with an added an exception for Twitch, it appears that the exception system is now broken. If this is the case, you need to disable clearing of cookies on browser close.

If this is not the case for you, try clearing your cookies to reset the BetterTTV settings.
