### ISSUE TITLE
(Suggestion) Stop pause when going to a new channel.

### ISSUE THREAD

**Issue by awesom3pand4** [night/BetterTTV#898]
Twitch has put a new update out; so when you go to a new channel whilst watching a channel it will pause the channel you were originally watching. I don't how you would do this but it would be good to have a feature to prevent this from happening.

**Comment by voloshink** [comment]
Twitch has acknowledged that this is a bug and are working to fix it

**Comment by Decicus** [comment]
For now, most browsers support that you click and drag the channel URL to the "new tab" area to open the link in a new tab without pausing the first stream.
