### ISSUE TITLE
Pinned highlighed messages: Set maximum amount pinned

### ISSUE THREAD

**Issue by Myrathi** [night/betterttv#901]
Currently there is the ability to make pinned messages time out after 1 minute... but it would be really useful to set how many you want pinned.

I use several chat windows while streaming and some are too small to have more than 5 pinned. One is significantly bigger and I could use having ~15 pinned.

**Comment by voloshink** [comment]
I think this is something we should add once the new settings system is added

**Comment by M-archand** [comment]
Has this idea been given any more thought? Been wanting it for a LONG time, would be nice to adjust amount of pinned messages, 10 is too much in my opinion.
