### ISSUE TITLE
BetterTTV not working

### ISSUE THREAD

**Issue by GeZix** [night/BetterTTV#902]
I did the debugging process and this is what I get in my console for chrome. No idea what any of this means. Any help would be appreciated 

EDIT: forgot to add the gyazo link https://gyazo.com/68d64634e55719ca512cd2233bd9e2cb

**Comment by voloshink** [comment]
Having server issues right now

**Comment by night** [comment]
We're not having server issues. Forgive @voloshink and his misinformation.

There's networking issues upstream most likely, but without traceroutes we cannot confirm. All of our servers are operating normally.
