### ISSUE TITLE
Disable... chat history navigation thing?

### ISSUE THREAD

**Issue by radicaled** [night/BetterTTV#909]
I can't find this in the BTTV options dialog: it's the, uh, thing where if you press the up/down arrow while in the chatbox and instead of bringing the cursor up/down a line it seems to scroll through your previous message history.

I'm heavily keyboard driven when I type (to fix typos, rephrase, etc), but the history scroll thing is really screwin' me up. I assume its not a bug, and just a hidden option, so how can I turn it off?

**Comment by voloshink** [comment]
Correct, it's a hidden setting. Type "/linehistory off" to disable the feature.
