### ISSUE TITLE
BetterTTV not working as of Jan. 16th, worked before. (Javascript console errors included)

### ISSUE THREAD

**Issue by RoastyMcToasty** [night/BetterTTV#910]
BetterTTV hasn't been working lately, the CDN is fine, I've checked other extensions and they were fine, then I looked at the Javascript console and there were a lot of errors. They overlap a little so you can see every one so it can be clear. I hope this is enough, thank you for the help.

Here they are:

![screen shot 2016-01-17 at 15 27 44](https://cloud.githubusercontent.com/assets/11619028/12377956/52832658-bd2f-11e5-924a-5d2c662356c2.png)
![screen shot 2016-01-17 at 15 28 15](https://cloud.githubusercontent.com/assets/11619028/12377957/5432fec4-bd2f-11e5-857e-bf440d6447d5.png)
![screen shot 2016-01-17 at 15 28 40](https://cloud.githubusercontent.com/assets/11619028/12377958/555551d0-bd2f-11e5-8e07-ba0109394f92.png)
![screen shot 2016-01-17 at 15 29 01](https://cloud.githubusercontent.com/assets/11619028/12377960/5a392500-bd2f-11e5-83a5-66c2f68ef9a2.png)
![screen shot 2016-01-17 at 15 29 15](https://cloud.githubusercontent.com/assets/11619028/12377961/5e231fd6-bd2f-11e5-847a-7f51e164bef0.png)
![screen shot 2016-01-17 at 15 29 28](https://cloud.githubusercontent.com/assets/11619028/12377962/5f55b53a-bd2f-11e5-91cf-427c95fc70d5.png)

**Comment by cletusc** [comment]
Unless I'm blind, I don't see _any_ messages from BTTV. Disable _all_ extensions except BTTV (this means disable FFZ as well), clear your cache, and try again.

**Comment by night** [comment]
BetterTTV is working most likely. Twitch is testing out SSL for a small amount of users, so your settings probably reset. You would need to go into the BetterTTV settings and retoggle all your settings.
