### ISSUE TITLE
Uparrow in Chat mechanics

### ISSUE THREAD

**Issue by quirxmode** [night/BetterTTV#912]
When you uparrow in the chat input window, per default it brings up the messages you previously posted. However if you composed a multiline message and want to uparrow onto a previous line to edit/fix something then it brings up the previous message and this is really annoying.

I hardly ever use the uparrow-to-previous-message-feature but I often want to edit something in a line above and currently the only way to do that is leftarrow through your whole text until you arrive in the desired line.... Maybe we can get an option changing the uparrow behaviour?

**Comment by MellowNebula** [comment]
Type "/linehistory off" to disable the feature
https://github.com/night/BetterTTV/issues/909#issuecomment-172283502
