### ISSUE TITLE
Feature request: Disable Auto-play on streaming going live.

### ISSUE THREAD

**Issue by krazyito65** [night/BetterTTV#914]
As the title suggest, I would like an option to not have the stream auto-play when it is open in my tab.  I have comcast and they limit my bandwidth, so when a stream starts up (usually my music stream) it wastes bandwidth.

**Comment by night** [comment]
If you use Google Chrome, tabs in the background auto-pause videos and sounds that load when you're not viewing them.

**Comment by krazyito65** [comment]
thats not the case with me.. When the stream restarts it auto plays.  But thanks for the help.
