### ISSUE TITLE
teather mode the text I want to type in chat before sending it is invisible

### ISSUE THREAD

**Issue by chemsed** [night/BetterTTV#924]
Change the color of the text please.

**Comment by night** [comment]
I have no idea what you mean..

**Comment by chemsed** [comment]
The text I'm typing is white on white. I can't see what I'm typing. Louis-Delmont Lafond


 

    Le Dimanche 24 janvier 2016 18h44, Night <notifications@github.com> a écrit :
 

 Closed #924.—

**Comment by night** [comment]
I don't know what "teather mode" is, sorry. BetterTTV doesn't have a "white on white" chat, and prevents white usernames. Unless you have a screenshot of the issue, there's no problem we can replicate.
