### ISSUE TITLE
Whisper error message not shown

### ISSUE THREAD

**Issue by kryogenic** [night/BetterTTV#925]
Whispering a user with private whispers enabled results in the error message appearing at the top of the list of chat messages.

Screenshot: http://puu.sh/mJ5eh/e869acbe46.png

The error should be sent to the whispers box instead.

**Comment by kryogenic** [comment]
BTTV Emotes don't work in whisper boxes either..

Possible duplicate of #825

**Comment by night** [comment]
> BTTV Emotes don't work in whisper boxes either..

This is a caveat to how we modify whisper messages. We did have emotes working, but they broke in December after Twitch pushed their whisper update. Due to the reasoning of why they broke and internal policies with BetterTTV's integration with Twitch, it's not possible to fix at present.

**Comment by night** [comment]
This issue should no longer occur.
