### ISSUE TITLE
Quality Video "Bypass"

### ISSUE THREAD

**Issue by kalarse** [night/BetterTTV#927]
Hello, I am actually unsure if this can be pulled off or not, but for those channels which are not partnered is a pain for not-that-good-connections viewing the streams with source quality, but if there is any way to bypass the restrictions that those kind of streamers (which needs to have at least, and as far as i know, about 40+ viewers) and be able to select from Source, High, Normal, Low and Mobile since entering the stream would be better.

Thanks

**Comment by night** [comment]
Twitch controls video transmuxing on their servers, and we don't have any say in who gets the resolution options, sorry. While it's theoretically possible to transmux streams ourselves, it's extremely costly to do so and we're a free product.
