### ISSUE TITLE
[Feature Request] Viewer count while in Theater Mode

### ISSUE THREAD

**Issue by adispen** [night/BetterTTV#929]
Been messing with this idea for a while since realizing you can't check viewer count in theater mode.  Wrote up some JS that allows you to see the current viewers while moused over the chat header.  When moused over, the title changes to the viewer count, and changes back when you mouse out.  Script is below

```javascript
var chan = $(".chat-header .room-title").text();
$(".chat-header")
.mouseover(function(){
  $(".chat-header .room-title").text(function(){
    return $(".live-count").text() + " viewers";
  });
})
.mouseout(function(){
  $(".chat-header .room-title").text(function(){
    return chan;
  });
});
```

**Comment by night** [comment]
We would rather not clutter the chat UI with elements unrelated to chat. You're welcome to pull request a change adding the count into the video player UI, but I don't believe this is a good solution as-is.
