### ISSUE TITLE
Language Translator 

### ISSUE THREAD

**Issue by suchhatred** [night/BetterTTV#936]
I'm from NA and i watch a lot of German / Korean LoL streams on twitch.tv, but unfortunately most of the time i can't fully understand what's going in chat because i don't speak the language. it would be great if some sort of translator could be implemented into the BTTV setting. That way an abundance of the more diverse streams would be watchable.

**Comment by wallrik** [comment]
Have you tried this option in BTTV settings? or are you looking for something else?
**Double-Click Translation** — Double-clicking on chat lines translates them with Google Translate

**Comment by night** [comment]
While we do have a quick tool to translate single lines, there's no way we can easily translate all chat lines (it's resource intensive and __very__ expensive). If you use Google Chrome you may need to use their page translation feature.
