### ISSUE TITLE
Personal Soundcloud-like chat/comment tracker for VODs

### ISSUE THREAD

**Issue by nickbedo** [night/BetterTTV#939]
Hey folks! I'm really loving BetterTTV. I pair it up with ReChat and it's a great experience!

Honestly not sure if this is a better suggestion for you or the ReChat folks but I would really love some sort of tracker in the VODs similar to Soundcloud, where you can see comments attached to timestamps. To be clear - this is for people to go back to vods and see when they we participating in chat. Sometimes I'll pop into chat for a while and ask questions or make jokes, and the streamer responds; I would love a way to go back after the live stream and find that moment in the VODs, but right now the only way to do that is to scrub through and hope to find that one single moment. If there was a highlighted bar or something letting me know of the moments where I left a comment in chat, that would be super useful to me :)

Thanks!

**Comment by night** [comment]
So BetterTTV doesn't keep logs of chats like ReChat does, nor do we plan to, sorry. There's numerous privacy violations with making chat that accessible, not to mention that storing data like that is technically in violation of Twitch's API Terms of Service (which states that user data **not** created by your application may not be stored for longer than 24 hours).
