### ISSUE TITLE
Slow, Sub-Only, and R9K quick-action buttons

### ISSUE THREAD

**Issue by ghost** [night/BetterTTV#942]
BTTV currently shows icons for each of slow mode (with actual value), sub-only mode, and R9K Beta mode. It would be useful for moderators to have a way to quickly disable/enable any of them. Not sure what the UX would be; always show the icons in the upper-right for the three modes (with inactive modes greyed out), and clicking one of the icons toggles the state of that mode?

Specific use case: A streamer I moderate for normally has R9K mode enabled, slow mode enabled, and sub-only mode disabled. For short periods, he will quickly do the following: turn off R9K mode, turn off slow mode, turn on sub-only chat. (Basically, for subscriber-only giveaways and/or "sub games".) With my proposal, this would reduce typing "/slowoff<enter>/r9kbetaoff<enter>/subscribers<enter>" (and typically another "/subscribers" and/or "/r9kbetaoff" because of a glitch that nullifies one of them >_<) down to three mouse clicks.

**Comment by night** [comment]
these exist within chat settings now
