### ISSUE TITLE
Making me chat twice

### ISSUE THREAD

**Issue by dwj1389** [night/BetterTTV#944]
Hello, i noticed just in past hour actually, when i chat in a twitch channel, it's sending my messages twice, i tried a few things with my account thinking maybe i got hacked, but nothing changed until i tried disabling the bettertv extension, at that point it stopped.

**Comment by night** [comment]
Disable all other extensions and see if the issues persists. We cannot reproduce this issue.

**Comment by night** [comment]
It's most likely the "Hide my Adblocker" extension.
