### ISSUE TITLE
BTTV Feature Request (new type of spam filter)

### ISSUE THREAD

**Issue by Picklelol** [night/BetterTTV#946]
I would love the ability to filter the fuck boys who spam (almost) every popular streamers chat with
 4Head WORDS 4Head IN 4Head BETWEEN 4Head EMOTES 4Head IN 4Head 2016  4Head 
4Head WORDS 4Head IN 4Head BETWEEN 4Head EMOTES 4Head IN 4Head 2016  4Head 4Head WORDS 4Head IN 4Head BETWEEN 4Head EMOTES 4Head IN 4Head 2016  4Head 4Head WORDS 4Head IN 4Head BETWEEN 4Head EMOTES 4Head IN 4Head 2016  4Head 

or anything in between (usually whatever they want the chat/broadcaster to see)

even modded channels accept them now a days, minus the nazi channels like trump etc.

I would love to filter them, but still see what their message was,
like the message above would be "4Head WORDS IN BETWEEN EMOTES IN 2016 "
with just 1 emote, so it doesn't take 6 lines but i still read the message (because sometimes chat can be hilarious)
 
I don't know if this is possible, but i'd 100% use it if it was available.

**Comment by night** [comment]
If we ever expand to spam filtering, this would be included as part of #144
