### ISSUE TITLE
Double chat entries when chatting on Twitch

### ISSUE THREAD

**Issue by Euther** [night/BetterTTV#949]
Hi, long time users... (Twitch.tv/euther) and promoter... As of today, I seem to get double chat entires when chatting.  

2:06 Euther: dups
2:06 Euther: dups
2:06 Your message was not sent because you are sending messages too quickly.

I am using version:
2:03 Euther: @Pandoraheals, v6.8R44
2:03 Euther: @Pandoraheals, v6.8R44
2:03 Your message was not sent because you are sending messages too quickly.

If I disable BTTV from chrome settings > Extensions everything works fine.

Any recommendations?

thx
Euther

**Comment by MellowNebula** [comment]
Do you have an extension called "Hide my Adblocker" installed, perchance?  
#944 #945

**Comment by Euther** [comment]
Umm... Yep... and sorry to not see #944 #945 ... :(
disabled it... BTTV works fine now... thank  you very much for replying Mellow!!!
