### ISSUE TITLE
New feature idea

### ISSUE THREAD

**Issue by EvenDemonsKnow1** [night/BetterTTV#950]
Alright, I was thinking for a feature, you could view streamers' past broadcasts even if streamers don't have past broadcasts set to save, because at the time of writing this, I was part of a hilarious stream, but the past broadcast never saved, which really sucks because I wanted to watch it again later and relive the hilarity that happened. Anyway, hopefully you can get back to me <3

**Comment by night** [comment]
This isn't possible, sorry. Twitch doesn't store video when it isn't set to.
