### ISSUE TITLE
BTTV settings request: Resub

### ISSUE THREAD

**Issue by SenorCristos** [night/BetterTTV#951]
This may seem like an odd request but possibly hiding your resub notification.
Heres why: A streamer i sub to is having a Sub-athon soon and for every sub and resub the streamer will continue streaming for x amount of time. And my auto resub notification has appeared already and its tempting to push it but id like to save it until that day. 

thank you for your consideration

**Comment by night** [comment]
You can disable that already in your Twitch settings: https://secure.twitch.tv/settings/notifications

**Comment by SenorCristos** [comment]
thanks
