### ISSUE TITLE
Improving linkify regex

### ISSUE THREAD

**Issue by wallrik** [night/BetterTTV#953]
I would submit this as a pull request but I don't feel like I fully understand the regex :confused:
My issue is that links that end with slash right after the domain does not get included in the link.

Example:
`https://www.google.com/maps/` The entire link gets included
`https://www.google.com/` The last / does not get included in the link

So, [this is the current](https://github.com/night/BetterTTV/blob/master/src/chat/templates.js#L35) regex:
```javascript
var regex = /(?:https?:\/\/)?(?:[-a-zA-Z0-9@:%_\+~#=]+\.)+[a-z]{2,6}\b(?:(?:[-a-zA-Z0-9@:%_\+.~#?&\/=!,]+)(?:[-a-zA-Z0-9@:%_\+.~#?&\/=]))?/gi;
```
If I punch that into [regexr.com](http://regexr.com/) and change the last `+` to `*` it includes the slash in their example text, `http://foo.co.uk/`.

I'm just not sure if that would lead to any other complications.

I think [Twitch vanilla](https://web-cdn.ttvnw.net/emberchat.js) uses this regex:
```javascript
/(?:game:(?:[-a-zA-Z0-9@:%_\+.~#?&\/\/=]*))|(?:https?:\/\/)?(?:[-a-zA-Z0-9@:%_\+~#=]+\.)+[a-z]{2,6}\b(?:[-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/g
```

**Comment by night** [comment]
Why does the last forward-slash need to be linked? The link still works fine without it. AFAIK this is a limitation of the current regex to properly handle trailing symbols, but since it doesn't cause any problems and is just a visual defect, I do not see any problem with how it is currently.
