### ISSUE TITLE
Suggestion: Have a feature which automatically fixes emote capitalization.

### ISSUE THREAD

**Issue by markipoli** [night/BetterTTV#954]
For example, if you type " kappa KEepo eleGiggle " it changes it to " Kappa Keepo EleGiggle " The proper capitals that will show the emote. Better discord has this feature.

**Comment by night** [comment]
This isn't possible, sorry. There are many similar emotes that only have a couple or few letter differences, so even if we ran a fuzzy search on all emotes (which could be resource intensive and chew CPU usage) it might autocorrect emotes to unwanted emotes.

If you want to ensure you don't mistype emotes, you can tab complete them instead.. Press tab after typing a few letters of an emote, and press tab to keep searching matches to shift+tab to reverse in the search list.
