### ISSUE TITLE
Creative section improvement

### ISSUE THREAD

**Issue by SAULGOODE** [night/BetterTTV#955]
Since Twitch decided to automatically have a promoted channel running when you click on the Creative section to browse it, it has become slow and annoying. If possible I would like to be able to browse Creative channels without having some random guitar player automatically have their stream running while I browse.

**Comment by night** [comment]
I personally do not experience any slow downs on that page of the directory. If the player is causing you to lag, you can pause the player by hovering over the player and clicking pause.
