### ISSUE TITLE
Channel Background image

### ISSUE THREAD

**Issue by Nathsters** [night/BetterTTV#956]
Ok a while ago, like night's channel, I remember you used to be able to set a image as the background of your channel by putting "#BTTV#bg=URL" in the "Image Links To" field. Is that still true or has it been changed?

**Comment by voloshink** [comment]
I think that's still true but i'm pretty sure that the url needs to be hosted on our site

**Comment by Nathsters** [comment]
Is there a way just a nobody like me can do that?

**Comment by night** [comment]
That is an experimental functionality that will not be happening everywhere in its current fashion. If we integrated channel backgrounds it would be automatic rather than manually added into channel panels.
