### ISSUE TITLE
Twitchs new "emote only mode" doesn't have icon in top right, like the slow mode and sub mode

### ISSUE THREAD

**Issue by Oxmaster** [night/BetterTTV#957]
Just a minor thing.

**Comment by night** [comment]
Emote only mode no longer works.

**Comment by Oxmaster** [comment]
Emote only mode is again available  

http://streamernews.tv/2016/05/21/twitch-emote-only-chat-mode-is-back/

**Comment by night** [comment]
It isn't possible to make a state icon since Twitch doesn't have that setting in ROOMSTATE for us to use.

**Comment by night** [comment]
@teak Can you get the CSS for this made. Twitch added it to their roomstate

**Comment by teak** [comment]
So just an icon?

**Comment by night** [comment]
Position it and what not.. I'll add the js for it in a bit.
