### ISSUE TITLE
Instructions on wildcard usage?

### ISSUE THREAD

**Issue by ar664** [night/BetterTTV#960]
I've been trying to block messages that have 100 characters or greater by doing .{100, } , but I keep getting:
Blacklist Keywords are now set to: ., "100,"

I don't know if there is a special format I need to follow, but hopefully I'm just not getting it.

**Comment by night** [comment]
That is not have wildcards work, sorry. It is not possible to block messages with 100 characters or greater using BetterTTV at this time.
