### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by Martii** [night/BetterTTV#961]
FYI,
So your code is forked at https://github.com/Abu3zzh/BetterTTV which your [current license prohibits](https://github.com/night/BetterTTV/blob/190ef3d8fbbc683f80208bc734a89460633f0dbd/license.txt#L13-L14). You will need to figure this out with GH's policy *(or modify your license)* but it has also been forked off-site at OpenUserJS.org *(OUJS)*.

Since the GH fork here doesn't have an issue tracker we will continue to handle it within the next 24 hours for our site with our issue tracker... if no response has been received from that user, @Abu3zzh,  that account will be removed.

Thank you,
OUJS Admin

**Comment by night** [comment]
We don't mind people editing the script for personal use (including personal forks, since it's unavoidable on GitHub). We only care when the code is being openly distributed (such as a UserScript). If someone uploaded our script as a UserScript to your website, then that is indeed violation of our copyright since your site's purpose is distribution of UserScripts.

**Comment by Martii** [comment]
> We only care when the code is being openly distributed (such as a UserScript). If someone uploaded our script as a UserScript to your website, then that is indeed violation of our copyright since your site's purpose is distribution of UserScripts.

@night 
Thank you for the clarification... we'll add it to the removal queue... @Abu3zzh will still have the approximate period allotted *(we relate to other time zones :)* to remedy this account wise on an agreeable, amicable level *(e.g. that user should delete the script to continue to stay on our site)* with OUJS but it has been tagged... if no action is taken we will remove the account as well.

Thanks again,
OUJS Admin

Closing at this level with GH.
