### ISSUE TITLE
Font Feature

### ISSUE THREAD

**Issue by OsteoidGore36** [night/BetterTTV#971]
One of my favorite features of FrankerFaceZ (another twitch modifier that clashes with BTTV), allows you to change the font of the twitch chat to many different fonts such as Times New Roman, Calibri, and even some other ridiculous ones like WingDings. I would like this because Times New Roman is easier on the eyes for me and other people. 

Thanks for considering!
OsteoidGore36

**Comment by night** [comment]
Merging with #57
