### ISSUE TITLE
Host buttion not working even after removal & re-added extention

### ISSUE THREAD

**Issue by NateDog965** [night/BetterTTV#972]
Hi, i am a user of this chrome google extension. i have noticed recently that the host button is not functioning like it should. it has come up with this error message "BetterTTV: There was an error hosting the channel. You may need to host it from your channel." In the past when you pressed the button it would send the command to your twitch channel automatically, but this function has stopped working. i wanted to put this up so that who made this can see and maybe fix the issue.

**Comment by night** [comment]
We recently fixed this issue. Can you confirm if the problem is resolved?
