### ISSUE TITLE
Blue buttons and DarkenTTV options

### ISSUE THREAD

**Issue by PavloBilyak** [night/BetterTTV#977]
When this options are on, titles on profile page become black and hard-readable.
![2016-02-23 09_46_46-birdie0 - twitch](https://cloud.githubusercontent.com/assets/7945905/13244919/842c7330-da12-11e5-9368-f85ebd888661.png)

**Comment by night** [comment]
I'm not sure where that is. Can you elaborate?

**Comment by PavloBilyak** [comment]
http://www.twitch.tv/<username>/profile

**Comment by PavloBilyak** [comment]
I just notice if just reload page, text become white.

**Comment by night** [comment]
It seems to work for me, so I'm not sure..
