### ISSUE TITLE
bug with "mod icons" on chrome

### ISSUE THREAD

**Issue by Leifman27** [night/BetterTTV#978]
Basically with bttv on (it doesn't happen vanilla, with bttv disabled) i now have this bug : http://i.imgur.com/ydl9TB9.png
it started after i cleared my cache today and happens to me in every chat room i have a mod at, seems to be "chrome only" and i suppose adding the fact i am on windowsxp is important

**Comment by night** [comment]
Already fixed by 126072e3113a5c8d9023d8cfd153fb4711ba9c50

**Comment by Leifman27** [comment]
well u said "already fixed" but it happens to me now.. does that mean i have to wait for bttv to update or something? or is there something for me to do to fix right away/now?
