### ISSUE TITLE
the same issue that was with "fixes mod icons" is present with the 'unban' now

### ISSUE THREAD

**Issue by Leifman27** [night/BetterTTV#981]
i am reffering to the fixed issue here : https://github.com/night/BetterTTV/commit/126072e3113a5c8d9023d8cfd153fb4711ba9c50
i noticed now that upon banning someone, the "unban" option is bugged as the timeout/ban were prior to that fix yesterday
so i suppose same fix will work that fixed the timeout/ban for the "unban"

**Comment by night** [comment]
The issue was already fixed, and I just pushed out the updated since we were waiting on css fixes overnight.

**Comment by Leifman27** [comment]
thank you :) as amazingly fast as ever
