### ISSUE TITLE
[Suggestion] Gray out "Chat" button when blocked behind slowmode/ban/timeout

### ISSUE THREAD

**Issue by drfino** [night/BetterTTV#982]

**Comment by night** [comment]
The chat button swaps to a timer already when there is slow mode or you get timed out or banned.

**Comment by drfino** [comment]
Yes but making it gray would indicate that you cannot chat. The same as
changing it to a darker purple.

**Comment by night** [comment]
Grey would mean to imply that the button is disabled. Since we can never be sure what the status of your account is in chat, it's not possible to disable the button entirely.

For example, if you get unbanned after a ban, we have no indication that you got an unban. The same goes for timeouts.

**Comment by drfino** [comment]
Ah ok that makes sense. Thanks for explaining.
