### ISSUE TITLE
Chats messages do not appear anymore on Opera

### ISSUE THREAD

**Issue by Vrakfall** [night/BetterTTV#983]
Today I noticed that my settings were reset once again. I imported my settings as usual and then the chat never appeared anymore. I tried to uninstall/reinstall the extension but nothing worked.

I'm using Opera-beta and it happened on Windows and Linux aswell.

**Comment by night** [comment]
It might be a bug in Opera, which if that's the case there's not much we can do. What errors appear in the JavaScript console, if any?

**Comment by Vrakfall** [comment]
I think I won't be able to check before very late tonight. I'll try my best to check it asap.

(Side question: Why didn't you upload the extension on the Opera store, as you did for Chrome? The installation would be easier.)

**Comment by night** [comment]
Our extension was created far before there was an "Opera store" for Opera "Next" (or whatever they call it now), which is why it isn't on their site.

**Comment by Vrakfall** [comment]
Here's the error message I get:

```javascript
GET https://edge.quantserve.com/quant.js net::ERR_INSECURE_RESPONSE
JQMIGRATE: Logging is active
JQMIGRATE: jQuery.browser is deprecated
The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED
GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED
GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED
No cast extension found
TMI.js [irc] WARNING: Could not parse IRC message: CAP.
TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
TMI.js [irc] WARNING: Could not parse IRC message: 353.
TMI.js [irc] WARNING: Could not parse IRC message: 366.
POST https://client-event-reporter-darklaunch.twitch.tv/timer 404 (Not Found)
GET https://api.betterttv.net/2/channels/guardsmanbob 404 ()
WebSocket connection to 'wss://darklaunch.tmi.twitch.tv/' failed: Connection closed before receiving a handshake response
Mixed Content: The page at 'https://www.twitch.tv/guardsmanbob/chat?popout=' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://irc-ws.darklaunch.us-west2.twitch.tv/'. This request has been blocked; this endpoint must be available over WSS.
TMI.js [irc] WARNING: Could not parse IRC message: CAP.
TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
TMI.js [irc] WARNING: Could not parse IRC message: CAP.
TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
TMI.js [irc] WARNING: Could not parse IRC message: 353.
TMI.js [irc] WARNING: Could not parse IRC message: 366.
```

This one line is the one appearing at the time the chat seems to disappear:
```javascript
GET https://api.betterttv.net/2/channels/guardsmanbob 404 ()
```

And this is the page loaded with the extension disabled (not uninstalled).
```javascript
GET https://edge.quantserve.com/quant.js net::ERR_INSECURE_RESPONSE
JQMIGRATE: Logging is active
JQMIGRATE: jQuery.browser is deprecated
GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED
GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED
GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED
No cast extension found
The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
WebSocket connection to 'wss://pubsub-edge.twitch.tv/v1' failed: Error in connection establishment: net::ERR_SOCKET_NOT_CONNECTED
TMI.js [irc] WARNING: Could not parse IRC message: CAP.
TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
WebSocket connection to 'wss://pubsub-edge.twitch.tv/v1' failed: Connection closed before receiving a handshake response
TMI.js [irc] WARNING: Could not parse IRC message: 353.
TMI.js [irc] WARNING: Could not parse IRC message: 366.
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
WebSocket connection to 'wss://pubsub-edge.twitch.tv/v1' failed: Error in connection establishment: net::ERR_SOCKET_NOT_CONNECTED
WebSocket connection to 'wss://pubsub-edge.twitch.tv/v1' failed: Connection closed before receiving a handshake response
WebSocket connection to 'wss://pubsub-edge.twitch.tv/v1' failed: Error in connection establishment: net::ERR_SOCKET_NOT_CONNECTED
TMI.js [irc] WARNING: Could not parse IRC message: CAP.
TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
TMI.js [irc] WARNING: Could not parse IRC message: 353.
TMI.js [irc] WARNING: Could not parse IRC message: 366.
```

Note that the only thing I did that generated that issue was to import my settings after an update reset them.

Uninstalling the extension and reinstalling it does change nothing.

It did it on both my computers (one on Windows 7, the other one on Linux Mint) with Opera Next (the beta version). Didn't try on the normal one but I guess it'll do the same.

**Comment by night** [comment]
There are no errors relating to BetterTTV that you posted. If I had to guess, BetterTTV is functioning but the settings may have been reset. You can check if "BetterTTV Settings" is in your chat settings.

**Comment by Vrakfall** [comment]
The settings are visible but whatever I change in them does nothing.

Note that it started hiding the chat after I imported my old settings, not after the update.

Is there any folder that keeps the old settings even if I uninstall the extension? I could probably just remove it and reinstall.

And if so, why does bttv settings reset every once in a while?

**Comment by Vrakfall** [comment]
After further researchs, I think the chat disappears because BTTV fails to load the history of the chat before the connection. Here's a more detailed stack trace of the message appearing in the console at the exact moment the chat disappears (I didn't see I could expand it, in my previous message):

```javascript
GET https://api.betterttv.net/2/channels/guardsmanbob 404 ()    @ global-c295ea7….js:16
send    @ global-c295ea7….js:16
p.extend.ajax    @ global-c295ea7….js:16
p.(anonymous function)    @ global-c295ea7….js:16
p.extend.getJSON    @ global-c295ea7….js:16
n.exports    @ betterttv.js?0.12543235106166395:44
E    @ betterttv.js?0.12543235106166395:44
c    @ betterttv.js?0.12543235106166395:44
```

**Comment by Vrakfall** [comment]
Also, when I check `https://api.betterttv.net/2/channels/guardsmanbob`, I get the following answer:

```javascript
{"status":404,"message":"Channel not found"}
```

but when I check it with a popular channel like `https://api.betterttv.net/2/channels/esl_csgo`, I get:

```javascript
{"status":200,"urlTemplate":"//cdn.betterttv.net/emote/{{id}}/{{image}}","bots":[],"emotes":[{"id":"55999813f0db38ef6c7c663e","channel":"thefreaking2","code":"gachiGASM","imageType":"png"},{"id":"554da1a289d53f2d12781907","channel":"NightDev","code":"(ditto)","imageType":"gif"},{"id":"55a1848cbcf695554143613c","channel":"FATPALA","code":"NoGodNo","imageType":"gif"}]}
```

**Comment by Vrakfall** [comment]
Wow, I just checked the highlights that were set. These are very old ones I don't use anymore. It means it went get them back from a very old settings file. Where do/did you store settings? Maybe that just an uninstallation + erasure of the files will solve my problem.

**Comment by night** [comment]
You can clear your cookies and cache to reset the settings. What might be happening is Twitch could be serving your pages over both SSL and non-SSL (they are running a limited test currently). If that's the case then your settings don't carry between those two pages. When/if Twitch moves everyone to SSL that issue will be fixed.

**Comment by Vrakfall** [comment]
Just a message to say it worked. It was me being impolite here, not answering. I apologize.
