### ISSUE TITLE
Name Colors and Highlights

### ISSUE THREAD

**Issue by Vendy13** [night/BetterTTV#984]
Hello!

I've just installed BTTV and noticed a few changes that I couldn't change without reverting back, so I thought it might be a good idea to have the option to customize them.

The first is the username colors are a lot more watered down with BTTV. I personally enjoyed the brighter colors better.

The second is the red highlighted messages. It seems a bit excessive to me, but I like the customizable words. I like the idea of just having those words highlighted rather than the entire message, and to have them highlighted a different color as well.

Thanks for all your work and loving the extension so far!

**Comment by night** [comment]
Username colors are darkened on light mode and lightened on dark mode. This is to prevent people from choosing colors you cannot read, like white on white or black on black (etc.). This is non-toggleable.

BetterTTV has done highlighting for years, while Twitch only recently added their own. Unfortunately people do not like change, so we haven't chosen to change our way of highlighting nor do we see an immediate reason to when you're the first to complain (out of millions of users).

**Comment by Vendy13** [comment]
I'm not sure if your reply was intended to sound as harsh as it came off, so I'll assume it wasn't meant to be. My post wasn't meant to sound like complaints but rather suggestions (as it was the "Suggest a Feature" link that brought me here in the first place).

I was simply suggesting the options be there, nothing more. Such as the option to change the highlight color. I hope that clears things up! :)

**Comment by Vendy13** [comment]
Also, apparently FrankerFaceZ has everything I mentioned PLUS some other things BTTV is missing. So, take what you will from that, but I'll just say it may be a smart move to consider having some things that your competition already has.
