### ISSUE TITLE
Host button will not show

### ISSUE THREAD

**Issue by kompalol** [night/BetterTTV#986]
The title says it pretty much. Host button doesnt show even though its "on" in the settings

**Comment by night** [comment]
I cannot reproduce this. Host buttons only appear on channel pages below the video player.

**Comment by kompalol** [comment]
Well, it doesnt show. 

Date: Fri, 26 Feb 2016 09:53:31 -0800

**Comment by night** [comment]
If it doesn't show then you do not have the "Host Button" setting in BetterTTV enabled.

**Comment by kompalol** [comment]
Yes, I do. And it still doesnt show. I'm not retarded mate.

Date: Sat, 27 Feb 2016 12:04:12 -0800
