### ISSUE TITLE
Temporary spam blacklist

### ISSUE THREAD

**Issue by rbhalla** [night/BetterTTV#990]
It would be great if you get click a message and temporarily blacklist (maybe just for web session duration or just till you move channel) so that things that suddenly start getting spammed don't start dominating the chat.

**Comment by night** [comment]
Would be implemented by #68 if it's ever implemented.

**Comment by rbhalla** [comment]
I'm not sure it's a duplicate of that issue. That issue is about highlighting keywords on a per channel basis, this issue is about temporary blacklisting certain messages for a single page load.

**Comment by night** [comment]
It is a duplicate since highlights and blacklists are in the same sub-system. This would be an extension of that issue, which is why this issue is now referenced in that issue..
