### ISSUE TITLE
Theatre mode without loss of stats

### ISSUE THREAD

**Issue by Quitch** [night/BetterTTV#991]
Love the extra room theatre mode gives the video, but at the same time I want to keep the follower count visible to get an idea of how many people are with me (feels more social).

**Comment by night** [comment]
Theater mode is designed to minimize the UI such as to remove all these stats. If you want stats available, then you can simply minimize the left sidebar instead of using theater mode.

**Comment by Quitch** [comment]
The problem is that minimising the sidebar doesn't:

a) remove the sidebar
b) remove the padding

So you're left with two choices:

1. a mode with stats AND a smaller video player
2. a larger video player BUT no stats

I'm not sure why the size of the video player should be linked to the display of an element which doesn't affect the size of said player.
