### ISSUE TITLE
AudioTwitch integration

### ISSUE THREAD

**Issue by Glaived** [night/BetterTTV#996]
An option to add a redirecting button to the service @AudioTwitch ?
e.g. : http://audiotwitch.tv/YOUR_CHANNEL_NAME_HERE

![ccpj-plxiaad3lp jpg large](https://cloud.githubusercontent.com/assets/1835170/13509856/06621120-e18e-11e5-8004-4a40df63d47c.jpg)

**Comment by night** [comment]
this has been broken for a while
