### ISSUE TITLE
Move chat

### ISSUE THREAD

**Issue by AdamWestPhD** [night/BetterTTV#999]
Hi,

I really love your add on Better TTV, but I feel that a very nice feature that is missing is the ability to move chat to the left (basically reverse the menu on the left with the chat on the right). I know that myself and a number of other people run twitch on monitor two while gaming or working on a project. Being able to switch the chat to the left would be a fantastic accessibility feature/quality of life improvement.

Cheers,

Ethan

**Comment by voloshink** [comment]
dupe of #202
